Encrypt JSON blobs
sourcegraph/sourcegraph pull request #13080
Opened 2020-08-17 23:11 UTC by daxmc99

Certain columns should be encrypted in the database. This adds encryption to those fields where the data is accessed.

Fixes https://github.com/sourcegraph/sourcegraph/issues/12263

2020-08-26 07:09 UTC, daxmc99 commented on cmd/repo-updater/repos/store.go
> +				//TODO (Dax): Determine if base64 is the best approach here
I'm not sure if this approach makes sense here. It might make more sense to change the type to bytes in the struct above and use a `bytea` type in Postgres to store it.

2020-08-26 08:20 UTC, ryanslade requested changes
LGTM. One thing I'm unsure of is that we're encrypting data in `internal/db/external_accounts.go` which is used in frontend, but we're not calling `secrets.Init` in frontend AFAICT.

2020-08-26 08:20 UTC, ryanslade commented on cmd/repo-updater/repos/store.go
> +				encryptedSource, err := intSecrets.EncryptBytes([]byte(info.CloneURL))
I think this should be named `encryptedURL`

2020-08-26 08:20 UTC, ryanslade commented on cmd/repo-updater/repos/store.go
> +				//TODO (Dax): Determine if base64 is the best approach here
I agree. My only concern is that we have recently added a few migrations to the repos table and I worry adding another one during this release could cause customer upgrades to take a long time.

2020-08-26 08:33 UTC, asdine requested changes
Because the `repo` table no longer contains the `sources` column, we need to change the way we want to encrypt the sources map. I have proposed another approach in comments

2020-08-26 08:33 UTC, asdine commented on cmd/repo-updater/repos/store.go
> +	sources, err = intSecrets.EncryptBytes(sources)
The sources byte slice represents is a json that will not be stored as is but will be used as an input for a postgresql query (like this one for example: https://github.com/sourcegraph/sourcegraph/blob/5edf20cd5630a949b5517586a2bd5a7c8c679da2/cmd/repo-updater/repos/store.go#L454-L551)

What we want to encrypt is not the sources json payload but rather the clone URL that's in it

2020-08-26 08:33 UTC, asdine commented on cmd/repo-updater/repos/store.go
> +
```suggestion
```

2020-08-26 08:33 UTC, asdine commented on cmd/repo-updater/repos/store.go
> +		decryptedSrc, err := intSecrets.DecryptBytes(sources.Raw)
Same here, Sources is no longer a column of the repo table so it doesn't make sense to encrypt it entirely anymore. What we want is to encrypt individual sensible source information

2020-08-26 15:09 UTC, daxmc99 commented on cmd/repo-updater/repos/store.go
> +	sources, err = intSecrets.EncryptBytes(sources)
Would it be ok to encrypt the entire sources blob? Have certain fields in the column that are encrypted instead of the whole column makes this a bit tricky

2020-08-27 02:22 UTC, unknwon commented
> LGTM. One thing I'm unsure of is that we're encrypting data in `internal/db/external_accounts.go` which is used in frontend, but we're not calling `secrets.Init` in frontend AFAICT.

We're calling it here: https://github.com/sourcegraph/sourcegraph/blob/9d438978c27fe25c63a2e78f209c156021c580b2/cmd/frontend/internal/cli/serve_cmd.go#L209

2020-08-27 06:04 UTC, asdine commented on cmd/repo-updater/repos/store.go
> +	sources, err = intSecrets.EncryptBytes(sources)
The `sources` column no longer exists actually, the `repo.Sources` map is turned into json only to be used as an input for a subquery, not to be stored inside a column.
That subquery will read the json and insert each field in its own dedicated column in the `external_service_repos table`.
If we take a look at the `external_service_repos` [schema](https://github.com/sourcegraph/sourcegraph/blob/main/internal/db/schema.md#table-publicexternal_service_repos), we can see where the content of the `repo.Sources` map will be stored.
I think all we need to encode is the `CloneURL` field of that map

2020-08-27 07:49 UTC, daxmc99 commented on internal/db/external_accounts.go
> +		return -1, err
I have to return an `int`. The err stops the caller from continuing but I wanted to choose a value that would never be a userID.

2020-08-28 08:10 UTC, ryanslade commented on internal/db/external_accounts.go
> +		return -1, err
I think returning 0 is fine then as they start at 1.

2020-08-29 07:18 UTC, unknwon approved these changes
Looking good! Excited to see this rolling out 😎

2020-08-29 07:18 UTC, unknwon commented on cmd/frontend/internal/usagestats/main_test.go
> +	"github.com/sourcegraph/sourcegraph/internal/db/dbtesting"
nit:
```suggestion
	"github.com/inconshreveable/log15"
	
	"github.com/sourcegraph/sourcegraph/internal/db/dbtesting"
```

2020-08-29 07:18 UTC, unknwon commented on cmd/repo-updater/repos/main_test.go
>  	"github.com/inconshreveable/log15"
nit:
```suggestion
	"github.com/inconshreveable/log15"

	secretsPkg "github.com/sourcegraph/sourcegraph/internal/secrets"
```

2020-08-29 07:18 UTC, unknwon commented on cmd/repo-updater/repoupdater/main_test.go
> +	"github.com/inconshreveable/log15"
nit:
```suggestion
	"github.com/inconshreveable/log15"

```

2020-08-29 07:18 UTC, unknwon commented on enterprise/cmd/repo-updater/authz/main_test.go
>  	"github.com/inconshreveable/log15"
nit:
```suggestion
	"github.com/inconshreveable/log15"

	secretsPkg "github.com/sourcegraph/sourcegraph/internal/secrets"
```

2020-08-29 07:18 UTC, unknwon commented on enterprise/internal/campaigns/main_test.go
>  	"github.com/inconshreveable/log15"
nit:
```suggestion
	"github.com/inconshreveable/log15"

	secretsPkg "github.com/sourcegraph/sourcegraph/internal/secrets"
```

2020-08-29 07:18 UTC, unknwon commented on enterprise/internal/campaigns/main_test.go
> +
```suggestion
```

2020-08-29 07:18 UTC, unknwon commented on internal/db/event_logs.go
> +	intSecrets "github.com/sourcegraph/sourcegraph/internal/secrets"
To be consistent with other places, we should name it like this?
```suggestion
	secretsPkg "github.com/sourcegraph/sourcegraph/internal/secrets"
```

2020-08-29 07:18 UTC, unknwon commented on internal/db/external_accounts.go
> +	intSecrets "github.com/sourcegraph/sourcegraph/internal/secrets"
```suggestion
	secretsPkg "github.com/sourcegraph/sourcegraph/internal/secrets"
```

2020-08-31 07:56 UTC, mrnugget approved these changes
Approving the two files in `campaigns` folder.

2020-09-16 05:28 UTC, daxmc99 commented
This PR is being closed for https://github.com/sourcegraph/sourcegraph/pull/13759

2020-09-16 05:28 UTC, closed without merging