repo-updater: add metrics for user-added external services
sourcegraph/sourcegraph pull request #13589
Opened 2020-09-02 07:55 UTC by unknwon

Adds three Prometheus metrics:
- Track number of code host connections added by users
- Track total number of repositories added by users
- Average repos per user can be derived from the above

Part of #12699

2020-09-02 09:08 UTC, ryanslade commented on cmd/repo-updater/repos/metrics.go
> +	promauto.NewGaugeFunc(prometheus.GaugeOpts{
I think we could derive this in prometheus. 

We can add another metric instead that measures the number of users who have added at least one external service, `x`

We could then derive the average in prometheus: `src_repoupdater_user_repos_total / x`

2020-09-02 09:09 UTC, ryanslade requested changes
Approach looks good, but see my comment about deriving the average in Prometheus

2020-09-02 09:10 UTC, keegancsmith commented on cmd/repo-updater/repos/metrics.go
> +`)
You don't need this metric. Rather log the total number of distinct users in prometheus. Then in prometheus you can divide `src_repoupdater_user_repos_total` by the number of distinct users. Number of distinct users is also in general a useful metric to track.

2020-09-02 09:25 UTC, ryanslade commented on cmd/repo-updater/repos/metrics.go
> +`)
I wonder what is more useful:

* total repos added by user / distinct users
* total repos added by user / distinct users who have added an external service

My guess is that most users won't bother to add an external service but it would be useful to know how many repos a user that uses the feature adds.

2020-09-03 03:28 UTC, unknwon commented on cmd/repo-updater/repos/metrics.go
> +	promauto.NewGaugeFunc(prometheus.GaugeOpts{
>We can add another metric instead that measures the number of users who have added at least one external service, x

We could then derive the average in prometheus: src_repoupdater_user_repos_total / x

That is smart!!

2020-09-03 03:34 UTC, unknwon commented on cmd/repo-updater/repos/metrics.go
> +	promauto.NewGaugeFunc(prometheus.GaugeOpts{
Addressed in https://github.com/sourcegraph/sourcegraph/pull/13589/commits/06f2a6d0d4e13313102d16e037aceb61ff4de553, PTAL!

2020-09-03 03:35 UTC, unknwon commented on cmd/repo-updater/repos/metrics.go
> +`)
I agree that "total number of users" is a generally useful metric, but I think "total repos added by user / distinct users who have added an external service" is more useful here.

2020-09-03 07:01 UTC, asdine approved these changes

2020-09-03 08:07 UTC, ryanslade commented on cmd/repo-updater/repos/metrics.go
> +`)
The new query returns a list of user ids, shouldn't it return a count?

2020-09-04 03:34 UTC, unknwon commented on cmd/repo-updater/repos/metrics.go
> +`)
> The new query returns a list of user ids, shouldn't it return a count?

@ryanslade: 🤦 Good catch! I don't know what I was doing.

2020-09-04 03:42 UTC, unknwon commented on cmd/repo-updater/repos/metrics.go
> +`)
Fixed in https://github.com/sourcegraph/sourcegraph/pull/13589/commits/7591f33334e8be0d2570fef695eadd34ea67e7bc

2020-09-04 09:31 UTC, unknwon commented
Merging as-is, happy to address any post-merge comments!

2020-09-04 09:32 UTC, merged