Enterprise home: add saved searches panel
sourcegraph/sourcegraph pull request #13669
Opened 2020-09-07 09:57 UTC by attfarhan

2020-09-08 18:22 UTC, limitedmage requested changes
Overall this looks great! I'll work on following the patterns from how data is loaded here in my PR. Eventually I think we need to go back and rethink data so that a single GraphQL query loads all the data the homepage needs though.

2020-09-08 18:22 UTC, limitedmage commented on web/src/search/panels/SavedSearchesPanel.tsx
> +export const SavedSearchesPanel: React.FunctionComponent<{
Can we add a storybook test for this component in all three states (empty, loading, populated)?

2020-09-08 18:22 UTC, limitedmage commented on web/src/search/panels/EnterpriseHomePanels.story.tsx
> +    fetchSavedSearches: sinon.spy(),
Can we add some mock data so that the storybook is generated with content?

2020-09-08 18:22 UTC, limitedmage commented on web/src/search/panels/SavedSearchesPanel.tsx
> +export const SavedSearchesPanel: React.FunctionComponent<{
Also, maybe add some unit tests for the tabbing filters working correctly.

2020-09-08 18:42 UTC, rrhyne commented on web/src/search/panels/SavedSearchesPanel.tsx
> +            <LoadingSpinner />
The text is corrected in the design. It should read 'Loading saved searches'.

2020-09-08 18:43 UTC, rrhyne commented on web/src/search/panels/SavedSearchesPanel.tsx
> +                    <PlusIcon className="icon-inline" />
My fault, should be the plus sign.

2020-09-09 06:04 UTC, attfarhan commented on web/src/search/panels/SavedSearchesPanel.tsx
> +                                        to={'/search?' + buildSearchURLQuery(search.query, patternType, false)}
The presence of `patternType:` in the raw query takes precedence over the `patternType` variable passed through to `buildSearchURLQuery`. Therefore, it will always take you to the correct URL. This is weird to read, though, so will see what we can do to improve this.

2020-09-09 07:08 UTC, attfarhan commented on web/src/search/panels/SavedSearchesPanel.tsx
> +                                                to={`/organizations/${search.namespace.namespaceName}/searches/${search.id}`}
Fixed, forgot to add fetch the typename in the gql query.

2020-09-09 14:36 UTC, limitedmage approved these changes

2020-09-09 14:36 UTC, limitedmage commented on web/src/search/panels/SavedSearchesPanel.tsx
> +    displayState?: 'loading' | 'empty' | 'populated'
We can test this without having this prop, by using the `fetchSavedSearches` prop instead. For loading, you can use [`NEVER`](https://rxjs.dev/api/index/const/NEVER) and for empty you can return an empty array.

2020-09-09 14:36 UTC, limitedmage commented on web/src/search/panels/SavedSearchesPanel.test.tsx
> +describe('SearchPage', () => {
```suggestion
describe('SavedSearchesPanel', () => {
```

2020-09-09 14:36 UTC, limitedmage commented on web/src/search/panels/SavedSearchesPanel.tsx
> +    displayState?: 'loading' | 'empty' | 'populated'
**suggestion**: Instead of using this, I recommend using `fetchSavedSearches` instead. For empty state, use `of()` with an empty result. For loading state, use [`NEVER`](https://rxjs.dev/api/index/const/NEVER)

2020-09-09 14:36 UTC, limitedmage commented on web/src/search/panels/SavedSearchesPanel.test.tsx
> +    it('should show all one search on "my searches tab"', () => {
**suggestion:** Add a test that checks that the mode has changed when the right button has been clicked. If you do this, I think this test, and the `mySearchesMode` prop, might not be needed.

2020-09-09 14:36 UTC, limitedmage commented on web/src/search/panels/SavedSearchesPanel.test.tsx
> +    it('should show all one search on "my searches tab"', () => {
```suggestion
    it('should show one search on "my searches tab"', () => {
```

2020-09-10 08:35 UTC, merged