searcher: support .sourcegraph/ignore
sourcegraph/sourcegraph pull request #13690
Opened 2020-09-08 09:25 UTC by stefanhengl

Relates to #6870

With this PR, searcher respects the contents of `.sourcegraph/ignore`. See https://github.com/sourcegraph/zoekt/pull/56 for more details.

2020-09-08 12:30 UTC, keegancsmith approved these changes
Is there a way we can exclude the file from being stored on disk? Then the bits that iterate over the file are agnostic to the fact the file doesn't exist? We also then get to skip storing those bits. I am guessing the answer is no since we stream in the archive, if so then no biggie.

LGTM

2020-09-08 12:33 UTC, keegancsmith commented
oh maybe there is a way we can store the ignore file once per archive? I realised that iterating twice over the list of files is not ideal every request. We can maybe store the computed ignore matcher. Anything seem reasonable with regard to that?

2020-09-08 13:09 UTC, stefanhengl commented
We have a [cache](https://sourcegraph.com/-/editor?remote_url=ssh%3A%2F%2Fgit%40github.com%2Fsourcegraph%2Fsourcegraph.git&branch=main&file=cmd%2Fsearcher%2Fsearch%2Fsearch.go&editor=JetBrains&version=v1.2.0&utm_product_name=GoLand&utm_product_version=2020.2.2&start_row=211&start_col=0&end_row=211&end_col=0) for the archives which we could maybe use to cache the ignore file, too. I will check.

2020-09-08 19:37 UTC, stefanhengl commented
> Is there a way we can exclude the file from being stored on disk? 

I extended 'fetch' such that it doesn't write ignored files to disk. It is a bit more complex than the first approach, but it leverages the cache which is great.

2020-09-09 10:45 UTC, keegancsmith requested changes

2020-09-09 10:45 UTC, keegancsmith commented on internal/store/store.go
> +		var buf bytes.Buffer
isn't this implying we copy the file into memory? Archives can quite easily be many GB. I don't think we can do that.

Maybe a better approach is to post process the zip file we store?

2020-09-10 06:49 UTC, stefanhengl commented
I added a new field `FilterTar` to the `store` which lets us define a filter function over tar-headers. The default filter function is a function that filters nothing, which makes this change transparent to any code not setting `FilterTar`.

Searcher sets the `ignore.Matcher` as its filter function. 

The retrieval of the ignore-file from gitserver is potentially brittle because we have to rely on the error message. Maybe it is a good idea to add a test to gitserver that makes sure that the error message stays the same?

2020-09-10 10:29 UTC, keegancsmith commented on cmd/searcher/search/filter.go
> +		if strings.Contains(err.Error(), "file does not exist") {
this is how we do it in other places. I think we may also need to handle other errors conditions here, I am not sure. See what we handle in `DefaultClient.Archive`, `FetchTar` and our interactions with the store in searcher. For example:

1. Empty repository can sometimes return a different error (has no branches)
2. A repository that is still cloning
3. An invalid repo@commit

These are likely handled in the other code path. Just want to ensure we don't regress on those since I assume FilterTar is called before FetchTar so may return different errors now.

2020-09-10 10:31 UTC, keegancsmith commented on cmd/searcher/search/search_test.go
> +		"ignore.me":  `func hello() string {return "world"}`,
how are the tests in this pkg vs graphqlbackend? :P

2020-09-10 10:32 UTC, keegancsmith commented on internal/store/store.go
> +type FilterFunc func(hdr *tar.Header) bool
nit: can you document this. eg what does returning true here do

2020-09-10 10:33 UTC, keegancsmith commented on internal/store/store.go
> +		}()
if I am not mistaken you don't need to make these changes here anymore. You should just be able to add in the extra filtertar logic.

2020-09-11 10:19 UTC, stefanhengl commented on cmd/searcher/search/filter.go
> +		if strings.Contains(err.Error(), "file does not exist") {
I think it should be fine.
FilterTar is called after FetchTar. While FetchTar calls [Archive](https://sourcegraph.com/-/editor?remote_url=ssh%3A%2F%2Fgit%40github.com%2Fsourcegraph%2Fsourcegraph.git&branch=sh%2Fsearcher-support-ignore&file=internal%2Fgitserver%2Fclient.go&editor=JetBrains&version=v1.2.0&utm_product_name=GoLand&utm_product_version=2020.2.2&start_row=166&start_col=21&end_row=166&end_col=21), FilterTar calls [SendExec](https://sourcegraph.com/-/editor?remote_url=ssh%3A%2F%2Fgit%40github.com%2Fsourcegraph%2Fsourcegraph.git&branch=sh%2Fsearcher-support-ignore&file=internal%2Fgitserver%2Fclient.go&editor=JetBrains&version=v1.2.0&utm_product_name=GoLand&utm_product_version=2020.2.2&start_row=224&start_col=14&end_row=224&end_col=22), both of which handle errors like "repo does not exist" or "still cloning" by converting a 404 to an error and returning it to the caller.
I have moved FilterTar out of the goroutine up just below FetchTar. For any error other than "file does not exist", FilterTar will return the error to the caller, just like FetchTar.

2020-09-11 10:31 UTC, stefanhengl commented on cmd/searcher/search/search_test.go
> +		"ignore.me":  `func hello() string {return "world"}`,
I think it makes sense to test this in isolation just for searcher. The question is, should we test this in graphqlbackend, too 🤔?  I am not 100% sure how we mock zoekt right now ... I will check.

2020-09-11 10:32 UTC, stefanhengl commented on internal/store/store.go
> +		}()
I moved the Filter out of the goroutine and restored the original logic.

2020-09-11 11:27 UTC, keegancsmith commented on cmd/searcher/search/search_test.go
> +		"ignore.me":  `func hello() string {return "world"}`,
I was asking a question along the lines of how was it writing tests for this package vs the time you have spent in graphqlbackend? IE is it nicer to do it here? :)

2020-09-11 11:30 UTC, keegancsmith approved these changes

2020-09-11 11:30 UTC, keegancsmith commented on internal/store/store.go
> +			return nil, err
minor: maybe just wrap this error saying it happened while calling FilterTar. Just in case the error returned is super obtuse (like os.IsNotExist)

2020-09-11 11:35 UTC, stefanhengl commented on cmd/searcher/search/search_test.go
> +		"ignore.me":  `func hello() string {return "world"}`,
😄 The GraphQL resolvers make things harder to test than they have to be. I would really like to move a lot of code out of graphqlbackend just for that reason.

2020-09-11 11:58 UTC, merged