Begin work on create page
sourcegraph/sourcegraph pull request #13725
Opened 2020-09-09 17:37 UTC by eseliger

2020-09-11 15:21 UTC, rrhyne approved these changes

2020-09-14 13:13 UTC, mrnugget approved these changes
Approved but unsure how this relates to the other create-campaign-page PR.

2020-09-14 16:30 UTC, mrnugget approved these changes

2020-09-14 16:30 UTC, mrnugget commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +                    Download Sourcegraph's cli tool, src-cli at{' '}
```suggestion
                    Download Sourcegraph's CLI tool, src-cli at{' '}
```

2020-09-14 16:30 UTC, mrnugget commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +                <p className="lead">Use Sourcegraph src-cli to preview your campaign:</p>
```suggestion
                <p className="lead">Use <code>src</code> to preview your campaign:</p>
```

2020-09-14 19:09 UTC, davejrt commented
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

2020-09-14 22:57 UTC, sqs requested changes

2020-09-14 22:57 UTC, sqs commented on web/src/globals.d.ts
>  }
Need to standardize on one or the other not both (.yml vs .yaml)

Also the file names should all end in .campaign.yaml because that’s the convention we’ve established in the docs.

2020-09-14 22:57 UTC, sqs commented on web/src/enterprise/campaigns/create/CreateCampaignPage.scss
> +        background-color: $gray-18;
Why is this background necessary? We very strongly want to avoid custom theme CSS because it’ll make it harder to add more color themes in the future. Can you just omit this or use CSS vars?

2020-09-14 22:57 UTC, sqs commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +        selectedSample,
I don’t think the download button is good. I added this comment on my PR in my commit message (on my phone now can’t pull it up easily). It adds noise and people will prefer to copy-paste anyway.

2020-09-14 22:57 UTC, sqs commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +                            <FileDownloadIcon className="icon-inline" /> Download yaml
YAML should be capitalized here because it’s an acronym (but I think this download button should be removed anyway as mentioned above)

2020-09-14 22:57 UTC, sqs commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +                <p className="lead">Use Sourcegraph src-cli to preview your campaign:</p>
I prefer the way of referring to the CLI in my PR. Are you planning to separately merge in my copy changes?

2020-09-14 22:57 UTC, sqs commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +    { name: 'Empty', file: emptySample },
I like having the file name shown and not some prose name. It establishes more clearly that these are files you need to save and edit.

2020-09-14 23:41 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +        selectedSample,
How about replacing it with a copy to clipboard button?

2020-09-14 23:42 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +    { name: 'Empty', file: emptySample },
I think the problem here is that it obscures the content of the examples: for instance, changing `Modify code using comby` to `comby.campaign.yaml` doesn't feel like it's as obvious, and expanding the whole action like `modify-code-using-comby.campaign.yaml` is going to cause the tab bar to be more than one line on most (all?) screen widths. (Plus, it's harder to read.)

@rrhyne, do you have any thoughts on ways we could have our file name cake and eat it too?

2020-09-14 23:43 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +                <p className="lead">Use Sourcegraph src-cli to preview your campaign:</p>
Yes, I'm about to steal all of your copy. :smile:

2020-09-14 23:44 UTC, LawnGnome commented on web/src/globals.d.ts
>  }
I'm going to boldly pick `.campaign.yaml` because (a) it aligns with the docs, and (b) it aligns with my personal biases towards expressive extensions. (I'll date myself, but I _hated_ `.htm` in the 8.3 days.)

2020-09-15 00:02 UTC, sqs commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +    { name: 'Empty', file: emptySample },
That’s a fundamental problem with filenames. What would it actually be named if it were a real file for a real campaign? We should pick that.

2020-09-15 00:04 UTC, sqs commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +        selectedSample,
Our audience doesn’t need that for this case. Also many of them wouldn’t trust it. A code block is how code is displayed in browsers, and anything else is just us trying to be helpful but actually just adding noise.

2020-09-15 01:25 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +        selectedSample,
Removed.

2020-09-15 01:27 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +    { name: 'Empty', file: emptySample },
I went with `hello-world.campaign.yaml`, `modify-with-comby.campaign.yaml`, and `update-go-imports.campaign.yaml` for now. The second one is definitely a bit of a stretch in terms of real world naming, but at least they all fit on a 1400 pixel wide browser.

2020-09-15 01:27 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +                    Download Sourcegraph's cli tool, src-cli at{' '}
This is moot now, since I adopted the wording from #13777.

2020-09-15 01:27 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.tsx
> +                            <FileDownloadIcon className="icon-inline" /> Download yaml
Moot, since the button is now gone.

2020-09-15 01:34 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.scss
> +        background-color: $gray-18;
I'm not sure the best way forward on this, as a web dilettante. [We have `$code-bg`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/web/src/SourcegraphWebApp.scss#L128:2), but it's [currently only used on Markdown panes](https://sourcegraph.com/search?q=code-bg+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+&patternType=literal) and isn't visually distinct, since it's just defined as `var(--body-bg)`.

I've changed this to `$code-bg` for now, and I think that's enough for us to merge this (screenshot coming momentarily), but I would like @rrhyne to weigh in on this. It's easy enough for us to change post cut if necessary.

2020-09-15 01:36 UTC, LawnGnome commented on web/src/enterprise/campaigns/create/CreateCampaignPage.scss
> +        background-color: $gray-18;
Actually, now I catch up on Slack chatter, I see [he may have beaten me to it](https://www.figma.com/file/HWLuLefEdev5KYtoEGHjFj/%F0%9F%93%9AWeb-%2F-Global-styles?node-id=0%3A1). If that is accepted, I can align this to that proposal.

2020-09-15 01:59 UTC, LawnGnome commented
OK, [here's how this looks right now in Storybook form](https://5f0f381c0e50750022dc6bf7-tpbqzjjcsx.chromatic.com/?path=/story/web-campaigns-createcampaignpage--page). For those who prefer screenshots (yes, my username is `eseliger` because _reasons_):

![image](https://user-images.githubusercontent.com/229984/93156160-67900e00-f6bc-11ea-8551-fa3f60dab731.png)

I think this is ready to be approved and merged. We'll probably change the code snippet styling more, but let's get this in so it makes the branch cut and then we can tinker with that later if need be. @mrnugget, could you review and merge if it's acceptable during your Tuesday, please?

2020-09-15 02:36 UTC, rrhyne commented on web/src/enterprise/campaigns/create/CreateCampaignPage.scss
> +        background-color: $gray-18;
Sorry all, I had a review I didn't realize was not commented that added commentary to this, but its all out of date now. The background sets the block off as a code sample vs. the body text. You can see in the screenshot it's hard very hard to differentiate... this is why @sqs added a border around the element in his design. 

I specified this as a color from our color system, but as Sqs noted, it should be a component. @LawnGnome with Felix and Erik out that won't get approved for a week. 

Let's deal with it after branch cut.

2020-09-15 02:40 UTC, rrhyne commented
@LawnGnome, One thing I think we should add, is an h4 above the tabs that reads 'Examples:'. Visually it is probably not going to be ideal,  but that was an element if @sqs's design that clearly denoted what the contents of the tabs contain.

2020-09-15 02:43 UTC, LawnGnome commented
@rrhyne Sure thing; done.

2020-09-15 03:08 UTC, sqs commented
I pushed some commits that make small tweaks that (IMO) improve it. What do you think?

Now it looks like:

![image](https://user-images.githubusercontent.com/1976/93160827-0cfbaf80-f6c6-11ea-90c8-c85de0d9398c.png)

2020-09-15 07:07 UTC, mrnugget commented
This looks good to me! I'm going to merge it.

2020-09-15 07:08 UTC, mrnugget approved these changes

2020-09-15 07:27 UTC, merged

2020-09-21 12:06 UTC, eseliger commented on web/src/globals.d.ts
> -}
should we then also remove it from the importer pattern? I wanted this to be rather general though, and we do have some .yml files in our repo, which won't work anymore now 🤔 https://sourcegraph.com/search?q=repo:github.com/sourcegraph/sourcegraph+f:.yml+type:path&patternType=literal