Regex for repogroups
sourcegraph/sourcegraph pull request #13730
Opened 2020-09-09 22:24 UTC by RedHeadedStranger99

Add regex to search scope for repo groups.

2020-09-10 13:02 UTC, keegancsmith requested changes
Nice stuff. Got a few inline comments I wouldn't mind taking a look at once resolved, so requesting changes.

2020-09-10 13:02 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search.go
> +			if repoPathString, ok := repoPath.(string); ok {
I'd recommend using a type switch here. You should also return an error if you get an unexpected type here.
```
switch v := repoPath.(type) {
  case string:
    ...
  case map[string]interface{}:
    ...
  default:
    return error
}
```

2020-09-10 13:02 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search.go
> +func resolveRepoGroups(settings *schema.Settings) (map[string][]*types.Repo, error, []string) {
nit: error is normally always the last returned value.

2020-09-10 13:02 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search.go
> +				regexPatterns = append(patterns, "^"+regexp.QuoteMeta(string(repo.Name))+"$")
we don't need to build up the list of patterns anymore, we should just be able to rely on patterns returned.

2020-09-11 00:49 UTC, beyang commented on cmd/frontend/graphqlbackend/search.go
> +				patterns = append(patterns, repoPathString)
```suggestion
				patterns = append(patterns, "^"+regexp.QuoteMeta(repoPathString)+"$")
```

^ I think this is a bit more precise and is what were previously doing here: https://github.com/sourcegraph/sourcegraph/pull/13730/files#diff-d270aecf1b7e3730429f967a1dad8114L768

2020-09-11 00:51 UTC, beyang approved these changes
Approving pending Keegan's comments are addressed.

2020-09-12 01:10 UTC, beyang commented
I will own this moving forward given that this is the last day of @RedHeadedStranger99's internship. Fixed a bug in the `Repos.List` method (instead of `AND`ing Postgres conditions extracted from the pattern, it should `OR` them). @keegancsmith PTAL.

2020-09-14 10:38 UTC, keegancsmith approved these changes

2020-09-14 10:38 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search.go
> +type regexPath struct {
deadcode, unusud

2020-09-14 10:38 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search.go
> +				log15.Warn("ignoring repo group object of unrecognized type", "object", repoSpec, "type", fmt.Sprintf("%T", repoSpec))
I think we should return an error? This would indicate us breaking sourcegraph and a log message will be ignored. if we are worried about someone missing this in the future, maybe this parsing of configuration can be pulled out and tested?

2020-09-14 10:38 UTC, keegancsmith commented on internal/db/repos_test.go
> +				if !reflect.DeepEqual(want.pattern, qs) {
nit: probably better to convert this into a string and compare that like we do for the verbose logging. Or convert into a `[]string` and use `cmp.Diff`

2020-09-14 17:00 UTC, beyang commented on cmd/frontend/graphqlbackend/search.go
> +				log15.Warn("ignoring repo group object of unrecognized type", "object", repoSpec, "type", fmt.Sprintf("%T", repoSpec))
It feels like a warning is more appropriate here. Otherwise, a mistake in the `search.repositoryGroups` field of global settings will break all searches. Currently, the editor will display yellow warning squiggles, but it won't prevent you from saving the bad config that has invalid entries in `search.repositoryGroups`.

2020-09-14 17:13 UTC, beyang commented on internal/db/repos_test.go
> +				if !reflect.DeepEqual(want.pattern, qs) {
Will look into later (I believe we need to add a `String()` method to the sqlf type).

2020-09-14 17:57 UTC, merged

2020-09-15 08:18 UTC, keegancsmith commented
Just do what you is done above, that should be good enough for comparison:

  fmt.Sprintf("%s %v", q.Query(sqlf.PostgresBindVar), q.Args())