Add base64 encoding to secretsPkg & provide first pass using saved_searches.go
sourcegraph/sourcegraph pull request #13759
Opened 2020-09-11 04:47 UTC by daxmc99

2020-09-11 08:35 UTC, asdine requested changes
I have a few comments about design decisions that I would like to discuss.
About decryption, I think that this could be done more transparently using the database package features.
Concerning how we encrypt the tables, I have a concern about performance, but also about genericity: We may need to find a way to make encryption easier, because I feel we are going to have to copy paste the `EncryptTable` method for every table that needs to be encrypted. Maybe there is something to extract there.

2020-09-11 08:35 UTC, asdine commented on cmd/frontend/internal/bg/db_test.go
> +		fmt.Println("Failed to init secrets package:", err)
Golang regexp package has this [`MustCompile`](https://golang.org/pkg/regexp/#MustCompile) function that is usually used during startup and that panics if the regexp is not valid.
I can see that this pattern is repeated in all the tests, maybe we can simplify this by adding a `secrectspkg.MustInit()` function in the secrets package.
Also, I think it's better to panic in this case, the stacktrace can be helpful for debugging

2020-09-11 08:35 UTC, asdine commented on internal/db/saved_searches.go
> +			plaintext, err := secretPkg.DecodeAndDecryptBytes([]byte(sq.Config.Query))
I really like your idea the other day about types that know how to decrypt themselves when scanned.
How about we add a type that implements the [sql.Scanner](https://golang.org/pkg/database/sql/#Scanner) interface and that is aware of the secrets package?
That way, all we'd have to do in the stores is to change the type of the encrypted field to that type and everything will be done automatically.

2020-09-11 08:35 UTC, asdine commented on internal/db/saved_searches.go
> +	return nil
```suggestion
	return rows.Err()
```

2020-09-11 08:35 UTC, asdine commented on internal/db/saved_searches.go
> +	q := sqlf.Sprintf("SELECT id,query from saved_searches where query like %s%%", secretPkg.KeyHash())
```suggestion
	q := sqlf.Sprintf("SELECT id, query from saved_searches where query like %s%%", secretPkg.KeyHash())
```

2020-09-11 08:35 UTC, asdine commented on internal/db/saved_searches.go
> +		updateQ := sqlf.Sprintf("UPDATE saved_searches SET query=%s WHERE id=%d", cryptBytes, sq.ID)
```suggestion
		updateQ := sqlf.Sprintf("UPDATE saved_searches SET query = %s WHERE id=%d", cryptBytes, sq.ID)
```

2020-09-11 08:35 UTC, asdine commented on internal/db/saved_searches.go
> +func (*savedSearches) EncryptTable(ctx context.Context) error {
If I understand correctly, this will generate N sequential requests to PG, without pause.
Do we want to do this? Some tables can be very large, shouldn't we proceed chunk by chunk instead?

2020-09-11 08:35 UTC, asdine commented on internal/secrets/encryptor.go
> +	DecodeAndDecryptBytes(b []byte) ([]byte, error)
I don't think this package should be aware of the fact that we decided to encode the encrypted values in base64 just to store them in the database.
It seems that this is a storage issue, that shouldn't leak in other parts of the code.

2020-09-11 09:08 UTC, tsenart commented on internal/db/saved_searches.go
> +			plaintext, err := secretPkg.DecodeAndDecryptBytes([]byte(sq.Config.Query))
This is a good idea!

2020-09-13 10:28 UTC, chayim commented on internal/db/saved_searches.go
> +func (*savedSearches) EncryptTable(ctx context.Context) error {
I agree on chunk by chunk - but I'd like to consider than an optimization once we're agreed upon how to get this in.  Having modeled the queries (albeit locally on my server) it's fairly low resource utilization - especially now that the prefix notion exists. Does that seem reasonable - that's where @daxmc99 and I landed on Thursday.

2020-09-14 06:36 UTC, unknwon commented on internal/db/saved_searches.go
> +			plaintext, err := secretPkg.DecodeAndDecryptBytes([]byte(sq.Config.Query))
Brilliant idea :)

2020-09-14 06:44 UTC, unknwon commented on enterprise/cmd/repo-updater/authz/main_test.go
> +	secretsPkg.MustInit()
Doesn't seem like any test under `authz/` directory is changed, is this required?

2020-09-14 06:44 UTC, unknwon commented on enterprise/cmd/repo-updater/authz/main_test.go
>  	"github.com/inconshreveable/log15"
nit:
```suggestion
	"github.com/inconshreveable/log15"

	secretsPkg "github.com/sourcegraph/sourcegraph/internal/secrets"
```

Same in other `main_test.go` files.

2020-09-14 06:44 UTC, unknwon commented on internal/db/saved_searches.go
> +	q := sqlf.Sprintf("SELECT id, query from saved_searches where query like %s%%", secretPkg.KeyHash())
This line seems far too early to be defined from its use, we should consider move it down to line 411?

2020-09-14 06:44 UTC, unknwon commented on internal/db/saved_searches.go
> +func (*savedSearches) EncryptTable(ctx context.Context) error {
Can we have a docstring to explain the intended purpose of this method?

2020-09-14 06:44 UTC, unknwon commented on internal/secrets/encryptor.go
> +	DecodeAndDecryptBytes(b []byte) ([]byte, error)
Agree. Also this interface is getting fat 😛

2020-09-14 10:51 UTC, keegancsmith commented on internal/db/saved_searches.go
> +		//if secretPkg.ConfiguredToEncrypt() {
nit: commented out code?

2020-09-14 10:51 UTC, keegancsmith commented on internal/db/saved_searches.go
> +		var es secretPkg.EncryptedStringValue
can't we just call this package `secret`?

2020-09-14 10:51 UTC, keegancsmith commented on internal/db/saved_searches.go
> +			&es,
These questions are more related to the secrets pacakge than this PR in particular. However, it seems appropriate to ask them now:

- What happens when the encryption key isn't specified?
- What happens if we have an encryption key in the past, but then remove it?
- What happens if someone changes the encryption key?
- What happens if we have plain text secrets and someone adds the encryption key?

2020-09-14 10:51 UTC, keegancsmith commented on internal/secrets/encryptor.go
> +	DecodeAndDecryptBytes(b []byte) ([]byte, error)
> Agree. Also this interface is getting fat 😛

Agreed. Which functions are actually used by callers external to this package? Additionally, it seems like all the call sites on `secrets` just use exported functions on the package. Externally this interface seems unused and an implementation detail that should be hidden?

2020-09-14 14:27 UTC, chayim commented on internal/db/saved_searches.go
> +			&es,
The practical use of the package involves calling ConfiguredToEncrypt(). This means that one can optionally enable or disable encryption.

If someone encrypts data and loses their key, it behaves like all other encryption. The data continues to exist in the database, but isn't readable.

Were the encryption key to change, based on the work done in the database package, the data would re-encrypt with the new key. The secrets package itself, does nothing without direct interaction.

When secrets are plaintext and an encryption key is added - we begin encrypting the data. This is based on code that is currently disabled.

2020-09-14 17:20 UTC, daxmc99 commented
Moved to draft while iterating on the `EncryptedStringValue` type to see if that is more useful than using the secrets pkg directly.

2020-09-15 06:46 UTC, unknwon commented
TODO for next pair session:
- [ ] Return original content if JSONValue is not base64-encoded.

2020-09-16 03:37 UTC, unknwon commented on cmd/frontend/internal/bg/db_test.go
> +		fmt.Println("Failed to init secrets package:", err)
Good point, addressed!

2020-09-16 03:39 UTC, unknwon commented on internal/db/saved_searches.go
> +		var es secretPkg.EncryptedStringValue
Thanks for the suggestion! Renamed.

2020-09-16 03:41 UTC, daxmc99 commented on internal/db/saved_searches.go
> +		//if secretPkg.ConfiguredToEncrypt() {
Dropped

2020-09-16 06:30 UTC, unknwon commented
Highlights for what @daxmc99 and I did on this pair session:

- We refactored the `secrets` package and extracted changes to a much smaller PR, expect that PR to be reviewed and merged first. cc @chayim

2020-09-16 06:48 UTC, keegancsmith commented on internal/db/saved_searches.go
> +			&es,
What exactly happens? IE what error conditions occur/etc. Right now it isn't clear from this PR. It almost looks like an error would happen and the app would break? What do we expect to happen to users just browsing sourcegraph when any of the above happens?

2020-09-16 06:49 UTC, keegancsmith commented
@unknwon did you manage to remove all the calls to `secrets.MustInit()`. It seems like we shouldn't need that.

2020-09-16 09:35 UTC, chayim commented on internal/db/saved_searches.go
> +			&es,
It looks like they've made those changes in the secrets package itself, to ensure something returns (at least empty strings and the like).

2020-09-17 04:37 UTC, unknwon commented
> @unknwon did you manage to remove all the calls to `secrets.MustInit()`. It seems like we shouldn't need that.

@keegancsmith: Yep we removed that in https://github.com/sourcegraph/sourcegraph/pull/13759/commits/7d4bcab8124dbd8fa5bfa7fe483a58bc2ffd756f.

2020-09-17 09:03 UTC, unknwon commented
Hightlights from today's pair session with @daxmc99:
- Removed `MustInit` and instead use `noOpEncryptor` as the initial value for the `defaultEncryptor`.
- Fixed all the failing tests, but we really don't like the way we handle JSON transformation for `secret.JSONValue`. Near the end of session, we started to think _why can't we just convert "secret" columns from JSONB to TEXT_, as we encrypt values of those columns, and they are in fact just TEXT and no longer holds the benefit of storing them in JSONB.

2020-09-23 13:12 UTC, tsenart commented on internal/db/saved_searches.go
> +		if err := rows.Scan(&ss.ID, &ss.Description, &es, &ss.Notify, &ss.NotifySlack, &ss.UserID, &ss.OrgID, &ss.SlackWebhookURL); err != nil {
Have you seen how types like https://github.com/sourcegraph/sourcegraph/blob/main/internal/db/dbutil/dbutil.go#L201 work? You could have something like:

```go
if err := rows.Scan(&ss.ID, &ss.Description, &secret.String{S: &ss.Query}, &ss.Notify, &ss.NotifySlack, &ss.UserID, &ss.OrgID, &ss.SlackWebhookURL);
```

2020-09-23 13:20 UTC, unknwon commented on internal/db/saved_searches.go
> +		if err := rows.Scan(&ss.ID, &ss.Description, &es, &ss.Notify, &ss.NotifySlack, &ss.UserID, &ss.OrgID, &ss.SlackWebhookURL); err != nil {
Good idea! Didn't think of this, only used this technic for scanning NULLABLE values of columns.

2020-09-25 02:28 UTC, unknwon commented on internal/db/saved_searches.go
> +		if err := rows.Scan(&ss.ID, &ss.Description, &es, &ss.Notify, &ss.NotifySlack, &ss.UserID, &ss.OrgID, &ss.SlackWebhookURL); err != nil {
Addressed in https://github.com/sourcegraph/sourcegraph/pull/13759/commits/8088062a92659e6bc31ed9acf8686ad71a5a15d7.

2020-09-26 04:14 UTC, unknwon commented
Closing this PR because it has too many history "noises", will create a fresh one for people to review.

2020-09-26 04:14 UTC, closed without merging