secrets: use base64 and make interface private
sourcegraph/sourcegraph pull request #13841
Opened 2020-09-16 05:22 UTC by unknwon

This changeset is extracted from #13759 to make it easier to review.

1. Refactored `secrets` package to do base64 encoding/decoding.
2. Prepend encryption key hash to ciphertext for easier filtering by primary or secondary key.

Co-authored-by: Dax McDonald <31839142+daxmc99@users.noreply.github.com>

2020-09-16 06:38 UTC, unknwon commented on internal/secrets/encryptor.go
> +	h.Write(k)
Stdlib is ignoring the error as well: 

https://github.com/golang/go/blob/9706f510a5e2754595d716bd64be8375997311fb/src/crypto/sha256/sha256.go#L257

2020-09-16 06:45 UTC, asdine approved these changes
LGTM, I just have one question about naming but nothing blocking

2020-09-16 06:45 UTC, asdine commented on internal/secrets/encryptor.go
> +type encryptorInterface interface {
nit: Isn't the `interface` suffix redondant with the type? I understand that it was made that way to not clash with the `encryptor` implementation, but perhaps we should rename that implementation to something that describes it better, like `gcmEncryptor` or something like this, wdyt?

2020-09-16 06:45 UTC, asdine commented on internal/secrets/encryptor.go
> +	// secondaryKeyHash is the previously hash that was prepended to ciphertext with `seperator`
```suggestion
	// secondaryKeyHash is the previous hash that was prepended to ciphertext with `separator`
```

2020-09-16 06:46 UTC, unknwon commented on internal/secrets/encryptor.go
> +type encryptorInterface interface {
>Isn't the interface suffix redondant with the type? 

Unfortunately it is... we're brain dead at the moment, we thought about the similar thing, since we get your vote, we'll change it!

2020-09-16 07:36 UTC, keegancsmith commented on internal/secrets/encryptor.go
> +	h.Write(k)
yeah, you can explicitly ignore it with `_ =` to get errcheck off your back.

2020-09-16 07:37 UTC, keegancsmith approved these changes

2020-09-16 08:03 UTC, chayim requested changes
With all the changes we've generally made to this it feels like the naming is off. We've created encryption that both encrypts and encodes.  While we need that specifically because of the database, the current result is that were we to need to pass encryption throughout parts of the application it is now both always encoded, and a string.
Maybe we should sold this simply by renaming encryptor to encodedEncryptor?

2020-09-16 08:03 UTC, chayim commented on internal/secrets/encryptor.go
> +	if failed {
The question previously regarding booleans on decryption failure but with errors extends here.

2020-09-16 15:42 UTC, daxmc99 commented on internal/secrets/encryptor.go
> +// Decrypt decrypts the plaintext using the primaryKey of the encryptor.
```suggestion
// Decrypt decrypts base64 encoded ciphertext using the primaryKey of the encryptor
```

2020-09-16 16:41 UTC, daxmc99 commented on internal/secrets/encryptor.go
> +	separator      = "$"
```suggestion
	separator      = "$" // used specifically because $ is not part of base64
```

2020-09-16 16:42 UTC, daxmc99 commented on internal/secrets/encryptor.go
> +	// secondaryKeyHash is the previous hash that was prepended to ciphertext with `separator`
```suggestion
	// secondaryKeyHash contains a partial hash of the previously used encryption key
```

2020-09-16 16:42 UTC, daxmc99 commented on internal/secrets/encryptor.go
>  // relies on the AES-GCM encryption defined in encrypt, within this package.
```suggestion
// relies on the AES-GCM encryption defined in encrypt, within this package, and returns a base64 encoded string
```

2020-09-16 19:18 UTC, daxmc99 commented on internal/secrets/encryptor.go
> +func (e encryptor) Decrypt(ciphertext string) (plaintext string, failed bool, err error) {
This was added for this case https://github.com/sourcegraph/sourcegraph/pull/13841/files#diff-77669ee8fba561ce20a87dd1e8351d1dR414-R423 

When we encounter a string that contains the separator it becomes tricky to determine if the string is encrypted. 

For example,  the string `asbeasa$someString` contains the seperator and is challenging to decrypt. This technically contains the seperator but at the wrong place. Decrypt cannot proceed but this could still be a valid unencrypted string. The `failed` boolean provides the information for this case.

2020-09-16 19:33 UTC, daxmc99 commented on internal/secrets/encryptor.go
> +	// primaryKeyHash is prepended to base64-encoded ciphertext with `separator`.
```suggestion
	// primaryKeyHash contains a partial hash of the active encryption key
```

2020-09-17 03:07 UTC, daxmc99 commented on internal/secrets/encryptor.go
>  	validKeyLength = 32 // 32 bytes is the required length for AES-256.
Renamed

2020-09-17 03:13 UTC, daxmc99 commented on internal/secrets/encryptor.go
> +// sliceKeyHash returns a string which is the first 6 bytes of given key's SHA256 checksum in hexadecimal.
Updated 👍

2020-09-17 04:16 UTC, unknwon commented on internal/secrets/encryptor.go
> +func (e encryptor) Decrypt(ciphertext string) (plaintext string, failed bool, err error) {
We changed `Decrypt` method to return a special error (`ErrDecryptAttemptedButFailed`) so it is up to callers what to do with it.

2020-09-17 04:19 UTC, unknwon commented
@daxmc99 and I are happy with the current state of this PR, and is going to merge as-is to unblock our work on https://github.com/sourcegraph/sourcegraph/pull/13759. Feel free to add post-merge comments and we'll address them along with #13759 assuming no major design change required.

2020-09-17 04:19 UTC, merged