campaigns: add backlink when creating changesets
sourcegraph/sourcegraph pull request #14033
Opened 2020-09-22 01:58 UTC by LawnGnome

Here's how the backlinks look in GitLab, as an example:

![image](https://user-images.githubusercontent.com/229984/93837577-7c7c1c80-fc3b-11ea-8590-7f03aa05451a.png)

The styling is taken from [how GitHub styles the line added when an issue is created from a comment](https://docs.github.com/en/github/managing-your-work-on-github/opening-an-issue-from-a-comment).

There's also a bonus refactor in here: #13965 added `internal/db/namespaces.go`: I've expanded this out to add the functionality I need (resolving a namespace from an ID tuple) and also brought that file more into line with other files in `internal/db` by using `sqlf` and namespacing its methods with an empty struct like the other files. Those are in separate commits, so if people would prefer these to go into separate PRs, I'm happy to make that split.

2020-09-22 08:06 UTC, mrnugget requested changes
Love the `namespaces.go` refactor and the rest of the code but marking it as "Request changes" because I think you need to add the decoration to `updateChangeset` too.

I also added comments regarding the `OwnedByCampaignID` check, which I think you can get rid of, which in turn would allow you to remove some tests, which in turn allows you to extend the existing one and makes it easier to add the same assertion for `update` :)

2020-09-22 08:06 UTC, mrnugget commented on enterprise/internal/campaigns/reconciler_test.go
> +	})
See above, I think you can get rid of the check and then also don't need these two tests anymore. Then you could, theoretically, fold the `"integration"` subtest into the reconciler test and simply add the assertion that `if tc.wantCreateOnHostCode { fakeSource.CreatedChangesets[0].Body should contain backlink }`

2020-09-22 14:07 UTC, eseliger commented on enterprise/internal/campaigns/testing/changeset_source.go
> +	// CreatedChangesets contains the changesets that were passed to CloseChangeset
```suggestion
	// CreatedChangesets contains the changesets that were passed to CreateChangeset
```

2020-09-22 20:22 UTC, LawnGnome commented on enterprise/internal/campaigns/reconciler.go
> +	if err := decorateChangesetBody(ctx, tx, cs); err != nil {
You are correct, and the "ugh" I said when I saw this notification this morning was due to the fact that I knew that and somehow forgot _after_ I'd done some of the plumbing. Updating the PR.

2020-09-22 20:26 UTC, LawnGnome commented on enterprise/internal/campaigns/reconciler.go
> +} = api.InternalClient
I 100% stole that from @sqs, who did something similar in #13965. It's one of those things that falls out of Go's type system when you think about it, but I'd never thought about it.

2020-09-22 20:37 UTC, LawnGnome commented on enterprise/internal/campaigns/reconciler.go
> +	if cid := cs.OwnedByCampaignID; cid != 0 {
> which will happen in the subsequent `tx.GetCampaign()` call

Actually, it won't, because the only option that's set is `ID: 0`, and [that will prevent any WHERE clauses from being added](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/campaigns/store_campaigns.go#L250-252), which means that a random campaign will be returned.

I'm unsure whether the right fix here is to drop the check and test in `GetCampaign` if no options have been enabled, or to keep the check. Thoughts?

2020-09-22 20:40 UTC, LawnGnome commented on enterprise/internal/campaigns/reconciler.go
> +	// To build the absolute URL, we need to know where Sourcegraph is!
Definitely. `InternalClient.ExternalURL()` [actually has two TODOs that are essentially "get rid of this"](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@331332d/-/blob/internal/api/internal_client.go#L218-222).

2020-09-22 20:52 UTC, LawnGnome commented on enterprise/internal/campaigns/reconciler_test.go
> +	})
Yep, good catch. Thanks for having that higher level view!

2020-09-22 20:52 UTC, LawnGnome commented on enterprise/internal/campaigns/testing/changeset_source.go
> +	// CreatedChangesets contains the changesets that were passed to CloseChangeset
I noticed that when I was addressing Thorsten's feedback, so this is fixed. Thanks!

2020-09-23 07:20 UTC, mrnugget commented on enterprise/internal/campaigns/reconciler.go
> +	if cid := cs.OwnedByCampaignID; cid != 0 {
I think the check should go into `determineAction`. Or in `loadAssociations`.

2020-09-23 07:22 UTC, mrnugget approved these changes

2020-09-23 19:08 UTC, LawnGnome commented on enterprise/internal/campaigns/reconciler.go
> +	if cid := cs.OwnedByCampaignID; cid != 0 {
`loadAssociations()` feels right to me. Thanks!

2020-09-23 19:17 UTC, LawnGnome commented
We're not in a pressing rush on this, so I'm going to leave this open for @mrnugget to take one last look at f74ea07 in his morning even with the approval, since he's made a couple of good points on how this should fit together. Otherwise, I think we're done here.

2020-09-24 00:30 UTC, eseliger approved these changes
LGTM

2020-09-24 00:30 UTC, eseliger commented on enterprise/internal/campaigns/reconciler.go
> +	}
I think this doesn't work, we throw ErrNoResults errors

```suggestion
	campaign, err := tx.GetCampaign(ctx, GetCampaignOpts{ID: id})
	if err != nil && err != ErrNoResults {
		return nil, errors.Wrapf(err, "retrieving owning campaign: %d", id)
	} else if campaign == nil {
		return nil, errors.Errorf("campaign not found: %d", id)
	}
```

2020-09-24 05:51 UTC, mrnugget approved these changes

2020-09-24 05:51 UTC, mrnugget commented
Thanks! I'm going to go ahead and merge it so we save a rebase.

2020-09-24 05:51 UTC, merged