Add 'Take Sourcegraph to your [code host]' popup
sourcegraph/sourcegraph pull request #14256
Opened 2020-09-28 22:26 UTC by tjkandala

Closes #14199.

- [x] - Convert `GoToCodeHostAction` to function component
- [x] - Implement popup
- [x] - Remove chrome extension toast

2020-09-28 23:09 UTC, sqs commented
In https://github.com/sourcegraph/sourcegraph/pull/14261 I made it so it shows the toast on your 3rd day of activity, not your 1st. Not sure how you're doing it here, but you should make it so this doesn't show up the very first time they visit Sourcegraph.

2020-09-28 23:19 UTC, tjkandala commented
We're removing the toast as part of [RFC 221](https://docs.google.com/document/d/19f4xleYBU1zZZdqMmXlLmFxeR-fwEpOwTOgViOFOnyo) in favor of inline alerts after the user has seen 2 hovers.

That's a good idea though; cc @sourcegraph/web @AlicjaSuska Should we check `daysActiveCount` for this popup?

2020-09-29 06:36 UTC, AlicjaSuska commented
This popup is displayed after clicking on 'view on GitHub'. I think it doesn't make sense to add the day count as criteria here. I think it makes sense to show this information even if someone clicks 'view on [code host]' for the first time.

2020-09-29 09:12 UTC, felixfbecker commented
@AlicjaSuska maybe we can include the criterium "Has seen at least 2 hovers" too with the same reasoning as for the alert?

2020-09-29 09:42 UTC, felixfbecker reviewed
**issue**: How are we going to test this and prevent regressions? Having a story for the modal sounds like a good idea, and maybe an integration test for the behavior?

2020-09-29 09:42 UTC, felixfbecker commented on web/src/auth/icons.tsx
> +        height={size ?? '64'}
**suggestion**: a `size` prop doesn't really make sense to me given this SVG doesn't even seem to be square. Is there any reason we can't use CSS to set the `height` or `width`? That way we can use `rem`, enforce our stylelint rules, easily make it responsive if needed etc. I'd generally avoid `size` because it's essentially an inline style like `style={{ height: '65px' }}`, which we disallow in favor of using CSS and class names.

2020-09-29 09:42 UTC, felixfbecker commented on web/src/repo/actions/GoToCodeHostAction.tsx
> +                <ModalContainer onClose={onClose} hideCloseIcon={true} className="justify-content-center">
**suggestion**: I'd put the modal into its own component (I was a bit confused for example by class names like `code-host-action__plus-icon`)

2020-09-29 09:42 UTC, felixfbecker commented on web/src/repo/actions/GoToCodeHostAction.tsx
> +                                <LinkOrButton
**question**: this is always a link, so why use `LinkOrButton` instead of `<a>`? Reading `LinkOrButton`, it would imply to the reader that it's dynamic, which could be confusing.

2020-09-29 09:42 UTC, felixfbecker commented on web/src/repo/actions/GoToCodeHostAction.tsx
> +                                <Icon size={56} />
**suggestion**: instead of unitless sizes, could we define this in CSS?

2020-09-29 10:10 UTC, felixfbecker commented on web/src/repo/actions/GoToCodeHostAction.tsx
> +                                <LinkOrButton
Okay, I just figured out that `LinkOrButton` is really badly named. It's not a link _or_ a button in any way (like `LinkOrSpan`), it's _always_ a link, but with the _behavior_ of a button. Imo it should be renamed to `ButtonLink`.

2020-09-30 09:31 UTC, AlicjaSuska commented
@felixfbecker let's add the '2 hovers' criteria, you're right.

2020-10-01 00:17 UTC, tjkandala commented
If the user clicks "Install the Sourcegraph browser extension" from the alert, but doesn't install the extension, should we disable the popover for the 'View on code host button'? They're both dependent on the user seeing 5 hovers now, so it might be annoying to see the popover after already looking to, but not installing, the extension.

2020-10-01 02:43 UTC, tjkandala commented on web/src/repo/actions/GoToCodeHostAction.tsx
> +                    placement: 'bottom-start' as const,
const assertion isn't necessary here

2020-10-01 19:17 UTC, tjkandala commented on web/src/integration/blob-viewer.test.ts
> +                    await driver.page.waitForSelector('.hover-overlay', { visible: true })
Should I keep this check? The test passes without it, but we may need to wait for the hover overlay if the hover provider in our mock extension becomes asynchronous.

2020-10-01 19:18 UTC, tjkandala commented on web/src/integration/blob-viewer.test.ts
> +                assert.deepStrictEqual(popoverHeader, "Take Sourcegraph's code intelligence to GitHub!")
Should we also assert that the popover is _not_ visible before $HOVER_OVERLAY hovers? If so, what would be the best approach here (I wasn't able to find such an assertion in our integration tests).

2020-10-01 19:43 UTC, tjkandala commented on web/src/integration/blob-viewer.test.ts
> +                assert.deepStrictEqual(popoverHeader, "Take Sourcegraph's code intelligence to GitHub!")
Is asserting that `execute(() => document.querySelector('.test-install-extension-popover')` returns null a satisfactory solution?

2020-10-02 07:49 UTC, AlicjaSuska commented
@tjkandala 
- I've changed the pointer to 12px square rotated 45 degrees - as you've suggested [See the design](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=378%3A28)
- I've updated the designs in [Figma](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=378%3A28). Please, pay attention to [dark mode](https://www.figma.com/file/V5t7KOzC6PIX75L4dz8IFc/RFC-221-Browser-extension-improve-discoverability-and-awareness-Approved?node-id=507%3A273) - I've changed the background color slightly
- about your comment: _'If the user clicks "Install the Sourcegraph browser extension" from the alert, but doesn't install the extension, should we disable the popover for the 'View on code host button'?_ - I see the value in showing the popover in the context of clicking on 'view on [code host] even if user already visited the extension page but didn't install. It can serve as reminder / seeing the potential benefit in context. I think they shouldn't be dependent. Both should be dismissed only explicitly by the user (by X for alert or 'no, thanks' for the popover) or by installing the extension.

2020-10-02 10:26 UTC, felixfbecker commented on shared/src/components/LinkOrButton.tsx
> + * It is keyboard accessible: unlike `<Link>` or `<a>`, pressing the enter key triggers it.
**thought**: I'm starting to question the validity of the entire `LinkOrButton`/`ButtonLink`  component. This comment stated that `<button>`s don't show a focus ring, which is false - the buttons in our app all have focus rings. But now I just verified that hitting <kbd>enter</kbd> when a link is focused also triggers navigation in Chrome, so that statement seems to be false too, leaving no reason to use this component.
The only case where it would not do anything is if the link only had `onClick`, but in that case it _should not be_ a link, it should be a `<button>`. It seems like for our use cases we should always use `<button>` or `<a>`/`<Link>` directly and avoid this component, potentially remove it.
cc @sourcegraph/frontend-engineers

2020-10-02 10:26 UTC, felixfbecker commented on web/src/auth/icons.tsx
> +        height={size ?? '64'}
This change wasn't reverted

2020-10-02 11:04 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.tsx
> +                    className="extension-permission-modal p-4 web-content text-wrap border shadow test-install-extension-popover"
**suggestion**: Bootstrap has CSS popovers, including triangles. Should we just use those (CSS only)? https://getbootstrap.com/docs/4.5/components/popovers/
If they don't match the design exactly, there are likely Sass variables we can set to refine colors etc.

2020-10-02 11:04 UTC, felixfbecker commented on web/src/integration/blob-viewer.test.ts
> +                    await driver.page.waitForSelector('.hover-overlay', { visible: true })
Everything in Puppeteer is always asynchronous, so yes, we should always have such checks.

2020-10-02 11:05 UTC, felixfbecker commented on web/src/integration/blob-viewer.test.ts
> +                assert.deepStrictEqual(popoverHeader, "Take Sourcegraph's code intelligence to GitHub!")
I think we should have such an assertions and I think that is a perfectly fine way to verify that.

2020-10-02 19:21 UTC, tjkandala commented on web/src/components/useModality.ts
> + * `useModality` adds focus trapping and intuitive close logic to modal containers.
It looks like it may be removed from the spec based on [this comment](https://github.com/whatwg/html/issues/3567#issuecomment-451451406). Regardless, the polyfill looks good, so I'll look into it after implementing the rest of RFC 221.

2020-10-02 21:14 UTC, tjkandala commented on web/src/components/PopoverContainer.scss
> +    animation: fadeIn 0.3s both ease-in;
I don't think that would work here ([explanation](https://fvsch.com/transition-fade)). 

This works for `HoverOverlay` since we set the opacity to 0 before we get the `overlayPosition`.
![Screenshot from 2020-10-02 17-05-15](https://user-images.githubusercontent.com/37420160/94969873-7a367f80-04d1-11eb-900a-c62119cba55b.png)

2020-10-02 22:23 UTC, tjkandala commented on web/src/repo/actions/InstallExtensionPopover.tsx
> +                    className="extension-permission-modal p-4 web-content text-wrap border shadow test-install-extension-popover"
I'm not sure that we can use it [CSS-only](https://getbootstrap.com/docs/4.5/components/popovers/#example-enable-popovers-everywhere), and the [API seems more complex](https://getbootstrap.com/docs/4.5/components/popovers/#methods) than raw Popper. I'll try using Reactstrap's `Popover`, which looks [promising](https://reactstrap.github.io/components/popovers/) ([implementation](https://github.com/reactstrap/reactstrap/blob/master/src/TooltipPopoverWrapper.js)).

2020-10-03 13:12 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.tsx
> +                    className="extension-permission-modal p-4 web-content text-wrap border shadow test-install-extension-popover"
Curious what happens when an element is assigned the CSS class `popover`? Why doesn't it work?

2020-10-04 04:01 UTC, tjkandala commented
Update: Replaced all (2) modals in the web app with `@reach/dialog`, replaced custom popover with reactstrap's popover and `@reach/popover` (to compare), and removed `useModality` hook.

### Reactstrap popover

<details>
<summary>Keyboard navigation</summary>
<img src="https://user-images.githubusercontent.com/37420160/95006224-05963a80-05d0-11eb-9276-90ec85b1e2f2.gif" />
</details>

Fade in and visuals are same as in original post.

### Reach popover

<details>
<summary>Keyboard navigation</summary>
<img src="https://user-images.githubusercontent.com/37420160/95006425-5e66d280-05d2-11eb-9559-867fff53b4ce.gif" />
</details>


No fade in.

#### Popover visuals

![Screenshot from 2020-10-03 23-46-01](https://user-images.githubusercontent.com/37420160/95006450-a259d780-05d2-11eb-911e-1032305d0183.png)

#### Summary

Reactstrap's popover is easier to visually customize, but I don't think it's meant to be used with interactive elements. Reach adheres to the [ARIA spec](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal), but is hard to position when compared to Popper's `modifiers` system (Popper does the heavy lifting for both reactstrap's popover and the original custom popover). 

I'll spend a little more time trying to get Reach's popover to align with the design. If that doesn't work out, I propose that we use reactstrap's popper combined with the [focus-trap](https://github.com/focus-trap/focus-trap) library to essentially recreate the original implementation, but with more robust and mature 3rd-party building blocks.

2020-10-04 04:42 UTC, tjkandala commented on web/src/repo/actions/InstallExtensionPopover.tsx
> +                    className="extension-permission-modal p-4 web-content text-wrap border shadow test-install-extension-popover"
Nothing happens :). I think we have to activate them with this [jQuery incantation](https://getbootstrap.com/docs/4.5/components/popovers/#example-enable-popovers-everywhere). We haven't had to do this yet since we use reactstrap's tooltip component, which re-implements this functionality without jQuery.

It looks like Bootstrap [adds the tooltip method to jQuery](https://sourcegraph.com/github.com/twbs/bootstrap/-/blob/dist/js/bootstrap.bundle.js#L6681), so we wouldn't be able to access it.

2020-10-05 06:59 UTC, lguychard commented on web/src/repo/actions/GoToCodeHostAction.tsx
> +    const [nextComponentUpdate, fileExternalLinksOrError] = useEventObservable<
Isn't getting an observable based off props changes meant to be achieved with dependency arrays?

```typescript
    /**
     * The external links for the current file/dir, or undefined while loading, null while not
     * needed (because not viewing a file/dir), or an error.
     */
    const fileExternalLinksOrError = useObservable<ExternalLinkFields[] | null | undefined | ErrorLike>(
        useMemo(() => {
            if (!props.repo || !props.filePath) {
                return of(null)
            }
            return merge(
                of(undefined),
                fetchFileExternalLinks({ repoName: props.repo.name, revision, filePath: props.filePath }).pipe(
                    catchError(error => [asError(error)])
                )
            )
        }, [props.repo, props.filePath])
    )
```

2020-10-05 09:29 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.tsx
> +                    className="extension-permission-modal p-4 web-content text-wrap border shadow test-install-extension-popover"
I wouldn't expect any of the behavior to work, but I would expect it to apply some styling (even if e.g. it's hidden by default). It seems that it doesn't apply anything, which led me to check whether we actually import the popover styles from Bootstrap yet in SourcegraphWebApp.scss, and we don't. So that explains why nothing happens. If we import it, there is styling applied, although the arrow is not positioned correctly without JS (e.g. using Reactstrap or custom logic). The CSS could potentially save the custom CSS that's in this PR for popovers and the TODO for making arrows.

2020-10-05 09:30 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.story.tsx
> +            }, [])
It would be good to add a comment why this is needed (it's not obvious)

2020-10-05 09:31 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.tsx
> +                    className="extension-permission-modal p-4 web-content text-wrap border shadow test-install-extension-popover"
What I was trying to understand was the reason behind why you said "I'm not sure that we can use it CSS-only"

2020-10-05 09:34 UTC, felixfbecker commented
@tjkandala looks like you did good research on the best solution for popovers! If we're using Reactstrap now, does that mean we also need to add an import to the Bootstrap styles and they should "just work"? (I see that we still have custom CSS for the popover despite using Reactstrap, and that the arrow still doesn't work)

2020-10-06 00:14 UTC, tjkandala commented
> @tjkandala looks like you did good research on the best solution for popovers! If we're using Reactstrap now, does that mean we also need to add an import to the Bootstrap styles and they should "just work"? (I see that we still have custom CSS for the popover despite using Reactstrap, and that the arrow still doesn't work)

Replaced custom CSS with Bootstrap styles, which fixed the arrow. Weirdly, importing Bootstrap styles changed the way that the offset works. 

#### No offset
![Screenshot from 2020-10-05 18-56-35](https://user-images.githubusercontent.com/37420160/95144700-482e5300-0747-11eb-8559-778b09dae3e4.png)

#### Offset "0, -4" (Same as original post)
![Screenshot from 2020-10-05 18-43-11](https://user-images.githubusercontent.com/37420160/95144717-51b7bb00-0747-11eb-99c2-5aafc3785110.png)

2020-10-06 16:51 UTC, AlicjaSuska requested changes
Thank you for this work @tjkandala I finally could test it after your help 🎉

Improvements that are needed:
- popup should appear for users who have **3 hovers**, not 5 (as it is now)
- **pointer** styles are not aligned with the design. If it's a very difficult fix we can also remove the pointer entirely to speed things up.
- in dark mode, there are **light points** in the corners of the popover. I'm not sure what are those.
<img width="439" alt="Screenshot 2020-10-06 at 18 40 36" src="https://user-images.githubusercontent.com/20326070/95231895-10d1ac00-0804-11eb-8470-c8ae9103a4f9.png">
- if we move forward with the pointer, it should be closer to the icon, 4 px above the divider (now it touches the divider) Design screenshot:
<img width="147" alt="Screenshot 2020-10-06 at 18 46 07" src="https://user-images.githubusercontent.com/20326070/95232076-50989380-0804-11eb-945f-b7628f7fbd07.png">
- after clicking on 'install the extension', Docs should open in the **new tab** (not in the same tab as currently)

2020-10-06 20:00 UTC, tjkandala commented
![Screenshot from 2020-10-06 15-20-47](https://user-images.githubusercontent.com/37420160/95253721-cf81d200-07ec-11eb-924f-d9c953acf704.png)

update: @AlicjaSuska. Links also open in new tabs when the user originally middle clicked 'Go to [code host]'.

2020-10-06 20:11 UTC, felixfbecker commented on web/src/components/Dialog.scss
> +.modal-body {
**thought**: Bootstrap has `modal` too, I wonder if we should reuse that (not in this PR or iteration though)

2020-10-06 20:11 UTC, felixfbecker commented on web/src/integration/blob-viewer.test.ts
> +                assert.deepStrictEqual(
```suggestion
                assert.strictEqual(
```

2020-10-06 20:11 UTC, felixfbecker commented on web/src/repo/RepoContainer.tsx
> +    /** TODO description */
TODO

2020-10-06 20:11 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.scss
> +        border-bottom-color: var(--body-bg) !important;
**question**: shouldn't this be set in global-styles for all popovers? Or perhaps there is just a Bootstrap Sass var we can set for this? Usually we need to set some Sass variables for every Bootstrap component when start using it to make it theme-aware, and this PR is the first one to use `popover`, so that's likely

2020-10-06 20:12 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.tsx
> -    // TODO: store type of original click (normal vs aux). If it was an aux click, open link in new tab
**suggestion**: shouldn't we just always open in a new tab, since it's an external link? Seems like that would save a lot of code

2020-10-06 20:14 UTC, felixfbecker commented
> popup should appear for users who have 3 hovers, not 5 (as it is now)

@AlicjaSuska this was something we discussed when we hacked on this, 3 felt very low. Do you feel strongly about 3?

2020-10-06 20:14 UTC, tjkandala commented on web/src/repo/actions/InstallExtensionPopover.tsx
> -    // TODO: store type of original click (normal vs aux). If it was an aux click, open link in new tab
I implemented this since the original implementation opened the link in the same tab, but you're right. I'll revert this

2020-10-06 20:22 UTC, tjkandala commented on package.json
> +    "@reach/dialog": "^0.11.2",
We use `@reach/dialog` for `SavedSearchModal` and `ExtensionPermissionModal`

2020-10-06 20:48 UTC, tjkandala commented on web/src/repo/actions/InstallExtensionPopover.scss
> +        border-bottom-color: var(--body-bg) !important;
Implemented this change. However, I found out that other popovers in our application broke once we imported Bootstrap's popover styles, probably since they were built without Bootstrap in mind. I set `$popover-max-width` to `auto`. Do you think this is the right change?

2020-10-06 20:50 UTC, tjkandala commented on web/src/components/Dialog.scss
> +.modal-body {
+1, Bootstrap modals are good

2020-10-07 06:20 UTC, felixfbecker commented on web/src/repo/actions/InstallExtensionPopover.scss
> +        border-bottom-color: var(--body-bg) !important;
We obviously can't break other popovers, so if that change fixes it, that sounds right. I wasn't aware we actually used the class elsewhere given we had not imported it. I also just found these styles:

https://github.com/sourcegraph/sourcegraph/blob/9308b5e932036efde80e6a7b926383130e8aeb98/web/src/SourcegraphWebApp.scss#L233-L239

They can probably be removed, and that comment looks like it doesn't apply if we set the [variables](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/twbs/bootstrap%24+%24popover+-f:dist&patternType=literal) correctly. The arrow also seems to be an element you have to explicitly render in the DOM, so that can just be omitted if we don't want it for certain popovers (like the rev switcher).

2020-10-08 08:34 UTC, AlicjaSuska commented
> > popup should appear for users who have 3 hovers, not 5 (as it is now)
> 
> @AlicjaSuska this was something we discussed when we hacked on this, 3 felt very low. Do you feel strongly about 3?

I think 3 is enough to understand what tooltips do. It's a gut feeling though, I don't have any strong evidence of 3 being better than 5. Why 3 felt low for you? @felixfbecker

2020-10-08 11:58 UTC, felixfbecker commented
Because you could reach 3 very easily accidentally by just moving the mouse across the page

2020-10-08 12:30 UTC, marekweb approved these changes

2020-10-08 20:52 UTC, felixfbecker approved these changes

2020-10-08 20:54 UTC, felixfbecker commented
@AlicjaSuska I think your concerns were all adressed, if not we can follow up :)

@tjkandala let's merge 🎉 
You can rebase with `git rebase --strategy-option="rename-threshold=10" main` which handled the renames flawlessly for me.

2020-10-08 23:47 UTC, merged