search: enable enterprise home panels by default
sourcegraph/sourcegraph pull request #14288
Opened 2020-09-29 21:43 UTC by limitedmage

Fixes #14287

2020-09-30 03:15 UTC, attfarhan approved these changes

2020-09-30 03:53 UTC, attfarhan requested changes

2020-09-30 03:53 UTC, attfarhan commented on dev/global-settings.json
> +    "showRepogroupHomepage": true
Should this be `showEnterpriseHomepage`?
```suggestion
    "showEnterpriseHomepage": true
```

2020-09-30 03:57 UTC, limitedmage commented on dev/global-settings.json
> +    "showRepogroupHomepage": true
This is the current name of the feature flag. I think there are arguments to be made for renaming it (eg. removing the `enterprise` word from it as we start to use it more in Cloud), but it's out of scope for this PR.

2020-09-30 09:00 UTC, attfarhan commented on dev/global-settings.json
> +    "showRepogroupHomepage": true
Oh sorry I mistyped `showEnterpriseHomePanels` to `showEnterpriseHomepage`. Doesn't this PR want to enable `showEnterpriseHomePanels ` by default? Why are we enabling `showRepogroupHomepage` by default in dev and not `showEnterpriseHomePanels`?

2020-09-30 10:54 UTC, lguychard commented on dev/global-settings.json
> +    "showRepogroupHomepage": true
This PR is switching the feature flag default for `showEnterpriseHomePanels` from `false` to `true`, so it doesn't need to be explicitly listed in `global-settings.json` anymore.

2020-09-30 10:54 UTC, lguychard approved these changes

2020-09-30 10:54 UTC, lguychard commented
@limitedmage can you add a changelog entry? Thanks!

2020-10-01 01:24 UTC, attfarhan approved these changes

2020-10-01 01:25 UTC, attfarhan commented on dev/global-settings.json
> +    "showRepogroupHomepage": true
Ah so sorry 🤦

2020-10-01 02:24 UTC, merged