search: stream out repository matches
sourcegraph/sourcegraph pull request #14311
Opened 2020-09-30 11:48 UTC by keegancsmith

This streams out repository matches. The adapter in stream.tsx sets the
fields to the same values that our graphql backend computed.

Part of #13067

2020-09-30 12:17 UTC, lguychard approved these changes
LGTM, left some non-blocking comments.

2020-09-30 12:17 UTC, lguychard commented on web/src/search/stream.tsx
> +    }
```suggestion
    const branch = repo?.branches[0]
    const revision = branch ? `@${branch}` : ''
```

2020-09-30 12:17 UTC, lguychard commented on web/src/search/stream.tsx
> +        label: md('[' + label + '](/' + label + ')'),
```suggestion
        label: md(`[${label}](/${label})`),
```

2020-09-30 12:17 UTC, lguychard commented on web/src/search/stream.tsx
> +                    throw new TypeError('internal error: expected MessageEvent in streaming search filematches')
```suggestion
                    throw new TypeError('internal error: expected MessageEvent in streaming search repomatches')
```

Alternatively, since we're doing the `if (!(event instanceof MessageEvent)) { }` dance three times already, here is a helper suggestion that would help DRY:

```typescript
const observeMessages = <T extends {}>(eventSource: EventSource, eventName: SearchEvent['type']): Observable<T> =>
    fromEvent(eventSource, eventName).pipe(
        map((event: Event) => {
            if (!(event instanceof MessageEvent)) {
                throw new TypeError('internal error: expected MessageEvent in streaming search ${eventName}')
            }
            try {
                const parsedData = JSON.parse(event.data) as T
                return parsedData
            } catch (err) {
                throw new Error(`Could not parse ${eventName} message data in streaming search`)
            }
        })
    )

subscriptions.add(
    observeMessages<RepositoryMatch[]>(eventSource, 'repomatches').pipe(
        map(matches => ({ type: 'repomatches' as const, matches }))
    ).subscribe(observer)
)
```

2020-09-30 12:39 UTC, keegancsmith commented on web/src/search/stream.tsx
> +}
I like that, much more explicit. One benefit of leaving the extra fields in here is its much easier to read the file and know what the fields are. I'm assuming its best to elide them though in TS code?

2020-09-30 12:39 UTC, keegancsmith commented on web/src/search/stream.tsx
> +const md = (text: string): GQL.IMarkdown => ({ __typename: 'Markdown', text } as GQL.IMarkdown)
ssssssh, don't tell anyone. But look at line 1.

2020-09-30 12:39 UTC, keegancsmith commented on web/src/search/stream.tsx
> +    }
aah, I knew there was a way with ?., just wasn't sure. So does this work even if branches is `[]` (ie declared, but empty)?

Edit: I got object is possibly undefined. So can't do this. But will atleast switch to string templates.

Edit 2: If you are unsure, just add more elvis operators. `repo?.branches?.[0]`

2020-09-30 12:39 UTC, keegancsmith commented on web/src/search/stream.tsx
> +                    throw new TypeError('internal error: expected MessageEvent in streaming search filematches')
`SearchEvent['type']` wow, nifty stuff. Is there a way to annotate the could not parse error with information about the original parsing error?

For bonus marks I am sure there is a way we can make observeMessages include `type` field in the response in a typesafe way.

2020-09-30 21:24 UTC, limitedmage requested changes

2020-09-30 21:24 UTC, limitedmage commented on web/src/search/stream.tsx
> +            'data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJMYXllcl8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9
This should be an image asset uploaded to our CDN

2020-09-30 21:24 UTC, limitedmage commented on web/src/search/stream.tsx
> +                    // File matches are additive
```suggestion
                    // Repository matches are additive
```

2020-09-30 21:24 UTC, limitedmage commented on web/src/search/stream.tsx
> +        // copy-pasta from repositories.go :'(
**nit:** remove line

2020-09-30 21:24 UTC, limitedmage commented on web/src/search/stream.tsx
> +    // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
**nit:** I don't think this is needed (at least it wasn't complaining on my local instance when I removed it)

2020-09-30 21:24 UTC, limitedmage commented on web/src/search/stream.tsx
> +const toMarkdown = (text: string): GQL.IMarkdown => ({ __typename: 'Markdown', text } as GQL.IMarkdown)
You can remove the above eslint comment with: 

```suggestion
const toMarkdown = (text: string): GQL.IMarkdown => ({ __typename: 'Markdown', text, html: '' })
```

2020-09-30 21:24 UTC, limitedmage commented on web/src/search/stream.tsx
> +        label: toMarkdown('[$label](/$label)'),
```suggestion
        label: toMarkdown(`[${label}](/${label})`),
```

2020-09-30 21:24 UTC, limitedmage commented on web/src/search/stream.tsx
> +            case 'repomatches':
We also need to update the `matchCount` whenever we get more `filematches` or `repomatches`; right now there is an error at the bottom of the page with not search results because it's 0 ([see code that renders this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@k/stream-repo/-/blob/web/src/search/results/SearchResultsList.tsx#L472:85)):
![image](https://user-images.githubusercontent.com/206864/94741023-5d127d00-0328-11eb-935e-88ceb981b761.png)

2020-09-30 21:27 UTC, limitedmage commented on web/src/search/stream.tsx
> +const md = (text: string): GQL.IMarkdown => ({ __typename: 'Markdown', text } as GQL.IMarkdown)
What are the implications of removing line 1? I'd rather not disable eslint warnings if possible.

2020-09-30 21:27 UTC, limitedmage approved these changes

2020-10-01 03:39 UTC, keegancsmith commented on web/src/search/stream.tsx
> +            'data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJMYXllcl8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9
This is copy-paste of how we do it right now. Our graphql layer literally returns this for every repository result. Given this is for the PoC layer, I will avoid doing work like that. I am sure this icon already exists in our repo somewhere.

2020-10-01 03:42 UTC, keegancsmith commented on web/src/search/stream.tsx
> +// This requires to add a RepositoryMatch event. We could however model FileMatch's as a generic type? What do you think is better?
I agree, there was something about using `extends` which gave me flashbacks to java. I prefer this :P

2020-10-01 03:42 UTC, keegancsmith commented on web/src/search/stream.tsx
> +const toMarkdown = (text: string): GQL.IMarkdown => ({ __typename: 'Markdown', text } as GQL.IMarkdown)
The generated IMarkdown type is incorrect, html is actually optional. I worry about setting it to the empty string and then another layer using it since the field will then be defined.

2020-10-01 03:42 UTC, keegancsmith commented on web/src/search/stream.tsx
> +        // copy-pasta from repositories.go :'(
Intentionally put in to justify my shame of the copy pasted base64 image below.

2020-10-01 03:42 UTC, keegancsmith commented on web/src/search/stream.tsx
> +    // eslint-disable-next-line @typescript-eslint/consistent-type-assertions
```suggestion
```

2020-10-01 03:42 UTC, keegancsmith commented on web/src/search/stream.tsx
> +            case 'repomatches':
yup, was planning on tackling stats in a later commit.

2020-10-01 03:47 UTC, keegancsmith commented on web/src/search/stream.tsx
> +const md = (text: string): GQL.IMarkdown => ({ __typename: 'Markdown', text } as GQL.IMarkdown)
Personally I think the warning is silly in the case I want to use it and leads to uglier code. I use it in the wrappers where I convert a filematch to a gql.IFileMatch. Every line of the function would go from referencing `fm` to `fileMatch`. I won't die on this hill, but 3 char min for variable names is silly.

2020-10-01 04:03 UTC, merged