graphqlbackend: remove unused types
sourcegraph/sourcegraph pull request #14326
Opened 2020-10-01 07:06 UTC by keegancsmith

These are types in our graphql API which are mentioned in any other
type/mutation/etc. This commit removes

- DefaultSettings
- DeploymentConfiguration
- Diff
- DiffSearchResult
- ExtensionRegistryPublishExtensionResult
- HiddenChangesetSpec
- HiddenExternalChangeset
- VirtualFile

It doesn't yet remove the relevant resolvers for those types. That will
be done in a later commit once we confirm these can be removed.

Context: I came across DiffSearchResult and noticed it was unused. I
then cooked up this little script to find all the unused types:

```shellsession
  (
      for t in $(awk '/^(type|enum|interface|union)/ { print $2 }' cmd/frontend/graphqlbackend/schema.graphql); do
          echo -n "$t"
          egrep "\b$t\b" cmd/frontend/graphqlbackend/schema.graphql | wc -l
      done
  ) | grep ' 1$' | sort | awk '{print $1}'
```

2020-10-01 07:07 UTC, keegancsmith commented
@sourcegraph/campaigns the majority of types seem to be campaigns related. Can you confirm they are safe to remove?

I'm not sure who is best to comment on the extension registry or setting types, so @sqs I think you originally wrote this stuff. Safe to remove?

2020-10-01 07:11 UTC, mrnugget requested changes
I don't think the assumption "if the type is not mentioned anywhere else in the schema it can be removed" is valid.

`HiddenChangesetSpec` and `VisibleChangesetSpec`, for example, both implement the `ChangesetSpec` and `Node` interfaces. Both are not mentioned explicitly because `ChangesetSpec` is used instead. Then you do a `... on VisibleChangesetSpec` in the query/mutation.

Example:

https://github.com/sourcegraph/sourcegraph/blob/7f1348b3407e56c33237c294c4ff09383a3ac69d/dev/reconciler-test-script/main.go#L155-L162

2020-10-01 07:21 UTC, keegancsmith commented
Nice, those were the ones I was most unsure of since when I grep for them they have a lot of hits. I suppose most of the other types we use this pattern we do `type foo = bar | baz` so the grep works. I'll update.

2020-10-01 07:21 UTC, sqs commented on cmd/frontend/graphqlbackend/schema.graphql
> -type ExtensionRegistryPublishExtensionResult {
https://github.com/sourcegraph/sourcegraph/pull/14327

2020-10-01 07:24 UTC, sqs commented on cmd/frontend/graphqlbackend/schema.graphql
> -type DefaultSettings implements SettingsSubject {
This does seem to be used: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+DefaultSettings+&patternType=regexp&case=yes

2020-10-01 07:27 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> -type VirtualFile implements File2 {
Reasonably sure that this is also used. But cc @eseliger because he knows.

2020-10-01 07:28 UTC, sqs commented
Commented on the 2 I know about.

2020-10-01 07:28 UTC, sqs commented
Commented on the 2 I know about.

2020-10-01 07:32 UTC, keegancsmith commented
haha well that generated some lively discussion quickly :) 

I improved my shell script to exclude mentions of `on $t`, but that misses things like DefaultSettings. The better solution is likely using type information in our graphql-go/graphql to decide which resolvers are never reached from the root. I'm gonna update this to be much more minimal and on types which seem to actually not be used.

For reference here is the updated shell script which checks for on:


```bash
(
    for t in $(awk '/^(type|enum|interface|union)/ { print $2 }' cmd/frontend/graphqlbackend/schema.graphql); do
        echo -n "$t"
        egrep "\b$t\b" cmd/frontend/graphqlbackend/schema.graphql | wc -l
    done
) | grep ' 1$' | sort | awk '{print $1}' | while read t; do
    git grep -q "\bon $t\b" || echo "$t"
done
```

2020-10-01 07:32 UTC, closed without merging

2020-10-01 07:37 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/schema.graphql
> -type VirtualFile implements File2 {
This one is weird, because I can only see references to it in test fixtures. https://sourcegraph.com/search?q=repo:github.com/sourcegraph+%5CbVirtualFile%5Cb&patternType=regexp

2020-10-12 14:53 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> -type VirtualFile implements File2 {
Yes it is, but we never fetch it directly, we fetch File2, and `__typename` and then check what we got back. But since we only fetch properties on `the `File2` interface, we don't need to specify the implementing entity. Hence, it's not mentioned, but still required to exist :)