repogroup: add icon styles, give cncf logo some margin
sourcegraph/sourcegraph pull request #14427
Opened 2020-10-06 00:07 UTC by bobheadxi

This is really minor, but since the CNCF logo is a square and there's no margin, it feels ever so slightly too close to the text. This is a quick hack to add a bit of a margin to this logo, but feel free to close with a better implementation :)  

![image](https://user-images.githubusercontent.com/23356519/95144187-9d4f8080-07aa-11eb-9ea8-06bab7ac3d93.png)

2020-10-06 14:24 UTC, poojaj-tech approved these changes
LGTM @bobheadxi! Thanks for improving the style 🎉

Adding @limitedmage in case she had any feedback.

2020-10-06 17:39 UTC, limitedmage requested changes
I'm thinking all logos should have this margin, not just CNCF. Can you modify this style in `web/src/repogroups/RepogroupPage.scss` in block `&__logo` instead?

2020-10-07 02:13 UTC, bobheadxi commented
@limitedmage made the change!

2020-10-07 18:10 UTC, limitedmage approved these changes

2020-10-07 18:10 UTC, limitedmage commented on web/src/repogroups/RepogroupPage.scss
> +        margin: 8px;
Can you use rem instead of pixels? 
```suggestion
        margin: 0.5rem;
```

2020-10-07 18:12 UTC, limitedmage commented on web/src/repogroups/RepogroupPage.scss
> +        margin: 8px;
Alternatively, you can use a bootstrap margin class `mr-2`.
https://about.sourcegraph.com/handbook/engineering/web/styling#spacing

2020-10-08 03:07 UTC, bobheadxi commented
TIL about chromatic 🤯 changes look good:

![image](https://user-images.githubusercontent.com/23356519/95410388-68802c80-0956-11eb-8cde-413a79d5ce06.png)

2020-10-08 03:07 UTC, merged

2020-10-08 03:07 UTC, bobheadxi commented
Thanks for the reviews @limitedmage @poojaj-tech !