docs: update search assets to work on dark background
sourcegraph/sourcegraph pull request #14932
Opened 2020-10-21 01:56 UTC by rvantonder

Closes #14365.

Renders correctly now:

![Screen Shot 2020-10-20 at 6 48 18 PM](https://user-images.githubusercontent.com/888624/96663585-cb35d880-1305-11eb-8cd1-e2a8868c1a22.png)

![Screen Shot 2020-10-20 at 6 55 01 PM](https://user-images.githubusercontent.com/888624/96663596-ce30c900-1305-11eb-8393-331c2440a3f1.png)

2020-10-21 04:31 UTC, christinaforney requested changes
This is awesome! Unfortunately it looks like light mode is broken now: 
![image](https://user-images.githubusercontent.com/1559622/96673550-9b91cb00-131b-11eb-84ed-ec2b1a881987.png)

2020-10-21 04:31 UTC, christinaforney commented on doc/code_search/reference/language.md
> +                </td>
I think this is an extra closing `</td>`

2020-10-21 04:34 UTC, sqs commented
You could try using CSS `filter: brightness(N%)` and maybe `hue-rotate(180deg)` too to make a white-foreground PNG dark in the light theme, without needing to upload duplicate images.

2020-10-21 04:39 UTC, rvantonder commented
Ah, thanks for catching @christinaforney, I assumed (wrongly) the docs are only in dark mode now since we only had one theme before. I'll figure out a solution to make this work for both. 

FWIW I tried `invert(100%)` before changing the assets but that would only invert the non-transparent part of the PNGs and not apply to the borders. I'll play around.

2020-10-21 22:31 UTC, rvantonder commented
@christinaforney I fixed things to work in dark and light mode. 

Got `invert(100%)` working for the toggle PNGs so I don't need extra dark versions, but doing the same for the railroad assets  is just a big pain and much easier to just override.

2020-10-23 06:18 UTC, stefanhengl approved these changes

2020-10-23 06:41 UTC, rvantonder commented
@christinaforney feel free to leave post merge feedback if any

2020-10-23 06:41 UTC, merged

2020-10-23 13:51 UTC, christinaforney commented
Looks good!