ci: add upgrade test
sourcegraph/sourcegraph pull request #14974
Opened 2020-10-22 08:00 UTC by bobheadxi

Closes https://github.com/sourcegraph/sourcegraph/issues/13877

2020-10-22 08:47 UTC, bobheadxi commented
@davejrt tagging you for review in case you had any immediate thoughts - it doesn't seem to be working right now, but it seems your e2e stuff (which I based the upgrade tests on) isn't either 😢 I'll circle back to this after the weekend

2020-10-22 11:49 UTC, davejrt commented
Yeah there are a few things I need to fix here. I'll get them into `main` and let you know so you can rebase.

2020-11-04 15:48 UTC, pecigonzalo commented on .buildkite/pipeline.qa.yml
> +- label: ':docker::arrow_double_up:'
```suggestion
- label: ':docker::arrow_double_up:'
  env:
    VAGRANT_SERVICE_ACCOUNT: buildkite@sourcegraph-ci.iam.gserviceaccount.com
```

2020-11-06 16:21 UTC, bobheadxi commented
IT'S GREEEEEEEN

![image](https://user-images.githubusercontent.com/23356519/98389502-1b939100-208f-11eb-95a4-9c5800067a2c.png)

2020-11-06 16:26 UTC, bobheadxi commented
cc @davejrt would appreciate a review on this!

2020-11-09 11:53 UTC, pecigonzalo requested changes
LGTM, but is there a test run of this to review? (maybe not possible)

2020-11-09 11:53 UTC, pecigonzalo commented on enterprise/dev/ci/ci/helpers.go
> +		c.branch == "ci/sourcegraph-upgrade" // TODO: remove
When should this be removed?

2020-11-09 11:53 UTC, pecigonzalo approved these changes
Sorry, intended to approve with comments.

2020-11-09 12:06 UTC, bobheadxi commented on enterprise/dev/ci/ci/helpers.go
> +		c.branch == "ci/sourcegraph-upgrade" // TODO: remove
> is there a test run of this to review? (maybe not possible)

Yep! This line of code that I will remove after review (hopefully from @davejrt at least) enables the QA run on this branch:

![image](https://user-images.githubusercontent.com/23356519/98539201-e70a1a00-22c6-11eb-9ed5-95cbb2087705.png)

The output seems similar to the main QA test - there is one failing test that does not fail the build, but it seems it is present in both so I assume it is covered by one of the other issues. Maybe @davejrt can clarify if this is expected?

2020-11-09 12:26 UTC, pecigonzalo commented on enterprise/dev/ci/ci/helpers.go
> +		c.branch == "ci/sourcegraph-upgrade" // TODO: remove
Nice!
I found the following, maybe they are mock values but please review https://buildkite.com/sourcegraph/qa/builds/310#cf68535d-cff5-481a-aea5-64cb3c3e9fd8/48-920

2020-11-09 12:35 UTC, bobheadxi commented on enterprise/dev/ci/ci/helpers.go
> +		c.branch == "ci/sourcegraph-upgrade" // TODO: remove
This comes from some setup I copied over from the existing QA pipeline I think, since it gets output there as well: [example from qa pipeline @ `main`](https://buildkite.com/sourcegraph/qa/builds/321#aa960b74-bacb-4df2-8fe0-0e30721f9856/33-894)

2020-11-09 12:36 UTC, bobheadxi commented on enterprise/dev/ci/ci/helpers.go
> +		c.branch == "ci/sourcegraph-upgrade" // TODO: remove
It seems to come from when we run `source /root/.profile`

2020-11-09 20:55 UTC, pecigonzalo commented on enterprise/dev/ci/ci/helpers.go
> +		c.branch == "ci/sourcegraph-upgrade" // TODO: remove
We might need to `set +x` when loading envs, this could leak a number of tokens otherwise.

2020-11-10 00:56 UTC, bobheadxi commented on enterprise/dev/ci/ci/helpers.go
> +		c.branch == "ci/sourcegraph-upgrade" // TODO: remove
Hm, tried to in [`e3fd640` (#14974)](https://github.com/sourcegraph/sourcegraph/pull/14974/commits/e3fd6401a0edb79c81c55c94aa0d812675a110f5) and got mysterious error: https://buildkite.com/sourcegraph/qa/builds/349#5ea8c4ce-6792-4343-bc8d-9c41d55139d8/83-187

```
sourcegraph-upgrade: + set +x
--
  | sourcegraph-upgrade: mesg: ttyname failed: Inappropriate ioctl for device
  | sourcegraph-upgrade: npm
  | sourcegraph-upgrade:
  | sourcegraph-upgrade: WARN npm npm does not support Node.js v14.7.0
  | sourcegraph-upgrade: npm WARN npm
  | sourcegraph-upgrade:  You should probably upgrade to a newer version of node as we
  | sourcegraph-upgrade: npm
  | sourcegraph-upgrade:  WARN npm can't make any promises that npm will work with this version.
  | sourcegraph-upgrade: npm
  | sourcegraph-upgrade: WARN
  | sourcegraph-upgrade:
  | sourcegraph-upgrade: npm
  | sourcegraph-upgrade:  Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
  | sourcegraph-upgrade: npm
  | sourcegraph-upgrade: WARN
  | sourcegraph-upgrade: npm You can find the latest version at https://nodejs.org/
```

Will investigate more later

2020-11-10 02:18 UTC, daxmc99 approved these changes

2020-11-10 02:19 UTC, daxmc99 commented on .buildkite/pipeline.qa.yml
> +- label: ':docker::arrow_right::chromium:'
I think we are trying to also add descriptions

2020-11-10 12:33 UTC, bobheadxi commented on .buildkite/pipeline.qa.yml
> +- label: ':docker::arrow_right::chromium:'
Labels for everyone! [`18f47ba` (#14974)](https://github.com/sourcegraph/sourcegraph/pull/14974/commits/18f47bae86ace67ce1be12af805d4173ece93cd2)

2020-11-10 13:09 UTC, davejrt approved these changes

2020-11-10 13:59 UTC, merged

2020-11-13 04:05 UTC, daxmc99 commented on test/setup-deps.sh
> +yes | gcloud auth configure-docker
🤨