Fixing a security hole on the host check.
sourcegraph/sourcegraph pull request #15146
Opened 2020-10-29 09:06 UTC by chayim

Previously we were checking only for things ending in sourcegraph.com,
meaning someone could register any matching domain such as
thisissourcegraph.com.

2020-10-29 10:58 UTC, felixfbecker requested changes

2020-10-29 10:58 UTC, felixfbecker commented on client/browser/src/browser-extension/scripts/optionsPage.main.tsx
> +    const showSourcegraphCloudAlert = currentTabStatus?.status.host.endsWith('.sourcegraph.com')
I actually think this should be a precise comparison, not a subhost check. This check would now fail for `https://sourcegraph.com`, which is actually the only case we want to show the "You're on Sourcegraph Cloud alert". @marekweb any reason we should show the alert for docs.sourcegraph.com, about etc too?

I wouldn't call it a "security hole" though. It just means we show an alert saying "you don't need to grant us permissions here, all good" on pages that are not sourcegraph.com.

2020-10-29 22:46 UTC, marekweb commented on client/browser/src/browser-extension/scripts/optionsPage.main.tsx
> +    const showSourcegraphCloudAlert = currentTabStatus?.status.host.endsWith('.sourcegraph.com')
I agree that this could be changed to be an exact comparison of the host with `sourcegraph.com`. I don't think we need to show the alert for any subdomains of sourcegraph.com.

2020-11-01 09:24 UTC, chayim commented on client/browser/src/browser-extension/scripts/optionsPage.main.tsx
> +    const showSourcegraphCloudAlert = currentTabStatus?.status.host.endsWith('.sourcegraph.com')
Thanks for the context! This means that the change will now replace the period I added with a forward-slash.

2021-03-29 06:04 UTC, closed without merging