Allow users to create campaigns
sourcegraph/sourcegraph pull request #15436
Opened 2020-11-05 10:58 UTC by mrnugget

2020-11-06 15:13 UTC, eseliger requested changes
LGTM, requesting changes so merging is blocked but it really  means approved so once we’re there feel free to dismiss my review. If that makes sense 😅

2020-11-06 15:13 UTC, mrnugget commented
> LGTM, requesting changes so merging is blocked
Good idea!

2020-11-06 21:21 UTC, chrispine approved these changes
Nice, thanks for this

2020-11-07 03:49 UTC, LawnGnome approved these changes

2020-11-09 12:42 UTC, eseliger approved these changes

2020-11-09 12:43 UTC, merged