db: add user credentials table and CRUD (ish) methods
sourcegraph/sourcegraph pull request #15512
Opened 2020-11-06 02:36 UTC by LawnGnome

This splits the original `campaign_user_credentials` (née `campaign_user_tokens`) table out from the draft #15301 PR, and refactors the Go types and methods to fit into `internal/db`, since this is now going to be a more generic table so others can reuse it at a later stage.

It might be easiest to read this in conjunction with the [high level plan for campaign user token support](https://docs.google.com/document/d/1AM37p6WoHh01R403BYnqguQQgeXEaBYEvd6s_ldTOAA/edit?usp=sharing), if you haven't already, since that should fill in most of the blanks on usage.

Random notes on design decisions that might be considered "interesting":

* Although records can be uniquely identified by `(domain, user_id, external_service_type, external_service_id)`, a `bigserial` field called `id` is still present to make addressing these records through GraphQL easier.
* Rather than separating create and update, the `userCredentials` type exposes an `Upsert` method, given the unique identifier noted above and the fact there's only one actual field that depends on it. This should align better with how we'll be using these records in practice.

This is also my first foray into the `secret` package, so if I'm misusing its encrypted field capabilities, now would be a good time to know that. :grimacing:

2020-11-06 09:40 UTC, mrnugget reviewed
The code looks fine to me, but I'm honestly surprised to see that this is now in `internal/db` and not in `enterprise/internal/campaigns`.

That does mean that we can't use it in transactions in our reconciler, because everything here uses the `dbconn.Global` connection.

That's not a blocker, but it's also not great that we don't have transactional guarantees when using credentials.

> since this is now going to be a more generic table so others can reuse it at a later stage.

Didn't we say we don't know how and when others will use reuse it at a later stage? And didn't we say that we only support simple `token string` for now?

With this we now need to map the the `Credential string` we get from the user to a `OAuthBearerToken` (GitHub and BitbucketServer) or `GitLabSudoableToken` in the resolver, right?

When and how are we going to use the others?

- `credTypeOAuthClient`
- `credTypeBasicAuth`
- `bitbucketserver.SudoableOAuthClient`


Edit: just to be clear, none of my concerns here are blockers, because I don't think we have time to redo this, but I'm surprised.

2020-11-06 09:57 UTC, mrnugget commented on internal/db/user_credentials.go
> +		t = credTypeGitLabSudoableToken
Which ones of these are usable in a git remote URL?

2020-11-06 17:34 UTC, eseliger approved these changes

2020-11-06 17:34 UTC, eseliger commented on internal/db/user_credentials.go
> +type userCredentialNotFoundErr struct{ args []interface{} }
I think this should be exported? And I think it should fulfill the notFounder interface.

2020-11-06 17:34 UTC, eseliger commented on internal/db/user_credentials.go
> +func (*userCredentials) List(ctx context.Context, opts UserCredentialsListOpts) ([]*UserCredential, int, error) {
I could imagine an IDs option could be helpful, but I'm not 1000000% sure yet how I'll end up using it in the graphql layer.

2020-11-06 17:34 UTC, eseliger commented on internal/db/user_credentials.go
> +		updated_at = excluded.updated_at
Could we make this a parameter and have a separate `Create` method? 
For a UI action that says "Add", I would expect it to fail and not upsert if something in the background changed while I entered data.

2020-11-06 18:37 UTC, LawnGnome commented on internal/db/user_credentials.go
> +		t = credTypeGitLabSudoableToken
We talked about this in person, but to record the answer: it depends, but for now only the `OAuthBearerToken` will be used, since that's all we need for the GA deliverable.

2020-11-06 18:38 UTC, LawnGnome commented on internal/db/user_credentials.go
> +func (*userCredentials) List(ctx context.Context, opts UserCredentialsListOpts) ([]*UserCredential, int, error) {
Let's leave it out for now, but it should be easy to add later if needed.

2020-11-06 18:40 UTC, LawnGnome commented on internal/db/user_credentials.go
> +type userCredentialNotFoundErr struct{ args []interface{} }
The `Users` equivalent also isn't exported, but it felt weird to me too. I'll make both of those changes.

2020-11-06 18:41 UTC, ElizabethStirling requested changes
I'd like to see the authorization checks for these CRUD methods in `user_credentials.go`, in order to make it impossible to accidentally use them without providing proper authorization. Additionally, what authorization scheme do we want to implement? I could see only letting user X touch the credentials belonging to user X as a reasonable solution, but if we need to allow administrators to modify the tokens of their users, I could see it getting a bit hairy.

2020-11-06 18:43 UTC, ElizabethStirling commented
cc @chayim, @daxmc99, could one of you take a look at the usage of the secrets package here? I want to verify that I'm not missing something.

2020-11-06 18:49 UTC, LawnGnome commented
> I'd like to see the authorization checks for these CRUD methods in `user_credentials.go`, in order to make it impossible to accidentally use them without providing proper authorization.

Is there an existing pattern for this that I could follow?

If not, I presume this would take the form of requiring a `User` to be passed into the public interface?

> Additionally, what authorization scheme do we want to implement?

For now, it's the simple case:

* The user the credential belongs to may perform any action on that credential.

In the future:

* Admins may manage credentials for anyone. I would presume this would include obscuring the actual credential for a non-owning users when `Get*` and `List` are invoked.

2020-11-06 18:50 UTC, LawnGnome commented on internal/db/user_credentials.go
> +		updated_at = excluded.updated_at
Sure. Would you also prefer a regular `Update`, and we just get rid of the `Upsert` altogether?

2020-11-06 19:03 UTC, ElizabethStirling commented
One case where we verify that the requestor is the current user or the site admin is in `user.go`

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/user.go#L99:20
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/site_admin.go#L69:6

I don't think we have a specific case for just checking that the user making the call is the current user, but I don't think it would be too difficult to just break out the "is current user" check in `CheckSiteAdminOrSameUser`, and have `CheckSiteAdminOrSameUser` just call that.

2020-11-06 19:03 UTC, eseliger commented on internal/db/user_credentials_test.go
> +	if have := err.NotFound(); !have {
Maybe use `errcode.IsNotFound(err)` here? That's what I was gonna use to check it

2020-11-06 19:05 UTC, LawnGnome commented on internal/db/user_credentials_test.go
> +	if have := err.NotFound(); !have {
Yeah, that's probably the extra context I needed. Thanks!

2020-11-06 19:06 UTC, mrnugget commented
@ElizabethStirling @LawnGnome FYI we already use those checks in our `campaigns/resolvers`: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+CurrentUser+f:campaigns/resolvers+-f:_test&patternType=regexp

And in our `campaigns.Service`: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+backend.Check+f:campaigns/service+-f:_test&patternType=regexp

I think we should use those same checks in the resolvers that @eseliger is working on.

2020-11-06 19:06 UTC, eseliger commented on internal/db/user_credentials.go
> +		updated_at = excluded.updated_at
Whatever is easier, for now I only need create. We've decided to cut scope and not allow update from the UI / API for now since it's easy to remove / add again (instead of update directly) for now.

2020-11-06 19:08 UTC, LawnGnome commented
> @ElizabethStirling @LawnGnome FYI we already use those checks in our `campaigns/resolvers`: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+CurrentUser+f:campaigns/resolvers+-f:_test&patternType=regexp
> 
> And in our `campaigns.Service`: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+backend.Check+f:campaigns/service+-f:_test&patternType=regexp
> 
> I think we should use those same checks in the resolvers that @eseliger is working on.

That was also my expectation, and I'm sorry for not being clear enough in my question to @ElizabethStirling: is adding authorisation checks at the database layer something we're planning to start as a best practice, or something we've already started doing?

2020-11-06 19:08 UTC, eseliger commented
Yes. Additionally, it's not possible to anywhere retrieve the credential through an API. We just store and check if _any_ entry is there, but don't even touch the credentials column in the graphql layer.

2020-11-06 19:09 UTC, LawnGnome commented on internal/db/user_credentials.go
> +		updated_at = excluded.updated_at
OK. I'll transform `Upsert` into `Create` for now, unless you need both.

2020-11-06 19:10 UTC, ElizabethStirling commented
If that's our pattern for how we implement AuthZ checks, I'm fine with that, so long as it's an intentional decision.
_Personally_, I'd like to consider AuthZ at the database layer, but would need to noodle on that more. Will add it to the security team's discussion and approve to unblock. Though, would still recommend you wait for a sanity check from @daxmc99 on the secrets package, since I haven't touched it nearly as much.

2020-11-06 19:10 UTC, ElizabethStirling approved these changes
Approved RE: AuthZ discussion.

2020-11-06 19:10 UTC, LawnGnome commented
> Will add it to the security team's discussion and approve to unblock. Though, would still recommend you wait for a sanity check from @daxmc99 on the secrets package, since I haven't touched it nearly as much.

Perfect, thanks!

2020-11-06 19:15 UTC, LawnGnome commented on internal/db/user_credentials.go
> +		updated_at = excluded.updated_at
Done, but if you want `Upsert` back, just let me know and I'll make the appropriate ~copy/paste~ highly technical refactor that only a true professional could make.

2020-11-06 19:31 UTC, daxmc99 commented
Some quick notes
https://github.com/sourcegraph/sourcegraph/issues/14166 is the tracking issue for RFC-214. This work isn't complete yet so the secrets package currently does nothing.

2020-11-06 19:55 UTC, daxmc99 approved these changes

2020-11-06 19:55 UTC, daxmc99 commented on internal/db/user_credentials.go
> +// 🐉 This marks the end of the public API. Beyond here are dragons.
🐉

2020-11-06 19:55 UTC, daxmc99 commented on internal/db/user_credentials_test.go
> +	// us over the hump.
TIL

2020-11-06 19:55 UTC, daxmc99 commented on internal/db/user_credentials.go
> +		&secret.StringValue{S: &raw},
Looks good, we actually do run with encryption enabled in tests (see main_test.go in this pkg) so my only suggestion would be to add a sanity test to ensure what you put into the test db != what resides in the db at rest

2020-11-06 19:55 UTC, daxmc99 commented on internal/db/user_credentials.go
> +	creds := []*UserCredential{}
Maybe nit?
```suggestion
	var creds []*UserCredential
```

2020-11-06 19:57 UTC, LawnGnome commented on internal/db/user_credentials.go
> +		&secret.StringValue{S: &raw},
That's a good call. I'll add a test for that, thanks!

2020-11-06 19:58 UTC, daxmc99 commented
Prior art viewable here (and other places scattered around `db` pkg 
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40aharvey/credential-table+file:%5Einternal/db/external_services%5C.go+secret&patternType=literal

2020-11-06 19:59 UTC, LawnGnome commented
> Prior art viewable here (and other places scattered around `db` pkg )

Thanks! I'd been cribbing pretty heavily from elsewhere, but I definitely still wanted a set of experienced eyes to look at this.

2020-11-06 20:13 UTC, LawnGnome commented
> The code looks fine to me, but I'm honestly surprised to see that this is now in `internal/db` and not in `enterprise/internal/campaigns`.

@mrnugget and I talked about this on a Zoom call earlier. I'll try to capture the outcome of that call below.

The short version is that we're going ahead with this PR, although we have more to discuss later.

> That does mean that we can't use it in transactions in our reconciler, because everything here uses the `dbconn.Global` connection.
> 
> That's not a blocker, but it's also not great that we don't have transactional guarantees when using credentials.

We agreed it wasn't a blocker for now.

> Didn't we say we don't know how and when others will use reuse it at a later stage? And didn't we say that we only support simple `token string` for now?

That is indeed all we're supporting right now.

There was a broader discussion around scoping and tech debt that I won't reproduce here, mostly because I don't want to put words in Thorsten's mouth, and also because I think this will be a follow up conversation in our sprint retro in a couple of weeks.

> With this we now need to map the the `Credential string` we get from the user to a `OAuthBearerToken` (GitHub and BitbucketServer) or `GitLabSudoableToken` in the resolver, right?

That is correct, except that GitLab will also use the `OAuthBearerToken`, since campaigns do not require `sudo` capabilities.

> When and how are we going to use the others?

In the short term, we're not, since our GA deliverable is token support only.

2020-11-06 20:19 UTC, merged

2020-11-09 06:23 UTC, unknwon reviewed
Very high-quality piece of code :)

2020-11-09 06:23 UTC, unknwon commented on internal/db/user_credentials.go
> +}
TIL! No more `fmt.Sprintf` for dynamic column names!

2020-11-09 06:23 UTC, unknwon commented on internal/db/user_credentials.go
> +func (*userCredentials) GetByID(ctx context.Context, id int64) (*UserCredential, error) {
What @ElizabethStirling has brought up about authz on DB layer (via `CheckSiteAdminOrSameUser`) is something I would ask for too. It does worry me that when we have more call sites of these methods other than campaigns code, we would easily forget to do authz. 

(I believe it is OK to have authz enforced on both resolvers and DB layers)

2020-11-09 06:23 UTC, unknwon commented on internal/db/user_credentials.go
> +func (*userCredentials) Delete(ctx context.Context, id int64) error {
I hope there are at least basic docstrings for these methods :)

2020-11-13 06:15 UTC, unknwon commented on internal/db/user_credentials.go
> +func (*userCredentials) GetByID(ctx context.Context, id int64) (*UserCredential, error) {
Pump up for @LawnGnome in case you missed :)

2020-11-13 07:38 UTC, LawnGnome commented on internal/db/user_credentials.go
> +func (*userCredentials) GetByID(ctx context.Context, id int64) (*UserCredential, error) {
Sorry, I was out until yesterday and failed to get through my GitHub notifications today. I promise to loop back to this tomorrow. 🙂

2020-11-13 22:11 UTC, LawnGnome commented on internal/db/user_credentials.go
> +func (*userCredentials) GetByID(ctx context.Context, id int64) (*UserCredential, error) {
I've filed https://github.com/sourcegraph/sourcegraph/issues/15770 for us to track this.

2020-11-13 22:23 UTC, LawnGnome commented on internal/db/user_credentials.go
> +func (*userCredentials) Delete(ctx context.Context, id int64) error {
There will be! #15771

2020-11-16 07:06 UTC, unknwon commented on internal/db/user_credentials.go
> +func (*userCredentials) GetByID(ctx context.Context, id int64) (*UserCredential, error) {
Thanks for following up 👍