Fa/create monitor
sourcegraph/sourcegraph pull request #15575
Opened 2020-11-09 11:42 UTC by attfarhan

Addresses https://github.com/sourcegraph/sourcegraph/issues/15415. This adds the basic create monitor page. It does not yet send the mutation to create a monitor, nor does it advance the form based on form submissions yet. These will happen in stacked PRs.

Figma: https://www.figma.com/file/Krh7HoQi0GFxtO2k399ZQ6/RFC-227-%E2%80%93%C2%A0Code-monitoring-actions-%26-notifications?node-id=2116%3A70

2020-11-09 19:13 UTC, limitedmage requested changes

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                            <a href="" target="_blank" rel="noopener">
Issue with TODO comment needed here too to populate this link.

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                            What other events would you like to monitor?{' '}
```suggestion
                            What other actions would you like to do?{' '}
```
To match Figma

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                <a href="" target="_blank" rel="noopener">
Issue with TODO comment needed here too to populate this link.

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                        </button>
Buttons have no spacing between them:
![image](https://user-images.githubusercontent.com/206864/98584664-1135ea80-227b-11eb-9c3e-263794a7e6d8.png)

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                        <Toggle title="Active" value={active} onToggle={toggleActive} className="mr-2" /> Active
Missing description from Figma
![image](https://user-images.githubusercontent.com/206864/98584745-2d398c00-227b-11eb-861b-9cc7f7a6b3da.png)

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                priority.
@quinnkeast Despite this text, looks like the current form design does NOT let the user customize delivery schedule or priority. Let's punt that for now and modify this text to match the current capabilities.

Can we add some designs for this so we can implement later? FYI @stefanhengl this might also require small changes in schema for schedule.

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                    </div>
I would consider removing this field until we support sending to other addresses, as right now it will only be sent the user's primary address. Thoughts on this @quinnkeast ?

2020-11-09 19:13 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                Code monitors watch your code for specific triggers and run actions in response. Learn more.
`Learn more` should be a link, we need a docs page for this. Please file an issue and add TODO comment. (All these docs pages issues I'm mentioning here can be a single issue in GitHub for simplicity)

2020-11-10 06:26 UTC, attfarhan commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                        </button>
I'm doing all interactions in a separate PR. This is just the basic UI.

2020-11-10 06:27 UTC, attfarhan commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                            Done
This is "Done" because this is the last _required_ step for creating a code monitor. Adding a trigger has "Continue" because it lets you advance to adding an action.

2020-11-10 09:34 UTC, attfarhan commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                    </div>
Yeah that makes sense 👍

2020-11-10 09:44 UTC, attfarhan commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                        Code monitors only support type:diff and type:commit search queries.
Used the bg-code class, differs from the colors in figma but it's the standard we use in our app. Cc @quinnkeast.

2020-11-10 09:52 UTC, attfarhan commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                Code monitors watch your code for specific triggers and run actions in response. Learn more.
Added all the docs and links to https://github.com/sourcegraph/sourcegraph/issues/15612.

2020-11-10 17:15 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                                        </button>
Sounds good!

2020-11-10 17:23 UTC, limitedmage reviewed
Looks great!

2020-11-10 17:23 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.scss
> +        background: $gray-10;
We should check if this is the same for both dark mode and light mode. I would prefer using a [theme-independent variable](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/branded/src/global-styles/colors.scss#L68) here

2020-11-11 03:41 UTC, attfarhan commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.scss
> +        background: $gray-10;
This actually doesn't do anything -- meant to remove this

2020-11-11 03:42 UTC, attfarhan commented
@limitedmage I'm going to merge this and create new PRs for the remaining functionality.

2020-11-11 03:43 UTC, limitedmage commented
> @limitedmage I'm going to merge this and create new PRs for the remaining functionality.

Yes, go ahead! Sorry, I approved with my last review but GitHub for some reason is still blocking :/

2020-11-11 03:59 UTC, merged

2020-11-25 13:01 UTC, quinnkeast commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                        <select className="form-control my-2 w-auto" disabled={true}>
@limitedmage I'm sorry, I missed this mention. I think it's worth having it visible so that the ownership is clear, but I agree there should be additional clarification.

We could update the subtext to:

>Event history and configuration will not be shared. Code monitoring currently only supports individual owners.

WDYT?

2020-11-30 19:05 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/CreateCodeMonitorPage.tsx
> +                        <select className="form-control my-2 w-auto" disabled={true}>
Sounds good to me! @attfarhan  can you add this the next time you modify this component?