Postgres grafana dashboards
sourcegraph/sourcegraph pull request #15641
Opened 2020-11-11 06:15 UTC by daxmc99

Part of https://github.com/sourcegraph/sourcegraph/issues/15029

TODO:
- [ ] Add dashboard for default db
- [ ] Add dashboard for code-intel db

2020-11-25 01:00 UTC, bobheadxi commented on monitoring/shared.go
> +var postgresVersion sharedObservable = func(dbName string, owner ObservableOwner) Observable {
why are these shared?

2020-11-30 19:31 UTC, daxmc99 commented on monitoring/shared.go
> +var postgresVersion sharedObservable = func(dbName string, owner ObservableOwner) Observable {
Dropped from shared

2020-12-01 11:43 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +	db        = "pgsql"
variables are scoped across the entire package, so these should be a bit descriptive:

```suggestion
	dbCodeintel   = "codeintel-db"
	dbSourcegraph = "pgsql"
```

(or something like that)

2020-12-01 11:43 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +	. "github.com/sourcegraph/sourcegraph/monitoring/monitoring"
```suggestion
	"github.com/sourcegraph/sourcegraph/monitoring/monitoring"
```

it's explicitly `monitoring` everywhere else, we should keep it that way for consistency, but also I feel it's better for discoverability (leads more directly to the new package documentation)

2020-12-02 00:10 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +	. "github.com/sourcegraph/sourcegraph/monitoring/monitoring"
Yeah, seeing how this is already the style. I would argue this might be a case when it is appropriate though since > 50% of lines need the import.

2020-12-02 07:11 UTC, bobheadxi approved these changes
nice!!

2020-12-02 07:11 UTC, bobheadxi commented on dev/pg_exporter/queries.yaml
> +pg_cache:
do we ship these queries with a standard sourcegraph distribution?

2020-12-02 07:11 UTC, bobheadxi commented on monitoring/monitoring/README.md
> +## func Generate
I think something went wrong with go generate here (is your go mod cache / vendor up to date?), CI is complaining as well

2020-12-02 18:34 UTC, daxmc99 commented on dev/pg_exporter/queries.yaml
> +pg_cache:
We will need to update our deployments with this file for pg_exporter to work with these queries

2020-12-02 19:43 UTC, daxmc99 commented on monitoring/monitoring/README.md
> +## func Generate
I dropped the change. I'm still not sure what is causing this. My local go mod is the same as master.

2020-12-03 11:48 UTC, bobheadxi commented on dev/pg_exporter/queries.yaml
> +pg_cache:
I think those will be important to have in place, otherwise these dashboards will probably end up blank on most deployments

2020-12-03 18:14 UTC, pecigonzalo commented on dev/pg_exporter/queries.yaml
> +pg_cache:
This file here is only for devs right? Im a bit confuse by this config being in the `dev/` folder

2020-12-03 18:15 UTC, daxmc99 commented on dev/pg_exporter/queries.yaml
> +pg_cache:
Yeah, this is just to develop locally with the new queries. This will require updates to our other deployments to support this.

2020-12-03 19:00 UTC, pecigonzalo commented
@daxmc99  where is the container configure for the deployments? I could not find a PR for it.

m asking as we could have most of `dev/pg_exporter/queries.yaml` be baked in the container if its static, and only mount any additional metrics we need for development. I believe it supports specifying a directory of configs instead of a file.

2020-12-03 19:21 UTC, daxmc99 commented
Yeah, we could bake those in. I opened a PR here
https://github.com/sourcegraph/deploy-sourcegraph/pull/1420

We currently don't build this image... which might be a reason in itself to bake this into the image

2020-12-08 07:28 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +							Description:       "transaction_durations",
```suggestion
							Description:       "transaction durations",
```

![image](https://user-images.githubusercontent.com/23356519/101453229-fc2ba480-3969-11eb-8f72-172b139916aa.png)

2020-12-08 07:29 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						Description:       "error scraping postgres exporter",
```suggestion
						Description:       "errors scraping postgres exporter",
```

2020-12-08 07:30 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						Critical:        monitoring.Alert().GreaterOrEqual(1).For(5 * time.Minute),
There are a few "status"-type metrics (such as `postgres_up`), but `postgres_up` uses `LessOrEqual(0)` while this uses `GreaterOrEqual(1)` - does this indicate migration success, or running migrations?

2020-12-08 07:30 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						Description:       "ratio of cache hits (should be 99%)",
```suggestion
						Description:       "ratio of cache hits",
```

2020-12-08 07:31 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
```suggestion
						PossibleSolutions: "Cache hit ratio should be 99%.",
```

(I'm not sure what someone would want to look at should this not be the case, might want to add it here)

2020-12-08 07:32 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
```suggestion
						PossibleSolutions: "none",
						PanelOptions:      monitoring.PanelOptions().Unit(monitoring.Percentage),
```

2020-12-08 07:33 UTC, bobheadxi approved these changes

2020-12-08 07:34 UTC, bobheadxi requested changes
Left some comments! Mostly to do with details about the dashboards (sorry about messy review)

2020-12-08 07:35 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
(I think should also make this query output a 0-100 value in this case)

2020-12-08 07:38 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
I think this is mostly for internal use. We should strive to keep this high otherwise we should add new indexes.

2020-12-08 07:40 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
Regardless, we should add a note here since we ship this to customers. I think adding new indexes is a valid possible solution, though since itl need action on our end maybe we could recommend admins open an issue?

2020-12-08 07:41 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						Critical:        monitoring.Alert().GreaterOrEqual(1).For(5 * time.Minute),
This is a bit obtuse. This is actually checking to see if the value of `dirty` is equal to 1. If it is, then the db is undergoing a migration. Long migrations can cause issues.

2020-12-08 07:45 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						Critical:        monitoring.Alert().GreaterOrEqual(1).For(5 * time.Minute),
Hm in that case, maybe call it `migration_in_progress` or something like that?

2020-12-08 08:03 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
That's a great idea!

2020-12-08 08:16 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
Why not `<1`? This comes from Postgres so we would need to change the scale in the Prometheus query.

2020-12-08 08:17 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						Critical:        monitoring.Alert().GreaterOrEqual(1).For(5 * time.Minute),
Done

2020-12-08 08:22 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
We do `* 100` and `.PanelOptions().Unit(monitoring.Percentage)` on quite a lot of our graphs:

https://sourcegraph.com/search?q=repo:%5Egithub.com/sourcegraph/sourcegraph%24+file:monitoring/.*+%7B:%5B_%5D%2C+PanelOptions:+monitoring.:%5B_%5D.Unit%28monitoring.Percentage%29%2C+:%5B_%5D%7D+count:999&patternType=structural

2020-12-08 08:45 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						PossibleSolutions: "none",
TIL, that looks straightforward

2020-12-08 08:46 UTC, daxmc99 commented
Thank you for the great review @bobheadxi! 🙇

2020-12-08 12:19 UTC, bobheadxi approved these changes
nice! some last minor nits, but not super important :)

2020-12-08 12:19 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +							" ensure that the migration has succeeded or contact Sourcegraph",
nit: is there documentation on how to check if migrations succeeded?

2020-12-08 12:19 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +						Query:           "avg(rate(pg_stat_database_blks_hit{datname!~\"template.*|postgres|cloudsqladmin\"}[5m]) / (rate(pg_stat_database_blks_hit{datname!~\"template.*|postgres|cloudsqladmin\"}[5m])
nit: you can use backticks here to avoid escaping

2020-12-08 12:19 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +							"to add additional indexes",
```suggestion
						PossibleSolutions: "Cache hit ratio should be at least 99%, please [open an issue](https://github.com/sourcegraph/sourcegraph/issues/new/choose) " +
							"to add additional indexes",
```

2020-12-08 17:52 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +							" ensure that the migration has succeeded or contact Sourcegraph",
The only way to check if a migration has succeeded is to check the table. I wouldn't want to provide this information here since clearing the 'dirty' value of the schema migrations table might appear to be a solution when it could cause data lose.

2020-12-08 17:53 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						Query:           "avg(rate(pg_stat_database_blks_hit{datname!~\"template.*|postgres|cloudsqladmin\"}[5m]) / (rate(pg_stat_database_blks_hit{datname!~\"template.*|postgres|cloudsqladmin\"}[5m])
Goland auto adds the escapes so I forget about these ha.

2020-12-10 00:58 UTC, daxmc99 commented
_Unfortunately, I realized that `pg_stat_statements` will likely require an update to our postgressql.conf we ship with our Postgres deployments. I decided to disable those for now and follow up in https://github.com/sourcegraph/sourcegraph/issues/13300

2020-12-10 01:00 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +						// TODO(Dax): Blocked by https://github.com/sourcegraph/sourcegraph/issues/13300,  need to enable `pg_stat_statements` in Postgres conf
Commented out for now

2020-12-10 01:03 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +							Description:     "schema migration status (where 0 is no migration in progress)",
Clarified description, we expect 0 here

2020-12-11 15:53 UTC, merged