Add GitHub webhook handlers to trigger permissions syncs for users and repos
sourcegraph/sourcegraph pull request #15709
Opened 2020-11-12 16:20 UTC by arussellsaw

This PR fixes https://github.com/sourcegraph/sourcegraph/issues/14917

❗ 🚧   WIP 🚨  ❗ 

TODO:
- [ ] Add Feature Flag checks to handlers
- [ ] Test that all events parse and update successfully
- [ ] Test that the permissions updates actually happen and change access/visibility

2020-11-12 16:26 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	r, err := backend.Repos.GetByName(ctx, api.RepoName("github.com/"+repo.GetFullName()))
this will throw a noisy error if the repo is nil, we should probably nil check and return quietly, or at least a sensible warning log

2020-11-12 16:26 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	accs, err := db.ExternalAccounts.List(ctx, db.ExternalAccountsListOptions{
same comment as nil repos here, this will cause an unintuitive error, so we should nil check and warning log here

2020-11-12 16:26 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	switch e := payload.(type) {
i have a feeling this is missing a 'userGetter interface { GetUser() *gh.User }` type

2020-11-12 16:29 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	log15.Warn(fmt.Sprintf("scheduleUserUpdate: Dispatching permissions update for user %d", accs[0].UserID))
this should not be a warning

2020-11-12 16:29 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	log15.Warn("scheduleRepoUpdate: Dispatching permissions update for repo %s", repo.GetFullName())
this should not be a warning

2020-11-12 16:29 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	log15.Warn(fmt.Sprintf("handleGithubUserAuthzEvent: Got github event %T", payload))
this should not be a warning

2020-11-12 16:30 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	log15.Warn(fmt.Sprintf("handleGithubRepoAuthzEvent: Got github event %T", payload))
this should not be a warning

2020-11-12 16:30 UTC, arussellsaw commented on cmd/frontend/webhooks/github_webhooks.go
> +	log15.Warn(eventType)
leftover debugging, delete

2020-11-12 16:42 UTC, arussellsaw commented
this will all need updating when https://github.com/sourcegraph/sourcegraph/pull/15530 merges as well cc @asdine

2020-11-13 08:10 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +func handleGithubRepoAuthzEvent(ctx context.Context, extSvc *repos.ExternalService, payload interface{}) error {
nit:
```suggestion
func handleGitHubRepoAuthzEvent(ctx context.Context, extSvc *repos.ExternalService, payload interface{}) error {
```

2020-11-13 08:10 UTC, unknwon commented on doc/admin/repo/permissions.md
> +* [public](https://developer.github.com/webhooks/event-payloads/#public)
```suggestion

#### GitHub

* [public](https://developer.github.com/webhooks/event-payloads/#public)
```

Our current Markdown render is strict on separating lines.

2020-11-13 13:56 UTC, arussellsaw commented
I've been able to test making a repo private removing that repo from other users, but at the moment i'm trying to test the membership add event, but for some reason my local instance is unable to find the repo by name, despite me being able to see the repo in the repos and external_service_repos table with the name mentioned in the error

2020-11-13 15:31 UTC, arussellsaw commented
i've fixed the query, it now uses internal actor and is able to see private repos ( https://sourcegraph.slack.com/archives/C07KZF47K/p1605279350000400 ) , however it doesn't change visibility for users added as collaborators on the repo, i think perhaps i need to set up github as an authz provider for that to work? cc @unknwon

2020-11-13 16:30 UTC, arussellsaw commented
this is tested working on my local machine! I was able to make a repo private and have my test user no longer able to query it instantly, then add that user as a collaborator and regain the ability to query instantly! 🎉  🎉

2020-11-13 16:42 UTC, tsenart commented
> this is tested working on my local machine! I was able to make a repo private and have my test user no longer able to query it instantly, then add that user as a collaborator and regain the ability to query instantly! 🎉 🎉

Damn! Good stuff!

2020-11-13 16:48 UTC, tsenart approved these changes
Approving to unblock, but you should add more weight to @flying-robot and @unknwon's reviews.

2020-11-13 16:48 UTC, tsenart commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	r, err := backend.Repos.GetByName(ctx, api.RepoName("github.com/"+repo.GetFullName()))
Could we use the `db.Repos` directly? I don't think the extra logic in `backend.Repos.GetByName` applies here.

2020-11-16 04:30 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	// 🚨 SECURITY: we want to be able to find any private repo here, so set internal actor
Suggestion: Make this warning as part of the function docstring, so the callers of this function would be warned.

2020-11-16 07:46 UTC, unknwon requested changes
Request changes to be sure I'm re-requested review after addressing the feedback.

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/httpapi.go
> +		gh := webhooks.GithubWebhook{
nit:
```suggestion
		gh := webhooks.GitHubWebhook{
```

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	"github.com/sourcegraph/sourcegraph/cmd/frontend/backend"
It is cleaner to place stdlib, third-party libs and our packages in different groups.

```suggestion
	"fmt"

	gh "github.com/google/go-github/v28/github"
	"github.com/inconshreveable/log15"

	"github.com/sourcegraph/sourcegraph/cmd/frontend/backend"
```

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +// handleGithubRepoAuthzEvent handles any github event containing a repository field, and enqueues the contained
```suggestion
// handleGitHubRepoAuthzEvent handles any GitHub event containing a repository field, and enqueues the contained
```

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +// repo for permissions synchronisation
nit:
```suggestion
// repo for permissions synchronisation.
```

Docstrings for signatures should be sentences (with periods).

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	if !conf.Get().ExperimentalFeatures.EnablePermissionsWebhooks {
Just a sanity check: what happens if there is no ExperimentalFeatures configed at all in the site config, would this panic?


```suggestion
	if !conf.ExperimentalFeatures().ExperimentalFeatures.EnablePermissionsWebhooks {
```


https://github.com/sourcegraph/sourcegraph/blob/1d9e6f86d61c66e7c45e84374574850e29953d95/internal/conf/computed.go#L291-L296

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	log15.Debug(fmt.Sprintf("handleGitHubRepoAuthzEvent: Got github event %T", payload))
```suggestion
	log15.Debug("handleGitHubRepoAuthzEvent.newEvent", "type", fmt.Sprintf("%T", payload))
```

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +	log15.Debug("scheduleRepoUpdate: Dispatching permissions update for repo %s", repo.GetFullName())
```suggestion
	log15.Debug("scheduleRepoUpdate: Dispatching permissions update", "repo", repo.GetFullName())
```

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	"github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos"
```suggestion
	"fmt"

	gh "github.com/google/go-github/v28/github"
	"github.com/inconshreveable/log15"

	"github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos"
```

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	log15.Debug(fmt.Sprintf("handleGitHubUserAuthzEvent: Got github event %T", payload))
Same suggestions as the other place.

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
To be extra safe:
```suggestion
	accs, err := db.ExternalAccounts.List(ctx, db.ExternalAccountsListOptions{
		ServiceType: extsvc.TypeGitHub
		ServiceID: "TBD",
		AccountID: githubUser.GetID(),
	})
```

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	}
Technically, we should get at most one user right? Otherwise we're overmatching. (Though doesn't seem would do anything bad in this particular case)

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	log15.Debug(fmt.Sprintf("scheduleUserUpdate: Dispatching permissions update for users %v", ids))
```suggestion
	log15.Debug("scheduleUserUpdate: Dispatching permissions update", "users", ids))
```

2020-11-16 07:46 UTC, unknwon commented on doc/admin/repo/permissions.md
> +## Webhook permissions syncing
```suggestion
## Faster permissions syncing via webhooks
```

@quinnkeast: Please advise, because it is complementary to background syncing, the current title makes it feel like a _replacement_.

2020-11-16 07:46 UTC, unknwon commented on internal/db/external_accounts.go
> +		conds = append(conds, sqlf.Sprintf("account_id=%d", opt.AccountID))
Just FYI: Using `%d` or `%s` has no difference in `sqlf.Sprintf`.

2020-11-16 07:46 UTC, unknwon commented on internal/db/external_accounts.go
> +		conds = append(conds, sqlf.Sprintf("account_id=%d", opt.AccountID))
Doesn't seem we added tests for this in the PR?

2020-11-16 07:46 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
This "TBD" also brings the question that would this work with multiple different GitHub instances are connected to Sourcegraph (e.g. GitHub.com and "mygithub.mycorp.com")?

2020-11-16 09:03 UTC, quinnkeast commented on doc/admin/repo/permissions.md
> +## Webhook permissions syncing
I think this is a good change, though it does still come across as a replacement, but I'd need more info about how the background syncing and webhooks work together before I can suggest a better title. Can you give me a fast summary?

2020-11-16 09:11 UTC, unknwon commented on doc/admin/repo/permissions.md
> +## Webhook permissions syncing
@quinnkeast: Yes!

The background permissions syncing basically loop over all users and repositories we know (by querying database), this means we can only notice a change of permissions for the same user/repo after we've finished processing a complete round (imagine we have >2M repos). Webhook, on the other hand is a "notify" to say "OK something changed related to permissions to this user/repo, let's check it now". 

Does this make sense/helpful?

2020-11-16 09:15 UTC, quinnkeast commented on doc/admin/repo/permissions.md
> +## Webhook permissions syncing
Yup!

In that case, I'd say this title works well. I'd suggest adding a clarifying line within the content for the section to mention that webhooks run complementary to background syncing to speed up permissions sync while `maintaining integrity (replace with a more accurate term)`.

2020-11-16 10:56 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
the current approach of not specifying by service ID allows it to work with users authed via multiple github instances, as that's how my testing environment worked. it just means we schedule two user IDs. but i think making this change would be fine too

2020-11-16 11:37 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
i don't think we have enough info on the webhook to determine ServiceID here, which seems to be actually the URL of the github instance rather than a unique ID per external service config. I don't think there's much risk in keeping this filter as is (just filtering on github user ID) as we don't actually pass any arguments to the update scheduler, and this webhook is authenticated by the secret signing of the payload anyway

2020-11-16 11:38 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	}
based on the discussion above it's possible to get the same user ID multiple times, if the user is authed via two different github configs

2020-11-17 09:37 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
we would also need the client ID here in order to filter on service ID which we won't get on a webhook

2020-11-18 05:23 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
OK, I agree with not passing the serviceID, but adding `ServiceType: extsvc.TypeGitHub` part is still appropriate because `AccountID` is not universally unique (only unique to a specific GitHub instance, though nothing bad could happen, but feels lazy for not having it as a filter condition given this is in the GitHub webhook handler :D )

2020-11-18 05:24 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_repo_authz_event.go
> +// handleGithubRepoAuthzEvent handles any github event containing a repository field, and enqueues the contained
GitHub shows this suggest was applied, but the file is "reverted" somehow?

2020-11-18 05:25 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	}
SGTM

2020-11-18 05:29 UTC, unknwon approved these changes
Nice work!

2020-11-18 05:29 UTC, unknwon commented on doc/admin/repo/permissions.md
> +## Faster permissions syncing via webhooks
Make sure this section is completed before merging 😛 To unblock the engineering work, I would suggest take doc portion out and do it in a follow up PR (so you have time to get a proper review from `@quinnkeast` ).

2020-11-18 08:29 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
annoyingly if you specify any of ClientID,ServiceID,ServiceType the query will build an AND clause of all three https://github.com/sourcegraph/sourcegraph/blob/5c2ed36f4977cf14ce43cf17fb5df6327ee703be/internal/db/external_accounts.go#L362 do you think it's safe to break this out into individual equality clauses?

2020-11-18 08:54 UTC, arussellsaw commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
this feels non blocking so i'm going to merge for now, but will re visit for any feedback

2020-11-18 08:56 UTC, merged

2020-11-18 14:52 UTC, unknwon commented on cmd/frontend/internal/httpapi/webhookhandlers/handle_user_authz_event.go
> +	})
It is annoying indeed. I think it does make sense break out because it no longer fits our use cases.