monitoring: Allow arbitrary number of alerts per Observable
sourcegraph/sourcegraph pull request #15716
Opened 2020-11-12 17:33 UTC by tsenart

This commit is the first in a series of changes that address recent
pains with our monitoring generator. It refactors things Observable to
have a slice of Alerts, rather than explicit Warning and Critical
fields, which allows us to have zero, or any number of alerts per panel.

2020-11-12 17:33 UTC, tsenart commented
Most changes are very mechanical refactorings. Focus your review effort in `generator.go`.

2020-11-12 17:38 UTC, tsenart commented
After this PR is merged, I want to change the PanelOptions to allow us to much more directly use the Grafana SDK.

2020-11-12 17:43 UTC, uwedeportivo approved these changes
LGTM with the caveat that i'm not deeply immersed in the philosophy of alerting anymore (ie. the 5 pillars), so i don't know how this fits there and where the discussion stands on that.

2020-11-12 17:43 UTC, uwedeportivo commented on monitoring/generator.go
> +		return fmt.Errorf("%s: has now Owner set", o.Name)
```suggestion
		return fmt.Errorf("%s: has no Owner set", o.Name)
```

2020-11-13 01:29 UTC, bobheadxi requested changes
> which allows us to have zero, or any number of alerts per panel.

Since the former can be possible with the explicit `Warning` and `Critical` fields (just remove the check for them), is the intent to set multiple `Warning` alerts? I'm concerned that the latter will look pretty bad in the panels (we generate "threshold" lines to indicate when a metric is above its alerting level, and even more of these beyond the warning/critical will get rather crowded), and also not make much sense - if you want more warnings, the right thing to do maybe is to introduce a new level of alerts. What is the path forward you envision with this change?

2020-11-13 09:18 UTC, tsenart commented
> I'm concerned that the latter will look pretty bad in the panels (we generate "threshold" lines to indicate when a metric is above its alerting level

Ah, good point! I didn't think of that.

> if you want more warnings, the right thing to do maybe is to introduce a new level of alerts. What is the path forward and use case you envision with this change?

It seemed natural to me that you could have any number of alerts defined on a metric, but I didn't consider the constraint you mentioned above, so I'm happy to close this PR in favour of just removing the validation. Thanks!
.

2020-11-13 09:18 UTC, closed without merging