Add 'failed' state to dbworkers and use it in campaigns
sourcegraph/sourcegraph pull request #15972
Opened 2020-11-19 12:43 UTC by mrnugget

This PR does a few tiny things:

* add a `failed` state to `dbworker` jobs, to distinguish between jobs that are errored and retryable (`errored` state) and jobs that errored but won't be retried (`failed` state)
* it adds a `MarkFailed` method to the store (and all the other stores that implement the interface, which is why there's so much boilerplate here — if someone has an idea on how to improve this, let me know)
* it changes the `(*workerutil.Worker).handle` method to check whether the error returned by the handler is `errcode.IsNonRetryable` and if so, it marks the job as `failed`.

2020-11-19 12:57 UTC, mrnugget commented on enterprise/internal/campaigns/reconciler.go
> -		// not dequeued up again.
This is what brought me here. Now, 500 lines of boilerplate later, I'm not so sure anymore...

2020-11-19 16:55 UTC, eseliger approved these changes
Nice, I don't think it's too much code, given how much of it is just mock data.
Also, I like that we don't need this dirty hack anymore.

2020-11-19 16:56 UTC, eseliger commented on client/web/src/enterprise/campaigns/utils.ts
> +    // TODO: We should create a separate UI state for these
Can you add a ticket and assign me if you don't want to do it?

2020-11-19 17:47 UTC, efritz commented on internal/workerutil/dbworker/store/store.go
> +	q := s.formatQuery(markErroredOrFailedQuery, quote(s.options.TableName), "failed", failureMessage, id)
There's docs in the store above with the now-outdated text:

```
	//   - state: an enum type containing at least `queued`, `processing`, and `errored`
```

2020-11-19 17:48 UTC, efritz requested changes
Can you add this field to the state enums? Otherwise these queries will fail on certain tables.

2020-11-20 08:06 UTC, mrnugget commented on client/web/src/enterprise/campaigns/utils.ts
> +    // TODO: We should create a separate UI state for these
Done! https://github.com/sourcegraph/sourcegraph/issues/16009 Haven't assigned it to someone yet, because I might give it a shot but not sure if I have any ideas 😬

2020-11-20 08:09 UTC, mrnugget commented on internal/workerutil/dbworker/store/store.go
> +	q := s.formatQuery(markErroredOrFailedQuery, quote(s.options.TableName), "failed", failureMessage, id)
I assumed "at least" covered the `failed` :) But updated.

2020-11-20 08:15 UTC, mrnugget commented
> Can you add this field to the state enums? Otherwise these queries will fail on certain tables.

I've tried to find some enums, but I don't see any besides the one in the campaigns code base. Any hints?

Also, which queries should fail when reading another state?

2020-11-20 12:57 UTC, mrnugget commented
Okay, I realized that you meant the database enums, so I tried to update those. I think in the end I managed to do that? But I also had to fix another down migration because of a view. @efritz can you take a look?

2020-11-24 15:14 UTC, efritz approved these changes
Code intel integration suite passed locally.

2020-11-24 17:08 UTC, merged

2020-11-25 02:23 UTC, keegancsmith commented on migrations/frontend/1528395752_extend_worker_state_enums_with_failed.up.sql
> +-- to the new one. Hence the verbosity here.
@mrnugget can't we just mutate the enums outside of a transaction? IE given we are just adding a state, this doesn't require a transaction?

2020-11-25 06:27 UTC, mrnugget commented on migrations/frontend/1528395752_extend_worker_state_enums_with_failed.up.sql
> +-- to the new one. Hence the verbosity here.
Locally it looks like we can use `ADD VALUE`:

```
sourcegraph@localhost:5432 sourcegraph# alter type lsif_upload_state add value 'f00b4r';
ALTER TYPE
sourcegraph@localhost:5432 sourcegraph# begin;
BEGIN
sourcegraph@localhost:5432* sourcegraph# alter type lsif_upload_state add value 'hello';
ALTER TYPE
sourcegraph@localhost:5432* sourcegraph# commit;
COMMIT
```

Inside and _outside_ the transaction.

But all of the comments in the the other two migrations that I looked at had this comment (the "Unfortunately [...]" is a copied comment from the other migrations)