search frontend: add global filter detection for query transformation
sourcegraph/sourcegraph pull request #16183
Opened 2020-11-25 23:49 UTC by rvantonder

This PR is about the logic that looks at a search query string and then sets URL parameters.

Before, we would set URL parameters for `case` and `patterntype` in the URL depending on query string contents. We would then erase the `field:value` members of the query string so they don't clutter the search bar. We want to preserve this, BUT we don't want to do this unconditionally any more, since subexpressions can contain `case` and `patterntype`, and the previous code didn't detect any of those possibilities. This leads to buggy. behavior in https://github.com/sourcegraph/sourcegraph/issues/13958.

This PR detects whether we can erase filters like `case` or `patterntype`. We can only do so if they are "global", see the first commit's `findGlobalFilter ` comments that checks this.

In the second commit, I use `findGlobalFilter` and simplify our current logic. See inline comments for more. @attfarhan would you throw a careful eye at the changes here?

2020-11-25 23:58 UTC, rvantonder commented on client/shared/src/util/url.ts
> -        if (discreteValueAliases.yes.includes(caseInQuery.value)) {
As I was simplifying this code, I realized there's a subtle bug here: `caseInQuery.value` could technically be in quotes, so `case:"yes"`. If the value here is `"yes"`, the test `discreteValueAlises.yes.includes('"yes"')` would be false, and we would not evaluate it case sensitively. You can see this bug in action with a query like:

`repo:^github\.com/sourcegraph/sourcegraph$ search case:"yes"`

it will return case insensitive results (a capitalized `search` is in there).

 Basically, this condition wouldn't fire and we would delete the case. Effectively, what this previous code did was assume that the value of `caseInQuery.value` was a `Literal` token.

I've preserved this behavior (did _not_ fix the bug) because that's going to be a distraction right now. I did make it explicit that we are only testing against the `literal` value.

2020-11-26 00:00 UTC, rvantonder commented on client/shared/src/util/url.ts
> -        if (discreteValueAliases.yes.includes(caseInQuery.value)) {
Filed https://github.com/sourcegraph/sourcegraph/issues/16186

2020-11-26 00:13 UTC, rvantonder commented on client/shared/src/util/url.test.ts
> +        expect(buildSearchURLQuery('foo', SearchPatternType.literal, false, undefined)).toMatchInlineSnapshot(
Updated everything to use `toMatchInlineSnapshot` for my sanity.

2020-11-26 00:14 UTC, rvantonder commented on client/shared/src/util/url.test.ts
> +            'patternType=literal&case=no&q=foo'
`case=no` is the default behavior. Let's allow this logic to always set it explicitly.

2020-11-26 00:20 UTC, rvantonder commented on client/shared/src/search/parser/validate.ts
> +    const result = scanSearchQuery(query)
We scan the query string twice with the current code, just like before. We don't need to do this twice in that context, but I will optimize this sort of thing later. Otherwise there's too much movement in one PR.

2020-11-26 10:28 UTC, attfarhan requested changes

2020-11-26 10:28 UTC, attfarhan commented on client/shared/src/search/parser/validate.ts
> +        let balanced = 0
It seems like balanced is unused? Or will it serve a purpose down the line?

2020-11-26 10:28 UTC, attfarhan commented on client/shared/src/util/url.ts
> +        patternTypeParameter = query.slice(globalPatternType.value?.range.start)
We need the end range passed to `slice`. patternType could be at the start/middle of a query.

2020-11-26 10:28 UTC, attfarhan commented on client/shared/src/util/url.test.ts
> +            ).toMatchInlineSnapshot('patternType=literal+foo+type:diff&case=no&q=foo+type:diff')
This test gives us the wrong value, and represents the bug from not including the end range when parsing patternType (see my other comment). This would give us a URL `https://sourcegraph.com/search?patternType=literal+foo+type:diff&case=no&q=foo+type:diff`. What we want is `https://sourcegraph.com/search?patternType=literal&case=no&q=foo+type:diff`. This issue appears for a test below too, where patternType is not at the end.

2020-11-26 10:28 UTC, attfarhan commented on client/shared/src/util/url.test.ts
> +            ).toMatchInlineSnapshot('patternType=literal+foo&case=no&q=type:diff+foo')
Same issue as other test

2020-11-26 10:28 UTC, attfarhan commented on client/shared/src/util/url.ts
> +    searchParameters.set('q', queryParameter)
Unsure if this is deliberate, but I believe this orders the URL to display the parameters in the order: patternType, case, query. Right now we show the query first, and I think it would be good to maintain this. Wdyt?

2020-11-26 18:38 UTC, rvantonder commented on client/shared/src/search/parser/validate.ts
> +        let balanced = 0
Oh good catch! I don't think we need this right now.

2020-11-26 18:42 UTC, rvantonder commented on client/shared/src/util/url.ts
> +    searchParameters.set('q', queryParameter)
Changing the order change isn't deliberate. It's just that the previous code runs this call 4 times inside a nested conditionals and it's avoidable. Since order isn't significant, I didn't pay attention to that. I'll reorder the `set` calls so that the previous order is preserved.

2020-11-26 18:48 UTC, rvantonder commented on client/shared/src/util/url.ts
> +        patternTypeParameter = query.slice(globalPatternType.value?.range.start)
![facepalm](https://user-images.githubusercontent.com/888624/67424842-ca9c2200-f58b-11e9-9c6c-400f8cf39716.gif)

thankssss

2020-11-26 19:35 UTC, rvantonder commented
@attfarhan I changed the code a bit so that we preserve the original URL param order and whether we put `case` in the URL params, such that no url tests need to be updated any more. I've undone the previous test changes. Should be good now.

2020-11-27 06:18 UTC, attfarhan approved these changes

2020-11-27 06:40 UTC, merged