campaigns: add changeset text search
sourcegraph/sourcegraph pull request #16202
Opened 2020-11-27 00:55 UTC by LawnGnome

Initial WIP.

### TODO

* [ ] Refactor the code currently in resolver to handle the parsed search
* [ ] Resolver tests
* [ ] UI

### Interesting things to write up when this is no longer a draft

* Negation
* Field parsing for next sprint

Closes #15781.

2020-11-27 04:34 UTC, eseliger commented on enterprise/internal/campaigns/store_changesets_test.go
> +						{Term: "she dreamt she was a bulldozer", Not: false},
Nit: that was no dream.

2020-12-04 09:28 UTC, mrnugget requested changes
Sweet! Looks good to me but I'm leaving it as "Request changes" until we are certain that we don't need to set `safe = false` in the resolver (see comment) :)

2020-12-04 09:28 UTC, mrnugget commented on enterprise/internal/campaigns/resolvers/resolver.go
> +		opts.TextSearch = ts.TextSearch
I think we also need to

```go
safe = false
```

here, since by searching for the repository name you can leak information (i.e. search for "repository-i-shouldnt-see" and a result will tell you that this repository includes the changes/code that the other repositories in the list also have).

2020-12-04 09:28 UTC, mrnugget commented on enterprise/internal/campaigns/search/changeset.go
> +	tree, err := syntax.Parse(search)
Nice!

2020-12-04 09:28 UTC, mrnugget commented on enterprise/internal/campaigns/search/changeset.go
> +func ParseChangesetSearch(search string) (*campaigns.ListChangesetsOpts, error) {
Thought: if we introduce a separate type here (and translate it when passed to the store) then this package doesn't depend on our `enterprise/internal/campaigns` package and both the `resolver` and the `campaigns` package can depend on this one.

 ```suggestion
func ParseChangesetSearch(search string) (*ChangesetSearchOpts, error) {
```

But feel free to ignore, this is just a "hmm, couldn't we also..." thought I had while reading this.

2020-12-04 09:28 UTC, mrnugget commented on enterprise/internal/campaigns/store_changesets.go
> +	// The general query format is for a positive query is:
```suggestion
	// The general SQL query format for a positive query is:
```

2020-12-04 09:28 UTC, mrnugget commented on enterprise/internal/campaigns/store_changesets.go
> +	// (field ~* value OR field ~* value)
Do you mean this?

```suggestion
	// (field1 ~* value OR field2 ~* value)
```

Asking because I'm not sure I understand the queries in the docstring here :|

2020-12-04 09:28 UTC, mrnugget commented on enterprise/internal/campaigns/store_changesets.go
> +LEFT JOIN changeset_specs ON changesets.current_spec_id = changeset_specs.id
Should we only do this when `len(opts.TextSearch) != 0`?

I'm asking because specs can be pretty heavy, with their diff and all of that, and since we check the `spec` field (which includes the `diff`), it needs to be loaded from disk. So we pay the full price of loading two tables, I think.

We have other methods here that construct the joins dynamically, like `preds`, and I think the same approach can be used here.

2020-12-04 09:28 UTC, mrnugget commented on enterprise/internal/campaigns/store_changesets_test.go
> +	}
These are some good tests!

2020-12-07 19:36 UTC, LawnGnome commented on enterprise/internal/campaigns/resolvers/resolver.go
> +		opts.TextSearch = ts.TextSearch
Great catch! Changed accordingly.

2020-12-07 19:39 UTC, LawnGnome commented on enterprise/internal/campaigns/search/changeset.go
> +func ParseChangesetSearch(search string) (*campaigns.ListChangesetsOpts, error) {
I'm inclined to leave it until it becomes a problem. It's technically possible, but once this supports field operators in #15783 et al then I'm not sure we're not going to end up with essentially a duplicate of `ListChangesetsOpts` anyway.

2020-12-07 19:42 UTC, LawnGnome commented on enterprise/internal/campaigns/store_changesets.go
> +LEFT JOIN changeset_specs ON changesets.current_spec_id = changeset_specs.id
You must have been peeking at my laptop, because the first version actually did do that.

The catch with this was that it made the query format string more complicated: since `sqlf` doesn't support named placeholders, you end up with a bare `%s` in the middle of the string, and I found it somewhat obscured what was going on.

I spent a bit of time with `EXPLAIN`, and PostgreSQL has been smart enough in my tests to not perform the join if there are no fields in the `SELECT` or `WHERE` clauses that depend on it: since it's a `LEFT JOIN`, there's no change to the resultset in `changesets` if the records exist or don't in `changeset_specs`. So, barring a tiny amount of query parsing overhead, there _shouldn't_ be an extra cost always having this join in place.

That said, I'm happy to put this back to being conditional if you feel strongly about it.

2020-12-07 19:43 UTC, eseliger approved these changes
Very nice, LGTM!

2020-12-07 19:43 UTC, eseliger commented on client/web/src/enterprise/campaigns/detail/changesets/EmptyChangesetListElement.tsx
> +                    The query specified in <span className="text-monospace">repositoriesMatchingQuery:</span> may not
wow 🤦

2020-12-07 19:43 UTC, eseliger commented on enterprise/internal/campaigns/store_changesets.go
> +LEFT JOIN changeset_specs ON changesets.current_spec_id = changeset_specs.id
+1

2020-12-07 19:43 UTC, eseliger commented on enterprise/internal/campaigns/resolvers/resolver.go
> +		opts.TextSearch = ts.TextSearch
Did anything change here?

2020-12-07 19:46 UTC, LawnGnome commented on enterprise/internal/campaigns/resolvers/resolver.go
> +		opts.TextSearch = ts.TextSearch
I, uh, might have forgotten to push [the commit](https://github.com/sourcegraph/sourcegraph/pull/16202/commits/30a6c5563d7667c7e531f1d9163ee8daf4a2615f). :grimacing:

2020-12-07 19:50 UTC, eseliger commented on enterprise/internal/campaigns/resolvers/resolver.go
> +		opts.TextSearch = ts.TextSearch
Looks good, thanks!

2020-12-09 08:01 UTC, mrnugget commented on enterprise/internal/campaigns/store_changesets.go
> +LEFT JOIN changeset_specs ON changesets.current_spec_id = changeset_specs.id
If Postgres is smart enough to not load this from disk, then that's fine and I don't feel too strongly about it. Although I would prefer the other version since it would make clearer for what the `LEFT JOIN` is used (the spare `%s` can be made ... less spare? with a comment like `%s -- joins when X`)

2020-12-09 08:01 UTC, mrnugget commented on enterprise/internal/campaigns/search/changeset.go
> +func ParseChangesetSearch(search string) (*campaigns.ListChangesetsOpts, error) {
Sounds good to me!

2020-12-09 08:02 UTC, mrnugget approved these changes

2020-12-09 17:56 UTC, LawnGnome commented on enterprise/internal/campaigns/store_changesets.go
> +LEFT JOIN changeset_specs ON changesets.current_spec_id = changeset_specs.id
Implemented.

2020-12-09 18:23 UTC, merged