dbworker: Mark errored records "failed" if retries are exhausted
sourcegraph/sourcegraph pull request #16355
Opened 2020-12-02 12:07 UTC by mrnugget

This fixes https://github.com/sourcegraph/sourcegraph/issues/16046 by implementing the idea in https://github.com/sourcegraph/sourcegraph/issues/16046#issuecomment-737173357.

It changes the `MarkErrored` method to either mark a record as errored or as failed, depending on whether it has exhausted all its retries or not.

Thoughts?

2020-12-02 16:03 UTC, efritz approved these changes

2020-12-02 16:03 UTC, efritz commented on internal/workerutil/dbworker/store/store.go
> +-- source: internal/workerutil/store.go:MarkErrored|MarkFailed
```suggestion
-- source: internal/workerutil/store.go:MarkFailed
```

2020-12-02 16:03 UTC, efritz commented on internal/workerutil/dbworker/store/store.go
>  -- source: internal/workerutil/store.go:MarkErrored|MarkFailed
```suggestion
-- source: internal/workerutil/store.go:MarkErrored
```

2020-12-02 16:03 UTC, efritz commented on internal/workerutil/dbworker/store/store.go
> +    {finished_at} = clock_timestamp(),
```suggestion
	{finished_at} = clock_timestamp(),
```

2020-12-02 16:03 UTC, efritz commented on internal/workerutil/dbworker/store/store.go
> +    {finished_at} = clock_timestamp(),
```suggestion
	{finished_at} = clock_timestamp(),
```

2020-12-02 16:04 UTC, efritz commented
This _may_ cause a lot of the frontend/graphql resolvers to fail if we're not converting the new 'failed' state correctly. Could you either confirm that failed records are ok or wait for me to validate before merge?

2020-12-02 16:40 UTC, mrnugget commented
> Could you either confirm that failed records are ok or wait for me to validate before merge?

I can do this, but I'm not sure what the best strategy is to, as they say in Pokemon, _catch them all_?

2020-12-03 00:56 UTC, LawnGnome approved these changes
LGTM from a campaigns perspective, but I obviously don't have @efritz's broader context here.

2020-12-03 02:50 UTC, efritz requested changes
This breaks auto-indexing (and LSIF processing, I think) due to the CASE statement in the markFailed query. Let me explore this a bit.

We might have to get rid of the enum types.

2020-12-03 03:44 UTC, efritz commented
#16384 and #16386 should be enough to preserve behavior, although #16385 is also nasty in that it hid the error message that made the markFailed query silently lock auto-index records.

Once these three get merged in let me try to reproduce some issues one more time, then this :baby: :eyes: 🎉 !

2020-12-03 08:16 UTC, mrnugget commented
Did you see my comment here? https://github.com/sourcegraph/sourcegraph/issues/16046#issuecomment-737248732 That might also be viable and, in contrast to this, would contain this behaviour to just campaigns code, no changes needed in other consumer code of `dbworker`.

Looks like you already did the work, but in maybe we should reconsider if this is another option?

2020-12-03 14:27 UTC, efritz commented
> That might also be viable and, in contrast to this, would contain this behaviour to just campaigns code, no changes needed in other consumer code of dbworker.

I think the changes here are good and also general enough to apply to all consumers. I'll want to be able to use markFailed &co in the worker and the executor at some point (if gitserver is down of course we want to retry!)

2020-12-03 14:36 UTC, efritz approved these changes
Merged in those changes to fix usage in codeintel - LGTM!

🚢

2020-12-03 14:50 UTC, merged

2020-12-03 23:59 UTC, chrispine reviewed
LGTM