Update postgres docs with solutions
sourcegraph/sourcegraph pull request #17189
Opened 2021-01-12 02:59 UTC by daxmc99

Addresses issues found in https://github.com/sourcegraph/sourcegraph/pull/17131

2021-01-12 08:07 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +	// default Postgres container is called pgsql
I think this comment change needs to be reverted - docker-compose still exports cAdvisor metrics for postgres, so the original comment is correct

2021-01-12 08:07 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +							Interpretation: "This value indicates issues retrieving metrics from postgres_exporter.",
```suggestion
								- Ensure the Postgres exporter can access the Postgres database. Also, check the Postgres exporter logs for errors.
							`,
							Interpretation: "This value indicates issues retrieving metrics from postgres_exporter.",
```

2021-01-12 08:08 UTC, bobheadxi commented on monitoring/monitoring/README.md
> +## func Generate
I think you need to revert the changes to this file (CI complaint). I think this might be caused by some sort of difference in your git repo setup, where the tool can't determine the correct remote to use?

2021-01-12 08:08 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +	// default Postgres container is called pgsql
(see the comment line after this line)

2021-01-12 08:10 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +							Interpretation: "This value indicates issues retrieving metrics from postgres_exporter.",
(not having the last line makes it impossible for the generator to detect how much indentation to remove)

2021-01-12 16:20 UTC, daxmc99 commented on monitoring/definitions/postgres.go
> +	// default Postgres container is called pgsql
Ahh, I did not know we had cAdvisor metrics in `docker-compose`

2021-01-12 17:36 UTC, daxmc99 commented on monitoring/monitoring/README.md
> +## func Generate
Found the issue, I needed to run `git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main` 
Updated the generate to not depend on the local git env

2021-01-13 06:48 UTC, bobheadxi approved these changes

2021-01-13 06:48 UTC, bobheadxi commented on monitoring/monitoring/doc.go
> +//go:generate go run github.com/princjef/gomarkdoc/cmd/gomarkdoc --repository.url "https://github.com/sourcegraph/sourcegraph" --repository.default-branch main -o README.md .
nice, thanks!!

2021-01-14 15:08 UTC, bobheadxi requested changes

2021-01-14 15:08 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +				Title:  "Kubernetes monitoring (ignore if using Docker Compose or server)",
```suggestion
				Title:  shared.TitleKubernetesMonitoring,
```

(revert)

2021-01-14 15:08 UTC, bobheadxi commented on monitoring/definitions/postgres.go
> +				Title:  "Provisioning indicators (not available on server)",
```suggestion
				Title:  shared.TitleProvisioningIndicators,
```

(revert)

2021-01-15 01:50 UTC, merged