Filter LSIF dumps with an orphaned commit
sourcegraph/sourcegraph pull request #17192
Opened 2021-01-12 07:04 UTC by alidn

# Checklist

- [x] Update the main codes
- [ ] Update the tests and mock methods: because current tests ignore commits for dumps, this PR causes all of the relevant tests to fail

Fixes #12588

2021-01-12 20:39 UTC, alidn commented
I did add unit test, but it seems like code intel upload is only available in enterprise, so I wasn't able to test it on my local dev instance.

2021-01-12 21:04 UTC, efritz commented
Hi Ali,

Thanks for the PR! I can champion this the rest of the way if you'd like. This is actually a simpler solution than what I was thinking of doing for that issue. Good job!

FYI you can run the enterprise stack locally by running ./enterprise/dev/start.sh instead of ./dev/start.sh.

2021-01-12 21:40 UTC, alidn commented
Sounds great, thank you for the review!

If I'm not mistaken, running `./enterprise/dev/start.sh` requires cloning `sourcegraph/dev-private` which is only accessible to team-members. Am I missing something?

2021-01-13 22:20 UTC, efritz requested changes

2021-01-13 22:20 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/api/exists.go
> +		dumpCommitExists, err := api.dbStore.HasCommit(ctx, dump.RepositoryID, dump.Commit)
`dbStore.HasCommit` actually has the same problem here as not checking at all: it's coming from the same datasource that could be stale. We actually need to talk to gitserver directly to ensure the commit exists on disk.

This is close, but it used the wrong store here.

2021-01-13 23:36 UTC, efritz commented
Taking over in https://github.com/sourcegraph/sourcegraph/pull/17256.

Thanks for your hard work, it made fixing this issue a lot easier on me :)

2021-01-13 23:36 UTC, closed without merging