Add user <-> public repo mapping table
sourcegraph/sourcegraph pull request #17421
Opened 2021-01-19 13:47 UTC by arussellsaw

This PR adds a new table to map users to public repositories, this is so we can allow users to add public repositories on sourcegraph.com without configuring a code host, and have that repo appear within their default search context.

2021-01-19 13:52 UTC, tsenart approved these changes

2021-01-19 13:52 UTC, tsenart commented on internal/db/user_public_repos.go
> +func (s *UserPublicRepoStore) SetUserRepo(ctx context.Context, userID int32, repoID api.RepoID) error {
How is this going to be used? This API makes it seem like we can only associate already synced repos, but the UI asks the user for repo names. Can you describe the steps?

2021-01-19 14:19 UTC, ryanslade approved these changes

2021-01-19 14:19 UTC, ryanslade commented on internal/db/user_public_repos.go
> +	_, err := s.store.Query(ctx, sqlf.Sprintf("INSERT INTO user_public_repos(user_id, repo_id) VALUES %v %v", userID, repoID))
You could use `s.store.Exec` here since you don't expect to return any rows

2021-01-19 14:28 UTC, ryanslade commented
Oh, you should probably add a test

2021-01-19 14:30 UTC, ryanslade commented on internal/db/user_public_repos.go
> +	return s.store.Exec(ctx, sqlf.Sprintf("INSERT INTO user_public_repos(user_id, repo_id) VALUES %v %v", userID, repoID))
```suggestion
	return s.store.Exec(ctx, sqlf.Sprintf("INSERT INTO user_public_repos(user_id, repo_id) VALUES (%v, %v)", userID, repoID))
```

2021-01-19 14:31 UTC, ryanslade requested changes
Noticed an error in the query and the need for some tests

2021-01-19 14:55 UTC, arussellsaw commented
@ryanslade good call, done. i also added a read method so i could actually test it

2021-01-19 15:57 UTC, ryanslade commented on internal/db/user_public_repos.go
> +	out := []int32{}
We have `basestore.ScanInts` already, maybe make a `ScanInt32s`?

2021-01-19 15:58 UTC, ryanslade commented on internal/db/user_public_repos.go
> +	out := []int32{}
Then you can just write:

```go
out, err := basestore.ScanInt32s(s.store.Query(...))
```

2021-01-19 15:59 UTC, ryanslade commented on internal/db/user_public_repos_test.go
> +	"github.com/sourcegraph/sourcegraph/internal/db/dbtesting"
Please group the imports

2021-01-19 15:59 UTC, ryanslade approved these changes

2021-01-19 17:11 UTC, unknwon commented on internal/db/user_public_repos.go
> +	return s.store.Exec(ctx, sqlf.Sprintf("INSERT INTO user_public_repos(user_id, repo_id) VALUES (%v, %v)", userID, repoID))
We don't have a unique constraint on `(user_id, repo_id)` so it's possible that we have duplicated pairs in this table?

If we have unique constraint on `(user_id, repo_id)`, then we can easily add `ON CONFLICT DO NOTHING` in the above SQL. WDYT?

2021-01-20 06:52 UTC, ryanslade commented on internal/db/user_public_repos.go
> +	return s.store.Exec(ctx, sqlf.Sprintf("INSERT INTO user_public_repos(user_id, repo_id) VALUES (%v, %v)", userID, repoID))
Good point! Please add that @arussellsaw 

This is something we forgot to do for the `external_service_repos` table originally and it was a pain to add later.

2021-01-20 10:35 UTC, ryanslade approved these changes
LGTM

Would still like the ScanInt32s addition but that can also be done in another PR

2021-01-20 10:53 UTC, arussellsaw commented
i was feeling lazy yesterday, i've added the scan func now

2021-01-20 10:53 UTC, merged

2021-01-20 11:06 UTC, ryanslade commented on internal/db/user_public_repos.go
> +	rows, err := basestore.ScanInt32s(s.store.Query(ctx, sqlf.Sprintf("SELECT repo_id FROM user_public_repos WHERE user_id = %v", userID)))
nit: You could just return here: