use debug package to improve the visibility of the logs
sourcegraph/sourcegraph pull request #17480
Opened 2021-01-20 16:17 UTC by 5h1rU

If you want to enable the logger, please add `debug = *` in the browser's local storage.

2021-01-20 16:40 UTC, tjkandala approved these changes
Looks good, here are some things we can add before merging:
- Recursive React hook to abstract over `Debugger#extend` for the web app
- Add at least root loggers for all processes (e.g. background page, worker thread, web app)

2021-01-25 14:50 UTC, marekweb commented
Idea: it might be worthwhile to add a `sourcegraph:` prefix to the namespace. As we've seen from enabling the debug flag, various libraries use the `debug` library, so it would be helpful to be able to filter to the ones that comes from our own code.

2021-02-20 02:38 UTC, tjkandala commented
Upon further investigation, we can't merge this PR, at least not with this library. We can't depend on `window.localStorage` in web workers, so we can't log extension actions now

2021-02-20 02:38 UTC, tjkandala requested changes
Upon further investigation, we can't merge this PR, at least not with this library. We can't depend on window.localStorage in web workers, so we can't log extension actions now

2021-02-22 16:04 UTC, felixfbecker commented
There's a way to programmatically enable it, right? Can we use `postMessage()` from the main thread to enable it in the worker? Or, just use the comlink API setup we have in place? With the latter we could also easily make it work for the browser extension and background pages

2021-02-24 16:01 UTC, umpox commented on yarn.lock
> +  version "0.0.0"
🤔

2021-05-17 22:33 UTC, Joelkw commented
@muratsu how close to "done" is this now?

2021-05-17 23:59 UTC, muratsu commented
We've shipped `sourcegraph.app.log` 4 days ago to aid debugging user issues. [#20474](https://github.com/sourcegraph/sourcegraph/pull/20474)

2021-08-19 23:36 UTC, 5h1rU commented
Closing this by now. Let me know if you still find this valuable, and it will be open again.

2021-08-19 23:36 UTC, closed without merging

2021-08-20 11:43 UTC, felixfbecker commented
@5h1rU I still think this would have immense value for debugging purposes, especially debugging customer issues with CE. Loic mentioned they added something like this at his previous company and it was a game-changer.