Page Header + Breadcrumb updates
sourcegraph/sourcegraph pull request #17521
Opened 2021-01-21 15:38 UTC by umpox

2021-01-22 15:57 UTC, eseliger approved these changes
Campaigns code changes LGTM

2021-01-22 16:03 UTC, tjkandala approved these changes
Code looks great, was fun playing around with responsiveness on Storybook!

2021-01-22 16:03 UTC, tjkandala commented on client/web/src/components/PageBreadcrumbs.tsx
> +    const [first] = path
This will likely never be an issue for this component, but I'm scarred by unchecked index access now. Should we add [`--noUncheckedIndexedAccess`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#no-unchecked-indexed-access) to our tsconfig?

2021-01-22 16:07 UTC, eseliger commented on client/web/src/enterprise/campaigns/preview/CampaignPreviewPage.tsx
> +                    distinctUntilChanged((a, b) => isEqual(a, b))
I think it's not type safe. Good catch @umpox!

2021-01-25 09:49 UTC, umpox commented
Note: Waiting a design update feedback from @AlicjaSuska in regards to the PageHeader font size (designs for this component differ to our current h1 sizes)

2021-01-25 15:25 UTC, AlicjaSuska requested changes
@umpox I've updated Figma designs for new H1 size (28px). The line-height is 32px :)

When reviewing your PR, I've noticed that:
- font sizes are in px, should be in em for accessibility reasons :)
- icons in the headers should be adjusted - bounding box is 32px square (please, see the designs)
- Top margin in the beader should be 24px (I think it is 16px now)

2021-01-25 15:48 UTC, felixfbecker commented on client/web/src/components/PageBreadcrumbs.tsx
> +    const [first] = path
Pretty sure we already got consensus on this in a past retro, so just waiting on someone to take the lead and migrate us :)

2021-01-26 11:44 UTC, felixfbecker commented on client/web/src/components/PageBreadcrumbs.tsx
> +const Breadcrumb: React.FC<{ to?: string }> = ({ to, children }) => {
**nit**: we generally prefer to avoid acronyms as they depend on institutionalized knowledge
```suggestion
const Breadcrumb: React.FunctionComponent<{ to?: string }> = ({ to, children }) => {
```

2021-01-26 11:44 UTC, felixfbecker commented on client/web/src/components/PageBreadcrumbs.tsx
> +                <Breadcrumb to={first.to}>
The `first.to` here is a bit confusing to me. The way I would interpret [this design](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-15431-Approved?node-id=563%3A759):

![image](https://user-images.githubusercontent.com/10532611/105840047-aae77b00-5fd2-11eb-9392-1c0fe0254e1c.png)

is that the icon links to the global campaigns index page, while "sourcegraph" (which is the first breadcrumb in this implementation) links to the "sourcegraph" org page. But with this implementation, it looks like the icon would also link to the "sourcegraph" org page, the same destination as the second link, which seems wrong.

cc @AlicjaSuska

2021-01-26 11:44 UTC, felixfbecker commented on client/web/src/components/PageBreadcrumbs.tsx
> +                    / <Breadcrumb to={to}>{text}</Breadcrumb>
When the `icon` is not provided, this would start the breadcrumbs with a leading slash. Is that intended? Do we even need to have `icon` optional? Is there any page where this would be used without an icon? 

cc @AlicjaSuska

2021-01-26 11:44 UTC, felixfbecker commented on client/web/src/components/PageBreadcrumbs.tsx
> +const Breadcrumb: React.FC<{ to?: string }> = ({ to, children }) => {
This component looks (almost) equivalent to our `LinkOrSpan` component

2021-01-26 11:44 UTC, felixfbecker commented on client/web/src/components/PageHeader.tsx
> +    <div className={classNames('text-muted mb-3', className)}>{children}</div>
**nit**: This component is called "muted", but also applies bottom margin. Without the margin it would just be equivalent to `text-muted`. Maybe just inline the `text-muted mb-3`? It looks a bit prematurely abstracted to me.

2021-01-26 11:46 UTC, felixfbecker commented
LGTM besides comments above - great work!

2021-01-26 15:02 UTC, umpox commented on client/web/src/components/PageBreadcrumbs.tsx
> +                <Breadcrumb to={first.to}>
Ah yeah this should be the case, I misread [this comment](https://github.com/sourcegraph/sourcegraph/issues/15563#issuecomment-763526231)

2021-01-27 09:00 UTC, AlicjaSuska commented on client/web/src/components/PageBreadcrumbs.tsx
> +                    / <Breadcrumb to={to}>{text}</Breadcrumb>
No, right now we don't have places like this in our system. If in the future, we will make a decision to have breadcrumbs without stating icon, the first breadcrumb would be just the name of the page

To illustrate, let's imagine that campaigns have no icon, then breadcrumbs will go 'campaigns/sourcegraph/my-campaign'

2021-01-27 09:03 UTC, umpox commented on client/web/src/components/PageBreadcrumbs.tsx
> +                    / <Breadcrumb to={to}>{text}</Breadcrumb>
@felixfbecker I've refactored this component to support this, and a variety of other breadcrumb configurations we might want later on. Also baked in the `PageBreadcrumbs` logic into `PageHeader`, as we can just treat the Icon as an extension to the header content now

2021-01-27 09:05 UTC, umpox commented on client/web/src/components/PageBreadcrumbs.tsx
> +                    / <Breadcrumb to={to}>{text}</Breadcrumb>
`PageHeader` should now just take at least one of `icon` or `text` and `to` can be used to optionally wrap in a link

2021-01-27 10:13 UTC, umpox commented
Just to confirm @AlicjaSuska 

https://github.com/sourcegraph/sourcegraph/issues/17702 Created to review general page inconsistencies
https://github.com/sourcegraph/sourcegraph/issues/16602 Exists to review our rem/px values across the app

Will add both of these to our FE Platform scratchpad!

2021-01-27 13:28 UTC, AlicjaSuska commented
Changes look really good @umpox thank you for all the work! I have one last correction to ask of you: slashes '/' in breadcrumbs should have $text-muted color, now they have $body color

2021-01-27 13:34 UTC, umpox commented
@AlicjaSuska Good catch, thank you! Have updated

2021-01-27 15:29 UTC, AlicjaSuska commented
All approved. Thank you @umpox

2021-01-28 11:11 UTC, felixfbecker commented on client/web/src/components/PageHeader.scss
> +        font-size: 0.75rem;
This just seems to be the `small` text style, can we just use `<small>`?
See in Figma:
![image](https://user-images.githubusercontent.com/10532611/106129669-c1bbd800-6160-11eb-889f-f2fba2161722.png)

2021-01-28 11:11 UTC, felixfbecker commented on client/web/src/components/PageHeader.scss
> +        font-size: 0.75rem;
Same here

2021-01-28 11:11 UTC, felixfbecker commented on client/web/src/components/PageHeader.scss
> +.page-header .page-header__icon {
Confused by this descendant selector - can `.page-header__icon` appear in any other context than under `.page-header`? (It shouldn't per the BEM convention)
If not, this should just be defined as `&__icon` in the block above (as it was before).

2021-01-28 11:11 UTC, felixfbecker commented on client/web/src/components/PageHeader.tsx
> +    byline?: React.ReactNode
**suggestion**: These props could benefit from docblocks that explain their purpose and where they're rendered (especially as a component that will be used by other teams)

2021-01-28 11:37 UTC, umpox commented on client/web/src/components/PageHeader.scss
> +.page-header .page-header__icon {
It's to increase specificity to override the `height` and `width` that `icon-inline` uses, happy to change if you think there's a cleaner way?

2021-01-28 12:07 UTC, felixfbecker commented on client/web/src/components/PageHeader.scss
> +.page-header .page-header__icon {
`icon-inline` is for scaling an icon with the surrounding text (making it match the line height). So if the `width` and `height` should be explicit, then the icon shouldn't use `icon-inline`.
Looking at Figma and the `line-height` of `h1` now, it seems like the icon is sized exactly for the `line-height` though, so just `icon-inline` should be enough?

2021-01-28 12:26 UTC, umpox commented on client/web/src/components/PageHeader.scss
> +.page-header .page-header__icon {
The line height for `h1` changed in these designs, it's now `28px` font-size and `32px` line-height. I presume this https://github.com/sourcegraph/sourcegraph/blob/4497b71c823ea6aad16084ef44d28ef70e2504eb/client/shared/src/global-styles/icons.scss#L20 is an implict link to our typical line-height/font-size ratio?

2021-01-28 12:38 UTC, felixfbecker commented on client/web/src/components/PageHeader.scss
> +.page-header .page-header__icon {
Yeah default font size is 14px with 20px line height. An `icon-inline` therefor spans exactly the line height. This is supposed to scale with larger font sizes, assuming that the ratio between font size and line height stays the same.
@AlicjaSuska would you be opposed to having `h1`'s line-height be 40px so that it maintains the same 20/14 ratio?
(implementation wise we could then just remove the explicit `line-height` for `h1` as it will inherit)

2021-01-29 08:42 UTC, AlicjaSuska commented on client/web/src/components/PageHeader.scss
> +.page-header .page-header__icon {
Let's do it. Thank you @felixfbecker 

@umpox I've updated headers in [Figma](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-breadcrumbs-headers-15431-Approved?node-id=343%3A175) and left some comments that explain details.

2021-01-29 10:37 UTC, felixfbecker approved these changes
💯

2021-01-29 10:43 UTC, merged