add hanburger nav menu
sourcegraph/sourcegraph pull request #17535
Opened 2021-01-21 22:17 UTC by 5h1rU

2021-01-23 01:00 UTC, tjkandala reviewed
Code looks good, but shouldn't the menu items collapse into the hamburger menu at 1025px width? It seems like we always show the hamburger menu in this implementation

2021-01-26 11:08 UTC, felixfbecker reviewed
LGTM otherwise!
Also left comments in Chromatic

2021-01-26 11:08 UTC, felixfbecker commented on client/web/src/nav/MenuNavItem.tsx
> +export const MenuNavItem: React.FunctionComponent<MenuNavItemProps> = props => {
**suggestion**: maybe add a docblock explaining what this is, i.e. a dropdown menu for use in the navbar?

2021-01-26 18:08 UTC, 5h1rU commented
> Code looks good, but shouldn't the menu items collapse into the hamburger menu at 1025px width? It seems like we always show the hamburger menu in this implementation (note: I may be missing context, I'm just looking at Figma and the linked GitHub issue)

Thanks for pointing this out @tjkandala 
This was already discussed with @AlicjaSuska Now, we are using `< 992px` as the width to show the hamburger menu

2021-01-27 15:02 UTC, felixfbecker commented on client/web/src/nav/NavLinks.tsx
> +                        {!this.props.minimalNavLinks && this.props.showCampaigns && <CampaignsNavItem />}
Sorry for being unclear - what I meant to suggest was not to extract these into a method (that still evaluates the condition multiple times) but to use nested conditions like this:
```ts
{!this.props.minimalNavLinks && <>
  	{!isErrorLike(this.props.settingsCascade.final) && <>
	  		{this.props.settingsCascade.final?.experimentalFeatures?.codeInsights && <InsightsNavItem />}
	  		{this.props.settingsCascade.final?.experimentalFeatures?.codeMonitoring && <CodeMonitoringNavItem />}
	</>}
	{this.props.showCampaigns && <CampaignsNavItem />}
</>}
```

Note how each condition is only checked exactly once and it is easier to see at a glance which items are disabled/enabled by e.g. the `minimalNavLinks` prop.

2021-01-27 15:49 UTC, AlicjaSuska requested changes
Great work @5h1rU ! The only thing missing is the chevron position change. When menu is closed, it should point down. When it's open, it should point up.

<img width="715" alt="Screenshot 2021-01-27 at 16 49 10" src="https://user-images.githubusercontent.com/20326070/106016301-9b922b80-60bf-11eb-870d-2ba291b176f1.png">

2021-01-27 19:37 UTC, 5h1rU commented
@AlicjaSuska dropdown behavior updated :)

2021-01-27 20:12 UTC, 5h1rU commented on client/web/src/nav/NavLinks.tsx
> +                        {!this.props.minimalNavLinks && this.props.showCampaigns && <CampaignsNavItem />}
Got it!

2021-01-27 20:30 UTC, felixfbecker commented
@AlicjaSuska that change looked unintentional/inconsistent with the dropdowns in the component library in Figma to me. I had pointed it out to Felipe here: 
https://www.chromatic.com/pullrequest?activeElementId=comparison-test-key-5f0f3b9bb320641bb08ced08-1200&appId=5f0f381c0e50750022dc6bf7&number=17535&view=changes

2021-01-28 12:14 UTC, felixfbecker commented
@AlicjaSuska Should the dropdown caret positions be updated for all dropdowns (the generic dropdown component)? It seems inconsistent to have them different only in the navbar, and the implementation (the rendering of the different carets) is now duplicated in every dropdown instead of just using `caret={true}`. If we want it to switch I think we should abstract it in a component, but that seems a bit out of scope for this PR.

2021-01-29 09:40 UTC, AlicjaSuska commented
I think carret should change its direction in all cases - it's better ux, carret state indicates that something changed and in which direction the movement will happen on click. @5h1rU can we change it for the nav bar items for now so they are all consistent with the current implementation of the command palette? We can take care of all other dropwdons in a separate issue @felixfbecker wdyt?

2021-01-29 09:47 UTC, felixfbecker requested changes
Let's update the other dropdowns in a separate PR (should be abstracted somehow, e.g. in a component or with CSS like `.dropdown-toggle[aria-expanded="true"]::after { rotate: 180deg; }`).

Other than that looks great!

2021-01-29 09:48 UTC, felixfbecker approved these changes
Woops that was meant to be an approval

2021-01-29 14:21 UTC, AlicjaSuska commented
@5h1rU I found one more visual correction to make:

- when hovering on the items in the menu, only one item row background should be highlighted. Instead, all rows change the background. Text color changes correctly on hover. It happens for both light and dark themes.

<img width="173" alt="Screenshot 2021-01-29 at 15 18 24" src="https://user-images.githubusercontent.com/20326070/106286030-7deece80-6245-11eb-99c0-63e825399f80.png">

Should be the same as in the usernav menu:
<img width="226" alt="Screenshot 2021-01-29 at 15 20 52" src="https://user-images.githubusercontent.com/20326070/106286151-9f4fba80-6245-11eb-889b-8539ce19d812.png">

2021-01-29 14:22 UTC, AlicjaSuska requested changes
Row highlight on hover described in the comment above.

2021-01-29 18:48 UTC, 5h1rU commented
> Let's update the other dropdowns in a separate PR (should be abstracted somehow, e.g. in a component or with CSS like `.dropdown-toggle[aria-expanded="true"]::after { rotate: 180deg; }`).
> 
> Other than that looks great!

Thanks, @felixfbecker. I'd love to create a new component for this purpose, the CSS solution is a good one, but I don't feel comfortable manipulating the Reactstrap core so much. The less custom CSS, the better.

2021-01-29 18:49 UTC, 5h1rU commented
@AlicjaSuska The problem with the hover status was addressed. Thanks for letting me know.

2021-02-01 10:02 UTC, AlicjaSuska approved these changes
LGTM! thank you @5h1rU

2021-02-01 10:36 UTC, AlicjaSuska commented
@5h1rU could you update the Figma Design link in Storybook to (this will link to the design system file, instead of the project file). Thank you!

https://www.figma.com/file/SFhXbl23TJ2j5tOF51NDtF/%F0%9F%93%9AWeb?node-id=1108%3A872

2021-02-01 15:02 UTC, merged