WIP: Cloud user settings security page
sourcegraph/sourcegraph pull request #17594
Opened 2021-01-23 05:24 UTC by artemruts

### Description

**WIP**

Fixes part of #17166 (will be split)

Adds code external accounts sign-in (GitHub, GitLab) while trying not to touch much of the original passwords forms (those need to be migrated to hooks).

TODO:
- [ ] make sure styles are pretty consistent with design in Figma
- [ ] test with bad GraphQL queries / unexpected responses
- [ ] test password form still works as expected
- [ ] cleanup TS and add more comments
- [ ] add a video

2021-01-25 14:18 UTC, quinnkeast commented
> confirm what auth providers cloud will have, can Cloud have multiple GitHub providers, etc?

For this milestone, Cloud users can only have one code host connection for each provider, and we'll only support GitHub and GitLab.

2021-02-02 08:44 UTC, quinnkeast approved these changes

2021-02-02 08:49 UTC, ryanslade approved these changes
Backend code LGTM

2021-02-02 08:49 UTC, ryanslade commented on internal/types/types.go
> +	IsPasswordSet         bool
I don't think this is used anywhere

2021-02-02 08:49 UTC, ryanslade commented on internal/database/users.go
> +func (u *UserStore) getPassword(ctx context.Context, id int32, passwd *sql.NullString) error {
nit: I'd personally prefer to have this function return (sql.NullString, error). 

Passing values around to be mutated is generally only used when it's really necessary. It does make the code a little more verbose but I think it's less error prone. For example, what happens if someone passed in a nil passwd by mistake ?

2021-02-02 08:49 UTC, ryanslade commented on internal/database/users.go
> +	return false, nil
```suggestion
	return passwd.Valid, nil
```

2021-02-02 11:29 UTC, ryanslade commented
@artemruts I just realised that we have `user.BuiltinAuth` which indicates where their password is `NULL`, so I believe we can use that instead of adding the new method.

2021-02-02 11:29 UTC, ryanslade requested changes
See my latest comment. I think we can use the `user.BuiltinAuth` to check for a null password

2021-02-02 16:44 UTC, artemruts commented
> See my latest comment. I think we can use the `user.BuiltinAuth` to check for a null password

Thanks, @ryanslade! `BuiltinAuth` will work, just tested in Dev. Will cleanup backend changes 🙇

2021-02-02 18:12 UTC, artemruts commented
@quinnkeast I'm wondering if we should add these changes (`Account security` page) under the cloud "feature flag" and still keep the old `Passwords` page as it is before GA? That would cause temp code duplication but would be resolved before we go GA. We'd simply remove the `Passwords` page. It seems safer that way.

WDYT?

2021-02-02 18:18 UTC, quinnkeast commented
Great question!

> It seems safer that way.

Suppose we ship this, and something goes wrong. What went wrong, and what are the worst things that can happen?

2021-02-02 18:55 UTC, artemruts commented
@quinnkeast
>Suppose we ship this, and something goes wrong. What went wrong, and what are the worst things that can happen?

Most likely nothing will blow up 😆
Basic logic is:

We display ExternalAccounts only for GitHub/Gitlab and only if we have Auth providers for them.
Right now only GitHub is configured for DotCom so that's the only one we should see.

I'd be down to merge as is if I can test these changes in more "production" env, our current "feature toggle" setup is not flexible for me to:
- merge as is
- enable only for myself
- test and verify
- enable for all of the users

So I could figure out:
1. how to test in more prod env (canary deploy) 
2. 2-step way
   - add back the `Passwords` page, add "feature toggle" for `Account security` page
   - deploy to prod
   - toggle for myself only, test and verify
   - delete "Passwords" page, remove "feature toggle" for `Account security` page
   - deploy again

2021-02-02 19:07 UTC, quinnkeast commented
Great breakdown. 

I feel we should go with #2 for now, with the idea we can enable it for the Sourcegraph team to use for a short while to catch any problems before we enable for Cloud as a whole. Better feature flagging will help us a lot here, but short term I think it's a lower priority.

2021-02-03 07:20 UTC, ryanslade approved these changes
Easy review now as no Go code has changed 😄

2021-02-03 16:48 UTC, merged