Prefill the code intel index configuration field with the inferred configuration
sourcegraph/sourcegraph pull request #17736
Opened 2021-01-28 02:52 UTC by gbrik

2021-02-01 20:09 UTC, Strum355 commented on enterprise/internal/codeintel/autoindex/enqueuer/observability.go
> +		InferIndexConfiguration: op("InferIndexConfiguration"),
Reminder that I _think_ some sister doc has to be updated to reflect a new metric : )

2021-02-01 20:33 UTC, Strum355 requested changes
Minor points up for discussion if there was an intent behind them that im missing

2021-02-01 20:33 UTC, Strum355 commented on enterprise/internal/codeintel/autoindex/config/json.go
> +func MarshalJSON(config IndexConfiguration) ([]byte, error) {
I would make this a method on IndexConfiguration, that way in https://github.com/sourcegraph/sourcegraph/pull/17736/files#diff-e69142e2be11e8c107a1805c6cce6c481ee88574781d432105bbd1aba8c789c2R106-R113 we can simply use https://golang.org/pkg/encoding/json/#MarshalIndent

2021-02-01 20:33 UTC, Strum355 commented on enterprise/internal/codeintel/autoindex/config/json.go
> +func UnmarshalJSON(data []byte) (IndexConfiguration, error) {
Same here about making it a method

2021-02-01 20:33 UTC, Strum355 commented on enterprise/internal/codeintel/autoindex/config/yaml.go
>  func UnmarshalYAML(data []byte) (IndexConfiguration, error) {
Same here as with json but with yaml : )

2021-02-01 21:59 UTC, efritz commented on enterprise/internal/codeintel/autoindex/enqueuer/observability.go
> +		InferIndexConfiguration: op("InferIndexConfiguration"),
The op here is just how things are grouped, so no dashboards should need to be updated on this change. Adding a completely new metric would, but the op here is just a tag on an existing one.

2021-02-01 22:03 UTC, Strum355 commented on enterprise/internal/codeintel/autoindex/enqueuer/observability.go
> +		InferIndexConfiguration: op("InferIndexConfiguration"),
Yap confirmed, all g :+1:

2021-02-01 22:04 UTC, efritz approved these changes
I'm approving contingent on Noah's comments.

2021-02-01 23:55 UTC, gbrik commented on enterprise/internal/codeintel/autoindex/config/json.go
> +func MarshalJSON(config IndexConfiguration) ([]byte, error) {
`json.MarshalIndent` implicitly calls `(IndexConfiguration) MarshalJSON()` so that would cause an loop IIUC.

2021-02-01 23:57 UTC, gbrik commented on enterprise/internal/codeintel/autoindex/config/json.go
> +func UnmarshalJSON(data []byte) (IndexConfiguration, error) {
same here about `jsonc.Unmarshal` implicitly calling `(IndexConfiguration) UnmarshalJSON(data []byte)` IIUC

2021-02-01 23:58 UTC, gbrik commented on enterprise/internal/codeintel/autoindex/config/yaml.go
>  func UnmarshalYAML(data []byte) (IndexConfiguration, error) {
ibid

2021-02-02 01:36 UTC, Strum355 commented on enterprise/internal/codeintel/autoindex/config/json.go
> +func MarshalJSON(config IndexConfiguration) ([]byte, error) {
Yep youre totally right. Having a function like this irks me but there doesnt seem to be a way to get it to work with encoding/json.Marshal : ( approving

2021-02-02 01:36 UTC, Strum355 approved these changes

2021-02-03 17:38 UTC, merged