search contexts: create initial (non-interactive) context switch button
sourcegraph/sourcegraph pull request #17932
Opened 2021-02-02 22:17 UTC by limitedmage

Creates the button with the correct styling. No real data or dropdown menu yet. Also adds some storybook tests for the Monaco query input.

2021-02-03 09:18 UTC, quinnkeast commented
Before I provide review, should I focus fully on the button itself, or should I also take the bar `|` and search input into consideration?

2021-02-03 11:20 UTC, eseliger approved these changes

2021-02-03 17:49 UTC, limitedmage commented
> Before I provide review, should I focus fully on the button itself, or should I also take the bar `|` and search input into consideration?

The whole search bar, including the bar and focus/hover styles. Note that there is a bug right now with resizing the window that I am looking at and will fix before checking.

2021-02-03 18:50 UTC, quinnkeast commented
So this is _really_ precise set of adjustments—forgive me! Ultimately, these come together to make the feature feel really refined. Some of details below can be found in the previous prototype Farhan made, because they don't come across well in static design artifacts—after playing around with it in the inspector, I think this takes us to the same outcome.
 
- [ ] The button should have a `4px` border radius.
- [ ] The button has the text-monospace class, but this results in `SF Mono` being used rather than `Menlo`, which is what the search query input uses.
- [ ] When focused, the button's external shadow adds 4px to the overall height of the button: when focused, the button should be the same height as when hovered.
- [ ] The bar should be `--border-color-2`.
- [ ] This hard to explain properly, but the bar `|` should be aligned to the right edge of the button, so that when the hover state kicks in, the fade out is almost impossible to see, because it's "hidden" by the button's background fading in. Making this work means:
  - [ ] Remove the margin from the right of the button, and then increasing the left and right padding on the button to `.375rem`. (This makes the visual spacing between the context:name, bar, and input work, even when the actual button element is butted up against the bar.)
  - [ ] Neither the button background or the bar should have an animation duration (instant). This makes it feel much snappier and more responsive as a side effect.
  - [ ] The `.monaco-query-input-container__focus-container` should have a `3px` left margin, a `.325rem` left padding. This makes the input content and position balance correctly with the button, particularly when the search input is focused and the user hovers over the context button. 
  - [ ]  The bar should not be visible while the input is focused (I can't remember how we solved this in the prototype—it might have been just the positioning of elements making it "overlapped" rather than actually being hidden).
  - [ ] The `.monaco-query-input-container__focus-container` should have a `4px` border radius on the top left and bottom left when focused.
  - [ ] The top and bottom of the focus state for the search input needs to be `1px` higher and lower respectively: the blue border is currently "inside" the broader input, rather than overlapping, as seen here: 
  <img width="121" alt="CleanShot 2021-02-03 at 19 30 35@2x" src="https://user-images.githubusercontent.com/6304497/106792472-75880080-6656-11eb-86ed-cc8e86162f15.png">

(To be sure—since this feedback is so precise, I'm happy to make these adjustments in the CSS myself preferred!)

2021-02-04 11:33 UTC, quinnkeast requested changes
Extra learning about the prototyping process: make sure the prototype is always accessible in the future! I had to find a [Loom recording of the prototype's implementation](https://www.loom.com/share/21b4fbbf1e52418d9f6032fcee86e115) to figure out how, and more importantly why, we'd finalized spacing questions.

These changes fine-tune the spacing. Of particular note: since the context button will become disabled when the context parameter is entered into the search query itself, the disabled button state needs to be neatly spaced within the larger frame and the focused search query input.

Here's what these changes result in within the UI (recorded locally):

![CleanShot 2021-02-04 at 12 30 59](https://user-images.githubusercontent.com/6304497/106887070-ef66cb00-66e4-11eb-9646-60ca7d3841ad.gif)

Question – should the disabled button state also be included in this PR?

2021-02-04 11:33 UTC, quinnkeast commented on client/web/src/search/input/MonacoQueryInput.scss
> +            margin-left: 0.1875rem;
```suggestion
            padding-left: 0.5rem; // smaller padding if the search context selector is visible
            margin-left: 0.0625rem;
```

2021-02-04 11:33 UTC, quinnkeast commented on client/web/src/search/input/SearchContextDropdown.scss
> +        padding: 0.125rem 0.375rem;
```suggestion
        margin-left: 0.25rem;
        margin-right: 0.25rem;
        padding: 0.125rem 0.25rem;
        line-height: 1rem;
```

2021-02-04 11:33 UTC, quinnkeast commented on client/web/src/search/input/SearchContextDropdown.scss
> +    }
```suggestion
```

Display permanently (isn't visible when search input is focused, which is desirable).

2021-02-04 11:33 UTC, quinnkeast commented on client/web/src/search/input/SearchContextDropdown.scss
> +        background-color: var(--border-color);
```suggestion
        height: 1.125rem;
        background-color: var(--border-color-2);
```

2021-02-04 11:33 UTC, quinnkeast commented on client/web/src/search/input/toggles/Toggles.scss
>          height: 1.25rem;
```suggestion
        height: 1.125rem;
```

2021-02-04 12:39 UTC, felixfbecker commented on client/web/src/search/input/SearchContextDropdown.scss
> +        color: var(--theme-color-plain);
This variable is for the customization of the CodeMirror theme, I think we shouldn't reference it in our app.

2021-02-04 12:39 UTC, felixfbecker commented on client/web/src/search/input/SearchContextDropdown.scss
> +        font-size: $code-font-size;
Instead of replicating the style of code, is there a reason why we can't use the more semantic `<code>` element?

2021-02-04 22:14 UTC, limitedmage commented on client/web/src/search/input/SearchContextDropdown.scss
> +        color: var(--theme-color-plain);
There is not. I've now created one and copied the color value from our MonacoEditor config.

2021-02-04 22:19 UTC, limitedmage commented
> Question – should the disabled button state also be included in this PR?

I was planning on adding new styles when needed (in this case, when we start parsing the query for `context` filter) to disable the button. One question in this case though: if someone searches for `(context:a foo) or (baz)`, would the button be disabled or would it be enabled for the `baz` part of the search? (Or in other words: What context should be used if the query (or part of it) does not have a `context` filter?)

2021-02-05 08:07 UTC, quinnkeast commented
>One question in this case though: if someone searches for (context:a foo) or (baz), would the button be disabled or would it be enabled for the baz part of the search? (Or in other words: What context should be used if the query (or part of it) does not have a context filter?)

The design philosophy is here is that the context selector conveys the search is happening "within" that context. Once a context parameter is present in the query input, the button selector is disabled to help convey the search is entirely self-contained. (The disabled button helps to convey what the content will "return" to when removed from the query). The example kind of goes against the idea that the query is "within" the context, because it's essentially searching a different context while still searching within the higher-level context.

That said, I can absolutely see someone trying that search, so it's an excellent example to think through and challenge this philosophy... @novoselrok do you have any thoughts on this?

2021-02-05 08:28 UTC, quinnkeast approved these changes

2021-02-05 08:38 UTC, novoselrok commented
> One question in this case though: if someone searches for (context:a foo) or (baz), would the button be disabled or would it be enabled for the baz part of the search? (Or in other words: What context should be used if the query (or part of it) does not have a context filter?)

I agree with @quinnkeast on this. If the context button is disabled, we should not use it in the query. Otherwise we might get unintended consequences where the users don't realise a context is applied on some parts of the query and not on the others. And it would be hard to convey this information properly.

2021-02-05 09:41 UTC, novoselrok approved these changes

2021-02-05 10:35 UTC, felixfbecker commented
From using Chromatic, the context button doesn't seem to be interactive, but is tab-focusable and announced to screen readers as a dropdown button. Is this intentional? If yes, how could it be communicated to screen reader users better that there is no dropdown and hitting space won't do anything?

2021-02-05 10:42 UTC, quinnkeast commented
> From using Chromatic, the context button doesn't seem to be interactive, but is tab-focusable and announced to screen readers as a dropdown button. Is this intentional? If yes, how could it be communicated to screen reader users better that there is no dropdown and hitting space won't do anything?

I understand this is just a temporary state due to how the project is being implemented, and the dropdown functionality isn't yet implemented. There won't be a condition when the project is complete where it's shown, but can't be toggled open (other than the disabled state, which would indicate as such). Is there a benefit to communicating this anyway? (Serious question – it'll make me better at reviewing for accessibility!)

2021-02-05 11:10 UTC, felixfbecker commented
Will this actually be visible to users (without a feature flag)? If not I think that's fine

2021-02-05 17:41 UTC, limitedmage commented
@felixfbecker  the actual dropdown menu will be added in the next PR :) This does require a feature flag enabled for users to see it.

2021-02-05 17:46 UTC, merged