Change file tree trigger icons
sourcegraph/sourcegraph pull request #17996
Opened 2021-02-04 22:55 UTC by tjkandala

## Overview

Addresses #16947, part of the greater RFC 250 Action Items Bar project (#16165)

### Open

#### Before

![open-before](https://user-images.githubusercontent.com/37420160/106964727-8eed8300-6710-11eb-9a50-b74393c53b2a.png)

#### After
![open-after](https://user-images.githubusercontent.com/37420160/106964743-96149100-6710-11eb-9796-4cf4e17369ee.png)

### Close

#### Before

![close-before](https://user-images.githubusercontent.com/37420160/106964812-b47a8c80-6710-11eb-981c-fb66343de63e.png)

#### After

![close-after](https://user-images.githubusercontent.com/37420160/106964814-b6dce680-6710-11eb-931d-e30f6dcd9fb6.png)

### Limitations

- Collapse icon tooltip doesn't work, so I kept the title attribute. I suspect that the original authors ran into the same problem. I believe it has to do with the `<Spacer>` element, but I couldn't find a quick fix. We should refactor the `<Tabs>` component when we improve panel styles (it's the parent of both the sidebar and the panel)
- Tooltip delay doesn't work. I added logic in our `<Tooltip>` component to read `data-delay` from elements with `data-tooltip`, but [Reactstrap doesn't seem to respect the `delay` prop](https://github.com/reactstrap/reactstrap/issues/520#issuecomment-632970952)

## Progress
- [x] Implementation progress milestones
  - [x] Replace open icon
    - [x] Update sidebar toggle styles  
  - [x] Replace close icon
- [ ] Approved by a frontend engineer 
- [ ] Approved by a designer (approve on Percy as well)

2021-02-05 10:41 UTC, AlicjaSuska commented
Thank you for making those changes @tjkandala 
- tooltip for collapse icon - if it's a long fix, we can move forward without it for now. When it comes to refactoring tabs - do you think it makes sense to plan for it soon or we should wait to redesign?
- could you add a hover state for the collapse icon ([color of the icon should change](https://www.figma.com/file/p7g56TD2qFbqxRJ4ODrbo7/RFC-250-Action-items-bar-Final-review?node-id=1186%3A42967))
- collapse icon is too close to the edge of the panel. Please, add 4px of right padding ([see designs](https://www.figma.com/file/p7g56TD2qFbqxRJ4ODrbo7/RFC-250-Action-items-bar-Final-review?node-id=1186%3A42967))

2021-02-16 13:00 UTC, AlicjaSuska requested changes
I've described changes in the comment above. @tjkandala please, let me know when you're ready for the next review :) Thank you!

2021-02-16 17:50 UTC, tjkandala commented
> Thank you for making those changes @tjkandala
> 
> * tooltip for collapse icon - if it's a long fix, we can move forward without it for now. When it comes to refactoring tabs - do you think it makes sense to plan for it soon or we should wait to redesign?

@AlicjaSuska  I discovered that the issue was that the tabs container set `overflow: auto;`. I got the tooltip working by setting `boundariesElement` to `window` ([Popper modifier](https://popper.js.org/docs/v1/#modifierspreventoverflow)). 

I also made the requested style changes.

As for refactoring tabs, the pressing need (tooltip) is now gone, so I'd say it can wait until the redesign. However other teammates have complained about technical debt there as well, and it will be touched as part of the "action items in references panel" issue, so maybe we can refactor it as part of that solution

2021-02-16 17:51 UTC, tjkandala commented
> * tooltip for collapse icon - if it's a long fix, we can move forward without it for now. When it comes to refactoring tabs - do you think it makes sense to plan for it soon or we should wait to redesign?

@AlicjaSuska  I discovered that the issue was that the tabs container set `overflow: auto;`. I got the tooltip working by setting `boundariesElement` to `window` ([Popper modifier](https://popper.js.org/docs/v1/#modifierspreventoverflow)). 

I also made the requested style changes.

As for refactoring tabs, the pressing need (tooltip) is now gone, so I'd say it can wait until the redesign. However other teammates have complained about technical debt there as well, and it will be touched as part of the "action items in references panel" issue, so maybe we can refactor it as part of that solution

2021-03-11 11:26 UTC, AlicjaSuska requested changes
Thank you for making changes @tjkandala!

- The collapse icon is still very close to the edge of the panel (collapse icon is too close to the edge of the panel. Could you please add 4px of right padding before mergining? ([see designs](https://www.figma.com/file/p7g56TD2qFbqxRJ4ODrbo7/RFC-250-Action-items-bar-Final-review?node-id=1186%3A42967)).

<img width="276" alt="Screenshot 2021-03-11 at 12 21 23" src="https://user-images.githubusercontent.com/20326070/110780254-c8ac2f00-8264-11eb-8a16-04f4cf4d595c.png">

- collapse icon should have the same color and hover state color as the 'open file tree icon'. Please, see the design linked above as well.

Thank you!

2021-03-16 22:07 UTC, tjkandala commented
@AlicjaSuska I believe those issues have been addressed in previous commits, can you try to pull the latest commits for this branch? Thanks!

![fileCollapseColor](https://user-images.githubusercontent.com/37420160/111386121-2afc9980-8682-11eb-9d27-ffd47d2ddca4.gif)
![fileCollapsePadding](https://user-images.githubusercontent.com/37420160/111386126-2c2dc680-8682-11eb-949f-6be9f8cdd7ce.png)

2021-03-19 20:47 UTC, AlicjaSuska approved these changes
The collapse icon should have the same color and hover state color as the 'open file tree icon'. Please, see the design linked above as well.

That would be great if you could change that @tjkandala :) Not a blocker though

2021-03-20 04:44 UTC, tjkandala commented
@AlicjaSuska Thanks, I'll open an issue for the colors

2021-03-20 05:20 UTC, merged