Search context: Add search context url param and append context to queries
sourcegraph/sourcegraph pull request #18209
Opened 2021-02-12 13:30 UTC by novoselrok

2021-02-12 22:38 UTC, limitedmage approved these changes
Looks great! Left some minor suggestions.

2021-02-12 22:38 UTC, limitedmage commented on client/shared/src/util/url.ts
> +
Just to confirm, In the URL scheme, is `context` going to be a separate parameter like `patternType` and not appended to the search query `q` parameter, right?

2021-02-12 22:38 UTC, limitedmage commented on client/web/src/SourcegraphWebApp.tsx
>          )
It would be a good idea to write an integration tests to verify this, mocking out the call to `fetchSearchContexts`

2021-02-12 22:38 UTC, limitedmage commented on client/web/src/search/index.tsx
> +    if (appendContextFilter && searchContextSpec && !isContextFilterInQuery(finalQuery)) {
Super minor: I guess in this case we're pre-pending it rather than appending it? Does it make a difference to the backend?

2021-02-12 22:38 UTC, limitedmage commented on client/web/src/search/stream.ts
> +        console.trace()
```suggestion
```

2021-02-12 22:41 UTC, limitedmage commented
Just remembered that we also likely need to add code to react to changes to the URL in `Layout.tsx`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/Layout.tsx#L163:1-164:1

2021-02-15 07:54 UTC, novoselrok commented on client/shared/src/util/url.ts
> +
Correct, context URL param corresponds to the context selected in the context menu dropdown.

2021-02-15 07:59 UTC, novoselrok commented on client/web/src/search/index.tsx
> +    if (appendContextFilter && searchContextSpec && !isContextFilterInQuery(finalQuery)) {
AFAIK, it shouldn't. As long as there aren't existing contexts in the query (which we prevent), it shouldn't matter.

2021-02-15 12:19 UTC, novoselrok commented
@limitedmage Lots of files changed, but mostly tests and passing the search context props everywhere. I considered splitting the PR, but there isn't a clean separation and would probably just cause more work.

2021-02-15 13:22 UTC, quinnkeast requested changes
Overall looks good to me, but I think there's one bug:

If I don't have a context set at all, it's not defaulting to global or the user context, and instead shows an empty context selector:

![image](https://user-images.githubusercontent.com/6304497/107951871-48621900-6f99-11eb-9f7c-20781dccc884.png)

2021-02-16 08:39 UTC, quinnkeast approved these changes

2021-02-16 18:02 UTC, limitedmage approved these changes

2021-02-16 18:02 UTC, limitedmage commented on client/web/src/search/input/SearchContextDropdown.tsx
> +                        selectSearchContextSpec={selectSearchContextSpec}
suggestion: add unit tests for this functionality

2021-02-17 07:20 UTC, novoselrok commented on client/web/src/integration/search.test.ts
> +        test('Streaming search with single repo result', async () => {
Git merges are hard 😞

2021-02-17 13:49 UTC, novoselrok commented
@limitedmage I took your suggestions and added the integration/unit tests. I also noticed that I didn't handle the case if URL context contains an unavailable context spec. So I added the functionality to append it to the query and resubmit the search. Everything is contained here if you want to check it out: https://github.com/sourcegraph/sourcegraph/pull/18209/commits/5ece818313a43fe6767ea218d8febdbd7ff609ff

2021-02-17 17:59 UTC, limitedmage approved these changes

2021-02-17 18:01 UTC, merged