Show reference actions in new UX
sourcegraph/sourcegraph pull request #18370
Opened 2021-02-17 14:01 UTC by umpox

2021-02-23 11:54 UTC, AlicjaSuska commented
Hi! Thank you for sharing this work. As we've discussed: the only thing that is cannot be aligned with the design is the thickness of the bottom line on mobile. I'm ok with it for now, it's not a blocker for me, especially if it's time-consuming to change.

Design vs implementation:
<img width="918" alt="Screenshot 2021-02-23 at 12 07 34" src="https://user-images.githubusercontent.com/20326070/108840083-263e4b80-75d6-11eb-88d5-131660f119ab.png">
<img width="1023" alt="Screenshot 2021-02-23 at 12 08 00" src="https://user-images.githubusercontent.com/20326070/108840089-28080f00-75d6-11eb-90fb-4d5f5a2d40ac.png">

Other notes from me: please, keep the text styles of action items the same as in current implementation: text color and text size should be different (is: 14px, should be 12px). It looks like something is overwriting the link color (contrast is too low both in light and dark theme). thank you!

2021-02-23 11:55 UTC, AlicjaSuska requested changes
Please, make changes to the text styles (I've listed them in my previous comment). Thank you!

2021-02-23 15:44 UTC, umpox commented
@AlicjaSuska 

I believe I've made these changes, the font sizes match the designs unless I'm missing something there? Updated example (I changed the text temporarily here to match the designs)
![image](https://user-images.githubusercontent.com/9516420/108868186-dc615f80-75ed-11eb-8ebe-cf748f9a10c1.png)

2021-02-23 15:52 UTC, umpox commented on client/branded/src/components/panel/Panel.scss
> +        &::after {
For reviewer:

This is the cleanest way I can think of reliably achieving this design, we essentially want to break these actions onto a new line depending on their length. This means these actions have no way of understanding when they are in a 'new row' (without using JS), so in this scenario we ensure the `border-bottom` always covers the full row, despite its positioning.

Interested to hear if you have any other solutions

2021-02-24 14:12 UTC, felixfbecker commented on client/branded/src/components/panel/Panel.scss
> +        &::after {
Do you have a screenshot of when they are wrapped (i.e. the desired visuals)?

2021-02-24 14:13 UTC, felixfbecker commented
Would be great to have a story in Storybook to try out :)

2021-02-24 14:18 UTC, umpox commented on client/branded/src/components/panel/Panel.scss
> +        &::after {
These are the designs https://www.figma.com/file/yPrTtrvmkUtizDuzWiqzrZ/9740-ActionItems-in-references-panel-don-t-look-good-Approved?node-id=246%3A11

Screenshots of the implementation are in the PR description, unless you mean something else?

2021-02-24 17:48 UTC, tjkandala approved these changes
The CSS solution seems fine and I definitely prefer this over a JS solution here. I'm actually doing something similar for the action items bar :) LGTM for frontend code.

Visually, action items don't look vertically centered while my expectation would be that they are (On Linux Chromium | 88.0.4324.182 (Official Build) snap (64-bit))

![Screenshot from 2021-02-24 12-33-11](https://user-images.githubusercontent.com/37420160/109042438-33267200-769e-11eb-9711-14be82582fb8.png)
![Screenshot from 2021-02-24 12-32-44](https://user-images.githubusercontent.com/37420160/109042448-34f03580-769e-11eb-93d9-42efd551099a.png)

2021-02-26 18:47 UTC, AlicjaSuska requested changes
Thank you for updating the labels @umpox In the design, font size was 12px (as it was in the original implementation). Here, it's 14px. Now, that I look at it, it's better this way. Let's leave it :)

There is only one small change I'd like to ask for: we've shortened the label to 'Hide / show other repositiories' not 'Hide / show ~~references from~~ other repositories'.

With this change, it's ready to go! 🎉

2021-03-01 11:53 UTC, umpox commented
Thanks @AlicjaSuska, the copy change is from code in a different repo, so I have made a separate PR there: https://github.com/sourcegraph/code-intel-extensions/pull/579

2021-03-02 09:44 UTC, AlicjaSuska approved these changes
Thank you for making changes to the copy in a separate PR @umpox. In this case, all good to go! 🎉

2021-03-02 13:08 UTC, merged