WIP
sourcegraph/sourcegraph pull request #18375
Opened 2021-02-17 14:29 UTC by Strum355

2021-02-17 17:10 UTC, efritz commented on client/web/src/enterprise/codeintel/detail/CodeIntelUploadTimeline.tsx
> +            if(upload.state === LSIFUploadState.COMPLETED) {
- [ ] will need to run prettier

2021-02-17 17:14 UTC, efritz commented on client/web/src/enterprise/codeintel/detail/CodeIntelUploadTimeline.tsx
> +import { Timeline, TimelineStage } from '../../../components/Timeline'
Can you add a storybook case here? See the file CodeIntelUploadPage.story.tsx.

2021-02-17 17:15 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +				_ = h.dbStore.MarkFailed(ctx, uploadID, reason)
We should at least log if there's a failure here.

2021-02-17 17:15 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +			_ = h.dbStore.MarkFailed(ctx, uploadID, reason)
Same as above.

2021-02-17 17:17 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +			if uploadID != -1 {
I don't like how we're signaling the different events here. Specifically, I don't like using a sentinel value for a partial error condition, and I don't like that we're touching the return values in the presence of a non-nil error.

Is there a way to break the handleEnqueueErr up so that it fetches the upload independently and we can handle error conditions one at a time?

2021-02-17 17:17 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/uploads.go
> +		uploadedParts := []int{}
```suggestion
		uploadedParts := make([]int, 0, len(rawUploadedParts))
```

2021-02-17 17:18 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/uploads.go
> +func (s *Store) MarkFailed(ctx context.Context, id int, reason string) (err error) {
- [ ] Add a test (you can mirror MarkQueued)

2021-02-17 17:18 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/uploads.go
> +UPDATE lsif_uploads SET state = 'failed', failure_message = %s WHERE id = %s
- [ ] Need to set additional fields (see how the workerutil/dbstore does it - you need at least a timestamp)

2021-02-17 17:19 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/util.go
> +}
```suggestion
func formatAWSError(err awserr.Error) string {
	var s3Err s3manager.MultiUploadFailure
	if errors.As(err, &s3Err) {
		if s3Err.OrigErr() != nil {
			return s3Err.OrigErr().Error()
		}

		return s3Err.Error()
	}

	return err.Message()
}
```

2021-02-17 17:19 UTC, efritz requested changes
<3

See inline feedback.

2021-02-17 17:20 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/util.go
> +}
So obvious :facepalm: the tunnelvision is real, thx!

2021-02-17 17:23 UTC, efritz commented
@Strum355 For non-multipart uploads, do we even create a record in the database? I'm assuming we either (1) don't need to handle this case as there's no record to fail, or (2) we should have a follow-up issue to do the same flow on the short upload side.

2021-02-17 17:24 UTC, Strum355 commented
> @Strum355 For non-multipart uploads, do we even create a record in the database? I'm assuming we either (1) don't need to handle this case as there's no record to fail, or (2) we should have a follow-up issue to do the same flow on the short upload side.

@efritz yea we do, the record needs to be marked for processing after all :slightly_smiling_face: [link](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@nsc/lsif-upload-error-handling/-/blob/enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go?utm_source=chrome-extension#L235). This runs within the transaction so Im assuming the insert is rolledback when the minio upload fails

2021-02-17 17:28 UTC, efritz commented
@Strum355 Yeah looks like the record is only there temporarily until the upload store returns an error and the `tx.Done()` issues a rollback. Guess this case is squeaky clean.

2021-02-17 17:29 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/util.go
> +}
I only changed it because I know VSCode likes to complain about unnecessary else branches (where the previous consequent did an unconditional return).

2021-02-17 17:29 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/util.go
> +}
I must have disabled that setting :thinking: is it from gopls?

2021-02-17 17:30 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/util.go
> +}
How would I know? I'm too scared to write these kind of statements anymore or _some editor somewhere will yell at me_.

2021-02-17 19:27 UTC, Strum355 commented
> @Strum355 Yeah looks like the record is only there temporarily until the upload store returns an error and the `tx.Done()` issues a rollback. Guess this case is squeaky clean.

Im a bit iffy about that being a thing, feels like swallowing an error and mightnt be immediately obvious to the user. But that can be for another PR :shrug:

2021-02-17 20:02 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +			if uploadID != -1 {
Yea this is definitely the thing that irked me about this PR. Ill let this sit over the weekend and come at it with a fresh mind

2021-05-13 13:48 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +		return
@efritz do we want to not mark as failed if it was neither a client error nor an s3 error?

2021-05-13 15:49 UTC, efritz commented on go.sum
>  github.com/hashicorp/golang-lru v0.5.4 h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
What happened here? There's no go.mod change.

2021-05-13 15:50 UTC, Strum355 commented on go.sum
>  github.com/hashicorp/golang-lru v0.5.4 h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
`go mod tidy`

2021-05-13 15:52 UTC, efritz approved these changes

2021-05-13 19:45 UTC, merged