Update user + org area settings
sourcegraph/sourcegraph pull request #18560
Opened 2021-02-23 10:29 UTC by umpox

2021-02-24 17:54 UTC, limitedmage reviewed
Can we add storybook tests for the changed components?

2021-02-24 18:10 UTC, tjkandala approved these changes

2021-02-24 18:10 UTC, tjkandala commented on client/web/src/components/PageHeader.tsx
> +    headingElement?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
👍️

2021-02-25 10:16 UTC, AlicjaSuska requested changes
Thank you for making those changes @umpox! The only thing that is not aligned with design is event log in user settings - it should be in a separate section, by itself.

Also, side note: in the user settings header we display 'name (displayName)' in org settings we only display 'name' in the header. I think we missed it when working on breaders.

2021-02-26 11:32 UTC, umpox commented
@AlicjaSuska Made those changes!

![image](https://user-images.githubusercontent.com/9516420/109295101-1452e780-7826-11eb-80d1-788d70a72576.png)

![image](https://user-images.githubusercontent.com/9516420/109295117-1c128c00-7826-11eb-900a-305c10b9a67c.png)

There's some follow up modifications in https://github.com/sourcegraph/sourcegraph/pull/18630 (updates icon colours and adds storybook tests in particular). Happy to merge this and iterate further there

2021-02-26 18:51 UTC, AlicjaSuska approved these changes
Awesome! Thank you for fixing all that @umpox 🎉

2021-03-01 09:39 UTC, merged