Log CampaignCreated[OrUpdated], ChangesetPublished events
sourcegraph/sourcegraph pull request #18604
Opened 2021-02-24 13:29 UTC by mrnugget

2021-02-24 13:30 UTC, mrnugget commented on client/web/src/enterprise/campaigns/preview/CreateUpdateCampaignAlert.tsx
> +            telemetryService.logViewEvent(`CampaignDetailsPageAfter${campaignID ? 'Update' : 'Create'}`)
As I wrote [on Slack](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1614171140064400): I messed this up the first time, but asked @ebrodymoore to confirm that it's okay to change it now, since I think these numbers were unused until now.

2021-02-25 15:16 UTC, eseliger approved these changes
Seems legit to me, as long as the lists of events are reflecting what we want to track here 👍

2021-02-25 15:39 UTC, mrnugget commented
Alright, I talked to @ebrodymoore and @malomarrec. What I have here is wrong in that the usagestats here need to do the grouping by current month (in the case of users/contributors) and in the case of campaign cohorts it needs to group the counts by creation month.

The extension usagestats show how that can be done: https://github.com/sourcegraph/sourcegraph/blob/319347a1712aa8cde7ac16fbdb07dc82308f44bd/internal/usagestats/extensions.go#L10

Usage stats can now contain slices of records, which is what we want here.

I'll update the PR tomorrow (if I can make the SQL work) and leave a comment here if it's ready for review again.

2021-02-26 15:13 UTC, mrnugget commented
Okay, this is now ready for review again, @sourcegraph/campaigns and @ebrodymoore.

Notable changes compared to before:

- The contributors/users counts are now only including the events **of the current month**. We discussed this yesterday and Eric said he can work with that.
- I've added the cohorts calculation: campaigns get grouped by the week in which they are created and we track the stats of these campaigns per creation week.

Here's what the output of that cohorts calculation looks like, one line per cohort:

![image](https://user-images.githubusercontent.com/1185253/109317748-4e83af80-784d-11eb-9209-194c3ee5079d.png)

That gets sent over the wire as a slice of cohorts. I've also discussed this with Eric and he said that it's fine. I'll need some help to prepare the schema on the other end though.

So: **please review the SQL, the names and the data structures here**.

If that is fine, I'll update the `pings.md`, changelog, etc. and then I'll update the corresponding BigQuery schema.

2021-02-26 15:37 UTC, mrnugget commented on internal/usagestats/campaigns_test.go
> +			(2, 'test-2', 2, NOW(), NOW(), $1, NOW())
I'm going to fix this so it's stable.

2021-02-26 16:18 UTC, mrnugget commented
(Updated so that the cohorts include only the last 12 months, as discussed in Slack with @ebrodymoore and @malomarrec)

2021-02-26 16:27 UTC, malomarrec approved these changes
🚀

2021-02-26 16:40 UTC, eseliger approved these changes
Seems legit, but my head exploded briefly 💭

2021-02-26 16:40 UTC, eseliger commented on internal/usagestats/campaigns.go
> +    created_at >= now() - (INTERVAL '12 months')
```suggestion
    created_at >= NOW() - (INTERVAL '12 months')
```

2021-02-26 16:40 UTC, eseliger commented on internal/usagestats/campaigns.go
> +    created_at >= now() - (INTERVAL '12 months')
```suggestion
    created_at >= NOW() - (INTERVAL '12 months')
```

2021-02-26 21:44 UTC, ebrodymoore commented on internal/usagestats/campaigns.go
> +    date_trunc('week', campaigns.created_at)::date          AS creation_week,
I _think_ you're anchoring all the weeks on `campaigns.created_at` so if a company doesn't create a campaign one week, that week won't show up in pings. I think that's fine because there's no data that we need back every week that is outside the cohort array, right?

2021-02-26 21:45 UTC, ebrodymoore requested changes
Added one comment that I just want to make sure is settled. Assuming you've tested this on an instance too? I followed all the SQL but want to make sure it looks right coming out of a real instance.

2021-03-01 08:31 UTC, mrnugget commented on internal/usagestats/campaigns.go
> +    date_trunc('week', campaigns.created_at)::date          AS creation_week,
Yeah, exactly. I don't create a "last 52 weeks" timeseries and then join the counts against it, but create the weeks based on when campaigns are created. That means less "empty" data is transferred.

2021-03-01 10:59 UTC, mrnugget commented on internal/usagestats/campaigns.go
> +    created_at >= now() - (INTERVAL '12 months')
Thanks for holding me accountable to the One True Standard Of SQL Formatting

2021-03-01 12:45 UTC, mrnugget commented
@ebrodymoore I tested the query locally on my instance and on k8s.sgdev.org. Here's the output in SQL:

My local instance:

```
 creation_week | campaigns_closed | campaigns_open | changesets_imported | changesets_unpublished | changesets_published | changesets_published_open | changesets_published_draft | changesets_published_merged | changesets_published_closed
---------------+------------------+----------------+---------------------+------------------------+----------------------+---------------------------+----------------------------+-----------------------------+-----------------------------
 2021-01-18    |                0 |              3 |                   0 |                     10 |                    0 |                         0 |                          0 |                           0 |                           0
 2021-02-01    |                0 |              2 |                   0 |                      4 |                    1 |                         0 |                          1 |                           0 |                           0
 2021-02-08    |                2 |              1 |                   0 |                      3 |                    1 |                         1 |                          0 |                           0 |                           0
 2021-02-22    |                1 |              1 |                   4 |                      0 |                    1 |                         1 |                          0 |                           0 |                           0
```

`k8s.sgdev.org`:
```
 creation_week | campaigns_closed | campaigns_open | changesets_imported | changesets_unpublished | changesets_published | changesets_published_open | changesets_published_draft | changesets_published_merged | changesets_published_closed
---------------+------------------+----------------+---------------------+------------------------+----------------------+---------------------------+----------------------------+-----------------------------+-----------------------------
 2020-10-26    |                1 |              0 |                   0 |                      6 |                    1 |                         1 |                          0 |                           0 |                           0
 2021-01-18    |                1 |              0 |                   6 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
 2021-02-22    |                1 |              0 |                   6 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
 2020-10-12    |                1 |              0 |                   3 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
 2020-12-14    |                1 |              0 |                   6 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
 2020-11-16    |                2 |              0 |                   9 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
 2020-09-21    |                0 |              7 |                   5 |                    276 |                    0 |                         0 |                          0 |                           0 |                           0
 2020-12-07    |                1 |              1 |                  61 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
 2021-01-25    |                1 |              0 |                   6 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
 2020-10-19    |                1 |              1 |                   6 |                     59 |                    1 |                         0 |                          1 |                           0 |                           0
 2021-02-15    |                1 |              1 |                   8 |                      0 |                    0 |                         0 |                          0 |                           0 |                           0
```

---

I also created https://github.com/sourcegraph/analytics/pull/109 to update the Big Query schema for this. Please take a look and approve/comment.

2021-03-02 01:04 UTC, LawnGnome approved these changes

2021-03-11 14:58 UTC, mrnugget commented
@ebrodymoore I just updated this PR together with @eseliger. The event names and the fields in the usage stats have been renamed to have "BatchChanges" in the name (and fix typos). We'll now update the schema in the analytics repository to accept the new data (and the old "campaigns"-named data of older instances)

2021-03-11 15:04 UTC, eseliger approved these changes

2021-03-11 15:04 UTC, eseliger commented on enterprise/internal/batches/reconciler/executor.go
> +
```suggestion
```

2021-03-11 15:04 UTC, eseliger commented on doc/admin/pings.md
> +  - Weekly campaign (open, closed) and changesets counts (imported, published, unpublished, open, draft, merged, closed) for campaign cohorts created in the last 12 months
Not acceptable

2021-03-15 20:38 UTC, LawnGnome approved these changes
LGTM.

2021-03-16 10:37 UTC, malomarrec commented
@ebrodymoore annoying metric-thirsty PM ping

2021-03-16 10:38 UTC, mrnugget commented
@malomarrec See this comment in the other PR: https://github.com/sourcegraph/analytics/pull/109#pullrequestreview-612736246

> DO NOT MERGE THE OTHER PR YET, I WILL BE UPDATING THE PRODUCTION DB SCHEMA IN 24 HOURS

2021-03-16 10:47 UTC, malomarrec commented
This validates the annoying PM persona.

2021-03-17 01:08 UTC, ebrodymoore commented
@mrnugget you can merge. thanks for your patience!

2021-03-17 01:10 UTC, eseliger commented
> @mrnugget you can merge. thanks for your patience!

![image](https://user-images.githubusercontent.com/19534377/111399582-f3afdc00-86c5-11eb-9ca6-4f79a509dcda.png)

😬

2021-03-17 08:05 UTC, mrnugget commented
> @mrnugget you can merge. thanks for your patience!

You didn't approve the PR though, so, for the record: I'm taking _this comment_ as approval when merging this :P

2021-03-17 08:14 UTC, merged

2021-03-17 15:18 UTC, ebrodymoore commented
> You didn't approve the PR though, so, for the record: I'm taking this comment as approval when merging this :P
But what if it wasn't approval 😮