Update navigation design for admin settings
sourcegraph/sourcegraph pull request #18630
Opened 2021-02-24 21:49 UTC by 5h1rU

2021-02-25 10:36 UTC, AlicjaSuska commented
Thank you for sharing the video @5h1rU! Looks really good already. Here are some things I've noticed:

- we should animate the arrows (I've changed this in the design as well). Section is closed - arrow points down, section is open - arrow points up.
- Icons color is different than on the design
- There is a double border around the section title. There should be a single border. Also, 2 bottom corners shouldn't be rounded.
Now:

![image (4)](https://user-images.githubusercontent.com/20326070/109140899-62e87f00-775d-11eb-957e-67399c955e8a.png)

Design:
<img width="771" alt="Screenshot 2021-02-25 at 11 35 02" src="https://user-images.githubusercontent.com/20326070/109141020-86132e80-775d-11eb-84e8-42b76f102017.png">

Thank you!

2021-02-25 14:51 UTC, 5h1rU commented
Thanks @AlicjaSuska 

> Icons color is different than in the design

This dark/light combination is not available in our CSS variables, I can create it, but this will be the only component with those colors. Also, if you look at the user [implementation](https://user-images.githubusercontent.com/9516420/109014388-feb9b280-76ab-11eb-8375-4f1992326362.png), the colors are different. Is this the intended behavior?

2021-02-25 14:57 UTC, umpox commented
I think the icon colour is something which I missed on the user page too. I think that's a good point though @5h1rU, this is different to how we display our icon with text components in the nav bar. Would be good to consider aligning this pattern if we're making this change

2021-02-25 18:50 UTC, limitedmage commented on client/web/src/components/Sidebar.scss
> +        border-color: var(--secondary);
Note that this color is not themed and will look the same on dark and light mode.

2021-02-25 18:50 UTC, limitedmage commented on client/branded/src/global-styles/colors.scss
> +    --color-bg-6: #{$gray-06};
Can we have the design team add these to our color palette in Figma? I saw the Figma design and this color doesn't have a name. cc @AlicjaSuska

2021-02-25 18:50 UTC, limitedmage commented on client/web/src/site-admin/SiteAdminSidebar.story.tsx
> +const { add } = storiesOf('web/site-admin/AdminSidebar', module).addDecorator(story => (
Can we add a Chromatic decorator `.addParameters({ chromatic: { viewports: [$x] }})` or a div wrapper with `style="width:$x"` to limit the width of this component? It looks too wide in the storybook tests

2021-02-25 18:50 UTC, limitedmage commented on client/web/src/site-admin/SiteAdminSidebar.tsx
> +                condition({}) &&
```suggestion
                condition() &&
```
Is the `{}` needed?

2021-02-25 19:38 UTC, 5h1rU commented on client/web/src/site-admin/SiteAdminSidebar.tsx
> +                condition({}) &&
condition() [expect an object as context parameter](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/util/contributions.ts#L3), I'm not sure if modifying the interface will produce side effects.

2021-02-26 12:53 UTC, felixfbecker commented on client/web/src/components/Sidebar.scss
> +        }
**suggestion**: This sidenav is a `list-group`. The `list-group-item-action` class for list group items in Bootstrap handles this border radius logic and is set up to be composable with `<button>`s: https://getbootstrap.com/docs/5.0/components/list-group/#links-and-buttons

2021-02-26 12:53 UTC, felixfbecker commented on client/web/src/components/Sidebar.tsx
> +            <Button
**issue**: for accessibility, the button that controls a collapsible area needs to have `aria-expanded` and `aria-controls` set.

2021-02-26 12:53 UTC, felixfbecker commented on client/web/src/site-admin/SiteAdminSidebar.story.tsx
> +                'https://www.figma.com/file/cT23UcGqbdjdV4H2yxweIu/%2311775-Map-the-current-information-architecture-%5BApproved%5D?node-id=0%3A1',
This link just shows me the whole information architecture design as opposed to just the sidebar displayed in the story:

![image](https://user-images.githubusercontent.com/10532611/109301515-5c7b0580-7838-11eb-94f5-c09f16a21352.png)

Could you change this to reference the frame that contains the sidebar specifically?

2021-02-26 12:53 UTC, felixfbecker commented on client/web/src/enterprise/site-admin/sidebaritems.ts
> +                    items: group.items,
This is now just referencing the same items from the original `group` so this whole `if` block can be removed :)

2021-02-26 12:53 UTC, felixfbecker commented on client/web/src/site-admin/SiteAdminSidebar.story.tsx
> +    </>
**fyi**: you can use the `WebStory` component to include the styles (and router too)

2021-02-26 12:53 UTC, felixfbecker commented on client/branded/src/global-styles/colors.scss
> +    --color-bg-6: #{$gray-06};
If this gets added, please also make sure it gets added as a `bg-6` helper class by increasing the end number in `backgrounds.scss`: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/branded/src/global-styles/background.scss#L3:1

2021-02-26 18:42 UTC, 5h1rU commented on client/web/src/site-admin/SiteAdminSidebar.story.tsx
> +add(
Good to know thanks 👍

2021-02-26 19:05 UTC, AlicjaSuska commented
@umpox @5h1rU good points, thank you for mentioning the consistency here. I've made some changes to the design:

- icons have regular body color, there is no need to differentiate them, they are part of the label
- chevrons have the same color as clickable icons in the rest of the app ($link) to indicate that this is the clickable element. I know that the whole row is clickable in the accordion but the chevron indicated that (and I wouldn't like to make icon+label+chevron blue, it doesn't look good)

Please, let me know what you think about this option :)

2021-02-26 19:38 UTC, 5h1rU commented
@AlicjaSuska I agree. Take a look at the updated video.

2021-03-02 21:08 UTC, AlicjaSuska requested changes
Thank you for the updates @5h1rU :) 

- would it be possible to add a divider below the section title? It would be consistent with the user settings visuals. The divider is present in the designs in Figma but may have been hard to notice in combination with the blue background on [this screen](https://www.figma.com/file/cT23UcGqbdjdV4H2yxweIu/11775-Map-the-current-information-architecture-Approved?node-id=68%3A1).

Current:
<img width="223" alt="Screenshot 2021-03-02 at 21 56 40" src="https://user-images.githubusercontent.com/20326070/109714730-0e9d2f00-7ba3-11eb-9927-3019369adb35.png">

With divider:
<img width="608" alt="Screenshot 2021-03-02 at 22 00 22" src="https://user-images.githubusercontent.com/20326070/109714763-18269700-7ba3-11eb-83da-7a534e76563b.png">

- chevrons should have the $link color (please, see my previous comment for details). Could you update this? Thank you!

- there is one more thing regarding the behavior after clicking on the menu item. I would like us to scroll up to the beginning of the page when user clicks on the menu item so they see the category from the top. I've recorded the [video](https://www.loom.com/share/738209da3e8549f7a089156dd07a45bd) that shows the extreme case when use clicks on 'Subscriptions' and sees the blank part of the page on the right. Scrolling to the top of the page would prevent situations like this. @5h1rU wdyt about this approach?

2021-03-02 22:37 UTC, 5h1rU commented
Yes, it makes sense @AlicjaSuska
I implement a scroll top when the route change.

2021-03-03 09:14 UTC, umpox commented on client/web/src/site-admin/sidebaritems.ts
> +        },
Shouldn't these links be swapped? (i.e. instrumentation navigated to `/~/debug` previously)

2021-03-04 10:05 UTC, umpox approved these changes

2021-03-04 17:59 UTC, AlicjaSuska approved these changes
Thank you for the update @5h1rU ! All looks really good :)

One minor thing (not a blocker, so I'm approving the PR): the page could scroll all the way to the top, now it's right at the beginning of the content what looks a little off to me.

Now:
<img width="1536" alt="Screenshot 2021-03-04 at 17 56 10" src="https://user-images.githubusercontent.com/20326070/110008119-a6be2400-7d1b-11eb-99a6-f3d87a5a00b6.png">

Imporved:
<img width="1535" alt="Screenshot 2021-03-04 at 17 56 16" src="https://user-images.githubusercontent.com/20326070/110008134-aaea4180-7d1b-11eb-823d-7358e170b7e1.png">

2021-03-04 18:02 UTC, merged