Initial lsif index tester
sourcegraph/sourcegraph pull request #18755
Opened 2021-03-01 21:55 UTC by tjdevries

2021-03-23 19:19 UTC, tjdevries commented
Todo:
- [ ] actually use lsif-validate
- [ ] check out main's go.mod & what not so I don't commit dumb things

2021-03-23 19:41 UTC, efritz requested changes
Good job! Some comments inline. You've also committed a good number of binary/inline files that should be pruned before merge.

I have no big issues with what's here but want to do a second review once some of the things I've mentioned are tidied up.

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/README.md
> +- lsif-clang compile_commands.json
Seems like the directions are unfinished.

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/lsif_parser.go
> +		return nil, err
```suggestion
		return nil, errors.Wrap(err, "Couldn't open file")
```

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/lsif_parser.go
> +			log.Fatalf("find failed with output '%v'\nArgs were '%v'\n", string(out), dirnames)
```suggestion
			return errors.Wrap(err, "find(%v) failed: %v", strings.Join(dirnames, ", "), string(out))
```

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/lsif_parser.go
> +func makeExistenceFunc(directory string) pathexistence.GetChildrenFunc {
Is this duplicated with some of @shrouxm 's recent efforts?

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +	logging.Init()
Possibly unnecessary after lines 83-87.

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +				results <- &projResult
This could be cleaner if you made `results` a struct of `struct { result ProjectResult; err error }`

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		go func(name string) {
Tips for doing this kind of parallel work with a fixed sized list:

```go
resultCh := make(chan resultType, len(inputSlice))
var wg sync.WaitGroup

for _, thing := range inputSlice {
    wg.Add(1) // Mark a worker BEFORE you schedule it

    go func(thing thingType){
      defer wg.Done()

      // do your work here
    }(thing)
}

wg.Wait() // Wait for all goroutines to exit
close(resultCh) // All writers are done, you can now safely close this

// Now you can safely iterate the results!
for result :=range resultCh {
    //
}
```

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +	testFiles, err := os.ReadDir(directory + "/lsif_tests")
```suggestion
	testFiles, err := os.ReadDir(filepath.Join(directory, "lsif_tests"))
```

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		fileResult, err := runOneTestFile(directory+"/lsif_tests/"+file.Name(), bundle)
```suggestion
		fileResult, err := runOneTestFile(filepath.Join(directory, "lsif_tests", file.Name()), bundle)
```

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +
```suggestion
```

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		return TestFileResult{}, errors.New("Yo dawg, you need some files")
```suggestion
		return TestFileResult{}, errors.Wrap(err, "Failed to read file")
```

2021-03-23 19:41 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +	json.Unmarshal(doc, &testCase)
Should catch this error in case the test file is malformed.

2021-03-23 19:41 UTC, efritz commented on enterprise/lib/codeintel/semantic/repl/main.go
>  func main() {
If changes in these files are actual fixes they should likely go in another PR.

2021-03-23 19:41 UTC, efritz commented on go.mod
> +	github.com/pelletier/go-toml v1.8.1
You may need to run `go mod tidy` in the root to clean up new but unused imports.

2021-03-24 18:05 UTC, shrouxm commented on enterprise/cmd/lsif-index-tester/lsif_parser.go
> +func makeExistenceFunc(directory string) pathexistence.GetChildrenFunc {
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/lib/codeintel/lsif/conversion/correlate.go?subtree=true#L46:6 

i added this fn last week, should be able to replace readBundle

2021-03-25 16:19 UTC, tjdevries commented on enterprise/cmd/lsif-index-tester/main.go
> +		go func(name string) {
Nice :) very cool! I added that change.

2021-03-25 23:43 UTC, tjdevries commented on enterprise/cmd/lsif-index-tester/lsif_parser.go
> +func makeExistenceFunc(directory string) pathexistence.GetChildrenFunc {
Cool :+1: got to remove this whole file now that I've rebased & added it.

2021-03-25 23:51 UTC, efritz commented on enterprise/cmd/lsif-index-tester/proc_profiling.go
> +		return -1, errors.New("Could not convert usage")
FYI: generally you want to return zero values for all other return values when returning an error. In Go it's best to adhere to this practice (with one big exception):

If you call a function and you get back an error, all other values shouldn't even be touched because you don't know if they contain garbage or not.

The exception here is the Reader interface, that returns the number of bytes read and `io.EOF`. This is a pretty stupid, asymmetric decision on the part of the language.

2021-03-26 00:49 UTC, efritz approved these changes
Binary enterprise/lib/codeintel/repl/repl is still committed.

Left comments, most all are code style and a few questions. These can obviously be handled easily after merge as well.

Some of these I just marked due to personal preference + consistency so most of them are definitely nits.

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +	}
```suggestion
	log15.Debug("... Generated compile_commands.json")
```

It's a lint error to have an else clause to an if that does an unconditional return (this may have been flagged in CI).

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		log15.Debug("... Generated compile_commands.json")
This log message is outdated.

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +	}
```suggestion
	if err != nil {
		return ProjectResult{}, err
	}

	log15.Debug("... Validated dump.lsif")
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		}, err
```suggestion
		return ProjectResult{}, err
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +
```suggestion
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +			logFatal("Had too many results", "results", results)
A reason this is fatal instead of a test error?

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +
```suggestion
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +	testCase := LsifTest{}
```suggestion
	var testCase LsifTest
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +	var fileResults []TestFileResult
```suggestion
	fileResults := make([]TestFileResult, len(testFiles))
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +
```suggestion
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		fmt.Println("conversion failed")
```suggestion
```

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		filePath := filepath.Ext(file.Name())
Misleading var name (it's an extension, not a path).

2021-03-26 00:49 UTC, efritz commented on enterprise/cmd/lsif-index-tester/main.go
> +		log15.Warn("No lsif test directory exists here", "directory", directory)
```suggestion
		if os.IsNotExist(err) {
			log15.Warn("No lsif test directory exists here", "directory", directory)
			return TestSuiteResult{}, nil
		}
		
		return TestSuiteResult{}, err
```

2021-03-29 12:59 UTC, tjdevries commented on enterprise/cmd/lsif-index-tester/main.go
> +			logFatal("Had too many results", "results", results)
Nope, just leftovers, I will fix.

2021-04-01 15:27 UTC, merged