One-click OAuth for code host + improved usability
sourcegraph/sourcegraph pull request #18849
Opened 2021-03-04 04:00 UTC by artemruts

### Description

This PR fixes #18743 and #18067

### TODO

- [ ] wire OAuth work that depends on #18805 
- [ ] QA everything together

### Screenshot

<img width="908" alt="new flow" src="https://user-images.githubusercontent.com/1319181/109909303-e03b5480-7c73-11eb-870c-b2a284548ff3.png">

2021-03-04 09:13 UTC, quinnkeast requested changes
Feeling good!

**OAuth elements:**

- [ ] The `Connect` dropdown should be the smaller variant (`btn-sm`), which can be seen on the [extensions page](https://sourcegraph.com/extensions).
- [ ] The `Remove` button should be `btn-sm`.

In the design, I'd made the buttons for the code hosts just a bit larger than the component buttons. I think eventually our component system needs a variant to support larger buttons, but now's not the best moment for it.

**Access token modal:**

- [ ] Modal backgrounds should be white.
- [ ] Needs spacing above helper description.
- [ ] Helper description should be 1.4 line height.
- [ ] Badge size and location is off.

<a href="https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-and-Private-Repos-for-Users-on-Cloud?node-id=2484%3A23"><img width="820" alt="CleanShot 2021-03-04 at 10 21 41@2x" src="https://user-images.githubusercontent.com/6304497/109941486-823e5980-7cd3-11eb-900f-6c1328e4b9d5.png"></a>

- [QA in Figma](https://www.figma.com/file/zXvqCASHDzmvKbrAl1EVsd/Public-and-Private-Repos-for-Users-on-Cloud?node-id=2484%3A23)

2021-03-04 17:34 UTC, artemruts commented
Quinn, thank you for taking a look.
Do you have any tips for visual diff workflows, do you use any tools?

Pushed new changes, not pixel perfect but should be definitely better 🤞
I try to write less custom css and mostly rely on bootstrap classes.

2021-03-10 18:44 UTC, artemruts commented on client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
> +
@tjkandala TJ, do you know what's the good place to put custom button variants and colors?
I think we'll start using that button variant and color for GitLab soon. TY!

2021-03-10 19:09 UTC, tjkandala commented on client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
> +
@artemruts I don't think it needs to move to /shared or /branded until we use it in the browser extension and/or marketing sites, so it can stay in /web. `/web/src/user/settings/codeHosts` seems like a good place at least name-wise. Maybe create an `index.scss` or `codeHosts.scss` file within that directory and put the code host button styles there. If we start using it outside of the user settings area (e.g. in repo settings), we can lift the file up then

2021-03-10 19:12 UTC, artemruts commented on client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.scss
> +
Thank you, TJ! Will do it now.

2021-03-11 09:37 UTC, quinnkeast commented
Couple of notes:

- The GitLab button seems to be taking me to https://gitlab.sgdev.org instead of GitLab.com for some reason.
- If I click a code host button then hit back, the spinner is shown indefinitely.

Otherwise it's _super nice_ to be able to just.. click the button and it's done!

2021-03-11 19:33 UTC, artemruts commented
> Couple of notes:
> 
> * The GitLab button seems to be taking me to https://gitlab.sgdev.org instead of GitLab.com for some reason.
> * If I click a code host button then hit back, the spinner is shown indefinitely.
> 
> Otherwise it's _super nice_ to be able to just.. click the button and it's done!

1. I think dev only has https://gitlab.sgdev.org/ configured as GitLab provider
2. I'll fix that!

2021-03-11 22:52 UTC, artemruts commented on client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
> +
@quinnkeast  let me know if I understood this right

### Context

1. OAuth navigations happen with `window.location.assign`
2. Right before the navigation starts I show the loading indicator
2. While SG and OAuth provider talk to each other (and the loading indicator spins) a user may press `ESC` or do another action and cancel the request
3. if the request(s) and the navigation didn't happen - we want to remove the loading indicator

It seems there may not be some browser native one-liner solution 🤔  maybe I'm missing something

### Example

```jsx
  <button
      type="button"
      onClick={() => {
          setOauthRequestFor(kind)
          ifNotNavigated(() => {
              // do this if we didn't navigate in the default 2000ms
              setOauthRequestFor(undefined)
          })
          navigateToAuthProvider(kind)
      }}
      className='btn mr-2 btn-dark'
  >
```

### Demo

![cancel](https://user-images.githubusercontent.com/1319181/110865753-1d19d380-8292-11eb-90ca-a6b7c490e52d.gif)

2021-03-12 02:14 UTC, artemruts commented on client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
> +    window.addEventListener('unload', unloadListener)
`beforeunload` - is too early

2021-03-12 04:23 UTC, tjkandala commented on client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
> +
The approach seems sane enough to me! I wonder why we need an interval here though, given that we only check that the total time has elapsed.

If I'm understanding the problem correctly, it's that you're waiting on both the unload event and 2000ms, and if 2000ms "happens" first, call the callback, but if the unload event is first, don't call the callback even after 2000ms? Here's how I'd solve it with RxJS:

```ts
timer(2000)
    .pipe(takeUntil(fromEvent(window, 'unload')))
    .subscribe(() => callback())
```

Otherwise, we could cut some lines with `setTimeout`, but maybe I'm missing why we need an interval

2021-03-12 04:55 UTC, artemruts commented on client/web/src/user/settings/codeHosts/UserAddCodeHostsPage.tsx
> +
yeah, `setInterval` should've been `setTimeout`, I think I had an some idea when I was writing that code but it escaped me 😆 

You got the logic right, we give X ms time for the navigation to happen, if it doesn't - call the callback.
I'll check the RxJS code, thanks!

2021-03-16 11:04 UTC, arussellsaw approved these changes
My only note is on the design, it feels weird that we have two different ways to connect a code host here, one that only does OAuth, the other that does both OAuth & access token. cc @quinnkeast 

![Screenshot 2021-03-16 at 11 04 01](https://user-images.githubusercontent.com/5236823/111299014-5615c780-8647-11eb-90d7-3c18cf103da6.png)

2021-03-16 11:06 UTC, arussellsaw commented
also the 'connect with code host' copy feels a bit terse

2021-03-16 12:42 UTC, quinnkeast commented
> My only note is on the design, it feels weird that we have two different ways to connect a code host here, one that only does OAuth, the other that does both OAuth & access token. cc @quinnkeast
> 
> ![Screenshot 2021-03-16 at 11 04 01](https://user-images.githubusercontent.com/5236823/111299014-5615c780-8647-11eb-90d7-3c18cf103da6.png)

I hear you on this! Ultimately, the reason for this approach is we have an explicit goal of prioritizing the OAuth code host connections, with the access token as a purposeful alternative. In exploring possible directions, this approach results in the best balance of this priority with overall usability. 

>also the 'connect with code host' copy feels a bit terse

Any thoughts on alternate copy?

2021-03-16 12:42 UTC, quinnkeast approved these changes

2021-03-16 12:48 UTC, arussellsaw commented
you could delete the copy altogether, and move the buttons outside of the current list object, to directly below the title, and change the list object for github & gitlab to have a subheading of something like 'Or connect using an access token'

2021-03-16 16:20 UTC, merged