codeintel: rename correlation conversion and move to enterprise/lib
sourcegraph/sourcegraph pull request #18897
Opened 2021-03-05 03:19 UTC by shrouxm

2021-03-05 18:24 UTC, efritz requested changes

2021-03-05 18:24 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/helpers_test.go
> +	for _, packageReference := range packageReferences {
This loop turns an efficient batch insert into 10k+ round trips to the database.

2021-03-05 18:24 UTC, efritz commented on enterprise/lib/codeintel/semantic/types.go
> +// Package pairs a package name and the dump that provides it.
Why are these moved now but not before?

2021-03-05 18:24 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/helpers_test.go
> +	for _, packageReference := range packageReferences {
Can you do the conversion first and only call `UpdatePackageReferences` once?

2021-03-08 20:37 UTC, shrouxm commented on enterprise/lib/codeintel/semantic/types.go
> +// Package pairs a package name and the dump that provides it.
these aren't moved they're new! altho i forgot to update the comments. this is a version of the types in lsifstore without the dump ID, so that the 'semantic' library doesn't have to know anything about storage. pre migration, there were already a bunch of types in lsifstore where there was a type X, and then a type 'QualifiedX' which just paired X with a dump ID. in a future PR i want to consolidate all those types in one place and make their naming convention consistent

2021-03-08 20:40 UTC, shrouxm commented on enterprise/internal/codeintel/stores/dbstore/helpers_test.go
> +	for _, packageReference := range packageReferences {
this is only inefficient in test code, do we still care? UpdatePackageReferences accepts semantic.PackageReferences now, which don't have a dump ID so we'd need a separate method to batch insert package references for different dumps (which isn't something we do anywhere right now in non-test code).

2021-03-08 20:41 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/helpers_test.go
> +	for _, packageReference := range packageReferences {
I guess this is fine in test code (I didn't notice).

2021-03-08 20:41 UTC, efritz approved these changes

2021-03-08 20:58 UTC, merged