Surface LSIF supported langs
sourcegraph/sourcegraph pull request #19072
Opened 2021-03-11 21:29 UTC by macraig

Make LSIF indexers we recommend easily accessible from the Code intel doc root.

2021-03-12 08:42 UTC, olafurpg approved these changes
Good idea!

2021-03-15 15:22 UTC, emchap requested changes

2021-03-15 15:22 UTC, emchap commented on doc/code_intelligence/index.md
> +<a class="btn" href="references/indexers.md">LSIF supported languages</a>
Do we want to include the * ahead of the text as on the previous line for stylistic consistency?

2021-03-15 15:23 UTC, emchap commented on doc/code_intelligence/index.md
> +<a class="btn" href="references/indexers.md">LSIF supported languages</a>
(If that's intentional as a difference, ignore me—thank you for doing this!)

2021-03-15 19:41 UTC, macraig commented on doc/code_intelligence/index.md
> +<a class="btn" href="references/indexers.md">LSIF supported languages</a>
It's intentional as we usually mark the Quickstart or "Intro to..." with the start to indicate the first section a user should look at. Does that make sense?

2021-03-15 20:03 UTC, emchap commented on doc/code_intelligence/index.md
> +<a class="btn" href="references/indexers.md">LSIF supported languages</a>
Sounds good!

2021-03-15 20:03 UTC, emchap approved these changes

2021-03-22 18:20 UTC, macraig commented on doc/code_intelligence/index.md
> +<a class="btn" href="references/indexers.md">LSIF supported languages</a>
```suggestion
<a class="btn" href="references/indexers">LSIF supported languages</a>
```

2021-03-22 19:19 UTC, merged