Rename "default repos" to "indexable repos"
sourcegraph/sourcegraph pull request #19091
Opened 2021-03-12 10:10 UTC by ryanslade

Default repos doesn't really convey the intent anymore. It was
originally just listing repos from the default_repos table on
sourcegraph.com so that they would be indexed. We are now pulling in
repos from more places so calling it "default repos" is confusing. The
intent is still that any repo included in should be indexed.

2021-03-12 10:11 UTC, ryanslade commented on enterprise/internal/insights/discovery/all_repos_iterator_test.go
> +	autogold.Want("defaultRepoStoreListCalls0", int(1)).Equal(t, indexableRepoStoreListCalls)
@slimsag I wasn't sure how to change `defaultRepoStoreListCalls0` here

2021-03-12 15:22 UTC, efritz requested changes
I think there's a lot of unrelated import changes.

2021-03-12 15:22 UTC, efritz commented on enterprise/cmd/executor/internal/worker/mock_command_runner_test.go
> +	"sync"
These seem very wrong.

2021-03-12 15:23 UTC, unknwon approved these changes
Didn't look into code as I expect just bunch of renaming, but the idea SGTM!

2021-03-12 15:35 UTC, ryanslade commented on enterprise/cmd/executor/internal/worker/mock_command_runner_test.go
> +	"sync"
Ah, that's goimports trying to organise the imports and failing.. Not sure why it's not grouping stdlib imports together as it should

2021-03-12 19:10 UTC, rvantonder commented
@keegancsmith agree-I've been exploring defining queries for each kind of search, and "Default DotCom repositories" is one that definitely deserves it own designation. I've been using `DotComDefault` as a name for a `repo` query that queries this set.

2021-03-17 12:06 UTC, ryanslade commented
Closing this as there wasn't enough consensus at to whether this was an improvement :)

2021-03-17 12:06 UTC, closed without merging