add banner to announce postgres version deprecation
sourcegraph/sourcegraph pull request #19192
Opened 2021-03-16 20:15 UTC by davejrt

2021-03-16 20:24 UTC, daxmc99 commented
This is an issue or RFC we can link to this? I wasn't aware we were deprecating Postgres <11

2021-03-16 20:29 UTC, daxmc99 requested changes
I'm very concerned with how quickly we are requiring a db migration. Is there a reason for the urgency?

2021-03-16 20:29 UTC, daxmc99 commented on cmd/frontend/graphqlbackend/site_alerts.go
> +		return []*Alert{{TypeValue: AlertTypeInfo, MessageValue: "Support for Postgres v11.x and below will be deprecated from Sourcegraph v3.27. Please reach out to support@sourcegraph.com if you require
Typically we only show alerts like this to site-admins (they are likely the only ones that can do anything)

2021-03-16 20:29 UTC, daxmc99 commented on cmd/frontend/graphqlbackend/site_alerts.go
> +	if cv.Minor() == 26 {
Are we only providing a single version notice? This seems a bit concerning since even we have had issues migrating to new Postgres versions quickly.

2021-03-16 23:47 UTC, davejrt commented
> This is an issue or RFC we can link to this? I wasn't aware we were deprecating Postgres <11

There's a discussion here. This is blocking a bunch of codeintel work

2021-03-16 23:48 UTC, davejrt commented on cmd/frontend/graphqlbackend/site_alerts.go
> +	if cv.Minor() == 26 {
It was agreed that the majority of customers only have one .shot upgrade, with the exception of a few outliers who have already been informed and agreed to this with CE

2021-03-17 01:43 UTC, daxmc99 approved these changes
LGTM

2021-03-17 11:21 UTC, merged