search contexts: database ORM
sourcegraph/sourcegraph pull request #19249
Opened 2021-03-18 06:57 UTC by novoselrok

TODO

2021-03-19 08:05 UTC, keegancsmith requested changes
Nice work! Mostly LGTM, but I had a few comments inline I'd like to take another look at once addressed so requesting changes.

2021-03-19 08:05 UTC, keegancsmith commented on internal/database/search_contexts.go
> +`
cc @unknwon to review for auth correctness.

2021-03-19 08:05 UTC, keegancsmith commented on internal/database/search_contexts.go
> +	sort.Slice(out, func(i, j int) bool { return out[i].Repo.Name < out[j].Repo.Name })
rather sort by id?

2021-03-19 08:05 UTC, keegancsmith commented on internal/database/search_contexts.go
> +		revisions := repositoryIDsToRevisions[repoID]
```suggestion
	for repoID, revisions := range repositoryIDsToRevisions {
```

2021-03-19 08:05 UTC, keegancsmith commented on internal/database/search_contexts.go
> +	var out []*types.SearchContextRepositoryRevisions
```suggestion
	out := make([]*types.SearchContextRepositoryRevisions, 0, len(repositoryIDsToRevisions))
```

2021-03-19 08:11 UTC, novoselrok commented on internal/database/search_contexts.go
> +	return s.listSearchContexts(ctx, sqlf.Sprintf("namespace_user_id = %d", userID))
Correct, but for the MVP we will only have public contexts. Once we add full management capabilities, including creating private contexts, I'll refactor this part of the code to handle private contexts.

2021-03-19 08:52 UTC, novoselrok commented on internal/database/search_contexts.go
> +}
I hadn't really thought about it, but I think you have a point. In this case the columns don't change (and not shared with other packages), so there is no real benefit to writing them out separately. I'll inline them in the queries for now, and extract them when (if) needed.

2021-03-19 10:35 UTC, keegancsmith commented on internal/database/search_contexts.go
> +	return s.listSearchContexts(ctx, sqlf.Sprintf("namespace_user_id = %d", userID))
Ok that makes sense. One potential issue is you are inserting contexts with the public field. Maybe you should only add the public column once you support it. Or just always insert it with value true until you support it?

2021-03-19 10:36 UTC, keegancsmith approved these changes
Approving after discussion around public :) Maybe just wait on hearing back from @unknwon on auth before merging. Can probably follow-up in another PR if this isn't connected to user accessible UI yet.

2021-03-19 10:54 UTC, novoselrok commented on internal/database/search_contexts.go
> +	return s.listSearchContexts(ctx, sqlf.Sprintf("namespace_user_id = %d", userID))
Ok, always inserting with `Public: true` makes sense for now.

2021-03-21 15:02 UTC, unknwon commented on internal/database/search_contexts.go
> +`
Authz looks good, but I think the query does not exclude deleted repos.

```go
var getSearchContextRepositoryRevisionsFmtStr = `
SELECT sc.repo_id, sc.revision, r.name
FROM search_context_repos sc
JOIN
	(SELECT id, name FROM repo WHERE deleted_at IS NULL AND (%s)) r -- populates authzConds
	ON r.id = sc.repo_id
WHERE sc.search_context_id = %d
`
```

2021-03-22 10:30 UTC, unknwon approved these changes
Didn't review anything other than the small portion about authz :)

2021-03-22 14:44 UTC, stefanhengl approved these changes

2021-03-22 14:44 UTC, stefanhengl commented on internal/database/search_contexts.go
> +WHERE deleted_at IS NULL AND (%s)
Do we set `deleted_at` anywhere?

2021-03-22 14:44 UTC, stefanhengl commented on internal/database/search_contexts.go
> +	err = tx.SetSearchContextRepositoryRevisions(ctx, createdSearchContext.ID, repositoryRevisions)
Wondering whether it makes sense to create a context without `RepositoryRevisions`? If not we could combine this function with `createSearchContext`? Probably has benefits keeping them separated?

2021-03-22 15:05 UTC, novoselrok commented on internal/database/search_contexts.go
> +WHERE deleted_at IS NULL AND (%s)
Not yet, I preemptively used it here so that I don't forget it, once I add the functionality for deleting search contexts.

2021-03-22 15:09 UTC, novoselrok commented on internal/database/search_contexts.go
> +	err = tx.SetSearchContextRepositoryRevisions(ctx, createdSearchContext.ID, repositoryRevisions)
I extracted and exported `SetSearchContextRepositoryRevisions` because it will be used later on when editing repository revisions for a specific context.

2021-03-23 07:36 UTC, merged