Cache busting app.bundle.js
sourcegraph/sourcegraph pull request #19479
Opened 2021-03-26 11:15 UTC by umpox

2021-03-29 18:20 UTC, ggilmore commented
@umpox I just merged https://github.com/sourcegraph/sourcegraph/pull/19509 into this one. Could you take a look at https://github.com/sourcegraph/sourcegraph/pull/19509#discussion_r603507690 when you get a chance?

2021-03-30 10:10 UTC, umpox commented
> @umpox I just merged #19509 into this one. Could you take a look at [#19509 (comment)](https://github.com/sourcegraph/sourcegraph/pull/19509#discussion_r603507690) when you get a chance?

This should be working nicely now!

2021-03-30 10:54 UTC, umpox commented
@sourcegraph/frontend-devs Would be useful to get 👀  on the frontend part of this code 

The relevant issue: https://github.com/sourcegraph/sourcegraph/issues/19471

2021-03-30 12:19 UTC, pdubroy commented on client/web/webpack.config.js
> +    // Prevent memory leak: https://github.com/webpack/webpack-dev-server/issues/377#issuecomment-241258405
Nit: maybe better to not bury the lede here, and instead say something like:

```
Do not use [chunkhash] or [hash] for development -- see https://github.com/webpack/webpack-dev-server/issues/377#issuecomment-241258405
```

2021-03-30 13:53 UTC, eseliger reviewed
Looks legit so far, I've tinkered around with it a bit and built a version that reads from disk in local dev, so we don't need to recompile on a bundle change.
Not sure if you want to adopt this or so, but here's a comparison of what I did to get this to work. https://github.com/sourcegraph/sourcegraph/compare/app-bundle-cache-bust...es/dev-load-manifest-from-disk?expand=1
This could also be modified to ignore file not found errors in dev mode, or even just return the hard-coded values and not read from the file at all. (Is this the reason you had to commit an empty webpack manifest file?)

2021-03-31 09:34 UTC, umpox commented
@eseliger Thinking about this, I don't think we need to watch `app.html` and `webpack.manifest.json` at all.

The manifest will always be updated on disk as `writeToFileEmit` is set to `true` when using the plugin. We'll use that to bootstrap the initial `app.html` for local dev, and then those filenames aren't going to change onwards so we can just let webpack do its recompiling in the background.

2021-03-31 09:36 UTC, umpox commented on ui/assets/webpack.manifest.json
> +{}
Hopefully not! I see your branch handles scenarios where this file might not exist? I was trying to figure out if `go:embed` would allow that, my Go knowledge is quite limited 😁  Do we need separate files for `dev` and `prod`? It'd be nice if we could get this into a single function to keep the two environments as close as possible, and not commit this file 

@ggilmore Has more background on this code!

2021-03-31 09:48 UTC, umpox commented on client/web/package.json
> +      "path": "../../ui/assets/styles/app.*.bundle.css"
This just runs in CI, like here: https://buildkite.com/sourcegraph/sourcegraph/builds/91535#53f65b46-737e-4d9c-8075-58b28f7aa8b0/192.

I'm actually going to remove `bundlesize` here, it's not adding much value (unless devs always check build logs) and judging from https://github.com/sourcegraph/sourcegraph/issues/4339, it seems that it's not that useful to us

2021-03-31 09:54 UTC, umpox commented on client/web/package.json
> +      "path": "../../ui/assets/styles/app.*.bundle.css"
Also, Webpack in local dev doesn't write these files to disk and now doesn't hash either so it shouldn't lead to files building up :)

2021-04-06 08:14 UTC, umpox commented
Hey @ggilmore, could you please help me with some Go changes on this? Ideally we don't want to commit `webpack.manifest.json` at all, but I'm not sure if the original code using `go:embed` supports this? See https://github.com/sourcegraph/sourcegraph/pull/19479#discussion_r604746104

2021-04-06 17:30 UTC, umpox commented
I've updated to use `ioutil.readFile` for both environments as shown in the branch @eseliger made. Is this approach OK for production too? Moving this into review

2021-04-07 16:36 UTC, unknwon requested changes
Request changes because the current approach might hurt performance.

2021-04-07 16:36 UTC, unknwon commented on cmd/frontend/internal/app/ui/handlers.go
> +	manifest, err := assets.LoadWebpackManifest()
This is loading a file from disk upon every request? Seems not ideal, can we cache that? e.g. use `sync.Once`.

2021-04-07 16:36 UTC, unknwon commented on ui/assets/load-manifest.go
> +func LoadWebpackManifest() (m *WebpackManifest, err error) {
Is the comment block related to the `LoadWebpackManifest`? If so, the empty line seems problematic (i.e. remove it); if not... the comment block feels orphan 🤔

2021-04-11 17:08 UTC, unknwon commented on ui/assets/load_manifest_dist.go
> +		manifestContent, err := assetsFS.ReadFile("webpack.manifest.json")
@eseliger Do you know how I can test this change actually works in my local dev?

2021-04-11 17:10 UTC, unknwon commented on cmd/frontend/internal/app/ui/router.go
> +		common.Error = pageErrorContext
The deleted line is problematic that when there is an error returned from `newCommon`, this line is guaranteed to panic.

2021-04-11 17:14 UTC, unknwon approved these changes
Hey, all, I've pushed a commit to fix the Go-related build and tests errors.

There is a web file having conflicts, though.

2021-04-13 00:34 UTC, eseliger commented on ui/assets/load_manifest_dist.go
> +		manifestContent, err := assetsFS.ReadFile("webpack.manifest.json")
I think you can use `-tags dist` in the `./dev/go-install.sh` script

2021-04-13 00:36 UTC, eseliger commented
@unknwon how come you got rid of go:embed for the dist version of this in my previous attempt to implement this? As far as I understand our build process, this mainfest file will not be in the docker container, so it needs to be bundled with the binary 🤔  (Maybe I misunderstood this, though)

2021-04-13 13:44 UTC, unknwon commented
> @unknwon how come you got rid of go:embed for the dist version of this in my previous attempt to implement this? As far as I understand our build process, this mainfest file will not be in the docker container, so it needs to be bundled with the binary 🤔 (Maybe I misunderstood this, though)

@eseliger Because I saw we already bundled everything under "assets" here: https://github.com/sourcegraph/sourcegraph/blob/24f469353b4855defcb117ab6fd267cd095062f8/ui/assets/assets_dist.go#L10-L11

2021-04-13 13:50 UTC, unknwon commented on ui/assets/load_manifest_dist.go
> +		manifestContent, err := assetsFS.ReadFile("webpack.manifest.json")
Nice! Confirmed working.

2021-04-13 14:48 UTC, eseliger commented
> @eseliger Because I saw we already bundled/embeded everything under "assets" here:

Ahhh! I was just reading `ReadFile` and was like "oh now we read files again" - forgot it's a virtual FS 👀 

Thank you for cleaning it up! I think this is ready to 🚢 then @umpox !

2021-04-14 09:32 UTC, valerybugakov commented on client/web/webpack.config.js
> +    new WebpackManifestPlugin({ writeToFileEmit: true, fileName: 'webpack.manifest.json' }),
If we don't hash for development — does that mean that we can disable the `WebpackManifestPlugin` plugin in development and just use `scripts/app.bundle.js` that won't change between recompilations?

2021-04-14 09:32 UTC, valerybugakov commented on ui/assets/manifest.go
> +	AppCSSBundlePath *string `json:"app.css"`
Go beginner here: should both of these fields have the same type, either `string` or `*string`?

2021-04-14 09:32 UTC, valerybugakov commented on client/web/webpack.config.js
> +    new WebpackManifestPlugin({ writeToFileEmit: true, fileName: 'webpack.manifest.json' }),
According to docs, `WebpackManifestPlugin` will write info about all chunks to the manifest file too. We only use a couple of fields from it at the moment: 

```
AppJSBundlePath string `json:"app.js"`
AppCSSBundlePath string `json:"app.css"`
```

Does it make sense to use [filter](https://github.com/shellscape/webpack-manifest-plugin#filter) config option to limit the number of entries written to the disk? I should improve build performance because we have a lot of small chunks in the application bundle.

2021-04-14 09:32 UTC, valerybugakov commented on client/web/package.json
> -      "path": "../../ui/assets/scripts/app.bundle.js"
What's the reason for removing `bundlesize` as a part of this PR?
Is it possible to use fuzzy matching for bundle-size tracking?

2021-04-14 09:56 UTC, umpox commented on client/web/package.json
> -      "path": "../../ui/assets/scripts/app.bundle.js"
See https://github.com/sourcegraph/sourcegraph/pull/19479#discussion_r604754472, we don't effectively use `bundlesize` anymore

2021-04-14 10:14 UTC, umpox commented on client/web/webpack.config.js
> +    new WebpackManifestPlugin({ writeToFileEmit: true, fileName: 'webpack.manifest.json' }),
Good catch, we can use `isInitial` to only return files that are required to run the app. Have tested for prod and dev builds and it works well

2021-04-14 10:42 UTC, felixfbecker commented on client/web/package.json
> +      "path": "../../ui/assets/styles/app.*.bundle.css"
I've checked the build log output in the past for the bundle sizes to compare bundle sizes between before and after a change on a PR (e.g. Renovate library upgrade or webpack config change).
Does removing have any benefit?

2021-04-14 10:53 UTC, umpox commented on client/web/package.json
> +      "path": "../../ui/assets/styles/app.*.bundle.css"
I think if we keep it we should look to get it visible on PRs, as right now the benefit seems marginal and we can already better analyse our bundle with `webpack-bundle-analyzer`. Do you have some more context on https://github.com/sourcegraph/sourcegraph/issues/4339#issuecomment-601860008? I'd love to have this visible on PRs

2021-04-14 11:06 UTC, valerybugakov commented on client/web/webpack.config.js
> +    new WebpackManifestPlugin({ writeToFileEmit: true, fileName: 'webpack.manifest.json' }),
Any thoughts on disabling it for development env completely?

2021-04-14 11:14 UTC, umpox commented on client/web/webpack.config.js
> +    new WebpackManifestPlugin({ writeToFileEmit: true, fileName: 'webpack.manifest.json' }),
Oops sorry missed that, I personally think we should replicate the prod build as much as possible (unless there's a significant disadvantage to doing so). Otherwise we might not realise if this functionality breaks in some way until we do a release

2021-04-14 12:35 UTC, valerybugakov commented on client/web/webpack.config.js
> +    new WebpackManifestPlugin({ writeToFileEmit: true, fileName: 'webpack.manifest.json' }),
My main concern was rebuilds performance in the development env, but after testing it locally, it seems that the difference is negligible. And I agree with the point about keeping setup consistent between envs. 👍

2021-04-14 12:36 UTC, valerybugakov approved these changes
👍

2021-04-14 12:36 UTC, eseliger commented on ui/assets/manifest.go
> +	AppCSSBundlePath *string `json:"app.css"`
`*string` will be serialized by default as `null` in json where `string` will be `""` for an empty CSS bundle, so I guess it makes sense, but it would also be possible to define `omitempty` in the json tag

2021-04-14 12:41 UTC, eseliger approved these changes

2021-04-14 12:42 UTC, merged

2021-04-14 13:31 UTC, felixfbecker commented on client/web/package.json
> +      "path": "../../ui/assets/styles/app.*.bundle.css"
There is a benefit for specific cases where you want to check it (like those I mentioned above), but not for the use case of keeping tabs on the size at every PR similar to code coverage (that would be awesome). I don't have more context/memory here other than that the GitHub app was broken and didn't work anymore. Maybe that has changed.