Create authorization_and_authentication.md
sourcegraph/sourcegraph pull request #19758
Opened 2021-04-07 17:49 UTC by emchap

As part of a conversation around our current docs, attempting to pair authorization and authentication workflows together in a single doc for customer discoverability.

2021-04-07 17:55 UTC, emchap commented
@unknwon can you tell me why my buildkite check failed, also? :)

2021-04-08 16:30 UTC, unknwon requested changes
Also would love a review from @quinnkeast

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +1. The system through which your users log in (SAML IdP, OAuth with a code host, username/password, OpenId Connect, Authentication Proxy)
```suggestion
1. The system through which your users log in (SAML IdP, OAuth with a code host, username/password, OpenID Connect, Authentication Proxy)
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +Sourcegraph supports username/password auth by default and SAML, OAuth, HTTP Proxy auth, and OpenId Connect if configured. Changing a username in Sourcegraph will allow the user to escalate permissio
```suggestion
Sourcegraph supports username/password auth by default and SAML, OAuth, HTTP Proxy auth, and OpenID Connect if configured. Changing a username in Sourcegraph will allow the user to escalate permissions, so if you are syncing permissions, you will need to add:
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +If you use Github, Gitlab, or Bitbucket Server, you can sync access permissions directly from the code host. Information is included in the section for the code host below.
```suggestion
If you use GitHub, GitLab, or Bitbucket Server, you can sync access permissions directly from the code host. Information is included in the section for the code host below. 
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +This is Sourcegraph’s default authentication option. To enable it, add the to your site config:
```suggestion
This is Sourcegraph’s default authentication option. To enable it, add the following to your site config:
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +}
```suggestion
{
  // Other config settings go here
  "auth.providers": [
    {
      "type": "builtin",
      "allowSignup": true 
    }
  ]
}
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +More info [here](../auth/index.md#builtin-password-authentication).
```suggestion
More info about [builtin password authentication](../auth/index.md#builtin-password-authentication). 
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +### Github Enterprise or Github Cloud Authentication and Authorization
```suggestion
### GitHub Enterprise or GitHub Cloud authentication and authorization
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +Github supports both permissions syncing and authentication (through OAuth). If you use Github as your code host, we do not officially support using another authentication mechanism (SAML, etc.). Ins
```suggestion
We support both authentication and permissions syncing (through OAuth) for GitHub. If you use GitHub as your code host, we do not officially support using another authentication mechanism (SAML, etc.). Instead, you’ll need to follow this flow:
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +1. Use SAML (or another auth mechanism) to log in to Github
```suggestion
1. Use SAML (or another auth mechanism) to log in to GitHub
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +2. Use Github OAuth to log in to Sourcegraph
```suggestion
2. Use GitHub OAuth to log in to Sourcegraph
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +[Follow these steps to configure authentication with Github via OAuth](../auth/index.md#github).
```suggestion
[Follow these steps to configure authentication with GitHub via OAuth](../auth/index.md#github). 
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +Once that is configured, follow [these steps](../repo/permissions.md#github) to configure access permissions. Users will log into Sourcegraph using Github OAuth, and permissions will be synced in the
```suggestion
Once that is configured, follow [these steps to configure access permissions](../repo/permissions.md#github). Users will log into Sourcegraph using Github OAuth, and permissions will be synced in the background.
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +### Gitlab Enterprise or Cloud Authentication and Authorization
```suggestion
### GitLab Enterprise or GiLab Cloud authentication and authorization
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +Gitlab supports both permissions syncing and authentication (through OAuth). If you use Gitlab as your code host, you have two available authentication flows:
```suggestion
We support both authentication and permissions syncing (through OAuth) for GitLab. If you use GitLab as your code host, you have two available authentication flows:
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +1. Use SAML (or another auth mechanism) to log in to Gitlab
```suggestion
1. Use SAML (or another auth mechanism) to log in to GitLab
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +2. Use Gitlab OAuth to log in to Sourcegraph
```suggestion
2. Use GitLab OAuth to log in to Sourcegraph
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +In this way, access to Sourcegraph will still be managed by your identity provider, using the code host as a middle step. This option is the simplest to configure. To do so, follow [these instruction
```suggestion
In this way, access to Sourcegraph will still be managed by your identity provider, using the code host as a middle step. This option is the simplest to configure. To do so, [set up GitLab as an authentication option](../auth/index.md#gitlab), and then [enable permissions syncing](../repo/permissions.md#oauth-application).
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +Alternatively, you can configure SAML authentication in to Sourcegraph, and use Gitlab permissions syncing in the background to control access permissions. To implement this method, you will need to
```suggestion
Alternatively, you can configure SAML authentication in to Sourcegraph, and use GitLab permissions syncing in the background to control access permissions. To implement this method, you will need to make sure that GitLab is able to return a value in `identities.provider` for the `GET /users` endpoint ([GitLab documentation](https://docs.gitlab.com/ee/api/users.html#for-admins)) that your identity provider is able to pass as the `nameID` in the SAML response. If that isn’t possible, you will need to use the first option. 
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +To configure SAML auth with Gitlab permissions, you will need to first [configure permissions from Gitlab](../repo/permissions.md#administrator-sudo-level-access-token). Then, [configure SAML authent
```suggestion
To configure SAML auth with GitLab permissions, you will need to first [configure permissions from GitLab](../repo/permissions.md#administrator-sudo-level-access-token). Then, [configure SAML authentication](../auth/saml/index.md). The `nameID` passed by the identity provider will need to match the value of `identities.provider`. For example, if the GitLab API returns:
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +   ]
```suggestion
"identities": [
   {"provider": "saml", "extern_uid": "email@domain.com"}
]
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +}
```suggestion
{
  "url": "https://gitlab.com",
  "token": "$PERSONAL_ACCESS_TOKEN",
  "authorization": {
    "identityProvider": {
      "type": "external",
      "authProviderID": "$AUTH_PROVIDER_ID",
      "authProviderType": "$AUTH_PROVIDER_TYPE",
      "gitlabProvider": "saml"
    }
  }
}
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +And configure the identity provider to pass the email address as the `nameId`.
```suggestion
And configure the identity provider to pass the email address as the `nameID`. 
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +### Bitbucket Server Authorization
```suggestion
### Bitbucket Server authorization
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +We do not currently support OAuth for Bitbucket Server. You will need to combine permissions syncing from Bitbucket Server with another auth mechanism (SAML, built-in auth, HTTP authentication proxie
```suggestion
We do not currently support OAuth for Bitbucket Server. You will need to combine permissions syncing from Bitbucket Server with another auth mechanism (SAML, built-in auth, HTTP authentication proxies). Bitbucket Server only passes usernames to Sourcegraph, so you’ll need to make sure that those usernames are matched by whatever mechanism you chose to use for access.
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +2. [Configure SAML authentication](../auth/saml/index.md). If you are using Bitbucket server, the `login` attribute is *not* optional—you need to pass the Bitbucket username as the `login` attribute.
```suggestion
2. [Configure SAML authentication](../auth/saml/index.md). If you are using Bitbucket Server, the `login` attribute is *not* optional—you need to pass the Bitbucket Server username as the `login` attribute. 
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +3. [Configure an HTTP authentication proxy](../auth/index.md#http-authentication-proxies), passing the Bitbucket username value as the `usernameHeader`.
```suggestion
3. [Configure an HTTP authentication proxy](../auth/index.md#http-authentication-proxies), passing the Bitbucket Server username value as the `usernameHeader`. 
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +### Explicit Permissions API Authorization
```suggestion
### Explicit Permissions API authorization
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +With any authentication mechanism, you can use our graphQL API to set permissions for all repositories. If you choose to do this, this is the *only* mechanism that can be used for permissions—all oth
```suggestion
With any authentication mechanism, you can use our GraphQL API to set permissions for all repositories. If you choose to do this, this is the *only* mechanism that can be used for permissions—all others will be ignored. Follow [these instructions](../repo/permissions.md#explicit-permissions-api) for the mutations needed within the GraphQL API to configure access.
```

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +### OpenId Connect Authentication
```suggestion
### OpenID Connect authentication
```

BTW, why is this section not above any other authorization sections?

2021-04-08 16:30 UTC, unknwon commented on doc/admin/config/authorization_and_authentication.md
> +### HTTP Authentication Proxy Authentication
```suggestion
### HTTP authentication proxy authentication
```

Same question

2021-04-08 16:31 UTC, unknwon commented
Thanks for the docs! Overall this looks great ❤️

2021-04-08 16:36 UTC, emchap commented
@unknwon Thank you! Added in your changes, thank you for them. :) Added Quinn as a reviewer as well.

I remain unsure why my buildkite check is failing, womp. Will wait on Quinn's review and then sort out whatever it is I broke.

2021-04-08 16:41 UTC, unknwon commented
<img width="283" alt="CleanShot 2021-04-09 at 00 41 22@2x" src="https://user-images.githubusercontent.com/2946214/114064520-5151d580-98cc-11eb-8f24-768c4f975515.png">

![](https://media4.giphy.com/media/gE6IUBRWZd744/giphy.gif)

2021-04-08 16:42 UTC, unknwon commented
The build error is

```

admin/config/authorization_and_authentication.md: disconnected page (no inlinks from other pages)
1 problems found
```

meaning this page is not linked by any other page, which is undiscoverable.

2021-04-08 16:48 UTC, emchap commented
@unknwon OH. Well, easy fix! Thank you. :)

2021-04-09 07:48 UTC, quinnkeast approved these changes
I ran amok. 🙈

Most of my suggestions are simple style changes to improve clarity. Note that two suggestions need follow-through, and I wasn't totally sure how to approach the anchor linking, so I left it out.

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +Sourcegraph has two authentication concepts to be mindful of:
```suggestion
Sourcegraph has two authentication concepts:
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +We suggest configuring both to use Sourcegraph Enterprise. If you do not configure permissions, all users will be able to see all of the code in the instance.
```suggestion
We suggest configuring both when using Sourcegraph Enterprise. If you do not configure permissions, all users will be able to see all of the code in the instance.
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +If you use GitHub, GitLab, or Bitbucket Server, you can sync access permissions directly from the code host. Information is included in the section for the code host below.
Proposal:

>If you use GitHub, GitLab, or Bitbucket Server, you can [sync access permissions directly from the code host](#). ~Information is included in the section for the code host below.~

We should generally [avoid directional language](https://about.sourcegraph.com/handbook/communication/content_guidelines/style_and_mechanics#avoid-directional-language). Instead, it'd be ideal to [link directly to the section as part of the sentence](https://about.sourcegraph.com/handbook/communication/content_guidelines/actionable_language#links).

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +If you do not use one of those listed code hosts, you will need to control access using our explicit permissions API, discussed below.
>If you do not use one of those listed code hosts, you will need to [control access using our explicit permissions API](#).

Same as the previous convention.

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +Sourcegraph does not support email-style usernames. In contexts in which you are providing the username to Sourcegraph, it will be normalized, which can impact username matching where that is relevan
```suggestion
Sourcegraph does not support email-style usernames. In contexts in which you are providing the username to Sourcegraph, it will be normalized, which can impact username matching where that is relevant. See [full documentation for username normalization](../auth/index.md#username-normalization).
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +This is Sourcegraph’s default authentication option. To enable it, add the following to your site config:
```suggestion
Built-in username/password authentication is Sourcegraph’s default authentication option. To enable it, add the following to your site config:
```

I just realized this particular convention isn't in the content guidelines (I'll add it), but where a {thing} is stated in a headline, we should avoid starting the paragraph with "This," as it's not necessarily clear what "This" refers to, particularly when readers have English as a second language.

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +More info about [builtin password authentication](../auth/index.md#builtin-password-authentication).
```suggestion
More info about [built-in password authentication](../auth/index.md#builtin-password-authentication). 
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +[Follow these steps to configure authentication with GitHub via OAuth](../auth/index.md#github).
```suggestion
Follow these steps to [configure authentication with GitHub via OAuth](../auth/index.md#github). 
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +Once that is configured, follow [these steps to configure access permissions](../repo/permissions.md#github). Users will log into Sourcegraph using Github OAuth, and permissions will be synced in the
```suggestion
Once authentication with GitHub via OAuth is configured, follow [these steps to configure access permissions](../repo/permissions.md#github). Users will log into Sourcegraph using Github OAuth, and permissions will be synced in the background.
```

Similar to the "this" convention, "that" here may be ambiguous.

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +Alternatively, you can configure SAML authentication in to Sourcegraph, and use GitLab permissions syncing in the background to control access permissions. To implement this method, you will need to
```suggestion
Alternatively, you can configure SAML authentication in Sourcegraph, and use GitLab permissions syncing in the background to control access permissions. To implement this method, you will need to make sure that GitLab is able to return a value in `identities.provider` for the `GET /users` endpoint ([GitLab documentation](https://docs.gitlab.com/ee/api/users.html#for-admins)) that your identity provider is able to pass as the `nameID` in the SAML response. If that isn’t possible, you will need to use the first option. 
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +We do not currently support OAuth for Bitbucket Server. You will need to combine permissions syncing from Bitbucket Server with another auth mechanism (SAML, built-in auth, HTTP authentication proxie
```suggestion
We do not currently support OAuth for Bitbucket Server. You will need to combine permissions syncing from Bitbucket Server with another authentication mechanism (SAML, built-in auth, HTTP authentication proxies). Bitbucket Server only passes usernames to Sourcegraph, so you’ll need to make sure that those usernames are matched by whatever mechanism you choose to use for access.
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +To sync Bitbucket server permissions, follow [these instructions](../repo/permissions.md#bitbucket-server). Then, do one of the following:
```suggestion
Follow the steps to [sync Bitbucket server permissions](../repo/permissions.md#bitbucket-server). Then, do one of the following:
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +2. [Configure SAML authentication](../auth/saml/index.md). If you are using Bitbucket Server, the `login` attribute is *not* optional—you need to pass the Bitbucket Server username as the `login` att
```suggestion
2. [Configure SAML authentication](../auth/saml/index.md). If you are using Bitbucket Server, the `login` attribute is *not* optional. You need to pass the Bitbucket Server username as the `login` attribute. 
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +With any authentication mechanism, you can use our GraphQL API to set permissions for all repositories. If you choose to do this, this is the *only* mechanism that can be used for permissions—all oth
```suggestion
With any authentication mechanism, you can use our GraphQL API to set permissions for all repositories. If you choose to do this, this is the *only* mechanism that can be used for permissions—all others will be ignored. Follow the instructions for the [mutations needed within the GraphQL API](../repo/permissions.md#explicit-permissions-api) to configure access.
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +Use this option if accessing using OpenID Connect, such as when logging in through a Google Workspace, or if other auth methods aren’t an option. [See setup instructions here](../auth/index.md#openid
```suggestion
Use OpenID Connect authentication if accessing using OpenID Connect, such as when logging in through a Google Workspace, or if other authentication methods aren’t an option. See [how to set up OpenID Connect authentication](../auth/index.md#openid-connect).
```

2021-04-09 07:48 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +This is not generally recommended unless this is a common authentication process within your organization. [See configuration instructions here](../auth/index.md#http-authentication-proxies).
```suggestion
HTTP authentication proxy authentication is not generally recommended unless it's a common authentication process within your organization. See [how to configure HTTP authentication proxies](../auth/index.md#http-authentication-proxies).
```

2021-04-09 20:40 UTC, emchap commented on doc/admin/config/authorization_and_authentication.md
> +This is Sourcegraph’s default authentication option. To enable it, add the following to your site config:
Super solid, thanks.

2021-04-09 20:41 UTC, emchap commented on doc/admin/config/authorization_and_authentication.md
> +More info about [builtin password authentication](../auth/index.md#builtin-password-authentication).
@quinnkeast Style question—I'm using `builtin` here because that's the name of the attribute in the site config (styled in that way). Do we still want to change this?

2021-04-10 21:00 UTC, unknwon approved these changes

2021-04-12 07:58 UTC, quinnkeast commented on doc/admin/config/authorization_and_authentication.md
> +More info about [builtin password authentication](../auth/index.md#builtin-password-authentication).
Shoot, this is a tricky one. Looking at the docs, the way we're using it right now is as a noun, "Builtin," rather than an adjective, "built-in." I'm not sure that's what we want to be doing, but I'm also not 100% comfortable changing it outright...

Options:
1. Use "built-in" everywhere except for the attribute in the config itself, where we keep `builtin`. Correct, but potential source of error if users assume the attribute is `built-in`.
2. Use "builtin" everywhere. Consistent, but also looks like a writing error, which I feel reflects poorly on "Sourcegraph's attention to detail" and the design principle "[trust is earned](https://about.sourcegraph.com/handbook/product/design_principles)."
3. Use a mix. I'd prefer not.

I lean towards #1. Wdyt?

2021-04-12 16:45 UTC, emchap commented on doc/admin/config/authorization_and_authentication.md
> +More info about [builtin password authentication](../auth/index.md#builtin-password-authentication).
@quinnkeast Option #1 seems fine to me! :) Went ahead and changed it to be built-in in text and `builtin` when referencing the attribute. I agree with you the "right" option looks wrong.)

2021-04-12 16:50 UTC, emchap commented
Okay I _think_ I got everything everyone mentioned. Thanks @quinnkeast and @unknwon—your edits made this much better! :)

2021-04-12 16:51 UTC, merged