Custom away prompt
sourcegraph/sourcegraph pull request #19864
Opened 2021-04-09 05:22 UTC by artemruts

### Description

Fixes https://github.com/sourcegraph/sourcegraph/issues/19832

### Todo

- [ ] confirm functionality with @quinnkeast 
- [ ] confirm general implementation with FE Plats
- [ ] mark as ready to review

### Demo

https://user-images.githubusercontent.com/1319181/114132189-e2777b00-98d1-11eb-82e1-83562316d403.mov

2021-04-09 07:29 UTC, quinnkeast requested changes
Looking great!

Only thing for this specific use: [the "OK" button should match the heading, and instead say "Discard."](https://about.sourcegraph.com/handbook/communication/content_guidelines/actionable_language#confirmation-messages)

2021-04-09 14:52 UTC, artemruts commented
> Looking great!
> 
> Only thing for this specific use: [the "OK" button should match the heading, and instead say "Discard."](https://about.sourcegraph.com/handbook/communication/content_guidelines/actionable_language#confirmation-messages)

Fixed

2021-04-09 15:06 UTC, artemruts commented
@sourcegraph/frontend-devs

I'm looking for an acceptable way to prevent away navigations with the  `react-router`'s `Prompt` component.  
Please see #19832

#### Observations

1. Passing JSON string to `Prompt` to have multiple messages/labels in not ideal, hard to validate.
2. Prompt will catch all `history` based navigation attempts, I have to use something like this:

`history.push(path, ALLOW_NAVIGATION)` and check for `ALLOW_NAVIGATION` in the `Prompt` to skip showing popup when the navigation is intentional (programmatic).

#### Notes

This was written very quickly and I'm looking for:
1. different approaches or ideas on how to improve this
2. potential problems with this approach

2021-04-09 16:56 UTC, umpox commented
A potential different, more flexible approach would be to use `history.block`: https://github.com/ReactTraining/history/blob/master/docs/blocking-transitions.md

E.g. <UserConfirmationModal />` could call `history.block` when mounted. I think this would give us better control of how we pass props and control different states of navigation

Does this currently handle events such as the user attempting to close the tab? I can't remember if react router supports that out of the box or if we'd need a `beforeunload` listener.

We should be able to use [React Portals](https://reactjs.org/docs/portals.html) to render `UserConfirmationModal`

2021-04-09 20:18 UTC, artemruts commented
> A potential different, more flexible approach would be to use `history.block`: https://github.com/ReactTraining/history/blob/master/docs/blocking-transitions.md
> 
> E.g. `<UserConfirmationModal />` could call `history.block` when mounted. I think this would give us better control of how we pass props and control different states of navigation
> 
> Does this currently handle events such as the user attempting to close the tab? I can't remember if react router supports that out of the box or if we'd need a `beforeunload` listener.
> 
> We should be able to use [React Portals](https://reactjs.org/docs/portals.html) to render `UserConfirmationModal`

Thanks @umpox, I'll take a look and make a demo!

2021-04-12 19:59 UTC, artemruts commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
> +            if (didRepoSelectionChange()) {
@umpox Hey, Tom, `history.block` definitely works. Thank you!  

Still not sure about a portals here, `@react/dialog` is already a portal.  
What would be a downside rendering that way?

2021-04-12 23:10 UTC, artemruts commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
> +            if (didRepoSelectionChange()) {
> E.g. <UserConfirmationModal /> could call history.block when mounted. I think this would give us better control of how we pass props and control different states of navigation

I'll move all of the logic into a single component and check how it looks

2021-04-13 02:24 UTC, artemruts commented on client/web/src/user/settings/repositories/UserAwayConfirmationModal.tsx
> +            }
@umpox moved everything into a single component, no need for portals, `<Dialog />` is already a portal.

Do you know if there would be a better way for `history.block` to ignore _some_ programmatic navigations?
E.g. I don't want to block if the `history` changed not on user action but in some callback via `history.push` 🤔 
Right now, I do something I'm not a fan of:

```js
history.push(myPath, "allow"); 
```

2021-04-13 20:33 UTC, tjkandala reviewed
I read through the `history.block` implementation and it doesn't look like there's any builtin way to ignore some programmatic navigations. 

However, I like what you've already built with the `predicate`; maybe we could pass a more general `predicate` that determines whether navigation is allowed given the React component state?

2021-04-13 20:33 UTC, tjkandala commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
>                                  // cancel the repeatUntil
Could we store a `allCodeHostsSynced`-like React state, set that here, and conditionally render a `<Redirect>` when that's true (also checking for it in the `UserAwayConfirmationModal` predicate?)

2021-04-13 22:49 UTC, artemruts commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
>                                  // cancel the repeatUntil
TJ, that's an excellent idea! Thank you, will make changes now.

2021-04-14 04:22 UTC, artemruts commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
>                                  // cancel the repeatUntil
TJ, I think I'll re-test current changes a few more times and probably merge.  
Started working on a proposed solution but maybe will need to schedule 15 min to sync with you. 

https://github.com/sourcegraph/sourcegraph/compare/ar/custom-router-prompt-better?expand=1

There's a tiny stale state problem, `changesSaved` is always outdated 🤔

2021-04-14 15:25 UTC, tjkandala commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
>                                  // cancel the repeatUntil
What happens if we render the `<Redirect>` after the `<AwayPrompt>`? Is it possible that the registered "blocker" is stale?

2021-04-14 16:58 UTC, artemruts commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
>                                  // cancel the repeatUntil
No luck with the callback ref approach we discussed on Slack, there’s a way to completely ignore `<Redirect>`  by using the `useLayoutEffect` in the `AwayPrompt` but it seems hacky :(

2021-04-14 17:10 UTC, tjkandala commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
>                                  // cancel the repeatUntil
What do you mean by "ignore `<Redirect>`? I'd guess that `useLayoutEffect` would allow us to register the latest blocker before the `<Redirect>` is rendered, which is the desired behavior. If so, `useLayoutEffect` sounds like a better solution than the callback ref approach (if it worked) because `AwayPrompt` would then be easily reusable.

2021-04-14 17:23 UTC, artemruts commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
>                                  // cancel the repeatUntil
With the use of `useLayoutEffect`, `AwayPrompt` never has time to get into the `history.block` callback (from my observations)

2021-04-14 18:50 UTC, unknwon approved these changes
I can't speak for web code, but the demo looks great!

2021-04-14 19:32 UTC, artemruts commented
I'll merge as is since it's time sensitive but:
- will create a spike to see how the [following](https://github.com/sourcegraph/sourcegraph/compare/ar/custom-router-prompt-better?expand=1) implementation can be improved and if it's worth it

2021-04-14 19:41 UTC, merged