Index all revisions referenced by search contexts
sourcegraph/sourcegraph pull request #20064
Opened 2021-04-15 18:59 UTC by camdencheek

This commit adds all of the revisions used by search contexts to the
list of revisions to index.

Fixes #19958

2021-04-15 19:04 UTC, camdencheek commented on internal/database/search_contexts.go
> +	if a := actor.FromContext(ctx); a == nil || !a.Internal {
I think it's reasonable to require that this is only called with an internal actor. Since this is necessarily not scoped to any user or org, we don't want this to be accessible by a normal user.

2021-04-15 19:05 UTC, camdencheek commented on internal/database/search_contexts.go
> +`
I'd appreciate eyes on this -- my SQL is a little rusty 😄

2021-04-16 06:04 UTC, novoselrok commented on internal/database/search_contexts.go
> +`
I think it's fine, I was a bit confused by the `JOIN`, but I realized we have to filter out deleted search contexts 😄

2021-04-16 06:06 UTC, novoselrok commented
@camdencheek I think the changes look OK, I still tagged @sourcegraph/search-core to review, because I don't have that much experience with this part of the code 🙂

2021-04-16 11:53 UTC, keegancsmith requested changes
can we avoid adding a direct dependency on database.SearchContexts in the `search/backend` pkg? For example see how we pass in `getRepoIndexOptions` to avoid a dependency on gitserver. I would add a new field to `RepoIndexOptions` called `GetExtraIndexedRevisions` or something like that. You also avoid the need to mock GetAllRevisionsForRepo then, and just independently unit test it.

2021-04-16 11:53 UTC, keegancsmith commented on internal/database/search_contexts.go
> +`
what values are valid for scr.revision? Can it be the empty string or HEAD? If so that is fine, since we use the same strings to indicate default branch :)

Otherwise query looks good. I think postgres should be able to execute this quickly :)

2021-04-16 12:18 UTC, novoselrok commented on internal/database/search_contexts.go
> +`
Yep, both of those values should be valid now and in the future.

2021-04-16 14:33 UTC, camdencheek commented on internal/database/search_contexts.go
> +`
@novoselrok I'll add a comment so the `JOIN` is easier to understand at a glance

2021-04-19 15:35 UTC, novoselrok approved these changes

2021-04-19 15:35 UTC, novoselrok commented on internal/database/search_contexts.go
> +	if Mocks.SearchContexts.GetAllRevisionsForRepo != nil {
I think you're not using these mocks anymore? If so, you can remove them.

2021-04-19 16:24 UTC, merged