Update Bootstrap to match redesign colors
sourcegraph/sourcegraph pull request #20093
Opened 2021-04-16 15:59 UTC by umpox

2021-04-20 12:25 UTC, umpox commented on client/branded/src/global-styles/buttons-redesign.scss
> +    $theme-colors: map-remove($theme-colors, 'primary', 'secondary', 'success', 'info', 'danger', 'warning', 'merged');
Note:

I originally used the Bootstrap mixins `button-variant` and `button-outline-variant` to try to configure these buttons. Unfortunately the level of customisation that bootstrap offers is not enough to effectively implement the redesign changes, primarily because Bootstrap makes a lot of assumptions about generating different colors for different button states. Instead of trying to almost overwrite everything with specificity, we ensure that Bootstrap does not create any variants for the redesign, and we have full freedom to style these ourselves

2021-04-20 13:49 UTC, eseliger approved these changes
Batch Changes change lgtm

2021-04-20 13:51 UTC, eseliger commented
There seem to be quite a few visual regressions in chromatic

2021-04-20 13:52 UTC, umpox commented
Thanks @eseliger, will fix!

2021-04-21 08:46 UTC, umpox commented on client/branded/src/global-styles/buttons-redesign.scss
> +@mixin redesign-button-variant(
Note: The buttons were a little problematic to get right alongside our current Bootstrap implementations.

I initially looked at scoping new `btn` styles under `theme-redesign` with the Bootstrap mixins `button-variant` and `button-outline-variant`. Unfortunately these make a lot of assumptions that are far away from our design, and it causes more trouble that it is worth to override these. 

Ideally we just want to write our own styles for these variants and not have to consider Bootstrap for these variants. I looked at scoping the current Bootstrap buttons to `:not(.theme-redesign`) and re-importing it after removing variants from `theme-colors` (ensuring Bootstrap does not create any button variants). This would work well, but it changes the specificity of our Bootstrap buttons, and has implications across the entire app where we are overriding this.

The approach here feels like the cleanest and most flexible one, interested to hear any thoughts on this

2021-04-21 08:48 UTC, umpox commented on client/branded/src/global-styles/colors-redesign.scss
> +$redesign-gray-06: #798baf;
This change is derived from the refresh changelog https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=966%3A9534. This was made before we started creating new issues for changes

2021-04-21 08:51 UTC, umpox commented on client/branded/src/global-styles/colors-redesign.scss
> -@if $bootstap-use-redesign-variables {
Removed as using `theme-colors-redesign`, and applying specific styles, means these variables should have minimal affect. The more significant ones have been moved to CSS variables

2021-04-21 08:52 UTC, umpox commented on client/branded/src/global-styles/colors-redesign.scss
> +    --info-2: #b8e3e8;
Closes https://github.com/sourcegraph/sourcegraph/issues/20172

2021-04-21 08:52 UTC, umpox commented on client/branded/src/global-styles/colors-redesign.scss
> +    --light-text: #{$white};
Closes https://github.com/sourcegraph/sourcegraph/issues/20092

2021-04-21 11:10 UTC, valerybugakov requested changes
New buttons look awesome!
If the inconsistencies I noticed you've already discussed with the design team and they just haven't been updated in Figma yet, let me know.

2021-04-21 11:10 UTC, valerybugakov commented on client/branded/src/global-styles/buttons-redesign.scss
> +    .btn-secondary,
Not sure if this is intentional and which version is correct. In mockups, `secondary button small` doesn't have a border, whereas the `secondary button regular` has in the disabled  state:

Small:
<img width="91" alt="Screenshot 2021-04-21 at 14 00 06" src="https://user-images.githubusercontent.com/3846380/115543604-2310c480-a2d4-11eb-9915-9b14f90f779c.png">

Regular:
<img width="109" alt="Screenshot 2021-04-21 at 13 59 55" src="https://user-images.githubusercontent.com/3846380/115543582-1ee4a700-a2d4-11eb-9255-f90013001f02.png">

cc @sourcegraph/design

2021-04-21 11:10 UTC, valerybugakov commented on client/storybook/src/preview.ts
> +}
Thanks 🙌
I wanted to add the same things.

2021-04-22 09:43 UTC, umpox commented on client/branded/src/global-styles/buttons-redesign.scss
> +            }
Yep, good eye thank you! Only on hover in light mode I believe

2021-04-22 09:57 UTC, umpox commented on client/branded/src/global-styles/GlobalStylesStory/ButtonVariants.tsx
> +)
I've raised this on Figma. I've included `btn-link` in the Storybook page for now as we're using it quite a lot and it seems quite similar to these styles.

Figma thread: https://www.figma.com/file/NIsN34NH7lPu04olBzddTw?node-id=908:2513#76061213

If we do restyle `btn-link` like this I think there will be a lot of regressions and that padding significantly changes. Unless I'm missing some other class that we use for this style 🤔

2021-04-22 09:59 UTC, umpox commented on client/branded/src/global-styles/buttons-redesign.scss
> +    .btn-secondary,
Good catch! Interested to hear your thoughts @sourcegraph/design

2021-04-22 10:05 UTC, felixfbecker commented on client/branded/src/global-styles/GlobalStylesStory/ButtonVariants.tsx
> +)
`btn-link` uses the `btn` padding for consistency (I think technically `btn` adds it), but it's easy to compose it with `p-0` to remove padding. I'd keep it as-is like you did

2021-04-22 10:08 UTC, umpox commented on client/branded/src/global-styles/buttons-redesign.scss
> +                @at-root #{selector-append('.theme-light', &)} {
`@at-root` output: `.theme-redesign.theme-light`
`.theme-light & {` output: `.theme-redesign .theme-light`

Unless I've overlooked something, I don't think it is possible to achieve the same with your version?

2021-04-22 10:08 UTC, umpox commented on client/branded/src/global-styles/border-radius.scss
> +:root .theme-redesign {
Yep! Thanks!

2021-04-22 12:38 UTC, felixfbecker commented on client/branded/src/global-styles/buttons-redesign.scss
> +                @at-root #{selector-append('.theme-light', &)} {
Ohh I see. I.e. it's more like `.theme-light&` but that's probably not possible?

2021-04-22 20:13 UTC, rrhyne commented on client/branded/src/global-styles/buttons-redesign.scss
> +    .btn-secondary,
I believe I've corrected this issue. There were several places wherein Figma secondary buttons were using color-bg-X instead of secondary-0X classes. This has been corrected in the Figma. If you have used that here could you correct?

2021-04-22 22:13 UTC, 5h1rU commented
@umpox Amazing work. 💪 🎉

The only question that I have is regarding the border-radius on the buttons. I took a look at the storybook and the "border-radius: 3px" [(see Figma)](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=875%3A585) is not applied.

2021-04-23 14:56 UTC, umpox commented on client/branded/src/global-styles/buttons-redesign.scss
> +    .btn-secondary,
Just updating this now! Thoughts on the rest of the buttons?

2021-04-26 08:06 UTC, umpox commented on client/branded/src/global-styles/buttons-redesign.scss
> +    .btn-secondary,
I've updated the borders of the disabled state and rest of the buttons. Keen to get this merged so we can discuss further contrast changes in the later design review

2021-04-26 08:10 UTC, umpox commented
Thanks @5h1rU, it was set to 4px but I think the designs have changed this

2021-04-26 09:30 UTC, valerybugakov approved these changes
Thanks for improving the `ButtonVariants` story. Looks awesome!

2021-04-26 09:30 UTC, valerybugakov commented on client/branded/src/global-styles/GlobalStylesStory/ButtonVariants.tsx
> +                    className={classNames('btn', `${variantType}-${variant}`, small && 'btn-sm')}
nit: to reduce duplication, `classNames(...)` might be extracted into a variable and reused across elements.

```tsx
const className = classNames('btn', `${variantType}-${variant}`, small && 'btn-sm')

return (
  <button className={className} />
  <button className={classNames(className, 'focus')} />

2021-04-26 09:30 UTC, valerybugakov commented on client/branded/src/global-styles/GlobalStylesStory/ButtonVariants.tsx
> +    variants: readonly string[]
nit: it's possible to make it narrower with `variants: typeof SEMANTIC_COLORS[number][]`

2021-04-26 12:15 UTC, merged