lsif/protocol: draft implementation of documentation extension
sourcegraph/sourcegraph pull request #20108
Opened 2021-04-17 00:35 UTC by slimsag

This is a draft implementation of a documentation extension for LSIF.

The aim of this extension is to enable LSIF indexers to produce API documentation
that is competitive with the API documentation offered in some languages today
through various websites such as:

* (Go) https://pkg.go.dev
* (Rust) https://docs.rs
* (Java) https://javadoc.io
* (Zig) https://ziglang.org/documentation/master/std/#builtin

This will be an LSIF-only extension, not an extension to LSP. The motivation for
doing this is outlined in https://github.com/slimsag/language-server-protocol/pull/1

**Coming soon:** This same thing, but in actual LSIF spec format not as a Go implementation.

Helps sourcegraph/sourcegraph#19389

Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>

2021-04-20 22:34 UTC, efritz requested changes
This looks reasonable but I want to wait until after our meeting tomorrow to figure out a few things like namespacing extension labels, etc.

2021-04-20 22:36 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	DocumentationUnexported DocumentationTag = "unexported"
I actually like that theres the option of `unexported`. Makes it useful for more than just consumers, but also internal producers :slightly_smiling_face:

2021-04-20 22:38 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	DocumentationUnexported DocumentationTag = "unexported"
My thinking here is that the web UI for this could expose check boxes or these tags, so if you check `Unexported` you will see docs for unexported/internal things in packages.

2021-04-20 22:43 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
From the LSIF spec:
> we introduced the definition result vertex for two reasons:
> 1. ...
> 1. To have support for languages where a definition can be spread over multiple ranges or even multiple documents. To support multiple documents ranges are added to a definition result using an 1:N item edge. Conceptually a definition result is an array to which the item edge adds items.

Whats the imagined flow here? Would it just work as-is today (show the different defs and let the user choose?). I dont have anything major here, more a curiosity of if the fact its a 1:N defResult to range mapping was in mind, if any caveats exist that I havent thought of that someone else mightve.

2021-04-20 22:48 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
Yes, it would "just work" in my mind. The idea here is that the `Range` here (the map key) maps to a definition result, which itself may contain N actual definitions in code in arbitrary locations. So this is not super different than it works in Sourcegraph today: you hover over something, get multiple definitions back and the user gets to choose.

Possible I've missed something though, if I am misreading anything let me know :D

2021-04-20 22:50 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
Thats pretty much in-line with how Im thinking of it too :slightly_smiling_face:

2021-04-20 22:53 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Title InteractiveMarkupContent `json:"title"`
Also just want to call out: this title has a dual-purpose.

One usage of it would be e.g. rendering a plain text version of the title in e.g. a search autocomplete box, or "index" section on a page like this, where the interactive and markdown parts would not be respected:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/3173176/115473276-4bbf8e00-a1f0-11eb-8077-5f27cd51675c.png">

The other use will be rendering the actual header for this documentation section, for example a function signature:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/3173176/115473379-7c072c80-a1f0-11eb-9308-41414b9660e2.png">

In our case, it would just be `func ServeFile(w ResponseWriter, r *Request, name string)` with no code block. And every type/variable name here could have hover, go-to-definition, find-references support.

2021-04-20 22:58 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
Heres a thought actually, does this accomodate for external symbols aka symbols referenced by monikers? If so, that should be outlined in the comment

2021-04-20 23:07 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
Yes, it does. I didn't call this out specially, because this is conceptually no different than interacting with a code document via `textDocument/hover` for example. The only difference is that you are interacting with some arbitrary (possibly generated) documentation, rather than a text document in the workspace.

The result is identical, though: a hover result, definition result, references result, etc. Just the same way you could interact with a document in a workspace and get reference to an external symbol, you could here.

2021-04-20 23:28 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
Okay so just so I have it clear and know Im on the same page, its perfectly ok to have a moniker vertex ID as a value for a range here, not just a definitionResult vertex ID?

2021-04-20 23:36 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
Oh! No, my expectation was that ONLY a `definitionResult` vertex ID would be acceptable here.

But I was under the impression that `definitionResult`, `hoverResult`, etc. themselves had ways to refer to an external symbol via a moniker -- it sounds like you are saying that is not true, and I've misunderstood how this works.

Now I'm just confused 🤣 how does a `textDocument/definition` edge refer to an external symbol in LSIF? The spec doesn't explain it at all from what I can see.

2021-04-20 23:42 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
For ranges that reference a symbol via moniker, an edge labeled `moniker` is attached to both a `moniker` vertex and the `resultSet` of the ref/use-site range

```js
{ id: 55, type: "vertex", label: "resultSet" }
{ id: 57, type: "vertex", label: "moniker",  kind: "import", scheme: "tsc", identifier: "node_modules/mobx/lib/mobx:ObservableMap" }
{ id: 58, type: "edge", label: "moniker", outV: 55, inV: 57 }
{ id: 59, type: "vertex", label: "range", start: { line: 17, character: 538 }, end: { line: 17, character: 551 } }
{ id: 60, type: "edge", label: "next", outV: 59, inV: 55 }
```

To my understanding, those ranges wont have a `definitionResult` vertex, but generally will have a `hoverResult` vertex so we get hovers without having to do a cross-repo association

2021-04-20 23:43 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
Its outlined in more detail [here](https://microsoft.github.io/language-server-protocol/specifications/lsif/0.4.0/specification/#exportsImports), the first part of the section covers `export` monikers aka the definition side, the next part covers `import` monikers aka ref/use side. The latter are the ones we're interested in here

2021-04-20 23:49 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
I don't like having implicit edges from _within_ a vertex. We should think of a way of tagging the information we need and representing the relations with actual edges. I have a few ideas on how to express this kind of thing in a more natural way with the graph infrastructure we already have.

A few questions before I'd propose anything though. Are ranges within the markup content only? How do you suppose this will be rendered in a client?

2021-04-20 23:50 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Children []uint64 `json:"children"`
I said this earlier, but I don't want vertexes to reference other vertexes outside of an edge association.

2021-04-20 23:53 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Definition map[Range]uint64 `json:"definition"`
I see, OK. I will need to update this then. If my brief read/understanding is correct, it sounds like we want to allow for a vertex ID here with either `label: "definitionResult"` OR an _edge ID_ with `label: "moniker"`?

Does that sound correct to you? Also wouldn't it need to be the moniker _edge_ ID, not the moniker _vertex_ ID? (otherwise, I presume we would not know where to find the `resultSet` if I am reading this correctly)

2021-04-20 23:58 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
OK, it's easy enough to represent this with explicit edge relations.

> Are ranges within the markup content only?

Yes, the `Range` refers to the `content` only.

> How do you suppose this will be rendered in a client?

See the 2nd use case I describe in my "title" comment above: https://github.com/sourcegraph/sourcegraph/pull/20108#discussion_r617084814

For `Documentation` specifically, the client would render a link to the other `Documentation`. e.g. if you wanted to write:

> See [this other documentation](#)

The only way for the LSIF indexer to link one documentation range to another is to be able to reference the other documentation, since it doesn't know anything about e.g. the URL to link to.

2021-04-20 23:59 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Children []uint64 `json:"children"`
no problem, I'll resolve this comment and we can continue in the other thread.

2021-04-20 23:59 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
So it goes ultimately to another documentation vertex as a target (and not a specific source range or anything)?

2021-04-21 00:01 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
Exactly correct! It's just linking to a documentation vertex in the same way I can link you to these:

* https://pkg.go.dev/net/http
* https://pkg.go.dev/net/http#pkg-overview
* https://pkg.go.dev/net/http#ListenAndServe

It does not link to a specific range within a documentation vertex (i.e. I cannot link you to a specific paragraph in another documentation, I don't think that's super useful)

2021-04-21 12:21 UTC, olafurpg reviewed
@slimsag This is shaping up nicely! I have one proposal for how to remove the implicit edges inside the vertexes. 

It took me a long time to grok the graph structure of LSIF and I'm still learning so I'm not sure if this proposal makes sense

2021-04-21 12:21 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
Here's a rough sketch of how you can model the existing `Documentation` data structure without referencing explicit edge IDs from vertexes

<img width="1206" alt="CleanShot 2021-04-21 at 14 18 01@2x" src="https://user-images.githubusercontent.com/1408093/115552256-66efd380-a2ac-11eb-90ec-20303a6df7c1.png">



The `InteractiveString -> Range -> resultSet` chain could be `InteractiveString -> Range -> documentationResult` instead if that simplifies things. The benefit of linking of `resultSet` is that (I think) it will be easier to handle cross-repo documentation.

2021-04-21 12:29 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
You could also reverse the `documentationResult ----parent---> documentationResult` edge with a child link. Either way, you should be able to reconstruct a tree hierarchy.

2021-04-21 13:00 UTC, Strum355 commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
I think linking to resultSet makes sense and would be a solution to the problem Ive brought up [here](https://github.com/sourcegraph/sourcegraph/pull/20108/files/c9e28317f8461653e19600202b4fee3206d7b337#r617087779) for Definition, Hover and References maps too.

2021-04-21 19:52 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/element.go
> +	VertexDocumentation VertexLabel = "documentation"
```suggestion
	VertexSgDocumentation VertexLabel = "sg:documentation"
```

...or similar

2021-04-21 19:52 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +type InteractiveMarkupContent struct {
Do you think this concept is general enough to support for regular docstrings?

We've had people ask for navigable javadoc/doxygen and similar previously. This could be a key part to that effort as well that's worth considering now.

2021-04-21 19:52 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
I think it makes sense to parallel how ranges work for documents. So we have a Documentation vertex that can describe any level of things.

A range contained by a document refers to extents within the document text. A range contained by a documentation object refers to extents within that documentation text (however it's structured).

The definition/hover/references map here just mirror the relationships we have already. I don't think any of this needs to modeled outside of the edge relations we already have (we're just extending the edges to work with vertexes of a new type).

2021-04-21 19:52 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
(This mirrors the diagram Olaf pasted, as far as I can tell 😄)

2021-04-21 19:52 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Children []uint64 `json:"children"`
The problem with this one is that it's ordered, so we'd need to have some sort of index property on the edges linking children together (unless the order is deterministic by the target vertex somehow, e.g. lexicographically sorted by title).

2021-04-21 20:01 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Children []uint64 `json:"children"`
Order definitely matters here, sorting is not an option.

2021-04-21 20:03 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +type InteractiveMarkupContent struct {
Yes, my hope was that we could support those in the future using this same concept.

2021-04-21 20:03 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Children []uint64 `json:"children"`
Ok that should still be easy as long as the order is known by the indexer (it would need to be to output the sorted list in the first place). We need to extend some edge relationships with something like:

```
{"type": "edge", "label": "documentationChild", "childIndex": n}
```

2021-04-21 20:04 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/element.go
> +	VertexDocumentation VertexLabel = "documentation"
[S]tephen [G]utekanst, no objections here!

2021-04-22 13:23 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Children []uint64 `json:"children"`
I think it would make sense to use an optional `sortText?: string` field for consistency with LSP `CompletionItem` https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion


```ts
/**
	 * A string that should be used when comparing this item
	 * with other items. When `falsy` the label is used
	 * as the sort text for this item.
	 */
	sortText?: string;
```

2021-04-23 01:02 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Content MarkupContent `json:"content"`
>  If you allow arbitrary markdown, people may also abuse this by adding non-code markup inside the Content field.

What do you mean by this?

My expectation is that a `Documentation` vertex's `InteractiveMarkupContent` may often be something like e.g.:

`title`:

```Markdown
```Go
Func foo() Bar
\```
```

`description`:

```Markdown
`Foo` is a function that does XYZ and can be used via a `Foo` `Instantiator` like:

\```
x := Instantiate(&Foo{})(...)
\```

Yielding a `Foo` value.
\```
```

I think that it _will_ be required that people take into account backticks from the markdown in order to determine where the `Range` is pointing to, exactly. If clients cannot handle that easily, they can render the Markdown as plain text

2021-04-23 02:12 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3173176/115807957-620b4c80-a39e-11eb-84fa-a77a50201660.png">

What is the reason here to use edges in the graph to attach the `InteractiveString` to the `Documentation` vertex? It seems from my perspective it would be simpler to just have these as actual fields, no different than how e.g. `tags` are a field or how `hoverResult` has a `contents` field embedded in its vertex data

2021-04-23 02:18 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Documentation map[Range]uint64 `json:"documentation"`
Ah, I guess because `InteractiveString` needs to reference `hoverResult` (albeit indirectly through a `resultSet`) - nevermind!

2021-04-23 03:22 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// ranges within a documentation string to have:
Help here would be much appreciated!

2021-04-23 03:25 UTC, slimsag commented
@efritz @olafurpg @Strum355 PTAL again - I've updated with what (I think) is the right structure in actual LSIF graph form based on what we've discussed.

One thing unclear to me is how to attach a `documentationResult` to a `range` itself (so that a range in the documentation can have corresponding hover/definition/etc results) - I'm not sure what edge type would be used for that? https://github.com/sourcegraph/sourcegraph/pull/20108#discussion_r618912542

2021-04-23 13:33 UTC, olafurpg reviewed
@slimsag I'm unable to reply in that thread so I'll continue here

![CleanShot 2021-04-23 at 15 23 08](https://user-images.githubusercontent.com/1408093/115877545-d9e18180-a447-11eb-93f0-db37bc40bee0.png)

One alternative is to keep detail/title as normal fields on the documentation object and use custom edges instead to attach ranges `documentationTitle` and `documentationLabel`


```json
{1, vertex, documentation, title, label}
{2, type: edge, label: documentationLabel, outV: 1, inVs}
{3, type: edge, label: documentationTitle, outV: 1, inVs}
```

2021-04-23 13:33 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
(ignore this comment if you opt to inline the title/detail fields)

Nit: can we use a different field name here? For example, `content` or `markup`. Currently, `result` is used by `hoverResult` and there are currently no other field name/type conflicts in the way we use LSIF (although I think that's by accident, it's not at all a documented requirement).

2021-04-23 13:33 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// ranges within a documentation string to have:
I would go with `contains` similar to how a document contains multiple ranges

2021-04-23 14:18 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// ranges within a documentation string to have:
I second using contains in the same way. We have document -(contains)-> range, which means the range refers to the document's text.

Same with documentation string. If it contains a range, that range is contained within the payload of the source vertex, whatever it is.

2021-04-23 14:18 UTC, efritz commented
@slimsag This looks **much** closer to what I'd like to see :) I think this is coming along very nicely at this point.

2021-04-26 23:52 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +type InteractiveMarkupContent struct {
The new setup incorporates this even more clearly, resolving thread.

2021-04-26 23:56 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
@olafurpg I am confused by this, you say `result` having "overlap" but my understanding is that all vertices have a distinct JSON type effectively - we should not need to worry about "one result type consuming one field name" I thought?

i.e. a vertex for a `hoverResult` would look like:

```json
{type:"vertex", label: "textDocument/hoverResult", result: {...}}
```

A documentationString vertex would look like:

```json
{type:"vertex", label: "sourcegraph:documentationString", result: {...}}
```

It's very unfortunate IMHO that LSIF has decided to choose to structure JSON in this way (i.e. it definitely means you must first interpret the `label` to know the actual type it should be unpacked into) but my understanding is that decision has already passed: `definitionResult`, `hoverResult`, etc. all use the same overlapping `result` field so for us not to here would be inconsistent.

Have I misunderstood anything?

2021-04-27 00:15 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	SortText *string `json:"sortText,omitempty"`
> resultSet -> documentation: no sortText, label "item" for consistency with definition/references

This one seems problematic as I try to reason through it: `item` edges say they are 1:N:

> To have support for languages where a definition can be spread over multiple ranges or even multiple documents. To support multiple documents ranges are added to a definition result using an 1:N item edge. Conceptually a definition result is an array to which the item edge adds items.

If there are multiple `documentationResult` attached to a `resultSet`, it wouldn't be clear to the client how to structure them without `sortText` (which one goes first?)

I'm also not sure supporting 1:N `resultSet`:`documentationResult` is useful, because the indexer could simply emit a single `documentationResult` for the range instead containing whatever is useful.

2021-04-27 00:25 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	SortText *string `json:"sortText,omitempty"`
I actually misunderstood it: the 1:N nature would be 1 `documentationResult` to N `resultSet`s, so there is a single piece of documentation, or a single definitionResult, hoverResult, etc. that is produced by multiple different ranges. However, I think my argument still stands(?)

2021-04-27 00:36 UTC, slimsag commented
@efritz @olafurpg PTAL once more!

2021-04-27 00:38 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	OutVs []uint64 `json:"outVs"`
I noticed that other LSIF edges use arrays of IDs like this, and adopted this here in order to have an ordered list of children vertices. This seems more natural to me and seems to match LSIF more than the LSP `sortText` hack we had previously discussed - thoughts?

2021-04-27 00:40 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// "documentationResult" vertex.
See [here](https://github.com/sourcegraph/sourcegraph/pull/20108#discussion_r620736759) for why I make an argument that we should use an explicit edge type here and not the existing "item" edge type. Open to hearing arguments for the other way though..

2021-04-27 00:45 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
Field names won't conflict because they're all tagged with label/type in the vertex/edge envelope.

2021-04-27 01:30 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	OutVs []uint64 `json:"outVs"`
I don't think there's any mention of such lists being ordered, but we could always just document it that way :shrug:

2021-04-27 01:32 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// "documentationResult" vertex.
Is the argument that you want a 1:1 edge instead of a 1:N edge?

2021-04-27 01:36 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	// its children should be e.g. displayed on their own dedicate page.
```suggestion
	// its children should be e.g. displayed on their own dedicated page.
```

2021-04-27 01:36 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
Is this meaning to say that for every such vertex there are exactly two siblings and anything else is currently invalid?

2021-04-27 01:49 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
Yes. Would it be nicer to introduce two distinct edge types (one for label and one for detail, like what [Olaf suggested here](https://github.com/sourcegraph/sourcegraph/pull/20108#pullrequestreview-643273680) ?

2021-04-27 01:50 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// "documentationResult" vertex.
Yes.

2021-04-27 01:50 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// "documentationResult" vertex.
Yes.

2021-04-27 01:50 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	OutVs []uint64 `json:"outVs"`
Yeah, that was my thinking here

2021-04-27 03:09 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
No, I think tagged edges are fine (there's as `property` on `item` edges to state the expected type of the target vertex). My issue here is that there's a logical hyper-structure over the graph where a documentation result vertex is useless on its own unless it's part of a specifically-shaped subgraph.

I think the relationships here are fine, but I'd like to change the documentation a bit to be less RFC-like and more descriptive about how consumers would handle the cases where one or more such relationships aren't there.

There's also an issue where you're describing additional constraints of vertexes based on the relationship of the vertexes (if you have a documentationString vertex in memory you can't validate it until you see all edges in the graph, as it could have multiple lines but be attached to one or more documentation result vertexes as a label and not a detail).

I'm not actually disagreeing with the structure here (I think all of the units on their own make sense, and I think the way I expect you'll emit them in lsif-go also make sense).

Maybe `DocumentationStringEdge` need to flip `InV` and `OutV`, in which case this wouldn't be so weird (you're pointing from strings to documentation results, instead of a documentation result having two edges to something else).

2021-04-27 08:43 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
It's correct that vertices have unique types and they're tagged with the label/type. My request to avoid reusing the `result` field name was motivated by a shortcut I took in lsif-java to encode all the vertex/edge types as a single protobuf message

https://github.com/sourcegraph/lsif-java/blob/92b2ba86e39c44393291ef6218e86aa8f16ed00a/lsif-semanticdb/src/main/protobuf/lsif.proto#L21

This shortcut works today because currently we have no field names that are reused for conflicting types. `definitionResult` and `referenceResult` have no `result` field. Without the shortcut, we'd have to write a ton of custom boilerplate code to decode/encode LSIF data structures.

Feel free to ignore my request, but if you don't have a strong opinion then I think it would be nice to make a best-effort to avoid reusing field names for conflicting types. This convention will make it easier for typed languages to encode LSIF data structures in their (primitive) type systems.

2021-04-27 09:09 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Tags []DocumentationTag `json:"tags"`
What do you think about adding detail, title and sort text to `Documentation`?
```suggestion
	Tags []DocumentationTag `json:"tags"`
	
	Label MarkupContent `json:"label"`	
	Detail MarkupContent `json:"detail"`
	
	SortText String `json:"sortText"`// Optional, uses `title` if not defined
```
1:n interactive ranges can be optionally attached to the label/detail via dedicated `documentationLabel`/`documentationDetail` edges. The benefit of inlining these fields is that they enforce a 1:1 relationship between documentation and label/details/sortText. It also makes `Documentation` more self-contained and easier to debug.

2021-04-27 09:17 UTC, olafurpg commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// "documentationResult" vertex.
I don't think it's problematic to use `item` for 1:1 relationships, but I also don't have a strong opinion against using a custom edge type for `result -> documentationResult`. Monikers use a custom `moniker` edge so there is precedence.

2021-04-27 13:32 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// "documentationResult" vertex.
Item is defined as having an array of `InV`, so it's only 1:1 by usage if you use it that way. The data structure explicitly wants items to be a fanout relationship. I'm fine with having a custom edge here as well.

2021-04-27 13:33 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
@olafurpg Thanks fro the context! That makes sense.

2021-04-27 13:37 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +type DocumentationChildrenEdge struct {
Do you think it's worth making this a generic new variant of contains like `HierarchicalContainsEdge`?

2021-04-27 13:38 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	// Whether this links the "label"" or "detail" string of the documentation.
```suggestion
	// Whether this links the "label" or "detail" string of the documentation.
```

2021-04-27 20:51 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +type DocumentationChildrenEdge struct {
I would generally say: stay away from generalizing things until there is a good reason and actually two users. We can generalize this later once there is a need to use it in multiple places

2021-04-27 20:52 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// "documentationResult" vertex.
Custom edge is much more clear to me, so going with that :)

2021-04-27 21:09 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
> a documentation result vertex is useless on its own unless it's part of a specifically-shaped subgraph.

This is true.

> more descriptive about how consumers would handle the cases where one or more such relationships aren't there.

If one of the relationships aren't there, the LSIF dump is _completely invalid_ in my view.

> Maybe DocumentationStringEdge need to flip InV and OutV, in which case this wouldn't be so weird (you're pointing from strings to documentation results, instead of a documentation result having two edges to something else).

I think maybe you are confused (or I am? lol) about what is going on here. The InV points to the documentationResult, so "documentation result has two edges pointing to strings" is _exactly_ what is happening here already in my view. Maybe I have in and out vertices mixed up, though?

2021-04-27 21:14 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Tags []DocumentationTag `json:"tags"`
`sortText` is no longer needed at all, see [this thread](https://github.com/sourcegraph/sourcegraph/pull/20108/files#r620744889).

The reason that the label and detail fields cannot be inlined is because we need to be able to attach a specific range in one of them back to e.g. a hover result (so that hovering over a range in the label or detail text can have a hover result) - this part of your original diagram in specific:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/3173176/116313549-c3e30200-a762-11eb-9add-5e75cc8b0d6d.png">

Now, if your argument is "we could BOTH inline the fields AND have them attached via edges (which can then attach a specific range)" then I guess I'm not sure I would see the point: it would be two separate ways of specifying the same thing, which just adds more complexity.

2021-04-27 21:20 UTC, slimsag commented
@efritz @olafurpg PTAL at this commit in specific: b487278

It tries to clarify some of the confusion I think us three are having around how documentationString gets attached to documentationResult and why.

2021-04-27 22:25 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
> If one of the relationships aren't there, the LSIF dump is completely invalid in my view.

**Hard** disagree. A dump is going to contain much more than data for API docs and I don't want to throw out entire dumps if we can serve something reasonable from it.

I don't think it's a critical error to have only description without labels. Or, alt, if a description is missing because there's no docstring but we can still display a signature and link to its usages.

> The InV points to the documentationResult.

Yup, so the edge goes _into_ the documentation result, not _from_. This is what you have currently:

```
documentationString --( documentationStringEdge/"label" )--------+
                                                                 |
                                                                 +--> documentationResult
                                                                 |
documentationString --( documentationStringEdge/"description" )--+
```

I think that _documentation result has two edges pointing to strings_ is backwards in this case.

2021-04-27 23:04 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
> A dump is going to contain much more than data for API docs and I don't want to throw out entire dumps if we can serve something reasonable from it.

That is fair, but we do have to draw a line somewhere.

> I don't think it's a critical error to have only description without labels. Or, alt, if a description is missing because there's no docstring but we can still display a signature and link to its usages.

I disagree, this is the wrong place to draw the line IMO. Suddenly by doing this we introduce a number of challenges:

* If search and index pages are based on the label (signature), what happens when the label is missing?
* Suddenly we need to worry about how users would understand this error ("it didn't show up in the search results, API docs seems to be missing some things")
* We suddenly need to think about how we would "fallback" to the description if a label is missing.
* If the description is missing, is that because the indexer outright failed to find one and an error should be displayed - or because there really isn't a description? If there is an explicit empty description, it's obvious the indexer emitted one but it's empty.
* "I wrote an indexer and it passed the validator fine" suddenly doesn't necessarily mean you did everything fine. Do we introduce "warnings" in the validator to say "you are missing a label/detail here, maybe you want that or maybe you don't"?

I would be fine drawing the line by saying one of these if label/detail is missing in a `documentationResult`:

* All documentation in the bundle should be considered invalid (I prefer this one most, it gives a clear "the indexer is wrong" state.)
* Just that `documentationResult` is invalid (I am fine with this one _only_ if we are talking about `documentationResult` being used outside the scope of API docs, e.g. being repurposed to store docstrings for symbols more generally.

But I think "let's try to make the best of what we have" is generally a quite bad approach, at least within the scope of one thing (API docs, not the entire LSIF bundle).

2021-04-27 23:09 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
@efritz I was definitely thinking of the edge directionality wrong, I pushed a commit to fix it in multiple places just now.

2021-04-27 23:09 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
😌 I was hoping that was the case :)

2021-04-27 23:11 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
@slimsag Here's a package with no docstrings and how it renders on pkg.go.dev: https://pkg.go.dev/github.com/efritz/gostgres@v0.0.0-20210427220155-a7a2442b8cb3/internal/expressions

Are there any descriptions here? Would you encode these as hundreds of vertexes holding empty strings?

2021-04-27 23:16 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
My thinking and original argument is: Yes, that would be hundreds of vertexes holding empty strings. That is the only way we can actually know the indexer did know _it is supposed to emit those_ and did not just _screw up in emitting them_.

If you want to make an argument for "descriptions should be optional", I am amenable to that - but that is a very different argument than "labels and descriptions should be optional and fallback to best-effort"

2021-04-27 23:20 UTC, efritz approved these changes

2021-04-27 23:20 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
My only wish is not to say MUST without specifying a consequence at this point.

2021-04-27 23:29 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +// They can be attached using a "documentationStringEdge".
Done! 765a8b9c5349dfcf18384770f3a7fa149b3c0e32

2021-04-27 23:34 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
Hmm, so I do understand the rationale for this but wouldn't this mean that we need to ensure all vertex fields are basically prefixed with non-conflicting names? Like `hoverResult` would ideally have its `result` field renamed to `hoverResult` to avoid conflicting with something else named `result` in the future?

If so - I can basically say: I agree with you! But I feel like as long as we're adopting upstream LSIF changes, that's going to be a losing battle. If they chose `result` for `hoverResult` then it's almost guaranteed that the next vertex that requires a payload - maybe one even exists today like `symbolResult` - will be named `result` and then your workaround will be broken.

So I don't have a strong opinion here other than "that would be nice, but I'm afraid by doing it here we're fooling ourselves into thinking this is the case long-term.."

2021-04-27 23:36 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
Here's an LSIF protobuf schema (just what we consume) that I drafted in **checks modtime** May 2020.

```
syntax = "proto3";

package lsif;

message Element {
    string id = 1;
    string type = 2;
    string label = 3;

    oneof data {
        MetaData metaData = 4;
        Document document = 5;
        Range range = 6;
        Moniker moniker = 7;
        PackageInformation packageInformation = 8;
        ResultSet resultSet = 9;
        HoverResult hoverResult = 10;
        DefinitionResult definitionResult = 11;
        ReferenceResult referenceResult = 12;
        Edge edge = 13;
    }
}

message MetaData {
    string version = 1;
    string projectRoot = 2;
}

message Document {
    string uri = 1;
}

message Range {
    int32 startLine = 1;
    int32 startCharacter = 2;
    int32 endLine = 3;
    int32 endCharacter = 4;
}

message Moniker {
    string kind = 1;
    string scheme = 2;
    string identifier = 3;
}

message PackageInformation {
    string name = 1;
    string version = 2;
}

message ResultSet {}

message HoverResult {}

message DefinitionResult {}

message ReferenceResult {}

message Edge {
    string outV = 1;
    repeated string inVs = 2;
    string document = 3;
}
```

2021-04-27 23:39 UTC, slimsag commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
(off-topic: pls pls pls don't let us adopt protobuf for LSIF, it's one of the slowest binary formats we could adopt - like moving from JSON to bson. We would be so much better off with something like flat buffers)

2021-04-27 23:40 UTC, slimsag commented
I'll leave this open in case there are any further comments/suggestions anyone wants to see included, but otherwise I basically consider this done at this point and am moving on to the lsif-go implementation of this.

Once we have an authoritative place to document our LSIF spec, I will happily send PRs to spec this out there as well.

2021-04-27 23:40 UTC, efritz commented on enterprise/lib/codeintel/lsif/protocol/documentation.go
> +	Result MarkupContent `json:"result"`
Whatever we decide will be backed by benchmarks.

2021-04-30 20:33 UTC, merged