Refresh design navbar
sourcegraph/sourcegraph pull request #20385
Opened 2021-04-24 00:11 UTC by 5h1rU

TODO

2021-04-27 17:07 UTC, umpox commented on client/web/src/user/UserAvatar.tsx
> +        )
Is this definitely what we want as a placeholder? It seems like this could lead to some weird behaviour. Especially if the `username` is used here, or if I set my `displayName` as something else

cc: @sourcegraph/design

2021-04-27 17:07 UTC, umpox commented on client/wildcard/src/components/NavBar/NavBar.tsx
> +                onClick={() => setOpen(!open)}
```suggestion
                onClick={() => setOpen(previous => !previous)}
```

As it's a toggle

2021-04-27 17:48 UTC, valerybugakov reviewed
Looks solid! Looking forward to the outstanding items from the TODO list.

2021-04-27 17:48 UTC, valerybugakov commented on client/web/src/nav/Feedback/FeedbackPrompt.tsx
> +                    'btn-secondary-outline': isRedesignEnabled,
It seems it should be `btn-outline-secondary` to apply Tom's updated styles.

```suggestion
                    'btn-outline-secondary': isRedesignEnabled,
```

2021-04-27 17:48 UTC, valerybugakov commented on client/web/src/nav/GlobalNavbar.tsx
> +                </NavItem>
Asked @quinnkeast in Figma about hover state. Not sure if we want to omit that. Navigation links look better when they signify that it's possible to interact with them.

Posting it here to track the discussion: [link](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw?node-id=1285:25090#77132033).

2021-04-27 17:48 UTC, valerybugakov commented on client/web/src/nav/GlobalNavbar.tsx
> +                            />
For some reason, the hover state doesn't work on this nav item.

2021-04-27 17:48 UTC, valerybugakov commented on client/web/src/nav/GlobalNavbar.tsx
> +                </NavItem>
Nav links jump a bit in Safari. Probably because of the `border-down`.

![Screen Recording 2021-04-27 at 20 14 10 (1)](https://user-images.githubusercontent.com/3846380/116284403-a1cb9d00-a7bf-11eb-89a2-c6cb0bf6effc.gif)

2021-04-27 17:48 UTC, valerybugakov commented on client/web/src/user/UserAvatar.tsx
> +        const [firstName, lastName] = name.split(' ').map((name: string) => name.split('')[0])
Splitting by a white space works for most cases, but a lot of people have multiple words in their names. Curious if anybody has thoughts on how to improve this heuristic.

2021-04-27 17:48 UTC, valerybugakov commented on client/web/src/user/UserAvatar.tsx
> +                {lastName}
Would this result in `Valery undefined` if I don't have white spaces in my `displayName` and `username`?

2021-04-27 17:48 UTC, valerybugakov commented on client/wildcard/src/components/NavBar/NavBar.module.scss
> +@import '../../../../branded/src/global-styles/breakpoints.scss';
It should be possible to use absolute paths, especially after @eseliger's fix that we merged today.
See more info here: https://github.com/sourcegraph/sourcegraph/blob/main/doc/dev/background-information/web/styling.md#css-modules

2021-04-27 17:48 UTC, valerybugakov commented on client/wildcard/src/components/NavBar/NavItem.module.scss
> +@import '../../../../branded/src/global-styles/breakpoints.scss';
let's convert to absolute paths if tooling allows it

2021-04-27 17:48 UTC, valerybugakov commented on client/wildcard/src/components/NavBar/NavBar.module.scss
> +    width: 0.0625rem; // 1px
Not related to the PR changes: maybe we should consider converting `px` to `rem` with some utility function, considering that all designs use `px`. Something similar to what is described in [this article](https://dev.to/nikolab/convert-px-to-rem-using-sass-3-methods-4ep2). What do you think? 

cc @umpox

2021-04-27 17:48 UTC, valerybugakov commented on client/wildcard/src/components/NavBar/NavBar.tsx
> +import navItemStyles from './NavItem.module.scss'
nit: these files suggest that this component can be split into three different files.

2021-04-27 17:48 UTC, valerybugakov commented on client/wildcard/src/components/NavBar/NavBar.tsx
> +    ) : (
totally optional: consider using `if () return` instead of the ternary. IMO ternaries are generally harder to read. If it's easy to avoid them, I vote for that :)

2021-04-28 16:05 UTC, felixfbecker commented on client/shared/src/commandPalette/CommandList.scss
> +        color: var(--icon-color);
**note**: Need to ensure this variable is defined for code hosts (in browser extension styles)

2021-04-28 16:55 UTC, 5h1rU commented on client/shared/src/commandPalette/CommandList.tsx
> +    }
@AlicjaSuska Thoughs?

2021-04-28 16:58 UTC, 5h1rU commented on client/web/src/nav/GlobalNavbar.scss
> +        border: 1px solid var(--brand-secondary) !important;
probably this can be fixed by providing a better scope with `theme-redesign` class. I'll explore.

2021-04-28 20:12 UTC, 5h1rU commented on client/web/src/user/UserAvatar.scss
> +            #5c7cfa 100%
The only existent reference is logo-purple. These colors are not present in any other place. Do you think adding these as variables will add value?

2021-04-28 21:07 UTC, 5h1rU commented on client/wildcard/src/components/NavBar/NavAction.module.scss
> +    :last-child {
Is that a problem even when we are using modules? Every module will have a custom selector associated with a single owner. 

Actions are tied to an unordered list, so applying classes manually to the first and last elements restricts scalability if more list elements need to be added.

2021-04-28 21:20 UTC, 5h1rU commented on client/wildcard/src/components/NavBar/NavBar.module.scss
> +    width: 0.0625rem; // 1px
I remember something similar discussed before, and some of the concerns were about how to make sure that the values on the PR's are the correct values. For example, if you are reviewing a PR, you want to check if the units used on the code are the same declared on Figma.

I believe that's not a problem, IMO that's not a reviewer responsibility but I'm not sure about what other devs adn designers think.

2021-04-28 21:45 UTC, 5h1rU commented on client/shared/src/commandPalette/CommandList.tsx
> +    buttonElement: ButtonElement = 'button',
@tjkandala @muratsu Do you think this is a potential source of problems? Not a blocker at all. We can live with the `span` element by now

2021-04-28 22:04 UTC, tjkandala commented on client/shared/src/commandPalette/CommandList.tsx
> +    buttonElement: ButtonElement = 'button',
Seems like it'll require [more "a lot more style overrides"](https://github.com/sourcegraph/sourcegraph/pull/4547#discussion_r294158298). We can change it to `button` when when we make time to do that, but if it's acceptable to keep is as `span` for now, we should

2021-04-29 07:16 UTC, pdubroy commented on client/wildcard/src/components/NavBar/NavAction.module.scss
> +    :last-child {
@felixfbecker I'm curious, do you have reason to believe that browsers implement it this way? That sounds like a naive implementation and I'd be surprised if that's literally how it works.

I'm generally pretty skeptical of these kinds of micro-optimizations, because (at least on the JS side of things), it's difficult to even benchmark these things properly unless without a proper understanding of how it's implemented.

2021-04-29 09:56 UTC, felixfbecker commented on client/wildcard/src/components/NavBar/NavAction.module.scss
> +    :last-child {
I'm happy to give more details on that, but just want to point out first that that is not what I see as the main reason for avoiding descendant selectors, and I don't want to focus a discussion on that (main reason half-way through). Details: 

The reason I added that (simplified, illustrative) explanation is because we often tend to think of selectors as targeting a specific node _left-to-right_, but in reality they are matched _right-to-left_ (which is specified in the [CSS spec here](https://www.w3.org/TR/selectors-4/#:~:text=to%20match%20a%20complex%20selector%20against%20an%20element%2C%20process%20it%20compound%20selector%20at%20a%20time%2C%20in%20right-to-left%20order.), and [this StackOverflow answer](https://stackoverflow.com/a/5813672/4208018) also gives some context if you're curious why). I find that awareness of this helps thinking more carefully about how to write selectors, as it makes it more obvious that if something unspecific is put at the _end_ of a selector, it has the potential to match a lot more than expected (now during every evaluation by the browser, or in the future when somebody makes a change to the DOM hierarchy).
If you're interested in how that can actually affect performance in the browser implementation, [this is a nice comment by a browser developer](https://shauninman.com/archive/2008/05/05/css_qualified_selectors#comment_3942).
Yes browsers optimize this, but they're also up against 4,011 CSS selectors in our app that need to be matched against 880,965 DOM nodes on a [large code file](https://sourcegraph.com/github.com/dotnet/runtime/-/blob/src/coreclr/gc/gc.cpp) (43,991 LOC, which is not unheard of from customers) in Sourcegraph.
All of a sudden the browser is spending 20s _just on rendering_, and that is on the most high-powered MacBook money can buy. This is obviously an extreme case that we would never get buttery-smooth, but even if you just take a normal-sized file and throttle your CPU 4x, rendering can take ~5s.

<img width="344" alt="Screen Shot 2021-04-29 at 10 51 24" src="https://user-images.githubusercontent.com/10532611/116526860-53f78780-a8da-11eb-9c49-dc9067293c5f.png">
<img width="471" alt="Screen Shot 2021-04-29 at 10 59 46" src="https://user-images.githubusercontent.com/10532611/116527331-da13ce00-a8da-11eb-8147-374b93689705.png">

Point here is, rendering perf is not an invented, hypothetical problem that we never actually have in practice just because browsers are great at optimizing.

I get the microoptimization argument, but the problem is that no single selector will significantly impact perf, but one day all of them combined give the performance a death by a thousand cuts. At that point it is _incredibly_ hard to refactor styles, precisely because descendant selectors are not easy to match directly to the element they apply to in the code. A codebase that liberally uses them becomes an entangled web of selectors and elements.

Compare that to the cost of simply always using explicit class names, which has been the established best practice for a long time (it's the core of conventions like BEM and CSSOM). There is no cost to giving elements a class name, and it actually makes the code easier to understand, as every style rule can be matched 1:1 to the element it matches too in TSX, and every element in TSX that is affected by some style is easily visible and can be mapped 1:1 to the CSS rule.

**And that is the main reason in my eyes**. A descendant selector can match arbitrarily deep. **Even when using CSS modules**, if the React component has a child React component, a descendant selector will pierce into the internals of that component, and every of its child components, and so on, and breaking the encapsulation and potentially matching unintended elements. So to your question @5h1rU, yes this is equally a problem when using CSS modules. This is usually not the case when the PR is made, because it was tested after all, but it is only a matter of time in a sufficiently large codebase with sufficiently large amount of developers until someone makes a change that causes this rule to match unintended elements, potentially internals of other components. For any dev aware of this problem, this now means on every change they make they need to be on the lookout for any parent styles that may affect their DOM hierarchy change, which makes simple and seamingly harmless changes complex.

To give a concrete example for the case here, lets say somebody in the next months made a seamingly harmless change, that wraps a child element under the `actions` in a `<span>`, or adds an icon (which is an `<svg>`). Suddenly the child of `<span>` will match as a `:first-child` as well, and the `<svg>`.

This is why we have this practice, and why we have a Stylelint warning to avoid descendant selectors (which should show up here, at least in VS Code). Code reviewers could look into and debate on every single PR that adds one whether this particular instance with the current DOM hierarchy is harmless, or affects perf significantly (it won't), but that doesn't scale and it is much easier to say "always avoid descendant selectors" (again, consider there is zero cost to simply using a class name).

Please also note that I am not saying "never use descendant selectors". We have them in a few limited places in our app (e.g. global styles, syntax highlighting) where assigning classes out would not be possible. That is why I asked "Is there a reason we can't apply a class to the items?" in my first comment, because sometimes there is a legit reason.

I'm also not saying "never use _child_ selectors (i.e. `>`)". Child selectors can make the problem slightly better by constrainting to _direct_ children, which means internals of React sub-components are less likely to be unintentionally messed with. But plain nesting without `>` or `&` in Sass compiles to descendant selectors.

I'm also not saying "Don't use `:first-child` and `:last-child`". That may be a misunderstanding here. It is totally fine to have a selector like `.action-item:first-child` and `.action-item:last-child`. This means, to your question @5h1rU, you don't need to apply classes to the first and last children manually - just a consistent class on all items, and then you can match the first and last of those with CSS. I agree that assigning classes on the first and last item manually would be cumbersome.

Sorry for the wall of text :)

2021-04-29 14:23 UTC, pdubroy commented on client/wildcard/src/components/NavBar/NavAction.module.scss
> +    :last-child {
Thanks @felixfbecker, I agree that maintainability is the strongest argument here and reason enough to avoid this if possible.

Thinking about this more, the descendant selector obscures the intention too — when looking at this rule, it's difficult to tell what elements it's intended to affect. If it's for the `li.action` items (that's my guess) then it seems too broad for that purpose.

Also, I didn't realize we had a [recommendation](https://docs.sourcegraph.com/dev/background-information/web/web_app#styles) about descendant selectors, and one of the reasons to have standards and style guides is to avoid having to debate them in every PR. :-)

2021-04-30 09:24 UTC, AlicjaSuska commented
1. Activation dropdown - logic and behaviour should stay the same. I'll add it to designs once I'm back next week. @5h1rU do you have any suggestions about changes here?
2. _Code host status icon: This change impact logic outside the navigation bar as component #20488_ - I see it's in eng backlog. When it can be worked on? Does it block this PR?
3. _Dropdown nav links design on small screens: Design doesn't reflect the nav links behaviour on small screens_ - I've added a[ dropdown nav design](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1955%3A33424) to Figma. I hope it's what's you're referring to @5h1rU .

If you meant [user nav](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=954%3A6162), behavior on small screens should stay the same. I don't think there is a need to design a separate experience for mobile as of now.

4. _Question: Are docs and about buttons part of the navbar when a user is unauthenticated?_ - yes, made the [correction](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1285%3A25090). Also, please see the [un-auth nav links menu](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=1955%3A36774) variant.
5. _Avatar CSS gradient: Based on the Figma design, the mesh gradient effect cannot be made with linear-gradient CSS. Any suggestion is welcome._ - I think that the gradient you created works fine as well (@quinnkeast please, see the comparison below and share your thoughts, thank you!). My bigger concern is that text in the avatar is very far from design. @5h1rU would you be able to fix it?

Also, about the gradient - we can also use the png export from Figma as the avatar. @5h1rU

<img width="170" alt="Screenshot 2021-04-30 at 11 20 51" src="https://user-images.githubusercontent.com/20326070/116675769-79ea5e00-a9a6-11eb-8f30-878ad1721417.png">
<img width="278" alt="Screenshot 2021-04-30 at 11 20 45" src="https://user-images.githubusercontent.com/20326070/116675774-7b1b8b00-a9a6-11eb-84e0-4946daf5e12b.png">

PNG EXPORT OF THE GRADIENT
![Gradient](https://user-images.githubusercontent.com/20326070/116675811-840c5c80-a9a6-11eb-94f4-2e6aa1e65dee.png)

2021-04-30 18:41 UTC, limitedmage requested changes
I don’t see in this PR that the search box is being shown in the search page. I think this should be added to this PR. No styling changes are needed for the search box interior itself, I will take care of those. But I think frontend platform team should own showing the search box container below the navbar.

2021-04-30 18:43 UTC, 5h1rU commented
> I don’t see in this PR that the search box is being shown in the search page. I think this should be added to this PR. No styling changes are needed for the search box interior itself, I will take care of those. But I think frontend platform team should own showing the search box container below the navbar.

Perfect, thanks for answering @limitedmage 
I Will update with the search bar included on this PR.

2021-04-30 19:32 UTC, limitedmage approved these changes

2021-04-30 19:32 UTC, limitedmage commented on client/web/src/Layout.tsx
>                      variant={
We should consider removing the `'no-search-input'` variant now that it's not relevant

2021-04-30 19:32 UTC, limitedmage commented on client/web/src/user/UserAvatar.scss
> +            #5c7cfa 100%
Should we use known colors here?

2021-04-30 19:32 UTC, limitedmage commented on client/wildcard/src/components/NavBar/NavBar.module.scss
> +    width: 0.0625rem; // 1px
For 1px width divider I personally prefer to just use 1px and disable the stylelint rule. Though I think in this case you might not need to specify width at all? Since the content is 0-width and border is 1px-width, the calculated width will be 1px.

2021-04-30 19:43 UTC, 5h1rU commented on client/web/src/Layout.tsx
>                      variant={
This variant is being used as part of a current logic, will be safe to remove when the redesign is done. Adding a TODO comment here.

2021-05-04 19:57 UTC, merged