Add ImagePullBackOff + update format
sourcegraph/sourcegraph pull request #20574
Opened 2021-05-01 01:46 UTC by abeatrix

Add troubleshooting steps for ImagePullBackOff & 429 Too Many Requests error to K8s troubleshooting docs based on @ggilmore's reply in customer issue #328

2021-05-01 01:48 UTC, daxmc99 commented on doc/admin/install/kubernetes/troubleshoot.md
> +2. Upgrade your account to a Docker Pro or Team subscription ([See Docker Hub for more information](https://www.docker.com/increase-rate-limits))
I would put this last and mention that it is optional. 
Setting ImagePullSecrets should get you most of the way

2021-05-01 01:50 UTC, daxmc99 requested changes

2021-05-01 01:50 UTC, daxmc99 commented on doc/admin/install/kubernetes/troubleshoot.md
> +3. Create a Docker Hub account with a higher rate limit > configure an `ImagePullSecrets` K8S object with your Docker Hub service that contains your docker credentials ([link to tutorial](https://kub
nit: change 3 to 1, markdown automatically increments numbered lists

2021-05-03 17:40 UTC, abeatrix reviewed
Rearrange items

2021-05-03 17:40 UTC, abeatrix commented on doc/admin/install/kubernetes/troubleshoot.md
> +3. Create a Docker Hub account with a higher rate limit > configure an `ImagePullSecrets` K8S object with your Docker Hub service that contains your docker credentials ([link to tutorial](https://kub
rearranged as suggested.

2021-05-03 19:09 UTC, daxmc99 approved these changes
LGTM

2021-05-04 15:46 UTC, merged