extensibility: extension registry redesign
sourcegraph/sourcegraph pull request #20822
Opened 2021-05-10 16:30 UTC by tjkandala

![Screenshot from 2021-05-10 12-28-57](https://user-images.githubusercontent.com/37420160/117692884-74053180-b18b-11eb-93e4-dd22ce113c27.png)

Note: the card redesign will be implemented in a separate PR.

2021-05-13 19:02 UTC, tjkandala commented on client/web/src/extensions/ExtensionCard.tsx
> +}
@muratsu this is basically an even worse version of the `hashCode` function we just got rid of, but it gets the job done here

2021-05-13 19:19 UTC, tjkandala commented on client/shared/src/extensions/extensionManifest.ts
> +            (typeof value.headerColor !== 'string' || !EXTENSION_HEADER_COLORS.has(value.headerColor))
@muratsu just validating new manifest fields. I didn't add validation for `iconDark` back when I added it (first extension registry refresh), so I added it now

2021-05-14 12:52 UTC, tjkandala commented on client/branded/src/global-styles/colors.scss
> +    --alert-success-text-color: #20612e;
@sourcegraph/frontend-platform Is there a better way to reach into the `.alert-success` color and opt out of the alert icon?

2021-05-17 05:37 UTC, muratsu commented
https://user-images.githubusercontent.com/1308560/118436713-23fc0280-b696-11eb-9908-1d0825a34596.mov

1. I wish the switch had a smooth animation like this (https://material-ui.com/components/switches/)
2. Once enabled, should we multiply the header color with some green like this implementation or should we temporarily use a fixed green color?
3. The pulse animation is substantially shorter than the overall green effect. Should we shorten the total animation time? Pulse is ~2s but the card remains green much longer.

2021-05-17 05:48 UTC, muratsu commented
Bug: Currently there doesn't seem to be a way to show all the enabled extensions on one page.

Steps: 
1. From the left menu select `Show Enabled`
2. Scroll down. 


Actual
The button under Programming Languages says `Show full category`

Expected
The button under Programming Languages says `Show more`?

2021-05-17 05:54 UTC, muratsu commented
On the bottom of the page `show more extensions` is hard to discover.

![image](https://user-images.githubusercontent.com/1308560/118438482-4e9b8a80-b699-11eb-8d99-4860509db507.png)

2021-05-17 06:12 UTC, muratsu commented on client/web/src/extensions/ExtensionCard.tsx
> +        [feedbackManager, optimisticFailureManager]
moving the animation to the css is a really great idea 👍

2021-05-17 06:19 UTC, valerybugakov commented on client/branded/src/global-styles/colors.scss
> +    --alert-success-text-color: #20612e;
The color is used [here](https://github.com/sourcegraph/sourcegraph/pull/20822/files#diff-05fc0583cb0b237cb20ad9ffd70974be241ef29111a720839027e8a29f0011aaR63), but I cannot find a use case for it in [Figma mockups](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-%22Marketplace%22-Concepts-%5BReview%5D?node-id=714%3A8). 
@muratsu, maybe you have an idea of where it's used in the actual UI?

2021-05-17 06:33 UTC, muratsu commented on client/web/src/extensions/ExtensionCard.tsx
> +}
Fun fact: The strings in JS are UTF-16 coded, meaning for some new characters we actually use surrogate pairs. Emojis are one such case.
```
var x = "👉hi😁";
for (z=0;z<x.length;z++) console.log(x.charCodeAt(z))
```
This code will print `55357 56393 104 105 55357 56833`. If you ever want to iterate chars of a string, it's best to use for..of as it will treat surrogate couples as one char

2021-05-17 07:29 UTC, valerybugakov reviewed
Registry redesign looks great, huge work @tjkandala 💪
Since I looked into the alert-color question, I quickly looked at the changes and left a couple of optional comments.

2021-05-17 07:29 UTC, valerybugakov commented on client/branded/src/global-styles/colors.scss
> +    --alert-success-text-color: #20612e;
It looks like this color is used for extension description text during the `--enable` animation. Is it important here to match the `.alert-success` color?  

I would suggest either keeping text color unchanged during the animation or picking the color from the OC color palette or our own CSS variables list because:

- after the redesign, alerts will use only colors defined in our CSS variables
- colors from our design system should be preferred over custom colors if possible

<img width="921" alt="Screenshot 2021-05-17 at 10 06 27" src="https://user-images.githubusercontent.com/3846380/118445951-a41b7a00-b721-11eb-96c3-f81e274e0d53.png">

2021-05-17 07:29 UTC, valerybugakov commented on client/web/src/extensions/ExtensionCard.scss
> +    &--enabled {
For some reason, the "Enabled for me" toggle goes `on` -> `off` -> `on` for me locally. Steps to reproduce:

1. Clone this branch.
2. Run `sg run enterprise-web-standalone`.
3. Open http://sourcegraph.test:3443/extensions?category=All.
4. Disable and enable `search-insights` extension.

Let me know if I missed some configuration steps.

![Screen Recording 2021-05-17 at 10 19 21](https://user-images.githubusercontent.com/3846380/118447604-936c0380-b723-11eb-9114-37f34ab8cb27.gif)

2021-05-17 07:29 UTC, valerybugakov commented on client/web/src/extensions/ExtensionCard.scss
> +        background-color: rgba($success, 0.2);
The border that separates sections of the extension card is mostly invisible during the `--enabled` animation. It would be great to keep contrast high enough even during the animation.

<img width="904" alt="Screenshot 2021-05-17 at 10 25 10" src="https://user-images.githubusercontent.com/3846380/118448089-1db46780-b724-11eb-9169-df075499536b.png">

2021-05-17 07:38 UTC, AlicjaSuska requested changes
Thank you for all the changes @tjkandala . Here are my notes. I've also created the '[Design QA](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/?node-id=975%3A2591)' page in Figma to show some of the changes that need to be done.

- [x] padding in the card is not aligned with the design ([Figma](https://www.figma.com/file/hciWKNbllHeHWoYcpfGQp2/RFC-305-Next-Up-Extensions-Registry-Marketplace-Concepts-Review?node-id=975%3A2667))
- [x] we should use H3 for the extension name, not 'font-weight-bold’ class
- [x] Change label from ~~'not enabled for all the users'~~ to 'disabled for all the users
- [x] Remove extra 8px margin from below the search bar
- [x] Change top and bottom margin for 'create extension' banned to 48px. I've added a separate issue for the banner changes #21007 btw
- [x] When clicking on the categories in the left menu, the transition is very slow. It looks like there is some delay, should be instant. I've recorded the [loom video](https://www.loom.com/share/b76efd591f094be0aa82a923b2ab3076) to show it.
- [x] We're missing the hover state for the left nav items. It should be $bg-2 (design from code monitoring mockups):
<img width="748" alt="Screenshot 2021-05-17 at 09 36 17" src="https://user-images.githubusercontent.com/20326070/118449433-70296000-b6f3-11eb-9af9-d9f73f826284.png">

- [x] Animation when turning on the extension: as a quick fix, can you remove the background from the card and leave only the green border (outside of the card area)? That would already look way better.

2021-05-17 07:40 UTC, AlicjaSuska commented on client/web/src/extensions/ExtensionCard.scss
> +        background-color: rgba($success, 0.2);
Please, see the comment below: I'd like to remove this green background from the card area entirely and only keep the border animation :)

2021-05-17 07:44 UTC, AlicjaSuska commented
Probably outside of the scope of this issue: there is something wrong going on with the header: button is misaligned, the icon is too small:
<img width="1120" alt="Screenshot 2021-05-17 at 09 20 42" src="https://user-images.githubusercontent.com/20326070/118450372-6b18e080-b6f4-11eb-86e2-70071bbbba14.png">

2021-05-17 08:53 UTC, AlicjaSuska commented
I agree with @muratsu - let's remove the 'show more extensions' button - full issue and reasoning here: #21011 @tjkandala @Joelkw

2021-05-17 14:05 UTC, tjkandala commented on client/web/src/extensions/ExtensionCard.tsx
> +}
Interesting, this was definitely going to bite me one day!

2021-05-17 14:08 UTC, tjkandala commented on client/branded/src/global-styles/colors.scss
> +    --alert-success-text-color: #20612e;
Sorry, the animation was implemented during the last registry refresh and I don't think it was in Figma (ad hoc implementation). Thanks for the suggestion, looks like we're scrapping the card color changes, only keeping the "glow"

2021-05-17 14:09 UTC, tjkandala commented on client/web/src/extensions/ExtensionCard.tsx
> +                                    <WarningIcon className="icon-inline" /> Invalid manifest
I'll add stories to Storybook so we can check it out

2021-05-17 14:56 UTC, tjkandala commented on client/web/src/extensions/ExtensionRegistrySidenav.tsx
> +    const showDisabled = useCallback(() => setEnablementFilter('disabled'), [setEnablementFilter])
I usually opt for `useCallback` when passing callbacks to components from external libraries since I don't want to make any assumptions about potential memoization of those components. I could read the implementation and find that it's not memoized now, but that could change over time, so I wrap callbacks with `useCallback` anyways.

In this case, even if `<DropdownItem>` is memoized, it's probably not so complex that unnecessary re-rendering would have a noticeable impact on performance.

2021-05-17 15:49 UTC, tjkandala commented on client/web/src/extensions/ExtensionCard.scss
> +    &--enabled {
I haven't been able to sign in on the standalone web server, but I have a theory as to why this is happening. 

The extension toggle reflects the optimistic enabled state, but synchronizes with the actual enabled state whenever it changes (in case e.g. an admin enables the extension for all users [optimistic], then the merged settings are returned which determine that it's enabled for them as well [if not explicitly disabled in user settings]). If the settings just didn't update, it wouldn't go back to off like this, so it looks like there's a temporary settings change that reflects the optimistic state, then another settings change that rolls it back. It also doesn't seem like a network error related to the settings mutation, or else we'd show an alert.

2021-05-17 15:57 UTC, tjkandala commented
@AlicjaSuska 

> * [ ]  we should use H3 for the extension name, not 'font-weight-bold’ class

It's already an `<h3>` (with `<a>` nested inside), but `.font-weight-bold` is redundant now, good catch

> * [ ]  Change label from ~'not enabled for all the users'~ to 'disabled for all the users

I intentionally changed the copy [here](https://github.com/sourcegraph/sourcegraph/pull/20740) since we can't guarantee that it is _disabled_ for all users, just that we haven't set it to be enabled by default because users can override those settings (user settings > site settings). Should we still change it back?

2021-05-18 07:43 UTC, valerybugakov commented on client/web/src/extensions/ExtensionRegistrySidenav.tsx
> +    const showDisabled = useCallback(() => setEnablementFilter('disabled'), [setEnablementFilter])
Is there any risk in passing the unmemoized `onClick` handler to the `<DropdownItem>` regardless of its internal implementation? 

Generally, if the component is simple enough: e.g., it's a layout with many children or a complex visual graphic, it should be ok to omit any optimizations.

2021-05-18 08:23 UTC, valerybugakov commented on client/web/src/extensions/ExtensionCard.scss
> +    &--enabled {
1. About standalone web server credentials: we have `k8s.sgdev.org admin user` in 1Password that can be used to log in to the web server. 
2. I was able to reproduce this behavior locally with our `frontend` server. The issue is visible if you enable network throttling to "Slow 3G": 
<img width="152" alt="Screenshot 2021-05-18 at 10 57 45" src="https://user-images.githubusercontent.com/3846380/118614405-47d45b00-b7f2-11eb-94c0-dd4336e29f2f.png">

This issue is noticeable with the standalone web server because it has native latency to reach the deployed API instance. To reproduce it: 
1. Enable network throttling.
2. Enable and disable the extension.
3. See how changes will be reflected in the UI

![Screen Recording 2021-05-18 at 10 54 02](https://user-images.githubusercontent.com/3846380/118614662-9550c800-b7f2-11eb-8b3b-c488e8938916.gif)

2021-05-18 08:25 UTC, valerybugakov commented on client/web/src/extensions/ExtensionCard.scss
> +        background-color: rgba($success, 0.2);
Btw, I like how enable-animation looks after the update 🙂

2021-05-18 13:54 UTC, tjkandala commented on client/web/src/extensions/ExtensionCard.scss
> +    &--enabled {
Seems like it's not a good idea to try to synchronize the toggle state with settings, since it'll lead to this confusing behavior any time the user toggles before the settings from the previous mutation have been received from the API. 

I can think of two fixes here (problem: top toggle state depends on the bottom toggle, truth is computed in the backend):
1) Don't synchronize toggle state with settings, rather compute optimistic state for both toggles from previous settings.
2) Don't be optimistic, rather add a loading state to the `<Toggle>` component. 

I think 1 is unnecessarily complex, especially considering that this UI will only be seen by site admins. @AlicjaSuska what do you think about the toggle loading state? We could add this along with the

2021-05-18 16:13 UTC, tjkandala commented on client/web/src/extensions/ExtensionCard.scss
> +    &--enabled {
@muratsu @AlicjaSuska @Joelkw We will tackle this issue for 3.29 as it shouldn't be a release blocker. We'll focus on featured extensions first, then return to these UX issues (#21062, #21063)

2021-05-19 18:23 UTC, AlicjaSuska approved these changes
Awesome work @tjkandala ! There is one thing (not a blocker) - could you remove the bottom padding from this element? It adds to the divider padding and the space is too big. Thank you!

<img width="406" alt="Screenshot 2021-05-19 at 20 21 22" src="https://user-images.githubusercontent.com/20326070/118864222-1043dc80-b8e0-11eb-9880-04ec2a84706e.png">

2021-05-19 19:02 UTC, merged