Implement fuzzy file finder with keyboard shortcut `f`.
sourcegraph/sourcegraph pull request #20921
Opened 2021-05-12 21:23 UTC by olafurpg

Previously, there was no way to interactively search for a file that
matches a given fuzzy query. This commit adds a new modal that activates
on the keyboard shortcut `t` and allows the user to quickly open a file
that fuzzily matches a given query.

The implementation in this commit is specifically designed to handle
large repositories with >100k source files. The fuzzy finder achieves
low-latency by:

1) implementating all the filtering inside the browser on the
   client-side
2) using bloom filters to quickly discard buckets of filenames that are
   guaranteed to not match a given query.  This techniqueis used by the
   Scala language server and documented in this blog post
   https://scalameta.org/metals/blog/2019/01/22/bloom-filters.html

The downside of this approach:

1) it can take a while to first download all filenames in the
   repository, especially for large repos like chromium/chromium
2) constructing the bloom filters may take a while on very large
   repositories. It's possible to work around this issue, but it's not
   implemented in this commit.
3) the bloom filter algorithmm is sometimes more strict compared to the
   fuzzy finder in VS Code and IntelliJ. There are techniques to make
   the fuzzy finder more fuzzy, for example we could make all-lowercase
   queries case-insensitive. It's also worth consider whether we want
   scrap the bloom filters altogether and use an entirely different
   approach, for example by reusing techniques from nvim-telescope.

Demo: low-latency filtering in the chromium/chromium repository (~400k source files). Observe that negative results (0 matches) return instantly, this is a key-feature of the bloom-filter approach.

![CleanShot 2021-05-12 at 21 24 48](https://user-images.githubusercontent.com/1408093/118044360-d9694600-b376-11eb-8c55-282d17f67550.gif)

Demo: exact matches are highlighted differently from incomplete matches making it easier to visually parse the results

![CleanShot 2021-05-12 at 22 14 33](https://user-images.githubusercontent.com/1408093/118044459-f43bba80-b376-11eb-868f-b9b6d6932818.png)

Demo: the intermediary page while the fuzzy finder is downloading filenames. For most repos with <20k source files, this step is usually instant. The result is cached for every repoName/commitID pair.

![CleanShot 2021-05-12 at 22 41 57](https://user-images.githubusercontent.com/1408093/118044619-2baa6700-b377-11eb-98a0-fc1d32948a14.png)

2021-05-16 11:34 UTC, olafurpg commented
This is ready for review now! I'm finally happy with the UX in the chromium repo. You can probably get away with a much simpler implementation if you only want to support repos with <50k source files but the current implementation should have acceptable performance even for repos that are larger than the chromium codebase.

2021-05-18 13:38 UTC, novoselrok reviewed
Works great, awesome work 😄 I found a couple of improvements, mostly in React-land. I'll take another look at the Bloom/Fuzzy code, but I doubt I'll be able to find a lot there.

2021-05-18 13:38 UTC, novoselrok commented on client/web/src/fuzzy/HighlightedText.tsx
> +export class HighlightedTextProps {
This class feels a bit out of place. I don't think you're using the `exactCount` and `isExact` methods anywhere, and `offsetSum` is used in only one place.

My suggestion would be to convert this class into an interface
```typescript
export interface HighlightedTextProps {
  text: string
  positions: RangePosition[]
  url?: string
}
```
and convert `offsetSum` into a static method that takes object of `HighlightedTextProps` as an argument. Wherever you instantiate `HighlightedTextProps`, replace it with an object `{ text, positions, url }`.

This also allows you to remove the `HighlightedTextPropsInstance` interface and simplify the `HighlightedText` component signature into:
```ts
export const HighlightedText: React.FunctionComponent<HighlightedTextProps> = ({ text, positions, url }) => {
```

2021-05-18 13:38 UTC, novoselrok commented on client/web/src/fuzzy/FuzzyModal.tsx
> +            error.what = what
Do you need the `.what` value anywhere?

2021-05-18 13:38 UTC, novoselrok commented on client/web/src/fuzzy/FuzzyModal.tsx
> +                    const url = files.results[focusIndex.value].url
You can simplify this by "clicking" the `<a />` tag that is nested inside. Suggestion:
```ts
const fileAnchor = document.querySelector<HTMLAnchorElement>(`#fuzzy-modal-result-${focusIndex.value} a`)
fileAnchor?.click()
```

This would also allow you to omit the `results` prop from the `RenderedFiles` interface and replace it with a `resultsCount`, since you're using `results` just for its length.

2021-05-18 18:42 UTC, limitedmage commented on client/web/src/tree/Tree.scss
> +// TODO(olafur): move the CSS below to a separate "FuzzyModal.scss" file
Also, you should use CSS Modules instead. https://docs.sourcegraph.com/dev/background-information/web/styling#css-modules

2021-05-18 19:02 UTC, limitedmage requested changes

2021-05-18 19:02 UTC, limitedmage commented on client/web/src/repo/RepoContainer.tsx
> +                    const input = document.querySelector('#fuzzy-modal-input') as any
Does this actually work in all browsers? I think you might need to give the browser the chance to render the input after displaying the modal before being able to query for it.

2021-05-18 19:02 UTC, limitedmage commented on client/web/src/tree/Tree.scss
> +}
These colors should use our variables.

2021-05-19 20:13 UTC, olafurpg reviewed
@limitedmage @novoselrok thank you so much for the detailed review! I learned a lot about TS/CSS 🙏 I don't have much experience with frontend development so I really appreciate your guidance.

I managed to address most of the comments, but a few of them remain unresolved.

2021-05-19 20:13 UTC, olafurpg commented on client/web/src/tree/Tree.scss
> +// TODO(olafur): move the CSS below to a separate "FuzzyModal.scss" file
I refactored this to use CSS modules and it's SO much cleaner 😁 

VS Code is not picking up the generated CSS module, but it's working as expected when I run the development server so I'm gonna ignore the VS Code errors.
![CleanShot 2021-05-19 at 22 02 22](https://user-images.githubusercontent.com/1408093/118877061-44be9500-b8ee-11eb-9b20-4285c551fe7d.png)

2021-05-19 20:13 UTC, olafurpg commented on client/web/src/tree/Tree.scss
> +    height: 1.5rem;
Done, the input field looks a bit too large IMO but it's not a big deal, we can refine the CSS  in a followup PR

![CleanShot 2021-05-19 at 22 07 24](https://user-images.githubusercontent.com/1408093/118877396-b0086700-b8ee-11eb-8312-b6b99121a656.png)

2021-05-19 20:13 UTC, olafurpg commented on client/web/src/tree/Tree.scss
> +    font-family: monospace;
Nice, done!

2021-05-19 20:13 UTC, olafurpg commented on client/web/src/tree/Tree.scss
> +.fuzzy-modal-cursor {
Nice catch! I removed the cursor class and everything still looks nice 😎

2021-05-19 20:13 UTC, olafurpg commented on client/web/src/tree/Tree.scss
> +}
How do I define variables? I tried to find how `--body-color` is defined but VS Code "search in files" feature is not giving me examples 🤔

2021-05-19 21:05 UTC, limitedmage commented on client/web/src/fuzzy/FuzzyModal.tsx
> +        <div role="navigation" className="fuzzy-modal" onMouseDown={() => props.onClose()}>
You can use Reach's `<Dialog>` and still apply custom styling. I would also recommend this as Reach is specifically built with accessibility in mind.

2021-05-19 21:06 UTC, limitedmage commented on client/web/src/tree/Tree.scss
> +// TODO(olafur): move the CSS below to a separate "FuzzyModal.scss" file
protip: if you open the generated `.d.ts` file VS will understand things. Kind of annoying :/

2021-05-19 21:09 UTC, limitedmage commented on client/web/src/fuzzy/BloomFilter.js
> +/* eslint-disable */
Hmm do you really need to fork this library instead of importing it and extending it? In this case another option is to fork this bloom filter, publish it on NPM, and add the dependency in that way, along with TypeScript definitions. Storing modified versions of third party libraries in our main repo is not something we ever do. @sourcegraph/frontend-devs  any ideas here?

2021-05-19 23:16 UTC, limitedmage commented on client/web/src/fuzzy/FuzzyModal.tsx
> +export const FuzzyModal: React.FunctionComponent<FuzzyModalProps> = props => {
Definitely, feel free to book some time on my calendar :)

2021-05-19 23:16 UTC, limitedmage commented
I'm thinking this should also be feature flagged so we can disable it until it's ready.

2021-05-19 23:17 UTC, eseliger commented on client/web/src/fuzzy/BloomFilter.js
> +/* eslint-disable */
I guess the easiest could be to just fork the repo into our sourcegraph org, make the changes required and publish it to NPM under `@sourcegraph/bloomfilter`, maybe?
Ultimately, we could try to get rid of that fork again, if we proposed adding a number API and the author of the package accepted a PR adding it, but for the shorter term, I think a fork should do?
I think the minimum is that it appears in the generated license bundle.

2021-05-19 23:20 UTC, eseliger commented on client/web/src/tree/Tree.scss
> +}
`var(--$variablename)` is the CSS syntax to _use_ a variable (ex. `var(--body-bg)`). There are plenty of them defined, which you can find [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/branded/src/global-styles/colors.scss). Chrome dev tools can also show them in the elements tab: 
![image](https://user-images.githubusercontent.com/19534377/118896906-958fb700-b909-11eb-8017-453c7692d655.png)

2021-05-19 23:21 UTC, limitedmage commented on client/web/src/fuzzy/FuzzyModal.module.scss
> +.modal {
@sourcegraph/frontend-devs / @sourcegraph/frontend-platform  do we still want to use BEM-style names with CSS modules?

2021-05-19 23:21 UTC, limitedmage commented on client/web/src/fuzzy/FuzzySearch.test.tsx
> +
You should also wrap the whole test in a higher-level `describe` so that all FuzzySearch tests are grouped together

2021-05-19 23:21 UTC, limitedmage commented on client/web/src/fuzzy/useLocalStorage.tsx
> +}
This is the standard pattern we use (see how we pass, for example, `patternType` and `setPatternType` everywhere throughout the app). For consistency I would prefer to follow the pattern we already use.

2021-05-19 23:29 UTC, eseliger commented on client/web/src/fuzzy/FuzzyModal.module.scss
> +.modal {
stylelint still complains if you don't so I think the current status is yes. I asked the same when I migrated batch changes CSS over to modules, and I kept BEM for now for that reason. Maybe we can discuss it tmr in the frontend-crew meeting, but I _think_ the current answer would be :yes, use BEM"

2021-05-20 06:47 UTC, novoselrok commented on client/web/src/fuzzy/FuzzyModal.tsx
> +            const next: any = await requestGraphQL(
It's automatically generated if you're running the development server, or if you manually run `yarn generate`. You also might need to restart VS Code to find those new generated files.

2021-05-20 13:50 UTC, pdubroy commented
@olafurpg This is super cool! Really nice work, especially if you don't have much experience with TS & CSS 😄

Just some high-level comments from my side:

- This is quite a big PR, and based on the comments so far it seems like the non-UI bits are almost ready to land, but the React stuff needs a bit more iteration. Consider breaking this up into two PRs, so you can land the plumbing stuff ASAP.
- I second @limitedmage's comment that we should put this behind a feature flag (this is in the handbook under [Continuous Releasability](https://about.sourcegraph.com/handbook/engineering/continuous_releasability#a-feature-flag-is-required-for-every-new-feature)). Once it's behind a feature flag then we can land it with a basic UI first, and worry about the finer points of the UX later.

2021-05-20 14:54 UTC, olafurpg commented
I added a feature flag but may have sc

@pdubroy Thank you! I agree this is a large PR. I think we have ironed out most of the React/UI stuff excluding storybook tests and BEM notation. I'm OK with continuing to iterate on this PR until all comments have been addressed, unless everybody think it would be better to merge only the fuzzy filtering parts first.

I will try to split up large PRs in the future!

2021-05-20 14:55 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.module.scss
> +.modal {
I also tried to get inspiration from other module.scss but they use a `&__grid` syntax that I'm not familiar with so I'm not sure how to apply that to the CSS in this PR.

2021-05-20 14:58 UTC, olafurpg commented on client/web/src/fuzzy/HighlightedText.module.scss
> +    color: #000000;
I can't find the original comment from @limitedmage, but adding one here as a reminder to turn these colors into variables.

2021-05-20 17:51 UTC, olafurpg commented
Thank you @limitedmage for the call! I opened #21201 to track improvements that can be added after merging this PR. I pushed a commit that adds the feature flag so this should be disabled unless the settings have `experimentalFeatures.fuzzyFinder: 'enabled'` or the URL has the query parameter `fuzzyFinder=debug` (I couldn't get the experimental settings working locally with the development server)

PS. I love the new react `<Link` single-page app routing, it's super fast to jump between files now 🤩 

![CleanShot 2021-05-20 at 19 19 35](https://user-images.githubusercontent.com/1408093/119022011-67a98180-b9a0-11eb-9128-6e833502366f.gif)

2021-05-20 19:01 UTC, limitedmage approved these changes
Left some small suggestions. Once those are addressed, I think this looks good to check in under a feature flag. Let's keep track of future work in #21201.

2021-05-20 19:01 UTC, limitedmage commented on client/web/src/fuzzy/FuzzyModal.tsx
> +const IS_DEBUG = window.location.href.toString().includes('fuzzyFinder=debug')
I think just using the feature flag should be enough. Try with the boolean as suggested and if it still doesn't work let me know.

2021-05-20 19:26 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +const IS_DEBUG = window.location.href.toString().includes('fuzzyFinder=debug')
I'm using the web-standalone development server for quick edit/debug feedback and I'm unable to update my settings on dotcom

![image](https://user-images.githubusercontent.com/1408093/119037109-d80cce80-b9b1-11eb-8580-4726cf177b21.png)

I wasn't able to get the chromium/chromium repo working on my local server (non-web-standalone). Is it OK to keep this logic for now? We can remove it after dotcom supports enabling the feature flag

2021-05-20 20:03 UTC, pdubroy reviewed
Some final minor comments from me.

I don't feel strongly about splitting it up. There are still some issues with the CSS and TypeScript code, but it's pretty contained and if you're planning to address it in follow up PRs, then I'm happy once @limitedmage is happy :-)

2021-05-21 09:50 UTC, olafurpg reviewed
@limitedmage @pdubroy Thank you for the review! I think I managed address all comments except BEM notation, which I propose we postpone for a separate PR.

The quality of this PR has dramatically improved with all of the insightful review comments. I have learned so much. I really appreciate all the help 🙏

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
>  /* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
I added a comment explaining why this can't be a `eslint-disable-next-line` due to JSX syntax restrictions.

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +const IS_DEBUG = window.location.href.toString().includes('fuzzyFinder=debug')
Nevermind, I removed the URL query parameter and I'm using the non-web-standalone server

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +    // NOTE: the query is cached in local storage to mimic IntelliJ.  It' quite
Fixed.

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +    console.log(props.settingsCascade.final)
Removed.

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +            props.settingsCascade.final?.experimentalFeatures?.fuzzyFinder === 'enabled')
Good point. I refactored the code so that the fuzzy finder has no side effects when disabled. Thanks for the searchStreaming example, that was helpful for inspiration.

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
>  function renderReady(
Good suggestion. Done. I renamed 

- `RenderedFiles` to `RenderedFuzzyResult`
- `method renderFiles(): RenderedFuzzyResult` to `method renderFuzzyResult(): RenderedFuzzyResult`
- `renderReady` to `renderFiles`

> Alternatively, this could be a React component.

I kept this as a method. I tried to refactor the method into a component that but I wasn't able to figure out how pass computed properties from the sub-component. We need computed properties to implement features like cycling the focus index.

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +                            type="button"
Sounds good, 👍 to refining the design later

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +            const next: any = await requestGraphQL(
Yes! Praise be, it's so nice to have auto-complete for GQL 🙏

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +            const next: any = await requestGraphQL(
I removed the `any` casts

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzySearch.test.tsx
> +import { BloomFilterFuzzySearch, allFuzzyParts, fuzzyMatchesQuery } from './BloomFilterFuzzySearch'
Good catch! The implementation started in `FuzzySearch.ts` and I forgot to rename the tests

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/HighlightedText.module.scss
> +    color: #000000;
Leaving this for a separate PR https://github.com/sourcegraph/sourcegraph/issues/21201

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/HighlightedText.tsx
> +export const HighlightedText: React.FunctionComponent<HighlightedTextProps> = props => {
I love that suggestion. Done

2021-05-21 09:50 UTC, olafurpg commented on schema/site.schema.json
> +          "default": "disabled"
Done, I also moved this to `settings.schema.json` for consistency with "search streaming". I manually verified that the setting is working as expected

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.module.scss
> +.modal {
Thank you for the explanation! That makes sense.

Is it OK if we postpone further CSS improvements until later? I'd love to minimize further changes in this PR since it's already quite large

2021-05-21 09:50 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
> +/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
I moved the tsx files to client/web/src/components/fuzzyFinder and kept the ts files in client/web/src/fuzzyFinder. There are still a few undesirable cyclic imports between the two, is that OK? I can followup in a separate PR to untangle those.

2021-05-21 09:59 UTC, olafurpg commented on client/web/src/components/fuzzyFinder/FuzzyModal.tsx
> +export interface FuzzyModalProps
FYI @limitedmage I refactored the code so that `FuzzyModal` has no state, only props. This should make it easier to add storybook tests in the future as we discussed offline.

2021-05-21 10:31 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
>              error.what = what
You're right. I removed this line.

2021-05-21 10:32 UTC, olafurpg commented on client/web/src/fuzzy/FuzzyModal.tsx
>      function onError(what: string): (error: any) => void {
That works. No more eslint-disable for this method \o/

2021-05-21 10:37 UTC, olafurpg commented on client/web/src/tree/Tree.scss
> +}
@eseliger Thank you! It was helpful to look at the colors in the devtools panel. I replaced the hardcoded colors with variables

2021-05-21 15:21 UTC, olafurpg commented on client/web/src/components/fuzzyFinder/FuzzyModal.tsx
> +// NOTE: the eslint-disable above can't be a eslint-disable-next-line because
Sounds good, I added a new item to remove the global eslint-disable

2021-05-21 18:08 UTC, limitedmage reviewed
Some more higher-level comments that can be addressed in follow-up PRs.

2021-05-21 18:08 UTC, limitedmage commented on client/web/src/components/fuzzyFinder/HighlightedLink.tsx
> +}
Do we want to move this to `CaseSensitiveFuzzySearch.ts` and not export it since it seems like the only place where it is used?

2021-05-21 19:02 UTC, marekweb commented
Is the keyboard shortcut `f` or `t`? The PR title and description seem to contradict each other.

2021-05-21 19:15 UTC, olafurpg commented
@marekweb the title was wrong (fixed now). The shortcut is t, the same as on GitHub. 


@limitedmage thank you for the second review! I’m looking forward to iterate on the solution as I see there is still a lot of quirks left and I have a lot to learn 😄

2021-05-21 20:20 UTC, felixfbecker commented on client/web/src/components/fuzzyFinder/HighlightedLink.tsx
> +}
**suggestion**: it may also be more idiomatic in TS to write this inline instead of an writing extra function:
```ts
props.positions.reduce((sum, position) => sum + position.startOffset, 0)
```

2021-05-24 06:03 UTC, olafurpg reviewed
Any advice on how to resolve the CI failure for Percy? I'd love to merge this PR in with minimal changes from the current form and separately address followup comments, which are tracked in https://github.com/sourcegraph/sourcegraph/issues/21201

I really appreciate all of the help and thoughtful review comments on this large PR 🙏

2021-05-24 18:18 UTC, limitedmage commented
@olafurpg  your Percy failures should go away if you sync your branch with main :)

2021-05-24 18:19 UTC, limitedmage commented on client/web/src/components/fuzzyFinder/FuzzyModal.tsx
> +interface RenderedFuzzyResult {
Yes, that's exactly what I meant :)

2021-05-25 07:48 UTC, merged