core/graceful affiliated repos
sourcegraph/sourcegraph pull request #21195
Opened 2021-05-20 15:20 UTC by ryanslade

- graphqlbackend: AffiliatedRepos should handle single failure
- Add test case for all code hosts failing

2021-05-20 16:24 UTC, unknwon requested changes

2021-05-20 16:24 UTC, unknwon commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +	"github.com/sourcegraph/sourcegraph/cmd/frontend/backend"
```suggestion
	"github.com/pkg/errors"
	"github.com/inconshreveable/log15"

	"github.com/sourcegraph/sourcegraph/internal/goroutine"
	"github.com/sourcegraph/sourcegraph/cmd/frontend/backend"
```

2021-05-20 16:24 UTC, unknwon commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +				if err := backend.CheckUserIsSiteAdmin(ctx, a.userID); err != nil {
I thought we don't want site admins to see others' config for the Cloud?

2021-05-20 16:25 UTC, unknwon reviewed
Oh no, hit the wrong button, wanted to just make few comments ...

2021-05-20 18:36 UTC, ryanslade commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +	"github.com/sourcegraph/sourcegraph/cmd/frontend/backend"
Ugh, `goimports` never quite gets it right

2021-05-20 18:36 UTC, ryanslade commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +				if err := backend.CheckUserIsSiteAdmin(ctx, a.userID); err != nil {
Yeah, good point. I'll remove this check

2021-05-21 07:57 UTC, ryanslade commented
@unknwon The tests were failing because the `RunTests` function used from `graph-gophers` was doing a DeepEqual on internal error state which isn't really under our control. I copied the code out of that package and modified it slightly. 

In a follow-up PR I could switch all our existing uses of `RunTests` to use the modified version which also uses `cmp.Diff` making it a lot easier to spot what's gone wrong. 

WDYT?

2021-05-24 13:21 UTC, unknwon approved these changes

2021-05-24 13:21 UTC, unknwon commented on cmd/frontend/graphqlbackend/testing.go
> +
```suggestion
```

2021-05-24 13:24 UTC, unknwon commented
> @unknwon The tests were failing because the `RunTests` function used from `graph-gophers` was doing a DeepEqual on internal error state which isn't really under our control. I copied the code out of that package and modified it slightly.
> 
> In a follow-up PR I could switch all our existing uses of `RunTests` to use the modified version which also uses `cmp.Diff` making it a lot easier to spot what's gone wrong.
> 
> WDYT?

If we can "fix" the "RunTests" then it would be great! Previously, I've been just calling the resolver method directly for error cases, and only use "RunTests" for the happy path:

https://github.com/sourcegraph/sourcegraph/blob/8adbbd51aea37c494ee5650c01293a04873be652/cmd/frontend/graphqlbackend/external_services_test.go#L51-L57

2021-05-24 13:25 UTC, merged