Pod eviction troubleshooting
sourcegraph/sourcegraph pull request #21374
Opened 2021-05-25 20:27 UTC by airamare01

How to doc on pod eviction troubleshoot

2021-05-25 21:35 UTC, daxmc99 requested changes

2021-05-25 21:35 UTC, daxmc99 commented on doc/admin/how-to/troubleshoot-pod-eviction.md
> +1. Run `kubectl exec -it <$EVICTEDPODNAME> -n sourcegraph -- df -h /mnt/cache`
After a pod is evicted, I would be surprised if you can `exec` into it. This could be the rescheduled pod you are exec'ing into. 
Also, `df -h /mnt/cache` would likely only be true for our pods since we use this undocumented convention. 

`kubectl describe pod $EVICTEDPOD` should provide the event which will be much more useful in most cases.

2021-05-25 21:35 UTC, daxmc99 commented on doc/admin/how-to/troubleshoot-pod-eviction.md
> +- [Sourcegraph - Alert solutions](https://docs.sourcegraph.com/admin/observability/alert_solutions)
We should also link to the k8s documentation here since this is not unique to Sourcegraph

2021-05-26 13:41 UTC, airamare01 commented on doc/admin/how-to/troubleshoot-pod-eviction.md
> +1. Run `kubectl exec -it <$EVICTEDPODNAME> -n sourcegraph -- df -h /mnt/cache`
Thanks for the clarification @daxmc99.
Made the changes to the doc.

2021-05-26 13:41 UTC, airamare01 commented on doc/admin/how-to/troubleshoot-pod-eviction.md
> +- [Sourcegraph - Alert solutions](https://docs.sourcegraph.com/admin/observability/alert_solutions)
Done.

2021-05-26 23:43 UTC, daxmc99 approved these changes
Looks good, one small nit to point towards K8s documentation on this

2021-05-26 23:43 UTC, daxmc99 commented on doc/admin/how-to/troubleshoot-pod-eviction.md
> +- [Sourcegraph - Install on Kubernetes](https://docs.sourcegraph.com/admin/install/kubernetes)
```suggestion
- [Kubernetes Eviction docs](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/)
```

2021-05-27 15:09 UTC, merged