Fuzzy finder: add new `fileNames` GraphQL property
sourcegraph/sourcegraph pull request #21422
Opened 2021-05-26 20:10 UTC by olafurpg

Previously, the fuzzy finder used the existing `files()` GraphQL method
to list all the filenames in the repo. This solution was slow in very
large repositories because it uses `git ls-tree` to support more
functionality than what the fuzzy finder needs. This commit adds a new
`fileNames: string[]` property that should have better performance.

2021-05-26 20:11 UTC, olafurpg commented on internal/vcs/git/tree.go
> +func LsFiles(ctx context.Context, repo api.RepoName, commit api.CommitID) ([]string, error) {
@efritz I manually tested this change locally and it seems to work like before. Any advice on how to test this properly?

2021-05-26 20:12 UTC, efritz requested changes

2021-05-26 20:12 UTC, efritz commented on internal/vcs/git/tree.go
> +func LsFiles(ctx context.Context, repo api.RepoName, commit api.CommitID) ([]string, error) {
Is this testable (based on current state of this package, I'm unfamiliar)?

2021-05-26 20:12 UTC, efritz commented on cmd/frontend/graphqlbackend/schema.graphql
> +    fileNames: [String!]!
If you always want it in the repo, I'd actually move this up to the `Commit` node (and well as the method that calls `LsFiles`).

2021-05-27 10:05 UTC, olafurpg commented on internal/vcs/git/tree.go
> +func LsFiles(ctx context.Context, repo api.RepoName, commit api.CommitID) ([]string, error) {
I added a GraphQL test case similar to `TestGitTree`. It doesn't test the actual `git ls-files` logic but it at least validates the GQL interface

2021-05-27 10:20 UTC, olafurpg commented
The CI tests failed with this error, are they related to the changes in this PR?
```

FAIL: TestWorkerConcurrent (3.00s)
--








--- FAIL: TestWorkerConcurrent/numHandlers=9 (0.07s)
--



worker_test.go:222: times 0 (2021-05-27 10:09:19.206874511 +0000 UTC m=+1.584702034-2021-05-27 10:09:19.23028836 +0000 UTC m=+1.608115877) and 18 (2021-05-27 10:09:19.229780267 +0000 UTC m=+1.607607778-2021-05-27 10:09:19.240550178 +0000 UTC m=+1.618377696) failed validation
--



worker_test.go:222: times 0 (2021-05-27 10:09:19.206874511 +0000 UTC m=+1.584702034-2021-05-27 10:09:19.23028836 +0000 UTC m=+1.608115877) and 19 (2021-05-27 10:09:19.229879338 +0000 UTC m=+1.607706853-2021-05-27 10:09:19.24046782 +0000 UTC m=+1.618295341) failed validation
--



worker_test.go:222: times 0 (2021-05-27 10:09:19.206874511 +0000 UTC m=+1.584702034-2021-05-27 10:09:19.23028836 +0000 UTC m=+1.608115877) and 20 (2021-05-27 10:09:19.230255625 +0000 UTC m=+1.608083158-2021-05-27 10:09:19.240573122 +0000 UTC m=+1.618400639) failed validation
--



worker_test.go:222: times 1 (2021-05-27 10:09:19.207057842 +0000 UTC m=+1.584885360-2021-05-27 10:09:19.230342539 +0000 UTC m=+1.608170055) and 19 (2021-05-27 10:09:19.229879338 +0000 UTC m=+1.607706853-2021-05-27 10:09:19.24046782 +0000 UTC m=+1.618295341) failed validation
--



worker_test.go:222: times 1 (2021-05-27 10:09:19.207057842 +0000 UTC m=+1.584885360-2021-05-27 10:09:19.230342539 +0000 UTC m=+1.608170055) and 20 (2021-05-27 10:09:19.230255625 +0000 UTC m=+1.608083158-2021-05-27 10:09:19.240573122 +0000 UTC m=+1.618400639) failed validation
--



worker_test.go:222: times 2 (2021-05-27 10:09:19.207234665 +0000 UTC m=+1.585062181-2021-05-27 10:09:19.218010515 +0000 UTC m=+1.595838101) and 20 (2021-05-27 10:09:19.230255625 +0000 UTC m=+1.608083158-2021-05-27 10:09:19.240573122 +0000 UTC m=+1.618400639) failed validation
--



FAIL
--



coverage: 88.2% of statements
--



FAIL	github.com/sourcegraph/sourcegraph/internal/workerutil	3.071s
--



ok  	github.com/sourcegraph/sourcegraph/internal/workerutil/dbworker	0.067s	coverage: 28.8% of statements
--



ok  	github.com/sourcegraph/sourcegraph/internal/workerutil/dbworker/store	23.500s	coverage: 74.1% of statements
--



?   	github.com/sourcegraph/sourcegraph/internal/workerutil/dbworker/store/mocks	[no test files]
--



ok  	github.com/sourcegraph/sourcegraph/migrations	0.040s	coverage: 75.0% of statements
--



?   	github.com/sourcegraph/sourcegraph/monitoring	[no test files]
--



?   	github.com/sourcegraph/sourcegraph/monitoring/definitions	[no test files]
--



?   	github.com/sourcegraph/sourcegraph/monitoring/definitions/shared	[no test files]
--



?   	github.com/sourcegraph/sourcegraph/monitoring/monitoring	[no test files]
--



?   	github.com/sourcegraph/sourcegraph/schema	[no test files]
--



?   	github.com/sourcegraph/sourcegraph/ui/assets	[no test files]
--



FAIL
--



🚨 Error: The command exited with status 1
--


user command error: exit status 1
```

2021-05-27 13:16 UTC, efritz commented on internal/vcs/git/tree.go
> +func LsFiles(ctx context.Context, repo api.RepoName, commit api.CommitID) ([]string, error) {
It's hard without mocking DefaultClient, which may not give you a lot left to test with. I was just putting this here as a reminder: "if there are other tests in this package for similar functions, it would be easy to copy-and-paste to test the new one", but if the package is already lacking in tests and it's not obvious how, no huge expectation to add a new one unless there's some critical logic that needs an automated case.

2021-05-27 13:17 UTC, efritz commented on cmd/frontend/graphqlbackend/schema.graphql
> +    fileNames: [String!]!
Is there any size of a repo where this is simply infeasible to do without paging? Do we need to consider this now before changing the interface down the road?

2021-05-27 13:17 UTC, efritz approved these changes
:tada:

2021-05-27 13:18 UTC, efritz commented
@olafurpg Looks like flake, was in a different package. Retrying and will look into test.

2021-05-27 14:12 UTC, merged