add first changes
sourcegraph/sourcegraph pull request #21474
Opened 2021-05-27 21:49 UTC by 5h1rU

2021-06-03 00:13 UTC, rrhyne commented
QA items here: 

https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Design-Refresh-Systemization-source-of-truth?node-id=4011%3A912

Note: this PR closes #19628

2021-06-03 12:41 UTC, umpox reviewed
Diff view looks really good! There's a few regressions I've noticed, these pages aren't caught by our visual regression tests yet so have a tendency to sneak in unnoticed

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/GitReferenceTag.scss
>      }
Issue: These changes will cause regressions in the revisions selector

Before:
![image](https://user-images.githubusercontent.com/9516420/120641517-95e09400-c46b-11eb-83b9-fb55cef2e60c.png)

After:
![image](https://user-images.githubusercontent.com/9516420/120641460-882b0e80-c46b-11eb-888e-536995746cf2.png)

Is it possible to scope these so they're not affected here?

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/GitReferenceTag.scss
>      }
We want the default badge styles in the revisions selector and I believe this is just the `<code>` styles on the diff page. I think it would be better to use `<code>` if possible instead of overriding `badge` styles

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/commit/DiffModeSelector.tsx
> +    size?: 'small'
nit: As this can only ever be a single string, I think it works better as a boolean

```suggestion
    small?: boolean
```

and then you can just do
`small && 'btn-sm'`

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/commits/GitCommitNode.tsx
> +            compact={Boolean(compact)}
is compact not already a boolean / not a required prop?

```suggestion
            compact={compact}
```

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/commits/GitCommitNodeByline.tsx
> +
```suggestion
```

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/GitReferenceTag.scss
>      }
Also affects the branches and tags pages

![image](https://user-images.githubusercontent.com/9516420/120644480-469c6280-c46f-11eb-92c1-f75d71001942.png)

![image](https://user-images.githubusercontent.com/9516420/120644507-5320bb00-c46f-11eb-800b-e6c8b4db6161.png)

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/commits/GitCommitNodeByline.tsx
> +
```suggestion
```

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/commits/GitCommitNode.tsx
> +import classNames from 'classnames'
Changes in this file also affect the /commits page, might be possible to scope it to only the diff view to avoid these regressions?

Before:
![image](https://user-images.githubusercontent.com/9516420/120645362-43ee3d00-c470-11eb-9cb6-09489d06f17c.png)


After:
![image](https://user-images.githubusercontent.com/9516420/120645383-4bade180-c470-11eb-8ea9-6b768b0ba3ed.png)

2021-06-03 12:41 UTC, umpox commented on client/web/src/repo/commits/GitCommitNode.tsx
> +    /** Determine the igt diff visualization UI */
```suggestion
    /** Determine the git diff visualization UI */
```

2021-06-03 17:27 UTC, rrhyne commented on client/web/src/repo/GitReferenceTag.scss
>      }
We are generally removing panels and borders so I think this change is ok. Ideally it would be wrapped in a container, but we were not expecting to get to this pages and there is a ticket to address after the redesign.

2021-06-03 17:35 UTC, rrhyne commented on client/web/src/repo/GitReferenceTag.scss
>      }
The revisions (branch/commit/tag) popover looks ok on my machine... I'm definitely not seeing the screenshot @umpox posted, but if that's the case, we do need to avoid introducing that regression.

2021-06-03 17:37 UTC, rrhyne commented on client/web/src/repo/commits/GitCommitNode.tsx
> +import classNames from 'classnames'
This is the commits page I'm seeing currently and I'd be ok with it shipping:

![image](https://user-images.githubusercontent.com/539268/120688155-9e2ed400-c457-11eb-9e81-36d322491d94.png)

2021-06-03 19:11 UTC, 5h1rU commented on client/web/src/repo/GitReferenceTag.scss
>      }
@rrhyne  probably is because you pulled the last changes were this issue was addressed.

2021-06-03 19:14 UTC, 5h1rU commented on client/web/src/repo/commits/GitCommitNode.tsx
> +            compact={Boolean(compact)}
Since this is an old implementation I prefer not to modify so much the original code. I'll put a TODO comment to review at some point in the future.

2021-06-03 23:37 UTC, rrhyne commented on client/web/src/repo/GitReferenceTag.scss
>      }
Thanks @5h1rU, the revisions (branch/commit/tag) popover looks great now.

2021-06-03 23:38 UTC, rrhyne approved these changes
Looks great!

2021-06-04 08:16 UTC, valerybugakov requested changes

2021-06-04 08:16 UTC, valerybugakov commented on client/web/src/repo/commits/GitCommitNodeByline.tsx
>      // Omit GitHub as committer to reduce noise. (Edits and squash commits made in the GitHub UI
Some changes deleted in this file are required for the Code Intel bottom panel redesign introduced in these PRs: https://github.com/sourcegraph/sourcegraph/pull/21560, https://github.com/sourcegraph/sourcegraph/pull/21631

This is how history section looks on this branch:

<img width="1020" alt="Screenshot 2021-06-04 at 11 04 51" src="https://user-images.githubusercontent.com/3846380/120768384-a9b0f680-c54e-11eb-89a6-a256b84d3170.png">

This is how it should look after the redesign: 

<img width="1021" alt="Screenshot 2021-06-02 at 14 53 24" src="https://user-images.githubusercontent.com/3846380/120505541-a3f4cd00-c3f7-11eb-907e-41d4ff54ddb1.png">

2021-06-04 08:16 UTC, valerybugakov commented on client/web/src/repo/commits/GitCommitNode.tsx
> -                <MessageWrapper>{node.subject}</MessageWrapper>
This change is required for the code intel bottom panel redesign.

2021-06-04 08:16 UTC, valerybugakov commented on client/web/src/repo/commits/GitCommitNodeByline.tsx
> +                <small className={`git-commit-node-byline git-commit-node-byline--has-committer ${className}`}>
`git-commit-node-byline` is now used in end-to-end tests as a `data-testid`:

https://github.com/sourcegraph/sourcegraph/blob/51785f2410e24a43ba47aaf375676a7564c2c38d/client/web/src/end-to-end/end-to-end.test.ts#L879

2021-06-04 08:25 UTC, felixfbecker commented on client/web/src/components/diff/FileDiffHunks.scss
> +        }
It would be good if the comment explained not just _what_ it matches, but _why_ it needs to use `:nth-child()`. I.e. why is it not feasible to add a CSS class on the element (possible answer: because the table is returned as HTML from the backend).

2021-06-04 08:25 UTC, felixfbecker commented on client/web/src/repo/commit/RepositoryCommitPage.tsx
> +                                    // eslint-disable-next-line @typescript-eslint/unbound-method
The referenced method is a method, so this ESLint rule is correct here – the method should be changed to a property arrow function, which would make this rule not complain here because `this` would be maintained (note who the method definitely references `this`, so it's an actual issue here, because the function _is_ called in the child component in a way that will unbind `this`).

2021-06-04 08:27 UTC, felixfbecker commented on client/web/src/components/diff/FileDiffNode.tsx
> +import classnames from 'classnames'
Imo `classNames` makes more sense because that's how it's capitalized in the DOM/React API (and in English, it would be two words).

But +1 to a lint rule for this, pointing this out on PRs and changing it back and forth is not a good use of our time :)

2021-06-04 14:32 UTC, umpox commented on client/web/src/repo/commits/GitCommitNodeByline.tsx
> +                <small className={`git-commit-node-byline git-commit-node-byline--has-committer ${className}`}>
Good catch, I can't see any styles applied to this, can it just be preserved as `data-testid`?

2021-06-04 15:18 UTC, valerybugakov approved these changes
Approving because the diff looks great and changes to the commit node component are non blocking anymore as we decided to keep bigger font-size.

2021-06-04 15:27 UTC, valerybugakov commented on client/web/src/repo/commits/GitCommitNode.tsx
> +    handleDiffMode?: (mode: DiffMode) => void
We need ESLint rule for that too. Starting to collect a list of conventions we want to enable 📝

2021-06-04 15:30 UTC, umpox approved these changes

2021-06-04 15:35 UTC, 5h1rU commented on client/web/src/components/diff/FileDiffNode.tsx
> +import classnames from 'classnames'
I created an issue to address this concern. https://github.com/sourcegraph/sourcegraph/issues/21748

2021-06-04 15:38 UTC, 5h1rU commented on client/web/src/repo/commits/GitCommitNode.tsx
> -                <MessageWrapper>{node.subject}</MessageWrapper>
Since we decided to preserve 14px as the font size, this small tag isn't necessary anymore.

2021-06-04 16:07 UTC, merged