Remove 'index' filter from suggestions (resolves #18806)
sourcegraph/sourcegraph pull request #21502
Opened 2021-05-28 14:13 UTC by fkling

From my understanding those filters are only used for the UI, so if this one shouldn't be listed then all that needs to be done is to remove it.

However, if it should be kept in that list then we would need to add a way "blacklist" filters.

Please let me know if that's the correct way to approach this.

2021-05-28 22:51 UTC, rvantonder requested changes
Cool! IMO this is fine to just remove, this is basically debug flag. Looking at build output the tests need updating (and possibly also the FILTERS definition?)

2021-05-29 04:27 UTC, fkling commented
Yeah, I definitely didn't pay attention to all the other places that need updating. Will do so on Monday.

2021-06-01 08:28 UTC, fkling commented
The UI review check seems unrelated to my changes.

2021-06-02 10:40 UTC, lguychard approved these changes

2021-06-02 18:57 UTC, merged