Auto index repogroups
sourcegraph/sourcegraph pull request #21982
Opened 2021-06-10 19:22 UTC by tjdevries

2021-06-10 19:38 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/background/indexing/mock_scanner_test.go
> +	"sync"
This is really stupid, go-mockgen is reordering imports and creating lint.

2021-06-15 22:14 UTC, efritz requested changes
🎉🎉🎉 This is shaping up 💪 💪 💪 💪 💪

2021-06-15 22:14 UTC, efritz commented on internal/search/repos/repos.go
> +		patterns, unionedPatterns := RepoGroupsToIncludePatterns(groupNames, groups)
Does it make sense for this function to return a count of patterns instead of the raw ones? It looks like only len is used.

2021-06-15 22:14 UTC, efritz commented on internal/search/repos/repo_groups.go
> +func ResolveRepoGroupsFromSettings(settings *schema.Settings) map[string][]RepoGroupValue {
Can we get a doc comment here?

2021-06-15 22:14 UTC, efritz commented on internal/search/repos/repo_groups.go
> +// Convert the repo groups from settings
Go-style doc comments (for exported things) need to start with the function name, e.g.

```go
// RepoGroupsToIncludePatterns returns a list of blah blah adn blah blah from blah blah
```

2021-06-15 22:14 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/repo_usage_test.go
> -package dbstore
You can also delete `indexable_repos.*.go` and the related observability fields.

2021-06-15 22:14 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/index_configuration.go
> +const getAutoIdexDisabledRepositoriesQuery = `
Idex

2021-06-15 22:14 UTC, efritz commented on enterprise/internal/codeintel/autoindex/enqueuer/iface.go
>  	ResetIndexableRepositories(ctx context.Context, lastUpdatedBefore time.Time) error
IndexableRepositories, UpdateIndexableRepository, and ResetIndexableRepositories are unused

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing_job.go
> +	repoStore := database.Repos(dbStore.Handle().DB())
You can add an `InitDB` call to the OSS worker package (I can show you exactly where if you can't find it) before the `InitDBStore`. These are all singleton initializers so you can call them as much as you want and you only get one dial (so don't worry about double-connecting).

You can then use `db` instead of extracting the handle from dbstore.

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/iface.go
>  	UpdateIndexableRepository(ctx context.Context, indexableRepository dbstore.UpdateableIndexableRepository, now time.Time) error
Unused

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/iface.go
>  	IndexableRepositories(ctx context.Context, opts dbstore.IndexableRepositoryQueryOptions) ([]dbstore.IndexableRepository, error)
Unused

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
> +	// TODO(autoindex): We should create a way to gather _all_ repogroups (including all user repogroups)
Can we add an issue # here to follow up on?

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
> +	settings, _ := s.settingStore.GetLastestSchemaSettings(ctx, api.SettingsSubject{})
Check error or explain why it's safe to ignore.

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
> +	_, includePatterns := searchrepos.RepoGroupsToIncludePatterns([]string{"cncf"}, groupsByName)
Can extract the literal slice into the top level so its declared similarly to a const value?

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
> +	disabledRepoGroupsList, err := s.dbStore.GetAutoindexDisabledRepositories(ctx)
Check err

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
> +		indexableRepositoryIDs = append(indexableRepositoryIDs, repoID)
```suggestion
		if _, ok := disabledRepoGroups[repoID]; !ok {
			indexableRepositoryIDs = append(indexableRepositoryIDs, repoID)
		}
```

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/index_scheduler.go
> +		indexableRepositoryIDs = append(indexableRepositoryIDs, repoID)
Reads a little cleaner in this case.

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/gen.go
>  //go:generate env GOBIN=$PWD/.bin GO111MODULE=on go install github.com/derision-test/go-mockgen/cmd/go-mockgen
Check new version on main of this, you'll have a conflict on this one: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/worker/internal/codeintel/indexing/gen.go

2021-06-15 22:14 UTC, efritz commented on internal/database/settings.go
> +func (o *SettingStore) GetLastestSchemaSettings(ctx context.Context, subject api.SettingsSubject) (*schema.Settings, error) {
Add a test for this if possible

2021-06-15 22:14 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/mock_iface_test.go
> +	"sync"
I think if you merge in main and re-run `./dev/generate.sh` a lot of this local BS will go away.

2021-06-16 13:14 UTC, tjdevries commented on enterprise/internal/codeintel/stores/dbstore/index_configuration.go
> +const getAutoIdexDisabledRepositoriesQuery = `
LUL

2021-06-16 13:55 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/observability.go
> +	getAutoindexDisabledRepositories       *observation.Operation
You can also remove `indexableRepositories` from this list.

2021-06-16 18:23 UTC, efritz commented on internal/database/settings_test.go
> +
```suggestion
```

2021-06-16 18:25 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/iface.go
> +// TODO: Go back through here and make sure we actually use each of these interface items
Seems good to me

2021-06-16 18:25 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/iface.go
> +// Can probably just re-use the names and get used to that.
```suggestion
type IndexingSettingStore interface {
	GetLastestSchemaSettings(context.Context, api.SettingsSubject) (*schema.Settings, error)
}

```

I think these names are good enough for the first pass :)

It's just ifaces for tests so it's not any huge deal since the places they're used are rather local.

2021-06-16 18:26 UTC, efritz commented on enterprise/internal/insights/discovery/discovery_test.go
> +// TODO: Can I just remove this then?
Did you find an answer?

2021-06-17 01:28 UTC, tjdevries commented on enterprise/internal/insights/discovery/discovery_test.go
> +// TODO: Can I just remove this then?
Yeah, couldn't find any more references

2021-06-17 01:52 UTC, efritz approved these changes

2021-06-17 12:24 UTC, efritz commented on doc/dev/background-information/codeintel/auto-indexing.md
> +TODO(TJ) - These docs need to be updated once we complete the refactoring of autoindexing.
Probably should remove this before merge (replace with a ticket or a non-rendering comment instead of it being in product docs for branch cut).

2021-06-17 12:26 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/services.go
> +	settingStore    *database.SettingStore
Is this used anywhere?

2021-06-17 12:29 UTC, efritz commented on migrations/frontend/1528395834_add_autoindex_enable.up.sql
> +
```suggestion

COMMENT ON COLUMN lsif_index_configuration.autoindex_enabled IS 'Whether or not auto-indexing should be attempted on this repo. Index jobs may be inferred from the repository contents if data is empty.';

```

2021-06-17 12:29 UTC, efritz approved these changes

2021-06-17 15:35 UTC, merged