internal/search: order results by repository priority (star count).
sourcegraph/sourcegraph pull request #22108
Opened 2021-06-16 05:51 UTC by rmmh

This should make result pages more stable and useful.

This requires sourcegraph/zoekt#89 for Zoekt results to include repo priorities.

2021-06-16 09:55 UTC, tsenart commented on cmd/frontend/internal/search/search.go
> +const MaxSearchBufferSize = 5 * (1 << 20) // 5MB
Please add doc strings to these constants.

2021-06-16 09:55 UTC, tsenart commented on cmd/frontend/internal/search/search.go
> +	ents      []*Item
nit: s/ents/items/

2021-06-16 09:55 UTC, tsenart commented on cmd/frontend/internal/search/search.go
> +		if first && queue.Len() > 0 && time.Since(start).Seconds() > MaxQueueDelaySeconds {
`start` seems to remain constant through the lifetime of the HTTP handler invocation. Do we need to reset `start` after we flush?

2021-06-16 09:55 UTC, tsenart commented on internal/search/result/commit.go
> +func (r *CommitMatch) Priority() float64 {
Thoughts on rank vs priority terminology? Rank clicks better for me, and is what we use across Sourcegraph to refer to what we're doing (i.e. ranked search results) but would love to hear your thoughts.

2021-06-16 09:55 UTC, tsenart commented on internal/search/result/match.go
>  	Key() Key
I *think* it would make sense  to put this in Key as field rather than in the Match interface. I came across this before when looking into repo result sorting. See https://github.com/sourcegraph/sourcegraph/pull/22108/files#diff-7650f12b4d12129d6cd0589b10d8c09a28926537b803ddb65f6b97f83614a7d9R63

2021-06-16 09:55 UTC, tsenart commented on cmd/frontend/internal/search/search.go
> -		_ = matchesBuf.Append(m)
Can we add some tests for this new behaviour?

2021-06-17 12:33 UTC, keegancsmith requested changes
Nice stuff. I have quite a bit of feedback. Happy to chat about it later today, since we likely will have some good value out of a VC chat on this.

### Strategy

Most search payloads seem to have a small result size. The way this algorithm is implemented, we will send the highest ranked result (found so far) after 300ms. Then we will send the sorted list once the search is complete (ie we never reach the max size). This seems like suboptimal behaviour, since the user has no results until we are complete.

It seems more appropriate to sort results before sending them to the user. We can then adjust how often we send results (ie adjust the "tick"). This would also avoid the need for a heap, and just rely on Sort. I realise you miss out on some sorting gaurentees, but this seems worth it from a latency perspective.

### Architecture

I would have expected something which takes in our Stream, and returns a new Stream which buffers + sorts. This then avoids coupling ranking to the presentation layer / HTTP streaming layer.

Above I suggested just sorting before sending to the user. This would also be a useful architecture which is mostly decoupled (we need a way to reorder results before send).

### Delay

What made you pick 300ms for the delay? Should we make it tunable for sourcegraph.com while we experiment?

100ms is perceptable to a human. Do you think we could have 80ms as the delay (to allow 20ms for other parts of our codebase to come in). I'm probably being too optimistic because we have a bunch of bad stuff on the critical path right now which means 100ms is likely the fastest part.

Maybe we can add some special logging which logs for your special k numbers, the number of events it found? Then we can analyse that data to pick k.

300ms seems like a good starting point, but would be great to try and see how small we can make it.

2021-06-17 12:33 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search_results.go
>  func compareSearchResults(left, right result.Match, exactFilePatterns map[string]struct{}) bool {
cc @camdencheek does this break any assumptions in deduplicating code? IE it will be possible in the future that after sorting, results from the same repo are not necessarily contiguous

2021-06-17 12:33 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search_results.go
> +	return apri < bpri
can we take this opportunity to clean up this to instead be less deeply nested? ie

```go
if apri != bpri {
  return apri < bpri
}
if arepo != brepo {
  return arepo < brepo
}
//...
```

2021-06-17 12:33 UTC, keegancsmith commented on cmd/frontend/internal/search/search.go
> +const MaxQueueDelaySeconds = 0.3
do these need to be exported?

2021-06-17 12:33 UTC, keegancsmith commented on cmd/frontend/internal/search/search.go
> +func (j *jsonArrayBuf) Append(b []byte) error {
update doc string

2021-06-17 12:33 UTC, keegancsmith commented on cmd/frontend/internal/search/search.go
> +			queuePop()
so we only send one result?

2021-06-17 13:46 UTC, camdencheek commented on internal/search/result/match.go
>  	Key() Key
+1. The intent is to make key contain all sorting/deduplicating info.

2021-06-17 13:54 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
>  func compareSearchResults(left, right result.Match, exactFilePatterns map[string]struct{}) bool {
>  it will be possible in the future that after sorting, results from the same repo are not necessarily contiguous

Shouldn't be a problem. Deduplicating doesn't dedup in place (uses a map slightly inefficiently), so we should be okay as it exists currently

2021-07-09 10:08 UTC, rmmh commented
Closing in favor of #22717.

2021-07-09 10:08 UTC, closed without merging