extensibility: refresh diff status bars
sourcegraph/sourcegraph pull request #22123
Opened 2021-06-16 11:20 UTC by tjkandala

2021-06-17 15:34 UTC, vovakulikov commented on client/web/src/components/diff/FileDiffHunks.tsx
> +                distinctUntilKeyChanged('headViewerId'),
**Q:** Is it here because we don't want to react on baseViewerID anymore?

2021-06-17 15:36 UTC, vovakulikov approved these changes
LGTM. I like this comprehensive description!

2021-06-17 15:52 UTC, tjkandala commented on client/web/src/components/diff/FileDiffHunks.tsx
> +                distinctUntilKeyChanged('headViewerId'),
Yep, technically each viewer ID should only change once (from `undefined` to fixed `ViewerId`), but the base and head viewer IDs could be returned from the extension host at different times, and we don't want to unsub and resub to `extensionHostAPI.getStatusBarItems(viewerId)`, especially with the [long ritual/song and dance we have to do to observe values across contexts](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/shared/src/api/client/api/common.ts?L41-51). There's a lot of Web Worker overhead on the commit page :)

2021-06-18 07:40 UTC, AlicjaSuska requested changes
Thank you for implementing this @tjkandala. Here are things that I think we should change:
- in the unified view, we should display head and base labels as well. I've commented in this [message](https://sourcegraph.slack.com/archives/C01T0BL4EFN/p1623788219032300?thread_ts=1623177353.000700&cid=C01T0BL4EFN) (I've seen you gave the thumbs up)
- please, reduce space between the extension static items, it should be 8px now it's 12px (4px tight padding, 4px margin, 4 px left padding)
- In [Figma](https://www.figma.com/file/30vUPTo5zeoQXdj5c6478w/?node-id=0%3A1), clickable elements have the link styles. Can you make this change? It also answers the question about the hover state (the same as for links: underline)

Thank you @tjkandala! Could you please ping me / request a review again when the changes are ready? :) 


Spacing screenshots:
<img width="544" alt="Screenshot 2021-06-18 at 09 35 02" src="https://user-images.githubusercontent.com/20326070/122524853-ed106800-d018-11eb-9540-9ac0dfd61a92.png">
<img width="427" alt="Screenshot 2021-06-18 at 09 34 52" src="https://user-images.githubusercontent.com/20326070/122524859-eeda2b80-d018-11eb-88d4-deba114372d9.png">

2021-07-12 15:30 UTC, tjkandala commented
Hi @AlicjaSuska, I made the changes you requested:

![Screenshot from 2021-07-12 11-28-38](https://user-images.githubusercontent.com/37420160/125314689-69d6ef00-e304-11eb-94ee-1d367fb1acb1.png)
![Screenshot from 2021-07-12 11-28-45](https://user-images.githubusercontent.com/37420160/125314694-6a6f8580-e304-11eb-9b75-c42e6bc3d146.png)

We have to apply link styles for the whole status bar item from an extension (if clickable) since we can't determine which part is semantically the "link," unlike the design in which `Author: ` didn't have link styles.

2021-07-13 12:23 UTC, AlicjaSuska approved these changes
Thank you @tjkandala ! From the screenshots, it looks good :)

*I couldn't see it locally though. Changes to spacing and link color weren't showing up, even thought I've pulled changes from this branch.

2021-07-14 15:36 UTC, merged