internal/repos: Set owner tag for sync metrics
sourcegraph/sourcegraph pull request #22260
Opened 2021-06-21 12:32 UTC by indradhanush

2021-06-21 12:53 UTC, ryanslade commented on internal/repos/syncer.go
> +		isUserOwned = true
I think we wanted to remove this and rely on the value of owner instead right?

2021-06-21 12:56 UTC, ryanslade commented on internal/repos/syncer.go
> +	// TODO: How does this flag indicate the conditions mentioned in the comment above hold true?
By default, user added external services can only add public code.

If they *are* allowed to add private code then we skip the filtering step on line 265

2021-06-21 13:01 UTC, ryanslade commented on internal/repos/syncer.go
> +		onSourced, err = s.makeNewRepoInserter(ctx, s.Store, isUserOwned, owner)
Agree that is confusing, we can hardcode to false since it always will be as the code is written now anyway.

2021-06-21 13:58 UTC, ryanslade commented on internal/repos/syncer.go
> +	defer save(&diff, owner, &err)
Ah, the second argument to `save` needed to be a string pointer.

When you defer, the arguments are evaluated immediately so the value is always going to be `ownerUndefined` which is what you declared on line 173.

If it's a pointer, then you're able to change the value before the deferred function is actually run. That's why the other two arguments are also pointers.

2021-06-21 17:58 UTC, indradhanush commented on internal/repos/syncer.go
> +	defer save(&diff, owner, &err)
Ah! Great catch! Thank you. This seems to have fixed the bug.

2021-06-21 18:01 UTC, indradhanush commented on internal/repos/syncer.go
> +		isUserOwned = true
Yeah. It appears that `isUserOwned` is being used in another place apart from the argument to `makeNewrepoInserter`

2021-06-21 18:06 UTC, indradhanush commented on internal/repos/syncer.go
> +		onSourced, err = s.makeNewRepoInserter(ctx, s.Store, isUserOwned, owner)
How do you feel about dropping the argument completely? The argument seemse to be passed from `makeNewRepoInserter` -> `insertIfNew` -> `syncRepo` where it is ultimately used in the check:

```
	if publicOnly && sourcedRepo.Private {
		return Diff{}, nil
	}
```

Admittedly I do not understand the need for this check yet.

2021-06-21 19:23 UTC, ryanslade commented on internal/repos/syncer.go
> +		isUserOwned = true
Can we not change all the uses of `isUserOwned` below to `owner == ownerUser`?

2021-06-21 19:40 UTC, ryanslade commented on internal/repos/syncer.go
> +		onSourced, err = s.makeNewRepoInserter(ctx, s.Store, isUserOwned, owner)
It's a very important check 😄 It allows us to specify cases where we should not sync private repos.

But, I think you're right. We can remove the argument in `makeNewRepoInserter` and `insertIfNew`. But we should make sure to continue to pass in `false` from `insertIfNew` -> `syncRepo`

2021-06-21 19:42 UTC, ryanslade requested changes
Cool, I think this is looking good. 

I think you just have a few small `TODO`'s to take care of and then we can do one final check.

We cam alter the actual alerts in another PR

2021-06-22 10:54 UTC, ryanslade commented on internal/repos/syncer.go
> +	owner := ownerUndefined
SyncRepo is only used for site level external services so I think we can safely set owner to site here

2021-06-22 10:58 UTC, ryanslade commented on internal/repos/syncer.go
> +	// https://sourcegraph.atlassian.net/browse/COREAPP-128
This channel is only used by the streaming inserter. It's not used by the ad hoc syncer since that's only enabled on .com and this channel is always nil on .com

2021-06-22 11:02 UTC, ryanslade commented on internal/repos/syncer.go
> +		syncStarted.WithLabelValues(family, string(*owner)).Inc()
I think to be safe we should do this at the top:

```go
var ownerTag string
if owner != nil {
  ownerTag = string(*owner)
}
```

And then use `ownerTag` lower down in `withLabelsValues`

If we skip the nil check we could panic

2021-06-22 11:02 UTC, ryanslade approved these changes
Just a few minor changes, approved to unblock

2021-06-22 11:53 UTC, ryanslade commented
LGTM, let's merge it 👍

2021-06-22 12:42 UTC, merged