chore: Fix usage of errors
sourcegraph/sourcegraph pull request #22657
Opened 2021-07-07 23:25 UTC by efritz

There are several places where I used `errors.Is(err, &want)` that are illegal, where `want` is not something that can be successfully compared. This PR gets rid of these illegal uses.

2021-07-07 23:26 UTC, efritz commented on internal/search/repos/repos.go
> -				if errors.As(err, &git.BadCommitError{}) {
cc @sourcegraph/search-core I believe this is an illegal use which can cause a panic during reflection (the pointer cannot be assigned).

2021-07-07 23:35 UTC, efritz commented on cmd/frontend/graphqlbackend/search_alert.go
> -	if errors.Is(err, authz.ErrStalePermissions{}) {
cc @sourcegraph/search-core I also believe this behavior is incorrect (especially if we switch over to cockroachdb errors package exclusively).

2021-07-08 02:07 UTC, camdencheek requested changes
There are a lot of instances of using `errors.As()` as a simple boolean check in this PR. My understanding is that is the whole purpose of `errors.Is()`. The rule I usually go by is "use `errors.Is()` when you just need to check if the error exists in the chain, and use `errors.As()` when you want to both check that the error exists in the chain _and_ you need to use the fields on the error." Does cockroachdb change the behavior of these compared to the stdlib package?

2021-07-08 02:07 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_alert.go
> -	if errors.Is(err, authz.ErrStalePermissions{}) {
I don't see why this one is incorrect. We don't use the fields of the error, so I don't see a reason to use `errors.As()` instead of `errors.Is()`.

2021-07-08 02:07 UTC, camdencheek commented on internal/search/repos/repos.go
> +				if errors.As(err, &e) {
why not `errors.Is(err, git.BadCommitError{})`?

2021-07-08 09:18 UTC, keegancsmith commented on internal/search/repos/repos.go
> -				if errors.As(err, &git.BadCommitError{}) {
Seems to be fine? https://play.golang.org/p/Du61aNDTf-U

2021-07-08 13:27 UTC, efritz commented
Ok I had a weirder understanding of the cochroachdb errors package behavior. I'm going to start over.

2021-07-08 13:27 UTC, closed without merging

2021-07-08 13:38 UTC, efritz commented on cmd/frontend/graphqlbackend/search_alert.go
> -	if errors.Is(err, authz.ErrStalePermissions{}) {
It _compares_ the fields of each error, though: https://play.golang.org/p/jlm2vWgNIrI

2021-07-08 13:38 UTC, efritz commented on internal/search/repos/repos.go
> -				if errors.As(err, &git.BadCommitError{}) {
Add fields: It _compares_ the fields of each error, though: https://play.golang.org/p/jlm2vWgNIrI

2021-07-08 13:48 UTC, keegancsmith commented on internal/search/repos/repos.go
> -				if errors.As(err, &git.BadCommitError{}) {
I'm not sure I understand. My example doesn't panic, returns true, and matches BadCommitError.Error signature. What's different in your example is the error type has a pointer receiver on Error.

2021-07-08 13:55 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_alert.go
> -	if errors.Is(err, authz.ErrStalePermissions{}) {
Woah. I had no idea. Apparently `errors.Is` only checks `==` equality, not just assignability like `errors.As`. These errors would have to implement a custom `Is()` in order to work like this. Oof. Golang error handling continues to surprise me in unfortunate ways

2021-07-08 13:57 UTC, efritz commented on cmd/frontend/graphqlbackend/search_alert.go
> -	if errors.Is(err, authz.ErrStalePermissions{}) {
I had to check myself a few times to make sure this was actually the behavior that was happening.

Good thing that we recently moved to cockroachdb so this become apparent. I'm going to have a larger-scale refactor of error values to make sure they're used consistently (if not correctly, it will be at least easier to repair mechanically).

2021-07-08 14:04 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_alert.go
> -	if errors.Is(err, authz.ErrStalePermissions{}) {
It seems cockroachdb has [HasType](https://pkg.go.dev/github.com/cockroachdb/errors#HasType), which seems to do what I thought `errors.Is` does.

2021-07-08 14:52 UTC, efritz commented on internal/search/repos/repos.go
> -				if errors.As(err, &git.BadCommitError{}) {
If `BadCommitError.Spec` has a different value in `err` than in what you're comparing, `Is` will return false while `As` returns true. `Is` tries to compare fields (falling back to `Is` method and comparing error strings).

`Is` is meant to compare _equivalent errors_ by some definition of equality
`As` is meant to unwrap/coerce an error into a specific type

Using `Is(err, &SomeBaseErr{})` is fundamentally broken if SomeBaseErr does not define `Is` and has an error string that uses internal fields. We need to use `HasType` instead (which is a planned part of cleanup I'm currently doing).

2021-07-08 15:38 UTC, camdencheek commented on internal/search/repos/repos.go
> -				if errors.As(err, &git.BadCommitError{}) {
I think there's some confusion here -- neither the changed code nor Keegan's example is using `errors.Is`, and `errors.As` does seem to work with an inline type, as demonstrated by Keegan's example. I think this line should have been okay as-is.

2021-07-08 15:42 UTC, efritz commented on internal/search/repos/repos.go
> -				if errors.As(err, &git.BadCommitError{}) {
Ah, sorry, I was only seeing half the change along with the comment. I don't remember how I got something to panic but I can't reproduce it how I remember it happening originally.

This may also be a behavioral difference between stdlib errors and the cockroachdb package.