add repo rev to predicate evaluation
sourcegraph/sourcegraph pull request #22692
Opened 2021-07-08 17:07 UTC by camdencheek

Previously, if a predicate evaluated to a match with a specific repo
rev, the rev would not be added to the expanded query. In practice, 
I don't think this could ever be hit because, if a repo rev was specified, 
the rev filter would apply after the predicate was evaluated as well, 
returning only results that matched the predicate-evaluted repo and 
the original revision-narrowed repo.

That said, there may be cases in the future where predicates can
evaluate to specific revisions of a repo, and fixing this now will save
some headaches down the road.

2021-07-08 20:05 UTC, rvantonder requested changes
![](https://media4.giphy.com/media/VbKLOdvCxBFNZpYvhL/giphy.gif?cid=5a38a5a228wje3bb1eyr56jr7q0hittcsc06rog2jpegu07o&rid=giphy.gif&ct=g)

Thanks for jumping on this. Left an optional suggestion. Requesting changes because this absolutely needs just some kind of test coverage (unit or otherwise).

2021-07-08 20:05 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +
We want to move away from the "@" syntax and appending strings. Currently we have one place where we do this, adding it here will make it two places, and more difficult to move away from completely. My recommendation is to do the following, even though it is currently arguably a bit more roundabout, but much cleaner from a maintenance standpoint. I think it pans out, but you'd have to check...

Sorry for the shorthand Go...

```go
nodes = append(nodes, query.Parameter{Field: query.FieldRepo, Value: "AS BEFORE"}, query.Parameter{Field: query.FieldRev, Value: repoMatch.Rev} // it's fine if repoMatch.Rev is empty because ConcatRevFilters will handle that case
b, _ := query.ToBasicQuery(nodes) // you can ignore error here it won't fail for adding a `rev` param
nodes = query.ConcatRevFilters(b).ToParseTree()
```

This because we have `ConcatRevFilters` to deal with this, but it needs to be a basic query. So we need to do the to/from parse tree conversion. I think it's equally succinct, and maybe a tad more inefficient, but it's going to save some skin dealing with this syntax.

2021-07-08 20:13 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +
Oh, interesting -- I had no idea we were moving away from the `@` syntax. Seems worth the upfront effort. Maybe I'll finally figure out how ConcatRevFilters and friends work 😄 

And thanks for the reminder on the tests 👍

2021-07-08 20:18 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +
`s/move away from/discourage` :-) I don't think we can get rid of `@` syntax any time soon at all, if ever. I hear it trips up users (where do I add the `@`, after the `$`? does the `$` need to be there? etc). But the bigger concern is that it's better to have a canonical representation that separates `rev` from `repo` internally. We currently still parse out `@xyz` downstream when resolving repos, but I'm hopeful I can help change that soon.

2021-07-08 20:25 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +
Hmmm, after thinking about this, I don't think you can actually do this here, since we are going in a loop over multiple repos 😭 . You will just end up with `repo:a rev:b repo:c rev:d ...`  and this can't be evaluated. What you really want is `(repo:a rev:b) or (repo:c rev:d) ...`, but since the `or` node isn't constructed here, those results cannot be made children of an or-operation, we do this somewhere else for this predicate.

2021-07-08 20:27 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +
So, I'm not sure that `ConcatRevFilters` is actually strictly correct here. Consider `repo:a@1 or repo:b@2`. How can that be represented with `rev?`

2021-07-08 20:27 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +
`repo:a@1 or repo:b@2` is not a basic query. `ConcatRevFilters` only works on valid basic queries.

2021-07-08 20:31 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +
I'm not sure I see why we couldn't make an `or` node here. We're already doing that for files (we want to match repo/file pairs). Why not repo/rev/file triples?

2021-07-08 20:32 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +
I'm not sure I remember either, maybe there was a reason :-) All I know is we do that later, currently here: So the `or` construction happens here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results.go?L1097-1099&subtree=true. Because of this, we can't separate the children into `repo:x rev:y` pairs within this function, since it just returns a list :-)

2021-07-08 20:35 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +
Ooh, I see. That seems changeable

2021-07-08 20:36 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +
Well, because my initial suggestion doesn't "just pan out" without more legwork, feel free to punt.

2021-07-09 06:01 UTC, keegancsmith reviewed
LGTM, but I'll leave it to our query language overlord to approve :)

2021-09-15 10:09 UTC, lguychard commented
@camdencheek is this something you plan on taking over the finish line or should it be closed?

2021-09-21 14:17 UTC, camdencheek commented
Oh, completely forgot about this. Will clean it up, but will likely open a new PR since this one is quite stale

2021-12-16 00:29 UTC, rvantonder commented
![abandon](https://user-images.githubusercontent.com/888624/67978774-12e4c100-fbd8-11e9-9c61-371341ae4d2a.jpeg)

2022-01-04 17:03 UTC, camdencheek commented
6 months seems like enough time to leave a PR open, don't ya think? 

@rvantonder I don't think anything has changed since our initial thread, and the only option is still to concatenate the revs directly with the repo, so the updated PR doesn't change that. Really, the only thing I changed since last review was adding tests.

2022-01-06 21:16 UTC, rvantonder approved these changes

2022-01-06 21:48 UTC, merged