internal/search: order results by repository priority (star count).
sourcegraph/sourcegraph pull request #22717
Opened 2021-07-09 10:07 UTC by rmmh

This makes result pages more stable and useful.

This commit takes the partially-ordered stream of results from the zoekt
backends and merges them using two new pieces of information added to
the API: the priority of the shard that a zoekt.SearchResult comes from,
and the maximum shard priority that the backend has not yet returned
results for.

This is a much better way to implement this feature than #22108, with less code, lower latencies, correctness guarantees, and no magic buffer size or latency goal numbers.

TODO: update changelog

2021-07-09 12:02 UTC, tsenart commented on internal/search/backend/horizontal.go
> +				mu.Unlock()
Do we need to protect the actual sending with this lock? Seems like there could be quite some contention with so many Zoekt endpoints? How about popping the heap items to be sent into a temporary local slice, unlocking and then sending off that slice?

2021-07-09 14:38 UTC, keegancsmith reviewed
Will give a closer review to both PRs on Monday, sorry my end of day.

I have one main concern which I need to think more about. But I think it is possible due to hitting limits that we don't always send results down. (ie hitting a limit before a shard is done?)

I also am not convinced yet that `resultQueue` will always be empty. Seems safe to add something which drains it once all streams finish.

2021-07-09 14:38 UTC, keegancsmith commented on internal/search/backend/horizontal.go
> +type PriorityQueue []*zoekt.SearchResult
nit: doesn't need to be exported

2021-07-09 14:38 UTC, keegancsmith commented on internal/search/backend/horizontal.go
> +				}
can we isolate the logic out to make this code less coupled to ordering? eg something like the dedupper implementation above. I imagine something like:

```
orderedResults.Add(sr)
for r, ok := orderedResults.Pop() {
  streamer.Send(r)
}
```

2021-07-13 19:16 UTC, keegancsmith commented
Took another look. My earlier review still stands: concerned about the need to flush the queue, want a more decoupled implementation.

Either way this is a nifty implementation! I like the use of max pending. The algorithm almost reminds me of a variant of "sliding window minimum" problems, but no need to optimize since endpoints is small.

Out of interest, are we gaurenteed that max pending is monotonically decreasing per endpoint? I assume so, otherwise we can't decide when to send :)

2021-07-15 09:20 UTC, rmmh commented on internal/search/backend/horizontal.go
> +				mu.Unlock()
The StreamSearch operations are already nested repeatedly and take locks to protect the send in at at least two layers above this. It doesn't seem to matter, since it's a few dozen locks for a search operation that takes at least tens of milliseconds.

2021-07-15 09:21 UTC, rmmh commented on internal/search/backend/horizontal.go
> +type PriorityQueue []*zoekt.SearchResult
done.

2021-07-15 09:21 UTC, rmmh commented on internal/search/backend/horizontal.go
> +				}
done

2021-07-16 11:44 UTC, tsenart approved these changes
LGTM

2021-07-16 12:07 UTC, keegancsmith commented
@rmmh I pushed the zoekt update so we could see what CI says. Also pushed to the backend dry run branch so we could see what the integration tests say https://buildkite.com/sourcegraph/sourcegraph/builds/101895

2021-07-16 12:16 UTC, keegancsmith commented on internal/search/backend/horizontal.go
> +				}
I imagined something which hid nearly all the changes here. For example a lot of the setup code/etc. Rather than blocking this review, lets land it and I can follow-up with a PR with my idea. Then we can discuss it further.

2021-07-16 12:30 UTC, keegancsmith requested changes
I'm still very concerned about the queue not being empty once this is all done. So I am requesting changes. I think this might have been missed when you addressed comments? But it was the reason  Irequested changes before.

2021-07-16 12:30 UTC, keegancsmith commented on internal/search/backend/horizontal.go
> +				endpointMaxPendingPriority[endpoint] = sr.Progress.MaxPendingPriority
> concerned about the need to flush the queue

I'm still concerned about this. Can we add an explicit flush once every goroutine is done? Maybe even log what the size of the queue is at the end?

I assume the reason it works is because the last result will always be `MaxPendingPriority=0` for each endpoint? I worry what happens when we hit limits though.

2021-07-16 15:02 UTC, keegancsmith commented
Seems to have a race condition that CI is complaining about. Try running with `go test -race` to repro.

2021-07-19 15:20 UTC, rmmh commented on internal/search/backend/horizontal.go
> +				endpointMaxPendingPriority[endpoint] = sr.Progress.MaxPendingPriority
Added a final flush with a logged warning when it's hit.

Yes, MaxPendingPriority should be 0 for each endpoint when it processes its last result.

2021-07-19 15:21 UTC, rmmh commented
> Seems to have a race condition that CI is complaining about. Try running with `go test -race` to repro.

It was racing on an unguarded read of resultQueueMaxLength-- harmless, but fixed.

2021-07-19 16:01 UTC, keegancsmith approved these changes
LGTM!

2021-07-19 16:38 UTC, merged