EventLogger: Return sourcegraph.com hostname only for internal referrers
sourcegraph/sourcegraph pull request #22864
Opened 2021-07-15 07:34 UTC by attfarhan

Addresses part of https://github.com/sourcegraph/sourcegraph/pull/22747#issuecomment-879764196

@malomarrec wants to distinguish referrers between direct traffic (which have an empty referrer) and navigation from within sourcegraph.com.

For Sourcegraph.com URLs, show the referrer as just sourcegraph.com, and remove all pathnames/query params to avoid leaking private repo/file names and search queries.

2021-07-15 08:07 UTC, malomarrec commented
@attfarhan how about returning `subdomain.sourcegraph.com`, so as to be able to attribute traffic to the docsite, about page, etc?
I think it would be a matter of removing whatever comes after the first `/` or `?`

2021-07-15 08:08 UTC, malomarrec requested changes
@attfarhan how about returning subdomain.sourcegraph.com, so as to be able to attribute traffic to the docsite, about page, etc?
I think it would be a matter of removing whatever comes after the first / or ?

2021-07-15 08:10 UTC, attfarhan commented
@malomarrec the docs site and about page were not affected by this at all (see my comment in Slack and in the original PR). It's only exact when the hostname is EXACTLY `sourcegraph.com` that we don't return the full URL.  See this screenshot for data we're already returning, and you'll see an about.sourcegraph.com domain is already returned in its entirety: https://sourcegraph.slack.com/files/UMJTLCRH9/F028484T57D/screen_shot_2021-07-14_at_6.43.58_pm.png

2021-07-15 08:13 UTC, malomarrec approved these changes

2021-07-19 08:07 UTC, eseliger approved these changes

2021-07-19 08:19 UTC, merged