API docs: LSIF: add GraphQL backend for "Go to API docs"
sourcegraph/sourcegraph pull request #22902
Opened 2021-07-16 01:20 UTC by slimsag

This adds everything we need to have existing codeintel tooltip GraphQL requests `?Ranges` and `?DefinitionAndHover` also fetch documentation info when present. This is just a path ID string, which we can use to compose a URL to the actual API docs page for the given symbol.

Here is an example of the [`?Ranges` query](http://localhost:3080/api/console#%7B%22query%22%3A%22query%20Ranges(%24repository%3A%20String!%2C%20%24commit%3A%20String!%2C%20%24path%3A%20String!%2C%20%24startLine%3A%20Int!%2C%20%24endLine%3A%20Int!)%20%7B%5Cn%20%20repository(name%3A%20%24repository)%20%7B%5Cn%20%20%20%20commit(rev%3A%20%24commit)%20%7B%5Cn%20%20%20%20%20%20blob(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20ranges(startLine%3A%20%24startLine%2C%20endLine%3A%20%24endLine)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20nodes%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20documentation%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20pathID%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repository%5C%22%3A%20%5C%22github.com%2Fsourcegraph-testing%2Fetcd%5C%22%2C%5Cn%20%20%5C%22commit%5C%22%3A%20%5C%22461eb90e5e85791f08332657dfdfa1a60677edf5%5C%22%2C%5Cn%20%20%5C%22path%5C%22%3A%20%5C%22auth%2Fstore.go%5C%22%2C%5Cn%20%20%5C%22startLine%5C%22%3A%2060%2C%5Cn%20%20%5C%22endLine%5C%22%3A%20110%5Cn%7D%22%2C%22operationName%22%3A%22Ranges%22%7D) returning the expected data:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/3173176/125877186-4704535a-f4a7-4a22-916f-fa38f16a86f6.png">

And here's an example of the [`?DefinitionAndHover` query](http://localhost:3080/api/console#%7B%22query%22%3A%22query%20DefinitionAndHover(%24repository%3A%20String!%2C%20%24commit%3A%20String!%2C%20%24path%3A%20String!%2C%20%24line%3A%20Int!%2C%20%24character%3A%20Int!)%20%7B%5Cn%20%20repository(name%3A%20%24repository)%20%7B%5Cn%20%20%20%20commit(rev%3A%20%24commit)%20%7B%5Cn%20%20%20%20%20%20blob(path%3A%20%24path)%20%7B%5Cn%20%20%20%20%20%20%20%20lsif%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20hover(line%3A%20%24line%2C%20character%3A%20%24character)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20markdown%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20range%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20start%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20end%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20line%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20character%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%20%20documentation(line%3A%20%24line%2C%20character%3A%20%24character)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20pathID%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repository%5C%22%3A%20%5C%22github.com%2Fsourcegraph-testing%2Fetcd%5C%22%2C%5Cn%20%20%5C%22commit%5C%22%3A%20%5C%22461eb90e5e85791f08332657dfdfa1a60677edf5%5C%22%2C%5Cn%20%20%5C%22path%5C%22%3A%20%5C%22auth%2Fstore.go%5C%22%2C%5Cn%20%20%5C%22line%5C%22%3A%2084%2C%5Cn%20%20%5C%22character%5C%22%3A%205%5Cn%7D%22%2C%22operationName%22%3A%22DefinitionAndHover%22%7D):

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3173176/125877298-16ceb138-55e6-4830-a34b-28b9440bb43f.png">

Signed-off-by: Stephen Gutekanst <stephen@sourcegraph.com>

2021-07-16 01:20 UTC, slimsag commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
> +	adjustedLocations, err := r.Definitions(ctx, line, character)
Notably, this implementation _does_ handle cross-repo lookups. So we'll be able to do "Go to API docs" for a symbol defined in another repo.

2021-07-16 01:21 UTC, slimsag commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query.go
> +	PathID string
I declared this as a struct type so we can extend it later if desired to e.g. include more hints about what kind of info can be found in the documentation.

2021-07-16 20:10 UTC, efritz commented on enterprise/internal/codeintel/stores/lsifstore/ranges.go
>  	}
This can become a very slow operation. Like the definition and reference locations above, is it possible to collapse the queries here into a series of bulk selects from the database instead of a set of n+1 queries?

2021-07-16 20:15 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
> +		ranges, err := r.lsifStore.Ranges(
This seems round-about to me. Can we add some of this logic into LSIF store instead of in the resolver? For example, the range check below is done in LSIF store (via `semantic.FindRanges`).

2021-07-19 18:33 UTC, slimsag commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
> +		ranges, err := r.lsifStore.Ranges(
At first, I tried replicating what the `r.Definitions` resolver does - and just adjusting it to do `(line, character) -> pathID` instead of `(line, character) -> definitionPosition` but it turned out to be a LOT of code:

* I would need to duplicate most of the `r.Definitions` function
* We wouldn't be able to use `r.monikerLocations` because it returns locations, we need path ID strings. So I'd need to duplicate that entire method, as well as introduce an LSIF store `DocumentationBulkMonikerResults` method which is mostly copied, as well as copying its underlying methods like `scanQualifiedMonikerLocations` etc. just in order to return a string instead of `Location` type.
* I would also need to introduce a new table for mapping monikers -> documentation; similar to how we have one mapping monikers -> definitions (the table argument to `r.monikerLocations`) - as well as all the logic to insert/update that table.

After I went down that path, it seemed like an awful lot so I felt I had the wrong approach and started over. I was thinking "I should be able to just call the `r.Definitions` resolver, and map the result it gives me to documentation instead" and that's how I ended up here with this.

I'm not positive I understand your ask, exactly - I have looked at `semantic.FindRanges`, but the reason we can't simply rely on that - and the reason this needs to be here in the resolver layer - is because we need to call into the `r.Definitions` resolver above to get the locations.

Maybe you have another idea / suggestion I'm not seeing?

2021-07-19 23:17 UTC, slimsag commented
Merged my stacked PR #22903 into here, sorry if that makes it more annoying to view now.

2021-07-19 23:53 UTC, slimsag commented on enterprise/internal/codeintel/stores/lsifstore/ranges.go
>  	}
Fixed; really good call here - can't believe I didn't think of this sooner.

2021-07-19 23:57 UTC, slimsag commented
@efritz PTAL at the very latest commit, c22bd9a10fd3e9f8196ff168b23828b45e038c91 - and my other comment https://github.com/sourcegraph/sourcegraph/pull/22902#discussion_r672536175

I think that discussion there is the last thing blocking this.

2021-07-20 13:46 UTC, efritz commented on enterprise/internal/codeintel/stores/lsifstore/documentation.go
> +		log.String("ids", fmt.Sprint(ids)),
Does this work? I thought you would have needed `strings.Join(...)` (I think there's a util function to format lists of ids).

2021-07-20 13:47 UTC, efritz commented on enterprise/internal/codeintel/stores/lsifstore/documentation.go
> +				return nil, errors.Wrap(err, "Atoi")
nit: generally I don't wrap calls errors from stdlib (unless it's something like exec.Cmd of which there could be many invocations in a short code area) as the error messages are already usually obvious.

2021-07-20 13:50 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
> +		ranges, err := r.lsifStore.Ranges(
My concern here is that you're calling `Ranges` which looks up *everything* about a window of source text. You are only extracting a single value from the matching ranges, which is the vast majority of what you brought back from the database here.

I think that there should be a more specific lsifstore method that will get you a list of documentation path ids from some input. That way it doesn't have to gather information for the ranges you filter out on lines 124-126.

2021-07-20 13:50 UTC, efritz requested changes
Last commit looks good 🎉 . I still have one outstanding comment about the use of `Ranges` inline.

2021-07-20 18:41 UTC, slimsag commented on enterprise/internal/codeintel/stores/lsifstore/documentation.go
> +		log.String("ids", fmt.Sprint(ids)),
It does work: https://play.golang.org/p/sa76VrSOOtT

I wasn't able to locate such a util function (using `repo:^github\.com/sourcegraph/sourcegraph$ []semantic.ID AND Join`) - and I can't use `strings.Join` without converting from `[]semantic.ID` to `[]string` first so I'll leave this as-is.

2021-07-20 18:42 UTC, slimsag commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
> +		ranges, err := r.lsifStore.Ranges(
Ohh! I get it, that makes a lot of sense - thank you!

2021-07-20 19:24 UTC, slimsag commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_documentation.go
> +		ranges, err := r.lsifStore.Ranges(
Fixed in f2593a6e296239059622b23f889386c93aed21e0

2021-07-20 20:52 UTC, merged