deployment_best_practices.md
sourcegraph/sourcegraph pull request #22907
Opened 2021-07-16 05:23 UTC by DaedalusG

This is the culmination of the Sourcegraph "What We Support" document: 
v2 https://docs.google.com/document/d/1AjJ4rjayco5HqHcEl9utGavdbFfFO1ODhgT8YJVkA7E/edit?ts=60d3839f#heading=h.7ut6cwhw8tww
v1 https://docs.google.com/document/d/1HyOIqAA92ZjJVTDhQcfr1fwU8HxTkFLpBEeQR_tQnmo/edit#heading=h.7ut6cwhw8tww

Will need to make some other PRs to set up indexing and hyperlinks to reach this page

2021-07-16 05:42 UTC, abeatrix approved these changes
LGTM! thanks Warren!

2021-07-19 22:51 UTC, daxmc99 requested changes
Some minor suggestions around k8s but looks good!

2021-07-19 22:51 UTC, daxmc99 commented on doc/admin/deployment_best_practices.md
> +- The Sourcegraph host&#39;s Kubernetes version should be 1.17, 1.18, or 1.19
```suggestion
- The suggested Kubernetes version is the current [GKE Stable release version](https://cloud.google.com/kubernetes-engine/docs/release-notes-stable)
- We attempt to support new versions of Kubernetes 2-3 months after their release.
```

2021-07-19 22:51 UTC, daxmc99 commented on doc/admin/deployment_best_practices.md
> +- The Sourcegraph host&#39;s Kubernetes version should be 1.17, 1.18, or 1.19
We should avoid suggesting the latest EKS here. We typically lag behind supporting the new k8s versions.

2021-07-19 22:51 UTC, daxmc99 commented on doc/admin/deployment_best_practices.md
> +  - vanilla Kubernetes .yaml files deployed with few modifications
```suggestion
```
The sooner we scope all changes to Kustomize overlays I think the better our customer experience will be. Feel free to disregard though, this is more of a nit.

2021-07-20 01:00 UTC, virginiaulrich approved these changes
Please consider Dax's review and LGTM from my side!

2021-07-20 01:08 UTC, bobheadxi requested changes
thanks for adding this type of information! 🙏  I think they should live in the relevant places instead of a separate page however, to keep them from going out of date and make it easier to find relevant information in the appropriate guides/docs

2021-07-20 01:08 UTC, bobheadxi commented on doc/admin/deployment_best_practices.md
> +## Deployment Best Practices
can we keep this information consolidated in the various deployment method documentation instead of giving it a separate page?

https://docs.sourcegraph.com/admin/install/docker-compose
https://docs.sourcegraph.com/admin/install/kubernetes
https://docs.sourcegraph.com/admin/install/docker

2021-07-20 01:08 UTC, bobheadxi commented on doc/admin/deployment_best_practices.md
> +## Additional Support Information
these don't seem related to deployment best practices 🤔

2021-07-20 01:08 UTC, bobheadxi commented on doc/admin/deployment_best_practices.md
> +  - Android Studio
this should be somewhere in https://docs.sourcegraph.com/extensions instead

2021-07-20 01:10 UTC, bobheadxi commented on doc/admin/deployment_best_practices.md
> +## Additional Support Information
again, I don't think this should be in a separate page - instead, we should optimize for making this information surfaceable via searches and/or add links at points in the documentation that is related to this information

2021-07-21 23:11 UTC, DaedalusG commented on doc/admin/deployment_best_practices.md
> +## Deployment Best Practices
@bobheadxi This document was first drafted as a what we support doc. While its titled "Best Practices" its intended as a tool that CEs, CSEs, and sales team members can show to customers intending to customize or diverge from "standard" use cases

2021-07-21 23:12 UTC, DaedalusG commented on doc/admin/deployment_best_practices.md
> +## Additional Support Information
As in other comment

2021-07-21 23:12 UTC, DaedalusG commented on doc/admin/deployment_best_practices.md
> +  - Android Studio
As in other comment

2021-07-22 00:03 UTC, merged

2021-07-22 01:42 UTC, bobheadxi commented on doc/admin/deployment_best_practices.md
> +## Deployment Best Practices
I've opened a PR with a potential direction, as well as added a patch to demonstrate how to apply what I'm talking about here! Would appreciate if you could take a look :)

- https://github.com/sourcegraph/sourcegraph/pull/23029#issuecomment-884603490
- https://github.com/sourcegraph/sourcegraph/commit/d076a6a8d6403d1ca4737aa4cc027c4fab24678e

2021-07-22 01:46 UTC, virginiaulrich commented on doc/admin/deployment_best_practices.md
> +## Deployment Best Practices
I think it's actually pretty important that this is a stand-alone document right now. At least for now. We want customers to easily see this all in one place for easier decision making and going down best path sooner. Can we please keep this as-is and also duplicate the information as you see fit (if you feel that strongly about it)? Happy to talk through this with you @bobheadxi so you can have context from the last 3 months of work, where this all came from, and why it matters quite a lot to not pull this info into multiple docs.

2021-07-22 01:54 UTC, bobheadxi commented on doc/admin/deployment_best_practices.md
> +## Deployment Best Practices
I'm curious why going through a link is a blocker here - for example, a customer looking for best practices regarding docker-compose can still easily see all relevant information (titled appropriately to hint at its contents), except this way _any_ customer who might not be even considering best practices yet can still see it as they go through the normal deployment docs. This makes it easier for us to update best practices as they change too.

Diff pasting here for reference: 

![image](https://user-images.githubusercontent.com/23356519/126580156-9cd982e5-168b-4bb6-bb2f-da2b4b8d7232.png)

If there's a decision document or something I can refer to about why going through links is very important, I'd appreciate if I could take a look! I'm skimming through one example listed (https://docs.gitlab.com/ee/administration/reference_architectures/#deviating-from-the-suggested-reference-architectures) and it's also primarily links, though it has a lot of context on deployment variation that they don't have documented elsewhere. I think a key difference is that we _do_ have references to strong recommendations about configuration everywhere, and it would be good to just consolidate. For example, in #23029 I noted some comments are copied in many places and each vary ever so slightly making it really hard to figure out what's "right"

2021-07-22 02:23 UTC, virginiaulrich commented on doc/admin/deployment_best_practices.md
> +## Deployment Best Practices
Oh I see! I missed this dif in #23029 when I looked earlier and then saw this comment and it didn't click to go back and look. I agree with your approach .... I was worried this doc had to go away, but keeping this doc, moving to links so info is not duplicated, is, of course, brilliant! Long day for me, Robert; sorry you had to take extra time to get to me to get this.

2021-07-22 02:25 UTC, bobheadxi commented on doc/admin/deployment_best_practices.md
> +## Deployment Best Practices
No worries! I just noticed my original comment was poorly worded too - instead of arguing against "giving it a separate page" I think I meant "_placing_ it on a separate page" 😅 Thank you for taking a look, and sorry for the misunderstanding!