Code insights/tooltip texts proofreading
sourcegraph/sourcegraph pull request #22970
Opened 2021-07-19 13:37 UTC by vovakulikov

Closes https://github.com/sourcegraph/sourcegraph/issues/22963

### Background
This PR adds an explanation tooltip for the disabled global visibility radio button in the creation form and fixes tooltip dashboard-related texts.

2021-07-19 13:39 UTC, vovakulikov commented on CHANGELOG.md
> +- Experimental: Search-based code insights can run over all repositories on the instance. To enable, use the feature flag `"experimentalFeatures": { "codeInsightsAllRepos": true }`. [#22759](https://
@felixfbecker Can you please take a look at this line

2021-07-19 13:40 UTC, vovakulikov commented on client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/utils/get-global-subject-tooltip-text.ts
> +        : "You don't have permission to change the global scope. Reach out to your site admin"
@Joelkw @AlicjaSuska @felixfbecker these tooltip texts require proofreading.

2021-07-19 13:54 UTC, felixfbecker commented on CHANGELOG.md
> +- Experimental: Search-based code insights can run over all repositories on the instance. To enable, use the feature flag `"experimentalFeatures": { "codeInsightsAllRepos": true }`. [#22759](https://
```suggestion
- Experimental: Search-based code insights can run over all repositories on the instance. To enable, use the feature flag `"experimentalFeatures": { "codeInsightsAllRepos": true }` and tick the checkbox in the insight creation/edit UI. [#22759](https://github.com/sourcegraph/sourcegraph/issues/22759)
```

2021-07-19 15:22 UTC, felixfbecker commented on client/web/src/insights/pages/dashboards/creation/components/insights-dashboard-creation-content/utils/get-global-subject-tooltip-text.ts
> +        : "You don't have permission to change the global scope. Reach out to your site admin"
I might just shorten/combine the sentences:
```suggestion
        : "Only site admins can change global settings"
```
Ideally I'd say "Only site admins can define global insights" or "[...] dashboards" if we know here whether this is for an insight or dashboard.

2021-07-20 10:20 UTC, AlicjaSuska requested changes
@vovakulikov as we've discussed today, we should change texts a little so they are more understandable for the users:

Creation UI:
- 'Only site admins can create global insights'.
I think it is more in the context of creation UI than saying 'Only site admins can change global settings' - as user is not directly trying to change the settings


Default dashboards:
- For orgs: 'This is an automatically created dashboard that lists all the [Org]'s insights. You can't edit this dashboard.' - this would explicitly state why editing is not available
- For All insights: 'This is an automatically created dashboard that lists all the  insights you have access to. You can't edit this dashboard.'
- For all private: 'This is an automatically created dashboard that lists all your private insights. You can't edit this dashboard.'

2021-07-20 11:27 UTC, vovakulikov commented
@AlicjaSuska I changed all text according to your comment above, thanks for it btw. 

Also, I used assign instead of `add` in the dashboard initial state and changed Add/remove insights to Assign or Remove insights in the dashboard context menu action.

2021-07-20 11:53 UTC, AlicjaSuska requested changes

2021-07-20 11:53 UTC, AlicjaSuska commented on client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
> +                case InsightsDashboardType.Organization:
@vovakulikov can we add :' This is an automatically created dashboard that lists all the [${dashboard.organisation.name} insights. You can't edit this dashboard.' for the Orgs?

2021-07-20 11:53 UTC, AlicjaSuska commented on client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
> +                    return `This is an automatically created dashboard that lists all the ${dashboard.owner.name}'s insights. You can't edit this dashboard.`
@vovakulikov in the current implementation we use '[user] insights' not '[users]'s insight'. I think we should be consistent here as well and change to ${dashboard.owner.name} insights (no 's). It came from my previous comment, sorry for this mistake. Thank you!

2021-07-20 11:56 UTC, vovakulikov commented on client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
> +                    return `This is an automatically created dashboard that lists all the ${dashboard.owner.name}'s insights. You can't edit this dashboard.`
@AlicjaSuska done, thanks

2021-07-20 12:00 UTC, vovakulikov commented on client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
> +                case InsightsDashboardType.Organization:
@AlicjaSuska not sure I got it. What is the difference between the current text and the text you suggested? dashboard owner name has a value of organization name in case if that dashboard has org scope of visibility if you meant it.

2021-07-20 12:26 UTC, AlicjaSuska commented on client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
> +                case InsightsDashboardType.Organization:
Oh, got it now. Sorry, please ignore the comment above. Thank you!

2021-07-20 12:27 UTC, AlicjaSuska approved these changes

2021-07-20 12:28 UTC, merged

2021-07-21 09:17 UTC, felixfbecker commented on client/web/src/insights/pages/dashboards/dashboard-page/hooks/use-dashboard-permissions.ts
> +                    return `This is an automatically created dashboard that lists all the ${dashboard.owner.name}'s insights. You can't edit this dashboard.`
I'd actually prefer if we changed the implementation to use possessive form everywhere, that's what we decided on in the design. The possessive form communicates the concept of ownership better and "Vova insights" sounds wrong grammatically imo.