WIP: codeintel: add dependency repositories referenced in LSIF uploads
sourcegraph/sourcegraph pull request #22984
Opened 2021-07-19 15:54 UTC by Strum355

2021-07-27 09:26 UTC, olafurpg reviewed
I just merged https://github.com/sourcegraph/sourcegraph/pull/23163, which unblocks this PR

2021-07-27 18:40 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/dependencyrepos/dependency_repos_adder.go
> +	}
One error is bad but two errors can bully their way through.

2021-07-27 18:49 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/dependencyrepos/dependency_repos_adder.go
> +func (h *dependencyRepoAddingHandler) Handle(ctx context.Context, record workerutil.Record) error {
Can this job be rolled into https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go?L55? I think we can generalize it to be not index-specific (and it saves us from having to monitor and maintain a separate queue although they perform the same class of work).

2021-07-27 18:50 UTC, efritz commented on internal/repos/jvm_packages.go
> +	}
Why would this contain things that aren't in the maven modules results?

2021-07-27 18:50 UTC, Strum355 commented on enterprise/cmd/worker/internal/codeintel/dependencyrepos/dependency_repos_adder.go
> +func (h *dependencyRepoAddingHandler) Handle(ctx context.Context, record workerutil.Record) error {
Yes, thats the advice I was looking for 👌 something felt not 100% about what I had but couldnt formulate it

2021-07-27 19:53 UTC, Strum355 commented on internal/repos/jvm_packages.go
> +	}
Those modules are fetched from the statically defined config

2021-07-27 20:00 UTC, efritz commented on internal/repos/jvm_packages.go
> +	}
Who is calling the enclosing function and why?

2021-07-27 20:01 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/dependencyrepos/dependency_repos_adder.go
> +func (h *dependencyRepoAddingHandler) Handle(ctx context.Context, record workerutil.Record) error {
It seems to be a simple swap over; you'll want to just move the same behavior into the Handle function of the other one then delete the additional resetter, dbstore, and registration code.

The behavior of the dependency index job will change a bit, but that's to be expected.

2021-07-27 20:01 UTC, Strum355 commented on internal/repos/jvm_packages.go
> +	}
This is called by repo-updater for uh repo-updater reasons. Not sure what else to say :sweat_smile:

2021-07-27 20:01 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/dependencyrepos/dependency_repos_adder.go
> +func (h *dependencyRepoAddingHandler) Handle(ctx context.Context, record workerutil.Record) error {
There may be ways to hook into the existing infra as well. See [this comment for some context](https://github.com/sourcegraph/sourcegraph/issues/21884#issuecomment-879089406).

2021-07-29 14:08 UTC, efritz commented on enterprise/cmd/worker/main.go
> +
This can be moved into NewSyncingJob.Routines to keep the initialization here clean

2021-07-29 14:10 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +		extsvcKind, ok := schemeToExternalService[packageReference.Scheme]
Lines 67-69 should likely not guard all of the new code here; you'll probably want to conditionally call QueueIndexForPackage instead of early-return.

2021-07-29 14:12 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +	return upload.Indexer == "lsif-go" || upload.Indexer == "lsif-java", nil
Might want to hold off on this until the queue settles down a bit after opening it to all go repos. My other comment here should still get us the behavior I think you were looking for here.

2021-07-29 14:14 UTC, efritz commented on internal/repos/store.go
> +func scanJVMDependencyRepo(rows *sql.Rows) ([]JVMDependencyRepo, error) {
This doesn't match the other scan signatures that take a second `queryErr error` argument.

2021-07-29 14:14 UTC, efritz commented on migrations/frontend/1528395857_codeintel_dependency_repos.up.sql
> +COMMENT ON COLUMN codeintel_dependency_repo_adding_jobs.upload_id IS 'The identifier of the triggering upload record.';
Can 🅱️emove?

2021-07-29 14:16 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/dependency_index.go
> +RETURNING 1
To confirm (pls test) if there's a conflict are there no result rows?

2021-07-29 18:37 UTC, Strum355 commented on enterprise/internal/codeintel/stores/dbstore/dependency_index.go
> +RETURNING 1
Ya thats right

2021-07-29 19:13 UTC, Strum355 commented on migrations/frontend/1528395857_codeintel_dependency_repos.up.sql
> +COMMENT ON COLUMN codeintel_dependency_repo_adding_jobs.upload_id IS 'The identifier of the triggering upload record.';
:b:yes

2021-07-29 22:21 UTC, Strum355 commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +		}
@tsenart `repos.NewStoreMetrics().MustRegister(...)` is called in a [few places](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@54d986146cb9316488e15e26efeb4542749e4070/-/blob/cmd/frontend/graphqlbackend/affiliated_repositories_connection.go?L78:15#tab=references) (here, https://github.com/sourcegraph/sourcegraph/pull/22984/files#diff-f2b2a0cba11155df9816d57716a5897c1d85cef38ff9987ce98f769db7871778R83-R87 and https://github.com/sourcegraph/sourcegraph/pull/22984/files#diff-0382a8372ce0be5f6f76d5e7936b151044fef822c439f66dc93e8cd7908a5207R37-R41 added in this PR alone) as both `github.com/sourcegraph/sourcegraph/cmd/gitserver/server.JVMPackagesSyncer` and `github.com/sourcegraph/sourcegraph/internal/repos.JVMPackagesSource` need a DB handle (as well as more syncers and sources in the future). 

Is it ok for this process to happen in this many locations, is there something better I can do here? Theres a lot of different constructs to build a mental map of when it comes to dealing with repo and external service stores, a lot of them overlapping, so its hard to know whats best to use :sweat_smile:

2021-07-30 09:36 UTC, olafurpg requested changes
I can't wait for this feature to land 😄 It's going to be so much fun when we start auto-indexing transitive dependencies

2021-07-30 09:36 UTC, olafurpg commented on internal/repos/jvm_packages.go
> +		fullDependencyString := parsedModule.SortText() + ":" + dep.Version
You can construct the dependency struct directly
```suggestion
		mavenDependency := MavenDependency{Module: parsedModule, Version: dep.Version}
```

2021-07-30 09:36 UTC, olafurpg commented on internal/repos/jvm_packages.go
> +	dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx)
Would it be possible to customize the query to filter matching modules inside the db? Here's we're loading the entire db into memory to filter on the application side.

2021-07-30 11:11 UTC, olafurpg commented on enterprise/internal/codeintel/stores/dbstore/dependency_index.go
> +func (s *Store) InsertCloneableDependencyRepo(ctx context.Context, dependency semantic.Package) (new bool, err error) {
Followup from call: can we validate before this call that the dependency exists? (has at least a `*-sources.jar`

2021-07-30 11:59 UTC, tsenart reviewed
Mid-review, posting already.

2021-07-30 11:59 UTC, tsenart commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +		}
Yeah, we should definitely refactor this. Can we just use `promauto` package and instantiate the metrics at the package level, rather than Store instance level?

2021-07-30 11:59 UTC, tsenart commented on internal/repos/sources.go
> +func NewSourcer(cf *httpcli.Factory, db *Store, decs ...func(Source) Source) Sourcer {
It feels wrong to add a required dependency to this  constructor that is only used by one Source implementation. I think we should instead use a decorator in call sites where needed, and leverage interface upgrades. This would reduce the changes in this area.

```go
type DBSource interface {
    Source
    SetDB(dbutil.DB)
}

// SetDB implements the DBSource interface.
func (s *JVMPackagesSource) SetDB(db dbutil.DB) { s.db = db }

// WithDB returns a decorator used in NewSourcer that calls SetDB on Sources that
// can be upgraded to it.
func WithDB(db dbutil.DB) func(Source) Source {
    return func(src Source) Source {
        if s, ok := src.(DBSource); ok {
            s.SetDB(db)
            return s
        }
        return src
}

// call sites
s := NewSourcer(cf, WithDB(db))
```

2021-07-30 11:59 UTC, tsenart commented on internal/repos/sources.go
> +func NewSourcer(cf *httpcli.Factory, db *Store, decs ...func(Source) Source) Sourcer {
And I think the dependency here should be `dbutil.DB`, not a `repos.Store`. Your Source should instantiate that internally as needed given the dbutil.DB.

2021-07-30 11:59 UTC, tsenart commented on internal/repos/sources.go
> +func NewSource(svc *types.ExternalService, cf *httpcli.Factory, db *Store) (Source, error) {
With the `DBSource` idea above, this method doesn't need to change. You can call `SetDB` on your source only where needed.

2021-07-30 12:18 UTC, tsenart requested changes
First round finished! Let me know if you want to discuss any of this on a Huddle.

2021-07-30 12:18 UTC, tsenart commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +			src, err := repos.NewSource(svc, cf, store)
Yeah, this file shouldn't have to change, because JVMPackagesSource doesn't implement `repos.AffiliatedRepositorySource`.

2021-07-30 12:18 UTC, tsenart commented on cmd/gitserver/main.go
>  	repoStore := database.Repos(db)
We already instantiated a repoStore here, why do it again? In any case, I think that should be done inside the `JVMPackagesSyncer`, lazily, perhaps protected by a `sync.Once`, and you only pass in a `dbutil.DB`

2021-07-30 12:18 UTC, tsenart commented on cmd/gitserver/server/vcs_syncer_jvm_packages.go
> +	dbDeps, err := s.DBStore.GetJVMDependencyRepos(context.TODO())
```suggestion
	dbDeps, err := s.DBStore.GetJVMDependencyRepos(ctx)
```

2021-07-30 12:18 UTC, tsenart commented on internal/extsvc/versions/sync.go
> +func NewSyncingJob(db *repos.Store) shared.Job {
This file should also not have to change since JVMPackagesSource doesn't implement `repos.VersionSource` which is used below.

2021-07-30 12:18 UTC, tsenart commented on internal/repos/jvm_packages.go
> +	dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx)
How large can this result set be? If very large, we should consider pagination to not clog up memory, otherwise it should be fine.

2021-07-30 12:18 UTC, tsenart commented on internal/repos/jvm_packages.go
> +	dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx)
Agree with @olafurpg here. Something like `GetJVMDependencyRepo(ctx, artifactPath)`

2021-07-30 12:18 UTC, tsenart commented on internal/repos/store.go
> +func (s *Store) GetJVMDependencyRepos(ctx context.Context) ([]JVMDependencyRepo, error) {
OK, I'm a bit confused. Why is this method defined on the `repos.Store`? This is a "code intel store" method for sure.

2021-07-30 14:49 UTC, Strum355 commented on cmd/gitserver/main.go
>  	repoStore := database.Repos(db)
database.Repos returns a *database.RepoStore, while repos.NewStore returns a *repos.Store (bit confusing, this is what I meant by the overlap). The latter itself contains a *database.RepoStore, so we could replace occurrences of `repoStore` here with `store.RepoStore`. How does that sound?

2021-07-30 14:49 UTC, Strum355 commented on cmd/gitserver/main.go
>  	repoStore := database.Repos(db)
Forgot to take the second part of your message into consideration there :sweat_smile: Ill have a look again with that in mind :slightly_smiling_face:

2021-08-02 13:24 UTC, Strum355 commented on internal/repos/store.go
> +SELECT identifier, version FROM codeintel_dependency_repos
Should we rename the column to `module` instead, so it matches the Go struct? https://github.com/sourcegraph/sourcegraph/pull/22984#discussion_r679746473

2021-08-02 13:29 UTC, olafurpg commented on internal/repos/store.go
> +SELECT identifier, version FROM codeintel_dependency_repos
I'll leave the decision to you. I like using `name` in the database column since it's more general can makes sense for non-JVM ecosystems like npm, pypi. For JVM-only structs I think it's nice to use `module`.

2021-08-02 14:32 UTC, Strum355 commented on internal/repos/store.go
> +func (s *Store) GetJVMDependencyRepos(ctx context.Context) ([]JVMDependencyRepo, error) {
@efritz based on this, do you think we have a good existing store to fit this into?

2021-08-02 14:42 UTC, efritz commented on internal/repos/store.go
> +func (s *Store) GetJVMDependencyRepos(ctx context.Context) ([]JVMDependencyRepo, error) {
Not outside of enterprise, but there's store/dbstore that has a few other small repo methods (get name by id)

2021-08-02 22:36 UTC, efritz commented on internal/repos/jvm_packages.go
> +	dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx)
Same advice around the use of the same method below: You shouldn't loop/parse everything into a single slice as you're pulling back the table without any limit for rows, and the table is likely to get very large fast.

You also shouldn't paginate the *rows* by reading every row sequentially in a single request, as you are not CPU bound in the following loops, but bound producing onto a channel that is bound by another database connection. This is a recipe for serious clogs.

Instead, you should do a pagination scheme via changing the signature of `GetJVMDependencyRepos` into something like:

```go
func (s *Store) GetJVMDependencyRepos(ctx context.Context, after *int) ([]..., error)
```

If `after` is supplied, then you add a condition that all ids must be `>= *after` (whatever you choose), and if the table is ordered by that ID (ascending) then you'll never repeat an element. End of result set returns an empty list. Inside of the method you should have a constant limit of some magnitude (500-1000 rows or so?)

2021-08-02 22:57 UTC, Strum355 commented on enterprise/internal/codeintel/stores/dbstore/dependency_index.go
> +func (s *Store) InsertCloneableDependencyRepo(ctx context.Context, dependency semantic.Package) (new bool, err error) {
Is your expected process for this that we fetch all extsvc for the type denoted in `dependency` parameter and then do the existence check e.g. for `semanticdb`, we fetch all JVM Dependencies extsvc, and then do a coursier call for every JVM Dependencies extsvc configuration to see if the package is visible from any of those extsvc?

2021-08-02 23:30 UTC, Strum355 commented on internal/repos/jvm_packages.go
> +		}
@olafurpg continuing on the thought from https://github.com/sourcegraph/sourcegraph/pull/22984/files#r681319542, upon discussing with Eric the idea of moving coursier.Exists out of repo-updater and into the worker flow before adding a repo to the cloneable repos table, it occurred to me that we need to check each jvm dependencies extsvc for which one the dependency is visible from. We then track the extsvc ID in the cloneable repos table and filter on that ID in call to `GetJVMDependencyRepos` in repo-updater, else a jvm dependencies extsvc \<X\> may claim to have visible a dependency that it actually doesnt.

2021-08-03 10:22 UTC, tsenart commented on internal/repos/jvm_packages.go
> +	dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx)
One thought I just had: The semantics of GetRepo should be that we actually get *one* repo from the source, so that we then Sync that repo alone. What's going on there with looking up things from the DB?

2021-08-03 11:27 UTC, olafurpg commented on internal/repos/jvm_packages.go
> +	dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx)
@tsenart a single package repo can contain multiple versions of a dependency where each version is a separate git tag. The database contains the list of dependency+version combinations, which are populated during LSIF upload.

2021-08-03 11:43 UTC, tsenart commented on internal/repos/jvm_packages.go
> +	dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx)
Thanks!

2021-08-03 13:01 UTC, efritz commented on internal/repos/store.go
> +func (s *Store) GetJVMDependencyRepos(ctx context.Context) ([]JVMDependencyRepo, error) {
Update; there's now an OSS codeintel dbstore that can have new methods accessible to OSS code (which is automatically inherited by the enterprise dbstore).

2021-08-04 19:39 UTC, efritz requested changes

2021-08-04 19:39 UTC, efritz commented on internal/codeintel/stores/dbstore/repos.go
> +	}
```suggestion
	conds := make([]*sqlf.Query, 0, 3)
	conds = append(conds, sqlf.Sprintf("scheme = semanticdb"))

	if filter.ArtifactName != "" {
		conds = append(conds, sqlf.Sprintf("name = %s", filter.ArtifactName))
	}
	if filter.After > 0 {
		conds = append(conds, sqlf.Sprintf("id > %d", filter.After))
	}

	limit := sqlf.Sprintf("")
	if filter.Limit != 0 {
		limit = fmt.Sprintf("LIMIT %s", filter.Limit)
	}
```

2021-08-04 19:39 UTC, efritz commented on internal/codeintel/stores/dbstore/repos.go
> +WHERE %s ORDER BY id LIMIT %v
```suggestion
-- source: internal/codeintel/stores/dbstore/repos.goo:GetJVMDependencyRepos
SELECT id, name, version FROM lsif_dependency_repos
WHERE %s ORDER BY id %s
```

2021-08-04 19:39 UTC, efritz commented on internal/codeintel/stores/dbstore/repos.go
> +			&dep.Module,
```suggestion
			&dep.ID,
			&dep.Module,
```

2021-08-05 11:00 UTC, Strum355 commented on internal/codeintel/stores/dbstore/repos.go
> +WHERE %s ORDER BY id LIMIT %v
Should it be the following instead? I made the query generic for other dependency types in the near future 
```suggestion
-- source: internal/codeintel/stores/dbstore/repos.go:GetLSIFDependencyRepos
SELECT id, name, version FROM lsif_dependency_repos
WHERE %s ORDER BY id %s
```

2021-08-05 12:51 UTC, efritz commented on internal/codeintel/stores/dbstore/repos.go
> +WHERE %s ORDER BY id LIMIT %v
Oops did I quote the wrong caller? I'd like to have some source (even if it's an over-approximation). Could we at least put the filename, or extend it with something like `repos.go:{caller1,caller2,caller3}` in the future?

2021-08-05 12:51 UTC, efritz commented on internal/codeintel/stores/dbstore/repos.go
> +	}
My major nit here was around the `interface{}` type value, when sqlf is perfectly suited for composing sql strings safely.

2021-08-05 12:52 UTC, Strum355 commented on internal/codeintel/stores/dbstore/repos.go
> +	}
Yep I have this changed locally :slightly_smiling_face:

2021-08-05 12:57 UTC, Strum355 commented on internal/codeintel/stores/dbstore/repos.go
> +WHERE %s ORDER BY id LIMIT %v
The caller wasnt wrong per se, its that the query is generic to allow also GetNPMDependencyRepos to use it, so there would be multiple callers of that query. Im cool with both of the last sentence :+1:

2021-08-05 20:28 UTC, Strum355 commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +	return upload.Indexer == "lsif-go" || upload.Indexer == "lsif-java", nil
Given this was 7 days ago, does this still hold?

2021-08-05 20:29 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +	return upload.Indexer == "lsif-go" || upload.Indexer == "lsif-java", nil
Nope, go ahead.

2021-08-05 20:31 UTC, Strum355 commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +		extsvcKind, ok := schemeToExternalService[packageReference.Scheme]
This is the only point Im not 100% sure I got right, feel free to resolve if all good

2021-08-05 20:32 UTC, efritz commented on internal/extsvc/jvmpackages/coursier/coursier.go
> +
Oof good catch on this strings.Split gotcha.

2021-08-05 20:33 UTC, efritz commented on internal/codeintel/stores/dbstore/repos.go
> +const getLSIFDependencyReposQuery = `
Can we source this query in a comment? That way we know where to look when we find slow queries.

2021-08-05 20:33 UTC, Strum355 commented on internal/codeintel/stores/dbstore/repos.go
> +const getLSIFDependencyReposQuery = `
Yup, was just doing that, even after you commenting before lol :facepalm:

2021-08-05 20:40 UTC, eseliger commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +	return upload.Indexer == "lsif-go" || upload.Indexer == "lsif-java", nil
Uhh, more repos 🤓

2021-08-05 20:40 UTC, efritz approved these changes

2021-08-05 20:40 UTC, efritz commented on internal/codeintel/stores/dbstore/repos.go
> +		}),
Do you know when log.Lazy occurs? I like to do things in endObservation so that we have an accurate time of the defer. Maybe this is semantically equivalent or close enough - as long as you checked a trace and go reasonable output I'm happy as a 🗜️ .

2021-08-05 20:40 UTC, efritz commented on internal/repos/jvm_packages.go
> +		}
We should really package this somewhere in the future.

2021-08-05 20:40 UTC, efritz commented on internal/repos/jvm_packages.go
> +	log15.Info("ARTIFACT PATH", "path", artifactPath)
Is this actionable pre-merge?

2021-08-05 20:40 UTC, efritz commented on internal/repos/jvm_packages.go
> +		return nil, err
Would be nice to wrap with "DBStore.GetJVMDependencyRepos" here, makes the source traceable.

2021-08-05 20:41 UTC, Strum355 commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +	return upload.Indexer == "lsif-go" || upload.Indexer == "lsif-java", nil
Just a handful.. :angel:

2021-08-05 20:42 UTC, Strum355 commented on internal/repos/jvm_packages.go
> +	log15.Info("ARTIFACT PATH", "path", artifactPath)
I thought I got rid of this :thonk:

2021-08-06 05:39 UTC, unknwon commented on cmd/gitserver/main.go
> +	codeintelDb := codeinteldbstore.NewWithDB(db, &observation.Context{
```suggestion
	codeintelDB := codeinteldbstore.NewWithDB(db, &observation.Context{
```

For naming consistency 😁

2021-08-06 05:39 UTC, unknwon commented on cmd/gitserver/server/vcs_syncer_jvm_packages.go
> +			// we dont call coursier.Exists here
This comment is a result, could you also add the cause/reason?

2021-08-06 05:39 UTC, unknwon commented on cmd/repo-updater/shared/main.go
> +				}
Could we have some comments explaining here why we only do `SetDB` on error-case.

2021-08-06 05:39 UTC, unknwon commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +	// if len == 0, it will return all external services, which we definitely dont want
nit: Could we have properly formatted sentences 😁 
```suggestion
	// If len == 0, it will return all external services, which we definitely don't want.
```

2021-08-06 05:39 UTC, unknwon commented on internal/conf/reposource/jvm_packages.go
> +func (m MavenDependency) LsifJavaDependencies() []string {
Since you're on this, could we have consistent name of the receiver? (i.e. pick `d` or `m`)

2021-08-06 05:39 UTC, unknwon commented on internal/conf/reposource/jvm_packages.go
> +func (d MavenDependency) IsJdk() bool {
Since you're on this, would you mind rename this method to `IsJDK`? It would be more idiomatic Go.

2021-08-06 11:25 UTC, Strum355 commented on cmd/repo-updater/shared/main.go
> +				}
Good catch, this is wrong

2021-08-06 11:34 UTC, Strum355 commented on cmd/gitserver/server/vcs_syncer_jvm_packages.go
> +			// we dont call coursier.Exists here
Yup, forgot to finish this sentence :slightly_smiling_face:

2021-08-06 13:23 UTC, Strum355 commented on internal/codeintel/stores/dbstore/repos.go
> +		}),
Im trying to see results in jaeger but we dont seem to be getting anything, so it feels to me like this is almost a noop without something further being done that I cant find much/any info on. Are we expected to use [ot.StartSpanFromContext](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@nsc/jvm-packages-autoadd/-/blob/internal/trace/ot/ot.go#L146:21) for these trace logs to actually be emitted somewhere?

2021-08-06 14:46 UTC, tsenart commented on internal/codeintel/stores/dbstore/repos.go
> +		}),
FWIW, we're heavily rate limited in Grafana Cloud right now, so your spans may not make it there. Waiting on their horrendous customer support to turn around.

2021-08-06 14:48 UTC, Strum355 commented on internal/codeintel/stores/dbstore/repos.go
> +		}),
Im still only testing locally for now, but thats good to know as well :slightly_smiling_face: Ive changed from 'selective' to 'all' to no avail, I only get other traces but we dont seem to be emitting any traces in most places, even though we're using log.Fields in contexts like this?

2021-08-09 08:47 UTC, olafurpg approved these changes
Minor comments. Otherwise LGTM for the parts that I'm familiar with 👍

2021-08-09 08:47 UTC, olafurpg commented on cmd/gitserver/server/vcs_syncer_jvm_packages.go
> +		if module.MatchesDependencyString(fullDependencyString) {
Nit: we don't need `fullDependencyString` to test if the dependency matches
```suggestion
		if module == parsedModule {
```

2021-08-09 08:47 UTC, olafurpg commented on internal/repos/jvm_packages.go
> +		fullDependencyString := reposource.MavenDependency{
You already have a `MavenDependency`, the `ParseMavenDependency(_.CoursierSyntax())` roundtrip is unnecessary.
```suggestion
		dependency := reposource.MavenDependency{
			MavenModule: parsedModule,
			Version:     dep.Version,
		}
```

2021-08-09 10:24 UTC, unknwon approved these changes

2021-08-09 10:24 UTC, unknwon commented on cmd/repo-updater/shared/main.go
> +				}
Curious what happens when `err != nil`? Will `server.JVMPackagesSource` panic when have no `db` set?

2021-08-09 11:00 UTC, Strum355 commented on cmd/repo-updater/shared/main.go
> +				}
This part should be hit, and repo-updater would die, same way as if github/gitlab wasnt configured correctly :slightly_smiling_face: https://github.com/sourcegraph/sourcegraph/pull/22984/files/d287085eb190f09e4c4efeb6c79bf553a0af1774#diff-dbb41edcf3df6545d4de38c7d844d1a6ce6453d4f2e56ffe61cc3d16071aa63bR230-R232

2021-08-09 12:42 UTC, Strum355 commented
@olafurpg does the latest commit address the semantic version problem? Only the one file needs it, vcs_syncer_jvm_packages.go

2021-08-09 12:44 UTC, olafurpg commented
@Strum355 Yes, although I think it would be nice to add a helper method to construct a `MavenDependency` from `module MavenModule, version string` instead of parsing the semantic version at the call site.

2021-08-17 20:27 UTC, efritz commented on enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go
> +			if err := h.indexEnqueuer.QueueIndexesForPackage(ctx, pkg); err != nil {
For the `shouldIndexDependencies` change to be useful, you also need to update this:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/codeintel/autoindex/enqueuer/infer.go?L12

and add a way to infer the repo/revision from the package

2021-08-17 20:28 UTC, efritz commented on internal/repos/jvm_packages.go
> +		dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx, dbstore.GetJVMDependencyReposOpts{
So it looks this table will never shrink and you'll always be re-checking the things that you've done in the lsat round.

Is this expected behavior? (I know it's an easy way to catch things like a dropped row that will be re-created periodically, but wanted to determine if the re-computation is an issue or not and if we do this elsewhere).

2021-08-17 20:29 UTC, efritz approved these changes

2021-08-17 20:37 UTC, Strum355 commented on internal/repos/jvm_packages.go
> +		dbDeps, err := s.dbStore.GetJVMDependencyRepos(ctx, dbstore.GetJVMDependencyReposOpts{
This is actually required, from my understanding. Repo-updater will take [diffs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@nsc/jvm-packages-autoadd/-/blob/internal/repos/syncer.go#L460:23) of the new state and the existing state and remove any repositories that were in the existing state but not in the new state, and add any missing ones.

2021-08-17 21:06 UTC, efritz approved these changes
LGTM

2021-08-24 14:48 UTC, merged