Improve quickstart dependencies install script
sourcegraph/sourcegraph pull request #23550
Opened 2021-08-04 10:48 UTC by grzesiek

### Description

This PR adds a few minor changes to to quick start dependencies installation script:

1. It adds convenience commands to move `golang-migrate` and `comby` into `/usr/local/bin`
2. It fixes `cp` commands used to move `watchman` binary and libraries into `/usr/local/{bin, lib}` that were broken.
3. It removes the command that creates `/usr/local/{bin,lib}` as these directories should be always available on a fresh Ubuntu installation.

2021-08-04 11:03 UTC, mrnugget requested changes
Thanks! Left a comment because I think the comments in two places are now outdated.

2021-08-04 11:03 UTC, mrnugget commented on doc/dev/getting-started/quickstart_1_install_dependencies.md
>      # install golang-migrate (you must rename the extracted binary to `golang-migrate` and move the binary into your $PATH)
This comment is now outdated. I suggest moving what's in the parentheses down above the `mv` command you added and changing it do something like this:

```
# The extracted binary must be in your $PATH. Here's how you'd move it to `/usr/local/bin` (which is most likely in your `$PATH`):
```

2021-08-04 12:55 UTC, mrnugget approved these changes
Fantastic! Thanks

2021-08-05 08:25 UTC, grzesiek commented
> Fantastic! Thanks

@mrnugget Is there anything I need to do to get this merged?

2021-08-05 08:49 UTC, mrnugget commented
> @mrnugget Is there anything I need to do to get this merged?

I'm investigating why CI doesn't run. Other than that: nothing to do from your side.

2021-08-05 09:09 UTC, mrnugget commented
This page in the handbook describes it: https://about.sourcegraph.com/handbook/engineering/external_contributions

Kicked off the build. When that's green, I can merge it.

2021-08-05 09:11 UTC, merged