Add detail to PostgreSQL doc
sourcegraph/sourcegraph pull request #23716
Opened 2021-08-09 10:35 UTC by macraig

Related to https://github.com/sourcegraph/sourcegraph/issues/16473

2021-08-09 13:59 UTC, efritz commented on doc/admin/external_services/postgres.md
> +If you choose to set up your own PostgreSQL server, please note **we do not recommend using the same PostgreSQL instance for different databases**. Although it is technically possible to point both d
It's technically possible _now_ but we also make no guarantee that some minor update may cause table names to conflict if they're pointed at the same instance.

It's a **requirement** for them to be different _databases_ and **strongly recommended** for them to be difference servers and/or hosts.

2021-08-09 13:59 UTC, efritz requested changes
See inline comment.

2021-08-09 14:04 UTC, macraig commented on doc/admin/external_services/postgres.md
> +If you choose to set up your own PostgreSQL server, please note **we do not recommend using the same PostgreSQL instance for different databases**. Although it is technically possible to point both d
```suggestion
If you choose to set up your own PostgreSQL server, please note **we strongly recommended for each database to be set up in different servers and/or hosts**. We suggest either:
```

2021-08-09 16:07 UTC, macraig commented on doc/admin/external_services/postgres.md
> +If you choose to set up your own PostgreSQL server, please note **we do not recommend using the same PostgreSQL instance for different databases**. Although it is technically possible to point both d
@efritz is that clearer? Feel free to edit

2021-08-10 18:32 UTC, efritz approved these changes

2021-08-10 18:43 UTC, merged