authz/perforce: support wildcard permissions
sourcegraph/sourcegraph pull request #23755
Opened 2021-08-10 14:34 UTC by bobheadxi

Closes https://docs.google.com/document/d/18cCjhZeSguEI-pdX7AJb8vwUoexZ3SVWX8ebX8Excu0/edit#

2021-08-10 14:40 UTC, bobheadxi commented on internal/authz/perforce/perforce.go
> +		depotPrefix = strings.ReplaceAll(depotPrefix, "...", "%")
Thoughts on performing the transformation here, vs [`listSQL`](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40d9f5113+file:%5Einternal/database/repos%5C.go+listSQL+type:symbol+&patternType=literal):

- doing the transformation later leaks the abstraction (database needs knowledge of perforce wildcards)
- doing the transformation here means previously parsed permissions tables will not have wildcards support until they get sync'd again (maybe?)
- doing the transformation here will break if we stop using `LIKE`

2021-08-10 14:54 UTC, bobheadxi commented on internal/authz/perforce/perforce.go
> +		depotPrefix = strings.ReplaceAll(depotPrefix, "...", "%")
Also due to this, considering renaming `ExternalRepoXXXPrefixes` and friends to `ExternalRepoXXXPartials`

2021-08-11 06:28 UTC, unknwon commented on internal/authz/perforce/perforce.go
> +		depotPrefix = strings.ReplaceAll(depotPrefix, "...", "%")
> Also due to this, considering renaming `ExternalRepoXXXPrefixes` and friends to `ExternalRepoXXXPartials` or `ExternalRepoXXXLike`, though I'm not sure if this change will be require a database migration

Rename to `ExternalRepoXXXContains` sounds appropriate, also with this change, we need to add more tests covering cases like `... LIKE "//Sourcegraph/%/Handbook/%"`.

Besides, I'm wondering what's differences between the two:

```
write group localization_app_w * //app/.../.../core/i18n/test/...
write group localization_app_w * //app/.../core/sfdc/config/labels/...
```

Does one occurrence of `.../` only represents one directory level?

Same question for the following:

```
write group localization_app_w * //app/*/*/core/i18n/test/...
write group localization_app_w * //app/*/core/sfdc/config/labels/...
```

2021-08-11 06:41 UTC, bobheadxi commented on internal/authz/perforce/perforce.go
> +		depotPrefix = strings.ReplaceAll(depotPrefix, "...", "%")
Interesting, I can't find an example of the multiple wildcards on the official docs. I'll investigate. The current behaviour with `%` is to match everything. i.e. `//app/%/core/` will match all of the following (similar for `*`):

```
//app/.../.../.../core/
//app/.../.../core/
//app/.../core/
```

If Perforce does enforce number of directories there this will get pretty gnarly

2021-08-11 06:56 UTC, bobheadxi commented on internal/authz/perforce/perforce.go
> +		depotPrefix = strings.ReplaceAll(depotPrefix, "...", "%")
Looks like not a happy situation - the above is correct for `...`, but turns out `*` behaves quite differently: https://www.perforce.com/manuals/cmdref/Content/CmdRef/filespecs.html#filespecs.synopsis.wildcards

![image](https://user-images.githubusercontent.com/23356519/128983281-e18affa5-fba0-41ed-96e7-88152e0f740c.png)

That third syntax, I'm going to scope out I think. I'll have to do some thinking about this, I'm not sure excluding things is possible with the `%` syntax.

2021-08-11 07:13 UTC, unknwon commented on internal/authz/perforce/perforce.go
> +		depotPrefix = strings.ReplaceAll(depotPrefix, "...", "%")
note: if `LIKE` does not work, maybe try regex search with `*`.

2021-08-11 09:36 UTC, bobheadxi commented on internal/authz/perforce/perforce.go
> +		depotPrefix = strings.ReplaceAll(depotPrefix, "...", "%")
@unknwon ce46fc411f8d2988710a88f7cbe816224c640d1d should implement `*` correctly!

2021-08-13 06:32 UTC, unknwon requested changes
Request changes for the doc change, but I'll focus on review the implementation first. I'd suggest separate out code change with doc change to land the PR faster.

2021-08-13 06:32 UTC, unknwon commented on CHANGELOG.md
> +- Basic support for Perforce permission table path wildcards are now supported. [#23755](https://github.com/sourcegraph/sourcegraph/pull/23755)
```suggestion
- Basic support for Perforce permission table path wildcards. [#23755](https://github.com/sourcegraph/sourcegraph/pull/23755)
```

2021-08-13 06:46 UTC, unknwon requested changes
Nice work!

In addition to existing tests, we also want to make sure what happens when we encounter permission rule like `review user alice * //Sourcegraph/.../.../Handbook/...` (derived from sample)

2021-08-13 06:46 UTC, unknwon commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			return errors.Wrap(err, "list external repositories by depot matching")
```suggestion
			return errors.Wrap(err, "list external repositories by contains matching")
```

There is no concept of depot at this layer.

2021-08-13 06:46 UTC, unknwon commented on internal/authz/perforce/perforce.go
> +		depotContains = strings.TrimRight(depotContains, ".") // drop trailing, treat everything as a prefix
This block of docstring putting right before L232 seems causing confusion, because L232 is trimming ending '...'. Since we have changed "prefix" to "contains", why can't we just replace ending '...' with `%` (i.e. no need to trim)?

2021-08-13 06:46 UTC, unknwon commented on internal/authz/perforce/perforce_test.go
> +open user alice * -//Sourcegraph/*/Handbook/...                      ## sub-match of wildcard A include
What is the capitalized "A"?

2021-08-13 06:46 UTC, unknwon commented on internal/database/dbtest/dbtest.go
> +
👍

2021-08-13 06:46 UTC, unknwon commented on internal/database/dbtest/dbtest.go
> +		config, err = url.Parse("postgres://sourcegraph:sourcegraph@127.0.0.1:5432/sg?sslmode=disable&timezone=UTC")
Unrelated change?

2021-08-13 06:46 UTC, unknwon commented on internal/database/repos.go
> +			er = append(er, sqlf.Sprintf("(external_id SIMILAR TO %s AND external_service_type = %s AND external_service_id = %s)", spec.ID+"%", spec.ServiceType, spec.ServiceID))
I think it no longer makes sense to always append a "%" here, there is nothing indicating this is a prefix matching anymore.

2021-08-13 06:55 UTC, bobheadxi commented on internal/database/repos.go
> +			er = append(er, sqlf.Sprintf("(external_id SIMILAR TO %s AND external_service_type = %s AND external_service_id = %s)", spec.ID+"%", spec.ServiceType, spec.ServiceID))
I think `Contains` still implies this a partial, though I suppose that doesn't strictly mean a prefix. Should I move the addition of `%` into the perforce syncer?

2021-08-13 06:56 UTC, bobheadxi commented on internal/database/dbtest/dbtest.go
> +		config, err = url.Parse("postgres://sourcegraph:sourcegraph@127.0.0.1:5432/sg?sslmode=disable&timezone=UTC")
Removed in 4e962a8d54ada7b7d7dd029153bee66feb36db35

2021-08-13 06:57 UTC, bobheadxi commented on internal/authz/perforce/perforce_test.go
> +open user alice * -//Sourcegraph/*/Handbook/...                      ## sub-match of wildcard A include
A little further up:

```
open user alice * //Sourcegraph/.../Handbook/...  ## wildcard A
```

2021-08-13 06:57 UTC, bobheadxi commented
@unknwon docs have been moved to https://github.com/sourcegraph/sourcegraph/pull/23880

2021-08-13 06:59 UTC, bobheadxi commented on internal/authz/perforce/perforce.go
> +		depotContains = strings.TrimRight(depotContains, ".") // drop trailing, treat everything as a prefix
This is a relic of https://github.com/sourcegraph/sourcegraph/pull/23755#discussion_r688281607 , but I think it makes sense to move the `%` suffix here if it exists

2021-08-13 07:16 UTC, bobheadxi commented
>  we also want to make sure what happens when we encounter permission rule like review user alice * //Sourcegraph/.../.../Handbook/... (derived from sample)

Added a test in https://github.com/sourcegraph/sourcegraph/pull/23755/commits/b05a23eeb6d6bf83a2822f5fddbffcc26834764b. This should be the correct behaviour: `...` should match any arbitrary number of parent directories, and the `/` in the middle indicate at least one directory level should be matched

2021-08-13 07:16 UTC, bobheadxi commented on internal/database/repos.go
> +			er = append(er, sqlf.Sprintf("(external_id SIMILAR TO %s AND external_service_type = %s AND external_service_id = %s)", spec.ID+"%", spec.ServiceType, spec.ServiceID))
pulled this out in https://github.com/sourcegraph/sourcegraph/pull/23755/commits/c4866a139ca6a9debad519e157fe601cdfda75fa

2021-08-13 07:16 UTC, bobheadxi commented on internal/authz/perforce/perforce.go
> +		depotContains = strings.TrimRight(depotContains, ".") // drop trailing, treat everything as a prefix
We still need to trim the end specifically to check for prefixes, and then add it back later - see https://github.com/sourcegraph/sourcegraph/pull/23755/commits/c4866a139ca6a9debad519e157fe601cdfda75fa

2021-08-13 08:14 UTC, unknwon reviewed
I think we're pretty close, just one last comment

2021-08-13 08:14 UTC, unknwon commented on internal/authz/perforce/perforce.go
> +	// Treat all paths as a prefix.
nit
```suggestion
	// Treat all paths as prefixes.
```

2021-08-13 08:14 UTC, unknwon commented on internal/authz/perforce/perforce_test.go
> +open user alice * -//Sourcegraph/*/Handbook/...                      ## sub-match of wildcard A include
Ah, I'm blind.

2021-08-13 08:14 UTC, unknwon commented on internal/database/repos_db_test.go
> +func filterRepoNames(names []types.RepoName, contains, excludes string) []types.RepoName {
Generally I'd prefer this type of helper, but I find using it here no longer makes what we want explicitly in tests (easy to miss due to over-match a record).

2021-08-13 08:16 UTC, bobheadxi commented on internal/database/repos_db_test.go
> +func filterRepoNames(names []types.RepoName, contains, excludes string) []types.RepoName {
I'd argue it makes it clearer - since we are matching on types of result, tests using `filterRepoNames` can now more accurately reflect what we are looking for in the results, e.g. stuff including/excluding certain substrings. Previously, would have to go back and forth between test expect and the predefined list of repos (and you'd have to count the indexes too 😅 )

2021-08-13 08:28 UTC, unknwon commented on internal/database/repos_db_test.go
> +func filterRepoNames(names []types.RepoName, contains, excludes string) []types.RepoName {
By writing `filterRepoNames`, we're introducing risks to have bugs in this helper as well.

For example, how do we know we have an implementation bug for the rule `//1*/Backend/...` with `want: filterRepoNames(repoNamesFromRepos(repos), "/Backend", "")`, where we didn't respect the path must start with `//1`?

2021-08-13 08:29 UTC, unknwon commented on internal/database/repos_db_test.go
> +func filterRepoNames(names []types.RepoName, contains, excludes string) []types.RepoName {
>you'd have to count the indexes too

I agree this is ugly, but at least explicit.

2021-08-13 08:40 UTC, bobheadxi commented on internal/database/repos_db_test.go
> +func filterRepoNames(names []types.RepoName, contains, excludes string) []types.RepoName {
🤔 In that case, I might make each repo a variable and require tests to list the exact repos they want explicitly

2021-08-13 08:57 UTC, bobheadxi commented on internal/database/repos_db_test.go
> +func filterRepoNames(names []types.RepoName, contains, excludes string) []types.RepoName {
476aadce2f421423873ff4e247b44d0511150751

2021-08-13 09:31 UTC, unknwon approved these changes
![](https://media2.giphy.com/media/QMoXJjGPsmJ6Pdc596/giphy.gif)

2021-08-13 09:49 UTC, merged