dotcom: Improve copy & styling of 3rd step in welcome flow
sourcegraph/sourcegraph pull request #23905
Opened 2021-08-13 14:58 UTC by kopancek

Changes of text copy & styling based on https://sourcegraph.atlassian.net/browse/COREAPP-205

Original:
<img width="627" alt="Screenshot 2021-08-13 at 16 57 58" src="https://user-images.githubusercontent.com/9974711/129376599-6ca9b85c-80c5-400e-be98-38c6953f68ab.png">

New:
<img width="644" alt="Screenshot 2021-08-13 at 16 57 38" src="https://user-images.githubusercontent.com/9974711/129376616-70a92667-9a54-4f67-9fbd-2b81c669325d.png">

2021-08-13 15:15 UTC, artemruts approved these changes
✨

2021-08-13 16:01 UTC, quinnkeast commented on client/web/src/auth/welcome/StartSearching.tsx
> +            <h4>Fetching repositories...</h4>
```suggestion
            <h3>Fetching repositories...</h3>
```

Sorry, we got swapped somewhere!

2021-08-13 16:01 UTC, quinnkeast commented on client/web/src/auth/welcome/StartSearching.tsx
> +                        <h3 className="m-0">Activity log</h3>
```suggestion
                        <h4 className="m-0">Activity log</h4>
```

2021-08-13 16:01 UTC, quinnkeast commented on client/web/src/auth/welcome/StartSearching.tsx
> +                        <h3 className="m-0">Activity log</h3>
Second part of the swap.

2021-08-13 16:02 UTC, quinnkeast requested changes
Looks good! Only change is that the `h3` → `h4` swap is in the wrong spot. I've added comments to fix.

2021-08-16 12:43 UTC, unknwon approved these changes

2021-08-16 12:44 UTC, quinnkeast approved these changes

2021-08-16 17:00 UTC, closed without merging