sketch: authz/github: sync permissions from team/org repo caches
sourcegraph/sourcegraph pull request #23978
Opened 2021-08-16 13:04 UTC by bobheadxi

Sketching out some potential ideas outlined in [Scaling repository permissions syncing](https://docs.google.com/document/d/17iD_Y1tG_lWFnQOI9xQ0p0VtcYVOOUzoeU83l7Uq20I/edit#)

2021-08-17 14:41 UTC, bobheadxi commented on internal/authz/github/github.go
> +// This may return a partial result if an error is encountered, e.g. via rate limits.
What happens if we do encounter rate limits? There doesn't seem to be anything right now for "continunuing" an in-progress sync

2021-08-18 15:12 UTC, bobheadxi commented on internal/authz/github/cache.go
> +	var cacheTTL time.Duration = 90 * time.Minute
TODO: configurize

2021-08-18 15:14 UTC, bobheadxi commented on internal/authz/github/github.go
>  func (p *Provider) FetchUserPermsByToken(ctx context.Context, token string) (*authz.ExternalUserPermissions, error) {
TODO: add ignoreCache

2021-08-18 15:19 UTC, bobheadxi commented on internal/authz/github/github.go
> +			if org.DefaultRepositoryPermission != "" && org.DefaultRepositoryPermission != "none" {
TODO: maybe do a positive check?

2021-08-18 15:29 UTC, bobheadxi commented
Sync'd with Joe today and confirmed this is a good direction - I'll be diving into this more over the next few days.

2021-08-18 15:40 UTC, bobheadxi commented on internal/authz/github/github.go
>  func (p *Provider) FetchUserPermsByToken(ctx context.Context, token string) (*authz.ExternalUserPermissions, error) {
tl;dr no paging at Provider level, hopefully nobody has access to more than 5000 * 100 = 500000 repositories via permissions

2021-08-18 15:40 UTC, bobheadxi commented on internal/authz/github/github.go
> +	groupsCache *groupsCache
Answer - yes

2021-08-19 06:40 UTC, bobheadxi commented on schema/github.schema.json
> +      }
Should I add a feature flag here as well?

2021-08-19 08:44 UTC, bobheadxi commented
Unsure about these fixtures mismatches: https://buildkite.com/sourcegraph/sourcegraph/builds/105691#0d70f6e8-0c08-4788-8f0e-39241800e043/432-433

TODO try to just update these, currently missing credentials

2021-08-19 08:45 UTC, bobheadxi commented on schema/github.schema.json
> +      }
https://github.com/sourcegraph/sourcegraph/pull/23978/commits/8e3527926fb55300eb1f722410d135b66301b51e

2021-08-20 01:04 UTC, daxmc99 reviewed
Still reviewing but this looks great so far!

2021-08-20 01:04 UTC, daxmc99 commented on internal/authz/github/cache.go
> +type cachedGroup struct {
Its a bit hard to tell there are two separate cache structs here `cachedGroup` & `groupsCache` 

Could you add a comment or maybe rename them?

2021-08-20 13:53 UTC, unknwon commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		extIDs, err := provider.FetchUserPerms(ctx, acct, &authz.FetchPermOptions{})
What is the rationale to have options struct be passed as a pointer? Seems unusual, unless we want to have functions to do in-place update.

2021-08-20 13:53 UTC, unknwon commented on internal/authz/github/cache.go
> +type cachedGroup struct {
Agree, what about `cachedGroup` and `cachedGroups`, looks more aligned.

2021-08-20 13:53 UTC, unknwon commented on internal/authz/github/cache.go
> +		cache: rcache.NewWithTTL(fmt.Sprintf("gh_groups_perms:%s:%s", codeHost.ServiceID, urn), int(ttl/time.Second)),
nit:
```suggestion
		cache: rcache.NewWithTTL(fmt.Sprintf("gh_groups_perms:%s:%s", codeHost.ServiceID, urn), int(ttl.Seconds())),
```

2021-08-20 13:53 UTC, unknwon commented on internal/authz/github/cache.go
> +	Repositories []extsvc.RepoID
From what I understand, we have the list of repo IDs is the value, and key is basically a string. My question is that what's the reason of having a dedicated `cachedGroup`?

2021-08-20 13:53 UTC, unknwon commented on internal/authz/github/github.go
> +	GitHubURL    *url.URL
We're already under the github package, having extra `GitHub` prefix in field names feels redundant 🤔

2021-08-20 13:53 UTC, unknwon commented on internal/authz/github/github.go
> +	seenRepos := make(map[extsvc.RepoID]bool, repoSetSize)
```suggestion
	seenRepos := make(map[extsvc.RepoID]struct{}, repoSetSize)
```

https://dave.cheney.net/2014/03/25/the-empty-struct

2021-08-20 13:53 UTC, unknwon commented on internal/authz/github/github.go
> +	// Now, we look for groups this user belongs to that give access to additional
Could we move rest of this method body into a separate helper? Because this method now gets fairly large.

2021-08-20 13:53 UTC, unknwon commented on internal/authz/iface.go
> +type FetchPermOptions struct {
```suggestion
type FetchPermsOptions struct {
```

2021-08-20 13:53 UTC, unknwon commented on internal/extsvc/github/common.go
> +type OrgDetails struct {
What's preventing us from put new field just into existing `Org` struct?

2021-08-20 13:53 UTC, unknwon commented on internal/extsvc/github/v3.go
> +func (c *V3Client) GetAuthenticatedUserTeams(ctx context.Context, page int) (
Please add docstring.

2021-08-20 13:53 UTC, unknwon commented on internal/extsvc/github/v3.go
> +func (c *V3Client) ListAffiliatedRepositories(ctx context.Context, visibility Visibility, page int, affiliations ...Affiliation) (
Please update docstring accordingly.

2021-08-20 13:53 UTC, unknwon commented on internal/extsvc/github/v3.go
> +	}
```suggestion
	if len(affiliations) > 0 {
		affilationsStrings := make([]string, 0, len(affiliations))
		for _, affiliation := range affiliations {
			affilationsStrings = append(affilationsStrings, string(affiliation))
		}
		path = fmt.Sprintf("%s&affiliation=%s", path, strings.Join(affilationsStrings, ","))
	}
```

2021-08-23 12:27 UTC, bobheadxi commented on internal/authz/iface.go
> +	InvalidateCaches bool
Ah yes, the intention for this option is to be able to leverage it in webhook handlers - I'll add at least one, I think I saw something for handling team events

I think an admin trigger is out of scope - the cache can be disabled entirely (with a negative value) if something is busted, cc @unknwon

2021-08-23 12:33 UTC, bobheadxi commented on internal/authz/github/github.go
> -	var cacheTTL time.Duration = 5 * time.Minute
This cache didn't exist before, so the increase is from 0 to I think 72 hours (`github.newAuthzProvider`) which @unknwon recommended. I think this feels high too, but I suppose it makes sense - do teams really change that often?

Some other points:

- Repositories sync don't leverage these caches (yet) - cc @unknwon for thoughts on this too
- I think appropriate force-updates on the right webhook handlers (https://github.com/sourcegraph/sourcegraph/pull/23978#discussion_r693925799) will keep these caches from being unpleasantly out of date
- The TTL is configurable in the provider config

2021-08-23 12:34 UTC, bobheadxi commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		extIDs, err := provider.FetchUserPerms(ctx, acct, &authz.FetchPermOptions{})
I've seen pointer options be used in APIs where the options are optional, which is why they are optional here

2021-08-23 12:38 UTC, bobheadxi commented on internal/authz/github/github.go
> +	GitHubURL    *url.URL
the `GitHubURL` should have the prefix, I don't think it's entirely clear what it's meant to be. `GitHubClient` is just for alignment with that since both are only used in setting up a client for this provider. I'd prefer if only one of these two existed to be honest, but didn't want to touch too much

2021-08-23 12:45 UTC, bobheadxi commented on internal/authz/github/cache.go
> +}
The caches must be separate:

- so that keys do not collide
- there is no concept of organizations/teams consistent across all providers, and even analogous concepts mean different things (e.g. groups (teams) are not subsets of projects (orgs) in Bitbucket), and how caches should be leveraged might be different based on API characteristics of each platform as well. Given the inconsistencies, I think using a shared cache would be confusing

Note that each `rcache.Cache` instance (from my understanding) only wraps inserts/queries in a prefix namespace in Redis for convenience, and is pretty low-overhead.

2021-08-23 12:49 UTC, bobheadxi commented on internal/authz/github/cache.go
> +	Repositories []extsvc.RepoID
It is useful to distinguish between an org and a team, since they are fetched/updated differently. We could do string manipulations to get this information from the key, or have a `.IsOrg` and then do string manipulation to get the information, but eventually a struct will be needed to ergonomically represent that, so I thought it clearer to just use a consistent struct everywehre.

It also means that we can expand the struct with additional metadata about cached groups if useful for debugging, since as we talked about this entire caching feature might cause a lot of pain when debugging 😁

2021-08-23 12:51 UTC, bobheadxi commented on internal/extsvc/github/common.go
> +type OrgDetails struct {
Because the `Org` struct represents information you can get in any of the REST APIs that gets organization information from a subfield of a response, but these additional fields can only be fetched from this specific get-an-organization API. Thought it would be misleading to have those in the `Org` struct

2021-08-23 13:05 UTC, bobheadxi commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		extIDs, err := provider.FetchUserPerms(ctx, acct, &authz.FetchPermOptions{})
That said, thought about it and decided to make these value structs instead :)

2021-08-23 13:09 UTC, bobheadxi commented on internal/authz/iface.go
> +type FetchPermOptions struct {
https://github.com/sourcegraph/sourcegraph/pull/23978/commits/ad42c11ecae909c8b3a251ddd3fb6a03b6bcfe60

2021-08-23 13:17 UTC, bobheadxi commented on internal/extsvc/github/v3.go
> +func (c *V3Client) GetAuthenticatedUserTeams(ctx context.Context, page int) (
e30cea098ecaddf385b0f31d586e0267b15ac4d3

2021-08-23 13:17 UTC, bobheadxi commented on internal/extsvc/github/v3.go
> +func (c *V3Client) ListAffiliatedRepositories(ctx context.Context, visibility Visibility, page int, affiliations ...Affiliation) (
e30cea098ecaddf385b0f31d586e0267b15ac4d3

2021-08-23 14:16 UTC, bobheadxi commented on internal/authz/github/github.go
> +	// Now, we look for groups this user belongs to that give access to additional
d78fde76920e2bf4a1947e363cef6d212e7c968b

2021-08-23 14:19 UTC, bobheadxi commented on internal/authz/github/cache.go
> +type cachedGroup struct {
https://github.com/sourcegraph/sourcegraph/pull/23978/commits/8d6eea4253aee8f4fffec89b896818868566da40

2021-08-23 18:38 UTC, tsenart commented on internal/authz/github/cache.go
> +package github
What's the rationale for storing group permissions in Redis, while all other permissions are in Postgres?

2021-08-23 18:53 UTC, bobheadxi commented on internal/authz/github/cache.go
> +package github
Permissions tracked in Postgres are permanent permissions used by Sourcegraph, and are based on provider-agnostic abstractions. No concept of "teams" and "organizations" as far as repo permissions goes exists in Sourcegraph, and the concepts are not quite the same across providers as well (e.g. GitHub vs Bitbucket), so it doesn't make sense to share groups caches across providers which makes it unclear where this would live within the database

Also the intent here is to only cache groups as an intermediary that is then used to build out lists of per-user permissions that are then persisted to databases, with the intention of reducing API usage (see PR description), so Redis seems like a good home for that. @unknwon and I talked about having the caches live in database instead, but for now agreed that there isn't sufficient justification for each provider to get its own tables

2021-08-23 18:58 UTC, tsenart commented on internal/authz/github/cache.go
> +package github
Thanks, makes sense!

2021-08-23 19:14 UTC, bobheadxi commented on internal/extsvc/github/common.go
>  }
@sourcegraph/batchers Is this struct (seemingly only used by `ReviewRequestRemovedEvent`) currently tracked in the database? Digging around it seems not to be, and I've updated fixtures accordingly, and I'm hoping to be able to reuse this struct for the v3 API

2021-08-23 19:18 UTC, bobheadxi commented on internal/extsvc/github/testdata/golden/GetAuthenticatedUserOrgs
> +   "login": "sourcegraph-vcr-repos"
It's not clear what user was used to generate this testdata, but I've added `vcr_test.go` to this package with a recommendation to use the `sourcegraph-vcr` user

2021-08-24 09:42 UTC, unknwon commented on internal/authz/iface.go
> +	InvalidateCaches bool
> I think an admin trigger is out of scope - the cache can be disabled entirely (with a negative value) if something is busted, cc @unknwon

I think the @daxmc99 is saying about individual force sync, disabling the cache entirely could cause sudden huge load to the code host and not super helpful to debug individual's permissions syncing problem.

2021-08-24 09:51 UTC, unknwon commented on internal/authz/github/github.go
> -	var cacheTTL time.Duration = 5 * time.Minute
> This cache didn't exist before, so the increase is from 0 to I think 72 hours (`github.newAuthzProvider`) which @unknwon recommended. I think this feels high too, but I suppose it makes sense - do teams really change that often?

I think we need to do some simple math here (have an assumption of the scale, and how many API calls we would save by having the additional cache layer, and does the saving worth the development we're doing). Also if by the time we re-use the cache it is often expired, seems defeating the point of caching it.

> Repositories sync don't leverage these caches (yet) - cc @unknwon for thoughts on this too

The immediate thought would be, is the way we store the cache that's friendly to repo-centric syncing? Usual situation is that the number of repos is several magnitude more than the number of users, which means we would have way more repo-centric syncs than user-centric syncs (ie. repo-centric syncing would be benefited from caching more).

2021-08-24 09:55 UTC, unknwon commented on internal/authz/github/cache.go
> +	Repositories []extsvc.RepoID
SGTM! I was just challenging to reduce one layer of abstraction 😁

2021-08-24 09:56 UTC, unknwon commented on internal/extsvc/github/common.go
> +type OrgDetails struct {
> Because the `Org` struct represents information you can get in any of the REST APIs that gets organization information from a subfield of a response, but these additional fields can only be fetched from this specific get-an-organization API. Thought it would be misleading to have those in the `Org` struct

Make sense! Could you also put these into the code comments?

2021-08-24 10:20 UTC, mrnugget commented on internal/extsvc/github/common.go
>  }
Yeah, it's persisted to the database but adding new fields is fine.

2021-08-24 12:57 UTC, bobheadxi commented on internal/extsvc/github/common.go
>  }
Would the added JSON annotations affect that?

2021-08-24 13:09 UTC, bobheadxi commented on internal/extsvc/github/common.go
>  }
Nevermind - I decided to just add a `restTeam` struct with the JSON annotations, this is too complicated 😅

2021-08-24 14:05 UTC, bobheadxi commented on internal/authz/github/github.go
> -	var cacheTTL time.Duration = 5 * time.Minute
> which means we would have way more repo-centric syncs than user-centric syncs (ie. repo-centric syncing would be benefited from caching more than user-centric syncing).

I'd like to do this in a follow-up PR right afte this if that's okay, I would like to land this PR soon so that I can organize with @ggilmore to start working on a similar approach with bitbucket

2021-08-24 14:17 UTC, bobheadxi commented on internal/authz/iface.go
> +	InvalidateCaches bool
4994a34b89c60349204fd09a5237f611f07318c8 adds an option to the API endpoint to invalidate caches encountered!

2021-08-24 14:21 UTC, unknwon commented on internal/authz/github/github.go
> -	var cacheTTL time.Duration = 5 * time.Minute
> I'd like to do this in a follow-up PR right after this if that's okay

In that case, I'd suggest adding a version annotation to the cache key, so in case we decide to change the cached format later, our code don't get confused with previous versions of cache. WDYT?

2021-08-24 14:24 UTC, bobheadxi commented on internal/extsvc/github/common.go
> +type OrgDetails struct {
a7a78435db90d2d2507c2bf7934b47e4f9441ceb

2021-08-24 15:12 UTC, unknwon requested changes
Still reviewing, submit my progress so far 😁 Thanks for all the followups BTW, appreciated ❤️ 

Request for changes for one critical comment about saving incomplete results to cache.

2021-08-24 15:12 UTC, unknwon commented on doc/admin/repo/permissions.md
> +permissions sync due to reduced instances of being rate limited by the code host.
```suggestion
For GitHub providers, Sourcegraph leverages caching of team and organization permissions to reduce the number of API calls used when syncing permissions. This can significantly reduce the amount of time it takes to perform a full permissions sync due to reduced instances of being rate limited by the code host.
```

2021-08-24 15:12 UTC, unknwon commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +	if args.Options != nil && args.Options.InvalidateCaches != nil {
`args.Options.InvalidateCaches` can still be `false` while `args.Options.InvalidateCaches != nil`, that is a legitimate value.
```suggestion
	if args.Options != nil && args.Options.InvalidateCaches != nil && args.Options.InvalidateCaches {
```

2021-08-24 15:12 UTC, unknwon commented on internal/authz/github/cache.go
> +// setGroup stores the given group in the cache
```suggestion
// setGroup stores the given group in the cache.
```

2021-08-24 15:12 UTC, unknwon commented on internal/authz/github/github.go
> +	groupsCache *cachedGroups
nit: I think the better way is to have our cache abstraction to be an interface and put a noop cache implementation when disabled. 

_this PR is already huge, if we're agree on this, let's do it in a followup PR_

2021-08-24 15:12 UTC, unknwon commented on internal/authz/github/github.go
> +				p.groupsCache.setGroup(group)
Hmm, if we boiled out when not done this time in case of error, why is it OK to use it (as the cache) the next time?

2021-08-24 15:13 UTC, mrnugget commented on internal/extsvc/github/common.go
>  }
Alright!

2021-08-24 15:25 UTC, bobheadxi commented on internal/authz/github/github.go
> +	groupsCache *cachedGroups
Agree that this should be follow-up work. However, I'll point out that I don't think a no-op implementation will be very helpful here - the implementation must be aware that the cache is not present, to avoid making extra calls to list out orgs/teams/etc when it can just fall back to listing all affiliated repositories (like before this PR) which is what it does when we check if groupsCache is nil

2021-08-24 15:25 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +	if args.Options != nil && args.Options.InvalidateCaches != nil {
I swear I got caught by this before as well haha, thanks!

2021-08-24 15:38 UTC, unknwon reviewed
Do we have a test covering different default organization permissions (none vs read)?

2021-08-24 15:38 UTC, unknwon commented on internal/authz/github/github.go
> +			// of the org's.
```suggestion
			// If a team's repos is a subset of an organization's, don't sync. Because when an organization
			// has at least default read permissions, a team's repos will always be a strict subset
			// of the organization's.
```

2021-08-24 15:38 UTC, unknwon commented on internal/authz/github/github.go
> +			return groups, err
Is the incomplete list of groups useful at all that we want to return with the error?

2021-08-24 15:38 UTC, unknwon commented on internal/authz/github/github.go
> +		}
nit: this is coupling cache manipulation with the operation of hitting the list groups API, if we could invalidate the cache before the call of `getAffiliatedGroups` is better decoupled. I also consider trying to delete a non-existent item in Redis is cheap, as `InvalidateCaches` is default false, so should only happen sporadically.

2021-08-24 15:41 UTC, bobheadxi commented on internal/authz/github/github.go
> +			return groups, err
Returning incomplete results (e.g. with f8f623aed40f8f87c4210ed97c96951a5b9f66a7 just now) is mostly just a pattern I noticed with https://sourcegraph.com/github.com/sourcegraph/sourcegraph@team-permissions-sync/-/blob/internal/authz/iface.go#L78:1-81:90 : 

```go
	// Because permissions fetching APIs are often expensive, the implementation should
	// try to return partial but valid results in case of error, and it is up to callers
	// to decide whether to discard.
```

2021-08-24 15:44 UTC, unknwon commented on internal/authz/github/github.go
> +				p.groupsCache.setGroup(group)
Yeah, looks aligned to what we want authz provider to do in case of error:

https://github.com/sourcegraph/sourcegraph/blob/26ce04177e989f911866985eadb9820e15862b96/internal/authz/iface.go#L57-L59

2021-08-24 15:45 UTC, unknwon commented on internal/authz/github/github.go
> +			return groups, err
haha, i was just linking the exact lines in another comment, SGTM!

2021-08-24 15:46 UTC, bobheadxi commented on internal/authz/github/github.go
> +		}
1. User <-> group associations are not cached so we must call the list groups API before reaching into the cache, which is better I think because we should make sure to have updated group memberships and it is an inexpensive call in most setups I believe. 
2. The intent of `InvalidateCaches` is to only invalidate caches *along the path of a sync*, to avoid causing massive spikes in every single user suddenly requiring a full sync if only a single team has changed by e.g. webhook. Because of this, and the above, caches cannot be invalidated without listing groups

2021-08-24 15:48 UTC, unknwon approved these changes
LGTM as long as the test mentioned in https://github.com/sourcegraph/sourcegraph/pull/23978#pullrequestreview-737361669 is addressed.

Approve to unblock.

2021-08-24 15:49 UTC, bobheadxi commented
> Do we have a test covering different default organization permissions (none vs read)?

Covered here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@team-permissions-sync/-/blob/internal/authz/github/github_test.go#L240:1-245:21

2021-08-25 02:14 UTC, merged

2021-08-25 15:07 UTC, bobheadxi commented on internal/extsvc/github/common.go
>  }
Turns out I forgot to undo this change - follow-up in https://github.com/sourcegraph/sourcegraph/pull/24316