repo-updater: Add PermsSyncer to syncer & sync private repo perms
sourcegraph/sourcegraph pull request #24028
Opened 2021-08-17 06:58 UTC by indradhanush

2021-08-17 09:19 UTC, tsenart requested changes

2021-08-17 09:19 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +		PermsSyncer: server.PermsSyncer,
Why do we need to couple the Syncer with PermsSyncer? As I said in a previous comment, they are orthogonal, so the struct definition should't have to change.

2021-08-17 09:19 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +				for _, r := range append(diff.Added, diff.Modified...) {
This mutates diff.Added, which I don't think is very clean. Can you find an alternative?

2021-08-17 09:19 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +					if r.Private {
This won't trigger a perms sync for repos that were private but became public. How do we handle those cases?

2021-08-17 09:41 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +					if r.Private {
My understanding is that if a repo has become public we don't need to sync permissions for them because the authz check doesn't use permissions for public repos.

2021-08-17 09:42 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +		PermsSyncer: server.PermsSyncer,
Any thoughts on how to access the `PermsSyncer` from within the `watchSyncer` function? :thinking:

2021-08-17 09:45 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +				for _, r := range append(diff.Added, diff.Modified...) {
Ran a quick test to verify this and I don't think it mutates `diff.Added` but creates a slice in-place? :thinking: 
Playground Link: https://play.golang.org/p/ev91DXTXnyy

2021-08-17 12:12 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +				for _, r := range append(diff.Added, diff.Modified...) {
Ah, this is a gotcha of slices. A new slice with a different backing array will be allocated by append if and only if the receiver doesn't have existing capacity. If it does, it will mutate. Here's an example: https://play.golang.org/p/siRs7al1k29

2021-08-17 12:13 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +		PermsSyncer: server.PermsSyncer,
Pass it as an argument?

2021-08-17 12:15 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +					if r.Private {
While that is true, we'll leave behind IDs in the user permissions that should no longer be there. We need to clean those up somehow or we're breaking the contract of those methods (which are supposed to eventually return private repos a user has access to only I believe).

2021-08-17 14:02 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +		PermsSyncer: server.PermsSyncer,
Ah, of course. I got so locked into the previous chain of thought that this never occurred to me. :sweat_smile:

2021-08-17 14:12 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +				for _, r := range append(diff.Added, diff.Modified...) {
This was very educational. Thank you. TIL. 

I looked through the references `repos.Diff` in the codebase and it doesn't appear that we are initialising it in any place with a non-zero capacity. However, I do see that there are no guarantees of it being this way always and the current approach leaves out a small chance of a nasty hard to find bug. I'm happy to change this to something safer. :ok_hand:

2021-08-17 14:24 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +					if r.Private {
Trying to detect a private repo becoming public here would require a bigger API change to `repos.Diff` and has a greater area of potential impact. IMO, the decision to sync or clean out such repos is the responsibility of the permission syncer and not the scheduler. As a result it should be beyond the scope of this PR.

It appears that we already have a check for private repos here before we process them for permissions syncing:
https://github.com/sourcegraph/sourcegraph/blob/main/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L455

And as a result of that check, the code path would follow along here and ultimately return an error:
https://github.com/sourcegraph/sourcegraph/blob/main/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L474-L487

2021-08-17 16:29 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +					if r.Private {
Will the permissions syncer then be changed to eventually remove now public repos from its tables?

2021-08-17 16:30 UTC, tsenart commented on cmd/repo-updater/shared/main.go
>  				continue
I think you want to run your code regardless of gps being nil, so you need to change this logic.

2021-08-17 16:31 UTC, tsenart approved these changes

2021-08-17 16:31 UTC, tsenart commented on cmd/repo-updater/shared/main.go
> +				for _, r := range append(diff.Added, diff.Modified...) {
Yeah, please change :)

2021-08-18 08:17 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
>  				continue
Good catch. I think I should move the perm syncing stuff before this check.

2021-08-18 08:54 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +					if r.Private {
I suppose that would be the right thing to do. I don't think we have an issue to track this at the moment. @unknwon any thoughts?

2021-08-18 10:02 UTC, unknwon commented on cmd/repo-updater/shared/main.go
> +				permsSyncer.ScheduleRepos(ctx, repoIDs...)
Could we add a Prometheus metric to track how many syncs are scheduled? Looping over `diff.Modified` means we will kick off a perm sync on almost every Git update, which seems a lot.

2021-08-18 10:12 UTC, unknwon commented on cmd/repo-updater/shared/main.go
> +				permsSyncer.ScheduleRepos(ctx, repoIDs...)
Oh NVM...

2021-08-18 10:13 UTC, unknwon approved these changes

2021-08-18 11:32 UTC, indradhanush commented on cmd/repo-updater/shared/main.go
> +				permsSyncer.ScheduleRepos(ctx, repoIDs...)
Created a [follow up PR](https://github.com/sourcegraph/sourcegraph/pull/24082) stacked on this so that we can go ahead and merge this without being blocked on the metrics related work, as I expect to need some help with that.

2021-08-18 11:34 UTC, merged