Enable sync all and add selection type tracking
sourcegraph/sourcegraph pull request #24710
Opened 2021-09-08 03:47 UTC by artemruts

### Description

This PR adds the following functionality:
1. enables the `sync all` UI for the "manage repositories" and post-sign-up flow pages
2. repositories now have `beta` badges instead of `new`
3. adds tracking to learn if the user is using the `sync all` feature or selects individual (own) repositories
4. adds tracking to learn if the user manually added public repositories by URL

### Tracking events

#### "manage repositories"  page

**event name**: `UserManageRepositoriesSave`
**payload**:

```ts
 {
     "userReposSelection": "all" | "specific" | null,
     "didAddReposByURL": boolean
 }
```
####  post-sign-up flow

**event name**: `PostSignUp_Repos_Saved`
**payload**:

```ts
 {
     "userReposSelection": "all" | "specific" | null,
 }
```

### UI changes

**Beta badges**
![beta badges](https://user-images.githubusercontent.com/1319181/132443085-96fb1ecd-e2b6-4259-bb2a-780e6e22c01b.png)

**Link to `sync all` docs**
![sync all docs](https://user-images.githubusercontent.com/1319181/132443133-adce24d5-d090-4c86-a87d-e2102c4b6a63.png)

2021-09-08 09:10 UTC, quinnkeast requested changes
We should avoid sprinkling links to docs at too granular a level, as then we're using the docs as a crutch instead of making the UI itself self-explanatory and intuitive.

With that in mind, let's remove the link from the helper text in the "Sync all" option, and update the top-level messaging to include a learn more link, which is a pattern we use in other places in Sourcegraph, and point at the [general docs page](https://docs.sourcegraph.com/code_search/how-to/adding_repositories_to_cloud rather than specifically the "Sync all" section.

Here's a screenshot of those changes (slight wording adjustment):

<img width="762" alt="image" src="https://user-images.githubusercontent.com/6304497/132480532-ffb5cd89-4bc9-4fd4-b0d7-eda475617a92.png">

>Choose which repositories to sync with Sourcegraph to search all your code in one place. <a>Learn more</a>

Additionally, I'm not sure if this is a consequence of this PR or something else, but the "other repositories by URL" option is missing:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/6304497/132481124-6b2eb705-4d1d-4cbd-8add-cd6446a8d5d4.png">

2021-09-08 15:07 UTC, artemruts commented
> We should avoid sprinkling links to docs at too granular a level, as then we're using the docs as a crutch instead of making the UI itself self-explanatory and intuitive.
> 
> With that in mind, let's remove the link from the helper text in the "Sync all" option, and update the top-level messaging to include a learn more link, which is a pattern we use in other places in Sourcegraph, and point at the [general docs page](https://docs.sourcegraph.com/code_search/how-to/adding_repositories_to_cloud) rather than specifically the "Sync all" section.
> 
> Here's a screenshot of those changes (slight wording adjustment):
> 
> <img alt="image" width="762" src="https://user-images.githubusercontent.com/6304497/132480532-ffb5cd89-4bc9-4fd4-b0d7-eda475617a92.png">
> 
> > Choose which repositories to sync with Sourcegraph to search all your code in one place. Learn more
> 
> Additionally, I'm not sure if this is a consequence of this PR or something else, but the "other repositories by URL" option is missing:
> 
> <img alt="image" width="855" src="https://user-images.githubusercontent.com/6304497/132481124-6b2eb705-4d1d-4cbd-8add-cd6446a8d5d4.png">

Thank you, I just didn't see any notes on where the link should go and to what section should it link. That's why I went with ☝️

2021-09-08 15:18 UTC, artemruts commented
> Additionally, I'm not sure if this is a consequence of this PR or something else, but the "other repositories by URL" option is missing:
> 
> <img alt="image" width="855" src="https://user-images.githubusercontent.com/6304497/132481124-6b2eb705-4d1d-4cbd-8add-cd6446a8d5d4.png">

I just checked locally, and the section is there. Maybe it has to do with how you're running the local instance if you use `sg.

2021-09-08 17:26 UTC, artemruts commented on client/web/src/auth/PostSignUpPage.tsx
> +                                                    We’ll sync and index these repositories so you can search your code
@quinnkeast I removed `to search with Sourcegraph`, I think it's obvious and will make lines break better.

2021-09-08 18:40 UTC, 5h1rU approved these changes
Excellent description. 🔥

2021-09-08 18:40 UTC, 5h1rU commented on client/web/src/auth/PostSignUpPage.tsx
> +                                                        {' '}
Do you need this empty space?

2021-09-09 01:04 UTC, artemruts commented on client/web/src/auth/PostSignUpPage.tsx
> +                                                        {' '}
I do 😄

2021-09-09 09:20 UTC, quinnkeast approved these changes
Looks great! Thanks!

2021-09-10 06:15 UTC, attfarhan approved these changes

2021-09-10 06:15 UTC, attfarhan commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
> +            eventLogger.log('UserManageRepositoriesSave', loggerPayload, loggerPayload)
```suggestion
            eventLogger.log('UserSettingsManageRepositoriesSaved', loggerPayload, loggerPayload)
```

2021-09-10 06:15 UTC, attfarhan commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
> +            eventLogger.log('UserManageRepositoriesSave', loggerPayload, loggerPayload)
To be consistent with other user settings page events.

2021-09-10 13:35 UTC, ryphil approved these changes
Metrics look good. Would love to track if they hit the Skip for Now button if possible but approving to unblock.

2021-09-10 15:16 UTC, artemruts commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
> +            eventLogger.log('UserManageRepositoriesSave', loggerPayload, loggerPayload)
Thank you!

2021-09-10 15:47 UTC, artemruts commented
> Metrics look good. Would love to track if they hit the Skip for Now button if possible but approving to unblock.

Synced with Ryan offline. "Skip" metrics already went out with https://github.com/sourcegraph/sourcegraph/pull/24022

2021-09-10 15:49 UTC, merged