WIP: Updating to Apollo client
sourcegraph/sourcegraph pull request #24912
Opened 2021-09-13 16:52 UTC by Numbers88s

## Context

Updating our graphql frontend implementation to use Apollo Client. See #24478 

## Changes
- Updates the CodeIntelConfigurationPage and underlying components.

- Updates

2021-09-13 22:12 UTC, efritz requested changes
Found a few issues playing with storybook and/or a local stack (looking only at the configuration list page at the global and repository scopes):

- I don't see any delete/edit buttons for policies I've just created (ensuring they aren't protected).
- There's _only_ a button to create a new policy on the global policies pane, even in the repository-specific page (in that page, global policies should be read-only and users should be able to make a new repository-specific policy).

2021-09-13 22:12 UTC, efritz commented on dev/site-config.json
> +  "codeIntelAutoIndexing.enabled": true
I put this in my own dev-private clone so that only code intel has to run the executors, which are kind of large.

2021-09-13 23:22 UTC, Numbers88s commented on dev/site-config.json
> +  "codeIntelAutoIndexing.enabled": true
Sounds good, I removed the `"codeIntelAutoIndexing.enabled":true` bit. 

I also updated the component, you should see the delete/edit buttons now. I got the logic backwards 😄 

w/r/t
> There's only a button to create a new policy on the global policies pane, even in the repository-specific page (in that page, global policies should be read-only and users should be able to make a new repository-specific policy).

Thanks for the explanation 👍  It really helped. I sorted it out, but please let me know if missed something.

2021-09-13 23:23 UTC, efritz commented on dev/site-config.json
> +  "codeIntelAutoIndexing.enabled": true
I'll run it again tonight and do another review pass 😃

2021-09-14 01:34 UTC, efritz requested changes
Looks better! Seems like there's a missing index configuration tab in the repository view:

<img width="829" alt="Screen Shot 2021-09-13 at 8 33 30 PM" src="https://user-images.githubusercontent.com/103087/133179966-46568957-4b76-4a1c-bb82-7ed7179e57dd.png">

And after deleting a policy from the list page, that policy should be removed from the list. Otherwise there's no indication of anything having happened, and doing it again causes a console error as the policy isn't found the second time.

2021-09-14 21:18 UTC, efritz approved these changes
Everything works locally!

2021-09-14 22:39 UTC, merged