FIX: Add primary email when user has no email
sourcegraph/sourcegraph pull request #25008
Opened 2021-09-15 17:40 UTC by abeatrix

This PR is to address the issue reported in https://github.com/sourcegraph/sourcegraph/issues/24976

Adding an email to accounts with no existing emails will break the email setting page for the user. This bug is blocking our customers from using Code Monitor. The root cause was the backend not being able to locate the primary email for the account in the database after an email has been added. To resolve this, we could check if the user has any existing email in their account when trying to add a new email and set the newly added email as the primary email if the account has no existing email. 

![image](https://user-images.githubusercontent.com/68532117/133482514-6e1fa883-7738-495f-901d-6c849d236387.png)

![image](https://user-images.githubusercontent.com/68532117/133480649-0be0ffad-273a-4dc2-b465-cdd0e74675ec.png)

2021-09-15 18:03 UTC, indradhanush commented on cmd/frontend/graphqlbackend/user_emails.go
> +		if err := database.UserEmails(r.db).SetVerified(ctx, userID, args.Email, true); err != nil {
I'm not sure if we want to mark the email as verified here. Maybe we should trigger a verification email instead?

2021-09-15 18:55 UTC, abeatrix commented on cmd/frontend/graphqlbackend/user_emails.go
> +		if err := database.UserEmails(r.db).SetVerified(ctx, userID, args.Email, true); err != nil {
I believe when site admin create a user with email added, the email is set as verified and primary automatically without triggering a verification email to bypass this bug, because email must be verified before they can be set as the primary email. If only a verification email Is sent in this step, this bug might still presist because after the email has been verified, it is still not set as the primary email?

2021-09-16 12:58 UTC, unknwon commented on cmd/frontend/graphqlbackend/user_emails.go
> +		if err := database.UserEmails(r.db).SetVerified(ctx, userID, args.Email, true); err != nil {
>I believe when site admin create a user with email added

This assumption is not true at all time, with this change, users can now add arbitrary emails and these emails become verified without being actually verified.

I think this is not the right place to set primary email, and that should happen when user verified an email, and when that email happens to be the only email, we then set the email to be the primary email automatically.

2021-09-16 12:59 UTC, unknwon requested changes
Request change because currently causes unintended side effects.

2021-09-16 16:28 UTC, abeatrix commented
@indradhanush @unknwon  Thank you both for the feedback, that makes a lot of sense! I updated the code so that only instances that do not have SMTP configured will set the email as primary and verified --would this approach work?

2021-09-16 18:53 UTC, indradhanush approved these changes
Great work in this PR! :rocket: 

Approved to unblock. Suggested a change to simplify the code by returning early and eliminating the nesting of the else block.

I think this now makes sense to mark the email as verified and as primary if the Sourcegraph instance cannot send emails.
Out of curiosity, is our customer's instance set up in this way that it cannot send emails? :thinking: 

I'd wait for @unknwon's review before merging as he probably has more context.

Sidenote: You've got a linter error that would need to be fixed before this can be merged. :slightly_smiling_face:

2021-09-16 18:53 UTC, indradhanush commented on cmd/frontend/graphqlbackend/user_emails.go
>  		}
```suggestion
		}
		return &EmptyResponse{}, nil
```

2021-09-16 18:53 UTC, indradhanush commented on cmd/frontend/graphqlbackend/user_emails.go
> +		}
```suggestion
	}
	// If user has no existing email, the added email will be set as the primary email
	if len(emails) == 0 {
		if err := database.UserEmails(r.db).SetVerified(ctx, userID, args.Email, true); err != nil {
			return nil, err
		}
		if err := database.UserEmails(r.db).SetPrimaryEmail(ctx, userID, args.Email); err != nil {
			return nil, err
		}
	}
```

2021-09-16 19:03 UTC, abeatrix commented on cmd/frontend/graphqlbackend/user_emails.go
> +		if err := database.UserEmails(r.db).SetVerified(ctx, userID, args.Email, true); err != nil {
See below for changes made

2021-09-16 19:30 UTC, abeatrix commented
@indradhanush Thank you for reviewing this during afterhour 🥺

2021-09-22 23:38 UTC, slimsag commented on cmd/frontend/internal/app/verify_email.go
> +		emails, err := database.GlobalUserEmails.ListByUser(ctx, database.UserEmailsListOptions{
```suggestion
		emails, err := database.UserEmails(db).ListByUser(ctx, database.UserEmailsListOptions{
```

This is better and the same, as we're trying to deprecate the old `Global*` variant in favor of explicitly passing the `db` around.

2021-09-22 23:43 UTC, slimsag commented on cmd/frontend/graphqlbackend/user_emails.go
> +		if err := database.UserEmails(r.db).SetVerified(ctx, userID, args.Email, true); err != nil {
@abeatrix if my reading of the code is right, the changes you've made to `cmd/frontend/internal/app/verify_email.go` are good and sufficient to address this bug - but the changes still in this file under the `AddUserEmail` method need to be undone I believe, as it would still lead to the issue Joe pointed out above

2021-09-22 23:44 UTC, slimsag commented
Awesome work on this!

2021-09-23 16:51 UTC, abeatrix commented on cmd/frontend/internal/app/verify_email.go
> +		emails, err := database.GlobalUserEmails.ListByUser(ctx, database.UserEmailsListOptions{
That's good to know! Thank you @slimsag!

2021-09-27 10:33 UTC, unknwon commented on cmd/frontend/internal/app/verify_email.go
> +			http.Error(w, fmt.Sprintf("User %d email %q cannot be verified", usr.ID, email), http.StatusBadRequest)
I think we should call what's been originally used as in line 63 `httpLogAndError(...`.

2021-09-27 10:33 UTC, unknwon commented on cmd/frontend/internal/app/verify_email.go
> +		// Set the verified email as primary if user has no primary email
We should move up line 66-69 here, because there is no need to attempt setting the primary email if the verification process had failed already.

2021-09-28 14:10 UTC, unknwon approved these changes
Approve to unblock

2021-09-28 14:10 UTC, unknwon commented on cmd/frontend/internal/app/verify_email.go
> +			log15.Warn("Failed to get user email", "error", err)
```suggestion
			log15.Error("Failed to get user email", "error", err)
```

2021-09-28 14:10 UTC, unknwon commented on cmd/frontend/internal/app/verify_email.go
> +		}
```suggestion
```

2021-09-28 14:10 UTC, unknwon commented on cmd/frontend/internal/app/verify_email.go
> +				return
```suggestion
				httpLogAndError(w, "Could not set primary email.", http.StatusInternalServerError, "userID", usr.ID, "email", email, "error", err)
				return
```

2021-09-28 14:15 UTC, indradhanush approved these changes

2021-09-28 14:15 UTC, indradhanush commented on cmd/frontend/graphqlbackend/user_emails.go
> +		return &EmptyResponse{}, nil
We probably don't need this anymore as the code will continue down and return on line 95.

```suggestion
```

2021-09-29 16:42 UTC, merged