Updating ConfigurationEditor to use Apollo
sourcegraph/sourcegraph pull request #25013
Opened 2021-09-15 20:34 UTC by Numbers88s

This PR updates ConfigurationEditor component as part of the Apollo client updates.

2021-09-15 22:37 UTC, efritz commented on client/web/src/enterprise/codeintel/configuration/RepositoryConfiguration.tsx
> +    telemetryService: TelemetryService
`ThemeProps` and `TelemetryProps` should include these fields already, no?

2021-09-15 22:38 UTC, efritz commented on client/web/src/enterprise/codeintel/configuration/ConfigurationEditor.tsx
> +    telemetryService: TelemetryService
same comment here as below (also not sure I missed any of these in the other PR)

2021-09-15 22:40 UTC, efritz requested changes
You're on 🔥 👏 !

The only weird behavior I saw (that I think doesn't match current behavior, or at least expected behavior) is that after saving the configuration the page state isn't updated properly.

It should be that the discard action should no longer be enabled, and navigating away from the page shouldn't prompt you to check your unsaved changes (you just saved them!).

2021-09-15 22:42 UTC, Numbers88s commented
Ah interesting, ok I'll take a look at that. Thank you!!

2021-09-15 22:43 UTC, Numbers88s commented on client/web/src/enterprise/codeintel/configuration/RepositoryConfiguration.tsx
> +    telemetryService: TelemetryService
Yeah it does 👍  I removed the dups then. I missed it coming from the extends.

2021-09-15 22:43 UTC, Numbers88s commented on client/web/src/enterprise/codeintel/configuration/ConfigurationEditor.tsx
> +    telemetryService: TelemetryService
Yeah it does 👍  I removed the dups then. I missed it coming from the extends.

2021-09-16 01:37 UTC, Numbers88s commented
I was under the impression that Apollo would handle the cache a little better, but its all good, I have more control over it now. It's fixed. Let me know what you think ✌️

2021-09-16 15:59 UTC, efritz approved these changes

2021-09-16 15:59 UTC, efritz commented
![image](https://user-images.githubusercontent.com/103087/133645734-fd21538b-0082-448c-9a0b-35e1a128bb55.png)

2021-09-16 16:57 UTC, merged