Adding Mattermost notification format
sourcegraph/sourcegraph pull request #25026
Opened 2021-09-16 03:32 UTC by it33

2021-09-20 14:06 UTC, bobheadxi requested changes
TIL Mattermost's webhooks are slack-compatible, thanks for documenting this! See feedback 😄

2021-09-20 14:06 UTC, bobheadxi commented on doc/admin/observability/alerting.md
> +#### Mattermost
Can we just make Mattermost an additional line in the Slack notifier documentation above, with a link to https://docs.mattermost.com/developer/webhooks-incoming.html , which notes that Mattermost is Slack-compatible? I think having a separate section demonstrating a Mattermost notifier with `"type": "slack"` is a bit confusing and fills like a typo

2021-09-23 15:31 UTC, it33 commented on doc/admin/observability/alerting.md
> +#### Mattermost
@bobheadxi highly appreciate the feedback. One of the reasons for the PR is that we're talking to Gartner today and they specifically asked about Mattermost's compatibility with SourceGraph. 

What we want to say is "Yes!" as it's good for both our companies and communities. 

Moreover, we want to make it easier for our community to adopt SourceGraph with a copy-and-paste solution for SourceGraph integration. 

While I do agree it can be slightly confusing to not insist that `mattermost` is explicitly declared as a type, this is standard knowledge for Mattermost users--We could add that option in future, my hope is it doesn't hold back our ability to talk to Gartner favorably about being explicit in SourceGraph-Mattermost compatibility.

2022-02-01 22:25 UTC, bobheadxi approved these changes

2024-01-10 20:32 UTC, eseliger commented
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

2024-01-10 20:32 UTC, closed without merging