doc: add Notifications on Sourcegraph cloud
sourcegraph/sourcegraph pull request #25092
Opened 2021-09-19 03:49 UTC by unknwon

TBD

2021-09-20 08:56 UTC, kopancek commented on doc/cloud/nofitications_on_cloud.md
> +1. **Everthing goes well:** All of your repositories are successfully cloned and indexed, search results are complete and coming back very fast.
Do we actually have a notification that says `Everything goes well`? Also, there seems to be a typo:
```suggestion
1. **Everything goes well:** All of your repositories are successfully cloned and indexed, search results are complete and coming back very fast.
```

2021-09-20 11:28 UTC, quinnkeast requested changes

2021-09-20 11:28 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **No repositories:** You have not added any repository, try [Adding repositories to Sourcegraph cloud](../code_search/how-to/adding_repositories_to_cloud.md).
```suggestion
1. **No repositories:** You have not added any repositories. Try [Adding repositories to Sourcegraph cloud](../code_search/how-to/adding_repositories_to_cloud.md).
```

2021-09-20 11:28 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Repositories cloning:** Some or all of your repositories are currently being cloned into Sourcegraph cloud. At this stage, search results are computed on-the-fly over your repositories which cou
```suggestion
1. **Repositories cloning:** Some or all of the repositories you've added to Sourcegraph are currently being cloned. At this stage, search results are computed on-the-fly over your repositories. Note that this may be slow, and you may not get search results across all of the repositories you've added to Sourcegraph.
```

2021-09-20 11:28 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Repositories indexing:** Some or all of your repositories are currently being indexed. At this stage, search results are coming back much faster for your repositories.
```suggestion
1. **Repositories indexing:** Some or all of your repositories are currently being indexed. Search results will return quickly across all of your repositories.
```

2021-09-20 11:28 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Everything goes well:** All of your repositories are successfully cloned and indexed, search results are complete and coming back very fast.
```suggestion
1. **Everything is good:** All of the repositories you've added to Sourcegraph have been cloned and indexed. Search results are fast across all of your repositories.
```

2021-09-20 11:28 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Something went wrong:** Something unexpected happened during repositories cloning stage, please refer to the [Troubleshooting](#Troubleshooting) section for possible solutions.
```suggestion
1. **Something went wrong:** Something unexpected happened while cloning the repositories you added to Sourcegraph. Please refer to the [Troubleshooting](#Troubleshooting) section for possible solutions.
```

2021-09-20 11:28 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Sourcegraph.com OAuth application is revoked on the code host:** You may have accidentally revoked the Sourcegraph.com OAuth application on the code host, if you do not see the Sourcegraph.com O
```suggestion
1. **Sourcegraph.com OAuth application is revoked on the code host:** Check whether the Sourcegraph.com OAuth application on the code host appears in your authorized OAuth applications list. If it does not appear, it may have been revoked. Try repeating [Adding repositories to Sourcegraph cloud](../code_search/how-to/adding_repositories_to_cloud.md).
```

2021-09-20 11:28 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **API rate limit exceeded:** The API rate limit quota of GitHub.com [shares among all OAuth applications authorized by that user, personal access tokens owned by that user, and requests authentica
```suggestion
1. **API rate limit exceeded:** GitHub.com's API rate limit quota is [shared among all OAuth applications authorized by a user, personal access tokens owned by that user, and requests authenticated with that user's username and password](https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps#normal-user-to-server-rate-limits). While Sourcegraph cloud consumes very low usage of API rate limit quota, if you have an unusually heavy workload during a given period of time, this rate limit may be exceeded. If this happens, the error should be resolved automatically within the next hour once the GitHub.com API rate limit quota is renewed.
```

2021-09-20 11:50 UTC, kopancek commented on doc/cloud/nofitications_on_cloud.md
> +1. **Repositories indexing:** Some or all of your repositories are currently being indexed. At this stage, search results are coming back much faster for your repositories.
Should we instead say, that `Search results will return quickly across all of your indexed repositories.`?
Because for those repositories that are still in the indexing queue, this is not really true.

2021-09-20 11:56 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Repositories indexing:** Some or all of your repositories are currently being indexed. At this stage, search results are coming back much faster for your repositories.
Ooh, great call!

2021-09-20 11:58 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Repositories indexing:** Some or all of your repositories are currently being indexed. At this stage, search results are coming back much faster for your repositories.
Updated original to get this idea across: searches will target all of the repositories, even unindexed ones, but they'll be faster when indexed.

2021-09-20 12:05 UTC, kopancek commented on doc/cloud/nofitications_on_cloud.md
> +1. **Sourcegraph.com OAuth application is revoked on the code host:** You may have accidentally revoked the Sourcegraph.com OAuth application on the code host, if you do not see the Sourcegraph.com O
Changed the text with the same context, but slightly different wording.

2021-09-20 12:06 UTC, kopancek commented on doc/cloud/nofitications_on_cloud.md
> +1. **API rate limit exceeded:** The API rate limit quota of GitHub.com [shares among all OAuth applications authorized by that user, personal access tokens owned by that user, and requests authentica
Changed the text with the same context, but slightly different wording. It reads better to me this way.

2021-09-20 12:20 UTC, quinnkeast commented on doc/cloud/nofitications_on_cloud.md
> +1. **Everything is good:** All of the repositories you've added to Sourcegraph have been cloned and indexed. Search results are fast across all of your repositories.
```suggestion
1. **Everything is good:** All of the repositories you've added to Sourcegraph have been cloned and indexed. Search results will be fast across all of your repositories.
```

2021-09-21 12:03 UTC, quinnkeast approved these changes

2021-09-21 12:06 UTC, merged