insights: Add metrics around the commit indexer
sourcegraph/sourcegraph pull request #25187
Opened 2021-09-21 19:39 UTC by CristinaBirkel

Closes #22037

Draft: I'm going to clean this up and then write up the description/testing steps.

2021-09-22 19:17 UTC, coury-clark requested changes
Looks good overall! Just need to change the per-repo counter into a single counter and should be good!

2021-09-22 19:17 UTC, coury-clark commented on enterprise/internal/insights/compression/observability.go
> +		Help: "Total number of commits added to the commit index for this repo",
```suggestion
		Help: "Number of commits added to the commit index",
```

This won't be tracking totals, just counts over some interval of time. Likewise since we aren't going to break out per-repo cardinality, this is an aggregated value.

2021-09-22 19:17 UTC, coury-clark commented on enterprise/internal/insights/compression/worker.go
> +	i.operations.countCommits.WithLabelValues(string(repoName)).Add(float64(len(commits)))
Ah didn't see this. This is going to be really large cardinality and doesn't add much utility over tracking an aggregate. If someone really needed to they can query the index directly for per-repo breakout. For now I think we are best off just with a high level aggregate count.

2021-09-22 19:28 UTC, CristinaBirkel commented on enterprise/internal/insights/compression/worker.go
> +	i.operations.countCommits.WithLabelValues(string(repoName)).Add(float64(len(commits)))
Okay sounds good! I wasn't sure if that would be useful or not; I'll take out the labels. 👍

2021-09-23 16:12 UTC, coury-clark approved these changes
LGTM!

2021-09-24 19:15 UTC, merged