insights: add site configuration value for commit indexer interval
sourcegraph/sourcegraph pull request #25312
Opened 2021-09-23 20:40 UTC by CristinaBirkel

Closes #22038

### Description

This adds a site configuration value for the commit indexer interval, (in minutes,) and reads the value in when setting the interval in the commit indexer.

### Testing Steps

This was a little tricky to test; it doesn't seem like the site configuration settings get saved through the UI. (Is that expected?) But I did verify:
- Saving an `insights.commit.indexer.interval` value warns that the service will need to be restarted in order for it to take effect.
- If I modify the site config in `dev-private` to include this value, the commit indexer interval is picked up and set appropriately.

Let me know if this sounds reasonable, or if I'm misunderstanding how to test it!

2021-09-23 21:03 UTC, coury-clark requested changes
LGTM other than the default time!

2021-09-23 21:03 UTC, coury-clark commented on enterprise/internal/insights/compression/worker.go
> +		intervalMinutes = 1
The documentation suggests a default of 60 minutes, but this would default to 1 if not provided. I think 60 is a more reasonable number.

2021-09-23 21:03 UTC, coury-clark commented on schema/site.schema.json
> +      "description": "The interval (in minutes) at which the commit indexer will check for new commits.",
```suggestion
      "description": "The interval (in minutes) at which the insights commit indexer will check for new commits.",
```

We have another team that is going to build a similar thing (that we may end up using), so let's be specific that this only affects the code insights one.

2021-09-23 21:08 UTC, CristinaBirkel commented on enterprise/internal/insights/compression/worker.go
> +		intervalMinutes = 1
Ah okay, I thought the default in the schema definition was actual default value that would get used! I thought this was more a safeguard for if a user put in a negative value. But that makes sense, and actually explains some of my confusion when testing. I'll change it. 👍

2021-09-23 21:08 UTC, CristinaBirkel commented on schema/site.schema.json
> +      "description": "The interval (in minutes) at which the commit indexer will check for new commits.",
Good call!

2021-09-24 19:16 UTC, coury-clark approved these changes
Nice!

2021-09-24 20:34 UTC, merged