Fa/amplitude http
sourcegraph/sourcegraph pull request #25324
Opened 2021-09-24 09:01 UTC by attfarhan

2021-09-27 07:10 UTC, unknwon requested changes
Request changes for some best practices on the backend.

2021-09-27 07:10 UTC, unknwon commented on internal/amplitude/publish.go
> +func Publish(amplitudeAPIToken string, jsonReq []byte) error {
```suggestion
func Publish(token string, body []byte) error {
```

Please also add some docstring.

2021-09-27 07:10 UTC, unknwon commented on internal/amplitude/publish.go
> +		log15.Warn("Could not log Amplitude event", "err", err)
Generally, I'd suggest having some kind of prefix to help locate the log faster. And this is a valid error (i.e. we must do something), not a warning (i.e. we should keep an eye on).

```suggestion
		log15.Error("amplitude: cannot create new request", "error", err)
```

2021-09-27 07:10 UTC, unknwon commented on internal/amplitude/publish.go
> +		resp, err := client.Do(req)
Our `httpcli` package [has builtin retry](https://github.com/sourcegraph/sourcegraph/blob/5d530e9f92d0ee6a403955965f8c5ed76ba3e5b5/internal/httpcli/client.go#L107-L109), so just simply do `httpcli.ExternalClient.Do(req)`.

2021-09-27 07:10 UTC, unknwon commented on internal/amplitude/publish.go
> +			}
It's a good time to do `switch` case.

2021-09-27 07:10 UTC, unknwon commented on internal/amplitude/types.go
> +type AmplitudeEventPayload struct {
```suggestion
type EventPayload struct {
```

Same for other occurrences, because we're already within the `amplitude` package.

2021-09-27 07:10 UTC, unknwon commented on internal/usagestats/event_handlers.go
> +	}
Looking at this usage of `amplitude.DenyList`, I'm wondering why can't we make `amplitude.DenyList` is map? Loop over a slice for every single call of `publishAmplitudeEvent` feels not worth it.


```go
// on there
var DenyList = map[string]struct{}{
	"event_name",
}

// on here
if _, ok := amplitude.DenyList[eventName]; ok {
	return nil
}
```

2021-09-27 20:09 UTC, eseliger reviewed
did a first pass

2021-09-28 01:11 UTC, unknwon commented on cmd/frontend/graphqlbackend/schema.graphql
> +        insertID: String
They definitely can, happen to start a thread yesterday in Slack: https://sourcegraph.slack.com/archives/CN4FC7XT4/p1632725381158200

2021-09-28 04:26 UTC, attfarhan commented on cmd/frontend/graphqlbackend/schema.graphql
> +        insertID: String
Hmm yes good call out. I've thought about this too, especially with Google Analytics which is even worse, because the project ID is always publicly available in a site's raw HTML.

For these fields specifically ({Event|Insert|Device}ID), it's a problem for Amplitude only, so could we make it so that the Amplitude event key needs to be passed through with the GraphQL API call? We'd have to obviously get the key to the frontend so we'd have to fetch it without exposing it.

2021-09-28 15:20 UTC, attfarhan commented
@unknwon @eseliger I addressed the first round of comments, PTAL! I do not have a good solution to the GraphQL API comment on bad actors currently. Still doing research to see what we can do to address that, but I wonder if it may be better to address it separately. The larger issue is that logEvent (even in its current state), can be triggered outside the app.

2021-09-29 01:51 UTC, unknwon commented
> I do not have a good solution to the GraphQL API comment on bad actors currently. Still doing research to see what we can do to address that, but I wonder if it may be better to address it separately. The larger issue is that logEvent (even in its current state), can be triggered outside the app.

Of course! That's a whole separate concern, I agree it does not make sense to address with this PR.

2021-09-29 01:59 UTC, unknwon requested changes
Thanks for addressing feedbacks!

Request changes to take another look before landing this PR.

2021-09-29 01:59 UTC, unknwon commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +	EventID        *int32
Is it logically making sense that not all four fields are populated from the request? If not, then we probably want to do a quick check that make sure these four fields are all or none of them are populated.

2021-09-29 01:59 UTC, unknwon commented on internal/amplitude/publish.go
> +func Publish(body []byte) error {
Please add a docstring.

2021-09-29 01:59 UTC, unknwon commented on internal/amplitude/publish.go
> +const apiUrl = "https://api2.amplitude.com/2/httpapi"
```suggestion
const apiURL = "https://api2.amplitude.com/2/httpapi"
```

2021-09-29 01:59 UTC, unknwon commented on internal/amplitude/publish.go
> +		log15.Warn("Could not log Amplitude event", "err", err)
This seems not addressed.

2021-09-29 01:59 UTC, unknwon commented on internal/amplitude/publish.go
> +		}
We generally want a `default` case catch status code that is even unexpected for errors, otherwise they're swallowed and we still think the system is functioning.

2021-09-29 01:59 UTC, unknwon commented on internal/usagestats/event_handlers.go
> +			DeviceID:        *args.DeviceID,
I think we would want a nil check for `args.DeviceID` first, so we get an error instead of runtime panic.

2021-09-29 05:04 UTC, attfarhan commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +	EventID        *int32
It is possible. It's definitely possible one day that we don't send any user properties from the frontend, but deviceID, InsertID, and EventID are not sent. The only required field is DeviceID, so it's also possible that we send only a device ID and not an insert or event ID. But in our current implementation, it _shouldn't_ happen. So we could add a check for that.

2021-09-29 05:30 UTC, attfarhan commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +	EventID        *int32
Yeah actually perhaps it makes sense to add a check for all 4. Since in our current implementation, it should be all or nothing.

2021-09-29 08:12 UTC, unknwon reviewed
Left some comments regarding some best practices, we're close!

2021-09-29 08:12 UTC, unknwon commented on internal/amplitude/publish.go
> +		return errors.WithMessage(err, "amplitude: cannot create new request")
I think errors on line 21 and 28 should be swapped? `http.NewRequest` only creates a new request object, and not yet sending the request to amplitude.

2021-09-29 08:12 UTC, unknwon commented on internal/amplitude/publish.go
> +		return errors.Errorf("amplitude: failed with %d %s", resp.StatusCode, string(body))
```suggestion
		return errors.Errorf("amplitude: failed with %d - %s", resp.StatusCode, string(body))
```

2021-09-29 08:12 UTC, unknwon commented on internal/amplitude/publish.go
> +		return err
We don't need to both log and return the error. Since this looks like a helper function, I suggest we should only return the error to the caller.

2021-09-29 08:12 UTC, unknwon commented on internal/amplitude/publish.go
> +			log15.Error("amplitude: Could not log Amplitude event", "error", err)
Since this function looks like a helper, I suggest we should only return the error to the caller.

2021-09-30 04:07 UTC, unknwon approved these changes
![](https://media4.giphy.com/media/jmS6YojdAaYw5z1LHi/giphy.gif)

2021-09-30 06:41 UTC, merged

2021-09-30 18:11 UTC, limitedmage commented on client/web/src/SourcegraphWebApp.tsx
> +        localStorage.setItem('SOURCEGRAPH_USER_PROPERTIES', JSON.stringify(userProps))
Question: Why use localStorage here instead of TemporarySettings?