codeintel: refactor lsif upload functionality to apollo
sourcegraph/sourcegraph pull request #25367
Opened 2021-09-24 20:07 UTC by Numbers88s

Refactor Lsif upload functionality to use Apollo as part of our ongoing efforts to update to apollo.

2021-09-28 20:27 UTC, efritz requested changes

2021-09-28 20:27 UTC, efritz commented on client/web/src/components/FilteredConnection/FilteredConnection.tsx
> +                                nodes = !shouldRefresh
I'm not currently convinced this is correct. I get strange behavior in the list view when paging now. It seems to _replace_ the set of nodes rather than _append_. Not sure why this change doesn't preserve that behavior (I assumed from the diff it would).

**This branch:**

![Kapture 2021-09-28 at 15 19 56](https://user-images.githubusercontent.com/103087/135160066-2b767db4-8dd6-46ba-b6fe-6a73315a86be.gif)

**Expected behavior (on Cloud):**

![Kapture 2021-09-28 at 15 21 20](https://user-images.githubusercontent.com/103087/135160255-a8d023c8-95dc-4567-8716-fead7637f20b.gif)

2021-09-28 20:27 UTC, efritz commented on client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.tsx
> +                        queryLisfUploadFields(id, apolloClient).pipe(
There also seems to be a bit of lost behavior here. When on a page for an index that isn't in a terminal state (COMPLETED or ERRORED, and as an aside we should update this to include some other new states), it should refresh every five seconds so that users will know when processing completes (or it moves from queued to processing).

You can check this behavior by uploading a bunch of indexes, or adding a `time.Sleep(time.Second * 10)` into the precise-code-intel worker to slow down processing enough to catch it. It seems to not update anymore. [This method](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/precise-code-intel-worker/internal/worker/handler.go?L82) processes uploads and would be the target for the sleep/sabotage.

I could have mucked something up on my end, though.

2021-09-29 00:28 UTC, Numbers88s commented on client/web/src/enterprise/codeintel/detail/CodeIntelUploadPage.tsx
> +                        queryLisfUploadFields(id, apolloClient).pipe(
Okay, I'll take a look at that method and check it out.

2021-09-29 00:30 UTC, Numbers88s commented on client/web/src/components/FilteredConnection/FilteredConnection.tsx
> +                                nodes = !shouldRefresh
Gotcha! thanks for finding it! I fixed it but gonna do a couple more test.

Also found another bug but want to confirm. In the cloud one, if you open the console, click "Show more", do you see a bunch of errors of duplicated keys as well?  This happens for me on main, so gonna fix that one as well.

2021-09-29 00:32 UTC, efritz commented on client/web/src/components/FilteredConnection/FilteredConnection.tsx
> +                                nodes = !shouldRefresh
React keys? Possibly. Can you make this happen consistently on Cloud, or only if there's a lot of moving data? It may be a race condition where a new upload pushes down the result set by one, so the backend is actually returning the tail of the previous page as the head of the next.

If that's the case, then we should ensure we deduplicate the nodes before concatenating them in the filtered connection.

2021-09-29 00:33 UTC, Numbers88s commented on client/web/src/components/FilteredConnection/FilteredConnection.tsx
> +                                nodes = !shouldRefresh
Definitely, which is what I did. Just checking in case its just my local. I'll push the changes, but just want to continue to keep testing it before I do.

2021-09-30 01:22 UTC, efritz commented on enterprise/internal/codeintel/stores/dbstore/indexes.go
> +WHERE %s ORDER BY queued_at, u.id DESC LIMIT %d OFFSET %d
```suggestion
WHERE %s ORDER BY queued_at DESC, u.id LIMIT %d OFFSET %d
```

This should preserve the tests (and actually be what we want to see). What I told you to add here was wrong because what we want is newest first, but the `DESC` only applies to the `u.id` here.

2021-09-30 01:24 UTC, efritz commented on client/web/src/components/FilteredConnection/FilteredConnection.tsx
> +                            let cne: C | ErrorLike | undefined = connectionOrError
nit: `cne` isn't a very descriptive name and might benefit from having additional context about _why_ we need to re-declare it here.

2021-09-30 01:24 UTC, efritz commented on client/web/src/components/FilteredConnection/FilteredConnection.tsx
> +                                nodes = [
```suggestion
                                // Deduplicate any elements that occur between pages. This can happen as results are added during pagination.
                                nodes = [
```

2021-09-30 01:25 UTC, efritz approved these changes
Looks good! Please apply the suggestion on the backend code before merging. Anything else is a nit comment.

2021-09-30 01:44 UTC, Numbers88s commented on client/web/src/components/FilteredConnection/FilteredConnection.tsx
> +                            let cne: C | ErrorLike | undefined = connectionOrError
all good, makes sense to me too. It started as a quick name to test and then I grew fond of it 😄

2021-09-30 16:16 UTC, merged