Update handbook links in doc
sourcegraph/sourcegraph pull request #26848
Opened 2021-10-29 16:13 UTC by siddhant94

Fixes #26633. Update handbook links in doc from `https://about.sourcegraph.com/handbook/*` to `https://handbook.sourcegraph.com/*` & `https://docs.sourcegraph.com/*`

2021-10-31 10:50 UTC, valerybugakov commented
@cla-bot check

2021-11-01 08:49 UTC, valerybugakov requested changes
@siddhant94, thanks for looking into it!
After fixing the issue mentioned in the review, it will be ready for merge.

2021-11-01 08:49 UTC, valerybugakov commented on internal/cmd/tracking-issue/testdata/issue-13988.md
> +We plan to complete all functional changes necessary to have individual Sourcegraphers (teammates) be able to add public code on sourcegraph.com. This is part of our first Cloud milestone as document
The CI check failed because fixtures [here](https://github.com/sourcegraph/sourcegraph/blob/main/internal/cmd/tracking-issue/testdata/fixtures.json) should be updated with the correct link to `out team page`.

2021-11-01 10:33 UTC, siddhant94 commented on internal/cmd/tracking-issue/testdata/issue-13988.md
> +We plan to complete all functional changes necessary to have individual Sourcegraphers (teammates) be able to add public code on sourcegraph.com. This is part of our first Cloud milestone as document
Got it. Reverted this file changes.

2021-11-01 11:13 UTC, valerybugakov requested changes

2021-11-01 11:13 UTC, valerybugakov commented on internal/cmd/tracking-issue/testdata/issue-13988.md
> +### Plan
Looks like we still have some changes made to this file. They cause the CI to fail. To resolve this, we can revert changes to this file via git to ensure it's not present in the diff.

2021-11-01 12:06 UTC, siddhant94 commented on internal/cmd/tracking-issue/testdata/issue-13988.md
> +### Plan
Ya did not cross-check. Now I have done it via git, and the updated PR does not contain that file in changes. Thanks.

2021-11-01 12:09 UTC, valerybugakov commented on internal/cmd/tracking-issue/testdata/issue-13988.md
> +### Plan
Triggered CI.

2021-11-01 12:50 UTC, valerybugakov requested changes
Final minor suggestions. The CI is green, so the merge is unblocked.

2021-11-01 12:50 UTC, valerybugakov commented on doc/dev/background-information/insights/backend.md
> +The current code insights backend is a beta version contributed by [Coury](https://handbook.sourcegraph.com/company/team#coury-clark-hehim) (based on previous work by [Stephen](https://handbook.sourc
```suggestion
The current code insights backend is a beta version contributed by [Coury](https://handbook.sourcegraph.com/company/team#coury-clark) (based on previous work by [Stephen](https://handbook.sourcegraph.com/company/team#stephen-gutekanst)) - it:
```

2021-11-01 12:50 UTC, valerybugakov commented on CONTRIBUTING.md
> -- [Size guidelines](https://about.sourcegraph.com/handbook/engineering/developer-insights#prefer-small-prs-lines)
Let's preserve this linking to https://handbook.sourcegraph.com/engineering/enablement#prefer-small-prs-400-lines

2021-11-01 12:50 UTC, valerybugakov commented on doc/dev/background-information/insights/index.md
> +  - [Code Insights team page](https://handbook.sourcegraph.com/engineering/code-graph/code-insights#code-insights-team)
```suggestion
  - [Code Insights team page](https://handbook.sourcegraph.com/engineering/code-graph/code-insights)
```

2021-11-01 14:24 UTC, siddhant94 commented on doc/dev/background-information/insights/backend.md
> +The current code insights backend is a beta version contributed by [Coury](https://handbook.sourcegraph.com/company/team#coury-clark-hehim) (based on previous work by [Stephen](https://handbook.sourc
Done

2021-11-01 14:27 UTC, siddhant94 commented
> Final minor suggestions. The CI is green, so the merge is unblocked.

thanks for the review. And I have done the review changes.

2021-11-01 16:09 UTC, valerybugakov approved these changes
Thank you! 🚀

2021-11-01 16:09 UTC, merged

2021-11-02 19:10 UTC, ltagliaferri commented
Hi @siddhant94, Sourcegraph would love to send you a Hacktoberfest treat, please email us at dev-ed@sourcegraph.com and reference this PR so we can set you up 🎃