web: codemod web/repo/RevisionsPopover web/repo/RepositoriesPopover c…
sourcegraph/sourcegraph pull request #26875
Opened 2021-11-01 12:37 UTC by gitstart-sourcegraph

## Descriptions

In process of migration from global CSS to [CSS modules](https://docs.sourcegraph.com/dev/background-information/web/styling#css-modules) using the [codemod](https://github.com/sourcegraph/codemod/tree/main/src/transforms/globalCssToCssModule) with some small manual fixes

## Refs

[Apply CSS Modules codemod to areas where automatic migration is possible](https://github.com/sourcegraph/sourcegraph/issues/23015)

## Success criteria

The stylesheets in the following directories are converted to CSS modules.

- client/web/src/repo/RevisionsPopover
- client/web/src/repo/RepositoriesPopover

2021-11-08 16:29 UTC, valerybugakov requested changes

2021-11-08 16:29 UTC, valerybugakov commented on client/web/src/repo/RevisionsPopover/RevisionsPopover.scss
> -.revisions-popover {
This class is used in end-to-end tests. Let's follow the [checklist](https://github.com/sourcegraph/codemod/tree/main/src/transforms/globalCssToCssModule#post-codemod-steps-in-the-sourcegraph-repo) defined in the codemod documentation to avoid such issues in pull requests.

https://github.com/sourcegraph/sourcegraph/blob/1d5a1187a900e6537411f9378145468e6b5918be/client/web/src/end-to-end/end-to-end.test.ts#L955

2021-11-08 16:29 UTC, valerybugakov commented on client/web/src/repo/RevisionsPopover/components/ConnectionPopoverList.tsx
> +export const ConnectionPopoverList: React.FunctionComponent<ConnectionPopoverListProps> = ({
Let's create a separate folder with the `index.ts` file for each new component instead of having all the files in one directory.

2021-11-08 16:29 UTC, valerybugakov commented on client/web/src/repo/RevisionsPopover/components/ConnectionPopoverTabs.module.scss
> +    --popover-item-padding-v: 0.25rem;
It seems that we can remove these variables because they are used only in one place.

2021-11-11 07:40 UTC, valerybugakov commented on client/web/src/repo/RevisionsPopover/components/ConnectionPopoverTabs.module.scss
> +    --popover-item-padding-v: 0.25rem;
@gitstart-sourcegraph, do we need these variables for some reason?

2021-11-11 07:42 UTC, valerybugakov approved these changes
Thanks!

Would you mind taking a look at the comment regarding CSS variables? If there's no reason to keep them, let's remove them before merging this PR.

2021-11-11 07:51 UTC, phunguyenmurcul commented on client/web/src/repo/RevisionsPopover/components/ConnectionPopoverTabs.module.scss
> +    --popover-item-padding-v: 0.25rem;
@valerybugakov ah sorry, I still keep it since we are using them in `padding` rule below, but since they are not reused in other places so I'm going to remove them and use value directly

2021-11-11 07:55 UTC, gitstart-sourcegraph commented on client/web/src/repo/RevisionsPopover/components/ConnectionPopoverTabs.module.scss
> +    --popover-item-padding-v: 0.25rem;
ah sorry, we still keep it since we are using them in padding rule below, but since they are not reused in other places so I'm going to remove them and use value directly

2021-11-11 10:04 UTC, merged