Add Redis monitoring dashboard
sourcegraph/sourcegraph pull request #26969
Opened 2021-11-02 22:30 UTC by daxmc99

2021-11-03 21:02 UTC, bobheadxi requested changes
You should be able to get a nice screenshot with real data if you want 😛 https://docs.sourcegraph.com/dev/how-to/monitoring_local_dev#grafana

2021-11-03 21:02 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +							-- Ensure redis-cache is running`},
I think this formatting expects a single dash - on my phone so can’t remember off the top of my head, but see other usages of this field for examples

2021-11-03 21:05 UTC, daxmc99 commented on sg.config.yaml
> +      IMAGE: sourcegraph/grafana:dev
@bobheadxi  I do have grafana running but I'm looking at how to setup the `redis_exporter` as well so that our Prometheus can hit it. 
The issue here is the difference between dev and prod env. We only run a single redis right now in the dev env.

2021-11-03 21:07 UTC, bobheadxi commented on sg.config.yaml
> +      IMAGE: sourcegraph/grafana:dev
See my other comment - if redis exporter is running in another environment, you can just port forward the prometheus from that environment for data

2021-11-03 21:08 UTC, daxmc99 commented on sg.config.yaml
> +      IMAGE: sourcegraph/grafana:dev
Ahh, sorry. That approach appears much easier.

2021-11-03 23:03 UTC, daxmc99 commented
Dashboard with data 😄 
<img width="1445" alt="Screen Shot 2021-11-03 at 6 01 23 PM" src="https://user-images.githubusercontent.com/31839142/140228761-c3fb267e-5e47-4cc5-82f7-4b17d2abf972.png">

2021-11-03 23:04 UTC, daxmc99 commented
@bobheadxi Should we add any container level monitoring? 
Also found some alerts here but I'm not sure if they would be worth adding https://awesome-prometheus-alerts.grep.to/rules.html#rule-redis-1-1

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +							Description: "redis-store up", Owner: monitoring.ObservableOwnerDevOps,
```suggestion
							Description: "redis-cache availability",
							Owner: monitoring.ObservableOwnerDevOps,
```

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +							`},
Can you add an `Interpretation` with what the value means here (0 vs 1)

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
>  						{Name: "redis-cache_up",
```suggestion
						{
							Name: "redis-cache_up",
```

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
>  						{Name: "redis-store_up",
```suggestion
						{
							Name: "redis-store_up",
```

(see other observables for consistency)

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +							Description: "redis-store up", Owner: monitoring.ObservableOwnerDevOps,
```suggestion
							Description: "redis-store availability",
							Owner: monitoring.ObservableOwnerDevOps,
```

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +							`},
Same here, an `Interpretation` indicating what the 0 and 1 means would be helpful

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +								- Ensure redis-store is running.
```suggestion
								- Ensure redis-store is running and has not crashed.
```

2021-11-04 00:29 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +								- Ensure redis-store is running.
or similar, `Ensure redis-store is running` feels a bit blunt maybe? 😅

2021-11-04 00:30 UTC, bobheadxi commented
> Should we add any container level monitoring? Also found some alerts here but I'm not sure if they would be helpful

These are standardized, I would look at what the other containers used, they're mostly in the `shared` library

2021-11-04 22:26 UTC, daxmc99 commented
Looks like our Redis instance in prod was suffering 😅 
<img width="1440" alt="Screen Shot 2021-11-04 at 5 24 05 PM" src="https://user-images.githubusercontent.com/31839142/140428916-ad8170ea-b65d-4ddd-8ee2-81206e69138c.png">

2021-11-05 00:42 UTC, bobheadxi reviewed
a few nits, otherwise LGTM!

2021-11-05 00:42 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +			{Title: "Redis Store",
```suggestion
			{
				Title: "Redis Store",
```

2021-11-05 00:42 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +					}},
```suggestion
					}
				},
```

2021-11-05 00:42 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +								- Ensure redis-cache is running
Match the other PossibleSolutions here?

2021-11-05 00:42 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +							Interpretation: "A value of 1 indicates the service is currently running"},
```suggestion
							Interpretation: "A value of 1 indicates the service is currently running"
						},
```

2021-11-05 00:42 UTC, bobheadxi commented on monitoring/definitions/redis.go
> +					}},
```suggestion
					}
				},
```

2021-11-05 22:50 UTC, daxmc99 commented
Thanks, @bobheadxi for the great review! It has been a second since I wrote any monitoring code and this was really straightforward.

2021-11-05 23:03 UTC, bobheadxi approved these changes
LGTMMMMM

2021-11-08 17:09 UTC, merged