Feedback and command line button in nav flash on page load
sourcegraph/sourcegraph pull request #27075
Opened 2021-11-04 15:17 UTC by gitstart-sourcegraph

## Description
Fix Nav item flashing on page load (FeedBack button and WebCommandList Button)

https://user-images.githubusercontent.com/19534377/138307798-c247073e-670c-42c1-be5c-9cf73239c2cb.mov

## Refs

- https://github.com/sourcegraph/sourcegraph/issues/26435
- https://www.loom.com/share/99ef01849bc44a3a86f8dc9c1e26e20b

2021-11-08 14:09 UTC, valerybugakov reviewed
@gitstart-sourcegraph, I see that the PR fixes the symptom of the issue, but what is the root cause of this flickering?

2021-11-08 14:30 UTC, gitstart-sourcegraph commented
> @gitstart-sourcegraph, I see that the PR fixes the symptom of the issue, but what is the root cause of this flickering?

@valerybugakov For now, app needs to check `authenticatedUser` before showing `FeedbackPrompt` `NavAction`, so those elements are added into DOM a litter bit later than others + those elements have `transition` css rule (inherit from `.btn` => so we see the flickering effect

2021-11-08 16:09 UTC, valerybugakov requested changes

2021-11-08 16:09 UTC, valerybugakov commented on client/wildcard/src/components/NavBar/NavAction.module.scss
> +    transition: visibility 0s;
@gitstart-sourcegraph, the proposed fix breaks the transition effect on the element that should be preserved. Correct me if I'm wrong here.

2021-11-09 02:35 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/NavBar/NavAction.module.scss
> +    transition: visibility 0s;
Thank @valerybugakov, my mistake, investigated deeply and found a reason for that here https://github.com/sourcegraph/sourcegraph/issues/26435#issuecomment-963422763

2021-11-11 06:45 UTC, gitstart-sourcegraph commented
@valerybugakov Updated PR to fix the issue, basically we just to replace `useEffect` with `useMemo` to have these class toggle work before components get rendered

2021-11-11 07:36 UTC, valerybugakov approved these changes

2021-11-11 07:45 UTC, merged