WIP on moving Org repositories to enterprise/
sourcegraph/sourcegraph pull request #27129
Opened 2021-11-05 13:27 UTC by rafax

2021-11-05 15:05 UTC, rafax commented on cmd/frontend/graphqlbackend/org.go
> +	return EnterpriseResolvers.orgRepositoryResolver.OrgRepositories(ctx, args, o.org, func(db database.DB, opt database.ReposListOptions, args *ListOrgRepositoriesArgs) RepositoryConnectionResolver {
This (passing a function) is done to avoid the need to make RepositoryConnectionResolver public - is there a better way @unknwon @kopancek ?

2021-11-05 15:05 UTC, rafax commented on cmd/frontend/graphqlbackend/orgs.go
> +	OrgRepositories(ctx context.Context, args *ListOrgRepositoriesArgs, org *types.Org, resolverFn func(database.DB, database.ReposListOptions, *ListOrgRepositoriesArgs) RepositoryConnectionResolver) (R
Should I use a dedicated type for resolverFn (to avoid the long type signature in multiple places)?

2021-11-05 15:05 UTC, rafax commented
@kopancek this is still WIP (I need to move tests at the very least), but I wanted to get your opinion whether this accomplishes what you had in mind for CLOUD-83.

2021-11-08 12:36 UTC, kopancek commented on cmd/frontend/graphqlbackend/orgs.go
> +	OrgRepositories(ctx context.Context, args *ListOrgRepositoriesArgs, org *types.Org, resolverFn func(database.DB, database.ReposListOptions, *ListOrgRepositoriesArgs) RepositoryConnectionResolver) (R
I think it's more readable this way

2021-11-08 13:14 UTC, rafax commented on cmd/frontend/graphqlbackend/orgs.go
> +	OrgRepositories(ctx context.Context, args *ListOrgRepositoriesArgs, org *types.Org, resolverFn func(database.DB, database.ReposListOptions, *ListOrgRepositoriesArgs) RepositoryConnectionResolver) (R
@kopancek "this way" - the way it's written, or with an extracted type?

2021-11-09 07:29 UTC, unknwon commented on cmd/frontend/graphqlbackend/org.go
> +	return EnterpriseResolvers.orgRepositoryResolver.OrgRepositories(ctx, args, o.org, func(db database.DB, opt database.ReposListOptions, args *ListOrgRepositoriesArgs) RepositoryConnectionResolver {
>This (passing a function) is done to avoid the need to make repositoryConnectionResolver public

What's preventing us from making it public? Personally I find callbacks are hard to reason about the code flow and the casue-and-effect.

2021-11-10 09:54 UTC, rafax commented on cmd/frontend/graphqlbackend/org.go
> +	return EnterpriseResolvers.orgRepositoryResolver.OrgRepositories(ctx, args, o.org, func(db database.DB, opt database.ReposListOptions, args *ListOrgRepositoriesArgs) RepositoryConnectionResolver {
Added a public "constructor" returning the public interface, removed function altogether, PTAL

2021-11-10 09:54 UTC, rafax commented on cmd/frontend/graphqlbackend/orgs.go
> +	OrgRepositories(ctx context.Context, args *ListOrgRepositoriesArgs, org *types.Org, resolverFn func(database.DB, database.ReposListOptions, *ListOrgRepositoriesArgs) RepositoryConnectionResolver) (R
Added a public "constructor" returning the public interface, removed function altogether, PTAL

2021-11-11 07:43 UTC, unknwon approved these changes
Changes LGTM.

2021-11-11 07:48 UTC, unknwon commented
@rafax Since you're off that I'm taking ownership of this PR moving forward.

Therefore I made following notable change to this PR (none of these can't be reverted if you don't agree):

I renamed `OrgRepositoryResolver` to be `EnterpriseResolver` because I think it is not low probability that we're going to have more features like listing org repositories that are not entirely /cleanly enterprise, which leaves space for us to easily add more methods to the `EnterpriseResolver` interface when the time comes.

---

@kopancek PTAL and pay more attention at changes around the actual functionality of listing org repos, in case anything broken here.

2021-11-11 16:50 UTC, kopancek requested changes

2021-11-11 16:50 UTC, kopancek commented on cmd/frontend/graphqlbackend/repositories.go
> +			repos, err := backend.NewRepos(r.db.Repos()).List(ctx, opt2)
What was the reason behind this change?

2021-11-11 16:50 UTC, kopancek commented on cmd/frontend/enterprise/enterprise.go
> +	EnterpriseResolver        graphqlbackend.EnterpriseResolver
I think the previous naming was more consistent with the conventions applied in `enterprise` folders.

E.g. the folder is `/enterprise/`, which should mean, that everything in the folder is related to enterprise stuff. Calling the resolver `EnterpriseResolver` does not tell me anything about what type of data it is returning. Whereas if I look at other resolver type names, it's immediately obvious.

In the future, when we add more functionality to this resolver, we can rename it accordingly. Now it seems to me like a premature generalisation.

```suggestion
	OrgRepositoryResolver        graphqlbackend. OrgRepositoryResolver
```

2021-11-11 16:50 UTC, kopancek commented on cmd/frontend/graphqlbackend/schema.graphql
> +    This can be used both for a user and an organization.
I vaguely remember fixing comments like this before. Great that you caught this in the schema doc 👍

2021-11-11 16:50 UTC, kopancek commented on cmd/frontend/graphqlbackend/enterprise.graphql
> +extend type Org {
Should this schema definition be in an `enterprise` folder as well? Otherwise it's still exposed in OSS version AFAIK

2021-11-12 09:17 UTC, unknwon commented on cmd/frontend/enterprise/enterprise.go
> +	EnterpriseResolver        graphqlbackend.EnterpriseResolver
Makes sense! I'll revert the rename.

2021-11-12 09:18 UTC, unknwon commented on cmd/frontend/graphqlbackend/repositories.go
> +			repos, err := backend.NewRepos(r.db.Repos()).List(ctx, opt2)
`backend.Repos` is an global variable, which does not respect our injected mock DB in tests, so we need to make it a way to accept the `r.db`.

2021-11-12 09:46 UTC, unknwon commented on cmd/frontend/graphqlbackend/enterprise.graphql
> +extend type Org {
Technically yes, but it is not possible within this PR because our graphqlbackend only lives in OSS right now, so referencing a file from enterprise will legally not allow anyone to make the OSS build (I think). This is something we should think about more holistically because the fact we're crazily injecting resolvers from enterprise to OSS is caused by not having an enterprise graphqlbackend that should instead wrapping on top of the OSS grapghqlbackend.

2021-11-16 09:38 UTC, unknwon commented on enterprise/cmd/frontend/internal/orgrepos/init.go
> +func Init(ctx context.Context, db dbutil.DB, _ conftypes.UnifiedWatchable, _outOfBandMigrationRunner *oobmigration.Runner, enterpriseServices *enterprise.Services, observationContext *observation.Con
```suggestion
func Init(ctx context.Context, db dbutil.DB, _ conftypes.UnifiedWatchable, _ *oobmigration.Runner, enterpriseServices *enterprise.Services, observationContext *observation.Context) error {
```

Seems overlooked?

2021-11-16 14:22 UTC, rafax commented on cmd/frontend/graphqlbackend/repositories.go
> +			repos, err := backend.NewRepos(r.db.Repos()).List(ctx, opt2)
@kopancek is this good to resolve?

2021-11-17 09:22 UTC, kopancek approved these changes

2021-11-17 09:53 UTC, merged