signup message small screens refactor
sourcegraph/sourcegraph pull request #27378
Opened 2021-11-10 18:33 UTC by pidoxy

closes #25216 
The fix

![localhost_3080_search_q=context_global+repo_%5Egithub%5C com_sourcegraph_sourcegraph%24+file_highlight scss+type_diff patternType=literal case=yes](https://user-images.githubusercontent.com/56538561/141172559-6d777c49-bdd4-4f03-8bf7-69c14454a3e4.png)

the issue
![issue](https://user-images.githubusercontent.com/56538561/141170080-cd9f36ed-cbb2-4662-b6e4-267101e4e412.png)

In the image above I placed the image at the top and centered the text on small screens, I thought of justifying the text and placing the image beside the heading but thought it looked better this way

@valerybugakov please review

2021-11-15 18:07 UTC, vanesa commented
@cla-bot check

2021-11-15 18:12 UTC, vanesa commented
@cla-bot check

2021-11-16 08:46 UTC, limitedmage commented
@marisak  or @rrhyne  can you take a look please and see if the suggested design for this is OK?

2021-11-16 08:49 UTC, limitedmage commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                            className="btn btn-primary col-md-3 col-12"
Can you post a screenshot of how this looks in the larger size? Not sure if using Bootstrap's columns is the right fix here as the original design is not based on columns. Let's wait and see what our design team suggests.

2021-11-16 08:57 UTC, pidoxy commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                            className="btn btn-primary col-md-3 col-12"
This is what it looks like on tablet screens, laptop screens, and large desktop screens @limitedmage 

![localhost_3080_search_q=context_global+repo_%5Egithub%5C com_sourcegraph_sourcegraph%24+file_highlight scss+type_diff patternType=literal case=yes (1)](https://user-images.githubusercontent.com/56538561/141954104-94b94768-4d6f-4d8e-8f34-d02ced447a55.png)

![localhost_3080_search_q=context_global+repo_%5Egithub%5C com_sourcegraph_sourcegraph%24+file_highlight scss+type_diff patternType=literal case=yes](https://user-images.githubusercontent.com/56538561/141954112-82d80057-f0b0-43a2-bbdf-57b97f075356.png)

![localhost_3080_search_q=context_global+repo_%5Egithub%5C com_sourcegraph_sourcegraph%24+file_highlight scss+type_diff patternType=literal case=yes (2)](https://user-images.githubusercontent.com/56538561/141954149-c9d74e51-18d4-4b7f-af30-9b75d6e72752.png)

2021-11-16 09:14 UTC, limitedmage commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                            className="btn btn-primary col-md-3 col-12"
Yeah, this doesn't look right, it should look the same as the original before the change. I don't think Bootstrap columns is the right way to go here. Can you try fixing this with @media CSS instead? You should use `@media (--md-breakpoint-down)` for this.

2021-11-16 09:16 UTC, pidoxy commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                            className="btn btn-primary col-md-3 col-12"
ok

2021-11-16 22:35 UTC, rrhyne commented
The small size design looks awesome and design is happy with the change! Nice work @pidoxy and thanks for the contribution. 

The larger size should probably use the full-size styling as @limitedmage  suggests.

2021-11-18 07:56 UTC, pidoxy commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                            className="btn btn-primary col-md-3 col-12"
Hi @limitedmage , I'm sorry for the delayed response

I had this after using @media (--md-breakpoint-down) but it's slightly different because of the layout change(flex), the space between the icon and the text is a little more here, the button is where it was, if it should be the exact same then I'd need to do two layouts using what was formerly there as display only for desktop screens and the one I did for mobile screens only

Is this fine? or should I do the latter suggestion?
<img width="1016" alt="Screenshot 2021-11-18 at 08 52 03" src="https://user-images.githubusercontent.com/56538561/142374847-3f4f1366-ed08-4a83-9d99-b45906ce9e67.png">


![localhost_3080_search_q=context_global+repo_%5Egithub%5C com_sourcegraph_sourcegraph%24+file_highlight scss+type_diff patternType=literal case=yes](https://user-images.githubusercontent.com/56538561/142373647-a72aa67e-69fe-4877-b0da-1c09b46ff825.png)

2021-11-23 01:25 UTC, vanesa commented
Hi @pidoxy thank you for your contribution! Just wanted to share with you that @limitedmage is currently on vacation and will be returning next week. She'll be able to address your comments then.

2021-11-29 23:24 UTC, limitedmage requested changes
Thanks for updating your PR! I've suggested a few extra changes that keep the same idea of your original code but simplify things a bit. I also changed the small screen view a bit to add some spacing. Here's how it looks:

![image](https://user-images.githubusercontent.com/206864/143958199-ad092356-4f7d-4f1f-99da-fd1f69913fc2.png)

Let me know what you think :)

2021-11-29 23:24 UTC, limitedmage commented on client/web/src/search/results/StreamingSearchResults.module.scss
> +        }
```suggestion
```

2021-11-29 23:24 UTC, limitedmage commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                        <div className={classNames('my-3 w-10 col-md-1', styles.streamingSearchResultsCtaIcon)}>
```suggestion
                    <div className="card my-2 mr-3 d-flex p-3 flex-md-row flex-column align-items-center">
                        <div className="mr-md-3">
```

2021-11-29 23:24 UTC, limitedmage commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                        <div className="col-md-7 px-md-0 text-md-start">
```suggestion
                        <div className="flex-1 my-md-0 my-2">
```

2021-11-29 23:24 UTC, limitedmage commented on client/web/src/search/results/StreamingSearchResults.tsx
> +                            className="btn btn-primary col-md-3 col-12"
```suggestion
                            className="btn btn-primary"
```

2021-11-30 18:03 UTC, pidoxy commented
Hi, @limitedmage this is very fine

2021-11-30 18:29 UTC, pidoxy commented
> Hi, @limitedmage this is very fine

should I push the changes or you'd do that from your end?

2021-11-30 19:31 UTC, limitedmage approved these changes

2021-11-30 19:31 UTC, merged

2021-11-30 19:32 UTC, limitedmage commented
@pidoxy Thanks for your contribution!! I've merged it into the main codebase.

2021-11-30 19:50 UTC, pidoxy commented
> @pidoxy Thanks for your contribution!! I've merged it into the main codebase.

thank you @limitedmage

2021-11-30 19:52 UTC, pidoxy commented
I have another PR, could you please help me review it @limitedmage ? it's PR #28106

2021-11-30 22:00 UTC, limitedmage commented
@pidoxy That PR is in code outside of my area of expertise, the other reviewers should be able to give much better feedback than I can.

2021-11-30 22:40 UTC, pidoxy commented
Ok, thank you