add/remove insight from dashboard
sourcegraph/sourcegraph pull request #27397
Opened 2021-11-11 04:30 UTC by unclejustin

Implements add/remove insights to/from dashboard functionality in the new graphql api

Closes https://github.com/sourcegraph/sourcegraph/issues/27218

2021-11-11 14:41 UTC, vovakulikov approved these changes
LGTM. Very creative solution due to lack of API query ids filters.

2021-11-11 14:41 UTC, vovakulikov commented on client/web/src/enterprise/insights/core/backend/code-insights-gql-backend.ts
> +        // Get array of added insight view ids
We also could add some check at the beginning of this logic and add an early return in case if a user hasn't changed anything about insights in a dashboar

2021-11-11 14:49 UTC, vovakulikov requested changes
Just realized that we also should add (and I think this is important for this mutation) cache modifications (`cache.modify()`). Like if the user removed insights from the dashboard we should remove these insight views from the dashboard without reloading the dashboard page. 

I made some refactoring around these insights fetching for dashboards here https://github.com/sourcegraph/sourcegraph/pull/27431

I think it makes sense to merge this https://github.com/sourcegraph/sourcegraph/pull/27431 first and after that add cache modification and merge this PR.

2021-11-11 14:51 UTC, vovakulikov commented on client/web/src/enterprise/insights/core/backend/code-insights-gql-backend.ts
> +                        ${addInsightToDashboardMutation}
Usually, we don't need to update the cache manually here cause Apollo can do that automatically if we include `insightIds` in the dashboard result after updateInsightsDashboard mutation (first mutation in this block) . But I'm not sure that BE will return correct `insightIds` cause addInsightToDashboardMutation and removeInsightViewFromDashboardMutation can be run before or after updateInsightsDashboard mutation.

2021-11-11 15:06 UTC, vovakulikov commented on client/web/src/enterprise/insights/core/backend/code-insights-gql-backend.ts
> +                        ${addInsightToDashboardMutation}
So in case if we have this query 

```
mutation UpdateDashboard($id: ID!, $input: UpdateInsightsDashboardInput!) {
   updateInsightsDashboard(id: $id, input: $input) {
      dashboard {
         id,
         title,
         views {
            nodes {
               id,
               presentation {}
               ...
            }
         }
      }
   }
   ${addInsightToDashboardMutation}
   ${removeInsightViewFromDashboardMutation}
}
```

where `addInsightToDashboardMutation` and `removeInsightViewFromDashboardMutation` are changing dashboard views list @CristinaBirkel @coury-clark can we say that result from updateInsightsDashboard mutation will be always correct (by correct I mean that all insight from `removeInsightViewFromDashboardMutation ` won't be there and insights from `addInsightToDashboardMutation` always will be there

2021-11-12 04:34 UTC, unclejustin commented
@vovakulikov I could not get this to work. It throws errors about `this` being undefined so I'm setting it as draft and we can sync up later.

2021-11-12 18:43 UTC, merged