[SG-26305] web: codemod `web/repo/commits` `web/repo/RepoRevisionSidebar.tsx` `web/repo/GitReference.tsx` components
sourcegraph/sourcegraph pull request #27480
Opened 2021-11-12 03:39 UTC by gitstart-sourcegraph

## Descriptions
 
 In process of migration from global CSS to [CSS modules](https://docs.sourcegraph.com/dev/background-information/web/styling#css-modules) using the [codemon](https://github.com/sourcegraph/codemod/tree/main/src/transforms/globalCssToCssModule) with some small manual fixes

## Refs
 
- [SG Issue](https://github.com/sourcegraph/sourcegraph/issues/26305)
- [Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-26305)

## Success criteria
 
The stylesheets in the following directories are converted to CSS modules.
 
- client/web/src/repo/commits
- client/web/src/repo/RepoRevisionSidebar.tsx 
- client/web/src/repo/GitReference.tsx

2021-11-15 16:50 UTC, valerybugakov requested changes

2021-11-15 16:50 UTC, valerybugakov commented on client/web/src/repo/GitReference.tsx
> -            className={classNames('git-ref-node list-group-item', className)}
The related end-to-end test should be updated.

https://github.com/sourcegraph/sourcegraph/blob/97666529a66da11e73a8b357f0b8cd6165963402/client/web/src/end-to-end/end-to-end.test.ts#L958

2021-11-17 02:54 UTC, gitstart-sourcegraph commented on client/web/src/repo/GitReference.tsx
> -            className={classNames('git-ref-node list-group-item', className)}
@valerybugakov Updated PR to replace the remaining `.git-ref-node` class usages in test

2021-11-18 16:42 UTC, valerybugakov approved these changes

2021-11-18 16:46 UTC, merged