shared: codemod shared/symbols shared/notifications shared/extensions…
sourcegraph/sourcegraph pull request #27488
Opened 2021-11-12 08:28 UTC by gitstart-sourcegraph

## Descriptions

This PR results from the [global-css-to-css-modules](https://github.com/sourcegraph/codemod/tree/main/src/transforms/globalCssToCssModule) codemod application with some manual fixes, caused by the usage of global CSS classes tied to a React component in other parts of the codebase

## Refs

- [SG Issue](https://github.com/sourcegraph/sourcegraph/issues/27077)
- [Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27077)

## Success criteria

The stylesheets in the following directories are converted to CSS modules.

- client/shared/src/components/ResultContainer.tsx
- client/shared/src/symbols
- client/shared/src/notifications
- client/shared/src/extensions

2021-11-12 10:11 UTC, gitstart-sourcegraph commented
Hello @valerybugakov  kindle help review Spec, and make suggestions on improvements. thanks

2021-11-16 17:33 UTC, valerybugakov requested changes

2021-11-18 16:55 UTC, gitstart-sourcegraph commented on client/shared/src/components/ResultContainer.scss
> -.result-container {
@valerybugakov Thanks, updated PR to convert that global css class to module css class

2021-11-22 15:45 UTC, gitstart-sourcegraph commented
Hi @valerybugakov kindly help review changes here.

2021-11-29 07:19 UTC, valerybugakov approved these changes

2021-11-29 09:29 UTC, merged