Create add_remove_local_repositories how to guide
sourcegraph/sourcegraph pull request #27505
Opened 2021-11-12 14:31 UTC by david-sandy

Created a how to guide for adding or removing repositories from the local development environment.

2021-11-16 16:05 UTC, kopancek approved these changes
LGTM. Added a suggestion with typo fix.

2021-11-16 16:05 UTC, kopancek commented on doc/dev/how-to/add_remove_local_repositories.md
> +To add or remove repositories, change the entires in the **repos** array:
```suggestion
To add or remove repositories, change the entries in the **repos** array:
```

2021-11-17 12:27 UTC, mrnugget requested changes
Please remove the tokens and rotate them in `dev-private` and let people know in #dev-announce.

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +      "token": "f189fe46ca1901b4988936cbc671f8305715ed73", // unprivileged sqs-test user
Uhm. I don't think this should be in here?

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +      "token": "1ec8973c1debb3232468b514b1a850dba87ee29a",
Same?

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +This file is located here: `/dev-private/enterprise/dev/external-services-config.json` on your local development environment.
I think this could be misleading, since `/dev-private` is a clone of the `dev-private` repository. I'd rephrase this to say something like "It's in the clone of `dev-private"

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +```
I don't think it's worth it to showcase this array again, without any changes.

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +```
One line needs to be removed

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +```
I don't think it's worth it to showcase this array again, without any changes.

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +**BEFORE** you make any changes, it is **strongly recommended** that you make a local backup of this file so that you can easily revert any changes if needed.
Do we need to call this out? It's in `git`, so they can always reclone the repository?

2021-11-17 12:27 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +      "repositoryQuery": ["affiliated"],
This one here is the killer, btw. This is what causes a lot of clones. I'd call out this line.

2021-11-18 15:15 UTC, david-sandy commented on doc/dev/how-to/add_remove_local_repositories.md
> +This file is located here: `/dev-private/enterprise/dev/external-services-config.json` on your local development environment.
That's a good point!  We don't want any confusion.

2021-11-18 15:15 UTC, david-sandy commented on doc/dev/how-to/add_remove_local_repositories.md
> +```
Gotcha!

2021-11-18 15:16 UTC, david-sandy commented on doc/dev/how-to/add_remove_local_repositories.md
> +**BEFORE** you make any changes, it is **strongly recommended** that you make a local backup of this file so that you can easily revert any changes if needed.
That is true, but, I was thinking of the scenario where they could have made additional changes before this one.  Is that a valid scenario?

2021-11-18 15:17 UTC, david-sandy commented on doc/dev/how-to/add_remove_local_repositories.md
> +      "repositoryQuery": ["affiliated"],
Do you mean "repositoryQuery": ["affiliated"]?

2021-11-18 15:32 UTC, mrnugget commented on doc/dev/how-to/add_remove_local_repositories.md
> +      "repositoryQuery": ["affiliated"],
Yep, see here: https://docs.sourcegraph.com/admin/external_service/github#configuration

2021-11-19 12:20 UTC, david-sandy commented on doc/dev/how-to/add_remove_local_repositories.md
> +      "repositoryQuery": ["affiliated"],
I see!  Great point!  Gold star for you!

2021-11-19 12:22 UTC, david-sandy commented on doc/dev/how-to/add_remove_local_repositories.md
> +```
Check.

2021-11-19 13:04 UTC, david-sandy commented on doc/dev/how-to/add_remove_local_repositories.md
> +      "repositoryQuery": ["affiliated"],
I split the changes into two sections, one for the repos array and one for the repositoryQuery value.

2024-01-10 20:35 UTC, eseliger commented
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

2024-01-10 20:35 UTC, closed without merging