ci: add annotation api
sourcegraph/sourcegraph pull request #27897
Opened 2021-11-18 10:10 UTC by asdine

This adds a script that allows buildkite steps to easily add a annotation when an error occurs.

Related to #26071 

Co-authored-by: Jean Hadrien Chabran <jh@chabran.fr>

2021-11-18 13:57 UTC, jhchabran approved these changes

2021-11-18 13:57 UTC, jhchabran commented on dev/check/shellcheck.sh
> +cd "$(dirname "${BASH_SOURCE[0]}")"/../.. || exit
The check would fail silently otherwise if it could not cd to that folder (as we removed the `trap`)

```suggestion
cd "$(dirname "${BASH_SOURCE[0]}")"/../.. || exit 1
```

2021-11-18 13:57 UTC, jhchabran requested changes
Really small thing that we missed! 

See my comment https://github.com/sourcegraph/sourcegraph/pull/27897/files#r752263483

2021-11-18 15:58 UTC, jhchabran approved these changes
💪:shell: 

See the comments, Approving to not have to re-review again!

2021-11-18 15:58 UTC, jhchabran commented on dev/ci/annotate.sh
> +set -ex
@asdine we forgot to remove that `x`, it's going to be noisy otherwise. 
```suggestion
set -e
```

2021-11-18 15:58 UTC, jhchabran commented on dev/check/shfmt.sh
> +EXIT_CODE=$?
```suggestion
set +e
OUT=$(shfmt -d .)
EXIT_CODE=$?
set -e
```

2021-11-18 15:58 UTC, jhchabran commented on dev/check/shfmt.sh
> +cd "$(dirname "${BASH_SOURCE[0]}")"/../.. || exit
```suggestion
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"/../..
```

2021-11-18 16:14 UTC, merged

2021-11-18 17:44 UTC, bobheadxi reviewed
This seems to go a bit against the `sg` mantra of _removing_ bash scripts, rather than adding more

I also envisioned that this would be in the generator rather than something that has to be explicitly called like this, which feels a bit complicated

2021-11-18 18:23 UTC, jhchabran commented
> This seems to go a bit against the `sg` mantra of _removing_ bash scripts, rather than adding more

Agreed. It's more of a prototype than anything else though, if that proves to be useful, it makes sense to get it back in `sg` or in the pipeline generator. 

> I also envisioned that this would be in the generator rather than something that has to be explicitly called like this, which feels a bit complicated

Yeah, it presently is a bit complicated, which is part of the discovery work on this. The original idea was to simply write the logs into a file, that is then read to create the annotation. The problem with that it's not working when you have concurrent commands being run. 

To explain our reasoning: 

Basically, the problem is as following, either we make the log output better, which is a lot of work, and would potentially make it harder to debug what happened, or we selectively annotate content that we know for sure is relevant to the user. 

There is a lot of value with the former, but the latter yields immediate feedback on what we could be doing with those annotations.

2021-11-19 03:04 UTC, bobheadxi commented
> The original idea was to simply write the logs into a file, that is then read to create the annotation. The problem with that it's not working when you have concurrent commands being run.

Allowing an entire directory for annotation output might be a workaround here, where different parts of the command can output things to different files which could then get selectively pulled out to annotations