Add CodeInsightsGQLApiEnabled to jscontext.go
sourcegraph/sourcegraph pull request #27919
Opened 2021-11-18 16:52 UTC by vovakulikov

This PR adds code insights gql feature flag to jscontext

2021-11-18 16:58 UTC, coury-clark approved these changes

2021-11-18 16:58 UTC, coury-clark commented on internal/conf/computed.go
> +	return true
```suggestion
	return enabled
```

2021-11-18 16:59 UTC, coury-clark requested changes
The truthiness of the frontend variable is flipped

2021-11-18 16:59 UTC, coury-clark commented on internal/conf/computed.go
> +func CodeInsightsGQLApiEnabled() bool {
This is backwards from the environment variable - the environment variable enables settings storage, not the GQL api

2021-11-23 10:00 UTC, vovakulikov commented
@CristinaBirkel can you help me with failing CI, I've changed the env setting flag logic for enabling GQL API feature flag in JSContext and pulled changes from the feature branch and now it seems like I've got some error about setting migration

2021-11-24 14:59 UTC, CristinaBirkel approved these changes
Ah, you don't need to worry about the failing CI--it's not you, it's the feature branch. :)

2021-11-29 14:46 UTC, merged