Add browser extension secure support for private repositories on cloud
sourcegraph/sourcegraph pull request #28387
Opened 2021-12-01 09:53 UTC by erzhtor

2021-12-02 10:20 UTC, indradhanush requested changes
Did a first pass. Could you please split this into three separate PRs to make changes incrementally:

1. PR with DB migration changes
2. PR with backend changes to the API stacked up on top of PR#1
3. PR with frontend changes stacked up on PR#2.

This would also make it easier for reviewers to move through PRs faster. :slightly_smiling_face:

2021-12-02 10:20 UTC, indradhanush commented on cmd/frontend/backend/repos.go
> +func (s *repos) GetByHashedName(ctx context.Context, name api.HashedRepoName) (_ *types.Repo, err error) {
Using `(_ *types.Repo, err error)` in the return type is sending a bit of a mixed message to me as a reader. We should either use named return types or not and in this case it appears like we're trying to do both. It might be easier to just return `(*types.Repo, error)` and I'd expect rest of the code to continue working.

2021-12-02 10:20 UTC, indradhanush commented on cmd/frontend/backend/repos.go
> +}
If we don't need to do any custom error handling, we could directly do:
`return s.store.GetHashedName` here.

2021-12-02 10:20 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +}) (*RepositoryResolver, error) {
Is there a reason the `HashedName *string` needs to be wrapped inside a `struct`? Could we do this instead:

```
func (r *schemaResolver) PureRepository(ctx context.Context, hashedName *string)
```

2021-12-02 10:20 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
Why `pureRepository`? The name feels a bit misleading, especially as we're using `hashedName` everywhere else.

2021-12-02 13:35 UTC, erzhtor commented on cmd/frontend/backend/repos.go
> +func (s *repos) GetByHashedName(ctx context.Context, name api.HashedRepoName) (_ *types.Repo, err error) {
I see, I was following the same convention from https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/backend/repos.go#L74. 
Also, `&err` seems to be used in the trace below. Let me know if you still think that we should still change this.

2021-12-02 13:37 UTC, erzhtor commented on cmd/frontend/backend/repos.go
> +}
As mentioned https://github.com/sourcegraph/sourcegraph/pull/28387#discussion_r761096857, I think, we trace error

2021-12-02 13:40 UTC, indradhanush commented on cmd/frontend/backend/repos.go
> +func (s *repos) GetByHashedName(ctx context.Context, name api.HashedRepoName) (_ *types.Repo, err error) {
Ah. Good catch! That makes sense and we should continue to use the named return parameters.

2021-12-02 13:41 UTC, indradhanush commented on cmd/frontend/backend/repos.go
> +}
Fair enough. In this case I think we can do `return repo, err` directly and won't need the `if` check.

2021-12-02 13:56 UTC, erzhtor commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +}) (*RepositoryResolver, error) {
I think, it is requirement for the schema resolvers, otherwise, I'm getting:
```
fatal: expected struct or pointer to struct, got *string (hint: missing `args struct { ... }` wrapper for field arguments?)
[enterprise-frontend]   used by (*graphqlbackend.schemaResolver).PureRepository
[enterprise-frontend]   used by (*graphqlbackend.schemaResolver).Root
```

2021-12-02 13:59 UTC, erzhtor commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
The reasoning was that `pureRepository` is exactly the same as `repository` resolver, meaning that it returns RepositoryResolver, but the difference is that it doesn't auto-clone under the hood as it happens for `repository`. 
I couldn't find a better naming for it, let me, please, know, if you have any naming suggestions?

2021-12-02 14:06 UTC, erzhtor commented
Thanks for the review, @indradhanush!

> Did a first pass. Could you please split this into three separate PRs to make changes incrementally:
> 
> 1. PR with DB migration changes
> 2. PR with backend changes to the API stacked up on top of PR#1
> 3. PR with frontend changes stacked up on PR#2.

Do you think, we can join 1st and 2nd options as a single PR, since the API won't be used until we release browser extension anyways? Otherwise, I'm just worried, that this splitting will block sequencial PRs from merging, until we release the previous ones.
-- 
A couple of additional questions, will appreciate if you could help with the answers:
1. Also, do you know the frequency of Sourcegraph Cloud releases?
2. Are those migrations run automatically when deployed? (I assume so, but want to clarify)

2021-12-03 13:05 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +}) (*RepositoryResolver, error) {
TIL! That makes sense. Thank you!

2021-12-03 13:19 UTC, indradhanush commented
> Do you think, we can join 1st and 2nd options as a single PR, since the API won't be used until we release browser extension anyways? Otherwise, I'm just worried, that this splitting will block sequencial PRs from merging, until we release the previous ones.

I thought I had added a comment about the migration in the review but can't seem to find it now. My main concern is that the alter table command is going to do a table rewrite. Our `repo` table is by far the largest table and without any benchmarks I'd prefer to err on the side of caution. I'm worried that this rewrite could take longer and incur a transaction timeout leading to manual intervention. As a result the smaller the subset of changes, the better IMO.

I understand that this does slow you down a bit, but it might be better for us to make recovery in the case of a failed DB migration as friction less as possible. 

Having said that, could you ask another pair of eyes (maybe in #dev-databases on Slack) to look and analyse the upcoming migration with this change? That would add more confidence and if they feel comfortable with it, let's go ahead and do part 1 and 2 together. Especially since it's an internal API that wont be used immediately. Also if we do go ahead with this, could you please also add a note as a headsup in that PR related to this?

> Also, do you know the frequency of Sourcegraph Cloud releases?

The frontend service on Cloud is released every 1 hour. But `repo-updater` and `gitserver` are deployed once a day.
    
> Are those migrations run automatically when deployed? (I assume so, but want to clarify)

Yes. The migrations are run automatically as part of the `sourcegraph-frontend` deployment.

2021-12-06 13:43 UTC, tsenart commented on cmd/frontend/graphqlbackend/schema.graphql
> +    pureRepository(
What's the reasoning for this query name? Also, could we instead add another parameter `hashedName` to `repositoryRedirect`?

2021-12-06 13:44 UTC, tsenart commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
I'd reuse `repositoryRedirect`, extending it with the necessary arguments to satisfy the new requirements.

2021-12-06 21:12 UTC, erzhtor commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
I like it. However, this was a suggestion from the repo-management team to create a new schema instead of updating existing `repository/repositoryRedirect` resolvers. WDYT @indradhanush, would extending `repositoryRedirect` be okay?

P.S: FYI, also, `repositoryRedirect` automatically tries to clone a repository if it doesn't exist in Sourcegraph. However, I can update logic to not clone if only hashedRepoName is passed.

2021-12-06 21:13 UTC, erzhtor commented on cmd/frontend/graphqlbackend/schema.graphql
> +    pureRepository(
https://github.com/sourcegraph/sourcegraph/pull/28387#discussion_r761117914

2021-12-06 21:46 UTC, erzhtor commented
Hey, @indradhanush, @tsenart, thank you for the reviews! 

I've updated PR by:
- Moved browser extension changes into a separate https://github.com/sourcegraph/sourcegraph/pull/28621 PR
- Updated migration to use SQL expression index instead of generated column

I would appreciate it if you could take a look at it again?

P.S: I would also be grateful if you could help/pair on fixing Go failing tests or share some docs/hints.

2021-12-07 11:08 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
> P.S: FYI, also, repositoryRedirect automatically tries to clone a repository if it doesn't exist in Sourcegraph Cloud. However, I can update logic to not clone if only hashedRepoName is passed.

My intention was to avoid custom conditional actions on the existing API and end up with mangled code. 

I still think a separate API is a better idea here. Regarding the name, how about `hashedRepository`? What do you think  @erzhtor?

2021-12-07 11:10 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
To clarify, if you'd like to go ahead and make the changes to the existing API and think that would be simpler, I'm happy to accept that. I will leave that call on you.

2021-12-07 11:36 UTC, tsenart commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
> My intention was to avoid custom conditional actions on the existing API and end up with mangled code.

I don't think we would end-up with mangled code necessarily. It's easier to have one place where the same thing happens, than many, even if that thing can happen with different arguments.

2021-12-07 11:46 UTC, tsenart commented on internal/database/repos.go
> +			lowerHashedNames[i] = strings.ToLower(name)
We're lowering the hashed name instead of the name here which is a bug. If we pass the hashes to the backend, the normalization needs to happen on the client side.

2021-12-07 11:46 UTC, tsenart commented on migrations/frontend/1528395953_add_repo_hashed_name_index.up.sql
> +CREATE INDEX IF NOT EXISTS repo_hashed_name_idx ON repo USING BTREE (encode(sha256(lower(name)::bytea), 'hex'));
It's more efficient in terms of storage and memory usage of the DB to index on a smaller data type, so let's avoid the encoding to `hex` since it's not necessary. On the query side, we'll have to `decode('%s', 'hex')`. Additionally, since this is now a single statement, we can add back the `CONCURRENT` keyword right?

```
CREATE INDEX CONCURRENTLY IF NOT EXISTS repo_hashed_name_idx ON repo USING BTREE (sha256(lower(name)::bytea));

2021-12-07 11:46 UTC, tsenart commented on internal/database/repos.go
> +	if len(opt.HashedNames) > 0 {
It doesn't seem like we ever pass more than one hashed name at once so we it'd probably simplify the code to support a single one.

2021-12-07 12:03 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
> I don't think we would end-up with mangled code necessarily. It's easier to have one place where the same thing happens, than many, even if that thing can happen with different arguments.

Hmm, fair enough. Let's go with the modifications to `repositoryRedirect` then. 

cc: @erzhtor

2021-12-07 12:12 UTC, erzhtor commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
Hey, @indradhanush, @tsenart, I'm updating to use the existing `repositoryRedirect` and wanted to clarify should I add this parameter to `repository` resolver as well or not?

2021-12-07 12:28 UTC, erzhtor commented on internal/database/repos.go
> +	if len(opt.HashedNames) > 0 {
Yes, for now, there is always only a single hashed name parameter. 

I can update to use a single HashedName (and it will be even simpler I think), it will be just not consistent with the rest of the RepoListOptions, which accepts an array of IDs, Names, etc. WDYT?

2021-12-07 12:47 UTC, tsenart commented on internal/database/repos.go
> +	if len(opt.HashedNames) > 0 {
> which accepts an array of IDs, Names, etc. WDYT?

I think it's fine to differ here and introduce a list once it's used / needed.

2021-12-07 13:04 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	{"Query", "pureRepository"}:                 {},
> I'm updating to use the existing repositoryRedirect and wanted to clarify should I add this parameter to repository resolver as well or not?

@erzhtor I don't think so, since the idea is to use `repositoryRedirect` as a proxy to find a repo by hashed name. Additionally for the requirements you won't need to use the `repository` resolver to query by hashed name I think? If you do, then by all means go for it. But overall my understanding so far is that just the changes to `repositoryRedirect` is fine. 

> P.S: I know that we can use repositoryRedirect directly, I just wanted to know if there is a convention for these resolvers to support the parameters.

Not that I'm aware of. The only resource about developing the GQL API I know about is here: https://docs.sourcegraph.com/dev/background-information/graphql_api

If you're unsure, it might be a good question for #dev-chat on Slack. :slightly_smiling_face:

2021-12-07 14:18 UTC, erzhtor commented on migrations/frontend/1528395953_add_repo_hashed_name_index.up.sql
> +CREATE INDEX IF NOT EXISTS repo_hashed_name_idx ON repo USING BTREE (encode(sha256(lower(name)::bytea), 'hex'));
> Additionally, since this is now a single statement, we can add back the CONCURRENT keyword, right?

Yep, I thought I pushed it. Fixed. Thanks! 👌 

> it's more efficient in terms of storage and memory usage of the DB to index on a smaller data type, so let's avoid the encoding to hex since it's not necessary. On the query side, we'll have to decode('%s', 'hex').

I didn't know how to construct `decode` for an array of hashed names, so used this approach. But since decided to go with the single hashed name where clause, will update to use decode instead of encoding in an index.

2021-12-07 15:30 UTC, tsenart approved these changes
LGTM. Do you still need to make sure that we don't try to clone repos when given via hashed name?

Also, happy to pair tomorrow to run this migration in production ahead of time.

2021-12-07 16:22 UTC, erzhtor commented
> LGTM. Do you still need to make sure that we don't try to clone repos when given via hashed name?

Thanks for the reviews! I've made it to not clone if only hashed name passed, which I thought will work. But I've updated not clone even when passed other name/cloneURL parameters just to make it safer.

> Also, happy to pair tomorrow to run this migration in production ahead of time.

Thank you, I would be grateful for that! 👍

2021-12-07 16:37 UTC, tsenart commented on cmd/frontend/backend/repos.go
> +func (s *repos) GetByHashedName(ctx context.Context, name api.RepoHashedName) (_ *types.Repo, err error) {
Do we need this method? It seems like a pass-through. I'd simplify and call `s.store.GetByHashedName` directly in the resolver.

2021-12-07 17:11 UTC, erzhtor commented on cmd/frontend/backend/repos.go
> +func (s *repos) GetByHashedName(ctx context.Context, name api.RepoHashedName) (_ *types.Repo, err error) {
I was following the rest of the codebase logic and added it here. But you're right, thank you. Updated!

2021-12-08 02:00 UTC, indradhanush approved these changes

2021-12-08 02:00 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +	HashedName *string
Nit: Could we pull this struct out into a definition like:

```go
type repositoryRedirectArgs struct {
    Name       *string
    CloneURL   *string
    HashedName *string
}
```

Now that the struct has expanded a bit, it might make the code slightly cleaner.

2021-12-08 02:00 UTC, indradhanush commented on cmd/frontend/graphqlbackend/schema.graphql
> +        Query the repository by hashed name.
It maybe worthwhile adding that the `hashedName` is the SHA256 checksum of the absolute repo name in lower case and provide an example using `github.com/sourcegraph/sourcegraph`.

2021-12-08 02:00 UTC, indradhanush commented on internal/database/repos.go
> +//
```suggestion
```

2021-12-08 02:00 UTC, indradhanush commented on internal/database/repos.go
> +//
```suggestion
//
```
```suggestion
```

2021-12-08 02:01 UTC, indradhanush commented
>   > Also, happy to pair tomorrow to run this migration in production ahead of time.
>
> Thank you, I would be grateful for that! +1

I might not be around to watch this (I would have loved to!), but I'll be curious to learn if we find out anything interesting from running this migration.

2021-12-08 09:10 UTC, erzhtor commented
@indradhanush, @tsenart, by the way, can you point out a place where we check if the user has access to see repository info or not (in graphqlbackend)? Is it done automatically somewhere in one place, or should it be part of each resolver?

P.S: I want to ensure that this hashed name access will follow the same permission checking rules, and the user will not be able to access other's private repositories.

2021-12-08 11:50 UTC, tsenart commented
> P.S: I want to ensure that this hashed name access will follow the same permission checking rules, and the user will not be able to access other's private repositories.

This is done in the `RepoStore` at the SQL level.

2021-12-08 11:52 UTC, tsenart commented on internal/database/repos.go
> +	HashedName *api.RepoHashedName
Why are we passing a pointer? Checking for zero value of empty string is more idiomatic if that zero value is not significant.

2021-12-08 13:01 UTC, erzhtor commented on internal/database/repos.go
> +	HashedName *api.RepoHashedName
I'm quite new to Golang and didn't know what is the best approach here. Thank you, updated https://github.com/sourcegraph/sourcegraph/pull/28387/commits/7eb23b96e2b830b280c0541f1f3a5dc772fb0176 .

2021-12-08 14:14 UTC, merged