codeintel: Instrument upload endpoint
sourcegraph/sourcegraph pull request #28382
Opened 2021-12-01 02:23 UTC by efritz

2021-12-01 22:43 UTC, eseliger approved these changes

2021-12-01 23:18 UTC, Strum355 requested changes
"quick" first pass review, will check again tomorrow :+1: really liking how its shaping up

2021-12-01 23:18 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +		uploadState, statusCode, err := h.constructUploadState(ctx, r)
```suggestion
		var state uploadState
		ctx, endObservation := h.operations.handleEnqueue.With(r.Context(), &err, observation.Args{})
		defer func() {
			fields := []log.Field{
				log.Int("statusCode", statusCode),
			}
			if state != uploadState{} {
				fields = append(
					fields,
					log.Int("upload.repositoryID", state.repositoryID),
					log.Int("upload.ID", state.uploadID),
					log.String("upload.commit", state.commit),
					log.String("upload.root", state.root),
					log.String("upload.indexer", state.indexer),
					log.Int("upload.indexID", state.associatedIndexID),
					log.Int("upload.numParts", state.numParts),
					log.Bool("upload.multipart", state.multipart),
					log.Bool("upload.suppliedIndex", state.suppliedIndex),
					log.Int("upload.index", state.index),
				)
			}
			endObservation(1, observation.Args{LogFields: fields})
		}()

		state, statusCode, err = h.constructUploadState(ctx, r)
```
you'll have to update the var name further down as well, I couldnt add a suggestion that far down :/ What do you think otherwise? I couldnt use `log.Object` to not include repo name & the fields are unexported, although we could export the ones we would want to log here and use `log.Object`?

2021-12-01 23:18 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_state.go
> +		// upload `identifier returned in this response.
```suggestion
		// upload identifier returned in this response.
```

2021-12-01 23:18 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler_multipart.go
> +	traceLog(log.Int("size", int(size)))
Just as a matter of cognitive load (and name collisions), I think itd be beneficial to have names e.g. `gzippedUploadSize`, particularly when `size` would refer to multiple things in a honeycomb dataset depending on the current op (single, multipart-non-final, multipart-final), and when `size` isnt _immediately_ obvious when looking at a trace :slightly_smiling_face:

2021-12-01 23:21 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/auth_github.go
> +	githubToken := query.Get("github_token")
This passes a boundary of abstraction: we wouldn't be able to add non-github tokens, or we'd have to accept them under `github_token` as well.

2021-12-01 23:21 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/auth_github.go
> +	githubToken := query.Get("github_token")
Ah right yea of course :+1:

2021-12-01 23:22 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +	return authMiddleware(http.HandlerFunc(handler.handleEnqueue), db, authValidators)
It's _only_ here though since this is a specific type of auth for an endpoint. This constructor is the only way you can create an upload handler.

2021-12-01 23:23 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +) {
I went back and forth on this a few times 😛

2021-12-01 23:24 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +		writeJSON(w, payload)
I can collapse these no prob.

2021-12-02 00:20 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +		uploadState, statusCode, err := h.constructUploadState(ctx, r)
Pushed a change related to this. See what you think. I don't know about `log.Object` so I have no opinion, will defer to you.

2021-12-02 14:17 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +			log.String("repositoryName", uploadState.repositoryName),
Should we still be logging repo name at any stage? This would additionally leak to honeycomb if/when we decide to instrument this section with honeycomb

2021-12-02 14:32 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/httpapi/upload_handler.go
> +			log.String("repositoryName", uploadState.repositoryName),
```suggestion
```

2021-12-02 15:30 UTC, Strum355 approved these changes

2021-12-02 15:30 UTC, merged