codemod browser-extension/after-install-page/AfterInstallPageContent browser-extension/options-menu/OptionsPage shared/code-hosts/*/style web/src/SourcegraphWebApp components to CSS modules
sourcegraph/sourcegraph pull request #28443
Opened 2021-12-02 04:09 UTC by gitstart-sourcegraph

## Description:
This PR results from the [global-css-to-css-modules codemod](https://github.com/sourcegraph/codemod/tree/main/src/transforms/globalCssToCssModule) application with some manual fixes, caused by the usage of global CSS classes tied to a React component in other parts of the codebase.
## Refs: 

- [SG Issue](https://github.com/sourcegraph/sourcegraph/issues/28261)

## Success criteria:

The stylesheets in the following directories are converted to CSS modules.

- [x]  client/browser/src/browser-extension/after-install-page/AfterInstallPageContent.scss
- [x] client/browser/src/browser-extension/options-menu/OptionsPage.scss
- [ ] client/browser/src/shared/code-hosts/*/style.scss
- [x] client/web/src/SourcegraphWebApp.scss — app__error and app__error-text classes.

2021-12-14 08:59 UTC, valerybugakov requested changes
@tjkandala, @erzhtor, could you take a look, please.

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/browser-extension/options-menu/components/OptionsPageContainer.module.scss
> +}
```suggestion
.options-page {
    width: 26rem;
    
    &--full {
        margin: 8rem auto;
    }
}
```

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/bitbucket-cloud/codeHost.ts
> +        actionItemPressedClassName: 'hover-overlay__action-item-pressed--bitbucket-cloud',
Let's omit this class since it doesn't add any styles to the element.
```suggestion
```

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/bitbucket-cloud/codeHost.ts
> +        actionItemPressedClassName: 'hover-overlay__action-item-pressed--bitbucket-cloud',
Also, it seems we can remove the `action-item` class from the `ActionItem` component here:

https://github.com/sourcegraph/sourcegraph/blob/2a30f0bacb7359cc2d0f1a1378d065dd6c5cfe91/client/shared/src/actions/ActionItem.tsx#L260-L266

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/app.scss
>  @import './shared/code-hosts/shared/HoverOverlay.scss';
It seems that we lost the styles defined in this file during the migration.
Let's convert it to a CSS module and inject `className` here.

https://github.com/sourcegraph/sourcegraph/blob/36477870e356d5be4843c7cade0610f7ef473554/client/browser/src/shared/code-hosts/shared/codeHost.tsx#L521-L523

```tsx
                <HoverOverlay
                    {...hoverOverlayProps}
                    {...codeHost.hoverOverlayClassProps}
                    className={classNames(styles.hoverOverlay, codeHost.hoverOverlayClassProps.className)}

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/bitbucket/codeHost.module.scss
> +    svg & {
Could you explain why do we need `&` after `svg`? This selector seems to be different from the previous version.

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/bitbucket/codeHost.module.scss
> +    :global(.no-results) {
Would it be possible to avoid using `:global()` here if we use CSS module generated class here? 

https://github.com/sourcegraph/sourcegraph/blob/36477870e356d5be4843c7cade0610f7ef473554/client/browser/src/shared/code-hosts/bitbucket/codeHost.tsx#L253

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/gerrit/codeHost.module.scss
> +    :global(.hover-overlay__contents) code {
This global class doesn't exist since we migrated the `HoverOverlay` component to CSS modules. 
We should use `hoverOverlayClassProps` here to provide styles specific to the code host:

https://github.com/sourcegraph/sourcegraph/blob/36477870e356d5be4843c7cade0610f7ef473554/client/browser/src/shared/code-hosts/gerrit/codeHost.ts#L381-L383

E.g., this style should use passed as `contentClassName`.

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/gerrit/codeHost.module.scss
> +    :global(.hover-overlay__close-button) {
The same comment applies to all `HoverOverlay` global classes here.

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/github/codeHost.module.scss
> +.command-palette-action-item--github {
Since these classes are in the CSS module, we don't need suffixes that ensure uniqueness.
Let's shorten them by removing repetitive parts. Applies to other scoped classes in this file.
```suggestion
.command-palette-action-item {
```

2021-12-14 08:59 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/phabricator/codeHost.module.scss
> +    :global(.icon--phabricator) {
It seems that it's Sourcegraph specific class name that can be scoped via CSS module and used here:

https://github.com/sourcegraph/sourcegraph/blob/36477870e356d5be4843c7cade0610f7ef473554/client/browser/src/shared/code-hosts/phabricator/codeHost.ts#L191-L201

2021-12-14 19:06 UTC, gitstart-sourcegraph commented on client/browser/src/shared/code-hosts/bitbucket/codeHost.module.scss
> +    svg & {
@valerybugakov sorry this slipped through our review, would undo change

2021-12-15 20:09 UTC, tjkandala approved these changes
Thanks! Manually tested on GitHub and it looks good cc @erzhtor

2021-12-15 20:57 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/bitbucket-cloud/codeHost.ts
> +        iconClassName: styles.iconBitbucketCloud,
Agree!
cc @gitstart-sourcegraph

2021-12-17 15:31 UTC, valerybugakov approved these changes
Looks good! Thank you for addressing all the comments.

Let's remove code-host suffixes from code-host-related CSS modules and convert classes from the BEM convention. It's a good merge after that. 

Please, double-check that PR doesn't contain any unnecessary changes similar to the one in `.github/teams.yml`.

2021-12-17 15:31 UTC, valerybugakov commented on .github/teams.yml
> +  - '@5h1ru'
It seems redundant.
```suggestion
```

2021-12-17 15:31 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/gerrit/codeHost.module.scss
> +.hover-overlay--gerrit {
Let's remove code host suffixes from CSS modules.
```suggestion
.hover-overlay {
```

2021-12-17 15:31 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/gerrit/codeHost.module.scss
> +.hover-overlay__contents code {
Let's convert classes from BEM notation to concise names because they are scoped automatically by CSS modules. Applies to other classes with `__` in the selector name.

```suggestion
.contents code {
```

2021-12-21 19:25 UTC, valerybugakov approved these changes
Thank you for addressing all comments!

2021-12-22 06:35 UTC, merged

2021-12-22 15:44 UTC, erzhtor commented
@gitstart-sourcegraph The after-install page seems to be broken after this PR: 
| Before | After |
| --: | :-- |
| ![image](https://user-images.githubusercontent.com/6717049/147118165-47ce516d-e623-48e8-81f3-b3e64b4932a5.png)|  ![image](https://user-images.githubusercontent.com/6717049/147118122-a1d922f3-b0da-4e43-b4ae-ba288a0f177f.png)