notebooks: add db store and get/create functions
sourcegraph/sourcegraph pull request #28535
Opened 2021-12-03 10:06 UTC by novoselrok

This PR adds a notebooks DB store and get/create functions with tests. It also adds validation functions for blocks. Since blocks are stored as JSON we have to ensure their validity before storing them in the DB.

The rest of the store functions will be added in a separate PR.

2021-12-03 15:25 UTC, camdencheek requested changes

2021-12-03 15:25 UTC, camdencheek commented on migrations/frontend/1528395947_notebooks.up.sql
> +    blocks JSONB DEFAULT '[]'::JSONB NOT NULL,
Maybe add a check constraint to this column? `constraint blocks_is_array check (jsonb_typeof(blocks) = 'array')`

2021-12-03 15:25 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +	After int32
Your notebook ID uses a `bigserial`, so I would expect `After` to be an `int64`. I realize that's awkward with the graphql layer only working with int32, but I think it's best for the database layer to use types as consistent with Postgres as possible.

2021-12-03 15:25 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +func notebooksPermissionsCondition(ctx context.Context, db dbutil.DB) (*sqlf.Query, error) {
nit: does this function need to return an error?

2021-12-03 15:25 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +	rows, err := s.Query(
I would recommend using `s.QueryRow()` here since you are looking up by ID and expect only a single value. See [GetMonitor](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/codemonitors/monitors.go?L192:1) for an example. It's also convenient because scanning just returns a `sql.ErrNoRows` if nothing was returned, so there's no need to do any checks that exactly one row was returned.

2021-12-03 15:25 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +		}
I think the "correct" way to do this would be to [implement the driver interfaces](https://www.alexedwards.net/blog/using-postgresql-jsonb) for `NotebookBlock`. I am not positive this will work as expected given the top-level is a slice, so it would possibly be necessary to make a helper `type NotebookBlocks []NotebookBlock` that implements the driver methods. I can't vouch for the approach since I've never actually tried it before, but I thought I'd give you an alternative to this two-step thing.

2021-12-03 15:25 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +	return s.GetNotebook(ctx, id)
Rather than the additional roundtrip, why not just alter the query to `RETURNING <all the columns needed for a Notebook>`?

2021-12-03 15:25 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +	}
Rather than treating `0` as a special case, I would highly recommend just making `Notebook.CreateorUserID` a `*int32` to make it clear from the client side that it's nullable.

2021-12-03 15:26 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +
```suggestion
```

2021-12-06 07:12 UTC, novoselrok commented on enterprise/internal/notebooks/store.go
> +func notebooksPermissionsCondition(ctx context.Context, db dbutil.DB) (*sqlf.Query, error) {
Nope, I'll simplify.

2021-12-06 08:39 UTC, novoselrok commented on enterprise/internal/notebooks/store.go
> +		}
Very nice, wasn't aware of this. Works great!

2021-12-06 08:43 UTC, novoselrok commented on enterprise/internal/notebooks/store.go
> +	}
I know it's a bit weird, but we're using this pattern across our codebase, e.g. namespaces: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+namespaceuserid+int32&patternType=literal

2021-12-06 14:24 UTC, camdencheek approved these changes
Thank you for all the nice tests!

2021-12-06 14:24 UTC, camdencheek commented on enterprise/internal/notebooks/store.go
> +}
Cool! This ended up nice and clean.

2021-12-06 14:24 UTC, camdencheek commented on enterprise/internal/notebooks/store_test.go
> +	t.Parallel()
very small nit: `t.Parallel()` should ideally be called first thing so that `dbtest.NewDB()` is also called in parallel. That's often the slowest part of the test, so running that in parallel is valuable.

2021-12-06 14:24 UTC, camdencheek commented on enterprise/internal/notebooks/store_test.go
> +	fmt.Println(blocks[0].QueryInput, createdNotebook.Blocks[0].QueryInput, blocks[0].QueryInput.Text, createdNotebook.Blocks[0].QueryInput.Text)
Is this println intentional?

2021-12-07 05:54 UTC, merged