Extract the remaining Webpack config duplication into a separate workspace
sourcegraph/sourcegraph pull request #28589
Opened 2021-12-04 20:19 UTC by gitstart-sourcegraph

## Problem statement
Three client packages use Webpack as a build tool. Webpack configuration is different for each package, but parts of it should be consistent. Instead of updating the same part of the configuration in multiple places, we can extract them into a standalone client workspace to have one source of truth.

## This issue can be started after two smaller tasks are completed:

https://github.com/sourcegraph/sourcegraph/issues/25183
https://github.com/sourcegraph/sourcegraph/issues/25214

## Refs
[GitStart Issue](https://app.gitstart.com/clients/sourcegraph/tickets/SG-21845)

## Success criteria
- The remaining Webpack config duplication is extracted into the build-config package and reused from the in consumer packages.
- The remaining Webpack config duplication is imported to the consumer packages via Typescript references import:
<code>import { getCacheConfig } from '@sourcegraph/build-config'</code>

2021-12-06 06:14 UTC, gitstart-sourcegraph commented
Hello @valerybugakov, could you help confirm if there are additional methods to be refactored, as part of this issue.

2021-12-08 11:41 UTC, valerybugakov commented
@gitstart-sourcegraph, please take a look at these files:
1. `client/web/webpack.config.js`
2. `client/web/dev/utils/constants.ts`
2. `client/storybook/src/main.ts`
3. `client/storybook/src/webpack.config.dll.ts`
4. `client/storybook/src/webpack.config.common.ts`
4. `client/browser/config/webpack/base.config.ts`
5. `client/browser/config/webpack/development.config.ts`
6. `client/browser/config/webpack/production.config.ts`
7. `client/browser/config/webpack/utils.ts`

See if any bits can be extracted into the `build-config` package to ensure consistency. 
A couple of examples that I see right away:
1. The `TerserPlugin` configuration can be reused.
2. The `ProvidePlugin` configuration can be reused.
3. Reusable path constants defined `client/storybook/src/webpack.config.common.ts` can be extracted.

The goal is to have all shareable building blocks and utilities extracted into the `build-config` package to have one source of truth. Let me know if it makes sense.

A couple of notes on the current state of things:
1. I noticed that we required modules from `@sourcegraph/build-config` twice in the `client/web/webpack.config.js`. We should use one `require` statement for each package/library.
2. We should delete unused variables like `MonacoWebpackPlugin` if they are not required in the configuration files after the update.

2021-12-08 11:46 UTC, valerybugakov requested changes
Let's work on the changes mentioned in the comment above.

2021-12-14 14:36 UTC, gitstart-sourcegraph commented
Hi @valerybugakov requested changes has been made. Thanks

2021-12-15 15:03 UTC, valerybugakov requested changes

2021-12-15 15:03 UTC, valerybugakov commented on client/build-config/src/webpack/commonConfig.ts
> +export const getCacheConfig = (...invalidateCacheFiles: string[]): Configuration['cache'] => ({
Let's make this argument an object to improve the readability in consumers; otherwise, it's not clear what arguments are for without digging into the implementation.

```suggestion
interface GetCacheConfigOptions {
  invalidateCacheFiles: string[]
}

export const getCacheConfig = ({ invalidateCacheFiles }: GetCacheConfigOptions): Configuration['cache'] => ({
```

2021-12-15 15:28 UTC, valerybugakov submitted a review, later dismissed

2021-12-15 15:28 UTC, valerybugakov commented on client/storybook/src/main.ts
>      getMonacoCSSRule,
`getMonacoCSSRule` and `getMonacoTTFRule` can be used `client/web/webpack.config.js`

2021-12-15 15:28 UTC, valerybugakov commented on client/web/webpack.config.js
> +  babelLoader,
It seems that `babelLoader` can also be used in `client/storybook/src/main.ts`:

https://github.com/sourcegraph/sourcegraph/blob/d976b60811badf204641f702bef7809d73580082/client/storybook/src/main.ts#L155-L159

2021-12-15 15:28 UTC, valerybugakov commented on client/browser/config/webpack/base.config.ts
> +    getCSSLoaders,
Does it make sense to extract `getCSSModulesLoader()` to ensure that we use consistent CSS modules configuration?

https://github.com/sourcegraph/sourcegraph/blob/d976b60811badf204641f702bef7809d73580082/client/storybook/src/main.ts#L177-L187

2021-12-15 15:28 UTC, valerybugakov commented on client/build-config/src/webpack/babel-loader.ts
> +export const babelLoader = {
Let's keep loaders wrapped into functions to be able to customize them later and be consistent with other loaders:
```suggestion
export const getBabelLoader = (): RuleSetRule => ({
```

@gitstart-sourcegraph, let's use the same pattern for plugins too.

2021-12-20 06:53 UTC, gitstart-sourcegraph commented
Hi @valerybugakov requested changes has been made.

2021-12-20 10:35 UTC, valerybugakov approved these changes
Thank you for addressing all the comments! 
LGTM with a couple of minor notes. After addressing them, the PR is good for merging.

2021-12-20 10:35 UTC, valerybugakov commented on client/build-config/src/webpack/css-loader.ts
> +    url?: boolean
Could you clarify how it defaults to `true`? It seems I'm missing something — in the `getCSSModulesLoader` implementation `url` is restructured and used as is.

2021-12-20 10:35 UTC, valerybugakov commented on client/storybook/src/webpack.config.common.ts
> +export const monacoEditorPath = path.resolve(NODE_MODULES_PATH, 'monaco-editor')
Let's export `monacoEditorPath` as `MONACO_EDITOR_PATH` from `@sourcegraph/build-config` and use it here. We have it defined in `client/build-config/src/webpack/monaco-editor.ts`.

2021-12-21 06:02 UTC, gitstart-sourcegraph commented on client/build-config/src/webpack/css-loader.ts
> +    url?: boolean
Updated comment.
Was added based on this documentation https://webpack.js.org/loaders/css-loader/#url

2021-12-21 10:04 UTC, valerybugakov requested changes
It seems we missed one option on the loader getter. I added a suggestion.
Everything else looks good. Also, let's make sure that the CI check is green before mering the PR.

2021-12-21 10:04 UTC, valerybugakov commented on client/build-config/src/webpack/css-loader.ts
> +     * Allow to enable/disables handling the CSS functions `url` and `image-set`.
```suggestion
     * Allow to enable/disable handling the CSS functions `url` and `image-set`.
     * Documentation: https://webpack.js.org/loaders/css-loader/#url.
```

2021-12-23 08:53 UTC, valerybugakov approved these changes
LGTM! 🚀

2021-12-23 14:11 UTC, merged