Wildcard V2: `<RadioButton />` Manual migration
sourcegraph/sourcegraph pull request #28669
Opened 2021-12-07 09:55 UTC by gitstart-sourcegraph

2021-12-20 14:49 UTC, oleggromov requested changes
There's one shortcoming with the UI - please see the comments.
Other than that, could you please share how you checked `ProductPlanFormControl.tsx` and `SelectAffiliatedRepos.tsx `? I couldn't see these components either in Storybook or in the app.

2021-12-20 14:49 UTC, oleggromov commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
> +            </div>
Couldn't check this page but code-wise it's fine too.

2021-12-20 14:49 UTC, oleggromov commented on client/web/src/components/RadioButtons.module.scss
> +    }
As I am not very familiar with the codebase, why these were added?

2021-12-20 17:23 UTC, valerybugakov commented on client/branded/src/global-styles/GlobalStylesStory/FormFieldVariants/FormFieldVariants.tsx
> +                <RadioButton
Agree with Oleg here 👍

2021-12-22 14:35 UTC, gitstart-sourcegraph commented
Hi @valerybugakov @oleggromov 
requested updates has  been added, Kindly take a look.

2021-12-23 02:26 UTC, gitstart-sourcegraph commented on client/web/src/components/RadioButtons.module.scss
> +    }
Because we are using `<small>` for label of `RadioButton` in `RadioButtons`, so we have to adjust vertical space a little bit

2021-12-23 02:30 UTC, gitstart-sourcegraph commented on client/web/src/user/settings/repositories/SelectAffiliatedRepos.tsx
> +            </div>
this UI in post sign up page (/welcome) but we have to modify some condition checks to force it showing
<img width="1284" alt="Screenshot at Dec 23 09-21-59" src="https://user-images.githubusercontent.com/89894075/147178628-bbce905d-11a0-49ac-a968-636ed004582e.png">

2021-12-23 14:02 UTC, valerybugakov commented
@gitstart-sourcegraph, you could also use the re-request review feature to signal that PR is ready for review after changes.

2021-12-27 10:09 UTC, oleggromov reviewed
Just approved the build in Percy.
Everything looks good, we can merge now 👍

2021-12-27 10:09 UTC, oleggromov commented on client/web/src/user/settings/repositories/UserSettingsManageRepositoriesPage.tsx
> +            </div>
Similar to that other page, I cannot now check it because of log in issue.
Anyways, trusting it's ok.

2021-12-27 10:09 UTC, oleggromov approved these changes

2021-12-27 13:36 UTC, oleggromov commented
Merging it since all checks are green.

2021-12-27 13:36 UTC, merged