cmd/repo-updater: add sync abort when user reached maximum allowed user added repos
sourcegraph/sourcegraph pull request #28674
Opened 2021-12-07 12:19 UTC by sashaostrikov

This is my first piece of "production" Go code, so any number of comments is highly appreciated!

**My main concern is about negative test (`testSyncIsNotAbortedWhenThereIsNoLastError`).** 

I wanted to skip actual calls to DB, so I mocked everything I could, but I haven't found a way to mock the TransactableHandle so that the "fake" transaction can be opened and the sync will go all the way through without any errors. For now this test fails with an error `* syncer: opening transaction: starting transaction: store: not transactable` and I just check that this error is not caused by my code which aborts the transaction, and therefore the test is green.

If anyone knows how to make this test pass without DB access and this error, please let me know.

**Another thing is 1 linter error** I don't know how to fix/suppress. I know for sure that there will be "\n", so I cannot get -1 from Index function

Error is as follows:
```
internal/repos/syncer.go:547:20: offBy1: Index() can return -1; maybe you wanted to do Index()+1 (gocritic)
                syncErrorLine := syncErrorWithoutPrefix[:strings.Index(syncErrorWithoutPrefix, "
")]
                                 ^
```

Closes https://github.com/sourcegraph/sourcegraph/issues/28177

2021-12-08 03:37 UTC, indradhanush requested changes

2021-12-08 03:37 UTC, indradhanush commented on internal/repos/syncer.go
> +	if errorLineStartIdx > -1 {
Let's flip this conditional to do an early return.

Reasoning: It helps to reduce nesting in the code. So something like this instead:

```go
    if errorLineStartIdx == -1 {
        return nil
    }

    // Do existing stuff here. 
```

2021-12-08 03:37 UTC, indradhanush commented on internal/repos/syncer.go
> +}
My understanding from reading this code is that we're trying to parse the error message and verify if the site / user limit has indeed been exceeded? If my understanding is correct, I would suggest that it would be sufficient to just check if we have the matching error string in the failure message of the sync job as defined in `userAddedRepoLimitError`. 

Reasoning: We shouldn't have to verify if the error raised was legitimate. That is the responsibility of the code which is raising this error. Our assumption here should be if the error was raised it is legitimate and we accept it as such. 

The added benefit of this would be that this helps us get away with the hacky string manipulation code which would be very fragile and difficult to maintain in the future.

2021-12-08 03:37 UTC, indradhanush commented on internal/repos/syncer.go
> +func updateExternalServiceOnError(
We can probably make this a method of the `Syncer` type instead since it already wants to use other attributes of the `Syncer`:

```go
func (s *Syncer) updateExternalServiceOnError
```

2021-12-08 03:37 UTC, indradhanush commented on internal/repos/syncer.go
> +	upsertErr := s.Store.ExternalServiceStore.Upsert(ctx, svc)
We can name this `err` itself. It's a commonly used Go convention unless `err` is already used somewhere and needs to be preserved.

2021-12-08 03:37 UTC, indradhanush commented on internal/repos/syncer.go
> +}
Nit: Code for this function can be inlined at the call site. There is not a lot of value from abstracting this away in this case, especially since it's used just once.

2021-12-08 09:14 UTC, sashaostrikov commented on internal/repos/syncer.go
> +}
Well, this code does a slightly different thing: it indeed takes limits from the error message, but it is done to compare with _actual limits taken from conf_. This is done in order not to abort a sync when we need to continue it. This happens only if the limits were increased and values from `conf` are now more than limits from last error.

Does it make sense?

2021-12-08 09:16 UTC, sashaostrikov commented on internal/repos/syncer.go
> +const userAddedRepoLimitError = "reached maximum allowed user added repos"
It was a Java habit of declaring all the constants at the top of the file :)

2021-12-08 09:32 UTC, sashaostrikov commented on internal/repos/syncer.go
> +func updateExternalServiceOnError(
IDE offered me this type of function extraction, but I really didn't know about when it is good to add methods of a type, and when to declare just a function

2021-12-08 09:50 UTC, sashaostrikov commented on internal/repos/syncer.go
> +}
`SyncExternalService` is already ~140 lines of code, I didn't want to add more lines to that and wanted to make this code more modular :) 
Moreover I think that my code is not "that important" to extend the `SyncExternalService` even more.
And I think this really looks concise and will not bother anyone with reading what they are not interested into (svc update code):
```go
	if err := checkLastSyncError(ctx, externalServiceID, s); err != nil {
		return s.updateExternalServiceOnError(ctx, externalServiceID, minSyncInterval, svc, err)
	}
```

2021-12-08 11:31 UTC, tsenart requested changes

2021-12-08 12:49 UTC, sashaostrikov commented on internal/repos/syncer.go
> +	if err := checkLastSyncError(ctx, externalServiceID, s); err != nil {
Well this is way more elegant than my solution. Will refactor the code, thanks!

Btw, do you know how to test [sync function](https://github.com/sourcegraph/sourcegraph/blob/59a7f5efe00ee3a7fdd784fe71f9b108060a387c/internal/repos/syncer.go#L622) without running queries against the DB?

If it is not possible, then the only way to test refactored logic is to write integration tests with DB access, which I wanted to omit in this PR, in favor of tests with mocks

2021-12-08 15:32 UTC, camdencheek commented on internal/repos/syncer.go
> +	if err := checkLastSyncError(ctx, externalServiceID, s); err != nil {
Yes! You can take a look at the [testing go code docs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/dev/background-information/languages/testing_go_code.md).

2021-12-08 15:48 UTC, tsenart commented on internal/repos/syncer.go
> +	if err := checkLastSyncError(ctx, externalServiceID, s); err != nil {
@sashaostrikov: Push what you have and I'll take a look.

2021-12-08 16:34 UTC, sashaostrikov commented on internal/repos/syncer.go
> +	if err := checkLastSyncError(ctx, externalServiceID, s); err != nil {
@tsenart pushed it. tests are still to be finished

Here is a screenshot of debugger, showing multierror nature of error returned by sync
![image](https://user-images.githubusercontent.com/94846361/145246520-a0035820-dde1-42cd-a0df-d90b28b74300.png)

2021-12-08 17:03 UTC, tsenart commented on internal/repos/syncer.go
> +	if err := checkLastSyncError(ctx, externalServiceID, s); err != nil {
Try  using `errors.HasType(err, &RepoLimitError{})`

2021-12-09 09:36 UTC, sashaostrikov commented on internal/repos/syncer.go
> +	if err := checkLastSyncError(ctx, externalServiceID, s); err != nil {
it worked, thanks!

I also found a reason why I was getting `multierror.Error` instead of `ReposLimitError` as an output of `sync` function. the error was doubled and wrapped into multierror as a part of defer function, which was committing/rolling back the DB transaction.

I fixed it in these lines of code:
https://github.com/sourcegraph/sourcegraph/blob/fc74eec2d3f212f1992a6c6f4f5d80b5feecb42b/internal/repos/syncer.go#L565-L574

2021-12-09 10:56 UTC, ryanslade commented on internal/repos/syncer.go
> +			// this check is added so that if txerr is just the same err returned from sync (not some error related to
I think we can simplify the whole `defer`. The underlying `Done` method will combine the `err` passed in with any errors that happens comitting the transaction, so I think we can do this: 

```go
defer func() {
		observeDiff(d)
		// We must commit the transaction before publishing to s.Synced
		// so that gitserver finds the repo in the database.
		err = tx.Done(err)
		if err != nil {
			return
		}

		if s.Synced != nil && d.Len() > 0 {
			select {
			case <-ctx.Done():
			case s.Synced <- d:
			}
		}
	}()
```

2021-12-09 12:28 UTC, sashaostrikov commented
PTAL, I've pushed the changes
@indradhanush 
@ryanslade 
@tsenart

2021-12-09 13:47 UTC, ryanslade approved these changes
LGTM 👍

2021-12-09 14:03 UTC, indradhanush reviewed
If I understand the new approach correctly, now we will stop syncing the external service the first time we encounter the limit exceeded error for a repo? And when it's time to sync again we will attempt to sync again and only stop when we see the same error again provided the user has not removed excess repos or the limit has been increased?

2021-12-09 14:12 UTC, sashaostrikov commented
> If I understand the new approach correctly, now we will stop syncing the external service the first time we encounter the limit exceeded error for a repo? And when it's time to sync again we will attempt to sync again and only stop when we see the same error again provided the user has not removed excess repos or the limit has been increased?

Yes, well basically with the new approach we stop the sync as soon as the `RepoLimitError` comes up, so we always try to sync at least one repo of a service

2021-12-09 14:18 UTC, sashaostrikov commented on internal/repos/syncer.go
> +	UserAdded, UserLimit uint64
Sure, 1 property on each line reads better, fixed and also added docs

2021-12-09 14:30 UTC, indradhanush approved these changes
LGTM!

2021-12-09 14:30 UTC, indradhanush commented on internal/repos/syncer.go
> +			if errors.HasType(err, &RepoLimitError{}) {
```suggestion
            // Stop syncing this external service as soon as we know repository limits
            // for user or site level has been exceeded. 
			if errors.HasType(err, &RepoLimitError{}) {
```

2021-12-09 19:29 UTC, merged