Wildcard V2: `<Alert />` Implementation
sourcegraph/sourcegraph pull request #28672
Opened 2021-12-07 10:51 UTC by gitstart-sourcegraph

## Wildcard implementation of the `` component.
### See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

Acceptance criteria
- [ ] Component is implemented within Wildcard
- [ ] Component has tests
- [ ] Component is accessible
- [ ] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)

## Implementation details
- Create the `` component similar to the [<button> component.](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard/src/components/Button)
- Copy `client/branded/src/global-styles/alert.scss` to the component folder and covert it to a CSS module.
- Move `.alert-heading` to `client/web/src/enterprise/batches/detail/changesets/ExternalChangesetNode.module.scss`.
- Leave `.alert-link` as a global class for now. Keep it in the CSS module wrapped into a `:global()` keyword.
- Move `client/branded/src/global-styles/GlobalStylesStory/AlertsStory.tsx` ([link](https://storybook.sgdev.org/?path=/story/wildcard-button--all-buttons)) to the new component folder and update it it match other stories in the Wildcard package.
- Use the `</button><button> component` as a blueprint for the new component.
Component API:

2021-12-17 16:51 UTC, valerybugakov submitted a review, later dismissed
LGTM with a couple of minor changes.

2021-12-17 16:51 UTC, valerybugakov commented on client/wildcard/src/components/Alert/Alert.module.scss
> +        /* Icon: mdi-react/Information */
```suggestion
        /* We cannot render SVG in HTML because then we will need to add it to every `.alert` element manually. */
        /* We can use it as a `mask-image` to apply CSS variables as a fill color. */
        /* Icon: mdi-react/Information */
```

2021-12-17 16:51 UTC, valerybugakov commented on client/wildcard/src/components/Alert/story/Alert.story.tsx
> +export const AllAlerts = () => (
Let's use the `Story` type in places like this one.

```suggestion
export const Alerts: Story = () => (
```

2021-12-17 16:51 UTC, valerybugakov commented on client/wildcard/src/components/Alert/story/Alert.story.tsx
> +        <AlertVariants variants={ALERT_VARIANTS} />
Let's move the contents of `AlertVariants` inside of this file. It was implemented separately to separate it from a huge global styles story which is not the case here.

2021-12-17 16:51 UTC, valerybugakov commented on client/wildcard/src/components/Alert/story/util.ts
> +}
Let's inline this into the story file and remove the `story` folder.

2021-12-17 16:52 UTC, valerybugakov commented
@gitstart-sourcegraph, please don't forget to add the `gitstart` label to your PRs. It triggers our Slack integration notifications.

2021-12-21 08:50 UTC, valerybugakov requested changes

2021-12-21 08:50 UTC, valerybugakov commented on client/wildcard/src/components/Alert/Alert.tsx
> +export const Alert: React.FunctionComponent<AlertProps> = React.forwardRef(
Let's use our type helper as we do in the `<MenuButton />` component for `forwardRef`: 

https://github.com/sourcegraph/sourcegraph/blob/c2c03ab391a2809614cb8482be4ccffbf239bb04/client/wildcard/src/components/Menu/MenuButton.tsx#L19

2021-12-21 08:50 UTC, valerybugakov commented on client/wildcard/src/components/Alert/Alert.story.tsx
> +const AlertVariants: React.FunctionComponent<AlertVariantsProps> = ({ variants, as }) => (
Sorry, I didn't communicate it clearly. Let's inline this component output into the `Alerts` story. It would allow removing the `AlertVariantsProps` interface.

2021-12-21 08:50 UTC, valerybugakov commented on client/wildcard/src/components/Alert/Alert.module.scss
> +:global(.alert-link) {
Let's create the `<AlertLink />` component to provide these styles and remove the `:global()` selector from here. Also, let's replace all the occurrences of the `.alert-link` class in the codebase with the new component. It is not used very often.

<img width="557" alt="Screen Shot 2021-12-21 at 10 49 03" src="https://user-images.githubusercontent.com/3846380/146899956-d1a481b6-a505-4912-8b92-05472d99bce9.png">

2021-12-22 13:51 UTC, AlicjaSuska reviewed
Alerts look good, they are aligned with Figma, thank you!

The only issue I found is the 'Dismiss' button placement - it is too close to the border. I've recorded a [loom](https://www.loom.com/share/758e065f2ac24be590fc817c6efda339) showing how to get to the dimensions in Figma. They are nested: text -> button -> alert.

2021-12-23 14:01 UTC, valerybugakov requested changes

2021-12-23 14:01 UTC, valerybugakov commented on client/wildcard/src/components/Alert/AlertLink.tsx
> +export const AlertLink: React.FunctionComponent<
We can remove `.alert-link` styles from `client/branded/src/global-styles/alert.scss` since we remove all `.alert-link` occurrences from the codebase.

2021-12-24 09:44 UTC, valerybugakov approved these changes
Great! Let's address a couple of minor comments and merge without an additional review because changes are pretty simple.

2021-12-24 09:44 UTC, valerybugakov commented on client/wildcard/src/components/Alert/Alert.story.tsx
> +            <Alert className={classNames('d-flex align-items-center', styles.alert, styles.alertInfo)}>
It seems that here styles are redundant because they are already provided by the `<Alert />` component

```suggestion
            <Alert variant="info" className="d-flex align-items-center">
```

2021-12-24 09:44 UTC, valerybugakov commented on client/wildcard/src/components/Alert/Alert.story.tsx
> +                <AlertLink to="/" onClick={flow(preventDefault, action(classNames('link clicked')))}>
An additional `padding-right: 0.5rem` is needed to match mockups.

2021-12-24 10:22 UTC, merged