Code intel/cesar/domain driven architecture
sourcegraph/sourcegraph pull request #28755
Opened 2021-12-08 20:35 UTC by Numbers88s

## 🤔  Description

Moving executor functionality to domain driven service architecture

## 🚀  GIF
_What gif best describes this PR or how it makes you feel?_

![hide](https://media.giphy.com/media/6IcNBPp1H79nO/giphy.gif)

2021-12-13 23:40 UTC, efritz approved these changes
:yes:

2021-12-15 17:38 UTC, eseliger requested changes

2021-12-15 17:38 UTC, eseliger commented on internal/database/database.go
> +	executorDB "github.com/sourcegraph/sourcegraph/cmd/frontend/services/executors/store/db"
We can't import from a `cmd` package in `internal`. This needs to move into an internal package as well. While we're at this: It'd be nice if executors code could become enterprise code but not a blocker :)

2021-12-15 18:28 UTC, efritz commented on internal/database/database.go
> +	executorDB "github.com/sourcegraph/sourcegraph/cmd/frontend/services/executors/store/db"
Thanks for catching this. @Numbers88s if you have trouble breaking this import down I can help or we could pair on this to get it over the 🏁 .

2021-12-16 05:02 UTC, Numbers88s commented on internal/database/database.go
> +	executorDB "github.com/sourcegraph/sourcegraph/cmd/frontend/services/executors/store/db"
@eseliger I tried moving it to enterprise but it was too much for right now, so I'll circle back to it. I did removed the import from `cmd` however now the codeinsights db is not passing its test 🙃 even thought I don't touch any of the insights code. What's the relationship here?

2021-12-16 18:21 UTC, eseliger commented on internal/database/database.go
> +	executorDB "github.com/sourcegraph/sourcegraph/cmd/frontend/services/executors/store/db"
I think that's a CI flake, we've seen these a couple times before.. Retrying might help 🙈

2021-12-16 19:33 UTC, Numbers88s commented on internal/database/database.go
> +	executorDB "github.com/sourcegraph/sourcegraph/cmd/frontend/services/executors/store/db"
Oh cool @eseliger, yeah that was it. It passed CI 🎉 .

2021-12-17 20:04 UTC, Numbers88s commented
Sorry y'all some git foo went awry. Closing this one and opening a clean one.

2021-12-17 20:04 UTC, closed without merging