Wildcard V2: <Card /> Implementation
sourcegraph/sourcegraph pull request #28764
Opened 2021-12-08 22:14 UTC by gitstart-sourcegraph

## Wildcard implementation of the `<Card />` component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Acceptance criteria
- [x] Component is implemented within Wildcard
- [x] Component has tests
- [x] Component is accessible
- [x] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)

## Refs
* [Gitstart Task](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27679) 
* [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/27679)

## Implementation details

1. Extract styles required for the component from Bootstrap to a CSS module:
    - Figure out what classes do we use from `node_modules/bootstrap/scss/_card.scss`.
    - Create a CSS module with classes that we need from `node_modules/bootstrap/scss/_card.scss` and variables from `client/branded/src/global-styles/card.scss`.
    - For top-level classes create small components that incorporate required styles, e.g., `CardTitle` for `.card-title`.
2. Move `client/branded/src/global-styles/GlobalStylesStory/CardsStory.tsx` ([link](https://storybook.sgdev.org/?path=/story/branded-global-styles--cards)) to the new component folder and update it to match other stories in the Wildcard package. 
3. Use [the `<Button />` component](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard/src/components/Button) as a blueprint for the new component.
4. Component API:

```tsx
<Card header="Featured" title="My cool title" subtitle="Subtitle">
  Body goes here
</Card>

// Also should be possible
<Card>
  <CardHeader>Featured</CardHeader>
  <CardBody>
     <CardTitle>My cool title</CardTitle>
     <CardSubtitle>Subtitle</CardSubtitle>
     <CardText>Body goes here</CardText>
  </CardBody>
</Card>
```

2021-12-15 16:58 UTC, valerybugakov requested changes
I updated the `Card` story to showcase some changes because I tested them locally. A couple of things to note:

1. Let's remove links to Bootstrap documentation if we bump into them because they are not relevant for Wildcard components. 
2. Let's try to limit the use of utility classes in component stories if possible and rely on existing Wildcard components.
3. Note some additional types used in the story. 
4. I removed most of the `<Card />` component props to keep it simple. It's hard to manage expectations of how the content will be rendered if only part of props is supplied. Let's keep only one API for now.
5. Let's use `--card-spacer-x` and `--card-spacer-y` CSS variables in sub-components.

2021-12-15 16:58 UTC, valerybugakov commented on doc/cloud/organizations/get_started_with_orgs_cloud.md
> +4. [Invite your teammates to the orgnaization](./inviting_users_to_org_on_sourcegraph_cloud.md)
Is this change intentional?

2021-12-15 16:58 UTC, valerybugakov commented on internal/featureflag/middleware.go
> +func TestSetFlagsOnContext(ctx context.Context, flags FlagSet) context.Context {
Is this change intentional?

2021-12-15 16:58 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.module.scss
> +.card-interactive {
Do we use `card-interactive` somewhere in the codebase?

2021-12-15 16:58 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.story.tsx
> +        {/* eslint-disable-next-line react/forbid-dom-props */}
Is this required?

2021-12-15 17:05 UTC, valerybugakov requested changes

2021-12-15 17:05 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.test.tsx
> +            <Card title="card title" subtitle="card subtitle" variant="interactive">
Let's update this test to use `Card` sub-components.

2021-12-15 17:05 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardBody.module.scss
> +    padding: 0.5rem;
Let's preserve CSS variables if they are used outside of the component in the codebase like `--card-spacer-x`.

<img width="676" alt="Screen Shot 2021-12-15 at 18 00 34" src="https://user-images.githubusercontent.com/3846380/146230965-c678c88e-aa3f-4a6a-aaff-16e3f9da692a.png">

2021-12-15 17:05 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardTitle.tsx
> +    <div className={classNames(styles.cardTitle, className)} {...attributes}>
Let's use the `h3` element here.

2021-12-15 17:05 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardTitle.module.scss
> +}
How these styles were extracted from Bootstrap? It seems that `node_modules/bootstrap/scss/_card.scss` contains only: 

<img width="291" alt="Screen Shot 2021-12-15 at 18 02 47" src="https://user-images.githubusercontent.com/3846380/146231509-ad4950fc-3a4c-426b-9b3a-e953f4e90d94.png">

2021-12-15 17:05 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardSubtitle.module.scss
> +}
How these styles were extracted from Bootstrap? It seems that `node_modules/bootstrap/scss/_card.scss` contains only: 

<img width="309" alt="Screen Shot 2021-12-15 at 18 02 53" src="https://user-images.githubusercontent.com/3846380/146231613-4d32ee5f-19e1-4305-92ad-9db017c0c296.png">

2021-12-15 17:35 UTC, gitstart-sourcegraph commented on doc/cloud/organizations/get_started_with_orgs_cloud.md
> +4. [Invite your teammates to the orgnaization](./inviting_users_to_org_on_sourcegraph_cloud.md)
Apologies, these were auto-generated during PR sync by our system, would be resolved in next push

2021-12-15 17:35 UTC, gitstart-sourcegraph commented on internal/featureflag/middleware.go
> +func TestSetFlagsOnContext(ctx context.Context, flags FlagSet) context.Context {
same as above

2021-12-15 19:18 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Card/Card.module.scss
> +.card-interactive {
This was used to add the hover and focus border, on interactive variant of card element.
Since we are not using variant anymore, kindly confirm this can be merged into the `.card` style rule, so all cards can have the `hover` and `focus` state border-color and box-shadow respectively, as represented in Figma design.

2021-12-15 19:27 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Card/components/CardSubtitle.module.scss
> +}
Added a couple more style rules, in order to match the design specifications from the Figma.
Kindly help confirm that we do not need to add any more style rules, asides from the ones extracted from Bootstrap, in an attempt to match sample cards from Figma design.

2021-12-15 19:28 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Card/components/CardTitle.module.scss
> +}
same as below

2021-12-15 20:44 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.module.scss
> +.card-interactive {
You're right. I forgot about this design in the Figma mockup because we don't have this class in the codebase at the moment. The implementation with two variants is correct. I reverted my change. 

Also, I see the issue that you mentioned initially with hover states of interactive cards. Let's fix the content jump.

2021-12-15 20:46 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardSubtitle.module.scss
> +}
Makes thanks. Let's match Figma mockups. 
Note: let's use semantic color variables where possible. E.g., here `var(--text-muted)` can be used instead of `var(--gray-07)`.

2021-12-15 20:48 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardSubtitle.module.scss
> +}
Also, according to the developer tools `margin-top` property is not valid with the current value, and `margin-bottom: 0` doesn't affect anything and can be deleted. If I don't miss anything, let's update these rules.

2021-12-15 20:49 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardTitle.module.scss
> +}
Using `h3` for the `CardTitle` can make some of these extra rules redundant. Please double-check that after the update.

2021-12-16 06:54 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Card/Card.story.tsx
> +        {/* eslint-disable-next-line react/forbid-dom-props */}
No, removing...

2021-12-16 18:51 UTC, gitstart-sourcegraph commented
Hi @valerybugakov requested changes has been implemented, Thanks

2021-12-17 16:22 UTC, valerybugakov requested changes
I noticed a couple of improvements we should make:

1. Border color in Figma uses the semantic variable `--border-color-2` instead of `--gray-04`.
2. We need to implement `:focus` styles for interactive cards to match mockups. It seems something similar is already done in the `InsighsCard` component:

https://github.com/sourcegraph/sourcegraph/blob/0226e05e02911b72126705d17b43ac5dc11cce09/client/web/src/enterprise/insights/pages/insights/creation/intro/cards/InsightCards.module.scss#L14-L17

<img width="180" alt="Screen Shot 2021-12-17 at 17 17 17" src="https://user-images.githubusercontent.com/3846380/146575124-7f36b240-8487-4e80-bfda-e63e1d839575.png">

3. The border shown on hover in the interactive mode doesn't match Figma mockups:

| Implementation | Figma |
| -- | -- |
| <img height="200" alt="Screen Shot 2021-12-17 at 16 58 59" src="https://user-images.githubusercontent.com/3846380/146572646-86b5c940-bf6c-4a02-9253-e60681411471.png"> | <img height="200" alt="Screen Shot 2021-12-17 at 16 58 48" src="https://user-images.githubusercontent.com/3846380/146572651-84b6a040-c647-482d-a39a-4a14d2cf43e1.png"> |

2021-12-17 16:22 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.module.scss
> +    }
It seems that we don't use the `hr` element nested into cards in our codebase, so we can omit these styles.
```suggestion
```

2021-12-20 10:02 UTC, valerybugakov requested changes
1. In the mockup card in the focused state doesn't have a gray border. Here's the screenshot of the current implementation:

<img width="55" alt="Screen Shot 2021-12-20 at 11 58 44" src="https://user-images.githubusercontent.com/3846380/146748920-03cf0ab8-11fb-4ae9-8b2d-d7b145c147d3.png">

2. It seems that the width of the card changes on hover while in the mockup in stay the same and doesn't outside of the initial container:

| Implementation | Mockup |
| -- | -- |
| <img height="250" alt="Screen Shot 2021-12-20 at 11 57 14" src="https://user-images.githubusercontent.com/3846380/146748930-398e6055-3dff-48da-8d91-5f8daaaa296d.png"> | <img height="250" alt="Screen Shot 2021-12-20 at 12 00 32" src="https://user-images.githubusercontent.com/3846380/146749295-7673b8fd-37ba-4978-8d41-0ff1d5cab596.png"> |

2021-12-21 10:23 UTC, valerybugakov requested changes
@gitstart-sourcegraph, the Jest snapshot needs to be updated according to [the failed CI check](https://buildkite.com/sourcegraph/sourcegraph-contractors/builds/11766#8a17add0-3400-49e7-8fae-b2f988a94024). Let's add it to our checklist - make sure the CI check is green before requesting a PR review.

2021-12-21 10:23 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardList.module.scss
> +.list-group {
These styles should match Bootstrap styles:

<img width="607" alt="Screen Shot 2021-12-21 at 12 09 35" src="https://user-images.githubusercontent.com/3846380/146911979-c0dacae8-1d7c-47d9-a481-ec78a7fee06b.png">

This component aims to replace usages of `list-group` inside of the `Card` component in the codebase during the migration. We don't need to use it two create a list of cards in the story. For that, let's use helper classes for now, like `<div className="d-flex ..." />`

2021-12-21 10:23 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.module.scss
> +    --hover-box-shadow: 0 0 0 0.125rem var(--primary) inset;
It seems that on hover, we show a 3px border: 2px from inset shadow and 1px from the actual border, whereas we need to show a 2px border according to mockups.

2021-12-21 10:23 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.tsx
> +export const Card: React.FunctionComponent<CardProps> = ({
Let's allow to change the element used for the card with `as` prop that default to `div`.  It will be helpful for `InsightsCard` that uses the `button` element for interactive cards.

2021-12-21 16:15 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Card/Card.tsx
> +export const Card: React.FunctionComponent<CardProps> = ({
Got it @valerybugakov,
On last update, `tabIndex={0}` was added on div element to ensure interactive card variants are focusable.
1. Are we to remove this, such that the interactive cards would require user to provide the interactive elements (e.g `button`) as props?.
2. If (1) above is true, it's assumed that if user chooses an interactive variant option, and does not pass in the interactive  element as prop (`e.g button`), it's expected that the focus state (only) would be inactive?.
3. Do we use the two options i.e making default `div` element interactive

2021-12-21 16:53 UTC, valerybugakov commented on client/wildcard/src/components/Card/Card.tsx
> +export const Card: React.FunctionComponent<CardProps> = ({
@gitstart-sourcegraph, it seems that the simplest solution, for now, would be to use the `button` element as a default value for `as` prop when the `interactive` variant is set. That way, we can remove `tabIndex={0}` and will be able to use interactive cards in the existing `InsightsCard` component. Let me know if you see issues with this approach.

2021-12-22 14:09 UTC, AlicjaSuska requested changes
Hello! Thank you for working on this issue. I've noticed that cards have significant spacing issues:
- padding around the card is too small (should bs 16)
- toggle and 'Edit' button are not aligned horizontally
- there should be more space around the edit button. I think the reason behind it is using link text instead of the [text button](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A3809). Text button looks the same in the default state but has some styles and padding applied. Text button in [Storybook](https://storybook.sgdev.org/?path=/story/wildcard-button--all-buttons)

2021-12-22 18:18 UTC, gitstart-sourcegraph commented
Thanks @AlicjaSuska 
Issues 1, 3 has been resolved.
The misalignment of Toggle and Edit is due to intrinsic style properties of the `Toggle` component as shown below
![Screenshot from 2021-12-22 18-32-12](https://user-images.githubusercontent.com/89894075/147136847-a94ff0c5-cb00-4af0-9bca-3af51f27b7dc.png)
@valerybugakov 
One solution would be to modify the `Toggle` component to fix this globaly, since the styles are applied to the `bar` and `knob` child classes. Another would be to create a style sheet for Card.Story.tsx to overwrite styles, since utiliy classes might not be able to select child elements directly.

2021-12-23 13:42 UTC, valerybugakov commented
> One solution would be to modify the Toggle component to fix this globally since the styles are applied to the bar and knob child classes.

Let's address this issue in a separate PR since it's not directly related to the `<Card />` component implementation.

2021-12-23 13:53 UTC, valerybugakov requested changes
UI looks awesome! Thank you for addressing all the issues.
Let's add `as` prop to all new card components. After that, the PR is good to go.

2021-12-23 13:53 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardTitle.tsx
> +export const CardTitle: React.FunctionComponent<React.HTMLAttributes<HTMLDivElement>> = ({
Let's allow to change the default HTML element via `as` prop.

2021-12-24 09:49 UTC, valerybugakov commented on client/wildcard/src/components/Card/components/CardTitle.tsx
> +export const CardTitle: React.FunctionComponent<React.HTMLAttributes<HTMLDivElement>> = ({
> Let's add `as` prop to all new card components. 

@gitstart-sourcegraph, I left this comment as an example of where we need this prop to be added. But it needs to be added to **all** new Card components. I see that it's been added only to the `CardTitle` component so far.

2021-12-24 09:50 UTC, valerybugakov requested changes
Check out the comment in the thread above.

2021-12-24 10:16 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Card/components/CardTitle.tsx
> +export const CardTitle: React.FunctionComponent<React.HTMLAttributes<HTMLDivElement>> = ({
@valerybugakov Updates PR with making all sub components support `as` prop

2021-12-24 13:04 UTC, valerybugakov approved these changes
Thanks!

2021-12-24 13:05 UTC, valerybugakov commented
@gitstart-sourcegraph, it seems [we merged](https://github.com/sourcegraph/sourcegraph/pull/28887#issuecomment-1000830996) the implementation prematurely in another PR. Let's ensure that we resolve merge conflicts without losing important changes made in this PR.

2021-12-24 13:25 UTC, gitstart-sourcegraph commented
@valerybugakov 🙏 really sorry for this mistake, was doing that in hurry for trying to resolve long running PRs, would take care in next time.

I check the main branch, it has the Popper.placement refactor changes for Tooltip and ‘forwarRef’ with ‘as’ prop changes for Card sub components

2021-12-24 13:26 UTC, valerybugakov commented
@gitstart-sourcegraph, ok, sounds good!

2021-12-24 13:27 UTC, valerybugakov approved these changes

2021-12-24 13:29 UTC, merged