all: Validate database schema on startup
sourcegraph/sourcegraph pull request #28804
Opened 2021-12-09 17:35 UTC by efritz

Work in progress, more to come.

2021-12-10 15:00 UTC, eseliger requested changes
LGTM, requesting changes to block merge

2021-12-10 15:07 UTC, mrnugget approved these changes
<img width="486" alt="screenshot_2021-12-10_16 06 55@2x" src="https://user-images.githubusercontent.com/1185253/145595602-66eea86a-cf54-461e-824a-5343de5435c1.png">

2021-12-15 19:11 UTC, efritz commented
I've re-added the original connection methods and guarded the new behavior with an envvar in 43d8d37. This should be mergeable without breaking any existing behavior.

2021-12-15 23:13 UTC, coury-clark commented on cmd/server/shared/shared.go
> +	for _, schemaName := range []string{"frontend", "codeintel"} {
Am I correct in thinking `codeinsights-db` will need to be added once we've migrated from Timescale? If so, what happens in the meantime, can we still run migrations on it?

2021-12-15 23:15 UTC, efritz commented on cmd/server/shared/shared.go
> +	for _, schemaName := range []string{"frontend", "codeintel"} {
This is in the `server` image. Will insights be embedded into the single docker image deployment?

2021-12-15 23:16 UTC, coury-clark commented on cmd/server/shared/shared.go
> +	for _, schemaName := range []string{"frontend", "codeintel"} {
ah - didn't realize that. No, I don't think so!

2021-12-15 23:26 UTC, coury-clark approved these changes

2021-12-15 23:45 UTC, efritz commented
Main dry run: https://buildkite.com/sourcegraph/sourcegraph/builds/121737

2021-12-16 00:03 UTC, eseliger approved these changes

2021-12-16 16:35 UTC, merged