Wildcard V2: <Link /> Implementation
sourcegraph/sourcegraph pull request #28837
Opened 2021-12-10 09:52 UTC by gitstart-sourcegraph

## Wildcard implementation of the <Link /> component.
See Wildcard V2 - Planned work for more context

## Acceptance criteria
- [x] Component is implemented within Wildcard
- [x] Component has tests
- [x] Component is accessible
- [x] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System)

## Implementation details
1) Move the [existing implementation](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/components/Link.tsx#L1:1) to the Wildcard package.
2) Extract styles required for the component from Bootstrap to a CSS module:
a) Extract classes from node_modules/bootstrap/scss/_reboot.scss related to Link to a component CSS module.
b) Merge our link SCSS variables with the newly created CSS module.
3) Create new Link story. Render the Link component with a regular text like we do here.
4) Use the <Button /> component as a blueprint for the new component.

2021-12-13 09:08 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/Link.tsx
> +    </a>
Hi @valerybugakov 
For the usage of `RouterLinkOrAnchor` since we shouldn't import `Link.module.scss`, `RouterLinkOrAnchor` would not contain this style.

**Suggestion**
We implement `Link` but make `InternalLink` changeable, what do you think?

```tsx

let InternalLink: React.ComponentType<LinkProps>

export const Link: React.FunctionComponent<LinkProps> = ({ className, ...rest }) => (
    <InternalLink className={classNames(styles.anchorLink, className)} {...rest} />
)

if (process.env.NODE_ENV !== 'production') {
    // Fail with helpful message if setLinkComponent has not been called when the <Link> component is used.
    InternalLink = () => {
        throw new Error('No Link component set. You must call setLinkComponent to set the Link component to use.')
    }
}

export function setLinkComponent(component: typeof Link): void {
    InternalLink = component
}

```

2021-12-15 11:43 UTC, valerybugakov commented on client/wildcard/src/components/Link/Link.tsx
> +    </a>
@gitstart-sourcegraph, thank you for tagging me here. After reviewing the current implementation, it seems that it will be beneficial to go away from the implicit global `Link` variable. Here's my suggestion:

1. Move `client/web/src/components/RouterLinkOrAnchor.tsx` to the Wildcard and expose it as a `RouterLink` with CSS module styles.
2. Extract `AnchorLink` into a separate file so the `browser` package can use directly. 
3. Remove `setLinkComponent` so every consumer explicitly uses `RouterLink` or `AnchorLink` depending on their needs. 

Let me know if you see any blockers with this approach.

2021-12-17 13:27 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/Link.tsx
> +    </a>
Hi @valerybugakov 
Quick question to confirm assumption and better understand suggestion.
1. There would be two new components created `RouterLink` and `AncorLink`
2. we would update all current usages of (`1`) above.
3. For usage of `Link` component in other wildcard components such as `ButtonLink`, which of the created components would be appropriate?
4. For movement of `RouterLinkOrAnchor` and exposing as `RouterLink` would we need to modify the implementation as we move?

2021-12-17 16:34 UTC, valerybugakov commented on client/wildcard/src/components/Link/Link.tsx
> +    </a>
@gitstart-sourcegraph,

1. correct.
2. correct.
3. `ButtonLink` is used only inside the `web` package, so we can safely use `RouterLink` inside the `ButtonLink` for now.
4. `RouterLink` should use styles from the CSS module you already created.

2021-12-23 06:24 UTC, gitstart-sourcegraph commented
Hi @valerybugakov 
Updated with requested changes. Kindly take a look if there are more improvements to be made.
Can we merge this branch into the `ButtonLink` PR while we continue with development process on this, to avoid being blocked.

2021-12-23 08:15 UTC, valerybugakov commented
@gitstart-sourcegraph, merging into `ButtonLink` PR sounds good.

2021-12-23 08:16 UTC, valerybugakov commented
@gitstart-sourcegraph, please remove `draft` status from the pull request if it's ready for review. It helps to filter out pull requests still in progress.

2021-12-23 08:45 UTC, valerybugakov requested changes

2021-12-23 08:45 UTC, valerybugakov commented on yarn.lock
> +anymatch@*, anymatch@^3.0.3, anymatch@~3.1.1:
Are these changes in `yarn.lock` intentional?

2021-12-23 08:45 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
> Move `client/web/src/components/RouterLinkOrAnchor.tsx` to the Wildcard and expose it as a `RouterLink` with CSS module styles.

According to the decision above, should we preserve the logic required for rendering absolute URLs defined in `RouterLinkOrAnchor`?

```tsx
    typeof to === 'string' && isAbsoluteUrl(to) ? (
        <a href={to} {...props}>
            {children}
        </a>
    ) : (
        <Link to={to} {...props}>
            {children}
        </Link>
    )
```

2021-12-23 08:45 UTC, valerybugakov commented on client/wildcard/src/components/Link/AnchorLink.tsx
> +export const AnchorLink: React.FunctionComponent<LinkProps> = ({ to, children, className, ...rest }) => (
1. Let's move `AnchorLink` and `RouterLink` into their folders named accordingly instead of having them together in one folder. 
2. Would it be possible to use `AnchorLink` inside of the `RouterLink` via `as` prop to reuse `styles.anchor` via composition instead of directly importing styles there?

```tsx
export const RouterLink: React.FunctionComponent< AnchorLinkProps> = ({ children, to, className, ...rest }) => (
  <AnchorLink as={Link} ... />
```

3. The same pattern can be used for props — instead of having them in a separate utility module, we can reuse `AnchorLinkProps` in the `RouterLink` component.

2021-12-23 08:45 UTC, valerybugakov commented on client/web/src/user/settings/repositories/SettingsRepositoriesPage.tsx
> +                    <AnchorLink to={`${routingPrefix}/repositories/manage`}>Add repositories</AnchorLink> to start
Could you clarify why we use `AnchorLink` instead of the `RouterLink` here? 
It seems that we should use `RouterLink` everywhere inside of the `web` package. Let me know if I'm missing something.

2021-12-23 08:45 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
Oh, after going through more changed files, it seems I see what the intention was: use `<AnchorLink />` explicitly for absolute URLs and `<RouterLink />` for internal URLs. 

Sorry I didn't make it clear. What I meant by "so every consumer explicitly uses `RouterLink` or `AnchorLink` depending on their needs." — the `browser` package that doesn't rely on `react-router` should use the `AnchorLink` link, and the `web` package should use `RouterLink`, which internally uses the `a` tag for absolute URLs like it was done in the `RouterLinkOrAnchor` component. It ensures that if the URL changes, it's rendered correctly — sometimes it's hard to track such changes because URLs are passed in props to React components, so it's better to keep this logic. Let me know if it makes sense.

2021-12-23 20:17 UTC, valerybugakov commented on yarn.lock
> +anymatch@*, anymatch@^3.0.3, anymatch@~3.1.1:
It seems that we had this issue in the `main` branch. Merging it into this branch should fix the problem.

2021-12-24 09:01 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
Thanks, we pushed the changes for update RouterLink AnchorLink implementations, we are going to make sure:

- Components in `client/web` use RouterLink only
- Components in `client/browser` use AnchorLink only

But not sure about components in `client/shared` package since they are used in both `client/web` and `client/browser`, could you help to clear it?

cc @oleggromov

2021-12-24 10:12 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
@gitstart-sourcegraph, I went through components using `<Link />` in the `shared` package, and it seems that all of them should use `RouterLink` except for `ActiveExtensionsPanel`. Let me know if I missed something here. Otherwise, let's update components accordingly.

2021-12-24 10:13 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
@valerybugakov Thanks, would do that. BTW it seems that we can't access buildkite for `contractors/*` prefix branch anymore

2021-12-24 10:17 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
@valerybugakov ah when you are here, I want to confirm the <Link /> usages in `ButtonLink`, the css rules of `AnchorLink` override all css from `btn`, what do you think if we update `.anchor-link` to `.anchor-link:not(:global(.btn))`?

2021-12-24 15:16 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
> Thanks, would do that. BTW it seems that we can't access buildkite for contractors/* prefix branch anymore

Responded in [the Slack channel](https://sourcegraph.slack.com/archives/C02D6RM6DFW/p1640358957058700).

2021-12-24 15:17 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
> what do you think if we update .anchor-link to .anchor-link:not(:global(.btn))?

Would it be possible to solve this issue in the `ButtonLink` component?

2021-12-25 17:44 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
It is causing UI visual changes, if you want to resolve this conflict in ButtonLink PR then we would use `Link` from `react-router-dom` directly (maybe keep the check for absolute url also). What do you think?

2021-12-26 16:01 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
@valerybugakov while replacing `<Link />` in `client/web` with `<RouterLink />` we are getting a lot of error in unit tests `Invariant failed: You should not use <Link> outside a <Router>` since we uses `AnchorLink` in test setups before. Do you have any suggestions for this issue?

2021-12-26 16:20 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
@gitstart-sourcegraph, will using `renderWithRouter` in these problematic tests fix the problem?
Also, could you share the list of failing tests reported by `jest`?

2021-12-26 16:36 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
@valerybugakov Pushed last updates. You can get the list from SourceGraph pipeline. I think `renderWithRouter` would be good

2021-12-26 17:22 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink.tsx
> +    <Link to={to} {...rest} className={classNames(styles.anchor, className)}>
@gitstart-sourcegraph, it seems that the number of errors is small enough that we can quickly fix them with `renderWithRouter`. Let's try this approach.

2022-01-06 16:39 UTC, umpox reviewed
@valerybugakov @oleggromov Few thoughts:

Browser code: No router, use `AnchorLink`: Good
Web code: Has router, use `RouterLink`: Good
Shared code: Unknown router. Using `RouterLink` could result in a router `<Link />`: Bad

This seems like it could be a problem. If some extension code uses a relative path for a link then it would use React router unexpectedly. WDYT? Let me know if I'm missing anything. Maybe we still need a way to explicitly set the link type in some scenarios 🤔

2022-01-06 16:39 UTC, umpox commented on client/shared/src/components/FileMatchChildren.tsx
> +                <RouterLink
I want to understand this further:

These are shared components that can be used across browser extensions and web code. Can we be sure that we can safely use `RouterLink` here? Isn't there a possibility that this will render a React Router `<Link />` and cause problems in the extension code

2022-01-06 16:39 UTC, umpox commented on client/shared/src/components/LinkOrButton.tsx
> +        <RouterLink
Likewise here. This is a shared component. If I pass `to="/search"` or something from extensions code then it will use React router, I think

2022-01-07 02:59 UTC, gitstart-sourcegraph commented on client/shared/src/components/FileMatchChildren.tsx
> +                <RouterLink
yeah, we saw the problem with `Link` usages in `shared` package. How about using a hook like `useInRouterContext` to make we only render `Link` from `react-router-dom` in `<BrowserRouter>`

https://sourcegraph.com/github.com/remix-run/react-router@f16c5490dfa75f15dcfb86d2a981a7c58a9d1a33/-/blob/packages/react-router/index.tsx?L381:17#tab=references

2022-01-10 12:39 UTC, valerybugakov requested changes
Discussed the question above with @umpox on the call. The issue is that:

1. We already have some components in `shared` that rely on React-router.
2. They are used only inside of the `web` package and cannot be used elsewhere, so they shouldn't live in the `shared` package in the first place.

This PR gives us explicit `Link` components and removes the implicit global variable which is a great start. We will remove React-router components from the `shared` package as a part of https://github.com/sourcegraph/sourcegraph/issues/21847.

2022-01-10 12:39 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink/RouterLink.tsx
> +export function useInRouterContext(): boolean {
It seems that we don't need `export` here.

```suggestion
function useInRouterContext(): boolean {
```

2022-01-10 12:39 UTC, valerybugakov commented on client/wildcard/src/components/Link/RouterLink/RouterLink.tsx
> +        const shouldUseAnchor = !isInRouter || (typeof to === 'string' && isAbsoluteUrl(to))
What do you think about throwing an error here in the development environment if `RouterLink` is used outside of the `react-router` context? It seems that we don't have a need for such usage, and we can safely ban it. It will keep links component usage more transparent.

```ts
if (process.env.NODE_ENV === 'development' && !isInRouter) {
  throw new Error('Please use the `AnchorLink` component outside of `react-router`')
}
```

Let me know if I missed any use-cases that will break in with this logic.

2022-01-10 19:15 UTC, valerybugakov requested changes
Sorry I didn't clarify. With the error thrown in the development mode we can remove the `shouldUseAnchor` logic altogether and always render `Link` in the `RouterLink` component.

2022-01-11 04:16 UTC, gitstart-sourcegraph commented
> Sorry I didn't clarify. With the error thrown in the development mode ...

@valerybugakov Related to `Link` components, current version of `ButtonLink` uses `RouterLink` but it seems that we are using `ButtonLink` in both `web` and `browser` (deps `ButtonLink` <- `ActionItem` <- `HoverOverlay`). Could you suggest which Link component we should use in `ButtonLink`?

2022-01-11 10:40 UTC, valerybugakov reviewed
> it seems that we are using `ButtonLink` in both `web` and `browser`.

@umpox, @gitstart-sourcegraph, you're right. It seems that we need to preserve the `Link` compatibility with the usage outside of the `react-router` context to use them inside of other reusable components. And it seems that `setLinkComponent` is the best solution, even though it would be great to eliminate this implicit global variable. 😕 Checking if we're in the `react-router` context in runtime would work, but there's no way to do it efficiently (without the `useContext` subscription) and without relying on private API (`__RouterContext`).

Going back and forth here, because the initial proposal didn't work: 
1. Move `Link` and `setLinkComponent` component from `client/shared/src/components/Link.tsx` to `client/wildcard/src/components/Link/Link.tsx`.
2. Remove `useInRouterContext` logic from `RouterLink`.
3. Go back to using `Link` in consumer packages like `web`, `browser`, and `shared` with corresponding `setLinkComponent` calls using either `RouterLink` or `AnchorLink` from the `wildcard` package. 

Let me know if it looks reasonable.

2022-01-11 16:41 UTC, gitstart-sourcegraph commented
@valerybugakov Sure, we would follow your suggestions. And I think we should keep the check for absolute url like what we had before

2022-01-13 17:20 UTC, gitstart-sourcegraph commented on .github/workflows/label-notify.yml
> +                  team/devops=@daxmc99 @JenRed777 @danieldides
Should revert this change
```suggestion
                  team/devops=@sourcegraph/cloud-devops
```

2022-01-14 15:03 UTC, valerybugakov commented on client/web/src/nav/NavBar/NavDropdown.module.scss
> +    --link-hover-decoration: none;
Are these variables required here in addition to what we had because of the higher `AnchorLink` CSS rule specificity?

2022-01-14 16:33 UTC, umpox reviewed
@gitstart-sourcegraph For browser extension code, we need to ensure that we do _not_ load the custom CSS for the `AnchorLink` component. Please can we add some logic to allow this to be configured with a `branded` prop? We already do this for the Badge component here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/wildcard/src/components/Badge/Badge.tsx#L55:1-56:1

2022-01-14 16:36 UTC, umpox commented on client/web/src/tree/components/TreeRowLabel.tsx
> +import type { LinkProps } from '@sourcegraph/wildcard/src/components/Link'
Do you mean from the root file, so it'd be possible to write `import type { LinkProps } from '@sourcegraph/wildcard`?

Maybe, I wanted to limit the amount of exports from the root so it was easier for consumers to find components with autocomplete. WDYT? I'm hoping that most consumers won't need to use these types directly

2022-01-14 18:14 UTC, gitstart-sourcegraph commented on .github/workflows/lsif-ts.yml
> -          - client/http-client
Should revert this change

2022-01-14 18:17 UTC, gitstart-sourcegraph commented on client/web/src/nav/NavBar/NavDropdown.module.scss
> +    --link-hover-decoration: none;
Yeah, but we can ignore these changes  with using `:where()` pseudo-class

2022-01-15 03:53 UTC, gitstart-sourcegraph commented on client/web/src/repo/RevisionsPopover/components/ConnectionPopoverNodeLink/ConnectionPopoverNodeLink.module.scss
> +    color: var(--text-muted) !important;
@valerybugakov  Thanks for that great suggestions. Updated module css with `:where` selector

2022-01-17 09:17 UTC, valerybugakov commented on client/browser/src/shared/code-hosts/bitbucket/codeHost.module.scss
> +    }
It should be redundant after the introduction of the `branded={false}` prop.

2022-01-17 09:17 UTC, valerybugakov commented on client/web/src/tree/components/TreeRowLabel.tsx
> +import type { LinkProps } from '@sourcegraph/wildcard/src/components/Link'
@umpox, it would be good to avoid referencing internal files of the `wildcard` package like it's done here:
`import type { LinkProps } from '@sourcegraph/wildcard/src/components/Link'`. Ideally, we want to always rely on the main entry point `@sourcegraph/wildcard` or others that we explicitly define.

2022-01-17 10:01 UTC, valerybugakov submitted a review, later dismissed
Almost there! One important change required:

We need to rename the `useBrandedBadge` prop to `useBrandedStyles` in the `HoverOverlay` component and use it for both `Badge` and `Link` used in `ActionItem` to avoid using our `Link` styles in the browser extensions.

2022-01-17 11:17 UTC, gitstart-sourcegraph commented
@valerybugakov for `... use it for both Badge and Link used in ActionItem to avoid using our Link styles in the browser extensions...`, does it mean to support `branded` prop in `ActionItem` and pass it down to all <Badge /> <Link /> usages and make sure that prop is false in `browser`

2022-01-17 16:54 UTC, valerybugakov commented
@gitstart-sourcegraph, I'll look into how we can orchestrate the `branded` prop for `ActionItem`. I will experiment locally with the branch and come back to you.

2022-01-19 17:25 UTC, valerybugakov commented
Hey @tjkandala, we're looking into introducing `WildcardThemeProvider` to differentiate between branded and non-branded environments and later provide themes to components without prop drilling. [Here's](https://github.com/sourcegraph/sourcegraph/pull/28837/commits/1528283878a1feb1af44d9a51a7b25740e6ec7f0) the first step where we add a dummy React context. Could you take a look and let us know if you see any limitations?

2022-01-19 18:30 UTC, tjkandala approved these changes
Just reviewed 1528283878a1feb1af44d9a51a7b25740e6ec7f0, the approach looks good and I can't think of any limitations atm!

2022-01-20 09:15 UTC, umpox approved these changes
Looking forward to getting this merged :)

2022-01-20 09:25 UTC, merged