Wildcard V2: `<Tooltip />` Implementation
sourcegraph/sourcegraph pull request #28887
Opened 2021-12-11 16:25 UTC by gitstart-sourcegraph

## Wildcard implementation of the `` component.
### See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context

## Acceptance criteria
- [x] Component is implemented within Wildcard
- [x] Component has tests
- [x] Component is accessible
- [x] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)

## Refs
* [Gitstart Task](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27691) 
* [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/27691)

## Implementation details
1. Move [the existing implementation](https://github.com/sourcegraph/sourcegraph/blob/main/client/branded/src/components/tooltip/Tooltip.tsx) to [the Wildcard package](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard).
2. Extract styles required for the component from Bootstrap to a CSS module:
    - Extract classes from `node_modules/bootstrap/scss/_tooltip.scss` into a component CSS module.
    - Merge our [tooltip global styles](https://github.com/sourcegraph/sourcegraph/blob/main/client/branded/src/global-styles/tooltips.scss) with the newly created CSS module.
    - Merge our [tooltip SCSS variables](https://github.com/sourcegraph/sourcegraph/blob/b1d4bfaa0a580f2c74c643a428c92e7c4893bac6/client/branded/src/global-styles/index.scss#L37-L41) with the newly created CSS module.
    - Feed CSS module classes to [the Reactstrap Tooltip implementation](https://github.com/reactstrap/reactstrap/blob/master/src/Tooltip.js) to avoid relying on the global `.tooltip` class.
2. Move `client/branded/src/components/tooltip/Tooltip.story.tsx` ([link](https://storybook.sgdev.org/?path=/story/branded-tooltip--hover)) to the new component folder and update it to match other stories in the Wildcard package.
3. Use [the `<button>` component](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard/src/components/Button) as a blueprint for the new component.

2021-12-20 12:08 UTC, valerybugakov requested changes

2021-12-20 12:08 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +// such as forceUpdate defined below.
Would it be possible to extract this functionality into an object that would expose component methods to avoid preserving the class component wrapper? I'm thinking about something like this:

```tsx
type TooltipInstance = Pick<UseTooltipState, 'forceUpdate'>

export class TooltipController {
  private instance: TooltipInstance | undefined
  
  public setInstance(instance?: TooltipInstance) {
    this.instance = instance
  }

  public forceUpdate() {
      this.instance?.forceUpdate()
  }
}

const Tooltip = () => {
  const { forceUpdate, ...state } = useTooltipState()
  
  // Can be integrated into `useTooltipState` logic.
  useEffect(() => {
    TooltipController.setInstance({ forceUpdate })
    
    return () => {
      TooltipController.setInstance()
    }
  }, [])
  
  // render logic of the Tooltip component...
}
```

Let me know if I missed any critical details and it's a feasible solution.

2021-12-20 12:08 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.module.scss
> +    :global(.arrow) {
To avoid keeping the global `arrow` class around, we can use `arrowClassName` exposed by the Reactstrap [component](https://github.com/reactstrap/reactstrap/blob/37a63c673269bcd6eb3a7331583afa94113b73f6/src/TooltipPopoverWrapper.js#L24).

2021-12-20 12:08 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.module.scss
> +    &:global(.show) {
Would it be possible to scoped `popperClassName` instead of the default global `show` class?

https://github.com/reactstrap/reactstrap/blob/37a63c673269bcd6eb3a7331583afa94113b73f6/src/Tooltip.js#L13-L16

2021-12-20 12:08 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.test.tsx
> +jest.mock('popper.js', () => {
Does it make sense to move this mock to the global set up to avoid having such issues in other tests?
Similar to `client/shared/dev/mockUniqueId.ts`.

2021-12-21 00:25 UTC, courier-new commented
Hey there! This is super exciting to see. I was wondering if it would be possible as part of this effort to upgrade reactstrap to the latest version? I think we're currently on 8.9.0 and the latest is 9.0.1. We're interested in using a new feature of the `Collapse` component in Batch Changes that was introduced in 9.0.0, but we found that when we tried to upgrade, it actually broke the tooltips.

2021-12-21 11:17 UTC, valerybugakov commented
@courier-new, thank you for letting us know about this! 

I agree with the plan proposed by @gitstart-sourcegraph — let's upgrade in a separate PR to avoid blocking this PR. @gitstart-sourcegraph, could you create an issue for yourself with that task?

2021-12-21 19:06 UTC, courier-new commented
Absolutely, I think that's a great plan! Thank you both for supporting this! Do you mind tagging me in the issue once you've created it so that I may follow along as well?

2021-12-22 10:45 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Tooltip/Tooltip.story.tsx
> +                    needed.)
Agreed @valerybugakov, however that was the existing behaviour, which has not been changed on this PR.
would you like this to be changed

2021-12-22 12:23 UTC, AlicjaSuska commented
Thank you for working on this! Would it be possible to add all the tooltip variants to the storybook:
- pointer on the left, right, top, bottom
- case showing the max width of the tooltip (tooltip with long text). I think that max-width is 256px as far as I remember

2021-12-23 14:07 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.story.tsx
> +                    needed.)
If you know how to fix it right away, let's address it. If it requires longer than 30 mins investigation, let's do it in a separate PR.

2021-12-23 14:13 UTC, valerybugakov requested changes

2021-12-23 14:13 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +    private static instance: TooltipInstance | undefined
Nice! Did you have a chance to test this controller locally?

2021-12-23 14:13 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/useTooltipState.tsx
> +import { TooltipController } from './Tooltip'
This dependency create a circular reference between `Tooltip.tsx` and `useTooltipState.tsx `. Let's extract `TooltipController` into a separate file to avoid that.

2021-12-23 14:13 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/useTooltipState.tsx
> +            console.log(event.type)
Let's ensure that we don't commit extra logs used for development purposes.
```suggestion
```

2021-12-24 05:08 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +    private static instance: TooltipInstance | undefined
Yeah. we added a story for demo it

2021-12-24 05:34 UTC, gitstart-sourcegraph commented
Thanks @AlicjaSuska We updated stories for all positions and max width case

2021-12-24 10:26 UTC, valerybugakov approved these changes
LGTM!
Let's address minor comments and merge without additional review.

2021-12-24 10:26 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.story.tsx
> +            url: 'https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=3131%3A38534',
It seems that this link is outdated and doesn't point to the tooltips frame. 

cc @sourcegraph/design, it would be awesome to update links in our stories in case you move/rename frames in Figma. Ideally, we should have automation for that, but manual updates would help for now.

2021-12-24 10:26 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.story.tsx
> +const ForceUpdateTooltip = () => {
Thanks for adding this story!

2021-12-24 10:26 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +    ) : null
Minor suggestion to avoid duplicate default value setting and simplify the return statement.

```suggestion
    const { subject, content, subjectSeq, placement = 'auto', delay } = useTooltipState()

    if (!subject || !content) {
        return null
    }

    return (
        <BootstrapTooltip
            // Set key prop to work around a bug where quickly mousing between 2 elements with tooltips
            // displays the 2nd element's tooltip as still pointing to the first.
            key={subjectSeq}
            isOpen={true}
            target={subject}
            placement={placement as Popper.Placement}
            // in order to add our own placement classes we need to set the popperClassNames
            // here is where bootstrap injects it's placement classes such as 'bs-tooltip-auto' automatically.
            popperClassName={classNames(
                styles.tooltip,
                styles.show,
                className,
                getTooltipStyle(placement as Popper.Placement)
            )}
            arrowClassName={styles.arrow}
            innerClassName={styles.tooltipInner}
            // This is a workaround to an issue with tooltips in reactstrap that causes the entire page to freeze.
            // Remove when https://github.com/reactstrap/reactstrap/issues/1482 is fixed.
            modifiers={TOOLTIP_MODIFIERS}
            delay={delay}
        >
            {content}
        </BootstrapTooltip>
    )
```

2021-12-24 10:26 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +                getTooltipStyle((state.placement ?? 'auto') as Popper.Placement)
Would it be possible to set the return type of the `getTooltipStyle` to `Popper.Placement` to avoid this type-casting?

2021-12-24 10:33 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Tooltip/Tooltip.story.tsx
> +            url: 'https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=3131%3A38534',
@valerybugakov It still works

2021-12-24 10:41 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.story.tsx
> +            url: 'https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=3131%3A38534',
Shoot, you're right. It works for me now.

2021-12-24 10:47 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +                getTooltipStyle((state.placement ?? 'auto') as Popper.Placement)
Since we are getting  `placement ` from html attribute, so we have to use casting `string` to `Popper.Placement` at least in `getPlacement`, but I think it's better

2021-12-24 11:00 UTC, valerybugakov commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +                getTooltipStyle((state.placement ?? 'auto') as Popper.Placement)
Do you mean we can do it in the `getPlacement` function?

2021-12-24 11:20 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Tooltip/Tooltip.tsx
> +                getTooltipStyle((state.placement ?? 'auto') as Popper.Placement)
we applied changes, could you take a quick look about this

2021-12-24 11:40 UTC, valerybugakov approved these changes
The updated `Tooltip` component looks much simpler now, thanks!

2021-12-24 12:24 UTC, merged

2021-12-24 13:02 UTC, valerybugakov commented
@gitstart-sourcegraph, somehow the `<Card />` component got into this PR, while it's still in the pull request [here](https://github.com/sourcegraph/sourcegraph/pull/28764). Could you take a look?