: Wildcard V2: <Icon /> ImplementationContractors/sg 27667Contractors…
sourcegraph/sourcegraph pull request #28886
Opened 2021-12-11 14:15 UTC by gitstart-sourcegraph

### Wildcard implementation of the <Icon /> component.

See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context
## Acceptance criteria

- [x] Component is implemented within Wildcard
- [x] Component has tests
- [x] Component is accessible
- [ ] Component matches [Figma designs](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1)

## Refs
* [Gitstart Task](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27667) 
* [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/27667)

## Implementation details

1.  Add new <Icon /> to the Wildcard package.
    - A wrapper component that receives svg and applies the icon-inline class.
    - Copy [the existing global styles](https://github.com/sourcegraph/sourcegraph/blob/main/client/shared/src/global-styles/icons.scss) to the component CSS module.
    - Remove redundant classes that we don't use in the codebase.
2.  Create a basic Storybook story that shows component usage.
3.  Use [the <Button /> component](https://github.com/sourcegraph/sourcegraph/tree/main/client/wildcard/src/components/Button) as a blueprint for the new component.
4.  Component API:

`<Icon svg={CloudOutlineIcon} />`

2021-12-15 17:15 UTC, valerybugakov requested changes

2021-12-15 17:15 UTC, valerybugakov commented on client/wildcard/src/components/Icon/Icon.tsx
> +interface IconProps {
```suggestion
import styles from './Icon.module.scss'

interface IconProps {
```

2021-12-15 17:15 UTC, valerybugakov commented on client/wildcard/src/components/Icon/Icon.story.tsx
> +export const Simple = () => (
```suggestion
import { Story } from '@storybook/react'

export const Simple: Story = () => (
```

2021-12-15 17:15 UTC, valerybugakov commented on client/wildcard/src/components/Icon/Icon.story.tsx
> +            url: 'https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=908%3A1',
Does it point to a specific Icon frame in Figma? It opens the frame with Form Elements for me.
If we don't have a relevant Figma frame, let's delete this configuration parameter.

2021-12-16 18:49 UTC, gitstart-sourcegraph commented
Hi @valerybugakov requested fixes has been added. Thanks

2021-12-17 16:26 UTC, valerybugakov approved these changes
✅

2021-12-17 16:27 UTC, valerybugakov approved these changes
Oh, I see that there's a failed CI check. If it's infrastructure issue, let's restart the job to ensure that it's green before merging.

2021-12-20 20:34 UTC, merged