Enabling fuzzy finder to be GA
sourcegraph/sourcegraph pull request #29010
Opened 2021-12-14 20:41 UTC by Numbers88s

## 🤔  Description

Makes Fuzzy Finder Generally Available

## 🔖  Relevant tickets

Fixes #29009  

## 🚀  GIF
_What gif best describes this PR or how it makes you feel?_

![shortcut](https://media.giphy.com/media/qXW2FiKwNGs8owkz3G/giphy.gif)

2021-12-14 20:46 UTC, Numbers88s commented on client/shared/src/settings/settings.ts
>          fuzzyFinderCaseInsensitiveFileCountThreshold?: number
Hey @olafurpg I noticed we don't actually use this `fuzzyFinderCaseInsensitiveFileCountThreshold` in the FuzzyFinder component. Did you have plans to expand on this feature or should I just take it out?

2021-12-15 07:24 UTC, olafurpg commented on client/shared/src/settings/settings.ts
>          fuzzyFinderCaseInsensitiveFileCountThreshold?: number
This threshold is used here
```
client/web/src/search/input/SearchNavbarItem.tsx
96:    const { fuzzyFinder, fuzzyFinderCaseInsensitiveFileCountThreshold } = getExperimentalFeatures(
129:                    caseInsensitiveFileCountThreshold={fuzzyFinderCaseInsensitiveFileCountThreshold}
```
This is only activated for very large repos (like chromium/chromium) where case-insensitive fuzzy matching becomes too fuzzy.

2021-12-15 07:24 UTC, olafurpg approved these changes
LGTM 👍 :letsgo:!

2021-12-15 07:45 UTC, olafurpg requested changes
I just observed a regression that must have happened recently, the fuzzy finder no longer fetches filenames for the current revision. I opened an issue https://github.com/sourcegraph/sourcegraph/issues/29032 and we should fix this before making it GA.

2021-12-15 21:07 UTC, Numbers88s commented on client/shared/src/settings/settings.ts
>          fuzzyFinderCaseInsensitiveFileCountThreshold?: number
right, and it gets passed to the fuzzyFinder but we don't pass it or use it within the fuzzyFinder.
```javascript
  return (
          <FuzzyModal
              repoName={repoName}
              commitID={commitID}
              initialMaxResults={DEFAULT_MAX_RESULTS}
              initialQuery=""
              downloadFilenames={downloadFilename}
              isLoading={isLoadingFilename}
              isError={filenameError}
              onClose={() => props.setIsVisible(false)}
              fsm={fsm}
              setFsm={setFsm}
          />
      )
```

2021-12-16 22:33 UTC, Numbers88s commented
> 

Hey @olafurpg fixed the issue highlighted on [#29032](https://github.com/sourcegraph/sourcegraph/issues/29032) on this PR. It's now good to be re-reviewed.

2021-12-17 07:17 UTC, olafurpg approved these changes
Awesome! Custom revisions are working now. LGTM 👍

2021-12-17 09:10 UTC, olafurpg commented
The puppeteer error seems related https://buildkite.com/sourcegraph/sourcegraph/builds/122176#e6eea611-3144-4627-bebd-22d98ac29150/6-16
```
    Error: GraphQL query "FileNames" has no configured mock response. Make sure the call to overrideGraphQL() includes a result for the "FileNames" query:
```

2021-12-17 09:39 UTC, olafurpg commented
The latest commit didn't seem to help with the puppeteer changes so I have no clue how to fix, and I'm not sure how to reproduce the failures locally. Any ideas @Numbers88s ?

2021-12-17 22:52 UTC, Numbers88s commented
> The latest commit didn't seem to help with the puppeteer changes so I have no clue how to fix, and I'm not sure how to reproduce the failures locally. Any ideas @Numbers88s ?

I looked everywhere, need to talk to another dev more familiar with CI. This will be the first thing I do when I get back 👍

2021-12-17 23:22 UTC, limitedmage requested changes

2021-12-17 23:22 UTC, limitedmage commented on schema/settings.schema.json
> -        },
We can't remove anything from this schema, just mark is as deprecated. If we remove it from the schema, there will be type errors trying to parse settings that still contain this key.

I personally think that we should NOT remove this yet. Instead, we should switch the feature to be on by default, and let users disable it with the experimental feature. Once it's been on by default for a while (eg. 6 months, though there's not really a hard rule on this) we can remove the feature flag check and mark the experimental feature as deprecated.

Both of these changes (setting the feature on by default, and then deprecating the feature flag) also needs to be accompanied by changelog entries.

2021-12-17 23:24 UTC, limitedmage reviewed
(removing my "request changes" status so that I don't block this PR while I'm out for the holidays :) )

2021-12-17 23:24 UTC, Numbers88s commented on schema/settings.schema.json
> -        },
Thank you! @limitedmage Cool good to know, I'll look into the changelog entries when I get back from holidays. Thanks again!

2022-01-03 21:11 UTC, Numbers88s commented on schema/settings.schema.json
> -        },
Hi @limitedmage I added them back and added the changelog entry. Let me know if this is what you meant or if I am missing something and thank you. Hope you had a good holiday too.

2022-01-05 15:23 UTC, olafurpg approved these changes
LGTM 👍 

Sidenote: it would have been nice to separate the bugfix from the actual config changes. The diff is quite complicated right now when it should have been a simple config change to enable the fuzzy finder by default.

2022-01-05 20:25 UTC, Numbers88s commented
> LGTM 👍
> 
> Sidenote: it would have been nice to separate the bugfix from the actual config changes. The diff is quite complicated right now when it should have been a simple config change to enable the fuzzy finder by default.

Yeah, agreed. I won't lump them together next time. 👍

2022-01-07 01:13 UTC, limitedmage approved these changes

2022-01-07 01:13 UTC, limitedmage commented on schema/settings.schema.json
> +          "description": "DEPRECATED: Enables fuzzy finder with keyboard shortcut `t`.",
If this isn't deprecated yet (since the changelog entry implies this flag still works, just that it's enabled by default), we shouldn't have `DEPRECATED` in the description until it's non-functional.

2022-01-07 05:00 UTC, merged