Update references of `deploy-sourcegraph-dot-com` to `deploy-sourcegraph-cloud`
sourcegraph/sourcegraph pull request #29016
Opened 2021-12-14 22:39 UTC by danieldides

The `deploy-sourcegraph-dot-com` repository is being renamed to `deploy-sourcegraph-cloud`. This PR will resolve any references to the old repository.

https://github.com/sourcegraph/sourcegraph/issues/28319

[_Created by Sourcegraph batch change `daniel.dides/rename-dot-com-to-cloud`._](https://k8s.sgdev.org/users/daniel.dides/batch-changes/rename-dot-com-to-cloud)

2021-12-14 23:22 UTC, danieldides commented
I'm not sure we want to update the `internal/cmd/tracking-issue/testdata/fixtures.json` file in this PR. It looks like some sort of historical data.

2021-12-14 23:47 UTC, daxmc99 commented on internal/cmd/tracking-issue/testdata/fixtures.json
>        "Title": "code insights: backend MVP implementation",
Might want to drop this diff since it could break some test data?

2021-12-14 23:48 UTC, daxmc99 requested changes
Looks like a test-data change was picked up here, we should drop that

2021-12-15 05:03 UTC, danieldides commented on internal/cmd/tracking-issue/testdata/fixtures.json
>        "Title": "code insights: backend MVP implementation",
Apologies for all the emails you got from the CLA-bot as I fought with Git on the new computer. This should have been removed from the PR.

2021-12-15 15:23 UTC, daxmc99 approved these changes

2021-12-15 15:23 UTC, merged