Extract util/errors.ts into a new common package
sourcegraph/sourcegraph pull request #29040
Opened 2021-12-15 11:58 UTC by gitstart-sourcegraph

## Description
As part of the process of Extracting non-UI modules from the shared package into a new workspaces, extract the `util/errors.ts` module into a new common package

## Refs
[SG Issue](https://github.com/sourcegraph/sourcegraph/issues/21847)
[Gitstart Issue](https://app.gitstart.com/clients/sourcegraph/tickets/SG-28892)

## Time estimate

- Pull requests with ~450 lines changed should take **3 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

2021-12-17 17:08 UTC, valerybugakov requested changes

2021-12-17 17:08 UTC, valerybugakov commented on client/common/README.md
> +### This package contains common files
```suggestion
# Common utilities

Generic utilities without any specific domain.
This package should not depend on any other Sourcegraph monorepo package.
```

2021-12-17 17:08 UTC, valerybugakov commented on client/common/jest.config.js
> +  collectCoverage: false, // Collected through Puppeteer
Oh, this should not be here. Let's remove this line from the `build-config` package too.

```suggestion
```

2021-12-17 17:08 UTC, valerybugakov commented on client/common/package.json
> +  "description": "Sourcegraph Common Files",
```suggestion
  "description": "Sourcegraph common utilities",
```

2021-12-17 17:08 UTC, valerybugakov commented on client/shared/tsconfig.json
> +  "include": ["**/*", ".*", "./src/**/*.json", "/client/common/**/*.ts"],
```suggestion
  "include": ["**/*", ".*", "./src/**/*.json"],
```

2021-12-17 17:08 UTC, valerybugakov commented on client/shared/tsconfig.json
>    "exclude": ["../../node_modules", "./node_modules", "./out", "./src/end-to-end"],
A reference should be added to every package that uses `@sourcegraph/common`. Would you please double-check other packages and update `tsconfig.json` accordingly?

```suggestion
  "exclude": ["../../node_modules", "./node_modules", "./out", "./src/end-to-end"],
  "references": [{ "path": "../common" }],
```

2021-12-17 17:08 UTC, valerybugakov commented on tsconfig.all.json
> +    { "path": "client/common" },
`.github/workflows/lsif-ts.yml` should be updated to include a new package.

2021-12-21 12:34 UTC, gitstart-sourcegraph commented
Hi @valerybugakov  updated with requested changes

2021-12-23 15:15 UTC, valerybugakov requested changes
I see that Percy failed with the issue already addressed in the `main` branch. Let's merge the `main` branch to ensure that CI checks are green.

2021-12-23 15:15 UTC, valerybugakov commented on client/common/src/errors/types.ts
> +export interface ErrorLike {
```suggestion
import { AGGREGATE_ERROR_NAME } from './constants'

export interface ErrorLike {
```

2021-12-23 15:15 UTC, valerybugakov commented on yarn.lock
> +anymatch@*, anymatch@^3.0.3, anymatch@~3.1.1:
Let's merge the `main` branch into this PR to ensure that this redundant change goes away. It shouldn't be present in the diff.

2021-12-24 10:29 UTC, valerybugakov approved these changes
Thanks!

2021-12-24 10:50 UTC, merged