Update github.md
sourcegraph/sourcegraph pull request #29264
Opened 2021-12-20 21:36 UTC by DaedalusG

Let customers know default branch is configurable on a repos github page, and is respected in default search results

2021-12-20 21:45 UTC, indradhanush requested changes
It's not guaranteed that the default branch will be named `master`, so we should just mention `default branch` as the phrase and not use a specific name.

Also left minor suggestions for brevity and punctuation. Thank you for the PR!

2021-12-20 21:45 UTC, indradhanush commented on doc/admin/external_service/github.md
> +GitHub uses the master branch as the default branch of a repository. This means that searches targeting a synched github repo will automatically default to results from the master branch. If however
```suggestion
GitHub uses the default branch of a repository for searches and the search results will be shown from the default branch. If you'd like the search results to be displayed from another branch by default, you may [change a repo's default branch on the github repo settings page](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch). If this is not an option, consider using [search contexts](https://docs.sourcegraph.com/code_search/how-to/search_contexts) instead. 
```

2021-12-20 22:25 UTC, DaedalusG commented on doc/admin/external_service/github.md
> +GitHub uses the master branch as the default branch of a repository. This means that searches targeting a synched github repo will automatically default to results from the master branch. If however
Thanks for the clarifications!

2021-12-21 00:15 UTC, Kelvin-Lee commented on doc/admin/external_service/github.md
> +Sourcegraph displays search results from the default branch of a repository when no `revision:` parameter is specified. If you'd like the search results to be displayed from another branch by default
Suggest to throw a link to the documentation on the "`revision:`" portion of the first sentence:

https://docs.sourcegraph.com/code_search/reference/queries#repository-revisions

2021-12-21 00:21 UTC, DaedalusG commented on doc/admin/external_service/github.md
> +Sourcegraph displays search results from the default branch of a repository when no `revision:` parameter is specified. If you'd like the search results to be displayed from another branch by default
Link added ✅

2021-12-21 08:08 UTC, unknwon approved these changes
Could you give this PR a better title?

2021-12-21 12:42 UTC, indradhanush approved these changes

2021-12-21 12:42 UTC, merged

2021-12-21 16:51 UTC, amberfurbush0317 reviewed
Looks good Warren!!