- Get rid of Bootstrap style imports
sourcegraph/sourcegraph pull request #29287
Opened 2021-12-21 19:20 UTC by gitstart-sourcegraph

## Problem
We depend on Bootstrap styles in our global styles a lot. But we don't plan to move forward with Bootstrap because we're working on our design system called Wildcard. To ease the transition to our styles and gain more control over visual changes, we want to move Bootstrap styles that we need into our codebase and eventually drop Bootstrap dependency.

## Refs
[Gitstart Task](https://app.gitstart.com/clients/sourcegraph/tickets/SG-29253)

## Success criteria
All Bootstrap CSS rules that we need are incorporated in our codebase.PR.

## Implementation details
Let's start with these SCSS files and create a separate PR for each one:

1. `client/branded/src/global-styles/nav.scss`

Notes:

1. We want to migrate away from SCSS variables to CSS variables when we bring Bootstrap styles to our codebas
- Some Bootstrap SCSS variables redefined on our side are located here: `client/branded/src/global-styles/index.scss`. Keep that in mind while migrating to CSS variables.

2. We don't need to bring all styles defined in the imported Bootstrap package. Check what styles do we use in the codebase first.

## Time estimate

- Pull requests with ~450 lines changed should take 6 hours at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.

- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

2022-01-10 14:08 UTC, valerybugakov requested changes

2022-01-10 14:08 UTC, valerybugakov commented on client/branded/src/global-styles/nav.scss
> +        @extend %container-flex-properties;
Because we do not need to keep other global classes that reuse `%container-flex-properties`, can we inline CSS rules instead of using SCSS features here?

2022-01-10 16:51 UTC, gitstart-sourcegraph commented on client/branded/src/global-styles/nav.scss
> +        @extend %container-flex-properties;
Thanks @valerybugakov , pushed changes to inline css rules and remove that reference

2022-01-11 11:51 UTC, valerybugakov approved these changes
Thanks!

2022-01-11 12:42 UTC, merged