Ag/rm new subscription btn
sourcegraph/sourcegraph pull request #29296
Opened 2021-12-21 23:17 UTC by anthonygedeon

## Context
Removes the `New Subscription` button and updates the body copy of the product component

## Result
![image](https://user-images.githubusercontent.com/47023801/147009814-97cf2d74-8059-45d3-b1ab-40caf71fdc09.png)

Closes #28987

2021-12-22 00:31 UTC, anthonygedeon commented
@sourcegraph/contribution-reviewers

2022-01-06 12:08 UTC, oleggromov requested changes
There's a copy change (typo) I requested.
Other than that, and suggested removal of changes to the `yarn.lock` file, it's all good. 

The reason why you aren't able to see this page/button locally is because it's required to be logged in. Not sure if that's possible via `sg start oss` - will check. Regardless, the change is correct. Thanks for your contribution! 👍

2022-01-06 12:08 UTC, oleggromov commented on client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
> +                        Conatct us to purchase a subscription for a self-hosted Sourcegraph instance. See{' '}
There's a typo:
```suggestion
                        Contact us to purchase a subscription for a self-hosted Sourcegraph instance. See{' '}
```

2022-01-06 12:08 UTC, oleggromov commented on yarn.lock
> +anymatch@*, anymatch@^3.0.3, anymatch@~3.1.1:
I think changes to `yarn.lock` shouldn't be part of this change as we a) try to keep PRs related to a single change and b) aim to update dependencies in an organized way.

Please let me know if updating to the latest main and running `yarn` are causing these - and in any case, please remove changes from this file from the PR.

2022-02-01 15:08 UTC, oleggromov commented
Due to inactivity here, I am closing this PR and opening a new one without the mentioned issues: https://github.com/sourcegraph/sourcegraph/pull/30490

2022-02-01 15:08 UTC, closed without merging