WIP
sourcegraph/sourcegraph pull request #29308
Opened 2021-12-22 16:41 UTC by ryanslade

2022-01-13 18:09 UTC, tsenart approved these changes
Please add backend integration tests in this PR as well. https://github.com/sourcegraph/sourcegraph/blob/main/dev/gqltest/search_test.go

2022-01-13 18:09 UTC, tsenart commented on cmd/frontend/graphqlbackend/search_results.go
> +			perms, err := authz.ActorPermissions(ctx, checker, a, content)
I think we could make this more performant by batching requests to the DB, rather than doing 1 per Match.

2022-01-13 18:09 UTC, tsenart commented on cmd/frontend/graphqlbackend/search_results.go
> +		// user so we'll return generic error and log something more specific.
Can we instead just make sure that the errors we return don't contain sensitive data?

2022-01-14 01:28 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +			perms, err := authz.ActorPermissions(ctx, checker, a, content)
Is it possible we could do even better by evaluating the permissions in advance, then just checking a file path against the permissions object in the returned closure? I'd be concerned about even a single db request per stream event.

2022-01-14 01:28 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +	return func(e streaming.SearchEvent) (streaming.SearchEvent, error) {
The returned function should probably take `ctx` as an argument rather than closing over a context, otherwise we're listening for events on a context that might be different than the context that this function is actually executed under.

2022-01-14 07:30 UTC, keegancsmith reviewed
agree with the current inline comments around perf. IE the filter func needs to be smart.

Any concerns around errors from backends containing path information? I don't think this is something that is currently possible, but just a thought :)

2022-01-14 08:55 UTC, ryanslade commented on cmd/frontend/graphqlbackend/search_results.go
> +			perms, err := authz.ActorPermissions(ctx, checker, a, content)
The checker that is passed in does a bunch of caching already. The first request per user will fetch all their sub-repo perms, build the rules and cache them. This is a cache that persists between requests and expires after a short period, currently 10 seconds. What this means is that we expect at most one db request every 10 seconds per frontend instance, per user. 

https://github.com/sourcegraph/sourcegraph/blob/main/internal/authz/sub_repo_perms.go#L221

2022-01-14 12:00 UTC, ryanslade commented
@tsenart I'm struggling to figure out how to do the backend integration tests. 

I've tried modifying [this test](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/graphqlbackend/search_test.go#L30) but the issue is that Zoekt isn't mocked so we get an error like this:

```
RepoUniverseText search failed: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

I assume I need to somehow mock out Zoekt itself using a fake searcher but I'm not sure where the best place to do that is? Maybe somehow injecting it into he `searchResolver`?

2022-01-14 15:22 UTC, ryanslade commented
I'm working on a test that just uses the resolver directly which should be enough to test that the pieces are hooked up correctly.

2022-01-14 16:23 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +			perms, err := authz.ActorPermissions(ctx, checker, a, content)
Ah, I see. Thanks for clarifying. I was thinking the checker was just a db instance, but this makes sense. 

In that case, I expect performance here to be good enough, but that's assuming the sync overhead of the cache isn't significant. I don't think that's a given in this case, considering that the sync primitives are going to be hit pretty hard since the cache is shared across all requests, and will be hit for every stream event in the process (as opposed to being scoped to the request, like most of our stuff that needs synchronization). 

TL;DR: please do some performance analysis when this rolls out to check that it doesn't adversely affect search speed/latency. This might be an ideal case to use a rollout feature flag on sourcegraph.com so it can easily be enabled/disabled.

2022-01-14 18:12 UTC, tsenart commented
> @tsenart I'm struggling to figure out how to do the backend integration tests.

When say backend integration tests, I mean https://github.com/sourcegraph/sourcegraph/blob/main/dev/gqltest/search_test.go

2022-01-17 09:48 UTC, ryanslade commented
> > @tsenart I'm struggling to figure out how to do the backend integration tests.
> 
> When say backend integration tests, I mean https://github.com/sourcegraph/sourcegraph/blob/main/dev/gqltest/search_test.go

🤦

2022-01-18 16:31 UTC, ryanslade commented
In order to get the backend integration tests to pass I'm going to need to introduce some new API's in our GraphQL layer that extend our explicit permissions API. That way the integration tests can do some permissions setup before running. 

Since that is going to be a bigger change and will mostly be touching other parts of the code I'm going to do it as a separate PR and merge this one.

2022-01-19 19:29 UTC, camdencheek requested changes

2022-01-19 19:29 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +			content := authz.RepoContent{
@ryanslade My apologies for waiting this long for this comment, but I didn't really read myself in on this whole sub-repo permissions thing until now.

This section is problematic for two reasons:
1) `Key()` isn't _really_ meant to be introspected on. This is my bad for failing to document this, but its intent is to be an opaque, unique key for a search result for deduping/merging results. There are no guarantees to its contents except its use for that purpose.
2) Because of (1), the value of `Path` on the key does not do what you need it to do here. This approach will work alright for `FileMatch` results, but for repo results and commit results, `Path` will be empty. This might be fine for repo results (assuming an empty path is okay), but for commit results, our `CommitMatch` type does not currently contain information about what files the commit modifies.

Looking at the logic in [another PR](https://github.com/sourcegraph/sourcegraph/pull/29771/files) for adding sub-repo perms to listing commits, it appears this information is necessary to do this correctly. 

TBH, I'm not entirely sure what the permission model is for sub-repo filtering of commits. Are users allowed to see commit messages for commits that modify a blocked file? If a commit modifies a blocked file, are users still allowed to see the portion of the diff that doesn't apply to that file?

2022-01-19 19:44 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +			content := authz.RepoContent{
(I made a low effort attempt to make `key()` private at some point but ran into an issue and gave up. Worth revisiting since this tendency to use `Key` recurred)

2022-01-19 20:11 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
> +			content := authz.RepoContent{
I realize I requested changes here without a clear path forward, so feel free to ping me to chat through some options here. I expect it will require some changes to commit/diff search in order for the needed information to be available here.

2022-01-20 17:59 UTC, ryanslade commented
Note to self:

We can do a type assertion against search matches so they we don't use the generic key.

For file matches we have a path.
Repo matches can be ignored since existing repo filtering takes care of this. 
Commit matches will be handled by including a set of paths modified by the commit, as mentioned in https://github.com/sourcegraph/sourcegraph/issues/29988

2022-01-20 17:59 UTC, ryanslade commented on cmd/frontend/graphqlbackend/search_results.go
> +			content := authz.RepoContent{
See this note: https://github.com/sourcegraph/sourcegraph/pull/29308#issuecomment-1017771634

2022-01-24 18:36 UTC, mollylogue commented
@ryanslade Are you planning to do a follow-up PR with filtering commits? Or are you planning to do that as part of this PR?

2022-01-25 08:27 UTC, ryanslade commented
@mollylogue My plan is to merge https://github.com/sourcegraph/sourcegraph/pull/30109 first and then come back to this PR and change it so that it doesn't use `Key()` anymore.

2022-01-31 11:33 UTC, ryanslade commented
I've now merged the change that includes modified files in commit matches but after merging those changes as well as changes in `main` there's an issue: 

The aggregator no longer has the `Error` field so I'm not sure what we should do when we encounter an error performing sub-repo filtering. Before, we were able to set the `Error` field so that it could bubble up.

@camdencheek any ideas?

2022-01-31 14:08 UTC, camdencheek commented
Aah shoot. That was me. Forgot you were using that. Moving into `doResults` sounds like a good spot to me.

2022-01-31 16:41 UTC, tsenart commented
> Aah shoot. That was me. Forgot you were using that. Moving into doResults sounds like a good spot to me.

@camdencheek: Could this be a Job middleware, now that we have this infrastructure?

2022-01-31 16:46 UTC, camdencheek commented
@tsenart Yes, absolutely, but I'm not going to ask @ryanslade to rewrite this PR to make that happen. I'll followup with a PR converting this to a job wrapper since I'm actively chipping away at `doResults` and friends anyways

2022-01-31 16:50 UTC, ryanslade commented
> @tsenart Yes, absolutely, but I'm not going to ask @ryanslade to rewrite this PR to make that happen. I'll followup with a PR converting this to a job wrapper since I'm actively chipping away at `doResults` and friends anyways

Thanks, appreciate that 😄

2022-01-31 16:53 UTC, ryanslade commented
@camdencheek PTAL

I'm about to stop for the day so wanted to give you a chance to give this a look.

The only thing I still want to do is add a couple more cases to `TestApplySubRepoFiltering`

2022-01-31 18:00 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results.go
>  	agg := run.NewAggregator(stream)
This is a problematic bit. When we create a new aggregator with a non-nil stream, we don't actually aggregate the results, we stream them as they come, only aggregating stats about the results. This means the `matches` on line 1834 will (usually) be `nil`. Confusing, I know, but we're actively working on making this more intuitive 😄 

I took the liberty of making [a PR](https://github.com/sourcegraph/sourcegraph/pull/30419) against this branch that moves the filter step to a stream func so the results are filtered before they ever hit the aggregator. This way, whether or not the aggregator actually aggregates the results, they will still run through the filter.

2022-01-31 18:24 UTC, camdencheek commented on internal/authz/sub_repo_perms.go
> +		perms, err = checker.Permissions(ctx, a.UID, c)
I don't think there is any need to pre-declare perms and err here

```suggestion
	c := RepoContent{
		Repo: repo,
	}

	for _, p := range paths {
		c.Path = p
		perms, err := checker.Permissions(ctx, a.UID, c)
```

2022-02-01 09:12 UTC, ryanslade commented on internal/search/result/file.go
> +// - A result representing the whole file (len(Symbols) == 0 && len(LineMatches) == 0)
Thanks GoLand for making all the typos jump out at me while reading code :)

2022-02-01 10:22 UTC, ryanslade commented
@camdencheek Thanks again for all your assistance with this PR, PTAL

2022-02-01 16:14 UTC, merged