Add link unfurl query to GraphQL API
sourcegraph/sourcegraph pull request #29343
Opened 2021-12-28 15:09 UTC by tjkandala

Closes #15735 (onboarding task for @vdavid).

TODO
- [x] Add query to GraphQL schema
- [x] Make HTTP request for URL
- [ ] Parse HTML and return relevant meta tags
- [ ] Follow redirects when making a request to the URL
- [ ] Add tests
- [ ] Add caching

This endpoint will be used by the [link-preview-expander](https://github.com/sourcegraph/sourcegraph-link-preview-expander/tree/HEAD) Sourcegraph extension.

2022-01-04 19:15 UTC, vdavid commented
Probably should've written my progress report here rather than under the bug, so copying it here:

---

I'm done with all features except:
 - **Validation:** I've noticed this among the requirements: "Validate the input as a valid URL". Not sure if this needs to be explicit or if it's OK if the endpoint accepts random garbage (as it does) without throwing an error.
 - **Some tests:** The HTTP fetching and Redis caching parts are not covered with tests yet. With my current skills, it'd take me an amount of time that I'd find hard to justify, plus I'd probably not do it the right way on my own.
 - **Standardization:** I'll need an in-depth review because I assume that I did a few things in an odd/non-standard way. This is my first bunch of commits at Sourcegraph and my first time coding Go independently. I'm pretty sure that I failed to follow some best practices. I'd be happy to get feedback and learn.
 - **References vs. values**: I'll especially need advice on this topic: the `LinkMetadata` struct having pointer fields allowed me to return `nil` instead of empty strings (a practice that the Go website encourages), but it caused me to use two dozen lines of boilerplate code which I don't like. Not sure about the best choice here.
 - **Function order**: Another area where I'll need specific advice is an order of functions in a Go file that's consistent with the codebase. I haven't found guidelines for this.

2022-01-04 22:27 UTC, slimsag commented on cmd/frontend/graphqlbackend/link_metadata_test.go
> +		}
This code is perfect, but just an FYI that in some cases others here have found a little library I wrote for snapshot testing useful: https://github.com/hexops/autogold

you definitely don't need to use it, just figured I'd mention it in case you find it interesting (it'd save you from writing all these if/else statements)

2022-01-04 22:28 UTC, slimsag commented on cmd/frontend/graphqlbackend/link_metadata.go
> +		log15.Debug("Saving to cache: ", "url", url)
FYI, we usually prefix all log statements with something, such as `link_metadata: <message>` otherwise when you actually want to find these logs in Stackdriver or elsewhere.. good luck 😛

2022-01-04 22:29 UTC, slimsag commented on cmd/frontend/graphqlbackend/link_metadata.go
> +		}
FYI a common practice in Go is to drop the else, so in this case you would just `return linkMetadata, true` without any `else` block. the same is true for the `// Cache miss` case below

2022-01-04 22:30 UTC, slimsag requested changes
.

2022-01-04 23:35 UTC, slimsag commented
So first of all, great work on the code here and everything. It looks pretty great! And also, nice work deciphering that issue/ticket.. it took me a couple of minutes to figure out / understand what this change is supposed to do from a product point of view.

Unfortunately, and this is 100% not your fault at all @vdavid, we gave you a bad first issue to work on and I'm really sorry this is the first code review you will get from me.. let me know if you want to chat about anything I say below, as for next steps I think those really are not on you at all, we should chat as a team about how to move forward on this

I hope this doesn't deter you from asking me for code review in the future - normally I'm much more of a brief review + stamp of approval kind of person 😉

Buckle up because we're going on a little ride..

## Context

The motivation behind this change appears to be making this [link preview expander](https://github.com/sourcegraph/sourcegraph-link-preview-expander) work out of the box. Currently, it appears customers who wish to use this must deploy, manage, and secure their own [cors-anywhere proxy service](https://github.com/Rob--W/cors-anywhere) and configure the extension to point to it. This adds friction and securing that service is _really hard_.

Previously, [I had blocked a PR from @tjkandala](https://github.com/sourcegraph/infrastructure/pull/2209#pullrequestreview-510790952) which tried to resolve this same issue by relaxing our own cors-anywhere deployment to send requests to any URL (which is a major security risk)

From what I can tell, after I blocked that PR a few stakeholders (and an ex-security team member) [discussed](https://github.com/sourcegraph/sourcegraph/issues/15584) and came to the solution which you and TJ implemented here.

However, this approach is still quite dangerous and would introduce a security vulnerability to Sourcegraph.

## Problem

What this change does is enable anyone with access to Sourcegraph's GraphQL API to issue a `linkMetadata("some url")` request, and in turn get back:

* The OpenGraph metadata preview image
* The page title
* The page description

On its own, this probably doesn't sound like harmful information to expose, and so I'm not surprised that we ended up here and thought this would be a safe approach (in fact, this is how blind SSRF vulnerabilities happen in most cases!)

## How this can be exploited

### With other vulnerable services

Suppose that Sourcegraph is ran behind a firewall with other trusted services on the network, but some of those other services are vulnerable.

1. If there is a service `http://docs.mycompanyinternal.net` which is vulnerable to the log4j exploit, for example, but it is assumed to be protected because we put it behind a firewall and only a very small team and other services on our network have access to it, this vulnerability in Sourcegraph can be used to exploit the service now: an attacker (a malicious employee with access to Sourcegraph, or an outsider who got access to Sourcegraph through some other exploit) can now use the Sourcegraph GraphQL API to issue a request to `http://docs.mycompanyinternal.net?log4jpayload` which would have normally been blocked by the firewall. Because Sourcegraph is on the same network, the request goes through and we have now assisted in this remote code execution exploit of the docs site.

2. If there is a service `http://api.mycompanyinternal.net` which accepts API requests and does not correctly reject non-POST requests (surprisingly common), an attacker could use this GraphQL API in order to determine that `api.mycompanyinternal.net` is actually a very standard service, for example, and issue a GET request to `http://api.mycompanyinternal.net/?delete_all_data` and wipe out company data.

You might be asking "but how common is that really? That would depend on other services in the network being vulnerable!" but in fact, this is exactly the reason that web browsers had to implement CORS in the first place: to ensure protection of the server receiving requests within intranets! :) Perhaps most notably vulnerable [were devices like printers](http://hacking-printers.net/wiki/index.php/Cross-site_printing), but still today too many random services are vulnerable.

### Without other vulnerable services

Even without other services in the network being vulnerable, this could still be used by an attacker via the information we're exposing: page title, description, and preview image.

Some examples:

1. If you're a contractor at Pear, inc. you could issue GET requests to a super secret team's metrics server, `http://grafana.bizops.pear.internal` and get preview images of metrics dashboards, bypassing the firewall rules put in place to prevent potentially malicious contractors like you from accessing those super-secret metrics.

2. If you're a trusted employee at Pear, Inc. but due to SOC2 compliance should not be able to have any access to the billing team's JIRA instance, you could merely use the Sourcegraph extension and hover over a `http://jira.billing.pear.internal` link and now you've seen billing info via the JIRA page title/description. This becomes an urgent compliance security issue with Sourcegraph that customers will raise.

## Solution space

There is _no_ solution in which we can safely deploy a service to bypass CORS of arbitrary URLs within a customer's network. It is literally the reason why browsers have CORS today, it is just flat out not safe to issue requests to arbitrary internal URLs on the network without fully respecting the CORS protocol.

There exist only two safe solutions in this space:

1. Site admins must explicitly list URLs for which it is OK for Sourcegraph to issue requests to.
2. OR, we must run such an API service ourselves in a very secure network on Sourcegraph.com and people's private Sourcegraph instances reach out to that hosted API in order to perform such requests. This is likely a non-practical option for two reasons:
    a. This is hard to secure on our end, [there may even be k8s and Google Cloud internal endpoints that could make us vulnerable in running such a service](https://madhuakula.com/kubernetes-goat/scenarios/scenario-3.html)
    b. From a privacy POV, we probably cannot do this: "when I hover over some code in Sourcegraph it makes requests to Sourcegraph.com and sends information only available in my code (URL parameters, etc.) We cannot allow our code to leave our network."

And so I arrive at my ultimate question: how much do we really want this link preview feature? 😝

2022-01-05 10:44 UTC, vdavid commented on cmd/frontend/graphqlbackend/link_metadata.go
> +		log15.Debug("Saving to cache: ", "url", url)
It makes absolute sense. Thanks for that info!

2022-01-05 10:48 UTC, vdavid commented on cmd/frontend/graphqlbackend/link_metadata.go
> +		}
Sure, thanks, noted.

2022-01-05 10:49 UTC, vdavid commented on cmd/frontend/graphqlbackend/link_metadata_test.go
> +		}
That's pretty neat, I'll remember it for next time.

2022-01-05 11:35 UTC, vdavid commented
Wow, thanks for the elaborate description and for catching these vulnerabilities. It makes a lot of sense.
After [reading a bit more](https://httptoolkit.tech/blog/cors-proxies/) on the topic, I also can't see other solutions than the current "deploy and manage your own CORS proxy" and the proposed allow-list restriction.

2022-03-07 20:09 UTC, closed without merging