Use scoped styles for the `<Button />` component
sourcegraph/sourcegraph pull request #29347
Opened 2021-12-28 16:32 UTC by gitstart-sourcegraph

## Description

The` </button><button>` component relies on the CSS module located in the same folder as the React component.

## Refs

[SourceGraph issue](https://github.com/sourcegraph/sourcegraph/issues/29316)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-29316)

2022-01-11 12:25 UTC, valerybugakov requested changes

2022-01-11 12:25 UTC, valerybugakov commented on client/wildcard/src/components/Button/Button.module.scss
> +}
Since we use it only in one place, we can inline these styles, and also, let's use only rem value in the same way as it's done in the Typography PR.

2022-01-11 12:25 UTC, valerybugakov commented on client/wildcard/src/components/Button/Button.module.scss
> +    @extend %label-base !optional;
Let's inline this.

2022-01-11 12:25 UTC, valerybugakov commented on client/wildcard/src/components/Button/Button.module.scss
> +    @extend %label-base-small !optional;
Let's inline this.

2022-01-13 09:08 UTC, valerybugakov reviewed
@gitstart-sourcegraph, we have quite a few unexpected changes in Percy and Chromatic diffs. Could you take a look at the root cause? Moving styles to CSS modules should not affect the UI in this PR.

2022-01-18 17:53 UTC, gitstart-sourcegraph commented
Hi @valerybugakov 
Based on creation of moduled button styles, Some  bootstrap style rules such as `btn-group` does not apply based since it attempts to select `.btn` elements in a `btn-group` wrapper.
would like to get your thoughts on Creating wildcard wrapper components, for such use cases. e.g creating a `ButtonGroup` component, to replace usage of `btn-group` className.

2022-01-19 16:56 UTC, valerybugakov commented
@gitstart-sourcegraph, sounds good. I see you have already started working on the implementation of the `ButtonGroup` component

2022-01-21 10:24 UTC, valerybugakov requested changes

2022-01-21 10:24 UTC, valerybugakov commented on .github/workflows/buildchecker.yml
> +      - run: ./dev/buildchecker/run.sh
Is it redundant?

2022-01-21 10:24 UTC, valerybugakov commented on client/web/src/components/externalServices/AddExternalServicesPage.module.scss
> +    border-color: #f8f9fa;
Could you clarify where this color comes from?

2022-01-21 10:24 UTC, valerybugakov commented on client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.module.scss
> +// Should be removed during the Button bootstrap migrations.
Should it be removed when we drop the button styles button Bootstrap import?

2022-01-21 10:24 UTC, valerybugakov commented on client/web/src/enterprise/insights/components/creation-ui-kit/live-preview-container/LivePreviewContainer.module.scss
> +        color: #959ba7;
It seems that these colors are used in multiple places after the migration. Could you clarify why do we need them?

2022-01-21 10:24 UTC, valerybugakov commented on client/wildcard/src/components/Button/Button.module.scss
> +.btn-group,
Ideally, `btn-group` styles should live a separate component. We don't have examples of referencing classes from other CSS modules, so it might be problematic. We can keep things as is and look into splitting them up later.

2022-01-21 10:24 UTC, valerybugakov commented on client/wildcard/src/components/index.ts
> +export { Button, ButtonGroup } from './Button'
Let's export components interfaces along with components.

2022-01-22 17:17 UTC, raph941 commented on client/wildcard/src/components/Button/Button.module.scss
> +.btn-group,
Okay, got it. was added this way to prevent having to replace usage of nested `.btn` selector with an element selector `button`, based on dynamic module naming, To support use cases of non `button` element `Button`(s).

2022-01-22 17:26 UTC, raph941 commented on client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.module.scss
> +// Should be removed during the Button bootstrap migrations.
Yes. Based on bootstrap styling, default button(no variant) should use this color (i believe would be added during migration), however if we apply that now, it would  override colors on some unmigrated buttons, which uses bootstrap classes such as `btn-primary` to apply variant styles.
i.e if `--body-color` is added as default, this would be redundant (with no side effect for non-removal)

2022-01-22 17:27 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.module.scss
> +// Should be removed during the Button bootstrap migrations.
Yes. Based on bootstrap styling, default button(no variant) should use this color (i believe would be added during migration), however if we apply that now, it would  override colors on some unmigrated buttons, which uses bootstrap classes such as `btn-primary` to apply variant styles.
i.e if `--body-color` is added as default, this would be redundant (with no side effect for non-removal)

2022-01-22 17:28 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Button/Button.module.scss
> +.btn-group,
Okay, got it. was added this way to prevent having to replace usage of nested `.btn` selector with an element selector `button`, based on dynamic module naming, To support use cases of non `button` element `Button`(s).

2022-01-23 19:37 UTC, gitstart-sourcegraph commented on client/web/src/components/externalServices/AddExternalServicesPage.module.scss
> +    border-color: #f8f9fa;
colors came from bootstrap's `.btn-light` style rule, reflected on the existing version of this button.

2022-01-24 17:05 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/insights/components/creation-ui-kit/live-preview-container/LivePreviewContainer.module.scss
> +        color: #959ba7;
This was added as the lighter shade of the btn-icon color, for the disabled state (from previous implementation). This has now been extracted into `Button.module.scss` and removed other occurrences

2022-01-27 14:59 UTC, valerybugakov commented on client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.module.scss
> +// Should be removed during the Button bootstrap migrations.
Let's wait for the https://github.com/sourcegraph/sourcegraph/pull/30096, which migrates almost all `Button` usages. After that, we should be able to delete these styles.

2022-01-28 08:03 UTC, gitstart-sourcegraph commented
@valerybugakov kindly help review changes on PR.

2022-01-31 07:41 UTC, valerybugakov requested changes
Should we be able to remove modules like `OldCreateBatchChangeContent.module.scss ` since https://github.com/sourcegraph/sourcegraph/pull/30096 is merged?

2022-02-01 06:35 UTC, gitstart-sourcegraph commented
@valerybugakov.
Considering the `Button` component is on active development / modification on other PRs, we keep getting merge conflicts => review changes => failing tests ..., we need to keep updating over and over. WDYT about pausing update in the mean time? Or fix all needed changes and get it merged?

2022-02-01 09:40 UTC, valerybugakov reviewed
@gitstart-sourcegraph, it's not under active development, and the @sourcegraph/frontend-platform doesn't have any ongoing work related to it. The conflicts result from the unexpected work that another team introduced to address their needs. I see that it slows down work on this PR, but after addressing current merge conflicts and removing redundant styles, the PR will be ready for merging.

2022-02-02 06:59 UTC, gitstart-sourcegraph commented
@valerybugakov 
conflict has been resolved and redundant styles removed. kindly take a look.

2022-02-02 09:53 UTC, valerybugakov requested changes
Could you fix the unexpected change reported by Chromatic?

<img width="955" alt="Screen Shot 2022-02-02 at 12 53 12" src="https://user-images.githubusercontent.com/3846380/152131382-43d8e403-3653-4ff0-99f3-9c0658434ab3.png">

2022-02-02 10:00 UTC, valerybugakov commented on client/web/src/enterprise/code-monitoring/components/actions/EmailAction.tsx
> +                    className={classNames('mr-2', styles.testEmailBtn)}
Could you clarify why this change is required?

2022-02-02 10:00 UTC, valerybugakov commented on client/web/src/components/externalServices/AddExternalServicesPage.module.scss
> +.btn-light {
Would it be possible to overcome this issue by using themes in selectors?

```scss
:global(.theme-light) .btn-light,
:global(.theme-dark) .btn-light {

2022-02-02 11:28 UTC, gitstart-sourcegraph commented on client/web/src/components/externalServices/AddExternalServicesPage.module.scss
> +.btn-light {
This worked along with more selectors to increase specificity

2022-02-02 11:28 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/code-monitoring/components/actions/EmailAction.tsx
> +                    className={classNames('mr-2', styles.testEmailBtn)}
Change reverted now

2022-02-02 13:18 UTC, valerybugakov requested changes
Could you share why the force-push was required? Can we help somehow to avoid that on our end? It's hard to review changes after it because the scope of the PR is quite big. Easy to miss small things like `console.log`.

2022-02-02 13:18 UTC, valerybugakov commented on client/web/src/enterprise/batches/create/OldCreateBatchChangeContent.tsx
> +    console.log({ name: sample.name, active })
Is it redundant?

2022-02-02 13:18 UTC, valerybugakov commented on client/web/src/enterprise/code-monitoring/CodeMonitorList.tsx
> -
Is it redundant?

2022-02-02 13:18 UTC, valerybugakov commented on client/web/src/enterprise/code-monitoring/components/FormActionArea.module.scss
> +.test-email-btn {
Should we remove this class after removing the reference to `styles.testEmailBtn`?

2022-02-02 15:12 UTC, gitstart-sourcegraph commented
@valerybugakov issue was caused due to issues from our system, team looking into it at the moment :pray:

2022-02-03 07:52 UTC, valerybugakov approved these changes
Thanks!

2022-02-03 09:19 UTC, merged