wildcard: implement Typography components
sourcegraph/sourcegraph pull request #29377
Opened 2021-12-31 13:41 UTC by gitstart-sourcegraph

## Description: 

Implement typography components: `Text`, `Label`, `Code`, and `H1`-`H6` in `wildcard` package

## Refs
- [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/27674)
- [GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27674)

## Implementation details

Suggestions for every component:

1. Use styles defined in `client/branded/src/global-styles/typography.scss` and merge them with Bootstrap styles `node_modules/bootstrap/scss/_type.scss` required for these elements.  
2. Feel free to drop unused CSS rules based on our [text mockups](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=5601%3A65477).
3. Consider extracting and extending base interfaces such as `TypographyProps`.

### 1. Headings

Create components for each HTML heading from `h1` to `h6`: e.g., `<H1 />`.

Each should have `props` typed as follows:

```tsx
interface H1Props extends React.HTMLAttributes<HTMLHeadingElement> {
    as?: React.ElementType;
    alignment?: 'left' | 'center' | 'right';
    mode?: 'default' | 'single-line' | 'break-word';
}
```

Check out the discussion in comments to learn about `alignment` and `mode`.

### 2. Text

Create `<Text />` component with the following API:
```tsx
interface TextProps extends React.HTMLAttributes<HTMLParagraphElement> {
    size?: 'small' | 'base';
    weight?: 'regular' | 'medium' | 'bold';
    as?: React.ElementType;
    alignment?: 'left' | 'center' | 'right';
    mode?: 'default' | 'single-line' | 'break-word';
}
```

- The `<p />` element tag should be used internally by default. 
- Small styles should use only `rem` value in `font-size` rule instead of the current `calc(min(...))` logic.
- `<strong /> ` element tag should be used in case of `weight="bold"`.

Check out the discussion in comments to learn about `alignment` and `mode`.

### 3. Label

Create `<Label />` component with the following API:
```tsx
interface LabelProps extends React.HTMLAttributes<HTMLLabelElement> {
    size?: 'small' | 'base';
    weight?: 'regular' | 'medium' | 'bold';
    alignment?: 'left' | 'center' | 'right';
    mode?: 'default' | 'single-line' | 'break-word';
    isUnderline?: boolean;
    isUppercase?: boolean;
}
```

- The `<label />` element tag should be used internally. 

### 4. Code

Create `<Code />` component with the following API:
```tsx
interface CodeProps extends React.HTMLAttributes<HTMLElement> {
    size?: 'small' | 'base';
    weight?: 'regular' | 'medium' | 'bold';
}
```

2021-12-31 13:51 UTC, gitstart-sourcegraph commented
Hello @valerybugakov @oleggromov 
As part of the Implementation process of `Typography` components, can we go ahead to extract styles of base elements such as `h1---h6, label ...` from `bootstrap` into css module files and use class like `styles.h1` in cmponents

2022-01-05 16:22 UTC, umpox commented
@gitstart-sourcegraph Yes please do!

2022-01-11 12:18 UTC, valerybugakov requested changes

2022-01-11 12:18 UTC, valerybugakov commented on client/wildcard/src/components/Typography/typography.module.scss
> +    font-size: calc(min(0.75rem, #{(11/12)}em));
From the issue description: 

> Small styles should use only rem value in font-size rule instead of the current calc(min(...)) logic.

2022-01-11 12:18 UTC, valerybugakov commented on client/wildcard/src/components/Typography/Text/Text.tsx
> +        const Component: React.ElementType<any> = AsComponent ?? (weight === 'bold' ? 'strong' : 'p')
After playing around with the implementation I noticed that `weight="bold"` changes layout properties of the `Text` component making it an `inline` element.  Maybe it's better to stick with the predictable approach for now and always use `p`. Consumers will be able to alter the tag via `as` prop if needed.

2022-01-11 12:18 UTC, valerybugakov commented on client/wildcard/src/components/Typography/typography.module.scss
> +small,
We can probably remove the `small` selector from here since we always apply the `.small` class where required.

2022-01-11 12:18 UTC, valerybugakov commented on client/wildcard/src/components/Typography/typography.module.scss
> +    @extend %small;
`%small` is not reused anywhere so we can inline these styles here.

2022-01-11 12:18 UTC, valerybugakov commented on client/wildcard/src/components/Typography/Text/Text.module.scss
> +.small {
Does it make sense to use `.small` from `Typography.module.scss` in favor of this CSS module to ensure the consistent style of small text across typography components?

2022-01-11 12:18 UTC, valerybugakov commented on client/wildcard/src/components/Typography/index.ts
> +export * from './Text'
It would be nice to also export all typography components under one namespace to be able to use like this:

```tsx
import { Typography } from '@sourcegraph/wildcard'

const Consumer = () => (
  <Typography.H1>Hello world!</Typography.H1>
)

2022-01-13 05:54 UTC, gitstart-sourcegraph commented
Updated with requested changes

2022-01-13 11:43 UTC, valerybugakov reviewed
Thanks! Changes look good, with one additional request about Storybook story update.

2022-01-13 11:43 UTC, valerybugakov commented on client/wildcard/src/components/Typography/Code/Code.story.tsx
> +export const AllProperties: Story = () => (
It's a bit hard to navigate stories for different typography components compared to what we have [for global text styles](https://storybook.sgdev.org/?path=/story/branded-global-styles--text). Could you create one story similar to the one we have for global text styles that would be more human-readable, close to [our Figma mockup](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/Wildcard-Design-System?node-id=5601%3A65477) and showcases all different variations of new components?

<img width="838" alt="Screen Shot 2022-01-13 at 12 39 40" src="https://user-images.githubusercontent.com/3846380/149323802-48151e4f-0a11-4990-9a04-067a576ba9dd.png">

vs 

<img width="843" alt="Screen Shot 2022-01-13 at 12 40 19" src="https://user-images.githubusercontent.com/3846380/149323883-27af3fc7-7eff-4a70-b499-326f16296a99.png">

Let me know if you see any issues with that.

2022-01-17 06:58 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Typography/Code/Code.story.tsx
> +export const AllProperties: Story = () => (
Updated now

2022-01-17 10:07 UTC, valerybugakov approved these changes
@gitstart-sourcegraph, awesome, thanks! 

It seems that `Typography.story.tsx` shows all variations of the Typography components. So we can remove other stories to make exploration simpler. It looks ready for merge after this proposed deletion.

2022-01-17 15:08 UTC, merged