refactor: optimize Tooltip component
sourcegraph/sourcegraph pull request #29495
Opened 2022-01-07 02:29 UTC by gitstart-sourcegraph

## Description

- Refactor some functions used in Tooltip
- Optimize Tooltip component with Rxjs

## Refs:

- [SourceGraph issue](https://github.com/sourcegraph/sourcegraph/issues/29434)
- [GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-29434)

2022-01-19 15:26 UTC, umpox requested changes
@gitstart-sourcegraph These changes look good but there's definitely still a noticeable lag.

With tooltip:

![withtooltip](https://user-images.githubusercontent.com/9516420/150158313-8647a99f-bb95-4f10-a030-b7bf6534a046.gif)

Without tooltip:

![notooltip](https://user-images.githubusercontent.com/9516420/150158349-564c2c26-de57-45f3-ae62-e631014ac12b.gif)

I think this will require some further discussion with @sourcegraph/frontend-platform. There's a possibility that handling this many tooltips is a limitation of the current library (PopperJS). We'll soon be looking into alternatives that might fix this.

2022-01-19 15:26 UTC, umpox commented on client/web/src/repo/RepoRevisionSidebarSymbols.tsx
> +        <li className={styles.repoRevisionSidebarSymbolsNode} data-tooltip={node.name}>
```suggestion
        <li className={styles.repoRevisionSidebarSymbolsNode}>
```

2022-01-19 15:41 UTC, umpox approved these changes
Thanks!

2022-01-20 07:24 UTC, valerybugakov approved these changes

2022-01-20 07:27 UTC, merged