Link to docs on incoming webhooks
sourcegraph/sourcegraph pull request #29549
Opened 2022-01-10 23:10 UTC by DaedalusG

Quick addition of docs

2022-01-10 23:17 UTC, bobheadxi requested changes

2022-01-10 23:17 UTC, bobheadxi commented on doc/admin/observability/alerting.md
> +> _Note: Learn more about generating a [Slack incoming webhook URL](https://api.slack.com/messaging/webhooks)_
```suggestion

> NOTE: Learn more about generating a [Slack incoming webhook URL](https://api.slack.com/messaging/webhooks)
```

for the nicely rendered admonition :)

2022-01-11 17:00 UTC, bobheadxi approved these changes

2022-01-11 17:38 UTC, alexAtSourcegraph reviewed
Looks good to me! :)

2022-01-11 17:38 UTC, alexAtSourcegraph approved these changes

2022-01-12 07:48 UTC, merged