search: use minimal search arguments
sourcegraph/sourcegraph pull request #29559
Opened 2022-01-11 05:53 UTC by rvantonder

2022-01-12 17:07 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results_test.go
> +	test := func(input string) string {
Rewrote this test to detect the Job kind being generated for "global" searches, instead of looking at `mode`. `mode` will go away soon.

2022-01-12 17:15 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +	repoOptionsCopy := repoOptions
After _a lot_ of debugging, I realized `repoOptions` needs to be copied when passed to the two uses below. It was copied previous to this change, but I assumed it didn't need to be, but it does. It means `repoOptions` is mutated somewhere. I don't know how or why, I suspect it may be the `cursor` field.

2022-01-12 17:19 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> -func (r *searchResolver) toSearchInputs(q query.Q) (*search.TextParameters, []run.Job, error) {
Key change: `args search.TextParameters` is not used from this point forward where jobs are created, cutting off the dependency.

2022-01-12 17:20 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> -	tr.LazyPrintf("resultTypes: %s", args.ResultTypes)
`args.ResultTypes` no longer influence the kind of search running. This info is logged in aggregator, with the name of the search job running, which directly logs the "result types" of a search.

2022-01-12 17:37 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +		repoOptionsCopy := repoOptions
After _a lot_ of debugging, I realized `repoOptions` needs to be copied when passed to the two uses below (`repositoryResolver.Excluded` and `searchrepos.Resolver`). It was copied previous to this change, but I assumed it didn't need to be, but it does. It means `repoOptions` is mutated somewhere in one of the goroutines. I don't know how or why, I suspect it may be the `cursor` field.

2022-01-12 17:38 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results_test.go
> +		t.Skip("@rvantonder to restore or delete this test. Skipping because repo minimal list is no longer called via this mock.")
I'm not 100% sure why this test breaks yet, but it seems to not call the minimal list repos mock function after I moved the `toRepoOptions` call up the stack. I will investigate further, but since the actual backend tests pass, I'm assuming this is a mock issue. (any hunches welcome)

2022-01-13 04:19 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search_results.go
> +		repoOptionsCopy := repoOptions
cc @tsenart to confirm.

2022-01-13 04:26 UTC, keegancsmith approved these changes
LGTM. FYI I merged in main to your branch since it looks like there was a bad commit on main affecting your CI.

2022-01-13 04:26 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search_results.go
> +func (r *searchResolver) toSearchInputs(q query.Q) ([]run.Job, search.RepoOptions, time.Duration, error) {
should we have some local tuple type recording the 3 return values now? Looking at the call sites you pretty much always pass on the 3 values to evaluateLeaf or doResults. Seems like a type wrapping them up is deserved, even if just private? This is quite a long list of return values :)

2022-01-13 04:26 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/search_results_test.go
> +		t.Skip("@rvantonder to restore or delete this test. Skipping because repo minimal list is no longer called via this mock.")
your hunch sounds correct. Checking if a mock is called is always the most brittle of tests.

2022-01-13 17:51 UTC, tsenart commented on cmd/frontend/graphqlbackend/search_results.go
> +func (r *searchResolver) toSearchInputs(q query.Q) ([]run.Job, search.RepoOptions, time.Duration, error) {
+1 to @keegancsmith's suggestion

2022-01-13 17:54 UTC, tsenart commented on cmd/frontend/graphqlbackend/search_results.go
> +		repoOptionsCopy := repoOptions
Yep, it needs to be copied because pagination mutates the Cursor field. It's unfortunate this was such a trap. Ideas to prevent this from happening again that don't have a major perf hit?

2022-01-13 17:56 UTC, tsenart approved these changes

2022-01-14 01:51 UTC, camdencheek requested changes

2022-01-14 01:51 UTC, camdencheek commented on cmd/frontend/graphqlbackend/search_results_test.go
> +		t.Skip("@rvantonder to restore or delete this test. Skipping because repo minimal list is no longer called via this mock.")
It looks like the issue here isn't actually that the mock isn't called. The mock _is_ called, but it panics due to a failed assertion inside the mocked function, so the call is never registered, which causes the `mockrequire` call to fail later in the test. 

```
expected: []string{"r", "p"}
actual  : []string(nil)
```

It appears that `opt.IncludePatterns` changed. I don't think this is expected, and may be an actual issue with the change. I think it makes sense to resolve this test failure before merge rather than skipping the test. 

> Checking if a mock is called is always the most brittle of tests.

Agreed, but it also ensures that the test is actually doing what it looks like it's doing 🙂

2022-01-14 21:30 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +func (r *searchResolver) toSearchInputs(q query.Q) ([]run.Job, search.RepoOptions, time.Duration, error) {
> Looking at the call sites you pretty much always pass on the 3 values to evaluateLeaf or doResults

Yeah the other thing is we actually only need one or two of the 3 calls now, which would also lessen this effect. We also have other places in our code where 3+ return values exist.

But in general I think bundling in a new type is OK. I'm going to be militant about not bloating that type with more fields because some new feature addition thinks it is a convenient vehicle to pass state downstream though. Unfortunately Go has no built-in way for me to enforce this and stop such abuse. In general I want to avoid the tendency where "hey I'm looking for a type to jam my data into, this looks good" where the thinking should instead be "Ok should I process this data into something specific at this phase in the pipeline? Is it specific to a search job I care about? Or is it a runtime value? At what point should it be introduced? etc."

2022-01-14 21:35 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results_test.go
> +		t.Skip("@rvantonder to restore or delete this test. Skipping because repo minimal list is no longer called via this mock.")
It turns out there was a real issue causing this test to fail (but it also causes integration tests to fail, so I couldn't actually resolve this without the other). Thanks for pointing out that it's not a completely useless test though.

2022-01-14 21:37 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +			args.RepoOptions = repoOptions
@camdencheek this was the bug causing tests to fail. The problem is that the repo search job still relies on args (and `RepoOptions` being set in it). With the change, that was broken (and scarily, previously, we would set `RepoOptions` in args in `doResults`, "in time" for the repo search job. Not good.

2022-01-14 21:50 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +		repoOptionsCopy := repoOptions
Separate concerns with appropriate types. The separable concerns I see here are (a) static repo options and (b) runtime data types for actually resolving repos. Looking at the result of [`toRepoOptions`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/search_results.go?L505-517&subtree=true), which is the constructor for `RepoOptions` type, it explicitly initializes these fields:

```go
return search.RepoOptions{
   RepoFilters:       repoFilters,
   MinusRepoFilters:  minusRepoFilters,
   SearchContextSpec: searchContextSpec,
   UserSettings:      r.UserSettings,
   OnlyForks:         fork == query.Only,
   NoForks:           fork == query.No,
   OnlyArchived:      archived == query.Only,
   NoArchived:        archived == query.No,
   Visibility:        visibility,
   CommitAfter:       commitAfter,
   Query:             q,
   }
```

These are all static values derived from the query. But the type of `search.RepoOptions` is:

```go
struct {
    RepoFilters []string
    MinusRepoFilters []string
    CaseSensitiveRepoFilters bool
    SearchContextSpec string
    UserSettings *Settings
    NoForks bool
    OnlyForks bool
    NoArchived bool
    OnlyArchived bool
    CommitAfter string
    Visibility RepoVisibility
    Limit int
    Cursors []*Cursor
    Query Q
}
```

`Cursors` and `Limit` is never set by `toRepoOptions`. This suggests they're a separate concern (and since they are not initialized here, they are a later runtime concern). So the answer to my mind is to find the earliest point at which initializing cursors and limit is appropriate, and do it there. If these runtime values share a close relationship (e.g., used in the same place) as the static `RepoOptions`, then it suggests these members should both be part of another parent type (like [`RepoSearch`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@13e2c486b66f30c0f5a37faed80c60a6a3b47930/-/blob/internal/search/run/repository.go?L23:6&subtree=true) job which is the first point at which we combine static values and runtime execution).

```go
type struct RepoSearch {
  RepoOptions // only static, derived from query
  Cursor
  Limit
  // other stuff
}
```

Right now `RepoSearch` hasn't been cut down to its essential state yet though, and still relies on `args`, but that's the gist. Basically we should defer the notion of `cursor` to the type that actually encapsulates runtime concerns, and `RepoOptions` isn't the right type. This all comes back to that whole "avoid bloating the type" thing I'm talking about in https://github.com/sourcegraph/sourcegraph/pull/29559/files#r785181474.

2022-01-14 22:18 UTC, rvantonder commented
finally green https://buildkite.com/sourcegraph/sourcegraph/builds/125741#9a7ed439-5f36-49a2-b3d5-579b76637374

2022-01-14 22:23 UTC, camdencheek approved these changes

2022-01-14 23:30 UTC, merged

2022-01-14 23:30 UTC, rvantonder commented on cmd/frontend/graphqlbackend/search_results.go
> +func (r *searchResolver) toSearchInputs(q query.Q) ([]run.Job, search.RepoOptions, time.Duration, error) {
will do in follow up PR. lot's to simplify in this area of our code now