[SG-29436] wildcard: migrate reactstrap Dropdown usages to wildcard/Menu MenuItem
sourcegraph/sourcegraph pull request #29582
Opened 2022-01-11 17:30 UTC by gitstart-sourcegraph

## Description

- Migrate reactstrap Dropdown usages to wildcard/Menu MenuItem 

## Refs
* [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/29436)
* [Gitstart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-29436)

2022-02-01 15:03 UTC, umpox reviewed
It's looking good, have left some comments with a few things I've found!

2022-02-01 17:40 UTC, gitstart-sourcegraph commented on client/web/src/nav/NavBar/NavDropdown.tsx
>  import ChevronUpIcon from 'mdi-react/ChevronUpIcon'
I added changes to handle open sub nav menu with down arrow key, could you confirm that it matches expected behavior or not?

2022-02-03 11:39 UTC, valerybugakov commented
@gitstart-sourcegraph, is this PR ready for review?

2022-02-03 11:41 UTC, raph941 commented
> @gitstart-sourcegraph, is this PR ready for review?

yes @valerybugakov it's ready

2022-02-03 11:51 UTC, gitstart-sourcegraph commented
yes @valerybugakov it's ready

2022-02-03 12:39 UTC, valerybugakov requested changes

2022-02-03 12:39 UTC, valerybugakov commented on client/web/src/search/notebook/SearchNotebookPageHeaderActions.tsx
> +                    <MenuItem className="btn-danger" onSelect={() => setShowDeleteModal(true)}>
Would it be possible to use `Button` here to remove the `btn-danger` class?

```tsx
<MenuItem as={Button} variant="danger" ... />

2022-02-03 12:39 UTC, valerybugakov commented on client/wildcard/src/components/Menu/Menu.tsx
> +export const Menu: React.FunctionComponent<MenuProps> = ({ children, isOpen, onOpenChange, ...props }) => {
Would it be possible to use `ForwardReferenceComponent` for this component too?

2022-02-03 12:39 UTC, valerybugakov commented on client/wildcard/src/components/Menu/MenuList.tsx
> +)) as ForwardReferenceComponent<'div', MenuItemsProps & { popoverContentPosition?: Position }>
Let's extract `MenuItemsProps & { popoverContentPosition?: Position }` into the `PopoverProps` interface to be consistent with other components.

2022-02-03 12:39 UTC, valerybugakov commented on client/web/src/nav/MenuNavItem.tsx
> +export const MenuNavItem: React.FunctionComponent<MenuNavItemProps> = ({ children }) => (
If possible, let's use `ForwardReferenceComponent` for wildcard component types.

2022-02-03 16:05 UTC, gitstart-sourcegraph commented on client/web/src/search/notebook/SearchNotebookPageHeaderActions.tsx
> +                    <MenuItem className="btn-danger" onSelect={() => setShowDeleteModal(true)}>
Thanks for the suggestion, applying this would require some css rules to customize UI of `danger` `Button` .i.e. `font-weight` `text-align` `border`

2022-02-07 10:37 UTC, umpox reviewed
Almost there, some small changes

2022-02-07 10:37 UTC, umpox commented on client/web/src/nav/NavBar/NavDropdown.tsx
> +                case 'ArrowDown': {
```suggestion
                case 'Enter': {
                    history.push(toggleItem.path)
                    event.preventDefault();
                    return
                }
                case 'ArrowUp':
                case 'ArrowDown': {
```

This is the behavior we want. It'll match or normal Menu components and ensure that the dropdown doesn't open when the link is clicked

2022-02-07 10:38 UTC, umpox commented on client/web/src/nav/NavBar/NavDropdown.tsx
>  import ChevronUpIcon from 'mdi-react/ChevronUpIcon'
See my latest comment!

2022-02-07 15:59 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/searchContexts/SearchContextOwnerDropdown.tsx
>                      @{authenticatedUser.username} <span className="text-muted">(you)</span>
Issue resolved now

2022-02-07 15:59 UTC, gitstart-sourcegraph commented on client/web/src/nav/NavBar/NavDropdown.tsx
> +                case 'ArrowDown': {
Resolved

2022-02-11 05:03 UTC, gitstart-sourcegraph commented
@umpox I Update + refactor those stories a bit to use new form + chromatic viewPorts. Could you take a look before merging?

2022-02-11 10:30 UTC, merged