[SG-27728] Wildcard V2: `<Select />` Manual migration
sourcegraph/sourcegraph pull request #29672
Opened 2022-01-13 04:32 UTC by gitstart-sourcegraph

## Manual migration required to update our code to use the `<Select />` Wildcard component.
See [Wildcard V2 - Planned work](https://docs.google.com/document/d/1NisbJPiadtt5jQw4vUUYJOr8dD6Urwn5V0mVq2wt6bE/edit#heading=h.g4cw92w3ouhw) for more context.

Note: Before doing this, we should check if there is scope for a codemod to automate this migration. If so, the codemod should be implemented and ran before starting work on this issue.

## Refs
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/27728)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27728)

### Implementation
1. Find all remaining usage of the `<select>` element: https://sourcegraph.com/search?q=context:global+repo:github.com/sourcegraph/sourcegraph+%3Cselect&patternType=literal.
2. Replace with the `<Select />` Wilcard component: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@contractors/SG-27660/-/blob/client/wildcard/src/components/Form/Select/Select.tsx?utm_source=VSCode-1.4.0#L60:24

### Acceptance criteria.

- [x] All incorrect usage of the previous pattern has been updated to use the Wildcard component

2022-01-13 05:36 UTC, gitstart-sourcegraph commented
HI @valerybugakov @umpox ,
Currently, the `Select` component, supports string type label property, however for use cases [such as this](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/enterprise/batches/create/NamespaceSelector.tsx?L43#tab=references), would require using a Node element as label to prevent UI diff, some cases use cases also require, extra classNames on `Label` element. Kindly confirm preferred approach.

2022-01-13 17:47 UTC, valerybugakov reviewed
It seems that going with `Node` as an allowed type would be the easiest way to go without changing UI in different parts of the app. We can refactor all variations to `string` type in a follow-up PR if needed.

2022-01-14 18:39 UTC, limitedmage commented on client/web/src/enterprise/code-monitoring/components/CodeMonitorForm.tsx
>                              id="code-monitor-form-owner"
Is an id still required?

2022-01-21 18:29 UTC, gitstart-sourcegraph commented
@valerybugakov @umpox Migrated all `<select />` usages with `wildcard/Select` component. There are some small UI changes and as far as I can see they are from `FormFieldMessage` component which render `<small />` with `display: block` but the current usages use `display: inline` for `small.text-muted`

2022-01-27 06:48 UTC, valerybugakov reviewed
Hey @oleggromov, could you help with reviewing this one?

2022-01-28 14:29 UTC, oleggromov requested changes
There's a few small changes that I think are needed:
1. code related changes (see the comments)
2. default Select styles changes (most of the comments are about these)

I am leaving 2) mostly to make sure it's not forgotten. Most likely, these should be addressed in the follow-up PR.

@AlicjaSuska would you mind taking a look and letting us know what you think is the best default style?

Please take a look at 1) and I'll answer your last question on Monday. Thanks!

2022-01-28 16:02 UTC, gitstart-sourcegraph commented on client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
> +                <Select
@oleggromov Thanks for showing this. Since we are wrapping those component with `form-inline`, it's kind of hard to put label in a separate line but keep the submit button at the same line as other components (in this case it's the submit button), I suggest to just remove `label` binding from `<Select />` and use another label outside of `<Form />` (the same as what we are using in `AddUserEmailForm`). BTW if you want a new prop for that then I will need specified requirements and designs for it since it's related to `message` element

cc @valerybugakov

2022-01-31 10:03 UTC, oleggromov commented on client/wildcard/src/components/Form/Select/Select.tsx
> +    ({ children, className, selectClassName, message, isValid, isCustomStyle, selectSize, ...props }, reference) => (
A nit: there's a typo in this file on the line 26 in "Boostrap", which should be "Bootstrap". Please change if you don't mind 😄

2022-02-04 10:54 UTC, gitstart-sourcegraph commented on client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
> +                <Select
@oleggromov Could you take a look... please?

2022-02-04 10:54 UTC, gitstart-sourcegraph commented
> Please take a look at 1) and I'll answer your last question on Monday. Thanks!

@oleggromov Any updates?

2022-02-08 19:02 UTC, eseliger commented on .github/workflows/label-move.yml
>    #     }
I think these changes are unintentional? 🤔

2022-02-14 14:50 UTC, oleggromov commented on client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
> +                <Select
Here's the diff I suggest to use: https://gist.github.com/oleggromov/7910fe6ae5cc39a1ac49a98b5154af7d
It produces the following result:
<img width="1172" alt="Screenshot 2022-02-14 at 17 49 39" src="https://user-images.githubusercontent.com/2196347/153886491-a5e223d7-9498-4371-9468-0fea7341c050.png">

It's not ideal because of addition of some hardcoded values, but is acceptable since it keeps them bound to the `SetUserPrimaryEmailForm` component.

2022-02-14 15:02 UTC, oleggromov commented
@gitstart-sourcegraph 
Please take a look at the [last comment](https://github.com/sourcegraph/sourcegraph/pull/29672#discussion_r805920580)

As to 
> @valerybugakov @umpox Migrated all <select /> usages with wildcard/Select component. There are some small UI changes and as far as I can see they are from FormFieldMessage component which render <small /> with display: block but the current usages use display: inline for small.text-muted. Should we fix those UI changes by adding css module class into FormFieldMessage of Select or we can keep that UI changes?

Could you please provide screenshots?

2022-02-14 15:03 UTC, gitstart-sourcegraph commented on client/web/src/user/settings/emails/SetUserPrimaryEmailForm.tsx
> +                <Select
Thanks, it looks ok to me. Could you please confirm that we just need to  resolve this and won't need to make changes for default style of `Select` in this PR?

2022-02-14 15:07 UTC, gitstart-sourcegraph commented
@oleggromov You can look at current Chromatic reports to see those UI changes

2022-02-15 14:48 UTC, oleggromov commented
> @oleggromov You can look at current Chromatic reports to see those UI changes

![image](https://user-images.githubusercontent.com/2196347/154085927-ad49098e-a9a1-481a-8f41-8451d3d17c66.png)
Is it the changes with the spacing?

2022-02-15 15:12 UTC, gitstart-sourcegraph commented
> Is it the changes with the spacing?

@oleggromov  Yes, it is

2022-02-17 13:11 UTC, oleggromov commented
Merged the latest `main` into this branch.
Two pages required manual merge, which I did:

## https://sourcegraph.test:3443/users/admin/batch-changes/create
<img width="1255" alt="Screenshot 2022-02-17 at 16 09 36" src="https://user-images.githubusercontent.com/2196347/154488479-a9da075a-5777-44bd-81f9-dffa8ad98405.png">

## https://sourcegraph.test:3443/extensions/registry/new
<img width="1256" alt="Screenshot 2022-02-17 at 16 09 45" src="https://user-images.githubusercontent.com/2196347/154488522-e8785941-9393-4299-aaea-4e98ac7b6f18.png">

Will merge the PR as soon as the tests pass.

2022-02-17 13:13 UTC, eseliger commented on client/web/src/enterprise/extensions/extension/RegistryExtensionForm.tsx
> +    <div className={className}>
This is adding the className to both the wrapper as well as the `<Select />` element, is that correct? Seems strange.

2022-02-17 13:19 UTC, oleggromov commented on client/web/src/enterprise/extensions/extension/RegistryExtensionForm.tsx
> +    <div className={className}>
Good catch, thanks! I checked visually that things are looking good but haven't noticed this part.

2022-02-17 13:57 UTC, merged