add user documentation for updateUser
sourcegraph/sourcegraph pull request #29735
Opened 2022-01-14 08:57 UTC by DaedalusG

This is just to add something to the docs about how admins can alter user metadata

2022-01-14 09:00 UTC, unknwon commented on doc/admin/how-to/mutate-user-api.md
> +```json
I think `graphql` would work better 😁

2022-01-14 17:38 UTC, DaedalusG commented on doc/admin/how-to/mutate-user-api.md
> +```json
ahh yeah good catch

2022-01-14 19:02 UTC, northyg requested changes
Looks good! Just saw a few typos to fix 

> This document (add will here) walk you through the steps of using mutation queries to update or remove users via the GraphQL API consule.

In a couple places Consule -> console.
place holder -> placeholder

2022-01-14 19:41 UTC, kevinwojo commented on doc/admin/how-to/mutate-user-api.md
> +This document walk you through the steps of using mutation queries to update or remove users via the GraphQL API consule.
```suggestion
This document walk you through the steps of using mutation queries to update or remove users via the GraphQL API console. 
```

2022-01-14 19:43 UTC, kevinwojo commented on doc/admin/how-to/mutate-user-api.md
> +# How to update or remove users with the GraphQL API consule
```suggestion
# How to update or remove users with the GraphQL API console
```

2022-01-24 17:59 UTC, northyg approved these changes

2022-01-24 18:07 UTC, merged