lsif-typed: Add more syntax kinds
sourcegraph/sourcegraph pull request #29929
Opened 2022-01-19 18:14 UTC by tjdevries

2022-01-19 18:17 UTC, efritz commented on proto/lib/codeintel/lsif_typed/lsif.proto
>  }
(Unrelated conversation)

> Field numbers in the range 16 through 2047 take two bytes. So you should reserve the field numbers 1 through 15 for very frequently occurring message elements.

We should ensure that we define the 16 most *frequently* used syntax kinds and ensure they come before any other variations that may not be as frequently occurring.

2022-01-19 18:20 UTC, tjdevries commented on proto/lib/codeintel/lsif_typed/lsif.proto
>  }
So it's OK for me to switch everything around at the moment?

2022-01-20 00:32 UTC, tjdevries commented
@olafurpg what is a `TermIdentifier` ?

2022-01-20 00:35 UTC, tjdevries commented
Thoughts on `BuiltinIdentifier` for things like `nil`, `true`, `false`, etc.?

2022-01-20 02:32 UTC, tjdevries commented
`StringLiteralSpecial` for characters like `\n`, `\t`, etc.

2022-01-20 07:27 UTC, olafurpg approved these changes
> Thoughts on `BuiltinIdentifier` for things like nil, true, false, etc.?
> `StringLiteralSpecial` for characters like \n, \t, etc.

Both of those make sense to add. They are highlighted as keywords in IntelliJ but I think it's OK to represent them with a different `SyntaxKind`. 

Another syntax kind we may want to add is something like `RegexpLiteralSpecial`, although we may need a few of those for different special kinds

![CleanShot 2022-01-20 at 08 26 56@2x](https://user-images.githubusercontent.com/1408093/150292642-905fd742-6e8b-4e96-8149-c2becf383f75.png)
![CleanShot 2022-01-20 at 08 27 05@2x](https://user-images.githubusercontent.com/1408093/150292658-a7a16d3b-ff62-4fd4-9760-c2e2d717a731.png)

However, we can add it separately. This PR LGTM 👍

2022-01-20 07:27 UTC, olafurpg commented on lib/codeintel/lsif_typed/lsif.ts
> +        Operator = 13
I'd remove `Operator`, `TermIdentifier` and `TypeIdentifier` and use `Identifier` instead. I was too trigger happy in the original draft, we should try to keep the number of classes small IMO

2022-01-20 07:30 UTC, olafurpg commented on lib/codeintel/lsif_typed/lsif.ts
> +        Operator = 13
We may want to have something like a `ConstIdentifier` that we use for consts in Go and fields in Java
![CleanShot 2022-01-20 at 08 29 49@2x](https://user-images.githubusercontent.com/1408093/150293023-37068319-99f4-4f91-8524-3260dee18c9c.png)
![CleanShot 2022-01-20 at 08 29 24@2x](https://user-images.githubusercontent.com/1408093/150293032-4dbd28e2-7f07-43d5-99eb-1076f1a9c619.png)

2022-01-20 17:28 UTC, tjdevries commented
![image](https://user-images.githubusercontent.com/4466899/150390558-9494226b-97cf-4122-917e-8fa8dceab6aa.png)

Testing out some more syntax highlighting from intelliJ, I will add other items that I think make sense given some highlighting like this.

2022-01-20 17:42 UTC, tjdevries commented
I'm not sure if this is actually all the languages or just the defaults, but here is a list of what jetbrains supports

![image](https://user-images.githubusercontent.com/4466899/150392776-57a01c62-dda7-484f-817d-575e9acda3d9.png)

2022-01-20 22:06 UTC, tjdevries commented
I intentionally did not sort / try to put numbers associated with the proto stuff here because I wanted to chat about the classes that I put in.

I could track down basically every one of these classes in IntelliJ. I **do not** think we need to have everyone one of these syntax kinds display a different color. I think many of them can be shown with the same color, but I do not think we should limit `SyntaxKind` to `ColorKind` (i.e., tightly couple `SyntaxKind` to what colors we will show). I would rather have a larger number of `SyntaxKind` vs what we display.

cc @varungandhi-src since you had been talking about `SyntaxKind` before.

I think it's best if we comment on individual lines to chat about them (that's why I pushed it the way it is, so you can see things grouped).

2022-01-24 16:48 UTC, olafurpg requested changes

2022-01-24 16:48 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  ShadedIdentifier = 0;
As discussed offline
```suggestion
  ShadowedIdentifier = 0;
```

2022-01-24 16:48 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  PackageIdentifier = 0;
As discussed offline
```suggestion
  PackageIdentifier = 0;
  ParameterIdentifier = 0;
```

2022-01-24 16:48 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  FunctionDefinition = 0;
Should this be `FunctionIdentifier`?

2022-01-24 16:48 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  TypeIdentifier = 0;
Move all of these up to live alongside other identifiers?

2022-01-24 16:48 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  // non-specific variables, function calls, etc.
Remove "function calls" if we add `FunctionIdentifier`
```suggestion
  // catchall for identifiers that don't fit under the more specific categories below
```

2022-01-24 16:48 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  // This is `if`, `else`, `return`, `class`, etc.
nit, for consistency with the other comments
```suggestion
  // `if`, `else`, `return`, `class`, etc.
```

2022-01-24 16:48 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +// TODO: Should make sure that nums 1-15 are the MOST common before releasing.
Decent rule of thumb but this is not a strong enough justification to split up groups like identifier kinds

2022-01-25 09:43 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  //    Included because many editors highlight a function definition seprately
```suggestion
  //    Included because many editors highlight a function definition seperately
```

2022-01-25 09:44 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  // builtin types only, such as `str` for Python or `uint89` in Go
```suggestion
  // builtin types only, such as `str` for Python or `uint8` in Go
```

2022-01-25 09:45 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  // python decorators, c-like __attribute__
```suggestion
  // Python decorators, c-like __attribute__
```

2022-01-25 09:45 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  TagDelimiter = 30;
```suggestion
  // Used for XML-like tags
  Tag = 28;
  // Attribute name in XML-like tags
  TagAttribute = 29;
  // Delimiters for XML-like tags
  TagDelimiter = 30;
```

2022-01-25 09:55 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  PackageIdentifier = 14;
Should we call this `ModuleIdentifier` instead of `PackageIdentifier`? I think module is the more common term, Python and JavaScript/TypeScript being the two big ones, there's also Ruby, Objective-C/Swift, Perl, and recently C++. `package` is applicable to JVM languages and Go.

2022-01-25 09:56 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  PunctuationSpecial = 5;
Should `PunctuationSpecial` be removed given that `StringLiteralSpecial` was added?

2022-01-25 10:00 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  ConstantIdentifier = 10;
Should we have a `MutableGlobalIdentifier` too? GoLand does different highlighting for those and I definitely appreciate that feature.

<img width="112" alt="Screen Shot 2022-01-25 at 3 29 28 PM" src="https://user-images.githubusercontent.com/93103176/150954912-af1ae844-093d-4e1d-b0f7-9265a5f9d150.png">

2022-01-25 10:03 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  BuiltinIdentifier = 8;
Should we have a separate identifier kind for null-like values? GoLand highlights those differently from builtins.

<img width="225" alt="Screen Shot 2022-01-25 at 3 33 31 PM" src="https://user-images.githubusercontent.com/93103176/150955555-3c0a41b4-9676-4b92-8e6e-283735fba7f0.png">

2022-01-25 10:21 UTC, varungandhi-src commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  FunctionDefinition = 23;
Would be good to have a matching `MacroDefinition` (e.g. GitHub highlights macro definitions slightly lighter that function definitions) and perhaps `MacroIdentifier` for calls (if there's a `FunctionIdentifier`?).

https://github.com/llvm/llvm-project/blob/6a028296fe62252791a6b470eeb8409b17d48cd0/clang/lib/Basic/Targets/PPC.cpp

2022-01-26 04:32 UTC, varungandhi-src approved these changes

2022-01-26 14:34 UTC, olafurpg approved these changes
LGTM 👍 I left a few more comments that I'm happy to address personally with a separate PR

2022-01-26 14:34 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  Operator = 1;
wdyt?
```suggestion
  OperatorIdentifier = 1;
```

2022-01-26 14:34 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  PunctuationSpecial = 5;
I'm surprised by this name, what's the difference between `PunctuationSpecial` and `StringLiteralSpecial`?

2022-01-26 14:34 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  PunctuationDelimiter = 3;
Should we use "delimiter" instead of "punctuation" for this category?

2022-01-26 14:34 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  StringLiteralRegex = 18;
We may need more kinds to support different regex features

- escapes like `\b`
- repeated like `*` and `+`
- wildcard like `.`
- delimeters like `(`, `)`, `[`, `]`
- join characters like `|`, `-`

IntelliJ seems to treat these differently
![CleanShot 2022-01-26 at 15 29 45](https://user-images.githubusercontent.com/1408093/151181678-ef960a4c-15dd-4da1-a1e6-80d177f98be3.png)

I might also make sense to separate these Regex kinds from string literals because some languages like JS have regex literals

2022-01-26 14:34 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  FunctionDefinition = 25;
nit: this should have `Identifier` in its suffix, same for `MacroDefinitionIdentifier`
```suggestion
  FunctionDefinitionIdentifier = 25;
```

2022-01-26 14:34 UTC, olafurpg commented on proto/lib/codeintel/lsif_typed/lsif.proto
> +  FunctionDefinition = 25;
I think it would make sense to have kinds for function/macro references as well, something like this
```proto
  FunctionIdentifier = 24;
  FunctionDefinitionIdentifier = 25;
  MacroIdentifier = 26;
  MacroDefinitionIdentifier = 27;
```

2022-01-26 14:34 UTC, merged