Move modules to the @sourcegraph/common package into util
sourcegraph/sourcegraph pull request #29976
Opened 2022-01-20 14:28 UTC by gitstart-sourcegraph

## Decription

Move modules to the `@sourcegraph/common` package into util

## Refs
- [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/29622)
- [GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-29622)

## Implementation Detail
Nest these modules next to places where they are used under `utils` folder:
- `link-click-handler`
- `createRecord`
- `prefixSumComputer`
- `ReferenceCounter`
- `wordHelpers`

Move these modules to the `@sourcegraph/common` package into `util`:
- `browserDetection`
- `dom` — rename to `highlightNode`
- `fetchCache`
- `hashCode`
- `icon` — rename to `isEncodedImage`
- `jsonc`
- `LocalStorageSubject`
- `markdown`
- `strings.ts`
- `types.ts`
- `url.ts` — move only utilities that are not product/api specific.
- `memoizeObservable` — move to the `rxjs` folder
- `rxjs`
- `rxjs/throttleTimeWindow.ts` — it seems it can be removed.

2022-01-20 14:38 UTC, gitstart-sourcegraph commented
@valerybugakov 
To confirm Implementation detail,`Nest these modules next to places where they are used under utils folder`
Entails creating new `utils` folders in directories of usage, and moving modules into them?

2022-01-21 10:05 UTC, valerybugakov commented
> Entails creating new utils folders in directories of usage and moving modules into them?
Correct.

2022-01-26 07:27 UTC, gitstart-sourcegraph commented
Hi @valerybugakov we noticed some issues due to importing components from `shared` package into the `common` package, causing a circular import between between @sourcegraph/shared <-> @sourcegraph/common, what do you think about best way to handle this use case

2022-01-31 08:01 UTC, valerybugakov requested changes

2022-02-07 16:30 UTC, valerybugakov approved these changes
Let's resolve merge conflicts, ensure that CI is still green, and proceed with merge.
Thanks!

2022-02-07 16:30 UTC, valerybugakov commented on client/common/src/util/url.ts
> +import { tryCatch } from '@sourcegraph/common'
Let's use relative imports for modules inside of the same package.

2022-02-07 16:30 UTC, valerybugakov commented on client/shared/src/util/rxjs/throttleTimeWindow.ts
> -export function throttleTimeWindow<T>(
Nice!

2022-02-08 05:09 UTC, merged