monitoring: Rename core-application to repo-management and refactor
sourcegraph/sourcegraph pull request #30026
Opened 2022-01-21 12:52 UTC by indradhanush

Stacked PR on top of #26865 which is a pre-requisite.

Also, when this is rolled out, we will need to rename [the team in OpsGenie](https://sourcegraph.app.opsgenie.com/teams/dashboard/01b8adfc-9b85-462b-a841-945791c17e9e/main) to `repo-management`. 

In this commit we introduce a struct to store the owner name, team
name and the slug since now all the teams have a custom format. As a
result, the existing switch-case in `toMarkdown` can be replaced in
exchange of a better data struct-ure (pun intended_.

2022-01-21 13:18 UTC, sashaostrikov approved these changes
LGTM! I've just added one little comment

2022-01-21 13:18 UTC, sashaostrikov commented on monitoring/monitoring/monitoring.go
> +func (o *ObservableOwner) String() string {
nit: probably this `String()` implementation is printing only the name for backward compatibility (possibly ObservableOwner is printed in some places and previously it was just a string with a name). 

Let's add a doc stating it, because for future readers it may not be very obvious why `String()` function contains only a string representation of 1 out of 3 properties of the struct

2022-01-21 16:27 UTC, indradhanush commented on monitoring/monitoring/monitoring.go
> +func (o *ObservableOwner) String() string {
Oops. That's code that I forgot to remove after I changed my approach a little bit. Good catch! Will remove.

2022-01-21 20:14 UTC, bobheadxi approved these changes
Having the observable owners be structured is a great idea! Just some comments about the potential naming and docstrings, but otherwise LGTM in principle. Thanks for contributing to the generator!

2022-03-07 20:09 UTC, slimsag commented
seems outdated + inactive, closing. feel free to reopen.

2022-04-01 08:49 UTC, ryanslade commented on monitoring/monitoring/monitoring.go
> +
nit: Inconsistent spacing

2022-04-01 08:49 UTC, ryanslade commented on monitoring/definitions/syntect_server.go
> +			shared.NewContainerMonitoringGroup(containerName, monitoring.ObservableOwnerRepoManagement, nil),
I think these 3 should maybe be owned by dev-ops?

2022-04-01 08:50 UTC, ryanslade commented on monitoring/definitions/github_proxy.go
> +			shared.NewContainerMonitoringGroup(containerName, monitoring.ObservableOwnerRepoManagement, nil),
I think these are also probably best owned by cloud dev-ops.

2022-04-01 08:52 UTC, ryanslade commented on monitoring/definitions/frontend.go
> +							Owner:          monitoring.ObservableOwnerRepoManagement,
Sign in isn't really owned by us.. but I'm not sure who it *is* owned by.

2022-04-01 08:52 UTC, ryanslade commented on monitoring/definitions/frontend.go
> +							Owner:          monitoring.ObservableOwnerRepoManagement,
My guess would be that sign in and signup issues should go to the cloud team

2022-04-01 08:53 UTC, ryanslade commented on monitoring/definitions/frontend.go
> +							Owner:       monitoring.ObservableOwnerRepoManagement,
cloud dev-ops?

2022-04-01 08:55 UTC, ryanslade requested changes
Sorry, requesting a few changes. Thanks for sticking with this issue for so long!

2022-04-01 08:55 UTC, ryanslade commented on monitoring/definitions/frontend.go
> +							Owner:       monitoring.ObservableOwnerRepoManagement,
Cloud dev-ops?

2022-04-01 08:55 UTC, ryanslade commented on monitoring/definitions/frontend.go
> +				Owner:          monitoring.ObservableOwnerRepoManagement,
I think these graphql metrics should also be owned by cloud  dev-ops. A spike with graphql in general is hard to own by a single team but since it would impact the cluster as a whole it kind of feels like their responsibility as first line defence at least.

2022-04-26 10:36 UTC, indradhanush commented
@ryanslade I'd like to keep the scope of this PR small and get it merged as change in ownership will require review from other teams and is out of scope of this PR at the moment. Trying to limit this PR to just refactor plus semantic changes of Core Application -> Repo Management, which is the same group in practice at the moment.

Happy to follow up with another one.

2022-04-26 10:50 UTC, sashaostrikov requested changes
Great job!

I agree with Ryan's comments about some monitorings should go to cloud dev-ops, I've 👍'd them. Let's change them and we're ready to go IMO

2022-04-26 10:51 UTC, indradhanush commented
@sashaostrikov I left context on the migration of ownership in the [above](https://github.com/sourcegraph/sourcegraph/pull/30026#issuecomment-1109634008) comment. 

Follow up PRs are in #34499 and #34450.

2022-04-26 10:57 UTC, sashaostrikov approved these changes
LGTM with follow-up PRs

2022-04-26 11:03 UTC, indradhanush commented
@ryanslade Looks like it's blocked based on your change request. LGTM if you are okay with the plan? :grin:

2022-04-27 10:13 UTC, ryanslade approved these changes

2022-04-27 10:13 UTC, merged