gitserver: Optionally return modified files from /search
sourcegraph/sourcegraph pull request #30109
Opened 2022-01-24 15:29 UTC by ryanslade

When sub-repo permissions are enabled we'll include modified files in
commit search results. This will allow us to filter out results that
touch files the user is not allowed to see.

2022-01-24 15:32 UTC, ryanslade commented
@mollylogue @camdencheek Tagging you guys on this to take a quick look. I could probably add more tests but this is the first stab at it and wanted you to have time to take a look today as I'll be stopping for the day soon. 

@mollylogue I noticed that your parsing code for `--name-only` had to deal with a weird case where the commits ids and file names kind of bled into each other but it doesn't appear to be an issue here in my basic tests and some manual testing. I'm not sure why..

2022-01-24 15:49 UTC, camdencheek approved these changes
Other than the small comments inline, this looks great. Seems like a nice, isolated change that should have almost no performance impact when it's not being used. Thanks!

2022-01-24 15:49 UTC, camdencheek commented on internal/gitserver/search/lazy_commit.go
> +	if len(files) > 0 && files[0] == "" {
Why would we have an empty first line?

2022-01-24 15:49 UTC, camdencheek commented on internal/search/commit/commit_new.go
> +	SubRepoPermissionsChecker authz.SubRepoPermissionChecker
We're [currently moving towards](https://github.com/sourcegraph/sourcegraph/pull/30068) search jobs being a "static" representation of what will be executed, which means we'd like to not store any "runtime" values on the struct, which includes things like a `SubRepoPermissionChecker`. I think it would be preferable for this to also be just a boolean `IncludeModifiedFiles` at this point.

2022-01-24 16:25 UTC, ryanslade commented on internal/gitserver/search/lazy_commit.go
> +	if len(files) > 0 && files[0] == "" {
I'm not sure why it happens but it was happening in the tests. I'll take a deeper look into why tomorrow.

2022-01-26 13:36 UTC, ryanslade commented
@camdencheek @mollylogue PTAL

I needed to change the way our commit scanner works and add a custom separator between commits because of the way modified files are appended to the commit messages. 

They're added after the commit message and are also separated by zero bytes which means we can no longer simply assume the number of "parts" will always be the same.

I've tested manually running a commit search and added some extra test cases so I think it should be safe.

2022-01-26 14:11 UTC, camdencheek commented
I'm not working today, but will take a closer look early tomorrow. Thanks for the ping!

2022-01-27 07:54 UTC, ryanslade commented on internal/gitserver/search/search.go
> +	// commitSeparator is a special sequence of bytes we use to separate each commit, zero bytes surrounding "SEP".
Possibly, but it would be a bigger change there I think since we don't send a format string to `git log` in that case.

2022-01-27 18:12 UTC, camdencheek requested changes

2022-01-27 18:12 UTC, camdencheek commented on internal/gitserver/search/search.go
> +	}
Now that we have a distinct commit separator, I don't think we need to condition this on `c.includeModifiedFiles` because `parts[11:]` will just be an empty slice if we aren't adding `--name-only`. This also means `CommitScanner` doesn't need to keep track of `includeModifiedFiles`, which is pretty nice.

2022-01-27 18:12 UTC, camdencheek commented on internal/gitserver/search/search.go
> +	commitSeparator = []byte("\x00SEP\x00")
I think a file named `SEP`, an author named `SEP`, a message body containing only `SEP`, or a ref named `SEP` would break this. While probably unlikely, I think it's avoidable. 

This might be an appropriate place to use an [ASCII Record Separator](https://www.asciihex.com/character/control/30/0x1E/rs-record-separator) byte 🤔

2022-01-28 07:38 UTC, ryanslade commented on internal/gitserver/search/search.go
> +	commitSeparator = []byte("\x00SEP\x00")
Ah, nice, I didn't know about that.

2022-01-28 09:07 UTC, ryanslade commented
@camdencheek Thanks for the detailed review. PTAL

2022-01-31 10:10 UTC, merged