Remove bootstrap style import `@import 'bootstrap/scss/forms'`
sourcegraph/sourcegraph pull request #30287
Opened 2022-01-27 11:23 UTC by gitstart-sourcegraph

## Problem Statement
We depend on Bootstrap styles in our global styles a lot. But we don't plan to move forward with Bootstrap because we're working on our design system called Wildcard. To ease the transition to our styles and gain more control over visual changes, we want to move Bootstrap styles that we need into our codebase and eventually drop Bootstrap dependency.

## Ref
[Parent Issue](https://github.com/sourcegraph/sourcegraph/issues/29200)
[SG Issue](https://github.com/sourcegraph/sourcegraph/issues/30279)
[Gitstart Task](https://app.gitstart.com/clients/sourcegraph/tickets/SG-30279)

## Success Criteria
- [ ] All highlighted imports has been removed
- [ ] All css rules currently used from the imports are now available in style sheets

## Implementation Details
Let's also remove the following imports and copy CSS rules that we need to our CSS files:

1) remove the imports @import 'bootstrap/scss/forms from global index.scss file
2) copy styles used in codebase into the global forms.scss file

## ETA
1.5 hrs with no UI changes
3 - 4 hrs if there are UI changes

2022-02-01 08:26 UTC, gitstart-sourcegraph commented
@valerybugakov,
kindly help review spec PR. 
Also, we're currently unable to view updated chromatic review on CI, any ideas why?

2022-02-03 09:37 UTC, valerybugakov commented
@gitstart-sourcegraph, we disabled Chromatic check for draft PRs. If you need to check a Chromatic diff after making several changes — mark your PR as ready for review and convert it back to draft. We will look into implementing commit message hints to trigger this step for specific commits later.

2022-02-03 12:20 UTC, gitstart-sourcegraph commented
@valerybugakov, PR ready for review. kindly take a look

2022-02-14 06:32 UTC, valerybugakov requested changes
I noticed some undesired UI changes happening because we define form rules earlier, and they have higher priority than some Bootstrap files like `_custom-forms.scss`.

<img width="632" alt="Screen Shot 2022-02-14 at 09 25 57" src="https://user-images.githubusercontent.com/3846380/153811541-de6c9ef0-4683-41a8-b93a-143bedd9c604.png">

Compare it to the UI on the main branch or our dogfood instance: https://k8s.sgdev.org/users/admin/settings/emails. Let's double-check other usages of the updated styles and ensure that we don't have unexpected changes.

2022-02-23 05:23 UTC, valerybugakov requested changes

2022-02-23 05:23 UTC, valerybugakov commented on .github/workflows/label-move.yml
> -  wcag-accessibility-board:
Redundant changes?

2022-02-23 05:23 UTC, valerybugakov commented on client/branded/src/global-styles/forms.scss
> +    --font-size-base: $font-size-base;
This CSS variable can be used in other parts of global styles. Let's define it in `client/branded/src/global-styles/index.scss`.

2022-02-23 05:23 UTC, valerybugakov commented on client/branded/src/global-styles/forms.scss
> +    --input-font-size-sm: 0.786em;
In Bootstrap this variable is defined relative to the `--font-size-base` variable. Let's preserve this relation:

```scss
--font-size-base: $font-size-base;
--input-font-size-sm: calc(var(--font-size-base) * 0.875);
```

This comment is applicable for other CSS variables defined here. Let's double-check if they should be calculated from already existing variables.

2022-02-23 05:23 UTC, valerybugakov commented on client/branded/src/global-styles/forms.scss
> +    --input-line-height: 1.429;
Should rely on `$line-height-base` define in `client/branded/src/global-styles/index.scss` as Bootstrap does it.

2022-02-23 05:23 UTC, valerybugakov commented on client/branded/src/global-styles/forms.scss
> +    --border-radius: 3px;
It's already defined in `client/branded/src/global-styles/border-radius.scss`

2022-02-23 05:23 UTC, valerybugakov commented on client/branded/src/global-styles/forms.scss
> +    --input-border-width: 1px;
This variable [is defined](https://github.com/sourcegraph/sourcegraph/pull/30352/files#diff-b0ec73ef001a2ee6c05a4c91bc55c4f37c9d04cb57c990e90c8019cf2c9f6f04R28) in a related PR. Let's make sure that we do not duplicate them.

2022-02-23 05:23 UTC, valerybugakov commented on client/branded/src/global-styles/forms.scss
> +    --input-padding-x: 0.75rem;
Defined in another PR too. Let's avoid duplication.

2022-02-25 09:13 UTC, gitstart-sourcegraph commented on client/branded/src/global-styles/forms.scss
> +    --input-font-size-sm: 0.786em;
We replaced the value of `$input-font-size-sm` in `typography.scss` so couldn't use this suggestion, kindly take a look

2022-02-25 16:27 UTC, gitstart-sourcegraph commented on .github/workflows/label-move.yml
> -  wcag-accessibility-board:
Reverted now.

2022-03-02 14:23 UTC, valerybugakov approved these changes

2022-03-02 14:23 UTC, valerybugakov commented on client/branded/src/global-styles/typography.scss
> +}
Let's move all global CSS variables affected by this PR into a `global-styles/variables.scss` and import it in `global-styles/index.scss` in a follow-up PR. It's confusing to see global CSS variables related to input in multiple places.

```scss
$input-font-size-sm: (11/14) + em;
// ...other SASS variables defined in `global-styles/index.scss`

:root {
    --spacer: #{$spacer};
    --font-size-base: #{$font-size-base};
    --line-height-base: #{$line-height-base};

  // input
  --input-font-size-sm: #{$input-font-size-sm};
  // ...other input related CSS variables
}

2022-03-03 09:11 UTC, gitstart-sourcegraph commented on client/branded/src/global-styles/typography.scss
> +}
To be resolved in #32117

2022-03-03 09:11 UTC, merged