ssbc: Prettify create batch change page
sourcegraph/sourcegraph pull request #30295
Opened 2022-01-27 15:26 UTC by eseliger

Not meant to be pixel perfect but some start towards a more "wow" effect when getting started with SSBC the first time. The visibility toggle is muted and disabled, but it makes it visually more appealing.

Also fixes a bug where the namespace on the editor page would not match the namespace of the batch change being edited.

![image](https://user-images.githubusercontent.com/19534377/151389269-51724987-c1ce-4231-9944-f03b3c8c2fb2.png)

Closes #31165

2022-01-31 19:56 UTC, courier-new requested changes
Ugh I really like how this looks, but on the other hand, most of these changes conflict with other UX decisions we've made or things I've already talked about with Rob explicitly. 🙁 I LOVE the input validation and I know that's something we can keep, but I'm less sure about the layout changes without Rob's blessing, and I did confirm with him on Friday that we want to keep the namespace selector **enabled** all the time. 😅

2022-01-31 19:56 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                            disabled={!!namespaceID}
Heads up, I did talk to Rob about this on Friday and he said we should leave the namespace selector enabled regardless of what version of the page you're on. He didn't think the URL mismatch was a concern (he says the user/org namespace stuff is really just design debt from Sourcegraph's early days where we leaned too hard on copying from GitHub and the like) and said the user should be able to do whatever they want here.

2022-01-31 19:56 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                />
So I don't want to speak for Rob but I actually think keeping the existing page layout is the intended design. What you've come up with might look a bit better, but I think there were reasons for the existing layout choices, and at the very least I think we'd want to discuss these with him in Figma before committing to these changes. Here's a couple of the concerns I have:

- The `PageHeader` is now inconsistently aligned between pages. On this form, it ends up sitting closer to the middle of the page, and only when you hit "Create" does it jump all the way back over to the left side. All the other screens we have in Figma for SSBC workflows have a consistent left alignment on this part of the layout.
- This drops the namespace from the breadcrumbs in `PageHeader` before "Create batch change." This is again a consistency thing, but I think it helps reinforce the unique identity of this batch change being a combination of namespace + name, and we talked in the designs about it reflecting whatever namespace you select from the dropdown, as it was implemented with `BatchChangePage`.
- Keeping the `h4` "Batch spec settings" above the form is also something Rob and I have discussed before and that I think we want to keep, because this form will come back for the batch change settings (to rename or move namespace).
- `Container` is just how we're supposed to use Wildcard for `<div className="container">` now. 😜

2022-01-31 19:56 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +        setNameValid(/^[\w.-]+$/.test(event.target.value))
Can we declare a constant for the string pattern for this regex, so that we can refer to the constant both here and for the `Input`'s `pattern` prop instead?

2022-01-31 19:56 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                                Only regular characters, _ and - are allowed.
Rob and I talked on Friday about copy being as much a component of UX design as the visuals around that copy. Rob said he wished he had been able to provide feedback on some of our recent copy decisions, so I'd maybe run this by him first in case he has any input. 🙂

2022-01-31 19:56 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                            Visibility <InfoCircleOutlineIcon className="icon-inline" data-tooltip="Upcoming feature" />
Same with this copy -- "Upcoming feature" isn't doing it for me but I don't have a better suggestion at the moment. 😂

2022-01-31 19:56 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                                    type="radio"
We do have `RadioButton` components in Wildcard, too. 😉

2022-01-31 22:47 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                />
> Container is just how we're supposed to use Wildcard for <div className="container"> now. 😜

Indeed not, it is something different 😬 a `.container` doesn't do much visually except for setting a width and making the children flex. The Container is something that brings visual distinction in by adding a border, background and padding, but isn't concerned about the display mode at all 🤔

2022-01-31 22:49 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                />
Oh you're totally right, my bad. 🙈 That's not confusing at all. 😬

2022-01-31 22:53 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                                Only regular characters, _ and - are allowed.
Sure, but just to underline, I don't think we are ever nailing anything down by putting in _some_ copy, I think that should either be frontloaded in designs or be adjusted in QA, but there's nothing preventing us ever from changing ANY of the wording in-app :)

2022-01-31 22:53 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                            Visibility <InfoCircleOutlineIcon className="icon-inline" data-tooltip="Upcoming feature" />
Yeah thought the same but also thought it doesn't matter much :D

2022-01-31 22:54 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                                    type="radio"
`RadioButton` is .. confusing me :D but anyways, I'll take that, thanks!

2022-01-31 22:57 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                                Only regular characters, _ and - are allowed.
Oh absolutely, appreciate the reminder. 😄 I was just thinking about it since Rob and I had just talked about it.

2022-02-11 16:18 UTC, rrhyne commented
@courier-new, @eseliger  and I discussed and I feel aligning to the global create forms pages is the right call. 

You are correct in considering the batch changes flow, and there will be some 'popping' in the UI and the header transitions between index and create and the execution and edit. 

That said, we are introducing something new to the system or editing for these pages. The severity of that action supports the isolation and transition to a more focused narrow page. 

Thanks for both of your concerns and the care you take with these decisions.

2022-02-14 19:17 UTC, eseliger commented
Addressed feedback and enabled namespace selector on all pages. @courier-new can you TAL?

2022-02-15 12:54 UTC, rrhyne commented
> The visibility toggle is muted and disabled, but it makes it visually more appealing. 

Is it disabled because it hasn't been built yet? If so can we add a label beside it to indicate why? Something like:

Visibility (_coming soon_) i

2022-02-15 12:54 UTC, rrhyne approved these changes
LGTM

2022-02-16 00:16 UTC, courier-new approved these changes
Looks great! Really happy to be getting somewhere so polished with this screen. 🙂 Left a couple small suggestions and am also in support of Rob's idea of _(coming soon)_ over the info icon, probably, but otherwise looks good to me!

2022-02-16 00:16 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                            <span className={classNames(nameValid === false && 'text-danger')}>
Just wanted to reiterate I love the conditional coloring just on the validation instructions SO MUCH. 🙂

2022-02-16 00:16 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                                        Private <LockIcon className="text-warning icon-inline" />
Accessibility suggestion (I know I've been dropping this sometimes too 👀)

```suggestion
                                        Private <LockIcon className="text-warning icon-inline" aria-hidden={true} />
```

2022-02-16 00:16 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +const NAME_PATTERN = /^[\w.-]+$/
```suggestion
/* Regex pattern for a valid batch change name */
const NAME_PATTERN = /^[\w.-]+$/
```

2022-02-16 15:53 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                                        Private <LockIcon className="text-warning icon-inline" />
Thanks for the reminder! I keep being too lax about this.

2022-02-16 17:05 UTC, merged