remove bootstrap style import @import `'bootstrap/scss/custom-forms'`
sourcegraph/sourcegraph pull request #30328
Opened 2022-01-28 05:50 UTC by gitstart-sourcegraph

### Problem statement
We depend on Bootstrap styles in our global styles a lot. But we don't plan to move forward with Bootstrap because we're working on our design system called Wildcard. To ease the transition to our styles and gain more control over visual changes, we want to move Bootstrap styles that we need into our codebase and eventually drop Bootstrap dependency.

### Refs
[Parent issue](https://github.com/sourcegraph/sourcegraph/issues/29200)
[SG issue](https://github.com/sourcegraph/sourcegraph/issues/29200)
[GitStart Task](https://app.gitstart.com/clients/sourcegraph/tickets/SG-30280)

### Success Criteria
- [ ] All highlighted imports has been removed

- [ ] All css rules currently used from the imports are now available in style sheets

### Implementation details

let's also remove the following imports and copy CSS rules that we need to our CSS files:

1. remove the import `@import 'bootstrap/scss/custom-forms` from global `index.scss` file
2. copy styles used in codebase into new global `custom-forms.scss` file within `client/branded/src/global-styles`
3. import file into global `index.scss`
Note: some style rules from @import 'bootstrap/scss/custom-forms are already being modified by styles in forms.scss

### ETA
70 minutes - initial implementation
180 minutes - with UI changes

2022-03-02 14:31 UTC, valerybugakov reviewed
Let's rebase this PR from `main` after merging [this one](https://github.com/sourcegraph/sourcegraph/pull/30287). We need to remove the duplication of CSS variables that I mentioned in the linked PR review.

2022-03-07 17:23 UTC, gitstart-sourcegraph commented
@valerybugakov requested change, for [this issue](https://github.com/sourcegraph/sourcegraph/issues/32117), has been added as part of this PR, kindly take a look

2022-03-09 13:05 UTC, valerybugakov requested changes

2022-03-09 13:05 UTC, valerybugakov commented on client/branded/src/global-styles/custom-forms.scss
> +    --custom-select-font-size: 0.875rem;
Should we depend on `--font-size-base` here instead?

2022-03-09 13:05 UTC, valerybugakov commented on client/branded/src/global-styles/variables.scss
> +    --input-font-size: var(--font-size-base);
Let's group CSS variables by adding comments between groups like we do for SCSS variables.

```suggestion
    --line-height-base: #{$line-height-base};
    // Input
    --input-font-size: var(--font-size-base);
```

2022-03-10 08:27 UTC, valerybugakov approved these changes

2022-03-10 08:34 UTC, merged