Remove bootstrap style import `@import 'bootstrap/scss/input-group'`
sourcegraph/sourcegraph pull request #30352
Opened 2022-01-28 13:30 UTC by gitstart-sourcegraph

## Ref
[Parent Issue](https://github.com/sourcegraph/sourcegraph/issues/29200)
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/30281)
[GitStart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-30281)

## Success Criteria
- [ ] All highlighted imports has been removed
- [ ] All css rules currently used from the imports are now available in style sheets

## Implementation Details
Let's also remove the following imports and copy CSS rules that we need to our CSS files:

1) remove the imports **@import 'bootstrap/scss/input-group** from global `index.scss` file
2) copy styles used in codebase into the global `input-group.scss` file

## ETA
5 - 9 hrs
- Move and modify @Mixins where required according to Chromatic UI changes.
- Move and modify scss variables where required according to Chromatic UI changes.

2022-01-28 13:47 UTC, gitstart-sourcegraph commented
UI Review
https://www.chromatic.com/pullrequest?appId=5f0f381c0e50750022dc6bf7&number=30352&view=changes

2022-02-03 10:09 UTC, gitstart-sourcegraph commented
@valerybugakov This is ready for review, kindly take a look.

2022-02-14 06:52 UTC, valerybugakov requested changes
Let's compare usages of updated classes in the branch against our dogfood instance or the `main` branch and ensure that we don't have unexpected changes.

2022-02-14 06:52 UTC, valerybugakov commented on client/branded/src/global-styles/input_group.scss
> +    --input-font-size: 1rem; // Assumes the browser default, typically `16px`
We have redefined Bootstrap variables here: 

https://github.com/sourcegraph/sourcegraph/blob/25b5aca6ca76336cca48dfa5c9aaa19b25543a8e/client/branded/src/global-styles/index.scss#L10

Changing font-size results in unexpected UI changes [here](https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph-typescript/-/stats/contributors).

2022-02-14 06:52 UTC, valerybugakov commented on client/branded/src/global-styles/input_group.scss
> +    --input-line-height: 1.5;
We already have redefined variable here: 

https://github.com/sourcegraph/sourcegraph/blob/25b5aca6ca76336cca48dfa5c9aaa19b25543a8e/client/branded/src/global-styles/index.scss#L11

Let's make sure that we do not override existing variables.

2022-02-23 04:57 UTC, valerybugakov approved these changes
⚡️

2022-02-23 07:41 UTC, merged