release/improve release instruction
sourcegraph/sourcegraph pull request #30453
Opened 2022-02-01 02:44 UTC by michaellzc

- v0.0.0
- release: improve patch release instruction

Closes https://github.com/sourcegraph/sourcegraph/issues/TODO.

#### Description

TODO: Add a brief description of what PR includes.

#### How to test

TODO: Describe how to test for PR reviewers.

#### Screenshots (TODO: if applicable)
| Before | After |
| -: | :- |
| | |

#### Before merging

- [ ] Test on different code hosts (if applicable)
    - [ ] GitHub
    - [ ] Gitlab
    - [ ] GitHub Enterprise
    - [ ] Refined GitHub
    - [ ] Phabricator
    - [ ] Phabricator integration
    - [ ] Bitbucket
    - [ ] Bitbucket integration

- [ ] Test on different browsers (if applicable)
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
- [ ] Add change log message to [client/browser/CHANGELOG.md](./client/browser/CHANGELOG.md), under "Unreleased" section. (if applicable)

2022-02-01 02:46 UTC, michaellzc commented on dev/release/src/release.ts
> +                                    'Re-run Buildkite on this branch, and ensure the build passes before merging this pull request'
This should clarify below confusion

- CI will fail unless `yarn run release release:finalize` is run
- It wasn't's obvious enough that we shouldn't run `yarn run release release:finalize` until all other changsets are merged

2022-02-01 03:10 UTC, michaellzc commented on dev/release/src/release.ts
> +        ? ''
when `notPatchRelease` (i.e., minor/major), the `yarn release:cut` command should generate the changelog automatically.

2022-02-01 16:07 UTC, caugustus-sourcegraph commented on dev/release/src/release.ts
> +- [ ] I copied all changelogs under the \`${release.version}\` section and they are grouped by type (e.g. \`Added\`, \`Changed\`, \`Fixed\`, \`Removed\`)
I'm having trouble following this last bullet - what's the difference between it and the one above?

2022-02-01 16:07 UTC, caugustus-sourcegraph commented on dev/release/src/release.ts
> +                                    'Run `yarn run release release:finalize` to generate the tags required. Notes, CI will not pass untill this command is run.',
```suggestion
                                    'Run `yarn run release release:finalize` to generate the tags required. **Note** CI will not pass until this command is run.',
```

2022-02-01 17:11 UTC, michaellzc commented on dev/release/src/release.ts
> +- [ ] I copied all changelogs under the \`${release.version}\` section and they are grouped by type (e.g. \`Added\`, \`Changed\`, \`Fixed\`, \`Removed\`)
The last one was trying to say each, it shouldn't look something like

```md
## 3.36.2

- Revert UX change
 ```

it should look something like

```md
## 3.36.2

### Changed
- Revert UX change
```

I get that my wording is pretty confusing. Any suggestion to make it more clear?

2022-02-01 22:00 UTC, caugustus-sourcegraph approved these changes

2022-02-01 22:13 UTC, bobheadxi requested changes
Nice to have this explicit! I think this should just be all part of `actionItems` though, instead of a separate thing

2022-02-01 22:13 UTC, bobheadxi commented on dev/release/src/release.ts
> +- [ ] I understood the convention of our changelog format. [learn more](https://keepachangelog.com/en/1.0.0/)
This doesn't look like our changelog format 🤔 Can we just assume to follow the existing changelog format?

2022-02-01 22:13 UTC, bobheadxi commented on dev/release/src/release.ts
> +- [ ] I created a new H2 title named \`${release.version}\` after the \`Unreleases\` section if it doesn't already exist
```suggestion
- [ ] Create a new H2 title named \`${release.version}\` after the \`Unreleased\` section if it doesn't already exist
```

2022-02-01 22:13 UTC, bobheadxi commented on dev/release/src/release.ts
> +- [ ] I copied all changelogs of the commits belong to this patch release into the new H2 title \`## ${release.version}\` and they are grouped by type (e.g. \`### Added\`, \`### Changed\`).
```suggestion
- [ ] Copy all changelog entries of the commits belong to this patch release into the new H2 title \`## ${release.version}\`, grouped into the types they were originally in (e.g. \`### Added\`, \`### Changed\`).
```

At this point, changelog entries should already be there as part of the cherry-picked commits

2022-02-01 22:29 UTC, michaellzc commented on dev/release/src/release.ts
> +- [ ] I understood the convention of our changelog format. [learn more](https://keepachangelog.com/en/1.0.0/)
I was assuming our format is derived from the keepachangelog format. They're close enough besides we don't have the date in the H2. Also, change types are slightly different, but every project has its own flavour.

But yeah, I think we can just ask the Release Captain to review our current changelog to learn about our convention.

```suggestion
- [ ] I understood the convention of our changelog format. [learn more](https://github.com/sourcegraph/sourcegraph/blob/main/CHANGELOG.md)
```

2022-02-01 22:32 UTC, bobheadxi commented on dev/release/src/release.ts
> +                                    'Re-run Buildkite on this branch, and ensure the build passes before merging this pull request'
```suggestion
                                    'Re-run Buildkite on this branch (e.g. with `sg ci build` and merge when the build passes.'
```

2022-02-01 22:32 UTC, bobheadxi commented on dev/release/src/release.ts
> +                                    'Run `yarn run release release:finalize` to generate the tags required. **Note** CI will not pass until this command is run.',
```suggestion
                                    'Run `yarn run release release:finalize` to generate the tags required. CI will not pass until this command is run.',
```

2022-02-01 22:34 UTC, bobheadxi commented on dev/release/src/release.ts
> +- [ ] Copy all changelog entries of the commits belong to this patch release into the new H2 title \`## ${release.version}\`, grouped into the types they were originally in (e.g. \`### Added\`, \`###
This should all go here: https://github.com/sourcegraph/sourcegraph/pull/30453/files#diff-0a309d06fb33c975bf398ddb8063e971e7c2803fb89a223a7d0495926cd2392fR429-R431

2022-02-01 22:38 UTC, michaellzc commented on dev/release/src/release.ts
> +                                    'Re-run Buildkite on this branch, and ensure the build passes before merging this pull request'
maybe we should be more explicit and direct?
```
Run `sg ci build` to retrigger a build on Buildkit and merge when the build passes.
```

2022-02-01 22:40 UTC, bobheadxi commented on dev/release/src/release.ts
> +                                    'Re-run Buildkite on this branch, and ensure the build passes before merging this pull request'
I imagine someone will prefer to use the Buildkite UI - either `sg ci build` or using the UI works, which is why I left it as `.e.g.` 😛

2022-02-01 22:40 UTC, michaellzc commented on dev/release/src/release.ts
> +                                    'Run `yarn run release release:finalize` to generate the tags required. **Note** CI will not pass until this command is run.',
The intention is to emphasize CI will not actually pass until we run  `yarn run release release:finalize` and we ask people to wait for CI run many times prior to this step.

This was confusing people who are first-time Release Captain.

2022-02-01 22:42 UTC, michaellzc commented on dev/release/src/release.ts
> +                                    'Re-run Buildkite on this branch, and ensure the build passes before merging this pull request'
this ⬇️ 

```
Re-run Buildkite on this branch (either run `sg ci build` or use the Buildkit UI) and merge when the build passes.
```

2022-02-01 22:42 UTC, bobheadxi commented on dev/release/src/release.ts
> +                                    'Run `yarn run release release:finalize` to generate the tags required. **Note** CI will not pass until this command is run.',
Yep! I think adding the note that it will be fail is good, but I'm not sure it needs to be `**Note**`d, there's not too much content here - mostly a nit :)

2022-02-01 22:43 UTC, bobheadxi commented on dev/release/src/release.ts
> +                                    'Re-run Buildkite on this branch, and ensure the build passes before merging this pull request'
```suggestion
                                    'Re-run Buildkite on this branch (either run `sg ci build` or use the Buildkite UI) and merge when the build passes.'
```

2022-02-01 22:45 UTC, michaellzc commented on dev/release/src/release.ts
> +                                    'Re-run Buildkite on this branch, and ensure the build passes before merging this pull request'
`--wait` 🪄

2022-02-02 00:05 UTC, bobheadxi approved these changes

2022-02-02 00:05 UTC, bobheadxi reviewed
![cool](https://graphite-user-uploaded-assets.s3.amazonaws.com/default-memes/cool.gif)

2022-02-02 00:06 UTC, merged