ci: caching mechanism for stateless agents
sourcegraph/sourcegraph pull request #30492
Opened 2022-02-01 15:19 UTC by jhchabran

Follow-up of https://github.com/sourcegraph/sourcegraph/pull/30123 

See #21130

This adds support for caching to improve build times on stateless agents. Without it, the build times are so high that it challenges the whole idea of going stateless.

It caches the biggest drags of moving to stateless agents (Docker excluded)

- [x] Node modules
	- about 200s saved on every build involving node
	- that can be taken further by working with yarn specifics, but it requires investing more time.

- [x] asdf 
	- about 20s saved on every builds
	- less external HTTP calls

- [ ] ~Go modules Cache~ will fix 
	- Need to enable the cache plugins to deal with absolute paths, postponed for the moment, should just be a matter of patching the plugin for those specific cases.

Other changes:

- If `WANT_STATELESS` is set to true, the pipeline generator will force a build of the `MainDryRun` type, targeting the `job` queue. 
- Fixed the Plugin function that allowed to use of only a single plugin
- Added docs enabling everyone to make use of the cache.
- Updated the pre-command hook to use asdf caching if and only if we're running on a stateless agent

➡️ Once this is merged, we can set up a scheduled build that takes the latest main and builds it on the stateless agents, let's say every hour. From there, we can observe its behavior until we are confident enough to roll it out.

2022-02-01 18:56 UTC, davejrt commented
How do we decide when to use `post-checkout` vs `pre-command`, you mentioned the other day @bobheadxi enlightened you to the fact that something only runs once. Is this related?

2022-02-01 23:29 UTC, bobheadxi requested changes
See inline comments

2022-02-01 23:29 UTC, bobheadxi commented on .buildkite/hooks/post-checkout
> +asdf install awscli
Should we have this in `pre-command` alongside other `asdf` commands?

2022-02-01 23:29 UTC, bobheadxi commented on doc/dev/how-to/cache_ci_artefacts.md
> +# How to cache CI artefacts
We should link to this page from https://docs.sourcegraph.com/dev/background-information/continuous_integration#pipeline-development

2022-02-01 23:29 UTC, bobheadxi commented on enterprise/dev/ci/internal/buildkite/buildkite.go
> +func WantsStatelessBuild() bool {
Can we change this to `buildkite.FeatureFlags.StatlessBuild`? Where:

```go
type featureFlags struct { StatelessBuild bool }
var FeatureFlags = featureFlags{ StatelessBuild: os.Getenv("STATELESS_BUILD") == "true") }
```

We used to have every operation calling out to random variables whenever they wanted to change whatever they wanted to, it was a nightmare 😂 We should make sure the intent of this is clear. I also think introducing the use of feature flags here is a good idea, but used sparingly

2022-02-01 23:29 UTC, bobheadxi commented on enterprise/dev/ci/internal/buildkite/buildkite.go
> +func FlattenStepOpts(stepOpts ...StepOpt) StepOpt {
I think we should privatize this if there's no need to export

```suggestion
func flattenStepOpts(stepOpts ...StepOpt) StepOpt {
```

2022-02-01 23:29 UTC, bobheadxi commented on enterprise/dev/ci/internal/ci/cache_helpers.go
> +		return nil
We should return a no-op step instead of having to worry about nil checks in many places

2022-02-01 23:29 UTC, bobheadxi commented on enterprise/dev/ci/gen-pipeline.go
> +
What is the intent of this? Doesn't this mean PR builds will become`main-dry-run`s?

If there is an issue the build should simply fail, so I don't think we should defend ourselves against deployments this way - if we don't want it to run on main, we should just not have `main` builds run on stateless agents

2022-02-02 11:41 UTC, jhchabran commented on enterprise/dev/ci/gen-pipeline.go
> +
>  if we don't want it to run on main, we should just not have main builds run on stateless agents

It's not that we don't want to run in on main, but that we want to pretend to run it on `main`, without affecting the normal operations for everyone, for a few days. 

> If WANT_STATELESS is set to true, the pipeline generator will force a build of the MainDryRun type, targeting the job queue.

The idea is to be able, through an additional environment variable to force a build on the stateless agents. Then we can use that variable to set up a scheduled build that will run what's building on the `main` branch for a few days. 

From there, we can observe how it performs for a few days without messing up with everyone's workflow on the CI.

2022-02-02 15:59 UTC, bobheadxi commented on enterprise/dev/ci/gen-pipeline.go
> +
Ah, I see - I thought we were A/B testing this against some % of all builds, and this flag would just make sure builds on the A/B test machines behaved correctly. In that scenario forcing a `main-dry-run` would not be ideal

2022-02-04 15:30 UTC, jhchabran commented on enterprise/dev/ci/internal/ci/cache_helpers.go
> +		return nil
Good idea!

2022-02-04 15:36 UTC, jhchabran commented on doc/dev/how-to/cache_ci_artefacts.md
> +# How to cache CI artefacts
It's linked in there already, though it's not very clear as it's not in its own section. I'll fix that 👍 !

2022-02-04 15:45 UTC, jhchabran commented
> How do we decide when to use `post-checkout` vs `pre-command`, you mentioned the other day @bobheadxi enlightened you to the fact that something only runs once. Is this related?

It's just a semantic difference, post-checkout is mostly saying that what we do in there is related to git somehow.

2022-02-04 15:46 UTC, jhchabran commented on enterprise/dev/ci/internal/buildkite/buildkite.go
> +func WantsStatelessBuild() bool {
Done!

2022-02-04 16:03 UTC, bobheadxi commented
> It's just a semantic difference, post-checkout is mostly saying that what we do in there is related to git somehow.

I agree with this interpretation 👍

2022-02-04 17:15 UTC, davejrt approved these changes

2022-02-04 17:42 UTC, bobheadxi approved these changes
awesome 😀 a few comments on some inline docs we can improve on

2022-02-04 17:42 UTC, bobheadxi commented on enterprise/dev/ci/internal/buildkite/buildkite.go
> +var FeatureFlags = featureFlags{
```suggestion
// FeatureFlags are for experimenting with CI pipeline features. Use sparingly!
var FeatureFlags = featureFlags{
```

2022-02-07 10:11 UTC, jhchabran commented on enterprise/dev/ci/gen-pipeline.go
> +
FYI @bobheadxi, @davejrt I'm creating a new pipeline for this, so we don't trigger BuildChecker in case of failures.

2022-02-07 10:12 UTC, merged