wrap the executor queue handler in actor http middleware
sourcegraph/sourcegraph pull request #30508
Opened 2022-02-01 21:11 UTC by mollylogue

2022-02-01 21:22 UTC, eseliger approved these changes

2022-02-01 21:22 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Doing a quick lookup, I'm not sure the context holds an internal actor here, did you make sure it comes through as internal?

2022-02-01 21:26 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
@mollylogue I think this will not work unless `req.Header.Geet(headerKeyActorUID) = headerValueInternalActor`.

2022-02-01 21:27 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/actor/http.go?L108

2022-02-01 22:01 UTC, mollylogue commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
So, that's the next part of this. Ensuring the header is set properly on the request

2022-02-01 22:05 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
You could do it in the [frontend reverse proxy](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@07f36e14cfed5728e886dea12f87a38546d1f2d0/-/blob/enterprise/cmd/frontend/internal/executorqueue/reverseproxy.go?L75), or in the [executor client](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/executor/internal/worker/workspace.go?L43) by adding an `http.extraHeader=Key: Value` in the `git fetch` request.

If you do the former you'll only have a context when the frontend proxies to itself. If you do the latter you'll have a context at the edge of the request, but you'll need to make sure that the headers get passed through to the second request (either way you'll have to add something to that first link).

2022-02-01 22:06 UTC, efritz requested changes
Blocking for safety 🐒 ; see inline conversation

2022-02-01 22:18 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
@efritz it sounds like both those solutions are geared towards making blanket assumptions that requests are to be done with an `internal` actor - is that wise? Especially with the work towards sub-repo permissions more often than not it seems better to be explicit regarding what actors to use. If we know the specific callsites that make requests to executor perhaps we should set the `internal` actor on that callsite and only on that callsite

2022-02-01 22:20 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
These are the only callsites from `executor` -> `gitserver`, and we do currently assume the executor is an internal actor.

2022-02-01 22:28 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
In that case I think the change needs to happen at callsites where `executor` -> `gitserver`, the context should be set to `internal` explicitly there, or perhaps an additional middleware on top here that resets the incoming request context back to `internal`?

2022-02-01 22:35 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Yeah that sounds like the "latter" method I described:

1. Update the frontend reverse proxy [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@07f36e14cfed5728e886dea12f87a38546d1f2d0/-/blob/enterprise/cmd/frontend/internal/executorqueue/reverseproxy.go?L75) to keep the header from `executor` -> `frontend` on the request `frontend` -> `gitserver`
2. Update the `git clone` callsite [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8acef370698c24fbe9dcf3498b675957be9436d3/-/blob/enterprise/cmd/executor/internal/worker/workspace.go?L43) and ensure the header is set.

These endpoints are protected by a specific auth mechanism (shared key set in site-config + executor environ) for executors in this set of proxy routes.

2022-02-01 22:39 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Okay sounds good, thanks for clarifying! This can be done in 1 with the default libraries by migrating to `httpcli.InternalClientFactory` and attaching `actor.WithInternalActor` on the context, but 2 will require some custom finicking it seems

2022-02-01 22:40 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Is part two any more than adding `"http.extraHeader=X-Sourcegraph-Actor-UID: internal",` to the git command?

2022-02-01 22:41 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
That should be it! Out of curiosity, is this required for other git commands @mollylogue ? I imagine executor is not the only services that calls out to git clone - what's the standard for passing actors around for these commands elsewhere?

2022-02-01 22:42 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
This is the only one that does so _out of the cluster_, though. Everybody else should use the gitserver client and not this frontend proxy which only exists because executors can't reach internal services like gitserver/pgsql.

2022-02-01 23:13 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Ah right! Thanks again for clarifying

2022-02-01 23:15 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Dr. Eric Clarity Fritz, PhD

2022-02-01 23:25 UTC, mollylogue commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Okay cool. I'm going to look a bit more into how those two pieces interact since this is a part of the code I'm super unfamiliar with and I'll let you know if I have questions.

2022-02-01 23:26 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Feel free to block 30 mins off my calendar whenever I'm free if you'd like a live walkthrough or Q&A.

2022-02-01 23:33 UTC, mollylogue commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
Also @bobheadxi we are definitely seeing other requests with missing actors, but I'm not sure if there are any others going to gitserver for the reasons @efritz mentioned. This one was the biggest/most frequent offender based on the metrics, which is why we were looking into it first.

2022-02-01 23:33 UTC, mollylogue commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
@efritz A walk through would be amazing and super helpful. I'll find some time to do that.

2022-02-01 23:36 UTC, mollylogue commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
> Yeah that sounds like the "latter" method I described:
> 
> 1. Update the frontend reverse proxy [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@07f36e14cfed5728e886dea12f87a38546d1f2d0/-/blob/enterprise/cmd/frontend/internal/executorqueue/reverseproxy.go?L75) to keep the header from `executor` -> `frontend` on the request from `frontend` -> `gitserver`, and also
> 2. Update the `git clone` callsite [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8acef370698c24fbe9dcf3498b675957be9436d3/-/blob/enterprise/cmd/executor/internal/worker/workspace.go?L43) and ensure the header is set.
> 
> These endpoints are protected by a specific auth mechanism (shared key set in site-config + executor environ) for executors in this set of proxy routes.

This all makes sense to me and seems like the right move.

2022-02-01 23:37 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
If you'd like {myself, @eseliger, @Strum355, or @mrnugget} to add any additional headers from `executor` -> `frontend` for tracking we can do that at any time. Since we have to hand-deploy the executors, any changes will require some infra version bumps so the ball's generally in our court for that anyway.

Anything that hits any of [these routes](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@07f36e14cfed5728e886dea12f87a38546d1f2d0/-/blob/enterprise/cmd/frontend/internal/executorqueue/queuehandler.go?L30) will be authenticated as an executor. The only issues downstream of this is making sure that the proper middleware is applied here to keep the same context on the forwarded/proxied requests.

2022-02-01 23:44 UTC, mollylogue commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
@efritz I think the headers are copied over from one request to another [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@07f36e14cfed5728e886dea12f87a38546d1f2d0/-/blob/enterprise/cmd/frontend/internal/executorqueue/reverseproxy.go?L80)

2022-02-01 23:47 UTC, mollylogue commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
r/e your above message, I think we're moving toward always having the actor set as a header (even if it's just internal), so if that can be added in the future that'd be awesome.

2022-02-01 23:47 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
😎  The remaining routes accessible under `/.executors/` don't serve any repo data, so adding a header from the executor may be all that's necessary.

2022-02-01 23:50 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return actor.HTTPMiddleware(authMiddleware(accessToken, base))
https://github.com/sourcegraph/sourcegraph/pull/30520

2022-03-16 20:57 UTC, mollylogue commented
@efritz I'd like to get this merged eventually. Are you okay with this change?

2022-03-16 20:58 UTC, efritz approved these changes

2022-03-16 21:28 UTC, merged