added disableSnapshot param to batch files with 'Pages' in title
sourcegraph/sourcegraph pull request #30718
Opened 2022-02-05 05:10 UTC by adeola-ak

Closes #30337

As per Issue #30337, these changes are to add the `disableSnapshot: false` to batch change story parameters that we still wish to have snapshotting on

2022-02-07 05:34 UTC, courier-new requested changes
I think a couple unwanted changes snuck in with this commit, which are causing the CI checks to fail! Don't worry, we've all done that before. 😛 And it's a great opportunity to practice more git! Let's see if we can drop those auto-generated `schema` files and the test changes we were making for the `DiffHunk` stuff.

2022-02-07 05:34 UTC, courier-new commented on client/web/src/components/diff/DiffHunk.module.scss
> +    display: flex;
It looks like some of our testing from the diff line break issue snuck into this PR! We probably want to remove this change and the other ones to `DiffHunk.module.scss` and `DiffHunk.tsx`.

2022-02-07 05:34 UTC, courier-new commented on client/shared/src/graphql/schema.ts
> +export type ID = string
It looks like a couple auto-generated files also snuck in here. I haven't run into this before, but maybe we need to add them to .gitignore. For now we can probably just remove them from the commit, too.

2022-02-07 23:24 UTC, LawnGnome approved these changes
LGTM, with the caveat that I haven't thought very hard about which stories should be snapshotted, but it's easy enough for us to add more later if we don't have sufficient coverage here.

Good job!

2022-02-07 23:24 UTC, LawnGnome commented on .gitignore
> +client/shared/src/graphql/schema.ts
Ideally, this should be in a separate PR, but if someone frontendy (like Kelli or Erik) is OK with this, then I am too.

2022-02-07 23:30 UTC, eseliger approved these changes
LGTM, thanks for doing this :)

One small thought, I think we should file a follow-up ticket (or keep the original one open) to re-evaluate how well our components are covered in snapshot tests now. This is a good change to act quickly on our exploding screenshot number, but I think ideally we'd be evaluating some of the individual stories as well, looking where we can combine stories into a single chromatic snapshot perhaps.

2022-02-07 23:30 UTC, eseliger commented on .gitignore
> +client/shared/src/graphql/schema.ts
Yeah in general, things that aren't concerned with the main purpose of that PR should be done separately.

For this particular case, I wonder if it's actually needed at all, this file was moved to a different place and should not exist on disk anymore, and if so should just be removed. When we just gitignore it, it could stay around and might cause confusion when this file is accidentally loaded into the TS project? No strong opinion though.

2022-02-08 00:10 UTC, adeola-ak commented on .gitignore
> +client/shared/src/graphql/schema.ts
ahh yes, thanks for the heads up on this. I'll make note of that for good practice. 
I added that to gitignore because i was having conflicts with that file showing up when i was trying to push the changes on friday. I'll remove it now

2022-02-08 00:15 UTC, adeola-ak commented
@eseliger yea good point, I'll close the original but create a follow up ticket tomorrow to start adressing this

2022-02-08 00:15 UTC, courier-new approved these changes
🙌 Thanks Adeola!

2022-02-08 00:29 UTC, merged