Enable eslint-plugin-wildcard globally
sourcegraph/sourcegraph pull request #30830
Opened 2022-02-08 10:38 UTC by gitstart-sourcegraph

## Description
Eslint wildcard plugin, should enabled on the root eslintrc.

## Success Criteria
Eslint wildcard plugin, is enabled on the root eslintrc.

1) Enable eslint-plugin-wildcard, in the projects's root eslintrc.js file.
2) remove Link forbid rule from eslintrc.js file, since it would now be brought in through the wildcard plugin
3) Resolve all lint rule side effects

## Gitstart Ticket
[Link](https://app.gitstart.com/clients/sourcegraph/tickets/SG-30471)

## Gitstart Issue
[Link](https://github.com/sourcegraph/sourcegraph/issues/30471)

2022-02-08 10:44 UTC, gitstart-sourcegraph commented
Noticed global wildcard plugins are being completely overwrote by `no-restricted-imports` in package eslintrc files such as `web/.eslintrc.js`, what would you suggest regarding best workaround for this.

2022-02-14 07:15 UTC, valerybugakov reviewed
@gitstart-sourcegraph, looking into related ESLint issues, it seems there's no automated way to merge multiple rule configurations. Probably, we should do it manually in the root ESLint config for now.

cc @umpox

2022-02-22 12:51 UTC, eseliger approved these changes

2022-02-22 15:59 UTC, valerybugakov commented on client/search-ui/.eslintrc.js
> +  extends: ['../../.eslintrc.js', ...baseConfig.extends],
Could you clarify why this is required?

2022-02-23 06:48 UTC, gitstart-sourcegraph commented on client/search-ui/.eslintrc.js
> +  extends: ['../../.eslintrc.js', ...baseConfig.extends],
This was because we needed `react/forbid-elements` rule from wildcard since it’s also being overwritten on global `eslintrc` file. Would merge `react/forbid-elements` into the global `.eslintrc` file, so we could safely remove this lines.

2022-02-24 09:55 UTC, valerybugakov requested changes

2022-02-24 09:55 UTC, valerybugakov commented on client/web/src/auth/TosConsentModal.tsx
> +                <Form onSubmit={onSubmit}>
Are we sure that it won't cause unexpected changes? If you spent time checking each `Form` change manually — sounds good. Otherwise, I would disable the `react/forbid-elements` rule for each affected line.

2022-02-24 09:56 UTC, valerybugakov commented on client/search-ui/.eslintrc.js
> +  extends: ['../../.eslintrc.js', ...baseConfig.extends],
Thanks, the update looks great!

2022-02-28 13:02 UTC, valerybugakov requested changes

2022-02-28 13:02 UTC, valerybugakov commented on .github/workflows/label-notify.yml
> +                  team/delivery=@dan-mckean @caugustus-sourcegraph @kevinwojo
Let's not forget to review redundant changes before moving the PR to review.

2022-02-28 13:02 UTC, valerybugakov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/components/drill-down-insight-creation-form/DrillDownInsightCreationForm.tsx
> +        <Form innerRef={ref} onSubmit={handleSubmit} noValidate={true} className={classNames(className, 'p-3')}>
Should we revert this change and other similar occurrences?

2022-03-01 16:32 UTC, gitstart-sourcegraph commented on client/web/src/auth/TosConsentModal.tsx
> +                <Form onSubmit={onSubmit}>
@valerybugakov Thanks for reviewing, we reverted the `Form` migration changes and use `eslint disable` comments instead

2022-03-02 10:37 UTC, valerybugakov approved these changes
Thanks!

2022-03-02 14:19 UTC, merged