Update postgres 12.7
sourcegraph/sourcegraph pull request #30917
Opened 2022-02-09 20:43 UTC by david-sandy

Update due to this issue: 
https://nvd.nist.gov/vuln/detail/CVE-2021-32027

## Test plan

Upgraded postgres from 12.6 to 12.7.  I updated the Dockerfile on my local machine was able to run it successfully.

2022-02-14 15:54 UTC, eseliger commented
@sourcegraph/dev-experience how is determined which postgres version is used in CI?
If we don't bump the documented minimum version of postgres required to run sourcegraph, CI should stay on 12.6.

2022-02-14 16:00 UTC, caugustus-sourcegraph commented
There are a lot of required changes from updating the docker image name - very simple search shows all these references, some of which need to be updated in this PR: https://sourcegraph.com/search?q=context:%40sourcegraph+postgres-12.6&patternType=literal. (I wonder if we should reconsider naming the image `12.x` and instead go with `postgres-12`?)

We should probably do some extra testing on the upgrade from 12.6 -> 12.7 using snapshots of live data, just to confirm there's no surprises. Not sure what kind of tests we've done in the past - @daxmc99 @davejrt Any thoughts?

2022-02-14 21:57 UTC, daxmc99 commented
According to the [Postgres versioning policy](https://www.postgresql.org/support/versioning/) this upgrades _should be_ minimally disruptive since we are going from 12.6 to 12.7. 

However, we run some init scripts within our Postgres images. This means that we need to run a few tests with this new image to ensure everything works as expected. There appears to be no migration step, simply running the new image with the same data looks like it should work

> I wonder if we should reconsider naming the image 12.x and instead go with Postgres-12

I like this idea, we should be continually using the minor version since it appears to be what is suggested and we would avoid issues like this automatically.

2022-02-14 22:00 UTC, daxmc99 requested changes
Ensure that all Postgres 12.6 references are removed (maybe a batch change could help here?) as reported by https://sourcegraph.com/search?q=context:%40sourcegraph/all+postgres-12.6&patternType=literal

2022-02-18 16:10 UTC, coury-clark commented
Following up from a [conversation in Slack](https://sourcegraph.slack.com/archives/C07KZF47K/p1645199504538079?thread_ts=1645187335.810979&cid=C07KZF47K), this will be deferred to 3.38 and removed as a release blocker in 3.37.

2022-02-28 14:29 UTC, caugustus-sourcegraph requested changes
Instead of renaming the images from `12.6` to `12.7`, can you rename it to just `12`? This will make future minor updates less tedious, because image references in deployment repos will then be able to auto-update.

2022-03-03 13:58 UTC, david-sandy commented
This is superseded by #31933

2022-03-03 13:58 UTC, closed without merging