Add GraphQL query that fetches all Org flag overrides
sourcegraph/sourcegraph pull request #30957
Opened 2022-02-10 13:11 UTC by pjlast

This PR adds a GraphQL query that fetches all organization flag overrides for the current user. The database query for this already existed as part of another query, this simply uses that database query and hooks it up to the GraphQL API.

This allows the frontend to react differently if a user belongs to different organizations where the feature flag means different behaviour depending on the organization.

## Test plan

TODO

2022-02-10 13:35 UTC, rafax approved these changes
Nit: you probably want a better description of this PR.

2022-02-10 13:35 UTC, rafax commented on client/web/src/featureFlags/featureFlags.ts
> +    namespace: string
Should we use `org` or `orgId` instead of namespace here? Given the type name is OrgFlagOverride, I'm not sure what namespace can be.

2022-02-10 13:35 UTC, rafax commented on client/web/src/featureFlags/featureFlags.ts
> + * Fetches all organization feature flag overrides for the current user
```suggestion
 * Fetches all feature flag overrides for organizations that the current user is a member of
```
?

2022-02-10 13:37 UTC, pjlast commented on client/web/src/featureFlags/featureFlags.ts
> +    namespace: string
I actually had it as `orgId` first, but then because decoding the string leads to a string of "Org:1" I changed it to namespace. But you are absolutely correct, going to change it back to `orgID` and maybe just do some string processing instead to actually return the ID.

2022-02-10 14:12 UTC, kopancek requested changes

2022-02-10 14:12 UTC, kopancek commented on cmd/frontend/graphqlbackend/feature_flags.go
> +	flags, err := database.FeatureFlags(r.db).GetOrgOverridesForUser(ctx, user.ID)
We are transitioning to a new and better way to use database, this is the new way:
```suggestion
	flags, err := r.db.FeatureFlags().GetOrgOverridesForUser(ctx, user.ID)
```

2022-02-10 14:23 UTC, pjlast commented on client/web/src/featureFlags/featureFlags.ts
> +                orgID: atob(value.namespace.id).split(':')[1],
I'll see if I can find some other examples. Just feels strange to return an `orgID` thats not really an `orgID`, but I'll rather be consistent

2022-02-11 03:48 UTC, unknwon approved these changes

2022-02-11 03:51 UTC, unknwon commented
Agree with Milan on the unit tests. It's horrible to work with GraphQL in Go... but you'd probably want to look up examples in https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/graphqlbackend/org_test.go (note: we do not have corresponding test file for `feature_flags.go` yet).

2022-02-11 11:14 UTC, kopancek approved these changes

2022-02-11 11:19 UTC, merged