Code Insights: Add view insight pings for the in-product landing page
sourcegraph/sourcegraph pull request #31048
Opened 2022-02-11 09:58 UTC by vovakulikov

WIP
Closes https://github.com/sourcegraph/sourcegraph/issues/30608

## Todo

- [x] Extract ping logic from the View components
- [x] Use newly extracted logic for the dashboard insight cards
- [x] Add Get-started-pageview
- [x] Add Get-started-page-hovers for the first demo chart component
- [x] Get-started-primary-cta-click
- [ ] Get-started-template-copy-click and get-started-template-use-click
- [ ] Get-started-tab-[TABNAME]-click and get-started-tab-[TABNAME]-more-click
- [ ] Get-started-big-template-click
- [x] Get-started-query-modification and get-started-repo-modification
- [ ] Get-started-docs-clicks
- [ ] Get-started-page-hovers
- [ ] Video-plays-clicks

2022-02-11 14:21 UTC, vovakulikov commented
@Joelkw Just to be sure should all of these pings be tracked weekly like we currently do for other code insights-related pings?

2022-02-11 17:15 UTC, unclejustin approved these changes
Looks good to me 🌮 !

One minor nitpick about how LivePreviewContainer is getting overloaded, but I've opened a tech debt issue to address that later.

2022-02-11 17:15 UTC, unclejustin commented on client/web/src/enterprise/insights/components/creation-ui-kit/live-preview-container/LivePreviewContainer.tsx
> +                        )}
these nested ternary statements are out of control: [Debt issue here](https://github.com/sourcegraph/sourcegraph/issues/31085)

2022-02-11 17:51 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/creation-ui-kit/live-preview-container/LivePreviewContainer.tsx
> +                        )}
I feel really bad about this change. We definitely should revisit our live preview containers component and chart components as well. Thanks for filling the issue.

2022-02-11 19:12 UTC, vovakulikov commented
@coury-clark Whenever you have time please have a look at this commit https://github.com/sourcegraph/sourcegraph/pull/31048/commits/765cf2bd46b9f2ee922fcc86c5253c98975b475b where I tried to add new pings to the BE aggregation logic and I'm super not sure about what I've done there.

2022-02-11 20:30 UTC, coury-clark commented on client/web/src/enterprise/insights/components/creation-ui-kit/live-preview-container/LivePreviewContainer.tsx
> +                        )}
I ? have no ? idea ? what ? talking : about : justin : you're 😄

2022-02-11 20:32 UTC, coury-clark commented
> Whenever you have time please have a look at this commit https://github.com/sourcegraph/sourcegraph/commit/765cf2bd46b9f2ee922fcc86c5253c98975b475b where I tried to add new pings to the BE aggregation logic and I'm super not sure about what I've done there.

cc @CristinaBirkel (who is working on pings)

2022-02-14 22:43 UTC, CristinaBirkel approved these changes
Okay I've committed a few fixes and these seem to be working! 🎉 I went through and tested out each of the pings locally and made sure they're showing up under `site-admin/pings`. The only one I couldn't test was `InsightsGetStartedTabMoreClick` because I don't see that button on the landing page.

2022-02-15 22:04 UTC, coury-clark commented on internal/types/types.go
> +	WeeklyInsightsGetStartedUniquePageViews *int32
Since we are adding new fields here, we need to update the analytics schema. Since you've never done this, I'll put a PR up for you.

2022-02-15 22:05 UTC, coury-clark commented on internal/types/types.go
> +	WeeklyInsightsGetStartedUniquePageViews *int32
@CristinaBirkel something I've added to the technical roadmap is a refactor of these pings such that (similar to the WeeklyAggregatedUsage field) we can add new pings without adding new fields.

2022-02-15 22:06 UTC, coury-clark commented on internal/types/types.go
> +	GetStartedHovers          *int32
Can this just be a new insight type (line 1137) instead?

2022-02-15 22:09 UTC, coury-clark requested changes
Putting a hold on this PR until we update the analytics pipeline.

Left a few inline comments also.

2022-02-15 22:22 UTC, coury-clark commented
Here is a branch with some analytics updates https://github.com/sourcegraph/analytics/pull/354. I didn't include the changes to the insight usage type, I wanted to see the PR responses first.

2022-02-15 22:30 UTC, vovakulikov commented on internal/types/types.go
> +	GetStartedHovers          *int32
@coury-clark do you suggest to create a special insight type for tracking events from the landing page. Like `insightType: InProductLandingPageSearchInsight` or `insightType: InProductLandingPageCaptureInsight` and send those types for Hovers FE events like telemetry.log('InsighHover', { insightType: "InProductLandingPageSearchInsight"}) ?

2022-02-15 22:32 UTC, coury-clark commented on internal/types/types.go
> +	GetStartedHovers          *int32
Yeah exactly - does that seem reasonable? Is that a substantial amount of work?

2022-02-15 23:02 UTC, vovakulikov commented on internal/types/types.go
> +	GetStartedHovers          *int32
@coury-clark Yes, it does. I added new types because I was thinking it would be easier for the backend to support this new ping and we wouldn't need to change anything around types. But if it's an easy thing I can change this on FE. 

BTW what do you think about datumClick, UI customization FE events. Should we also send a different type there? (I think we should, but just checking)

2022-02-15 23:26 UTC, coury-clark commented on internal/types/types.go
> +	GetStartedHovers          *int32
I'd say if we introduce a new type it needs to be consistent for all of the pings that emit from the insight.

2022-02-16 01:52 UTC, Joelkw commented
@vovakulikov correct, they should track weekly, the same way our other pings track uniques + total counts weekly. Thank you!

Also @vovakulikov 
> This PR also refactors our existing pings logic
Statements like that are helpful, thank you! Can you make sure to test our existing pings are still working on k8s after we merge this? You can see pings here https://sourcegraph.looker.com/dashboards/208?Instance=dax%40sourcegraph.com or in the site admin pings page on k8s.

2022-02-16 12:28 UTC, vovakulikov commented
@Joelkw I check our ping statistic page and found an interesting bug/type mismatch. As you can see at the moment we have a bunch of possible values for the InsightType. This happened because FE sends different types of values for these types.

```json
[
   {  "InsightType": "CaptureGroup", "Edits": 0, ... },
   {  "InsightType": "LangStats", "Edits": 0, ... },
   {   "InsightType": "backend", "Edits": 0, ... },
   {   "InsightType": "captureGroupInsights", "Edits": 0, ... },
   {   "InsightType": "runtime", "Edits": 0, ... },
   {   "InsightType": "searchInsights", "Edits": 0, ... },
]
```

In this PR I fixed this and now possible values for the insightType is the following enum 
```ts
export enum CodeInsightTrackType {
    // standard search based insight 
    SearchBasedInsight = 'SearchBased',
    
    // standard lang stats insight
    LangStatsInsight = 'LangStats',
    
    // Standard capture group insight
    CaptureGroupInsight = 'CaptureGroup',
    
    // Any in product landing page insight
    InProductLandingPageInsight = 'InProductLandingPageInsight',
    
    // Any cloud landing page insight
    CloudLandingPageInsight = 'CloudLandingPageInsight'
}
```

Let me know if this change breaks something (from my perspective it shouldn't maybe I'm missing something)

@coury-clark I haven't changed anything on the backend since your changes. I assume that we should delete the landing page specific FE events that are grouped by insight type (since we have special insight types for the landing page insights) 

Also, I checked the ping page and I could see a new insight ping type there `InProductLandingPageInsight` but Hovers ping for this type is stuck at just 1 count. I'm not sure this is correct actually. Do we group these events by user id?

2022-02-16 12:31 UTC, vovakulikov commented on internal/types/types.go
> +	GetStartedHovers          *int32
https://github.com/sourcegraph/sourcegraph/pull/31048#issuecomment-1041442720

2022-02-16 16:49 UTC, coury-clark commented
@vovakulikov 

I don't see anything that would group hovers by user: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/internal/usagestats/code_insights.go?L44-54&utm_product_name=GoLand&utm_product_version=GoLand

2022-02-16 16:50 UTC, coury-clark commented on internal/types/types.go
> +	GetStartedHovers          *int32
Can we remove these new fields from InsightUsageStatistics now?

2022-02-16 16:50 UTC, coury-clark commented on internal/types/types.go
> +	GetStartedDataPointClicks *int32
```suggestion
```

2022-02-16 20:01 UTC, coury-clark approved these changes
Approved - still need to wait for analytics pipeline change to merge.

2022-02-16 23:14 UTC, Joelkw commented
@vovakulikov Thanks! Okay to divide them by type, sure.

2022-02-17 17:14 UTC, ebrodymoore commented
All good on my end to merge this. Just updated the schema so these data points can be received!

2022-02-17 18:44 UTC, merged