insights: add sub-repo permissions checker to code-insights worker
sourcegraph/sourcegraph pull request #31049
Opened 2022-02-11 10:28 UTC by sashaostrikov

As an initial implementation, sub-repo permissions are checked for every repo in search results of code insights search query. No caching (per repoID) is happening currently.

If repo supports sub-repo permissions, then search result related to this repo is excluded and the data point of this repo is dropped

## Test plan
I wrote unit tests for code-insights worker layer and database layer.

2022-02-11 19:56 UTC, bobheadxi commented on internal/database/sub_repo_perms_store.go
> +func (s *subRepoPermsStore) RepoIdSupported(ctx context.Context, repoId api.RepoID) (bool, error) {
What if I have a perforce repo, with no sub-repo perms, and want to run code insights over it? Maybe this should check for whether any sub-repo perms are actually configured for this code host as well

2022-02-11 20:25 UTC, coury-clark requested changes
Thanks for doing this!

Looks like one of the search paths also needs this filtering. I also have a question about this detection - we don't want to exclude *all* private repos - just the ones with sub-repo permissions enabled.

2022-02-11 20:25 UTC, coury-clark commented on internal/database/sub_repo_perms_store.go
> +SELECT EXISTS(
Does this query actually check for sub-repo permissions? To me this would filter out any private repo, which is not something we would want to do in Code Insights.

2022-02-11 20:25 UTC, coury-clark commented on enterprise/internal/insights/background/queryrunner/work_handler.go
> +func checkSubRepoPermissionsForRepoId(ctx context.Context, checker authz.SubRepoPermissionChecker, repoId api.RepoID, err error) (bool, error) {
I don't see the sub repo filtering applied to the streaming search mode.
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ao/sub-repo-perms-code-insights/-/blob/enterprise/internal/insights/background/queryrunner/work_handler.go?L257

2022-02-11 20:25 UTC, coury-clark commented on enterprise/internal/insights/background/queryrunner/work_handler.go
> +		if authz.SubRepoEnabled(checker) {
I'd suggest moving this check into the `checkSubRepoPermissions` function, since we already just assume errors out of that function exclude the repo.

2022-02-14 08:26 UTC, ryanslade reviewed
Agree with the other comments.

It's actually quite tricky to know whether a repo has any sub-repo permissions
because syncing them will only happen after the repo has already been added. For
this reason we can't simply look in the `sub_repo_permissions` table since initially
we won't have any data.

So for now we decided to simply check whether the repo was private and Perforce, as this
is the only external service we currently support for sub-repo permissions.

We could go one step further as @bobheadxi mentioned an join against the `external_services`
table. We'd then have to look into the config to check whether the sub repo permissions have
been enabled in the `authentication` section. Also, bear in mind that a repo could have been
added by more then one external service so we need to check for all rows in 
`external_service_repos`. Messy, but it can be done. 

Or, we can keep our existing code that basically filter our all Perforce repos when sub-repo 
permissions have been enabled on the instance. Much simpler and in practice I think will be fine. 
In the short term I don't imagine anyone will enable sub-repo permissions and then not enable it 
for their perforce repos.

2022-02-14 08:43 UTC, sashaostrikov commented on internal/database/sub_repo_perms_store.go
> +func (s *subRepoPermsStore) RepoIdSupported(ctx context.Context, repoId api.RepoID) (bool, error) {
AFAIK, there is no such thing as Perforce repo without sub-repo perms, because Perforce cannot "unsupport" this feature and therefore every Perforce repo includes sub-repo perms by default.

I even guess that there _should_ not be such thing as having a code host with Perforce repos and disabled sub-repo perms experimental feature. Because this way Sourcegraph will not be able to process the repo in a correct way. But considering human factor, this experimental feature can be disabled, that's why before invoking this function, there is a check in place: `if authz.SubRepoEnabled(checker)`

cc @ryanslade to sanity check my thoughts about Perforce and sub-repo perms

2022-02-14 08:44 UTC, sashaostrikov commented on internal/database/sub_repo_perms_store.go
> +SELECT EXISTS(
Well, that's a nice test case which I'm going to add now (private non-Perforce repo), thanks!

The predicates in SQL query are joined with ANDs, that's why this query will not filter out any private repo, but also consider it being a perforce (in current conditions) (`AND external_service_type IN (%s)`)

2022-02-14 08:45 UTC, ryanslade commented on internal/database/sub_repo_perms_store.go
> +func (s *subRepoPermsStore) RepoIdSupported(ctx context.Context, repoId api.RepoID) (bool, error) {
See my review comment 😄

2022-02-14 08:46 UTC, sashaostrikov commented on enterprise/internal/insights/background/queryrunner/work_handler.go
> +func checkSubRepoPermissionsForRepoId(ctx context.Context, checker authz.SubRepoPermissionChecker, repoId api.RepoID, err error) (bool, error) {
oh, that's a great catch, thanks! I will fix it

2022-02-14 08:59 UTC, sashaostrikov commented on enterprise/internal/insights/background/queryrunner/work_handler.go
> +		if authz.SubRepoEnabled(checker) {
Let me try and check if I can make it look not ugly. For now there are 2 such functions (differs in receiving repoID as a `string` or `api.RepoID`) and I cannot think about other way than to duplicate `if authz.SubRepoEnabled(checker)` in both of them

2022-02-14 14:32 UTC, sashaostrikov commented
@coury-clark I fixed/answered the comments, PTAL

2022-02-14 15:58 UTC, coury-clark commented on enterprise/internal/insights/background/queryrunner/work_handler.go
> +		if authz.SubRepoEnabled(checker) {
Yeah - that's fine. What you updated to is also fine! I was suggesting consolidating the enabled check inside those functions as well.

2022-02-14 16:14 UTC, coury-clark commented
> So for now we decided to simply check whether the repo was private and Perforce, as this
is the only external service we currently support for sub-repo permissions.

I'll assume this is okay for now and follow up with @Joelkw. This wasn't something that was entirely clear to us, but may be an acceptable trade off. The reality is Code Insights is substantially less valuable in this environment anyway, so nitpicking which repos get excluded might not be relevant.

2022-02-14 17:00 UTC, bobheadxi commented on internal/database/sub_repo_perms_store.go
> +func (s *subRepoPermsStore) RepoIdSupported(ctx context.Context, repoId api.RepoID) (bool, error) {
Thanks for the detailed responses Ryan and Alex!

2022-02-14 17:26 UTC, merged