symbols: Fix "too many SQL variables"
sourcegraph/sourcegraph pull request #31110
Opened 2022-02-11 23:40 UTC by chrismwendt

https://github.com/sourcegraph/sourcegraph/pull/27986 switched from deleting one path at a time to deleting all paths in one SQL query. The number of paths is unbounded, and we hit the limit on Sourcegraph.com:

`t=2022-02-11T22:56:12+0000 lvl=eror msg="diskcache.Cached Fetch" error="failed to fetch missing archive cache item: databaseWriter.WriteDBFile: store.DeletePaths: too many SQL variables" count=1.000 elapsed=5.384 component=symbols`

This reverts the behavior back to deleting one path at a time. Deleting 3287 paths took 197ms before this change and 204ms after.

## Test plan

Saved a SQLite DB that had paths deleted by running `sqlite3 file.zip .dump` from before and after this change, sorted, and compared them with `diff`. No difference.

2022-02-14 06:47 UTC, keegancsmith approved these changes

2022-02-15 14:05 UTC, efritz requested changes
I'd rather not make single-parameter requests in tight loops like this with _no_ batching.

2022-02-15 14:07 UTC, eseliger commented on cmd/symbols/internal/database/store/symbols.go
> -	return s.Exec(ctx, sqlf.Sprintf(`DELETE FROM symbols WHERE path IN (%s)`, sqlf.Join(pathQueries, ",")))
for postgres for sure, not sure if SQLite supports it, too
Maybe just try it? 

```go
s.Exec(ctx, sqlf.Sprintf(`DELETE FROM symbols WHERE path = ANY (%s)`, pq.Array(pathQueries)))
```

2022-02-15 14:28 UTC, efritz commented on cmd/symbols/internal/database/store/symbols.go
> -	return s.Exec(ctx, sqlf.Sprintf(`DELETE FROM symbols WHERE path IN (%s)`, sqlf.Join(pathQueries, ",")))
Yeah that's the use I was thinking of. @chrismwendt Doing this instead should keep the batch operation, make the query plan the same (so query insights only sees one parameter and correctly aggregates latencies, etc), and not have the parameter blow-up problem you're seeing with doing a sqlf join.

2022-02-15 21:03 UTC, chrismwendt commented on cmd/symbols/internal/database/store/symbols.go
> -	return s.Exec(ctx, sqlf.Sprintf(`DELETE FROM symbols WHERE path IN (%s)`, sqlf.Join(pathQueries, ",")))
`pq.Array()` throws the error: `store.DeletePaths: sql: converting argument $1 type: unsupported type sqlf.Query, a struct`, maybe because Postgres-style bindings are incompatible with the SQLite driver.

Unfortunately, SQLite doesn't support binding an array to a single variable. You have to bind each element to a different variable:

- https://github.com/mattn/go-sqlite3/issues/773#issuecomment-575143395
- https://github.com/mapbox/node-sqlite3/issues/373#issuecomment-74682286

2022-02-15 21:03 UTC, chrismwendt commented
What's the downside of the tight loop? It's almost as fast and the code is much simpler.

I went ahead and chunked paths 1,000 at a time.

2022-02-15 21:54 UTC, efritz commented
If this is all SQLite (and will stay that way) you can ignore me

2022-02-15 22:12 UTC, chrismwendt commented
I imagine if we switched away from SQLite we'd instrument the new code and find any hotspots.

Merging is still blocked 😬

2022-02-15 22:13 UTC, efritz approved these changes

2022-02-15 22:54 UTC, merged