codeintel: expose code intel info for `GitBlob`
sourcegraph/sourcegraph pull request #31442
Opened 2022-02-17 22:14 UTC by Strum355

Closes https://github.com/sourcegraph/sourcegraph/issues/31073

## Test plan

2022-02-17 23:58 UTC, efritz requested changes

2022-02-17 23:58 UTC, efritz commented on cmd/symbols/main.go
> +		log.Fatalf("Failed to create parser pool: %s", err)
_failed to parser pool_ 👨‍🍳

2022-02-17 23:58 UTC, efritz commented on cmd/symbols/internal/api/handler.go
> +	mapping, err := ctags.ListLanguageMappings(r.Context(), h.ctagsBinary)
You gotta update ctags dep here?

2022-02-17 23:58 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +	}
I feel like this is a good candidate for something in the lower resolver layer. Would be nice to have this tested and callable outside of graphql.

2022-02-17 23:58 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +	fmt.Println(path.Ext(filepath))
```suggestion
```

2022-02-17 23:58 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +var (
Can we move these declarations out into some other const-like package? This should be a nice source-of-truth for things like auto-generated docs/directories in the future.

2022-02-17 23:58 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +	return nil, nil
TODO?

2022-02-17 23:58 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +func (r *preciseCodeIntelSupportResolver) Indexers() *[]gql.CodeIntelIndexerResolver {
Does this have to be a pointer?

2022-02-17 23:59 UTC, Strum355 commented on cmd/symbols/internal/api/handler.go
> +	mapping, err := ctags.ListLanguageMappings(r.Context(), h.ctagsBinary)
Yea, that PR is pending

2022-02-18 00:03 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +	fmt.Println(path.Ext(filepath))
I'm gonna tweet charity majors

2022-02-18 00:04 UTC, efritz commented on cmd/symbols/internal/api/handler.go
> +	mapping, err := ctags.ListLanguageMappings(r.Context(), h.ctagsBinary)
- [ ] update go.mod

2022-02-18 11:11 UTC, mrnugget commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +			}
It probably doesn't matter, but I'd turn the loop around and compile the patterns only once.

2022-02-18 11:11 UTC, mrnugget commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +			hasNative = true
This feels like something that could be defined on the indexers and not in the GraphQL layer. As in: a `IsNative() bool` method on the indexers.

2022-02-22 14:14 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +func (r *preciseCodeIntelSupportResolver) Indexers() *[]gql.CodeIntelIndexerResolver {
the slice? Unfortunately yea, else it complains about it being "not a pointer" for purposes of being nil...even though a slice can be nil

2022-02-22 14:17 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +			}
Not sure what way youre thinking, `glob.Compile` only takes a single pattern, and each language has a unique (as i understand) set of patterns

2022-02-23 10:49 UTC, mrnugget commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +			}
Oh, I see. I misread the loop the first time.

2022-02-23 14:54 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +	return nil, nil
Done in [`430b957` (#31442)](https://github.com/sourcegraph/sourcegraph/pull/31442/commits/430b9573f57b08ae25680b71a687f99639ee2722)

2022-02-23 14:58 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_uploads.go
> +func (r *queryResolver) closestDumpIDs() []int {
:laff: you actually did it you madman

2022-02-23 15:04 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/resolvers/query_uploads.go
> +func (r *queryResolver) closestDumpIDs() []int {
![image](https://user-images.githubusercontent.com/18282288/155346036-660ddf38-c53d-4a9e-9c62-c3b31e3df774.png)

2022-02-23 16:11 UTC, efritz commented on cmd/frontend/graphqlbackend/codeintel.graphql
> +type GitBlobCodeIntelInfo {
Plan to still do this pre-merge?

2022-02-23 16:12 UTC, Strum355 commented on cmd/frontend/graphqlbackend/codeintel.graphql
> +type GitBlobCodeIntelInfo {
Yea in progress rn

2022-02-23 19:02 UTC, Strum355 commented on cmd/frontend/graphqlbackend/codeintel.graphql
> +type GitBlobCodeIntelInfo {
Done here, lmk wyt [`e8ee841` (#31442)](https://github.com/sourcegraph/sourcegraph/pull/31442/commits/e8ee8418c9f42fd61f8b2d35522969592edc55f8)

2022-02-23 19:22 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +var (
Done here, lmk wyt [`44e5cd8` (#31442)](https://github.com/sourcegraph/sourcegraph/pull/31442/commits/44e5cd84f402102318f18e9c7af17cc7419bbe76)

2022-02-23 21:12 UTC, efritz approved these changes
Nothing blocking :)

2022-02-23 21:44 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +			hasNative = true
I've changed this code for a new invariant, so I dont know if this is still particularly relevant

2022-02-23 22:39 UTC, Strum355 commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +	}
Done here, lmk wyt etc etc [`ab3a4f0` (#31442)](https://github.com/sourcegraph/sourcegraph/pull/31442/commits/ab3a4f00597f5a00b1e8b47c1b0c749a9c99005b)

2022-02-23 22:40 UTC, efritz commented on enterprise/cmd/frontend/internal/codeintel/resolvers/graphql/codeintel_info_resolver.go
> +	}
:shipit:

2022-02-24 14:17 UTC, merged