Add functionality and feature flag to allow hard deleting organizations
sourcegraph/sourcegraph pull request #31528
Opened 2022-02-19 02:17 UTC by miveronese

Ticket: https://sourcegraph.atlassian.net/browse/CLOUD-81

This PR adds the following:
- a new graphql mutation to allow hard deletion of organizations 
- a new HardDelete method (in the OrgStore)
- unit tests

## Test plan
### Unit tests
Run the new tests with:
`go test ./cmd/frontend/graphqlbackend/. -v -run TestRemoveOrganization` 
and 
`go test ./internal/database/. -run  TestDeleteOrganization_OnPremise -v`
`go test ./internal/database/. -run  TestDeleteOrganization_OnCloud -v`

### Manual test (via api/console)

1. Case one: you are in the DotCom mode but don't have the feature flag "org-deletion" enabled or it is set to false
Run `sg start dotcom` 
Go to the /api/console
Try to delete an organization by running the "removeOrganization" mutation
You should see an error message informing that this operation is not supported

2. Case two: you are in the DotCom mode and the feature flag "org-deletion" is set to true
Run `sg start dotcom` 
Go to the /api/console
Try to hard delete an organization by running the "removeOrganization" mutation
All should work and the org will be hard deleted from the orgs table and from the associated tables

3. Case three: you are not in the DotCom mode
Run `sg start` 
Go to the /api/console
Try to hard delete an organization
You should see an error message informing that this operation is not supported

### Queries
````
mutation CreateFeatureFlag{
	createFeatureFlag(
      name: "org-deletion",
	  value: false,
   ){
     __typename
   }
 }
````

```
mutation {
  removeOrganization(organization: "org-id") {
        alwaysNil

  }
}
```

2022-02-19 02:19 UTC, miveronese commented on client/web/src/org/backend.ts
> +export const ORG_DELETION_FEATURE_FLAG_NAME = 'org-deletion'
I'm  uncertain on how to properly feature flags for this case, so the  idea was to check if an org has the  "org-deletion" flag enabled and follow the example from email invitations.  

I didn't use "experimentalFeatures" because that  looks more like an option to manage external user access to some features via their user settings or organization settings that can be managed in the UI (correct me, please, if I got this wrong)

2022-02-21 15:51 UTC, miveronese commented on internal/database/orgs.go
> +}
@novoselrok , for notebooks, so far, I could see only the "settings" table being affected...  I'm wondering if , when I creating a notebook, I missed some step that could mean that data would be added to another table besides "settings"...

2022-02-21 16:14 UTC, kopancek requested changes

2022-02-21 16:14 UTC, kopancek commented on cmd/frontend/graphqlbackend/org.go
> +func (r *schemaResolver) HardDeleteOrganization(ctx context.Context, args *struct {
I would call it just `removeOrganization` to follow the convention we use on other graphql resolvers. And the resolver could either do a soft delete or hard delete, depending on the feature flag value. WDYT?

2022-02-21 16:14 UTC, kopancek commented on internal/gqltestutil/organization.go
> +
Was this intentional?

2022-02-21 16:14 UTC, kopancek commented on cmd/frontend/graphqlbackend/org.go
> +	enabled, _ := r.db.FeatureFlags().GetOrgFeatureFlag(ctx, orgID, OrgDeletionFeatureFlag)
instead of getting a feature flag for a specific organization, I think it would be better here if we have a global feature flag. We either want hard deletes on the whole instance or we don't.

2022-02-21 16:14 UTC, kopancek commented on client/web/src/org/backend.ts
> +export const ORG_DELETION_FEATURE_FLAG_NAME = 'org-deletion'
I think using the internal feature flagging API like you did is the best option here. But I think using a global flag instead of an organization override will be better.

2022-02-21 16:14 UTC, kopancek commented on client/web/src/org/backend.ts
> +}
We are trying to migrate away from the `requestGraphql` to use React hooks `useQuery` or `useMutation` instead. See the latest changes from Pietro for an example: https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/user/settings/privacy/UserSettingsPrivacyPage.tsx#L32

2022-02-21 16:16 UTC, novoselrok commented on internal/database/orgs.go
> +}
On Cloud, users don't have to add `showSearchNotebook` to their settings. The `showSearchNotebook` feature is enabled globally in the site-admin settings.

When creating a notebook only the `notebooks` table is affected. Here is the DB [code](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/notebooks/store.go?L334-359) for creating a notebook.

2022-02-21 17:44 UTC, miveronese commented on cmd/frontend/graphqlbackend/org.go
> +func (r *schemaResolver) HardDeleteOrganization(ctx context.Context, args *struct {
That's an interesting idea, Milan! And like it and will try that approach.

2022-02-21 17:45 UTC, miveronese commented on cmd/frontend/graphqlbackend/org.go
> +	enabled, _ := r.db.FeatureFlags().GetOrgFeatureFlag(ctx, orgID, OrgDeletionFeatureFlag)
It makes sense

2022-02-21 17:48 UTC, miveronese commented on internal/gqltestutil/organization.go
> +
Oops, that was unintentional -- a leftover that shouldn't have been committed.

2022-02-21 18:36 UTC, miveronese commented on client/web/src/org/backend.ts
> +export const ORG_DELETION_FEATURE_FLAG_NAME = 'org-deletion'
@kopancek , do you have an example to share on the use of global flag vs org override flag? I am not sure if I got this correctly.

2022-02-21 20:35 UTC, miveronese commented on cmd/frontend/graphqlbackend/org.go
> +	enabled, _ := r.db.FeatureFlags().GetOrgFeatureFlag(ctx, orgID, OrgDeletionFeatureFlag)
I am assuming that, in this case, the FF value should be fetched from the context?  Like this:
```
	flags := featureflag.FromContext(ctx)
	value := flags.GetBoolOr("org-deletion", false)
```

2022-02-22 06:30 UTC, kopancek commented on client/web/src/org/backend.ts
> +export const ORG_DELETION_FEATURE_FLAG_NAME = 'org-deletion'
Yes, you can try doing just that. If that does not work, you can use the same function as you do now, but from the DB package instead: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/feature_flags.go?L560

2022-02-22 06:31 UTC, kopancek commented on cmd/frontend/graphqlbackend/org.go
> +func (r *schemaResolver) HardDeleteOrganization(ctx context.Context, args *struct {
But now that I think about it. If we want this feature disabled everywhere else other than cloud, it might be better if it returns an error if the feature flag value is `false`.

2022-02-24 02:55 UTC, miveronese commented on cmd/frontend/graphqlbackend/org_test.go
> +		featureFlags.GetOrgFeatureFlagFunc.SetDefaultReturn(true, nil)
@sourcegraph/cloud-saas ,wondering why line 479 (`featureFlags.GetOrgFeatureFlagFunc.SetDefaultReturn(true, nil)`)  is not working as in other tests that use the same approach. I mean: even when the bool passed is true, the  test fails because the flag is not enabled.... I checked all tests that use this same approach and all work fine except another one in this same file. On line 244, when changing the bool passed to `featureFlags.GetOrgFeatureFlagFunc.SetDefaultReturn( )` to false,  I would expect the test to fail, but it doesn't... 🤔

2022-02-24 03:16 UTC, unknwon commented on cmd/frontend/graphqlbackend/org.go
> +	if err := database.Orgs(r.db).HardDelete(ctx, orgID); err != nil {
You likely want this otherwise you'll hit a panic once the feature flags mocking is fixed.

```suggestion
	if err := r.db.Orgs().HardDelete(ctx, orgID); err != nil {
```

2022-02-24 03:16 UTC, unknwon commented on cmd/frontend/graphqlbackend/org_test.go
> +		featureFlags.GetOrgFeatureFlagFunc.SetDefaultReturn(true, nil)
I did not dig deeper, but it looks to me the method you really want to mock is not the `GetOrgFeatureFlagFunc`.

```go
	flags := featureflag.FromContext(ctx)
	orgHardDeletionEnabled := flags.GetBoolOr("org-hard-deletion", false)
```

2022-02-25 03:34 UTC, miveronese commented on cmd/frontend/graphqlbackend/org.go
> +	if err := database.Orgs(r.db).HardDelete(ctx, orgID); err != nil {
thanks, @unknwon . That fixed the issue and saved from a rabbit hole. 🎉

2022-02-25 05:24 UTC, unknwon requested changes
Overall LGTM 👍 

Left some comments, request changes because I want to take a last look before merging.

2022-02-25 05:24 UTC, unknwon commented on cmd/frontend/graphqlbackend/org.go
> +// RemoveOrganization removes an org and all resources associated to it. Depending on the flag value, it will hard delete or soft delete the org.
>Depending on the flag value, it will hard delete or soft delete the org.

I do not see anywhere we are doing soft-delete? From what I understood, this endpoint is solely about hard deleting the organization, is that correct?

2022-02-25 05:24 UTC, unknwon commented on cmd/frontend/graphqlbackend/org.go
> +	}
We are currently swallowing the underlying error:

```suggestion
	if err != nil {
		return nil, err
	} else if orgDeletionFlag == nil || !orgDeletionFlag.Bool.Value {
		return nil, errors.New("hard deleting organization is not supported")
	}
```

2022-02-25 05:24 UTC, unknwon commented on cmd/frontend/graphqlbackend/org_test.go
> +	mockedFeatureFlag := featureflag.FeatureFlag{Name: "org-deletion", Bool: &featureflag.FeatureFlagBool{Value: false}, Rollout: nil, CreatedAt: time.Now(), UpdatedAt: time.Now(), DeletedAt: nil}
nit: could you break this struct initialization into multiple lines? (i.e. each field on its own line). This long is getting a bit long.

2022-02-25 05:24 UTC, unknwon commented on cmd/frontend/graphqlbackend/org_test.go
> +	})
Simpler way:

```suggestion
	featureFlags.GetFeatureFlagFunc.SetDefaultReturn(&mockedFeatureFlag, nil)
```

2022-02-25 05:24 UTC, unknwon commented on cmd/frontend/graphqlbackend/org_test.go
> +	})
ditto

2022-02-25 05:24 UTC, unknwon commented on internal/database/orgs.go
> +	}
I haven't checked each, but if we have defined `ON DELETE CASCADE` on the [database schema](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/schema.md), technically we do not need to do manual deletions. I only checked `names` table which does have this property.

2022-02-25 05:24 UTC, unknwon commented on internal/database/orgs.go
> +	}
Practically, what is the rationale of returning an error if I want to delete an organization that simply does not exist?

Also, is this checkpoint too late here? Because if this organization with the ID does not exist, how could other resources binding to the organization exist?

2022-02-25 05:24 UTC, unknwon commented on internal/database/orgs_test.go
> +	}
nit: We have this test helper
```suggestion
	require.NoError(t, err)
```

2022-02-25 19:43 UTC, miveronese commented on internal/database/orgs.go
> +	}
Yes,  you are right about the `names` table, @unknwon . It has a ON DELETE CASCADE (my bad :)) , but org_members doesn't, so I will keep the ones that don't have this property.

2022-02-28 04:33 UTC, unknwon approved these changes
Nothing blocking, LGTM 👍

2022-02-28 04:33 UTC, unknwon commented on cmd/frontend/graphqlbackend/org.go
> +		return nil, errors.New("hard deleting organization is not supported")
nit: this would the error message a bit more clear, since currently it is identical to the error message of the feature flag not enabled.
```suggestion
		return nil, errors.New("hard deleting organization is only supported on Sourcegraph.com")
```

2022-02-28 04:33 UTC, unknwon commented on internal/database/orgs.go
> +	}
99% sure that if there is no record exists, `getBySQL` returns error `sql.ErrNoRows`, so what you actually want would be:
```suggestion
	orgs, err := o.getBySQL(ctx, "WHERE id=$1 LIMIT 1", id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil
		}
		return err
	}
```

Ignore this if not the case.

2022-02-28 19:37 UTC, miveronese commented on internal/database/orgs.go
> +	}
`o. getBySQL`  returns an empty array when no record is found, so I will skip this suggestion.

2022-02-28 19:42 UTC, miveronese commented on cmd/frontend/graphqlbackend/org.go
> +func (r *schemaResolver) HardDeleteOrganization(ctx context.Context, args *struct {
@kopancek , I think I need your 👍  before be allowed to merge this PR. :)

2022-03-01 03:47 UTC, unknwon commented
Never tried, but looks like we may be able to dismiss reviews. If you feel your other work are being blocked by merge of this PR and you're confident, let's dismiss and rely on post-merge feedback. Otherwise, let's wait for Milan.

<img width="939" alt="CleanShot 2022-03-01 at 11 46 11@2x" src="https://user-images.githubusercontent.com/2946214/156101006-16f1aa8f-865f-4f8b-8c66-68ec8d87acdd.png">

2022-03-01 03:48 UTC, unknwon commented
BTW CI is not passing.

2022-03-01 07:38 UTC, rafax commented on cmd/frontend/graphqlbackend/org.go
> +	} else if orgDeletionFlag == nil || !orgDeletionFlag.Bool.Value {
nit: do you really need the else here? if the previous condition is true, we will exit the function, so I think we can remove the else to follow the Go style https://go.dev/doc/effective_go#if

2022-03-01 07:38 UTC, rafax commented on internal/database/orgs.go
> +	if _, err := tx.Handle().DB().ExecContext(ctx, "DELETE FROM org_members WHERE org_id=$1", id); err != nil {
nit: would it make sense to add the delete statements to an array, and iterate over it? with the amount of repetition right now, it would be hard to spot a missing ! or any other small mistakes

2022-03-01 07:38 UTC, rafax commented on cmd/frontend/graphqlbackend/schema.graphql
> +    Removes an organization.
Can you provide more context here for users of this API- how is "removeOrganization" different from "deleteOrganization" above? Should one be called "hardDelete"? Or, should we mention one of those marks the org a as deleted, and the other cleans up dependencies and deletes?

2022-03-01 17:54 UTC, miveronese commented on cmd/frontend/graphqlbackend/org.go
> +	} else if orgDeletionFlag == nil || !orgDeletionFlag.Bool.Value {
Good point, @rafax ! I will update this part.

2022-03-01 18:11 UTC, miveronese commented on cmd/frontend/graphqlbackend/schema.graphql
> +    Removes an organization.
I update the description of both methods (removeOrganization and deleteOrganization) @rafax , but haven't changed the name of the first to "hardDelete" -- initially, it was named this way, but @kopancek  noted that a better name would be "removeOrganization" as this is the convention we use on other graphql resolvers.

2022-03-02 02:30 UTC, unknwon requested changes
Request changes because I think we need [authz check](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@19c853f071131e0598ba16a931570484921ce34c/-/blob/cmd/frontend/graphqlbackend/org.go?L143), otherwise anyone is able to delete any org on cloud.

2022-03-02 02:52 UTC, unknwon commented on cmd/frontend/graphqlbackend/schema.graphql
> +    Removes an organization.
Forgot the fact we already have `deleteOrganization`, then I strongly think we should just add `hardDelete` option instead of a new method, like for deleting users: 

https://github.com/sourcegraph/sourcegraph/blob/ff97e1deece731ead34679cc490b4adc2aa97f11/cmd/frontend/graphqlbackend/schema.graphql#L210

2022-03-02 10:55 UTC, rafax commented on internal/database/orgs.go
> +		query := fmt.Sprintf("DELETE FROM %s WHERE %s=%v", t, tablesAndKeys[t], id)
nit: inline query? but up-to-you

2022-03-02 10:57 UTC, rafax requested changes
I think we need a bit more authz here

2022-03-02 10:57 UTC, rafax commented on cmd/frontend/graphqlbackend/org_test.go
> +	t.Run("Returns an error when in DotComMode but feature flag is not enabled", func(t *testing.T) {
Add a case for user trying to delete an org they are not a member of?

2022-03-03 00:42 UTC, miveronese commented on cmd/frontend/graphqlbackend/schema.graphql
> +    Removes an organization.
@unknwon , I've following your suggestion to use `deleteOrganization` instead of `removeOrganization` and am wondering if it is ok to leave that first function (`deleteOrganization`) where it is now [(in graphqlbackend/site_admin.go](https://github.com/sourcegraph/sourcegraph/blob/ff97e1deece731ead34679cc490b4adc2aa97f11/cmd/frontend/graphqlbackend/site_admin.go#L102))  or if it would make more sense to move it to [/graphqlbackend/org.go](https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/graphqlbackend/org.go)

2022-03-03 03:54 UTC, miveronese commented
@unknwon and @rafax , the PR has been updated based on your last suggestions. 
- Deleted the `removeOrganization` function and moved its logic to  the `deleteOrganization`, so now it can handle both soft and hard deletions.
- Added a check to allow only org members to hard deleting their org
- Updated the tests accordingly
(Fingers crossed :D )

2022-03-03 07:55 UTC, unknwon commented on internal/database/orgs.go
> +		query := fmt.Sprintf("DELETE FROM %s WHERE %s=%v", t, tablesAndKeys[t], id)
FYI, `fmt.Sprintf` is vulnerable to SQL injection, though I don't think it matters here as values are essentially hard-coded in code. But could be better to put a [security comment](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+SECURITY%3A&patternType=literal) saying be cautious about changing lines here.

The "correct" way is:

https://github.com/sourcegraph/sourcegraph/blob/9b506745ca5548a85eb76ec688ead71146e78bb1/internal/database/repos.go#L1598

2022-03-03 08:07 UTC, unknwon approved these changes
Nothing blocking from me, thanks for the followup!

2022-03-03 18:13 UTC, miveronese commented
> Nothing blocking from me, thanks for the followup!

Yes!

2022-03-04 00:52 UTC, miveronese commented
Trying to figure out what the error showed by buildkite/sourcegraph ("Misc linters") mean... I run the linters several times locally and didn't see any errors... 🤔  Any suggestions?

2022-03-04 06:47 UTC, unknwon commented
> Trying to figure out what the error showed by buildkite/sourcegraph ("Misc linters") mean... I run the linters several times locally and didn't see any errors... 🤔 Any suggestions?

Looks like some copy paste error?  https://buildkite.com/sourcegraph/sourcegraph/builds/135078#ba83ca0f-6dea-45fc-8106-9869c7138d1b/769-770

```diff
-// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
-// the given values.
+// SetDefaultReturn calls SetDefaultHook with a function that returns the
+// given values.
```

Maybe try regenerate the mock?

2022-03-07 01:26 UTC, unknwon commented
Your build is now green! Let's ask @kopancek and @rafax to give a final look.

2022-03-07 07:43 UTC, kopancek approved these changes
LGTM!

2022-03-07 17:42 UTC, rafax approved these changes
A few non-blocking comments, LGTM otherwise.

2022-03-07 18:34 UTC, miveronese commented on cmd/frontend/graphqlbackend/site_admin.go
> +		// 🚨 SECURITY: For On-premise, only site admins can soft delete orgs.
Your observation makes sense, @rafax . By the way, do we want to allow soft delete for Cloud too?

2022-03-07 19:48 UTC, miveronese commented on cmd/frontend/graphqlbackend/site_admin.go
> +		// 🚨 SECURITY: For On-premise, only site admins can soft delete orgs.
Here's the commit with the helper and a check for soft delete + updated tests: https://github.com/sourcegraph/sourcegraph/pull/31528/commits/c4dc1a41e5993580a653120a5025e065db1c91c0

2022-03-08 04:12 UTC, unknwon commented on internal/database/orgs.go
> +	tablesAndKeys := map[string]string{
Makes total sense to me!

2022-03-08 18:44 UTC, merged