DRAFT Changes for backend
sourcegraph/sourcegraph pull request #31881
Opened 2022-02-25 18:13 UTC by david-sandy

This is a DRAFT.
This is on-going and needs more testing and needs the front-end (react) components completed.

## Test plan

2022-03-03 21:32 UTC, eseliger commented
Hi David! I think you can either [extend the JSContext](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/jscontext/jscontext.go?L49) which will then render the fields into the HTML head so that you can access them as `window.context.X`, or add new properties [to the site object in GQL](https://sourcegraph.com/gitlab.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L5181#tab=def) so you can dynamically query it when the signup form is rendered (just a suggestion, you can really add it anywhere in the GQL API where you think it makes sense). 

You can read the configured value in the backend using the `conf` package at `github.com/sourcegraph/sourcegraph/internal/conf`.

Those properties you can use in the frontend code to make the validation decisions. 

If anything about these mechanisms is unclear to you, please reach out :)

2022-03-04 10:48 UTC, eseliger commented
An empty array? That's very weird 🤔 Haven't seen that before. Are you sure you have configured something in the site config of your instance?

When I add something to the `experimentalFeatures`, it shows up for me:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/19534377/156749652-60b1462b-5e1e-4ef5-b6da-38c015c03e8c.png">

2022-03-11 14:31 UTC, jeanduplessis commented on client/web/src/auth/SignUpForm.tsx
> +import { nil } from 'ajv'
It would seem this import is not used in the file?

2022-03-11 14:39 UTC, eseliger requested changes
Added inline comments that should fix most of the CI issues for you and some code suggestions.

2022-03-11 14:39 UTC, eseliger commented on internal/database/users_test.go
> +  letters := 0
is this code indented using spaces? If so, can you please switch to tabs, otherwise the compiler will complain

2022-03-11 14:39 UTC, eseliger commented on client/web/src/auth/SignUpForm.tsx
> +import { nil } from 'ajv'
I don't see this being used

2022-03-11 14:39 UTC, eseliger commented on client/web/src/auth/SignUpForm.tsx
> +                asynchronousValidators: [validatePassword]
Looking at the code, it doesn't seem like it needs to be async? Would be a nice simplification if so.

2022-03-11 14:39 UTC, eseliger commented on client/web/src/auth/SignUpForm.tsx
> -                            minLength={12}
Can we still set this to the value we derive from the config? Ie 

```
minLength={window.context.experimentalFeatures.passwordPolicy?.enabled && window.context.experimentalFeatures.passwordPolicy.minimumLength ?? 12}
```

2022-03-11 14:39 UTC, eseliger commented on client/web/src/auth/SignUpForm.tsx
> +
```suggestion
function validatePassword(password: string): Observable<string | undefined> {
```

2022-03-11 14:39 UTC, eseliger commented on client/web/src/auth/SignUpForm.tsx
> +        }
`minimumLength` can be null here. You need to check if it is set first. The same applies to the rule below.

2022-03-11 14:39 UTC, eseliger commented on client/web/src/auth/SignUpForm.tsx
> +            const specialCharacters = /[!"#$%&'()*+,\-./:;<=>?@[\]^_`{|}~]/
Can we add a comment in the backend section and here to make sure this stays in sync?

2022-03-11 14:39 UTC, eseliger commented on client/web/src/user/settings/auth/UserSettingsPasswordPage.tsx
> +    private validatePassword(password: string): void {
Can we share this code between the two uses in the webapp? Should be relatively simple to have it return `string | undefined` and then make that work for both cases we have here.

2022-03-11 14:39 UTC, eseliger commented on schema/site.schema.json
>      "search.index.enabled": {
There seem to be unrelated formatting changes in here. Can you revert those please?

2022-03-11 14:39 UTC, eseliger commented on internal/security/security.go
> +	minPasswordRunes := conf.AuthMinPasswordLength()
Oh we already have a setting for the `minPasswordLength`? What's the deprecation strategy here? When the experimental password policies are enabled this won't be honored anymore.

2022-03-11 14:39 UTC, eseliger commented on internal/security/security.go
> +	minPasswordRunes := conf.AuthMinPasswordLength()
Good thing: Using your new method we finally reflect the validation rules in the frontend properly :)

2022-03-11 14:39 UTC, eseliger commented on internal/security/security.go
> +	upperCase := false;
```suggestion
	letters := 0
	numbers := false
	upperCase := false
```

2022-03-11 14:39 UTC, eseliger commented on internal/security/security.go
> +		return errors.New("password empty")
This is now inconsistent with the same check above https://github.com/sourcegraph/sourcegraph/pull/31881/files#diff-5686f50ca6130e9e6a93f5a6ad14d3b556317018f951d84b1e790150abec3ef5R31

2022-03-11 14:39 UTC, eseliger commented on internal/security/security.go
> +// This validates the password using the Paassord Policy configured
```suggestion
// This validates the password using the Password Policy configured
```

2022-03-11 14:39 UTC, eseliger commented on internal/security/security.go
> +// Package PasswordPolciy implements a configurable password policy
```suggestion
// Package security implements a configurable password policy
```

2022-03-11 15:28 UTC, quinnkeast commented
A best practice for any cases where we require a password is to also surface those requirements in the password form itself. Does this touch on that in any way, or rather, is it feasible for us to do this conditionally?

2022-03-14 15:52 UTC, david-sandy commented on client/web/src/auth/SignUpForm.tsx
> -                            minLength={12}
If it is not set, it will default to the old method.

2022-03-14 15:54 UTC, eseliger commented on client/web/src/auth/SignUpForm.tsx
> -                            minLength={12}
From an accessibility perspective, it would be nice if we still set the min length property on the input correctly, either to 12 or to the configured value.

2022-03-14 15:54 UTC, david-sandy commented on client/web/src/auth/SignUpForm.tsx
> -                            minLength={12}
Gotcha.  Let me see if I can do that.

2022-03-14 15:56 UTC, david-sandy commented on internal/security/security.go
> +	minPasswordRunes := conf.AuthMinPasswordLength()
> Oh we already have a setting for the `minPasswordLength`? What's the deprecation strategy here? When the experimental password policies are enabled this won't be honored anymore.

Correct.

2022-03-14 15:59 UTC, eseliger commented on internal/security/security.go
> +	minPasswordRunes := conf.AuthMinPasswordLength()
Do we need to document that this is deprecated? Or can we maybe even re-use this property so we won't break it for existing customers?

2022-03-14 16:03 UTC, eseliger commented on internal/security/security.go
> +	minPasswordRunes := conf.AuthMinPasswordLength()
Two quick ideas would be:

- We could either drop the property from the password policy object that does the same and only use the old one across the board
- Or fall back to that deprecated value in the backend instead and populate the password policy length property using that config flag, if set.

2022-03-29 02:10 UTC, david-sandy commented on internal/database/users_test.go
> +  letters := 0
Corrected.

2022-03-29 02:13 UTC, david-sandy commented on client/web/src/auth/SignUpForm.tsx
> +        }
I think that is corrected.

2022-03-29 02:26 UTC, david-sandy commented on client/web/src/auth/SignUpForm.tsx
> -                            minLength={12}
Added.

2022-03-29 02:31 UTC, david-sandy commented on internal/security/security.go
> +	minPasswordRunes := conf.AuthMinPasswordLength()
The current password values and such are mostly hard coded.  The minLength were hardcoded to 12 as were the old password checks.  I would like to do this in a phase 2 rollout.

2022-03-29 02:49 UTC, david-sandy commented on dev/site-config.json
> +  "repoListUpdateInterval": 5,
Changed back.

2022-03-30 21:29 UTC, slimsag commented
@eseliger updated, PTAL

2022-03-31 17:02 UTC, eseliger approved these changes
Code LGTM, thanks for all the follow-ups @david-sandy!

2022-03-31 17:02 UTC, eseliger commented on dev/site-config.json
> +  "experimentalFeatures": {
Do we really need this policy on by default in dev? It makes it harder to quickly set up a few accounts with bogus passwords for local testing.

2022-04-11 16:29 UTC, merged