ci: run all jest tests in one operation
sourcegraph/sourcegraph pull request #31924
Opened 2022-02-28 13:32 UTC by valerybugakov

## Test plan

Ensure that all `jest` client tests are executed on CI.

2022-03-01 13:37 UTC, valerybugakov commented on enterprise/dev/ci/internal/ci/operations.go
> +	pipeline.AddStep(":jest::chrome: Test (client/browser)",
Titles made consistent with Go tests:

<img width="405" alt="Screen Shot 2022-03-01 at 16 36 24" src="https://user-images.githubusercontent.com/3846380/156178904-2a3adf38-5877-4fdc-a843-096ced95e49c.png">

2022-03-01 14:16 UTC, umpox approved these changes
Nice 👍

2022-03-01 15:51 UTC, bobheadxi commented on enterprise/dev/ci/internal/ci/operations.go
>  func frontendTests(pipeline *bk.Pipeline) {
Should we just inline this function alongside the other `:jest: Test` steps? Or move all the `:jest: Test` sub-steps into this function?

2022-03-01 15:53 UTC, bobheadxi commented on dev/ci/yarn-test.sh
> +yarn_test "$@"
FYI as of https://github.com/sourcegraph/sourcegraph/pull/31969 this is just the yarn command now without the need for the function (there should be a merge conflict)

2022-03-01 15:54 UTC, bobheadxi requested changes
See comments! Also watch out for https://github.com/sourcegraph/sourcegraph/pull/31969

2022-03-01 23:18 UTC, limitedmage commented on doc/dev/background-information/ci/reference.md
> +  - **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6
Does `Test (all)` include `client/web` and `client/browser`?

2022-03-02 08:01 UTC, valerybugakov commented on doc/dev/background-information/ci/reference.md
> +  - **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6
Nope, it doesn't.

2022-03-02 08:09 UTC, valerybugakov commented on enterprise/dev/ci/internal/ci/operations.go
>  func frontendTests(pipeline *bk.Pipeline) {
Unit tests are grouped with other pipeline steps by package: e.g., all `web` package specific steps are grouped under `func addWebApp()`. I want to keep this structure in place here, and we can revisit it in a follow-up PR.

2022-03-02 23:48 UTC, limitedmage commented on doc/dev/background-information/ci/reference.md
> +  - **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6
Awesome, thanks for confirming! I'm not too familiar with CI code so I won't "approve" the PR, but it looks good to me on the behavior side!

2022-03-03 02:42 UTC, bobheadxi commented on enterprise/dev/ci/internal/ci/operations.go
>  func frontendTests(pipeline *bk.Pipeline) {
Oh I see - I conflated this with the go tests, which adds everything in one operation

2022-03-03 02:47 UTC, bobheadxi commented on dev/ci/yarn-test.sh
> -cd "$1"
I think this means we can remove `root_dir` and just use relative paths instead (e.g. `JEST_JUNIT_OUTPUT_DIR="./test-reports"` on line 18)

2022-03-03 02:47 UTC, bobheadxi approved these changes
nice! 😁

2022-03-03 08:49 UTC, merged