Add frontend component to allow hard deleting an organization
sourcegraph/sourcegraph pull request #32031
Opened 2022-03-02 02:34 UTC by miveronese

Jira Ticket: CLOUD-81

This PR adds the frontend changes to allow Cloud users that are org members to hard delete the organizations they belong to.

## Test plan

For manual tests

1) When **not in DotCom mode**, the new component should not be visible and the current flow for deleting an org won't change
- Run `sg start` , create an org and visit the org Settings Page. 
- The "Delete this Organization" component should not be visible
- Go to the Site Admin area >  Organization and delete the new organization.
-  Check the database to confirm that the org has been only soft deleted but not hard deleted.
 
2) When in DotCom mode, the new component should be visible and orgs can be hard deleted by org members
- Run `sg start dotcom` , create an org and visit the org Settings Page. 
- The "Delete this Organization" component should be visible.
-  Delete the new organization. You should be redirected to the User Settings page.
-  Check the database to confirm that the org has been hard deleted.

Videos showing case 1 and 2:
https://user-images.githubusercontent.com/1552863/156676333-286463ef-aa4d-4eb8-8e7d-6c80ba66970c.mov
https://user-images.githubusercontent.com/1552863/156676371-b36058a6-e334-4b09-9f7e-705ba90aa69b.mov

Images:
<img width="1166" alt="Screen Shot 2022-03-03 at 4 20 10 PM" src="https://user-images.githubusercontent.com/1552863/156676516-7ca030fc-701a-43e9-8efa-f25a23624a2c.png">
<img width="1338" alt="Screen Shot 2022-03-03 at 4 20 33 PM" src="https://user-images.githubusercontent.com/1552863/156676542-0aa12357-4cf2-474c-b8a2-4653b9fe9609.png">

2022-03-02 02:41 UTC, miveronese commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +            <div>
Pardon my ignorance, but can a user that is not an Admin see the Org Settings page?
When adding this check, I assumed that the answer would be 'yes', but now I am not sure...

2022-03-02 02:54 UTC, unknwon commented
Side: Please mark PR ready for review if it is ready for review :) https://handbook.sourcegraph.com/departments/product-engineering/engineering/cloud/saas/#making-pull-requests-and-asking-for-code-reviews

2022-03-02 21:45 UTC, miveronese commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +            <div>
Thank you so so much, @quinnkeast ! These bullet points perfectly clarified everything :) 🙏

2022-03-04 06:32 UTC, unknwon commented
> Videos showing case 1 and 2:
> https://user-images.githubusercontent.com/1552863/156676333-286463ef-aa4d-4eb8-8e7d-6c80ba66970c.mov
> https://user-images.githubusercontent.com/1552863/156676371-b36058a6-e334-4b09-9f7e-705ba90aa69b.mov

In case you missed it, https://github.blog/2021-05-13-video-uploads-available-github/

2022-03-04 06:34 UTC, unknwon commented
This is all frontend so I won't going to review. Looks like you're using stacked PRs here, so you would want to first merge `mv/org-deletion` to `main`, then you need a pull and merge from `main` to `mv/org-deletion-frontend` before GitHub correctly displays the diff of this PR.

2022-03-04 12:52 UTC, kopancek requested changes
I noticed that the [build is failing with some errors](https://buildkite.com/sourcegraph/sourcegraph/builds/135145#bffbf480-de4c-47f7-8d8f-37c9cb2ec76f). Make sure to rebase from `main` and run eslint and prettier locally.

2022-03-04 12:52 UTC, kopancek commented on client/web/src/org/settings/DeleteOrg.tsx
> +        <div className="mt-3 mb-5">
is this wrapping div necessary? Can we provide proper styles on the `Container` itself?

2022-03-04 12:52 UTC, kopancek commented on client/web/src/org/settings/DeleteOrg.tsx
> +    const toggleDeleteModal = useCallback(() => setShowDeleteModal(show => !show), [setShowDeleteModal])
What is the point of `show => !show` here? Isn't this enough?
```suggestion
    const toggleDeleteModal = useCallback(() => setShowDeleteModal(!showDeleteModal), [setShowDeleteModal, showDeleteModal])
```

2022-03-04 12:52 UTC, kopancek commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +    const [isOrgNameValid, setIsOrgNameValid] = useState<boolean>()
I think a better name here would be `orgNamesMatch` or similar. Because we are not really testing validity, but if the names match.

2022-03-04 12:52 UTC, kopancek commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +        [org.id, history])
We've decided to refactor the use `rxjs` and `requestGraphql` to use `useQuery` or `useMutation` hooks instead. It seems like a perfect opportunity to use apollo, since this is new code.
Bonus - it gives us the `loading` and `error` states for free.

2022-03-04 12:52 UTC, kopancek commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +        {props.org.viewerIsMember && (
I think we can move this check to the top of the render method and return `null` if viewer is not member.

2022-03-04 12:52 UTC, kopancek commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +                    <strong>You are going to delete { org.name } from Sourcegraph.</strong>This cannot be undone. Deleting an organization will remove all of its synced repositories from Sourcegraph,
Nit - split into multiple lines
```suggestion
                    <strong>You are going to delete { org.name } from Sourcegraph.</strong>
                    This cannot be undone. Deleting an organization will remove all of its synced
                    repositories from Sourcegraph, along with the organization's code insights, 
                    batch changes, code monitors and other resources.
```

2022-03-04 12:52 UTC, kopancek commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +                    status={isOrgNameValid === undefined ? undefined : isOrgNameValid ? 'valid' : 'error'}                />
Can `isOrgNameValid` ever be `undefined`? What is the advantage of showing it as undefined? Shold we even show the input status? Wouldn't it be better to just disable the `Delete` button, like we do below?

2022-03-04 19:14 UTC, miveronese commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +        [org.id, history])
Milan, just to make sure I got this right.... 

I am using the `deleteOrganization` mutation that was already in place (In another PR, I updated that mutation by adding a new argument to it, `hard: boolean`.) 
As [deleteOrganization uses requestGraphql](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/site-admin/backend.ts#L884), I am assuming that I should refactor it [here](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/site-admin/backend.ts#L884) to use Apollo instead. Is this what you mean?

My first attempt was to avoid using the DeleteOrganization mutation from the `site-adin/backend.ts` file and, instead, add something like the following block `DeleteOrgModal.tsx` [client/web/src/org/settings/DeleteOrgModal.tsx]. But, when running the linters, I got an error (from the graqhpl codegen cli, I think) complaining that the DeleteOrganization mutation was defined twice.

```export const DELETE_ORG_MUTATION = gql`
    query DeleteOrganization($organization: ID!, $hard: Boolean) {
        deleteOrganization(organization: $organization, hard: true) {
        ...
        }
    }
```

2022-03-04 19:57 UTC, miveronese commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +        [org.id, history])
Or, on a 2nd thought, I think that just following [this example ](deleteOrganization) on how to use those hook without having to touch [deleteOrganization](deleteOrganization)  or duplicate it will be enough.... 🤔 https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/org/members/AddMemberToOrgModal.tsx

2022-03-04 23:14 UTC, miveronese commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +                    status={isOrgNameValid === undefined ? undefined : isOrgNameValid ? 'valid' : 'error'}                />
Yes, the check for `undefined` can be removed , indeed. But if we remove the status, we won't display those cool icons that inform the user once the name type matches or not... I think they provide a good user experience.

<img width="424" alt="Screen Shot 2022-03-04 at 3 10 38 PM" src="https://user-images.githubusercontent.com/1552863/156854528-d34d088a-6b69-4c23-b4ca-753c467cea64.png">
<img width="431" alt="Screen Shot 2022-03-04 at 3 10 46 PM" src="https://user-images.githubusercontent.com/1552863/156854529-4ef4e62e-9a8c-47b5-8329-611963dee24d.png">

2022-03-04 23:39 UTC, miveronese commented
Moved this PR  to Draft while addressing the PR reviewer suggestions/requests.

2022-03-05 01:56 UTC, miveronese commented
Percy is complaining here too... Wondering what is the course of action to to approve  the "visual changes"pointed by it?

2022-03-08 11:05 UTC, quinnkeast commented
> Percy is complaining here too... Wondering what is the course of action to to approve the "visual changes"pointed by it?

I can review/approve Percy checks—in this case, it seems like a buggy visual test on Percy's end.

2022-03-08 11:32 UTC, quinnkeast commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +                <p className="text-mutedpt-3">Please type the organization's name to continue</p>
Just spotted this: this string ought be the label for the input, rather than a separate `<p>` element.

2022-03-08 11:33 UTC, quinnkeast commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +                    Sourcegraph, along with the organization's code insights, batch changes, code monitors and other
```suggestion
                    Sourcegraph, along with the organization’s code insights, batch changes, code monitors and other
```

Nit: [smart apostrophe vs. dumb apostrophe](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/style_and_mechanics/#apostrophes).

2022-03-08 11:34 UTC, quinnkeast commented on client/web/src/org/settings/DeleteOrgModal.tsx
> +                <p className="text-mutedpt-3">Please type the organization's name to continue</p>
```suggestion
                <p className="text-mutedpt-3">Please type the organization’s name to continue</p>
```

Smart vs. dumb apostrophe tweak.

2022-03-09 01:15 UTC, miveronese commented
Hi @quinnkeast and @kopancek ,I've  just pushed the last changes  based on your reviews (used smart apostrophe + fixed a text that should be an Input label instead of a <p>). Here's an updated screenshot). 🙏 

<img width="771" alt="Screen Shot 2022-03-08 at 5 02 54 PM" src="https://user-images.githubusercontent.com/1552863/157353239-3d1b43b3-c7dd-45ba-99af-cc434031fd56.png">

2022-03-10 15:52 UTC, kopancek approved these changes
Looks good to me, good work 👍

2022-03-10 16:07 UTC, merged