Wildcard V2: <Popover /> style migration
sourcegraph/sourcegraph pull request #32306
Opened 2022-03-08 09:40 UTC by gitstart-sourcegraph

## Description
Manual Migrations to <Popover /> wildcard component, in highlighted files and components with usage of `dropdown-menu`

## Refs
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-27695)
[SourceGraph Link](https://github.com/sourcegraph/sourcegraph/issues/27695)
[Review Changes](https://www.chromatic.com/pullrequest?appId=5f0f381c0e50750022dc6bf7&number=30231&view=changes)
[Loom video](https://www.loom.com/share/9cf7574f320d43f1b8794167dbdd2a17)
[Parent Issue](https://github.com/sourcegraph/sourcegraph/issues/29200)

## Test Plan
 - Run web app using preview app.
 - Confirm there are no UI variations while comparing all use cases of Popover with prod environment

## Preview App
[Frontend](https://client-sourcegraph-frontend-pr-239.onrender.com/)
[Storybook](https://client-sourcegraph-storybook-pr-239.onrender.com/)

## Implementation
### Styles migration:
1. Migrate usage of `dropdown-menu` class to Wildcard Popover
1. Remove `dropdown-menu` Bootstrap dependency - reimplement styles in Popover CSS module

Note: `dropdown-menu` usage is also required for the `Menu` components. We should wait until this migration (https://github.com/sourcegraph/sourcegraph/issues/27701) is finished before migrating away from global styles.

## App preview:

- [Web](https://sg-web-contractors-sg-27695-1.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-mlyraxcmss.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

2022-05-19 05:26 UTC, valerybugakov commented
@gitstart-sourcegraph, could you take a look at this PR? We still want to get rid of the Bootstrap import.

2022-05-19 07:09 UTC, valerybugakov commented
Let's link to [a new parent issue](https://github.com/sourcegraph/sourcegraph/issues/29200) since [the Popover migration ticket](https://github.com/sourcegraph/sourcegraph/issues/27695#issuecomment-1131289656) is closed and the migration is completed.

2022-06-02 04:30 UTC, valerybugakov requested changes

2022-06-02 04:30 UTC, valerybugakov commented on client/web/src/nav/UserNavItem.tsx
> +                                About Sourcegraph <Icon as={OpenInNewIcon} />
Why did we remove accessibility attributes from the `Icon` here?

2022-06-02 04:30 UTC, valerybugakov commented on client/web/src/nav/UserNavItem.tsx
> +                            Help <Icon as={OpenInNewIcon} />
Why did we remove accessibility attributes from the `Icon` here?

2022-06-07 12:53 UTC, gitstart-sourcegraph commented on client/web/src/nav/UserNavItem.tsx
> +                                About Sourcegraph <Icon as={OpenInNewIcon} />
Resulted from wrong conflict resolution. Reverted...

2022-06-07 12:53 UTC, gitstart-sourcegraph commented on client/web/src/nav/UserNavItem.tsx
> +                            Help <Icon as={OpenInNewIcon} />
same as above

2022-06-08 03:45 UTC, valerybugakov approved these changes
Let's fix one more accessibility regression and merge this PR. 
Please keep an eye on unexpected changes like this.

2022-06-08 03:45 UTC, valerybugakov commented on client/wildcard/src/components/Menu/MenuText.tsx
> +    <Component ref={reference} {...props} className={classNames(styles.dropdownItem, className)}>
Should we keep the `role` attribute here?

2022-06-08 06:56 UTC, merged