remove redis cache dependency
sourcegraph/sourcegraph pull request #32413
Opened 2022-03-09 22:06 UTC by davejrt

An attempt at solving https://github.com/sourcegraph/sourcegraph/issues/30656 by creating an interface.

2022-03-09 22:09 UTC, davejrt commented
@bobheadxi this pass is basically following your advice to...make things not red. A lot of tests failing at the moment though so any pointers would be much appreciated.

2022-03-11 01:41 UTC, bobheadxi commented
@davejrt the line you linked there is to a test success! I think you're talking about this: https://buildkite.com/sourcegraph/sourcegraph/builds/136206#ca996ee0-ab1a-498a-b27b-51f963cdb795/131-417

To debug this, you'll want to go to the test in question, indicated like so:

```
     | 	/buildkite/builds/buildkite-agent-5c66fb6cd9-8dslc-1/sourcegraph/sourcegraph/internal/repos/github_test.go:824 +0x5f5
```

That is here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dt/abstract_cache/-/blob/internal/repos/github_test.go?L824

Here, you have provided a nil `NewCacheFunc`, this will cause a panic when the client tries to construct a new cache. You'll want to make sure this parameter is non-nil

2022-03-11 01:42 UTC, bobheadxi commented on internal/extsvc/github/common_test.go
> +func newTestClientWithAuthenticator(t *testing.T, auth auth.Authenticator, cli httpcli.Doer, newCache NewCacheFunc) *V3Client {
I just noticed this pattern the other day, I think this pattern calls for this to be called `NewCacheFactory`

2022-03-11 01:42 UTC, bobheadxi commented on internal/extsvc/github/redis.go
> +type NewCacheFunc func(key string, ttl int) Cache
I just noticed this pattern the other day, I think this pattern calls for this to be called `NewCacheFactory`

2022-03-11 01:43 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/app/app.go
> +	client := github.NewV3Client(apiURL, auther, nil, nil)
all usages where `nil` is provided will the constructor to panic, because right now we _always_ try to construct a cache. You probably want to provide:

```
newCache := func(key string, ttl int) github.Cache { return rcache.NewWithTTL(key, ttl) }
```

like you do elsewhere

2022-03-17 09:45 UTC, tsenart commented
I'm wondering if we still need caching at this layer given we have it also in the default httpcli clients: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/httpcli/client.go?L113&subtree=true

2022-03-21 09:46 UTC, jhchabran commented
I see that https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/260b10f5a998a31c46de4b32aac1830bcb750e1b?visible=4 happened only a few days ago, which makes me question why we're dealing with two caches either, where both are using `etags` (See https://sourcegraph.com/github.com/gregjones/httpcache@901d90724c7919163f472a9812253fb26761123d/-/blob/httpcache.go?L96-98) 

It leads the way down to https://docs.sourcegraph.com/admin/repo/permissions#teams-and-organizations-permissions-caching. 

I did not dig that far in the code yet to confidently answer if we need or don't need to cache things on top of what `httpcli` caches here. @indradhanush could you, if you have a minute briefly point us toward the answer to @tsenart question?

2022-03-21 09:46 UTC, jhchabran commented
I see that https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/260b10f5a998a31c46de4b32aac1830bcb750e1b?visible=4 happened only a few days ago, which makes me question why we're dealing with two caches either, where both are using `etags` (See https://sourcegraph.com/github.com/gregjones/httpcache@901d90724c7919163f472a9812253fb26761123d/-/blob/httpcache.go?L96-98) 

It leads the way down to https://docs.sourcegraph.com/admin/repo/permissions#teams-and-organizations-permissions-caching. 

I did not dig that far in the code yet to confidently answer if we need or don't need to cache things on top of what `httpcli` caches here. @indradhanush could you, if you have a minute briefly point us toward the answer to @tsenart question?

2022-03-23 00:30 UTC, bobheadxi commented
The GitHub package here likely predates all the httpcli improvements, and I didn't notice that we had caching at that layer when we implemented this and https://github.com/sourcegraph/sourcegraph/pull/31275 . I pulled up some context behind the original issue, https://github.com/sourcegraph/sourcegraph/issues/30656#issuecomment-1075779142 , for more details behind the goal of this change

@indradhanush do you think your `getConditional` from https://github.com/sourcegraph/sourcegraph/pull/31275 would be supported out of the box by `httpcli`, based on your investigation into this?

If that is the case, the next step would be to do some experiments with the GitHub API to determine if the other cached API call, `GetRepository` IIRC, can leverage the new `getConditional` function as well. Then we can implement this PR by completely removing all explicit caching from the GitHub client, which would be a great code cleanup.

However, looks like with `httpcli` importing `rcache`, so there's no way out of a redis dependency everywhere at the moment (as noted in the original issue context) - a potential follow-up would be to investigate if we can extract the redis dependency from `httpcli`. I'm not sure that's feasible at a glance without a sacrifice to the ergonomics of the libraries, but I think an initial step of removing the custom caching here would be good progress as well

2022-03-23 00:32 UTC, bobheadxi commented
@davejrt for context on conditional github requests, see https://github.com/sourcegraph/sourcegraph/pull/31275#issuecomment-1040861999

2022-03-23 06:45 UTC, indradhanush requested changes

2022-03-23 06:45 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_service_collaborators.go
> +	newCache := func(key string, ttl int) github.Cache { return rcache.NewWithTTL(key, ttl) }
```suggestion
	newCache := func(key string, ttl int) github.Cache { 
	    return rcache.NewWithTTL(key, ttl) 
	}
```

This might be easier to read quickly.

2022-03-23 06:45 UTC, indradhanush commented on internal/extsvc/github/v3.go
>  }
This cache should not have a TTL. We don't want to change this behaviour since orgs is a resource that does not change very frequently. The `ListOrganization` method handles invalidating the cache by using conditional requests, which helps us to check against the API if the content has changed without incurring a deduction from the API rate limit quota.

2022-03-23 06:51 UTC, indradhanush commented
> I did not dig that far in the code yet to confidently answer if we need or don't need to cache things on top of what httpcli caches here. @indradhanush could you, if you have a minute briefly point us toward the answer to @tsenart question?

> @indradhanush do you think your getConditional from https://github.com/sourcegraph/sourcegraph/pull/31275 would be supported out of the box by httpcli, based on your investigation into this

I haven't used the `httpcli` myself yet but if we can access the redis cache from the GitHub client, then I don't see any reason why we couldn't also reuse it instead of the extra cache that's baked into the client at the moment. I think it's worth a shot given that simplifies the GitHub client. And then as @bobheadxi suggested a potential follow up to inject the redis cache dependency into `httpcli` at initialisation instead of having it baked in. In that case we'd still reach our goal of removing redis as a dependency on this client, but it just takes a slightly longer route.

2022-04-13 17:30 UTC, closed without merging