database: Restrict site-admin affiliated errors
sourcegraph/sourcegraph pull request #32727
Opened 2022-03-17 14:32 UTC by tsenart

Site admins were so far loading errors for all org owned external services, not only their own and site-level.

This caused additional load in the DB as per this [Slack thread](https://sourcegraph.slack.com/archives/CMBA8F926/p1647518650685719).

## Test plan

Integration test.

2022-03-17 15:36 UTC, kopancek requested changes

2022-03-17 15:36 UTC, kopancek commented on internal/database/external_services_test.go
> +	// or self owned external services.
Should we add a case when the site-admin is also a member of the organization? In that case, that site-admin should get the error.

2022-03-17 15:36 UTC, kopancek commented on internal/database/external_services.go
> +  )
I think a correct check would be:
```suggestion
WHERE
  (
    (es.namespace_user_id = %s) OR
    (es.namespace_org_id IN (SELECT org_id FROM org_members WHERE user_id = %s)) OR 
    (%s AND es.namespace_user_id IS NULL AND es.namespace_org_id IS NULL)
  )
```

Not sure about the performance/syntax here, maybe doing a JOIN on the org_members table would do what we want as well

2022-03-17 15:57 UTC, kopancek commented on internal/database/external_services.go
> +  )
But now that I think about it, this can be an improvement for a follow up PR 🤔

2022-03-17 15:57 UTC, kopancek approved these changes

2022-03-18 06:00 UTC, unknwon commented on internal/database/external_services_test.go
> +	// or self owned external services.
>Should we add a case when the site-admin is also a member of the organization? In that case, that site-admin should get the error.

+1.

But this PR seems a pure gain so doesn't feel the need to block on this.

2022-03-18 09:46 UTC, eseliger approved these changes

2022-03-18 11:51 UTC, merged