batches: show status pill on "Executions" tab with active executions
sourcegraph/sourcegraph pull request #32795
Opened 2022-03-18 21:19 UTC by adeola-ak

Closes #32341

i am getting this error 

`Unsafe member access .state on an 'any' value.eslint[@typescript-eslint/no-unsafe-member-access]
`

`Unsafe member access .length on an 'any' value.eslint[@typescript-eslint/no-unsafe-member-access]
`

i dont know if this needs to be addressed as i do see a similar error somewhere else. I think I know why it's giving me the error but not exactly sure how to address it beside adding the question marks to only evaluate if certain values are true

## Test plan

Tested several different values and states and results were as expected

2022-03-21 01:50 UTC, LawnGnome requested changes
There's an issue with the filter logic right now, but I'm glad we already had everything we needed to figure out the value without adding a new field to the GraphQL call.

One thought: this has the same problem we (as a team, at least) discussed in another PR last week about only getting one page of `batchSpecs` in the batch change query, right? So the number we provide might be misleading if there are more than 100 executions in progress.

As a stopgap, could we also get `pageInfo { hasNextPage }` in the `batchSpecs` field in the `BatchChangeFields` fragment, and then use that to append a `+` to whatever number we show in the pill if we know there are more executions than we have in the `nodes` array?

Finally, on the type errors, I also see the same thing in VSCode. Doing a full TS build actually works as expected (the CI passes, and I can run it locally), but there's something about how our GraphQL generated types get included that seems to cause this on a regular basis — I often grapple with this and usually get frustrated and just let the CI figure it out. I'd love to know what I'm missing here as well!

2022-03-21 01:50 UTC, LawnGnome commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                                {batchChange.batchSpecs
I don't think this check is doing anything, since `batchSpecs` is ultimately a concrete type (taken from the generated `graphql-operations.ts`):

```tsx
    batchSpecs: {
        __typename?: 'BatchSpecConnection'
        nodes: Array<{ __typename?: 'BatchSpec'; state: BatchSpecState }>
    }
```

I'm fairly sure you can remove the entire ternary here, along with the question mark on `nodes`, and just keep `batchChange.batchSpecs.nodes.filter(...).length`.

2022-03-21 01:50 UTC, LawnGnome commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                            <Badge variant="warning" pill={true} className="ml-1">
I'm thinking this probably shouldn't be a warning if the number of executions is zero, because right now it looks like this:

![image](https://user-images.githubusercontent.com/229984/159195803-148988f9-fce1-44c8-8776-62856ef047c5.png)

If you move the logic to calculate the number of executions into a `useMemo()` hook up above, then you can use that value to figure out the right variant here as well.

2022-03-21 01:50 UTC, LawnGnome commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                                          node => node.state === 'PROCESSING' || 'QUEUED'
This conditional isn't quite right. If we put in the parentheses that the language implicitly adds when evaluating this, it ends up looking like this:

```ts
(node.state === 'PROCESSING') || 'QUEUED'
```

Or, put another way, the callback is essentially doing this:

```ts
if (node.state === 'PROCESSING') {
  return true
} else {
  return 'QUEUED'
}
```

This actually works, because `filter()` just looks to see if the return value isn't false-y, but what it really means is that the filter doesn't do anything right now, as every node will return either `true` or the string `'QUEUED'`.

Instead, you probably want:

```ts
node => node.state === 'PROCESSING' || node.state === 'QUEUED'
```

(Sidebar: some languages provide a dedicated function or operator for this, but as far as I can remember on a Monday morning, TypeScript isn't one of them. You _can_ do something similar with something like `new Set(['PROCESSING', 'QUEUED']).has(node.state)`, but that has extra overhead to create the set, and definitely isn't worth it for two entries. I'd probably start using that kind of construction if I either had tens of values to check against, or if I was doing that comparison a _lot_ and already had an array ready to go that I could turn into a set once.)

2022-03-21 12:06 UTC, eseliger commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                                          node => node.state === 'PROCESSING' || 'QUEUED'
Great explanation!

2022-03-21 14:47 UTC, adeola-ak commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                                          node => node.state === 'PROCESSING' || 'QUEUED'
ahhhh yes i should have noticed that mistake. Thanks for the explanation Adam! :)

2022-03-21 14:49 UTC, adeola-ak commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                                {batchChange.batchSpecs
makes sense! thank you

2022-03-21 14:53 UTC, adeola-ak commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                            <Badge variant="warning" pill={true} className="ml-1">
yes good point, never used useMemo let me do some research

2022-03-21 21:33 UTC, adeola-ak commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                            <Badge variant="warning" pill={true} className="ml-1">
any chance anyone can do a quick pair on this part? @LawnGnome @eseliger

2022-03-21 21:36 UTC, eseliger commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                            <Badge variant="warning" pill={true} className="ml-1">
Absolutely, but it's 10:30pm over here so please tomorrow :)

2022-03-21 21:45 UTC, adeola-ak commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                            <Badge variant="warning" pill={true} className="ml-1">
oh yea! hehe okay ill send an invite for tomorrow.Thanks!

2022-03-22 01:30 UTC, LawnGnome commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                            <Badge variant="warning" pill={true} className="ml-1">
I'm also happy to, but since I'm literally 12 hours out of sync with you right now, I suspect it'll be easier to work out a time with Erik!

2022-03-22 14:00 UTC, BolajiOlajide commented
> sorry this includes changes from my other branch :( thats what i was trying to avoid when i was doing git stash and stuff. Still have to get better with it, sorry about that. But you'll see I did add the useMemo and pagination changes on the last few files

No worries. If you want to pair on removing the things you don't need in the previous commit with git, I'm happy to hop on zoom with you. @adeola-ak

2022-03-22 20:02 UTC, adeola-ak commented
thanks @BolajiOlajide I just fixed it! This is ready for review again

2022-03-22 20:05 UTC, eseliger approved these changes
LGTM!

2022-03-22 20:05 UTC, eseliger commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                                {executingCount} {batchChange.batchSpecs.pageInfo.hasNextPage && <> + </>}
I don't think there should be a space before the number, wdyt? `20+` vs `20 +`
```suggestion
                                {executingCount}{batchChange.batchSpecs.pageInfo.hasNextPage && <>+</>}
```

2022-03-22 20:11 UTC, adeola-ak commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +                                {executingCount} {batchChange.batchSpecs.pageInfo.hasNextPage && <> + </>}
no space! removed it, thanks

2022-03-22 23:43 UTC, LawnGnome approved these changes
LGTM! Thanks for making those changes.

2022-03-23 01:05 UTC, courier-new approved these changes
Thanks Adeola, and thanks to everyone who helped share feedback on this while I was out, too. 🙂 I have the smallest of suggestions, just to keep us more consistent in our use of enums, but otherwise 🚢!

2022-03-23 01:05 UTC, courier-new commented on client/web/src/enterprise/batches/detail/BatchChangeDetailsTabs.tsx
> +            batchChange.batchSpecs.nodes.filter(node => node.state === 'PROCESSING' || node.state === 'QUEUED').length,
```suggestion
            batchChange.batchSpecs.nodes.filter(node => node.state === BatchSpecState.PROCESSING || node.state === BatchSpecState.QUEUED).length,
```

2022-03-23 01:46 UTC, BolajiOlajide approved these changes
Looks good!

2022-03-23 21:44 UTC, adeola-ak commented
@eseliger @BolajiOlajide any thoughts on why buildkite is failing? at first Kelli pointed out that it was due to adding the hasNextPage to the backend without adding the same field  to the types where needed. I think Ive now added the field to all the types needed but buildkite is still failing

2022-03-23 21:46 UTC, BolajiOlajide commented
> @eseliger @BolajiOlajide any thoughts on why buildkite is failing? at first Kelli pointed out that it was due to adding the hasNextPage to the backend without adding the same field to the types where needed. I think Ive now added the field to all the types needed but buildkite is still failing

<img width="1146" alt="Screenshot 2022-03-23 at 22 45 28" src="https://user-images.githubusercontent.com/25608335/159801157-0200d162-7d9b-4df6-bf25-afaff796e62e.png">

@adeola-ak There are some `eslint` errors, that's what's causing `buildkite` to fail.

2022-03-23 21:47 UTC, eseliger commented
The concrete logs are in the eslint step in buildkite:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/19534377/159801233-0baf0174-32d4-40bb-941a-4be20e97130c.png">

It is complaining about some imports section formatting. I think eslint should do that automatically for you when you run it over the file by saving it in the editor :)

2022-03-27 20:08 UTC, merged