insights: Creating insights in LAM also adds them to global dashboard
sourcegraph/sourcegraph pull request #32901
Opened 2022-03-22 16:27 UTC by CristinaBirkel

Part of https://github.com/sourcegraph/sourcegraph/issues/32796

## Description

WIP. Just putting this up for collaboration purposes.

## Test plan

TBD

2022-03-24 17:47 UTC, coury-clark requested changes
A few things that need to be addressed, but overall looks good

2022-03-24 17:47 UTC, coury-clark commented on enterprise/internal/insights/store/dashboard_store.go
> +SELECT id FROM dashboard WHERE type = 'limited access mode dashboard';
Would strongly prefer this string doesn't contain spaces, for example underscored. Would suggest something like 
`limited_access_mode`.

What is the default for this type? If we are going to introduce a dashboard type it might make sense to avoid nil values here and come up with a default standard type, even possibly `standard`.

2022-03-24 17:47 UTC, coury-clark commented on enterprise/internal/insights/store/dashboard_store.go
> +	id, _, err := basestore.ScanFirstInt(s.Query(ctx, sqlf.Sprintf(getLimitedAccessModeDashboardSql)))
Did you consider using an upsert query here? 
https://www.postgresqltutorial.com/postgresql-upsert/

2022-03-24 17:47 UTC, coury-clark commented on enterprise/internal/insights/store/dashboard_store.go
> +func (s *DBDashboardStore) EnsureLimitedAccessModeDashboard(ctx context.Context) (int, error) {
All of the db operations in this function should be wrapped in a transaction to ensure consistency.

2022-03-24 17:47 UTC, coury-clark commented on enterprise/internal/insights/store/insight_store.go
> +	uniqueIds := make([]string, 0)
I'd suggest taking a look at [`basestore.ScanStrings`](https://sourcegraph.com/search?q=context:%40sourcegraph/all+basestore.ScanStrings+) for consistency in the codebase

2022-03-24 17:47 UTC, coury-clark commented on enterprise/internal/insights/store/dashboard_store.go
> +SELECT id FROM dashboard WHERE type = 'limited access mode dashboard';
I'd also suggest we add this as a constant somewhere, similar to the other db enumerated values https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/store/store.go?L352:2

2022-03-24 17:49 UTC, leonore approved these changes
leaving a couple comments, but functionality wise it looks good to me!

2022-03-24 17:49 UTC, leonore commented on enterprise/internal/insights/background/license_check_test.go
> +		return basestore.ScanInt(timescale.QueryRow(`SELECT COUNT(*) FROM dashboard WHERE type = 'limited access mode dashboard'`))
should we have this as a var at the top of the file? and should we just call it `limited access mode`, since it's already in the dashboard table?

2022-03-24 17:49 UTC, leonore commented on enterprise/internal/insights/resolvers/dashboard_resolvers.go
> +	dashboards, err := tx.GetDashboards(ctx, store.DashboardQueryArgs{ID: []int{int(dashboardID.Arg)},
should there be a tech debt ticket to update the `DashboardQueryArgs` `ID` field to `IDs`, if it's too significant of a change to do here?

2022-03-24 17:49 UTC, leonore commented on enterprise/internal/insights/resolvers/insight_view_resolvers.go
> +		if args.Input.Dashboards != nil {
is this check necessary if we only populate `dashboardIds` when it is not nil above? (applies on line 625 below as well)

2022-03-24 18:46 UTC, CristinaBirkel commented on enterprise/internal/insights/store/dashboard_store.go
> +	id, _, err := basestore.ScanFirstInt(s.Query(ctx, sqlf.Sprintf(getLimitedAccessModeDashboardSql)))
Hmm, I haven't found a way to get this to work, because `type` isn't a unique column. Do you know what the query might look like?

2022-03-24 18:47 UTC, CristinaBirkel commented on enterprise/internal/insights/store/dashboard_store.go
> +SELECT id FROM dashboard WHERE type = 'limited access mode dashboard';
Agree to the constant; I definitely meant to do that at some point. And I don't mind changing the name. I was going to leave `type` as `NULL` when there isn't any special type, but don't have a strong preference there.

2022-03-24 18:49 UTC, CristinaBirkel commented on enterprise/internal/insights/store/dashboard_store.go
> +func (s *DBDashboardStore) EnsureLimitedAccessModeDashboard(ctx context.Context) (int, error) {
I added that in here: https://github.com/sourcegraph/sourcegraph/pull/32992/files#diff-04b9b038b3daf5c0ff7c9a82a611e0133fdfe63bbbaa24ce60142e2f1ee07c4eR334

I think prior to that PR the only usages were already wrapped in a transaction, but yes definitely makes sense.

2022-03-24 18:50 UTC, CristinaBirkel commented on enterprise/internal/insights/store/insight_store.go
> +	uniqueIds := make([]string, 0)
Perfect, thank you!!

2022-03-24 18:51 UTC, CristinaBirkel commented on enterprise/internal/insights/resolvers/dashboard_resolvers.go
> +	dashboards, err := tx.GetDashboards(ctx, store.DashboardQueryArgs{ID: []int{int(dashboardID.Arg)},
I left it as-is because we already have `UserID` and `OrgID` as names for the other array arguments. I figured it might be a convention. If we change this one I think we should change those as well, but I'm not sure I have a strong opinion about it at this point. Might be cleaner to add in a separate PR as tech-debt. Feel free to add an issue if you would like!

2022-03-24 18:53 UTC, CristinaBirkel commented on enterprise/internal/insights/resolvers/insight_view_resolvers.go
> +		if args.Input.Dashboards != nil {
Yes actually, I didn't have this check in at first and quickly found it was a bug! 🐛 The reason being that `dashboardIds` could have one item in it (the LAM dashboard) even though the mutation arguments had no dashboards. If that's the case, there's nothing to validate on the next line, as that validation step only applies to any dashboards passed in by the user. Does that make sense?

2022-03-24 23:50 UTC, coury-clark approved these changes

2022-03-25 00:37 UTC, merged

2022-03-25 10:09 UTC, leonore commented on enterprise/internal/insights/resolvers/dashboard_resolvers.go
> +	dashboards, err := tx.GetDashboards(ctx, store.DashboardQueryArgs{ID: []int{int(dashboardID.Arg)},
it seems we're the only ones in the org [doing it this way](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+ID%5Cs%2B%5C%5B%5C%5D&patternType=regexp), so I've added a ticket for this: [#33705](https://github.com/sourcegraph/sourcegraph/issues/33075)