gitserver: add localclone worker
sourcegraph/sourcegraph pull request #33072
Opened 2022-03-25 09:15 UTC by asdine

This adds a new background job to the worker service. This job reads rows from the `gitserver_localclone_jobs` table and clones repos from one gitserver instance to another.
Optionally, it deletes the source repository after successful copy.
This job will be used to migrate repos asynchronously between gitserver instances without contacting the code host.

### Highlights

- The worker is implemented using the [workerutil](https://docs.sourcegraph.com/dev/background-information/workers) package. This PR contains mostly code that complies with the expected interfaces and database structure.
- I added a new package in `cmd/gitserver/background` which will contain all the background jobs we want to run in the worker service. This is to mimic most of the existing job implementations.

## Test plan

- Unit test
- Run sg with double gitservers and insert rows in the `gitserver_localclone_jobs` table. Tested with and without deletion.

Fixes #32827

2022-03-25 14:04 UTC, efritz requested changes

2022-03-25 14:04 UTC, efritz commented on cmd/worker/shared/main.go
> +	gitserverbg "github.com/sourcegraph/sourcegraph/cmd/gitserver/background"
`cmd/worker` should not cross-import `cmd/gitserver`. Would it be possible to move the gitserver background package into `internal/gitserver/background` or into `cmd/worker/internal/gitserver`?

Luckily it looks like there's no imports of any cmd/gitserver things from inside the new background routines.

2022-03-28 07:45 UTC, ryanslade approved these changes
LGTM, apart from what Eric said

2022-03-28 07:45 UTC, ryanslade commented on cmd/gitserver/background/local_clone.go
> +// TODO(asdine): Load environment variables from here.
Is it safe to deploy with this TODO?

2022-03-28 08:38 UTC, vrto commented on cmd/worker/shared/main.go
> +	gitserverbg "github.com/sourcegraph/sourcegraph/cmd/gitserver/background"
Just making a note here, we ought to drive intentional dependencies (and prevent the unintended ones) using automated checks.

2022-03-28 09:32 UTC, vrto reviewed
Awesome to see this becoming a thing, can't wait to see it in action! Left a few small questions to ponder.

2022-03-28 09:32 UTC, vrto commented on cmd/gitserver/background/local_clone.go
> +	db := database.NewDB(wdb)
Since we only need to use a single store (`GitServerLocalClone`) from this component, wouldn't it be better to inject it directly into this method rather than creating it inside?

2022-03-28 09:32 UTC, vrto commented on cmd/gitserver/background/local_clone.go
> +	job, ok := record.(*types.GitserverLocalCloneJob)
This collides with the imported `job` package, should we give it a different name?

2022-03-28 09:32 UTC, vrto commented on cmd/gitserver/background/local_clone.go
> +func (h *localCloneHandler) Handle(ctx context.Context, record workerutil.Record) (err error) {
Do we have to accept `workerutil.Record` in the first place, since we require it to actually be `GitServerLocalCloneJob`?

2022-03-30 06:56 UTC, asdine commented on cmd/worker/shared/main.go
> +	gitserverbg "github.com/sourcegraph/sourcegraph/cmd/gitserver/background"
> cmd/worker should not cross-import cmd/gitserver. Would it be possible to move the gitserver background package into internal/gitserver/background or into cmd/worker/internal/gitserver?
> Luckily it looks like there's no imports of any cmd/gitserver things from inside the new background routines.

Thanks for pointing that out, I think it makes more sense to move it to cmd/worker/internal/gitserver

2022-03-30 06:57 UTC, asdine commented on cmd/gitserver/background/local_clone.go
> +// TODO(asdine): Load environment variables from here.
Yes, right now everything is hard coded but the values should be fine. Also, the worker is not used for now

2022-03-30 06:59 UTC, asdine commented on cmd/gitserver/background/local_clone.go
> +	db := database.NewDB(wdb)
We can do this too yes, I just reproduced a pattern that was found in other worker implementations but since we don't have the same constraints we don't need to do the same thing

2022-03-30 07:00 UTC, asdine commented on cmd/gitserver/background/local_clone.go
> +func (h *localCloneHandler) Handle(ctx context.Context, record workerutil.Record) (err error) {
Yes, because this type implements an interface that the workerutil needs.
I will add a comment to make it more clear

2022-03-30 07:02 UTC, asdine commented on cmd/gitserver/background/local_clone.go
> +	job, ok := record.(*types.GitserverLocalCloneJob)
Shadowing in go is fine most of the time, until of course you need to use the upper scope identifier in the function

2022-03-30 07:27 UTC, asdine commented
I don't really like the name "GitserverLocalClone" so I was thinking we could rename this to `GItserverReplicator` instead, as this seems to be the standard name for this kind of process.
@ryanslade @vrto If there is no objection I will rename this type in this PR, and rename the table in another one

2022-03-30 07:32 UTC, vrto approved these changes

2022-03-30 15:49 UTC, efritz approved these changes

2024-01-10 20:38 UTC, eseliger commented
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

2024-01-10 20:38 UTC, closed without merging