Change user pending permissions ID to int64
sourcegraph/sourcegraph pull request #33158
Opened 2022-03-28 18:50 UTC by varsanojidan

Closes [#31810](https://github.com/sourcegraph/sourcegraph/issues/31810)

Move user_pending_permission table's ID's to int64 to avoid reaching the max allowed value of int32 due to the sequencing applied to the ID value is postgress

## Test plan
Validated against existing test cases and locally, will also inspect dogfood after deployment

2022-03-29 07:48 UTC, ryanslade commented on enterprise/internal/database/perms_store.go
> +	p.PendingUserIDs = map[int64]bool{}
Instead of a bool value you can use an empty `struct{}`, it's a trick that means you don't need to allocate any memory for the values in the map. You can still check for existence in the map using `_, ok := m[key]`

2022-03-29 07:48 UTC, ryanslade commented on enterprise/internal/database/perms_store.go
> +
nit: Empty space

2022-03-29 07:52 UTC, ryanslade commented on migrations/frontend/1648524019/down.sql
> +ALTER SEQUENCE IF EXISTS user_external_accounts_id_seq RESTART;
I think this should be `user_pending_permissions_id_seq`

2022-03-29 07:53 UTC, ryanslade commented on migrations/frontend/1648524019/up.sql
> +ALTER SEQUENCE IF EXISTS user_external_accounts_id_seq RESTART;
I think this should be `user_pending_permissions_id_seq`

2022-03-29 07:59 UTC, ryanslade commented on enterprise/internal/database/perms_store.go
> +	p.IDs = roaring.NewBitmap()
I'm going to create a debt issue to remove usages or roaring.Bitmap from our permissions code. It just complicates the code with no gain at this point since we always just end up turning them into slices of ints eventually.

2022-03-29 08:09 UTC, ryanslade requested changes
Nice, looks mostly good apart from the migration.

2022-03-29 08:09 UTC, ryanslade commented on enterprise/internal/database/perms_store.go
> +	p.IDs = roaring.NewBitmap()
https://github.com/sourcegraph/sourcegraph/issues/33172

2022-03-29 09:13 UTC, unknwon approved these changes
+1 to Ryan's comments.

2022-03-29 09:13 UTC, unknwon commented on enterprise/internal/database/perms_store.go
> +
nit
```suggestion
```

2022-03-29 14:46 UTC, varsanojidan commented on migrations/frontend/1648524019/down.sql
> +ALTER SEQUENCE IF EXISTS user_external_accounts_id_seq RESTART;
whoooooooooooooops how did that happen lol

2022-03-30 08:18 UTC, ryanslade approved these changes

2022-03-30 14:34 UTC, merged