gitserver: update janitor so it sets repo sizes
sourcegraph/sourcegraph pull request #33263
Opened 2022-03-31 09:00 UTC by sashaostrikov

Gitserver janitor during its first run will now query the DB for repos in gitserver_repos table which have repo_size_bytes = NULL and update them with calculated values. Janitor always calculates a size of a repo (i.e. directory in file system) and now these data are used to fill the gaps in gitserver repo sizes.

Closes https://github.com/sourcegraph/sourcegraph/issues/33000

## Test plan
Unit tests are added

2022-03-31 10:32 UTC, ryanslade requested changes
The main change I think we need is to batch the writes to the database in some way

2022-03-31 10:32 UTC, ryanslade commented on cmd/gitserver/server/cleanup.go
> +	// There is no need for a second run because all repo sizes will be set until this moment
Worth adding a note that they are update after each update. (I think?)

2022-03-31 10:32 UTC, ryanslade commented on internal/database/gitserver_repos.go
> +		if err := rows.Scan(&dbutil.NullString{S: &name}, &dbutil.NullInt32{N: &ID}); err != nil {
I don't think the name or id can ever be null so you don't need to use NullString or NullInt32

2022-03-31 10:32 UTC, ryanslade commented on internal/database/gitserver_repos.go
> +// INSERT clause has shard_id column which is hardcoded to "0" because of not null constraint.
From the code it looks like we're passing in the shard id string so I don't understand this comment

2022-03-31 10:32 UTC, ryanslade commented on internal/database/gitserver_repos.go
> +		values = append(values, sqlf.Sprintf("(%s, %s, %s, now())", repo, shardID, size))
The map could be very large to the point where the number of values in the statement are too large to pass to posgres. 

We can either do the trick where we pass data in as an array or we can insert in batches.

Doing it in batches is simpler but would require more round trips to the database but in this case it's not too much of an issue since this is running in a background job.

2022-03-31 12:42 UTC, sashaostrikov commented on cmd/gitserver/server/cleanup.go
> +	// There is no need for a second run because all repo sizes will be set until this moment
Sorry, I cannot quite get it. After each sg update/gitserver restart you mean? There will still be just one update, because only repos without size are updated. All freshly cloned repos always have a size. Ones without a size are just repos which were cloned before https://github.com/sourcegraph/sourcegraph/issues/32197 was merged

2022-03-31 12:42 UTC, sashaostrikov commented on internal/database/gitserver_repos.go
> +		if err := rows.Scan(&dbutil.NullString{S: &name}, &dbutil.NullInt32{N: &ID}); err != nil {
that's true, fixed it

2022-03-31 12:43 UTC, sashaostrikov commented on internal/database/gitserver_repos.go
> +// INSERT clause has shard_id column which is hardcoded to "0" because of not null constraint.
that's a stale comment, right

2022-03-31 12:55 UTC, sashaostrikov commented on internal/database/gitserver_repos.go
> +		values = append(values, sqlf.Sprintf("(%s, %s, %s, now())", repo, shardID, size))
yeah, I agree about batching, I think [batch inserter](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/batch/batch.go) is an easy way out

2022-03-31 13:09 UTC, ryanslade commented on internal/database/gitserver_repos.go
> +		values = append(values, sqlf.Sprintf("(%s, %s, %s, now())", repo, shardID, size))
TIL

2022-03-31 16:02 UTC, ryanslade commented on cmd/gitserver/server/cleanup.go
> +	// There is no need for a second run because all repo sizes will be set until this moment
What I mean is that we also update the size whenever a repo is pulled right?

2022-03-31 16:04 UTC, ryanslade approved these changes

2022-04-01 12:55 UTC, sashaostrikov commented on cmd/gitserver/server/cleanup.go
> +	// There is no need for a second run because all repo sizes will be set until this moment
The size is set during initial repo clone (https://github.com/sourcegraph/sourcegraph/issues/32197).
When the size is set -- it is not updated anymore.

But now I begin to think that the repo can grow and the size will not be right. We need to think about a way to update sizes when they are already present in the database.

I guess we missed this thing here, because the next step was to remove calculation of directory size from janitor and use sizes from database...

cc @asdine when you are back -- we need to think about this one more time

2022-04-01 13:48 UTC, ryanslade commented on cmd/gitserver/server/cleanup.go
> +	// There is no need for a second run because all repo sizes will be set until this moment
I would think the easiest thing to do is update the size after each fetch unless it's very expensive to check the size each time?

2022-04-01 14:39 UTC, sashaostrikov commented on cmd/gitserver/server/cleanup.go
> +	// There is no need for a second run because all repo sizes will be set until this moment
there is a curious thing here.

I forgot that in fact this is implemented [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1ed408a6c609e0a27ee58f4cf625303331e9ee87/-/blob/cmd/gitserver/server/server.go?L2205:14), but it doesn't seem to work (at least on cloud), because there are still a lot of repos without size

This is something to be investigated, we had a look with Asdine, but didn't find a reason of such behaviour

2022-04-04 12:10 UTC, merged