Update helm.md
sourcegraph/sourcegraph pull request #33307
Opened 2022-04-01 10:21 UTC by dan-mckean

Add some more intro guidance.

Add some extra handholding to the GKE guidance.

## Test plan

Docs changes

2022-04-01 10:38 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +## High level overview of how to use Helm with Sourcegraph
Is the advice in this new section legit?

Is prepping customizations before starting a good idea?

2022-04-01 10:38 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +TODO
TODO

2022-04-01 18:52 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +   - [Google GKE](#configure-sourcegraph-on-elastic-kubernetes-service-eks)
```suggestion
   - [AWS EKS](#configure-sourcegraph-on-elastic-kubernetes-service-eks)
```
Same as above - we're missing Google's section

2022-04-01 18:52 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +> ℹ️ This quickstart guide is useful to those already familiar with Helm who have a good unstanding of how to use Helm in the environment they want to deploy into, and just who want to quickly deploy
```suggestion
> ℹ️ This quickstart guide is useful to those already familiar with Helm who have a good understanding of how to use Helm in the environment they want to deploy into, and just who want to quickly deploy Sourcegraph with Helm with default configuration. If this doesn't cover what you need to know, see the links above for platform specific guides.
```

(Although I liked your suggestion about getting rid of this section and just directing everyone to provider-specific instructions)

2022-04-01 18:52 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +(There are no pre-requisites to creating this file ahead of deployment!)
This is confusing - I think you're trying to convey that this file can be prepared in advance of the deployment?

2022-04-01 18:52 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +Add into your overide file the below values to configure both your ingress hostname and your storage class. We recommend configuring Ingress to use [Application Gateway](https://azure.microsoft.com/e
```suggestion
Add into your override file the below values to configure both your ingress hostname and your storage class. We recommend configuring Ingress to use [Application Gateway](https://azure.microsoft.com/en-us/services/application-gateway) to expose Sourcegraph publicly on a domain of your choosing and Storage Class to use [Azure Disk CSI driver](https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi).
```

2022-04-04 16:40 UTC, michaellzc requested changes

2022-04-04 16:40 UTC, michaellzc commented on doc/admin/install/kubernetes/helm.md
> +> Alternatively, you can use your own choice of Ingress Controller and disable the `HTTP Load Balancing` add-on, [learn more](https://cloud.google.com/kubernetes-engine/docs/how-to/custom-ingress-con
```suggestion
1. You need to have a GKE cluster (>=1.19) with the `HTTP Load Balancing` addon enabled. Alternatively, you can use your own choice of Ingress Controller and disable the `HTTP Load Balancing` add-on, [learn more](https://cloud.google.com/kubernetes-engine/docs/how-to/custom-ingress-controller).
```

the formating was messed up

2022-04-04 16:40 UTC, michaellzc commented on doc/admin/install/kubernetes/helm.md
> +Add into your overide file the below values to configure both your ingress hostname and your storage class. We recommend configuring Ingress to use [Container-native load balancing] to expose Sourceg
the intention of putting the link `[override.yaml]` directly above the snippet is provide us the ability to do something similar to

https://github.com/dagger/dagger/blob/main/docs/core-concepts/1204-secrets.md?plain=1
https://docs.dagger.io/1204/secrets#sops

in the future

where we can reference a remote file from the snippet from markdown, and it will render nicely

with the current approach, we will always risk values getting out-of-sync

maybe put it back?

2022-04-04 16:40 UTC, michaellzc commented on doc/admin/install/kubernetes/helm.md
> +TODO
this step would be almost identical with https://github.com/sourcegraph/sourcegraph/blob/5f418ebc09629e51b608a9a37a0311454d1ed0f4/doc/admin/install/kubernetes/helm.md?plain=1#L558-L592

maybe we can extract this out to a standalone guide in the `#confugration` section, like `Using custom TLS secrets in Ingress`

2022-04-04 16:40 UTC, michaellzc commented on doc/admin/install/kubernetes/helm.md
> +4. Have the Helm CLI installed and run the following command to link to the Sourcegraph helm repository
```suggestion
1. Your account should have sufficient access equivalent to the `cluster-admin` ClusterRole.
1. Connect to your cluster (via either the console or the command line using `gcloud`) and ensure the cluster is up and running by running: `kubectl get nodes` (several `ready` nodes should be listed)
1. Have the Helm CLI installed and run the following command to link to the Sourcegraph helm repository
```

another nit pick, can we change all sequence to `1`? Markdown will transform them to proper sequence number.

it's just easier because we don't have to count when adding more items to the list

2022-04-04 16:40 UTC, michaellzc commented on doc/admin/install/kubernetes/helm.md
> +4. Have the Helm CLI installed and run the following command to link to the Sourcegraph helm repository
```suggestion
1. Your account should have sufficient access equivalent to the `cluster-admin` ClusterRole.
1. Connect to your cluster (via either the console or the command line using `eksctl`) and ensure the cluster is up and running by running: `kubectl get nodes` (several `ready` nodes should be listed)
1. Have the Helm CLI installed and run the following command to link to the Sourcegraph helm repository
```

2022-04-04 16:40 UTC, michaellzc commented on doc/admin/install/kubernetes/helm.md
>  > You may consider using your custom Ingress Controller instead of Application Gateway, [learn more](https://docs.microsoft.com/en-us/azure/aks/ingress-basic)
the formatting is messed up now. Should we put this above or below?

```suggestion
> You may consider using your custom Ingress Controller instead of Application Gateway, [learn more](https://docs.microsoft.com/en-us/azure/aks/ingress-basic)

1. You need to have a AKS cluster (>=1.19) with the following addons enabled:
   - [Azure Application Gateway Ingress Controller](https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-new)
   - [Azure Disk CSI driver](https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers)
```

2022-04-05 09:25 UTC, dan-mckean reviewed
Fix deployment links

2022-04-05 09:25 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +<a class="btn" href="#configuration">Configuration</a>
```suggestion
<a class="btn" href="#configuration">Configuration</a>
- <a class="btn" href="#configure-sourcegraph-on-google-kubernetes-engine-gke">Google GKE</a>
```

2022-04-05 09:25 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +1. Select your deployment method and follow the guidance:
```suggestion
1. Select your deployment method and follow the guidance:
   - [Google GKE](#configure-sourcegraph-on-google-kubernetes-engine-gke)
```

2022-04-05 09:26 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +(There are no pre-requisites to creating this file ahead of deployment!)
```suggestion
(The configuration override file can be created in advance of deployment!)
```

2022-04-05 09:28 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
>  ```yaml
```suggestion
[override.yaml](https://github.com/sourcegraph/deploy-sourcegraph-helm/tree/main/charts/sourcegraph/examples/gcp/override.yaml)
```yaml
```

2022-04-05 09:29 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +TODO
For now - can you just replicate it with any necessary changes please @michaellzc

2022-04-05 09:31 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
>  > You may consider using your custom Ingress Controller instead of Application Gateway, [learn more](https://docs.microsoft.com/en-us/azure/aks/ingress-basic)
I think below. Putting it above it lacks context. And it's still within that step.

2022-04-05 09:38 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +   - Sourcegraph can be deployed using Helm with no customizations to the default [values.yaml](https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/main/charts/sourcegraph/values.yaml) but th
```suggestion
```

2022-04-05 09:38 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +   - It's worth reviewing these and preparing them ahead of anything else, using the guidance in [Configuration](#configuration).
```suggestion
   - Most environment are likely to need changes from the defaults - use the guidance in [Configuration](#configuration).
```

2022-04-05 17:26 UTC, michaellzc approved these changes

2022-04-05 17:27 UTC, merged