[SG-33093.1] Enable accessibilityAudit on `client/web/src/integration/batches.test.ts`
sourcegraph/sourcegraph pull request #33332
Opened 2022-04-02 16:10 UTC by gitstart-sourcegraph

## Description

- Enabling accessibility audit on `batches` page in its integration test

## Refs

[SG Issue](https://github.com/sourcegraph/sourcegraph/issues/33093)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-33093)

## Test plan

Run the integration test `yarn test-integration:base client/web/src/integration/batches.test.ts`

## Success criteria

- All integration tests with percy snapshots have `accessibilityAudit` enabled

2022-04-03 16:37 UTC, gitstart-sourcegraph commented
@umpox @valerybugakov  could you review the first PR for `accessibilityAudit`? Would need your suggestions on some `a11y-ignore` usages (already left comments for issues)? 

BTW it seems that we know another issue of current `wildcard/Menu` with Reach Menu + Popover, it's about Popover removes `MenuList` from DOM, it causes `aria-controls` attribute in `MenuButton` invalid

2022-04-04 08:59 UTC, umpox commented
@gitstart-sourcegraph The `aria-controls` issue is interesting. We could work around this by using `isExpanded` from `Menu` to only add `aria-controls` when visible. I think this is OK though, it seems from reading this issue: https://github.com/w3c/aria/issues/995 that `aria-controls` has relatively low support. We should be able to make these components accessible without it

2022-04-04 09:24 UTC, umpox requested changes
Thanks! Left some some comments

2022-04-04 09:24 UTC, umpox commented on client/web/src/components/AppRouterContainer/AppRouterContainer.tsx
> +        <div role="main" data-layout={true} className={classNames(styles.appRouterContainer, className)} {...rest}>
```suggestion
        <main data-layout={true} className={classNames(styles.appRouterContainer, className)} {...rest}>
```

I think this should be equivalent

2022-04-04 09:24 UTC, umpox commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
> +                            we can use `--gray-02` or find another color for `--link-color`
```suggestion
                            There are a lot of `Link` usages in `--color-bg-2=--gray-03` container, to fix this issue
                            we can use `--gray-02` or find another color for `--link-color`
```

@gitstart-sourcegraph Lets just link to a GitHub issue for these contrast issues. I think we will encounter quite a few of them. We might not want to address all of these as the WCAG color contrast algorithm is changing to be more accurate in the next version of the specification (WCAG 3). Let's leave a comment with a link to this issue wherever we have this problem (and it doesn't appear to be a genuine bug) .

```suggestion
                            GitHub issue: https://github.com/sourcegraph/sourcegraph/issues/33343
```

2022-04-04 09:24 UTC, umpox commented on client/web/src/nav/StatusMessagesNavItem.tsx
> +                    aria-label={this.state.isOpen ? 'Hide tasks status message' : 'Show tasks status message'}
```suggestion
                    aria-label={this.state.isOpen ? 'Hide status messages' : 'Show status messages'}
```

2022-04-04 15:37 UTC, umpox commented on client/wildcard/src/components/Menu/MenuButton.tsx
> +    // since `menu-*` doesn't exit on DOM
```suggestion
    // We unset aria-controls as it causes accessibility issues if the Menu is not yet rendered in the DOM.
    // aria-controls has low support across screen readers so this shouldn't be an issue: https://github.com/w3c/aria/issues/995
```

2022-04-05 07:56 UTC, gitstart-sourcegraph commented
@umpox could you help to check percy snapshots reports? It seems that all snapshots from this PR is new

2022-04-05 08:30 UTC, umpox approved these changes
Two small comments, rest looks good! I think the Percy changes aren't related to this PR, but because we're currently having some issues with Percy builds on main. Will look into it and have re-ran the build to check if that fixes

2022-04-05 08:30 UTC, umpox commented on client/web/src/components/AppRouterContainer/AppRouterContainer.tsx
> +            - `role="main"` to fix rule: "landmark-one-main" (Document should have one main landmark)
```suggestion
```

We can remove this now

2022-04-05 08:30 UTC, umpox commented on client/wildcard/src/components/PageHeader/PageHeader.tsx
> +        <header className={classNames(styles.container, className, 'a11y-ignore')}>
```suggestion
        <div className={classNames(styles.container, className)}>
```

Let's just keep this as a `div`. Header may be the wrong element here as we can't control where this component is used

2022-04-05 15:42 UTC, gitstart-sourcegraph commented
Thanks @valerybugakov  @umpox  all checks are good except percy check. Should we merge this PR or wait for the fixes?

2022-04-05 16:56 UTC, merged