repo-updater: move vcs/git/tree/ReadTree to gitserver/commands/ReadTree
sourcegraph/sourcegraph pull request #33610
Opened 2022-04-07 14:57 UTC by sashaostrikov

@ryanslade I think that `commands.go` will get very big, can we probably have the same file structure as it was in `git` package?

## Test plan
Check that tests are green

2022-04-08 08:09 UTC, ryanslade requested changes
Looks good, but we want them as methods on the client

2022-04-08 08:09 UTC, ryanslade commented on cmd/frontend/backend/inventory.go
> +			return gitserver.ReadDir(ctx, db, authz.DefaultSubRepoPermsChecker, repo, commitID, path, false)
We want this to be a method on the gitserver client so that it cal be called like:

```go
gitserver.NewClient(db).ReadDir(...)
```

2022-04-08 08:13 UTC, ryanslade commented
> @ryanslade I think that commands.go will get very big, can we probably have the same file structure as it was in git package?

@mollylogue said the same thing. Maybe it's just me who actually prefers not to spread things across lots of files 😄 

Do you find it makes it easier to find the code you're looking for or just easier to work with when the files are smaller?

2022-04-08 08:50 UTC, sashaostrikov commented on cmd/frontend/backend/inventory.go
> +			return gitserver.ReadDir(ctx, db, authz.DefaultSubRepoPermsChecker, repo, commitID, path, false)
Oh, yes, thanks. Will fix it!

2022-04-08 15:49 UTC, sashaostrikov commented
> Do you find it makes it easier to find the code you're looking for or just easier to work with when the files are smaller?

Well, I think what is in my head is trying to follow SOLID to some extent. Large files by definition can accidentally violate Single Responsibility because if there is much code, then adding some other code which is not closely related can be overlooked easier.

I understand that we are just describing commands in this single file, but this file will get approx >1.5k lines in the end (my wild guess). IMO working with smaller files is easier as well as navigating in them.

Another reason why I asked, is that we had several files divided by functionality in `git` package and `gitserver` package seems to have just a single file `commands.go` :)

2022-04-08 15:49 UTC, sashaostrikov commented
@ryanslade PTAL it's ready for review :)

2022-04-11 06:34 UTC, ryanslade approved these changes

2022-04-11 06:34 UTC, ryanslade commented on internal/gitserver/commands.go
> +	"github.com/sourcegraph/sourcegraph/internal/vcs/util"
Looks like the import grouping got a little messed up here

2022-04-11 13:00 UTC, merged