batches: change filename in diffnode from link to plain text
sourcegraph/sourcegraph pull request #33625
Opened 2022-04-07 21:15 UTC by adeola-ak

Closes #33083

Changed filename link to plaintext as there is not a working path. The text is blue. Are we happy with it being this color or does it look like it may still be a link? I think it looks slightly better than white but understand the blue could be a little misleading

<img width="479" alt="Screen Shot 2022-04-07 at 5 08 13 PM" src="https://user-images.githubusercontent.com/67931373/162309489-6af933db-0fbf-4952-9168-22c027b42909.png">

white text:
<img width="493" alt="Screen Shot 2022-04-07 at 5 13 03 PM" src="https://user-images.githubusercontent.com/67931373/162312361-c966b9f3-ec2f-4a5f-a9dc-24a1bbf71396.png">

## Test plan
Verify there is no need for a link since there isn't always a logical place to link to

2022-04-07 23:05 UTC, BolajiOlajide approved these changes
Looks good to me.

2022-04-08 05:17 UTC, courier-new commented
(Adeola and I talked about this over slack, but Adeola's going to look through some of the other pages where this component is used, since it isn't only a Batch Changes component, and determine whether we want to remove the link everywhere or just in the case of Batch Change file diffs!)

2022-04-08 08:33 UTC, danielmarquespt commented
I think the text needs to be white, so its not confused with a link.

2022-04-08 10:43 UTC, eseliger requested changes
I think we only want this in batch changes, on the diff and commit pages I think this makes total sense to have and would be sad to lose :)

2022-04-11 14:20 UTC, adeola-ak commented
@BolajiOlajide @courier-new @eseliger hi everyone, actually after further review i believe we should leave this text as is (as a link). I think it only appears it does not direct anywhere because in @danielmarquespt's example he is only viewing one changed repo. However, the link behaves as normal as it appends a number of some sort to the URL and then focuses. In a list with more than one repo, you can see this behavior more clearly. What do we think?

2022-04-11 14:22 UTC, eseliger commented
Does it focus on that diff again after you reload the page? I think the problem we were seeing here is that that doesn't work. @danielmarquespt can you confirm that's what you found faulty here?

2022-04-11 15:01 UTC, adeola-ak commented
When i tried it, it was working it's just hard to see it working and focus with only 1 diff on the page. When I looked at other BC's that had more diffs, it worked

2022-04-11 17:37 UTC, danielmarquespt commented
Two things here:

1. As a User I expect that clicking on "readme.md" I would navigate to a page (modal whatever) that would display me the actual "readme.md" file. And that's not happening. 
2. Providing a way to link to somewhere within this page is useful, however the way to find that link should not be the filename itself as its confusing and non standard for the user. For example, imagine that on this thread, clicking on the username of any commenter would made the browser focus on the post you've just clicked. It would be strange.


If we want to keep the link to focus on a diff it should be something link this:

![Screenshot 2022-04-11 at 18 31 46](https://user-images.githubusercontent.com/7814431/162796793-cccc976e-9664-498e-9a4f-43f077c8414b.png)

Where we are linking somewhere else rather than the of the file.

-- 

As I was writing this, I noticed that here: https://k8s.sgdev.org/organizations/sourcegraph/batch-changes/update-to-stateless-queue?visible=4 on the diffs we have a "view" link to get to the file, and the filename just focusses on the page itself (the behaviour we are trying to remove)

![Screenshot 2022-04-11 at 18 33 29](https://user-images.githubusercontent.com/7814431/162797055-baec775a-09b3-4342-a423-703c5c98ade8.png)

This seems very counter intuitive to me, and I'm trying to understand if there is a strong reason for this to be this way? I think the standard should be the opposite, the filename links to the "View file at revision", and something else should focus on the actual page. I will check with the design team to see if there is a strong scenario to keep the page anchor on the filename.

I'll get back to you.

2022-04-12 03:27 UTC, adeola-ak commented
okay @danielmarquespt this all makes sense to me. Its a hard call because I do agree that the focusing isnt what I would expect when clicking the file name link, which is why i didnt even remember that it did that last week but I also know that if I just change it on our batch changes pages, it still will have that behavior in on the other areas where the diff is used like that. I'll await your response - thanks

2022-05-02 20:03 UTC, adeola-ak commented
<img width="485" alt="Screen Shot 2022-05-02 at 2 53 05 PM" src="https://user-images.githubusercontent.com/67931373/166307516-89797b0f-0d6a-4119-8964-7f87002c69a3.png">

Actually it looks like the last two occurrences in the picture are the only examples of where the component is being used outside of Batches

I think I will change to what you suggested (file link opens file name and # focuses)

2022-05-02 20:44 UTC, adeola-ak commented
New behavior - screenshot from storybook

if it is not a file it is plain text if its a file the file can be accessed by clicking the name and there is a # included which had the previous behavior of focusing

<img width="691" alt="Screen Shot 2022-05-02 at 4 42 53 PM" src="https://user-images.githubusercontent.com/67931373/166324395-7925f8f6-4d4d-4c9e-bde2-ee5305839a79.png">

2022-05-03 00:05 UTC, eseliger reviewed
@danielmarquespt can you please review the design proposed here with the new anchor thing and/or advise how to get this into a mergeable state, design-wise? Thanks!

2022-05-03 00:05 UTC, eseliger commented on client/web/src/components/diff/FileDiffNode.tsx
> +                        <Link to={{ ...location, hash: anchor }} className={classNames('ml-2', styles.headerPath)}>
I think this needs a tooltip and some aria tags if we stick to this as-is so it is accessible. Let's wait for Daniels input.

2022-05-03 00:05 UTC, eseliger commented on client/web/src/components/diff/FileDiffNode.tsx
>                              </Button>
Can't this just simply be a link now? Or why does it have to be a `<Button as={Link}>`?

2022-05-03 12:17 UTC, danielmarquespt commented
I'm ok with the proposed behaviour and design. The only change we need is the `͢` char. Feels too low, I would suggest `→` instead

2022-05-03 12:18 UTC, danielmarquespt commented on client/web/src/components/diff/FileDiffNode.tsx
> +                        <Link to={{ ...location, hash: anchor }} className={classNames('ml-2', styles.headerPath)}>
Good point, we need to ensure accessibility standards.

2022-05-03 12:32 UTC, adeola-ak commented on client/web/src/components/diff/FileDiffNode.tsx
>                              </Button>
I actually was going to convert it to a link but just eventually left it as is because of the styles that were applied with some of the button props that I lost when I changed it to just `<Link>`. I've seen this done like this in code alot so i thought it was fine. Should I change it?

2022-05-03 12:35 UTC, adeola-ak commented on client/web/src/components/diff/FileDiffNode.tsx
> +                        <Link to={{ ...location, hash: anchor }} className={classNames('ml-2', styles.headerPath)}>
@danielmarquespt tooltips needed here? and not sure what I would call it if so lol

2022-05-03 12:35 UTC, danielmarquespt commented on client/web/src/components/diff/FileDiffNode.tsx
> +                        <Link to={{ ...location, hash: anchor }} className={classNames('ml-2', styles.headerPath)}>
Yes. I think it is. Anchors in html are expressed with a # link, and our user base is technical enough to be familiar with that.

2022-05-03 12:39 UTC, adeola-ak commented on client/web/src/components/diff/FileDiffNode.tsx
>                              </Button>
changed it

2022-05-03 12:43 UTC, adeola-ak commented on client/web/src/components/diff/FileDiffNode.tsx
> +                        <Link to={{ ...location, hash: anchor }} className={classNames('ml-2', styles.headerPath)}>
what should i name the tooltip?

2022-05-03 12:55 UTC, eseliger commented on client/web/src/components/diff/FileDiffNode.tsx
>                              </Button>
Tried the Button as Link implementation, and it looks more like a button than like a link, while here in this instance I think we want to have a link. The button has weird padding around it (also not symmetrical), it pushes the tooltip away a little and the focus state isn't very clear:

<img width="365" alt="CleanShot 2022-05-03 at 14 53 03@2x" src="https://user-images.githubusercontent.com/19534377/166456420-08a2e6e4-4370-4aa5-9c4d-b7db5fc2d6b8.png">

cc @courier-new maybe I am telling bad advice here though and that's desired? Maybe you know more :)

2022-05-05 20:04 UTC, adeola-ak commented
@eseliger is this good to go?

2022-05-05 21:25 UTC, eseliger approved these changes
LGTM! @danielmarquespt all good here?

2022-05-05 21:25 UTC, eseliger commented on client/web/src/components/diff/FileDiffNode.tsx
> +                            aria-label="View diff"
```suggestion
                            data-tooltip="Pin diff"
                            aria-label="Pin diff"
```

or something similar? The user already looks at the diff :)

2022-05-05 21:25 UTC, eseliger commented on client/web/src/components/diff/FileDiffNode.tsx
> +                                className="pr-0 pl-2 fw-bold"
Would margin instead of padding work here too? Otherwise, the focus state is not centered.
<img width="502" alt="Screenshot 2022-05-05 at 23 24 14@2x" src="https://user-images.githubusercontent.com/19534377/167028074-cc8aa89f-189d-4e23-8f6f-752302970df4.png">

(And it's kinda cut off, but that seems to be a general problem on this page with multiple links, so let's not fix it in here)

2022-05-06 01:23 UTC, merged