Remove file names from Helm guide
sourcegraph/sourcegraph pull request #33699
Opened 2022-04-11 06:59 UTC by dan-mckean

Comment out confusing file names and add in links to examples.

## Test plan
dd

2022-04-11 14:41 UTC, caugustus-sourcegraph requested changes
Can you merge the latest main and resolve the conflicts? I think most of these edits aren't relevant after the changes from https://github.com/sourcegraph/sourcegraph/pull/33671.

2022-04-11 19:32 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +
```suggestion
```

2022-04-11 19:32 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +
```suggestion
```

2022-04-11 19:32 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
>  apiVersion: v1
This is a little tricky - the Secret doesn't actually belong in the override file. Instead it's a separately deployed resource, outside of the helm chart.

In the external database section we say a little blurb about how we recommend using secrets / needs to be deployed to the same namespace. Maybe we can reuse that here?

2022-04-11 19:32 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +<!--`gitserver-ssh.Secret.yaml`-->
Hm - if we remove the filename reference from this snippet the next command doesn't make sense (`kubectl apply -f gitserver-ssh.Secret.yaml`). Maybe this needs a  "Save this file as x" sentence?

2022-04-11 19:32 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +<!--`sourcegraph-frontend-tls.Secret.yaml`-->
Same as the gitserver-ssh - that filename reference needs to be visible, so that the next command makes sense.

2022-04-11 19:32 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
> +<!--`sourcegraph-frontend-tls.Secret.yaml`-->
Same as above - filename is referenced later

2022-04-12 07:40 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +<!--`gitserver-ssh.Secret.yaml`-->
```suggestion
Create the a file with the following and save it as `gitserver-ssh.Secret.yaml`
```

2022-04-12 07:42 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +<!--`sourcegraph-frontend-tls.Secret.yaml`-->
```suggestion
Create the a file with the following and save it as `sourcegraph-frontend-tls.Secret.yaml`
```

2022-04-12 07:42 UTC, dan-mckean commented on doc/admin/install/kubernetes/helm.md
> +<!--`sourcegraph-frontend-tls.Secret.yaml`-->
```suggestion
Create the a file with the following and save it as `sourcegraph-frontend-tls.Secret.yaml`
```

2022-04-18 12:20 UTC, caugustus-sourcegraph approved these changes

2022-04-18 12:20 UTC, caugustus-sourcegraph commented on doc/admin/install/kubernetes/helm.md
>  apiVersion: v1
Took a stab at it - how does that look to you @dan-mckean?

2022-04-18 12:28 UTC, merged