ci: run client linters on changed files
sourcegraph/sourcegraph pull request #33701
Opened 2022-04-11 08:01 UTC by valerybugakov

## Context

[Related Slack thread](https://sourcegraph.slack.com/archives/C01N83PS4TU/p1649449651416709).

## Test plan

Verify that ESLint and Stylelint CI checks are executed only on files changed in the PR.

2022-04-11 08:19 UTC, vovakulikov commented on package.json
> +    "lint:js": "DOCSITE_LIST=\"$(./dev/docsite.sh -config doc/docsite.json ls)\" NODE_OPTIONS=\"--max_old_space_size=16192\" eslint",
Since this is an internal command and it makes sense only for other package.json scripts I think it would be better if we name it something like `_lint:js` (of course it would be better if we could leave a comment about this but JSON doesn't support comments 😢 )

2022-04-13 10:09 UTC, jhchabran reviewed
Just reviewing the Go code on my end, that's 👍 for me, with a minor comment on readability :)

2022-04-13 10:09 UTC, jhchabran commented on enterprise/dev/ci/internal/ci/operations.go
> +func addClientLinters(lintOnlyChangedFiles bool) operations.Operation {
Could we split this function into two variants? The one that deals with only changes and the one that runs everything? It would make the pipeline definitions easier to read. And we could also have the label reflect which flavor is being run too!

2022-04-13 10:35 UTC, jhchabran requested changes

2022-04-13 10:35 UTC, jhchabran commented on doc/dev/background-information/ci/reference.md
> +- **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6,
This seems to be incorrect, on a release branch, we would want to run everything actually! (Talking about ESLint changed)

2022-04-13 10:35 UTC, jhchabran commented on doc/dev/background-information/ci/reference.md
> +- **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6,
This seems to be incorrect, on a tagged release, we would want to run everything actually! (Talking about ESLint changed)

2022-04-13 10:35 UTC, jhchabran commented on doc/dev/background-information/ci/reference.md
> +  - **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6
Isn't that the case where we actually want to only check for changes?

2022-04-13 10:35 UTC, jhchabran commented on doc/dev/background-information/ci/reference.md
> +  - **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6
Same

2022-04-13 10:37 UTC, valerybugakov commented on doc/dev/background-information/ci/reference.md
> +- **Client checks**: Puppeteer tests prep, Puppeteer tests chunk #1, Puppeteer tests chunk #2, Puppeteer tests chunk #3, Puppeteer tests chunk #4, Puppeteer tests chunk #5, Puppeteer tests chunk #6,
@jhchabran, I forgot to regenerate the reference after the last change; thanks!

2022-04-13 10:41 UTC, jhchabran approved these changes
Small nitpick on the field naming, but good otherwise!

2022-04-13 10:41 UTC, jhchabran commented on enterprise/dev/ci/internal/ci/pipeline.go
> +			LintOnlyChangedFiles:      c.RunType.Is(runtype.PullRequest),
```suggestion
			ClientLintOnlyChangedFiles:      c.RunType.Is(runtype.PullRequest),
```

I think that would be clearer this way, to avoid creating the assumption that we're applying this logic on everything!

2022-04-13 10:42 UTC, valerybugakov commented
@jhchabran, thanks for a quick review! 💜

2022-04-13 12:45 UTC, vovakulikov approved these changes

2022-04-14 07:37 UTC, merged