feat: create step-1 for 4-step create form layout
sourcegraph/sourcegraph pull request #33816
Opened 2022-04-12 21:50 UTC by BolajiOlajide

## Screenshot

<img width="1511" alt="Screenshot 2022-04-12 at 22 49 48" src="https://user-images.githubusercontent.com/25608335/163060218-09dd82cd-f005-474f-9a26-44e740aeb803.png">

## Test plan

* Navigate to the `/batch-changes/create` - the new tab navigation for the configuration step should be displayed.
* Navigating to `/users/<namespace_user_id>/batch-changes/<batch_change_name>/configuration` which is an alias for the read-only configuration for batch changes should display a similar page with disabled input fields.

Closes #32337

2022-04-13 15:12 UTC, eseliger reviewed
I think this question is mostly for @courier-new, but we should clarify it before we merge this:

Currently, this adds a new place where the tab bar is added. We already have one in the `BatchSpecExecutionDetailsPage`, it's still missing in the `EditPage` and now is added to this page as well. To make it work across all three of those, I think the end-state would be to consolidate them all into a single page, that adds the header and additional header elements, based on state, and adds the tab bar as well. Currently, it also looks different to the one that we use in the `BatchSpecExecutionDetailsPage`.

I think the ideal structure would be something like:
```
BatchSpecArea
- Header
- TabBar # lives at the top level of the Area component.
  - BatchChangeConfigurationPage
  - BatchSpecEditorPage
  - BatchSpecExecutionPage
  - BatchSpecPreviewPage
```

The question now: Do we want to merge this as-is (pending code review), or do we want this to be a step towards the above requirement to make it work on all the pages? I think you, Kelli, were to pick up this work afterwards so I'm interested in hearing what would work best for you :)

2022-04-13 17:11 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +            <Tabs>
Yes, I took a look at the one used in the `BatchSpecExecutionDetailsPage`, and why I opted to use this is because this one is currently from the `wildcard` design system.

Also, as the work for breaking the creation of batch changes go on, we'd be removing the tabs defined in the `BatchSpecExecutionDetailsPage`, since this will act as the main page for the four steps required to run a batch change.

2022-04-13 20:38 UTC, LawnGnome requested changes
I've just done a fairly low level review, as I defer to @eseliger and @courier-new on the nitty gritty of how this should really work, but I think we need to fix the width/margin issue in my review before we merge this. Otherwise, LGTM.

2022-04-13 20:38 UTC, LawnGnome commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +        <div className="w-100 m-4">
Applying the margin here appears to shift the entire content 1.5rem to the right, which means the contents of the div are off-centre, and the page gets a horizontal scrollbar.

(This is probably also the root cause of the border weirdness Erik found below.)

Could we just apply a top/bottom margin here, and then do our horizontal padding in a child?

2022-04-13 20:38 UTC, LawnGnome commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +        <Form className="container my-4 pb-5 w-50" onSubmit={handleCreate}>
This `w-50` probably shouldn't apply below a certain breakpoint (`sm` or `xs`?), as it compresses the form to a point where it's difficult to use:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/229984/163266151-ceebe202-edb4-44b2-800e-e629810709d1.png">

Not a blocker, as we generally haven't given a lot of love to our layouts on phones, but if we're already in the styles we might want to fix this at the same time.

2022-04-13 20:41 UTC, LawnGnome commented
One additional thought which isn't related to this PR per se, but is more fodder for @danielmarquespt and our everyday SSBCers: the namespace selector should probably include the actual user or organisation name as well as the friendly name. I can easily imagine a scenario where a customer has multiple overlapping organisations with similar or the same names (for example, a re-org that's in progress but not complete, or recently completed but the old organisations still have meaning), and having another way to disambiguate similar items would make sense to me.

2022-04-14 04:52 UTC, courier-new commented
Hey, sorry I haven't had a chance to look this over yet! I know there's a couple open questions I want to weigh in on, though, so I'll be reviewing first thing tomorrow. 🙂

2022-04-15 00:15 UTC, courier-new reviewed
I'm okay merging this with a couple changes, as it's still a step in the right direction and fairly minimal in terms of duplication for now. I agree we'll see a lot of merging/consolidation happen in my ticket, but I don't want to invest a ton of time in dreaming up an ideal "middle state" for this PR when the rest of the changes should follow basically as soon as I find the time to get to them, and the read-only version of the form gets us a good part of the way there anyway. 😄

2022-04-15 00:15 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +            <Tabs>
I think we should probably try to match the tabs style to the tabs on `BatchSpecExecutionDetailsPage`, because that style with the slightly bigger font size is the style we use across the other pages in Batch Changes, too.

2022-04-15 00:15 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                    </TabPanel>
Heheheh I was wondering how you would handle this for now.

2022-04-15 00:15 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                </div>
I'm not sure why it wasn't reflected in this particular design on Figma, but I think we do still want the radio buttons to match what's on the "Create" form:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/8942601/163495698-37a92fcd-b2a7-487e-bd71-1838bba5d3b6.png">

2022-04-18 16:13 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                    </TabPanel>
I went with this approach because ideally these tabs will be disabled so folks won't even get there. The only way to get there is through the read-only configuration URL and we aren't exposing that yet, we just created the alias temporarily.

I'm happy to switch to something else if this isn't appropriate.

2022-04-18 18:14 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                </div>
Oh! Okay I've reverted it to the radio buttons then.

2022-04-19 10:54 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                </div>
did you push that change yet? Just catching up on reviews here and I can't seem to find it 😬

2022-04-19 13:19 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                </div>
Not yet. I should have pushed before responding.

2022-04-19 18:14 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +        <div className="w-100 m-4">
Yes, that's what caused the issue Erik pointed out. Thanks.

2022-04-19 19:04 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +        <Form className="container my-4 pb-5 w-50" onSubmit={handleCreate}>
Fixed.

![Screenshot 2022-04-19 at 19 58 56](https://user-images.githubusercontent.com/25608335/164077132-d0790a3a-332a-4cd6-87f6-f2e79b7c3fd8.png)

2022-04-19 19:05 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +            {isReadOnly ? null : (
Fixed.

2022-04-19 19:05 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +            <Tabs>
Done

2022-04-19 19:07 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                </div>
Pushed the change now.

2022-04-19 19:11 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                    </TabPanel>
Haha! Alright.

2022-04-19 20:13 UTC, LawnGnome approved these changes
LGTM with those changes. Nice work!

2022-04-19 21:54 UTC, courier-new commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> -                        </small>
Sorry just noticed one other thing -- this wasn't part of the designs because it's an @eseliger original, but I'm pretty sure Rob was on board with keeping it. 🙂

2022-04-19 22:18 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> -                        </small>
Oh! I see. I'll add this then.

2022-04-19 22:50 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> -                        </small>
Done @courier-new

2022-04-20 11:36 UTC, eseliger approved these changes

2022-04-20 11:36 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                        2. Batch Specification
I'm sorry, this is also wrong in the designs - it's a word I can't get out of Robs vocabulary 😆 the correct term for the file is batch spec, as we name it in the docs :) 

```suggestion
                        2. Batch spec
```

2022-04-20 11:36 UTC, eseliger commented on client/web/src/enterprise/batches/create/CreateOrEditBatchChangePage.tsx
> +                        <div>Batch Specification</div>
```suggestion
                        <div>Batch spec</div>
```

2022-04-20 19:05 UTC, merged