Revert "remove caching at github client layer in favor of httpcli caching"
sourcegraph/sourcegraph pull request #34002
Opened 2022-04-18 11:38 UTC by indradhanush

Reverts sourcegraph/sourcegraph#33219

2022-04-18 14:24 UTC, mollylogue approved these changes

2022-04-18 19:51 UTC, bobheadxi requested changes
https://github.com/sourcegraph/sourcegraph/pull/33219#discussion_r852366634 - OOO until tomorrow, can take a closer look then!

2022-04-19 00:29 UTC, indradhanush commented
Happy to wait. Let's chat when you're back.

2022-04-19 09:42 UTC, ryanslade commented
@indradhanush Branch cut is today, do you think this is a release blocker?

2022-04-19 09:53 UTC, indradhanush commented
@ryanslade That's a good call out. I just commented with my findings in the original PR [here](https://github.com/sourcegraph/sourcegraph/pull/33219/files#r852835124). Would you be able to take a look and verify this? 

My feeling is that this is now a release blocker as we seem to have introduced a regression with the `GetRepository` (important and release blocker) and the `ListOrganizations` (not release blocker since it's not used currently) API.

If you agree, let's go ahead and mark this as a release blocker.

2022-04-19 12:24 UTC, indradhanush commented
@bobheadxi Based on the [latest findings](https://github.com/sourcegraph/sourcegraph/pull/33219#discussion_r852900816), it does seem like we have a regression in the caching mechanism and back to back calls to `/repos` API incurs an API call that counts against the rate limit. I'm marking this as a release blocker. 

I'm ending my day soon so likely won't be around for the release cut deadline. Feel free to take the call based on your judgement. I can come back and take a look at this tomorrow again.

2022-04-19 12:27 UTC, indradhanush commented
@davejrt Forgot to tag you here.

2022-04-19 12:52 UTC, ryanslade commented
cc @keegancsmith as release captain 🚢

2022-04-19 18:21 UTC, keegancsmith commented
@indradhanush any reason you didn't land this today?

2022-04-19 18:22 UTC, keegancsmith commented
@bobheadxi you marked this PR as needing changes. What do you need to check before landing this release blocker?

2022-04-19 18:33 UTC, keegancsmith commented
Ok I dived into all the different comment threads lol. If I am not mistaken the current state of this is the tests didn't have the caching middleware, so the assumption that there is a regression is incorrect. IE this revert likely won't land since the evidence it is needed was based on a faulty infra in our test env. I am moving forward with creating a RC without this PR. If I am wrong in this, I'm happy to create a new release candidate. If I am right, please tell me so I can remove the release blocking tag.

2022-04-19 22:08 UTC, bobheadxi commented
@keegancsmith , @ryanslade , @indradhanush - I've confirmed this is not an issue: https://github.com/sourcegraph/sourcegraph/pull/34004#discussion_r853523786

Removing the release-blocker label

2022-04-21 01:58 UTC, closed without merging