internal/extsvc/github: Add failing test for ListOrganizations
sourcegraph/sourcegraph pull request #34004
Opened 2022-04-18 12:26 UTC by indradhanush

Test case to verify #33219 is buggy.

## Test plan

2022-04-19 15:08 UTC, bobheadxi commented on internal/extsvc/github/v3_test.go
>  		cli, save := newV3TestEnterpriseClient(t, "ListOrganizations")
If you look into this function it looks like the the caching middleware is no longer registered: https://github.com/sourcegraph/sourcegraph/blob/main/internal/httptestutil/recorder.go#L80

cc @davejrt

2022-04-19 15:11 UTC, bobheadxi commented on internal/extsvc/github/v3_test.go
>  		cli, save := newV3TestEnterpriseClient(t, "ListOrganizations")
(though `httpcli` should probably export the preconfigured `CachedTransportOpt` for use in these cases)

2022-04-19 15:11 UTC, bobheadxi commented on internal/extsvc/github/v3_test.go
>  		cli, save := newV3TestEnterpriseClient(t, "ListOrganizations")
The lack of that middleware would explain why the cache isn't being hit in tests (there is no cache). The cache is instantiated by default for prod users of `httpcli` however

2022-04-19 22:06 UTC, bobheadxi commented on internal/extsvc/github/v3_test.go
>  		cli, save := newV3TestEnterpriseClient(t, "ListOrganizations")
looks fine with the cache set up in tests:

```
=== RUN   TestGetRepository
t=2022-04-19T15:02:43-0700 lvl=dbug msg="TRACE github" host=api.github.com path=/repos/sourcegraph/sourcegraph code=200 duration=483.520708ms
t=2022-04-19T15:02:43-0700 lvl=dbug msg=doRequest status="200 OK" x-ratelimit-remaining=4997
t=2022-04-19T15:02:43-0700 lvl=dbug msg="TRACE github" host=api.github.com path=/repos/sourcegraph/sourcegraph code=200 duration=3.931083ms
t=2022-04-19T15:02:43-0700 lvl=dbug msg=doRequest status="200 OK" x-ratelimit-remaining=4997
```

Also see the updated VCRs that demonstrate this in action, with `X-From-Cache`: https://github.com/sourcegraph/sourcegraph/pull/34004/commits/b3a0e430cc0526a975038c827769e9bd48a0971b

2022-04-20 06:48 UTC, indradhanush commented on internal/extsvc/github/v3_test.go
>  		cli, save := newV3TestEnterpriseClient(t, "ListOrganizations")
Thank you for your work! This was a great find! <3

2022-04-20 06:49 UTC, indradhanush commented
Outdated by #34161.

2022-04-20 06:54 UTC, bobheadxi commented
@indradhanush well still want to merge these test updates at some point!

2022-04-20 06:56 UTC, indradhanush commented
@bobheadxi Sorry my bad. I can update this PR today and get it ready for review.

2022-04-20 15:58 UTC, bobheadxi requested changes
@indradhanush I noticed you've re-generated your VCRs but none of the recordings have `X-From-Cache` anymore - did you have redis set up correctly? When I ran the tests previously I definitely saw `X-From-Cache` in the recordings

2022-04-20 15:58 UTC, bobheadxi commented on internal/extsvc/github/common.go
> +	log15.Debug("doRequest", "status", resp.Status, "x-ratelimit-remaining", resp.Header.Get("x-ratelimit-remaining"))
Do we still need/want this?

2022-04-20 16:13 UTC, indradhanush commented
@bobheadxi Hmm. That's super weird. Even though the assertion for the rate limit verifies that the second request uses the cache. I had redis running locally if that's what you meant by having redis setup correctly. Is there an additional step that needs to be done? 

Note that I had to add the calls to rcache.SetupForTest in these tests to suppress the warnings related to redis connection not found.

2022-04-20 16:15 UTC, bobheadxi commented
> Note that I had to add the calls to rcache.SetupForTest in these tests to suppress the warnings related to redis connection not found.

Ah if you've suppressed the warnings then maybe it's fine? I had to set an env variable to get it to use my cache

2022-04-20 16:16 UTC, bobheadxi approved these changes
If the test coverage is satisfactory let's go 😁 Thanks for your investigation!

![](https://media2.giphy.com/media/IwAZ6dvvvaTtdI8SD5/200.gif)

2022-04-21 01:53 UTC, indradhanush commented on internal/extsvc/github/common.go
> +	log15.Debug("doRequest", "status", resp.Status, "x-ratelimit-remaining", resp.Header.Get("x-ratelimit-remaining"))
I think it's useful, especially when running the tests. I'd weigh towards keeping it.

2022-04-21 01:55 UTC, indradhanush commented
> Ah if you've suppressed the warnings then maybe it's fine? I had to set an env variable to get it to use my cache

Oh. What was the env? Should we be using that instead of `rcache.SetupForTests(t)`? 

Also if we're expecting the `X-From-Cache` header to be set and it isn't getting set currently, then isn't that unexpected behaviour?

2022-04-21 01:56 UTC, indradhanush commented
@bobheadxi I'll go ahead and merge it and if we need to follow up with some investigations regarding the `X-From-Cache`, I'm happy to do that as a follow up PR.

2022-04-21 01:57 UTC, merged