vsce: add experimental esbuild support
sourcegraph/sourcegraph pull request #34010
Opened 2022-04-18 14:59 UTC by tjkandala

Adds ability to build the VS Code extension with esbuild. Production build time has gone from 120 seconds to 1.5 seconds on my M1 Pro MBP!

 
<img width="344" alt="Screen Shot 2022-04-18 at 10 55 36 AM" src="https://user-images.githubusercontent.com/37420160/163827354-0065ce77-1c99-40a0-8e64-f507a909433d.png">

![Screen Shot 2022-04-18 at 10 55 22 AM](https://user-images.githubusercontent.com/37420160/163827375-2423b5ae-0d7d-476a-9c9a-16da8fb77913.png)

TODO: 
- support webworker VS Code extension host
- add self-review comments
- ensure no regressions with integration tests
- Remove "with esbuild!" from `<BrandHeader>`

## Test plan

TODO

2022-04-26 21:28 UTC, abeatrix approved these changes
A small typo that results in running the `yarn watch:esbuild` command to fail with `Error: Command "task:guild" not found.` Other than that is a great change to replace the webpack build, it's SO MUCH FASTER!! Thank you TJ!

2022-04-26 21:28 UTC, abeatrix commented on client/vscode/package.json
> +    "watch:esbuild": "NODE_ENV=development WATCH=true yarn task:guild esbuild",
```suggestion
    "watch:esbuild": "NODE_ENV=development WATCH=true yarn task:gulp esbuild",
```

2022-04-26 21:36 UTC, abeatrix requested changes
Looks like the current build for VS Code Web does not work

![image](https://user-images.githubusercontent.com/68532117/165396391-42b4bcc3-fa05-4ec8-ada1-b8b5f1a883ae.png)

2022-04-26 21:36 UTC, abeatrix commented on client/vscode/src/webview/search-panel/components/BrandHeader.tsx
> +            Search your code and 2M+ open source repositories WITH ESBUILD!
```suggestion
            Search your code and 2M+ open source repositories
```

2022-05-25 15:26 UTC, abeatrix commented
Should we document this somewhere? 

```
Steps for node extension host
1. Run yarn build:esbuild in the client/vscode directory
2. Run "Launch VS Code Extension" task in VS Code

Steps for webworker extension host
1. Run yarn build:esbuild:web in the client/vscode directory
2. Run "Launch VS Code Web Extension" task in VS Code

```

2022-06-10 02:42 UTC, merged

2022-06-10 02:57 UTC, tjkandala commented
@vdavid I've merged the esbuild PR!