[vscode] Change headers are added to fetch requests
sourcegraph/sourcegraph pull request #34389
Opened 2022-04-23 12:30 UTC by ptxmac

This fixes #34338

2022-04-26 09:29 UTC, ptxmac commented
@cla-bot check

2022-04-28 00:17 UTC, abeatrix requested changes
Thank you for this contribution! This looks good to me and maybe we can simplify it even more. 

Also, we might want to update other parts of the code that is using the previous method for consistency or to unblock your issue completely, for example, the [extension.ts](https://github.com/ptxmac/sourcegraph/blob/ptx/change-header-type/client/vscode/src/extension.ts#L75-L91) file and the [eventSource.js](https://github.com/ptxmac/sourcegraph/blob/ptx/change-header-type/client/vscode/src/vendor/eventSource.js#L16). Or I can just update those once this is merged if you prefer.

2022-04-28 00:17 UTC, abeatrix commented on client/vscode/src/backend/requestGraphQl.ts
>      const accessToken = accessTokenSetting()
```suggestion
    const accessToken = overrideAccessToken || accessTokenSetting()
```

2022-04-28 00:17 UTC, abeatrix commented on client/vscode/src/backend/requestGraphQl.ts
>      if (overrideAccessToken) {
```suggestion
    if (accessToken) {
        headers.set('Authorization', `token ${accessToken}`)
    }
```
Then remove everything in the else if statement?

2022-04-29 19:34 UTC, abeatrix approved these changes
As mentioned the changes look good to me. We might want to update other files that still using the previous implementation, like the [extension.ts](https://github.com/ptxmac/sourcegraph/blob/ptx/change-header-type/client/vscode/src/extension.ts#L75-L91) and [eventSource.js](https://github.com/ptxmac/sourcegraph/blob/ptx/change-header-type/client/vscode/src/vendor/eventSource.js#L16) files, which we can do after this is merged if the current changes is working for you since we were not able to reproduce the issue on our side CC @tjkandala

2022-05-04 07:28 UTC, ptxmac commented
Sorry, I got a bit behind and didn't notice the comments.

I see you unresolved the suggestion again? Do you want them added in this change, or just push that to a future PR?

As it - this PR solved the problem for me, from my usage everything in the vscode extension works as it should

(I'm still very confused as to why my vscode / node is broken, but that's a problem for another time)

2022-05-05 16:08 UTC, abeatrix commented
@ptxmac we can go merge what you have changes to unblock the issue for you, but it looks like your PR is not passing the required test so it's blocking us to merge the fix. Can you try to update your PR according to the failed tests so that we can merge it, please?

2022-05-06 08:13 UTC, ptxmac commented
> @ptxmac we can go merge what you have changes to unblock the issue for you, but it looks like your PR is not passing the required test so it's blocking us to merge the fix. Can you try to update your PR according to the failed tests so that we can merge it, please?

Sure, but it's a bit unclear from the workflows which test is actually failing.
I've rebased on main, just to see if that fixes some of them

2022-05-06 20:32 UTC, abeatrix commented
@ptxmac Since the failed tests are blocking this PR, I have merged my PR with yours to see if that'd work. 
Please take a look at https://github.com/sourcegraph/sourcegraph/pull/35080 and let me know if this build works for you, thanks!

2024-01-10 20:40 UTC, eseliger commented
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

2024-01-10 20:40 UTC, closed without merging