Docs Update: Add Scheduled Builds
sourcegraph/sourcegraph pull request #34526
Opened 2022-04-26 17:39 UTC by abeatrix

Add instruction to create `Scheduled Builds` to docs

## Test plan

Docs update

2022-04-27 16:24 UTC, jhchabran commented on doc/dev/background-information/ci/index.md
> +
I think it could be useful to mention, the environment variables, which were a breakthrough moment in your understanding. 

```suggestion
You can also inject custom environment variables, for example, to trigger a custom [Run Type](#Run-types). 
```

2022-04-27 16:26 UTC, jhchabran commented on doc/dev/background-information/ci/index.md
> +You can schedule builds with build schedules, which automatically create builds at the  specified intervals.
Just adding a minor suggestion to explain why those builds could be useful. 

```suggestion
You can schedule builds with build schedules, which automatically create builds at the specified intervals. They are useful to create, for example, nightly builds. 
```

2022-04-27 21:29 UTC, abeatrix commented on doc/dev/background-information/ci/index.md
> +
Thanks for the reminder, since I just noticed the section has been moved to another page yesterday 😆

2022-04-27 21:29 UTC, abeatrix commented
Adding @bobheadxi as a reviewer since the section has been moved by him yesterday.

2022-04-27 22:03 UTC, bobheadxi requested changes
Thanks for the docs! Could you move this to the https://docs.sourcegraph.com/dev/background-information/ci/development#buildkite-infrastructure section (under "Buildkite infrastructure") instead, since it has to do with pipeline setup?

2022-04-27 22:03 UTC, bobheadxi commented on doc/dev/background-information/ci/development.md
> +![image](https://user-images.githubusercontent.com/68532117/165358554-85e48dd0-379c-4461-aef7-09e1cd058569.png)
```suggestion
![new schedule](https://user-images.githubusercontent.com/68532117/165358554-85e48dd0-379c-4461-aef7-09e1cd058569.png)
```

2022-04-27 22:03 UTC, bobheadxi commented on doc/dev/background-information/ci/development.md
> +![image](https://user-images.githubusercontent.com/68532117/165358933-a27e4293-a363-4a77-84d7-a3ce67f743d2.png)
```suggestion
![cron interval](https://user-images.githubusercontent.com/68532117/165358933-a27e4293-a363-4a77-84d7-a3ce67f743d2.png)
```

2022-04-27 22:32 UTC, abeatrix commented
> Thanks for the docs! Could you move this to the https://docs.sourcegraph.com/dev/background-information/ci/development#buildkite-infrastructure section (under "Buildkite infrastructure") instead, since it has to do with pipeline setup?
Yea that makes sense. I've moved it to the bottom under "Buildkite infrastructure" :)

2022-05-02 08:28 UTC, jhchabran approved these changes

2022-05-02 16:31 UTC, bobheadxi approved these changes
LGTM, thank you!

2022-05-02 16:31 UTC, merged