doc: add info about user/repo pending permissions
sourcegraph/sourcegraph pull request #34573
Opened 2022-04-27 12:12 UTC by sashaostrikov

While I still remember anything about it, I am adding this doc :)

## Test plan
Not a functional change

2022-04-27 12:16 UTC, ryanslade commented on doc/admin/repo/permissions.md
> +Pending permissions are created and stored when the repo permissions fetched from the code host contain users which are not yet users of Sourcegraph. This information is stored for the purpose of imm
```suggestion
Pending permissions are created and stored when the repo permissions fetched from the code host contain users which are not yet users of Sourcegraph. This information is stored for the purpose of immediate repo access for such users after joining Sourcegraph. During the process of user creation `user_pending_permissions` is queried and if there are any permissions for the user being created, then these permissions are added to `user_permissions` table and this user is ready to go in no time. Without pending permissions, user would have waited for user a permissions sync to happen.
```

2022-04-27 12:17 UTC, ryanslade commented on doc/admin/repo/permissions.md
> +`user_pending_permissions` table has a `bind_id` column which is an ID of the user of external code host: a username for Bitbucket Server, a GraphID for GitHub or a user ID for GitLab.
```suggestion
`user_pending_permissions` table has a `bind_id` column which is an ID of the user of external code host: a username for Bitbucket Server, a GraphQL id for GitHub or a user ID for GitLab. 
```

2022-04-27 12:18 UTC, ryanslade commented on doc/admin/repo/permissions.md
> +User pending permission is a composite entity containing of:
```suggestion
User pending permission is a composite entity comprising of:
```

2022-04-27 12:19 UTC, ryanslade commented on doc/admin/repo/permissions.md
> +`repo_pending_permissions` table maps `user_pending_permissions` entities to repo ID alongside with permission type (read/write). One row of the table maps one repo ID to an array of `user_pending_pe
We only have `read` access for now, so probably don't want to say `read/write`

2022-04-27 12:19 UTC, ryanslade approved these changes
Nice, thanks for adding this!

2022-04-27 12:21 UTC, sashaostrikov commented on doc/admin/repo/permissions.md
> +User pending permission is a composite entity containing of:
oh, that was a typo of "consisting", but I like comprising, thanks :)

2022-04-27 14:40 UTC, indradhanush requested changes
Looks good. Thank you for adding this!

Would be nice to have some eyes from @bobheadxi for a final check.

2022-04-27 14:40 UTC, indradhanush commented on doc/admin/repo/permissions.md
> +Pending permissions are created and stored when the repo permissions fetched from the code host contain users which are not yet users of Sourcegraph. This information is stored for the purpose of imm
```suggestion
Pending permissions are created and stored when the repo permissions fetched from the code host contain users which are not yet users of Sourcegraph. This information is stored for the purpose of immediate repo access for such users after joining Sourcegraph. During the process of user creation `user_pending_permissions` is queried and if there are any permissions for the user being created, then these permissions are added to `user_permissions` table and this user is ready to go in no time. Without pending permissions, new users will have to wait for their permissions sync to complete.
```

2022-04-27 14:40 UTC, indradhanush commented on doc/admin/repo/permissions.md
> +As soon as new user is created (to be more precise -- during the creation process itself), pending permissions are used to populate "ordinary" permissions (`repo_permissions` and `user_permissions` t
```suggestion
As soon as a new user is created on Sourcegraph, pending permissions (`repo_pending_permissions` and `user_pending_permissions`) are used to populate "ordinary" permissions (`repo_permissions` and `user_permissions` tables), after which the `user_pending_permissions` is cleared (however, `repo_pending_permissions` [is not](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8e128dd3434b9e548176f8f1148ead3981458db9/-/blob/enterprise/internal/database/perms_store.go?L979-981)).
```

2022-04-27 14:40 UTC, indradhanush commented on doc/admin/repo/permissions.md
> +`user_pending_permissions` table has a `bind_id` column which is an ID of the user of external code host: a username for Bitbucket Server, a GraphID for GitHub or a user ID for GitLab.
```suggestion
The `user_pending_permissions` table has a `bind_id` column which is an ID of the user of the external code host, for example a username for Bitbucket Server, a GraphID for GitHub or a user ID for GitLab. 
```

2022-04-27 14:40 UTC, indradhanush commented on doc/admin/repo/permissions.md
> +- and `bind_id`
```suggestion
- `service_type` (e.g. `github.com`, `gitlab`, `bitbucketServer`)
- `service_id` (ID of the code host, e.g. `https://github.com/`, `https://gitlab.com/`)
- `permission` (bitmask for a set of permissions)
- `object_type` (type of what is enumerated in `object_ids_ints` column; for now it is `repos`)
- `bind_id`
```

2022-04-27 14:40 UTC, indradhanush commented on doc/admin/repo/permissions.md
> +`repo_pending_permissions` table maps `user_pending_permissions` entities to repo ID alongside with permission type (only `read` currently). One row of the table maps one repo ID to an array of `user
```suggestion
`repo_pending_permissions` table maps `user_pending_permissions` entities to repo ID along with the permission type (currently only `read` is supported). Each row of the table maps a repo ID to an array of `user_pending_permissions` entries. It is designed as an inverted `user_pending_permissions` for more performant CRUD operations (see the DB migration description in [this commit](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/0705aa790d31fcd51713f4432496cc6bbb49cce8...bc30ae1186cf7a491ef21a5c00cb2f565288dfbb#diff-660eca66a5fad95783448fa468b2ce2fR50)).
```

2022-04-27 14:48 UTC, bobheadxi commented on doc/admin/repo/permissions.md
> +#### External code host user <-> Sourcegraph user mapping
```suggestion
#### External code host user to Sourcegraph user mapping
```

2022-04-27 14:49 UTC, bobheadxi commented on doc/admin/repo/permissions.md
> +
```suggestion
### Pending permissions

> NOTE: This section describes some very technical details behind background permissions sync. In most cases, you will not need to consult this section.

```

Alternatively we can also describe under which situations this section will be helpful!

2022-04-28 17:21 UTC, bobheadxi commented on doc/admin/repo/permissions.md
> +The `user_pending_permissions` table has a `bind_id` column which is an ID of the user of the external code host, for example a username for Bitbucket Server, a GraphID for GitHub or a user ID for Gi
```suggestion
The [`user_pending_permissions` table](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/schema.md#table-public-user-pending-permissions) has a `bind_id` column which is an ID of the user of the external code host, for example a username for Bitbucket Server, a GraphID for GitHub or a user ID for GitLab.
```

2022-04-28 17:22 UTC, bobheadxi commented on doc/admin/repo/permissions.md
> +all of which are included in a unique constraint. This entity is addressed in `user_ids_ints` column of `repo_pending_permissions` table by `id`.
```suggestion
all of which are included in a unique constraint. This entity is addressed in `user_ids_ints` column of [`repo_pending_permissions` table](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/schema.md#table-public-repo-pending-permissions) by `id`.
```

2022-04-28 17:22 UTC, bobheadxi commented on doc/admin/repo/permissions.md
> +`repo_pending_permissions` table maps `user_pending_permissions` entities to repo ID along with the permission type (currently only `read` is supported). Each row of the table maps a repo ID to an ar
```suggestion
[`repo_pending_permissions` table](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/schema.md#table-public-repo-pending-permissions) maps `user_pending_permissions` entities to repo ID along with the permission type (currently only `read` is supported). Each row of the table maps a repo ID to an array of `user_pending_permissions` entries. It is designed as an inverted `user_pending_permissions` for more performant CRUD operations (see the DB migration description in [this commit](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/compare/0705aa790d31fcd51713f4432496cc6bbb49cce8...bc30ae1186cf7a491ef21a5c00cb2f565288dfbb#diff-660eca66a5fad95783448fa468b2ce2fR50)).
```

2022-04-28 17:23 UTC, bobheadxi commented on doc/admin/repo/permissions.md
> +- `bind_id`
Can we just link https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/authz/perms.go?L190-218&utm_source=raycast-sourcegraph instead?

2022-04-28 20:14 UTC, sashaostrikov commented on doc/admin/repo/permissions.md
> +- `bind_id`
We can certainly add this link. My initial intention was not to enumerate these columns, but to include that these columns act as in fact a "composite primary key" and used in definition of uniqueness of a user_pending_permission entry

2022-04-28 20:37 UTC, bobheadxi commented on doc/admin/repo/permissions.md
> +- `bind_id`
Link inclusion is fine then! (or a symbol search for that symbol might be safer, in case it moves)

2022-04-29 05:46 UTC, unknwon reviewed
Thank you! Left some comments.

2022-04-29 05:46 UTC, unknwon commented on doc/admin/repo/permissions.md
> +Pending permissions are created and stored when the repo permissions fetched from the code host contain users which are not yet users of Sourcegraph. This information is stored for the purpose of imm
```suggestion
Pending permissions are created and stored when the repo permissions fetched from the code host contain users which are not yet having accounts on Sourcegraph. This information is stored for the purpose of immediate repo access for such users after joining Sourcegraph. During the process of user creation, `user_pending_permissions` is queried and if there are any permissions for the user being created, then these permissions are moved to `user_permissions` table and this user is ready to go in no time. Without pending permissions, new users will have to wait for their permissions sync to complete.
```

2022-04-29 05:46 UTC, unknwon commented on doc/admin/repo/permissions.md
> +As soon as a new user is created on Sourcegraph, pending permissions (`repo_pending_permissions` and `user_pending_permissions`) are used to populate "ordinary" permissions (`repo_permissions` and `u
```suggestion
As soon as a new user is created on Sourcegraph, pending permissions (`repo_pending_permissions` and `user_pending_permissions`) are used to populate "ordinary" permissions (`repo_permissions` and `user_permissions` tables), after which the `user_pending_permissions` is cleared (however, `repo_pending_permissions` [is not](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@8e128dd3434b9e548176f8f1148ead3981458db9/-/blob/enterprise/internal/database/perms_store.go?L979-981) for performance concerns and user IDs are monotonically increasing and would never repeat).
```

2022-04-29 05:46 UTC, unknwon commented on doc/admin/repo/permissions.md
> +- `service_type` (e.g. `github.com`, `gitlab`, `bitbucketServer`)
```suggestion
- `service_type` (e.g. `github`, `gitlab`, `bitbucketServer`)
```

2022-04-29 05:46 UTC, unknwon commented on doc/admin/repo/permissions.md
> +- `permission` (bitmask for a set of permissions)
Pretty sure this is a string of the access level, right now the only possible value is "read".

2022-04-29 05:46 UTC, unknwon commented on doc/admin/repo/permissions.md
> +all of which are included in a unique constraint. This entity is addressed in `user_ids_ints` column of [`repo_pending_permissions` table](#repo-pending-permissions) by `id`.
```suggestion
All of which are included as a unique constraint. This entity is addressed in `user_ids_ints` column of [`repo_pending_permissions` table](#repo-pending-permissions) by `id`.
```
I am not sure I understand the phrase "is addressed in", could you clarify?

2022-04-29 05:46 UTC, unknwon commented on doc/admin/repo/permissions.md
> +Overall, one entry of `user_pending_permissions` table means that _"There is a user with `bind_id` ID of this exact (`service_id`) external code host of this (`service_type`) type with such permissio
```suggestion
Overall, one entry of `user_pending_permissions` table means that _"There is a user with `bind_id` ID of this exact (`service_id`) external code host of this (`service_type`) type with such permissions for this (`object_ids_ints`) set of repos"_.
```

2022-04-29 18:28 UTC, bobheadxi approved these changes
Nice, thank you!

2022-05-06 17:36 UTC, merged