[SG-5168] Update NPS widget to collect use cases
sourcegraph/sourcegraph pull request #34589
Opened 2022-04-27 15:44 UTC by gitstart-sourcegraph

## Description
We recently introduced use cases at the company level and are now seeking to operationalize them. One gap to achieve that is tying customer feedback to use cases.
[RFC 600](https://docs.google.com/document/d/1_ClgFMY1aak3xG533j1KQYmIbx6u_QUnB8GL_GQWocM/edit#): Add use cases to the NPS widget, that just got reviewed, proposes to introduce collecting them.
This involves (proposal 1 in the RFC) updating the NPS widget to collect use cases [mockups](https://www.figma.com/file/WsGbJHkx7usyZpwa02RdQK/?node-id=1329%3A1718)

Urgency: It's important to start collecting use cases data. While this is not an emergency, it will have an immediate impact on the business.

## Refs
[Sourcegraph Issue](https://github.com/sourcegraph/about/issues/5168)
GitStart Ticket

## How to replicate current behavior:

- Open Sourcegraph.com in new incognito tab
- Run localStorage.setItem('temporarySettings', '{"user.daysActiveCount":2}') in the browser console
- Reload the page and the survey toast should appear. Relevant component [SurveyToast](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/marketing/SurveyToast.tsx?L73%3A48-73%3A114=&utm_source=VSCode-2.2.0)
- Click on "10" it will then load [SurveyPage](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/web/src/marketing/SurveyPage.tsx) at https://sourcegraph.com/survey/10

## Desired behavior:

- Click a number in toast
- Click "Continue" in toast
- Toast updates to show form shown in Figma mockups

## Implementation Plan
- Create a 4 Mutli-step form to compliment the `SurveyToast.ts`
- Modify unit tests accordingly.
- Fix integration tests for failing accessibility audits.

## Test Plan
- If `How to replicate current behavior` section steps does not work, add prop `forceVisible={true}` on `L216` `client/web/src/Layout.tsx`
- Ensure the UI matches the [figma design](https://www.figma.com/file/WsGbJHkx7usyZpwa02RdQK/?node-id=1329%3A1718).
- Ensure unit and integration test pass.

## Time Estimate
- `15 to 20 hours` to create the new UI and functionalities, update unit tests as some old ones will become obsolete.

2022-05-03 03:54 UTC, valerybugakov requested changes

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyUseCaseForm.module.scss
> +    gap: 0.5rem;
It seems that `gap` is different in the mockup: `6px` vs `8px` here.

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveySuccess.module.scss
> +    font-size: 0.875rem;
It seems redundant. Our default `font-size` is `0.875rem`.

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveySuccess.module.scss
> +    font-size: 0.875rem;
It seems redundant. Our default `font-size` is `0.875rem`.

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveySuccess.tsx
> +    handleDismiss: () => void
We usually use `handle*` for handers defined in the component and `on*` for props. 

```suggestion
    onDismiss: () => void
```

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveySuccess.tsx
> +    { label: 'How to link to multiple lines of code', link: 'ebay.com' },
@umpox, do we know who will provide links for this list?

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +export interface userFeedbackProps {
```suggestion
export interface UserFeedbackProps {
```

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +            setToggleErrorMessage(true)
Should we also check for user input on the `useCase` step to avoid empty submits?

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +        score: '',
Could we change the default value to `-1`? That would allow using stricker type this property — `number` instead of `number | string`.

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +        if (userFeedback.score !== '') {
Then the check here would be `userFeedback.score !== -1`

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +                        setUserFeedback(current => ({ ...current, ...props }))
```suggestion
                    handleDone={formState => {
                        setUserFeedback(current => ({ ...current, ...formState }))
```

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +    const [activeStep, setActiveStep] = useState(ToastSteps.rate)
```suggestion
    const [activeStep, setActiveStep] = useState<ToastSteps>(ToastSteps.rate)
```

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +            return null
Should we throw an error if an unknown `activeStep` is set?

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyUseCaseForm.module.scss
> +    > div {
Would it be possible to avoid element selectors by applying this rule via a separate class?

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyUseCaseCheckbox.tsx
> +    onChange?: (isChecked: boolean) => void
Should this prop be required?

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyUseCaseForm.tsx
> +                    <Button variant="primary" size="sm" onClick={() => handleSubmit()}>
Would it be possible to remove the redundant wrapper here?

```suggestion
                    <Button variant="primary" size="sm" onClick={handleSubmit}>
```

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyUseCaseForm.tsx
> +            onDismiss={() => handleDismiss()}
Would it be possible to remove the redundant wrapper here?

```suggestion
            onDismiss={handleDismiss}
```

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/Toast.module.scss
> +        font-weight: 600;
It seems redundant since the default `h2` `font-weight` is `600`

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/Toast.module.scss
> +    svg {
Can we create a separate CSS class for the SVG icon?

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyUserRatingForm.tsx
> +export { SurveyUserRatingForm }
Usually, we specify the `export` statement right before the component declaration. Is there a reason for it to be defined separately here?

2022-05-03 03:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyUseCaseCheckbox.module.scss
> +        -ms-transform: rotate(45deg);
Autoprefixer will take care of these properties: 

```suggestion
```

2022-05-03 05:25 UTC, gitstart-sourcegraph commented on client/web/src/marketing/SurveyToast.tsx
> +            setToggleErrorMessage(true)
Sounds good, should we also have an error message displayed when user attempts to proceed from step 2, without submitting the useCases? what message would be ideal?

2022-05-03 06:54 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +            setToggleErrorMessage(true)
Let's wait for the response from the @sourcegraph/design team. Maybe it's a conscious decision not to add an error message here. I would add something like, "Please select one of the use-cases to proceed.".

2022-05-03 07:01 UTC, quinnkeast commented on client/web/src/marketing/SurveyToast.tsx
> +            setToggleErrorMessage(true)
I personally believe we should not make it required. If it's required, we're likely to get bad data if users aren't sure what to select or don't want to answer. By keeping it optional, we can be confident in the responses being intentional.

@malomarrec @rrhyne wdyt?

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyRatingRadio.tsx
> -                        />
Can we try to keep this in?

It uses radio buttons intentionally here for improved accessibility. The benefit is that users can immediately understand there is a list of X amount, and that they can only select one

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyForm.tsx
> +        history.push(`/survey/${newScore}`)
I think we might be able to remove this page (SurveyPage) and the route. I'll double check.

cc: @quinnkeast. Figma comment: https://www.figma.com/file/WsGbJHkx7usyZpwa02RdQK?node-id=1329:1719#188637009

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveySuccess.module.scss
> +}
```suggestion
```

I think we should remove this. It's a bit of a "magic number" and I think it might be a result of a different default line height in Figma compared to our webapp

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveySuccess.tsx
> +    { label: 'How to link to multiple lines of code', link: 'ebay.com' },
@quinnkeast Any ideas as to if we have URLs for these links, or if we should change this content entirely? 

Figma comment here too: https://www.figma.com/file/WsGbJHkx7usyZpwa02RdQK?node-id=1329:1719#188634721

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyToast.tsx
> +                    toggleShouldPermanentlyDismiss={toggleShouldPermanentlyDismiss}
```suggestion
                    toggleShouldPermanentlyDismiss={setShouldPermanentlyDismiss}
```

Should be the same, I think? And we shouldn't need the extra `toggleShouldPermanentlyDismiss` function in this file then

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyUseCaseCheckbox.tsx
> +            <span className={classNames(styles.checkbox, checked ? styles.checkmark : styles.checkboxDefault)} />
Can we use `<input type="checkbox"` in this component?

It'll be better for accessibility. We should be able to get a similar solution to what we had in `SurveyRatingRadio` - an `<input>` element that appears as a button

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyUseCaseForm.module.scss
> +}
```suggestion
```

Also think we can remove this, as it seems like a minor change which is due to differences between Figma and our app if anything else.

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyUseCaseForm.tsx
> +                        ))}
```suggestion
            subtitle={<span id="usecase-group" className={styles.toastSubtitle}>You are using sourcegraph to...</span>}
            cta={
                <div className="mb-2">
                    <div className={styles.checkWrap}>
                        {OPTIONS.map(({ id, labelValue }) => (
                            <SurveyUseCaseCheckbox
                                onChange={() => handleSelectUseCase(id)}
                                key={id}
                                label={<span id={id} className={classNames('ml-1', styles.checkboxLabel)}>{labelValue}</span>}
                                aria-labelledby={`usecase-group ${id}`}
                            />
                        ))}
```

I think we'll have to do something like this to make it accessible. Note the ids on each element + subtitle and aria-labelledby

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyUserRatingForm.tsx
> +                {toggleErrorMessage && <div>Please select a score between 0 to 10</div>}
Not included in design, cc: @quinnkeast 

I think we should give this text `color: var(--danger)` at a minimum.

2022-05-03 10:43 UTC, umpox commented on client/web/src/marketing/SurveyUserRatingForm.tsx
> +                {toggleErrorMessage && <div>Please select a score between 0 to 10</div>}
```suggestion
                {toggleErrorMessage && <div role="alert">Please select a score between 0 to 10</div>}
```

So it notifies screen readers

2022-05-04 04:17 UTC, valerybugakov commented on client/web/src/marketing/SurveyToast.tsx
> +            setToggleErrorMessage(true)
Makes sense, thanks for a quick response @quinnkeast!

2022-05-04 13:07 UTC, umpox commented on client/web/src/marketing/SurveyUseCaseForm.tsx
> +                                aria-labelledby={`usecase-group ${id}`}
```suggestion
                                aria-labelledby="usecase-group"
```

We can actually just use the subtitle, as we now set `label` through `Checkbox`

2022-05-04 13:08 UTC, umpox commented on client/web/src/marketing/SurveyUserRatingForm.tsx
> +                <SurveyRatingRadio ariaLabelledby="survey-form-scores" onChange={onChange} />
```suggestion
                <SurveyRatingRadio ariaLabelledby="survey-toast-scores" onChange={onChange} />
```

2022-05-05 14:17 UTC, gitstart-sourcegraph commented on client/web/src/marketing/SurveyUseCaseCheckbox.tsx
> +            as="label"
@umpox Noticed some side effect of making this change.
Currently the `as="label"` helps to ensure that clicking any side of the button actually triggers the check.
However with `as="div"` we currently have a case were clicking the edge areas of the button does not trigger the check.
WDYT  if we rendered a native `input` element here, to avoid multiple labelling with `Checkbox` component

2022-05-09 09:11 UTC, umpox reviewed
Thanks. FYI I'm chasing some required admin changes for the backend work, it's taking a little longer than expected but, as this code is specifically scoped to folders that don't often change, I think we're OK to keep this PR around a little longer

2022-05-09 09:11 UTC, umpox commented on client/web/src/marketing/SurveyUseCaseCheckbox.tsx
> +            as="label"
Ah I see, OK let's go with this approach now. We can revisit when we migrate `<input` elements away,

2022-05-31 13:17 UTC, umpox commented
@gitstart-sourcegraph I've merged the backend work required for this survey (https://github.com/sourcegraph/sourcegraph/pull/35940) into this PR.

Please can you update this branch to submit the data?

Requirement notes:
- [ ] Use case submissions should follow the enums now in GQL. See the example mutation in the [previous PR description](https://github.com/sourcegraph/sourcegraph/pull/35940).
- [ ] We should not submit "Other" as a use case to GQL, it should just show the `"What else are you using Sourcegraph to do?"` question
- [ ] `"What else are you using Sourcegraph to do?"` and `"Anything else you'd like to share with us?"` can just be submitted to GQL as strings
- [ ] Clicking "Done" or the "X" in the top right should submit the mutation. The only required field is `score` so it should still be possible for a user to submit feedback by clicking the "X" before they even click "Continue" in the first screen

2022-06-03 06:11 UTC, gitstart-sourcegraph commented
Would it be beneficial to modify this to include the use cases as well?.
e,g `after using @sourcegraph for <xyz>: ${feedback}`
https://github.com/sourcegraph/sourcegraph/blob/2abe73cfcaed9de179fd91a1ea68b751342fdbe6/client/web/src/marketing/TweetFeedback.tsx#L18-L21

2022-06-07 12:52 UTC, umpox commented
Thanks @gitstart-sourcegraph, reviewing now. I'll make some small changes directly to the PR in the interest of time, as it's quite large now!

2022-06-07 12:52 UTC, umpox commented
Thanks @gitstart-sourcegraph, reviewing now. I'll make some small changes directly to the PR in the interest of time, as it's quite large now!

2022-06-08 09:33 UTC, umpox commented
@gitstart-sourcegraph Made some changes and following up on design + product questions in our internal Slack channels. I'll take over this PR from now until it is merged, thank you!

2022-06-08 16:58 UTC, jasongornall commented on client/web/src/marketing/components/SurveyRatingRadio.tsx
> +                        className={classNames(radioStyles.ratingBtn, !focused && radioStyles.ratingBtnDefault, {
should these styles be called focused and unfocused vs default and regular?

2022-06-08 17:01 UTC, jasongornall commented on client/web/src/marketing/components/SurveyUseCaseForm.tsx
> +] as const
is this necessary?

2022-06-08 17:23 UTC, jasongornall commented
https://user-images.githubusercontent.com/6912393/172678980-06e03581-109c-48de-8b54-afa2ff590f29.mp4

Using tab I can only seem to select 0 or 10?

2022-06-08 17:31 UTC, jasongornall commented
https://user-images.githubusercontent.com/6912393/172680558-421bba7a-a91c-465b-9a72-51676e7322ee.mp4

x button may be broken

2022-06-09 03:38 UTC, valerybugakov reviewed
@jasongornall already mentioned everything that bumped into testing locally.
I found only one additional issue in the Storybook story and left a couple of optional suggestions. 

The backend integration looks solid! 💪

2022-06-09 03:38 UTC, valerybugakov commented on client/web/src/marketing/toast/SurveyToast.tsx
> +        if (!loadingTemporarySettings) {
Optional: it's a bit tricky to follow all the steps that would lead to the survey toast becoming visible. Extracting `loadingTemporarySettings` logic into a wrapper component that would render `null` until we received all the required settings would simplify the render function.

2022-06-09 03:38 UTC, valerybugakov commented on client/web/src/marketing/toast/SurveyToast.tsx
> +        email: '',
To address the blank email field in the submitted form data that @jasongornall mentioned, we could prefill it if the `authenticatedUser` is available.

2022-06-09 03:38 UTC, valerybugakov commented on client/web/src/marketing/toast/SurveyUseCaseToast.tsx
> +    }, [useCases, otherUseCase, additionalInformation, email])
Optional: what do you think about removing the internal component state in favor of the state defined in the `SurveyToast` to keep one source of truth? We wouldn't need to synchronize states using `useEffect`, and we would rely on the `UserFeedbackProps` type already defined one level above.

2022-06-09 03:38 UTC, valerybugakov commented on client/web/src/marketing/components/SurveyUseCaseCheckbox.module.scss
> +    color: var(--body-color);
It seems that removing these styles doesn't make any difference.

2022-06-09 03:38 UTC, valerybugakov commented on client/web/src/marketing/components/SurveyUseCaseForm.module.scss
> +    font-size: 0.75rem;
We could remove this class in favor of `<Text size="small" />`.

2022-06-09 03:38 UTC, valerybugakov commented on client/web/src/marketing/components/SurveyUseCaseForm.tsx
> +] as const
It makes this array `readonly` with more precise type information VS only keeping type information about item structure.

| Without `as const` | With `as const` |
| -- | -- |
| <img width="218" alt="Screen Shot 2022-06-09 at 11 31 43" src="https://user-images.githubusercontent.com/3846380/172758419-97d22411-fea9-41dd-967c-568ad1f2e437.png"> | <img width="502" alt="Screen Shot 2022-06-09 at 11 31 33" src="https://user-images.githubusercontent.com/3846380/172758435-f84d4eb2-3dd2-4af6-a61f-86653bdcaa54.png"> |

2022-06-09 04:13 UTC, valerybugakov commented on client/web/src/marketing/toast/SurveyUserRatingToast.tsx
> +                <SurveyRatingRadio ariaLabelledby="survey-toast-scores" onChange={onChange} />
Actually @jasongornall [spotted](https://github.com/sourcegraph/sourcegraph/pull/34589#issuecomment-1150192186) this one too. I missed this comment 🙂

2022-06-09 09:24 UTC, umpox commented on client/web/src/marketing/toast/SurveyToast.tsx
> +        if (!loadingTemporarySettings) {
Agree, it's tricky as we also utilise the temporary setting values for other logic (like setting future states after dismissal). I've reworked this a bit more though, now there's `SurveyToastTrigger` (handles the visibility logic) and `SurveyToastContent` (handles everything once the toast is visible)

2022-06-09 09:46 UTC, umpox commented on client/web/src/marketing/toast/SurveyUserRatingToast.tsx
> +                <SurveyRatingRadio ariaLabelledby="survey-toast-scores" onChange={onChange} />
Agree, good catch!

I've updated it, here's how it looks now:

https://user-images.githubusercontent.com/9516420/172818238-25ffee53-b429-43ae-8465-26aabcad9ca5.mp4

cc: @jasongornall This also fixes your issue. The question about the tabs is just that these are radio buttons (can only select 1 score at a time), and it should use arrow keys to navigate within the radio button group.

This should now match the W3 examples so confident it is accessible: https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/radio/radio-1/radio-1.html

2022-06-09 09:48 UTC, umpox commented on client/web/src/marketing/toast/SurveyToast.tsx
> +        email: '',
This is actually intentional, we [overwrite this ourselves in the backend using the UID.](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@contractors/SG-5168/-/blob/cmd/frontend/graphqlbackend/survey_response.go?L116%3A1-128%3A1=)

I guess this is so users can't spoof feedback from other accounts

2022-06-09 10:02 UTC, umpox commented on client/web/src/marketing/toast/SurveyUserRatingToast.tsx
> +                <SurveyRatingRadio ariaLabelledby="survey-toast-scores" onChange={onChange} />
OK fixed for reals now I think

https://user-images.githubusercontent.com/9516420/172821472-1df9478c-d0b3-4ed2-804b-f5a551dbac1d.mp4

2022-06-09 10:46 UTC, umpox commented
@jasongornall 
> x button may be broken

I haven't been able to replicate this unless I had `forceVisible` on? Was this the case for you? That's only really used for testing/Storybook so shouldn't affect actual users

>repro: add other use-case and then uncheck then submit.

Good catch, have fixed - thanks!

2022-06-09 10:46 UTC, umpox commented on client/web/src/marketing/toast/SurveyUseCaseToast.tsx
> +    }, [useCases, otherUseCase, additionalInformation, email])
I agree, I've restructured this quite a bit to support this now, PTAL!

2022-06-09 12:29 UTC, jasongornall commented
> I haven't been able to replicate this unless I had `forceVisible` on? Was this the case for you? That's only really used for testing/Storybook so shouldn't affect actual users
> 
> >

Yeah I had force visible on. This may be a non issue you can just ignore....

2022-06-10 11:24 UTC, valerybugakov commented on client/web/src/marketing/toast/SurveyToast.tsx
> +        if (!loadingTemporarySettings) {
The update looks great 👍

2022-06-10 11:30 UTC, valerybugakov approved these changes
Updates look solid! ⛴

2022-06-28 08:13 UTC, merged