Code Insights: Add search context filter v1
sourcegraph/sourcegraph pull request #34620
Opened 2022-04-28 01:48 UTC by vovakulikov

Closes https://github.com/sourcegraph/sourcegraph/issues/33830

## Background 

## Test plan

- Make sure that all integration tests work properly with 
- Make sure all visual details look correct according to the search UI [designs](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0-%2333249-%26-v.1-%2333830)-%5Bready-for-dev%5D?node-id=1313%3A24762)

2022-04-28 12:17 UTC, AlicjaSuska requested changes
Thank you for sharing your work @vovakulikov. Great progress!

I've created a [Design QA page](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/?node-id=1526%3A27257) with all the issues I found as well as the loom video for searching and focus issues.

2022-04-29 06:24 UTC, vovakulikov commented
@AlicjaSuska thanks for your review, I have fixed almost all problems but just to make sure that I haven't missed anything important I list them below

- **search issues**, as we tackled this yesterday it turned out that this is BE issue and we have the same problem. I created an issue for this problem for the team search product https://github.com/sourcegraph/sourcegraph/issues/34686
- **list styling**, I adjusted visual styles for hover and keyboard picked items accordingly to your designs, thanks for catching this. 
- **success focus states** I removed the success state from the filter field as we discussed this yesterday on sync. I left the error state actually for a regular expression and search context field (only state without error message below) because it makes sense to show that we didn't find a search context or regular expression filters have a problem. 
- **monospace** it turned out that we didn't have a proper CSS variable for it, I added monospace for all needed elements according to designs. 
- **Add color to ‘@’ to align with contexts selector** this is actually it turned out complex thing to do. I added syntax highlight for repo and -repo values though. but for context for some reason, our logic about highlighting doesn't work. I suggest moving forward without it and implementing this later.
- **Update insight only after selecting context, not when searching** So this works in the following way now: 1. You input something in the search field. 2. We are in parallel making requests for suggestion items and also request to validate that your input context value exists and render an error state if your input value doesn't exist 3. If your input value is valid we re-run the insight data card. 

https://user-images.githubusercontent.com/18492575/165894322-d882e1b1-93ed-4840-b245-860c4aebcf31.mov

2022-04-29 23:38 UTC, unclejustin approved these changes
LGTM @vovakulikov, just few comments.

I think in the future to keep the size down we should separate the new components from actually using them. Then we would have a nice clean separation of concerns in the PRs.

2022-04-29 23:38 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/utils.ts
> +import { Validator } from '../../../../../form/hooks/useField'
non-blocking: we should unit test this file

2022-04-29 23:38 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/search-context/DrillDownSearchContextFilter.tsx
> +            ) : null}
non-blocking: I think this would be a lot cleaner if we used short circuits instead of nested ternarys.

For example:
```typescript
if (loading) {
        return <LoadingSpinner />
    }

    if (error) {
        return <ErrorAlert error={error} />
    }

    if (!data) {
        return null
    }

    if (queryBasedContexts.length === 0) {
        return (
            <span className={styles.suggestNoDataFound}>
                No query-based search contexts found.{' '}
                <Link to="/contexts/new" rel="noreferrer noopener" target="_blank">
                    Create search context
                </Link>
            </span>
        )
    }

    return (
        <>
            {queryBasedContexts.map(context => (
                <ComboboxOption key={context.id} value={context.spec} className={styles.suggestItem}>
                    <TruncatedText as="small" className={styles.suggestItemName}>
                        <ComboboxOptionText />
                    </TruncatedText>

                    <TruncatedText as="small" className={styles.suggestItemDescription}>
                        {context.description}
                    </TruncatedText>
                </ComboboxOption>
            ))}
        </>
    )
```

2022-04-29 23:38 UTC, unclejustin commented on client/web/src/enterprise/insights/components/trancated-text/TrancatedText.tsx
> +import { forwardRef } from 'react'
non-blocking: we should fix the typo in this file name. TrancatedText -> TruncatedText

2022-04-29 23:38 UTC, unclejustin commented on client/web/src/integration/insights/drill-down-filters.test.ts
> +        await delay(500)
non-blocking: Curious does this delay need to actually be 500ms? Would 5 work? What about 0? If it needs to be 500ms will that always be true?

2022-04-30 08:51 UTC, AlicjaSuska approved these changes
Thank you for making changes @vovakulikov lgtm! I agree with your points in the previous comment - let's move forward with styles that are applied now :)

I've noticed one thing about 'default filters applied' message that needs correcting (probably in a separate issue):
1. open insights with default filters applied - 'Default filters applied' text is displayed, pink dot displayed
2. Change filters (reduce scope)  / reset filters - text should disappear (now, it's still being displayed), dot disappears

Here is the [loom](https://www.loom.com/share/1c21be7e23574826bc4b7ae7ec1a58e3) showing what's happening and the [Figma design](https://www.figma.com/file/Ml5dtV9ni4mfffbfOfF9jg/Allow-search-contexts-as-filters-to-code-insights-(v0-%2333249-%26-v.1-%2333830)-%5Bready-for-dev%5D?node-id=1281%3A26570) (diagram) that shows the desired flow.

2022-05-02 03:03 UTC, vovakulikov commented on client/web/src/integration/insights/drill-down-filters.test.ts
> +        await delay(500)
@unclejustin this is 500 because we have an input debounce and async validation debouncing logic within the form hook. So if we remove this or set it to 0 or 5ms this test will fail.

2022-05-02 03:11 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/search-context/DrillDownSearchContextFilter.tsx
> +            ) : null}
100% agree, I rewrote this logic with early returns, thanks!

2022-05-02 03:12 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/utils.ts
> +import { Validator } from '../../../../../form/hooks/useField'
I created an issue for integration and unit test catch up around this new functionality around filter panel

2022-05-02 03:22 UTC, vovakulikov commented
@AlicjaSuska thanks for noticing this, I created an issue for tracking this problem with applied filter text here https://github.com/sourcegraph/sourcegraph/issues/34752

Let's continue conversation around this in that issue.

2022-05-02 13:40 UTC, merged