Bo/fix accessibility issues
sourcegraph/sourcegraph pull request #34716
Opened 2022-04-29 20:41 UTC by BolajiOlajide

## Test plan

Tested with screen reader to make sure the page is now more accessible.

Closes #34669, #34666

2022-05-03 03:31 UTC, courier-new approved these changes
Looks great!! Made 1 suggestion for a potentially different take on screen-reading the changeset stats, otherwise 🚢!!

2022-05-03 03:31 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
Ugh, amazing, why was this *ever* a `<div />`!! 😂

2022-05-03 03:31 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeNode.tsx
> +                        }
It's a bit rough here that we kinda have to duplicate the label text with slightly different wording for `aria` and hide the real one. I'm wondering if we ought to encapsulate all of these changesets stats in a `<div role="region" />` and `aria-label` that as "Changeset stats" instead. It makes it a bit more fluid to navigate, allows us to drop "changesets" from the screen-read labels, and in turn allows us to then use `aria-labelledby` for each specific status KPIs with the actual DOM labels, instead of kinda duplicating them:

```tsx
<div role="region" aria-label="Changeset stats">
    <ChangesetStatusOpen
        aria-labelledby="changesets-open-label"
        className="d-block d-sm-flex"
        label={
            <span className="text-muted" id="changesets-open-label">{`${node.changesetsStats.open} open`}</span>
        }
    />
```

(Disclaimer: haven't actually tested that code, just a suggestion 😅)

2022-05-03 03:31 UTC, courier-new commented on client/web/src/batches/icons.tsx
> +            aria-hidden={true}
❤️

2022-05-03 03:33 UTC, courier-new commented
Oh one other comment, I just noticed on the Storybook story and UI review check on Chromatic, it looks like the connection list gained some extra top padding that we might not want:

![image](https://user-images.githubusercontent.com/8942601/166401634-6dfbe7d6-9de5-4de7-8c0e-e2eb79720424.png)

2022-05-03 10:42 UTC, eseliger requested changes
This breaks the grid, so requesting changes. Added two more small inline comments but those aren't as critical to me.

2022-05-03 10:42 UTC, eseliger commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
because a `<ul>` doesn't support css grid 😬 Now the grid lives on the line items, which behaves like flex containers, but not the initial grid anymore:

On this branch:
![CleanShot 2022-05-03 at 12 14 53@2x](https://user-images.githubusercontent.com/19534377/166437222-86c7a5d7-87a8-4773-b86a-0d645f0b5ea4.png)

On main:
![CleanShot 2022-05-03 at 12 18 48@2x](https://user-images.githubusercontent.com/19534377/166437433-decc0af5-3a55-4224-a1ae-d10b3368ac08.png)

2022-05-03 10:42 UTC, eseliger commented on client/web/src/enterprise/batches/list/BatchChangeNode.tsx
> +                        }
since this is a list node, the ID would not be unique, but otherwise this could work :)

2022-05-03 10:42 UTC, eseliger commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                                <H3 as={H2} className="align-self-end flex-1" aria-live="assertive" aria-atomic="true">
Are you sure we want to be assertive here? What's our bar to set that property 🤔

2022-05-03 10:42 UTC, eseliger commented on client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx
> +                <Badge variant="success" className={styles.statePill} aria-hidden={true}>
Do we want this to be hidden? It's the only indicator we got for the open/closed/draft status.

2022-05-03 14:43 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
NOOOOO darn it CSS grid. 😭

2022-05-03 14:52 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                                <H3 as={H2} className="align-self-end flex-1" aria-live="assertive" aria-atomic="true">
Oh! That's an artifact I should've removed - i was testing something and I forgot to remove that. Ideally, we want it to be `polite` instead of it being `assertive`, however it doesn't work either way because the components from the design system don't forward HTML props so that never gets forwarded. 

I'll need to refactor for this to work. Thanks

2022-05-03 14:54 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
Unfortunately, Erik is right lol. Struggled with that part a bit and I should have added a comment about why that regression might exist.

Another option (a bit hacky sort of) is to set a fixed width on the individual changeset icon + text. Haven't tried that but I'll see how much of that gets fixed.

2022-05-03 14:57 UTC, eseliger commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
why do we need to switch away from css-grid here? we use that pattern in quite a few places :(

2022-05-03 15:02 UTC, eseliger commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
oh lord, in that case I think we should table it and look for a general working solution first. This pattern is adopted across multiple pages and lists.. It feels like it's a non-trivial effort to get it to work again somewhat similarly.

2022-05-03 15:43 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                                <H3 as={H2} className="align-self-end flex-1" aria-live="assertive" aria-atomic="true">
Ah! If you need another way to announce the total count change, FPT also recently introduced the super lightweight [`screenReaderAnnounce`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/wildcard/src/utils/screenReaderAnnounce.ts?L10%3A45=), which you could potentially use instead.

2022-05-03 15:51 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeStatePill.tsx
> +                <Badge variant="success" className={styles.statePill} aria-hidden={true}>
I think it's okay since Bolaji put an `aria-label` on the parent up at line 64, instead.

2022-05-05 23:37 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeNode.tsx
> +                        }
Yes this works. Made some minor change to Kelli's suggestion but it works. :)

2022-05-06 00:22 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
What's the best way to get this sorted? @eseliger @courier-new 

I've done a bit of digging today and couldn't find a way around maintaining the grid and changing the pattern to fix this accessibility issue.

2022-05-06 00:22 UTC, BolajiOlajide commented
> Oh one other comment, I just noticed on the Storybook story and UI review check on Chromatic, it looks like the connection list gained some extra top padding that we might not want:
> 
> ![image](https://user-images.githubusercontent.com/8942601/166401634-6dfbe7d6-9de5-4de7-8c0e-e2eb79720424.png)

Fixed.

2022-05-06 00:27 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
We're likely not to be the only team displaying a `FilteredConnection` that needs to function as a grid. I think it's okay to revert this part of your PR and, if there isn't a dedicated issue already, file one specifically for supporting a grid layout in the `ConnectionList` component for FPT to own.

2022-05-06 00:30 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
Got it. Thanks.

2022-05-06 00:31 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
(Bonus points if you throw in a comment by this line to explain why we can't use `ul` right now)

2022-05-06 00:48 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                                <H3 as={H2} className="align-self-end flex-1" aria-live="assertive" aria-atomic="true">
Done

2022-05-06 01:54 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeListPage.tsx
> +                        <ConnectionList as="ul">
I've created an issue for the `ConnectionList` [here](https://github.com/sourcegraph/sourcegraph/issues/35034)

@eseliger @courier-new Can you review this PR one last time? Thanks.

2022-05-06 10:01 UTC, eseliger approved these changes

2022-05-06 10:01 UTC, eseliger commented on client/web/src/enterprise/batches/list/BatchChangeNode.module.scss
> -        }
was this style not needed anymore?

2022-05-06 17:00 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeNode.module.scss
> -        }
Yes we do. It was part of the last group of commits I `un-did` and I forgot to push.
I just did now.

2022-05-06 18:56 UTC, courier-new approved these changes
💯  Thanks for working through these Bolaji!! Just had one question of sorts.

2022-05-06 18:56 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeNode.tsx
> +                                aria-hidden={true}
TIL `aria-labelledby` can still use content from an element that's `aria-hidden`. 😮  Just curious, does it read it off twice if you don't `aria-hide` it? I admit it was a bit unexpected to see this at first (wait, but the label is... hidden?), until I read the docs explaining that still works.

2022-05-06 18:56 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeNode.tsx
> +                                aria-hidden={true}
(Do you think it's worth including any comment here about the interaction between `aria-labelledby` and `aria-hidden`?)

2022-05-06 18:59 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/list/BatchChangeNode.tsx
> +                                aria-hidden={true}
Yes. 
The screen readers reads the content twice if aria-hidden isn't true, i found that odd myself but I recently learnt it's because in the event there's more than one content in a group and only one acts a the description for the group then it makes sense that the screen reader doesn't automatically assume the other contents of the group shouldn't be read unless it's explicitly specified.

I'm out for dinner but I'll add a comment as soon as I'm back.

2022-05-06 19:01 UTC, courier-new commented on client/web/src/enterprise/batches/list/BatchChangeNode.tsx
> +                                aria-hidden={true}
Got it! Thanks for explaining, Bolaji, that does seem reasonable. Good to know! 🙂

2022-05-10 01:26 UTC, LawnGnome approved these changes
Nice work!

2022-05-10 22:23 UTC, merged