monitoring: hide alerts table
sourcegraph/sourcegraph pull request #34809
Opened 2022-05-03 06:40 UTC by michaellzc

## Test plan

2022-05-03 06:40 UTC, michaellzc commented
Current dependencies on/for this PR:
* main
  * **PR #34808** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/34808" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #34809** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/34809" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/34809?utm_source=stack-comment).

2022-05-03 23:08 UTC, bobheadxi commented
@michaellzc thoughts on https://github.com/sourcegraph/sourcegraph/pull/34808#issuecomment-1116741617 instead? If there are no alerts here I don't think we should stretch the semantics of `Container` for custom dashboards without doing some wholistic exploration/design work

2022-05-04 00:14 UTC, bobheadxi requested changes
> should I hack into [renderRules](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/monitoring/monitoring.go?L286:21) and renderDocumentatino as well so we can get rid of all the observable transformer?

Could you clarify this a bit?

2022-05-04 00:14 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	NoAlertsDefined bool
Can this just be inferred? If all observables in all groups have no alerts, disable the alerts table?

2022-05-04 00:22 UTC, michaellzc commented
> > should I hack into [renderRules](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/monitoring/monitoring/monitoring.go?L286:21) and renderDocumentatino as well so we can get rid of all the observable transformer?
> 
> Could you clarify this a bit?

the `NoAlerts` flag right now only prevents the rendering of the alerts toggle and alerts table in the dashboard, but it will still render prometheus rules and the auto-gen alerts documentation unless we add the custom transformer like

```go
containersNoAlertTransformer := func(observable shared.Observable) shared.Observable {
		return observable.WithNoAlerts(`Alerts are enabled in service-specific dashboard.`)
}

shared.NewKubernetesMonitoringGroup(containerName, monitoring.ObservableOwnerDevOps, &shared.KubernetesMonitoringOptions{
  PodsAvailable: containersNoAlertTransformer,
}),
```

Notes: if we can infer this from the groups, we shouldn't need to do anything special to the current generator for docs and prom alerts rules

> Can this just be inferred? If all observables in all groups have no alerts, disable the alerts table?

That would be great and I will take a look

2022-05-04 17:47 UTC, michaellzc commented on monitoring/monitoring/monitoring.go
> +	}
do you prefer to merge these two blocks under the same if condition? 
does it mater whether we're mutating `board.Annotations.List` or `board.Templating.List` first?

2022-05-04 18:46 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +func (c *Container) isAlertDefined() bool {
Alerts should be defined as a preferred default, so this condition should be inverted:

```suggestion
func (c *Container) noAlertsDefined() bool {
```

2022-05-04 18:48 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	}
I think the ordering of variables inserted into annotations and templating matters, if that can be preserved I don't mind the blocks being joined

2022-05-05 12:58 UTC, caugustus-sourcegraph approved these changes

2022-05-05 12:58 UTC, caugustus-sourcegraph commented on monitoring/monitoring/monitoring.go
> +	if !c.noAlertsDefined() {
I'm sympathetic to @bobheadxi's [point here](https://github.com/sourcegraph/sourcegraph/pull/34809#discussion_r865159551) about alerts being the default, but I do want to mention that `!c.noAlertsDefined` is harder to think about than `c.isAlertDefined`.

2022-05-05 19:54 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	if !c.noAlertsDefined() {
I'd be fined with a reassignment a la `hasAlertsDefined := !c.noAlertsDefined()` and using that throughout, but on the `Container` itself we should export an API that is representative of the default state

2022-05-09 23:55 UTC, michaellzc commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/34809?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: RicP9zqDgyRrH5qyJYZs

2022-05-09 23:55 UTC, merged