extensions: add allow only Sourcegraph authored extensions setting
sourcegraph/sourcegraph pull request #35054
Opened 2022-05-06 14:39 UTC by taras-yemets

Closes https://github.com/sourcegraph/sourcegraph/issues/34962

## Test plan

2022-05-16 08:54 UTC, unknwon commented on enterprise/cmd/frontend/internal/registry/allow.go
> +		if allowedExtensionIDs == nil {
```suggestion
		if len(allowedExtensionIDs) == 0 {
```

It is better and more robust to check for length of a slice than the `nil`.

2022-05-16 08:54 UTC, unknwon commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
Could you explain the change here? We're iterating over `extensionsWithAllowedPublisher` but checking on `x.ExtensionID`?

2022-05-16 08:54 UTC, unknwon commented on enterprise/cmd/frontend/internal/registry/allow.go
> +}
nit:
```suggestion
func isSourcegraphAuthoredExtension(p *client.Publisher) bool {
	return p.Name == "sourcegraph"
}
```

All we need is the publisher, doesn't seem worth passing in the entire extension struct.

2022-05-16 09:56 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
> +		if allowedExtensionIDs == nil {
@unknwon, I wonder if it covers the case when [`getAllowedExtensionsFromSiteConfig` returns `nil`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@taras-yemets/add-allow-only-sourcegraph-extensions-setting/-/blob/enterprise/cmd/frontend/internal/registry/allow.go?L68-79)?
Sorry, I'm new to Go and I may be asking silly questions 🙂

2022-05-16 10:14 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
@unknwon, my understanding is that `x.ExtensionID` represents the id of an extension with the allowed publisher (Sourcegraph-authored if [`getAllowOnlySourcegraphAuthoredExtensionsFromSiteConfig()`](https://sourcegraph.com/-/editor?remote_url=git@github.com:sourcegraph/sourcegraph.git&branch=taras-yemets/add-allow-only-sourcegraph-extensions-setting&file=enterprise/cmd/frontend/internal/registry/allow.go&editor=VSCode&version=2.2.2&start_row=80&start_col=0&end_row=86&end_col=1) returns `true` or all if it returns `false`).
As we can have allowed extensions defined and allow only Sourcegraph extensions setting set to `true` we filter by both parameters ([test case](https://sourcegraph.com/-/editor?remote_url=git@github.com:sourcegraph/sourcegraph.git&branch=taras-yemets/add-allow-only-sourcegraph-extensions-setting&file=enterprise/cmd/frontend/internal/registry/allow_test.go&editor=VSCode&version=2.2.2&start_row=116&start_col=1&end_row=145&end_col=2&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands)).

The settings priority may need some clarification here. As ["allowRemoteExtensions"](https://sourcegraph.com/-/editor?remote_url=git@github.com:sourcegraph/sourcegraph.git&branch=taras-yemets/add-allow-only-sourcegraph-extensions-setting&file=schema/site.schema.json&editor=VSCode&version=2.2.2&start_row=1020&start_col=0&end_row=1026&end_col=10&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands) setting accepts extension ids, should it have higher priority than ["allowOnlySourcegraphExtensions"](https://sourcegraph.com/-/editor?remote_url=git@github.com:sourcegraph/sourcegraph.git&branch=taras-yemets/add-allow-only-sourcegraph-extensions-setting&file=schema/site.schema.json&editor=VSCode&version=2.2.2&start_row=1027&start_col=0&end_row=1031&end_col=9&utm_campaign=vscode-extension&utm_medium=direct_traffic&utm_source=vscode-extension&utm_content=vsce-commands) setting? So that the site admin could disable all non-Sourcegraph authored extensions by default, but allow a few 3-rd party extensions they trust?
For example, 
```
{
  "allowOnlySourcegraphAuthoredExtensions": true, // allow only Sourcegraph authored
  "allowRemoteExtensions": ["beyang/bash"]
} 
```
What do you think, @ryankscott?

2022-05-16 18:24 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
@ryankscott, I gave it another thought and now it seems that the suggested change by me would be confusing for admins. 
Now I think that if admin explicitly specifies certain extensions as allowed, it should take precedence over the "allowOnlySourcegraphAuthoredExtensions" setting. This will let admins specify a few Sourcegraph authored and a few third-party authored extensions. 
If allowed extensions are not specified, then we filter the extensions based on the "allowOnlySourcegraphAuthoredExtensions" setting.

2022-05-17 03:50 UTC, unknwon commented on enterprise/cmd/frontend/internal/registry/allow.go
> +		if allowedExtensionIDs == nil {
It does, that's why `len` is better 😁

2022-05-17 03:52 UTC, unknwon commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
Ah OK, thanks, on another look it is just a variable swap, I got caught on the variable name. LGTM!

2022-05-17 03:53 UTC, unknwon approved these changes
I am not very familiar with extensions backend, but the video LGTM.

2022-05-17 04:20 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
> +		if allowedExtensionIDs == nil {
I think I get why only `nil` check is here.
When allowed extensions are an empty slice it looks like [we want to return an empty slice too](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/cmd/frontend/internal/registry/allow_test.go?L82)(no remote extensions are allowed), but when it's `nil` we just [return all the extensions](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/cmd/frontend/internal/registry/allow_test.go?L79) (all are allowed).

But if the empty slice means that no remote extensions are allowed, I wonder how is it different from [the `false` value](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/schema/site.schema.json?L1022%3A11=).

2022-05-17 04:22 UTC, taras-yemets commented
@unknwon, thank you for the pairing session and review - both are super helpful 🙏🏻

2022-05-17 04:28 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
> +		if allowedExtensionIDs == nil {
> But if the empty slice means that no remote extensions are allowed, I wonder how is it different from [the false value](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/schema/site.schema.json?L1022%3A11=).

Ah, `false` is a possible value of the `remoteRegistry` field. Ignore this part, please. Sorry for the confusion.

2022-05-17 04:33 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
Updated this logic in https://github.com/sourcegraph/sourcegraph/pull/35054/commits/0f17b42711d3794fc7e9b1416bf7f804fd9b9d0a

2022-05-17 04:48 UTC, unknwon approved these changes

2022-05-17 04:48 UTC, unknwon commented on enterprise/cmd/frontend/internal/registry/allow.go
> +			allow := make(map[string]any)
```suggestion
			allow := make(map[string]struct{})
```

Not directly related to this PR but based on the actual usage, `any` is not actually needed, because `struct{}` would allocate zero space. Let's fix it since you touched the line 😁

2022-05-17 07:13 UTC, ryankscott commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
Just to clarify the behaviour so I understand.

1. `allowOnlySourcegraphAuthoredExtensions` is true and you've added extensions to `allowRemoteExtensions`
In this case you that Sourcegraph authored extensions **and** any extension in the `allowRemoteExtensions` setting will be available. Non-Sourcegraph extensions can be added to `allowRemoteExtensions` and they will be available.

2. `allowOnlySourcegraphAuthoredExtensions` is false and you've added extensions to `allowRemoteExtensions`
In this case only extensions in the `allowRemoteExtensions` setting will be available. 

If that's the case I guess we can think of these two settings as a filter, which logically combine with an OR. Is that correct?

Other questions:
- If we add new extensions are they automatically included in the `allowOnlySourcegraphAuthoredExtensions`?
- Is it possible that someone can name their extension `sourcegraph/*` e.g. `sourcegraph/RyansMaliciousExtension` and be included in that setting?

2022-05-17 07:39 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
> allowOnlySourcegraphAuthoredExtensions is true and you've added extensions to allowRemoteExtensions
In this case you that Sourcegraph authored extensions and any extension in the allowRemoteExtensions setting will be available. Non-Sourcegraph extensions can be added to allowRemoteExtensions and they will be available.

No, according to the current implementation, in this case, `allowOnlySourcegraphAuthoredExtensions` setting will be ignored and only extensions listed in `allowRemoteExtensions` field will be allowed ([field description](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@taras-yemets/add-allow-only-sourcegraph-extensions-setting/-/blob/schema/site.schema.json?L1029&utm_source=VSCode-2.2.2)). I made this change as I think that we need to leave admins a possibility to allow only _some_ of the Sourcegraph-authored extensions and maybe some third-party extensions. 

> allowOnlySourcegraphAuthoredExtensions is false and you've added extensions to allowRemoteExtensions
In this case only extensions in the allowRemoteExtensions setting will be available.

Yes, correct.

> If that's the case I guess we can think of these two settings as a filter, which logically combine with an OR. Is that correct?

Yes, the current OR works in this way: if `allowRemoteExtensions` is defined (even if empty), we allow only the mentioned extensions. If it's not defined, we look at the `allowOnlySourcegraphAuthoredExtensions` field. The [existing test cases](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@taras-yemets/add-allow-only-sourcegraph-extensions-setting/-/blob/enterprise/cmd/frontend/internal/registry/allow_test.go?L80-259) contain more config variations with the expected results.

> If we add new extensions are they automatically included in the allowOnlySourcegraphAuthoredExtensions?

Yes, as long as the remote registry field is not defined or points to the default remote registry URL (sourcegraph.com/.api/registry) and the publisher is `sourcegraph`. By the way, we probably should mention this registry condition in the field description. 

> Is it possible that someone can name their extension sourcegraph/* e.g. sourcegraph/RyansMaliciousExtension and be included in that setting?

I don't think so, as we [filter by the publisher name](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@taras-yemets/add-allow-only-sourcegraph-extensions-setting/-/blob/enterprise/cmd/frontend/internal/registry/allow.go?L85-87), not by the extension name. One can't create another `sourcegraph` account on sourcehraph.com to publish from and can't publish an extension under the other username than the currently logged in person (see screenshots below).

![image](https://user-images.githubusercontent.com/25318659/168755155-d6a4e78f-597f-4ee4-b815-eee3a0b91cc2.png)
![image](https://user-images.githubusercontent.com/25318659/168756288-824adb4b-a021-4807-883b-b684991d9cb9.png)

2022-05-17 07:46 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
Hm, maybe if the `remoteRegistry` is other than sourcegraph.com/.api/registry and `allowOnlySourcegraphAuthoredExtensions` is `true`, we should disallow all the extensions? What do you think, @ryankscott?

2022-05-17 07:49 UTC, ryankscott commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
>  I made this change as I think that we need to leave admins a possibility to allow only some of the Sourcegraph-authored extensions and maybe some third-party extensions.

Makes sense, this is a logical trade-off and easy to explain the hierarchy. Is there any easy way for someone to get all Sourcegraph authored extensions? I believe this is also a problem with [air-gapped environments](https://docs.google.com/document/d/1ymCMW9TBeirdqjTPx0zmYfNc5v-zYKCwLF2bxZJzXiA/edit#) as you need to first find then transfer them to your air-gapped environment.  

Either way, let's validate these rules with the CE team. I can put a message in their Slack channel. 

>I don't think so, as we [filter by the publisher name](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@taras-yemets/add-allow-only-sourcegraph-extensions-setting/-/blob/enterprise/cmd/frontend/internal/registry/allow.go?L85-87), not by the extension name. One can't create another sourcegraph account on sourcehraph.com to publish from and can't publish an extension under the other username than the currently logged in person (see screenshots below).

Great, thanks.

2022-05-17 07:53 UTC, taras-yemets commented on enterprise/cmd/frontend/internal/registry/allow.go
>  			if _, ok := allow[x.ExtensionID]; ok {
> Is there any easy way for someone to get all Sourcegraph authored extensions?

Yes, to have only Sourcegraph authored extensions on the /extensions page one should set `allowOnlySourcegraphAuthoredExtensions` to `true` and leave `remoteRegistry` and `allowRemoteExtensions` fields empty (not defined).

> let's validate these rules with the CE team

Great! Thank you! Could you please verify [this one](https://github.com/sourcegraph/sourcegraph/pull/35054#discussion_r874479677) too?

2022-05-17 12:02 UTC, vdavid approved these changes
Nice first Go code!!! 🎉

2022-05-17 12:02 UTC, vdavid commented on cmd/frontend/registry/api/extensions.go
> +		return nil, errors.Errorf("non Sourcegraph authored extensions are not allowed in site configuration")
Nit: in the term "non Sourcegraph authored", one or two dashes are missing. As I'm not a native English speaker, I'm unsure where, but it looks weird to me. I'd probably write "non-Sourcegraph authored". If this message is displayed to users, I'd double-check the punctuation with a native speaker. Grammarly also indicated that "the" is missing before the word "site", and I agree that it sounds better.

2022-05-17 12:16 UTC, taras-yemets commented on cmd/frontend/registry/api/extensions.go
> +		return nil, errors.Errorf("non Sourcegraph authored extensions are not allowed in site configuration")
Good catch! Thank you!

2022-05-17 16:20 UTC, eseliger approved these changes
took a brief look, code lgtm

2022-05-18 05:56 UTC, abeatrix approved these changes
Not familiar with Go but it works the same for me as shown on your video. Great job!

2022-05-18 05:56 UTC, abeatrix commented on schema/site.schema.json
> +        "allowOnlySourcegraphAuthoredExtensions": {
Based on the other configuration names, would it make more sense to rename it to something like "allowExternalAuthoredExtensions" or "disableNonSourcegraphAuthoredExtensions"? The one you have looks good though!

2022-05-18 09:59 UTC, ryankscott requested changes
LGTM with a couple of nits to be addressed.

2022-05-18 09:59 UTC, ryankscott commented on CHANGELOG.md
> +- Added site config parameter `extensions.allowOnlySourcegraphAuthoredExtensions`. [#35054](https://github.com/sourcegraph/sourcegraph/pull/35054)
We should add a description to what it does here e.g. When enabled only extensions authored by Sourcegraph will be able to be viewed and installed. For more information see XYZ

2022-05-18 09:59 UTC, ryankscott commented on cmd/frontend/registry/api/extensions.go
> +		return nil, errors.Errorf("Only Sourcegraph-authored extensions are allowed in the site configuration.")
Nit: Perhaps we flip this to say "Only extensions authored by Sourcegraph are allowed in this site configuration"

2022-05-18 10:11 UTC, ryankscott commented on schema/site.schema.json
> +        "allowOnlySourcegraphAuthoredExtensions": {
I can't see any conventions if we start settings with "allow" or "disable", nor if there's conventions around if we change this based on the default value. Is there any guidance from the engineering side here?

Otherwise perhaps we run this past our technical writing team?

2022-05-18 10:59 UTC, taras-yemets commented on CHANGELOG.md
> +- Added site config parameter `extensions.allowOnlySourcegraphAuthoredExtensions`. [#35054](https://github.com/sourcegraph/sourcegraph/pull/35054)
Updated docs and changelog https://github.com/sourcegraph/sourcegraph/pull/35054/commits/faf368b0b2dd62d5b70b8607a1acfb920684e276

2022-05-18 11:02 UTC, taras-yemets commented on schema/site.schema.json
> +        "allowOnlySourcegraphAuthoredExtensions": {
> Is there any guidance from the engineering side here?

No, to my knowledge.

> Otherwise perhaps we run this past our technical writing team?

Agree! Requested review from @jwayman.

2022-05-18 14:55 UTC, ryankscott commented on doc/admin/extensions/index.md
> +On Sourcegraph Enterprise, you can restrict users to using only Sourcegraph-autored extensions by setting [`extensions.allowOnlySourcegraphAuthoredExtensions`](../config/site_config.md) to `true` in
Minor typo: s/autored/authored

2022-05-19 10:56 UTC, ryankscott approved these changes
Pending feedback from Jeff. Otherwise LGTM

2022-05-23 08:20 UTC, merged