codeintel: removing bloom filters
sourcegraph/sourcegraph pull request #35203
Opened 2022-05-10 00:39 UTC by Numbers88s

- Removed the uses of `DEBUG_PRECISE_CODE_INTEL_BLOOM_FILTER_BAIL_OUT`
- Simplified the resulting code and eliminated any paths that were now unreachable. 
- Removed the `lib/codeintel/bloomfilter` package 
- Removed the `filter` column on the lsif_references table

## Test plan

#32908 disabled the bloom filters from the query path. We haven't seen a performance degradation in two months so we can assume it's safe to delete entirely.

![](https://media.giphy.com/media/26tOXgoz0WNQhwb04/giphy.gif)

2022-05-12 12:51 UTC, efritz requested changes

2022-05-12 12:52 UTC, efritz commented on migrations/frontend/1652143849/metadata.yaml
> +name: drop_filter_column_from_lsif_references_table
This name is out of date now

2022-05-12 16:02 UTC, efritz approved these changes
Main dry run passed. Two comments about things that might not need changing here.

2022-05-13 01:13 UTC, Numbers88s commented on internal/cmd/tracking-issue/testdata/fixtures.json
> +      "Body": "### Plan\r\n\r\nThis sprint covers 2021-02-01 through 2021-01-12.\r\n\r\n### Availability\r\n\r\nIf you have planned unavailability this iteration (e.g., vacation), you can note that h
Oh it references the function `ReferenceIDsAndFilters` which change its name to `ReferenceIDs`. That's what I changed in this line. Should I leave it as `ReferenceIDsAndFilters`?

2022-05-13 01:25 UTC, efritz commented on internal/cmd/tracking-issue/testdata/fixtures.json
> +      "Body": "### Plan\r\n\r\nThis sprint covers 2021-02-01 through 2021-01-12.\r\n\r\n### Availability\r\n\r\nIf you have planned unavailability this iteration (e.g., vacation), you can note that h
Yeah this is just test data for the tracking issue bot.

2022-05-13 01:48 UTC, Numbers88s commented on internal/cmd/tracking-issue/testdata/fixtures.json
> +      "Body": "### Plan\r\n\r\nThis sprint covers 2021-02-01 through 2021-01-12.\r\n\r\n### Availability\r\n\r\nIf you have planned unavailability this iteration (e.g., vacation), you can note that h
Oh gotcha, changed it back.

2022-05-13 15:38 UTC, merged