codeintel: create CTA for users to try out new reference panel
sourcegraph/sourcegraph pull request #35333
Opened 2022-05-11 21:00 UTC by Numbers88s

Adds CTA to reference panel for users to try out the new version.

## Test plan
Manually tested. 

![](https://media.giphy.com/media/7MZ0v9KynmiSA/giphy.gif)

2022-05-12 12:54 UTC, efritz commented on client/branded/src/components/panel/views/ReferencePanelCta.tsx
> +export const ReferencePanelCta: React.FunctionComponent = () => {
Can we get a screenshot of this component on the old ref panel for the PR description? (Do it before you set it non-draft but don't rush if we're still refactoring)

2022-05-12 12:54 UTC, efritz commented on client/branded/src/components/panel/TabbedPanelContent.tsx
> +        redesignedEnabled
```suggestion
        redesignedEnabled === true
```

For consistency, we do it this way in BlobPanel.

2022-05-12 12:56 UTC, efritz requested changes
Things left to do:

- [ ] Create "clean" issue for users
- [ ] Add a similar dismissible alert on the **new** ref panel that links to the issue for feedback
- [ ] Have a way to transfer coolCodeIntel=true to this new temporary setting (this might only affect sg org on cloud, so maybe we just do this part by hand).

2022-05-12 15:57 UTC, Numbers88s commented on client/branded/src/components/panel/views/ReferencePanelCta.tsx
> +export const ReferencePanelCta: React.FunctionComponent = () => {
Totally. Done ✅

2022-05-17 20:14 UTC, rrhyne commented
On the "enable the feature" banner, can we change the dismiss to the close icon?  That is our standard pattern.

2022-05-18 22:04 UTC, efritz commented
@rrhyne Look good?

![Screen Shot 2022-05-18 at 5 03 16 PM](https://user-images.githubusercontent.com/103087/169163442-30fa4743-a680-4d45-b61e-144457dd3831.png)

![Screen Shot 2022-05-18 at 5 03 26 PM](https://user-images.githubusercontent.com/103087/169163445-ea331ff8-3575-4ab3-ac38-4921730c6d58.png)

2022-05-18 22:06 UTC, efritz commented
Blocked by https://github.com/sourcegraph/analytics/pull/452.

2022-05-19 09:17 UTC, mrnugget approved these changes

2022-05-19 22:50 UTC, efritz approved these changes

2022-05-19 22:50 UTC, merged