Revert "ci: re-enable cache and use plugin fork"
sourcegraph/sourcegraph pull request #35332
Opened 2022-05-11 20:54 UTC by bobheadxi

Reverts sourcegraph/sourcegraph#35310

2022-05-11 20:54 UTC, michaellzc approved these changes

2022-05-11 21:19 UTC, davejrt requested changes
The issue here is not with the yarn cache, it's the `tar` commands in `asdf-install.sh` which I have changed to bsdtar [here](https://github.com/sourcegraph/sourcegraph/pull/35334)

2022-05-12 05:33 UTC, unknwon approved these changes
I approve when I see a revert.

2022-05-12 05:34 UTC, closed without merging

2022-05-12 05:34 UTC, bobheadxi commented
hahaha thanks, but it's no longer needed!