wildcard: Typography export refactor
sourcegraph/sourcegraph pull request #35345
Opened 2022-05-12 03:45 UTC by gitstart-sourcegraph

## Description
1. Added support for relative import of `Typography` components, within the wildcard package, to prevent cyclic import graphs.
2. Added support for binding more props to Header and Text components. This would help to maintain current usage/ prop binding of native header and text elements after migration.

## Ref
https://github.com/sourcegraph/sourcegraph/issues/27677

## Test plan
Check use cases of wildcard's `Typography.xxx` components, ensure they can still be imported and used as previously used.

2022-05-12 03:55 UTC, valerybugakov requested changes

2022-05-12 03:55 UTC, valerybugakov commented on client/wildcard/src/components/index.ts
> +export { Code, H1, H2, H3, H4, H5, H6, Label, Text, Typography } from './Typography'
Let's remove `Code, H1, H2, H3, H4, H5, H6, Label, Text` exports to ensure that they are used consistently through the `Typography` object.

2022-05-12 04:11 UTC, valerybugakov commented on client/wildcard/src/components/index.ts
> +export { Code, H1, H2, H3, H4, H5, H6, Label, Text, Typography } from './Typography'
We should be able to do it after merging of all other heading-migration PRs.

2022-05-13 03:09 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/index.ts
> +export { Code, H1, H2, H3, H4, H5, H6, Label, Text, Typography } from './Typography'
@valerybugakov We update PR after merged the heading migration tickets. Could you take a look?

2022-05-13 10:25 UTC, merged