Add check to make sure remote and local release branch are synced
sourcegraph/sourcegraph pull request #35360
Opened 2022-05-12 11:46 UTC by marsblkm

- move branch check function to `ensureBranchUpToDate()` to make sure it can be done on any branch
- accomodate existing `ensureMainBranchUpToDate()`
- make sure release branch can be checked as well
- a new pr to replicate https://github.com/sourcegraph/sourcegraph/pull/34200

Solve: https://github.com/sourcegraph/sourcegraph/issues/32783

## Test plan
@marsblkm tested locally and **manually** by doing the following:
1. Checkout to branch `3.39` and randomly commit something (to simulate the scenario)
2. Checkout to `main`
3. Merge `jm/check-local-and-remote-release-branch` into `main`.
4. Set up dry run mode and execute `yarn release release:create-candidate final`

<img width="703" alt="image" src="https://user-images.githubusercontent.com/11640534/164342889-2cf253b8-3346-4334-a951-ca97c984731f.png">

2022-05-12 11:46 UTC, marsblkm commented
@keegancsmith

2022-05-12 13:55 UTC, keegancsmith requested changes

2022-05-12 13:55 UTC, keegancsmith commented on dev/release/src/release.ts
> -
you shouldn't be deleting these extra newlines. This comment applies all over this file. Don't delete the newlines inside of multiline strings.

2022-05-12 14:12 UTC, marsblkm commented on dev/release/src/release.ts
> -
Just got that reverted. Actually those changes are introduced by running `yarn prettier`...

2022-05-13 07:19 UTC, keegancsmith commented
@marsblkm I'm not sure what is up with your prettier such that it edits newlines in strings, but I ran the one we pin in sourcegraph since it needed formatting. I just force pushed the result onto your branch, which also has the benefit of triggering CI with my privilages. Lets hope this gets us over the finish line and can merge this :)

2022-05-13 07:21 UTC, keegancsmith approved these changes

2022-05-13 07:21 UTC, keegancsmith commented on dev/release/src/release.ts
> +            ensureReleaseBranchUpToDate(branch)
cc @sourcegraph/delivery does this make sense? Either way gonna approve and ship. We can follow-up if this looks wrong.

2022-05-13 13:13 UTC, marsblkm commented
Not sure what happened here but it seems like it needs manual merge...?

2022-05-16 06:51 UTC, keegancsmith commented
I'm following up on https://github.com/sourcegraph/sourcegraph/issues/32427 will have this merged soon.

2022-05-18 21:55 UTC, merged