[SG-35282]: Wildcard V2: Apply <Input /> Codemod on `client/web/enterprise`
sourcegraph/sourcegraph pull request #35414
Opened 2022-05-13 10:16 UTC by gitstart-sourcegraph

## Problem statement

Migration is required to update our code to use the `<Input />` Wildcard component.
See [parent issue](https://github.com/sourcegraph/sourcegraph/issues/27722) for more context. 

## Success criteria

All occurrences of the `<input />` element are replaced with the `<Input />` Wildcard component.

## Implementation details

- Rename the `Input` component `variant` prop to `size`.
- Use the `Input` codemod created [here](https://github.com/sourcegraph/codemod/pull/94) to speed up the migration.

## Refs
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/35282)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-35282)
[Demo](https://www.loom.com/share/8d317fd7665040fb8dabd851b43b3efa)

Test Plan
- All `<input/>` elements are migrated to `<Input/>` wildcard component.
- No UI diff available

2022-05-26 07:32 UTC, valerybugakov requested changes

2022-05-26 07:32 UTC, valerybugakov commented on client/web/src/enterprise/search/stats/SearchStatsPage.tsx
> +                    inputSymbol={
Move button our of the `inputSymbol`

2022-05-26 07:32 UTC, valerybugakov commented on client/web/src/enterprise/insights/components/form/form-radio-input/FormRadioInput.tsx
> +            <Input formControl={false} type="radio" {...otherProps} />
Let's remove the `formControl` prop from the `Input` component and ignore the eslint rule here.

2022-05-27 07:52 UTC, valerybugakov requested changes

2022-05-27 07:52 UTC, valerybugakov commented on client/web/src/enterprise/codeintel/configuration/components/ReposMatchingPatternList.tsx
> -                    <div className={styles.grid}>
Trying to understand what the reason for changing the layout here was?

2022-05-27 08:22 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/codeintel/configuration/components/ReposMatchingPatternList.tsx
> -                    <div className={styles.grid}>
Was changed initially to support usage of `inputSymbol` here, safe to revert now...

2022-05-27 13:03 UTC, valerybugakov approved these changes
Thanks!

2022-05-27 13:56 UTC, merged