[SG-35283]: Wildcard V2: Apply <Input /> Codemod `auth` `components` `extensions` `marketing` `notebooks`
sourcegraph/sourcegraph pull request #35526
Opened 2022-05-17 05:59 UTC by gitstart-sourcegraph

## Problem statement

Migration is required to update our code to use the `<Input />` Wildcard component.
See [parent issue](https://github.com/sourcegraph/sourcegraph/issues/27722) for more context. 

## Success criteria

All occurrences of the `<input />` element are replaced with the `<Input />` Wildcard component.

## Implementation details

- Rename the `Input` component `variant` prop to `size`.
- Use the `Input` codemod created [here](https://github.com/sourcegraph/codemod/pull/94) to speed up the migration.

## Refs
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/35283)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-35283)

## Affected Packages includes
- `client/web/src/auth`
- `client/web/src/components`
- `client/web/src/extensions`
- `client/web/src/marketing`
- `client/web/src/notebooks`

Test Plan
- All `<input/>` elements from the mentioned folders are migrated to `<Input/>` wildcard component.
- No UI diff available

2022-05-30 04:55 UTC, valerybugakov requested changes
Let's remove all the redundant changes from PRs before requesting the review.

2022-05-30 05:06 UTC, valerybugakov requested changes
Let's fix the Chromatic diff shown for the [CollaboratorsPanel](https://www.chromatic.com/component?appId=5f0f381c0e50750022dc6bf7&csfId=web-search-panels-collaboratorspanel&specName=CollaboratorsPanel&buildNumber=43993) story. It seems that input borders shouldn't be rounded on the right side.

2022-05-30 05:06 UTC, valerybugakov commented on client/web/src/notebooks/notebook/NotebookCommandPaletteInput.module.scss
> +    --input-placeholder-color: #757575;
Could you share the reasoning behind this change?

2022-05-30 05:06 UTC, valerybugakov commented on client/wildcard/src/components/Form/Input/Input.tsx
> +                        status === InputStatus.loading && styles.inputLoading,
Let's merge the `main` branch into this PR.

2022-05-30 05:06 UTC, valerybugakov commented on client/web/src/notebooks/listPage/ImportMarkdownNotebookButton.module.scss
> +    display: none !important;
Do we need `!important` here?

2022-05-30 05:06 UTC, valerybugakov commented on client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.tsx
> +                    className={isLineRangeValid === false ? 'mb-0' : 'mb-0'}
Should we convert it to `mb-0` without ternary then?

2022-05-30 05:06 UTC, valerybugakov commented on client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.tsx
> +                            <span className={styles.inputError}>
Is this `className` required only to change the error font-size from the default one to the custom one? Does it make sense to keep it consistent with every other `Input` error in the application?

2022-05-30 05:28 UTC, gitstart-sourcegraph commented
Hey @valerybugakov apologies this PR is still in progress, needed to mark it as ready for review in order to get chromatic review CI. Would update requested changes and request another review once ready.

2022-05-30 05:55 UTC, gitstart-sourcegraph commented on client/web/src/notebooks/listPage/ImportMarkdownNotebookButton.module.scss
> +    display: none !important;
it's needed to override `d-flex` (has `important`) property applied internally (in `Input` component) on `LoaderInput`.

2022-05-30 05:57 UTC, gitstart-sourcegraph commented on client/web/src/notebooks/blocks/file/NotebookFileBlockInputs.tsx
> +                            <span className={styles.inputError}>
Yea makes sense

2022-05-30 06:12 UTC, gitstart-sourcegraph commented on client/web/src/notebooks/notebook/NotebookCommandPaletteInput.module.scss
> +    --input-placeholder-color: #757575;
This was added to resolve UI diff on placeholder input color here.

Default (Before updating placeholder color with this change)
<img width="1068" alt="Screenshot 2022-05-30 at 7 05 28 AM" src="https://user-images.githubusercontent.com/89894075/170928057-89c6774a-d267-4c43-bad5-f59e6bb7cbe9.png">

Expected (Existing placeholder color)
<img width="1068" alt="Screenshot 2022-05-30 at 7 02 11 AM" src="https://user-images.githubusercontent.com/89894075/170928262-43853107-daf2-468b-adf3-794231294e59.png">

WDYT?

2022-05-30 07:32 UTC, valerybugakov commented
@gitstart-sourcegraph, got it! Makes sense. We can convert back to draft after triggering the Chromatic build.

2022-05-30 10:53 UTC, valerybugakov commented on client/web/src/notebooks/notebook/NotebookCommandPaletteInput.module.scss
> +    --input-placeholder-color: #757575;
I think we can keep the default color here for consistency and better contrast reasons.

2022-05-30 10:58 UTC, valerybugakov requested changes

2022-05-30 10:58 UTC, valerybugakov commented on .github/workflows/lsif-typescript.yml
> +name: lsif-typescript
Should we revert this change?

2022-05-30 10:58 UTC, valerybugakov commented on .github/workflows/reviewdog.yml
> +name: reviewdog
Should we revert this change?

2022-05-30 10:58 UTC, valerybugakov commented on client/web/src/notebooks/listPage/ImportMarkdownNotebookButton.module.scss
> +    display: none !important; // Overrides d-flex css class on Input;
Let's convert the `d-flex` class in the `Input` component to a CSS module class. Then the `!important` here will become redundant.

2022-05-31 05:37 UTC, valerybugakov approved these changes
Thanks!

2022-05-31 05:49 UTC, merged