[SG-35284] Wildcard V2: Apply <Input /> Codemod client/web/org client/web/repo client/web/savedSearches client/web/site-admin client/web/user
sourcegraph/sourcegraph pull request #35534
Opened 2022-05-17 10:08 UTC by gitstart-sourcegraph

## Problem statement

Migration is required to update our code to use the `<Input />` Wildcard component.
See [parent issue](https://github.com/sourcegraph/sourcegraph/issues/27722) for more context. 

## Success criteria

All occurrences of the `<input />` element are replaced with the `<Input />` Wildcard component.

## Implementation details

- Rename the `Input` component `variant` prop to `size`.
- Use the `Input` codemod created [here](https://github.com/sourcegraph/codemod/pull/94) to speed up the migration.

## Refs
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/35284)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-35284)

Test Plan
- All `<input/>` elements are migrated to `<Input/>` wildcard component.
- No UI diff available

2022-06-02 07:59 UTC, gitstart-sourcegraph commented on client/web/src/components/FilteredConnection/ui/ConnectionForm.module.scss
> +.input {
```suggestion
}

.input {
```

2022-06-02 08:02 UTC, gitstart-sourcegraph commented on client/web/src/components/FilteredConnection/ui/ConnectionForm.tsx
>                          type="search"
Added this to preserve style for use cases where full width input is needed. Used `w-auto` to maintain, use cases where non full width input is used.

2022-06-02 12:52 UTC, valerybugakov requested changes

2022-06-02 12:52 UTC, valerybugakov commented on client/web/src/repo/settings/RepoSettingsMirrorPage.tsx
> +                                        <Icon as={LockIcon} /> Only visible to site admins
What's the reason for removing accessibility attributes here?

2022-06-03 06:20 UTC, valerybugakov approved these changes

2022-06-03 07:22 UTC, merged