[SG-33258]: Wildcard `<Input />` migration
sourcegraph/sourcegraph pull request #35579
Opened 2022-05-17 17:39 UTC by gitstart-sourcegraph

## Descripton
In order to preserve layout needed for some css rules such as `form-group > .form-control`, to be appropriately applied on the wildcard `Input` component, the modification was made, to separate the support for `LoaderInput` from the default Input component

## Ref
[SG Parent Issue](https://github.com/sourcegraph/sourcegraph/issues/33258)

## Test Plan
View components on storybook to ensure expected behavior

2022-05-17 18:41 UTC, gitstart-sourcegraph commented
Hi @valerybugakov 
Help take a look at changes here, for updating the layout of `Input` component as discussed.
WDYT about usage of `Input` and `FormInput`, with regards to how intuitive their use cases would be to component users.

2022-05-19 02:18 UTC, valerybugakov requested changes
See the comment on the `FormInput` implementation.

2022-05-19 02:20 UTC, valerybugakov commented on client/wildcard/src/components/Form/Input/FormInput.tsx
> +export enum FormInputStatus {
The `FormInputStatus` should extend the `InputStatus` with the `loading` property.

2022-05-23 08:18 UTC, gitstart-sourcegraph commented
Paused since this implementation might not be very intuitive for component users.
Would be re-visited after migration efforts in #35579

2022-05-23 08:18 UTC, closed without merging