[SG-35349] Migrate to use `@stripe/react-stripe-js` from `react-stripe-elements`
sourcegraph/sourcegraph pull request #35610
Opened 2022-05-18 03:08 UTC by gitstart-sourcegraph

## Description

- Migrating from `react-stripe-elements` to `@stripe/react-stripe-js` + `@stripe/stripe-js`

## Refs

- [Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-35349)
- [Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/35349)

## Test plan

- Update unit test
- Confirm payment functionality still working correctly

2022-05-18 03:17 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/user/productSubscriptions/__snapshots__/ProductSubscriptionForm.test.tsx.snap
> +                Only absolute URLs are supported
@valerybugakov could you please take a look at this spec PR and this error?

1. I think it's from using `queryGraphQL` in  `client/web/src/enterprise/dotcom/productPlans/ProductPlanFormControl.tsx` and I couldn't find the way we are using to mock graphql queries in `queryGraphQL`. And as I know we are migrating to use `useMutataion` and `useQuery`, should we do it in `ProductPlanFormControl` component.
2. Could we have an instruction how to test stripe in dev? I can run app locally with `SOURCEGRAPH_API_URL=https://sourcegraph.com SOURCEGRAPHDOTCOM_MODE=true` to make Stripe card element shows up but couldn't make a completed payment process.

2022-05-19 07:00 UTC, valerybugakov commented on client/web/src/enterprise/user/productSubscriptions/__snapshots__/ProductSubscriptionForm.test.tsx.snap
> +                Only absolute URLs are supported
1. Let's mock `ProductPlanFormControl` or `_queryProductPlans` to fix the test error.
2. Use `sg start dotcom` to start the local instance of the Sourcegraph application. Provide Strip test API keys via environment variables. It should be sufficient to complete the payment process in the dev environment.

2022-05-19 11:27 UTC, valerybugakov requested changes
Marking as reviewed until the test error is fixed, along with other things discussed in Slack.

2022-05-21 05:33 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/user/productSubscriptions/__snapshots__/ProductSubscriptionForm.test.tsx.snap
> +                Only absolute URLs are supported
Thanks @valerybugakov I added back required mocks from old code version and synced some changes from Quinn PR. Unfortunately since we don't have `dev-private` repo access, we couldn't run `sg start dotcom`

2022-05-25 01:48 UTC, valerybugakov approved these changes
Tested locally. LGTM!

2022-05-25 01:49 UTC, valerybugakov commented on client/web/src/enterprise/user/productSubscriptions/__snapshots__/ProductSubscriptionForm.test.tsx.snap
> +                Only absolute URLs are supported
I'm discussing the possibility of adding you to the `dev-private` repo with the security team. 👍

2022-05-25 02:25 UTC, merged