CI: Push CI metrics to OKAYHQ
sourcegraph/sourcegraph pull request #35666
Opened 2022-05-18 20:20 UTC by davejrt

Pushes total count, incident duration and flake count to okayHQ. 

Data has been back loaded to the 15th of May so when this runs on Sunday 22 it will continue to load data for this month. 

Follow up: update [history github action](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/.github/workflows/buildchecker-history.yml) with okay token to start uploading data. 

## Test plan

Works locally, and have verfied data is being receied with Tomas from OKAYHQ

2022-05-18 20:53 UTC, bobheadxi requested changes
> Data has been back loaded to the 15th of May so when this runs on Sunday 22 it will continue to load data for this month.

🥇

2022-05-18 20:53 UTC, bobheadxi commented on dev/buildchecker/main.go
> +	"github.com/sourcegraph/sourcegraph/dev/okay"
I think this should be further down with the other sourcegraph imports!

2022-05-18 20:53 UTC, bobheadxi commented on dev/buildchecker/main.go
> +			eventTime, _ := time.Parse("2006-01-02T00:00:00Z", recordDateString+"T00:00:00Z")
Might want to handle the error here regardless just in case

2022-05-18 20:53 UTC, bobheadxi commented on dev/buildchecker/main.go
> +						Value: float64(incidents[recordDateString] * 60000),
```suggestion
						// Convert minutes to ms
						Value: float64(incidents[recordDateString] * 60000),
```

2022-05-18 20:53 UTC, bobheadxi commented on dev/buildchecker/main.go
> +					},
There are constructors for all of these: https://sourcegraph.com/github.com/sourcegraph/sourcegraph-incremental-indexing-fork@5cd8e8c8af6b913d37dcbaeefde291e4defa8fe5/-/blob/dev/okay/metric.go?L16-26

2022-05-18 20:53 UTC, bobheadxi commented on dev/buildchecker/main.go
> +				log.Fatal("okay.NewClient: ", err)
```suggestion
				log.Fatal("okay.Push: ", err.Error())
```

2022-05-18 20:53 UTC, bobheadxi commented on dev/buildchecker/main.go
> +		okayCli.Flush()
```suggestion
		if err := okayCli.Flush(); err != nil {
			log.Fatal("okay.Flush: ", err.Error())
		}
```

2022-05-19 08:01 UTC, jhchabran approved these changes

2022-05-19 08:01 UTC, jhchabran commented on dev/buildchecker/main.go
> +					"unique_key":   eventTime.Format(time.RFC3339),
nit: it may be more logical to name the unique key `"ts"`, the example with `unique_key` in the other code is named like that because it was an aggregation of multiple fields + some labels.

2022-05-19 11:52 UTC, davejrt commented on dev/buildchecker/main.go
> +				UniqueKey: []string{
@jhchabran this is what you were suggesting right?

2022-05-19 12:14 UTC, jhchabran commented on dev/buildchecker/main.go
> +				UniqueKey: []string{
Ah no, that's incorrect, OkayHQ API will complain about this. I was suggesting the following: 

```go
okay.Event{
  UniqueKey: []string{"ts"}, 
  Properties: map[string]string{
    "ts": eventTime.Format(time.RFC3339),
  },
```

I should have written the example first, the unique key thing is a bit ambiguous in its name (I think they should have named it `UniqueKeyName` and that would be a good small change to do on the lib if you're up for it 😊 )

2022-05-19 15:08 UTC, davejrt commented on dev/buildchecker/main.go
> +				UniqueKey: []string{
Right! Thanks for clarifying, it has been somewhat confusing working out this uniquekey thing

2022-05-19 16:20 UTC, bobheadxi reviewed
Mostly nits!

2022-05-19 16:20 UTC, bobheadxi commented on dev/buildchecker/main.go
> +
```suggestion
```

2022-05-19 16:20 UTC, bobheadxi commented on dev/buildchecker/main.go
> +
```suggestion
```

2022-05-19 16:20 UTC, bobheadxi commented on dev/buildchecker/main.go
>  	log.Println("done!")
This message might not make sense without any context (there's no corresponding start message, like "Pushing to OkayHQ...")

2022-05-19 16:20 UTC, bobheadxi commented on dev/buildchecker/main.go
> +				"incidentDuration": okay.Duration(time.Duration(time.Duration(incidents[recordDateString]) * time.Minute)),
```suggestion
				"incidentDuration": okay.Duration(time.Duration(incidents[recordDateString]) * time.Minute),
```

I'm _think_ this works without double-casting it 🤔

2022-05-19 16:20 UTC, bobheadxi commented on dev/buildchecker/main.go
> +				UniqueKey: []string{
Yeah the unique key API is a bit clunky, though I suppose it's flexible

2022-05-19 16:20 UTC, bobheadxi commented
@davejrt make sure to attach this PR to the corresponding issue 👍

2022-05-19 20:17 UTC, merged