[SG-35514] logging(gitstart): migrate gitserver logging
sourcegraph/sourcegraph pull request #35859
Opened 2022-05-23 11:27 UTC by gitstart-sourcegraph

## Description

The main existing logger usage to replace are calls to log15.

## Test plan

All ~125 occurrences of log15 calls in files that appear related to gitserver are replaced with logging calls to an appropriately scoped log.Logger instance, e.g. ones held by the parent struct:

https://sourcegraph.com/search?q=context:global+r:%5Egithub%5C.com/sourcegraph/sourcegraph%24++content:%22log15.%22+lang:go+f:gitserver&patternType=literal

Green CI builds.

## Refs

- [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/35514)
- [GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-35514)

2022-05-24 14:51 UTC, keegancsmith commented
I'm unaware of best practices we are developing around the naming of the loggers, so adding @bobheadxi to comment on this PR in case we have some :)

2022-05-24 14:59 UTC, keegancsmith requested changes
neat :) Got a few inline comments that require changes. Sorry couldn't finish the review before I had to go, so partial review.

2022-05-24 14:59 UTC, keegancsmith commented on cmd/gitserver/main.go
> +		logger.Warn(fmt.Sprintf("found zero gitserver instance, trying again in %s", backoff))
use structural logging here

2022-05-24 14:59 UTC, keegancsmith commented on cmd/gitserver/server/cleanup.go
> +		s.Log.Info("re-cloning expired repo", log.String("repo", string(repo)), log.String("cloned", recloneTime.String()), log.String("reason", reason))
there is `log.Time` for the recloneTime field.

2022-05-24 14:59 UTC, keegancsmith commented on cmd/gitserver/server/cleanup.go
> +			log.String("repo", d.Path()),
```suggestion
			log.String("repo", string(d)),
```

2022-05-25 10:25 UTC, closed without merging

2022-05-28 03:01 UTC, bobheadxi commented on cmd/gitserver/server/cleanup.go
> +		s.Log.Error("cleanup: error iterating over repositories", log.Error(err))
The appropriate way to do this would probably be to create a logger scoped under "cleanup" - i'll double check the new PR next week to make sure we address this!

2022-05-28 03:02 UTC, bobheadxi commented
Thanks for the feedback on this PR @keegancsmith ! I just saw this PR, Ill make sure your comments are applied in the new PR (https://github.com/sourcegraph/sourcegraph/pull/36005) next week (i'm not sure why there's 2)