wip
sourcegraph/sourcegraph pull request #35892
Opened 2022-05-23 19:01 UTC by Numbers88s

Continue moving functionality to new service infrastructure.

## Test plan
Tested locally to ensure job is still registered.

2022-05-24 22:03 UTC, efritz commented on internal/codeintel/uploads/background/cleanup/config.go
> +	c.CommitResolverMaximumCommitLag = c.GetInterval("CODEINTEL_UPLOAD_COMMIT_RESOLVER_MAXIMUM_COMMIT_LAG", "0s", "The maximum acceptable delay between accepting an upload and its commit becoming resolv
Can we leave this one as `PRECISE_CODE_INTEL_COMMIT_RESOLVER_MAXIMUM_COMMIT_LAG` as it was added by customer request just so we can (for now) avoid a change notice and have them alerted?

Please put a TODO to rename the variable to match the service, and we can build an extension on top of the base-env package here to do fallback/aliases so it can be more uniform while also being backcompat.

2022-05-24 22:03 UTC, efritz commented on internal/codeintel/uploads/background/cleanup/janitor.go
> +	j.HandleAuditLog(ctx)
Can we collect/report errors from these functions?

2022-05-24 22:04 UTC, efritz commented on internal/codeintel/uploads/background/cleanup/observability.go
> +		// TODO - rename things here similar to this
I'll handle these two pre-merge.

2022-05-24 22:08 UTC, efritz commented
- [ ] Wait for #35972 to land first
- [ ] Add initial service dashboards now that there production functionality

2022-05-25 02:42 UTC, Numbers88s commented on internal/codeintel/uploads/background/cleanup/janitor.go
> +	j.HandleAuditLog(ctx)
whoops. done ✅

2022-05-25 02:43 UTC, Numbers88s commented on internal/codeintel/uploads/background/cleanup/config.go
> +	c.CommitResolverMaximumCommitLag = c.GetInterval("CODEINTEL_UPLOAD_COMMIT_RESOLVER_MAXIMUM_COMMIT_LAG", "0s", "The maximum acceptable delay between accepting an upload and its commit becoming resolv
Absolutely. Done ✅

2022-05-26 00:03 UTC, efritz requested changes

2022-05-26 00:07 UTC, Numbers88s commented on internal/codeintel/uploads/background/cleanup/janitor.go
> +	// Reconciliation and denormalization
Is there an example of how we handle/collect multierror?

2022-05-26 00:24 UTC, efritz commented on internal/codeintel/uploads/background/cleanup/janitor.go
> +	// Reconciliation and denormalization
[SIR YOU ARE ON THE CODE INTEL TEAM](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4f79e96c577fa574191445d1a796c314bb844650/-/blob/lib/errors/errors.go?L44:6#tab=references)

2022-05-26 00:25 UTC, Numbers88s commented on internal/codeintel/uploads/background/cleanup/janitor.go
> +	// Reconciliation and denormalization
Lol. I knew someone (probably you) had written it already.

2022-05-26 01:58 UTC, Numbers88s commented on internal/codeintel/uploads/background/cleanup/janitor.go
>  	// To be implemented in https://github.com/sourcegraph/sourcegraph/issues/33375
Removed ✅

2022-05-26 02:00 UTC, Numbers88s commented on internal/codeintel/uploads/background/cleanup/janitor.go
> +	// Reconciliation and denormalization
Found one I like better 😄 ... using code intel 😎

2022-05-26 13:43 UTC, merged