Move filed from `shared` package to `search-ui` package
sourcegraph/sourcegraph pull request #35903
Opened 2022-05-23 21:43 UTC by limitedmage

Move file related to search results to the `search-ui` package.

## Test plan

There should be no major code changes here, just import changes. All tests and CI should pass.

2022-05-23 22:39 UTC, abeatrix requested changes
https://github.com/sourcegraph/sourcegraph/blob/1c7eb1f044d6acb5b54a9e759530224d03aa7fa4/client/vscode/src/webview/search-panel/alias/FileMatchChildren.tsx#L19

`import { displayRepoName } from '@sourcegraph/shared/src/components/RepoLink'` ?

I thinks other than the two issues I've brought up, the  rest of the changes should not break what we have for the VS Code extension, thanks!

2022-05-23 22:39 UTC, abeatrix commented on client/search-ui/src/components/index.ts
> +
```suggestion
import styles from './FileMatchChildren.module.scss'
export { styles as FileMatchChildrenStyles }
```

The VS Code extension is using the FileMatchChildren.module.scss [here](https://github.com/sourcegraph/sourcegraph/blob/1c7eb1f044d6acb5b54a9e759530224d03aa7fa4/client/vscode/src/webview/search-panel/alias/FileMatchChildren.tsx#L19), is it possible to export it as well?

2022-05-23 22:59 UTC, limitedmage commented
@abeatrix  Thanks for the review! Addressed your comments.

2022-05-24 06:23 UTC, vdavid approved these changes
JetBrains works well!
Thanks for tidying up, it's a lot nicer now! <3

2022-05-24 17:30 UTC, merged