[SG-33302.12] Upgrade to the latest react version and migrate to the new root API
sourcegraph/sourcegraph pull request #36045
Opened 2022-05-25 18:10 UTC by gitstart-sourcegraph

## Description

Upgrade to the latest react version and migrate to the new root API, on all packages

## Test plan

Make sure all checks are passed in CI and app runs as expected

## Refs

- [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/33302)
- [GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-33302)

2022-05-26 18:28 UTC, gitstart-sourcegraph commented
Some packages need to be upgraded  to a supported React 18 version

react-visibility-sensor
react-scroll-manager
@types/recharts
@react-aria/live-announcer

2022-06-08 05:32 UTC, gitstart-sourcegraph commented
@valerybugakov There are still remaining tests that I have tried but couldn't fix them (actually it's passed locally). Could you take a look?

2022-06-23 06:11 UTC, valerybugakov reviewed
I'm looking into integration test failures, thanks for the heads up!

In the meantime, could you ensure that we don't have React warnings related to unknown props on DOM elements in integration tests output: `React does not recognize the '%s' prop on a DOM element`? We can do it in a separate PR if the problem exists on the `main` branch.

2022-07-12 03:51 UTC, gitstart-sourcegraph commented
@valerybugakov Could you help to check what are wrong in `buildkite/sourcegraph` pipeline? the `buildkite/sourcegraph-contractors ` is fine after fixes for remaining tests + new components

2022-07-12 05:49 UTC, valerybugakov reviewed
Thanks, it feels that we're pretty close to the finish line! 🚀

2022-07-12 05:49 UTC, valerybugakov commented on client/wildcard/src/hooks/useObservable.ts
> +    const handleError = useCallback((error: any) => {
Would `unknown` work here as well? It's a preferable way to type unknown variables.

```suggestion
    const handleError = useCallback((error: unknown) => {
```

2022-07-12 05:49 UTC, valerybugakov commented on client/web/src/featureFlags/useFeatureFlag.test.tsx
> +                    const [overrides, setOverrides] = React.useState({
Could you elaborate on why hooks are required here compared to the previous version and why we need to disable the rules of hooks here? It would be helpful to add this reasoning as a comment for future reference.

2022-07-12 05:49 UTC, valerybugakov commented on client/web/src/enterprise/user/settings/ExternalAccountNode.tsx
> +                         * Issue: This JSX tag's 'children' prop expects a single child of type 'ReactNode', but multiple children were provided
Thanks for adding the comment here!

2022-07-12 05:49 UTC, valerybugakov commented on client/search-ui/src/components/FileSearchResult.test.tsx
> +    (): typeof _VisibilitySensor => ({ children, onChange }: React.ComponentProps<typeof _VisibilitySensor>) => (
Does it make sense to move this mock to the `shared` package and utilize it via `setupFiles` property defined in `jest.config.ts` to avoid repetition?

2022-07-12 05:50 UTC, valerybugakov reviewed
Btw, I fixed the integration test issue. All Buildkite pipelines are green now ✅

2022-07-12 16:47 UTC, gitstart-sourcegraph commented
@valerybugakov Thanks. We updated PRs to resolve your comments. Could you please re-review?

2022-07-13 05:16 UTC, valerybugakov requested changes
Thanks for applying review fixes; they look great!

I noticed a regression with the insights grid view that we need to fix before merging this one. Check out [this story](https://5f0f381c0e50750022dc6bf7-tkqgckofam.chromatic.com/?path=/story/web-insights-smartinsightsviewgridexample--smart-insights-view-grid-example) to see the repro. 

<img width="898" alt="Screen Shot 2022-07-13 at 13 04 18" src="https://user-images.githubusercontent.com/3846380/178655927-1ccda178-2a7b-4f19-b0ab-42585222613a.png">

Also, let's do more manual testing of the application for this PR by going through different pages on the app and checking that it looks as expected.

2022-07-13 18:25 UTC, gitstart-sourcegraph commented
@valerybugakov I found the issue which happens on the `ViewGrid` usage in `SmartInsightsViewGrid`. Could you take a look at my last commit?

2022-07-14 01:20 UTC, valerybugakov commented on client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
> +                setIsLayoutInitialized(true)
Makes sense to me, thanks!
@vovakulikov, could you take a look?

2022-07-14 10:01 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
> +                setIsLayoutInitialized(true)
@valerybugakov @gitstart-sourcegraph I tested it locally, everything is fine there after this fix. But

I also think that we could just change `useEffect` to `useLayoutEffect` there to avoid this "layout stealing" problem and not having addition flag state about layout intisialization. 

As I understood `react-grid-layout` fires `onLayoutChange` in mount phase so with `useLayoutChange` it should be possible to write layouts before this callback will be fired and it also will help `react-grid-layou`t with layout memorization. 

**With your fix we have** 
 - useEffect calling but it does nothing because we haven't set init flag yet
 - RGL (react-grid-layout) calls `handleLayoutChange` and we set initial flag and some layouts after `setLayouts(recalculateGridLayout(allLayouts, insights))`
 - RGL does call it `handleLayoutChange` again because we set a layout on previous step 
 - use effect works this time since we initialized layout init and set default layout
 - RGL does call it `handleLayoutChange` again because we set a layout on previous step in use effect
 
 As you can see there are too many jumps between different states and callbacks calls. So I propose 
 
**With just useLayoutEffect instead of useEffect**
- Run useLayoutEffect and set initial layout
- RGL does call first `handleLayoutChange`

and after this two steps memorization starts to work inside of RGL components.

2022-07-14 10:30 UTC, valerybugakov commented on client/web/src/enterprise/insights/components/insights-view-grid/SmartInsightsViewGrid.tsx
> +                setIsLayoutInitialized(true)
Thanks for the detailed breakdown, @vovakulikov!

2022-07-14 18:33 UTC, gitstart-sourcegraph commented on client/wildcard/src/types.ts
> +            : As extends React.ComponentType<PropsWithChildren<infer P>>
@valerybugakov  I made this change to support using `as` with components which require `function type` for `children` prop

2022-07-15 01:22 UTC, valerybugakov commented on client/wildcard/src/types.ts
> +            : As extends React.ComponentType<PropsWithChildren<infer P>>
Could you share some examples?

2022-07-15 01:56 UTC, gitstart-sourcegraph commented on client/wildcard/src/types.ts
> +            : As extends React.ComponentType<PropsWithChildren<infer P>>
It's for fixing build-ts errors for usages of `CreationUIForm` with `as=Component` which have `children: (inputs: RenderPropertyInputs) => ReactNode` in props

2022-07-15 03:52 UTC, valerybugakov approved these changes
Tested the application locally, and everything looks good so far. 
Thanks for a lot of fixes on the PR 🙌

2022-07-15 03:58 UTC, merged