generate: fix PGDATASOURCE for internal/database/gen.sh with nix
sourcegraph/sourcegraph pull request #36099
Opened 2022-05-26 17:09 UTC by Strum355

With Nix, I have the following env-var set:
```sh
PGDATASOURCE=postgresql:///postgres?host=/home/noah/.sourcegraph/postgres
PGDATA=/home/noah/.sourcegraph/postgres/13.6
PGDATABASE=postgres
PGUSER=noah
PGHOST=/home/noah/.sourcegraph/postgres
```
As this datasource uses Unix socket instead of TCP, it was resulting in a `PGDATASOURCE` that wouldnt work:

```sh
+ export PGDATASOURCE=postgres://noah:@/home/noah/.sourcegraph/postgres:/sg-squasher-frontend
+ PGDATASOURCE=postgres://noah:@/home/noah/.sourcegraph/postgres:/sg-squasher-frontend
+ export CODEINTEL_PGDATASOURCE=postgres://noah:@/home/noah/.sourcegraph/postgres:/sg-squasher-codeintel
+ CODEINTEL_PGDATASOURCE=postgres://noah:@/home/noah/.sourcegraph/postgres:/sg-squasher-codeintel
+ export CODEINSIGHTS_PGDATASOURCE=postgres://noah:@/home/noah/.sourcegraph/postgres:/sg-squasher-codeinsights
+ CODEINSIGHTS_PGDATASOURCE=postgres://noah:@/home/noah/.sourcegraph/postgres:/sg-squasher-codeinsights
+ ./tmp-sg migration describe -db frontend --format=psql -force -out internal/database/schema.md
❌ DB not available: failed to connect to `host=/home/noah/.sourcegraph/postgres user=noah database=home/noah/.sourcegraph/postgres:/sg-squasher-frontend`: server error (FATAL: database "home/noah/.sourcegraph/postgres:/sg-squasher-frontend" does not exist (SQLSTATE 3D000))
```

This change makes it look like this instead:

```sh
+ export 'PGDATASOURCE=postgresql:///postgres?host=/home/noah/.sourcegraph/postgres'
+ PGDATASOURCE='postgresql:///postgres?host=/home/noah/.sourcegraph/postgres'
+ export 'CODEINTEL_PGDATASOURCE=postgresql:///postgres?host=/home/noah/.sourcegraph/postgres'
+ CODEINTEL_PGDATASOURCE='postgresql:///postgres?host=/home/noah/.sourcegraph/postgres'
+ export 'CODEINSIGHTS_PGDATASOURCE=postgresql:///postgres?host=/home/noah/.sourcegraph/postgres'
+ CODEINSIGHTS_PGDATASOURCE='postgresql:///postgres?host=/home/noah/.sourcegraph/postgres'
+ ./tmp-sg migration describe -db frontend --format=psql -force -out internal/database/schema.md
```

cc'ing @keegancsmith in case he has a better solution

## Test plan

I ran the thing : ) maybe someone outside of Nix should also run the thing and edit this message

2022-05-26 19:08 UTC, efritz approved these changes

2022-05-26 19:09 UTC, efritz requested changes
Actually no, won't this use your default dataqbase or squashing? Don't do that 🤔

2022-05-26 21:52 UTC, efritz commented on internal/database/gen.sh
> +  PGDATASOURCE_BASE=$PGDATASOURCE
Do we know this is set or should we fall to the else if empty?

2022-05-26 21:55 UTC, Strum355 commented on internal/database/gen.sh
> +  PGDATASOURCE_BASE=$PGDATASOURCE
Im not sure what makes more sense, the else doesn't work if `PGHOST` points to a file, should we just bail if PGDATASOURCE isnt set?

2022-05-26 21:56 UTC, efritz commented on internal/database/gen.sh
> +  PGDATASOURCE_BASE=$PGDATASOURCE
Yeah I think print an error and exit 1 is a good idea. Otherwise someone else will have to look at this file :shudder:

2022-05-26 22:04 UTC, Strum355 commented on internal/database/gen.sh
> +  PGDATASOURCE_BASE=$PGDATASOURCE
Have set a check, lemme know what you think of the message.

2022-05-26 22:05 UTC, efritz approved these changes

2022-05-27 06:18 UTC, keegancsmith approved these changes

2022-05-27 11:18 UTC, merged