Fix reversed sort and cap data series
sourcegraph/sourcegraph pull request #36376
Opened 2022-06-01 14:55 UTC by unclejustin

- Fix date sorting
- Cap data series limit to 20

## Test plan

- Open any filterable insight
- Sorting date "Oldest" should show oldest series first
- Should not let you enter more than 20 for data series limit

2022-06-02 22:22 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
> +                    max={20}
Possible solutions

We could store the original series count on the initial page load. I do not like this idea, however. Since we will allow users to save this limit, that would be the max returned on a future page load. Which then means we can never increase the limit in the future. Ideally we would get a max series count back from the API, but that would entail changing the current queries. I'm not against it, but we would need to get that into the schedule.

2022-06-02 22:24 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
> +                    max={20}
One more note.

It's not obvious but setting a max value only limits what the "up arrow" will do. You can still override the value by typing in any number you want. That gets us around the "you can only go down" problem, but again, it's not obvious.

Also, do you want me to restrict that value from manual entry as well? We'll need some more javascript there. Not terrible, but I'd like your input before I commit time to it.

2022-06-06 08:33 UTC, AlicjaSuska commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
> +                    max={20}
Thank you for those comments @unclejustin I think we should put more time into making this experience better. With current limitations, it is very confusing.

- user shouldn't be able to override the value manually. If they enter a number bigger than the limit, we should automatically change this number to the highest possible (ex. if we can display max. 20 data series and they enter 21, we should change number to 20).
- I think that working on getting a max series count back from the API (that you've mentioned above) is necessary here. I don't think that either showing bigger number and displaying less data series or not being able to bring back data series once settings are saved are good experiences. @unclejustin let's discuss it during the sync as it needs more time (from the BE team I suppose?) @Joelkw FYI

2022-06-06 08:45 UTC, AlicjaSuska requested changes
@unclejustin I've recorded a [loom](https://www.loom.com/share/14b2d266c949420d82359b7ad7851254) with additional feedback / issues I found:
- filtering works only for detect&track insights, it should work for all IMO
- visual issues (we can leave them out until we have usability testing results)
- loading feels slow - potentially making it feel faster when only changing the number of series (details in the loom)
- input field behaviour - top number & cannot delete the '1'

Thank you!

2022-06-06 15:09 UTC, CristinaBirkel commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
> +                    max={20}
We had a `totalSeriesCount` scoped in originally, but then removed it because it didn't seem like it was needed. I think we should be able to add this back in. @unclejustin does that sound like the right solution? I can add a ticket for it and do it early this week.

2022-06-06 15:52 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
> +                    max={20}
@CristinaBirkel sounds perfect 🎉

2022-06-08 05:55 UTC, Joelkw commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
> +                    max={20}
Agree with @AlicjaSuska here!

2022-06-16 23:16 UTC, unclejustin commented
@AlicjaSuska this _should_ be working as expected now.

2022-06-22 12:51 UTC, AlicjaSuska commented
Hi @unclejustin - making the note here in the issue: yesterday I couldn't load the insights (as per our DMs) and today the 'web' link does not open at all. It only shows blank page and 'not found' text.

2022-06-27 07:37 UTC, AlicjaSuska commented
@unclejustin FYI - still experiencing the same issues with loading

2022-06-28 23:36 UTC, felixfbecker commented
@AlicjaSuska @unclejustin were you able to resolve the issues?

2022-06-29 00:45 UTC, unclejustin commented
@AlicjaSuska this is _finally_ working for me.

2022-06-29 15:47 UTC, unclejustin commented
@felixfbecker this is a follow-up to a previous PR that was waiting on backend support. No issue was created.

2022-06-29 16:09 UTC, AlicjaSuska requested changes
@unclejustin thank you for making changes. I found a weird behavior ([loom](https://www.loom.com/share/2a0e67b5a41a49c6888bb169b0d1a9e0)):
- when changing the number manually, no matter what number I click on the keyboard, it changes automatically to the max number of series
- I think that when deleting characters in the field, we should not display 1 as default value at all times. We should allow user to delete all characters and in case they click out of the field in this moment, put 1 as default value. (If there are no characters in the input, it's ok to show the loading state on the chart)

2022-06-30 08:13 UTC, AlicjaSuska commented
@unclejustin agree - let's cap to 20 and in the helper text let's write ('max 20') as well because it's about the maximum number of data series, not the total number detected :) Thnak you!

2022-07-01 20:48 UTC, unclejustin commented
@AlicjaSuska friendly ping! Could I get a review please.

2022-07-01 20:48 UTC, unclejustin commented
@vovakulikov I've made enough changes here to warrant another tech review when you have a moment.

2022-07-04 09:16 UTC, AlicjaSuska commented
Thank you for your [loom](https://www.loom.com/share/cbb171f6e4174399b769440bf5630668) @unclejustin I've recorded a [Loom](https://www.loom.com/share/15b399e65f0548d3bf2026ee1486e679) reply as well :)

Main points:
1. showing max number of data series on the chart when user deletes all the number in the input: the perfect solution for when user deletes all numbers in the input field is to show the loading state (until they type in a number or click out of the field and we fill it with '1'). Anyways, I totally see your point about this PR taking long and I'm fine with leaving the proposed solution (displaying up to 20 series) for now.
2. I've noticed that when I delete everything from the input field and click out, it remains empty. We can't leave it like this. If we decide to show all data series (established above), we should fill out the number to max number of data series (basically what we are showing on the chart)
3. When user types in the number bigger than max number of data series (for ex. 30), we need to change this number to max number of data series (for example 20). Otherwise, it is confusing.

I leave it to you in what order and in which PRs you'd like to address the issues. I think that the solution as it is now looks buggy because of points 2 and 3. I think it's not ready to be shown to customers.

---

In the recording, I've promised to list all the cases again so we have clarity on what the '**ideal state**' would be. Let's sync about what we can do from here to make it as easy and quick to implement as possible.

'max' - short for 'the maximum number of data series on the chart (up to 20)'

1. Navigation with arrows: user can't go lower than 1 and higher than max. When they ready the limit, disable the respective arrow.
2. User deletes all the digits from input field - show loading state on the chart until user types in something or clicks out of the field.
2a. User deletes all the numbers and clicks out of the field - fill the input with '1' and display 1 data series
3. User types in the number higher than max - change the number in the input field to max
4. User types in the number lower than 1 - change the number in the input field to 1

---

@unclejustin according to your suggestion about displaying max number of series when the input field is empty, we could change point 2a. to 'User deletes all the numbers and clicks out of the field - fill the input with max and display max number of data series' - I'm fine with this if that's easier on your side.

---

About 'highest' / 'lowest' being confusing as they bring results from all data series (not only from currently displayed ones) - I agree. I would like to add a helper text in this section. Is it possible to show the total number of series for the insight?

2022-07-04 09:19 UTC, AlicjaSuska requested changes
@unclejustin for this solution to be ready to use we need to at least correct the 2 items:
- empty field after user deletes all the digits. It needs to show the number of series displayed don'tthe chart
- issue with correcting number higher than max (example: 30 --> 20)
Otherwise, the solution looks buggy :(

Please, also see the comment above for more details. Thank you!

2022-07-05 18:39 UTC, unclejustin commented
@AlicjaSuska & @vovakulikov this PR is ready for review.

2022-07-05 20:21 UTC, vovakulikov approved these changes
@unclejustin I left a few comments and questions about tech and design aspects, thanks for refactoring the series display options filter panel with a standard useForm useField hooks.

2022-07-05 20:21 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/sort-filter-series-panel/SortFilterSeriesPanel.tsx
> +        if (inputValue.length > 0) {
@unclejustin @AlicjaSuska Maybe you've discussed this already but I'm not sure about this logic. Generally, changing input values while the user types their value is a bad practice because we don't know maybe I type 150 because I want to type 15 but just hit 0 by accident. And according to this logic, we reset their value to max (20) which is force users to type 15 again.

2022-07-05 22:17 UTC, unclejustin commented on client/web/src/enterprise/insights/pages/insights/creation/search-insight/utils/insight-sanitizer.ts
> +                seriesDisplayOptions: {
This is an excellent idea.

2022-07-05 22:29 UTC, unclejustin commented
@AlicjaSuska, @vovakulikov made some comments about using validation functions to prevent submitting incorrect values to the backend and informing the user that something is wrong. So instead of clamping the valued between 1 and MAX we let the user enter `150` for example and update an error message to say "The maximum limit you can set for this insight is 10".

This is a better approach in my opinion, but does imply that I need designs and verbiage for these error states. If you agree with vova and me, I can knock something together using examples from other forms so you just have to review what I've done.

Or I can wait for you to design something.

Or we can leave it as is.

#### Side note: What happened here?

This panel used to not use the `form api` so input validation was not readily available. This clamping logic is a holdover from this PRs "pre-form API" roots.

2022-07-06 12:59 UTC, AlicjaSuska requested changes
Hi @unclejustin - I've recorded a [loom](https://www.loom.com/share/b430628bf696409384675a8711c77199) with the review

Main points:
- we need to start with a correct value in the input, now it always shows 20
- let's add delay when changing the number to max for better, less confusing, experience

@vovakulikov I've also addressed your suggestion about the error states int he video :)

2022-07-06 18:27 UTC, vovakulikov commented
@AlicjaSuska I see your points. Now I'm wondering do we really need any validations there about the number of series. 

As I understood this we have a number of series that we manually created or that were generated on the backend in case of capture group insights (let's call this number M). And we want to limit the number of display series with M as the max value there? 

My question would be why do we need to do this? Why I can't specify just 10 series for my insights that at the moment has only 2 series, we don't know maybe the number of series  would be increased in the future (maybe I manually created them, maybe my code base would be changed and capture group will generate more series) 

It works in the opposite direction as well. What if I have insight that has 14 series and I specify display option filters with 10 and then my insights for some reason got only 8 series. Do we need to change/update our filter in this case?

For me, the display series filter is just a filter that specifies the max rendered series on the chart, and in my opinion, it should be limited by any dynamic number of series, it should be limited only by static (20 series) only. 

cc @Joelkw @unclejustin

2022-07-06 22:16 UTC, unclejustin commented
@AlicjaSuska when we last spoke we had the following outstanding items, I've been able to address only one of them 😢 

At this point, if there are no show-stopping bugs we will need to merge this in and move on.

### Delay updating number before updating 300ms.

Can't do it without a _lot_ of work.  Skipped.

### Disable the arrows

Not possible unless we build a new custom component. Again, outside the scope of this issue. Skipped.

### All limits default to 20. Fixed!

Below are some general thoughts that came up while working on this. Apologies if you've already thought through everything below 😅 

### Notes 1

When we first started this feature it was designed to live in its own panel and was originally built under that assumption. Some of the complexity around this feature is related to shoe horning this feature into a place it was not intended to be. (the state updates about whether filters have been updated, saving sorting vs filters since they aren't the same thing, decoupling form input from actual submission values, etc).

If we are going to leave sort & limit in the filters panel, I strongly believe we need to rethink how it functions to be more in line with the rest of the filters.

### Notes 2

When @vovakulikov and I synced up to try and fix some of these issues we came up with various other scenarios that could be confusing to users, that further pushes me to believe we need to think about this a little bit more.

1. If we save a limit value then add a series, the limit value gets reset. Is that ok? Is that expected? How do we communicate this?
2. If we save a limit for a capture group, but then the total series changes such that the new series count is below the current limit, does that mean we update the limit? What if the series count changes again?

2022-07-06 23:39 UTC, vovakulikov commented
@unclejustin if you don't plan to resolve my comments above (definitely non-blocking questions and suggestions) can you please create issue/issues for them just to be sure we won't forget about them later.

2022-07-07 15:36 UTC, AlicjaSuska commented
@vovakulikov I see what you mean. If we're not able to implement the behavior as designed, we will need to change to 'max number of displayed data series.

It was not my first choice when designing as it may be confusing since the number displayed will not always match the number of series. Many users will not read carefully enough to realize that it's a 'max' number. It's better in cases like this to minimize the cognitive load and go with a simpler solution IMO.

This doesn't invalidate the case that you've mentioned (what if total number changes in the future) - we will display 'max n' next to the filed. When in doubt, users can refer to it.

2022-07-08 00:45 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
> +                        parseSeriesDisplayOptions(seriesCount, seriesDisplayOptionsField.input.value)
Excellent catch, this is correct. Updated.

2022-07-08 00:48 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
> -        onFilterValuesChange = noop,
Roger that, I've put it back.

2022-07-08 00:53 UTC, unclejustin commented
> I think that when the total number of series changes, we shouldn't reset the filters automatically. We don't do it for the repo filters if the scope of the insight changes.

@AlicjaSuska did some digging, found and fixed the problem 🎉  display options no longer get reset

2022-07-08 01:03 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +        limit: parseSeriesLimit(debouncedFilters.seriesDisplayOptions.limit),
As per Alicja's comment, we're not going to use the validators right now. This parsing is happening up here in part because we need this value to be a number, not a string.

2022-07-08 01:04 UTC, unclejustin commented
@AlicjaSuska issues for missing items

- https://github.com/sourcegraph/sourcegraph/issues/38452
- https://github.com/sourcegraph/sourcegraph/issues/38453

@vovakulikov, I went through and resolved all of your comments that have final decisions on them. The remaining comments would require a change in the UX, so I'm leaving that decision to @AlicjaSuska

2022-07-11 14:26 UTC, unclejustin commented
@AlicjaSuska this one still needs review or approval please 🙇

2022-07-14 12:28 UTC, AlicjaSuska approved these changes
Thank you for creating the additional issues for missing items @unclejustin

2022-07-14 12:34 UTC, AlicjaSuska commented
I've also added an [issue](https://github.com/sourcegraph/sourcegraph/issues/38804) for smaller UI improvements so it doesn't slip when we work on this panel next time.

2022-07-15 16:59 UTC, felixfbecker commented
@unclejustin can this be merged now?

2022-07-16 00:41 UTC, merged