logging(gitstart): migrate internal/search to use lib/log
sourcegraph/sourcegraph pull request #36457
Opened 2022-06-02 09:15 UTC by gitstart-sourcegraph

> ## Problem statement
> `internal/search` is a shared library that still uses log15. We should migrate this package to use lib/log instead.
> 
> ## Success criteria
> All 22 usages of log15 in `internal/search` are replaced with calls to an appropriately scoped logger instance
> 
> https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Einternal/search+log15&patternType=literal
> 
> ## Implementation details
> Callsites provide loggers to the package (no logger should be instantiated within the package)
> 
> * In struct functions, all loggers should be set to the struct and provided.
> * In helper functions, all loggers should be provided as a parameter.
> 
> ## Time estimate
> * Pull requests with ~450 lines changed should take **48 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
> * Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

2022-06-07 08:49 UTC, burmudar commented on internal/search/backend/index_options.go
> +	logger "github.com/sourcegraph/sourcegraph/lib/log"
we don't need the module alias here

2022-06-07 08:50 UTC, burmudar commented on internal/search/job/jobutil/job.go
> +	slogger := logger.Scoped("toFeatures", "To features ")
rogue space after `To features`

2022-06-07 08:51 UTC, burmudar commented on internal/search/job/jobutil/sub_repo_perms_job.go
> +	slogger.Warn("Applying sub-repo permissions to search results", logger.String("error", errs.Error()))
we can use `log.Error` here instead

2022-06-07 09:07 UTC, gitstart-sourcegraph commented on internal/search/job/jobutil/sub_repo_perms_job.go
> +	slogger.Warn("Applying sub-repo permissions to search results", logger.String("error", errs.Error()))
@burmudar this is still a draft PR. The review guideline on the other PR would be applied here once ready

2022-06-07 10:20 UTC, burmudar commented on internal/search/job/jobutil/sub_repo_perms_job.go
> +	slogger.Warn("Applying sub-repo permissions to search results", logger.String("error", errs.Error()))
ah @gitstart-sourcegraph apologies 🙏🏼

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options.go
> +	getSearchContextRevisions func(repoID int32) ([]string, error), slog log.Logger,
use name `log` instead

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options.go
> +	getSiteConfigRevisions := siteConfigRevisionsRuleFunc(c, slog)
Use name `log` instead

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options.go
> +func siteConfigRevisionsRuleFunc(c *schema.SiteConfiguration, slog log.Logger) revsRuleFunc {
Use name `log`

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options_test.go
> +		log.Logger
Shouldn't this be
```go
type caseT struct {
		name              string
		conf              schema.SiteConfiguration
		searchContextRevs []string
		repo              int32
		want              zoektIndexOptions
		log                 log.Logger
}
```

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options_test.go
> +			b := GetIndexOptions(&tc.conf, getRepoIndexOptions, getSearchContextRevisions, tc.Logger, tc.repo)
`tc.log`

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options_test.go
> +		log.Logger
Shouldn't this be `log   log.Logger`

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options_test.go
> +			b := GetIndexOptions(&conf, getRepoIndexOptions, getSearchContextRevs, tc.Logger, 1)
`tc.log`

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/metered_searcher.go
> +	slogger := slog.Scoped("StreamSearch", "Stream search ")
This logger should be scopped to the `meteredSearcher` struct

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/backend/metered_searcher.go
> +			slogger.Warn("meteredSearcher: Error injecting new span context into map: %s", slog.Error(err))
Use structural logging here

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/job/jobutil/job.go
> +		slog.Scoped("toFeatures", "To Features").Warn("search feature flags are not available")
Pass this logger as a parameter into this func

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/job/jobutil/sub_repo_perms_job.go
> +	slogger := slog.Scoped("applySubRepoFiltering", "Filters a set fo matches using the provided")
Pass this logger as a parameter into this func

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/searcher/search.go
> +	slogger := slog.Scoped("Run", "Run calls the searcher service on a set of repositories")
Scope this logger to the `TextSearchJob` struct

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/structural/structural.go
> +		return runStructuralSearch(ctx, clients, s.SearcherArgs, repoSet, stream, s.Logger)
Logger should be the first parameter

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/structural/structural.go
> +	slog.Logger
Shouldn't this be `log    log.Looger`

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/zoekt/indexed_search.go
> +	slog.Logger
Shouldn't this be `log    slog.Looger`

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/zoekt/indexed_search.go
> +	userPrivateRepos := searchrepos.PrivateReposForActor(ctx, clients.DB, t.RepoOpts, t.log)
Logger should be the first parameter

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/zoekt/symbol_search.go
> +	userPrivateRepos := repos.PrivateReposForActor(ctx, clients.DB, s.RepoOpts, s.log)
Logger should be the first parameter

2022-06-10 06:57 UTC, gitstart-sourcegraph commented on internal/search/zoekt/zoekt.go
> +	slogger := slog.Scoped("getSpanContext", "get span context in zoekt")
Pass this logger as a parameter to this func

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on cmd/searcher/internal/search/search_structural.go
> +func structuralSearchWithZoekt(ctx context.Context, p *protocol.Request, sender matchSender, log slog.Logger) (err error) {
Make log the first param here

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on cmd/searcher/internal/search/search_structural.go
> +	zoektMatches, _, _, err := zoektSearch(ctx, patternInfo, branchRepos, time.Since, p.IndexerEndpoints, nil, log)
Make `log` the first param

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on cmd/searcher/internal/search/zoekt_search.go
> +func zoektSearch(ctx context.Context, args *search.TextPatternInfo, branchRepos []zoektquery.BranchRepos, since func(t time.Time) time.Duration, endpoints []string, c chan<- zoektSearchStreamEvent, l
Make `log` the first parameter here

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options.go
> +	getSiteConfigRevisions := siteConfigRevisionsRuleFunc(c, log)
Make `log` the first param here

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options.go
> +func siteConfigRevisionsRuleFunc(c *schema.SiteConfiguration, slog log.Logger) revsRuleFunc {
pass `log` as a first param

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on internal/search/backend/index_options_test.go
> +		log.Logger
this should be `log log.Logger`

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on internal/search/backend/metered_searcher.go
> +			m.log.Warn("meteredSearcher: Error injecting new span context into map: %s", slog.Error(err))
Use this instead 
`m.log.Warn("meteredSearcher: Error injecting new span context into map:", slog.Error(err))`

2022-06-20 11:53 UTC, gitstart-sourcegraph commented on internal/search/repos/repos_test.go
> +			r := Resolver{Opts: tc.opts, DB: db, log: logtest.Scoped(t)}
pass `log` as the first param

2022-06-20 11:56 UTC, gitstart-sourcegraph commented on internal/search/job/jobutil/mapper.go
> +func MapAtom(log log.Logger, j job.Job, f func(job.Job) job.Job) job.Job {
I do not see an update to the call signature on `MapAtom`

2022-06-22 17:52 UTC, bobheadxi commented on internal/search/zoekt/zoekt.go
> +func SearchOpts(log log.Logger, ctx context.Context, k int, fileMatchLimit int32, selector filter.SelectPath) zoekt.SearchOptions {
```suggestion
func SearchOpts(logger log.Logger, ctx context.Context, k int, fileMatchLimit int32, selector filter.SelectPath) zoekt.SearchOptions {
```

(careful about conflicting with the package name!)

2022-06-22 17:53 UTC, bobheadxi commented on internal/search/zoekt/indexed_search.go
> +func DoZoektSearchGlobal(log slog.Logger, ctx context.Context, client zoekt.Streamer, args *search.ZoektParameters, c streaming.Sender) error {
Also note that context should come first, as per https://docs.sourcegraph.com/dev/how-to/add_logging#basic-conventions

2022-06-22 17:54 UTC, bobheadxi commented on internal/search/job/jobutil/sub_repo_perms_job_test.go
> +		log         log.Logger
```suggestion
```

We can just set this all at once below! (see other suggestion)

2022-06-22 17:54 UTC, bobheadxi commented on internal/search/job/jobutil/sub_repo_perms_job_test.go
> +			matches, err := applySubRepoFiltering(tt.log, ctx, checker, tt.args.matches)
```suggestion
			matches, err := applySubRepoFiltering(logtest.Scoped(t), ctx, checker, tt.args.matches)
```

2022-06-23 08:49 UTC, jhchabran requested changes

2022-06-23 08:49 UTC, jhchabran commented on cmd/searcher/internal/search/hybrid.go
> +func zoektSearchIgnorePaths(log log.Logger, ctx context.Context, client zoekt.Streamer, p *protocol.Request, sender matchSender, indexed api.CommitID, ignoredPaths []string) (ok bool, err error) {
This was marked as resolved but it's not the case: https://github.com/sourcegraph/sourcegraph/pull/36457#discussion_r904074840 Please correct this.

2022-06-23 08:49 UTC, jhchabran commented on cmd/searcher/internal/search/search_structural.go
> +func structuralSearchWithZoekt(log slog.Logger, ctx context.Context, p *protocol.Request, sender matchSender) (err error) {
And there is another one here. @bobheadxi asked explicitly to apply the same logic to all occurrences.

2022-06-23 08:49 UTC, jhchabran commented on cmd/searcher/internal/search/search_structural.go
> +func structuralSearchWithZoekt(log slog.Logger, ctx context.Context, p *protocol.Request, sender matchSender) (err error) {
Our comment was also asking to use `logger` instead of `log` to name the argument. It's really strange to rename a package just because we want to use its name to name an argument.

2022-06-23 09:02 UTC, jhchabran commented on cmd/searcher/internal/search/hybrid.go
> +func zoektSearchIgnorePaths(logger log.Logger, ctx context.Context, client zoekt.Streamer, p *protocol.Request, sender matchSender, indexed api.CommitID, ignoredPaths []string) (ok bool, err error) {
here

2022-06-23 21:12 UTC, bobheadxi reviewed
Overall LGTM but there are some merge conflicts, can you address those first? thanks!

2022-06-24 16:36 UTC, bobheadxi commented on internal/search/run/repository_test.go
> +func repoShouldBeAdded(t *testing.T, ctx context.Context, clients job.RuntimeClients, repo *search.RepositoryRevisions, filePatternsInclude, filePatternsExclude []string) (bool, error) {
I think Go conventions would dictate that `context.Context` _always_ comes first:

```suggestion
func repoShouldBeAdded(ctx context.Context, t *testing.T, clients job.RuntimeClients, repo *search.RepositoryRevisions, filePatternsInclude, filePatternsExclude []string) (bool, error) {
```

2022-06-24 16:41 UTC, bobheadxi commented
Main dry run: https://buildkite.com/sourcegraph/sourcegraph/builds/156553

2022-06-27 18:18 UTC, gitstart-sourcegraph commented
@bobheadxi can you please do a final review on this PR

2022-06-27 20:30 UTC, bobheadxi commented
@gitstart-sourcegraph there is a panic in the integration tests:

```
2022-06-27T20:28:52.831109017Z [0;32m20:28:52                  frontend | [0mpanic: runtime error: invalid memory address or nil pointer dereference
2022-06-27T20:28:52.831128453Z [0;32m20:28:52                  frontend | [0m[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1f8701d]
2022-06-27T20:28:52.831134093Z [0;32m20:28:52                  frontend | [0mgoroutine 9758 [running]:
2022-06-27T20:28:52.831263903Z [0;32m20:28:52                  frontend | [0mgithub.com/sourcegraph/sourcegraph/internal/search/searcher.(*TextSearchJob).Run.func2.1()
2022-06-27T20:28:52.831290496Z [0;32m20:28:52                  frontend | [0m	github.com/sourcegraph/sourcegraph/internal/search/searcher/search.go:118 +0x81d
```

2022-06-27 20:32 UTC, bobheadxi commented on internal/search/searcher/search.go
> +						s.Log.Warn("searchFilesInRepo failed", sglog.Error(err), sglog.String("repo", string(repoRev.Repo.Name)))
https://sourcegraph.com/search?q=context:%40sourcegraph/all+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40contractors/SG-36384+.TextSearchJob%7B...%7D&patternType=structural

2022-06-27 20:50 UTC, bobheadxi commented on internal/search/searcher/search.go
> +						s.Log.Warn("searchFilesInRepo failed", sglog.Error(err), sglog.String("repo", string(repoRev.Repo.Name)))
Looks like it's here: https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40contractors/SG-36384+repoPagerJob+struct+%7B+...+%7D+OR+repoPagerJob%7B...%7D&patternType=structural

There is a logger on this struct that gets used by `TextSearchJob`, but that logger is never initialized

2022-06-27 22:02 UTC, gitstart-sourcegraph commented on internal/search/searcher/search.go
> +						s.Log.Warn("searchFilesInRepo failed", sglog.Error(err), sglog.String("repo", string(repoRev.Repo.Name)))
Modified all instances of `repoPagerJob` struct. How do we run the integration test to check in case of future cases?

2022-06-27 22:20 UTC, bobheadxi commented on internal/search/searcher/search.go
> +						s.Log.Warn("searchFilesInRepo failed", sglog.Error(err), sglog.String("repo", string(repoRev.Repo.Name)))
Good question - I'll look into this and let you all know in the channel :)

I've kicked off a build for you for now: https://buildkite.com/sourcegraph/sourcegraph/builds/156860

2022-06-27 22:50 UTC, bobheadxi commented on internal/search/searcher/search.go
> +						s.Log.Warn("searchFilesInRepo failed", sglog.Error(err), sglog.String("repo", string(repoRev.Repo.Name)))
https://github.com/sourcegraph/sourcegraph/pull/36457#issuecomment-1168007401

2022-06-28 06:23 UTC, gitstart-sourcegraph commented
Main dry run: https://buildkite.com/sourcegraph/sourcegraph/builds/156553

2022-06-28 06:41 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/search.go
> +		log:          log.Scoped("searchResolver", ""),
```suggestion
		log:          log.Scoped("searchResolver", "search resolver for BatchSearchImplementer"),
```

2022-06-28 07:07 UTC, bobheadxi commented
Main dry run on  https://github.com/sourcegraph/sourcegraph/commit/5f8e9f5dcc53c8cb70a16b7af3427eb4e40f7b05: https://buildkite.com/sourcegraph/sourcegraph/builds/156914#0181a90c-c9d5-4bfd-9843-2ae1cef9728d 

```
2022-06-28T07:01:27.105981635Z [0;33m07:01:27                  searcher | [0m{"SeverityText":"DEBUG","Timestamp":1656399687105767646,"InstrumentationScope":"server","Caller":"search/search.go:183","Function":"github.com/sourcegraph/sourcegraph/cmd/searcher/internal/search.(*Service).search.func1","Body":"search request","Resource":{"service.name":"searcher","service.version":"main-dry-run-contractors-SG-36384_156914_2022-06-28_5f8e9f5dcc53","service.instance.id":"06ecdc7975aa"},"Attributes":{"repo":"github.com/sgtest/java-langserver","commit":"03efbe9558acc532e88f5288b4e6cfa155c6f2dc","pattern":"^func.*$","isRegExp":true,"isStructuralPat":false,"languages":[],"isWordMatch":false,"isCaseSensitive":false,"patternMatchesContent":true,"patternMatchesPath":true,"matches":0,"code":"200","duration":0.007759188,"indexerEndpoints":[],"error":"<nil>"}}
2022-06-28T07:01:27.109121169Z [0;34m07:01:27                  frontend | [0mpanic: runtime error: invalid memory address or nil pointer dereference
2022-06-28T07:01:27.109141688Z [0;34m07:01:27                  frontend | [0m[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1f8701d]
2022-06-28T07:01:27.109148434Z [0;34m07:01:27                  frontend | [0mgoroutine 23942 [running]:
2022-06-28T07:01:27.109153756Z [0;34m07:01:27                  frontend | [0mgithub.com/sourcegraph/sourcegraph/internal/search/searcher.(*TextSearchJob).Run.func2.1()
2022-06-28T07:01:27.109159207Z [0;34m07:01:27                  frontend | [0m	github.com/sourcegraph/sourcegraph/internal/search/searcher/search.go:118 +0x81d
```

2022-06-28 16:59 UTC, bobheadxi commented
@gitstart-sourcegraph same issue here:

```
2022-06-28T08:26:22.181199959Z [0;34m08:26:22                  searcher | [0m{"SeverityText":"DEBUG","Timestamp":1656404782180950377,"InstrumentationScope":"server","Caller":"search/search.go:183","Function":"github.com/sourcegraph/sourcegraph/cmd/searcher/internal/search.(*Service).search.func1","Body":"search request","Resource":{"service.name":"searcher","service.version":"main-dry-run-contractors-SG-36384_156923_2022-06-28_32f912b267f7","service.instance.id":"8384b2e87363"},"Attributes":{"repo":"github.com/sgtest/appdash","commit":"ebfcffb1b5c00031ce797183546746715a3cfe87","pattern":"^func.*$","isRegExp":true,"isStructuralPat":false,"languages":[],"isWordMatch":false,"isCaseSensitive":false,"patternMatchesContent":true,"patternMatchesPath":true,"matches":419,"code":"200","duration":0.007552197,"indexerEndpoints":[],"error":"<nil>"}}
2022-06-28T08:26:22.185773026Z [0;35m08:26:22                  frontend | [0mpanic: runtime error: invalid memory address or nil pointer dereference
2022-06-28T08:26:22.185792709Z [0;35m08:26:22                  frontend | [0m[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1f8701d]
2022-06-28T08:26:22.185798112Z [0;35m08:26:22                  frontend | [0mgoroutine 19540 [running]:
2022-06-28T08:26:22.185803045Z [0;35m08:26:22                  frontend | [0mgithub.com/sourcegraph/sourcegraph/internal/search/searcher.(*TextSearchJob).Run.func2.1()
2022-06-28T08:26:22.185808187Z [0;35m08:26:22                  frontend | [0m	github.com/sourcegraph/sourcegraph/internal/search/searcher/search.go:118 +0x81d
2022-06-28T08:26:22.185812816Z [0;35m08:26:22                  frontend | [0mgolang.org/x/sync/errgroup.(*Group).Go.func1()
2022-06-28T08:26:22.185833355Z [0;35m08:26:22                  frontend | [0m	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
2022-06-28T08:26:22.185838542Z [0;35m08:26:22                  frontend | [0mcreated by golang.org/x/sync/errgroup.(*Group).Go
2022-06-28T08:26:22.185843403Z [0;35m08:26:22                  frontend | [0m	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d
```

2022-06-30 15:41 UTC, bobheadxi commented
Kicking off another main-dry-run: https://buildkite.com/sourcegraph/sourcegraph/builds/157552

2022-06-30 16:28 UTC, bobheadxi approved these changes
This looks fine for now - we can refine the scopes, and if needed the API, further down the line. Let's avoid having this PR become stale again and merge this - main-dry-run is green so this should be good to go

2022-06-30 17:12 UTC, merged

2022-07-01 19:50 UTC, camdencheek commented
This change seems to be [causing panics](https://github.com/sourcegraph/sourcegraph/issues/38105). I can't find an obvious place that a logger was left uninstantiated, so I plan to revert this PR. Additionally, I don't think adding the loggers to jobs is the correct path here since jobs should only contain data, not runtime types like loggers, so I would prefer if these changes were implemented by the search team.