logging(gitstart): migrate internal/database to lib/log
sourcegraph/sourcegraph pull request #36466
Opened 2022-06-02 11:40 UTC by gitstart-sourcegraph

> ## Problem statement
> `internal/database` is a shared library that still uses log15. We should migrate this package to use lib/log instead.
> 
> ## Success criteria
> All 30 usages of log15 in `internal/database` are replaced with calls to an appropriately scoped `lib/log` logger.
> 
> https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Einternal/database+log15&patternType=literal
> 
> ## Implementation details
> Callsites provide loggers to the package (no logger should be instantiated within the package)
> 
> * In struct functions, all loggers should be set to the struct and provided.
> * In helper functions, all loggers should be provided as a parameter.
> 
> ## Time estimate
> * Pull requests with ~450 lines changed should take **48 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
> * Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

2022-06-06 08:42 UTC, gitstart-sourcegraph commented on go.sum
> +github.com/766b/go-outliner v0.0.0-20180511142203-fc6edecdadd7/go.mod h1:1SzhThoS5lcKfE4IFOLQJ04WCmFpaAiPe8H9yqXyYSU=
Why this?

2022-06-06 08:42 UTC, gitstart-sourcegraph commented on internal/database/migration/runner/logger.go
> +func DisableLogging() {}
Can we remove these functions and instances they are called?

2022-06-06 08:42 UTC, gitstart-sourcegraph commented on internal/database/migration/runner/runner.go
> +		log.String("tuples", fmt.Sprintf("%d of %d", progress.TuplesDone, progress.TuplesTotal)),
Use structural logging

2022-06-06 12:06 UTC, burmudar commented on internal/database/migration/runner/run.go
> +	slogger.Info("Checking for active migrations")
`targetDefinitions` is missing here

2022-06-06 12:08 UTC, burmudar commented on internal/database/migration/runner/run.go
> +	slogger := r.logger.With(log.String("schema", schemaContext.schema.Name))
it is a bit confusing to have two different loggers here

2022-06-06 12:09 UTC, burmudar commented on internal/database/migration/runner/runner.go
> +		logger:         log.Scoped("NewRunnerWithSchemas", "create new runner with schema"),
Think this should just be `log.Scoped("Runner", "")`

2022-06-06 12:12 UTC, burmudar commented on internal/database/migration/runner/runner.go
> +			[]log.Field{
might be better to use `log.Object` here instead

2022-06-06 12:13 UTC, burmudar commented on internal/database/migration/runner/runner.go
> +	return []log.Field{
might be better to use `log.Object` here instead

2022-06-06 12:17 UTC, burmudar commented on internal/database/dbcache/cached_indexable_repos.go
> +		logger:     log.Scoped("NewIndexableReposLister", "List indexable repos"),
Scoped name should be according to the struct/component name ie. `IndexableReposLister`

2022-06-06 12:18 UTC, burmudar commented on internal/database/dbconn/config.go
>  func buildConfig(dataSource, app string) (*pgx.ConnConfig, error) {
I think  a logger should be passed in as a param here instead

2022-06-06 12:19 UTC, burmudar commented on internal/database/external_services.go
> +		logger: log.Scoped("External service store", "ExternalServicesWith instantiates and returns a new ExternalServicesStore with prepared statements"),
use the same case as the struct for the scope name `externalServiceStore`. Also the description should be empty in this case and not the comment to the method.

2022-06-06 12:30 UTC, gitstart-sourcegraph commented on internal/database/migration/runner/run.go
> +	slogger := r.logger.With(log.String("schema", schemaContext.schema.Name))
The structural logging values for `logger` and `slogger` are different but are reused in multiple places. So they were scopped to their appropriate `logger` and used accordingly

2022-06-06 12:33 UTC, burmudar commented on internal/database/repos.go
> +	logger := log.Scoped("scanRepo", "scan the repo")
If we look where `scanRepo` [is being used](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@36c320a88aa7594663ede8ce0cf3b5e97f0d8f69/-/blob/internal/database/repos.go?L784:13)
I think we should rather define the logger on the original `database/repos.go` struct and pass it in here as a parameter.

2022-06-06 17:33 UTC, gitstart-sourcegraph commented on internal/database/dbconn/config.go
>  func buildConfig(dataSource, app string) (*pgx.ConnConfig, error) {
At what point do we pass logger as a parameter or create a new scope? Is there a rule to follow?

2022-06-06 18:11 UTC, bobheadxi commented on internal/database/migration/runner/run.go
>  	)
This migration is not quite correct - we are creating an _info_ log entry with the fields, so you want:

```
logger := r.logger.With(
		log.String("schema", schemaContext.schema.Name),
	)

logger.Info("Checked current schema state",
		log.Ints("appliedVersions", extractIDs(byState.applied)),
		log.Ints("pendingVersions", extractIDs(byState.pending)),
		log.Ints("failedVersions", extractIDs(byState.failed)))
```

2022-06-07 08:44 UTC, burmudar commented on internal/database/repos.go
> +func scanRepo(rows *sql.Rows, r *types.Repo, logger log.Logger) (err error) {
`logger` should be the first param here. If `context` is first, then logger should be second

2022-06-07 08:44 UTC, burmudar commented on internal/database/repos.go
> +		logger: log.Scoped("ReposWith", ""),
the scoped name should be the struct name `repoStore`

2022-06-07 08:45 UTC, burmudar commented on internal/database/migration/runner/runner.go
> +		return log.Object("progress-hase", log.Bool("in-progress", false))
I think the object name should have the same object name as on line 463

2022-06-07 15:32 UTC, bobheadxi commented on internal/database/dbconn/config_test.go
> +	logger := logtest.Scoped(t)
This should be the tightest scope possible, i.e. on line 51

2022-06-07 15:34 UTC, bobheadxi commented on internal/database/external_services.go
> +		logger: log.Scoped("externalServiceStore", ""),
Same here, this should accept a logger - as outlined in the issue requirements, there should be no instantiation of loggers in this package. Please double check all instances of `log.Scoped()` in this PR to make sure that all usages are only `logger.Scoped()`, _not_ logger instantiations

2022-06-07 15:35 UTC, bobheadxi requested changes
Reminder of the requirements outlined:

> Callsites provide loggers to the package (**no logger should be instantiated within the package**)
>
> - In struct functions, all loggers should be set to the struct and provided.
> - In helper functions, all loggers should be provided as a parameter.

2022-06-08 10:21 UTC, gitstart-sourcegraph commented on internal/database/dbconn/connect.go
> +	// logger := log.Scoped("ConnectInternal", "connects to the given data source and return the handle")
Please remove commented code

2022-06-08 10:21 UTC, gitstart-sourcegraph commented on internal/database/dbtest/dbtest.go
> +	logger := log.Scoped("dbConn", "connects a new test db")
This is a test file. Shouldn't we be using the `logtest`

2022-06-08 19:04 UTC, bobheadxi requested changes

2022-06-08 19:04 UTC, bobheadxi commented on internal/database/migration/cliutil/addlog.go
> +func AddLog(logger log.Logger, commandName string, factory RunnerFactory, outFactory OutputFactory) *cli.Command {
Don't pass this logger in here, just create a logger in the action below

2022-06-08 19:04 UTC, bobheadxi commented on internal/database/migration/runner/validate.go
> +	logger.Warn("Schema not in expected state")
```suggestion
	slogger.Warn("Schema not in expected state")
```

2022-06-08 19:04 UTC, bobheadxi commented on internal/database/security_event_logs.go
> +	// Production output from this logger (SRC_LOG_FORMAT=json) complies with the OpenTelemetry log data model
I think we can remove all of these comments (in the other fields as well)

2022-06-08 19:04 UTC, bobheadxi commented on internal/database/users.go
> +		logger: log.Scoped("userStore", ""),
initialization should not happen here

2022-06-08 20:25 UTC, gitstart-sourcegraph commented on internal/database/users.go
> +		logger: log.Scoped("userStore", ""),
Do we also need to pass in the logger into the `Users` func?

2022-06-08 20:28 UTC, bobheadxi commented on internal/database/users.go
> +		logger: log.Scoped("userStore", ""),
Yes, quoting from the issue description:

> no logger should be instantiated within the package

The package being `internal/database`, which this code is within

2022-06-17 13:49 UTC, jhchabran commented on cmd/frontend/internal/cli/serve_cmd.go
>  	sqlDB, err := connections.EnsureNewFrontendDB("", "frontend", &observation.TestContext)
Following up on https://sourcegraph.slack.com/archives/C03FWK7UZMK/p1655460973587039 

The `EnsureNewFrontendDB` function will pull its logger from the `observation.Context` here, whose logger is `nil` at this stage.

2022-06-17 13:53 UTC, jhchabran commented on cmd/frontend/internal/cli/serve_cmd.go
>  	sqlDB, err := connections.EnsureNewFrontendDB("", "frontend", &observation.TestContext)
Quick fix: 

```go
func InitDB(logger sglog.Logger) (*sql.DB, error) {
	obsCtx := observation.TestContext
	obsCtx.Logger = logger
	sqlDB, err := connections.EnsureNewFrontendDB("", "frontend", &obsCtx)
```

2022-06-17 17:52 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/webhook_logs.go
> +	// Production output from this logger (SRC_LOG_FORMAT=json) complies with the OpenTelemetry log data model
Minor note - these docstrings are never required, don't worry about adding them :)

2022-06-17 17:55 UTC, bobheadxi commented on cmd/frontend/internal/app/ui/handlers.go
> +	logger := sglog.Scoped("server error handler", "")
```suggestion
	logger := sglog.Scoped("commonHandler", "")
```

2022-06-17 17:56 UTC, bobheadxi commented on cmd/frontend/internal/httpapi/httpapi.go
> +	logger := sglog.Scoped("NewInternalHandler", "")
```suggestion
	logger := sglog.Scoped("InternalHandler", "")
```

2022-06-17 17:56 UTC, bobheadxi commented on cmd/github-proxy/github-proxy.go
> +	// "github.com/sourcegraph/sourcegraph/lib/log/otfields"
```suggestion
```

2022-06-17 17:59 UTC, bobheadxi commented on doc/dev/how-to/add_logging.md
> +  "github.com/sourcegraph/log"
This diff should not be in your branch - maybe a botched merge?

2022-06-17 18:13 UTC, bobheadxi commented on doc/dev/how-to/add_logging.md
> +>>>>>>> 7f1aa182f1e3a0491f5a3b81f34c099db38cdd08
This file should have no diffs :)

2022-06-17 18:15 UTC, bobheadxi commented on internal/database/batch/batch.go
> +		operations:           getOperations(sglog.Scoped("Inserter", "")),
I think we should have this provided

2022-06-17 18:17 UTC, bobheadxi commented
Overall LGTM, left some comments!

2022-06-20 18:07 UTC, bobheadxi commented on doc/dev/how-to/add_logging.md
>  ```go
@gitstart-sourcegraph can we revert all changes to this file?

2022-06-20 18:10 UTC, bobheadxi commented
Kicking off a `main-dry-run`: https://buildkite.com/sourcegraph/sourcegraph/builds?branch=main-dry-run%2Fcontractors%2FSG-36387

2022-06-20 20:18 UTC, bobheadxi approved these changes
CI looks green, and `sg start` seems healthy :) Thank you!

2022-06-20 20:19 UTC, bobheadxi commented on cmd/worker/internal/migrations/migrators/extsvc_webhook_migrator.go
> +	// Production output from this logger (SRC_LOG_FORMAT=json) complies with the OpenTelemetry log data model
@gitstart-sourcegraph mentioned in another review comment that these comments should be removed, can you please remove them?

2022-06-20 20:28 UTC, bobheadxi commented on cmd/worker/internal/migrations/migrators/extsvc_webhook_migrator.go
> +	// Production output from this logger (SRC_LOG_FORMAT=json) complies with the OpenTelemetry log data model
Here's all the places it should be removed from: https://sourcegraph.com/search?q=context:%40sourcegraph/all+%22logger+is+a+standardized%2C+strongly-typed%2C+and+structured+logging+interface%22+repo:github.com/sourcegraph/sourcegraph%24%40contractors/SG-36387&patternType=regexp

2022-06-20 20:29 UTC, bobheadxi requested changes
see review comment: https://github.com/sourcegraph/sourcegraph/pull/36466#discussion_r901981547

2022-06-20 20:37 UTC, bobheadxi approved these changes
Ah well, wasn't that big of a deal so I removed the comments myself in https://github.com/sourcegraph/sourcegraph/pull/36466/commits/8c532e9a2c7c607387ded61ff5b2f7a2a50ca0c2 :)

2022-06-20 20:53 UTC, bobheadxi commented
@cla-bot check

2022-06-20 23:04 UTC, merged