Split large log lines up into smaller pieces
sourcegraph/sourcegraph pull request #36472
Opened 2022-06-02 13:27 UTC by burmudar

This addresses the following issue we were seeing on the pipeline
```
build 151159 job "0181205f-a064-4c8a-ae29-b4c8fc2acf48": unexpected status code 400: Max entry size '65536' bytes exceeded for stream '{app="buildkite", branch="main", build="151159", command="./tr dev/ci/yarn-web-integration.sh \"client/web/src/integration/batches.test.ts client/web/src/integration/blob-viewer.test.ts\"", component="build-logs", job="0181205f-a064-4c8a-ae29-b4c8fc2acf48", name=":puppeteer::electric_plug: Puppeteer tests chunk #1", queue="stateless,standard,default,job", retries_count="0", started_at="2022-06-01T17:51:40.783Z", state="failed", step_key="puppeteerelectricplugPuppeteertestschunk1", type="script"}' while adding an entry with length '563798' bytes]
```

1. After a line has been added to the stream values, we check whether we should split the line up into smaller pieces.
2. Each smaller piece has it's timestamp nanosecond value increased by 1 - this is safe todo, since the original Buildkite timestamps are in ms, so we on't override anything else (🙏🏼)
3. We  then replace the last value added with all the chunked pieces

Closes #36240
## Test plan
Unit Tests plus local loki instance

### Local Loki instance
Launch Loki with the following `docker-compose.yaml` which sets the `max_entry_line_size` to `1kb`
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml -distributor.max-line-size=1kb
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
```

2. Launch it `docker-compose up -d`
3. Download build logs and push them to the local loki instance using the change in this PR
```
$ go run . ci logs --build 151159 -out http://127.0.0.1:3100
Fetching logs for https://buildkite.com/sourcegraph/sourcegraph/builds/151159 ...
Pushing to Loki instance at "127.0.0.1:3100"
✅ Pushed 1110 entries from 1 streams to Loki
```

### The error with current sg
```
ℹ️ Auto updating sg ...
✅ sg has been updated!
To see what's new, run 'sg version changelog'.
Fetching logs for https://buildkite.com/sourcegraph/sourcegraph/builds/151159 ...
Pushing to Loki instance at "127.0.0.1:3100"
❌ Failed to push 1 streams:
 - build 151159 job "0181205f-a064-4c8a-ae29-b4c8fc2acf48": unexpected status code 400: Max entry size '1024' bytes exceeded for stream '{app="buildkite", branch="", build="151159", command="./tr dev/ci/yarn-web-integration.sh \"client/web/src/integration/batches.test.ts client/web/src/integration/blob-viewer.test.ts\"", component="build-logs", exit_status="1", finished_at="2022-06-01T17:56:00.355Z", job="0181205f-a064-4c8a-ae29-b4c8fc2acf48", name=":puppeteer::electric_plug: Puppeteer tests chunk #1", queue="", retries_count="0", started_at="2022-06-01T17:51:40.783Z", state="failed", step_key="puppeteerelectricplugPuppeteertestschunk1", type="script"}' while adding an entry with length '1337' bytes
❌ failed to push all logs
```

2022-06-02 13:40 UTC, jhchabran requested changes
Minor comments, eager to merge this 😊

2022-06-02 13:40 UTC, jhchabran commented on dev/sg/internal/loki/loki.go
> +	time.Sleep(1 * time.Second)
Left over 😇 ?

2022-06-02 13:53 UTC, burmudar commented on dev/sg/internal/loki/loki.go
> +	chunks := splitIntoChunks([]byte(entry[1]), chunkSize)
ooooh good point!

2022-06-02 13:55 UTC, burmudar commented on dev/sg/internal/loki/loki.go
> +	time.Sleep(1 * time.Second)
Whoops ...
![Oops](https://media.giphy.com/media/SwyTq2jJxc9im6BYnN/giphy-downsized.gif)

2022-06-02 14:11 UTC, burmudar commented on dev/sg/internal/loki/loki.go
> +	time.Sleep(1 * time.Second)
Removed 👼🏼

2022-06-02 14:11 UTC, burmudar commented on dev/sg/internal/loki/loki.go
> +	chunks := splitIntoChunks([]byte(entry[1]), chunkSize)
I've added a todo and will create a follow up issue to update this!

2022-06-02 16:09 UTC, bobheadxi commented on dev/sg/internal/loki/loki.go
> +		lastValue := values[len(values)-1]
It's a bit confusing to add a value and then operate on this most recent value - maybe we should add this within the above block instead?

```go
	if ts == previousTimestamp {
			// Check if the combined chunk is oversided before doing a merge here
			values[len(values)-1][1] = values[len(values)-1][1] + fmt.Sprintf("\n%s", line)
		} else {
```

2022-06-03 10:44 UTC, burmudar commented on dev/sg/internal/loki/loki.go
> +		lastValue := values[len(values)-1]
Moved to happen earlier. I tried some slicing  fu but since the one branch needs to replace the last entry and the other just add more items - I could not quite find a nice fit so came up with what we have now.

2022-06-03 12:10 UTC, jhchabran commented
@burmudar would gladly review, but the build is failing its unit tests :) 

```
FAIL | NewStreamFromJobLogs (0.01s)
FAIL |   NewStreamFromJobLogs/merge_timestamps (0.00s)
FAIL | 	github.com/sourcegraph/sourcegraph/dev/sg/internal/loki	0.101s
```

2022-06-03 12:47 UTC, burmudar commented
Sorry about that @jhchabran ... I was a bit _over confident in my change_

2022-06-03 12:54 UTC, burmudar commented on dev/sg/internal/loki/loki.go
> +		lastValue := values[len(values)-1]
I was a bit in between two minds with this tbh. I feel the chunking should rather happen in the push streams part of the code, but then it is wasteful to go through _all values again_ and add it to a new values with some added chunks ... possibly 🤷🏼.

Another reason for moving to the push streams part is anyone using the method will benefit from the chunking, whereas now only if logs are read. I guess this is just making a decision between explicit and implicit chunking

2022-06-03 13:28 UTC, jhchabran commented
> Sorry about that @jhchabran ... I was a bit _over confident in my change_

NW mate, that's exactly what the CI is there for 😊 ! Happens to me often too :)

2022-06-03 13:42 UTC, jhchabran approved these changes
The CI logs will be much more accurate with this 🎉

2022-06-03 14:47 UTC, bobheadxi approved these changes
Fantastic, thank you 😁

2022-06-03 14:47 UTC, bobheadxi commented on dev/sg/internal/loki/loki.go
> +const maxEntrySize = math.MaxUint16
Maybe add a quick docstring here about how Loki rejects entries above a certain size!

2022-06-03 14:47 UTC, bobheadxi commented on dev/sg/internal/loki/loki.go
> +		lastValue := values[len(values)-1]
I think it's fine to embed here and make it implicit - `NewStreamFromJobLogs` should return a Loki stream that _can be pushed to Loki_, which when unchunked does not hold 😅 I see you made the change though, thanks!

2022-06-03 15:38 UTC, merged