insights: [wip] Poll insight when data is backfilling
sourcegraph/sourcegraph pull request #36484
Opened 2022-06-02 14:50 UTC by chwarwick

I think I've got this generally working at this point, and wanted to get some feedback to make sure I was headed in the correct direction before continuing on with clean up and testing.

closes #35479
## Test plan
tbd

2022-06-02 14:52 UTC, chwarwick commented
I couldn't get apollo's polling to work when it was going though rxjs and I saw other users reporting the same issues with `watchQuery`

2022-06-03 07:03 UTC, vovakulikov approved these changes

2022-06-03 07:03 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +            onChange={isVisible => {
@chwarwick can we just rewrite it without manual checks. Like 

```js
onChange={setWasVisibile}
```

2022-06-03 07:03 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +            onChange={isVisible => {
@chwarwick can we just rewrite it without manual checks. Like 

```js
onChange={setWasVisibile}
```

2022-06-03 07:03 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +    const { error, loading, stopPolling } = useQuery<GetInsightViewResult, GetInsightViewVariables>(
@chwarwick do we want to have the same logic for the standalone page as well?

2022-06-03 07:03 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +    const { error, loading, stopPolling } = useQuery<GetInsightViewResult, GetInsightViewVariables>(
@chwarwick do we want to have the same logic for the standalone page as well?

2022-06-03 07:06 UTC, vovakulikov approved these changes
Thanks, @chwarwick, I'm surprised that such a cool improvement didn't take so many changes. I left a few non-blockers questions, I approved this PR in advance since CI is red now (but it seems this is because of mocks in storybook so should be easy to fix it)

2022-06-03 07:16 UTC, vovakulikov requested changes
@chwarwick Actually I found something that might be worth fixing in this PR. If you open the all insight dashboard on the k8s for example you will see that we do not fetch all insights but only that are in visible viewport, I saw that you used react-sensor lib to preserve this logic but I think this doesn't work properly at the moment. I see a lot of requests on the all insights dashboard even if only a few of them are visible. 

<img width="1173" alt="Screenshot 2022-06-03 at 15 13 59" src="https://user-images.githubusercontent.com/18492575/171806437-704f7e36-f1ff-4d7d-9558-5270563717b9.png">

2022-06-03 09:35 UTC, vovakulikov commented
Also (not a blocker but just for the record) since we dropped our useInsightData hook here we also removed our logic about fetching parallelization as well, This means that we're going to fetch all insights that we see on the screen in parallel, prior to this PR we had a logic that we're fetching insights sequentially but in parallel by 2 insights. 

I'm not sure that this is a problem since I don't think that we will have cases when too many insights fit into the visible area on the screen and therefore we will bombard our backend with many requests. 

Also, I want to mention that perhaps we already have a solution for it, some time ago I wrote [an apollo link for sequentially fetching](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=client%2Fhttp-client%2Fsrc%2Fgraphql%2Flinks%2Fconcurrent-requests-link.ts&editor=JetBrains&version=v1.2.2&start_row=29&start_col=22&end_row=29&end_col=22). @chwarwick you can try to use this one to preserve this logic about fetching.

2022-06-03 13:58 UTC, chwarwick commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +            onChange={isVisible => {
This was a last min addition because it was fetching too often, i'll pull it into an onCallback and just pass that func.  I only want to capture the initial false -> true flip otherwise it triggers the useQuery hook to refetch on every change.

2022-06-03 14:00 UTC, chwarwick commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +    const { error, loading, stopPolling } = useQuery<GetInsightViewResult, GetInsightViewVariables>(
I think it makes sense to keep them consistent so my plan was to make them the same.

2022-06-03 14:05 UTC, chwarwick commented
> Also, I want to mention that perhaps we already have a solution for it, some time ago I wrote [an apollo link for sequentially fetching](https://sourcegraph.com/-/editor?remote_url=git%40github.com%3Asourcegraph%2Fsourcegraph.git&branch=main&file=client%2Fhttp-client%2Fsrc%2Fgraphql%2Flinks%2Fconcurrent-requests-link.ts&editor=JetBrains&version=v1.2.2&start_row=29&start_col=22&end_row=29&end_col=22). @chwarwick you can try to use this one to preserve this logic about fetching.

I'll check that out, I was seeing fetch 6 at a time for me, I don't think it's as big as issue because they are no longer running live queries just a quick hit to postgres, but if what you have can work I'll try dropping that in.  Your screenshot above looks like that is all the Language Stats insights getting pulled at once.   I don't think anything I did would cause that, but I'll double check.

2022-06-03 18:22 UTC, unclejustin approved these changes
Nothing but a small question. Vova already covered the rest 🎉

2022-06-03 18:22 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +            skip: !wasVisble,
Why `wasVisible` and not `isVisible`?

2022-06-03 18:31 UTC, chwarwick commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/BackendInsight.tsx
> +            skip: !wasVisble,
@unclejustin I started with `isVisible` but it caused a re-query every time the visibility changed because it's a dependency to the hook.  What I really want is skip if this hasn't been visible yet, and after that I don't care if it is or isn't visible.

2022-06-07 18:47 UTC, chwarwick commented
@vovakulikov I was able to use the sequential fetching link for apollo so that should be addressed.

2022-06-07 18:56 UTC, chwarwick commented
@AlicjaSuska Added you as a reviewer but there are no visual changes and in current state the polling for the updates is disabled, because of an issue with the chart Y axis as data updates.

2022-06-08 14:35 UTC, vovakulikov commented
@chwarwick 
> I don't think it's as big as issue because they are no longer running live queries just a quick hit to Postgres, but if what you have can work I'll try dropping that in

I don't fully understand yet what is going on on the all insight dashboard but I still see that we trigger fetching for all insight on the page when I hit the All insight dashboard. We don't have this problem on the dogfood at the moment so assume that something happening with react sensor there or the skip parameter in `useQuery` doesn't work properly.

**This PR implementation** 
<video src="https://user-images.githubusercontent.com/18492575/172642843-75e1468d-ff92-4795-8d78-a134faf77d47.mov" />

**The dogfood behaviour** 
<video src="https://user-images.githubusercontent.com/18492575/172642916-ba530a5a-f210-465c-9da3-6f765d4d8037.mov" />

@chwarwick let me know if you won't be able to find the root cause of this problem, we can pair on this. But my main guess so far is that we set `wasVisible` at component mount because the react-grid renders the all cards first → then react sensor trigger `wasVisible` state → then we start fetching → then the react-grid puts cards into the grid and they are going away from the screen (but this doesn't matter because we already triggered the fetching)

2022-06-09 15:57 UTC, vovakulikov approved these changes

2022-06-09 16:02 UTC, merged