Insights/fix-drilldown-ux
sourcegraph/sourcegraph pull request #36588
Opened 2022-06-03 21:41 UTC by unclejustin

Related to: https://github.com/sourcegraph/sourcegraph/issues/36286

## Test plan

- Open storybook
- Go to Drill Down Popover
- Sort & Limit should show purple dot always
- "Default filters applied" shoud hide when changing any filter, including Sort & Limit
- "Save default filters" should enable when changing anything in Sort & Limit

2022-06-03 21:43 UTC, unclejustin commented
@AlicjaSuska from my interpretation the purple dots just show when a filter is applied. By that logic "Sort & Limit' always have something applied because it defaults to a value. If that is wrong please let me know how you want it to work.

2022-06-06 05:42 UTC, vovakulikov commented
@unclejustin 

>@AlicjaSuska from my interpretation the purple dots just show when a filter is applied. By that logic "Sort & Limit' always have something applied because it defaults to a value. 

I think in this case I would say we should check the difference between default filter values and the last changed filter values, if they are different we should render the purple dot if they are the same we shouldn't, similar to other filter sections that we have there. (for other sections the default state is empty but the concept stays the same, changed → purple dot)

2022-06-06 10:16 UTC, AlicjaSuska requested changes
Agree with @vovakulikov - we should display the purple dot only if sorting values are different than default ('highest' and max number of data series).

2022-06-07 00:50 UTC, unclejustin commented
@AlicjaSuska I have the dots showing up on change now with one exception. The filter icon on the insight card itself does not reflect this change. I would like to hold off on fixing this until I address the implementation problems with this part of the code in [this issue](https://github.com/sourcegraph/sourcegraph/issues/36589).

In short: Getting the change icon on the filter icon at the card level will introduce a good amount of tech debt that is going to all go away when that next issue is complete. I will push to have that issue completed next iteration before the release if you are ok with me waiting until then.

cc @vovakulikov You said this would be a problem and, oh buddy you were right.

2022-06-07 22:58 UTC, unclejustin commented
@AlicjaSuska thanks for the clarification. This one is ready for review then.

2022-06-08 05:49 UTC, vovakulikov commented
@AlicjaSuska @unclejustin I think I found one more problem around filters and how we show that we some filters applied. 

At the moment:
- I open the filters and change something around series display options
- I see purple point as a sigh that I changed something
- Then I save current filters as default one

After that I expect to see the the purple dot in the insight card has papered because it's our visual sight that this insight was filtered, when I open the filter section I expect to see the purple dot next to the filter that is different from the very default (empty) value. 

The current behavior:
- When you save series display filters as default you can't see the purple dot in the insight card
- You can't see the purple dot in the filter section as well

I'm not sure that's the right behavior here actually, but now series display filter acts a bit different from the other filters 

https://user-images.githubusercontent.com/18492575/172540777-17608440-8af1-4fd2-ae10-23fe07bf372a.mov

2022-06-08 05:52 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
> +                            (!hasFiltersChanged && !hasSeriesDisplayOptionsChanged)
@unclejustin do you plan to include series display options in the filter object in the future? Just to avoid complexity in the codebase and to avoid manual handling of this filter?

2022-06-08 15:09 UTC, unclejustin commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/drill-down-filters-panel/drill-down-filters/DrillDownInsightFilters.tsx
> +                            (!hasFiltersChanged && !hasSeriesDisplayOptionsChanged)
No, all of this is going to change or go away completely when this is updated to use the form API.

2022-06-08 15:13 UTC, unclejustin commented
@vovakulikov 

> When you save series display filters as default you can't see the purple dot in the insight card

This is a known limitation that I am ignoring for this PR. It will be resolved when we update this to use the form API

RE: your other observation I think I understand the problem. I interpreted the design to mean "show the dot when the options are different". This is to say when the current options are different than what is saved.

But I think you mean for it to be different than the default options.

@AlicjaSuska can you confirm that we want the purple dot to show when the options are different than the default, not different than the saved options?

2022-06-08 22:34 UTC, unclejustin commented
@AlicjaSuska done. The purple dot indicator now shows when display options differ from the default.

2022-06-10 04:51 UTC, vovakulikov approved these changes
Tech changes look good to me.

2022-06-10 09:00 UTC, AlicjaSuska approved these changes
Thank you @unclejustin - dot appears in the menu for non-default values as expected

2022-06-10 19:08 UTC, merged