Northyg doc update
sourcegraph/sourcegraph pull request #36607
Opened 2022-06-04 06:47 UTC by northyg

## Test plan

2022-06-04 21:44 UTC, northyg commented
@sourcegraph/contribution-reviewers

2022-06-07 16:32 UTC, abeatrix requested changes
LGTM but it looks like it's serving the same purpose as the [Quickstart for setting up the local environment](https://docs.sourcegraph.com/dev/setup/quickstart), so maybe @bobheadxi or the @sourcegraph/dev-experience team can help with the review?

2022-06-07 16:32 UTC, abeatrix commented on doc/dev/how-to/develop_sourcegraph.md
> +
I think it would be helpful to mention the differences/limitations between the Enterprise version and the OSS version, like how extensions are not supported on the OSS version as users have run into a [similar issue ](https://gitlab.com/gitlab-org/gitlab/-/issues/361820)before.

2022-06-07 16:33 UTC, bobheadxi commented
> but it looks like it's serving the same purpose as the [Quickstart for setting up the local environment](https://docs.sourcegraph.com/dev/setup/quickstart)

Agree, this is a duplicate of https://docs.sourcegraph.com/dev/setup/quickstart (or at least, what that doc should be) - is there a reason we need a separate guide?

2022-06-26 21:43 UTC, closed without merging