Replace Sentry capture call in SecurityEventLogger with logger call
sourcegraph/sourcegraph pull request #37212
Opened 2022-06-14 12:54 UTC by jhchabran

## Test plan

2022-06-14 12:54 UTC, jhchabran commented
Current dependencies on/for this PR:
* main
  * **PR #37209** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/37209" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #37212** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/37212" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/37212?utm_source=stack-comment).

2022-06-14 23:24 UTC, bobheadxi commented on internal/database/security_event_logs.go
> +	logger := log.Scoped("security_events", "Security events logs")
```suggestion
	logger := log.Scoped("SecurityEvents", "Security events")
```

2022-06-15 16:00 UTC, bobheadxi requested changes

2022-06-15 16:00 UTC, bobheadxi commented on internal/database/security_event_logs.go
> +		s.logger.Error(string(e.Name), log.String("event", string(j)), log.String("traceID", trace.ID(ctx)), log.Error(err))
I just notice we have a trace ID, this should use our `WithTrace` logging: https://docs.sourcegraph.com/dev/how-to/add_logging#traced-sub-loggers (sorry I missed this on the first review!)

2022-06-15 17:44 UTC, jhchabran commented on internal/database/security_event_logs.go
> +		s.logger.Error(string(e.Name), log.String("event", string(j)), log.String("traceID", trace.ID(ctx)), log.Error(err))
Oh nice catch! (np, I'll take a late catch before the merge any day over a post merge one 😆👍)

2022-06-15 17:54 UTC, bobheadxi approved these changes
beautiful :)

2022-06-15 18:02 UTC, merged