code monitoring: log frontend events
sourcegraph/sourcegraph pull request #37238
Opened 2022-06-14 21:47 UTC by limitedmage

Log frontend events as described in [RFC 700](https://docs.google.com/document/d/1QpB2tAginNjvprW51A4F7bT8kHU0SqceBIuGXEN22zk/edit#heading=h.yltlv6dgwggx).

| Event description | Logged event name | Notes |
|---|---|---|
| Code monitoring homepage viewed | `CodeMonitoringViewed` | Pre-existing event, not outlined in RFC 700. Previously called `ViewCodeMonitoringPage` |
| Code monitor getting started page viewed | `CodeMonitoringGettingStartedPageViewed` | |
| Code monitor library item clicked | `CodeMonitoringExampleMonitorClicked` | |
| Code monitor creation started | `CreateCodeMonitorPageViewed` | Pre-existing event, previously `ViewCreateCodeMonitorPage` |
| Code monitor created | `CreateCodeMonitorFormSubmitted` | Pre-existing event |
| Code monitor update started | `ManageCodeMonitorPageViewed` | Pre-existing event, previously `ViewManageCodeMonitorPage` |
| Code monitor updated | `ManageCodeMonitorFormSubmitted` | |
| Code monitor deleted | `ManageCodeMonitorDeleteSubmitted` | |
| Logs page viewed | `CodeMonitoringLogsPageViewed` | |

## Test plan

Trigger the events listed and verify they are being sent to the server by analyzing the network tab in the browser's dev tools.

## App preview:

- [Web](https://sg-web-jp-cmlogevents.onrender.com)
- [Storybook](https://5f0f381c0e50750022dc6bf7-sbuozvhbtz.chromatic.com)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

2022-06-15 16:43 UTC, camdencheek commented
If it's helpful, these are the current events we send pings for: 
```
            'ViewCodeMonitoringPage',
            'ViewCreateCodeMonitorPage',
            'ViewManageCodeMonitorPage',
            'CodeMonitorEmailLinkClicked'
```

2022-06-15 16:54 UTC, camdencheek commented
> are being changed to ...PageViewed

Works for me. Could you document which event names you changed in this PR so I can query for both the old and the new events? We don't want pings to show a weird drop because we changed the event names.

2022-06-16 00:11 UTC, camdencheek commented
@limitedmage is this ready for review?

2022-06-16 14:49 UTC, limitedmage commented
> @limitedmage is this ready for review?

It is!

2022-06-16 18:56 UTC, camdencheek requested changes

2022-06-16 18:56 UTC, camdencheek commented on client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
> +                    eventLogger.log('CodeMoitoringLogsPageViewed')
```suggestion
                    eventLogger.log('CodeMonitoringGettingStartedPageViewed')
                    break
                case 'logs':
                    eventLogger.log('CodeMonitoringLogsPageViewed')
```

2022-06-16 18:56 UTC, camdencheek commented on client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
> +                    eventLogger.log('CodeMoitoringLogsPageViewed')
Also, why `logPageView('CodeMonitoring')` above, but not `logPageView('CodeMonitoringLogsPage')` here?

2022-06-16 18:56 UTC, camdencheek commented on client/web/src/enterprise/code-monitoring/CodeMonitoringPage.tsx
> +    useEffect(() => eventLogger.logPageView('CodeMonitoring'), [])
Shouldn't this be `logPageView('CodeMonitoringPage')`?

2022-06-16 22:57 UTC, merged