[SG-37461]: logging(gitstart): migrate internal/repos to sourcegraph/log
sourcegraph/sourcegraph pull request #37603
Opened 2022-06-23 10:07 UTC by gitstart-sourcegraph

## Task URL
https://app.gitstart.com/tasks/64396

## Test plan

##Credit cost
70 credits

2022-07-16 02:16 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +			src, err := repos.NewSource(ctx, log.Scoped("getNodesAndErrors", ""), a.db, svc, cf)
```suggestion
			src, err := repos.NewSource(ctx, log.Scoped("repos.source", ""), a.db, svc, cf)
```

2022-07-16 02:16 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/external_service.go
> +	scopes, err := repos.GrantedScopes(ctx, log.Scoped("GrantedScopes", ""), scopeCache, r.db, r.externalService)
```suggestion
	scopes, err := repos.GrantedScopes(ctx, r.logger.Scoped("GrantedScopes", ""), scopeCache, r.db, r.externalService)
```

2022-07-18 08:25 UTC, 0xedb commented on cmd/frontend/graphqlbackend/external_service.go
> +	scopes, err := repos.GrantedScopes(ctx, log.Scoped("GrantedScopes", ""), scopeCache, r.db, r.externalService)
fixed

2022-07-18 08:25 UTC, 0xedb commented on cmd/frontend/graphqlbackend/affiliated_repositories_connection.go
> +			src, err := repos.NewSource(ctx, log.Scoped("getNodesAndErrors", ""), a.db, svc, cf)
fixed

2022-07-18 12:10 UTC, gitstart-sourcegraph commented on internal/repos/main_test.go
> -		log15.Root().SetHandler(log15.DiscardHandler())
```go
logtest.InitWithLevel(m, log.LevelNone)
```

2022-07-21 05:39 UTC, bobheadxi commented on cmd/repo-updater/shared/main.go
> +	go repos.RunRepositoryPurgeWorker(ctx, log.Scoped("shared.Main", ""), db, purgeTTL)
Why is this scope `shared.Main`? shouldn't it be `RepositoryPurgeWorker`? Entries logged by this logger belong to that, not `Main`

2022-07-21 05:39 UTC, bobheadxi commented on enterprise/internal/batches/sources/sources.go
> +		cloneURL, err := repos.CloneURL(log.Scoped("sources.extractCloneURL", ""), svc.Kind, svc.Config, repo)
same here

```suggestion
		cloneURL, err := repos.CloneURL(log.Scoped("CloneURL", ""), svc.Kind, svc.Config, repo)
```

2022-07-21 06:48 UTC, bobheadxi commented on cmd/repo-updater/repoupdater/server.go
> +		sourcer = repos.NewSourcer(s.Logger.Scoped("handleExternalServiceSync", ""), db, httpcli.ExternalClientFactory, repos.WithDependenciesService(depsSvc))
same as the other suggestions - please audit scopes, scopes should apply to what is going to get logged

```suggestion
		sourcer = repos.NewSourcer(s.Logger.Scoped("repos.Sourcer", ""), db, httpcli.ExternalClientFactory, repos.WithDependenciesService(depsSvc))
```

2022-07-21 14:00 UTC, jhchabran requested changes
A few remarks, but we're getting there!

2022-07-21 14:00 UTC, jhchabran commented on internal/repos/sources.go
> +		return NewBitbucketServerSource(logger, svc, cf)
This constructor is not scoping the logger on its own, so it should be scoped here.

2022-07-21 14:00 UTC, jhchabran commented on internal/repos/sources.go
> +		return NewPhabricatorSource(logger, svc, cf)
This constructor is not scoping the logger on its own, so it should be scoped here.

2022-07-21 14:00 UTC, jhchabran commented on internal/repos/sources.go
> +		return NewGitLabSource(ctx, logger, db, svc, cf)
This constructor is not scoping the logger on its own, so it should be scoped here.

2022-07-21 14:00 UTC, jhchabran commented on internal/repos/syncer.go
> +	worker, resetter := NewSyncWorker(ctx, s.Logger, store.Handle(), &syncHandler{
```suggestion
	worker, resetter := NewSyncWorker(ctx, s.Logger.Scoped("syncWorker", ""), store.Handle(), &syncHandler{
```

2022-07-22 08:46 UTC, jhchabran approved these changes

2022-07-22 13:54 UTC, merged