ci: fix go flakes in database/internal
sourcegraph/sourcegraph pull request #37775
Opened 2022-06-27 17:02 UTC by jhchabran

Over time, we have increased the `maxDbConns` ƒor the test database from [3 to 10](https://github.com/sourcegraph/sourcegraph/pull/22756/files) and then [10 to 20](https://github.com/sourcegraph/sourcegraph/commit/97fc4fc563fe7e8878dc472e60c228444281b2d5). 

This triggered flakes due to exhausting database connections that were fixed with https://github.com/sourcegraph/infrastructure/pull/3383. But the flakes are still appearing. 

After taking a deeper look at the problem, I've found that the amount of parallelism that we're using within the go tests is setting those up for flakes. Go tests run as `GOMAXPROCS` packages test binary in parallel, which is then running some tests concurrently. 

The problem is that `GOMAXPROCS * maxDbConns > 200`, so once in a while, those tests will fail. 

So this PR lowers both `GOMAXPROCS` from `15~18` to `10` and `maxDbConns` from `20` to `15`. That's not ideal, but this should reduce further the number of flakes (to I hope, zero, but time will tell).  

## Test plan

- Ran 200 times the `internal/database` tests with various settings
- With the changes in the diff, [they were green on 200 runs](https://buildkite.com/sourcegraph/sourcegraph/builds/156764) and [the integration tests](https://buildkite.com/sourcegraph/sourcegraph/builds/156770) were also green.

2022-06-27 20:19 UTC, bobheadxi requested changes

2022-06-27 20:19 UTC, bobheadxi commented on internal/database/dbtest/dbtest.go
> +	testDB.SetMaxOpenConns(15)
```suggestion
    conns, err := strconv.Atoi(os.Getenv("TESTDB_MAXOPENCONNS"))
    if err != nil || conns == 0 {
        conns = 20
    }
	testDB.SetMaxOpenConns(conns)
```

2022-06-27 20:19 UTC, bobheadxi commented on enterprise/dev/ci/internal/ci/operations.go
> +			bk.Env("GOMAXPROCS", "10"),
```suggestion
			// Max DB connections is set to 200: https://github.com/sourcegraph/infrastructure/blob/main/docker-images/buildkite-agent-stateless/postgresql.conf
			// Because we run tests concurrently, the following must hold to avoid connection issues:
			//
			//   GOMAXPROCS * TESTDB_MAXOPENCONNS < 200
			//
			// We aim a bit below the threshold to be safe.
			bk.Env("GOMAXPROCS", "10"),
			bk.Env("TESTDB_MAXOPENCONNS", "15")
```

2022-06-28 09:20 UTC, burmudar approved these changes

2022-06-28 10:39 UTC, merged