Ak/home recent files panel
sourcegraph/sourcegraph pull request #37791
Opened 2022-06-27 20:51 UTC by AdhamKhalifa

closes #37362
### Description

This feature hypothesizes that showing recently modified files using git history of a user will result in more interaction with the panels, which will help current and new users when they use Sourcegraph.

This work will only affect logged-in users and it goes through a feature flag. The feature includes the following:

-a list of files recently opened or used in repos will be suggested and made visible to the logged-in user. This will be based on the user’s git history. If the user has git history, it will check the recently modified files through git. gitFilesDisplay is where the files are rendered. It creates a list of the files based on the gitSet list and creates a URL for each file and points to the file through git. The file is shown in the form of (git repo’s title > recently modified file’s file path).

## Test plan

The algorithm will be tested by trying the case when the user has no git history, and when the user has git history but doesn't have any recently modified files.

2022-06-28 20:31 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
> -            <table className={classNames('mt-2', styles.resultsTable)}>
You should roll back these changes so that it's using tables instead of a list. Tables make more sense for accessibility here and match the changes made to other panels.

2022-06-28 20:31 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
> +        <div>
A table should also be used here as above.

2022-06-28 20:37 UTC, AdhamKhalifa commented on client/web/src/search/panels/RecentFilesPanel.tsx
> +                                >
I guess this character is for the Link tag?

2022-06-28 20:40 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
> +                                >
You also need to replace it in the compute query so that the search returns it.

2022-06-30 21:48 UTC, limitedmage requested changes
Some suggestions:

- Update the title of the PR to not have `ak` and instead be a relevant commit message with a bit more detail. Eg. `home panels: update Recent Files panel to show recently edited files`

2022-06-30 21:48 UTC, limitedmage commented on yarn.lock
>    dependencies:
Sync with your branch with `main`, changes to this file should be gone.

2022-06-30 21:48 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
> -    const [isLoadingMore, setIsLoadingMore] = useState(false)
This and everywhere else where uses of this was removed (eg lines 105, 146) needs to be added back. This is used for accessibility, so users of screen readers can know if more items are being loaded. (Looks like this removal was from resolving a merge conflict).

2022-06-30 21:48 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
> -
nit: add back removed line

2022-06-30 21:48 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
> +    const gitSet = useMemo(() => {
Looks like this identical to the code in [RepositoriesPanel](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/search/panels/RepositoriesPanel.tsx?L195). Can you factor it out into a custom hook in a new file that both files can use? Maybe also move the definition of `ComputeParseResult` there.

2022-06-30 21:48 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
> +            <table className={classNames('mt-2', styles.resultsTable)}>
Instead of creating a new table here, consider adding some conditional code to `contentDisplay` to use the right `tbody`. This also makes the change in line 222 unnecessary.

2022-06-30 21:48 UTC, limitedmage commented on client/web/src/search/panels/RecentFilesPanel.tsx
>              state={processedResults ? (processedResults.length > 0 ? 'populated' : 'empty') : 'loading'}
Does this also need to change for when users have no search history but do have git history?

2022-07-13 21:18 UTC, limitedmage approved these changes

2022-07-14 17:01 UTC, merged