[SG-37398] - Migrate graphqlbackend.RepositoryResolver to use sourcegraph/log
sourcegraph/sourcegraph pull request #37928
Opened 2022-06-29 12:22 UTC by gitstart-sourcegraph

## Description

Add a logger to schemaResolver, and initialize it with log.Scoped (or logtest where appropriate) wherever schemaResolver is created (unless an existing logger is easily available, in which case that should be used)
Add a logger to RepositoryResolver, and let it be injected from NewRepositoryResolver. Use log.Scoped (or logtest where appropriate) to provide the logger at [all usages of NewRepositoryResolver](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend+NewRepositoryResolver&patternType=literal)
[3 log15 usages inside cmd/frontend/graphqlbackend/repository.go](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Ecmd/frontend/graphqlbackend/repository%5C.go+log15+&patternType=literal) are replaced with calls to the appropriate logger

## Refs
- [SourceGraph Issue](https://github.com/sourcegraph/sourcegraph/issues/36382)
- [GitStart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-37398)
- 
## Test plan
- A good way to test this PR is just to run the branch locally, and open [the issue link](https://github.com/sourcegraph/sourcegraph/issues/36382), compare the changes on the PR and the listed issues. All of them must be fixed
### Creedit cost
- 50 credits

2022-06-29 14:17 UTC, jhchabran commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +		logger:            sglog.Scoped("schemaResolver", ""),
```suggestion
		logger:            sglog.Scoped("schemaResolver", "GraphQL Schema Resolver"),
```

2022-06-29 14:28 UTC, jhchabran commented on cmd/frontend/graphqlbackend/repository.go
> +		r.logger.Error("adding phabricator repo", log.String("callsign", args.Callsign), log.String("name", *args.URI), log.String("url", args.URL))
This can panic if `args.URI` is `nil`, which wasn't a problem before, because the pointer was being passed to `log15` which probably handled `*string` automatically. 

So we need to have a nil check on `log.URI`, something along the lines of 

```
var uri string
if args.URI != nil {
  uri = *args.URI
}

// ... 
r.logger.Error(.., log.String(uri), ...) 
```

I think this can be painful, especially when logging stuff coming from response payloads, which often have `*string` for fields. Will make a quick PR to see how it would look if we had a `log.StringPtr` to handle these cases.

2022-06-29 14:31 UTC, jhchabran commented on enterprise/cmd/frontend/internal/authz/resolvers/repositories.go
> +		resolvers[i] = graphqlbackend.NewRepositoryResolver(log.Scoped("Nodes", ""), r.db, repos[i])
```suggestion
		resolvers[i] = graphqlbackend.NewRepositoryResolver(log.Scoped("repos.nodes", ""), r.db, repos[i])
```

The "nodes" scope doesn't make much sense here, because it's a top level scope, as it's not tied to a particular resolver.

2022-06-29 14:40 UTC, jhchabran commented on enterprise/cmd/frontend/internal/batches/resolvers/changeset.go
> +		repoResolver: graphqlbackend.NewRepositoryResolver(log.Scoped("changesetResolver", ""), store.DatabaseDB(), repo),
```suggestion
		repoResolver: graphqlbackend.NewRepositoryResolver(log.Scoped("batches.changesetResolver", ""), store.DatabaseDB(), repo),
```

Same idea there.

2022-07-05 06:57 UTC, jhchabran requested changes
@gitstart so we came up with the following: 

- use [`log.Stringp`](https://doctree.org/github.com/sourcegraph/log/-/go/-//?id=Stringp) when dealing with string pointers and others, so we don't have to do some nil checks. 
- let's scope the logger within the resolver constructors, so `NewRepoResolver`'s logger is scoped to "repo". See https://github.com/sourcegraph/sourcegraph/pull/37928/files#diff-1b69ec756b8c172dc6c0e13ce47eb8e499a371f4f6141859c8b8624dcf30ec7dR69

2022-07-15 19:16 UTC, closed without merging

2022-07-15 19:20 UTC, bobheadxi commented
@gitstart-sourcegraph was this meant to be closed?

2022-07-15 19:47 UTC, gitstart-sourcegraph commented
> @gitstart-sourcegraph was this meant to be closed?

Yes moved here https://github.com/sourcegraph/sourcegraph/pull/38902