Add compute live preview component
sourcegraph/sourcegraph pull request #38125
Opened 2022-07-01 22:07 UTC by unclejustin

## Test plan

TBD

2022-07-07 16:43 UTC, unclejustin commented
@AlicjaSuska this is ready for design review. You will need to use both storybook and the web preview links to see the "blurry" and fully rendered versions.

Note: this is only for the preview card itself, not the placement on the creation UI screen. Final layout issue regarding how it fits with the rest of the page will be addressed in the issue mentioned above.

- Blurry: in web preview
- Full render in storybook

2022-07-08 00:03 UTC, vovakulikov requested changes
@unclejustin I left a few as I think important questions there. Thanks for implementing this in such a short timeframe though.

2022-07-08 00:03 UTC, vovakulikov commented on client/web/src/enterprise/insights/pages/insights/creation/ComputeLivePreview.tsx
> +                                    getDatumName={(datum: any) => datum.name}
@unclejustin why do we need to use any here? Can we improve generic types in the `getLivePreviewContent` method instead?

2022-07-08 01:06 UTC, unclejustin commented on client/web/src/enterprise/insights/pages/insights/creation/ComputeLivePreview.tsx
> +interface LineChartLivePreviewProps {
WOMP: behold the shame of my copy pasta 🤡

2022-07-08 10:14 UTC, AlicjaSuska commented on client/web/src/enterprise/insights/pages/insights/creation/ComputeLivePreview.tsx
> +                                    getDatumName={(datum: any) => datum.name}
I agree that this example is not the best. Let's improve it:
- add more data series for each group
- change colors so that they align with the default colors in the form

@unclejustin here is the [design](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/Compute-x-Insights%2C-RFC-696%2C-%2337923-%5BReady-fro-dev%5D?node-id=2096%3A18587) for this example chart. Thank you!

@vovakulikov I think that level of 'bluryness' is ok here. It should come across as the bar chart but should be blurred enough so that people don't take it as actual chart and start reading values :)

2022-07-08 10:14 UTC, AlicjaSuska commented on client/web/src/enterprise/insights/components/creation-ui/live-preview/constants.ts
> +        group: 'Sourcegraph',
I agree that this example is not the best. Let's improve it:

add more data series for each group
change colors so that they align with the default colors in the form
@unclejustin here is the [design](https://www.figma.com/file/DqZHetdfqHSVzzWtyfjOmr/Compute-x-Insights%2C-RFC-696%2C-%2337923-%5BReady-fro-dev%5D?node-id=2096%3A18587) for this example chart. Thank you!

@vovakulikov I think that level of 'bluryness' is ok here. It should come across as the bar chart but should be blurred enough so that people don't take it as actual chart and start reading values :)

2022-07-08 10:18 UTC, AlicjaSuska requested changes
@unclejustin thank you for looping me in :)

Please, see my comment about chart visuals in the thread above.

I've also noticed that the name of the insight type is incorrect - should be 'group results' not 'map results'. I've made this change in figma last week after discussions with Felix and Coury.

In addition, I think we should change the URLs we use for different insight types - they do not align with the official naming, but mirror our internal initial working names.

.../compute -> .../group-results
.../search -> .../track
.../capture-group -> .../detect-and-track

If we can't change the track and detect&track types anymore because of our tracking, let's at least change the compute to group-results when we still can. Thank you :)

2022-07-08 17:43 UTC, unclejustin commented on client/web/src/enterprise/insights/components/creation-ui/live-preview/constants.ts
> +        group: 'Sourcegraph',
Thanks @AlicjaSuska! This is very helpful.

2022-07-08 23:59 UTC, unclejustin commented
@AlicjaSuska & @vovakulikov this is ready for re-review.

@vovakulikov I'm having a type problem on `client/web/src/enterprise/insights/pages/insights/creation/ComputeLivePreview.tsx` would you mind taking a look when you have a moment 🙇

2022-07-13 05:29 UTC, vovakulikov commented
@unclejustin I think I solved this problem with types around bar and blur backdrop components. [See this commit](https://github.com/sourcegraph/sourcegraph/pull/38125/commits/b4322f7ad6c9926a33cbb904569cdf1011373002)

A few things that I've noticed during this fix:
- ComputeLivePreview compontent (and its story) shouldn't be stored on the top level in creation directory (live preview was placed there just because we had to share it between different creation pages) compute live preview is unique and it's used only in compute creation UI so it should be under compute creation UI directory. 
- `COMPUTE_MOCK_CHART` constant shouldn't placed inside shared components since it's unuquie compute specific data and this isn't shared in other places. 

These are controversial points, @unclejustin let me know if you're disagree about it. A general thought: it feels like we don't have any rules and structure in our projects that is staring to became a problem since we're getting bigger in terms of UI/logic/shared parts.

2022-07-13 08:45 UTC, vovakulikov approved these changes
@unclejustin I finished the second round of review. Everything is legit, I still left a few notes and questions there, they do not block this PR but I think they are easy enough to fix them in this PR. If you don't have time for them, please create a separate issue for it 😉

2022-07-13 08:45 UTC, vovakulikov commented on client/web/src/enterprise/insights/pages/insights/creation/ComputeLivePreview.tsx
> +    const mapSeriesToCompute = (series: Series<BackendInsightDatum>[]): LanguageUsageDatum[] =>
@unclejustin I think this selector function could be moved out of this component render body call function.

2022-07-13 08:45 UTC, vovakulikov commented on client/web/src/enterprise/insights/pages/insights/creation/compute/components/ComputeInsightCreationContent.tsx
> +function seriesToPreview(
@unclejustin do we need this? I think we can easily change `series` prop type in `ComputeLivePreview` component and remove seriesToPreview selector here.

2022-07-13 08:45 UTC, vovakulikov commented on client/web/src/enterprise/insights/pages/insights/creation/compute/components/ComputeInsightCreationContent.tsx
> +function seriesToPreview(
@unclejustin We have simular approach with selectors in Compute and SearchBased insights forms but this comes from the fact that we have to share live preview component between these forms and we have to have a base series prop for each of form. 

Here we don't need to do this in my opinion and we can have `ComputeLivePreview` with compute specific prop types.

2022-07-13 09:21 UTC, vovakulikov commented on client/web/src/enterprise/insights/pages/insights/creation/compute/components/ComputeInsightCreationContent.tsx
> +    const { repositories, stepValue, allReposMode } = useInsightCreationForm({
@unclejustin I think you should rebase main because in my PR I added compute insights specific form fields without reusing parts from the search-based insight creation form.

2022-07-13 12:06 UTC, AlicjaSuska requested changes
@unclejustin in the preview and in storybook I still see the older version of the chart (with 3 bars).

2022-07-13 23:30 UTC, AlicjaSuska approved these changes
Thank you for making changes @unclejustin All looks good, approved on my part :)

2022-07-13 23:48 UTC, merged