ci: Run with Sentry source map uploading in release build
sourcegraph/sourcegraph pull request #38394
Opened 2022-07-07 10:35 UTC by plibither8

## Test plan

2022-07-18 07:27 UTC, valerybugakov commented on doc/dev/background-information/ci/reference.md
> +- Build and upload sourcemaps to Sentry
We probably want to move it under some operation set for consistency reasons. 
The `Client Checks` set looks like the most suitable one, but according to the comment: 

> If the conditions for the addition of an operation cannot be expressed using the above arguments, please add it to the switch case within `GeneratePipeline` instead.

it should not be used for an optional step. What's the recommendation here, @sourcegraph/dev-experience?

2022-07-18 07:27 UTC, valerybugakov commented on enterprise/dev/ci/internal/ci/operations.go
> +			bk.Env("SENTRY_UPLOAD_SOURCE_MAPS", "1"),
Are [other](https://github.com/sourcegraph/sourcegraph/pull/38391/files) `SENTRY_*` env variables set using Buildkite secrets?

2022-07-18 07:47 UTC, valerybugakov commented on enterprise/dev/ci/internal/ci/operations.go
> +			bk.Env("SENTRY_UPLOAD_SOURCE_MAPS", "1"),
Does it make sense to keep `SENTRY_PROJECT` in secrets too? We might want to upload source maps for other projects (e.g., the existing browser-extension project). Keeping that in mind and the overhead of managing secrets, it may be better to expose `SENTRY_PROJECT` and `SENTRY_ORGANIZATION` using env variables. WDYT?

2022-07-18 07:49 UTC, plibither8 commented on enterprise/dev/ci/internal/ci/operations.go
> +			bk.Env("SENTRY_UPLOAD_SOURCE_MAPS", "1"),
Ahh right! Didn't think of it that way -- you're right! I'll set these in the Buildkite operation itself 😄

2022-07-18 08:58 UTC, valerybugakov approved these changes
LGTM! Let's wait for the input from the DX team 🙂

2022-07-18 16:29 UTC, jhchabran requested changes

2022-07-18 16:29 UTC, jhchabran commented on doc/dev/background-information/ci/reference.md
> +- Build and upload sourcemaps to Sentry
This file is not meant to be edited by hand, but instead generated with `sg generate go`

2022-07-18 16:29 UTC, jhchabran commented on doc/dev/background-information/ci/reference.md
> +- Build and upload sourcemaps to Sentry
I think it's better to leave it as it's currently done, i.e in a switch at the end of the GeneratePipeline func, tied to a release branch. 

It does not relate much semantically with the client tests, it's closer to a build artefact actually.

2022-07-19 06:30 UTC, plibither8 commented
@jhchabran thanks for the reviews! Just wanted to know want you want changed exactly, could catch that from your comments 😅.

> This file is not meant to be edited by hand, but instead generated with `sg generate go`

 Yep, I generated it from that command only 🙂

2022-07-19 09:26 UTC, jhchabran approved these changes

2022-07-19 09:31 UTC, merged