adr: consolidate redis
sourcegraph/sourcegraph pull request #38480
Opened 2022-07-08 13:57 UTC by jhchabran

Follow-up to what has been discussed in the [Backend Crew meeting](https://docs.google.com/document/d/1Y51d863Nuqr9BzbTbwwSF9jes0ro71vB724oc2p8qsQ/edit#bookmark=kix.q3glfa62kub9)

How to review:

1. Check that the wording accurately reflect our decision
2. If you're against the decision, post a comment

## Test plan

n/a it's an adr

2022-07-08 13:59 UTC, eseliger approved these changes
Thanks :)

2022-07-08 13:59 UTC, eseliger commented
cc @nicksnyder

2022-07-08 14:04 UTC, rafax commented
cc @sourcegraph/cloud 
@filiphaftek I remember you mentioning we treat `redis-store` in a different way from `redis-cache` -> it has disk persistence? Assumes data survives restarts?

2022-07-08 15:50 UTC, bobheadxi approved these changes

2022-07-08 16:04 UTC, danieldides approved these changes

2022-07-08 17:15 UTC, daxmc99 requested changes

2022-07-08 17:15 UTC, daxmc99 commented on doc/dev/adr/1657287546-consolidate-redis-store-and-redis-cache-in-a-single-instance.md
> +The original reasoning for having two has been lost over time. Regardless of the original context, right now there are no advantages for having two instances instead of one.
This is a classic example of Chesterson's fence or a [load bearing poster](https://www.youtube.com/watch?v=QRVExJZKIT8). I don't think we can remove this _until_ we understand why we built it in the first place.

2022-07-08 17:20 UTC, daxmc99 commented
Since each image has a slightly different config (`store` returning an error once it becomes full, and `cache` acting as a LRU) what is the proposed path forward? A single redis instance or two separate ones with one config?  I think this would be fine if we use the `cache` config and ensure that no information needs to be backed up there permanently.

2022-07-08 19:21 UTC, nicksnyder commented
It seems like we can use a single instance to store both evictable and non-evictable data by using `volatile-lru` or `volatile-lfu` evicition policy and then tagging evicable keys with the `expire` field set to `true`.
https://redis.io/docs/manual/eviction/#eviction-policies

2022-07-08 19:23 UTC, nicksnyder commented
The redis docs also say this

>The volatile-lru and volatile-random policies are mainly useful when you want to use a single instance for both caching and to have a set of persistent keys. However it is usually a better idea to run two Redis instances to solve such a problem.

2022-07-11 06:09 UTC, jhchabran commented on doc/dev/adr/1657287546-consolidate-redis-store-and-redis-cache-in-a-single-instance.md
> +The original reasoning for having two has been lost over time. Regardless of the original context, right now there are no advantages for having two instances instead of one.
Thanks for bringing your concern 🙏 I understand your point, though we did try to understand why it was like this and judged that we could address the two use cases with a single instance and multiple database. We prioritised moving forward. 

Please note that this ADR only materialises the collective decision from the backend crew meeting, were we to discover that it's a freaking bad idea during implementation, this would be roll backed instantly. 

In retrospective, asking for help explicitly understanding the original reasoning would have been better 👍

2022-07-11 07:10 UTC, jhchabran commented
> what is the proposed path forward?  

@daxmc99, this is an ADR, so the goal here is to simply capture the decision, the path forward in terms of technical details if left out on purpose. It is to be addressed in the tracking issue.

It basically says to everyone that yes, there's an agreement that we want to dig into this and it logs a trace of our reasoning at that time. Were we to discover it's not a good idea at all, another ADR will be logged to reflect that, with the proper context. In the end, ADRs fix the issue of not being able to understand a previous decision, precisely avoiding Chesterson's fence scenarios. 

I hope this clarifies that this issue is not a _YOLO let's blindly drop a redis_ 😄:pray:

2022-07-11 09:34 UTC, keegancsmith commented on doc/dev/adr/1657287546-consolidate-redis-store-and-redis-cache-in-a-single-instance.md
> +The original reasoning for having two has been lost over time. Regardless of the original context, right now there are no advantages for having two instances instead of one.
We have two because we configured one to evict data as a cache, and the other to act as a store which would persist to disk and not evict. If I am not mistaken the only thing in the store is session data. We could just use postgres and just deprecate store.

2022-07-11 13:43 UTC, efritz commented on doc/dev/adr/1657287546-consolidate-redis-store-and-redis-cache-in-a-single-instance.md
> +The original reasoning for having two has been lost over time. Regardless of the original context, right now there are no advantages for having two instances instead of one.
@daxmc99 For the record, this was discussed in last week's backend crew meeting. Out of the attendants of that meeting I've had the longest tenure, and the choice of two Redii pre-existed my joining. I think the "original reasoning being lost" was from me not having a solid answer of why we had two instances in the first place, but I'm fairly confident that the original reasoning (we used to use redis-store for a job queue in the early days of LSIF, so there was higher usage) is no longer relevant.

I've also talked to @kevinwojo about this earlier last week, and he said that upgrade/restoration of instances have been made difficult specifically because of malformed Redis data that's hard to track down. He was on board with reducing the complexity here (and stated that the flushing of session data is probably preferable over a bad upgrade).

But thank you **so much** for referring to this phenomenon, because I feel like it's an extremely easy trap to fall into.

2022-07-11 16:38 UTC, daxmc99 commented on doc/dev/adr/1657287546-consolidate-redis-store-and-redis-cache-in-a-single-instance.md
> +The original reasoning for having two has been lost over time. Regardless of the original context, right now there are no advantages for having two instances instead of one.
Your comments about this previously are what lead me to discover it, so thank you! 
I think it is fine to comment with something like "as best we can tell, Redis was setup to do xyz".
My goal was to discourage recording decisions where we cannot trace back the original decision or do some best effort investigation of why it was made. 

I think the discussions above are proof that deep thought has been devoted to avoiding this problem

2022-07-11 16:46 UTC, daxmc99 approved these changes
> this is an ADR, so the goal here is to simply capture the decision, the path forward in terms of technical details if left out on purpose. It is to be addressed in the tracking issue. 

Thanks for clarifying!

2022-07-11 17:37 UTC, bobheadxi requested changes
Right now the ADR states:

> The original reasoning for having two has been lost over time. Regardless of the original context, right now there are no advantages for having two instances instead of one. 

The original reasoning has been brought up a few times in review comments - we should make sure the ADR captures the original reasoning, and why it no longer stands

2022-07-11 20:01 UTC, jhchabran commented
> One final note: I think multiple folks including me got the impression early on that this was a let's drop redis 

Yes, the wording wasn't really precise on my end, my mistake. 

@daxmc99 Our exchange made me think, whether or not ADR are becoming a thing that we often use, making the intention explicit in the PR description would have saved a lot of time here.

2022-07-11 23:02 UTC, daxmc99 commented
I think some additional notes on our ADR doc page would he helpful as well. 
(Not to start another thread but FWIW I liked Github discussions)

2022-07-11 23:03 UTC, daxmc99 approved these changes

2022-07-11 23:20 UTC, bobheadxi approved these changes
I like the new framing - why we have 2, and the hopeful end state (we want to end with 1 for the sake of X reason). Thanks for the update!

2022-07-12 06:57 UTC, merged