REST API for interacting with Github webhooks
sourcegraph/sourcegraph pull request #38542
Opened 2022-07-11 09:34 UTC by susantoscott

Created a library to create, list, find, and delete Github webhooks. This will be used to automate the creation of Github webhooks for repository syncing.

## Test plan
go test -run TestGitHubWebhooks
Given that we are creating webhooks to a real repo, a personal access token is needed to build a webhook for my repo

2022-07-14 15:00 UTC, ryanslade commented on internal/repos/webhooks/github.go
> +func (g GithubWebhookAPI) ListSyncWebhooks(ctx context.Context, repoName string, token string) ([]Payload, error) {
It's more common to use pointer receivers, can you change them all to:

```go
func (g *GithubWebhookAPI) Foo()
```

2022-07-14 15:00 UTC, ryanslade commented on internal/repos/webhooks/github.go
> +type GithubWebhookAPI struct {
nit: It's GitHub, not Github

If I don't point it out, @unknwon will 😄

2022-07-14 15:09 UTC, ryanslade commented on internal/repos/webhooks/client.go
> +package githubwebhook
nit: We probably want the directory name to also be `githubwebhooks`

2022-07-14 15:10 UTC, ryanslade commented on internal/repos/webhooks/testing.go
> +package githubwebhook
If this only used for tests you should append `_test.go` to the filename so that it doesn't get compiled into non-test code. In that case, maybe call it `helpers_test.go`

2022-07-14 15:11 UTC, ryanslade commented on internal/repos/webhooks/github.go
> +func urlBuilder(repoName string) (newUrl string, err error) {
Can you add a couple of small tests for these two methods?

2022-07-14 15:12 UTC, ryanslade commented on internal/repos/webhooks/github.go
> +func urlBuilder(repoName string) (newUrl string, err error) {
nit: We usually don't use named return values unless there's a really good reason to do so.

2022-07-14 15:13 UTC, ryanslade commented on internal/repos/webhooks/github.go
> +	return newUrl, nil
nit: It's idiomatic go to avoid `else` in most places and return early instead:

```go
    if u.Host == "github.com" {
		return fmt.Sprintf("https://api.github.com/repos%s/hooks", u.Path)
	}
    return fmt.Sprintf("https://%s/api/v3/repos%s/hooks", u.Host, u.Path)
```

2022-07-14 15:45 UTC, mollylogue commented on internal/repos/webhooks/github.go
> +	client *Client
So, I think we'd ideally want to be using the existing V3 [client](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/extsvc/github/v3.go?L30) which is already set up to make API calls to Github. It would probably simplify this a good bit.

2022-07-14 15:54 UTC, mollylogue commented on internal/repos/webhooks/github.go
> +			Url:          fmt.Sprintf("%s/enqueue-repo-update", targetUrl),
This `/enqueue-repo-update` endpoint is probably not what we want our webhooks to publish to, since it's an internal endpoint so it isn't exposed to the internet. We already have public endpoints for webhooks for github, which include validating the secret from the webhook (see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/github_webhooks.go?L160)). [This](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@84865f790625b44d64bf39af1f6c0a61bf9f395d/-/blob/cmd/frontend/webhooks/github_webhooks.go?L41) is the handler for the endpoint, which currently deals w/ batch changes events, and [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/httpapi/router/router.go?L66) is where the actual endpoint is defined. You'll want to use this endpoint for publishing webhook events, and expand the handling within that endpoint to recognize the correct type of event and call `enqueueRepoUpdate`.

2022-07-15 05:33 UTC, unknwon commented
I'm curious what's the reasoning for not putting these changes in https://github.com/sourcegraph/sourcegraph/blob/main/internal/extsvc/github/v3.go?

2022-07-21 08:07 UTC, ryanslade reviewed
Good progress! Left a few, mostly small comments

2022-07-21 08:07 UTC, ryanslade commented on internal/extsvc/github/v3.go
> +		if parts[len(parts)-1] == "github-webhooks" {
Worth checking here that len(parts) > 0 just to be safe otherwise you can end up with a panic. 

If len(parts) == 0 then just return 0, false

2022-07-21 08:07 UTC, ryanslade commented on internal/extsvc/github/v3.go
> +	if err != nil && err.Error() != "EOF" {
```suggestion
	if err != nil && err != io.EOF {
```

2022-07-21 08:07 UTC, ryanslade commented on internal/extsvc/github/v3.go
> +	url := fmt.Sprintf("%s/tests", u)
This looks like something left over from testing?

2022-07-21 08:07 UTC, ryanslade commented on internal/repos/github_handler.go
> +package repos
Do we need any of this code in this PR? This looks related to future work and doesn't have any tests.

2022-07-21 08:07 UTC, ryanslade commented on internal/extsvc/github/v3_test.go
> +var repoName = "ghe.sgdev.org/milton/test"
Might be worth also testing against github.com to make sure there are no API differences

2022-07-22 09:06 UTC, ryanslade commented
@susantoscott Before asking other's for a review, it's worth going back over the previous review comments and marking all the ones you've dealt with as resolved.

2022-07-22 09:42 UTC, susantoscott commented on internal/extsvc/github/v3.go
> +	url := fmt.Sprintf("%s/tests", u)
This is intentional; it mocks GitHub's response to a push event from the user

2022-07-22 10:39 UTC, ryanslade commented on internal/extsvc/github/v3.go
> +	url := fmt.Sprintf("%s/tests", u)
So calling this method will tell GitHub to send us a webhook?

2022-07-22 10:41 UTC, susantoscott commented on internal/extsvc/github/v3.go
> +	url := fmt.Sprintf("%s/tests", u)
Not really a webhook, but GitHub will send a details like the webhook ID, repo information, etc.

2022-07-22 10:47 UTC, ryanslade commented on internal/extsvc/github/v3.go
> +	url := fmt.Sprintf("%s/tests", u)
If we're using it somewhere I'd leave it in, if not, then let's remove it as it's a little confusing why it's included.

2022-07-26 08:12 UTC, indradhanush requested changes
Thank you for pushing this through. I loved that you added a direct link to the API docs for each method on the client that you're adding. ❤️

2022-07-26 08:12 UTC, indradhanush commented on internal/extsvc/github/v3.go
> +	return c.request(ctx, req, result)
See comment below.

2022-07-26 08:12 UTC, indradhanush commented on internal/extsvc/github/v3.go
> +	resp, err := c.delete(ctx, url, "", &result)
Since there is no `result` to be parsed in the response, we can change the signature of the `delete` method to not need the `result any` argument. Instead in the function `delete()` we can directly pass `struct{}{}` where we call `.request()`.

See comment above.

2022-07-26 08:12 UTC, indradhanush commented on internal/extsvc/github/v3.go
> +		return false, errors.Newf("expected 204 status code, got %d", resp.statusCode)
Nit: `expected status code 204, got %d` is consistent with the error string format.

2022-07-26 08:12 UTC, indradhanush commented on internal/extsvc/github/v3.go
> +	return fmt.Sprintf("https://%s/api/v3/repos%s/hooks/%d", u.Host, u.Path, hookID), nil
Not an issue, but I have a slight confusion if the API URL is always `api.github.com` even for GitHub Enterprise Cloud (note that this different from GitHub enterprise). Something to cross check. I do not remember this clearly.

2022-07-26 08:12 UTC, indradhanush commented on internal/extsvc/github/v3_test.go
> +
Can you make these into separate test cases? The issue here right now is that they're not isolated from each other. You can nest `t.Run()` inside another `t.Run()` and they will be run as separate test cases. This ensures that even if one fails, the other will run nevertheless and is treated as a separate test failure.

2022-07-26 09:04 UTC, susantoscott commented on internal/extsvc/github/v3.go
> +	return fmt.Sprintf("https://%s/api/v3/repos%s/hooks/%d", u.Host, u.Path, hookID), nil
Yes it's the same. I've linked the docs for both the GitHub Enterprise Cloud and GitHub Enterprise Server in the docstrings for the functions.

2022-07-26 09:39 UTC, susantoscott commented on internal/extsvc/github/v3_test.go
> +
Resolved by using t.Error() instead of t.Fatal()

2022-07-26 11:11 UTC, indradhanush approved these changes
🚀

2022-07-26 11:12 UTC, merged