codeintel: alert when all executor jobs are failing
sourcegraph/sourcegraph pull request #38767
Opened 2022-07-13 19:33 UTC by Strum355

Creates alert for executors error rate that alerts when the rate of errors is 100%, indicating some global misconfiguration (as happened before with src-cli related issues).

The alert is a bit special in that it uses a different query to the panel, one based on [`last_over_time`](https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time) aggregate. We do this as we dont want the alert to mark itself as resolved if there happens to be a period over the defined window where there are _no_ auto indexing jobs (aka when the error rate is "technically" < 100%). 

The screenshot below illustrates how the alert query maintains the last value over a predefined window, so that if no executor jobs are processing but over the error rate was 100% before, we will continue alerting as the absence of running jobs does not imply the issue is resolved.

![image](https://user-images.githubusercontent.com/18282288/178816415-d456432e-0150-49e1-a131-175c7a8c8684.png)

Closes https://github.com/sourcegraph/sourcegraph/issues/30494

## Test plan

Only modifies dashboards/alerts, n/a

2022-07-13 19:37 UTC, efritz commented on monitoring/monitoring/monitoring.go
> +	// with %%[1]s.
This seems a bit brittle, but I see why it's done (you want to supply the lookback window at a different level of abstraction than the alert query). Is it possible to make it type-impossible to construct an alert that expects a lookback query without supplying a value (or at least using a default value [here](https://github.com/sourcegraph/sourcegraph/pull/38767/files?diff=split&w=1#diff-4132060621aa0b48b1ada84cd9c0fc0984c98250bfce3fe78d4f15eb5d8b39f6R333))?

2022-07-13 19:39 UTC, bobheadxi requested changes

2022-07-13 19:39 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	lookbackWindow time.Duration
This sounds super fragile - I think if `AlertQuery` is used, that should be treated as a hard override on alerts, i.e. no options are applied at all

2022-07-13 19:39 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	AlertQuery string
We should move this to `ObservableAlertDefinition` with `rawQuery`, then the API would be:

```go
monitoring.RawAlert(query).For(time.Hour).GreaterOrEqual(100),
```

2022-07-13 19:41 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	// with %%[1]s.
Agreed that this sounds super fragile, but I think it would be best to not do this for now

2022-07-13 19:42 UTC, Strum355 commented on monitoring/monitoring/monitoring.go
> +	AlertQuery string
Im having a bit of difficulty seeing how this is the right place for this case (too many abstraction layers, my head :exploding_head: ). Id like to have this defined at the same place as the panel query, as this is where we have the panel query being built 
https://github.com/sourcegraph/sourcegraph/pull/38767/files#diff-38dd11ae9cda5810bba1baabf511ec68b1ce7f90622093c797dc3e2fc676c889R138

2022-07-13 19:43 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	// with %%[1]s.
> Is it possible to make it type-impossible to construct an alert that expects a lookback query without supplying a value

This would be an alternative as well, e.g. with a new `observableLookbackAlertDefinition` that you can only get on `WithLookback` - but that still has the issue of requiring a perfectly crafted raw query

2022-07-13 19:45 UTC, efritz commented on monitoring/monitoring/monitoring.go
> +	AlertQuery string
@bobheadxi In this particular example the alert query will be the same for anything using this panel - the only thing that changes is the threshold.

2022-07-13 19:46 UTC, efritz commented on monitoring/monitoring/monitoring.go
> +	// with %%[1]s.
@Strum355 Might be good to just hard-code the lookback into the error rate panel alert definition for now. I think the other comment thread is a higher impact thing to solve up-front (and we can always re-parameterize the lookback later). I think this will be a bit specific to error rate alerts, though.

2022-07-13 19:47 UTC, Strum355 commented on monitoring/monitoring/monitoring.go
> +	AlertQuery string
I do like the idea of having the alert done at the point _above_ as rob illustrated, but not in the sense of supplying the query at that high a level, as the panel query is lower

2022-07-13 19:49 UTC, efritz commented on monitoring/monitoring/monitoring.go
> +	AlertQuery string
Yeah I agree with @Strum355's take here, but not 100% clear how to define it this way.

2022-07-13 19:49 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +	AlertQuery string
> too many abstraction layers, my head 🤯

Agreed on that 😆 

From the other thread:

> Might be good to just hard-code the lookback into the error rate panel alert definition for now

+1, this is the gist of the other thread as well - and in the interest of that, is why I suggest it be placed on the alert type itself, rather than the panel type - I would favour explicitness, i.e. "for this _alert_ I am doing something very different", plus at the end of the day that is what we are overriding here

2022-07-18 16:54 UTC, Strum355 commented on monitoring/monitoring/monitoring.go
> +	AlertQuery string
Updated the PR to (hopefully) address this. Spent too much time trying various approaches so Im just gonna go with this :laff:

2022-07-18 16:59 UTC, Strum355 commented
Added alert queries to the documentation too 
![image](https://user-images.githubusercontent.com/18282288/179536118-9c1896f7-54c4-421d-91ef-a496c9f58551.png)

2022-07-19 02:20 UTC, bobheadxi approved these changes
Some minor details about naming and the generated output, but otherwise LGTM :)

2022-07-19 02:20 UTC, bobheadxi commented on monitoring/monitoring/monitoring.go
> +func (a *ObservableAlertDefinition) Query(query string) *ObservableAlertDefinition {
```suggestion
// CustomQuery sets a different query to be used for this alert instead of the query used
// in the Grafana panel. Note that thresholds, etc will still be generated for the panel, so
// ensure the panel query still makes sense in the context of an alert with a custom
// query.
func (a *ObservableAlertDefinition) CustomQuery(query string) *ObservableAlertDefinition {
```

2022-07-19 02:20 UTC, bobheadxi commented on monitoring/monitoring/documentation.go
> +Query: %s
```suggestion
Custom alert query: %s
```

2022-07-19 15:10 UTC, merged