emit SCIP from syntect
sourcegraph/sourcegraph pull request #39264
Opened 2022-07-21 21:26 UTC by tjdevries

## Test plan

- [ ] Multi-byte stuff
- [ ] other languages
- [ ] more files
- [ ] etc :)

2022-07-22 06:05 UTC, olafurpg reviewed
This looks great!

2022-07-26 06:40 UTC, olafurpg requested changes

2022-07-26 06:40 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__multibyte.cs.snap
> +//            ^ PunctuationBracket
Should this be `PunctuationDelimiter` instead of `PunctuationBracket`? From scip.proto

```proto
// `;` `.` `,`
PunctuationDelimiter = 2;
// (), {}, [] when used syntactically
PunctuationBracket = 3;
```

2022-07-26 06:40 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__multibyte.cs.snap
> +//                    ^ PunctuationBracket
I intuitively expected the `StringLiteral` occurrence to cover all characters of the string, including the double quotes. The `PunctuationBracket` syntax kind should only be used for the characters `{([])}` and `PunctuationDelimiter` should be used for `;,.=`

2022-07-26 06:40 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__multibyte.cs.snap
> +//              ^ IdentifierKeyword
I expected this to be a delimiter
```suggestion
//              ^ PunctuationDelimiter
```

Alternatively, I'm fine with dropping all punctuation occurrences, I don't think they add much value to syntax highlighting. JetBrains product don't seem to give them unique colors, except commas that we can add in a separate PR

![CleanShot 2022-07-26 at 08 34 15@2x](https://user-images.githubusercontent.com/1408093/180939780-5abd7614-f6f9-4ef9-913d-5288e27eb63a.png)
![CleanShot 2022-07-26 at 08 37 19@2x](https://user-images.githubusercontent.com/1408093/180939833-523819f9-5457-49d1-936f-956fafa6fa99.png)

2022-07-26 16:57 UTC, tjdevries commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__multibyte.cs.snap
> +//              ^ IdentifierKeyword
this file got messed up cause it thought it was go -- should look a lot different now

2022-07-26 18:16 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__func.go.snap
> +//                      ^^^ IdentifierBuiltin
FWIW, SCIP has `IdentifierNull`, but `IdentifierBuiltin` works as well

2022-07-26 18:16 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__larger.cs.snap
> +              var markup = new Regex(@"\s\s+").Replace(component.Markup, "").Trim();
The `Regex` identifier is missing an occurrence

2022-07-26 18:16 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_sciptect__test__.__multibyte.cs.snap
> +//              ^ IdentifierKeyword
We still have `PunctuationBracket` for the open/close quotes. I think it would make sense to drop those in favor of having the `StringLiteral` cover the entire string (including quotes)

2022-07-26 18:17 UTC, olafurpg approved these changes
The comments are mostly for improvements that we can do in a separate PR. LGTM 👍 since there's already a ton of great improvements in the diff that we can go ahead and merge. It should be safe to merge this since it only adds the new `/scip` endpoint

2022-07-26 19:35 UTC, fkling commented
This doesn't actually call the "sciptect" implementation from the HTTP endpoint yet, right? Or am I missing something? How do you plan to decide between using treesitter and sciptect (or how/where do you do that if I'm missing it)?

2022-07-27 09:46 UTC, olafurpg reviewed
@fkling this PR only updates syntax-highlighter, and we can followup later by adding support to actually start using the new `/scip` endpoint

2022-07-27 09:46 UTC, olafurpg commented on docker-images/syntax-highlighter/src/main.rs
> +    match sg_syntax::scip_highlight(q.into_inner()) {
IIUC, the `/scip` endpoint doesn't use syntect yet. Should we add a new property to `SourcegraphQuery` to allow the client to determine whether to use treesitter or syntect?

2022-07-29 03:54 UTC, tjdevries commented
Ok @fkling / @olafurpg I connected all the endpoints for Codemirror and tried to separate out as much logic as I could for the old blob view so that I we could have two separate code paths as much as possible (without directly copying & pasting tons of stuff). Let me know if I did the graphql stuff right.

I ran this locally and was able to try:
- code mirror w/out tree-sitter
- code mirror w/ tree-sitter
- no codemirror w/out tree-sitter
- no codemirror w/ tree-sitter

and got the results I was expecting. However, there is definitely quite a bit of work left to twiddle the highlighting bits (which we could do in this PR or just do in a follow PR, as that's pretty easy to do).

I won't be here friday, but we can probably merge this monday (assuming no one sees anything that looks off to them)

2022-07-29 10:27 UTC, olafurpg reviewed
I got this working locally 👍 The only blocking questions we should resolve before merging relate to the new GraphQL endpoint. Is this an API we are comfortable supporting indefinitely? Are the names future proof and self-explanatory?

LGTM but will leave it to somebody else to stamp an approval since I won't be around to comment on PRs until I'm back from PTO.

2022-07-29 10:27 UTC, olafurpg commented on cmd/frontend/graphqlbackend/schema.graphql
> +    scip: String!
What do you think about including the encoding in the field name? That allows us to return a more efficient encoding in the future.
```suggestion
    base64_scip: String!
```

2022-07-29 10:27 UTC, olafurpg commented on cmd/frontend/internal/highlight/highlight.go
> +		fmt.Println("=============================")
Delete printlns
```suggestion
```

2022-07-29 10:27 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/syntect_files/func.go
> +package main
It would be good to add a few additional scip/syntect snapshot files for other common language:

- json
- js
- ts
- java
- python
- yaml

2022-07-29 10:28 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/syntect_files/func.go
> +package main
In particular, JSON could use more love 
![CleanShot 2022-07-29 at 12 28 17](https://user-images.githubusercontent.com/1408093/181740443-2e9fcce2-328d-49fa-a639-f476d454ad06.png)

It's totally fine to address the actual colors with a separate PR, but I think it's a good idea to commit snapshots today to document the current behavior.

2022-07-29 19:43 UTC, fkling commented
Sorry, I won't get to reviewing this anymore today. I'll read up on some GraphQL schema design best practices and come back to this on Monday. I almost think we don't want to introduce a new field for that, at least not this way.
We can also remove the GraphQL changes for now and just merge the highlighting changes.

2022-08-01 18:12 UTC, fkling commented
Alright, I didn't actually end up reading too much about GraphQL. On the other PR you said you don't know how important backwards compatibility is and I agree. Still, I think we already have all the fields we need (`highlight {html, lsif}`) we would just have to update the implementation not generate both the frontend to request only one or the other.

If you don't want to look into that I'm happy to do it. In that case we can merge this PR without the GraphQL changes.

The PR is still in draft mode, is there anything else you want to do? I can't comment on the Rust implementation unfortunately.

2022-08-02 20:10 UTC, tjdevries commented on docker-images/syntax-highlighter/crates/sg-syntax/src/sg_sciptect.rs
> +        scope_mapping.insert("punctuation".to_string(), SyntaxKind::PunctuationBracket);
We can handle this dicussion more here: https://github.com/sourcegraph/scip/issues/78

2022-08-02 20:11 UTC, tjdevries commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/syntect_files/func.go
> +package main
Added a bunch of examples and fixed more common cases

2022-08-11 12:59 UTC, fkling commented
@tjdevries I guess this can be closed?

2022-08-14 01:29 UTC, closed without merging