[SG-37914] Extract bootstrap style import `buttons`
sourcegraph/sourcegraph pull request #39286
Opened 2022-07-22 05:59 UTC by gitstart-sourcegraph

## Description
Extract / Remove usage of bootstrap's style sheet import on codebase.

## Success criteria
- Bootstrap button import is removed from `client/branded/src/global-styles/index.scss`
- Migrate remaining usage of `btn`, `btn-*` classes to wildcard component.

## Implementation Detail

- [x] Migrate `.btn-icon` usage to `<Button variant="icon">` 
- [x] Migrate `.btn-link` usage to `<ButtonLink />`, if it's not a good fit, migrate to `<Button variant="link" />`
- [x] Migrate `.btn-block` usage to `<Button display="block" />`
- [x] Migrate remaining usage of `<button ...>` on codebase to wildcard `<Button />` component.
- [x] Remove usage of `@import 'bootstrap/scss/buttons'`
- [x] Verify there are no UI diff as a result of any of the steps above.

### Refs
[Gitstart ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-37914)
[SG Issue](https://github.com/sourcegraph/sourcegraph/issues/37914)

## Test Plan
- Identify migrated usage of bootstrap class.
- Verify that they have no UI diff as a result of migrations carried out in this PR.
   - To test ```client/web/src/org/members/AddMemberToOrgModal.tsx```   and ```client/web/src/org/members/InviteMemberModal.tsx```
      - open ```client/web/src/org/area/routes.tsx``` and comment out ```Line 25  -  the condition for settings/members``` 
      - go to ```/organizations/sourcegraph/settings/members``` on the web app.

## Links
- [UserCodeHosts.tsx](http://localhost:3080/welcome)
- TourTask.tsx in storybook
- [HomeTab.tsx](http://localhost:3080/github.com/sourcegraph/sourcegraph)

2022-07-27 08:44 UTC, gitstart-sourcegraph commented on client/web/src/api/graphiql-theme.scss
> -        @extend .btn-primary;
A side effect to removing this, shows on hover state background shown in quick demo below.
Want to get your thoughts on proffered approach of resolving this.
1. Define rules here to resolve diffs.
2. Migrate use case to wildcard's button component.

CC: @valerybugakov

2022-07-27 09:57 UTC, valerybugakov commented on client/web/src/api/graphiql-theme.scss
> -        @extend .btn-primary;
@gitstart-sourcegraph, we should preserve the current behavior, and we also want to reuse existing styles instead of duplicating them in the graphiql-theme file. Do you have ideas on how to implement that?

2022-07-27 11:29 UTC, gitstart-sourcegraph commented on client/web/src/api/graphiql-theme.scss
> -        @extend .btn-primary;
Yea, so am considering the option of hiding default graphpiql button and add our Button with our design,
then trigger click on default graphiql button when user clicks on our button.
Does it make sense?.

2022-07-29 04:02 UTC, valerybugakov commented on client/web/src/api/graphiql-theme.scss
> -        @extend .btn-primary;
@gitstart-sourcegraph, would it be possible to render `<Button as={GraphiQL.Button}  />` [here](https://github.com/sourcegraph/sourcegraph/blob/main/client/web/src/api/ApiConsole.tsx#L171) to apply our styles explicitly?

2022-07-29 08:51 UTC, gitstart-sourcegraph commented on client/web/src/api/graphiql-theme.scss
> -        @extend .btn-primary;
I see `GraphiQL.Button` does not support `className` prop [Ref here](https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/ExecuteButton.tsx), which might be a limitation to using the suggested `<Button as={GraphiQL.Button} />`, kindly take a look at the workaround in [this  commit](https://github.com/sourcegraph/sourcegraph/pull/39286/commits/21ebad64ec4538951b24da084055821363976594).

2022-08-01 05:35 UTC, valerybugakov requested changes

2022-08-01 05:35 UTC, valerybugakov commented on client/web/src/api/ApiConsole.module.scss
> +:global(.graphiql-container) .toolbar-button {
Do we need the `.graphiql-container` class to increase selector specificity?

2022-08-01 05:35 UTC, valerybugakov commented on client/web/src/codeintel/ReferencesPanel.tsx
> +                                    className={classNames('p-0', styles.sideBlobCollapseButton)}
Could you explain why we can remove it here even though we don't use `variant="icon"`?

2022-08-01 05:35 UTC, valerybugakov commented on client/jetbrains/webview/src/search/input/JetBrainsToggles.module.scss
> +    border: none;
Aren't these styles applied anyway by the `variant="icon"` prop?

2022-08-01 05:35 UTC, valerybugakov commented on client/web/src/api/ApiConsole.tsx
> +                                variant="secondary"
Nice, that's the way to go 👍

2022-08-01 05:35 UTC, valerybugakov commented on client/web/src/enterprise/code-monitoring/components/logs/CollapsibleDetailsWithStatus.tsx
> +            <Button onClick={toggleExpanded} className={styles.expandButton}>
Should we add `variant="icon" display"block"` here?

2022-08-01 05:35 UTC, valerybugakov commented on client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.tsx
> +                <Button onClick={toggleExpanded} className={classNames('d-block', styles.expandButton)}>
Would it be possible here to use `display="block"` and remove the `d-block` global class?

2022-08-01 05:35 UTC, valerybugakov commented on client/web/src/org/members/InviteMemberModal.tsx
> +                <Button className={styles.closeButton} onClick={dismissWithLogging}>
`variant="icon"`?

2022-08-01 05:35 UTC, valerybugakov commented on client/branded/src/global-styles/index.scss
> -@import 'bootstrap/scss/buttons';
It means that the VSCode package won't have access to these global styles, but [we still use many global button classes there](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+btn-+lang:typescript+rev:contractors/SG-37914.1&patternType=literal). Could you also migrate them as a part of this PR?

We also use some global button classes in the browser extension. Let me know if you have ideas on removing them without affecting the UI!

2022-08-02 06:31 UTC, gitstart-sourcegraph commented on client/web/src/api/ApiConsole.module.scss
> +:global(.graphiql-container) .toolbar-button {
Yes. Ordinarily `color` rule is overriden by `.graphiql-container button` selector.

2022-08-02 06:59 UTC, gitstart-sourcegraph commented on client/web/src/codeintel/ReferencesPanel.tsx
> +                                    className={classNames('p-0', styles.sideBlobCollapseButton)}
We didn't add the `icon` variant as a substitute for `btn-icon` because `btn-icon` className was redundant and removing it makes no visual difference. WDYT?

BEFORE ==>
![Screenshot 2022-08-02 at 7 58 29 AM](https://user-images.githubusercontent.com/89894075/182311837-28c2cb70-9f19-4d46-9268-dbadaf2fad0e.png)


AFTER <==
![Screenshot 2022-08-02 at 7 57 03 AM](https://user-images.githubusercontent.com/89894075/182311609-1185399b-efc4-44b3-ac35-08345d749256.png)

2022-08-02 07:15 UTC, gitstart-sourcegraph commented on client/jetbrains/webview/src/search/input/JetBrainsToggles.module.scss
> +    border: none;
They should, however they aren't applied by `variant="icon"`, 
This is what we have with just `variant="icon"` binded on code.
Notice on the devtool, that the icon style className from wildcard isn't binded tot he DOM element, I wonder why that is. WDYT?.
![Screenshot 2022-08-02 at 8 10 54 AM](https://user-images.githubusercontent.com/89894075/182314404-d4a0687b-014c-4942-b138-ce6707d71995.png)

2022-08-02 07:59 UTC, gitstart-sourcegraph commented on client/web/src/org/members/InviteMemberModal.tsx
> +                <Button className={styles.closeButton} onClick={dismissWithLogging}>
Here we are able to reproduce existing UI without `btn-icon` and `variant="icon"`, see comparison below, WDYT?

With `btn-icon`
![Screenshot 2022-08-02 at 8 57 47 AM](https://user-images.githubusercontent.com/89894075/182323105-e2d39550-4930-4bd7-a7fb-4bbfcee43361.png)

With `variant="icon"`
![Screenshot 2022-08-02 at 8 57 23 AM](https://user-images.githubusercontent.com/89894075/182323196-7150de63-af01-4b38-a4a5-5ef1e1c08fb4.png)

Without `btn-icon` && `variant="icon"`
![Screenshot 2022-08-02 at 8 57 03 AM](https://user-images.githubusercontent.com/89894075/182323301-af79d60d-edc3-4f10-959d-79b810e11990.png)

2022-08-02 10:55 UTC, valerybugakov commented on client/jetbrains/webview/src/search/input/JetBrainsToggles.module.scss
> +    border: none;
Do you use `JetBrainsSearchBox.story.tsx` to inspect these changes? I think it lacks `<WildcardThemeContext.Provider value={{ isBranded: true }}>` which is required for branded styles. Could you try wrapping the story into it to check if it fixes the issue?

2022-08-02 10:56 UTC, valerybugakov commented on client/web/src/org/members/InviteMemberModal.tsx
> +                <Button className={styles.closeButton} onClick={dismissWithLogging}>
Looks good, thanks!

2022-08-02 10:57 UTC, valerybugakov commented on client/web/src/codeintel/ReferencesPanel.tsx
> +                                    className={classNames('p-0', styles.sideBlobCollapseButton)}
Looks good, thanks!

2022-08-02 11:10 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/code-monitoring/components/logs/CollapsibleDetailsWithStatus.tsx
> +            <Button onClick={toggleExpanded} className={styles.expandButton}>
Same as above

BEFORE ==>
![Screenshot 2022-08-02 at 12 07 37 PM](https://user-images.githubusercontent.com/89894075/182360759-0e2bef5b-6de9-4752-ad13-89cca150b977.png)

AFTER <==
![Screenshot 2022-08-02 at 12 08 58 PM](https://user-images.githubusercontent.com/89894075/182360812-891ae7db-3e9c-4ce3-820a-c0524c2f9387.png)

2022-08-02 11:23 UTC, gitstart-sourcegraph commented on client/web/src/enterprise/code-monitoring/components/logs/TriggerEvent.tsx
> +                <Button onClick={toggleExpanded} className={classNames('d-block', styles.expandButton)}>
Ah adding `display="block"` causes a UI diff, Removing `d-block` only though produces no UI diff.
![Screenshot 2022-08-02 at 12 21 38 PM](https://user-images.githubusercontent.com/89894075/182363085-2e997f69-3d5c-4e50-b0ac-1f60497c2744.png)

2022-08-02 13:02 UTC, gitstart-sourcegraph commented on client/jetbrains/webview/src/search/input/JetBrainsToggles.module.scss
> +    border: none;
That works, thanks. 👍

2022-08-03 15:33 UTC, gitstart-sourcegraph commented on client/branded/src/global-styles/index.scss
> -@import 'bootstrap/scss/buttons';
> We also use some global button classes in the browser extension. Let me know if you have ideas on removing them without affecting the UI!

I did setup the browser extension package, and did verified that we have no UI diff as a result of removing bootstrap's button style import, since `btn-*` classNames binds style rules from the codeHost's stylesheet (e.g Github), and not from sourcegraph from my exploration.

> It means that the VSCode package won't have access to these global styles, but [we still use many global button classes there](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+btn-+lang:typescript+rev:contractors/SG-37914.1&patternType=literal). Could you also migrate them as a part of this PR?

After testing the local version of the vscode package on this PR, I also verified that there are no UI diffs caused as a result of removal of `bootstrap`'s button style, since we still have bootstrap's button import in `forkedBranded.scss`.
which would be removed in #39362

Could you please help to confirm 🙂.

2022-08-10 00:38 UTC, valerybugakov commented on client/branded/src/global-styles/index.scss
> -@import 'bootstrap/scss/buttons';
>  since btn-* classNames binds style rules from the codeHost's stylesheet (e.g Github), and not from sourcegraph from my exploration

You're right.

2022-08-10 03:47 UTC, valerybugakov reviewed
@gitstart-sourcegraph, could you please merge the `main` branch into this PR to run tests with the removed `forkedBranded.scss` file?

2022-08-10 04:00 UTC, valerybugakov requested changes
Can we eliminate [the remaining `btn` class usages](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:typescript+rev:contractors/SG-37914.1++className%3D%22.%2Bbtn&patternType=regexp) that used bootstrap styles?

2022-08-10 06:24 UTC, gitstart-sourcegraph commented
> Can we eliminate [the remaining `btn` class usages](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+lang:typescript+rev:contractors/SG-37914.1++className%3D%22.%2Bbtn&patternType=regexp) that used bootstrap styles?

Thanks Valery, Yes we can eliminate them. 
The remaining `.btn` usage are are found in the `vscode` package, which is currently being resolved in a follow-up issue #39362 (mutually independent until #39567 was merged).
WDYT about moving forward with this PR while keeping the bootstrap's button import in `base.scss` (to maintain button style in `vscode` package), and remove it as part of #39362?

2022-08-10 07:32 UTC, valerybugakov approved these changes
Thanks!

2022-08-10 07:45 UTC, merged