feat(build-tracker): Adds a build-tracking service to provide better notifications about build failures
sourcegraph/sourcegraph pull request #39355
Opened 2022-07-25 10:43 UTC by burmudar

Adds a service which creates build failure notifications like this 👇🏼 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/1001709/180759024-bb390870-b2e1-4648-b22d-28ef0a8979a7.png">

[Infrastructure PR](https://github.com/sourcegraph/infrastructure/pull/3707)

## Test plan
1. Pointed buildkite webhook to my local machine
2. Deployed docker image to buildkite kubernetes cluster

2022-07-25 12:43 UTC, burmudar commented
After speaking with @jhchabran he made the good point that in this repo we would have access to sg linting. The teammate resolver was also not available outside of this repo - rather I couldn't get it to import when in the infra repo.

2022-07-25 13:03 UTC, jhchabran requested changes
Lots a small comments here and here! Don't let them give you the impression this is bad, first it's mostly about design and not what it is doing and secondly the outcome of this code is really massive!

For the sake of delivering this sooner, on my side, I'd be ok with merging this with only the most important changes, and then taking this as an interesting opportunity to see how to simplify it.

2022-07-25 23:50 UTC, bobheadxi reviewed
First pass review :) lots of stuff here, excited to get this shipped!

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/Dockerfile
> +FROM golang:1.18.1-alpine@sha256:42d35674864fbb577594b60b84ddfba1be52b4d4298c961b46ba95e9fb4712e8 AS builder
This layer is currently unused - that said, can we move the build into the Dockerfile? We do this in many places but this seems to defeat the purpose of Dockerfiles providing reproducible builds 🤣

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/README.md
> +# BUILD TRACKER
TODO?

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/build.go
> +	if b.Pipeline.Name != nil {
+1, it's a small function to just have available

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/build.go
> +	if b.Pipeline == nil {
Can't trust the Buildkite API with anything 😬

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/main.go
> +func (s *BuildTrackingServer) processBuildkiteRequest(req *http.Request, token string) (*BuildEvent, error) {
I think it's fine the provide it as a parameter - loading all config up-front clarifies where configuration is coming form, and it's important to recognize that processing a request involves validating the Buildkite request contains the (webhook?) token (I think that's what's going on here?)

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/main.go
> +	w.WriteHeader(http.StatusOK)
Idea - server config validation could go here

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/main.go
> +		return ErrJSONUnmarshall
This makes sense actually, and is one way to export sentinel errors while still tracking root causes:

1. first, we fail to unmarshal the body for reason X, and we note it
2. then, we tell the caller we failed to unmarshal the body (and nothing more)

(also nit I think "unmarshall" is one "L" 😋 )

2022-07-25 23:50 UTC, bobheadxi commented on dev/build-tracker/slack.go
> +	buf.Reset()
Yeah this is only needed if we recycle the buffer (which you _could_, but there's no need)

2022-07-25 23:50 UTC, bobheadxi commented on enterprise/dev/ci/scripts/notify-build-done.sh
> +    curl -v -X POST -H "Content-Type: application/json" -d "$data" http://169.0.178.64:8080/done
The address hardcoded here seems kind of clunky - we might want docstrings, or get a subdomain for it (`buildkite.sourcegraph.com`?)

2022-07-26 08:54 UTC, burmudar commented on enterprise/dev/ci/scripts/notify-build-done.sh
> +    curl -v -X POST -H "Content-Type: application/json" -d "$data" http://169.0.178.64:8080/done
Actually this is from the early iteration before I read and understood that buildkite actually has a webhook api. So I'll be removing this script!

2022-07-26 10:29 UTC, burmudar commented on dev/build-tracker/build.go
> +	if b.Pipeline.Name != nil {
man this small function is just so nice. Thanks for the suggestion <3

2022-07-27 08:20 UTC, burmudar commented on dev/build-tracker/build.go
> +	if b.Pipeline == nil {
A little bit more on this. There are actually two pipeline types. One that is part of the Build type and is 99% nil and then a Pipeline type that gets sent with the event!

I am now using the Pipeline type that gets sent with the event and it has loads more detail!

2022-07-27 08:22 UTC, burmudar commented on dev/build-tracker/build.go
> +	if name == "" {
Most definitely was! Good catch!

2022-07-27 08:22 UTC, burmudar commented on dev/build-tracker/build.go
> +func NewBuildFrom(event *BuildEvent) *Build {
Went for this ❤️ along with a few others!

2022-07-27 08:46 UTC, burmudar commented on dev/build-tracker/main.go
> +	}, nil
Good point - think once upon a time something was returning an error there. Needless to say - I am removing this now :D

2022-07-27 08:48 UTC, burmudar commented on dev/build-tracker/main.go
> +func (s *BuildTrackingServer) processBuildkiteRequest(req *http.Request, token string) (*BuildEvent, error) {
yip @bobheadxi. For each request we validate that the event was sent by Buildkite by validating the token. There is more advanced validation that can be done by using HMAC but that is future work.

I do agree with @jhchabran - the token will be static for the life of the server so it might as well be part of it too 👍🏼

2022-07-27 09:33 UTC, jhchabran commented on dev/build-tracker/build.go
> +type BuildEvent struct {
name suggest that these are always "build" events, whereas they can be job events. What about renaming it as just `Event` ?

2022-07-27 09:38 UTC, jhchabran commented on dev/build-tracker/build.go
> +func (s *BuildStore) AllFinishedBuilds() []*Build {
What does "all" brings in semantically? is that possible to not get all of them? 

I'd suggest just rename this to `FinishedBuilds`

2022-07-27 09:42 UTC, jhchabran commented on dev/build-tracker/main.go
> +	serverLog := logger.Scoped("server", "Server which tracks events received from Buildkite and sends notifications on failures")
nit: 
```suggestion
	logger = logger.Scoped("server", "Server which tracks events received from Buildkite and sends notifications on failures")
```

2022-07-27 09:45 UTC, jhchabran commented on dev/build-tracker/main.go
> +	event, err := s.processBuildkiteRequest(req)
Inlining this function inside would enable to not have to declare custom error types as they exists solely because of that underlying function.

2022-07-27 09:49 UTC, jhchabran commented on dev/build-tracker/main.go
> +					now := time.Now()
Usually, when you want to ease testing, you define a `var nowFunc func() time.Time` in your package, this way in your tests, you can swap it with a mocked version.

2022-07-27 09:50 UTC, jhchabran commented on dev/build-tracker/main.go
> +// Server starts the http server and listens for buildkite build events to be sent on the route "/buildkite"
```suggestion
// Serve starts the http server and listens for buildkite build events to be sent on the route "/buildkite"
```

2022-07-27 09:51 UTC, jhchabran commented on dev/build-tracker/slack.go
> +	Channel string
```suggestion
	channel string
```

2022-07-27 09:52 UTC, jhchabran commented on dev/build-tracker/slack.go
> +func (c *NotificationClient) sendNotification(build *Build) error {
```suggestion
func (c *NotificationClient) send(build *Build) error {
```

we know it's a notification as we are on that type

2022-07-27 09:52 UTC, jhchabran commented on dev/build-tracker/slack.go
> +	notifcationLogger := c.logger.With(log.Int("buildNumber", build.number()), log.String("channel", c.Channel))
```suggestion
	logger := c.logger.With(log.Int("buildNumber", build.number()), log.String("channel", c.Channel))
```

2022-07-27 09:54 UTC, jhchabran commented on dev/build-tracker/slack.go
> +func grafanaURLFor(logger log.Logger, build *Build) string {
You could take out the logger here and let the calling code handle the logging logic.

2022-07-27 09:54 UTC, jhchabran commented on dev/build-tracker/slack.go
> +		logger.Error("failed to marshall GrafanaPayload", log.Error(err))
```suggestion
		errors.Wrapf("failed to marshall GrafanaPayload: %w", err)
```

2022-07-27 09:55 UTC, jhchabran commented on dev/build-tracker/slack.go
> +func slackMention(teammate *team.Teammate, build *Build) string {
We're copying this over and over, what about bringing that into the teammate package?

2022-07-27 09:56 UTC, jhchabran commented on dev/build-tracker/slack_test.go
> +	println(config.SlackToken)
```suggestion
```

2022-07-27 09:57 UTC, jhchabran commented on dev/build-tracker/slack_test.go
> +	if !*RunIntegrationTest {
Let's make sure we mention that in the README

2022-07-27 09:57 UTC, jhchabran commented on dev/build-tracker/util.go
> +func intp(v *int, defaultValue int) int {
unless there's an occurrence where we give something else than zero here, let's just avoid passing around the defaultValue?

2022-07-27 18:27 UTC, burmudar commented on dev/build-tracker/main.go
> +					now := time.Now()
TIL ooooh - that is extremely useful

2022-07-28 09:50 UTC, burmudar commented on dev/build-tracker/main.go
> +						if delta >= window {
Added a comment above the `go func()`

2022-07-31 14:00 UTC, sanderginn commented on dev/build-tracker/build.go
> +		return true
Is there any difference using `fallthrough` as opposed to
```go
switch b.state() {
case "passed", "failed", "blocked", "canceled":
	return true
default:
	return false
}
```

2022-08-01 14:06 UTC, burmudar commented on dev/build-tracker/build.go
> +		return true
there isn't - yours is more readable, so I'll change it 👍🏼

2022-08-01 14:56 UTC, bobheadxi approved these changes
Overall LGTM 😁 excited to start trialing this!

2022-08-01 14:56 UTC, bobheadxi commented on dev/build-tracker/build.go
> +type Build struct {
Might want to include a brief docstring here describing that this wrapper adds some additional helper functions for safely retrieving fields and additional metadata

2022-08-01 14:56 UTC, bobheadxi commented on dev/build-tracker/main.go
> +}
Seems unused!

```suggestion
```

2022-08-01 15:00 UTC, burmudar commented on dev/build-tracker/main.go
> +}
oooh thanks <3

2022-08-02 17:25 UTC, merged