[Admin Analytics] export search stats
sourcegraph/sourcegraph pull request #39426
Opened 2022-07-26 10:56 UTC by thenamankumar

closes https://github.com/sourcegraph/sourcegraph/issues/39325
Add a button to Export Admin Analytics Search Stats in CSV format.

[search_analytics.csv](https://github.com/sourcegraph/sourcegraph/files/9189066/search_analytics.csv)

https://www.loom.com/share/226904d6fd824e7e814402bb8e2e33dc

## Test plan
<img width="933" alt="CleanShot 2022-07-26 at 16 25 28@2x" src="https://user-images.githubusercontent.com/22571395/180990034-de14e7b8-2af0-4466-a381-b496096c6335.png">

2022-07-27 08:04 UTC, mrnugget requested changes

2022-07-27 08:04 UTC, mrnugget commented on client/web/src/site-admin/analytics/components/ExportButton.tsx
> +import React from 'react'
I'm getting _a lot_ of warnings from our linters with this file:

<img width="1069" alt="screenshot_2022-07-27_10 02 18@2x" src="https://user-images.githubusercontent.com/1185253/181194597-92cb3db4-dd64-4d1a-8a7e-7565514179f8.png">

2022-07-27 08:04 UTC, mrnugget commented on client/web/src/site-admin/analytics/components/ExportButton.tsx
> +}
Why is this so generic? It's only used in one place. I'd suggest you use the proper concrete type for variables and only pass in the dateRange. Using the `path` to get to the data feels a bit weird, too.

2022-07-27 10:48 UTC, thenamankumar commented on client/web/src/site-admin/analytics/components/ExportButton.tsx
> +}
I am going to use this in every other admin analytics page as well. Waiting on their CSV file formats to be decided and reviewed. 

The other pages will have exactly the same functionality.

2022-07-27 11:02 UTC, thenamankumar commented on internal/adminanalytics/search.go
> +func (s *Search) ExportCSV(ctx context.Context) (*string, error) {
We have extracted it out in `internal/adminanalytics` as a domain. In the graphql-backend we have `siteAnalyticsResolver` with the proper naming. 

These internal structs are also used for caching cron job.

2022-07-27 11:16 UTC, thenamankumar commented on client/web/src/site-admin/analytics/components/ExportButton.tsx
> +import React from 'react'
resolved

2022-07-27 11:16 UTC, thenamankumar commented on internal/adminanalytics/search.go
> +	}
resolved

2022-07-29 07:51 UTC, mrnugget approved these changes

2022-07-29 07:51 UTC, mrnugget commented on internal/adminanalytics/search.go
> +func (s *Search) ExportCSV(ctx context.Context) (*string, error) {
Yeah, other resolvers (in codeintel, batches, dependencies, insights) are also outside of `graphqlbackend` but still called `*Resolver`. This _is_ a GraphQL resolver and acts as one, so I'd still say it makes sense to name it as such.

2022-07-29 07:51 UTC, mrnugget commented on client/web/src/site-admin/analytics/components/ExportButton.tsx
> +            element.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(lodash.get(data, path)))
Just be aware that there's URI size limits. So with enough data it's possible that this won't work because it's too big.

2022-08-02 12:50 UTC, closed without merging

2022-08-03 03:22 UTC, unknwon commented
Hmm, what happened to this PR?