[SG-39285] Remove style duplication caused by the forkedBranded.scss file
sourcegraph/sourcegraph pull request #39567
Opened 2022-07-28 11:38 UTC by gitstart-sourcegraph

### Descriptions
- Move `forkedBranded.scss` file in favor of the `branded.scss` import

### Refs
[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/39285)
[GitStart Issue](https://app.gitstart.com/clients/sourcegraph/tickets/SG-39285)

### Implimentation details
- [x] Rename `client/branded/src/global-styles/index.scss` to `client/branded/src/global-styles/base.scss`
- [x] Move `@import './highlight';` from `base.scss` to `client/branded/src/global-styles/index.scss`
- [x] `client/vscode/src/webview/index.scss` should import `client/branded/src/global-styles/base.scss` instead of `forkedBranded.scss`
- [x] All style changes specific to the VSCode theme should be made in the `client/vscode/src/webview/index.scss`

### Test plan
- The details above should be implemented
- The changes are vscode extension, just check if there no UI changes

2022-08-01 04:58 UTC, valerybugakov requested changes

2022-08-01 04:58 UTC, valerybugakov commented on client/vscode/src/webview/forkedBranded.scss
> -@import 'bootstrap/scss/forms';
`.form-group` class from this `@import` is used in `client/vscode/src/webview/search-panel/components/SavedSearchForm.tsx`. It seems `form-group mb-0` classes can be completely removed. Could you double-check that, please?

2022-08-01 04:58 UTC, valerybugakov commented on client/vscode/src/webview/index.scss
> +$input-transition: none;
Do we still need these SCSS variables? If so, could you share places where they are used?

2022-08-01 04:58 UTC, valerybugakov commented on client/vscode/src/webview/index.scss
> +@import 'bootstrap/scss/card';
Let's merge [this approved PR](https://github.com/sourcegraph/sourcegraph/pull/39403) and then remove this code from here.

2022-08-01 04:58 UTC, valerybugakov commented on client/branded/src/global-styles/index.scss
>  @import './highlight';
Let's a comment here explaining why we need a separate entry point for VSCode styles: "The VSCode extension uses its syntax-highlighting theme, that's why we need a separate `base.scss` entry point for all branded styles without syntax highlighting. Client applications that want to inherit the default theme fully should use this file as a base theme."

2022-08-03 11:18 UTC, gitstart-sourcegraph commented on client/vscode/src/webview/index.scss
> +$input-transition: none;
That's right, we are safe to remove these variables now.

2022-08-03 11:28 UTC, gitstart-sourcegraph commented on client/vscode/src/webview/forkedBranded.scss
> -@import 'bootstrap/scss/forms';
Yes it can be completely removed, we have a UI diff as side effect though. It's a good diff though IMO, WDYT?

BEFORE
<img width="1228" alt="Screenshot 2022-08-03 at 12 25 37 PM" src="https://user-images.githubusercontent.com/89894075/182596992-d8bbaabc-f84d-4a99-8841-bb9f96391226.png">

AFTER
<img width="1228" alt="Screenshot 2022-08-03 at 12 24 11 PM" src="https://user-images.githubusercontent.com/89894075/182597022-58cfd96b-06a8-4ab0-9d12-7c873a837495.png">

2022-08-05 12:01 UTC, valerybugakov approved these changes
Thanks! LGTM

2022-08-08 04:53 UTC, merged