Require env var for custom git fetch
sourcegraph/sourcegraph pull request #39630
Opened 2022-07-28 18:38 UTC by daxmc99

Requires an env var for this site config to take effect

## Test plan

Manual review 
Manual testing

2022-08-04 14:06 UTC, andreeleuterio approved these changes

2022-08-04 14:06 UTC, evict commented
Thanks @andreeleuterio for proposing to moving it to a file! Makes things a lot easier.

2022-08-04 14:46 UTC, daxmc99 commented on cmd/gitserver/server/customfetch_test.go
> +	})
`t.Cleanup` should be called near the resources you want to remove. It should be called around line 54

2022-08-08 06:59 UTC, unknwon approved these changes
Thanks and LGTM other than some world-class formatting issues 😛

2022-08-08 06:59 UTC, unknwon commented on cmd/gitserver/server/customfetch.go
> +
nit

```suggestion
```

2022-08-08 06:59 UTC, unknwon commented on cmd/gitserver/server/customfetch.go
> +
nit
```suggestion

	var cc []*schema.CustomGitFetchMapping
	err = json.Unmarshal(r, &cc)
```

2022-08-08 06:59 UTC, unknwon commented on CHANGELOG.md
> +- Custom Git fetch configuration `experimentalFeatures.customGitFetch` is now deprecated. The configuration is now moved to a file, use environment variable `CUSTOM_GIT_FETCH_CONF` to set the config
nit: it is actually unused, "deprecated" sounds like people can still live with the old approach (i.e. change through site config)

2022-08-08 06:59 UTC, unknwon commented on cmd/gitserver/server/customfetch_test.go
> +
```suggestion
```

2022-08-15 16:30 UTC, DaedalusG commented on CHANGELOG.md
> +- Custom Git fetch configuration `experimentalFeatures.customGitFetch` is now unused. The configuration has been moved to a file and no longer uses the site-admin settings. Use environment variable `
Assuming the `CUSTOM_GIT_FETCH_CONF` env var is to be set on the `sourcegraph-frontend` deployment? Does this env var need to be set on any other deployments?

2022-08-15 16:31 UTC, DaedalusG reviewed
Assuming the CUSTOM_GIT_FETCH_CONF env var is to be set on the sourcegraph-frontend deployment? Does this env var need to be set on any other deployments?

2022-08-16 09:30 UTC, evict commented on CHANGELOG.md
> +- Custom Git fetch configuration `experimentalFeatures.customGitFetch` is now unused. The configuration has been moved to a file and no longer uses the site-admin settings. Use environment variable `
The env var needs to be set on the `gitserver`! Doesn't work from the `frontend` deployment.

2022-08-17 07:49 UTC, DaedalusG commented on CHANGELOG.md
> +- Custom Git fetch configuration `experimentalFeatures.customGitFetch` is now unused. The configuration has been moved to a file and no longer uses the site-admin settings. Use environment variable `
```suggestion
- Custom Git fetch configuration `experimentalFeatures.customGitFetch` is now unused. The configuration has been moved to a file and no longer uses the site-admin settings. In gitserver, use environment variable `CUSTOM_GIT_FETCH_CONF` to set the config file to read the settings from. [#39630](https://github.com/sourcegraph/sourcegraph/pull/39630).
```

2022-09-01 02:19 UTC, DaedalusG commented
Moved the docs updates from a separate branch to this one 👍, please take one more look at this since I've created a dedicated usage doc

2022-09-01 02:48 UTC, unknwon approved these changes

2022-09-01 04:20 UTC, DaedalusG approved these changes

2022-09-01 17:00 UTC, daxmc99 commented
@evict @andreeleuterio Is there a reason we moved this to a file? 
I actually think this UX is noticeably harder for the critical customer who uses this. 
I don't think this can be complete until we provide precise instructions for how to use this in a k8s deployment environment. 
I'm happy to do that but I'm not fully understanding what moving from a config option to a file gives us. 

It seems simpler to keep the config in the site-config and leverage an infrastructure-level config option to tune it.

2022-09-01 18:28 UTC, DaedalusG requested changes
Holding this till we can provide easy instructions of how to mount the config file

2022-09-02 13:55 UTC, keegancsmith reviewed
What is the original motivation for this? TBH what we are doing now is just more clunky and lives outside of things like being able to use the migrator/etc for it.

Generally when deprecating something we give a release or two before making it non functional.

2022-09-02 13:55 UTC, keegancsmith commented on cmd/gitserver/server/customfetch_test.go
> +	customGitFetchCmdConf = "/tmp/customGitConfig.json"
/tmp is not always a writeable tmp dir. Luckily go provides something which will return a path for you and clean it up when the test is done:
```suggestion
	customGitFetchCmdConf = filepath.Join(t.TempDir(), "customGitConfig.json")
```

2022-09-02 13:55 UTC, keegancsmith commented on schema/site.schema.json
> +          "description": "JSON array of configuration that maps from Git clone URL domain/path to custom git fetch command. DEPRECATED: CONFIGURATION MOVED TO A LOCAL FILE USE ENVIRONMENT VARIABLE `C
nit: put the deprecated notice at the start of description. Also say the variable is now ignored.

2022-09-03 03:24 UTC, andreeleuterio commented
@keegancsmith you can find more context [here](https://github.com/sourcegraph/security-issues/issues/229). tl;dr is that this can't be a site-admin setting in the context of Managed Instances.

2022-09-27 07:24 UTC, keegancsmith commented on schema/site.schema.json
> +          "description": "DEPRECATED: THIS VALUE WILL IS IGNORED. CONFIGURATION MOVED TO A LOCAL FILE USE ENVIRONMENT VARIABLE `CUSTOM_GIT_FETCH_CONF` TO SET FILE PATH. JSON array of configuration th
Can't we still read this value if the envvar is not set for 2 releases just so we don't break the customers we know use this? Additionally I'd document that the envvar needs to be set on the gitserver container.

2022-10-07 15:24 UTC, evict commented
Closing this MR in favour of a simpler solution: https://github.com/sourcegraph/sourcegraph/pull/42704. This makes sure the customer can keep using it while others have the option of disabling it.

2022-10-07 15:24 UTC, closed without merging

2022-10-10 17:34 UTC, daxmc99 commented on schema/site.schema.json
> +          "description": "DEPRECATED: THIS VALUE WILL IS IGNORED. CONFIGURATION MOVED TO A LOCAL FILE USE ENVIRONMENT VARIABLE `CUSTOM_GIT_FETCH_CONF` TO SET FILE PATH. JSON array of configuration th
Please provide feedback on this new PR https://github.com/sourcegraph/sourcegraph/pull/42704