[SG-39284] Upgrade yarn to the latest version - Setup
sourcegraph/sourcegraph pull request #39728
Opened 2022-07-31 18:13 UTC by gitstart-sourcegraph

## Description

Follow the official migration guide [from yarn](https://yarnpkg.com/getting-started/migration#step-by-step)

## Refs

[Sourcegraph Issue](https://github.com/sourcegraph/sourcegraph/issues/39284)
[Gitstart Ticket](https://app.gitstart.com/clients/sourcegraph/tickets/SG-39284)

2022-08-01 05:47 UTC, valerybugakov requested changes
@gitstart-sourcegraph, please force-push to remove the latest commit from the git history our the repository. Removing all zip archives committed to the repo **is important** to avoid polluting git history with large files. 

We do not want to use the Plug'n'Play feature with zero installs. It's mentioned in [the issue description](https://github.com/sourcegraph/sourcegraph/issues/39284). Initially, we want to use the `node-modules` `nodeLinker` to minimize the changes required for the upgrade. 

We want to upgrade to the latest version of `yarn` with minimal changes required in our codebase. Mainly it should be commands and some configuration files. Let me know if you bump into any sweeping changes while working on the task.

2022-08-01 05:52 UTC, gitstart commented
:D thanks @valerybugakov actually we are going to ask you about it too

2022-08-02 04:16 UTC, valerybugakov commented on enterprise/dev/ci/internal/ci/cache_helpers.go
> +		Paths:       []string{"node_modules", ".yarn/cache"},
To avoid affecting other branches while this PR is WIP, let's change the `ID` and `Key` fields here to indicate a different version of `yarn`. E.g.,

```go
ID:          "node_modules_yarn_v3",
Key:         "cache-node_modules-yarn_v3-{{ checksum 'yarn.lock' }}",
RestoreKeys: []string{"cache-node_modules-yarn_v3-{{ checksum 'yarn.lock' }}"},

2022-08-02 04:29 UTC, valerybugakov commented on dev/ci/yarn-run.sh
> +  yarn run "$cmd"
Is there a flag that can mute the output of the `yarn run` command? 
A couple of issues [mentioned](https://github.com/yarnpkg/berry/pull/3406#issuecomment-938545138) the `--quiet` flag.

2022-08-02 04:50 UTC, gitstart-sourcegraph commented on dev/ci/yarn-run.sh
> +  yarn run "$cmd"
@valerybugakov  I don't think we have that flag in this version, I tried both --silent or --quite, both of them don't work. could you help to try?

2022-08-02 05:45 UTC, valerybugakov reviewed
Let's try removing `web-ext` package, which is not used in the repo anymore, to remove transitive dependency on the `dtrace-provider` package, which causes failure [here](https://buildkite.com/sourcegraph/sourcegraph-contractors/builds/44835#01825cbb-6ba8-47b7-84f8-698b0bb9c6e8).

Also, let's explicitly add `@sentry/cli` to our `package.json` to see if it resolves another issue reported by the build linked above.

2022-08-04 08:11 UTC, gitstart-sourcegraph commented
As discussed on Slack, we may need to upgrade Yarn on `code-intel-extensions`. Still wait for the confirmation from @valerybugakov

2022-08-05 12:03 UTC, valerybugakov reviewed
@taras-yemets is going to help us on that front! With upcoming changes, we won't need to run yarn install in another repo with a potentially incompatible `yarn` version. Let's wait for this improvement.

2022-08-05 14:10 UTC, taras-yemets commented
> @taras-yemets is going to help us on that front! With upcoming changes, we won't need to run yarn install in another repo with a potentially incompatible yarn version.

On it: https://github.com/sourcegraph/sourcegraph/pull/40017 (wip)

2022-08-10 00:30 UTC, valerybugakov reviewed
@gitstart-sourcegraph, could you pull the `main` branch into this PR? The issue with code-intel extensions should be addressed by https://github.com/sourcegraph/sourcegraph/pull/40017

2022-08-10 04:30 UTC, valerybugakov requested changes

2022-08-10 04:30 UTC, valerybugakov commented on client/jetbrains/package.json
> +    "lint:js": "yarn run -T eslint --cache 'webview/**/*.[jt]s?(x)'",
Is `-T` required here because `eslint` is installed in the root `package.json`?

2022-08-10 04:30 UTC, valerybugakov commented on client/shared/dev/generateCssModulesTypes.js
> -const TSM_COMMAND = `yarn --silent --ignore-engines --ignore-scripts tsm --logLevel error "{${CSS_MODULES_GLOB},${JETBRAINS_CSS_MODULES_GLOB}}" --includePaths node_modules client`
Let's use [`logFilters`](https://yarnpkg.com/configuration/yarnrc#logFilters) to set yarn output to `warning` in the development environment and to `error` on CI.

2022-08-10 14:59 UTC, gitstart-sourcegraph commented on client/jetbrains/package.json
> +    "lint:js": "yarn run -T eslint --cache 'webview/**/*.[jt]s?(x)'",
@valerybugakov  yes, it is. As I know we can list `eslint` (or others) in `dependencies` to fix this too.

2022-08-10 15:42 UTC, gitstart-sourcegraph commented on client/shared/dev/generateCssModulesTypes.js
> -const TSM_COMMAND = `yarn --silent --ignore-engines --ignore-scripts tsm --logLevel error "{${CSS_MODULES_GLOB},${JETBRAINS_CSS_MODULES_GLOB}}" --includePaths node_modules client`
@valerybugakov  I updated to use `GLOBAL_YARN_LOG_LEVEL` in yarnrc.yml file. we would have to update CI env for this variable. Could you take a look?

2022-08-10 18:05 UTC, gitstart-sourcegraph commented on client/shared/dev/generateCssModulesTypes.js
> -const TSM_COMMAND = `yarn --silent --ignore-engines --ignore-scripts tsm --logLevel error "{${CSS_MODULES_GLOB},${JETBRAINS_CSS_MODULES_GLOB}}" --includePaths node_modules client`
oh I have just realized that `logFilters` is not for defining which log level should be printed but for `overrides for log levels for message names or message text` it's something like when yarn print message with code `YN0000` which is an `infor` message (from https://yarnpkg.com/advanced/error-codes#yn0019---unused_cache_entry) we can use this config to make it as `error`, then yarn will finish execution with `Failed with errors`, or `Failed with errors` with `warning`.  IMO we should `discard` `YN0002` `YN0060` `YN0013` `YN0007`. WDYT?

2022-08-10 18:07 UTC, gitstart-sourcegraph commented
> @gitstart-sourcegraph, could you pull the `main` branch into this PR? The issue with code-intel extensions should be addressed by #40017

@valerybugakov `client/browser` test step is good now.

2022-08-11 03:25 UTC, gitstart-sourcegraph commented
@valerybugakov The remaining error on pipeline is `Test (all)` I tried to run the `BUILDKITE_COMMAND` locally but couldn't make it. Could you please take a look?

2022-08-12 04:19 UTC, valerybugakov reviewed
I will discuss the issue in go tests with the code-intel team.

2022-08-12 14:12 UTC, valerybugakov requested changes

2022-08-12 14:12 UTC, valerybugakov commented on internal/codeintel/autoindexing/enqueuer_test.go
> +					"yarn install --immutable --non-interactive",
Let's revert all changes in the `internal/codeintel` directory.

2022-08-12 14:12 UTC, valerybugakov commented on lib/codeintel/autoindex/config/yaml_test.go
> +      - yarn install --immutable --non-interactive
Let's revert all changes in the `lib/codeintel` directory.

2022-08-15 16:46 UTC, gitstart-sourcegraph commented
@valerybugakov Thanks for the suggestions, all CI checks are passed in `contractors` pipeline. could you help to check errors in `buildkite/sourcegraph-async `

2022-08-17 04:45 UTC, valerybugakov requested changes

2022-08-17 04:45 UTC, valerybugakov commented on client/browser/package.json
> +    "run-integration": "TS_NODE_PROJECT=src/integration/tsconfig.json SOURCEGRAPH_BASE_URL=https://sourcegraph.com mocha --parallel=${CI:-\"false\"} --retries=2 ./src/integration/**/*.test.ts",
Do we want to keep this change?

2022-08-17 04:45 UTC, valerybugakov commented on client/shared/dev/generateCssModulesTypes.js
> -const TSM_COMMAND = `yarn --silent --ignore-engines --ignore-scripts tsm --logLevel error "{${CSS_MODULES_GLOB},${JETBRAINS_CSS_MODULES_GLOB}}" --includePaths node_modules client`
Sounds good 👍

2022-08-17 04:45 UTC, valerybugakov commented on doc/dev/how-to/cache_ci_artefacts.md
> +	})
Let's keep the original tabulation here.

2022-08-17 04:45 UTC, valerybugakov commented on doc/dev/how-to/ci_soft_failure_and_still_notify.md
>  +   bk.Cmd("please-fail-lol"),
Let's clean up changes in `*.md` files before merging the PR. If any changes in `*.md` files are required, please comment in the PR regarding why we need `bk.SoftFail(1, 2),` added here.

2022-08-17 04:45 UTC, valerybugakov commented on package.json
> +    "_test-integration": "TS_NODE_PROJECT=client/web/src/integration/tsconfig.json mocha --parallel=${CI:-\"false\"} --retries=1 --jobs=2",
Does the yarn command fail if the `CI` variable is not set?

2022-08-17 04:47 UTC, valerybugakov reviewed
The async pipeline is flaky. Since it's not required for the PR merge, we can look into it in a follow-up PR. I believe we have this issue on the `main` branch too.

2022-08-17 05:44 UTC, gitstart-sourcegraph commented on package.json
> +    "_test-integration": "TS_NODE_PROJECT=client/web/src/integration/tsconfig.json mocha --parallel=${CI:-\"false\"} --retries=1 --jobs=2",
yes, it will fail without this change

2022-08-17 15:44 UTC, gitstart-sourcegraph commented on doc/dev/how-to/ci_soft_failure_and_still_notify.md
>  +   bk.Cmd("please-fail-lol"),
@valerybugakov `+ bk.Cmd("please-fail-lol"),` is not a new change, it's for document

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/89894075/185183498-53ec57fc-dc90-4a7f-8ba0-8a4816584981.png">

2022-08-18 03:01 UTC, gitstart-sourcegraph commented on doc/dev/how-to/cache_ci_artefacts.md
> +	})
Thanks. Didn't notice these changes when resolving conflicts

2022-08-18 03:02 UTC, gitstart-sourcegraph commented on client/shared/dev/generateCssModulesTypes.js
> -const TSM_COMMAND = `yarn --silent --ignore-engines --ignore-scripts tsm --logLevel error "{${CSS_MODULES_GLOB},${JETBRAINS_CSS_MODULES_GLOB}}" --includePaths node_modules client`
@valerybugakov  I added logFilters, could you please check logs on pipeline?

2022-08-19 03:28 UTC, valerybugakov commented on doc/dev/how-to/ci_soft_failure_and_still_notify.md
>  +   bk.Cmd("please-fail-lol"),
Oh, wow! I see, thanks for attaching the screenshot 🙏

2022-08-22 13:04 UTC, valerybugakov reviewed
Running main-dry-tests [here](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=main-dry-run%2Fvb%2Fyarn-v3-test).

2022-08-22 13:24 UTC, valerybugakov reviewed
@gitstart-sourcegraph, it would be nice to understand why the `@sentry/cli` download fails. We use this CLI to upload source maps on the main branch. Could you try to create a new branch and call `yarn run -T sentry-cli --version` somewhere on CI to see if it works? 

Or even better, change the sourcemaps upload logic, so it happens on your branch, and we can see if it works without issue with the new package manager. [Here's the logic](https://github.com/sourcegraph/sourcegraph/blob/9f4a212bfb0c090167cb9ec1e275875b7bffeba0/enterprise/dev/ci/internal/ci/pipeline.go#L234-L235) that you need to tweak. Make it always true in a separate branch and ensure that it doesn't fail. 

<img width="459" alt="Screenshot 2022-08-22 at 21 19 02" src="https://user-images.githubusercontent.com/3846380/185931798-73b375b2-c89c-445c-bb26-4ef4d5b96a36.png">

2022-08-22 17:41 UTC, gitstart-sourcegraph commented
@valerybugakov About the issue of @sentry/cli `STDERR`, I can see from their source code, those `STDERR` are from `npmLog.info` which shoulda print logs at info level but not sure why yarn prints `STDERR` there.

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/89894075/185984062-653fc612-3782-4075-bb75-b407cfa33d44.png">

And I tried to run `yarn run -T sentry-cli --version` on our CI and it stills work fine:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/89894075/185984980-9a078e88-f816-4fc1-ae84-d4aceddf85c5.png">

2022-08-23 03:01 UTC, valerybugakov reviewed
@gitstart-sourcegraph, thanks for looking into the sentry-cli problem. We can address it in the follow-up investigation. Could you create an issue about it with your findings around log levels?

We need to fix [the failing GitHub action](https://github.com/sourcegraph/sourcegraph/runs/7957932787?check_suite_focus=true). 

<img width="430" alt="Screenshot 2022-08-23 at 10 58 51" src="https://user-images.githubusercontent.com/3846380/186059912-98e7d6fc-13dc-47dc-b21b-619f409ed5d9.png">

2022-08-23 03:07 UTC, valerybugakov commented on client/shared/dev/generateCssModulesTypes.js
> -const TSM_COMMAND = `yarn --silent --ignore-engines --ignore-scripts tsm --logLevel error "{${CSS_MODULES_GLOB},${JETBRAINS_CSS_MODULES_GLOB}}" --includePaths node_modules client`
Looks good to me! Thanks.

2022-08-23 03:07 UTC, valerybugakov reviewed
@jhchabran, @burmudar, could you look at this PR from the DX team ownership perspective? Tagging you here because you looked into various improvements for CI client checks. 🙂 

I triggered the dry-run [here](https://buildkite.com/sourcegraph/sourcegraph/builds?branch=main-dry-run%2Fvb%2Fyarn-v3-test). The new `yarn` output on CI looks good, and the caching mechanism seems to be working without issues. P.S. This PR should make the registry URLs hack for the Verdaccio proxy obsolete.

2022-08-23 04:14 UTC, gitstart-sourcegraph commented
> We need to fix [the failing GitHub action](https://github.com/sourcegraph/sourcegraph/runs/7957932787?check_suite_focus=true).

@valerybugakov About this, we can use `yarn dlx -p @sourcegraph/scip-typescript scip-typescript index --yarn-workspaces` as an replacement for `yarn global add ...` but we are using `yarn --silent --json workspaces info` inside @sourcegraph/scip-typescript, which will cause yarn throwing errors for deprecated flags. We need to update that call to use `yarn workspace info --json` with yarn@^2 or yarn@^3. 
WDYT about this?

2022-08-23 08:03 UTC, burmudar reviewed
Nothing outright jumps at me as being problematic. I defer final approval to you @valerybugakov and @jhchabran

2022-08-23 10:16 UTC, jhchabran requested changes
There is something broken with fetching yarn 3.2.X: 

```
--2022-08-22 17:48:18--  https://classic.yarnpkg.com/downloads/3.2.2/yarn-v3.2.2.tar.gz
--
  | Resolving classic.yarnpkg.com (classic.yarnpkg.com)... 34.148.79.160, 52.204.121.99
  | Connecting to classic.yarnpkg.com (classic.yarnpkg.com)\|34.148.79.160\|:443... connected.
  | HTTP request sent, awaiting response... 301 Moved Permanently
  | Location: https://github.com/yarnpkg/yarn/releases/download/v3.2.2/yarn-v3.2.2.tar.gz [following]
  | --2022-08-22 17:48:19--  https://github.com/yarnpkg/yarn/releases/download/v3.2.2/yarn-v3.2.2.tar.gz
  | Resolving github.com (github.com)... 140.82.112.4
  | Connecting to github.com (github.com)\|140.82.112.4\|:443... connected.
  | HTTP request sent, awaiting response... 404 Not Found

```

https://buildkite.com/sourcegraph/sourcegraph-contractors/builds/47792#0182c6a9-fc63-4f87-b245-cdf73f68344e/169-256

2022-08-24 15:40 UTC, gitstart-sourcegraph commented
Thanks @jhchabran we updated tool-versions to use binary classic yarn (1.x) in system instead of modern yarn (3.x) which should be managed in workspace. cc @valerybugakov

2022-08-24 16:12 UTC, jhchabran requested changes

2022-08-24 16:12 UTC, jhchabran commented on .tool-versions
> +yarn 1.22.19
@gitstart-sourcegraph can we add a comment indicating that yarn is going to get the correct version because of the yarnrc? 

cc @valerybugakov

2022-08-25 03:24 UTC, valerybugakov commented on .tool-versions
> +yarn 1.22.19
Agree 👍

2022-08-25 03:33 UTC, valerybugakov reviewed
The current state looks good to me! I asked @sourcegraph/frontend-devs to take a look at this. Let's wait for feedback and merge this PR tomorrow if no new issues arise.

2022-08-25 04:47 UTC, valerybugakov commented on .tool-versions
> +yarn 1.22.19
Strange, `asdf` [supports](https://github.com/asdf-vm/asdf/pull/1092) comments but if [fails](https://buildkite.com/sourcegraph/sourcegraph/builds/169094#0182d31f-bea7-4a9b-9bf9-8e93750f624a) on CI because of that.

2022-08-25 07:00 UTC, valerybugakov commented on .tool-versions
> +yarn 1.22.19
@jhchabran, @burmudar, any suggestions for adding a comment here without causing a failure on CI? It works for me locally, and I didn't find any related issue in [the asdf repo](https://github.com/asdf-vm/asdf).

2022-08-25 11:58 UTC, eseliger commented
`sg start` doesn't work for me. 
```
Unknown Syntax Error: Unsupported option name ("--no-progress").

$ yarn cache clean [--mirror] [--all]
$ yarn cache clean [--mirror] [--all]
$ yarn config get [--json] [--no-redacted] <name>
$ yarn config set [--json] [-H,--home] <name> <value>
$ yarn config unset [-H,--home] <name>
$ yarn set resolution [-s,--save] <descriptor> <resolution>
$ yarn set version from sources [--path #0] [--repository #0] [--branch #0] [--plugin #0] [--no-minify] [-f,--force] [--skip-plugins]
$ yarn set version [--only-if-needed] <version>
$ yarn workspaces list [--since] [-R,--recursive] [-v,--verbose] [--json]
$ yarn --clipanion=definitions
$ yarn help
$ yarn help
$ yarn help
$ yarn <leadingArgument> ...
$ yarn -v
$ yarn -v
$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
$ yarn bin [-v,--verbose] [--json] [name]
$ yarn config [-v,--verbose] [--why] [--json]
$ yarn dedupe [-s,--strategy #0] [-c,--check] [--json] [--mode #0] ...
$ yarn exec <commandName> ...
$ yarn explain peer-requirements [hash]
$ yarn explain [--json] [code]
$ yarn info [-A,--all] [-R,--recursive] [-X,--extra #0] [--cache] [--dependents] [--manifest] [--name-only] [--virtuals] [--json] ...
$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
$ yarn link [-A,--all] [-p,--private] [-r,--relative] <destination>
$ yarn unlink [-A,--all] ...
$ yarn node ...
$ yarn plugin import from sources [--path #0] [--repository #0] [--branch #0] [--no-minify] [-f,--force] <name>
$ yarn plugin import <name>
$ yarn plugin remove <name>
$ yarn plugin list [--json]
$ yarn plugin runtime [--json]
$ yarn rebuild ...
$ yarn remove [-A,--all] [--mode #0] ...
$ yarn run
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
$ yarn up [-i,--interactive] [-E,--exact] [-T,--tilde] [-C,--caret] [-R,--recursive] [--mode #0] ...
$ yarn why [-R,--recursive] [--json] [--peers] <package>
$ yarn workspace <workspaceName> <commandName> ...
$ yarn create [-p,--package #0] [-q,--quiet] <command> ...
$ yarn dlx [-p,--package #0] [-q,--quiet] <command> ...
$ yarn init [-p,--private] [-w,--workspace] [-i,--install]
$ yarn npm audit [-A,--all] [-R,--recursive] [--environment #0] [--json] [--severity #0]
$ yarn npm info [-f,--fields #0] [--json] ...
$ yarn npm login [-s,--scope #0] [--publish]
$ yarn npm logout [-s,--scope #0] [--publish] [-A,--all]
$ yarn npm publish [--access #0] [--tag #0] [--tolerate-republish] [--otp #0]
$ yarn npm tag add <package> <tag>
$ yarn npm tag list [--json] [package]
$ yarn npm tag remove <package> <tag>
$ yarn npm whoami [-s,--scope #0] [--publish]
$ yarn pack [--install-if-needed] [-n,--dry-run] [--json] [-o,--out #0]
$ yarn patch-commit [-s,--save] <patchFolder>
$ yarn patch [--json] <package>
$ yarn unplug [-A,--all] [-R,--recursive] [--json] ...
$ yarn search
$ yarn upgrade-interactive
$ yarn workspaces focus [--json] [--production] [-A,--all] ...
$ yarn workspaces foreach [-R,--recursive] [--from #0] [-A,--all] [-v,--verbose] [-p,--parallel] [-i,--interlaced] [-j,--jobs #0] [-t,--topological] [--topological-dev] [--include #0] [--exclude #0] [--no-private] [--since] <commandName> ...
--------------------------------------------------------------------------------
❌ failed to run web
```

2022-08-26 04:50 UTC, valerybugakov reviewed
> About this, we can use `yarn dlx -p @sourcegraph/scip-typescript scip-typescript index --yarn-workspaces` as the replacement for `yarn global add ...` but we are using `yarn --silent --json workspaces info` inside @sourcegraph/scip-typescript, which will cause yarn throwing errors for deprecated flags. We need to update that call to use `yarn workspace info --json` with yarn@^2 or yarn@^3. 

@gitstart-sourcegraph, we already have [an issue](https://github.com/sourcegraph/scip-typescript/issues/163) for it in the `@sourcegraph/scip-typescript` repo! I'll chat with @olafurpg on the best way to address it.

2022-08-26 09:17 UTC, valerybugakov commented on .tool-versions
> +yarn 1.22.19
@jhchabran, excellent, thanks!

2022-08-26 11:46 UTC, jhchabran commented on .tool-versions
> +yarn 1.22.19
@valerybugakov, @gitstart-sourcegraph it's fixed (see https://buildkite.com/sourcegraph/sourcegraph/builds/169411) you can re-add the comment in the .tool-version !

2022-08-29 11:36 UTC, valerybugakov reviewed
The current state looks great! I'm still testing different commands locally and asked a couple more people to take a look. Let's merge it tomorrow if nothing comes up.

2022-08-29 23:46 UTC, eseliger commented
no longer seeing the issue with `sg start` 👍

2022-08-30 11:04 UTC, valerybugakov commented on client/web/package.json
> +    "test:regression": "yarn run -T task:mocha './src/regression/**/*.test.ts' --exit",
Might the `-T` flag here be the reason for [this CI failure](https://buildkite.com/sourcegraph/sourcegraph/builds/169925#0182ede5-4538-42ef-8e55-9e8930ba5767/458-463)?

2022-08-30 11:10 UTC, valerybugakov commented on client/vscode/package.json
> +    "task:gulp": "yarn cross-env NODE_OPTIONS=\"--max_old_space_size=8192\" gulp",
Should we use the `-T` flag here in the same manner we do it for the `task:gulp` NPM script in the `web` package?

2022-08-31 04:07 UTC, valerybugakov reviewed
Pushed a couple of fixes and [triggered](https://buildkite.com/sourcegraph/sourcegraph/builds/170236) the `main-dry-run` build.

2022-09-01 03:39 UTC, valerybugakov approved these changes
🎉

2022-09-01 03:39 UTC, merged