Add flow to refresh oauth tokens and retry requests
sourcegraph/sourcegraph pull request #39840
Opened 2022-08-02 19:03 UTC by miveronese

This is a WIP, resulted from work in collaboration and the guidance of @unknwon. 
I'm opening it as a Draft so I can collect some feedback and help to answer some questions + explain some of the decisions made.

## Some context:
- The goal of the first PR is to have a foundation for the new  "refresh  token + retry process" and use it in the GiLab auth provider.
- In the next PRs, we can hook the other auth providers to use the mechanism here. 

## ToDos:

- add tests
- hook other auth providers (should be done in another PR)

## Test plan

2022-08-02 19:05 UTC, miveronese commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		tokenExpired := errcode.IsUnauthorized(err) && err.Error() == "invalid_token"
Does it make sense to add the new flow to try to refresh a token here? It wasn't clear to me why we are refreshing the token before we get a 401...

2022-08-02 19:06 UTC, miveronese commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		tokenExpired := errcode.IsUnauthorized(err) && err.Error() == "invalid_token"
Also, if we keep the check here, it would be good to also check the error description, to make sure this is really an expired token issue. Does anyone know how I could get/inspect the message here? I don't thing that, right now, we have it in the "err".

2022-08-02 19:08 UTC, miveronese commented on enterprise/internal/authz/gitlab/authz.go
> +	return newOAuthProvider(op, nil, helper.RefreshToken)
The changes on the previous files (authz/authz.go and authz/gitlab.go) were necessary to get the External Service ID and the DB here. :)

2022-08-02 19:09 UTC, miveronese commented on enterprise/internal/batches/sources/gitlab.go
> +	provider := gitlab.NewClientProvider(urn, baseURL, cli, nil)
I am not 100% if I should pass a `nil` instead of the `tokenRefresher` function here... 🤔

2022-08-02 19:11 UTC, miveronese commented on enterprise/internal/oauth/refresh_helper.go
> +package oauth
I would love to keep this inside the `internal/oauthutil` package, but we need access to the DB in this helper and , if we add it under `internal/oauthutil`  , will have an import cycle problem.

2022-08-02 19:14 UTC, miveronese commented on internal/extsvc/auth/oauth_bearer.go
> +	RefreshToken string
Initially, we added the RefreshToken field to the oauthContext, under `internal/oauthutil`. But oauthContext has access to  client data but not to user data and didn't seem a good place for it. That's why I am suing RefreshToken here.

2022-08-02 19:16 UTC, miveronese commented on internal/extsvc/gitlab/client.go
> +	return c.doWithBaseURLAndOAuthTokenRefresher(ctx, req, result)
My understanding is that we can replace  `doWithBaseURL`  (commented out in line 234) with the new client method function `doWithBaseURLAndOAuthTokenRefresher`... Did I got this wrong? 🤔

2022-08-02 19:17 UTC, miveronese commented on internal/oauthutil/oauth2.go
> +}
Initially, we had the RefreshToken field as part of this struct. See a comment above where I explain why it has been removed.

2022-08-02 19:18 UTC, miveronese commented on internal/oauthutil/token.go
> +	}
When manually testing the "refresh token + retry request" new flow, got error such as `missing grant_type` and `missing refresh_token`. That's why I am setting them here.

2022-08-02 19:20 UTC, miveronese commented on internal/repos/oauthhelper.go
> +func (r *RefreshTokenConfig) RefreshToken(ctx context.Context, doer httpcli.Doer, oauthCtx oauthutil.OauthContext) (string, error) {
I don't like this kind of duplication and tried several ways to avoid it, but always hit "import cycle" errors.

2022-08-02 19:23 UTC, miveronese commented on internal/extsvc/auth/oauth_bearer.go
> +type oauthBearerTokenWithRefresher struct {
@unknwon ,I  cannot remember what was the use case for this struct... 🤔

2022-08-03 05:19 UTC, unknwon commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		tokenExpired := errcode.IsUnauthorized(err) && err.Error() == "invalid_token"
I don't think we need to do a refresh here at all, it is no longer the perms syncer's concern with the new refresh mechanism (which is handled at the API request level).

2022-08-03 05:21 UTC, unknwon commented on enterprise/internal/batches/sources/gitlab.go
> +	provider := gitlab.NewClientProvider(urn, baseURL, cli, nil)
I _guess_ batch changes code logic will make API requests, thus a `tokenRefresher` is needed, but since it wasn't handling token expiration at all, we can leave a TODO as a followup (with a GitHub issue).

2022-08-03 05:27 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +	return c.doWithBaseURLAndOAuthTokenRefresher(ctx, req, result)
IIRC `doWithBaseURLAndOAuthTokenRefresher` was just a stopgap to not fix compile errors on all call sites to `doWithBaseURL` (method signatures were different initially during our pairing session, but now they look the same), since `doWithBaseURLAndOAuthTokenRefresher` is smart enough to know if the OAuth token refresh is needed at all (i.e. if a PAT is used, it will not try to refresh).

TLDR, I think we can just delete the current `doWithBaseURL` and rename the `doWithBaseURLAndOAuthTokenRefresher`.

2022-08-03 05:29 UTC, unknwon commented on internal/oauthutil/oauth2.go
> +}
>Please, see a comment above where I explain why it has been removed.

Do you have a link to the comment?

2022-08-03 05:31 UTC, unknwon commented on internal/extsvc/auth/oauth_bearer.go
> +type oauthBearerTokenWithRefresher struct {
Pretty sure we can just delete this if there is no usage of it in this PR.

2022-08-03 05:33 UTC, unknwon commented on internal/repos/oauthhelper.go
> +func (r *RefreshTokenConfig) RefreshToken(ctx context.Context, doer httpcli.Doer, oauthCtx oauthutil.OauthContext) (string, error) {
What's the exact error?

2022-08-03 15:29 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +					log.Bool("tokenExpired", tokenExpired),
Can we include this boolean in the `acctLogger.Warn` statement? That would make the logs more readable IMO.

2022-08-03 15:29 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +				acctLogger.Warn("setExternalAccountExpired, couldn't refresh token",
Ideally, this logic would go to the provider itself. E.g. if we call `provider.FetchUserPerms`, it can also refresh the token if needed. That way, the consumer (perms syncer) does not need to worry about token refresh at all. Similar to how we use `doWithBaseURLAndOAuthTokenRefresher` below.

Not sure how the discussion/changes went while I was away, so feel free to tell me why we need to keep this here.

2022-08-03 15:29 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +	_, token, err := gitlab.GetExternalAccountData(&acct.AccountData)
Should we first check if the auth provider is actually a gitlab auth provider before calling gitlab here? E.g. if it failed for non-gitlab at the moment, we would just fail here.

2022-08-03 17:12 UTC, miveronese commented on internal/oauthutil/oauth2.go
> +}
Oops, forgot to save the comment. Here is the link: https://github.com/sourcegraph/sourcegraph/pull/39840/files#r936943700

2022-08-03 17:14 UTC, miveronese commented on internal/oauthutil/oauth2.go
> +}
The reason for removing the RefershToken field is that OauthContext has access to  client data but not to user data and, because of that, it didn’t seem like the best place to put the attribute RefreshToken.
As we need the refresh token, it make more sense, imo, to pass it to the helper (example [here](https://github.com/sourcegraph/sourcegraph/pull/39840/files#r936943700))

2022-08-03 20:13 UTC, miveronese commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +				acctLogger.Warn("setExternalAccountExpired, couldn't refresh token",
Many thanks, @kopancek , for catching this. After taking another look at this part,  I realized that this logic is not even necessary.

Let me try to describe the steps that I followed to conclude this: 

- [`fetchUserPermsViaExternalAccounts`](https://github.com/sourcegraph/sourcegraph/blob/mv/refresh-token/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L278) calls [`provider.FetchUserPerms`](https://github.com/sourcegraph/sourcegraph/blob/mv/refresh-token/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go#L377) which uses a [`client`](https://github.com/sourcegraph/sourcegraph/blob/mv/refresh-token/enterprise/internal/authz/gitlab/oauth.go#L107)  that already comes with a tokenRefresher when making the API call to list projects. 

- in consequence, when we call `c.do` to [list projects,](https://github.com/sourcegraph/sourcegraph/blob/mv/refresh-token/internal/extsvc/gitlab/projects.go#L225) the client's `do` method will use [`doWithBaseURLAndOAuthTokenRefresher`](https://github.com/sourcegraph/sourcegraph/blob/mv/refresh-token/internal/extsvc/gitlab/client.go#L288) which will let [`oauthutil.DoRequest` ](https://github.com/sourcegraph/sourcegraph/blob/mv/refresh-token/internal/extsvc/gitlab/client.go#L322)handle the token expiration...

2022-08-03 22:17 UTC, miveronese commented on internal/repos/oauthhelper.go
> +func (r *RefreshTokenConfig) RefreshToken(ctx context.Context, doer httpcli.Doer, oauthCtx oauthutil.OauthContext) (string, error) {
Here are two examples of the full output:

1) if the helper is added as part of the package oauthutil (in `internal/oauthutil/`) and used by `internal/repos/gitlab`

```
Failed to build worker: 'bash -c if [ -n "$DELVE" ]; then
  export GCFLAGS='all=-N -l'
fi
go build -gcflags="$GCFLAGS" -o .bin/worker github.com/sourcegraph/sourcegraph/enterprise/cmd/worker' failed: package github.com/sourcegraph/sourcegraph/enterprise/cmd/worker
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared
	imports github.com/sourcegraph/sourcegraph/cmd/worker/internal/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/db
	imports github.com/sourcegraph/sourcegraph/internal/database
	imports github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab
	imports github.com/sourcegraph/sourcegraph/internal/oauthutil
	imports github.com/sourcegraph/sourcegraph/internal/database: import cycle not allowed
package github.com/sourcegraph/sourcegraph/enterprise/cmd/worker
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared
	imports github.com/sourcegraph/sourcegraph/cmd/worker/internal/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/db
	imports github.com/sourcegraph/sourcegraph/internal/database
	imports github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab
	imports github.com/sourcegraph/sourcegraph/internal/oauthutil
	imports github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab: import cycle not allowed: exit status 1:
package github.com/sourcegraph/sourcegraph/enterprise/cmd/worker
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared
	imports github.com/sourcegraph/sourcegraph/cmd/worker/internal/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/db
	imports github.com/sourcegraph/sourcegraph/internal/database
	imports github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab
	imports github.com/sourcegraph/sourcegraph/internal/oauthutil
	imports github.com/sourcegraph/sourcegraph/internal/database: import cycle not allowed
package github.com/sourcegraph/sourcegraph/enterprise/cmd/worker
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared
	imports github.com/sourcegraph/sourcegraph/cmd/worker/internal/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/codeintel
	imports github.com/sourcegraph/sourcegraph/cmd/worker/shared/init/db
	imports github.com/sourcegraph/sourcegraph/internal/database
	imports github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab
	imports github.com/sourcegraph/sourcegraph/internal/oauthutil
	imports github.com/sourcegraph/sourcegraph/internal/extsvc/gitlab: import cycle not allowed

````


2) when  the helper is  in `enterprise/internal/oauth/refresh_helper.go` and used by `internal/repos/gitlab`


```
--------------------------------------------------------------------------------
Failed to build gitserver: 'bash -c if [ -n "$DELVE" ]; then
  export GCFLAGS='all=-N -l'
fi
go build -gcflags="$GCFLAGS" -o .bin/gitserver github.com/sourcegraph/sourcegraph/cmd/gitserver' failed: package github.com/sourcegraph/sourcegraph/cmd/gitserver
	imports github.com/sourcegraph/sourcegraph/internal/repos
	internal/repos/gitlab.go:16:2: use of internal package github.com/sourcegraph/sourcegraph/enterprise/internal/oauth not allowed: exit status 1:
package github.com/sourcegraph/sourcegraph/cmd/gitserver
	imports github.com/sourcegraph/sourcegraph/internal/repos
	internal/repos/gitlab.go:16:2: use of internal package github.com/sourcegraph/sourcegraph/enterprise/internal/oauth not allowed

```

2022-08-08 10:31 UTC, unknwon commented on internal/oauthutil/oauth2.go
> +}
Got it, makes sense!

2022-08-11 05:25 UTC, unknwon requested changes
Nice, most of changes are LGTM!

Suggested new PR title: "oauth: support automatic token refresh and retry logic for GitLab"

2022-08-11 05:25 UTC, unknwon commented on enterprise/internal/authz/gitlab/oauth.go
> +// The client used by this method will be in charge of updating the oauth token if it is expired and retry the request.
```suggestion
// The client used by this method will be in charge of updating the OAuth token if it is expired and retry the request.
```

2022-08-11 05:25 UTC, unknwon commented on enterprise/internal/authz/gitlab/oauth.go
> +
```suggestion
```

2022-08-11 05:25 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +// it  will make a retry and refresh in case the token has expired.
```suggestion
// it will try to refresh the token and retry the same request when the token has expired.
```

2022-08-11 05:25 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +	return client
Ideally, it should be done in the opposite way.

1. Move the body of current `newClient` to `NewClientWithTokenRefresher`.
2. In `newClient`, call `NewClientWithTokenRefresher(..., p.tokenRefresher)`

2022-08-11 05:25 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +
```suggestion
```

2022-08-11 05:25 UTC, unknwon commented on enterprise/internal/authz/gitlab/oauth.go
> +	client := p.clientProvider.NewClientWithTokenRefresher(p.clientURL, &auth.OAuthBearerToken{Token: tok.AccessToken}, p.clientProvider.HTTPClient, helper.RefreshToken)
Because we no longer use `GetOAuthClient`, which has the capability to cache "clients", we need to create a followup issue to support caching, or address it in this PR.

I don't have the historical context of why caching clients is needed, so I'm leaning towards the former.

2022-08-11 05:25 UTC, unknwon commented on internal/database/refresh_token_helper_test.go
> +	}
```suggestion
	require.NoError(t, err)
	assert.Equal(t, expectedNewToken, newToken)
```

2022-08-11 05:25 UTC, unknwon commented on internal/database/refresh_token_helper_test.go
> +	}
ditto

2022-08-11 05:25 UTC, unknwon commented on internal/extsvc/auth/oauth_bearer.go
> +
Is this still needed?

2022-08-11 05:25 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +		if oauthContext != nil {
```suggestion
	if ok && oauthContext != nil {
```

2022-08-11 05:25 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +func getOauthContext() *oauthutil.OauthContext {
```suggestion
func getOAuthContext() *oauthutil.OauthContext {
```

2022-08-11 05:25 UTC, unknwon commented on internal/extsvc/gitlab/client_test.go
> +func TestClient_doWithBaseURLWithOAuthContext(t *testing.T) {
```suggestion
func TestClient_doWithBaseURL(t *testing.T) {
```

2022-08-11 06:50 UTC, ryanslade commented on internal/database/oauth_token_helper.go
> +		success := err == nil
I think you need named return values like the method lower down for defer to have access to err here

2022-08-11 06:56 UTC, ryanslade commented on internal/oauthutil/token.go
> +	r.Body.Close()
Might want to check the error here too

2022-08-11 13:21 UTC, miveronese commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +					log.Bool("tokenExpired", tokenExpired),
resolving this as it outdated.

2022-08-11 15:48 UTC, pjlast commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> -		}
What is the reasoning behind removing the waitForRateLimit? 🤔

2022-08-11 16:12 UTC, miveronese commented on enterprise/internal/authz/gitlab/oauth.go
> +	client := p.clientProvider.NewClientWithTokenRefresher(p.clientURL, &auth.OAuthBearerToken{Token: tok.AccessToken}, p.clientProvider.HTTPClient, helper.RefreshToken)
Hum, I[ think this suggestion ](https://github.com/sourcegraph/sourcegraph/pull/39840#discussion_r943100678)will address the cache issue...

2022-08-11 16:18 UTC, miveronese commented on internal/extsvc/auth/oauth_bearer.go
> +
yes, it's used here: https://github.com/sourcegraph/sourcegraph/blob/mv/refresh-token/internal/oauthutil/oauth2.go#L96

2022-08-11 16:25 UTC, miveronese commented on internal/extsvc/gitlab/client.go
> +func getOauthContext() *oauthutil.OauthContext {
@unknwon , are my eyes tricking me or both lines are equal?  Wondering if the suggestion is to export the function...

2022-08-11 17:04 UTC, miveronese commented on internal/oauthutil/token.go
> +	r.Body.Close()
@ryanslade , I am wondering if this format would be acceptable for SG codebase

````
	body, err := io.ReadAll(io.LimitReader(r.Body, 1<<20))
	defer func(Body io.ReadCloser) {
		err := Body.Close()
		if err != nil {
			logger.Error("oauth2: error closing body", log.Error(err))
		}
	}(r.Body)

2022-08-11 17:08 UTC, miveronese commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> -		}
Good catch! I'm returning it back to where it was :)

2022-08-12 03:50 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +func getOauthContext() *oauthutil.OauthContext {
![CleanShot 2022-08-12 at 11 50 16@2x](https://user-images.githubusercontent.com/2946214/184281819-dafc2e22-d927-415e-8357-75ea936f9291.png)

2022-08-12 05:14 UTC, unknwon commented on internal/oauthutil/token.go
> +	r.Body.Close()
I'm leaning towards just ignoring the `Close` error here.

2022-08-12 05:20 UTC, unknwon commented
Please re-request review once ready again 🙏

2022-08-12 13:08 UTC, miveronese commented on internal/extsvc/gitlab/client.go
> +func getOauthContext() *oauthutil.OauthContext {
I was so blind! :D

2022-08-12 18:21 UTC, miveronese commented
Team, suggestions were addressed (thank you!!) and a change was made to fix a problem pointed by a test on buildkite.

You can see the diff here[](https://github.com/sourcegraph/sourcegraph/pull/39840/commits/56687ecc8a7c73bc8a7f8a0615a5531f81928470#diff-2781bcb50a9a16a3cbce94d0db108ca460a12c1e3443a70e1b285c31588280fbL116) , in the oauth.go file (a function signature was changed). 

The based url used originally passed as a param to that fubction was the one from the clientProvider (https://gitlab.com). But, as shown on this test,[](https://github.com/sourcegraph/sourcegraph/blob/56687ecc8a7c73bc8a7f8a0615a5531f81928470/enterprise/internal/authz/gitlab/oauth_test.go#L77)  the base url should be “ https://gitlab.com/api/v4”.

2022-08-15 04:07 UTC, unknwon reviewed
Thanks for the followup! Didn't finish another full review, but left some comments :)

2022-08-15 04:07 UTC, unknwon commented on enterprise/internal/authz/gitlab/oauth.go
> +// The client used by this method will be in charge of updating the Oauth token if it is expired and retry the request.
Grammarly says so...

```suggestion
// The client used by this method will be in charge of updating the OAuth token if it has expired and retrying the request.
```

2022-08-15 04:07 UTC, unknwon commented on enterprise/internal/authz/gitlab/oauth_test.go
> +	mockedOauthCtx :=
```suggestion
	mockedOAuthCtx :=
```

2022-08-15 04:07 UTC, unknwon commented on internal/database/oauth_token_helper.go
> +	}()
```suggestion
	defer func() {
		success := err == nil
		gitlab.TokenRefreshCounter.WithLabelValues("external_account", strconv.FormatBool(success)).Inc()
	}()
	
	refreshedToken, err := oauthutil.RetrieveToken(doer, oauthCtx, r.OauthRefreshToken, oauthutil.AuthStyleInParams)
	if err != nil {
		...
	}
```

2022-08-15 04:07 UTC, unknwon commented on internal/database/oauth_token_helper_test.go
> +		_ = json.Unmarshal([]byte(extSvc[0].Config), &result)
I think the error here is worth checking.

2022-08-15 04:07 UTC, unknwon commented on internal/database/oauth_token_helper_test.go
> +		}
assert.Equal(t, expectedRefreshToken, result["token.oauth.refresh"])

2022-08-15 04:07 UTC, unknwon commented on internal/database/oauth_token_helper_test.go
> +
```suggestion
```

2022-08-15 04:07 UTC, unknwon commented on internal/database/oauth_token_helper_test.go
> +	ctxOauth := oauthutil.OAuthContext{}
```suggestion
	oauthCtx := oauthutil.OAuthContext{}
```

2022-08-15 04:07 UTC, unknwon commented on internal/database/oauth_token_helper_test.go
> +
```suggestion
```

2022-08-15 08:23 UTC, ryanslade commented on internal/oauthutil/token.go
> +	r.Body.Close()
I'm ok with just ignoring the error like Joe said, we have many places in the codebase where we do something like that:
https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+_+%3D+%5Cw.Close%28%29&patternType=regexp

2022-08-17 10:01 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +		tokenRefresher:   refresher,
I think we were not using passed `refresher` in your previous manual tests, which concerns me a little bit (or maybe why your tests weren't passing).

We need to carefully e2e test manually before merging this PR.

2022-08-17 10:04 UTC, unknwon approved these changes

2022-08-17 11:56 UTC, kopancek approved these changes

2022-08-17 12:12 UTC, miveronese commented on internal/extsvc/gitlab/client.go
> +		tokenRefresher:   refresher,
Thank you, @unknwon ! Once I have a 
a notebook, I will test the whole flow again. Interesting is that manual tests )until the part I described) and unit tests were green 🤔... I will take a look at the changes you pushed and see what I can find.

2022-08-17 13:52 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +		tokenRefresher:   refresher,
OK, I've manually e2e tested refresh for external accounts, changes were missing for it to work are added in https://github.com/sourcegraph/sourcegraph/pull/39840/commits/3908aaf99d89560b10988f8e0791f5376d12ea5a.

2022-08-17 14:16 UTC, kopancek approved these changes

2022-08-17 17:03 UTC, merged

2022-08-24 17:45 UTC, eseliger reviewed
Found this diff by accident while trying to find something else, added 3 questions I had while reading it!

2022-08-24 17:45 UTC, eseliger commented on enterprise/internal/batches/sources/gitlab.go
> +	provider := gitlab.NewClientProvider(urn, baseURL, cli, nil)
yes it does, what's needed to support that?

2022-08-26 09:20 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +	}
Oh gosh, good catch! The `baseURL` should be passed in for comparison ... will send a PR soon.

2022-08-26 09:21 UTC, eseliger commented on internal/extsvc/gitlab/client.go
> +	}
Thanks!

2022-08-26 09:23 UTC, unknwon commented on enterprise/internal/batches/sources/gitlab.go
> +	provider := gitlab.NewClientProvider(urn, baseURL, cli, nil)
The duty of the `tokenRefresher` is to take care of storing the new token back to the database. Here are examples for storing back to `user_external_accounts` and `external_services` tables: https://github.com/sourcegraph/sourcegraph/blob/main/internal/database/oauth_token_helper.go

2022-08-26 10:18 UTC, unknwon commented on internal/extsvc/gitlab/client.go
> +	}
PR sent: https://github.com/sourcegraph/sourcegraph/pull/40897