Code Insights: Support color for compute powered insight
sourcegraph/sourcegraph pull request #40038
Opened 2022-08-05 20:22 UTC by vovakulikov

Closes https://github.com/sourcegraph/sourcegraph/issues/38832

## Background 
Considering a given timeframe for Sourcegraph 4.0, we disable multi-series support for compute-powered insight. This PR 
- hides add a new series button in the creation UI
- adds colour picker to series creation form
- adjust the insight card layout for the compute-powered insight. Now it doesn't render legend block (see related comment https://github.com/sourcegraph/sourcegraph/pull/39805#issuecomment-1205879211) 

## Test plan
- Go to the compute insight creation UI 
- Create compute insight (make sure that you can't have more than one series) 
- See that this insight was created correctly, and you can see it on the dashboard page.

2022-08-08 12:27 UTC, chwarwick approved these changes
This appears good to me.  I did notice that it takes on Track Changes edit behavior where you could remove the 1 and only series, and not the capture group behavior where you can't.  I think that is ok assuming we intend to eventually add back the ability to have multiple series.

2022-08-08 12:33 UTC, AlicjaSuska requested changes
Thank you for making this change @vovakulikov
1. we need to change the copy on the 'group results' card to mirror this change from

> Insight that groups results by repository, path, author or date. You will define each data series manually.

To:

> Insight based on a custom Sourcegraph search query that groups results by repository, path, author or date. 

2. Small visual issue: disabled group buttons (author and date) have all round corners. When buttons become active, issue no longer exists:
<img width="311" alt="Screenshot 2022-08-08 at 14 28 09" src="https://user-images.githubusercontent.com/20326070/183418031-9bdcb8d5-349b-4f06-be07-a22f9fcbc28a.png">

3. Not critical, can be out of scope: I'm not sure about how useful is to keep both 'name' for the series and 'name' for the chart. In this case when we only have one series, they would probably be the same in most cases. My proposition is to remove the 'name' field form the data series form for now. Also, data series name is not displayed in the final chart on the dashboard.

4. Important: when creating insight from the 'all insights' dashboard, it was not saved. I couldn't find it in 'All insights' ([loom](https://www.loom.com/share/d78e5a38b8464b0595c0981979868994)). When creating an insight from my private dashboard, insight was added there correctly ([loom](https://www.loom.com/share/4af2e5f52ccc4f889165674c004754c7)).

2022-08-08 15:39 UTC, vovakulikov commented
Thanks @chwarwick @AlicjaSuska for your review

- About remove behavior, this is a good comment. The compute creation UI reuses the same data series component that we use for the track changes creation UI. I didn't refactor this component because as you mentioned we perhaps will get this behavior for compute insight anyway. 

-  copy on the 'group results'. @AlicjaSuska thanks for catching this. I updated the copy. 
- `Small visual issue: disabled group buttons`. This problem comes from the wildcard component and we've seen this before while were creating this page initially. I have an issue for it here https://github.com/sourcegraph/sourcegraph/issues/40094 
- `Not critical, can be out of scope: I'm not sure about how useful is to keep both 'name' for the series and 'name' for the chart`. This is a good call. I agree that we don't need to have this name field here if we have only one series. Currently this component has been reused from the track changes creation UI and it makes it difficult to just remove it for compute powered creation UI. Let's track this in a separate issue here https://github.com/sourcegraph/sourcegraph/issues/40095. I'm not sure that we will have time for it but let's mark this as a stretch issue for the iteration 26
- `Important: when creating insight from the 'all insights' dashboard, it was not saved. I couldn't find it in 'All insights'` I tried to repro this in sourcegraph.sourcegraph staging and couldn't catch this. But this sounds like BE problem. I will try to catch this and notify BE engs if needed, thanks for noticing this

2022-08-10 09:16 UTC, vovakulikov commented
This should be fixed now in this branch 

> Important: when creating insight from the 'all insights' dashboard, it was not saved. I couldn't find it in 'All insights'

2022-08-10 15:04 UTC, AlicjaSuska commented
Thank you @vovakulikov for making changes and creating the issues. I think everything looks good now, the insight also was saved in 'all insights' correctly.

2022-08-10 15:05 UTC, AlicjaSuska approved these changes

2022-08-11 09:43 UTC, merged