Search: Add aggregation panel mock UI
sourcegraph/sourcegraph pull request #40138
Opened 2022-08-09 12:35 UTC by vovakulikov

Closes https://github.com/sourcegraph/sourcegraph/issues/39954
Closes https://github.com/sourcegraph/sourcegraph/issues/40088

[Low-fi Figma designs](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126?node-id=260%3A11)

## Background 
This PR adds mock (no data) UI for aggregation panel UI on the search result page. 

## Follow-ups
- The sidebar panel is stored in the `search-ui` package. Currently, chart UI components are stored in the `web` package. Because of this, PR introduces a cyclic link since we import chart UI into search from `web` and the `web` package imports `search-ui` for the search result page. Webpack can handle this, and this is how it works at the moment, but we should move chart UI into Wildcard (or another separate package) to resolve this problem in our codebase https://github.com/sourcegraph/sourcegraph/issues/40136

## Test plan
- Go to the search result page 
- See that nothing is changed and the side panel layout looks correct for mobile and desktop 
- Turn on the global feature flag `search-aggregation-filters.`
- See that you can see mock UI for the aggregation panel, panel should look properly for mobile and desktop

2022-08-09 17:10 UTC, vovakulikov commented
Convert to draft status since the Hi-Fi design is in process, and we will adjust this PR implementation as soon as possible, right after the design is complete.

2022-08-12 16:29 UTC, felixfbecker commented on client/search-ui/src/results/sidebar/SearchAggregations.tsx
> +        enterpriseLicenseHasFeature(feature: "code-insights")
Why do we need to do a license check for this – this is counter to [the decision in the RFC](https://docs.google.com/document/d/1yLV7MGOEXYT3yPvBxHHm8y2-p737KIrju_QPqlhBYz4/edit#heading=h.ot1jcs9xa5ch)?

2022-08-12 16:29 UTC, felixfbecker commented on client/search-ui/src/results/sidebar/SearchAggregations.tsx
> +const AGGREGATION_MODE_URL_KEY = 'aggregation_mode'
I would suggest to call this parameter `groupBy` just like in the UI, so it becomes e.g. `&groupBy=repo`. "mode" is more ambiguous (for example, I at first thought it would encode whether the full view is used or not)

2022-08-12 16:29 UTC, felixfbecker commented on client/wildcard/src/components/Charts/components/bar-chart/components/GroupedBars.tsx
> +                                    opacity={activeSegment ? (activeSegment.category.id === category.id ? 1 : 0.5) : 1}
Consistency between charts on the dashboard and on the search page was a stated goal (and also reduces complexity) – can we keep this style consistent? @AlicjaSuska any reason they should be different?

2022-08-15 10:52 UTC, vovakulikov commented on client/search-ui/src/results/sidebar/SearchAggregations.tsx
> +        enterpriseLicenseHasFeature(feature: "code-insights")
This is a good call. Here we should use an enterprise check instead, which should be just a sync prop check.

2022-08-15 10:59 UTC, vovakulikov commented on client/wildcard/src/components/Charts/components/bar-chart/components/GroupedBars.tsx
> +                                    opacity={activeSegment ? (activeSegment.category.id === category.id ? 1 : 0.5) : 1}
@felixfbecker I'm not sure I understand what this means 
>can we keep this style consistent?

Do you mean that we should have it in the core `BarChart` component, and your comment here is more about my comment above about moving this logic to the consumer? 

@AlicjaSuska for the context - at the moment, the active bar is highlighted, fading other bars with `opacity: 0.5`. I think this is okay for the first version, but it doesn't seem correct because behind bars, we have Y-axis lines, and you can see them through semi-transparent bar elements. 

Instead of opacity, I think we should use just different color (darken color) for non-active bars. My logic was that different consumers would want to have a different logic about highlighting/fading active/other bars. 

With this PR change in dashboard, creation UI, and search result page charts, they all have the same logic/styles about active/non-active bars.

2022-08-15 20:06 UTC, vovakulikov commented on client/search-ui/src/results/sidebar/SearchAggregations.tsx
> +const AGGREGATION_MODE_URL_KEY = 'aggregation_mode'
Agreed, that Makes sense. Thanks for spotting this.

2022-08-16 02:05 UTC, felixfbecker commented on client/wildcard/src/components/Charts/components/bar-chart/components/GroupedBars.tsx
> +                                    opacity={activeSegment ? (activeSegment.category.id === category.id ? 1 : 0.5) : 1}
Maybe I misunderstood the code/comment here, looks like it actually is consistent between consumers, just that this is new styling behavior. That seems fine then. But I think we should avoid more updates to styling of the charts in the interest of keeping the engineering effort small (unless they're required fixes part of the grouping insight type follow-up work). I think seeing the Y axis lines is also fine through opacity, we shouldn't get lost over whether it should be opacity or a darker color and which color it should be.

2022-08-16 02:13 UTC, felixfbecker approved these changes
Just approving to mark that my concerns (pending one suggestion) are resolved, I didn't review the code itself.

2022-08-16 02:13 UTC, felixfbecker commented on client/search-ui/src/results/sidebar/SearchAggregations.tsx
> +        case 'groups':
We decided we'll only use the first capture group, so this should be singular. I'd also recommend spelling `captureGroup` out, because `groupBy=group` could be confusing.
```suggestion
        case 'captureGroup':
```

2022-08-16 12:05 UTC, vovakulikov commented on client/search-ui/src/results/sidebar/SearchAggregations.tsx
> +        case 'groups':
Agreed, I changed serialise/deserialise functions. Thanks.

2022-08-16 19:24 UTC, unclejustin requested changes
@vovakulikov I have a couple of concerns about overloading `BarChart`. Please take a look.

2022-08-16 19:24 UTC, unclejustin commented on client/wildcard/src/components/Charts/components/bar-chart/BarChart.tsx
> +    getTruncatedXTick?: (formattedTick: string) => string
I feel like BarChart is getting pretty overloaded. I think there is an opportunity to break the axis out into their own components here. WDYT?

2022-08-16 19:24 UTC, unclejustin commented on client/wildcard/src/components/Charts/components/bar-chart/components/TooltipContent.module.scss
> +    // Be default Text (which is p element) has bottom margin
```suggestion
    // The default Text (which is p element) has bottom margin
```

2022-08-16 19:24 UTC, unclejustin commented on client/wildcard/src/components/Charts/components/bar-chart/components/TooltipContent.tsx
> +            {category.data.length > 1 && <H3>{category.id}</H3>}
Is it possible for the length to be less than 1? If not, I think we can get rid of this check altogether.

2022-08-16 19:24 UTC, unclejustin commented on client/wildcard/src/components/Charts/components/bar-chart/components/TooltipContent.tsx
> +    }
I'm not sure how I feel about this early return. I feel like we're hiding some of the intent in how this is used.

WDYT about breaking this out to its own component and handling the switch in `BarChartContent` where it's called?

2022-08-16 20:18 UTC, vovakulikov commented on client/wildcard/src/components/Charts/components/bar-chart/components/TooltipContent.tsx
> +    }
I thought about moving this special case to the consumer level of this tooltip component (which is barChartContent, but then it becomes more complex to compose this with other components (it's another case that you need to keep in mind, so I picked hide this complexity in TooltipContent component). 

In an ideal world, you should be able to compose these components freely like 
```tsx
<BarChartRoot>
  <AxisX>
  <AxisY>
  <BarChartContent>{() => <YourCustomBarChartContent />}</BarChartContent>
  <YourCustomTooltipContent/>
</BarChartRoot>

```

So I want to think about the BarChart component as a built-in component that you can use as something that can allow you to visualise your data quickly, but if you need to do something custom (custom tooltip or custom axis or chart content, you need to build your own chart with low-level blocks that we provide.

2022-08-16 20:33 UTC, vovakulikov commented on client/wildcard/src/components/Charts/components/bar-chart/components/TooltipContent.tsx
> +            {category.data.length > 1 && <H3>{category.id}</H3>}
This is correct since we handle a special single data point with early return we can remove this check here

2022-08-16 21:19 UTC, unclejustin commented on client/wildcard/src/components/Charts/components/bar-chart/components/TooltipContent.tsx
> +    }
> if you need to do something custom (custom tooltip or custom axis or chart content, you need to build your own chart

I feel like we're already into that realm here. I don't feel strongly enough about it to block this PR though.

2022-08-16 21:20 UTC, unclejustin approved these changes

2022-08-16 22:05 UTC, limitedmage approved these changes

2022-08-18 08:54 UTC, merged