Replace DevToolTime with Discord in search footer
sourcegraph/sourcegraph pull request #40315
Opened 2022-08-12 19:39 UTC by jdorfman

Signed-off-by: Justin Dorfman <justin.dorfman@sourcegraph.com>

Replaces the DevToolTime logo/ad with a Discord server invite.

## Test plan

- Is the svg logo optimized
- Make sure link works
- Grammar check
- Run by Fabiana (branding)

2022-08-12 19:44 UTC, jdorfman commented
@fabicastp This will replace this:
![Image 2022-08-12 at 12 41 50 PM](https://user-images.githubusercontent.com/398230/184431554-d9ce8740-5615-4e04-bd77-06c6713e1bea.jpg)

With this:
<img width="991" alt="Image 2022-08-12 at 12 42 28 PM" src="https://user-images.githubusercontent.com/398230/184431801-76cda5b7-45f4-4324-a7ff-d5903ddc87dd.png">

2022-08-12 19:47 UTC, limitedmage approved these changes
LGTM from the dev side 👍

2022-08-12 19:48 UTC, limitedmage commented on client/web/src/search/home/SearchPageFooter.tsx
>                          className={styles.devToolTimeWrapper}
Very minor but may want to replace this and other CSS class that say `devToolTime` with something more relevant here (maybe `discord`?)

2022-08-12 19:48 UTC, limitedmage commented on client/web/src/search/home/SearchPageFooter.tsx
> -                            src={`${assetsRoot}/img/devtooltime-logo.svg`}
We can delete this image if it's not used anywhere anymore.

2022-08-12 19:54 UTC, jdorfman commented on client/web/src/search/home/SearchPageFooter.tsx
>                          className={styles.devToolTimeWrapper}
@limitedmage good catch. I'm not sure what to do. Can I just rename it or do I need to update the class in a CSS file?

2022-08-12 20:49 UTC, jdorfman commented on client/web/src/search/home/SearchPageFooter.tsx
> -                            src={`${assetsRoot}/img/devtooltime-logo.svg`}
done

2022-08-15 15:47 UTC, jdorfman commented
@limitedmage can you help me with the CSS 🙏

2022-08-15 16:18 UTC, danieldides commented
I'm not sure if it matters but that is the [old discord logo](https://support.discord.com/hc/en-us/articles/1500009438682-A-Fresh-New-Look-to-Celebrate-Our-6th-Birthday) in the screenshot.

2022-08-15 16:26 UTC, jdorfman commented
@danieldides yeah I was emphasizing what this PR would replace. In hindsight, I can see how it could be confusing.

2022-08-15 20:23 UTC, jdorfman commented
@danieldides @limitedmage what are the final steps to get this merged?

2022-08-15 20:25 UTC, danieldides commented
@jdorfman It looks like it's failing a check in buildkite
> Checked 2 files and found SVG optimizations. Please run 'yarn optimize-svg-assets ui/assets/img' and commit the result.

2022-08-16 16:47 UTC, jdorfman commented
@danieldides it keeps failing even those I'm getting this:

```
$ yarn optimize-svg-assets ui/assets/img

yarn run v1.22.4
$ svgo --multipass --config="./svgo.config.js" ui/assets/img
Processing directory 'ui/assets/img':


codemonitoring-notify-dark.svg:
Done in 40 ms!
1.136 KiB - 0% = 1.136 KiB

codemonitoring-search-dark.svg:
Done in 20 ms!
0.986 KiB - 0% = 0.986 KiB

codemonitoring-notify-light.svg:
Done in 26 ms!
1.129 KiB - 0% = 1.129 KiB

customer-logos-dark.svg:
Done in 92 ms!
15.871 KiB - 0% = 15.871 KiB

codemonitoring-illustration-light.svg:
Done in 109 ms!
46.549 KiB - 0% = 46.549 KiB

discord-footer-logo.svg:
Done in 25 ms!
1.051 KiB - 0% = 1.051 KiB

homepage-hero-dark.svg:
Done in 911 ms!
179.215 KiB - 0% = 179.215 KiB

logo-chrome.svg:
Done in 27 ms!
3.286 KiB - 0% = 3.286 KiB

codemonitoring-illustration-dark.svg:
Done in 103 ms!
47.935 KiB - 0% = 47.935 KiB

customer-logos-light.svg:
Done in 76 ms!
15.87 KiB - 0% = 15.87 KiB

codemonitoring-search-light.svg:
Done in 4 ms!
0.983 KiB - 0% = 0.983 KiB

sourcegraph-mark.svg:
Done in 2 ms!
0.528 KiB - 0% = 0.528 KiB

homepage-hero-light.svg:
Done in 750 ms!
173.888 KiB - 0% = 173.888 KiB

notepad-illustration-light.svg:
Done in 26 ms!
6.279 KiB - 0% = 6.279 KiB

sourcegraph-logo-dark.svg:
Done in 10 ms!
4.795 KiB - 0% = 4.795 KiB

sourcegraph-logo-light.svg:
Done in 14 ms!
4.795 KiB - 0% = 4.795 KiB

notepad-illustration-dark.svg:
Done in 18 ms!
6.498 KiB - 0% = 6.498 KiB

logo-firefox.svg:
Done in 414 ms!
211.686 KiB - 0% = 211.686 KiB
✨  Done in 3.54s.
```

2022-08-17 20:54 UTC, chwarwick requested changes

2022-08-17 20:54 UTC, chwarwick commented on enterprise/internal/insights/resolvers/aggregates_resolvers.go
> -	for _, mode := range types.SearchAggregationModes {
The changes in this file look like they are accidentally included.

2022-08-17 20:58 UTC, jdorfman commented
Opening up a new PR, don't ask.

2022-08-17 20:58 UTC, closed without merging