Sanitise base64 encoded SVGs in Markdown rendering
sourcegraph/sourcegraph pull request #40416
Opened 2022-08-16 13:33 UTC by evict

## Test plan

2022-08-17 13:29 UTC, unclejustin commented on client/common/src/util/markdown/markdown.ts
> +                    } catch (any) {
```suggestion
                    } catch (error) {
```

@evict the linter is upset with `any`

2022-08-17 14:40 UTC, mohammadualam approved these changes

2022-08-17 23:19 UTC, felixfbecker reviewed
I would suggest we simply remove `svg` (and the other SVG elements) form the `allowedTags` list. Code Insights extensions were the only known consumer, and they don't display these anymore anywhere, and extensions are being deprecated in general. If any extension or extension README or Notebook markdown used `<svg>` somewhere directly it will probably not be completely broken just because the graphic is missing. The impact of this will be non-existent to negligible, compared to trying to handle a bunch of extra cases that might still have security holes and need a lot of additional code.

2022-08-17 23:19 UTC, felixfbecker commented on client/common/src/util/markdown/markdown.ts
> +                        cleaned = sanitize(window.atob(b64object), {
Note that this can throw if the string contains Unicode (which is caught below though)
https://developer.mozilla.org/en-US/docs/Web/API/btoa

2022-08-17 23:19 UTC, felixfbecker commented on client/common/src/util/markdown/markdown.ts
> +                    if (!attribs.data.includes('base64,')) {
`data:` URIs can contain code without `base64` encoding too. This catches the base64 case but leaves the vulnerability open for plaintext

2022-08-17 23:19 UTC, felixfbecker commented on client/common/src/util/markdown/markdown.ts
> +                        cleaned = sanitize(window.atob(b64object), {
Also not sure if `sanitize-html` is safe to call on XML

2022-08-18 08:46 UTC, evict commented on client/common/src/util/markdown/markdown.ts
> +                    if (!attribs.data.includes('base64,')) {
You are right. `ascii` and `utf8` work as well. If you can use any case as well `AscII` or `BaSe64` would already bypass current filter.

2022-08-18 08:47 UTC, evict commented on client/common/src/util/markdown/markdown.ts
> +                        cleaned = sanitize(window.atob(b64object), {
We are still only looking for HTML style tags like `script` and the XSS would require HTML syntax to trigger, so it's fine.

2022-08-18 08:50 UTC, evict commented on client/common/src/util/markdown/markdown.ts
> +                    if (!attribs.data.includes('base64,')) {
> I would suggest we simply remove `<object>` from the `allowedTags` list until we have a CSP. Code Insights extensions were the only known consumer, and they don't display these anymore anywhere, and extensions are being deprecated in general. If any extension or extension README or Notebook markdown used `<object>` somewhere it will probably not be completely broken just because the embed is missing and an SVG could still be embedded with an `<img>` as a workaround. The impact of this will be non-existent to negligible, compared to trying to handle a bunch of extra cases that might still have security holes and need a lot of additional code.

If outright disabling `<object>` is possible then this is the best option. No need to try and build an XSS filter if we can disable it. 👍  @sourcegraph/code-insights can we disable usage of  `<object>` tags in markdown?

2022-08-19 16:09 UTC, evict commented
@felixfbecker I've removed the `<object>` tags and updated the tests!

2022-08-23 14:33 UTC, lrhacker requested changes

2022-08-23 14:33 UTC, lrhacker commented on client/common/src/util/markdown/markdown.ts
>                  // Support SVGs for code insights.
```suggestion
                // Support SVGs for code insights.
```
Removing the comment would be good too!

2022-08-23 14:33 UTC, lrhacker commented on client/common/src/util/markdown/markdown.test.ts
>      it('allows SVG <object> tags', () => {
Should this test label (and the "filters" test below) now be that it does not allow `object` tags with any additional properties (i.e. it filters out `data`, `type`, etc.)?

2022-08-23 14:55 UTC, evict commented on client/common/src/util/markdown/markdown.ts
>                  // Support SVGs for code insights.
We still support SVGs right? Just not inside `object` tags?

2022-08-23 14:56 UTC, lrhacker commented on client/common/src/util/markdown/markdown.ts
>                  // Support SVGs for code insights.
Yeah, I think the comment was specifically calling out the need for the special-case of `object` tags (which was specifically for Code Insights).

2022-08-23 15:08 UTC, evict commented on client/common/src/util/markdown/markdown.test.ts
>      it('allows SVG <object> tags', () => {
Good point! I've changed the labels of two tests and removed the base64 test case.

2022-08-23 15:59 UTC, merged

2022-08-23 17:41 UTC, felixfbecker commented on client/common/src/util/markdown/markdown.ts
> -                object: ['data', { name: 'type', values: ['image/svg+xml'] }, 'width'],
Note that this change only changes the allowed _attributes_ for `<object>` (it's under the `allowedAttributes` property). It's still explicitly listed in the `allowedTags` array on line 106, which may be a bit confusing. I don't know if that has security implications though, I don't know what damage an empty `<object>` could do or what attributes are allowed by default.

2022-08-24 08:30 UTC, evict commented on client/common/src/util/markdown/markdown.ts
> -                object: ['data', { name: 'type', values: ['image/svg+xml'] }, 'width'],
Nothing is allowed by default, so indeed it would be empty. I am going to create a separate PR to remove the `allowedTag` from line `106`. I missed this.