Call store.ListIndexableRepos in (*repos).ListIndexable
sourcegraph/sourcegraph pull request #40476
Opened 2022-08-17 13:08 UTC by mrnugget

The docstring for `(*repos).ListIndexable` says:

> ListIndexable calls database.IndexableRepos.List, with tracing. It lists
> ALL indexable repos which could include private user added repos.
> In addition, it only lists cloned repositories.

But it didn't call `database.IndexableRepos`.

So either the docstring was wrong or the code. This PR here makes the
code do what the docstring says, but I'm not sure whether that's
correct - looking for feedback here.

(Data point that speaks for this change: the `s.cache.List` method
called right before also calls `store.ListIndexableRepos` in case the
cache is invalid)

## Test plan

- Existing tests

2022-08-17 13:11 UTC, eseliger approved these changes

2022-08-19 10:16 UTC, keegancsmith commented
@mrnugget Let me take a closer look to confirm the behaviour here. I'm on an offsite, mind if I take a look next week before merging?

2022-08-19 10:17 UTC, mrnugget commented
Yeah, sure. I kept it open so you can make sure this is correct.

2022-08-23 17:03 UTC, keegancsmith requested changes
Ok so this is indeed very confusing. `ListIndexableRepos` is meant to only be called on sourcegraph.com. It returns a subset of repos. ListMinimalRepos returns _all_ repos, which is the correct behaviour on non-sourcegraph.com instances.

This is a bit of a mess and confusing. Maybe a minimal change to improve lives here is to keep what you are doing, but make ListIndexableRepos call out to ListMinimalRepos if not on dotcom?

2022-08-24 09:13 UTC, mrnugget commented
> This is a bit of a mess and confusing. Maybe a minimal change to improve lives here is to keep what you are doing, but make ListIndexableRepos call out to ListMinimalRepos if not on dotcom?

I think a version of that is already happening, see these lines above: 

https://github.com/sourcegraph/sourcegraph/blob/13f5e5639282e5704cf496ef7e684b89d3b6e9c8/cmd/frontend/backend/repos.go#L202-L210

So with that in mind I think the better option might be to change the docstring instead, right? (And maybe rename `store.ListIndexableRepos` to `store.ListDotComIndexableRepos` to be safe?)

2022-08-24 13:31 UTC, mrnugget commented
Okay, I updated the PR to only change the docstring. This use of the `store.ListIndexableRepos` stumped me a bit and makes me wonder whether it _is_ only used on dot-com:

https://github.com/sourcegraph/sourcegraph/blob/beb37241664d3505004b2af21e1fdb16dd12c757/cmd/repo-updater/shared/main.go#L539-L547

I'm pretty sure we don't want the behaviour of that method (only return repos with >= 8 stars, ...) on customer instances, so I'm wondering whether that whole block should be in a `if sourcegraphDotcom() { }` condition.

2022-08-24 14:33 UTC, keegancsmith approved these changes

2022-08-24 14:33 UTC, merged