[SG-40293] Extract bootstrap style import @import 'bootstrap/scss/reboot.scss'
sourcegraph/sourcegraph pull request #40574
Opened 2022-08-18 15:59 UTC by gitstart-sourcegraph

## Description
This PR is about extracting `reboot.scss` from, bootstrap to `group styles`
## Problem statement
We depend on Bootstrap styles in our global styles a lot. But we don't plan to move forward with Bootstrap because we're working on our design system called Wildcard. To ease the transition to our styles and gain more control over visual changes, we want to move Bootstrap styles that we need into our codebase and eventually drop Bootstrap dependency.

## Implementation details
1. Remove bootstrap import https://github.com/import 'bootstrap/scss/reboot.scss
2. Copy style rules used in codebase from bootstrap stylesheet

## Success criteria
1. All highlighted imports have been removed
2. All CSS rules currently used from the imports are now available in style sheets

#Refs
1. [Sourcegraph issue](https://github.com/sourcegraph/sourcegraph/issues/40293).
2. [Gitstart Tickect](https://app.gitstart.com/clients/sourcegraph/tickets/SG-40293)
## Test plan
- `reboot.scss` rules are migrated from `bootstrap` to `global styles` and redundant rules are removed
- No UI diff relating to these changes exist

2022-08-29 12:31 UTC, valerybugakov reviewed
@gitstart-sourcegraph, leaving a comment here to ensure that we're aware of the unexpected diffs in Percy that we need to fix before the proper PR review

2022-08-29 12:31 UTC, valerybugakov commented on client/branded/src/global-styles/forms.scss
> +label {
If it's possible to visually separate imported `reboot.css` styles for our custom styles, let's leave comments at the beginning and end of such sections. E.g,.

```scss
// ------------------- Start reboot.scss styles imported from Bootstrap ----------------------
...reboot scss
// ------------------- End reboot.scss styles imported from Bootstrap ----------------------

...our scss

2022-08-31 07:40 UTC, gitstart-sourcegraph commented on client/branded/src/global-styles/base.scss
> -
Removed this piece in favour of selector in `reboot.scss`

2022-08-31 07:40 UTC, gitstart-sourcegraph commented on client/web/src/org/members/OrgPendingInvites.tsx
> -                                    as="a"
Since there was no `to/href` prop binding here for ancor element, it's safe to remove `as="a"` and resolve UI diff on hover in stylesheet.

2022-08-31 07:40 UTC, gitstart-sourcegraph commented on client/branded/src/global-styles/reboot.scss
> +}
Kept this despite having migrated `a` in favour of `Link`, since `Link` components still uses this global selector style.

2022-09-01 05:05 UTC, valerybugakov commented on client/wildcard/src/components/Button/story/Button.story.tsx
>          <Button
Let's convert this component to `ButtonLink` then

2022-09-01 05:05 UTC, valerybugakov commented on client/wildcard/src/components/Button/Button.test.tsx
> +        const { asFragment } = renderWithBrandedContext(<Button as="div">I am a div</Button>)
Could you share the context behind this change?

2022-09-01 05:05 UTC, valerybugakov commented on client/web/src/org/members/OrgPendingInvites.tsx
> -                                    as="a"
It seems after removing `as` props from the `InviteMemberModalHandler` component, we can remove it from the internal implementation of the component where we have `<Button {...rest} onClick={onInviteClick} as={as as any} size="sm">`

2022-09-01 05:39 UTC, gitstart-sourcegraph commented on client/wildcard/src/components/Button/Button.test.tsx
> +        const { asFragment } = renderWithBrandedContext(<Button as="div">I am a div</Button>)
This change was made as a result of migrating away from usage of `as="a"` on `Button` on codebase.

2022-09-02 05:12 UTC, valerybugakov requested changes

2022-09-02 05:12 UTC, valerybugakov commented on client/branded/src/global-styles/variables.scss
> +    --font-weight-base: 400;
Let's move CSS variables from the `client/branded/src/global-styles/utilities.scss` here to have all `--font-weight-*` variables in one place.

2022-09-02 05:12 UTC, valerybugakov commented on client/web/src/org/members/OrgPendingInvites.tsx
> -                                    as="a"
@gitstart-sourcegraph, based on our observation that `as="a"` is required for server-side navigation, we probably should keep this `as` prop here and use `AnchorLink` here. Did you test it locally?

2022-09-02 05:12 UTC, valerybugakov commented on client/web/src/org/members/OrgMembersListPage.tsx
> -                                    as="a"
@gitstart-sourcegraph, based on our observation that `as="a"` is required for server-side navigation, we probably should keep this `as` prop here and use `AnchorLink` here. Did you test it locally?

2022-09-02 05:48 UTC, raph941 commented on client/web/src/org/members/OrgMembersListPage.tsx
> -                                    as="a"
Ah yea, so for this case there was no `href` or `to` prop binded to this element, i.e no navigation takes place on click (renders an anchor without href). It basically just toggles the modal visibility using `onClick` event handler.

<img width="624" alt="Screenshot 2022-09-02 at 6 43 24 AM" src="https://user-images.githubusercontent.com/45232708/188066921-8af2311f-abdb-4c74-ab09-092a9e79cfc2.png">

2022-09-02 07:39 UTC, gitstart-sourcegraph commented on client/web/src/org/members/OrgMembersListPage.tsx
> -                                    as="a"
Yes I tested this locally. For this case there was no `href` or `to` prop binded to this element, i.e no navigation takes place on click. It basically just toggles the modal visibility using `onClick` event handler.


https://user-images.githubusercontent.com/89894075/188082845-02465692-c7e0-4b7d-9029-a9114ac261fa.mov

2022-09-05 10:43 UTC, valerybugakov approved these changes

2022-09-05 11:18 UTC, merged