Prevent stopping repo-sync if querying Bitbucket projectKeys returns "fatal" error
sourcegraph/sourcegraph pull request #40582
Opened 2022-08-18 19:57 UTC by varsanojidan

Fixes #40449 
Currently, when looping through the [projectKeys](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/bitbucketserver.go?L281) for a BitBucket host, if we encounter a "fatal" error (i.e. unauthorized, forbidden etc...) we [stop the repo sync](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/syncer.go?L606) completely. This causes repos to become stale and excluded repos to still show up. Because this is an error related to on projectKey out of several, we shouldn't assume that if we fail on the one projectKey we will fail on all of them. Ideally there wouldn't be any unauthorized projectKeys in the list, but in the case that someone makes a mistake and adds a bad projectKey to the list, or permissions on the projectKey were changed, we don't want to have repo-syncing permanently turned off.

## Test plan
Tested locally using a bitbucket ACC that didn't have access to certain projects, added a sourced repo to excluded, repo was excluded now where it was not excluded before this change. Existing tests pass.

Existing tests pass

2022-08-19 07:01 UTC, indradhanush requested changes
This looks like a great PR to use `errors.Warning` that was introduced recently. https://github.com/sourcegraph/sourcegraph/blob/main/lib/errors/warning.go#L30

2022-08-19 07:07 UTC, varsanojidan commented
> This looks like a great PR to use `errors.Warning` that was introduced recently. https://github.com/sourcegraph/sourcegraph/blob/main/lib/errors/warning.go#L30

That a great idea, thanks for pointing it out!

2022-08-19 08:12 UTC, ryanslade commented on internal/repos/sources.go
> +	// NonFatalError identifies that if the error is considered fatal (for example unauthorized) , it should not stop the sync
```suggestion
	// NonFatalError identifies that if the error is considered fatal (for example unauthorized), it should not stop the sync
```

2022-08-19 08:15 UTC, ryanslade commented on internal/repos/syncer.go
> +			if !res.NonFatalError && fatal(err) {
I think if we do what Indra suggested and use the warning error type then the logic can be moved into the `fatal` function.

2022-08-19 18:47 UTC, varsanojidan commented
@indradhanush addressed the review comments

2022-08-20 09:49 UTC, indradhanush approved these changes
Looks good. Left some suggestions. Approve to unblock.

2022-08-20 09:49 UTC, indradhanush commented on internal/repos/bitbucketserver.go
> +				// so set this error as a warning so that the sync continues.
```suggestion
				// Getting a "fatal" error for a single project key is not a strong 
				// enough reason to stop syncing, instead wrap this error as a warning
				// so that the sync can continue.
```

2022-08-20 09:49 UTC, indradhanush commented on internal/repos/syncer.go
> +		if err != nil && errors.As(err, &ref) {
Nit: The check for `err != nil` is not needed. `errors.As` will take care of that already. 

I added this here: https://github.com/sourcegraph/sourcegraph/pull/40631.

2022-08-20 09:49 UTC, indradhanush commented on internal/repos/syncer.go
>  		return errcode.IsUnauthorized(err) ||
Nit: new line here should improve readability. 😀 
```suggestion

		return errcode.IsUnauthorized(err) ||
```

2022-08-22 08:24 UTC, ryanslade commented on internal/repos/syncer.go
> +		var ref errors.Warning
I wonder if it's worth adding an `errors.IsWarning` method to make this easier?

2022-08-22 08:33 UTC, ryanslade commented on internal/repos/syncer.go
> +		var ref errors.Warning
Proposed here:
https://github.com/sourcegraph/sourcegraph/pull/40656

2022-08-22 16:54 UTC, merged

2022-08-23 07:31 UTC, ryanslade commented on internal/repos/syncer.go
> +		if errors.IsWarning(err) && !errcode.IsAccountSuspended(err) {
Why are we checking accountSuspended here and again lower down?

2022-08-23 16:01 UTC, indradhanush commented on internal/repos/syncer.go
> +		if errors.IsWarning(err) && !errcode.IsAccountSuspended(err) {
My interpretation is that we want to avoid not reporting a fatal error for suspended accounts here. The check below does not have the `!` for the accountSuspended check.

2022-09-07 16:32 UTC, varsanojidan commented on internal/repos/syncer.go
> +		if errors.IsWarning(err) && !errcode.IsAccountSuspended(err) {
I realized I forgot to reply to this but yeah that's why