batches: prevent fighting between polling and show more button in workspaces connection
sourcegraph/sourcegraph pull request #40717
Opened 2022-08-23 07:33 UTC by courier-new

Fixes the problem observed in the UI when loading additional workspaces from the execution list with the "show more" button where sometimes no additional workspaces would appear. This is due to the response with the extra page of paginated data "fighting" with the response from the regular polling request for the already-loaded pages.

So, shouldn't Apollo Client be smart enough to handle that? Turns out there's a couple things going on here that make the situation non-ideal:

1. **The fact that we're polling paginated data in the first place**
    - Apollo has historically outright stated this is unsupported and `pollInterval` is not to be used in conjunction with `fetchMore` [[1](https://github.com/apollographql/apollo-client/issues/1121)] [[2](https://github.com/apollographql/apollo-client/issues/1087)], and what we've implemented is a big fat workaround.
2. **We didn't have an `id` to identify a `BatchSpecWorkspaceResolution` by**
    - When we would query and write to this field from other screens from the execution UI, then, Apollo would default to completely overwriting any previous workspace we got, causing confusion and breaking certain cache writes.
3. **Our workspace connection data can only be queried on a `BatchSpec` node**
    - One of many deep architectural choices of our GraphQL setup, one can only query such things as workspaces by first querying their parent batch spec `node` type and then providing a nested query to its workspaces. This makes custom field policies, such as those which are [typically recommended](https://www.apollographql.com/docs/react/pagination/core-api/#merging-paginated-results) for properly merging paginated data in Apollo Client ~impossible~ really hard to get right. 😅 I spent a while trying, but a) it's really hard to get insight as to what Apollo Client is _actually doing_ to validate if your changes are having any impact, and b) there are not many places with documentation or examples for this configuration outside of very basic examples.

So, how do we get around this?

1. Don't *actually* use `pollInterval` and `fetchMore` at the same time.
    - We now query the workspaces' place in queue, state, and diff stat separately from the "normal connection" query; the former, dynamic data will be polled regularly with a manual polling interval, and the latter, mostly non-changing data will only be requested once per page load.
    - As Apollo is still smart enough to merge these results in the cache, we can then pull the combined data from both out for the workspaces list UI.
2. Expose the workspace resolution job id as a field on the `BatchSpecWorkspaceResolution`
3. 🤷‍♀️ It's not in scope of this singular issue to solve this problem right now. But when we're the only product team actively trying to poll paginated data, I doubt it's really a priority for anyone else, either.

### Demo video:

https://user-images.githubusercontent.com/8942601/186096225-5eaa7e39-b175-43d0-aa26-61f1894dfb51.mov

### Problems

The one (big) annoyance with this technique is that the Apollo Client cache doesn't seem to work the same way in the Storybook stories environment, so our workspace lists are in stories are... empty. 🙃 I couldn't seem to find _any_ documentation about somehow configuring the mock provider with initial test data pre-loaded in the cache, so the only way I could see that we get around this would be if we manually wrote the mock data to the appropriate cache keys within each storybook story, which would be soooo tedious and brittle. 😭

Of course, we could have ditched Apollo Client and reverted to the old `requestGraphQL` request style or something else for this query, but this didn't feel like the right call because:
- It's promoting a fractured system and really just delays the work for us to make this work in Apollo later on when we completely migrate to Apollo.
- Our polling practices are bad for other reasons (for example, the fact that we poll tons of fields that aren't ever going to change, and the fact that we poll forever even if we can be confident that the thing we were polling for stopped changing) that would be a lot harder to solve without a cache.

### Follow Up

It's probably worth porting this solution to the changesets list on the batch change detail page, as well. This problem also impacts that list, but it happens a _lot_ less frequently, it seems, so that's a lower priority. I'll write up an issue for this.

I'm also going to be writing up a more general issue about improving our polling strategies to more effectively take advantage of the cache. 

## Test plan

Extensive manual testing.

2022-08-23 07:34 UTC, courier-new commented on client/web/src/enterprise/batches/batch-spec/execute/ExecutionStatsBar.story.tsx
> +            <div className={styles.statsBar}>
This isn't related, I just noticed the story styling looked funky when checking over stories for missing mocked request data.

2022-08-23 07:35 UTC, courier-new commented on client/web/src/enterprise/batches/batch-spec/execute/backend.ts
> +            first: 50,
Now that we aren't polling for the full workspace every 2.5 seconds, increasing the size of a page of workspaces is a lot cheaper and felt worth doing. 🙂

2022-08-23 07:36 UTC, courier-new commented on client/web/src/enterprise/batches/batch-spec/execute/workspaces/Workspaces.story.tsx
> -import { DecoratorFn, Meta, Story } from '@storybook/react'
I decided to just delete this story because it's components are covered by multiple other stories, and at this point it's just a search + filters box with an empty list underneath it because of the problem I mentioned in the PR description. 😭

2022-08-23 20:41 UTC, Piszmog approved these changes

2022-08-24 13:21 UTC, eseliger requested changes
I have very mixed feelings about this.

First, thanks A LOT for digging so deep here and figuring out that we're holding apollo wrong (according to their definition of wrong, I still think it's okay 😬) and finding a solution that can work around it!

Some thoughts:
- The fact that we need to do a +332loc diff just to get live-like data to work on a single list is completely nuts to me. When we still used rxjs, people said it's "too complex" and there it required a little bit of rxjs understanding and then ~10-15loc added. Also, whenever we add a new field that could change over time, we must now remember to add it to the second, polling query (but also get benefits from this, outlined further down).
- For batch changes, 90% of the UIs are meant to be a live-like representation of the state to keep trust, so we would have to port this +332loc diff to all our lists. Beyond that even, we (or someone at least) will need to port it to the lists outside of batch changes eventually so that the executors page, code intel indexing pages etc also don't suffer from this bug.
  - I would even go so far and say that apollo cache doesn't matter for us in 95% of cases since to build trust we don't want to rely on stale, cached results in the UI anyways. I don't trust the live execution view that it's correct when if flashes outdated state briefly on page visit, tbh.
  - Surely it's possible to generalize this logic enough so that we could reuse it without adding THAT much overhead, but the points below will still stand.
- This seems like a LOT of overhead and a very steep learning curve, too which I fear will prevent people from making more of Sourcegraph live-like.
- Why does apollo dictate where we need to add IDs, I really dislike that.
- I don't think it's great to fetch 10s of thousands of state information upfront, because:
  - The query to determine queue rank is relatively slow and has O(n) cost, which is absolutely acceptable for n=20 or even n=50, and is also a cost we'll swallow when the user _actually_ needs all the jobs including queue rank, but seems like unnecessary DB strain for lists of which we usually show way less at a given point in time 
  - The performance of this query determines the refresh rate of the state in the UI and for a 10k workspace execution that is now 500x slower, even at 1ms resolution time, it now means the minimum refresh interval becomes 500ms, and 1ms is far too optimistic
  - The number of bytes transmitted for this is also 500x higher, which is likely limiting on slower networks. 
- Blocker: This doesn't work with filters. Ie. when I filter by `state = "processing"`, it wouldn't be able to eliminate that row from the list and grab a new one from the server. This is a pretty crucial use-case to me since I often observe currently running jobs.

What I do like though is that we can control which fields we need to re-fetch and which we don't for live updates. This can be very helpful in reducing load.

Maybe we can address the issue with fetching 10s of thousands of records by back-feeding the list of visible IDs to the refresh polling thing? 
- For a first fetch of a new list, the list method itself fetches all the state params
- We get the new 50 additional IDs, add those to the refetcher state
- The next time the refetcher runs, it also fetches data for these, now updating 50 more records, but not 10s of thousands. Maybe I'm missing something obvious here though...

I was gonna approve this to unblock finally getting _something_ working here, pending some tests on a large execution on k8s post-merge re: performance, but now that I discovered that last bullet point about filtering, I think we need to revisit this yet another time, sigh. Sorry :( 
How bad would reverting to rxjs be? It'd be likely a 1d job and it works reasonably well on other lists. It's a little hard to read, correct, but it works and as outlined above, I don't think we care about the caching properties of apollo too much.

2023-01-31 00:12 UTC, closed without merging