WIP CodeMirror: make Cmd-f trigger search globally
sourcegraph/sourcegraph pull request #40792
Opened 2022-08-24 14:05 UTC by oleggromov

## Test plan

2022-08-25 12:11 UTC, oleggromov commented
@sourcegraph/frontend-platform I tagged you because I touched the `Layout.tsx` and you may want to be aware of this change.

2022-08-25 12:17 UTC, olafurpg requested changes

2022-08-25 12:17 UTC, olafurpg commented on client/web/src/Layout.tsx
> +            <CodeMirrorContext.Provider value={{ setCodeMirrorBlobEditor, triggerSearchIfAvailable }}>
Just curious: was it necessary to wrap all these components under `CodeMirrorContext.Provider` or would it have been possible to only wrap the components that use `setCodeMirrorBlobEditor` and `triggerSearchIfAvailable`?

2022-08-25 12:17 UTC, olafurpg commented on client/search-ui/src/input/CodeMirrorQueryInput.tsx
> +                    onTriggerSearch()
This case seems to be triggering with the old blob view, preventing Cmd+F to work. We should only return `true` if the new blob view is visible

2022-08-25 12:41 UTC, oleggromov commented on client/web/src/Layout.tsx
> +            <CodeMirrorContext.Provider value={{ setCodeMirrorBlobEditor, triggerSearchIfAvailable }}>
Strictly speaking it isn't necessary but I much prefer having a context around it (usual thing in React apps, we've got multiple contexts ourselves) than passing props down through tens of different components (which we also do to be fair).

2022-08-25 12:42 UTC, oleggromov commented on client/search-ui/src/input/CodeMirrorQueryInput.tsx
> +                    onTriggerSearch()
Great catch, thank you! Will fix now!

2022-08-26 04:36 UTC, valerybugakov requested changes
The bundlesize check [shows](https://github.com/sourcegraph/sourcegraph/pull/40792/checks?check_run_id=8016350532) a massive increase in the main chunk bundle. Based on the functionality added in this PR, it should not be happening. It might be related to the new import from the `web` package into the `search-ui` package. 

The best way to investigate this issue would be using the `analyze-bundle` NPM script defined in the `web` package. It uses [the statoscope](https://github.com/statoscope/statoscope) Webpack plugin under the hood, which should help find the root cause.

2022-08-26 04:36 UTC, valerybugakov commented on client/search-ui/src/input/LazyMonacoQueryInput.tsx
> +import { useCodeMirrorContext } from '@sourcegraph/web/src/repo'
The `search-ui` package was extracted from the web package to be able to share logic between the VSCode extension and the web application. We should not have imports from the `@sourcegraph/web` package here. 

The functionality required for the component should be moved to the `search-ui` package if it's not specific to the web application, or it should be injected into components here via props or React context. Let me know if it doesn't make sense.

2022-08-29 13:37 UTC, oleggromov commented on client/search-ui/src/input/LazyMonacoQueryInput.tsx
> +import { useCodeMirrorContext } from '@sourcegraph/web/src/repo'
Thank you, this makes sense. I've turned to passing the callback through props as you recommended.

2022-08-30 05:53 UTC, valerybugakov reviewed
@oleggromov, did you have a chance to look into bundlesize increase of the `main` chunk? We need to understand where it's coming from and either prevent it from happening or increase the main chunk limit (a less desirable outcome).

2022-08-30 12:37 UTC, oleggromov commented
> @oleggromov, did you have a chance to look into bundlesize increase of the `main` chunk? We need to understand where it's coming from and either prevent it from happening or increase the main chunk limit (a less desirable outcome).

I am trying to figure this out now. The import from `web/` is removed and I am not sure where it comes from.
Will post an update soon.

2022-08-30 14:38 UTC, oleggromov commented
I think I've found out what the issue is:

1. To make `Cmd+F` trigger CodeMirror search from _everywhere_ in the app, I import `useCodeMirrorBlobSearch` into `Layout`
2. `useCodeMirrorBlobSearch` imports `openSearchPanel` from `@codemirror/search`, which imports the [entire CodeMirror](https://github.com/codemirror/search/blob/main/package.json#L29-L30) as it seems
3. This makes the entire CodeMirror go into the main chunk, which increases the bundle size

Not sure I see an easy way around this right now, especially without changing the architecture of key handling.

One (kinda crazy) idea is to disconnect `Cmd+F` handling (`Shortcut` component basically) and CodeMirror response to it (`openSearchCallback` invocation) but this will require a big refactoring and a non-obvious architecture.

@sourcegraph/frontend-platform maybe you have other ideas?

**A more radical solution** would be to say we're definitely getting rid of Monaco, which should reduce bundle size, and just proceed with shipping it as is.

But for this, I need @olafurpg and @macraig input at least.

2022-08-30 18:43 UTC, macraig commented
@oleggromov what would the drawbacks and/or consequences of getting rid of Monaco be?

2022-08-30 21:31 UTC, oleggromov commented
> @oleggromov what would the drawbacks and/or consequences of getting rid of Monaco be?

I am guessing it is gonna happen anyways in the future as we migrate to CodeMirror. But I am not sure what the current plan is.

2022-08-31 06:54 UTC, olafurpg commented
The timeline for Monaco deprecation might be long since Monaco is used in various places (several admin UIs, and batch changes). I don't think we can realistically remove it from the app within the short period I'd like to get Cmd+F working globally with the new blob view. I'll take over this issue and investigate alternative solutions once the extension migration is done. Maybe Felix Kling has some creative ideas once he returns next week. In the meantime, I recommend we close this PR for now and leave the Cmd+F issue open.

2022-08-31 11:37 UTC, oleggromov commented
This makes sense to me!
Thank you @olafurpg

2022-08-31 11:37 UTC, closed without merging