Vk/integrate aggregation api
sourcegraph/sourcegraph pull request #40803
Opened 2022-08-24 16:00 UTC by vovakulikov

Closes https://github.com/sourcegraph/sourcegraph/issues/39956
Closes https://github.com/sourcegraph/sourcegraph/issues/40766

## Backround
This PR connects GQL Aggregation API with aggregation UI on the frontend. I recorded a [loom](https://www.loom.com/share/8dc8de38cbc54d87bf57f180d7bd9e62) in order to describe changes that this PR makes and the current state of aggregation project. 

## Todo 
- [x] Connect GQL API to the aggregation UI 
- [x] Adjust UI based on the lates [Figma designs](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=1913%3A35438)
- [ ] Add Info icon UI
- [ ] Fix storybook stories
- [ ] Fix existing integration tests
- [ ] Add new integration tests for aggregation data fetching
  
## Test plan
- Make sure that FE handler all possible states in aggregation UI appropriate (as it descirbed in Figma designs)
- Make sure that repositories, file name and author aggregation types work correctly 
- Test that side panel and expanded (the full mode) view don't have any visual regressions

2022-08-24 22:01 UTC, felixfbecker commented
> Adjust UI based on the lates [Figma designs](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=1913%3A35438)
> Add Info icon UI

These feel like things that are not related directly to the title/purpose of this PR, so I would suggest not blocking on them to merge. Of course (1) is already done so if that's the case we don't have to extract it out of the PR with extra labor.

2022-08-24 22:01 UTC, unclejustin requested changes
I couldn't finish the review because I can't get it to compile 😢 but I do have some comments so far.

2022-08-25 09:13 UTC, vovakulikov commented on client/search-ui/src/results/aggregation/hooks.ts
> +type SerializedAggregationMode = `${SearchAggregationMode}` | ''
@unclejustin this expression gives us a union type of values of the current enum type. So in this case  `${SearchAggregationMode}` gives us 'REPO' | 'PATH' | 'AUTHOR' | 'CAPTURE_GROUP' type this allows us to be more type safety in parse function. If some of enum value will be changed we still catch this with this type. (we could use just string type here but this doesn't give use the same type safety as enum and string literal types) 

But I didn't know that SearchAggregationMode type is also does the same when we compare it with string values. But apparently this is what it does. I will remove string literals here and will use plain enum values, thanks!

2022-08-25 09:25 UTC, vovakulikov commented on client/search-ui/src/results/sidebar/SearchAggregations.tsx
> +    const { data, error, loading } = useSearchAggregationData({ query, patternType, aggregationMode })
Nice call, I will change return type of this hook and will use union types there in order to suppress all impossible states.

2022-08-25 09:27 UTC, vovakulikov commented on client/wildcard/src/components/Charts/types.ts
> +    onDatumLinkClick?: (event: React.MouseEvent, datum: Datum) => void
I updated the Pie chart handler.

2022-08-25 09:31 UTC, vovakulikov commented on client/search-ui/src/results/aggregation/SearchAggregationResult.tsx
> +                    availability={data?.searchQueryAggregate?.modeAvailability}
@unclejustin I disagree with this line
>So we can assume that data will be available

We want to render aggregation mode buttons always (even if we don't have data for them). So data here might be undefined if we're still loading data but already rendered the buttons.

2022-08-25 09:39 UTC, vovakulikov commented on client/search-ui/src/results/aggregation/hooks.ts
> +}
I updated comments here, I hope this will make more sense. Let me know if you still want to discuss this.

2022-08-25 09:41 UTC, vovakulikov commented on client/search-ui/src/results/aggregation/hooks.ts
> +    limit?: number
I don't have a strong preferences about it. I made it required and passed default values in both consumers.

2022-08-25 13:42 UTC, unclejustin commented on client/search-ui/src/results/aggregation/SearchAggregationResult.tsx
> +                    availability={data?.searchQueryAggregate?.modeAvailability}
That makes sense thanks for the clarification!

2022-08-25 14:00 UTC, unclejustin commented on client/search-ui/src/results/aggregation/AggregationChartCard.tsx
> +export function AggregationChartCard(props: AggregationChartCardProps): ReactElement {
I think we can simplify this a bit more. Out of scope for this PR, I've opened [this issue](https://github.com/sourcegraph/sourcegraph/issues/40849) to track it.

2022-08-25 14:02 UTC, unclejustin approved these changes

2022-08-25 14:03 UTC, merged