cmd/gitserver/server: Make var tlsExternal into a func
sourcegraph/sourcegraph pull request #40927
Opened 2022-08-26 14:03 UTC by indradhanush

Making this into a function allows us to test the code to guarantee
that multiple certificates configured in the config are written into
the SSLCAInfo file correctly.

Also we don't need the type hint anymore since the type is now inferred
from the return type of the function itself. Which makes the code easier
to read.

Change inspiration out of looking into https://github.com/sourcegraph/customer/issues/1136 and https://github.com/sourcegraph/sourcegraph/issues/38128 respectively this week.

## Test plan

Added a test case.

2022-08-26 14:32 UTC, keegancsmith requested changes

2022-08-26 14:32 UTC, keegancsmith commented on cmd/gitserver/server/serverutil.go
> +	tls := conf.Cached(getTlsExternal)()
this effectively creates a new cache (and background goroutine that never dies) on every call to runWith. Unfortunetly it doesn't work this way, which is why we use the var.

2022-08-26 14:33 UTC, keegancsmith commented
You can extract the function which takes the `conf` and returns the cached state and just test that directly. But you need to call conf.Cached once per process.

2022-08-29 09:44 UTC, indradhanush commented on cmd/gitserver/server/serverutil.go
> +	tls := conf.Cached(getTlsExternal)()
TIL. Thank you for pointing this out. Saved myself from future pain. 

Also added note to conf.Cached about this.

2022-08-29 10:57 UTC, keegancsmith approved these changes

2022-08-29 10:57 UTC, keegancsmith commented on cmd/gitserver/server/serverutil.go
> +func getTlsExternal() *tlsConfig {
nit: call this function something like `getTLSExternalDoNotCall` to avoid accidental calling (easier to realise it is a mistake)

2022-08-29 11:24 UTC, indradhanush commented on cmd/gitserver/server/serverutil.go
> +func getTlsExternal() *tlsConfig {
Nice idea. Fixed. 👌🏽

2022-08-29 11:36 UTC, merged

2022-09-05 11:28 UTC, ryanslade commented on cmd/gitserver/server/serverutil.go
> +// so that we can test it.
Some typos, should be:

```
// getTlsExternal exists as a function instead of being passed directly to conf.Cached below
// so that we can test it.
```

2022-09-05 11:28 UTC, ryanslade commented on cmd/gitserver/server/serverutil.go
> +// tlsExternal will create a new cache for this gitserer process and store the certificates set in
Typo in `gitserer`

2022-09-05 11:29 UTC, ryanslade commented on cmd/gitserver/server/serverutil.go
> +// This creates a long lived
Looks like an incomplete sentence