Aggregation UI: Add aggregation zero state UI
sourcegraph/sourcegraph pull request #40959
Opened 2022-08-27 09:42 UTC by vovakulikov

Based on https://github.com/sourcegraph/sourcegraph/pull/40943
Part of https://github.com/sourcegraph/sourcegraph/issues/40766

[Figma designs](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=246%3A11)

## Background
In this PR we added zero state (bars-like) background for search unavailable error. See tables below for different themes and UI modes

| Aggregation UI | Theme  | Standard UI | Simple UI |
| ------------- | ------------- | ------------- | ------------- |
| Sidebar UI  | Light theme |  <img width="1158" alt="Screenshot 2022-08-27 at 12 21 43" src="https://user-images.githubusercontent.com/18492575/187024293-ecd772ae-a401-49c2-89b1-7e3404066309.png">| <img width="1158" alt="Screenshot 2022-08-27 at 12 21 38" src="https://user-images.githubusercontent.com/18492575/187024313-398987c3-2d7b-4872-b2ac-9e363bd4b1e8.png"> |
| Sidebar UI | Dark theme  | <img width="1158" alt="Screenshot 2022-08-27 at 12 21 48" src="https://user-images.githubusercontent.com/18492575/187024445-32fbbf19-9884-40ac-a5eb-627ee7149948.png"> | <img width="1158" alt="Screenshot 2022-08-27 at 12 21 34" src="https://user-images.githubusercontent.com/18492575/187024396-a00a2d99-2ac2-466b-8914-ed06661d0c24.png"> |
| Full UI | Light theme | <img width="1158" alt="Screenshot 2022-08-27 at 12 20 09" src="https://user-images.githubusercontent.com/18492575/187024525-66e1d67d-c957-40ff-bf59-fb415bbfc807.png"> | <img width="1158" alt="Screenshot 2022-08-27 at 12 20 15" src="https://user-images.githubusercontent.com/18492575/187024668-1eb929f0-772a-4458-a5cc-6b97cb89b637.png"> |
| Full UI | Dark theme | <img width="1158" alt="Screenshot 2022-08-27 at 12 20 03" src="https://user-images.githubusercontent.com/18492575/187024704-08df2e4f-3116-46d5-a0ec-d8d275d463a5.png"> | <img width="1158" alt="Screenshot 2022-08-27 at 12 20 21" src="https://user-images.githubusercontent.com/18492575/187024713-55633c8c-da0a-4b36-947c-c5dc2d1b15f0.png"> |

 

## Test plan

2022-08-29 15:50 UTC, unclejustin approved these changes

2022-08-29 15:50 UTC, unclejustin commented on client/search-ui/src/results/aggregation/AggregationChartCard.tsx
> +            </DataLayoutContainer>
Not for this PR, but I still think this should be handled in the parent component, and these loading/error states should be separate components.

2022-08-29 15:50 UTC, unclejustin commented on client/search-ui/src/results/aggregation/AggregationChartCard.module.scss
> +    background: var(--body-bg);
Not for this PR, but I've started pushing back on using `rem` for anything other than font-size. I think it's a mistake. We see a great example here with `top` being actual pixels but `padding` being rems. It doesn't make sense to me. Padding should not grow if I just want the text larger. And If I use cmd +/- to zoom, it will already increase the padding anyway.

2022-08-29 18:21 UTC, AlicjaSuska requested changes
Thank you for making those changes and being proactive about the colors @vovakulikov 

Here are some thoughts from me:

- [x] I think we should disable grouping buttons when the aggregation is loading so it's not possible to select another grouping that is not available. Currently, all buttons become active. This would prevent us from having the error state and message from examples in the first place. I hope it's doable
- [ ] In the expanded view, could we limit the text width to 500px? Now, it's very wide
- [ ] I also created a version of the placeholder [chart for the expanded view](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM/Aggregation-insights%3A-display-%22grouped%22-insights-for-existing-searches-%2339126-%5Bready-for-dev%5D?node-id=2559%3A29398) - it's more proportional. @vovakulikov could you please change this asset? Thank you

Regarding the colors of the bars:

- [ ] Simple UI - expanded view - dark: $gray-09 - light: $gray-03
- [ ] Simple UI - panel - dark: $gray-11 - light: $gray-02 (in the current implementation: dark looks fine, light is a little too light IMO)
- [ ] Old UI - panel - dark: $gray-09 - light: $gray-03
- [ ] Old UI - expanded view - the same values as for the panel view

2022-08-29 19:06 UTC, vovakulikov commented on client/search-ui/src/results/aggregation/AggregationChartCard.tsx
> +            </DataLayoutContainer>
@unclejustin In this case we have to handle all this branches UI logic inside of consumer too. And this will make both consumers (full UI mode and sidebar UI) complex

I usually like ideas about compositions, this gives use flexibility and makes UI parts more explicit and straightforward. 

In this case I couldn't come up with good API to use power of UI composition here. But maybe I'm looking at this component too long and It really should be better with low level UI block. 

@unclejustin If you have time please share your thoughts about usage of these low level separate components in consumers

2022-08-29 19:08 UTC, vovakulikov commented on client/search-ui/src/results/aggregation/AggregationChartCard.module.scss
> +    background: var(--body-bg);
@unclejustin Actually I think even top shoud be rem according to our CSS style lint rules. I think search-ui package wasn't properly connected to our linting system when it was created. 

But I agree with your about rem/px thought for padding. I don't want to increase incosistensy though but I would be happy to migrate all none font related units to pixels some day.

2022-08-30 10:47 UTC, vovakulikov commented
@AlicjaSuska I changed colors as you suggested, IMO gray-02 looks to light in the light theme and it makes error text hard to read. I think we can sacrifice contrast of these gray bars in order to improve readeability of error message. Since gray bars is completely visual and decorative element of UI it should make sense. 

| Original colors  | Gray 02 | Gray 02 with opacity 0.6 |
| --------------- | -------- |  ------------------------ |
| <img width="238" alt="Screenshot 2022-08-30 at 13 11 35" src="https://user-images.githubusercontent.com/18492575/187417149-cae83e31-2009-49e9-b5bb-65e2f72cc3fd.png">  | <img width="237" alt="Screenshot 2022-08-30 at 13 11 58" src="https://user-images.githubusercontent.com/18492575/187417197-03c0b0b7-dfb7-42fe-900f-4524ee235942.png">  | <img width="239" alt="Screenshot 2022-08-30 at 13 36 05" src="https://user-images.githubusercontent.com/18492575/187417223-4b8c794d-65b4-4f32-b02d-2c7ace4c3cab.png"> |

2022-08-30 12:15 UTC, AlicjaSuska commented
Thank you @vovakulikov - colors render here differently than in Figma. Let's keep your suggested color for the bars. Thank you

2022-08-30 18:19 UTC, felixfbecker commented
>  I think we should disable grouping buttons when the aggregation is loading so it's not possible to select another grouping that is not available. Currently, all buttons become active. This would prevent us from having the error state and message from examples in the first place. I hope it's doable

@AlicjaSuska I don't think that's a good idea. In the state where the user overrides the timeout, it gets increased to 60s. That means the user needs to wait up to a minute just to be able to choose a different attribute (that then may load again up to a minute), because it will disable the buttons. The user may have selected an attribute mistakenly or just wanted to play around with it, and different attributes can have different times to load. I would rather still allow them to select it while loading and show an error. I would generally consider disabling UI while loading an anti pattern if it can be avoided. UI should always make it easy to correct mistakes (be "forgiving").

2022-08-30 18:24 UTC, felixfbecker commented
@vovakulikov on this PR, the chart background is a lot taller than in the design. Will that be addressed as part of the "Chart is much taller than in design" item in https://github.com/sourcegraph/sourcegraph/issues/40766 ?

2022-08-30 18:27 UTC, vovakulikov commented
@felixfbecker yes it will be discussed and addressed in the https://github.com/sourcegraph/sourcegraph/issues/40766 (from personal perspective we shouldn't make it smaller in all error/loading/data states, because in data mode when we have chart it will make chart smaller and it will be hard to aim bars, in loading and error state changing height of this block will introduce layout shift that I want to avoid there) cc @AlicjaSuska

2022-08-30 18:31 UTC, felixfbecker commented
> (from personal perspective we shouldn't make it smaller in all error/loading/data states, because in data mode when we have chart it will make chart smaller and it will be hard to aim bars, in loading and error state changing height of this block will introduce layout shift that I want to avoid there)

Not sure if I understand you correctly here but I assume what you mean is the heights between all states should be consistent, which I agree with.

2022-08-30 18:32 UTC, vovakulikov commented
>what you mean is the heights between all states should be consistent, which I agree with.

@felixfbecker This is exactly what I mean

2022-08-31 08:50 UTC, AlicjaSuska approved these changes

2022-08-31 08:52 UTC, AlicjaSuska commented
Just a final note here: heights shouldn't differ but we should add some extra top-bottom padding to the section for the error state to match the designs (@vovakulikov I mentioned it yesterday in our DMs)

2022-08-31 09:10 UTC, merged