Draft a GHA to check PRs on 4.0
sourcegraph/sourcegraph pull request #40984
Opened 2022-08-29 13:06 UTC by jhchabran

## Test plan

2022-08-29 13:58 UTC, jhchabran commented
cc @keegancsmith as this was your idea 😊

2022-08-29 14:02 UTC, mrnugget commented
> Run with dday set to 2022-09-09 and no label:

The last entry in your list -- shouldn't this be a different date?

2022-08-29 14:03 UTC, mrnugget requested changes
Thank you for doing this! I request changes because I think we should make clear with the label name that this is only an "ack" and not "please put this in the release", since authors of unrelated changes will also have to use it for their PRs.

Can we also make the "failed" message a bit more explanatory?

2022-08-29 14:03 UTC, mrnugget commented on .github/workflows/fourpointoh-protector.yml
> +name: Release 4.0 protection
```suggestion
name: Sourcegraph 4.0 code freeze
```

2022-08-29 14:03 UTC, mrnugget commented on .github/workflows/fourpointoh-protector.yml
> +          has_label="${{contains(github.event.pull_request.labels.*.name, 'must-go-in-4.0')}}"
```suggestion
          has_label="${{contains(github.event.pull_request.labels.*.name, 'i-acknowledge-this-goes-into-4.0')}}"
```

2022-08-29 14:03 UTC, mrnugget commented on .github/workflows/fourpointoh-protector.yml
> +              echo "✅ Label 'must-go-in-4.0' is present"
```suggestion
              echo "✅ Label 'i-acknowledge-this-goes-into-4.0' is present"
```

2022-08-29 14:03 UTC, mrnugget commented on .github/workflows/fourpointoh-protector.yml
> +              echo "❌ Label 'must-go-in-4.0' is absent"
```suggestion
              echo "❌ Label 'i-acknowledge-this-goes-into-4.0' is absent"
```

2022-08-29 14:12 UTC, jhchabran commented
> Thank you for doing this! I request changes because I think we should make clear with the label name that this is only an "ack" and not "please put this in the release", since authors of unrelated changes will also have to use it for their PRs.
> 
> Can we also make the "failed" message a bit more explanatory?

It totally makes sense, thanks for suggesting this.

2022-08-29 14:18 UTC, mrnugget approved these changes
Sweet!

2022-08-29 14:18 UTC, mrnugget commented on .github/workflows/fourpointoh-protector.yml
> +              echo "👉 If you are 100% sure your changes should go in 4.0, label your PR with 'i-acknowledge-this-goes-into-4.0''"
```suggestion
              echo "👉 We're in the Sourcegraph 4.0 code freeze. If you are 100% sure your changes should go in 4.0 or provide no risk to the release 4.0, add the label your PR with 'i-acknowledge-this-goes-into-4.0''"
```

2022-08-29 14:19 UTC, jhchabran commented
> > Run with dday set to 2022-09-09 and no label:
> 
> The last entry in your list -- shouldn't this be a different date?

@mrnugget Why? We're launching on sep 9th 2022 right? I tested that before that this PR is not blocking anyone.

2022-08-29 14:33 UTC, mrnugget commented
> Why? We're launching on sep 9th 2022 right? I tested that before that this PR is not blocking anyone.

Does that mean you have case 1 and 3 mixed up? In the year 202**1** a PR should not have a red check, right? Only >= 202**2**-09-09 and without a label, right?

<img width="771" alt="screenshot_2022-08-29_16 32 09@2x" src="https://user-images.githubusercontent.com/1185253/187225887-afe9e99c-cd7c-4fd3-8bc4-9f046cb7c60e.png">

2022-08-29 16:40 UTC, jhchabran commented
@mrnugget on the first scenario, the release day is set in the past, so you have to set a label for the check to pass. That particular test was "without" the label. It's basically the same thing as opening a PR on Sep 12th without the label, the check will block the PR. 

The third one, is when the release day is set on the Sep 9th (next week), but the PR being open today, it's passing without the label. 

I think the part you're missing is that dday is the release date, I just moved it in the past to check things. I didn't change the current date.

2022-08-30 06:47 UTC, merged

2022-08-30 07:34 UTC, mrnugget commented
> I think the part you're missing is that dday is the release date, I just moved it in the past to check things. I didn't change the current date.

Oh, that was it. Thanks!