add extended timeout feature
sourcegraph/sourcegraph pull request #41211
Opened 2022-09-01 15:08 UTC by unclejustin

## Test plan

2022-09-01 19:54 UTC, felixfbecker commented
@unclejustin just FYI an integration test for the expand button is failing on this PR

2022-09-01 20:19 UTC, felixfbecker commented
@unclejustin I tested the web preview and noticed this PR didn't remove the "Loading..." text per [the accepted proposal by Joel in Figma](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=2653:30074#255201807). Could you include that change?

2022-09-01 20:24 UTC, felixfbecker commented
I also noticed that the text is larger than in the design. I think it's supposed to use the small button variant, but uses regular size here. The intended font size is 12px, but it is currently 14px.

2022-09-02 00:20 UTC, unclejustin commented
Thanks for the review @felixfbecker !

@AlicjaSuska some thoughts. Now that "Loading..." is gone, it looks like the site is just not responding after you click to run aggregations.

I'm using a "small" button from Wildcard, but the font size is now too small. 11px instead of 12px. I can fix it with a CSS override, but I wanted your opinion before I did so. Overriding a core component like this doesn't feel right to me.

I've hidden the expand button as per the design, but it flashes in and out while the data is loading. I'm working on keeping it from flashing, but it breaks some important tests if I do. So I've left it in this "flashing" state for now so I can confirm the pipeline is green otherwise.

2022-09-05 11:47 UTC, AlicjaSuska requested changes
Thank you for working on this @unclejustin. Here are some changes that I'd like to suggest:

1. Text size in the button - in the [storybook](https://storybook.sgdev.org/?path=/story/wildcard-button--all-buttons) min. text size for the button is 0.75rem (12px). I'm not sure why it comes at 11px here. It's not a good size. If there is anything to update directly in the component to align with desired values, I think it's ok to make changes directly to the component.
2. Another issue with text in the button is that it shouldn't be 'regular' but 'medium' - a little heavier style. @unclejustin could you please try to address it as well?
3. Please, use 16px x 16px bounding box for the icon. Not it is 24x24. 
4. The chart skeleton in the background is too tall (I think it applies to all the error states) - in the design it's 115px, in the implementation it is over 200px.
5. After re-running the aggregation, I got this error message. I think we should have a better state with the error message, not the alert.
<img width="251" alt="Screenshot 2022-09-05 at 13 43 48" src="https://user-images.githubusercontent.com/20326070/188441659-79ae2a8a-31da-4846-a99b-c6671ca9300a.png">

2022-09-05 14:43 UTC, vovakulikov commented on client/web/src/search/results/sidebar/SearchAggregations.tsx
> +        !error && data && data.searchQueryAggregate?.aggregations?.__typename !== 'SearchAggregationNotAvailable'
I don't think we should hide expand button on error or `SearchAggregationNotAvailable` case, as Felix said somewhere in Figma that this button can help with re-triggering aggregation data here.

2022-09-05 14:43 UTC, vovakulikov commented on client/web/src/search/results/sidebar/SearchAggregations.tsx
> +        !error && data && data.searchQueryAggregate?.aggregations?.__typename !== 'SearchAggregationNotAvailable'
If we still want to have it I would suggest move this out from the render and have a small quick selector function. 
I'm trying to experiment and see is it better to keep render call a bit less verbose but more dense.

2022-09-05 14:43 UTC, vovakulikov commented on client/web/src/search/results/components/aggregation/hooks.ts
>          calculatedAggregationModeRef.current = null
@unclejustin I actually think that this line (that I did write) doesn't work as I designed) The chart only works correctly because in the parent components we have set of different state updates and we trigger aggregation hook multiple times, see useEffect manages to mutate `calculatedAggregationModeRef` and therefore re-trigger useQuery call on the next `useSearchAggregationData`

This is a very flaky mechanism, I think we should change it to useState here.

2022-09-06 13:14 UTC, vovakulikov commented
@AlicjaSuska during local testing I found this run aggregation button text as a very confusing part, at the beginning I run a search, and I see skeleton and after I see button Run aggregation. It feels like a UI bug, users can't answer the questions what were happening before they see Run aggregation button (was it a bug?) 

I think we should provide a better error message and the button Run aggregation below and not just one button. @Joelkw [suggestion about removing aggregation error](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=1908:20472#255201807) is based on the fact that we're not showing Loading copy here. But based on your comment above about Loading (and I agree with you) we should have loading state.

2022-09-06 13:20 UTC, vovakulikov commented
@AlicjaSuska about loading state height, please consider that if different states have different heights it will introduce layout shift there. We need to be very careful with it on the search result page. This page already has a lot of jumps when the first part of the search results comes in. Having another layout shift here may make this page even more jumpy and clumsy.

2022-09-06 17:25 UTC, unclejustin commented
> 1. Text size in the button - in the [storybook](https://storybook.sgdev.org/?path=/story/wildcard-button--all-buttons) min. text size for the button is 0.75rem (12px). I'm not sure why it comes at 11px here. It's not a good size. If there is anything to update directly in the component to align with desired values, I think it's ok to make changes directly to the component.

Looks like the base font for buttons has been set to 0.875rem (about 7 months ago). So 16 * 0.875 = 14px. So 0.75rem of 14px is 10.5px.  I don't know why the base font is not 16px anymore.

I have updated it to 0.857rem ~12px

> 2. Another issue with text in the button is that it shouldn't be 'regular' but 'medium' - a little heavier style. @unclejustin could you please try to address it as well?

✅ 

> 3. Please, use 16px x 16px bounding box for the icon. Not it is 24x24.

A lot has changed in how this has been rendered. It is still a 24x24 bounding box, but it _looks_ correct to me. The arrow is the same size as in Figma anyway. Please confirm.

> 4. The chart skeleton in the background is too tall (I think it applies to all the error states) - in the design it's 115px, in the implementation it is over 200px.

✅ 

> 5. After re-running the aggregation, I got this error message. I think we should have a better state with the error message, not the alert. Probably the 'we couldn't provide the aggregation, without an option to re-run'
> 
> <img alt="Screenshot 2022-09-05 at 13 43 48" width="251" src="https://user-images.githubusercontent.com/20326070/188441659-79ae2a8a-31da-4846-a99b-c6671ca9300a.png">
> 

Outside the scope of this PR. There is some commentary about this on Slack, though. So a fix should be coming soon.

> 6. The 'loading...' meassge - I think there was a misunderstanding here. I think we should still use the loading message, together with the 'run aggregation' in the flow as follows:
> * user runs a search, 'Loading...' in the panel
> * timeout: 'Loading' changes to 'Run aggregation' button
> * user clicks on the button - display 'Loading...' again until they get the results
> 
> For this case with 60s timeout, I think we should show that the process is still ongoing. A static 'loading...' works ok for the initial 2s timeout but here, since we have 60s, I would like us to add animation to '...' so that it doesn't look like nothing is happening. It can be a simple animation of drawing them and removing dot-by-dot. @unclejustin is it feasible?

✅  but check my work please.

🏓  back to you @AlicjaSuska

2022-09-06 20:11 UTC, felixfbecker commented
> 6. The 'loading...' meassge - I think there was a misunderstanding here. I think we should still use the loading message, together with the 'run aggregation' in the flow as follows:
> user runs a search, 'Loading...' in the panel
> timeout: 'Loading' changes to 'Run aggregation' button
> user clicks on the button - display 'Loading...' again until they get the results

@AlicjaSuska [@Joelkw's proposal that we agreed on](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=1908:20472#255201807) explicitly included _removing_ any "Loading..." text (at least for the initial load) and explained the reason:

> 1) change our loading state to only show the skeleton chart, but not the word "loading..."
> 
> Why: 
> If we don't say "loading..." we don't need to explain to a user why we went from "loading..." to no results. The two paths are: you see the skeleton chart, and then you get results; or, you see the skeleton chart, and then you're given the option to run the aggregation. Both are acceptable and they both reframe from "Sourcegraph is not powerful and times out a lot." 
> 
> (Yes, a user can (and will) probably figure out that we show proactive aggregations sometimes and not always, and likely assume it's based on how fast they complete. I am less worried about user confusion here than about always showing a "we failed to complete in time" message, because the user, even if confused, can get what they need by clicking the 'run aggregation button'. ) 

I also updated the design 5 days ago [and tagged you in Figma](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=275:1628#258528302) because I saw the "Loading..." hadn't been removed yet from the design after we agreed on it.

This is what I [called out in my comment](https://github.com/sourcegraph/sourcegraph/pull/41211#issuecomment-1234738571) earlier on this PR.

I agree with @Joelkw's proposal and reasoning strongly and am really hesitant to go back and forth about this on the PR at this stage of the project when we had this discussion in the design last week and agreed on it.

Re @vovakulikov:

> @AlicjaSuska during local testing I found this run aggregation button text as a very confusing part, at the beginning I run a search, and I see skeleton and after I see button Run aggregation. It feels like a UI bug, users can't answer the questions what were happening before they see Run aggregation button (was it a bug?)
> 
> I think we should provide a better error message and the button Run aggregation below and not just one button. @Joelkw [suggestion about removing aggregation error](https://www.figma.com/file/cKSeCtmBh9aiPsAVoKsLgM?node-id=1908:20472#255201807) is based on the fact that we're not showing Loading copy here. But based on your comment above about Loading (and I agree with you) we should have loading state.

The suggestion is not based on not showing loading copy, but not showing loading copy is a requirement to not show an error/only show the button, because we don't want to show that something is loading and then suddenly change it to a button – that would be confusing.

The real reason that we only want to show the user the button and **not** an error (as explained by @Joelkw) is that we don't want to throw a bunch of errors and loading states at the user all the time for something they didn't ask for. You're right in that showing an error and a loading state is clearer for users that want to use the aggregation feature to explain what is going on. But consider that for the vast majority of cases, the user will still come to the search results page for the search results and **not** for the aggregations, so not making our product look bad (like it errors all the time) in the majority case takes precedence over being super clear to users that explicitly want to use the aggregation feature. We are a sidecar and have to consider the search UX as a whole, not only the experience with the aggregation feature. In the full UI view things can be different.

I do think it would be okay to show the "Loading..." indicator after clicking "Run aggregations" if you all care for it but I also don't want to cause more band-and-forth work for @unclejustin at this point than necessary.

2022-09-06 20:49 UTC, Joelkw commented
See this thread for the [expected state](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1662497324096039?thread_ts=1662473472.104109&cid=C01RVEVPWLC): 

Let’s move the expected state at least to where we are aligned right now across product and design:

1. Show a “loading…” while it proactively runs
2. Show only a “run aggregation” option (NO error message/additional info) if it does not run proactively
3. After hitting “run aggregation” a user sees the “loading…” indicator again.

whether we keep #1 or modify that more is TBD but let's move forward for today.

2022-09-06 21:28 UTC, vovakulikov commented
@unclejustin (just a check)

>Show only a “run aggregation” option (NO error message/additional info) if it does not complete proactively

I think in all other cases (in case of query is invalid or aggregation isn't possible for a given query) we still need to show a common error UI (not the ErrorAlert but the aggregation error UI)

2022-09-06 22:43 UTC, unclejustin commented
> I think in all other cases (in case of query is invalid or aggregation isn't possible for a given query) we still need to show a common error UI (not the ErrorAlert but the aggregation error UI)

That is correct. I am only showing "Run aggregation" when `TIMEOUT_EXTENSION_AVAILABLE` is returned for a reason type.

2022-09-06 22:43 UTC, unclejustin commented
@AlicjaSuska this is ready for review again.

2022-09-07 00:02 UTC, AlicjaSuska approved these changes

2022-09-07 04:35 UTC, merged