Render "no data" error message for searches with no results
sourcegraph/sourcegraph pull request #41277
Opened 2022-09-02 18:07 UTC by unclejustin

Related to https://github.com/sourcegraph/sourcegraph/issues/40871

display "zero data" error message

## Test plan

Run any search that returns no results. For example "asdfasdfasdf"

Should render the "No data to display" over the chart skeleton

2022-09-02 18:41 UTC, vovakulikov reviewed
@unclejustin I like the component restructure that you did here. I left a few minor comment about code base. 

About functionality I think you missed the part where we should hide this sidebar section when we don't have any search matches results.

2022-09-02 18:41 UTC, vovakulikov commented on client/web/src/search/results/components/aggregation/ErrorContainer.tsx
> +    console.log(size)
🐱

2022-09-02 18:41 UTC, vovakulikov commented on client/web/src/search/results/components/aggregation/AggregationChartCard.tsx
> +            <ErrorContainer size={size} className={className}>
Let's name it more explicit like SearchAggregationErrorContainer? Because I see how people will encounter in this file as they search something about generic error container component

2022-09-02 19:28 UTC, unclejustin commented on client/web/src/search/results/components/aggregation/ErrorContainer.tsx
> +    console.log(size)
That's uhhhh supposed to be there.

2022-09-02 21:27 UTC, vovakulikov commented on client/web/src/search/results/sidebar/SearchFiltersSidebar.tsx
> +            repoFilters.length > 0,
@unclejustin why do we use repoFilters here as a check for the aggregation panel? I thought we should use results field instead. Basically I think the check should be the same that we use for the no search result page 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/client/search-ui/src/results/StreamingSearchResultsList.tsx?L208-222&utm_product_name=WebStorm&utm_product_version=WebStorm&utm_source=JetBrains-v2.0.0

Just to be sure we're doing right thing here I would discuss it with @limitedmage (just because logic there for this page isn't so clear to me)

2022-09-05 10:38 UTC, AlicjaSuska commented
@unclejustin I've added myself as a reviewer as well - a friendly reminder to add me to all the PRs with the UI/UX changes :)

The following points do not work as expected - after searching for "repo:sourcegraph/sourcegraph", chart isn't rendered automatically, I still need to select the aggregation - was that the intent?

> 3. Search for "repo:sourcegraph/sourcegraph"
> 4. Should render the chart

+1 to @vovakulikov comment:

> About functionality I think you missed the part where we should hide this sidebar section when we don't have any search matches results.

The section should be collapsed. If someone opens it, all buttons should be disabled, no chart should be shown. Currently, the whole section not there at all:
<img width="1535" alt="Screenshot 2022-09-05 at 12 38 02" src="https://user-images.githubusercontent.com/20326070/188430115-872503f4-b0a3-47f1-808a-3beca5873124.png">

2022-09-05 10:38 UTC, AlicjaSuska requested changes
Please, see the comment above for the details

2022-09-06 11:18 UTC, vovakulikov commented
Since this one is an important part for the 4.0 @unclejustin I fixed comments while you were off. I fixed @AlicjaSuska comment and resolved conflicts with main. 

@AlicjaSuska can you please check this one again and approve if you don't see any other problems here. 

> The section should be collapsed. If someone opens it, all buttons should be disabled, no chart should be shown. Currently, the whole section not there at all:

@AlicjaSuska this isn't what we agreed on in the issue thread. Felix suggested hide the whole section and I agree with him, because this is how repository filters section works.

2022-09-06 16:21 UTC, vovakulikov approved these changes

2022-09-06 18:20 UTC, AlicjaSuska approved these changes

2022-09-06 18:21 UTC, merged