Tl/implement path match ranges
sourcegraph/sourcegraph pull request #41296
Opened 2022-09-04 22:38 UTC by tbliu98

## Test plan

2022-09-05 15:24 UTC, camdencheek requested changes
Direction looks great! Small comments inline.

> Right now, paths will only be highlighted if the search result is explicitly a PathMatch.

I'm not sure how I feel about this. In my mind, this violates the principle of least surprise. It looks weird to me to have paths highlighted on some results but not others. 

This is especially true because we don't emit path matches if there are any content matches in the file. For example, in your screenshot, we don't emit a path match for `internal/database/access_tokens.go` because there is a content match for that file. This means the results won't visually represent the fact that the path `internal/database/access_tokens.go` is a match for your query.

2022-09-05 15:24 UTC, camdencheek commented on internal/search/job/jobutil/job.go
> +func zoektQueryPatternsAsRegexps(q zoektquery.Q) (res []*regexp.Regexp) {
A couple of comments on this function:
1) This should probably be written to use `zoektquery.VisitAtoms()` so that it also traverses through `Not` nodes and `Type` nodes
2) I think we want to only extract patterns that can match paths here. Both `zoektquery.Regexp` and `zoektquery.Substring` have `FileName` fields and `Content` fields that restrict to that type, so I think we just want to check that `!typedQ.Content`

2022-09-05 15:24 UTC, camdencheek commented on internal/search/job/jobutil/job.go
> +				}
Should we take into account `file:` patterns here?

2022-09-05 15:24 UTC, camdencheek commented on internal/search/zoekt/indexed_search.go
> +func DoZoektSearchGlobal(ctx context.Context, client zoekt.Streamer, args *search.ZoektParameters, zoektQueryRegexps []*regexp.Regexp, c streaming.Sender) error {
nit: instead of `zoektQueryRegexps`, can we call this something like `pathRegexps` to make its purpose more clear?

2022-09-05 15:24 UTC, camdencheek commented on internal/search/job/jobutil/job.go
> +				}
Additionally, I don't think we actually want to use `Pattern` for this. The `TextPatternInfo` has a (poorly-named) `IncludePatterns` field which is the list of patterns that the file path needs to match. I think we should use that instead.

2022-09-06 02:36 UTC, tbliu98 commented on internal/search/job/jobutil/job.go
> +				}
I think we want to actually check both `Pattern` and `IncludePatterns`. It looks like `IncludePatterns` is only populated if the `file:` filter is present. But if path matches show up in the results for a query that doesn't have a `file:` filter, we still want to highlight those.

But yeah, we should take into account `file:` patterns. They're actually not being highlighted as is -- I missed that, thankfully code review is a thing 😄

2022-09-06 02:58 UTC, tbliu98 commented
>  This means the results won't visually represent the fact that the path internal/database/access_tokens.go is a match for your query.

Thanks for the feedback on this @camdencheek, I wasn't sure which way to go here. Initially I was worried about adding too much new visual noise, but I also think it makes sense to be consistent in how we display results. I can see how this inconsistency could be surprising to a user. 

I can add `PathMatches` as a field to our other match types in a follow-up PR to keep the scope of this one limited to getting the behavior right.

2022-09-06 16:39 UTC, tbliu98 commented on internal/search/job/jobutil/job.go
> +func zoektQueryPatternsAsRegexps(q zoektquery.Q) (res []*regexp.Regexp) {
Didn't know `zoektquery.VisitAtoms()` existed -- very helpful!

2022-09-06 17:56 UTC, limitedmage reviewed
Frontend code looks good to me. I think we should update the color used to highlight though, the contrast is way too low. I opened https://github.com/sourcegraph/sourcegraph/issues/41378 and assigned to @almeidapaulooliveira to pick the right color. I don't know if that should be a blocker for this feature, @benvenker  and @almeidapaulooliveira  can decide.

2022-09-06 18:25 UTC, camdencheek approved these changes
A couple of small comments inline, but this is looking good 🥳 

> I can add PathMatches as a field to our other match types in a follow-up PR to keep the scope of this one limited to getting the behavior right.

Sounds great!

2022-09-06 18:25 UTC, camdencheek commented on internal/search/job/jobutil/job.go
> +				if patternInfo.PatternMatchesPath {
I think this condition should be inside `getPathRegexpsFromTextPatternInfo`, right? Because, even if `PatternMatchesPath == false`, we still want to get the highlighted ranges from `patternInfo.IncludePatterns`, yes?

2022-09-06 18:25 UTC, camdencheek commented on internal/search/zoekt/indexed_search.go
> +	ZoektQueryRegexps []*regexp.Regexp
Since it's not immiediately clear from context, could we add a comment explaining what this is for? Same applies to other places we add this field to a struct. 

I'm not very good about this, but since jobs are now one of our primary forms of abstraction, it would be nice if we could understand them better at a glance without needing to go find where the field is used or how it's populated.

2022-09-06 21:22 UTC, tbliu98 commented on internal/search/job/jobutil/job.go
> +				if patternInfo.PatternMatchesPath {
had to think about it for a minute but yes I think you're right

2022-09-06 21:30 UTC, merged