[code-nav]: Moving graphql transport layer to individual service layers
sourcegraph/sourcegraph pull request #41596
Opened 2022-09-09 19:29 UTC by Numbers88s

Moving codenav resolvers to the service's transport layer.

## Test plan
Run all the test :all_the_things:

2022-09-26 18:59 UTC, efritz requested changes

2022-09-26 18:59 UTC, efritz commented on internal/codeintel/sharedresolvers/cloneurls.go
> +// host to see if the repository actually exists.
Is there a way we can reuse the existing implementation of this instead of copying it? It didn't originate from the graphqlbackend package.

2022-09-26 19:01 UTC, Numbers88s commented on internal/codeintel/sharedresolvers/cloneurls.go
> +// host to see if the repository actually exists.
yeah I'll look into it for sure

2022-09-26 20:02 UTC, Numbers88s commented on internal/codeintel/sharedresolvers/cloneurls.go
> +// host to see if the repository actually exists.
Done.

2022-09-26 20:04 UTC, efritz approved these changes

2022-09-26 20:21 UTC, efritz commented
Ran it locally, seemed golden :shipit:

2022-09-27 17:25 UTC, efritz commented
Fixes #41129. Fixes #41130. Fixes #41131. Fixes #41132.

2022-09-28 19:55 UTC, efritz commented
@Numbers88s I'm going to merge this but I'll also babysit CI and the deployments and revert if necessary.

2022-09-28 19:55 UTC, merged

2022-10-13 22:28 UTC, chrismwendt commented on internal/codeintel/codenav/transport/graphql/resolver.go
> -	}
@Numbers88s it looks like this section didn't get copied over to the new location of the surrounding code:

https://github.com/sourcegraph/sourcegraph/blob/ec3175a40b3e80ec85b723231d0b420041a0b010/internal/codeintel/codenav/transport/graphql/root_resolver.go#L51-L65

I think that was the only place `QueueRepoRev()` was ever called, so now it's dead code.

Was that intentional, or should we add this section back in?

2022-10-14 20:10 UTC, Numbers88s commented on internal/codeintel/codenav/transport/graphql/resolver.go
> -	}
Oh interesting, that's for bringing this up. I got to take a look at it then. It should've been.

2022-10-14 21:01 UTC, Numbers88s commented on internal/codeintel/codenav/transport/graphql/resolver.go
> -	}
Here's the fix.

👉 https://github.com/sourcegraph/sourcegraph/pull/43017