ranking: introduce maxQueueMatchCount
sourcegraph/sourcegraph pull request #41626
Opened 2022-09-12 13:13 UTC by stefanhengl

the queue depth (IE number of search results) can be a poor measure to protect against OOMs because the number of matches varies a lot depending on the query.

Here we introduce another counter that can trigger a partial flush: maxQueueMatchCount. The goal is to set it high enough so that it doesn't trigger for reasonable queries, but low enough so that it protects the queue from extreme match counts.

## Test plan
- adapted unit tests
- local testing

2022-09-13 06:24 UTC, stefanhengl commented on internal/search/backend/horizontal.go
> -	sr.Stats = zoekt.Stats{}
Previously, we stripped stats from the search results. Now we keep them because we need to subtract the the match count when we pop the search result from queue.

2022-09-13 12:13 UTC, keegancsmith requested changes

2022-09-13 12:13 UTC, keegancsmith commented on internal/search/backend/horizontal.go
>  	metricFinalQueueSize.Add(float64(q.queue.Len()))
I noticed that we also call FlushAll after your initial duration thing. That means these stats will be misleading.

2022-09-13 12:13 UTC, keegancsmith commented on internal/search/backend/horizontal.go
>  		sr.Stats = q.stats
I'm not sure if this behaviour is correct after sr.Stats is not cleared. TBH I'm having a hard time now tracking this. Maybe you need a central method which deals with Pop and send so we can be very clear with the invariants going on.

Almost certain this will require changes, since you call FlushAll with your duration stuff.

2022-09-13 12:13 UTC, keegancsmith commented on internal/search/backend/horizontal.go
> +	for q.isFull() || q.queue.isTopAbove(maxPending) {
maybe move all of this logic into your isFull method (with a different name?) and pass in maxPending. Then the logic around when we decide to send something is all together.

2022-09-14 08:59 UTC, stefanhengl commented on internal/search/backend/horizontal.go
> +	for q.isFull() || q.queue.isTopAbove(maxPending) {
done

2022-09-14 09:02 UTC, stefanhengl commented on internal/search/backend/horizontal.go
>  	metricFinalQueueSize.Add(float64(q.queue.Len()))
I extracted the metrics and call them explicitly only before the last flush.

2022-09-14 09:04 UTC, stefanhengl commented on internal/search/backend/horizontal.go
>  		sr.Stats = q.stats
I believe this should have worked because we are popping all results and then set the matchCount to 0 afterwards. However, having it all within the new pop() method and sharing the code with FlushReady is much neater.

2022-09-14 14:08 UTC, keegancsmith approved these changes

2022-09-14 14:08 UTC, keegancsmith commented on internal/search/backend/horizontal.go
> +	}
should this be done in enqueue instead? Right now technically I think you should be checking this when doing FlushAll as well. I think moving the check to the same place you increment matchCount makes the most sense for understanding its behaviour.

2022-09-15 11:17 UTC, merged