Update username constraint to allow underscores
sourcegraph/sourcegraph pull request #41723
Opened 2022-09-19 08:31 UTC by thenamankumar

closes https://github.com/sourcegraph/sourcegraph/issues/35751

Allow underscores in usernames the same way hyphens are allowed.
A username can end with either an underscore or a hyphen but can not start with either.
There cannot be two or more continuous underscores, hyphens or dots in a username. 

made changes to:
- database constraint
- frontend form validators
- username normalization

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/22571395/190978541-a2914c82-2ee5-4d0d-9b4e-fc7343aa8fd2.png">

## Test plan

Perform migration via `sg migration up -db=frontend`

- Go to settings -> Profile
- Update username field and save

2022-09-19 09:57 UTC, pjlast requested changes

2022-09-19 09:57 UTC, pjlast commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
I would allow usernames to start with `_`. GitLab allows this, and if you try to link a GitLab account that starts with an underscore you'll run into issues. See here: https://github.com/sourcegraph/sourcegraph/issues/41298

Might have to test the consecutive underscores thing as well

2022-09-19 09:59 UTC, thenamankumar commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
Should we allow consecutive usernames?

2022-09-19 10:03 UTC, pjlast commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
Well it comes down to the following: If someone tries to sign in with GitLab, and their GitLab username doesn't match our Sourcegraph constraints, then the account goes into a strange state.

So we either need to allow whatever GitLab allows, or we need to make some adjustments to the username when a user logs in with a GitLab account that has an invalid username

2022-09-19 10:21 UTC, thenamankumar commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
Gitlab allows consecutive symbols: 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/22571395/190996842-5667ac1f-f2a8-4063-9fbb-79ea21a5d88e.png">

- underscores are treated same as alphanumeric
- can not begin with hyphen 
- can not end with dot
- symbols can be consecutive

Should I make it exactly like Gitlab?

2022-09-19 10:38 UTC, pjlast commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
Maybe we can ask someone about the reason for the current constraints, just to make sure we don't cause some problems.

But my view is that we'll keep running into issues if users try to sign in with different configurations of this

2022-09-19 15:43 UTC, thenamankumar commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
I have made underscores to work like alphanumeric, so they can come anywhere, any number of times. Didn't change rest.

2022-09-20 05:16 UTC, pjlast commented
Buildkite still seems a bit angry

2022-09-20 05:19 UTC, pjlast commented
tagging @efritz to maybe just review the DB changes but I think its good

Obviously future usernames added with this schema will be incompatible with previous schemas.

2022-09-20 05:20 UTC, pjlast commented
@thenamankumar you can maybe just check Buildkite, there's a message explaining how to address the "incompatible changes" to DB schemas

2022-09-20 10:12 UTC, thenamankumar commented
> 

had to run `sg generate` to update db schema files.

2022-09-20 10:54 UTC, pjlast commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
```suggestion
	DROP CONSTRAINT users_username_valid_chars,
    ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
```

2022-09-20 10:54 UTC, pjlast commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/up.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9_](?:[a-zA-Z0-9_]|[-.](?=[a-zA-Z0-9_]))*-?$'::citext);
```suggestion
	DROP CONSTRAINT users_username_valid_chars,
    ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9_](?:[a-zA-Z0-9_]|[-.](?=[a-zA-Z0-9_]))*-?$'::citext);
```

2022-09-20 12:47 UTC, efritz commented on cmd/frontend/auth/auth.go
> +	disallowedCharacter = lazyregexp.New(`[^a-zA-Z0-9\-\.\_]`)
Underscore isn't a meta character, you shouldn't need to escape it here. Is this regexp tested in unit tests?

2022-09-20 12:48 UTC, efritz commented on cmd/frontend/auth/auth.go
> +// - Usernames with consecutive `-` or `.` or `_` characters are not allowed
This seems outdated after https://github.com/sourcegraph/sourcegraph/pull/41723/files#r974409781

2022-09-20 12:51 UTC, efritz commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
Just to be clear, if an instance downgrades after a newly-allowable user registers, the site-admin will have to manually change the name to something without underscores.

Does this seem correct?

(This is fine with me, just wanted to make sure we start thing this way as an eng org).

If we always would suggest the same action we could automate it here (a quick update to re-name users before the alter table).

2022-09-20 12:54 UTC, efritz commented
@thenamankumar @pjlast I have no problems with this migrations 👍 

The constraint is getting strictly wider, which shouldn't affect any existing data. This does, however, make buildkite angry with the backcompat tests. We're running _old_ unit tests which expect a failure when an underscore is included, but we explicitly allow that now. It's an easy fix to add an entry into the flakefile (the summary of the backcompat failure gives exact instructions). You'll want to create one for 3.43 AND 4.0 if you add it before the release finishes.

2022-09-20 12:57 UTC, pjlast commented on cmd/frontend/auth/auth.go
> +	disallowedCharacter = lazyregexp.New(`[^a-zA-Z0-9\-\.\_]`)
We can also replace `a-zA-Z0-9_` with `\w`

2022-09-20 13:00 UTC, pjlast commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
The only tricky bit with renaming users automatically is that there could be 2 users like `_pjlast` and `pjlast` and automatically renaming the first to the second one would cause conflicts (I think).

Hmmm 🤔 but I guess if there are conflicts (and it is enforced on a DB level), then the migration would fail and the admin would get some sort of feedback. So perhaps it is worth doing like that

2022-09-20 13:01 UTC, efritz commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
Would not be a great user experience though. Maybe it's fine to just fail immediately and have the user decide in this case.

2022-09-21 22:05 UTC, thenamankumar commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
I would prefer for admins to handle the username changes themselves if they decide to roll back. I don't want to magically change username for a lot of users. And even with auto-revert, there can be conflicts.

2022-09-21 22:08 UTC, thenamankumar commented
> @thenamankumar @pjlast I have no problems with this migrations 👍
> 
> The constraint is getting strictly wider, which shouldn't affect any existing data. This does, however, make buildkite angry with the backcompat tests. We're running _old_ unit tests which expect a failure when an underscore is included, but we explicitly allow that now. It's an easy fix to add an entry into the flakefile (the summary of the backcompat failure gives exact instructions). You'll want to create one for 3.43 AND 4.0 if you add it before the release finishes.

@efritz 

I am not planning to make this part of the 4.0 release. But I have doubts regarding how the flakefile works.

If I add the tests to the file as mentioned in the docs, will they be always ignored even if they fail?

In the next release after 4.0 can I remove these tests from flakefile?

2022-09-21 22:47 UTC, thenamankumar commented on cmd/frontend/auth/auth.go
> +// - Usernames with consecutive `-` or `.` or `_` characters are not allowed
updated

2022-09-21 22:47 UTC, thenamankumar commented on cmd/frontend/auth/auth.go
> +	disallowedCharacter = lazyregexp.New(`[^a-zA-Z0-9\-\.\_]`)
updated everywhere

2022-09-21 22:47 UTC, thenamankumar commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/up.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9_](?:[a-zA-Z0-9_]|[-.](?=[a-zA-Z0-9_]))*-?$'::citext);
updated

2022-09-21 22:48 UTC, thenamankumar commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
updated

2022-09-26 08:35 UTC, pjlast commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
```suggestion
// - Usernames that start with `-` are not allowed
```

2022-09-26 08:37 UTC, pjlast commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +    ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
```suggestion
ALTER TABLE users
	DROP CONSTRAINT users_username_valid_chars,
	ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
```

Consistent use of tabs and spaces

2022-09-26 08:38 UTC, pjlast commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/up.sql
> +    ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^\w(?:\w|[-.](?=\w))*-?$'::citext);
```suggestion
ALTER TABLE users
	DROP CONSTRAINT users_username_valid_chars,
	ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^\w(?:\w|[-.](?=\w))*-?$'::citext);
```

Consistent use of tabs and spaces

2022-09-26 08:46 UTC, thenamankumar commented on cmd/frontend/auth/auth.go
> +// - Usernames that start with `-` or `_` are not allowed
updated

2022-09-26 08:46 UTC, thenamankumar commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +    ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
updated

2022-09-26 08:46 UTC, thenamankumar commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/up.sql
> +    ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^\w(?:\w|[-.](?=\w))*-?$'::citext);
updated

2022-09-26 08:46 UTC, pjlast approved these changes

2022-09-26 09:00 UTC, merged

2022-09-27 05:57 UTC, unknwon commented on migrations/frontend/1663569995_update_username_valid_chars_contraint/down.sql
> +  ADD CONSTRAINT users_username_valid_chars CHECK (username ~ '^[a-zA-Z0-9](?:[a-zA-Z0-9]|[-.](?=[a-zA-Z0-9]))*-?$'::citext);
+1 to let "admins to handle the username changes themselves if they decide to roll back". Collisions will have unexpected impersonates for users.

2022-09-27 05:59 UTC, unknwon commented
@thenamankumar @pjlast - I think this change is CHANGELOG-worthy.

2022-10-14 09:20 UTC, keegancsmith commented on migrations/frontend/squashed.sql
> +    CONSTRAINT users_username_valid_chars CHECK ((username OPERATOR(~) '^\w(?:\w|[-.](?=\w))*-?$'::citext))
@thenamankumar: FYI this has a subtle change you likely did not intend. `\w` means word in your locale. In our CI environment (and likely your dev env) your postgres DB is likely has the locale set to `C` which does not support utf8. Which is equivalent to what we had before. However, in my devenv (and I suspect a few customers) the locale I have is `en_US.UTF8` which makes `\w` mean a _lot_ more chars. For example in my devenv the test case for `レンフレッド` is regarded as a valid username but in our tests we expect it to be false.

I have since updated my devenv postgres to use the C locale (or no locale). I will create a discussion in slack about locale and postgres.