codeintel: fix incorrect range highlight for adjusted modified ranges
sourcegraph/sourcegraph pull request #41955
Opened 2022-09-22 18:45 UTC by Strum355

The long awaited follow up to https://github.com/sourcegraph/sourcegraph/pull/21287, where we fix the ranges. Potentially due to how things have been shuffled around, this may also be undoing the changes made in that PR, so we should be testing this well before/after going live.

Fixes the issue described by here https://github.com/sourcegraph/sourcegraph/issues/41933

## Test plan

Tested locally

2022-09-22 18:46 UTC, Numbers88s approved these changes

2022-09-22 18:58 UTC, efritz commented on internal/codeintel/codenav/service.go
> +		}
If `getSourceRange` returns a valid commit/range when ok = false, then I'd suggest duplicating or flagging this behavior for Ranges only and not the other callers.

2022-09-22 18:59 UTC, efritz requested changes
left comments inline

2022-09-28 13:55 UTC, efritz commented on internal/codeintel/codenav/service.go
> +		if includeFallbackLocations || !ok {
```suggestion
		if !ok && !includeFallbackLocations {
```

...right?

2022-09-28 13:56 UTC, efritz commented on internal/codeintel/codenav/service.go
> +// they are simply dropped.
```suggestion
// commit. If includeFallbackLocations is true, then any range in the indexed commit that cannot be translated
// will use the indexed location. Otherwise, such location are dropped.
```

I think might be more clear (since "changed since" leaks details about the caller).

2022-09-28 13:57 UTC, Strum355 commented on internal/codeintel/codenav/service.go
> +		if includeFallbackLocations || !ok {
yap, have it unpushed locally

2022-09-28 19:51 UTC, efritz commented on internal/codeintel/codenav/service_ranges_test.go
> +		{ID: 53, Commit: "deadbeef", Root: "sub4/", RepositoryID: 42},
nit: `deadbeef1` and `deadbeef2` would keep the text aligned omg that's such a huge hit

2022-09-28 19:51 UTC, efritz approved these changes

2022-09-29 13:12 UTC, merged