Insights/integration-test-populated-dashboard
sourcegraph/sourcegraph pull request #41962
Opened 2022-09-22 22:10 UTC by unclejustin

WIP

## Test plan

Integration tests should pass

2022-09-23 22:37 UTC, unclejustin commented on client/web/src/integration/insights/dashboards/render-populated-dashboard.test.ts
> +        testContext.overrideGraphQL({ GetInsightView: () => GET_INSIGHT_VIEW_SEARCH_BASED_INSIGHT })
Note: Need t call `overrideGraphQL` directly because `GetInsightView` is called multiple times. The way `testContext` is written, you re-call `overrideGraphQL` if you need to re-mock a query.

2022-09-27 09:19 UTC, vovakulikov commented on client/web/src/integration/insights/dashboards/render-populated-dashboard.test.ts
> +        testContext.overrideGraphQL({ GetInsightView: () => GET_INSIGHT_VIEW_SEARCH_BASED_INSIGHT })
Hmm. nice, I didn't know that testContext has a kind of stack behaviour (I thought it was last write win)

2022-09-27 09:21 UTC, vovakulikov commented on client/web/src/integration/insights/dashboards/render-populated-dashboard.test.ts
> +async function getLinks(page: Page, labels: string[]): Promise<string[]> {
Let's leave a JS doc comment here; I think it would be helpful because you usually expect the integration test to be very explicit and clean.

2022-09-27 09:21 UTC, vovakulikov approved these changes

2022-09-27 11:10 UTC, vovakulikov requested changes
@unclejustin I checked this test manually and it seems it doesn't work as we expect. As I expected override gql mock works in the way where last override wins. Because of this all insights on the page that share gql request `GetInsightsView` has the same response (the last one `GET_INSIGHT_VIEW_COMPUTE_INSIGHT`)

<img width="1341" alt="Screenshot 2022-09-27 at 17 03 25" src="https://user-images.githubusercontent.com/18492575/192510061-e99cef49-6881-445e-950b-6150c75f37dc.png">

Search-based insight is loading because there is a runtime error in the console. Mock returns unexpected result (compute-like data) that is incompatible with insight configuration (search-based)

I think we should not calling overrideGraphQL method multiple time but having one GetInisghtView mock where you should be able to get arguments of the query and based on this arguments (like on insight id) return different mock datasets

2022-09-27 11:26 UTC, vovakulikov commented
@unclejustin am I right thinking that this PR will close this issue https://github.com/sourcegraph/sourcegraph/issues/41813 as well?

2022-09-27 15:00 UTC, unclejustin commented
> @unclejustin am I right thinking that this PR will close these issues https://github.com/sourcegraph/sourcegraph/issues/41813, https://github.com/sourcegraph/sourcegraph/issues/41811 as well?

@vovakulikov no. This one only asserts that the dashboard renders. Those other PRs will assert that each insight is the actual correct type.

2022-09-28 09:06 UTC, vovakulikov approved these changes
@unclejustin checked this manually, works as expected. Also, I merged the main into this branch and fixed a few problems after it with selectors. 

<img width="1341" alt="Screenshot 2022-09-27 at 17 03 25" src="https://user-images.githubusercontent.com/18492575/192738386-3f0a2d9c-891b-4bb4-9b1e-57326e199b9f.png">

2022-09-28 11:11 UTC, merged