Create Cloud Instance onboarding doc
sourcegraph/sourcegraph pull request #41993
Opened 2022-09-23 10:26 UTC by danielmarquespt

As part of the growth initiative we need to offer proper guidance for new cloud users. Due to lack of a better onboarding experience right now we are relying on this document to offer initial guidance.

This will be shared in the welcome email, and there is not need to be linked from anywhere else in the Docs

## Test plan
n/a... I think

2022-09-23 10:58 UTC, vdavid approved these changes
LGTM, suggested some minor changes.

2022-09-23 10:58 UTC, vdavid commented on doc/getting-started/cloud-instance.md
> +Sourcegraph supports out of the box support for different auth providers, our documentation provides guidance on how to setup these
```suggestion
Sourcegraph supports out-of-the-box support for different auth providers. Our documentation provides guidance on how to setup these.
```

2022-09-23 16:45 UTC, danielmarquespt reviewed
Added discord url

2022-09-26 09:26 UTC, malomarrec requested changes

2022-09-26 09:39 UTC, danielmarquespt commented on doc/getting-started/cloud-instance.md
> +[GitHub](https://docs.sourcegraph.com/admin/external_service/github)
Makes sense

2022-09-26 09:40 UTC, danielmarquespt commented on doc/getting-started/cloud-instance.md
> +## 👥 Inviting users and SSO
Included. And changed the order so that inviting single users comes after this

2022-09-26 09:40 UTC, danielmarquespt commented on doc/getting-started/cloud-instance.md
> +By default the Sourcegraph instance cannot send emails. So features like password resets, email invites and code monitors will not work
added

2022-09-26 09:40 UTC, danielmarquespt commented on doc/getting-started/cloud-instance.md
> +Sourcegraph is nothing without your code. So this is essential to harness the power of Sourcegraph and multiply the potential of your developer team
Good point. Made it more simple

2022-09-26 09:48 UTC, malomarrec approved these changes

2022-09-27 11:00 UTC, merged