Refactor use of oauth bearer token to match oauth terminology
sourcegraph/sourcegraph pull request #42234
Opened 2022-09-28 12:54 UTC by pjlast

This is a quick refactor to have the `OAuthBearerToken` be a complete OAuth token, and use it instead of having another separate implementation of the OAuth token spec.

## Test plan

Existing tests should work, it's a refactor.

2022-09-28 13:49 UTC, eseliger requested changes

2022-09-28 13:49 UTC, eseliger commented on internal/extsvc/auth/oauth_bearer.go
> +	AccessToken  string    `json:"access_token"`
changing this from `Token` to `access_token` will break unmarshalling existing tokens afaict.

2022-10-04 12:52 UTC, pjlast commented on internal/database/oauth_token_helper.go
>  		}()
@miveronese does it still make sense to have these `gitlab.TokenRefreshCounter` increments here?

2022-10-04 17:45 UTC, miveronese commented on internal/database/oauth_token_helper.go
>  		}()
I am not sure about the original context around starting exporting to Prometheus these types of metrics, so I would prefer to double-check with the Repo Management team if this was supposed to be a temporary thing or not.

2022-10-04 17:50 UTC, miveronese commented on internal/database/oauth_token_helper.go
> +		refreshedToken, err := oauthutil.RetrieveToken(doer, oauthCtx, refreshToken)
@unknwon , can you refresh my memory on why we needed this originally? I remember that it was necessary but the reason escaped my memory :D

2022-10-04 17:54 UTC, miveronese commented on internal/database/oauth_token_helper.go
>  		}()
My main concern here is if there's an alert that uses these metrics (or any Grafana dashboard that is fed with it). So removing them wold be risky.

2022-10-04 18:28 UTC, pjlast commented on internal/database/oauth_token_helper.go
>  		}()
I think they need to be factored out. These increments are specific to GitLab and will trigger for every refresh at the moment. So we'll have to trigger them in the GitLab client and not generically for every Auth provider

2022-10-04 19:42 UTC, miveronese commented on internal/database/oauth_token_helper.go
>  		}()
Agree -- these need to be moved in a way that they can be used by other auth providers not only GL

2022-10-04 21:47 UTC, miveronese commented
And update: I'm not sure if this was triggered by the recent commits such as the removal of AuthStyles or by something else, but the refresh stopped working for GL only. I will do some more tests later against previous versions to double-check my hypothesis and see what's wrong.

2022-10-05 11:32 UTC, pjlast commented
>Refresh_token can be an empty string when we get it from the config file (GL case). In that case, we should not return an error.

I don't think that's the correct conclusion. If the token is expired and no refresh token is present, that error should definitely be returned, or at least be treated as we would normally have treated an expired token

2022-10-05 13:34 UTC, pjlast commented
@miveronese I just converted the GitLab case to use the refresh interface, it was simple enough

2022-10-05 13:41 UTC, pjlast commented on internal/extsvc/auth/oauth_bearer.go
> +	AccessToken  string    `json:"access_token"`
@eseliger I worked through the code and marhsalling of existing tokens won't be affected. All tokens from `user_external_accounts` are unmarshalled into `oauth2.Token`s (and are already stored as `access_token`. And unmarshalling from `external_services` does not unmarshal into an `OAuthBearerToken` either

2022-10-05 13:48 UTC, eseliger commented on internal/extsvc/auth/oauth_bearer.go
> +	AccessToken  string    `json:"access_token"`
Batch changes stores OAuthBearerTokens as well, I think these would be affected

2022-10-05 13:55 UTC, pjlast commented on internal/extsvc/auth/oauth_bearer.go
> +	AccessToken  string    `json:"access_token"`
Ah, gotcha, I missed that context. Thanks

2022-10-17 14:34 UTC, closed without merging