internal/types: Add CloneStatusCorrupted
sourcegraph/sourcegraph pull request #42270
Opened 2022-09-29 00:06 UTC by indradhanush

Fixes #42212

## Test plan

Just a new option for the `clone_status` column of `gitserver_repos` table.
Baby steps on #42207.

Code is not used. Tests will follow in subsequent PRs.

2022-09-29 07:24 UTC, sashaostrikov approved these changes

2022-09-29 09:50 UTC, mrnugget requested changes
Why a new clone status vs. adding another column?

I'm asking because I think adding a new value to this enum takes more than just this change: we need to define how and when the state is set (essentially define the state machine again).

1. We'd also need to update `gitserver_repos_statistics` and add a new column and update these triggers https://github.com/sourcegraph/sourcegraph/blob/fe0284fc6f6cb6b400f7cd099f4d93a93b2257e8/migrations/frontend/squashed.sql#L435-L573
1. We'd need to revisit a lot of the places where we use `CloneStatusCloned` too: https://sourcegraph.sourcegraph.com/search?q=CloneStatusCloned&groupBy=repo

    Example: right now we set `clone_status = "cloned"` every time we recalculate the repository size. What if the repo is corrupted? Do we set the status to `"corrupted"` and then 5min later it flips back to `"cloned"` when we calculate the size?
3. Are `"corrupted"` repositories "purgable"? Right now only "cloned" repos are purgeable: https://github.com/sourcegraph/sourcegraph/blob/main/internal/database/gitserver_repos.go#L203
4. What about places like this that assume a repo doesn't exist if the status is not `"cloning"` or `"cloned"`? https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go?L203:32 Are they invalid with the introduction of `"corrupted"`? Should we treat `"corrupted"` repositories as existing?

So, "Request changes" here because these are all the questions I think we must answer before we introduce another state.

Otherwise thinks might break in unexpected ways, statistics are off, admin UI shows wrong data.

(Yes, adding _just_ this line doesn't break anything, but I don't think this line by itself is valuable enough and I'd rather want us to put the effort in to decide what this line should mean before we add it)

2022-09-29 21:47 UTC, mollylogue commented
I agree that maybe `clone_status` isn't the correct place for this (at least without a full audit of the system and everywhere that it's used).

2022-09-30 08:48 UTC, sanderginn commented
Came here via #thanks.

>What about places like this that assume a repo doesn't exist if the status is not "cloning" or "cloned"? https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/worker/internal/codeintel/indexing/dependency_indexing_scheduler.go?L203:32 Are they invalid with the introduction of "corrupted"? Should we treat "corrupted" repositories as existing?

Forgive me if the answer is obvious, I'm here to be educated. Is there a reason why this shouldn't be encapsulated in something akin to `info.RepoExists()`?

2022-09-30 09:10 UTC, mrnugget commented
> Is there a reason why this shouldn't be encapsulated in something akin to `info.RepoExists()`?

Nobody's done it yet :) I think I'd personally define something like that on the type itself, like `func (s RepoCloneStatus) Exists() bool { return s == RepoCloneStatusCloned || s == RepoCloneStatusCloning }` so it's all in the same place.

2022-09-30 09:44 UTC, mrnugget commented
> My thought is that either way, the complexity that comes with adding a new state / column here is unavoidable and between the two, a new state for `clone_status` is the better choice. What do you think?

Yeah, I agree. But as I wrote above: we need to be really careful about adding one and we (and our system) needs to know what the new state _means_. Example: if a repository is `cloning` we know that the next state it goes into is `cloned` or `not_cloned`, it doesn't go back into `""` (unknown).

Now we need to define what it means if a repository is `"corrupted"`: does it still exist on disk? what's the next state - `"not_cloned"` or `"cloning"`? Do we count `"corrupted"` repo's disk size towards overall usage? etc.

@pjlast and I touched on the same questions when he added the "reclone"-button to the UI. There's an endpoint in gitserver that allows you to reclone a repository by cloning it into a tmp-dir and then doing a rename to switch the clone in place -- what happens to the `clone_status` there? what happens if something fails?

And you provided one answer here:

> When I think about this, corrupted repos should be treated as existing because a repo corruption follows when we attempt to fetch on an existing repo. And if we encounter an error during cloning, we mark them as not_cloned and update the last_error column in the gitserver_repos table.

I agree with that. We should treat corrupted repos as existing. They still take up disk space, they might still work. So in practice this would mean if we add another column to `repo_statistics` and `gitserver_repos_statistics` to track `"corrupted"` then in the UI we should show under "cloned" the sum of `cloned + corrupted`.

That's the stuff we need to think through before adding a new value or a new column, which brings me to...

> 👉 The more I think about this as I attempt to answer all the questions above, the more confused I am. clone_status means (and should) if we were ever able to clone the repo or not. And updating it for subsequent fetch operations does not feel right.
Maybe we should introduce a new fetch_status column instead?

There's multiple possible answers to it :) Take a look [at this StackOverflow question and its answer](https://stackoverflow.com/questions/1404526/big-vs-nested-statemachines) to get a feel for how divided opinions are.

Some say "yeah, you can have one big state machine, with overlapping states" (which is what we'd have here if we were to add "corrupted" as a new value, right? A `clone_status = "corrupted"` or `clone_status = "fetching"` would mean that the repo has been `"cloned"` and still is, but now it's in this additional, overlapping state) and some say "multiple small state machines", which in our case could mean (purely for illustrative purposes here) that we add a `maintenance_status` column that has possible values `"ok", "gc-running", "corrupted", "fetching"` and our application logic would need to encode that `maintenance_status` can _only_ ever mean something if (and only if) `clone_status = "cloned"`.

I have to admit that my brain and state machines aren't the greatest match and I often struggle to see far down the road, so I can only say that _instinctively_ I lean towards multiple smaller state machines, but I can't give you a fully thought out "in this case, because of X and Y, you need one big machine vs. multiple smaller ones".

Maybe it's enough to say that it feels simpler to have non-overlapping states and to say that we keep `clone_status` as it is and add another column/state-machine to represent the states a repository can be in once `clone_status = "cloned"`. (That would allow us to represent the "reclone-in-tmp-dir" state I found with Petri accurately)

(As an example: take a look at `Changeset`, which has a bunch of different state machines: https://github.com/sourcegraph/sourcegraph/blob/41498108f0670193175fe99ad03b0658d93805c2/enterprise/internal/batches/types/changeset.go#L263-L285)

2022-09-30 22:55 UTC, indradhanush commented
Overall, the sense I am getting so far is that it is better to introduce another column instead of introducing more permutations to the `clone_status` state machine. This should also help us avoid bugs in the future where we fail to account for one of the options. I will go ahead and close this PR.

I'm OOO next week and can pick up the effort once I'm back.

2022-09-30 22:55 UTC, closed without merging