codeintel: Support bulk deletion of LSIF uploads
sourcegraph/sourcegraph pull request #42395
Opened 2022-09-30 23:00 UTC by chrismwendt

Resolves https://github.com/sourcegraph/sourcegraph/issues/41193

![CleanShot 2022-09-30 at 16 56 52@2x](https://user-images.githubusercontent.com/1387653/193367225-162ba582-db82-4cb1-863d-92053beae2a3.png)

## Test plan

Upload some LSIF dumps, visit http://localhost:3080/site-admin/code-graph/uploads, check/uncheck, delete, select matching, delete matching.

2022-10-02 13:50 UTC, efritz requested changes

2022-10-02 13:50 UTC, efritz commented on internal/database/migration/shared/upgradedata/stitched-migration-graph.json
> +					1657635365
🤔 

Seems like you have some lint in CI as well (and need to regenerate mocks). You should run `go generate ./...` in the root to fix these errors.

2022-10-02 13:52 UTC, efritz commented on internal/codeintel/uploads/internal/store/store_uploads.go
> +func (s *store) DeleteUploads(ctx context.Context, opts types.DeleteUploadsOptions) (err error) {
Can we get a unit test for this?

2022-10-02 13:52 UTC, efritz commented on internal/codeintel/uploads/internal/store/store_uploads.go
> +	defer unset(ctx)
<3

2022-10-02 13:54 UTC, efritz commented on client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadsPage.tsx
> +                            }
Would it be good idea (follow-up PR would be good too) to batch these into a single request?

2022-10-03 17:02 UTC, chrismwendt commented on client/web/src/enterprise/codeintel/uploads/pages/CodeIntelUploadsPage.tsx
> +                            }
Chatted in Zoom: it should be fast enough as-is, and we can batch it in a separate PR later if anyone notices it being slow.

2022-10-03 22:03 UTC, efritz approved these changes

2022-10-04 02:17 UTC, merged