[fix] Make "internal" gitlab repos behave like private repositories
sourcegraph/sourcegraph pull request #42424
Opened 2022-10-03 11:53 UTC by kopancek

fixes #41909

## Test plan

Added unit tests.

Tested manually against gitlab.sgdev.org.

1. Created an "internal" repository
2. Added 2 users to my local sg instance
3. Connected the gitlab.sgdev.org as an OAuth source and added external service with repo permissions syncing based on OAuth
4. Verified that
  a. Site admin can see the repository (site admins are godlike b*tches and can see everything)
  b. User who did not add Gitlab in Settings -> Account Security cannot search the repository
  c. User who added Gitlab in Settings -> Account Security can search the repository

2022-10-03 12:08 UTC, pjlast commented
This my require a change to how we fetch user perms: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/authz/gitlab/sudo.go?L227

The query only fetches Private repositories, but if internal repos are treated as Private now, they would have to be fetched as well

2022-10-03 15:40 UTC, miveronese approved these changes
Thanks for also sharing how you run/test if the query params are working. 🙏

2022-10-04 07:14 UTC, pjlast requested changes

2022-10-04 07:14 UTC, pjlast commented on enterprise/internal/authz/gitlab/sudo.go
> +	q.Add("visibility", "internal")
This doesn't quite work, the `visibility=internal` check overrides the `visibility=private` check. You can confirm by creating both a Private and an Internal repo. Only the Internal repo will show up with the parameters set like this. Not sure if there is an easy way that fetches both Internal and Private repos together

2022-10-04 09:34 UTC, kopancek commented on enterprise/internal/authz/gitlab/sudo.go
> +	q.Add("visibility", "internal")
fixed in the latest commit 🤞

2022-10-04 12:10 UTC, pjlast approved these changes

2022-10-04 12:44 UTC, merged