Update syntax-highlighter docker container
sourcegraph/sourcegraph pull request #42486
Opened 2022-10-04 09:00 UTC by olafurpg

Context https://sourcegraph.slack.com/archives/C022SPMNR0W/p1663771635349499

Fixes #41493

Previously, the single container deployment option used an old version of our syntax highlighter causing several new features to no longer work, including C# highligting and the new `"syntaxHighlighting"` site-config section.

## Test plan

Any advice on how to test this locally? I failed to run `docker build cmd/server` due to p4 errors.

2022-10-04 09:53 UTC, keegancsmith commented
There is some way using sg I think to trigger docker image builds in CI. You could then pull down the server docker image locally and test.

2022-10-04 11:54 UTC, mrnugget commented
> There is some way using sg I think to trigger docker image builds in CI.

`sg ci build docker-images-patch` (or: `sg ci build docker-images-patch-notest`) is what you want, I think

2022-10-04 13:17 UTC, jhchabran approved these changes

2022-10-04 13:17 UTC, jhchabran commented on docker-images/syntax-highlighter/Dockerfile
> +# TODO: the syntect_server binary is kept around for backwards compatibility
This makes me think we could have a code insight for these things.

2022-10-04 13:18 UTC, jhchabran commented
@olafurpg as the PR is up for review, I assume you ran your tests ?

2022-10-04 16:02 UTC, mrnugget commented on docker-images/syntax-highlighter/Dockerfile
> +# TODO: the syntect_server binary is kept around for backwards compatibility
Why is that necessary? Who still accesses the old binary?

Also, if you add the new binary, why not use it in the final `CMD` in this file?

2022-10-11 11:00 UTC, olafurpg commented
@jhchabran I haven't tested this change yet. The `sg ci build docker-images-patch` job failed in buildkite https://buildkite.com/sourcegraph/sourcegraph/builds/177072

Are you able to take over this PR? I don't feel comfortable merging and I'm not sure how to test this properly

2022-11-28 10:07 UTC, olafurpg commented
@jhchabran any chance somebody from #dev-experience could take over this PR? We will soon start using tree-sitter syntax highlighting for a lot more languages so that it won't be only C# that has broken highlighting by default for single-container deployments

2022-11-28 10:24 UTC, sanderginn commented
Hey @olafurpg, sorry for the lack of response here. We can take this over from you. Can you (roughly) specify 'soon', so that we can prioritise it accordingly?

2022-11-29 11:45 UTC, olafurpg commented
@sanderginn It would be nice if we can fix this before the next release. Worst case, the release after that.

2022-12-01 11:17 UTC, sanderginn commented on cmd/server/Dockerfile
> +COPY --from=docker.io/sourcegraph/syntax-highlighter:175652_2022-10-04_5ae1e4363e56 /syntect_server /usr/local/bin/
You're copying to `/syntect_server`, but the `CMD` targets `/syntax_highlighter` on L59

2022-12-01 11:23 UTC, sanderginn requested changes
Small fix required

2022-12-01 11:23 UTC, sanderginn commented on docker-images/syntax-highlighter/Dockerfile
> +RUN cp ./target/release/syntect_server /syntax-highlighter
```suggestion
RUN cp ./target/release/syntect_server /syntax_highlighter
```

Otherwise the `CMD` on L59 targets a nonexisting directory

2022-12-01 11:23 UTC, sanderginn commented on cmd/server/Dockerfile
> +COPY --from=docker.io/sourcegraph/syntax-highlighter:175652_2022-10-04_5ae1e4363e56 /syntect_server /usr/local/bin/
Shouldn't this copy `/syntax_highlighter` instead?

2022-12-01 12:33 UTC, sanderginn commented on cmd/server/Dockerfile
> +COPY --from=docker.io/sourcegraph/syntax-highlighter:175652_2022-10-04_5ae1e4363e56 /syntect_server /usr/local/bin/
@davejrt not sure if I can approve yet – can you shed some light on this question?

2022-12-01 12:35 UTC, sanderginn commented on cmd/server/Dockerfile
> +COPY --from=docker.io/sourcegraph/syntax-highlighter:175652_2022-10-04_5ae1e4363e56 /syntect_server /usr/local/bin/
Oh sorry your initial comment wasn't loading for me yet 🤦‍♂️

2022-12-01 12:36 UTC, sanderginn commented on cmd/server/Dockerfile
> +COPY --from=docker.io/sourcegraph/syntax-highlighter:175652_2022-10-04_5ae1e4363e56 /syntect_server /usr/local/bin/
Did not need more clarification than that

2022-12-01 12:36 UTC, sanderginn approved these changes

2022-12-01 14:02 UTC, merged

2022-12-01 16:08 UTC, bobheadxi commented
@olafurpg the container is no longer starting in s2:

```
2022/12/01 16:07:22 worker command: env ROCKET_PORT={{.Port}} /syntax_highlighter
2022/12/01 16:07:22 worker 13: started on port 44717
2022/12/01 16:07:22 worker 15: started on port 44503
2022/12/01 16:07:22 worker 17: started on port 45385
2022/12/01 16:07:22 worker 13: env: can't execute '/syntax_highlighter': No such file or directory
2022/12/01 16:07:22 worker 15: env: can't execute '/syntax_highlighter': No such file or directory
2022/12/01 16:07:22 worker 17: env: can't execute '/syntax_highlighter': No such file or directory
2022/12/01 16:07:22 worker 18: started on port 45649
2022/12/01 16:07:22 worker 18: env: can't execute '/syntax_highlighter': No such file or directory
```

2022-12-01 16:15 UTC, olafurpg commented
@bobheadxi Can you please investigate this issue? I'm only working 15hr/week these days and on irregular hours

2022-12-01 16:22 UTC, sanderginn commented
@bobheadxi seems to me like [L32](https://github.com/sourcegraph/sourcegraph/blob/main/docker-images/syntax-highlighter/Dockerfile#L32) needs to copy `syntax_highlighter` still. Do you agree?

2022-12-01 16:24 UTC, bobheadxi commented
Looks like it, Noah mentioned similarly here: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1669911191464239?thread_ts=1669910986.795149&cid=CHXHX7XAS

2022-12-01 16:29 UTC, bobheadxi commented
https://github.com/sourcegraph/sourcegraph/pull/45000