security: update go version in asdf to 1.18.7
sourcegraph/sourcegraph pull request #42549
Opened 2022-10-05 08:32 UTC by burmudar

Update go version to latest security release see https://groups.google.com/g/golang-announce/c/xtuG5faxtaU
## Test plan
Green CI

2022-10-05 08:47 UTC, jhchabran requested changes
Good call to update this 🙏

2022-10-05 08:47 UTC, jhchabran commented on .tool-versions
> +golang 1.18.7
We need to update the check in `sg` as well :) 

https://github.com/sourcegraph/sourcegraph/commit/cc3010911fb4093c71236a78cd72f7767630e92d#diff-d6971f9b789dfaad28401bbb466beee887d64bb586d8bb9e2bc0567136e5cdbdR38

2022-10-05 08:48 UTC, burmudar commented on .tool-versions
> +golang 1.18.7
Good spot! Lemme update that 🚒

2022-10-05 09:40 UTC, burmudar commented
For future reference - I tried updating to `1.19.7` and there were about 3 test failures which don't seem like a lot of work to update https://buildkite.com/sourcegraph/sourcegraph/builds/175939#0183a76f-d17a-4eff-9f2a-4cc227881969

2022-10-06 14:51 UTC, jhchabran approved these changes

2022-10-06 14:52 UTC, merged