Update MAUs
sourcegraph/sourcegraph pull request #42640
Opened 2022-10-06 14:12 UTC by thenamankumar

Closes: https://github.com/sourcegraph/sourcegraph/issues/42598

- [x] Add percentage, total numbers toggle for frequency of day use
- [x] Move BuildFrequencyDatums to backend
- [ ] Track only registered users for MAUs & frequency of day use. (currently based on anonymous id)
- [x] Change "Average DAU/WAU/MAU for the date range" chart to show MAUs for last 3 months. @rrhyne should we take 3 months before current month?
- [ ] Add display as monthly option for the User Activities chart. 
- [ ] [Exclude event types](https://sourcegraph.slack.com/archives/C03JNPY7V3L/p1660795181951239)

2022-10-07 11:42 UTC, mrnugget requested changes
Requesting changes because I think the code can be cleaned up and simplified a bit and I'd love to see at least one test that makes sure the SQL works.

2022-10-07 11:42 UTC, mrnugget commented on internal/adminanalytics/users.go
> +func (f *Users) Maus(ctx context.Context) ([]*UsersMAUNode, error) {
```suggestion
func (f *Users) MonthlyActiveUsers(ctx context.Context) ([]*UsersMAUNode, error) {
```

2022-10-07 11:42 UTC, mrnugget commented on internal/adminanalytics/users.go
> +	return fmt.Sprintf("%d-%d", prevYear, int(prevMonth))
This whole function can be replaced with this, no?

```go
func getPrevMonth(now time.Time, prev int) string {
	d := now.AddDate(0, prev, 0)
	return fmt.Sprintf("%d-%d", d.Year(), d.Month())
}
```

2022-10-07 11:42 UTC, mrnugget commented on internal/adminanalytics/users.go
> +		AND TO_CHAR(timestamp, 'YYYY-MM') IN (%s)
Using a string here feels hacky to me. Why not `EXTRACT(MONTH FROM timestamp) = %s AND `EXTRACT(YEAR FROM timestamp)`?

2022-10-07 11:42 UTC, mrnugget commented on internal/adminanalytics/users.go
> +	}
```suggestion
	months := []*sqlf.Query{
		sqlf.Sprintf("%s", getPrevMonthString(now, 2)),
		sqlf.Sprintf("%s", getPrevMonthString(now, 1)),
		sqlf.Sprintf("%s", getPrevMonthString(now, 0)),
	}
```

2022-10-07 11:42 UTC, mrnugget commented on internal/adminanalytics/users.go
> +type UsersMAUNode struct {
`Node` seems a bit out of place when talking about database rows.

```suggestion
type MonthlyActiveUsersRow struct {
```

2022-10-07 11:42 UTC, mrnugget commented on internal/adminanalytics/users.go
> +func (f *Users) Maus(ctx context.Context) ([]*UsersMAUNode, error) {
There's 0 tests for this and it's a lot of complex SQL and date handling. Please add a least 2-3 high-level tests that make sure the results are correct.

See this test I added recently for how to add some events to the database and then test on top of it. I think in your case here I'd write a test that has 3-4 users with events over 13 months (so it crosses a year boundary) and then make sure that the monthly-active-users are reported correctly for each month. (you might have to change the code here to take `now time.Time` as a parameter so you can change it in tests and then add another public method that passes `time.Now()` in)

2022-10-07 11:42 UTC, mrnugget commented on internal/adminanalytics/users.go
> +		if err := rows.Scan(&data.Date, &data.Count); err != nil {
Can `basestore.NewSliceScanner` help? See https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/repo_kvps.go?L74-77

2022-10-07 12:32 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +			COUNT(date) AS days_used
yeah we can do `count(distinct date)`. will update.

2022-10-07 12:37 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +	return fmt.Sprintf("%d-%d", prevYear, int(prevMonth))
Because https://pkg.go.dev/time#Time.AddDate

```
AddDate normalizes its result in the same way that Date does, so, for example, adding one month to October 31 yields December 1, the normalized form for November 31. 
```

Just wanted to avoid the possible magic.

2022-10-07 12:39 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +		AND TO_CHAR(timestamp, 'YYYY-MM') IN (%s)
for 3 months that makes it 6 variables to be passed in exact order.

2022-10-07 12:52 UTC, mrnugget commented on internal/adminanalytics/users.go
> +	return fmt.Sprintf("%d-%d", prevYear, int(prevMonth))
Then I'd expect a docstring and tests to test exactly that.

2022-10-07 13:03 UTC, mrnugget commented on internal/adminanalytics/users.go
> +		AND TO_CHAR(timestamp, 'YYYY-MM') IN (%s)
Why not build a start and end date then and check that `timestamp >= startDate AND timestamp <= endDate`?

Or just pass in 1 date and calculate the interval in SQL?

```sql
select id, timestamp from event_logs where timestamp >= (now() - '3 months'::interval) and timestamp <= now();
```

If you use the strings method like this, the database won't use any index, because it has to calculate the string for every event_log row in the table.

I just tested on production:

```sql
-- BAD: this takes ~10s to run on sourcegraph.com
select count(*) from event_logs where TO_CHAR(timestamp, 'YYYY-MM') IN ('2022-08', '2022-09', '2022-10');
-- BETTER: this takes ~2s to run on sourcegraph.com
select count(*) from event_logs where timestamp >= '2022-08-01'::timestamp and timestamp <= now();
```

2022-10-07 13:07 UTC, mrnugget commented on internal/adminanalytics/users.go
> +		AND TO_CHAR(timestamp, 'YYYY-MM') IN (%s)
This is also slow, btw.:

```sql
select count(*) from event_logs
where (extract(year from timestamp) = 2022 AND extract(month from timestamp) = 8)
OR (extract(year from timestamp) = 2022 AND extract(month from timestamp) = 9)
OR (extract(year from timestamp) = 2022 AND extract(month from timestamp) = 10);
```

So I'd really try to make use of that btree index on `timestamp` and have a range.

2022-10-10 10:31 UTC, erzhtor commented on client/web/src/site-admin/analytics/AnalyticsCodeInsightsPage/index.tsx
>                  description: aggregation.selected === 'count' ? 'Insight hovers' : 'Users hovering insights',
In the legend tooltip (description), we say "Users hovering insights", so it kinda confuses, because `totalUniqueUsers` is still based on `anonynous_user_id` (aka device id) and not the user. I think we either should leave it as is using `totalRegisteredUsers` or update the tooltip. The same applies in all other changes to `totalRegisteredUsers` to `totalUniqueUsers`.

2022-10-10 10:31 UTC, erzhtor commented on internal/adminanalytics/utils.go
> +}
I think we already have it defined in https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/eventlogger/event_logger.go?L24:5

2022-10-10 13:06 UTC, thenamankumar commented on client/web/src/site-admin/analytics/AnalyticsCodeInsightsPage/index.tsx
>                  description: aggregation.selected === 'count' ? 'Insight hovers' : 'Users hovering insights',
@erzhtor if you check the diff, I have updated the `totalUniqueUsers` to be based on `user_id` and not `anonymoyus_id`. That is exactly the same way, the analytics team use it in looker and used for billing as well.


One thing which got missed earlier was, on user deletion, when the user_id is set to 0 and anonymous_id for all the event logs for that user is also updated to a common newly generated uuid. So for a deleted user the anonymous id will be common for all the logs irrespective of the device or browser. 

That is why now we are using `CASE WHEN user_id = 0 THEN anonymous_user_id ELSE CAST(user_id AS TEXT) END` in place of aggregating based on `anonymous_id`. 

 https://github.com/sourcegraph/sourcegraph/pull/42640/files#diff-fab5526857e504bb95c14f75a8dc4d66e9413595484f6e6a321c28c7b2cb34b7R54

2022-10-10 13:16 UTC, erzhtor commented on client/web/src/site-admin/analytics/AnalyticsCodeInsightsPage/index.tsx
>                  description: aggregation.selected === 'count' ? 'Insight hovers' : 'Users hovering insights',
> `CASE WHEN user_id = 0 THEN anonymous_user_id ELSE CAST(user_id AS TEXT)`
Yep, I have seen this in the diff, and it still uses deleted users's device id, that was my question. Are we ok with it? When users is deleted each of their devices/browsers become a unique user count. I remember we specifically avoided using `totalUniqueUsers` for that reason.

2022-10-10 13:22 UTC, thenamankumar commented on client/web/src/site-admin/analytics/AnalyticsCodeInsightsPage/index.tsx
>                  description: aggregation.selected === 'count' ? 'Insight hovers' : 'Users hovering insights',
> > `CASE WHEN user_id = 0 THEN anonymous_user_id ELSE CAST(user_id AS TEXT)`
> > Yep, I have seen this in the diff, and it still uses deleted users's device id, that was my question. Are we ok with it? When users is deleted each of their devices/browsers become a unique user count. I remember we specifically avoided using `totalUniqueUsers` for that reason.

Each of their devices/browsers doesn't become a unique user count. Even after deletion if we count over anonymous_id it will count 1 deleted user as 1 irrespective of the device. 

Because: https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/internal/database/users.go?L619:39

all the different anonymous_id for that deleted user are updated to common uuid on deletion.

2022-10-10 13:44 UTC, erzhtor commented on client/web/src/site-admin/analytics/AnalyticsCodeInsightsPage/index.tsx
>                  description: aggregation.selected === 'count' ? 'Insight hovers' : 'Users hovering insights',
Oh, got it, I thought that anonymous_user_id remans the same after deletion. Nice! Thanks for clarifying!

2022-10-10 13:45 UTC, erzhtor approved these changes

2022-10-10 18:31 UTC, rrhyne approved these changes
I can't really comment on all the code here, but the discussion I'm seeing seems to be on the right track, so approved, for what it's worth.

2022-10-10 19:39 UTC, thenamankumar commented
> I can't really comment on all the code here, but the discussion I'm seeing seems to be on the right track, so approved, for what it's worth.

Did you take a look at the loom video? I monthly wanted you to check the design there.

2022-10-10 20:24 UTC, rrhyne commented
Yeah, looks fine.  

One thought I just had re-watching though... perhaps we add the deleted users beside the registered user count in the secondary KPIs on the right to help people realize where active users could be higher without having to read both tooltips to put it together?

2022-10-11 16:36 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +		AND TO_CHAR(timestamp, 'YYYY-MM') IN (%s)
I'll update it to use start end

2022-10-11 17:44 UTC, thenamankumar commented on internal/adminanalytics/utils.go
> +}
reused from there.

2022-10-11 17:44 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +type UsersMAUNode struct {
updated

2022-10-11 17:45 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +		AND TO_CHAR(timestamp, 'YYYY-MM') IN (%s)
used from, now for where clause. still need to group on date part.

2022-10-11 17:46 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +func (f *Users) Maus(ctx context.Context) ([]*UsersMAUNode, error) {
updated

2022-10-11 17:46 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +	if f.Cache == true {
updated

2022-10-11 17:46 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +func getPrevMonthString(now time.Time, prev int) string {
updated

2022-10-11 17:46 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +			COUNT(date) AS days_used
updated

2022-10-11 17:46 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/schema.graphql
> +  year-month
updated

2022-10-11 17:47 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/schema.graphql
> +type AnalyticsUsersMAU {
updated

2022-10-11 17:47 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/schema.graphql
> +    maus: [AnalyticsUsersMAU!]!
updated

2022-10-12 09:02 UTC, thenamankumar commented on internal/adminanalytics/users.go
> +func (f *Users) Maus(ctx context.Context) ([]*UsersMAUNode, error) {
Added tests

2022-10-12 09:03 UTC, thenamankumar commented
@mrnugget addressed the feedback and added tests

2022-10-12 09:38 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.42 kb) | 0.00% (+0.42 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/naman/ipa-4.1/compare-report.html;tab=live_object) for a full comparison between the commits bb152f2 and 94f0fe3 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-10-12 12:25 UTC, mrnugget approved these changes

2022-10-12 12:25 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +  year-month for which the total active users are calculated
Maybe provide an example of a value here, since `year-month` could be `2022-05` or `22-5` or.. wow, maybe even `22-october`.

2022-10-12 12:25 UTC, mrnugget commented on internal/adminanalytics/cache.go
> +}
Please let's not 😄 

Instead do this:

1. Add a global var here: `var cacheDisabledInTest = false`
2. Add a `func init() { cacheDisabledInTest = true }` to a *test file*. See examples: https://sourcegraph.sourcegraph.com/search?q=init%28%29+file%3A_test.go&groupBy=repo

2022-10-12 12:25 UTC, mrnugget commented on internal/adminanalytics/users_test.go
> +		t.Fatal(fmt.Sprintf("only %d nodes returned", len(results)))
```suggestion
		t.Fatalf("only %d nodes returned", len(results))
```

2022-10-12 12:25 UTC, mrnugget commented on internal/adminanalytics/users_test.go
> +}
Thanks for adding these tests! Greatly appreciated!

2022-10-12 15:45 UTC, thenamankumar commented on internal/adminanalytics/users_test.go
> +		t.Fatal(fmt.Sprintf("only %d nodes returned", len(results)))
updated

2022-10-12 15:45 UTC, thenamankumar commented on internal/adminanalytics/cache.go
> +}
updated

2022-10-12 16:49 UTC, merged