Add optional switch for disabling custom git fetch
sourcegraph/sourcegraph pull request #42704
Opened 2022-10-07 14:54 UTC by evict

Disable custom git fetch through an environment variable

## Test plan

- [ ] ci tests
- [ ] manual review

2022-10-07 20:17 UTC, daxmc99 commented on cmd/gitserver/server/customfetch.go
> +var disableCustomGitFetch = env.Get("DISABLE_CUSTOM_GIT_FETCH", "false", "Disable custom git fetch")
I think we should switch to `ENABLE_CUSTOM_GIT_FETCH`. This feature should be disabled by default imo

2022-10-07 20:18 UTC, daxmc99 requested changes
This also needs to be mentioned in our `CHANGELOG.md` file

2022-10-07 22:38 UTC, DaedalusG requested changes
This is a much better approach than mounting a json file with the repo to fetch mapping 👍 
I do agree with Dax, probably better to have it disabled by default. Branched and switched the booleans -- PR: https://github.com/sourcegraph/sourcegraph/pull/42723

2022-10-10 17:33 UTC, daxmc99 approved these changes
LGTM, I'll defer to @DaedalusG to get customer feedback on this. We should inform them of this change prior to the release so they aren't blindsided

2022-10-10 17:33 UTC, daxmc99 commented on cmd/gitserver/server/customfetch_test.go
> +	remoteURL, _ := vcs.ParseURL(remoteUrl)
```suggestion
	remoteURL, err := vcs.ParseURL(remoteUrl)
```
Why are we swallowing the err here?

2022-10-12 03:17 UTC, valerybugakov commented on cmd/gitserver/server/customfetch.go
>  		return map[string][]string{}
Would it be helpful for customers to see a warning in logs in case `c != nil && enableCustomGitFetch == "false"`? 

It would make the potential misconfiguration more visible: the site configuration has a `customGitFetch`, but the `ENABLE_CUSTOM_GIT_FETCH` environment variable is not set to `true`.

2022-10-12 09:20 UTC, evict commented on cmd/gitserver/server/customfetch.go
>  		return map[string][]string{}
Thanks, I agree it would be helpful for customers. Especially now we are changing this feature. I've added a `WARNING` if this happens. Since this is an edge case that should rarely occur, I think it's fine to initiate the logger here. Do you agree @daxmc99?

2022-10-12 09:22 UTC, evict commented on cmd/gitserver/server/customfetch_test.go
> +	remoteURL, _ := vcs.ParseURL(remoteUrl)
The URLs are statically configured, I think that's why in the original tests it's ignored. Do you think it is better to add `err` handling?

2022-10-13 18:23 UTC, daxmc99 commented on cmd/gitserver/server/customfetch.go
>  		return map[string][]string{}
I think a warning here would be a great idea

2022-10-13 18:35 UTC, daxmc99 approved these changes
LGTM! This approach makes sense. 
One last note is that the large diff here seems to be due to some auto-formatting running over the JSON. Might want to regen the schema again to avoid this.

2022-10-14 09:06 UTC, merged

2022-11-22 04:10 UTC, amieroth reviewed
All good on my side.