sg: make bg tasks less intrusive
sourcegraph/sourcegraph pull request #42830
Opened 2022-10-11 17:23 UTC by jhchabran

In some contexts, having the final ✅  printed by the background task succeeding is very confusing as it makes you think your command worked whereas it did not. 

See https://sourcegraph.slack.com/archives/C01N83PS4TU/p1665478325331859

## Test plan

2022-10-11 18:28 UTC, marekweb commented
Nice, this will also help mitigate the complaint that was raised in #42029, on those skipped short-lived commands

2022-10-11 18:41 UTC, marekweb approved these changes

2022-10-11 19:15 UTC, bobheadxi requested changes
I think we should just never leave any output from background jobs - including the "waiting for..." message. Maybe leave it on in verbose mode?

Right now the command also waits for the update to complete - it might be confusing for to have the command wait for the update to complete with no indication as to what is going on, which is why the output is there. An alternative would be to have the message only print if the job isn't done in X seconds, for example

Note that IMO we _should_ wait for the update to complete in most cases, rather than cancelling immediately

2022-10-11 19:15 UTC, bobheadxi commented on dev/sg/internal/background/background.go
> -	out.WriteLine(output.Line(output.EmojiSuccess, output.StyleSuccess, "Background jobs done!"))
Should we leave this in verbose mode?

Also, isn't this confusing if we print the progress ("waiting for...") and then never have an indicator that it finished?

2022-10-11 19:15 UTC, bobheadxi commented on dev/sg/main.go
> +		}
Nice 😁

2022-10-12 05:13 UTC, jhchabran commented on dev/sg/internal/background/background.go
> -	out.WriteLine(output.Line(output.EmojiSuccess, output.StyleSuccess, "Background jobs done!"))
Isn't your program finishind with exit 0 the most obvious signal it finished without error? It feels actually quite natural and that's how most CLI program behave.

2022-10-12 05:17 UTC, jhchabran commented
@bobheadxi since we're talking about ideal behaviour, I'd much prefer for our background task code to simply stop as soon as `sg` exits. Good call on silencing everything unless in verbose mode.

2022-10-12 05:29 UTC, bobheadxi commented on dev/sg/internal/background/background.go
> -	out.WriteLine(output.Line(output.EmojiSuccess, output.StyleSuccess, "Background jobs done!"))
Yes, but even in CLIs if a progress start indicator is shown it's a bit strange if it isn't "closed"? At least within sg most progress start indicators are accompanied with a "done"-style message

Also, an sg command can exit with non-zero status codes even if the background job completes successfully, so status 0 is not a reliable indicator here

2022-10-12 05:32 UTC, bobheadxi commented
> I'd much prefer for our background task code to simply stop as soon as sg exits

This would make it quite difficult for `sg` to update in the background, except with very long-running commands like `sg start` 🤔 For context, the initial implementation of auto-updates would prevent you from doing _anything_ until an update completes, which is why we prioritize completing updates today

2022-10-12 08:55 UTC, mrnugget commented
> This would make it quite difficult for `sg` to update in the background, except with very long-running commands like `sg start` 🤔 For context, the initial implementation of auto-updates would prevent you from doing _anything_ until an update completes, which is why we prioritize completing updates today

I think that makes sense though. Every other app - from Docker, to CleanShot X, to macOS App Store - quits its background tasks when I quit the program. They don't halt and say "wait a second until we're done doing this thing that you didn't ask us to do..."

2022-10-13 08:44 UTC, mrnugget approved these changes

2022-10-13 08:44 UTC, mrnugget commented on dev/sg/internal/background/background.go
> +				out.WriteLine(output.Line(output.EmojiSuccess, output.StyleSuccess, "Background jobs done!"))
You're now printing this once for every job -- is that the intention? I'd personally move it out of the loop

2022-10-13 08:44 UTC, mrnugget commented on dev/sg/main.go
> +		}
Can you somehow make sure that this also doesn't run when you get help output?

2022-10-13 12:35 UTC, jhchabran commented on dev/sg/internal/background/background.go
> -	out.WriteLine(output.Line(output.EmojiSuccess, output.StyleSuccess, "Background jobs done!"))
That's why it now never prints anything unless you're in verbose mode, making it consistent.

2022-10-13 12:36 UTC, jhchabran commented on dev/sg/main.go
> +		}
Yes, the reason for which `help` is not in there is exactly because it's not ran, I checked for it when making this change.

2022-10-13 12:37 UTC, jhchabran commented on dev/sg/internal/background/background.go
> +				out.WriteLine(output.Line(output.EmojiSuccess, output.StyleSuccess, "Background jobs done!"))
Woops my bad.

2022-10-13 12:51 UTC, merged