dev/sg: update 'sg rfc' with new RFC terms, modernize command
sourcegraph/sourcegraph pull request #42893
Opened 2022-10-12 17:45 UTC by bobheadxi

## Test plan

2022-10-12 17:46 UTC, bobheadxi commented
Current dependencies on/for this PR:
* main
  * **PR #41579** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/41579" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #42893** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/42893" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/42893?utm_source=stack-comment).

2022-10-12 17:50 UTC, burmudar approved these changes
Ahhh man. This is so nice! Thanks

2022-10-12 17:52 UTC, burmudar requested changes
@bobheadxi did you mean to merge into the gcloud secrets PR? Main has some other changes which splits the rfc into beong able to search public and private rfcs

2022-10-12 17:53 UTC, michaellzc approved these changes
lgtm

2022-10-12 17:54 UTC, michaellzc commented
unrelated comment regarding search result quality

```sh
go run ./dev/sg rfc search 'private terraform' | wc -l                                                                                                                                                                                                                  10:53:12
     108
```

looks like `queryRFC` is trying to match stuff from both title and body , so there is a lot of noise

2022-10-12 18:09 UTC, bobheadxi commented
> did you mean to merge into the gcloud secrets PR? Main has some other changes which splits the rfc into beong able to search public and private rfcs

Yes, I didn't want to conflict with your changes - I've stacked this PR on top of yours :)

2022-10-12 18:10 UTC, bobheadxi commented
> looks like queryRFC is trying to match stuff from both title and body , so there is a lot of noise

Yeah a next step could be to configure the query with flags (`--title` maybe, and I think a `description` field is also available - I see in one of your docs @michaellzc you have `#cloud` in it, but that's the only usage I've seen)

2022-10-12 18:15 UTC, michaellzc commented
> > looks like queryRFC is trying to match stuff from both title and body , so there is a lot of noise
> 
> Yeah a next step could be to configure the query with flags (`--title` maybe, and I think a `description` field is also available - I see in one of your docs @michaellzc you have `#cloud` in it, but that's the only usage I've seen)

I was playing around with the search in GDrive and see if it can pick up stuff in the doc description

 Label is actually a separate feature and needs #it-tech-ops to enable it https://support.google.com/a/answer/9292382?hl=en

2022-10-13 08:41 UTC, mrnugget approved these changes

2022-10-13 12:25 UTC, burmudar approved these changes

2022-10-13 16:03 UTC, bobheadxi commented on dev/sg/internal/rfc/rfc.go
> +	FolderID:    "1KCq4tMLnVlC0a1rwGuU5OSCw6mdDxLuv",
cc @sanderginn I think this is folder ID - using this for the link (see the new generated `Description`) points to the folder, I'm guessing the confusion comes from using it in the `parents in '%s'` query, which says "look for files with parent $ID", which in this case is a folder ID

2022-10-13 18:09 UTC, merged