docs/update add GCE custom image deployment type
sourcegraph/sourcegraph pull request #42911
Opened 2022-10-13 00:13 UTC by abeatrix

Close: https://github.com/orgs/sourcegraph/projects/290

This PR adds GCE custom image deployment type to docs.

Pipeline for creating GCE images automatically can be found in https://github.com/sourcegraph/deploy/commit/4e8f722ceccc41a829eec1d07827868c1e42a2e3

All GCE image files are stored in the Storage bucket under `Sourcegraph AMI project`

These images pull the latest helm charts when users first launch their instance initially.

![image](https://user-images.githubusercontent.com/68532117/195469825-bf89ec50-da1c-40b8-b750-d384498e885f.png)

![image](https://user-images.githubusercontent.com/68532117/195469938-e589cb29-cd63-440e-835d-75a0ab3eac05.png)

## Test plan

run `yarn docsite:serve` to see build locally

2022-10-18 21:56 UTC, jjeffwarner commented on doc/admin/deploy/images/gce.md
> +3. Copy the **URL**
From the three vertical dots, a Copy Authenticated URL and pasting it into the Cloud Storage File didn't work. Also a browser copy on the .tar.gz file in the bucket window didn't work either. I ended up using the `BROWSE` button in the Cloud Storage file input field to find it.

2022-10-19 22:26 UTC, abeatrix commented on doc/admin/deploy/images/gce.md
> +3. Copy the **URL**
Updated steps to reflect this, thanks for catching that @jjeffwarner !

2022-10-21 15:09 UTC, jdpleiness commented on doc/admin/deploy/index.md
> +To start, you will need to decide your on deployment method, including Kubernetes with or without Helm, as they are noninterchangeable it. In short, you **cannot** change your deployment type of a ru
```suggestion
To start, you will need to decide your on deployment method, including Kubernetes with or without Helm, as they are noninterchangeable. In short, you **cannot** change your deployment type of a running instance.
```

2022-10-21 15:10 UTC, jdpleiness commented on doc/admin/deploy/index.md
> +For more information, follow the install and configuration docs for your specific deployment type.
```suggestion
For more information, follow the installation and configuration docs for your specific deployment type.
```

2022-10-21 15:11 UTC, jdpleiness commented on doc/admin/deploy/index.md
> +Configuration at the deployment level focuses on ensuring your Sourcegraph runs optimally, based on the size of your repositories and the number of users. Configuration options will vary based on the
```suggestion
Configuration at the deployment level focuses on ensuring your Sourcegraph deployment runs optimally, based on the size of your repositories and the number of users. Configuration options will vary based on the type of deployment you choose. Consult the specific configuration deployment sections for additional information.
```

2022-10-21 15:15 UTC, jdpleiness commented on doc/admin/deploy/machine-images/gce.md
> +2. Nevigate to [Google Cloud Storage](https://console.cloud.google.com/storage) and select a project where you will store the image and deploy the instance in
```suggestion
2. Navigate to [Google Cloud Storage](https://console.cloud.google.com/storage) and select a project where you will store the image and deploy the instance in
```

2022-10-21 15:43 UTC, jdpleiness requested changes
Awesome work 😄 

I am wondering about the clarity of our instance sizing chart however. Perhaps we should add ranges to it? For example: 
|                  | **XS**     | **S**       | **M**       | **L**       | **XL**      |
|------------------|------------|-------------|-------------|-------------|-------------|
| **Users**        | 500  - 1,000       | 1,000 - 5,000      | 5,000 - 10,000      | 10,000  - 20,000    | 20,000+      |
| **Repositories** | 5,000 - 10,000     | 10,000 - 50,000    | 50,000 - 100,000     | 100,000 - 250,000    | 250,000+     |
| **Series**       | N2         | N2          | N2          | N2          | N2          |

2022-10-21 15:43 UTC, jdpleiness commented on doc/admin/deploy/machine-images/gce.md
> +4. Under the **Boot disk** section, click **CHANGE** and nevigate to the **CUSTOM IMAGES** tab
```suggestion
4. Under the **Boot disk** section, click **CHANGE** and navigate to the **CUSTOM IMAGES** tab
```

2022-10-21 15:43 UTC, jdpleiness commented on doc/admin/deploy/machine-images/gce.md
> +Your can also switch user in the terminal with the command below:
```suggestion
Your can also switch users in the terminal with the command below:
```

2022-10-21 15:43 UTC, jdpleiness commented on doc/admin/deploy/machine-images/gce.md
> +If you fall between two sizes, choose the larger of the two. For example, if you have 8,000 users with 80,000 repositories, your instance size would be **M**. If you have 1,000 users with 80,000 repo
Wouldn't a deployment with 8,000 users and 80,000 repositories choose a **L** according to this chart?

2022-10-21 15:43 UTC, jdpleiness commented on doc/admin/deploy/machine-images/gce.md
> +2. Nevigate to your instance console after your instance is stopped
```suggestion
2. Navigate to your instance console after your instance is stopped
```

2022-10-21 16:41 UTC, abeatrix commented on doc/admin/deploy/machine-images/gce.md
> +If you fall between two sizes, choose the larger of the two. For example, if you have 8,000 users with 80,000 repositories, your instance size would be **M**. If you have 1,000 users with 80,000 repo
Ohhh nice catch!!!!

2022-10-21 17:12 UTC, jdpleiness approved these changes

2022-10-21 17:13 UTC, abeatrix commented
@jdpleiness Good point! I have updated the range to `<=` to keep the table within page width as discussed 😄 Thank you so much!!

![image](https://user-images.githubusercontent.com/68532117/197251521-3df3a3b2-e08a-44c9-a191-6b4c20e0f8f1.png)

2022-10-21 17:23 UTC, merged