executors: Support bash syntax when available
sourcegraph/sourcegraph pull request #43046
Opened 2022-10-17 13:28 UTC by eseliger

Executors for now ran commands as scripts in sh only, this adds support for bash as well. This is something that we supported in batch changes forever due to customer feedback. In batch changes, we used an approach where we would run the container with `/bin/bash mktemp` and then `/bin/sh mktemp` to determine which shell is available. I think this approach is actually nicer, because it
- respects the PATH setting in the container for bash
- doesn't require up to 2 additional container boots before the actual command can be run

## Test plan

Verified locally that things still work as expected and that bash detection is reliable.

2022-10-17 13:57 UTC, efritz commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +# Only on the first run, check if we can upgrade to bash.
Should we also check for ksh, zsh, fish, etc...

2022-10-17 13:57 UTC, efritz approved these changes

2022-10-17 13:59 UTC, eseliger commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +# Only on the first run, check if we can upgrade to bash.
Good question, we _might_ but then we also have to determine an order of precedence for those. For src-cli we so far said no to that, and you can still run `fish -c my command` if you really need to.
Do you feel strongly about that?

2022-10-17 14:19 UTC, eseliger commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +  else
I am no shell or linux expert by any means, but err codes are propagated correctly here, is there anything else I am not considering that might break when bash is not the root process?

2022-10-18 08:51 UTC, BolajiOlajide approved these changes

2022-10-21 20:11 UTC, LawnGnome requested changes
I think we need to address the `which` issue before merging, but this seems OK otherwise.

2022-10-21 20:11 UTC, LawnGnome commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +  bash_path=$(which bash)
Today's installment of "Adam knows things he wishes he didn't": `which` isn't guaranteed to be available. (For example, it's not in the base `fedora` image.)

Instead, how about:

```suggestion
  bash_path=$(command -p -v bash)
```

2022-10-21 20:11 UTC, LawnGnome commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +  else
I think this is OK, but it might be cleaner to `exec "${bash_path}" "$0" skip-check` instead, in which case the process is simply replaced and the `exit` is unnecessary.

2022-10-24 08:28 UTC, courier-new commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +  bash_path=$(which bash)
For the unenlightened, can you explain what this command does? As you might imagine, it's difficult to google effectively.

2022-10-24 08:30 UTC, LawnGnome commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +  bash_path=$(which bash)
`which` shows the full path of the first binary that is found in the `$PATH` that matches the first parameter. So, for example:

```
~ ❯ which bash
/opt/homebrew/anaconda3/bin/bash
```

[Here's the man page, if you're far too interested.](https://linux.die.net/man/1/which)

2022-10-24 08:33 UTC, LawnGnome commented on enterprise/cmd/executor/internal/worker/workspace/files.go
> +  bash_path=$(which bash)
We clarified in meatspace that the actual question was around `command`. Sorry.

`command` is [a POSIX-specified utility](https://pubs.opengroup.org/onlinepubs/9699919799/) — usually provided as a shell builtin — that provides ways of introspecting into commands available on the path.

Specifically: `-p` says to use the default value of `$PATH`, and `-v` says to output a "description" of the command, which for actual binaries will just be the absolute path name of the binary.

2022-10-24 08:40 UTC, LawnGnome approved these changes
LGTM. Thanks!

2022-10-24 09:01 UTC, merged