New Cloud CTA Section on /search
sourcegraph/sourcegraph pull request #43295
Opened 2022-10-21 13:25 UTC by bretthayes

This PR closes #43253 and adds a new CTA Section on `/search`.

## Test plan
- Check that the CTA section is gracefully responsive down to mobile (no mobile design was provided so there's no requirements, but just ensure it looks nice)
- Check that all CTA links work and go to their corresponding locations (signup.sg, docs.sg)
- Check that event data is being logged for the top nav cta, and both links in the Cloud CTA Section (signup.sg, docs.sg)

## Todo
- [ ] After the page is live, I will complete the configuration of [the A/B test for positioning](https://optimize.google.com/optimize/home/?authuser=0&hl=en-US#/accounts/4705180113/containers/15523203/experiments/9) the section below the hero. The base metric position will start with this section being placed above the hero, as I anticipate it performing much better.
- [ ] Logging CTA events on signup.sourcegraph.com as defined in the Metrics artboard will be created in a TBD PR

2022-10-21 18:14 UTC, limitedmage approved these changes

2022-10-21 18:14 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/Illustration.tsx
> +export const Illustration: React.FunctionComponent<
Can we make this an SVG asset file instead? That way it won't affect the bundle size and will be cached by the CDN even if we update the code.

2022-10-21 18:14 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +    const bylines: string[] = [
Looks like these are not being animated as called out in the Figma. Without the animation, the change seems very abrupt. The code for the animation is here: https://codingartistweb.com/2021/04/rotating-words-with-css/

2022-10-21 18:14 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                        <Text size="small">or try our self-hosted solution.</Text>
I left a comment in Figma about how this link does not look clickable (no underline and it's the same color as the rest of the text).

2022-10-21 18:15 UTC, limitedmage commented on client/web/src/search/home/LoggedOutHomepage.tsx
> -                <SelfHostInstructions {...props} />
Let's delete this component entirely if it's not being used. If we need to add it back, we can get it from git history.

2022-10-21 19:55 UTC, st0nebraker approved these changes
Looks good. I confirmed the events logging & firing in the console. Still TBD on where they are stored & aggregating that data. I know our team is still generally ramping this up & we can watch initial impression changes with our A/B test

2022-10-21 19:55 UTC, st0nebraker commented on client/web/src/search/home/LoggedOutHomepage.tsx
> -import { SelfHostInstructions } from './SelfHostInstructions'
Should we delete this component altogether now? Or keep it alive for a bit?

2022-10-21 20:23 UTC, bretthayes commented on client/web/src/search/home/LoggedOutHomepage.tsx
> -import { SelfHostInstructions } from './SelfHostInstructions'
I think we should delete it for now

2022-10-21 20:24 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                        <Text size="small">or try our self-hosted solution.</Text>
Sounds good, will move this around as per the design changes

2022-10-21 20:27 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/Illustration.tsx
> +export const Illustration: React.FunctionComponent<
Yes for sure! Where are assets usually placed in the monorepo?

Is importing SVGs as ReactComponents not the best practice here? Ie:

```jsx
import { ReactComponent as Illustration } from './illustration.svg'
```

2022-10-21 20:35 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                        href="https://docs.sourcegraph.com"
@limitedmage do you know why I can't use the wildcard `Link` component here with the URL pointing to docs in the `to` prop? I get this linting error:

```bash
 Literal unversioned docs links
   client/web/src/search/home/TrySourcegraphCloudSection/index.tsx:1: found link to 'https://docs.sourcegraph.com', use a '/help' relative path for the link instead: to="https://docs.sourcegraph.com"
```

2022-10-21 20:43 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                        href="https://docs.sourcegraph.com"
You should use a link to `/help` instead; this will link the user to the docs page matching their sourcegraph version.

2022-10-21 21:27 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                        href="https://docs.sourcegraph.com"
Ahhh, just realized what `/help` does 💡 Thank you!

2022-10-22 00:49 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +    const bylines: string[] = [
All updated now; it simplified the implementation a lot. I ended up keeping the first byline static below the `sm` breakpoint. `sm` and above animates nicely ✨

2022-10-22 00:50 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/Illustration.tsx
> +export const Illustration: React.FunctionComponent<
Found the [docs](https://handbook.sourcegraph.com/departments/engineering/dev/process/product_documentation/#images-and-binary-assets) and endded up uploading it to sourcegraph-assets.

2022-10-24 16:20 UTC, st0nebraker requested changes

2022-10-24 16:20 UTC, st0nebraker commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                            <span>Automate large-scale code changes.</span>
Looks so good! I am seeing some of this line get cut off & remain on screen when it's next sibling shows. So maybe adjust the line height for the parent?

https://user-images.githubusercontent.com/59381432/197575154-f5a404e3-918d-44e9-8bc2-f6e557bb545d.mov

2022-10-24 16:20 UTC, st0nebraker commented on client/web/src/search/home/TrySourcegraphCloudSection/TrySourcegraphCloudSection.module.scss
> +        }
I'm just curious why we're not animating on mobile, is that part of the design or convention?

2022-10-24 18:11 UTC, st0nebraker commented on client/web/src/search/home/TrySourcegraphCloudSection/TrySourcegraphCloudSection.module.scss
> +        }
Meant xs screens or at all, not just strictly mobile. Gotcha 👍🏻

2022-10-24 19:13 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                            <span>Automate large-scale code changes.</span>
I wasn't see this but I added a line height that matches the height of the parent. Can you check again?

2022-10-24 19:38 UTC, bretthayes commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                            <span>Automate large-scale code changes.</span>
https://user-images.githubusercontent.com/1733936/197611104-c9599855-b20e-4132-ba00-3147077f2796.mov

2022-10-24 19:59 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/Illustration.tsx
> +export const Illustration: React.FunctionComponent<
Yes that's the right process!

2022-10-24 20:33 UTC, st0nebraker commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                            <span>Automate large-scale code changes.</span>
Looks good!

2022-10-24 20:33 UTC, st0nebraker approved these changes

2022-10-24 20:33 UTC, merged

2022-10-24 20:34 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/index.tsx
> +                        <H3 className={styles.bylines}>
These don't semantically feel like headers to me. I recommend instead putting them in a <p>.

2022-10-24 20:34 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/TrySourcegraphCloudSection.module.scss
> +@keyframes spin_words{
Since this is SCSS, the `@keyframes` directive can be nested into the `.bylines` rules.

2022-10-24 20:34 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/TrySourcegraphCloudSection.module.scss
>      }
To me, the animation feels, at the same time, too slow and too fast. The animation itself feels too slow, and the transition between the iterations happens too fast. I recommend [adding extra no-changes keyframes](https://css-tricks.com/css-keyframe-animation-delay-iterations/) to make the animation feel better-paced.

2022-10-24 20:34 UTC, limitedmage commented on client/web/src/search/home/TrySourcegraphCloudSection/TrySourcegraphCloudSection.module.scss
> +        @media (--sm-breakpoint-up) {
Why are there no animations in the xs size? The first byline still appears.