scaletesting: add bitbucket client for codehost copy
sourcegraph/sourcegraph pull request #43343
Opened 2022-10-24 09:01 UTC by burmudar

See title
## Test plan
Test locally

2022-10-24 13:00 UTC, jhchabran requested changes

2022-10-24 13:00 UTC, jhchabran commented on dev/scaletesting/codehostcopy/bitbucket.go
> +	log log.Logger
```suggestion
	logger log.Logger
```

2022-10-24 13:00 UTC, jhchabran commented on dev/scaletesting/codehostcopy/bitbucket.go
> +	u, _ := url.Parse(def.URL)
If we're not dealing with the error, we're better off with a string there.

2022-10-24 13:00 UTC, jhchabran commented on dev/scaletesting/codehostcopy/bitbucket.go
> +	c := bitbucket.NewClient(def.Username, def.Password, u)
There's no token based auth? If yes, that means those should be mandatory indeed. I think you talked about that earlier.

2022-10-24 13:00 UTC, jhchabran commented on dev/scaletesting/codehostcopy/bitbucket.go
> +		if l.Name == "https" || l.Name == "http" {
Is there a case where http is actually acceptable?

2022-10-24 13:00 UTC, jhchabran commented on dev/scaletesting/codehostcopy/bitbucket/client.go
> +	resp, err := http.DefaultClient.Do(req)
Let's adjust the timeouts there, the default one has very loose defaults.

2022-10-24 14:48 UTC, burmudar commented on dev/scaletesting/codehostcopy/bitbucket/client.go
> +	resp, err := http.DefaultClient.Do(req)
Adjusted to be 15 secs

2022-10-24 15:23 UTC, burmudar commented on dev/scaletesting/codehostcopy/main.go
> +
```suggestion
```

2022-10-26 12:46 UTC, jhchabran approved these changes

2022-10-26 12:53 UTC, merged