WIP: add hasbeenactive
sourcegraph/sourcegraph pull request #43370
Opened 2022-10-24 16:47 UTC by mrnugget

This PR is to add a sorting flag for returning users that have a null value for `lastActiveTime` or not. This user state may be caused by a user having never been active on the Sourcegraph instance, or having not been active for 93 days (this is the length of time entries in the `event_logs` table are persisted in the database)

## Test plan
Unit Tests

2022-10-24 16:49 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +        hasBeenActive: Bool
```suggestion
        neverActive: Bool = true
```

2022-11-04 18:41 UTC, efritz requested changes
Talked in a hack session about the desired semantics. Here are a few tips to get you further towards this. This should make the test easier to write as well now that we've clarified the misunderstanding.

2022-11-04 18:41 UTC, efritz commented on cmd/frontend/graphqlbackend/schema.graphql
> +        neverActive: Bool
- [ ] Rename to `includeNeverActive`
- [ ] Re-document and make it explicit that this parameter is only effective when `inactiveSince` is also provided

2022-11-04 18:41 UTC, efritz commented on cmd/frontend/graphqlbackend/users.go
> +	NeverActive   *bool
- [ ] Rename to `IncludeNeverActive`

2022-11-04 18:41 UTC, efritz commented on internal/database/users.go
> +	}
- [ ] Nest this in the if statement above so that it only applies when both `InactiveSince` and `NeverActive` are set.

2022-11-04 18:41 UTC, efritz commented on internal/database/users.go
> +`
```suggestion
const listUsersWithEventsCond = `
(EXISTS (
	SELECT 1 FROM event_logs
	WHERE event_logs.user_id = u.id
))
`
```

2022-11-04 18:41 UTC, efritz commented on internal/database/users.go
> +	}
```suggestion
	if !opt.IncludeNeverActive {
		conds = append(conds, sqlf.Sprintf(listUsersWithEventsCond))
	}
```

2022-11-04 18:41 UTC, efritz commented on internal/database/users.go
> +	NeverActive bool
- [ ] Rename
- [ ] Redocument to match graphql layer semantics

2022-11-04 20:03 UTC, DaedalusG commented on cmd/frontend/graphqlbackend/schema.graphql
> +        neverActive: Bool
You know what, I think the path of least resistance here is `excludeNeverActive` with `inactiveSince` including never active users by default

I think thats the direction Thorston had been going anyway and it prevents having to go back and make a more complicated implementation of `inactiveSince` 🤔

2022-11-07 18:07 UTC, DaedalusG commented on cmd/frontend/graphqlbackend/schema.graphql
> +        neverActive: Bool
It turns out I did need to do some logic shifting on the default behavior of `sinceLastActive` filter -- see latest commit

2022-11-07 18:08 UTC, DaedalusG commented on internal/database/users.go
> +	}
I believe I've got this sorted out -- this was the tricky part to understand

2022-11-08 09:14 UTC, mrnugget commented on cmd/frontend/graphqlbackend/users.go
> +	if args.IncludeNeverActive != nil {
I think this should also be nested under `if args.InactiveSince != nil {`

2022-11-08 09:14 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +        Returns users that have not been active at any point in time.
I'd add a note that this only has an effect if `inactiveSince` is set.

2022-11-24 01:47 UTC, DaedalusG commented
After exploring this a bit more I will need to review the logic and rename some variables that are named never active -- this is in light of the fact that users may have `lastActiveTime` `null` due to all their `event_logs` entries expiring after 93 days of inactivity 

I still think having a filter here is going to come in handy though, in `src users clean` I'll move to using the `last_active_at` db entry -- [more context here](https://github.com/sourcegraph/src-cli/issues/833#issuecomment-1325831047)

cc: @mrnugget @efritz

2022-12-15 19:12 UTC, DaedalusG commented
Closing in liu of: https://github.com/sourcegraph/src-cli/pull/901

2022-12-15 19:12 UTC, closed without merging