Upgrade git version to 2.38.1
sourcegraph/sourcegraph pull request #43615
Opened 2022-10-28 17:00 UTC by varsanojidan

Upgrade git to version 2.38.1

We previously had it upgraded to min 2.35.2 [here](https://github.com/sourcegraph/sourcegraph/pull/37712), but that had a bug with the git commit-graph command, so we reverted it [here](https://github.com/sourcegraph/sourcegraph/pull/39537)

The new version of git [resolves](https://lore.kernel.org/git/d1d460f6-e70f-b17f-73a5-e56d604dd9d5@github.com/) the bug above so we can safely upgrade again.

## Test plan

Just a version change, built the container locally and verified the version

2022-10-28 17:10 UTC, mollylogue approved these changes
💯 this is the bug that was causing a lot of repo corruptions, right?

2022-10-28 17:14 UTC, varsanojidan commented
> 💯 this is the bug that was causing a lot of repo corruptions, right?

There were actually 2 bugs in play here:

We tried to upgrade to 2.35.2 to get the fix for this bug: https://github.blog/2022-04-12-git-security-vulnerability-announced/

But that version of git had the commit-graph bug that caused the corruptions: https://lore.kernel.org/git/581c7ef2-3de4-eb8a-bfbb-d4bca3522a2d@github.com/T/

So we ended up reverting and going back to the old version, and now this should push us past both bugs, plus give us access to Scalar as an added bonus 😄.

2022-10-30 06:51 UTC, mrnugget requested changes
Can you also update these two places here?

- https://github.com/sourcegraph/sourcegraph/blob/1beba7d86196bf8db08cf33e90c518fa980b43e1/dev/sg/dependencies/mac.go#L39
- https://github.com/sourcegraph/sourcegraph/blob/1beba7d86196bf8db08cf33e90c518fa980b43e1/dev/sg/dependencies/ubuntu.go#L36

Once that's done and this is merged, can you post in `#dev-chat` that folks need to upgrade their `git` versions locally?

2022-10-30 06:51 UTC, mrnugget commented on CHANGELOG.md
> +- Updated minimum required veresion of `git` to 2.38.1 in `gitserver` and `server` Docker image. This addresses: https://github.blog/2022-04-12-git-security-vulnerability-announced/ and https://lore.
```suggestion
- Updated minimum required version of `git` to 2.38.1 in `gitserver` and `server` Docker image. This addresses: https://github.blog/2022-04-12-git-security-vulnerability-announced/ and https://lore.kernel.org/git/d1d460f6-e70f-b17f-73a5-e56d604dd9d5@github.com/. [#43615](https://github.com/sourcegraph/sourcegraph/pull/43615)
```

2022-10-30 06:51 UTC, mrnugget commented on cmd/gitserver/Dockerfile
> +    # We require git 2.35.2 to fix this vulnerability:
I'd delete the old comment (it's 4 minor versions behind, I think we don't need to call this out) and I'd change this one here to not mention 2.35.2 (it's confusing that's it's named, but then we don't use it:

```suggestion
    # We require git 2.38+ because we need a fix for this vulnerability to be included:
```

2022-10-31 11:41 UTC, sashaostrikov approved these changes
Agree with Thorsten's comments, apart from that LGTM brat

2022-11-02 14:54 UTC, mrnugget approved these changes

2022-11-02 15:11 UTC, merged