Code Insights: Add insight timeout UI
sourcegraph/sourcegraph pull request #43842
Opened 2022-11-03 03:07 UTC by vovakulikov

Closes https://github.com/sourcegraph/sourcegraph/issues/42297
Based on https://github.com/sourcegraph/sourcegraph/pull/43841
[Figma Designs](https://www.figma.com/file/aMO6sPoUHDUUcqa25wFnWl/Surface-timeout-limit-hit-to-end-users-in-the-UI-%2339969-Review?node-id=260%3A11)

## Todo
- [x] Implement click-to-open tooltip logic (actually, it's implemented in the separate PR here https://github.com/sourcegraph/sourcegraph/pull/43841). Note: this PR should be merged after PR with  click-to-open tooltip implementation 
- [x] Implement mock UI with timeout UI tooltip 
- [ ] Integrate this PR UI with real API implementation (this real API will be implemented in this PR https://github.com/sourcegraph/sourcegraph/pull/43452)

## Test plan
- The timeout UI should match the design

2022-11-03 03:15 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.02% (+0.53 kb) | 0.02% (+2.23 kb) | 0.01% (+1.70 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vk/add-insight-timeout-ui/compare-report.html;tab=live_object) for a full comparison between the commits 7623d37 and 6608a62 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-23 01:26 UTC, vovakulikov commented
@AlicjaSuska this is ready for design review, please take a look, I haven't found a good  insight that has any timeout errors on the k8s but you can check the storybook stories with different timeout errors mocks. 

Note: Recently we had a conversation about error generalising and I saw that you added it in the design changelog (thank you for this). But since BE doesn't implement anything besides timeout error I didn't add general errors on the fronted (since it's not possible to get anything but timeout error right now).  As we introduce new type of errors we add new errors messages on the frontend.

2022-11-25 12:05 UTC, AlicjaSuska requested changes
Thank you for implementing this Vova!

Please, update the tooltip text for the data series error - it is currently the same as for the general error. Also, could you please double-check the color of the link in the tooltip - it seems darker than in the designs. It should be 'link-color/dark'. Other than that, the implementation works well.

As we've discussed on slack, I've designed the v.2 of tooltip - with more popover-like styles and a list of timed-out points. I've created a separate issue for it [here](https://github.com/sourcegraph/sourcegraph/issues/44811).

2022-11-29 14:26 UTC, vovakulikov commented
@AlicjaSuska I fixed copy of the series timeout error tooltip, I checked the link color and I think problem there is in the fact that we don't have any link variation in the wildcard implementation. This means that we use all links with same color which is `--link-color: #0055c5;` for the light theme and ` --link-color: #66aaff` for the dark theme. 

I think you're right that this seems a bit off in our case, but I would suggest that we would solve this problem in a follow up PR. From what I've seen about links in the wildcard this change about adding color variation isn't so straightforward as it should be.

2022-11-29 18:22 UTC, chwarwick commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-chart/BackendInsightChart.tsx
> +export const BackendInsightTimeoutIcon: FC<BackendInsightTimeoutIconProps> = props => {
Do you need a higher level Error here, since the api returned error allows for other error types not just timeouts?

2022-11-29 20:04 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-chart/BackendInsightChart.tsx
> +export const BackendInsightTimeoutIcon: FC<BackendInsightTimeoutIconProps> = props => {
@chwarwick do you mean to name this more generic? I was thinking about it but since our api doesn't implement any other errors and we would have to revisit FE as soon as we add new error types on the backend anyway I left this with more explicit Timeout error.

2022-11-29 21:07 UTC, chwarwick commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-chart/BackendInsightChart.tsx
> +export const BackendInsightTimeoutIcon: FC<BackendInsightTimeoutIconProps> = props => {
I was thinking that the displayed message is coupled to this, so at some point you are probably going to want some sort of `BackendInsightError` that figures the type and shows the right message.  

With it like this as soon as there is a 2nd error the ternary's where it's shown/hidden because an issue.

2022-11-29 22:49 UTC, vovakulikov commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-chart/BackendInsightChart.tsx
> +export const BackendInsightTimeoutIcon: FC<BackendInsightTimeoutIconProps> = props => {
Aha, I got your thought, yes I think you're correct we need to have error type to switch between different error messages. I don't want to support generic errors system at the moment because 
- we still support only one error type
- different error types probably will require different UI as well, see second version of timeout for example. 

Considering this I would like to not go ahead with generic error UI here and wait for the further work on this. @chwarwick feel free to disagree, I spent to much time with this problem it might be I have a blurry eye already.

2022-11-29 23:25 UTC, chwarwick commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-chart/BackendInsightChart.tsx
> +export const BackendInsightTimeoutIcon: FC<BackendInsightTimeoutIconProps> = props => {
I'm ok with that decision, just making a note that it will need to be dealt with sooner or later.

2022-11-30 09:59 UTC, philipp-spiess commented
@AlicjaSuska / @vovakulikov 

I’m not sure if reusing the dark mode link color works in this case. The tooltip has a brighter color than the default dark mode background and as a result the contrast really isn't great:

<img width="492" alt="Screenshot 2022-11-30 at 10 56 54" src="https://user-images.githubusercontent.com/458591/204765682-db1e5144-a81d-455b-8afa-6c79f100a2f0.png">
<img width="604" alt="Screenshot 2022-11-30 at 10 56 48" src="https://user-images.githubusercontent.com/458591/204765694-a751f74d-2256-4c76-a284-0e6ce212bd55.png">

2022-11-30 10:02 UTC, philipp-spiess commented
I’m also not sure if the pattern of putting intractable content inside a tooltip is actually something that is expected? Should we use popovers for intractable content?

2022-11-30 10:04 UTC, philipp-spiess approved these changes
Code LGTM but I’m a bit unsure about the interactable tooltip pattern being established here. Is this something we do in the app already?

2022-11-30 10:04 UTC, philipp-spiess commented on client/web/src/enterprise/insights/components/insights-view-grid/components/backend-insight/components/backend-insight-chart/BackendInsightChart.module.scss
> +    --link-color: #4393e7;
If we go ahead with this let's also overwrite `--link-color-hover:`

2022-11-30 14:35 UTC, vovakulikov commented
@philipp-spiess Thanks for the review. I agree with your concern about the tooltip UI; it works as a popover in this case. You have to click the target to see an error message with a link inside the tooltip. We can't have any focusable/interactive elements in the tooltip. This is true.

To implement this, I had to extend the tooltip component and make it possible to have a fully controlled tooltip state from consumers. This allowed me to use tooltip (with tooltip styles, like background, tail styles, ...etc.) and set up popover-like logic about its show/hide logic. 

I could use Popover + tooltip-like styles in code insight consumer. This is true, but in the tooltip UI, we had enough specific logic about the tail position, for example, which I don't want to care of/fix in code insight (or any other) consumers.

2022-11-30 14:50 UTC, philipp-spiess commented
@vovakulikov Oh yeah I don't worry about the specific implementation that you worked on, I think what you did is fine. My concern is more about the general design decision of using a tooltip if what we want the user to do is interact with the content?

2022-11-30 15:06 UTC, philipp-spiess commented
@vovakulikov Oh, great! Yeah this looks way better IMO 🙂  Thanks for explaining!

2022-12-01 15:43 UTC, AlicjaSuska approved these changes

2022-12-01 15:57 UTC, merged