auth: initial implementation of SOAP
sourcegraph/sourcegraph pull request #43853
Opened 2022-11-03 10:41 UTC by unknwon

## Test plan

Manually tested with the "Okta test instance admin" in 1Password and the "OpenID Connect (sourcegraph.test:3443)" application.

---

Stacked on https://github.com/sourcegraph/sourcegraph/pull/43645, closes https://github.com/sourcegraph/customer/issues/1426

2022-11-03 10:57 UTC, unknwon commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +AND created_at <= %s
If any SQL guru has a better query, please suggest it!

2022-11-03 11:45 UTC, rafax approved these changes

2022-11-03 11:45 UTC, rafax commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
Should we have a feature flag / some other kind of toggle for running this (here, on in CleanUp)?

2022-11-03 11:59 UTC, unknwon commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
Good callout! For this PR I think it's fine to be dynamic (check if we need to do any work within `cleanup`). Once we have https://github.com/sourcegraph/customer/issues/1427 implemented, then the presence of the env var can be used as an indicator/toggle. WDYT?

2022-11-03 12:02 UTC, rafax commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
Sounds good, can you leave a TODO referencing that issue here?

2022-11-03 12:05 UTC, mrnugget commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
Why not run this in `worker` like a job? That way you can allowlist/denylist it via env vars.

2022-11-03 12:06 UTC, mrnugget commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
You could add it to these jobs and get all the goodies that come with it: https://github.com/sourcegraph/sourcegraph/blob/29e831e7c6220c46e42afb60ca014f20e7688bca/enterprise/cmd/worker/main.go#L43-L71

And we're also thinking about building a dashboard for these kind of workers

2022-11-03 12:13 UTC, mrnugget requested changes
Left a comment on SQL, which I think should be heavily simplified. I also think this should go into `worker` instead of having it in `frontend` (we're moving away from background routines in `frontend`, or are at least trying to, right?)

2022-11-03 12:13 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +SELECT array_agg(id)
Why `array_agg`? You can just `SELECT id` and then `basestore.ScanInts`, right?

2022-11-03 12:13 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
I think this query can be heavily simplified, no? Instead of having 2 subselects, you can just join the tables?

Example:

```sql
SELECT users.id
FROM users
JOIN user_external_accounts ON user_external_accounts.user_id = users.id
WHERE user_external_accounts.service_type = 'foobar'
AND users.created_at <= (now() - '15 days ago'::interval)
GROUP BY users.id HAVING COUNT(*) = 1;
```

2022-11-03 13:39 UTC, unknwon commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +SELECT array_agg(id)
>You can just `SELECT id` and then `basestore.ScanInts`, right?

I can, but why is it better? 🤔

2022-11-03 13:47 UTC, unknwon commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
I think the semantics changed with your example, it gives false positives when the user has one external account with `'foobar'` but also has external accounts other than `'foobar'`. 🤔 

We want to only list users IFF the user has a single external account with the `service_type = "sourcegraph-operator"`.

2022-11-03 14:01 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.03 kb) | 0.01% (+1.03 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/jc/soap-03-cleanup/compare-report.html;tab=live_object) for a full comparison between the commits d347b80 and 69c2b1a or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-03 15:03 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +SELECT array_agg(id)
Because it's a database and a database client/driver that are built on the concept of returning rows 😄 Why aggregate the rows in a different data structure before returning and scanning them? If you return the rows instead of aggregating, then potentially they can be streamed.

2022-11-03 15:12 UTC, eseliger commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +SELECT array_agg(id)
Agree that SQL should only be concerned with these things if no other way is available. This will also for example affect the query insights because the returned row count will always be 1 and not the actual count.

2022-11-03 15:27 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
Fair enough!

2022-11-04 05:48 UTC, unknwon commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
Actually... I do want to know if there is a smarter way to write this SQL... @efritz @eseliger CTA! <img src="https://media2.giphy.com/media/3o84sIgvTmkC4W8MRa/giphy.gif"/>

2022-11-04 06:25 UTC, unknwon commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
After looking into https://docs.sourcegraph.com/dev/background-information/workers, I think it is too heavy-lifting (requires a dedicated database table) for a simple clean-up job.

2022-11-04 06:37 UTC, unknwon commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +SELECT array_agg(id)
Addressed in https://github.com/sourcegraph/sourcegraph/pull/43853/commits/ff57b8b86b2f239f84cd95a6474795f3d2c2abef, PTAL!

2022-11-04 09:12 UTC, mrnugget commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
There are more types of workers. You don't need to have a database table. Examples:

- https://github.com/sourcegraph/sourcegraph/blob/6b6f03d614bbb4038a8eedd90c1dd6c0d04e06df/cmd/worker/internal/repostatistics/compactor.go
- https://github.com/sourcegraph/sourcegraph/blob/mrn/zoekt-repos/cmd/worker/internal/zoektrepos/zoektrepos.go

These are simple periodic goroutines. It would be trivial to convert your cleanup job into one of these workers.

I think you can just look at these two or other jobs and copy them, but in case that's not enough, here's more info: https://docs.sourcegraph.com/dev/background-information/backgroundroutine

2022-11-04 09:36 UTC, unknwon commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
Thanks for the examples! I'll take another look.

2022-11-04 09:45 UTC, eseliger commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
Not running in frontend is IMO the way to go because otherwise we horizontally scale this routine for no benefit

2022-11-04 09:55 UTC, eseliger commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
Hmm not sure if it's any smarter, some maybe slightly more readable form might be

```sql
SELECT u.id FROM users u
JOIN user_external_accounts uea ON uea.user_id = u.id
WHERE
	u.id IN (
		SELECT user_id FROM user_external_accounts GROUP BY user_id HAVING COUNT(*) = 1
	)
	AND
	uea.service_type = 'sg'
	AND
	u.created_at <= NOW() - interval '10 day';
```

2022-11-04 09:59 UTC, kopancek commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
I think even with the changed semantics, the query will work as you want it to work.

I do not expect a situation, where our SG operator has a user account, that is also linked to other provider than the `sourcegraph-operator` one. So it should be safe to delete all the user accounts, that have that service_type attached, regardless of if it's the only one or if there are more (which should never happen in my book).

2022-11-04 09:59 UTC, kopancek commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
I suggested using workers even on the initial RFC, so +1 on this idea 👍

2022-11-04 10:01 UTC, unknwon commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
>I do not expect a situation, where our SG operator has a user account, that is also linked to other provider than the sourcegraph-operator one.

S2 😛

2022-11-04 10:05 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
PR desciption says that's expected though:

> It skips users that have external accounts connected other than service type "sourcegraph-operator" because we need to handle the special case of S2 (where Sourcegraph operators have both regular Okta and SOAP external accounts connected).

2022-11-04 10:12 UTC, unknwon commented on enterprise/cmd/frontend/internal/auth/sourcegraphoperator/clean_up.go
> +`,
> Hmm not sure if it's any smarter, some maybe slightly more readable form might be
> 
> ```sql
> SELECT u.id FROM users u
> JOIN user_external_accounts uea ON uea.user_id = u.id
> WHERE
> 	u.id IN (
> 		SELECT user_id FROM user_external_accounts GROUP BY user_id HAVING COUNT(*) = 1
> 	)
> 	AND
> 	uea.service_type = 'sg'
> 	AND
> 	u.created_at <= NOW() - interval '10 day';
> ```

Thanks @eseliger! Pushed in https://github.com/sourcegraph/sourcegraph/pull/43853/commits/8fc02941e499d6c8c91b910a29ebf9207d216518.

I put the `SELECT user_id FROM user_external_accounts WHERE service_type = %s` as the  subselect because in 99.9% of runtime, it should return nothing.

2022-11-04 10:53 UTC, unknwon commented on enterprise/cmd/frontend/main.go
> +	goroutine.Go(func() { sourcegraphoperator.CleanUp(ctx, logger, db) })
Alright, the worker version pushed!

2022-11-04 11:12 UTC, eseliger approved these changes

2022-11-04 12:43 UTC, mrnugget approved these changes

2022-11-04 12:43 UTC, mrnugget commented on enterprise/cmd/worker/main.go
> +		"auth-sourcegraph-operator-cleaner": auth.NewSourcegraphOperatorCleaner(),
Can you add a quick entry to `doc/admin/workers.md` to explain what this one does?

2022-11-06 05:41 UTC, unknwon commented on enterprise/cmd/worker/main.go
> +		"auth-sourcegraph-operator-cleaner": auth.NewSourcegraphOperatorCleaner(),
Oh, absolutely... thanks for the reminder! I did notice some writings in `doc/admin/workers.md` but forgot to ask what's the process to add/keep-up-to-date 😅 (was kinda expecting a linter in CI)

2022-11-06 06:25 UTC, unknwon commented on enterprise/cmd/worker/main.go
> +		"auth-sourcegraph-operator-cleaner": auth.NewSourcegraphOperatorCleaner(),
Added in https://github.com/sourcegraph/sourcegraph/pull/43853/commits/fc1638242b4f2ed7ab3f4dd9031b69df628d9db1!

2022-11-07 08:07 UTC, mrnugget commented on enterprise/cmd/worker/main.go
> +		"auth-sourcegraph-operator-cleaner": auth.NewSourcegraphOperatorCleaner(),
> (was kinda expecting a linter in CI)

Feel free to add one 😬 

There's also the `Description() string` methods on each `job.Job` that are essentially unused. We could probably move the description from the Markdown file over to those methods and then ✨ _somehow_ ✨ auto-generate the Markdown file.

2022-11-09 13:33 UTC, unknwon commented
Merging as-is, happy to address any post-merge comments!

2022-11-09 13:33 UTC, merged

2022-11-10 07:26 UTC, unknwon commented on enterprise/cmd/worker/main.go
> +		"auth-sourcegraph-operator-cleaner": auth.NewSourcegraphOperatorCleaner(),
Sounds like a quick hackathon project 😁!