update Batch Changes and Code Insights CTAs to mention Cloud
sourcegraph/sourcegraph pull request #43985
Opened 2022-11-06 06:41 UTC by sqs

Previously, these CTAs said you needed to install Sourcegraph self-hosted to use Batch Changes or Code Insights. Now they mention Cloud first.

## Test plan

View `/batch-changes` and `/insights` in dotcom mode.

2022-11-06 06:48 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.53 kb) | 0.00% (+0.53 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/sqs/install-cta/compare-report.html;tab=live_object) for a full comparison between the commits 0830345 and e659285 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-06 22:19 UTC, sqs commented
@Joelkw @felixfbecker I see some `licensed` checks that determine whether to show a `+ Create your first insight` button, and whether to show `Explore template` or `Use template`. All instances get a free tier of 2 global insights, so shouldn't we just always show that button and `Use template`, and let the product inform the user if they have exceeded the licensed limits?

2022-11-08 03:29 UTC, sqs commented
Reviewers: because this is code that affects marketing CTAs and not functionality, you can do a less-intensive review.

2022-11-08 06:22 UTC, Joelkw commented
@sqs to answer the specific CTA questions – 

>  All instances get a free tier of 2 global insights, so shouldn't we just always show that button and Use template, and let the product inform the user if they have exceeded the licensed limits?

Fine with these changes! 

(Details for anyone else: the product does note on the creation form if you've hit your limit as well. There was some thought on not leading users on (they can't use the template, because they can't save it) but that's small and we likely over-corrected in that direction given beta-to-GA fears of pricing pushback as we exited free beta. For the main CTA, the + Create first insight is replaced with a "schedule demo" if you don't have a license. We've never had anyone actually schedule it, however, so for now it's fine to revert this as well, at least until we someday focus on in-product conversions when we're further along the PLG journey.)

2022-11-08 06:22 UTC, Joelkw approved these changes

2022-11-08 10:44 UTC, eseliger requested changes
Content changes LGTM, but I think we need to revert the removal of the DotcomGettingStartedPage, see comment inline

2022-11-08 10:44 UTC, eseliger commented on client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
> -const DotcomGettingStartedPage = lazyComponent<DotcomGettingStartedPageProps, 'DotcomGettingStartedPage'>(
I think we want to keep this special-case page for dotcom. The content of getting started can be 100% the same, but it serves the following purposes:

- It doesn't register additional routes
- It is a version that doesn't show the list page as an option

After this change, `https://sourcegraph.com/batch-changes/create` will be available (but not functional).
Also, the getting started page looks broken:
<img width="1499" alt="Screenshot 2022-11-08 at 11 40 38@2x" src="https://user-images.githubusercontent.com/19534377/200544087-0623b53d-bec8-4085-94e8-1e20fc22931b.png">

2022-11-08 10:44 UTC, eseliger commented on client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
> -const DotcomGettingStartedPage = lazyComponent<DotcomGettingStartedPageProps, 'DotcomGettingStartedPage'>(
if you want one of batch changes to take this over, lmk.

2022-11-08 16:41 UTC, vovakulikov reviewed
I'm ok with code insights changes from tech point of view but I would like to get a quick check from @AlicjaSuska about design changes on Code Insights landing pages. 

A few points from me about this PR.

- I see that you removed introduction videos about code insights as well, I haven't found there any outdated information about cloud or install requirements though. Personally I've found this video very useful. 
- Template section is also might be useful in order to give a quick sense of what code insights capable of 
- Footer links, I think it was one of most noticeable places where we had link to our documentation, do we really want to remove them? (find with removing from landing page but in this case I would add theme somewhere else) 

cc @AlicjaSuska

2022-11-09 02:54 UTC, sqs commented on client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
> -const DotcomGettingStartedPage = lazyComponent<DotcomGettingStartedPageProps, 'DotcomGettingStartedPage'>(
@eseliger I want to remove disparities between dotcom and non-dotcom as much as possible, even if it means a bit of jankiness like that error message. I think our audience will understand that, and it paves the way for things like read-only access or demos for some of the UI (not in scope now, but possibly something we'd like in the future to work on on Growth Marketing). I will update that error message to say that you need to use Sourcegraph Cloud or self-hosted, and then I think it's fine.

2022-11-09 02:58 UTC, sqs commented
@vovakulikov:

* I will link the videos from the docs (should have added that in this PR, will add it now). The page was very long IMO and we want to be driving people to our docs, which always have the latest videos and other materials.
* Code Insights templates still show up on self-hosted instance (just not on dotcom anymore, but users can still go to the docs).
* The docs are now linked even more prominently IMO, above the fold under `Resources`.

2022-11-09 03:03 UTC, sqs commented on client/web/src/enterprise/batches/global/GlobalBatchChangesArea.tsx
> -const DotcomGettingStartedPage = lazyComponent<DotcomGettingStartedPageProps, 'DotcomGettingStartedPage'>(
I also just made it so the `/create` route is not registered on dotcom (with just an if-statement in the JSX).

2022-11-09 03:07 UTC, sqs commented
@AlicjaSuska I'm going to merge this because 98% of the changes should be good and the rest are marketing copy/layout-related, so easy to change if you have other ideas.

2022-11-09 03:46 UTC, merged