graphql: add support for filtering webhook logs by webhook ID.
sourcegraph/sourcegraph pull request #44012
Opened 2022-11-07 09:39 UTC by sashaostrikov

Test plan:
New GraphQL tests added, existing tests updated.

Closes https://github.com/sourcegraph/sourcegraph/issues/44001

2022-11-07 09:43 UTC, mrnugget requested changes
Requesting changes because we should use the builtin `ID` type instead of exposing the underlying type. And since that'll change how the rest of the code works, I didn't look to closely at the rest :)

2022-11-07 09:43 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +        webhookID: Int
This is more conventional:

```suggestion
        webhook: ID
```

See [the other references](https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+%3A+ID+file%3Aschema%5C.graphql%24+repo%3Asourcegraph%24&patternType=standard&groupBy=repo) in our schema.

2022-11-07 09:47 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ao/filter-logs-by-webhook-id-gql/compare-report.html;tab=live_object) for a full comparison between the commits abf2417 and 4dd79ce or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-07 10:02 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/schema.graphql
> +        webhookID: Int
yep, I forgot about this type, will change it, thanks!

2022-11-07 10:55 UTC, sashaostrikov commented
@mrnugget I've changed `int` to `graphql.ID`, ready for review now

2022-11-07 11:17 UTC, mrnugget approved these changes

2022-11-07 11:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +			},
Why test for `-1` specifically? (Why not test for `-2`?) If I put in `0` the test breaks, because `0` is set, even though that's an invalid ID.

2022-11-07 11:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/webhook_logs.go
> +		if id != -1 {
See below. I'd change this to `if id <= 0`

2022-11-07 11:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +		},
Nitpick, but: I'd save some precious bytes here 😛 
```suggestion
		{ID: 1, WebhookID: int32Ptr(1), StatusCode: 200},
		{ID: 2, WebhookID: int32Ptr(1), StatusCode: 500},
		{ID: 3, WebhookID: int32Ptr(1), StatusCode: 200},
		{ID: 4, WebhookID: int32Ptr(2), StatusCode: 200},
		{ID: 5, WebhookID: int32Ptr(2), StatusCode: 200},
		{ID: 6, WebhookID: int32Ptr(2), StatusCode: 200},
		{ID: 7, WebhookID: int32Ptr(3), StatusCode: 500},
		{ID: 8, WebhookID: int32Ptr(3), StatusCode: 500},
```

(Also makes it more readable, IMHO)

2022-11-07 11:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +		}
```suggestion
		filteredWebhookLogs = append(filteredWebhookLogs, webhookLogs...)
```

Or:

```go
		filteredWebhookLogs := make([]*types.WebhookLog, len(webhookLogs))
		copy(filteredWebhookLogs, webhookLogs)
```

I'd also rename `filteredWebhookLogs` to `logs`, because they're not filtered there

2022-11-07 11:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +		filter := func(items []*types.WebhookLog, predicate func(log *types.WebhookLog) bool) []*types.WebhookLog {
`items` is unused. This function doesn't do what you think it does, I think :)

2022-11-07 12:00 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +			},
This is to support the [behaviour](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/webhook_logs.go?L112&subtree=true) of how logs filtering by webhook ID and external service ID is done. `-1` is treated as not providing an ID at all -- no filtering.

But now I think that any "negative ID" should be treated that way, not only `-1`.

`0` is another special case which means "find all webhooks logs which doesn't have an assigned webhook", that's why the test "breaks"

2022-11-07 12:05 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +		filter := func(items []*types.WebhookLog, predicate func(log *types.WebhookLog) bool) []*types.WebhookLog {
it's a typo, I wanted to use `items`, thanks!

2022-11-07 12:08 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +		}
About naming:
In such cases I usually use `filtered...` name right away even before being filtered, because this variable is reassigned after each filtering stage (and becomes filtered eventually).

But when would you add `filtered` prefix to show that the slice contains filtered elements?

2022-11-07 15:27 UTC, merged

2022-11-08 09:18 UTC, mrnugget commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +			},
Uhm, I don't follow. If I look at the code I see 

```go
	// If set and non-zero, this limits the webhook logs to those matched to
	// that configured webhook. If set and zero, this limits the webhook logs to
	// those that did not match any webhook. If nil, then all webhook
	// logs will be returned.
	WebhookID *int32
```

It's a pointer.

We're also talking about the GraphQL API here, not the database layer. So why should `-1` and `0` be special values in the GraphQL API? We do have optional parameters in GraphQL, so we can just say "if webhook is set, then use that in the database options, otherwise no"

2022-11-08 09:54 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/webhook_logs_test.go
> +			},
I agree that if it exists -- we just pass it to the database options.

fixed here https://github.com/sourcegraph/sourcegraph/pull/44067