internal/repos: Add debug logs
sourcegraph/sourcegraph pull request #44020
Opened 2022-11-07 12:09 UTC by indradhanush

Also wrap errors in some places.

## Test plan

Only logging and error wrapping. No functional change.

2022-11-07 12:30 UTC, sashaostrikov reviewed
I think some logs can/should be probably changed with metrics, because overall number of added log lines multiplied by a number of repos fetched/synced from GH can be very large.

Some log lines seem a bit redundant, I've left the comments with my thoughts.

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/github.go
> +		s.logger.Debug("unfiltered", log.String("repo", fmt.Sprintf("%v", res.repo.NameWithOwner)))
It seems to produce as much log lines as there are repos fetched from GitHub, which is pretty much(?)

Did you think about adding a metric instead of logging, or adding an aggregated log with a number of repos?

Or do you need all repo names instead?

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/scheduler.go
> +		logger.Debug("RunScheduler: watching config")
Should we add a scope "RunScheduler" instead of prefixing the log messages?

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/scheduler.go
> +		logger.Debug("RunScheduler: watching config")
And regarding this exact log line: I'm curious why is it so important?

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/syncer.go
> +	logger.Debug("SyncRepo started")
Not sure about necessity of adding this log as well, tbh

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/syncer.go
> +		logger.Debug("repo not foundin DB, skipping")
```suggestion
		logger.Debug("repo not found in DB, skipping")
```

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/syncer.go
> +				s.Logger.Debug("external service repo deleted", log.Int32("stored.ID", int32(stored.ID)))
```suggestion
				s.Logger.Debug("external service repo deleted", log.Int32("deleted.ID", int32(stored.ID)))
```

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/syncer.go
> +		return nil, errors.Wrapf(err, "failed to get repo: %q")
I think you forgot to add a parameter which will be used in a string template

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/syncer.go
> +		s.Logger.Debug("syncer: committing transaction")
probably worth creating a new logger instance with "syncer" scope

2022-11-07 12:30 UTC, sashaostrikov commented on internal/repos/syncer.go
> +				s.Logger.Debug("syncer: context done")
should the message be different?

2022-11-07 12:31 UTC, indradhanush commented on internal/repos/github.go
> +		s.logger.Debug("unfiltered", log.String("repo", fmt.Sprintf("%v", res.repo.NameWithOwner)))
Yes, that's the intention since I'm missing some repos in the customer issue. I want to verify the repo is being passed from one abstraction to another. Since it's a debug log, I'm not too worried about it (customer has repos in the order of 100s, not thousands) and can remove it once we find the bug.

2022-11-07 12:32 UTC, indradhanush commented on internal/repos/scheduler.go
> +		logger.Debug("RunScheduler: watching config")
Just a frame of reference to debug when multiple stuff is happening simultaneously. 🙂

2022-11-08 01:21 UTC, indradhanush commented on internal/repos/syncer.go
> +		s.Logger.Debug("syncer: committing transaction")
Good point. I checked and `s.Logger` is already initialised with the `syncer` scope [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/repo-updater/shared/main.go?L176). 

I'll drop the `syncer:` prefix in the logs here.

2022-11-08 07:12 UTC, sashaostrikov reviewed
I think there are a couple of unresolved comments from my previous review, plus I've asked a couple of questions about necessity of logging the whole repo structure instead of a name.

2022-11-08 07:12 UTC, sashaostrikov commented on internal/repos/github.go
> +		s.logger.Debug("unfiltered", log.String("repo", fmt.Sprintf("%v", res.repo.NameWithOwner)))
I double-checked with JH, he told me that we _don't_ store logs of all levels (and filter them afterwards), so we are good to add a number of debug statements 👍🏻

2022-11-08 07:12 UTC, sashaostrikov commented on internal/repos/scheduler.go
> +		logger.Debug("RunScheduler: watching config")
gotcha!

Let's create a scoped logger (`RunScheduler` scope) for this function as well

2022-11-08 07:12 UTC, sashaostrikov commented on internal/repos/syncer.go
> +		logger.Debug("repo not foundin DB, skipping")
it doesn't seem to be fixed, does it?

2022-11-08 07:12 UTC, sashaostrikov commented on internal/repos/github.go
> +		s.logger.Debug("unfiltered", log.String("repo", fmt.Sprintf("%v", res.repo.NameWithOwner)))
do we really need to do `fmt.Sprintf("%v", res.repo.NameWithOwner)` on a string field?

2022-11-08 07:12 UTC, sashaostrikov commented on internal/repos/github.go
> +				s.logger.Debug("context error", log.String("repo", fmt.Sprintf("%v", r)))
do you want to print the whole `github.Repository` type or will `r.NameWithOwner` suffice like in previous cases?

2022-11-08 07:24 UTC, indradhanush commented on internal/repos/syncer.go
> +		logger.Debug("repo not foundin DB, skipping")
Hmm. Weird. I remember committing your suggestion. 🤔

2022-11-08 07:27 UTC, indradhanush commented on internal/repos/syncer.go
> +				s.Logger.Debug("external service repo deleted", log.Int32("stored.ID", int32(stored.ID)))
Using a different name in the logs will be confusing. Usage of `stored.ID` here is intentional.

2022-11-08 07:28 UTC, indradhanush commented on internal/repos/github.go
> +				s.logger.Debug("context error", log.String("repo", fmt.Sprintf("%v", r)))
I do want the whole `repo` here. I want to be able to inspect the structure of the variable for a missing repo to see if there are any corner cases.

2022-11-08 07:35 UTC, sashaostrikov commented on internal/repos/github.go
> +				s.logger.Debug("context error", log.String("repo", fmt.Sprintf("%v", r)))
I see. Do you think adding the field names in this case (`%+v`) can be useful?

2022-11-08 07:35 UTC, indradhanush commented on internal/repos/github.go
> +		s.logger.Debug("unfiltered", log.String("repo", fmt.Sprintf("%v", res.repo.NameWithOwner)))
Good catch! Will fix.

2022-11-08 07:38 UTC, indradhanush commented on internal/repos/github.go
> +				s.logger.Debug("context error", log.String("repo", fmt.Sprintf("%v", r)))
Good idea, makes sense. 👍🏽

2022-11-08 08:39 UTC, sashaostrikov requested changes
PTAL at my comment, scoped logger creation needs to be fixed

2022-11-08 08:39 UTC, sashaostrikov commented on internal/repos/scheduler.go
> +	logger.Scoped("RunScheduler", "git fetch scheduler")
unfortunately it won't work this way, you need to assign it to a new variable and use it

2022-11-08 08:40 UTC, ryanslade commented on internal/repos/github.go
> +			s.logger.Debug("context error", log.String("nameWithOwner", nameWithOwner))
Don't we log the errors that are sent back in the `results` chan? Maybe instead we can wrap the error and include the repo name?

2022-11-08 08:41 UTC, ryanslade commented on internal/repos/github.go
> +			s.logger.Debug("context error", log.String("nameWithOwner", nameWithOwner))
(Same comment for the other places where we sent the error back)

2022-11-08 08:41 UTC, ryanslade commented on internal/repos/github.go
> +				s.logger.Debug("context error", log.String("repo", fmt.Sprintf("%+v", r)))
Agree with @sashaostrikov, probably too noisy to log the entire struct,

2022-11-08 08:42 UTC, ryanslade commented on internal/repos/scheduler.go
> +		logger.Debug("watching config")
I think this could get very noisy and doesn't convey too much info

2022-11-08 08:44 UTC, indradhanush commented on internal/repos/scheduler.go
> +	logger.Scoped("RunScheduler", "git fetch scheduler")
Argh, I missed that in a rush. 🤦🏽‍♂️

2022-11-08 08:44 UTC, indradhanush commented on internal/repos/github.go
> +			s.logger.Debug("context error", log.String("nameWithOwner", nameWithOwner))
Wrapped error with the repo name is a good idea! Will fix!

2022-11-08 08:44 UTC, ryanslade commented on internal/repos/syncer.go
> +		logger.Debug("repo not found in DB, skipping")
This happens when we *don't* have a NotFound error so the log isn't accurate. 

Maybe instead we can wrap the error and include the repo name?

2022-11-08 08:44 UTC, sashaostrikov commented on internal/repos/syncer.go
> +				s.Logger.Debug("external service repo deleted", log.Int32("stored.ID", int32(stored.ID)))
When you take a look at logs, you usually don't have the source code before your eyes (and customers for sure don't as well), that's why you/customer will just see that `external service repo deleted` and then in log attributes will notice that `stored.ID=123`.

I guess this will confuse everyone much worse than a variable name (with its own semantics) not being the same for the logging attribute name (with its own _very different_ semantics).

WDYT?

2022-11-08 09:24 UTC, mrnugget commented on internal/repos/syncer.go
> +		logger.Debug("repo not found in DB, skipping")
Repo name should be included in all the logs, right? since the logger is scoped to have the name in every message (see first line of this function)

2022-11-08 11:09 UTC, indradhanush commented on internal/repos/syncer.go
> +		logger.Debug("repo not found in DB, skipping")
I looked at the code calling `SyncRepo` which seems to handle the error. This log is redundant. I've removed it and instead wrapping the error now.

@ryanslade Good call out on the `NotFound` error. I missed the real error in the earlier log message.

2022-11-08 11:11 UTC, indradhanush commented on internal/repos/syncer.go
> +	logger.Debug("SyncRepo started")
Addressed in the similar comment about RunScheduler. Marking as resolved.

2022-11-08 11:24 UTC, sashaostrikov approved these changes
LGTM overall!

PTAL at my suggestion and also seems like you've missed [this](https://github.com/sourcegraph/sourcegraph/pull/44020#discussion_r1016299996) comment of mine, which I'd like you to take a look at

2022-11-08 11:24 UTC, sashaostrikov commented on internal/repos/github.go
> +			results <- &githubResult{err: errors.Wrap(err, "context error for repository: namewithOwner="+nameWithOwner)}
```suggestion
			results <- &githubResult{err: errors.Wrapf(err, "context error for repository: namewithOwner %q", nameWithOwner)}
```

2022-11-08 11:26 UTC, indradhanush commented
> PTAL at my suggestion and also seems like you've missed https://github.com/sourcegraph/sourcegraph/pull/44020#discussion_r1016299996 comment of mine, which I'd like you to take a look at

@sashaostrikov Sorry, my bad. Thank you for the review. I'm enabling auto merge for now and will follow up with another PR to fix it as I'd like to not block the [patch release](https://github.com/sourcegraph/sourcegraph/issues/43840).

2022-11-08 11:29 UTC, ryanslade approved these changes

2022-11-08 11:29 UTC, indradhanush commented on internal/repos/github.go
> +			results <- &githubResult{err: errors.Wrap(err, "context error for repository: namewithOwner="+nameWithOwner)}
I decided to stick with the similar convention used in this function already.

2022-11-08 11:39 UTC, indradhanush commented
@sashaostrikov Turns out I had some time. Fixed the suggestions in this PR itself.

2022-11-08 11:50 UTC, indradhanush commented on internal/repos/github.go
> +			results <- &githubResult{err: errors.Wrap(err, "context error for repository: namewithOwner="+nameWithOwner)}
Had a change of heart and decided to fix it in both the instances.

2022-11-08 11:52 UTC, sashaostrikov commented on internal/repos/github.go
> +			results <- &githubResult{err: errors.Wrap(err, "context error for repository: namewithOwner="+nameWithOwner)}
Best approach ever! :value-high-agency:

2022-11-08 11:54 UTC, merged