Improved CTAs
sourcegraph/sourcegraph pull request #44053
Opened 2022-11-08 00:19 UTC by bretthayes

This closes #43752 with some improved CTAs.

## Changelog
- added a `Try Sourcegraph Cloud` CTA button for logged in dotCom and self-hosted users
- moved the Feedback button from the nav to the user menu as a modal instead of a popup
- no change to pro tip since it's already shown to all users
- instead of adding a CTA to our settings page (without being spammy since we already have a button in the top nav), I added it to the subscriptions page since we mention self-hosted pricing there

There is no way to know a self-hosted user vs a dot com user, so consolidating the wording for one option simplifies the solution.

## Test plan
- check that the feedback prompt in the modal works from the user menu
- check that the global nav cta button works and links to signup
- check that the signup cta on the pricing/subs page links to signup

2022-11-08 00:34 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.13 kb) | 0.01% (+0.82 kb) | 0.01% (+0.69 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/brett/ctas/compare-report.html;tab=live_object) for a full comparison between the commits 7d3ee6e and 10dbe78 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-08 21:49 UTC, st0nebraker approved these changes
One console error comment below. Besides that looks good! I see all 3 test requirements fulfilled 👍🏻

2022-11-08 21:49 UTC, st0nebraker commented on client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
> +                        </Text>
```suggestion
                        <>
                            Search your private code with{' '}
                            <Link to="https://signup.sourcegraph.com/" onClick={() => eventLogger.log('ClickedOnCloudCTA')}>
                                Sourcegraph Cloud
                            </Link> or contact us to purchase a subscription for a self-hosted Sourcegraph instance. See{' '}
                            <Link to="https://about.sourcegraph.com/pricing">pricing</Link> for more information.
                        </>
```
I think the `<>` fragment was used because of the console error below.  `<PageHeader/>` assigns `description` to a `Text` tag one level down
<img width="966" alt="image" src="https://user-images.githubusercontent.com/59381432/200682611-8f8da082-bbf0-420a-850d-8079784ac823.png">

2022-11-10 00:01 UTC, st0nebraker requested changes
Just one comment from some new changes to `Feedback`!

2022-11-10 00:01 UTC, st0nebraker commented on client/web/src/nav/GlobalNavbar.tsx
> -                            onSubmit={handleSubmitFeedback}
I think we want to keep the `Feedback` action available for unauth'd users here. In standup today we were chatting about this & Quinn added some optimizations to Feedback since your work has been in flight.

2022-11-10 19:47 UTC, bretthayes commented on client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
> +                        </Text>
Ah, thanks Becca!

2022-11-10 20:47 UTC, bretthayes commented on client/web/src/nav/GlobalNavbar.tsx
> -                            onSubmit={handleSubmitFeedback}
Cool, I agree - I think that's a good idea. I brought back the Feedback popover for unauth'd users in the top nav. For auth'd users, the Feedback will now be in the user menu to simplify to top nav space.

2022-11-10 20:48 UTC, bretthayes commented on client/web/src/nav/GlobalNavbar.tsx
> -                            onSubmit={handleSubmitFeedback}
### Before
![Screen Shot 2022-11-10 at 3 47 47 PM](https://user-images.githubusercontent.com/1733936/201202676-95c0c087-0132-4bb0-83af-bd7c58f768dc.png)

### After
![Screen Shot 2022-11-10 at 3 47 55 PM](https://user-images.githubusercontent.com/1733936/201202677-f347ceae-5c76-4b8c-a112-82bf32d603ac.png)

2022-11-10 20:51 UTC, bretthayes commented on client/web/src/nav/GlobalNavbar.tsx
> -                            onSubmit={handleSubmitFeedback}
## Auth'd users

### Before
![Screen Shot 2022-11-10 at 3 50 39 PM](https://user-images.githubusercontent.com/1733936/201203149-58137edc-4b61-4a50-b25b-0485a1773fc2.png)

### After
![Screen Shot 2022-11-10 at 3 49 54 PM](https://user-images.githubusercontent.com/1733936/201203148-cd0a3b3c-f607-457b-859f-d1c12d754058.png)

2022-11-11 02:28 UTC, st0nebraker approved these changes

2022-11-11 02:28 UTC, merged