fuzzy finder: join shortcut segments with + on Linux+Windows
sourcegraph/sourcegraph pull request #44150
Opened 2022-11-09 13:29 UTC by Strum355

On MacOS, fuzzy finder shortcuts looked fine when joined without a `+`:
![image](https://user-images.githubusercontent.com/18282288/200842489-e5c081d8-a883-49c3-98ef-2002d92c1a46.png)

However, on Linux+Windows, it looked unnatural to not join with a `+`. This PR addresses this and leaves the original for Mac only.

A new set of type definitions were added as `navigator.platform` is deprecated, but most browsers don't implement the new (experimental) alternative `navigator.userAgentData.platform`, and the typescript type definitions also dont include it. This doesnt impact the functionality of the code at runtime, as its purely type definitions

<details>
<summary>Browser support for `navigator.userAgentData.platform`</summary>

![image](https://user-images.githubusercontent.com/18282288/200842295-115f9917-976a-48ed-895f-b8a545ae4dea.png)

</details>

---

Before on Linux+Windows:
![image](https://user-images.githubusercontent.com/18282288/200841838-1574aaa6-73cd-4e52-94dd-105fefe6699e.png)

After on Linux+Windows:
![image](https://user-images.githubusercontent.com/18282288/200841858-9c5fce2a-c284-49af-897c-dd30f293403d.png)

MacOS unchanged.

## Test plan

Much noodling in dev-tools on both Linux+Mac, Firefox+Safari+Chromium

## App preview:

- [Web](https://sg-web-nsc-fuzzyfinder-shortcuts-nonmac.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

2022-11-09 13:45 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.10 kb) | 0.00% (+0.10 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/nsc/fuzzyfinder-shortcuts-nonmac/compare-report.html;tab=live_object) for a full comparison between the commits 3a860b5 and f1b2890 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-09 13:47 UTC, olafurpg requested changes

2022-11-09 13:47 UTC, olafurpg commented on client/web/src/components/KeyboardShortcutsHelp/KeyboardShortcutsHelp.tsx
> +                navigator?.userAgentData?.platform?.includes('macOS') || navigator?.platform?.includes('Mac') ? '' : '+'
We should use `isMacPlatform` that's already imported in scope

2022-11-09 14:05 UTC, Strum355 commented on client/web/src/search/helpers.tsx
> +    let searchQueryParameter = buildSearchURLQuery(query, patternType, caseSensitive, selectedSearchContextSpec)
how was this not caught in a previous PR??? wtf prettier

2022-11-09 15:52 UTC, Strum355 commented on client/common/src/util/browserDetection.ts
> -    return window.navigator.platform.includes('Mac')
`navigator.platform` is deprecated and not recommended to be used anymore, with `navigator.userAgentData.platform` replacing it. Should have no impact on adding it here besides it being done now rather than down the line when browsers start dropping support for it

2022-11-09 15:55 UTC, Strum355 commented on client/web/src/components/KeyboardShortcutsHelp/KeyboardShortcutsHelp.tsx
> +            return [...(keybinding.held || []), ...ordered].map(key => renderShortcutKey(key)).join(joinString)
Sounds good to me, can wait :+1:

2022-11-09 16:08 UTC, olafurpg approved these changes
LGTM 👍🏻 for the `+` change, but would be good to get a separate stamp for `isMacPlatform` changes

2022-11-09 18:27 UTC, limitedmage commented on client/common/src/util/browserDetection.ts
> -    return window.navigator.platform.includes('Mac')
[`navigator.userAgentData` is not broadly supported](https://caniuse.com/mdn-api_workernavigator_useragentdata) (doesn't work in Safari or Firefox). Let's keep `navigator.platform` for now.

FWIW browsers will never drop support for this 😅 Though they might [hardcode it to something useless like they did with `navigator.appName`.](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/appName)

2022-11-09 18:32 UTC, Strum355 commented on client/common/src/util/browserDetection.ts
> -    return window.navigator.platform.includes('Mac')
> (doesn't work in Safari or Firefox).
the code still falls back to `navigator.platform`, so all browsers should function fine here

2022-11-09 18:33 UTC, limitedmage commented on client/common/src/util/browserDetection.ts
> -    return window.navigator.platform.includes('Mac')
Yup posted an edit a bit late 😅

2022-11-09 18:38 UTC, vovakulikov commented on client/common/src/util/browserDetection.ts
> -    return window.navigator.platform.includes('Mac')
I don't have any preferences here. I'm sure that browsers will never drop support for this though. Usually it's good to use new api as much as possible. If it has a right fallback with `window.navigator.platform.includes('Mac')` I don't see any blockers for not doing this. 

Speaking about new API and expressions: using || seems a bit ancient. Should we use here ?? operator instead? @Strum355?

2022-11-09 18:42 UTC, Strum355 commented on client/common/src/util/browserDetection.ts
> -    return window.navigator.platform.includes('Mac')
> Speaking about new API and expressions: using || seems a bit ancient. Should we use here ?? operator instead? @Strum355?

Can definitely do this

2022-12-06 15:25 UTC, Strum355 commented
Have rebased this branch and incorporated all the feedback cc @fkling @limitedmage @vovakulikov

2022-12-06 23:25 UTC, limitedmage approved these changes

2022-12-09 15:07 UTC, merged