insights: oob migration for saving recording times for existing insights
sourcegraph/sourcegraph pull request #44165
Opened 2022-11-09 17:29 UTC by leonore

closes #43496

## Test plan

Added unit tests for migrator and helpers
Tested manually on existing insights by setting supports_augmentation = FALSE and deleting all existing recording times

2022-11-10 21:33 UTC, chwarwick commented
I think this looks good, but I think we also need an noop migrator that reports 100% if insights is disabled.

2022-11-10 23:27 UTC, coury-clark requested changes
One small change to prevent any deadlock issues

2022-11-10 23:27 UTC, coury-clark commented on enterprise/internal/oobmigration/migrations/insights/recording_times_migrator.go
> +	for id, metadata := range series {
seems like you could move this into the loop above?

2022-11-10 23:27 UTC, coury-clark commented on enterprise/internal/oobmigration/migrations/insights/recording_times_migrator.go
> +			lastRecordedAt: lastRecordedAt,
Just talking out loud:

If a record is currently queued when this runs, we should be fine because the new recording time will be written whenever that job executes.

2022-11-10 23:27 UTC, coury-clark commented on enterprise/internal/oobmigration/migrations/insights/recording_times_migrator.go
> +		"SELECT id, created_at, last_recorded_at, sample_interval_unit, sample_interval_value FROM insight_series WHERE supports_augmentation IS FALSE LIMIT %s FOR UPDATE SKIP LOCKED",
When locking rows access should always been in a stable order:

`order by id`

2022-11-11 10:38 UTC, leonore commented on enterprise/internal/oobmigration/migrations/insights/recording_times_migrator.go
> +		"SELECT id, created_at, last_recorded_at, sample_interval_unit, sample_interval_value FROM insight_series WHERE supports_augmentation IS FALSE LIMIT %s FOR UPDATE SKIP LOCKED",
interesting thank you. I'll add this to the oob migration development docs too

2022-11-14 14:37 UTC, chwarwick commented on enterprise/internal/oobmigration/migrations/insights/recording_times_migrator.go
> +	tx, err := m.store.Transact(ctx)
looking back at the last oob migration, the `up` also got an early return if code insights is disabled.  I think this is necessary because there may be no db.  I think `down` needs the same.

2022-11-14 16:47 UTC, merged