WIP HACK: Streaming git blame
sourcegraph/sourcegraph pull request #44199
Opened 2022-11-10 11:10 UTC by mrnugget

## Test plan

2022-11-10 11:18 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/mrn+jh/streaming-git-blame/compare-report.html;tab=live_object) for a full comparison between the commits dac7a3a and ef37174 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-14 15:23 UTC, jhchabran commented
@mrnugget I've tested our new code against the renderer, by just reading things on the server instead of streaming to the client, it works as intented. At this point, I'm inclined to reach out to @philipp-spiess to see if we can get started on the frontend side.

2022-11-14 15:42 UTC, mrnugget commented on internal/gitserver/commands_test.go
> +filename format.go`
Nit: trailing newline needed, I think

2022-11-14 15:44 UTC, mrnugget commented on internal/gitserver/stream_hunk.go
> +			close(p.done)
Nit: I think we should break/return here

2022-11-14 17:26 UTC, jhchabran commented
@philipp-spiess in order to update the frontend to use that new feature: 

- I have put the route behind a feature flag `enable-streaming-git-blame` (bool), it will return a 404 otherwise. 
  - Can we shield the POC on your side behind the same feature flag on the client side? 
- At this stage, our primary target is really to **POC this more than anything else** and test it on the scale-testing instance. Therefore, we're looking at a crude hack at this stage, as long as it tells us if blaming large and old files works better than before, we're good. 
- The API now has a new route: `:repo/glob/-/stream-blame/:path'. 
  - It returns _json lines_ and not JSON, to accomodate with streaming the responses. 
  - It looks like this: `[{hunk}, {hunk}]\n[{hunk, ...}]` 
    - The number of hunks in each batch is not fixed. 
    - There are a few differences with the graphql structure which I pasted below for your convenience, we can work out if we want to clean stuff once we have validated the POC. 
    - Yes, the `(Start|End)Bytes` are at `0`, which is normal (that's a consequence of using `--incremental` with `git blame` but this should not be a problem as we don't need that data to display things in the UI.

```
[{"StartLine":110,"EndLine":111,"StartByte":0,"EndByte":0,"CommitID":"599b6b513a72fe233b15d2f3388c349545d7fa49","Author":{"Name":"Stephen Gutekanst","Email":"slimsag@users.noreply.github.com","Date":"2018-10-01T22:10:43Z"},"Message":"docs: add CONTRIBUTING + open-source FAQ (#178)","Filename":"README.md"}]
[{"StartLine":95,"EndLine":96,"StartByte":0,"EndByte":0,"CommitID":"9be8ad00d0795756fc330b70749dccea80505a75","Author":{"Name":"Beyang Liu","Email":"beyang@sourcegraph.com","Date":"2018-10-01T19:04:55Z"},"Message":"update README","Filename":"README.md"}]
[{"StartLine":100,"EndLine":102,"StartByte":0,"EndByte":0,"CommitID":"9be8ad00d0795756fc330b70749dccea80505a75","Author":{"Name":"Beyang Liu","Email":"beyang@sourcegraph.com","Date":"2018-10-01T19:04:55Z"},"Message":"update README","Filename":"README.md"}]
[{"StartLine":103,"EndLine":104,"StartByte":0,"EndByte":0,"CommitID":"02a03f54c15c3f86fcec2aed2f2b00adae5cd237","Author":{"Name":"Sourcegraph","Email":"hi@sourcegraph.com","Date":"2018-10-01T06:08:12Z"},"Message":"Publish Sourcegraph as open source 🚀","Filename":"README.md"}]
```

You can test this for yourself by running the following `curL` command: 

```
curl 'https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/stream-blame/README.md' -H 'authority: sourcegraph.test:3443' -H 'accept: application/json' -H 'cache-control: no-cache' -H 'content-type: application/json' -H 'cookie: PASTE_FROM_AN_EXISTING_SESSION' -H 'origin: https://sourcegraph.test:3443' -H 'referer: https://sourcegraph.test:3443/github.com/stretchr/testify/-/blob/_codegen/main.go?subtree=true' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' -v
```

As a reference, here is what we're sending back through the normal graphql call:

```json
{
  "data": {
    "repository": {
      "commit": {
        "blob": {
          "blame": [
            {
              "startLine": 16,
              "endLine": 17,
              "author": {
                "person": {
                  "email": "frenchben@docker.com",
                  "displayName": "French Ben",
                  "user": null
                },
                "date": "2018-01-31T14:01:02Z"
              },
              "message": "Update error output to be clean",
              "rev": "bbca6551549492486ca1b0f8dee45553dd6aa6d7",
              "commit": {
                "url": "/github.com/hashicorp/go-multierror/-/commit/bbca6551549492486ca1b0f8dee45553dd6aa6d7"
              }
            },
           // ...
          ]
        }
      }
    }
  }
}
```

2022-11-15 16:28 UTC, camdencheek commented on cmd/frontend/internal/app/ui/stream_blame.go
> +			flusher.Flush()
I expect that flushing here is not desirable since flushing is a blocking operation that will likely be slower than just marshaling the next chunk. The OS flushing is almost definitely good enough.

2022-11-16 12:04 UTC, philipp-spiess commented
@jhchabran @mrnugget 

https://github.com/sourcegraph/sourcegraph/pull/44476 😎 

Most of the stuff here is pretty straight forward. I decided to add an early-flush once we have received the first 50 hunks and emit those so we can have a fast initial render and then wait for the remainder of the hunks to go through before doing the final flush. 

This is something we can tweak later on though!

2022-11-16 12:07 UTC, philipp-spiess commented on cmd/frontend/internal/app/ui/router.go
> +	repoRev.Path("/stream-blame{Path:.*}").Methods("GET", "HEAD").Name(routeStreamBlame)
We probably want to move this into the `/.api/` path somehow so that we have proper authentication and cors header support, but for a _let's-quickly-try-this-on-the-scale-testing-instance_ this works 😄

2022-11-17 09:21 UTC, mrnugget commented
It looks like the two of you already talked about this, but just so it's recorded here, here's what I sent to JH yesterday:

* I talked with @efritz about adding a new streaming endpoint yesterday. He's aligned with us and agrees that we can add an endpoint for this, **BUT** we should keep it consistent with the other streaming endpoints. Meaning:
* We should define this streaming endpoint next to the others: https://github.com/sourcegraph/sourcegraph/blob/3033610b103e82904dfa7eabd33e1494c8520d3a/cmd/frontend/internal/httpapi/router/router.go#L70-L71 (I don't know why they are also defined in the "internal" API below. We need to figure tha tout)
* Handler should then go somewhere here: https://github.com/sourcegraph/sourcegraph/blob/3033610b103e82904dfa7eabd33e1494c8520d3a/cmd/frontend/internal/httpapi/httpapi.go#L124
* We should reuse as much as possible from their stack here: https://github.com/sourcegraph/sourcegraph/blob/3033610b103e82904dfa7eabd33e1494c8520d3a/internal/search/streaming/http/writer.go#L26
* We should use [server-sent events](https://en.wikipedia.org/wiki/Server-sent_events) as the protocol, not jsonlines. That's already what that writer I linked to in previous line does.

2022-11-17 10:50 UTC, mrnugget commented on cmd/frontend/internal/app/ui/stream_blame.go
> +			flusher.Flush()
This is copied from the streaming-search server-sent events write: https://github.com/sourcegraph/sourcegraph/blob/3033610b103e82904dfa7eabd33e1494c8520d3a/internal/search/streaming/http/writer.go#L100 They flush after every event/data.

2022-11-17 16:12 UTC, camdencheek commented on cmd/frontend/internal/app/ui/stream_blame.go
> +			flusher.Flush()
Yes, but we [wrap that writer in a buffer](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@d6c61f503dedaed83b108d4ab5dbf97ee0a09d4a/-/blob/cmd/searcher/internal/search/search.go?L112-114), which collects events until we get to 32KB payloads

2022-11-17 18:24 UTC, jhchabran commented
So some results from the testing on the scale testing instance: 

With the streaming git blame enabled: 

`megarepo/git/git.c`
<img width="612" alt="CleanShot 2022-11-17 at 19 15 37@2x" src="https://user-images.githubusercontent.com/10151/202525483-641802e8-5026-42dc-9776-5cf48cb852a5.png">

`megarepo/git/readme.md` 

<img width="584" alt="CleanShot 2022-11-17 at 19 16 06@2x" src="https://user-images.githubusercontent.com/10151/202525566-721382fb-322b-4627-8b85-78af3fcf12fe.png">

With the normal GitBlame graphql call: 

`megarepo/git/git.c`

<img width="610" alt="CleanShot 2022-11-17 at 19 13 06@2x" src="https://user-images.githubusercontent.com/10151/202525082-dd4d384a-41a9-48c1-8505-854997f16596.png">


`megarepo/git/readme.md` 

<img width="594" alt="CleanShot 2022-11-17 at 19 17 56@2x" src="https://user-images.githubusercontent.com/10151/202526106-5fe66e9a-8cf1-41a5-ac23-f4915bb39723.png">

---

Basically, the timings are not that different from each other, but the TTFB way better, meaning the UI is getting updated with the most recent commits much earlier. 

Therefore, it's a significant improvement from a end user perspective. 

As for why it's still taking long to get the first bytes with the streaming, I started digging and apart from the fact that `git blame` on the README takes about 20seconds to give back some results and `git blame --incremental` takes about 10 secs to produce the first results, I suspect the way we handle the responses in between gitserver and the frontend is where it's happening. Perhaps we could make it better by flushing more aggressively? 

Some traces: https://console.cloud.google.com/traces/list?tid=90a0303df2d5450b7f9f98943a208c5d&project=sourcegraph-scaletesting and https://console.cloud.google.com/traces/list?tid=c9a215a141d644d7a83563cc1914919e&project=sourcegraph-scaletesting

Still, it's a good enough iteration this far and it's behind a feature flag. I'll clear the code tomorrow morning. Meanwhile, the code itself is at https://github.com/sourcegraph/sourcegraph/compare/docker-images-candidates-notest/mrn+jh+ps/streaming-git-blame .

2022-11-18 18:15 UTC, jhchabran commented on client/web/src/Layout.tsx
> +        routeMatch,
Ignore this, linter stuff, donno why it's there. Probably been fixed but we started that branch earlier.

2022-11-18 18:15 UTC, jhchabran commented on client/web/src/enterprise/user/productSubscriptions/UserSubscriptionsProductSubscriptionsPage.tsx
> +                            <Link
Ignore this, linter stuff, donno why it's there. Probably been fixed but we started that branch earlier.

2022-11-18 18:15 UTC, jhchabran commented on client/web/src/nav/GlobalNavbar.tsx
> +        PlatformContextProps,
Ignore this, linter stuff, donno why it's there. Probably been fixed but we started that branch earlier.

2022-11-18 18:21 UTC, camdencheek approved these changes
LGTM!

2022-11-18 18:36 UTC, camdencheek requested changes
Oops, sorry for the weird review pattern. Made a couple of comments, most minor. The goroutine leak issue should be addressed before merge though. Happy to pair on it if you'd like -- my explanation was a little sparse 😄

2022-11-18 18:36 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +		var done bool
nit: why is `done` being defined up here? Looks like you can just do `done, err := ...` on line 119

2022-11-18 18:36 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +		return nil, errors.Errorf("HERE Expected at least 4 parts to hunkHeader, but got: '%s %s'", rev, content)
`HERE`?

2022-11-18 18:36 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +	numLines, _ := strconv.Atoi(fields[2])
Should we check these errors? Seems like swallowing these could cause some confusing behavior in the future

2022-11-18 18:36 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +		done = true
Is it possible there are annotations that aren't listed here? Because if there are, it looks like this will stop parsing a commit early rather than just ignoring the unhandled annotations. That could put the stream parser in a weird state.

2022-11-18 18:36 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +	rc io.ReadCloser
IMO, `rc` should not be stored on `blameHunkReader` because it cannot be accessed concurrently. Instead, I think it would be less error-prone to pass it into `br.readHunks` so that the only handle that is retained is in the hunk parser.

2022-11-18 18:36 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +		return nil, true, nil
I think this can cause a goroutine leak. Basically, because we don't drain `br.hunks`, the goroutine running `parse()` will block indefinitely when trying to write to `br.hunks`.

2022-11-18 18:39 UTC, camdencheek reviewed
Actually, looking closer at this, do we actually need a background goroutine? Can `Read()` just scan a single hunk from the byte stream and return it rather than depending on all the channel operations?

2022-11-18 18:39 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +		return nil, true, nil
Actually, looking closer at this, do we actually need a background goroutine? Can Read() just scan a single hunk from the byte stream and return it rather than depending on all the channel operations?

2022-11-18 18:43 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +	go br.readHunks(ctx)
readHunks go br

2022-11-18 18:45 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +func (br *blameHunkReader) Read() (hunk []*Hunk, done bool, err error) {
Is `ok bool` or `done bool` more idiomatic? The return values kind of surprised me at a glance.

2022-11-18 18:46 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +			break
You break here, which causes a second close. You should only defer the close in this function to ensure it happens exactly once.

2022-11-18 18:47 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +		if done {
If you can't have done = true and err != nil here, I'd use an else if

2022-11-18 18:48 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +			p.hunksCh <- hunkResult{hunk: cur}
Can you ensure that you will drain the channel here? Otherwise you might want for every write to have a select with a ctx.Done() case as well.

2022-11-18 18:49 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +		return nil, true, nil
I think this would work instead:

```go
res, ok := <-br.hunks
if !ok {
    return ...
} else if res.err != nil {
    return ...
} else {
    return ...
}
```

2022-11-18 18:49 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +		return nil, true, nil
Then you don't even need br.done/p.done.

2022-11-18 18:50 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +		done = true
Should the default case in this condition be "" and not default?

2022-11-18 18:51 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +	rc io.ReadCloser
Is blameHunkReader accessed concurrently?

2022-11-18 18:53 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +	rc io.ReadCloser
The channels in it are concurrently referenced by the `Read()`-calling goroutine and the `br.readHunks()` goroutine

2022-11-18 19:29 UTC, felixfbecker commented on client/web/src/repo/blame/useBlameHunks.ts
> +    Author: {
In JSON, the naming convention is camelCase (I think also used in our search streaming API). I assume it's a quick change to add JSON property name annotations in Go, could that be done for consistency?

2022-11-21 08:30 UTC, mrnugget commented on cmd/frontend/internal/app/ui/stream_blame.go
> +			flusher.Flush()
Ah, interesting. But that's not the OS flushing then, right?

2022-11-21 08:54 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +                'X-Sourcegraph-Should-Trace': 1,
@felixfbecker Yes, that's because the client side is not finished. I hardcoded this for my tests and left it so we don't forget adding this if we detect it's enabled.

2022-11-21 08:54 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +        const hunks = new BehaviorSubject<Omit<BlameHunk, 'displayInfo'>[] | undefined>(undefined)
I'll deflect to @philipp-spiess, I have no idea what you're talking about :)

2022-11-21 09:02 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +    Author: {
cc @philipp-spiess

2022-11-21 09:10 UTC, burmudar commented on internal/gitserver/commands.go
> +func streamBlameFileCmd(ctx context.Context, command gitCommandFunc, path string, opt *BlameOptions, repo api.RepoName, checker authz.SubRepoPermissionChecker) (HunkReader, error) {
nit: can the argument order match `StreamBlameFile` (with the exception of command)

2022-11-21 10:38 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +    Author: {
I've changed the JSON tags for the blame hunk to be lowecased but the author sub-struct already had JSON tags in go that were explicitly starting with an upper-case letter. Since we want to cherry pick this into the release candidate today, we decided not to change the Author sub-struct right now to avoid issues but I'll follow up with this.

2022-11-21 10:40 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                'X-Sourcegraph-Should-Trace': 1,
I made this conditionally based on an URL param now. We probably want to create a small wrapper over `fetchEventSource` that does this for all requests. Will do this as a follow-up.

2022-11-21 10:41 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +        const hunks = new BehaviorSubject<Omit<BlameHunk, 'displayInfo'>[] | undefined>(undefined)
Fixed! My worry was that the observable is cached and it needs to be replayed when i.e a user disables and enables git blame again but a normal `Observable` also works this way (I think `memoizeObservable` is already doing that for us then).

2022-11-21 10:51 UTC, taras-yemets commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    },
@philipp-spiess, we transform `RawStreamHunk` to `BlameHunk` here (the difference is only in `author` field names casing). `BlameHunk` type comes from `graphql-operations`. As we use it for GraphQL and streaming results what do you think about moving the `BlameHunk` definition to `client/web/src/repo/blame/useBlameHunks.ts` to be more explicit?

2022-11-21 10:55 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    },
`BlameHunk` is an autogenerated type based on the GraphQL query, right? I’m not sure I understand your suggestion.

2022-11-21 10:55 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    parents: [],
cc @jhchabran

2022-11-21 10:58 UTC, taras-yemets commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    },
> BlameHunk is an autogenerated type based on the GraphQL query, right?

Yes, it is. I mean do we want to use autogenerated type as `useBlameHunks` hook return type if it can query streaming API (but not the GraphQL) under the hood?
My suggestion is to define `BlameHunk` interface in the current file instead of using the autogenerated one. WDYT, @philipp-spiess?

2022-11-21 11:04 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    parents: [],
I'm going to get it in this PR, otherwise we're breaking the feature to view blame prior to the current commit. I missed it when hacking on this.

2022-11-21 11:25 UTC, taras-yemets commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
I'm not sure about the commit URL here. Should it include the _"/.api/blame/"_ part?

2022-11-21 11:30 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    parents: [],
@jhchabran Nah you didn't miss it: it was just added after you started :D 

There're some other fields that we'll want to add later though (but this doesn't have to be today): https://github.com/sourcegraph/sourcegraph/pull/44476#discussion_r1023919248

2022-11-21 11:32 UTC, taras-yemets commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
@jhchabran, I wonder if we can get commit URL value from backend (e.g. [git_commit.go?L197](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1a002b7546fb80d898252b53eb68af99eab469de/-/blob/cmd/frontend/graphqlbackend/git_commit.go?L197))?

2022-11-21 12:14 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
Nope! You're right, this is an issue after the url name refactoring. cc @jhchabran if we can compute the url in the backend this would be better I think (Similar like we do it for for GraphQL)?

2022-11-21 12:15 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    },
Oh yeah I see what you mean 👍

2022-11-21 12:21 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
Fixed for now in the frontend to unblock the PR

2022-11-21 12:21 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    },
Fixed

2022-11-21 12:44 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
That wouldn't make sense, because it would refer to the streaming API. What are these URLs used for? I suspect they're used to generate links in the UI perhaps?

2022-11-21 12:46 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
I'll probably return a different payload than what we're sending now, so I can include the parents, so perhaps I can do it there as well, I'll ping you :)

2022-11-21 12:48 UTC, taras-yemets commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
> I suspect they're used to generate links in the UI perhaps?

Yes, they are ([useBlameHunks.ts?L94](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1a002b7546fb80d898252b53eb68af99eab469de/-/blob/client/web/src/repo/blame/useBlameHunks.ts?L94), [BlameDecoration.tsx?L181](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1a002b7546fb80d898252b53eb68af99eab469de/-/blob/client/web/src/repo/blob/BlameDecoration.tsx?L181)).

2022-11-21 14:21 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
> I'll probably return a different payload than what we're sending now, 

Cool! In this case let's not forget to revert these changes: https://github.com/sourcegraph/sourcegraph/pull/44199/files#diff-f38a70af975d2348d79cd689595f213715e62b12d3953ccdd35f7224a1cdac23R679-R688

2022-11-21 15:15 UTC, jhchabran commented on internal/gitserver/stream_hunks.go
> +		return nil, true, nil
done

2022-11-21 15:15 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    parents: [],
fixed, I added the parents the response.

2022-11-21 15:22 UTC, jhchabran commented
@mrnugget can you take a look at the backend side so we don't have to rush too much later to fix something that would come out during the review? 

I had to make it really simple to get the parent commits in the response, we're running a bit against the clock to get this baked in the release later today.

2022-11-21 15:27 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +        }).pipe(throttle(() => interval(1000), { leading: true, trailing: true })),
@taras-yemets I added this to throttle the updates on the UI side (otherwise this would re-render for every hunk that is streamed in). However I can't get the trailing logic to work right, do you know what I’m doing wrong? Basically the last hunks (so the earliest commits) are no longer rendered 😖 

Without the throttle:

![image](https://user-images.githubusercontent.com/458591/203092709-b889347f-c043-499a-a4bb-8d4c8dd72937.png)

2022-11-21 15:33 UTC, jhchabran commented on client/web/src/repo/blame/useBlameHunks.ts
> +                                    url: `${repoAndRevisionPath}/-/commit/${hunk.commitID}`,
done in https://github.com/sourcegraph/sourcegraph/pull/44199/commits/199147a88a3b5437aea32013195df1edbdca88df

2022-11-21 15:38 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +        }).pipe(throttle(() => interval(1000), { leading: true, trailing: true })),
Okay this seems to work now 😅 

<img width="2523" alt="Screenshot 2022-11-21 at 16 37 00" src="https://user-images.githubusercontent.com/458591/203095564-8f161aa8-839c-4d3f-af2e-64f4d3334da8.png">

This is how it looks:

https://user-images.githubusercontent.com/458591/203095628-cab80aa1-3afd-4801-993a-d2888ff1aabf.mov

The flickering is a bit annoying but we can fix this later (this is only experimental and we're changing the way how we render the blames as well in https://github.com/sourcegraph/sourcegraph/pull/44148

2022-11-21 15:46 UTC, taras-yemets commented on client/web/src/repo/blame/useBlameHunks.ts
> +        }).pipe(throttleTime(1000, asyncScheduler, { leading: true, trailing: true })),
```suggestion
        }).pipe(throttleTime(1000, undefined, { leading: true, trailing: true })),
```
nit: @philipp-spiess, `asyncScheduler` seems to be a [default value](https://rxjs.dev/api/index/function/throttleTime) so we can skip it ([usages](https://sourcegraph.com/search?q=context:%40taras-yemets/sg+throttletime%28&patternType=standard&sm=1))

2022-11-21 16:04 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +        }).pipe(throttle(() => interval(1000), { leading: true, trailing: true })),
Fixed the flickering issue in my latest PR: Because of `useEffect`, CodeMirror was notified about an updated data source after the React tree re-rendered

2022-11-21 16:04 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +        }).pipe(throttleTime(1000, asyncScheduler, { leading: true, trailing: true })),
Done!

2022-11-21 16:17 UTC, efritz commented on internal/gitserver/stream_hunks.go
> +				p.hunksCh <- hunkResult{hunk: cur}
```suggestion
				select {
					case <- p.hunksCh <- hunkResult{hunk: cur}:
					case <- ctx.Done():
						return
				}
```

I think every write needs this as you're not draining the channel (on the consumer side) to ensure that all writes succeed when the context is canceled and the consumer bails out.

2022-11-21 16:28 UTC, jhchabran commented on internal/gitserver/stream_hunks.go
> +				p.hunksCh <- hunkResult{hunk: cur}
Thank you 🙏

2022-11-21 17:12 UTC, camdencheek commented on internal/gitserver/commands.go
> +			fmt.Printf("len(remainingLines): %d\n", len(remainingLines))
stray printfs?

2022-11-21 17:12 UTC, camdencheek commented on internal/gitserver/stream_hunks.go
> +			p.hunksCh <- hunkResult{err: err}
I think an error here would cause another goroutine leak. Sending an error up the channel will cause the consumer to stop calling `Read()`, but this loop will continue, so as soon as we try to send another event on the channel, it will block indefinitely.

I'm a bit uncomfortable with this channel code in general, and would feel much more confident about a late inclusion in the release if this was modified to not use goroutines/channels.

2022-11-21 17:17 UTC, camdencheek commented on cmd/frontend/internal/app/ui/stream_blame.go
> +			flusher.Flush()
Yes, that's right. We don't use OS flushing because we buffer JSON entries, then build the JSON array on flush, so it's not actually raw bytes we're buffering.

2022-11-21 18:02 UTC, jhchabran commented on internal/gitserver/stream_hunks.go
> +			p.hunksCh <- hunkResult{err: err}
Ack, as we're not rushing things as much as we thought we'd be, I'll update the code tomorrow. I'll make it decent tomorrow 🙏

2022-11-21 18:02 UTC, jhchabran commented on internal/gitserver/stream_hunks.go
> +			p.hunksCh <- hunkResult{err: err}
Also, I should just quit the loot there anyway.

2022-11-21 19:19 UTC, felixfbecker commented on client/web/src/repo/blame/useBlameHunks.ts
> +                        assembledHunks = [...assembledHunks]
Why do we need to copy the array here? This leads to iterating through every previous on every new hunk which doesn't seem good from a performance standpoint.

Maybe it would be better to make the Observable emit each hunk individually, and let the caller aggregate it into an array without having to copy it every time?

2022-11-21 19:31 UTC, philipp-spiess commented on client/web/src/repo/blame/useBlameHunks.ts
> +                        assembledHunks = [...assembledHunks]
There were some issues with propagation in the react tree that I wanted to fix with this but in the first version I only had one early emit after the first few hunks while this now emits after every single hunk.

We'll run into similar issues when we aggregate at the caller I think (maybe it'll be a bit better because we can throttle but then we'd have to make sure we don't loose individual values).

I'll test this again without recreating the array. If we really have to do something to invalidate hooks I'll maybe create an object that has a reference to the array that I can recreate instead. 🤔

Maybe we can connect the observable directly into the code mirror extension and can skip the react re-render parts as well. Will look into it.

2022-11-22 10:25 UTC, jhchabran commented on internal/gitserver/stream_hunks.go
> +			p.hunksCh <- hunkResult{err: err}
@camdencheek I corrected the code, thank you for pointing out my mistake there 🙏

2022-11-22 11:43 UTC, camdencheek approved these changes

2022-11-22 13:07 UTC, taras-yemets commented on client/web/src/repo/blame/useBlameHunks.ts
> +            map(blames => ({ current: blames }))
```suggestion
            map(hunks => (hunks ? hunks.map(blame => addDisplayInfoForHunk(hunk, sourcegraphURL)) : undefined)),
            map(hunks => ({ current: hunks }))
```

nit: just to be consistent with the type name from the return value (`BlameHunk`) and the formatting function (`addDisplayInfoForHunk`)

2022-11-22 13:38 UTC, taras-yemets approved these changes
Frontend changes look good to me.
Checked out the branch and tested on the CodeMirror blob view - it works 🚀 
Great work 👍🏻

2022-11-22 14:43 UTC, evict commented on internal/gitserver/commands.go
> +	}
It's good to check this arg for safety, but not strictly necessary because we filter potentially malicious arguments in `IsAllowedGitCmd`.

2022-11-24 09:26 UTC, jhchabran commented
@philipp-spiess could you deal with the conflicts on the tsx files so we can merge this 🙏 ?

2022-11-24 09:42 UTC, ryanslade commented on cmd/frontend/internal/httpapi/router/router.go
> +
nit: Why the extra spaces?

2022-11-24 09:56 UTC, ryanslade commented on cmd/frontend/internal/httpapi/stream_blame.go
> +		if gitdomain.IsRepoNotExist(err) {
That error implements `NotFound` so will be caught by `errcode.IsNotFound(err)` below.

2022-11-24 10:05 UTC, ryanslade commented on cmd/frontend/internal/httpapi/stream_blame.go
> +	api.CommitID `json:"commitID"`
bit: Maybe move this to the top of the struct to make it more obvious that it's embedded

2022-11-24 10:06 UTC, ryanslade commented on internal/gitserver/client.go
> +	"github.com/sourcegraph/sourcegraph/internal/actor"
nit: Should be grouped at the bottom with other `/sourcegraph` imports

2022-11-24 10:08 UTC, ryanslade commented on internal/gitserver/commands.go
> +		return nil, err
When `hasAccess` is false we may return `nil, nil` here which may break things higher up. 

I'd suggest returning a specific `Not Authorized` error

2022-11-24 10:09 UTC, jhchabran commented on cmd/frontend/internal/httpapi/router/router.go
> +
nit: forgot about it and brain didn't register when looking at my own code

2022-11-24 10:12 UTC, ryanslade commented on internal/gitserver/stream_hunks.go
> +func (p hunkParser) parse(ctx context.Context) {
I think this is safe in this case, but still strange to see a non pointer receiver on a relatively complex type. There's a chance that this leads to bugs later if new fields are added that need to be mutated.

2022-11-24 10:35 UTC, philipp-spiess commented
> @philipp-spiess could you deal with the conflicts on the tsx files so we can merge this 🙏 ?

@jhchabran  done!

2022-11-24 10:52 UTC, jhchabran commented on internal/gitserver/commands.go
> +		return nil, err
Fixed, thank you for catching this 🙏

2022-11-24 11:06 UTC, sashaostrikov approved these changes
LGTM from gitserver perspective!
(but build fails due to error in ts file)

2022-11-24 15:10 UTC, merged