New Code Insight example, add dotcom CTA, general cleanup
sourcegraph/sourcegraph pull request #44248
Opened 2022-11-10 23:11 UTC by st0nebraker

Closes #43754 & #43239

- New icon style
- Fix broken dotcom mock locally
- Adds new code insight example
- Adds CTA to description
- Reduces text content noise to streamline message & encourage tinkering

## Test plan

2022-11-10 23:19 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.19 kb) | 0.01% (+1.19 kb) | 0.14% (+1) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/code-insights-dotcom-cleanup/compare-report.html;tab=live_object) for a full comparison between the commits 174b342 and 942023c or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-12 00:25 UTC, limitedmage reviewed
Overall looks great! Left some comments and questions.

2022-11-12 00:25 UTC, limitedmage commented on client/shared/src/global-styles/icons.scss
> +    background: #EEDFFF;
Is this the same in dark mode and light mode? Can we add these to `colors.scss`?

2022-11-12 00:25 UTC, limitedmage commented on client/shared/src/global-styles/icons.scss
> +.violet-bg {
Any classes here are global. Is this necessary or is the same class in `Icon.modules.scss` (which is scoped) sufficient?

2022-11-12 00:25 UTC, limitedmage commented on client/wildcard/src/components/Icon/Icon.tsx
> +    violetBg?: boolean
Suggestion for a more semantic naming. Also, no date is required, we have Git history.

```suggestion
    /**
     * Brand icon variation with violet background
     * 
     * More info: https://handbook.sourcegraph.com/departments/engineering/design/brand_guidelines/
     */
    branded?: boolean
```

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-description/CodeInsightsDescription.tsx
> +                    <Link to="/help/code_insights" rel="noopener">
I think we have to add `target="_blank"` to the links so they open in a new tab

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-description/CodeInsightsDescription.tsx
> +                            Sign up for a 30-day trial on Sourcegraph Cloud.
Should there be a period at the end of the CTA link?

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/components/code-insights-examples-picker/CodeInsightsExamplesPicker.tsx
> +                <Link to="/help/code_insights/references/common_use_cases">See more use cases</Link>
Should this also open in a new tab?

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
> +                            bodyText="Code Insights requires a local Sourcegraph installation via Docker Compose or Kubernetes. You can check it out for free by installing locally."
Does Code Insights not work on Cloud managed instances?

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/insights/CodeInsightsRouter.tsx
> +    if (!fetched && process.env.NODE_ENV !== 'development') {
Why is this change needed?

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
> +                    bodyText="Batch Changes requires a local Sourcegraph installation via Docker Compose or Kubernetes. You can check it out for free by installing locally."
Does batch changes not work on Cloud managed instances either? This seems contradictory with the Cloud 30-day trial CTA above.

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
> +                                <Link to="https://signup.sourcegraph.com/" onClick={() => eventLogger.log('ClickedOnCloudCTA')}>
Should we log a different event here on Batch Changes vs Code Insights CTA?

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
>                              </Link>
Again verify that these do open in a new tab

2022-11-12 00:25 UTC, limitedmage commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
> +            <div className="row align-items-center">
Why is this needed? Verify the page still works on different screen resolutions all the way down to 320px width.

2022-11-14 18:47 UTC, st0nebraker commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
> +            <div className="row align-items-center">
With the right column text getting longer, in my opinion it looks better for the video to be centered vertically & not aligned at the top to balance the 2 columns. What do you think?

![image](https://user-images.githubusercontent.com/59381432/201741044-790a3a45-0d61-47f6-a28a-dd3ee8c82f4f.png)

2022-11-14 18:51 UTC, st0nebraker commented on client/shared/src/global-styles/icons.scss
> +    background: #EEDFFF;
Yes! Same in dark mode from what I can tell from designs documentation. Added this to our color variables [here](https://github.com/sourcegraph/sourcegraph/pull/44248/commits/315d01b5a896db0d1bfd9e1cf09610b564d941d6), added all of our violet secondary brand colors, skipping the others for now since they aren't used. Link to color documentation added for future iteration here

2022-11-14 18:52 UTC, st0nebraker commented on client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-description/CodeInsightsDescription.tsx
> +                    <Link to="/help/code_insights" rel="noopener">
Sure thing, added this addendum to all new links in this PR

2022-11-14 18:53 UTC, st0nebraker commented on client/web/src/enterprise/insights/CodeInsightsRouter.tsx
> +    if (!fetched && process.env.NODE_ENV !== 'development') {
I noted in the PR, this page wasn't rendering for web standalone in dev & dotcom mode (`SOURCEGRAPHDOTCOM_MODE=true sg start web-standalone`) because of this line

2022-11-14 19:03 UTC, st0nebraker commented on client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-description/CodeInsightsDescription.tsx
> +                            Sign up for a 30-day trial on Sourcegraph Cloud.
It's on the Figma and a similar CTA on the home page. Do you think it looks bad?

2022-11-14 19:24 UTC, st0nebraker commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
> +                    bodyText="Batch Changes requires a local Sourcegraph installation via Docker Compose or Kubernetes. You can check it out for free by installing locally."
I'm asking for clarification. Maybe the old phrasing is best here `Batch Changes requires a Sourcegraph Cloud or self-hosted instance.`

2022-11-15 17:20 UTC, bretthayes commented on client/web/src/enterprise/batches/list/GettingStarted.tsx
> +                                <Link to="https://signup.sourcegraph.com/" onClick={() => eventLogger.log('ClickedOnCloudCTA')}>
We had a chat about this the other day in our growth marketing sync. I think the event name being the same is ok so we can keep them all in the same basket. But we should attach an `origin` or some other named param so we can filter these events in Amplitude by page path or if the url contains a specific string. That will help us differentiate locations to understand where they're clicked.

ie:
```js
eventLogger.log('ClickedOnCloudCTA', { url: window.location.href })
```

cc: @kelsey-brown

2022-11-15 22:18 UTC, limitedmage commented on client/web/src/enterprise/insights/CodeInsightsRouter.tsx
> +    if (!fetched && process.env.NODE_ENV !== 'development') {
Oh weird! @sourcegraph/code-insights is this a good way to go about fixing this?

2022-11-15 23:36 UTC, st0nebraker commented on client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-description/CodeInsightsDescription.tsx
> +                            Sign up for a 30-day trial on Sourcegraph Cloud.
I see what you mean, I can see having it either way since it's such a long text it's almost a sentence 😬

2022-11-15 23:54 UTC, felixfbecker commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/components/code-insights-examples-picker/examples.ts
> +        description: 'Find vulernable OpenSSL versions in the Python Ecosystem',
```suggestion
        description: 'Find vulnerable OpenSSL versions in the Python Ecosystem',
```

2022-11-16 00:05 UTC, felixfbecker commented on client/web/src/enterprise/insights/CodeInsightsRouter.tsx
> +    if (!fetched && process.env.NODE_ENV !== 'development') {
@vovakulikov

2022-11-16 16:28 UTC, st0nebraker commented on client/wildcard/src/components/Icon/Icon.tsx
> +    violetBg?: boolean
There are already boolean props & a prop for size variation on `Icon`. So it seems to me like the preferred convention is to have `Icon` control the variations. This is a new design variation of icons we haven't implemented yet. I'm happy to follow whichever convention is preferred by the frontend team. `<VioletIcon />` wrapper feels like too much code to me, personally. Happy to pass a className for this too. Let me know!

2022-11-17 00:30 UTC, limitedmage commented on client/wildcard/src/components/Icon/Icon.tsx
> +    violetBg?: boolean
I think making this a variant of `Icon` makes sense. But I agree that naming it after the color is not ideal. We could go with the `variant` way similar to what we have with buttons, something like this which can be extended later: 
```
variant?: 'none' | 'branded' // 'none' inherits color from surrounding text and is the defualt. 'branded' uses a contrasting purple background and foreground.
```

2022-11-18 21:17 UTC, st0nebraker commented on client/wildcard/src/components/Icon/Icon.tsx
> +    violetBg?: boolean
These pages got re-designed after development & now the icons on the CTA's are gone. So these sections will be removed anyway for now 🤷🏻

2022-11-18 23:05 UTC, st0nebraker commented on client/web/src/enterprise/insights/CodeInsightsRouter.tsx
> +    if (!fetched && process.env.NODE_ENV !== 'development') {
Hm - Ok if no one else can reproduce I removed it

2022-11-18 23:09 UTC, st0nebraker commented on client/web/src/enterprise/insights/pages/landing/getting-started/components/code-insights-description/CodeInsightsDescription.tsx
> +                code into a queryable database and lets you create customizable, data visualization in seconds.
In my opinion, there's too much text on this page and not enough room for tinkering for prospective devs. From my  perspective, slimming down the content would be a big improvement.

- Saying "you" too much reads poorly imo.
- Ah, yes "data visualizations" is the better phrasing ✅ .
- Removed the comma that's there from prod currently.
- Returned "dashboards" highlight. I was thinking "data visualizations" is a better known term to highlight in this instance.

2022-11-21 19:29 UTC, bretthayes commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
> +                    </section>
As a suggestion, we could share this component to be used on the other pages for #43917 and #43989. Maybe under marketing components? Then we could have props for the text, link, event name for logging, and a variant for the two designs (outlined/filled).

2022-11-21 19:29 UTC, bretthayes commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
> +                            <Link to="https://signup.sourcegraph.com/?p=insights" onClick={() => telemetryService.log('ClickedOnCloudCTA', { url: window.location.href })}>
Just curious why we're using telemetry service here vs our event logger? There's a few other instances of this in this PR, but I won't comment on each to save you from repetitiveness. 

Also, just a note that any link which is outbound and logged at the same time should open in a new tab so we can ensure the event is logged. See [thread](https://sourcegraph.slack.com/archives/C046X8AG5NY/p1668804917162249?thread_ts=1668803114.517019&cid=C046X8AG5NY) for details. There is also an [issue](https://github.com/sourcegraph/analytics/issues/713) to add `url` into the pipeline so we don't have to add them manually to each event log.

2022-11-21 19:59 UTC, felixfbecker commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
> +                            <Link to="https://signup.sourcegraph.com/?p=insights" onClick={() => telemetryService.log('ClickedOnCloudCTA', { url: window.location.href })}>
`TelemetryService` is just an abstract interface over our `EventLogger`. In the webapp,  at runtime `telemetryService === eventLogger`.

2022-11-21 20:00 UTC, felixfbecker commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
> +                            <Link to="https://signup.sourcegraph.com/?p=insights" onClick={() => telemetryService.log('ClickedOnCloudCTA', { url: window.location.href })}>
See [implementations of `TelemetryService`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/shared/src/telemetry/telemetryService.ts?L14:18&subtree=true#tab=implementations_typescript)

2022-11-21 20:57 UTC, bretthayes commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
> +                            <Link to="https://signup.sourcegraph.com/?p=insights" onClick={() => telemetryService.log('ClickedOnCloudCTA', { url: window.location.href })}>
Cool, thanks @felixfbecker! So should we use `telemetryService.log` over `eventLogger.log` instead of accessing the eventLogger directly?

2022-11-21 23:13 UTC, bretthayes requested changes

2022-11-21 23:13 UTC, bretthayes commented on client/web/src/marketing/components/CloudCTABanner.tsx
> +        </p>
Looks like buildkite is still failing:
- [rename](https://buildkite.com/sourcegraph/sourcegraph/builds/184586#01849c10-3e46-47cc-90bc-852cfee2d371/292-314) component to `CloudCtaBanner`
- Use [Text](https://buildkite.com/sourcegraph/sourcegraph/builds/184586#01849c10-3e46-47cc-90bc-852cfee2d371/292-315) instead of `p`

2022-11-22 00:43 UTC, st0nebraker commented on client/web/src/marketing/components/CloudCTABanner.tsx
> +        </p>
Thanks! Ok buildkite is good now ✅

2022-11-22 00:50 UTC, felixfbecker commented on client/web/src/enterprise/insights/pages/landing/dot-com-get-started/CodeInsightsDotComGetStarted.tsx
> +                            <Link to="https://signup.sourcegraph.com/?p=insights" onClick={() => telemetryService.log('ClickedOnCloudCTA', { url: window.location.href })}>
`TelemetryService`

2022-11-22 17:25 UTC, bretthayes approved these changes

2022-11-22 19:19 UTC, merged

2022-11-22 22:20 UTC, st0nebraker commented
Hey @kelsey-brown - This PR got merged in today. Just adds 4 more `ClickedOnCloudCTA` events from new Cloud CTAs on the Batch Changes & Code Insights product pages. Also ensured all `ClickedOnCloudCTA` events open in a new window so the event gets logged appropriately. Just an FYI. I'm not changing this status to `measuring` since these are minor tweaks I imagine you don't need to do much off of.

2022-11-23 15:37 UTC, kelsey-brown commented
Thanks @st0nebraker! Useful because I can attribute more clicks to the fact that we have more CTAs.