Log external requests
sourcegraph/sourcegraph pull request #44286
Opened 2022-11-11 14:15 UTC by vdavid

- Closes https://github.com/sourcegraph/sourcegraph/issues/44027 eventually

This is very much WIP

Progress so far:
- Added `RedisLoggerMiddleware`
- Added `RedisLogItem` with a preliminary format
- At this point, it **successfully logs** to Redis
- It seems to be causing some errors—I see weird stuff in the console
- Stack trace parsing is completely missing

## Test plan

TODO: No test plan yet.

2022-11-24 09:59 UTC, mrnugget reviewed
I did a first pass and left a bunch of comments with suggestions/questions. I didn't look at the frontend code yet, because I assume that my comments on GraphQL schema etc. might change frontend.

One comment on the screenshot though: can we make this _really dense_? 😄 We send _a lot_ of requests and I think we should maybe have a single line per request and then uncollapse on click or something.

I'm very excited for this! :)

2022-11-24 09:59 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +        lastKey: String
It'd be consistent with the rest of our API if you name this `after`. See: https://sourcegraph.sourcegraph.com/search?q=context:global+content:%22after:+String%22+file:schema%5C.graphql+repo:sourcegraph%24&patternType=standard&sm=0&groupBy=repo

2022-11-24 09:59 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    ): [OutboundRequest!]!
Just like the comment on `lastKey`: I think `OutBoundRequestConnection` would be more idiomatic to return. Especially since you can then return the `pageInfo` with the next cursor to use.

2022-11-24 09:59 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +}
Doesn't have to be in this PR, but just FYI: we also have this type https://github.com/sourcegraph/sourcegraph/blob/7d234ffe2f73177f6bcc8418499397fc4c71f858/cmd/frontend/graphqlbackend/schema.graphql#L8112-L8125

We could probably replace `WebhookLogHeader` with `HTTPHeader` in a follow-up PR.

2022-11-24 09:59 UTC, mrnugget commented on enterprise/internal/authz/syncjobs/records_reader.go
> +		ListKeys(ctx *context.Context, prefix string) ([]string, error)
I don't think we should use pointers for a `context.Context` here. It's an identity-less object that can be wrapped/unwrapped and no caller/callee should care about a specific instance.

If you want to make it optional I suggest defining a different method.

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/client.go
> +func IsRiskyKey(key string) bool {
Short docstring please :)

Also: would `IsRiskyHeader` be a better name? Key is awfully generic

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/external.go
> +}
I think you want `atomic.Int*` here :) See [these examples](https://sourcegraph.sourcegraph.com/search?q=context:global+atomic.Int+repo:sourcegraph&patternType=standard&sm=0&groupBy=repo)

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +				requestBody, _ = io.ReadAll(req.Body)
Do you need to close the `Body` then? Does this empty the `req.Body` or does it preserve it?

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +
```suggestion
```

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +			deleteExcessItems()
Hmmm, should we really do that in the request path? Or if we keep it here can we do that in a [`MULTI`](https://redis.io/commands/multi/) together with the `Set`?

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +	var items []*types.OutboundRequestLogItem
```suggestion
	items := make([]*types.OutboundRequestLogItem, 0, len(rawItems))
```

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +	all, err := redisCache.ListKeys(nil, keyPrefix)
The placeholder is `context.Background()` if you don't have a contex tied to, say, a user request.

```suggestion
	all, err := redisCache.ListKeys(context.Background(), keyPrefix)
```

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +func getAllValuesAfter(redisCache *rcache.Cache, keyPrefix string, lastKey *string, limit int) ([][]byte, error) {
Go convention is to treat `""` as "nothing" in case of strings. So in this case I'd use this

```suggestion
func getAllValuesAfter(redisCache *rcache.Cache, keyPrefix string, lastKey string, limit int) ([][]byte, error) {
```

and then check `if lastKey != ""`

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +func GetAllOutboundRequestLogItemsAfter(lastKey *string, limit int) ([]*types.OutboundRequestLogItem, error) {
Have you considered using a [Redis list](https://redis.io/docs/data-types/lists/) as the data type instead of single keys? I wonder whether that won't make things easier.

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +			if key > *lastKey {
So this is just comparing strings, right?

2022-11-24 09:59 UTC, mrnugget commented on internal/rcache/rcache.go
> +	} else {
See above, I think you should just pass in `context.Background()` instead of making `ctx` optional

2022-11-24 09:59 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +		return DoerFunc(func(req *http.Request) (*http.Response, error) {
I would assume that if logging-to-redis was turned off that this middleware would be a noop. What it does instead is to save the request and then delete it immediately, right?

2022-11-24 10:36 UTC, vdavid commented on enterprise/internal/authz/syncjobs/records_reader.go
> +		ListKeys(ctx *context.Context, prefix string) ([]string, error)
That's exactly the conclusion I came to last night after going to bed 😄
Yes, the original intention was to make it optional, but the solution didn't feel right.

Also, I'm not big on deciding pointers vs no pointers in Go yet. This is probably the area where I feel a lack of knowledge of best practices the most often in Go.

2022-11-24 11:03 UTC, vdavid commented on cmd/frontend/graphqlbackend/schema.graphql
> +    ): [OutboundRequest!]!
Hmm, at first I thought this was just a rename, but if you mean that I should change the structure to [WebhookLogConnection's](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L8000) then my decision not to do that was intentional.

We always want to return all items (optionally filtered by "after"), we have no pagination and the total count is pretty redundant as well because we're always getting the items. So while I realized that was the most common solution, in this case I saw no value added by matching the format of `WebhookLogConnection`.
On the other hand, I found examples like [pendingInvitations](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L1609) and [outOfBandMigrations](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L1513) which followed the pattern I used, so this also seemed idiomatic.
WDYT?

2022-11-24 12:12 UTC, vdavid commented on internal/httpcli/external.go
> +}
Why is that?
I've looked into `atomic.Int64` but I don't understand the benefit in this case. We use a lock around the update operation, which should make it thread-safe, regardless of whether the update itself is atomic or non-atomic.
Isn't that so?
I'll update it because it's probably safe and good practice if you're suggesting it (and definitely won't break anything), but I'm curious about what I'm missing.

2022-11-24 12:25 UTC, mrnugget commented on internal/httpcli/external.go
> +}
If I understand the code correctly you want a thread-safe integer that's updated and read. That's what atomic.Int is made for. Sure, you can use a struct with the int and the lock, but it's essentially the same thing as atomic.Int. I suggested it because I assume it's less code to use atomic.Int.

2022-11-24 12:27 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    ): [OutboundRequest!]!
Fair enough! I assumed `lastKey` _is_ cursor-based pagination, since it effectively works like `endCursor`.

2022-11-24 12:29 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    key: String!
```suggestion
    id: ID!
```

That would be more idiomatic. It should then [also implement the `Node` interface](https://sourcegraph.sourcegraph.com/search?q=context:global+implements+Node+file:schema+repo:sourcegraph%24&patternType=standard&sm=0&groupBy=repo) so it can be retrieved by ID. If you then add a "by id" resolver [here](https://github.com/sourcegraph/sourcegraph/blob/79c786a929cceadf15b1ca9c5cae88537a62d255/cmd/frontend/graphqlbackend/graphqlbackend.go#L567) it works just like any other Node in our API.

2022-11-24 12:33 UTC, vdavid commented on internal/httpcli/external.go
> +}
Honestly, I think I'm safe to do this without a lock or `atomic`. It's a single primitive value assignment for `set` and a primitive read for `get`; they should both be atomic already.
It was a copy&paste mistake I made when I used `tlsExternalConfig` as an example, where they use a struct rather than a primitive.

2022-11-24 12:57 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +				requestBody, _ = io.ReadAll(req.Body)
Nice catch! Yeah, it probably messed with the read pointer of `Body`. Not sure if we're using `req` after this point for anything else, but even if not, we _may_ use it in the future. So `req.GetBody()` (which works with a **copy** of the body) seems to be the correct way to go.
I also found that `Copy` is often a better choice than `ReadAll` for performance, but in this case, `ReadAll` looks good to me.

Closing the stream: It's a `ReadCloser`, so it seems to need no closing. (As a Go rookie, I'm just discovering these things, hence the underconfident phrasing. 🙂 Btw, thanks for pointing out these things! They help me a lot to develop a good eye for things to watch out for in Go.)

2022-11-24 13:06 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +			deleteExcessItems()
I was wondering where to do the deletion; my notes around my decision-making about this are [here](https://docs.google.com/document/d/1LZKjmVUh6jIwX_NQiItaIoCSBwTq4neJfvA1CmNBJmI/edit#bookmark=id.45nszoxmrlko). Could be done at "get", but that sounds weird and inefficient. It could be time-triggered, like a background cleanup process, but that seemed like blatant overengineering. And then there is "set", which also ensures that there are never more than `{limit}` items stored for more than what's probably a few milliseconds.

MULTI is an option, but check out my train of thought in the doc: my conclusion was that there was no harm done if this is done as a non-atomic transaction. And the benefit of this implementation is that it's very simple to read/understand.

My suggestion is that I leave a comment in the code for this block to alleviate doubt about this in the future (along the lines of "This is okay to do without MULTI because....")

What do you think?

2022-11-24 13:16 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +	var items []*types.OutboundRequestLogItem
Ah, nice catch. I've tried to be mindful to allocate memory in advance where I can, but apparently missed this one.

It's also instructional because even if I didn't miss this one, I'd have done `items := make([]*types.OutboundRequestLogItem, len(rawItems))` (set the size, not the capacity), and then `items[index] = &item` rather than appending.
Setting the capacity seems better because it probably saves the computer setting each pointer to `nil` first.

2022-11-24 13:22 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +			deleteExcessItems()
Happy with that, yeah. As I wrote in another comment: using Redis' `list` data structure might be something to look at too.

2022-11-24 13:23 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +	var items []*types.OutboundRequestLogItem
```
items := make([]*types.OutboundRequestLogItem, len(rawItems))
```

That also works, but would require you to use `for i, ... {` in the loop and then do `items[i]` to assign. Otherwise you'll end up with `len(rawItems)` null elements and the ones you appended.

2022-11-24 13:25 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +	var items []*types.OutboundRequestLogItem
Yup, that's what I meant above by `then items[index] = &item rather than appending`. I fell into this trap yesterday when I wrote tests, I was like whaat why is there an empty item in Redis?? That was also an instructional 20 minutes while I figured it out :D

2022-11-24 13:30 UTC, vdavid commented on internal/httpcli/external.go
> +}
Whoa, mind=blown. I imagine getting that int only halfway set when read 😬 Probably not a concern for this value that will
- very rarely change
- always be a fairly small number (probably only the last byte being set to non-zero ever)
- not cause harm even if it's imprecise when read
but knowing that I can't rely on primitives not guaranteed to be thread-safe is a very important takeaway, so thank you!
Will make this atomic to be extra safe.

2022-11-24 13:42 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +			if key > *lastKey {
Yes. It's a fixed prefix and the date/time in ISO format so it's always lexicographically ascending by time. StackOverflow said `a > b` was safe to use and more performant than `strings.Compare()` so I went with it.

2022-11-24 13:51 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +func GetAllOutboundRequestLogItemsAfter(lastKey *string, limit int) ([]*types.OutboundRequestLogItem, error) {
In summary: yes and no, and the reason for this choice is historical.

I considered using lists in the very beginning, but then the expectation might have been to store 50ish item _per request type_ (so, potentially much more items than I do now), and perhaps categorized by other factors (e.g. successful/failed requests). For that case, I wanted to be able to get a filtered subset of the items by prefixes and postfixes, and a Redis list can't do that.

Then it became only 50ish items, and we're always getting all of them. For this scenario, a single Redis list makes sense, and would perhaps make a few things easier, like trimming it with `LTRIM`, making it a better choice.
However, as this solution is already implemented and tested, I'm not sure if it's worth investing time in reimplementing the storage layer with a Redis list.
My suggestion is to stay with the current implementation.
WDYT?

2022-11-24 13:56 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +		return DoerFunc(func(req *http.Request) (*http.Response, error) {
Ah, true, thank you! I added an `if limit==0` check to the getter, but not the setter.
How much fun this function could've had saving and deleting all those items. 😿 
I've added the check now.

2022-11-24 14:47 UTC, vdavid commented on cmd/frontend/graphqlbackend/schema.graphql
> +    key: String!
It was a conscious decision (I called it "id" first to be idiomatic, but then it just started getting weird and I standardized the terminology on "key").
I understand that it's good practice, so I've implemented the `Node` interface now. But TBH I can't see the immediate benefit; it feels a bit like introducing dead code.  I could also introduce a graphQL endpoint to make the code reachable, but then that'd be another piece of dead code. So if you can give more reasoning, it helps.

2022-11-24 14:51 UTC, vdavid commented
@mrnugget I’ve responded to all your comments so far, and pushed all my commits. I’ll now work on the UI, remembering your ask “can we make this really dense? 😄” which also makes a lot of sense to me.

2022-11-24 16:11 UTC, vdavid commented
UI evolution:

Yesterday:
<img width="1153" alt="CleanShot 2022-11-24 at 01 25 39@2x" src="https://user-images.githubusercontent.com/2552265/203668121-5ac23b9f-944c-480c-b376-9ed23938cc55.png">

Today:
<img width="1144" alt="CleanShot 2022-11-24 at 17 09 28@2x" src="https://user-images.githubusercontent.com/2552265/203827969-a8733162-a5b2-4744-b5f4-aff33d3169ea.png">

Tomorrow:
✨ ✨ ✨

2022-11-24 16:13 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    key: String!
Hmmm, yeah, I'm with you, but I do think there's value in it, since it doesn't cost _that_ much put it makes frontend code much easier to develop later.

2022-11-24 16:15 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +func GetAllOutboundRequestLogItemsAfter(lastKey *string, limit int) ([]*types.OutboundRequestLogItem, error) {
Fine with me! If it doesn't buy you much, sure. We're also talking about tiny numbers, so Redis probably doesn't care.

2022-11-24 18:07 UTC, bobheadxi requested changes
Reviewed the bits pertaining to the redis cache :)

2022-11-24 18:07 UTC, bobheadxi commented on internal/httpcli/redis_logger_middleware.go
> +	all, err := redisCache.ListKeysWithPrefix(context.Background(), keyPrefix)
context should be propagated IMO, we have context available at the callsite of `GetAllOutboundRequestLogItemsAfter`

2022-11-24 18:07 UTC, bobheadxi commented on internal/rcache/rcache.go
> +	}(c)
If we have a real error from the connection, and `Close` errors, we discard the arguably more useful error in favour of the `Close` error. If we want to keep the error from `Close` we should only assign it to `err` if `err` is nil.

2022-11-24 18:07 UTC, bobheadxi commented on internal/httpcli/redis_logger_middleware.go
> +const keyPrefix = "outbound:"
The `redisCache` instance is used for caching results of APIs that support conditional requests: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@a49c8c8b7a374deafb6841723f0afa535561c0b6/-/blob/internal/httpcli/client.go?L86-92

If you want to store a different type of data, in this case outbound requests, you should create a new `outboundRequestsRedisCache` and set a site-configurable TTL for it. Then you don't need to implement the various `prefix` variants of functions on the redis cache - each cache instance is already designed to represent a prefixed namespace within the cache, and creating new ones is not expensive or anything

2022-11-24 18:17 UTC, vdavid commented
Wow, awesome tips, @bobheadxi, thank you! I'll fix them tomorrow!

2022-11-24 18:27 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: String
Should this be `gql.DateTime`? In practice we want users to provide a timestamp since the redis keys are all timestamps, that they are compared as strings is an implementation detail

2022-11-25 08:14 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: String
I think it's more an opaque `after` cursor, as I argued above. I think exposing it as DateTime might be a bit leaky, since it's irrelevant for the client. The client wants to say "give me the requests after this one if there are new ones" and shouldn't have to worry about timestamps etc., IMHO

2022-11-25 09:43 UTC, vdavid commented on internal/rcache/rcache.go
> +		if ctx != nil {
Absolutely! Thanks for spotting that! It was leftover code from the transient state when I passed the context by reference. (But then Thorsten pointed out that was probably not the right choice, so I reverted it, but this remained.)

Btw, I also reverted the rest of my changes to `ListKeys()`'s interface, and that's why I didn't reach out to you in the end. Thank you for doing the review anyway, you added some great points!

2022-11-25 09:47 UTC, vdavid commented on internal/rcache/rcache.go
> +	}(c)
@bobheadxi My intention was exactly this (only report the `Close` error if we have no previous errors), and I think the code already does what you say. See the `if ... err == nil` check above. I'm pretty new to Go, maybe I misunderstand the syntax or something?

2022-11-25 10:31 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +const keyPrefix = "outbound:"
I absolutely agree, did these changes, and the code is of course a lot cleaner this way.

The only thing is that I don't see much value in making the TTL site-configurable. TTL for `redisCache` is also [hard-coded](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/httpcli/client.go?L84). If customers need to configure it later, it's very easy to add a setting for this, so I'll just hard code this for now.

2022-11-25 10:41 UTC, vdavid commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: String
I don't have a strong stance on this, but I never intended to provide a "give me the items after date X" feature.
I even [considered](https://docs.google.com/document/d/1LZKjmVUh6jIwX_NQiItaIoCSBwTq4neJfvA1CmNBJmI/edit#bookmark=id.1ej1q0pxf2eb) just an incremental int64 key; I went with dates because I found them better suited for the purpose, but the intention is still only to have "some incremental value", not a date.

2022-11-25 11:42 UTC, mrnugget approved these changes

2022-11-25 11:42 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +        startPolling(OUTBOUND_REQUESTS_PAGE_POLL_INTERVAL)
Should the `startPolling` go into the `then`?

2022-11-25 11:42 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
Hmmm, adding to our previous conversation: I'm pretty sure that if you use `after: String` and turn your GraphQL result into a proper connection (with `pageInfo`) you could use `useConnection` here and then "simply" call `fetchMore`.

But not super sure. Just wanted to flag it (again! I know)

2022-11-25 11:42 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                    )
Should we make these GraphQL arguments to the GraphQL query and then do filtering client side?

2022-11-25 11:42 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                        <strong>The list updates every five seconds.</strong>
Should we add a `{loading && <LoadingSpinner inline={true} />}` in here?

2022-11-25 11:42 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    return headers ? (
Nit: I think you can do `if (!headers) { return null }`

2022-11-25 11:42 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    Get a log of the latest outbound external requests
I'd add that this is for site-admins only.(See other places in the schema where we have that disclaimer)

2022-11-25 11:42 UTC, mrnugget commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +	result, err := httpcli.GetAllOutboundRequestLogItemsAfter(ctx, after, conf.Get().OutboundRequestLogLimit)
Why do you need to pass `conf.Get().OutboundRequestLogLimit` in? Inside `httpcli` there's `outboundRequestLogLimit`, the `atomic.int32`, no?

2022-11-25 11:42 UTC, mrnugget commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +	item, _ := httpcli.GetOutboundRequestLogItem(string(id))
Don't you need to unmarshal the ID first? In your `ID()` method you marshal it, which adds `"OutboundRequest:` to it and then base64 encodes it. Usually we unmarshal them in the resolver layer again.

2022-11-25 11:42 UTC, mrnugget commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +}
Nit: I'd turn the really short methods here into one-liners :)

2022-11-25 11:42 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +	creatorStackFrame, _ := getFrames(4).Next()
Do we (can we) filter them so that `httpcli` doesn't show up? Like here: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/dbconn/dynamic_metadata.go?L106-117

2022-11-25 11:54 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +        startPolling(OUTBOUND_REQUESTS_PAGE_POLL_INTERVAL)
No. I know it looks weird. To avoid confusion, I've added this comment:

        // Workaround for https://github.com/apollographql/apollo-client/issues/3053 to update the variables.
        // Weirdly enough, we don't need to wait for refetch() to complete before restarting polling.
        // See http://www.petecorey.com/blog/2019/09/23/apollo-quirks-polling-after-refetching-with-new-variables/

2022-11-25 14:05 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                    )
Do you mean **server**-side? Asking because we already filter client-side 😄 
I don't see the value of filtering server-side. Or to be more precise, I think it doesn't matter much for now, both options work, and client-side filtering came with less code.

2022-11-25 14:10 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                        <strong>The list updates every five seconds.</strong>
I could, but `{loading && <LoadingSpinner />` is already there [a few lines below](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dv/log-outgoing-requests/-/blob/client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx?L144).
I noticed that our different pages put the loading spinner at different levels, e.g. migrations page [puts it to the top](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dv/log-outgoing-requests/-/blob/client/web/src/site-admin/SiteAdminMigrationsPage.tsx?L137) while the repos page puts in [only for the list](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dv/log-outgoing-requests/-/blob/client/web/src/site-admin/SiteAdminRepositoriesPage.tsx?L324%3A41-324%3A49). I preferred the latter because it seemed more respectful (less controlling) toward the site admin, letting them read about the purpose of the page before enabling the feature.

2022-11-25 14:14 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    return headers ? (
Yeah, I could, that would be the Go way for sure 😄

I see them as equally good, and I personally prefer ternaries because they are more concise and more functional-style. I don't think we have a coding style guide item for this, so I'd prefer to leave it like this.

If you have a reason why it'd be the preferred way, I'm happy to change it plus consider changing my general preference for the future.

2022-11-25 14:15 UTC, vdavid commented on cmd/frontend/graphqlbackend/schema.graphql
> +    Get a log of the latest outbound external requests
Oh, thank you, I didn't notice this disclaimer before!

2022-11-25 14:20 UTC, vdavid commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +	result, err := httpcli.GetAllOutboundRequestLogItemsAfter(ctx, after, conf.Get().OutboundRequestLogLimit)
It's because I don't like that hacky solution for pushing the limit info from `conf` to `httpcli`, and wanted to avoid using it where that piece of info was available from another source. But now that we have the hacky thing there, I guess it's the same, and you raising it probably indicates that it looks weird, so I've changed it according to your suggestion.

2022-11-25 14:25 UTC, vdavid commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +	item, _ := httpcli.GetOutboundRequestLogItem(string(id))
Ah, nice catch. Yes, it's base64-encoded at this point, and needs decoding. I probably would've noticed this in my tests, but the comment probably saved me a few minutes of figuring out why filtering is not working properly :)

2022-11-25 14:27 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                    )
Ah, yes, meant server-side of course. Okay, if you don't think it's worth it, then let's keep it client-side.

2022-11-25 14:27 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                        <strong>The list updates every five seconds.</strong>
Makes sense!

2022-11-25 14:27 UTC, vdavid commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +}
Ah, I didn't know that was the preferred way. I've checked a few examples but those were not one-lines. Now I can see that in a few cases we're using one-liners in our codebase. Fine by me, removed some linebreaks!

2022-11-25 14:28 UTC, mrnugget commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +	result, err := httpcli.GetAllOutboundRequestLogItemsAfter(ctx, after, conf.Get().OutboundRequestLogLimit)
Makes sense!

2022-11-25 14:31 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +	creatorStackFrame, _ := getFrames(4).Next()
Sure, I definitely can, I just wasn't sure which one is more helpful info to show:
a.) the caller of `NewExternalClientFactory` (which, in some cases, is `internal/httpcli/client.go:96`)
b.) the caller of the `internal/httpcli` package.

I went with a.), but I can easily go with b.) – I guess your stance is that b.) is more useful?

2022-11-25 14:45 UTC, mrnugget commented on internal/httpcli/redis_logger_middleware.go
> +	creatorStackFrame, _ := getFrames(4).Next()
Hmmmm. I think I want to know where the request comes from, not where the client was instantiated, you know? But now that you mention it, both are useful.

2022-11-25 14:45 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
This is a tough one.
I wasn't aware of this standard: https://relay.dev/graphql/connections.htm, and I like it a lot. I also like our `useConnection` implementation—I wasn't familiar with it before.

But I'm not sure it's well-suited for this use case. `useConnection` seems to handle the case when there are 1,000 items, and we only want to show a portion of them and paginate the rest.
Here, we want to show _all_ items (`hasNextPage` is always false) and keep on polling for new items only.
Based on this, I _think_ `useQuery` as a LEGO piece is better suited for the solution we want than `useConnection`, so I'd keep this until we want to develop it into a more complex solution.
What do you think about this?

2022-11-25 14:45 UTC, mrnugget commented on cmd/frontend/graphqlbackend/outbound_requests.go
> +}
I might be peculiar in my tastes here 😛 But I'm selfishly trying to indoctrinate you while you're fresh to Go

2022-11-25 14:47 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +	creatorStackFrame, _ := getFrames(4).Next()
I agree that knowing where the call comes from is more useful. I just thought it's also worth logging which client it uses.

2022-11-25 14:47 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
Yeah, exactly what I thought. You're not really pagination through a connection. So you'd have to fight `useConnection`, which sucks (I've done it)

That being said there's a "best of both worlds" approach possible maybe: structure the GraphQL API so you have a `OutboundRequestConnection` with `pageInfo` and all of that, but then still use `useQuery` here. Up to you. This is merely a suggestion and I understand if you don't want to change it now.

2022-11-25 15:07 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
I don't mind changing it if it brings value. But I'm not sure what value it brings. It'd denfinitely make the API more hackable for customers, but I don't know how much our customers actually hack on top of our APIs, and how much we want to serve them.

**Because:**
 - **if** we strictly want to serve _our_ client, than all the `totalCount`, `pageInfo`, and even the Node compatibility are unnecessary and pretty much just add dead code because we're not using these features.
 - **But** if our intention is to make our API hackable because we expect customers to build their own dashboards on top of them (and we want to actively support this) then of course! let's add all these parts to make this interface compatible with GraphQL Cursor Connections, and make it similar to our majority of endpoints.

**My guess** is that we don't have a strong stance on this because we have these nine existing query endpoints where we one can query several of _something_ but the result will not match the Cursor Connections format:
<img width="826" alt="CleanShot 2022-11-25 at 15 59 54@2x" src="https://user-images.githubusercontent.com/2552265/204011506-3b5cddab-2ab7-4204-9715-ed35842b2900.png">

This decision was not entirely conscious on my part. When I implemented the API, I only considered _our_ client and not hackability. Hackability only came to mind later when your suggestions pushed the API toward generalization, and I started to wonder about the reasons, and the top guess on my mind is hackability for customers.

So, questions:
1. Why would you say `pageInfo` would be useful to include?
2. Do you think it's worth the cost of introducing (and later, having to maintain) API features that our client doesn't use?

Sorry for the long message on a seemingly unimportant topic, but it would be very useful for me to understand your thinking around this.

2022-11-25 15:25 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
> So, questions:
> Why would you say pageInfo would be useful to include?

You are already filtering (`lastKey`) and you return a list of things. That makes me think it's awfully close to all the other connections we have.

In your screenshot only 5 of those are "arrays" of things and I'd argue that `savedSearches` and the feature-flag ones should be connections. 

> Do you think it's worth the cost of introducing (and later, having to maintain) API features that our client doesn't use?

The cost is 10-20 lines of Go, possibly less. Examples:

https://github.com/sourcegraph/sourcegraph/blob/b7318c2322f3688ecc2f25a28ce3291f3a67576e/cmd/frontend/graphqlbackend/access_tokens.go#L237-L248

https://github.com/sourcegraph/sourcegraph/blob/41d1a47f3fd8a28a17fab4da84bc02336438ee37/cmd/frontend/graphqlbackend/executor_secret_connection.go#L37-L54

In your case the code would be simpler.

So to me these are not features for features sake (I don't care about our customers using _this_ here), but more for keeping things consistent with the rest of our API. We already have a pretty inconsistent API (yes, I do think most of the examples you listed should've been connections) but for the relatively small price of 10-20 lines we could make it a tiny bit more consistent.

If you're feeling strongly about not doing it, that's fine, I'm not going to block on this.

2022-11-25 16:17 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
Thanks for the explanation! It makes sense, and the amount of code needed is less than I thought. So I'm happy to make the change.

Btw:

> Yeah, exactly what I thought. You're not really pagination through a connection. So you'd have to fight useConnection, which sucks (I've done it)

`useConnection` is probably just getting even worse for this purpose: https://github.com/sourcegraph/sourcegraph/pull/44703 – so happy that I went with `useQuery`.

2022-11-25 16:43 UTC, philipp-spiess reviewed
Sorry I saw you mentioned the connection/pagination stuff so I got curious 😅  I’m mostly asking out of curiosity because I don't fully understand what's going on yet.

2022-11-25 16:43 UTC, philipp-spiess commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +        startPolling(OUTBOUND_REQUESTS_PAGE_POLL_INTERVAL)
This part needs to be inside a `useEffect` otherwise you risk refetching often when something outside of this component re-renders it for unknown reasons.

Also I’m not quite sure what's going on here:

- We make a network request and get back some data and some items.
   - In case there are no items, we continue to poll the same request
   - However if there are items, we update the network request with a new `after` cursor so that we only get _newer_ items. 

Is this correct?

What I miss is where do we append items to the existing array? Do they just disappear? 🤔

2022-11-25 16:43 UTC, philipp-spiess commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
I’m not quite sure why we use a `FilteredConnection` here if we don't have a pagination of some form (maybe I misread the comments)?

2022-11-25 16:43 UTC, philipp-spiess commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                            (!args.query || matchesString(request, args.query)) &&
The number of items is somehow capped, right? Otherwise this might get really expensive.

2022-11-25 16:43 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/schema.graphql
> +    ): [OutboundRequest!]!
> We always want to return all items (optionally filtered by "after")

Is this because the backend caps the responses automatically? What if we ever change the backend and decide to keep a longer history of these requests?

2022-11-25 16:48 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
@philipp-spiess, that's correct, we don't have pagination.
@mrnugget's reason, if I understand correctly, was consistency: to make the endpoint more similar to other endpoints that respond with a set of items.

2022-11-25 16:54 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +        startPolling(OUTBOUND_REQUESTS_PAGE_POLL_INTERVAL)
Thanks, I've wrapped it into a `useEffect`!

You are absolutely right that this is weird! @mrnugget also didn't get this at first, so I added [this comment](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dv/log-outgoing-requests/-/blob/client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx?L98) to avoid further confusion. Basically, the `refetch` is only there to apply the change to the variables, that's all. We're throwing away the result for the `refetch` (which is, by the way, most likely empty because we've just loaded the data milliseconds before it—but it doesn't actually matter whether it's empty or not).
We're fetching the data with `useQuery` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dv/log-outgoing-requests/-/blob/client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx?L84).

2022-11-25 16:56 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                            (!args.query || matchesString(request, args.query)) &&
> I’m not quite sure why we use a `FilteredConnection` here if we don't have a pagination of some form (maybe I misread the comments)?

Just to provide the dropdown filter for success/failure, and the free-text search pretty much for free, without doing a custom implementation of a data display component with filters etc.

> The number of items is somehow capped, right? Otherwise this might get really expensive.

Yes, it's capped at a limit set by the admin, 50 being the suggested default.

2022-11-25 16:57 UTC, philipp-spiess commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
@vdavid Consistency for the filter components? Yeah that part is still missing and being [worked on right now by Sara](https://www.figma.com/file/bNslgBGdDYj7DSk25M47Nv/Strategic-FE-Audit---Sorting?node-id=2263%3A2902&t=Yp8h3kyvlSrBVXqq-1)

For the rest take a look at `<ConnectionList/>` and `<ConnectionContainer/>` which re-implement the UI in more reusable pieces outside of the `FilteredConnection`

2022-11-25 16:58 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                            (!args.query || matchesString(request, args.query)) &&
> > We always want to return all items (optionally filtered by "after")

> Is this because the backend caps the responses automatically? What if we ever change the backend and decide to keep a longer history of these requests?

Yes, the backend only stores a number of items (N=50 by default), and returns all of them for the first call (`after` being `null`), then only the ones with IDs larger than `after`. Even if the site admin sets it to something like 500, the data is transmitted only once, and each piece is fairly small.

2022-11-25 16:59 UTC, philipp-spiess commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +        startPolling(OUTBOUND_REQUESTS_PAGE_POLL_INTERVAL)
Thanks! Polling in Apollo is such a mess 🤕

2022-11-25 17:00 UTC, philipp-spiess commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                            (!args.query || matchesString(request, args.query)) &&
> Just to provide the dropdown filter for success/failure, and the free-text search pretty much for free, without doing a custom implementation of a data display component with filters etc.

Makes sense! Yeah we really need the new filter components to be usable in a standalone way 😅

2022-11-25 17:06 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
@philipp-spiess 
> Consistency for the filter components?

No, consistency for the GraphQL API. The majority of our API endpoints that return a set of _something_ follow this standard: https://relay.dev/graphql/connections.htm. Only a handful of them don't, and Thorsten's point was that they should follow it, to make our endpoints consistent with each other. His point was that it's only about 10–20 extra code lines to make the current interface be compatible with the pattern we use for most of similar endpoints.
And that even if we do no pagination or use the returned pieces of data for now (`hasNextPage` would be just a hand-coded `false`), he sees value in making it similar.
It's still up for debate.

2022-11-25 17:09 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                            (!args.query || matchesString(request, args.query)) &&
Haha, I just proved that `FilteredConnection` _can_ be abused to do client-side filtering 😆 
The only annoying part is that ugly `delay(200)` [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@dv/log-outgoing-requests/-/blob/client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx?L112).

2022-11-25 18:07 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: String
Ah, in that case can we change the docstring here to match other instances in the GraphQL API where we have this type of `after` cursor? e.g. 

```
        """
        An opaque cursor that is used for pagination.
        """
        after: String
```

2022-11-25 18:09 UTC, bobheadxi commented on internal/httpcli/redis_logger_middleware.go
> +const keyPrefix = "outbound:"
For reference, here's how I made a live-configurable TTL: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@81082be686593f286efe4febe54d3ec06df807cb/-/blob/enterprise/internal/authz/syncjobs/records_store.go?L44:1-63:2

We could potentially bundle this type of behaviour into `redisCache` itself as well. Configuration is useful in case e.g. the load of this is higher than expected, or you want a larger window for debugging data - up to you :)

2022-11-25 18:10 UTC, bobheadxi commented on internal/rcache/rcache.go
> +	}(c)
Ah yes my bad, I misread - it is correct as-is!

2022-11-25 18:17 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: String
```suggestion
        """
        An opaque cursor that is used for pagination.
        """
        after: String
```

2022-11-25 18:17 UTC, bobheadxi commented on internal/rcache/rcache.go
> +func (r *Cache) DeleteMulti(keys []string) {
nit: `GetMulti` uses varargs, so we might want to keep consistency here with varargs as well:

```suggestion
func (r *Cache) DeleteMulti(keys ...string) {
```

2022-11-25 18:17 UTC, bobheadxi commented on internal/httpcli/redis_logger_middleware.go
> +				log.Error(jsonErr)
`log.Error` does not create a log entry, it creates a log _field_, so you need a logger here to actually log this log field - see https://docs.sourcegraph.com/dev/how-to/add_logging#writing-log-messages

2022-11-25 18:18 UTC, bobheadxi commented on internal/httpcli/redis_logger_middleware.go
> +		log.Error(err)
Same here, `log.Error` does not create a log entry, only a log field.

2022-11-25 18:21 UTC, bobheadxi commented on internal/httpcli/redis_logger_middleware.go
> +				log.Error(jsonErr)
Logging in httpcli is complicated because clients are often instantiated as a package-level variable

2022-11-25 18:22 UTC, bobheadxi commented on internal/httpcli/redis_logger_middleware.go
> +				log.Error(jsonErr)
It's a bit complicated, but you could set the error in request context and have it be picked up by the logging middleware: https://github.com/sourcegraph/sourcegraph/blob/250437c8851968143d071f700ee26f70e8869a48/internal/httpcli/client.go#L296-L300

2022-11-28 13:45 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +const keyPrefix = "outbound:"
By default, only the last fifty requests are stored, and the intention is that they won't set this to a number higher than 1,000. Considering this, and that we are logging a request for each _ping_, the 7-day limit seems to be impossible to reach. So I think it's fine to leave it hard-coded.

2022-11-28 15:06 UTC, vdavid commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +    const lastId = items[items.length - 1]?.id ?? null
Based on what I've heard, I've altered the API to conform with the Cursor Connections spec.

2022-11-28 16:08 UTC, jhchabran commented on internal/httpcli/redis_logger_middleware.go
> +	creatorStackFrame, _ := getFrames(4).Next()
Just in case this might be useful, but you could take a look at this code https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/dbconn/dynamic_metadata.go?L59 which shows how to exclude certain package from the stacktrace.

2022-11-28 16:33 UTC, vdavid commented on internal/httpcli/redis_logger_middleware.go
> +	creatorStackFrame, _ := getFrames(4).Next()
Thanks, @jhchabran! Thorsten pointed me to Eric's PR that added this, so I'm familiar with what this code does.

I think what we have now is already useful. I prefer to release the feature and collect feedback on it before further improving it. Then we'll see what improvements we see as useful.

2022-11-29 10:05 UTC, philipp-spiess approved these changes
Frontend LGTM 🚀

2022-11-29 10:05 UTC, philipp-spiess commented on client/web/src/site-admin/SiteAdminOutboundRequestsPage.tsx
> +                            ●
Since this is only used for visual guidance, it should probably by wrapped with `<VisuallyHidden/>`

2022-11-29 11:08 UTC, merged

2022-11-29 13:45 UTC, eseliger reviewed
sorry for being late to the party! I had a few comments pending that I didn't get around finishing yet - nothing critical at all, just some comments/advice around GraphQL

2022-11-29 13:45 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +A single logged webhook delivery.
comment is wrong

2022-11-29 13:45 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +    A list of webhook logs.
comment is wrong

2022-11-29 13:45 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +    The total number of webhook logs in the connection.
comment is wrong

2022-11-29 13:45 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +    The request log item ID. Looks like "2021-01-01T00_00_00.000000" – Same as the Redis keys.
No need to explain the format here, ids are meant to be opaque. Also, should this type implement `Node`? Otherwise it can't be queried by ID.

2022-11-29 13:45 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +    duration: Float!
what's the unit of this float? ms? 
More so, does it have to be float or is ms resolution good enough for us?

2022-11-29 13:45 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: ID
`after` should be of type `String` usually as per relay, also would be good to stay consistent and also allow the `first: Int` property here - that'll help with the pagination effort

2022-11-29 13:45 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlbackend.go
> +		"OutboundRequest": func(ctx context.Context, id graphql.ID) (Node, error) {
This only works once the type also implements the `Node` interface in the graphql schema

2022-11-29 13:47 UTC, vdavid commented
@eseliger Thanks for the review! I'll fix these in a follow-up PR!

2022-11-29 16:09 UTC, vdavid commented on cmd/frontend/graphqlbackend/schema.graphql
> +    The request log item ID. Looks like "2021-01-01T00_00_00.000000" – Same as the Redis keys.
Oh, true. It actually already implements Node, just I missed the `implements Node` here.

2022-11-29 16:25 UTC, vdavid commented on cmd/frontend/graphqlbackend/schema.graphql
> +    duration: Float!
@eseliger Thanks for pointing it out! I also hate when an interface doesn't specify the unit of measurement; it's embarrassing that I feel into this trap now. It's **seconds**. Current precision is nanoseconds, but a millisecond resolution would probably be totally enough.

I'm seeing these solutions:
a.) Just clarify this in the comment. That is, add "The total time the request took to complete, **in seconds**."
b.) Change the name in the GraphQL to `durationInSeconds`
c.) Like b.), but also on the back end (it starts getting problematic here because to do this properly, I'd need to migrate the old format in Redis
d.) Change the graphQL and front-end to milliseconds and `int`, and change the name to `durationMs`.
e.) like d.), but back end also (also needs migrating old data)

I'd go with **a.)**. b.) and d.) are also fine with me if you believe it helps much. I probably won't put more effort into it than that
.
I'll go with a.) until you respond!

2022-11-29 16:32 UTC, vdavid commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: ID
> `after`

Hmm, it was a string at first, but when I implemented the Node interface I had to change it to ID because I needed to unmarshal the base64 encoding. I can look into how to make this a string if you believe this is a mistake.

> `first`

Context: In earlier stages, this endpoint only returned an array, I intentionally didn't want to match the [GraphQL Cursor Connection Spec](https://relay.dev/graphql/connections.htm) because it seemed like introducing too much dead code we won't use. But reviewers started requesting it to be more like our other endpoints, so by now it is almost like a normal endpoint. At this point, I agree that it'd make sense to add `first`, too. I'll add it!

2022-11-29 16:46 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +    duration: Float!
Yeah `d` feels good to me as it would also get around potential floating point precision issues, but if it's a ton of work don't bother with it.

2022-11-29 16:47 UTC, eseliger commented on cmd/frontend/graphqlbackend/schema.graphql
> +        after: ID
> Hmm, it was a string at first, but when I implemented the Node interface I had to change it to ID because I needed to unmarshal the base64 encoding. I can look into how to make this a string if you believe this is a mistake.

I think it should be as simple as doing `graphql.ID(arg.ID)` when passing to the unmarshaller, the reason is simply that it should not be a client concern nor should the client be encouraged to pass an ID to the after field, so we can simply change what the cursor contains later, should we have a need for that. Doing that case is pretty standard in our code base fwiw, so I don't feel bad about it :) 

> Context: In earlier stages, this endpoint only returned an array, I intentionally didn't want to match the [GraphQL Cursor Connection Spec](https://relay.dev/graphql/connections.htm) because it seemed like introducing too much dead code we won't use. But reviewers started requesting it to be more like our other endpoints, so by now it is almost like a normal endpoint. At this point, I agree that it'd make sense to add first, too. I'll add it!

Perfect, thanks!

2022-11-30 12:22 UTC, vdavid commented
@eseliger addressed everything in https://github.com/sourcegraph/sourcegraph/pull/44937
Thanks for taking the time for doing the review. The copy&paste mistakes were embarrassing, the rest was instructional!

2023-01-17 09:19 UTC, keegancsmith commented
@vdavid looking at the code here, is there a reason you don't use redis list operations? It looks like you are basically simulating that, but relying on `ListKeys` which has poor performance (we should document this better). ListKeys is essentially O(N), where N is the number of keys in _all_ of redis. The surprising complexity here is you call Scan on every single outgoing request. Redis list operations are much more appropriate for this data structure, and I see we have a FIFOList structure which looks like it will handle this use case? cc @burmudar

2023-01-17 09:37 UTC, burmudar commented
> 

@jhchabran ☝🏼

2023-01-17 09:43 UTC, jhchabran commented
@keegancsmith @vdavid yes, the `FIFOList` was build with that exact case in mind, as I had a pretty similar case with the slow graphql requests. A big convenience is that because the FIFOList is capped in capacity, you don't have to deal with expiring old keys.

2023-01-17 10:05 UTC, keegancsmith commented
@vdavid I might just port this code to `FIFOList` since the only users of rcache's `ListKeys`, `DeleteMulti`, `SetMulti` is this code. Likely faster to just port it and remove those functions instead of adding another API surface to support in "no redis" world.

2023-01-17 10:09 UTC, vdavid commented
@keegancsmith I agree. It was not the optimal choice and I considered switching to a LIST a few times during the feature development, but as the list is always short (usually 50 items, but there's a hard cap at 500) and it's an in-memory store, the gains didn't seem enough to justify the refactoring at the time. Thanks a lot if you're doing this, and let me know if I should jump in and help, happy to clean this up if it's a blocker.

2023-01-17 10:48 UTC, keegancsmith commented
Just to make it clearer, the gains are in fact worth it since ListKeys will look at _every key_ in the _entire_ redis store, not just the keys related to slow requests. These aren't marshalled over the wire luckily, since match runs server side on redis. But if I am not mistaken since redis is just a big hash table, it doesn't have an effecient range query / prefix matching on keys.