Migrate TreePage fetching to newer useConnection, show button to /commits after one load
sourcegraph/sourcegraph pull request #44300
Opened 2022-11-11 17:30 UTC by philipp-spiess

Closes #43685

## Test plan

2022-11-11 17:38 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+0.90 kb) | 0.01% (+0.90 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/tree-commits-improvements/compare-report.html;tab=live_object) for a full comparison between the commits 786984f and 4c90934 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-18 11:16 UTC, valerybugakov commented on client/web/src/repo/tree/TreePageContent.tsx
> +    const after = useMemo(() => (showOlderCommits ? null : formatISO(subYears(Date.now(), 1))), [showOlderCommits])
Minor question: could you share some context on why `useMemo` is required here? It seems that the result type is `string | null`, so it shouldn't mess up React hook dependencies, and the computation itself is relatively cheap.

2022-11-18 11:17 UTC, valerybugakov commented on client/web/src/repo/tree/TreePageContent.tsx
> +        refetchAllRef.current = refetchAll
Re-fetching looks tricky with the current setup of things 🙃

2022-11-18 11:18 UTC, valerybugakov approved these changes
Tested using [the PR preview deployment](https://sg-web-ps-tree-commits-improvements.onrender.com/github.com/sourcegraph/sourcegraph/-/commits). LGTM!

2022-11-18 13:02 UTC, AlicjaSuska requested changes
Thank you for making those changes @philipp-spiess! Overall, the main mechanism is working well. As per our conversation on slack - let's remove the 'no commits in this tree' message. It doesn't really make sense to show the 'empty-state-like' message at the end of the list.

Regarding adding commits page link to the sub-directories, let's create a separate issue for it outside of the scale audit.

2022-11-18 15:40 UTC, philipp-spiess commented on client/web/src/repo/tree/TreePageContent.tsx
> +    const after = useMemo(() => (showOlderCommits ? null : formatISO(subYears(Date.now(), 1))), [showOlderCommits])
The output here is using Date.now() which we want to be stable and not change after individual renders, otherwise this would update the query variables and that seems like something with undesired consequences.

2022-11-21 13:45 UTC, AlicjaSuska approved these changes
Thank you @philipp-spiess !

2022-11-21 14:01 UTC, merged