Move background repo syncing to ome goroutine
sourcegraph/sourcegraph pull request #44313
Opened 2022-11-11 23:24 UTC by varsanojidan

Closes https://github.com/sourcegraph/sourcegraph/issues/33496

## Test plan
Existing tests pass.

2022-11-11 23:29 UTC, varsanojidan commented
@ryanslade Tagging you explicitly to make sure this is the change you had in mind here: https://github.com/sourcegraph/sourcegraph/issues/33496

2022-11-14 09:30 UTC, ryanslade requested changes
Nice, thanks for taking this.

As we want to preserve the order and also handle spikes in jobs being added without blocking I think we should use a notification pattern as described in the comments.

2022-11-14 09:30 UTC, ryanslade commented on internal/repos/syncer.go
> +			return errors.Wrapf(ctx.Err(), "context done")
nit: Probably don't need to wrap the error here as the error itself will say pretty much the same thing.

2022-11-14 09:30 UTC, ryanslade commented on internal/repos/syncer.go
> +			syncFunc := func() {
nit: You don't need to create the `syncFunc` variable, you can do something like this:

```go
func() {
  // do tuff
}()
```

2022-11-14 09:30 UTC, ryanslade commented on internal/repos/syncer.go
> +	SyncRepoMap map[api.RepoID]struct{}
I think we need a mutex around this map and we're reading and writing to it from different goroutines.

2022-11-14 09:30 UTC, ryanslade commented on internal/repos/syncer.go
> +			s.SyncRepoChan <- BackgroundRepoSyncJob{
I think we can do something like this, which we've done in [other places already](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@39605962dde796b218a4f4066203223a258b855b/-/blob/enterprise/cmd/repo-updater/internal/authz/perms_syncer.go?L1038)

When added a job:

1. Check if job already added, if so do nothing.
2. If we need to process it, store job in slice (so that we know the order) and map to track that it was added.
3. Send notification that job was added. If we can't send, just skip the message since it means the worker is already processing something. ([See this](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@39605962dde796b218a4f4066203223a258b855b/-/blob/enterprise/cmd/repo-updater/internal/authz/request_queue.go?L95))

In the consumer:

In a loop:

1. Check for item in slice
2. If there, remove from slice and process it and go back to step 1
3. If nothing there, wait on  notification channel
4. Back to step 1

2022-11-14 13:22 UTC, mrnugget commented on internal/repos/syncer.go
> +			s.SyncRepoMap[repo.ID] = struct{}{}
If you keep it like that you'd need a lock around that. Otherwise you have a race condition here.

2022-11-14 13:23 UTC, mrnugget reviewed
I understand the problem this is trying to solve, but I do wonder: is adding yet another background goroutine and a set of in-memory data the best solution here?

I think we should slowly work towards https://github.com/sourcegraph/sourcegraph/issues/16197 and adding another background routine that's based on in-memory state of the repo-updater is going in the opposite direction.

For example: can't we use database-backed workers for this? With a `repo_sync_jobs` table, for example. And before we insert a new job we check, in a transaction, whether there is already a repo_sync_job with the given `repo_id` OR if there has been one added in last, say, 2min?

2022-11-21 10:58 UTC, ryanslade commented
I think @mrnugget is right. At some point we need to commit to the idea of storing repo management state in the database and guess there's no better time than the present. Especially since this particular change isn't strictly necessary it probably makes sense to drop it and instead find time to slowly start moving state into the db. 

@varsanojidan, sorry for the wasted work but at least you got to practice some Go concurrency and helped us make a decision here. I'll drop a note so that we can discuss this briefly in the retro today 😄

2022-11-21 11:22 UTC, mrnugget commented
btw. I plan on building a proof-of-concept this week/next for how we could move stuff to the database. I suspect it's harder than I think but possibly easier than some of you think :)

2022-11-21 13:24 UTC, varsanojidan commented
I agree with you guys I think in the grand scheme of things it makes a lot more sense to make repo-updater a lot rather than adding more goroutines on top of it, so I fully support the idea.

2022-11-21 15:54 UTC, closed without merging