allow batch changes BB server webhook to use top-level webhook handler
sourcegraph/sourcegraph pull request #44386
Opened 2022-11-14 23:21 UTC by mollylogue

Decided to do BB server first, then BB cloud will be in a second PR (both felt like too much for one).

## Test plan
Validated via unit tests, but I still need to do a full manual validation locally using ngrok (i.e. set up some BB server webhooks and validate that the original behavior still works, as well as using the new top level handler). (Why this is still a draft)

2022-11-15 17:50 UTC, mollylogue commented
I've successfully locally set up webhooks using both the legacy batch changes pattern for bb server, as well as the new top-level handler, and both seem to work. It looks like we're able to process the event in both cases and make it successfully to the underlying BB server handler for batch changes. I'm not entirely sure what behavior the webhook should trigger and how to validate that. It'd be nice if a batch changes teammate could weigh in here.

2022-11-16 06:08 UTC, sashaostrikov approved these changes
LGTM overall, nice!

Left a couple of comments

2022-11-16 06:08 UTC, sashaostrikov commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +func (h *WebhookRouter) HandleBitBucketServerWebhook(logger log.Logger, w http.ResponseWriter, r *http.Request, codeHostURN extsvc.CodeHostBaseURL, payload []byte) {
I'd rename the receiver to `r` for `router` :)
```suggestion
func (r *WebhookRouter) HandleBitBucketServerWebhook(logger log.Logger, w http.ResponseWriter, r *http.Request, codeHostURN extsvc.CodeHostBaseURL, payload []byte) {
```

2022-11-16 06:08 UTC, sashaostrikov commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +func (h *WebhookRouter) parseEvent(r *http.Request, payload []byte) (any, string, error) {
I'd rename the receiver to `r` for `router` :)

```suggestion
func (r *WebhookRouter) parseEvent(r *http.Request, payload []byte) (any, string, error) {
```

2022-11-16 06:08 UTC, sashaostrikov commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +func (h *WebhookRouter) handleBitbucketServerWebhook(logger log.Logger, w http.ResponseWriter, r *http.Request, urn extsvc.CodeHostBaseURL, secret string) {
I'd rename the receiver to `r` for `router` :)
```suggestion
func (r *WebhookRouter) handleBitbucketServerWebhook(logger log.Logger, w http.ResponseWriter, r *http.Request, urn extsvc.CodeHostBaseURL, secret string) {
```

2022-11-16 06:08 UTC, sashaostrikov commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +	var m error
this looks more canonical IMHO

```suggestion
	var err error
```

2022-11-16 06:08 UTC, sashaostrikov commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +			log15.Warn("Dropping Bitbucket Server webhook event", "type", fmt.Sprintf("%T", event))
is there a way to use `"github.com/sourcegraph/log"` instead of `log15` which is considered deprecated? (AFAIK)

2022-11-16 06:08 UTC, sashaostrikov commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +			log15.Warn("Dropping Bitbucket Server webhook event", "type", fmt.Sprintf("%T", event))
ah, I see, it will require some refactoring...

2022-11-16 08:30 UTC, ryanslade commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +		case eventTypeNotFoundError:
If you make `eventTypeNotFound` implement the `NotFound` method then we can use `errcode.IsNotFound` here which is a pattern we use in many places:

https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+errcode.IsNotFound&patternType=standard&sm=0&groupBy=path

2022-11-16 08:32 UTC, ryanslade commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	sig := r.Header.Get("X-Hub-Signature")
Are we sure this is correct? That's a GitHub header and I also seem to remember that BitBucket doesn't send secrets. I think we may have hacked something on top of it where they need to append the secret the the incoming webhook URL.

2022-11-16 12:32 UTC, mrnugget requested changes

2022-11-16 12:32 UTC, mrnugget commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	// internal actor on the context.
Which shared secret?

2022-11-16 12:32 UTC, mrnugget commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +func (h *WebhookRouter) parseEvent(r *http.Request, payload []byte) (any, string, error) {
It'd would clash with `r *http.Request`, so maybe `wr`

2022-11-16 12:32 UTC, mrnugget commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +		log15.Error("Could not decode external service config")
Wrong message, I think?

2022-11-16 13:41 UTC, eseliger reviewed
mirroring the feedback on this PR, but nothing additional stood out

2022-11-16 13:41 UTC, eseliger commented on cmd/frontend/enterprise/enterprise.go
> +		BatchesBitbucketServerWebhook:   &emptyWebhookHandler{"batches bitbucket server webhook"},
for consistency
```suggestion
		BatchesBitbucketServerWebhook:   &emptyWebhookHandler{name: "batches bitbucket server webhook"},
```

2022-11-16 15:38 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	sig := r.Header.Get("X-Hub-Signature")
It looks to me like BB Server does have a secret, like Github does. It's BB Cloud that doesn't support secrets and where we add our hacky appended secret currently.

2022-11-16 15:43 UTC, mollylogue commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +		log15.Error("Could not decode external service config")
I just used the same message we were using for github/gitlab for getting the external service config, but I'm happy to update it to something more specific.

2022-11-16 15:46 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	sig := r.Header.Get("X-Hub-Signature")
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go?L78 you can see in the current implementation that this is the header we use.

2022-11-16 15:55 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	// internal actor on the context.
We see this message [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/gitlab_webhooks.go?L17-18) as well. It's referencing the fact that this function is called from [this function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/webhooks/gitlab_webhooks.go?L77) where the secret validation is done.

2022-11-16 15:58 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	// internal actor on the context.
The shared secret is the one they create when creating the webhook object our GQL console and then also when creating the actual webhook in BB server.
<img width="721" alt="Screen Shot 2022-11-16 at 8 57 07 AM" src="https://user-images.githubusercontent.com/17705637/202230250-846fd2d8-c420-4527-9365-31db803fe6f7.png">

2022-11-16 16:09 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +		case eventTypeNotFoundError:
👍

2022-11-16 16:15 UTC, mollylogue commented on cmd/frontend/enterprise/enterprise.go
> +		BatchesBitbucketServerWebhook:   &emptyWebhookHandler{"batches bitbucket server webhook"},
👍 good catch

2022-11-16 16:18 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	payload, err := io.ReadAll(r.Body)
Yes. Thank you 🙏 I refactored this bit about 20 times so that must've gotten dropped somewhere. 🤦‍♀️

2022-11-16 16:42 UTC, mollylogue commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +			log15.Warn("Dropping Bitbucket Server webhook event", "type", fmt.Sprintf("%T", event))
Yeah, agreed. Unfortunately it wasn't super simple. I was thinking maybe a follow-up after this to try to get rid of all the usages of `log15` in this package.

2022-11-16 17:13 UTC, mollylogue commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +	// internal actor on the context.
So, this comment was here before, and I didn't feel comfortable removing it. Could we change it to something like "If we've made it here, then the shared secret for the BitbucketServer webhook has been validated, so we can use an internal actor on the context". Idk what's best. I think having a comment on _why_ it's safe to use an internal actor isn't a bad idea, but I don't have a strong feeling about what the message should be.

2022-11-17 07:59 UTC, mrnugget commented on enterprise/cmd/frontend/internal/batches/webhooks/bitbucketserver.go
> +	// internal actor on the context.
Yeah, I think your proposal is better. The "If we've made it here, the secret has been validated" makes a lot of sense.

2022-11-21 20:07 UTC, mollylogue commented
Validation steps taken locally:

- Add BB Server code host config. ✅
- Start NGROK ✅
- Get URL and add as external URL to site config ✅
- Start server ✅
- Create a batch change for the BB server repo
-- Ensure token is added for code host for batch changes under settings  ✅
-- Generate SG token and run src login https://sourcegraph.test:3443/  ✅
-- Create batch change using src batch apply -f new-batch-spec.batch.yaml and validate changeset shows up in batch changes ui  ✅
- Publish changeset to PR on the codehost   ✅
- On BB Server, set up Webhooks using NEW endpoint   ✅
- On BB Server, go to PR and toggle “ready for review” or “needs work”  ✅
- Immediately check in batch changes UI for updated state  ✅
- Repeat process w/ legacy webhooks handler. ✅

2022-11-21 20:46 UTC, mollylogue commented
@eseliger see the above for the validation that I did. Lmk if that looks good to you.

2022-11-21 20:50 UTC, eseliger commented
Looks good to me, thanks for testing to thoroughly!

2022-11-21 21:23 UTC, mollylogue commented
One thing to note: When we set up webhooks the _new_ way, we still see this banner in the batch changes UI:
<img width="1124" alt="Screen Shot 2022-11-21 at 1 18 51 PM" src="https://user-images.githubusercontent.com/17705637/203160709-167dddee-525e-46ae-b5e5-c3f5da8ed9b7.png">

We need to update that so that it doesn't display if the user has the new top-level webhook set up (or link to new docs once we have them.)

2022-11-21 21:46 UTC, eseliger commented
ah great catch!

2022-11-22 16:23 UTC, ryanslade commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
nit: I assume this is what we had before, but maybe a 400 is a better error code here?

2022-11-22 16:27 UTC, ryanslade commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	if secret == "" {
I wonder if we could reverse this check to be `if secret != ""` then do the signature check and return on error. That we only need to have `wr.HandleBitbucketServerWebhook` once at the end of the function.

2022-11-22 16:29 UTC, ryanslade approved these changes
LGTM, especially with all the extra testing!

2022-11-22 17:49 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
Good call. 👍

2022-11-22 17:50 UTC, mollylogue commented on cmd/frontend/webhooks/bitbucketserver_webhooks.go
> +	if secret == "" {
👍

2022-11-22 20:07 UTC, merged