graphqlbackend: add permissionsSyncJobs endpoint
sourcegraph/sourcegraph pull request #44387
Opened 2022-11-14 23:40 UTC by bobheadxi

## Test plan

2022-11-14 23:40 UTC, bobheadxi commented
Current dependencies on/for this PR:
* main
  * **PR #44251** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/44251" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #44257** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/44257" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #44258** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/44258" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #44387** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/44387" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/44387?utm_source=stack-comment).

2022-11-14 23:47 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.13 kb) | 0.00% (+0.40 kb) | 0.00% (+0.28 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/11-14-graphqlbackend_add_permissionsSyncJobs_endpoint/compare-report.html;tab=live_object) for a full comparison between the commits 6b0db24 and a55b91d or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-15 17:21 UTC, kopancek commented on cmd/frontend/graphqlbackend/authz.graphql
> +        count: Int
We already have a standard way to do pagination. [Based on PageInfo type defined in graphql (IIRC)](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L4293-L4302). Which in turn is based on cursor pagination, not offset and limit.

I think we can reuse it instead of introducing custom code. The convention is then to ask for

first: Int
after: String
Where first is basically the limit as you use it. And after is the cursor that points to the item after which want to get the next page worth of items. You can see it in action on [org members here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/schema.graphql?L5776-L5789).

2022-11-15 17:21 UTC, kopancek commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +}
I don't see these methods defined on the `PermissionsSyncJobs` type in graphql schema. What is the reason for defining these other public functions on the resolver itself?

2022-11-15 17:21 UTC, kopancek commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +type permissionsSyncJobResolver struct{ authz.SyncJobStatus }
I think you can consider splitting all of these resolvers into their own file. They seem to be completely separate from responsibility point of view.

2022-11-15 17:21 UTC, kopancek commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +package resolvers
I don't see any unit tests for these resolvers (or any other new code), would expect it for the final PR.

2022-11-15 17:21 UTC, kopancek commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +	vals := c.GetMulti(keys...)
Getting everything out of the cache seems inefficient to me. Should we only get some limited amount of items out? In theory we do not even need the `totalCount`. We just need to know if there are more items to read, so something like `hasNextPage` should be enough.

2022-11-15 17:36 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +        count: Int
Ah, I copied this from another endpoint here. That said, I currently don't intend for this endpoint to be paginated - it should only ever return the X most recent runs, older runs will expire and should not be paginated for

2022-11-15 17:37 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +}
It's documented above these 3 - they implement `sort.Interface`

2022-11-15 17:40 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +	vals := c.GetMulti(keys...)
Let's discuss this in the other thread: https://github.com/sourcegraph/sourcegraph/pull/44387#discussion_r1023057903

2022-11-15 17:43 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +	vals := c.GetMulti(keys...)
Right now the redis key is `prefix/type-id`, if I make it `prefix/timestamp`-only we might be able to make this sort by key so that we would not need to get everything at once.

Regarding pagination, see https://github.com/sourcegraph/sourcegraph/pull/44387#discussion_r1023085390

2022-11-15 23:30 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +}
Removing in favour of key sort!

2022-11-15 23:54 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +	vals := c.GetMulti(keys...)
We still need to list all keys at once for Redis-related reasons, but this should be infrequent and small-scale enough as to not be a major issue. Retrieving the values will respect the count now

2022-11-16 00:45 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +type permissionsSyncJobResolver struct{ authz.SyncJobStatus }
I think I will keep these in the same file for now - they are both very thin adapters for the GraphQL interfaces, and it seems the general practice is to keep them together (e.g. the bitbucket endpoint resolver)

2022-11-16 00:46 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +        count: Int
For now I'm opting to not implement pagination here, since the endpoint and data are not designed to return enough data to warrant pagination at the moment.

2022-11-16 02:21 UTC, bobheadxi commented on enterprise/internal/authz/syncjobs/records_reader.go
> +}
We are bottlenecked usually by provider rate limits, so in practice we will be seeing at most 10k entries for the default 5m TTL at most for most providers, which is well within a manageable range for Redis

2022-11-16 02:30 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +        count: Int
I did rename `count` to `first`, however, so the parameters can one day be extended to paginate if needed!

2022-11-16 02:39 UTC, unknwon approved these changes

2022-11-16 09:35 UTC, pjlast commented on enterprise/internal/authz/syncjobs/records_reader.go
> +}
Not sure how true this is for user-based permissions syncing, where each user token has its own rate limit.

But I also can't think that the number will be crazy high with a 5m TTL

2022-11-16 09:37 UTC, pjlast approved these changes

2022-11-16 11:43 UTC, mrnugget requested changes
Requesting changes because I think we should be consistent in our GraphQL API.

2022-11-16 11:43 UTC, mrnugget commented on CHANGELOG.md
> +- A new experimental endpoint, `permissionsSyncJobs`, that lists the states of recently completed permissions sync jobs and the state of each provider. [#44387](https://github.com/sourcegraph/sourceg
Let's be precise here, it's not an endpoint :)

```suggestion
- A new experimental GraphQL query, `permissionsSyncJobs`, that lists the states of recently completed permissions sync jobs and the state of each provider. [#44387](https://github.com/sourcegraph/sourcegraph/pull/44387)
```

2022-11-16 11:43 UTC, mrnugget commented on cmd/frontend/graphqlbackend/authz.graphql
> +    ): PermissionsSyncJobs
This should return a `PermissionSyncJobConnection` to be consistent with our API. See this for another example:

https://github.com/sourcegraph/sourcegraph/blob/15dc7723d8ba62fbf9a667204ec2a0ecb70713df/cmd/frontend/graphqlbackend/schema.graphql#L2767-L2791

2022-11-16 11:43 UTC, mrnugget commented on cmd/frontend/graphqlbackend/authz.graphql
> +State of a permission sync job.
Ah permission sync job is the state of a permission sync job? 😄

2022-11-16 11:43 UTC, mrnugget commented on cmd/frontend/graphqlbackend/authz.graphql
> +    completedAt: DateTime!
This should be nullable if you want to return non-completed sync jobs in the future, right?

2022-11-16 11:43 UTC, mrnugget commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +			jobs.jobs = append(jobs.jobs, permissionsSyncJobResolver{j})
What's the difference?

2022-11-16 11:45 UTC, mrnugget commented on cmd/frontend/graphqlbackend/authz.graphql
> +    This endpoint currently only reports recently completed sync jobs, with an expiry configurable by 'authz.syncJobsRecordsTTL'.
Why add the `status: ` thing then? Let's not add code that's dead.

2022-11-16 13:30 UTC, eseliger commented on cmd/frontend/graphqlbackend/authz.graphql
> +        first: Int
It would be good to support `after: String` based pagination here. Especially since we limit the maximum number of rows returned as well

If 100 is the default, that should be explicit in the schema by saying 

```suggestion
        """
        Number of jobs returned. Maximum number of returned jobs is 500. Up to 100 jobs are returned by default.
        """
        first: Int = 100
```

2022-11-16 13:30 UTC, eseliger commented on cmd/frontend/graphqlbackend/authz.graphql
> +type PermissionsSyncJobs {
Connections should have PageInfo and TotalCount as well

2022-11-16 13:30 UTC, eseliger commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +func (r *permissionsSyncJobsResolver) Nodes() ([]graphqlbackend.PermissionsSyncJobResolver, error) {
```suggestion
func (r *permissionsSyncJobsResolver) Nodes() []graphqlbackend.PermissionsSyncJobResolver {
```

2022-11-16 16:19 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +    message: String!
Message here contains the specific errors involved, while status is an enum with limited information

2022-11-16 16:19 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +    This endpoint currently only reports recently completed sync jobs, with an expiry configurable by 'authz.syncJobsRecordsTTL'.
Completed could mean completed with error, or completed with success (see the status enum type), so there are a non-zero number of states here

2022-11-16 16:21 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +        first: Int
Reasoning for not adding pagination here yet: https://github.com/sourcegraph/sourcegraph/pull/44387#discussion_r1023393939

Thanks for the default though!

2022-11-16 16:21 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +type PermissionsSyncJobs {
I could add these, but I'm not intending to support pagination here yet: https://github.com/sourcegraph/sourcegraph/pull/44387#discussion_r1023393939

The PageInfo type could just return some stub data I suppose that implies every request is a single page, WDYT?

2022-11-16 16:23 UTC, eseliger commented on cmd/frontend/graphqlbackend/authz.graphql
> +type PermissionsSyncJobs {
that works, or overfetch by 1 and see if `len(res) > first` and set hasnextpage based on that
Generally, if we can work towards a schema that would not need a breaking change when we advance things further, I'd be up for that :)

2022-11-16 16:25 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +			jobs.jobs = append(jobs.jobs, permissionsSyncJobResolver{j})
- If status is nil, we don't care what the job's status is, add them all as resolvers
- If status is _not_ nil, add only jobs matching the status argument

I'll add a docstring!

2022-11-16 16:31 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +    id: Int!
What format does this ID take? It looks like it's meant to be globally unique, currently perms sync job IDs are not - should I be generating one?

2022-11-16 16:33 UTC, eseliger commented on cmd/frontend/graphqlbackend/authz.graphql
> +    id: Int!
In graphql, that is usually Base64 encoded “EntityName:nongloballyuniqueidentifier“
MarshalRepositoryID gives an example how this works!

2022-11-16 16:34 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +State of a permission sync job.
Docstring is a linter requirement 😅 Found myself a bit lacking in imagination here

2022-11-16 16:46 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +    message: String!
Updated the docstring here!

2022-11-16 16:49 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/authz.graphql
> +    id: Int!
Thanks! In the job here there is an array (ProviderStatus) that isn't treated as a connections/nodes, the ID on that doesn't necessarily have to implement Node right?

2022-11-16 16:56 UTC, eseliger reviewed
lgtm, pending implementing the remaining comments (not sure if review was re-requested intentionally yet?)

2022-11-16 16:56 UTC, eseliger commented on cmd/frontend/graphqlbackend/authz.graphql
> +    ): PermissionsSyncJobsConnection
Is there a reason this should be nullable? Otherwise:

```suggestion
    ): PermissionsSyncJobsConnection!
```

2022-11-16 16:56 UTC, eseliger commented on cmd/frontend/graphqlbackend/authz.graphql
> +        first: Int
```suggestion
        first: Int = 100
```

2022-11-16 16:56 UTC, eseliger commented on cmd/frontend/graphqlbackend/authz.graphql
> +    id: Int!
yeah I think that's ok, if we want to avoid confusion we might want to rename it to something else if we got anything better, but not strictly required.

2022-11-16 17:16 UTC, eseliger approved these changes
LGTM, pending one last thing for `Node`

2022-11-16 17:16 UTC, eseliger commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
>  	}
This resolver should have a method called `NodeResolvers`

Should be called like that: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/graphqlbackend.go?L366 for the authz resolver in the same method
For that, add to the interface type this signature https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/batches.go?L302
Finally, the NodeResolvers method should return a mapping from Kind to a resolver func.

2022-11-16 17:16 UTC, eseliger commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +	return relay.MarshalID("EventTime", j.s.Completed)
The Kind is usually expected to be the name of the entity, otherwise this might still not be globally unique (what if someone adds the EventTime node type)

```suggestion
	// Use eventTime because RequestID can repeat
	return relay.MarshalID("PermissionsSyncJob", j.s.Completed)
```

2022-11-16 18:10 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
>  	}
Thanks, added and tested! https://github.com/sourcegraph/sourcegraph/pull/44387/commits/1687dfe48c520525e2aee023fcd20f9057d87fa5

![image](https://user-images.githubusercontent.com/23356519/202259526-c692715b-65a8-4cef-bcbc-3df97332cc25.png)

2022-11-16 18:12 UTC, eseliger commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
>  	}
Looks good!

2022-11-16 19:44 UTC, merged

2022-11-17 07:29 UTC, mrnugget commented on enterprise/cmd/frontend/internal/authz/resolvers/resolver.go
> +			jobs.jobs = append(jobs.jobs, permissionsSyncJobResolver{j})
Oh, I see. `else if` strikes again.

2023-01-19 07:38 UTC, keegancsmith commented on enterprise/internal/authz/syncjobs/records_reader.go
> +		ListKeys(ctx context.Context) ([]string, error)
@bobheadxi sorry to revive an old PR. But I've been reviewing our use of redis and noticed this use of ListKeys. FYI this operation has the complexity of listing _all_ keys on the redis instance, not just those associated with the named cache. It will only return the relevant keys, but redis doesn't have a way to do this otherwise.

How many keys do you expect us to get? From looking around, it seems like this would be better suited using `rcache.FIFOList`. WDYT?
Instead of this

2023-01-19 08:07 UTC, bobheadxi commented on enterprise/internal/authz/syncjobs/records_reader.go
> +		ListKeys(ctx context.Context) ([]string, error)
The FIFOList wasn't available at the time, but I did spot it in other PRs - I can make the switch here :) Will open a PR tomorrow!