Add initial onboarding (public) repos
sourcegraph/sourcegraph pull request #44398
Opened 2022-11-15 09:11 UTC by erzhtor

Closes https://github.com/sourcegraph/sourcegraph/issues/42982.
## Test plan
- Remove `EXTSVC_CONFIG_FILE` env var
- `sg start`
- Open http://localhost:3080/site-admin/external-services
- Check that new external service was added
- Rerun (or also delete external service) and make sure that no new external services were added

2022-11-15 10:57 UTC, ryanslade commented on cmd/repo-updater/shared/main.go
> +		IncludeDeleted: true,
Did we do this so that they can delete the service manually if they want to?

2022-11-15 10:58 UTC, ryanslade commented on internal/database/external_services.go
> +	displayName string
We don't seem to set this value anywhere.

2022-11-15 10:58 UTC, ryanslade commented on internal/database/external_services.go
> +	if len(o.DisplayNames) > 0 {
We should add a test case to confirm this works

2022-11-15 11:05 UTC, sashaostrikov commented on cmd/repo-updater/shared/main.go
> +	ghToken := env.Get("ONBOARDING_EXTERNAL_SERVICE_GH_TOKEN", "", "GitHub token for onboarding external service. Token can be without any permissions.")
I would extract reading an environment variable to `cmd/repo-updater/shared/main.go` and only call `createOnboardingExternalService` if this variable is set.

2022-11-15 11:05 UTC, sashaostrikov commented on cmd/repo-updater/shared/main.go
> +	svcs, err := db.ExternalServices().List(ctx, database.ExternalServicesListOptions{
I guess we can first check whether this external service exists and return early. 

This way we won't create `externalService` variable which is in fact unused if such external service already exists.

We can also create a const for `GITHUB (Onboarding Repositories)` in this case.

2022-11-15 11:14 UTC, erzhtor commented on cmd/repo-updater/shared/main.go
> +		IncludeDeleted: true,
Yes, that's right.

2022-11-15 11:17 UTC, erzhtor commented on internal/database/external_services.go
> +	displayName string
Sorry, this is left over from the previous implementation. Thanks for catching it. Removed.

2022-11-15 11:31 UTC, erzhtor commented on internal/database/external_services.go
> +	if len(o.DisplayNames) > 0 {
Thanks, added tests 0b78ce8ce38bbed0e70593dcff592e96be80e4f6

2022-11-15 11:35 UTC, eseliger commented on cmd/repo-updater/shared/main.go
> +	ghToken := env.Get("ONBOARDING_EXTERNAL_SERVICE_GH_TOKEN", "", "GitHub token for onboarding external service. Token can be without any permissions.")
How do we provisos this token? If they all belong to the same user account, and we have 100 trial instances, probably all of them will be Rate limited and stop working 🙁

2022-11-15 11:36 UTC, eseliger commented on cmd/repo-updater/shared/main.go
> +			"token": "`+ ghToken + `",
Need to quote properly, in case the token contains quotes

2022-11-15 11:38 UTC, erzhtor commented on cmd/repo-updater/shared/main.go
> +	ghToken := env.Get("ONBOARDING_EXTERNAL_SERVICE_GH_TOKEN", "", "GitHub token for onboarding external service. Token can be without any permissions.")
Thanks! Updated 704d2649d177cd3927e4586d9686929e38543ffe

2022-11-15 11:38 UTC, erzhtor commented on cmd/repo-updater/shared/main.go
> +	svcs, err := db.ExternalServices().List(ctx, database.ExternalServicesListOptions{
Thanks! Updated 704d2649d177cd3927e4586d9686929e38543ffe

2022-11-15 11:44 UTC, ryanslade commented on internal/database/external_services_test.go
> +		// We should find all services were updated after a time in the past
nit: It looks like this comment has been copy pasted in a lot of test cases, no need to clear them all up now but we can remove this one at least.

2022-11-15 11:53 UTC, erzhtor commented on internal/database/external_services_test.go
> +		// We should find all services were updated after a time in the past
Updated.

2022-11-15 14:24 UTC, sashaostrikov commented on cmd/repo-updater/shared/main.go
> +		// TODO: Update list of repos (clarify)
do we still need this todo?

2022-11-15 14:24 UTC, sashaostrikov approved these changes
LGTM! 👍🏻

2022-11-16 11:55 UTC, mrnugget commented on cmd/repo-updater/shared/main.go
> +		DisplayNames:   []string{onboardingExternalServiceDisplayName},
What if the customer edits the name? You'd create the a duplicate with the old name on the next startup, right?

2022-11-16 12:00 UTC, mrnugget requested changes
I'm not convinced that this is the right solution. We don't have precedent for "run a single job in a specific environment, once", but I don't think repo-updater is the place for it. There's also a potential bug in case the user renames the code host config.

I'd highly recommend re-thinking the approach here and possibly creating this  external service through the API.

2022-11-24 11:31 UTC, erzhtor commented
Thank you, everyone, for the reviews! It turned out to be more effort than initially thought. I am closing this now, as it is less priority than the other tasks, and I will revisit it in the future.

2022-11-24 11:31 UTC, closed without merging