insights: remove dirty queries resolver and store logic
sourcegraph/sourcegraph pull request #44416
Opened 2022-11-15 14:20 UTC by leonore

closes #44093

opened https://github.com/sourcegraph/sourcegraph/issues/44415

## Test plan

Ran existing unit tests and created an insight

2022-11-15 14:30 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/leo/remove-dirty-queries/compare-report.html;tab=live_object) for a full comparison between the commits e1aa30e and 145f2d5 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-15 17:55 UTC, coury-clark requested changes
Since this is a breaking change in the API we will need to include a changelog entry and try to scrub any references, for example [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/code_insights/references/common_reasons_code_insights_may_not_match_search_results.md?L41:9)

Code changes look good, just need to make sure we aren't breaking something for someone here.

2022-11-16 13:42 UTC, leonore commented
> Since this is a breaking change in the API we will need to include a changelog entry and try to scrub any references, for example [here](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/code_insights/references/common_reasons_code_insights_may_not_match_search_results.md?L41:9)
> 
> Code changes look good, just need to make sure we aren't breaking something for someone here.

thanks for catching! I ran a search and I think I've got it all. have a look at the doc changes 
https://sourcegraph.sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40leo/remove-dirty-queries+dirty+quer+or+dirty+metadata+or+dirtymeta&patternType=standard&sm=0&groupBy=path

2022-11-29 16:44 UTC, coury-clark approved these changes

2022-11-29 16:50 UTC, merged