Do not run useless final sync for deleted external service
sourcegraph/sourcegraph pull request #44549
Opened 2022-11-17 13:26 UTC by mrnugget

While looking at https://github.com/sourcegraph/sourcegraph/issues/44146 we noticed that the sync that runs when an external service is useless, since

1. `handleExternalServiceValidate` will early-exit if it's been marked as deleted
2. the sync job handler will throw an error if the external service is deleted

That means we don't need to run the final sync because it didn't have an effect anymore.

Since that's removed, there's also no need anymore to delete external services asynchronously (which only seemed to happen in our test suites anyway), since we only delete the repos/external-service from the database now.

## Test plan

- Manual testing
- Existing tests

2022-11-17 13:35 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/mrn+es/clean-up-ext-svc-deletion/compare-report.html;tab=live_object) for a full comparison between the commits 94e106c and ba327d5 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-17 14:29 UTC, ryanslade commented
I think the description above is missing a word or two:

>  that runs when an external service is useless, since

2022-11-17 14:34 UTC, mrnugget commented
> I think the description above is missing a word or two:

The next two bullet points explain why it's useless (in the most literal sense: it doesn't have a use). I'm adding punctuation to make it clearer

2022-11-17 14:41 UTC, ryanslade commented
I still think maybe it's missing the word "deleted" after "when an external service is"

2022-11-17 14:50 UTC, mrnugget commented
> I still think maybe it's missing the word "deleted" after "when an external service is"

Fixed!

2022-11-17 15:10 UTC, ryanslade commented
Ok, so this just fails early when you try and sync a deleted external service. That makes sense, but do we still have the code that actually tries to trigger a final sync? I don't remember why we wanted to do that in the first place.

2022-11-17 15:50 UTC, mrnugget commented
> That makes sense, but do we still have the code that actually tries to trigger a final sync? I don't remember why we wanted to do that in the first place.

No. There's no final sync anymore. I think the final sync was back from a time before we had the soft-deletion of external services and that `DeleteExternalService` method that soft-deletes repos. I can't think of any reason why we want to do a final sync, because (as I wrote above) the final sync would early-exit anyway.

2022-11-21 16:21 UTC, mollylogue approved these changes
🙏 this is great. I'm guessing this means that we can now delete external services (w/ lots of repos) in the UI that previously timed out.

2022-11-22 06:16 UTC, sashaostrikov requested changes
removing last sync LGTM.

however, removing async deletion is at least used by [one of our customers](https://github.com/sourcegraph/customer/issues/841) and fixes one customer issue. I don't think we should remove `async` option

2022-11-22 10:29 UTC, mrnugget commented
> however, removing async deletion is at least used by [one of our customers](https://github.com/sourcegraph/customer/issues/841) and fixes one customer issue. I don't think we should remove `async` option

NICE! Good callout. Will add it back.

2022-11-22 10:45 UTC, mrnugget commented
@sashaostrikov restored async deletion. Can you take another look?

2022-11-22 10:55 UTC, sashaostrikov approved these changes
:shipit::shipit::shipit:

2022-11-22 10:55 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services.go
> -	"github.com/inconshreveable/log15"
Nice 👍🏻

2022-11-22 11:50 UTC, merged