Fix word break for repo pages
sourcegraph/sourcegraph pull request #44550
Opened 2022-11-17 13:32 UTC by philipp-spiess

Fixes #43687

Make sure that the header component allows long repo paths.

@AlicjaSuska: Page thumbnails also break very oddly in this view (they are displayed in the second line here?). What do you think of hiding some of the interim levels? e.g. if there are more than 8 directories or so, we hide some of the middle ones and just display a generic `...`? 

E.g. like this:
 
<img width="1349" alt="Screenshot 2022-11-17 at 14 31 57" src="https://user-images.githubusercontent.com/458591/202459694-d1eaceca-1612-4042-a019-57224e377220.png">

## Test plan

Tested locally:

<img width="1734" alt="Screenshot 2022-11-17 at 14 28 51" src="https://user-images.githubusercontent.com/458591/202459738-d5df4e57-ca60-47ca-a124-115842242c43.png">

2022-11-17 13:40 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.59 kb) | 0.01% (+1.59 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/fix-word-break-for-repo-pages/compare-report.html;tab=live_object) for a full comparison between the commits 64d14be and cc7bd73 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-17 20:33 UTC, lrhacker approved these changes

2022-11-18 10:08 UTC, AlicjaSuska requested changes
Thank you for making those changes @philipp-spiess. As we've discussed on slack:
- the main change of the title works well :) The only issue is the folder icon size - it is too small. Let's keep it the original size.
- regarding the breadcrumbs - I agree, this implementation is incorrect. Please, see the (old) figma [mockup](https://www.figma.com/file/A4gGoseJDz8iPeHP515MfQ/%F0%9F%A5%96Breaders-(breadcrumbs-%2B-headers)-%2315431-%5BApproved%5D?node-id=624%3A241&t=1O1clckqIfJOBwr4-4) for reference regarding the logic of adding '...' and which breadcrumb to show.

Thank you!

2022-11-23 16:17 UTC, philipp-spiess commented
@AlicjaSuska I'd like to work on the breadcrumbs changes in a different PR as they will quickly spiral out of control, do you mind reviewing this again for the page title only? I've also added an example to the storybook and updated the screenshot.

2022-11-28 10:28 UTC, merged