Update-repo-not-updated.md
sourcegraph/sourcegraph pull request #44644
Opened 2022-11-21 07:35 UTC by rakeshjosh2003

Update the how-to guide for troubleshooting repo update, sync related issues.
## Test plan

2022-11-21 11:53 UTC, rakeshjosh2003 commented
@cla-bot check

2022-11-21 14:35 UTC, amenne reviewed
This lgtm might want to get someone like Jason (bc he helped with this ticket) to also review but don't let me block this merge

2022-11-21 20:19 UTC, DaedalusG commented on doc/admin/how-to/repo-not-updated.md
> +6. Check the size of repository, if it's a large repository it may take long time to sync and update. To find the size of your .git directory where the repository resides, use command `du – sh .git`.
```suggestion
6. Check the size of repository, if it's a large repository it may take long time to sync and update. To find the size of your .git directory where the repository resides, you may use our (`git-stats` script)[https://docs.sourcegraph.com/admin/monorepo#statistics]. You may also use command `du – sh .git` to get the size, and command `git count-objects -v` to count the number of unpacked object files and disk space consumed by them. 
```

2022-11-21 20:21 UTC, DaedalusG commented on doc/admin/how-to/repo-not-updated.md
> +6. Check the size of repository, if it's a large repository it may take long time to sync and update. To find the size of your .git directory where the repository resides, use command `du – sh .git`.
This is the semi official script to gather info we try to collect when we're dealing with a large repo.

2022-11-21 20:24 UTC, DaedalusG requested changes
This looks pretty good, please see my suggested change -- for brevity it might be nice to remove the standard shell commands so that users just use our script -- but I leave that to your discretion. See this [slack thread](https://sourcegraph.slack.com/archives/C01JR51JR5J/p1668804190162189?thread_ts=1668794516.343189&cid=C01JR51JR5J) for more context.

2022-11-21 23:42 UTC, rakeshjosh2003 commented
> This looks pretty good, please see my suggested change -- for brevity it might be nice to remove the standard shell commands so that users just use our script -- but I leave that to your discretion. See this [slack thread](https://sourcegraph.slack.com/archives/C01JR51JR5J/p1668804190162189?thread_ts=1668794516.343189&cid=C01JR51JR5J) for more context.

Hey Waren, Thanks for the review and suggestions, I have modified the doc.

2022-11-22 01:03 UTC, gabtorre requested changes

2022-11-22 01:03 UTC, gabtorre commented on doc/admin/how-to/repo-not-updated.md
> +8. Check the codehost connection from sourcegraph instance, if there is any issue it needs to be resolved for the repository to sync and update.
```suggestion
8. Check the code host connection from your Sourcegraph instance. If there is any issue, it needs to be resolved for the repository to sync and update.
```

2022-11-22 01:03 UTC, gabtorre commented on doc/admin/how-to/repo-not-updated.md
> +6. Check the size of repository, if it's a large repository it may take long time to sync and update. To find the size of your .git directory where the repository resides, you may use our [`git-stats
```suggestion
6. Check the size of the repository. If it's a large repository, it may take a long time to sync and update. To find the size of your .git directory where the repository resides, you may use our [`git-stats` script](https://docs.sourcegraph.com/admin/monorepo#statistics). 
```

2022-11-29 03:29 UTC, rakeshjosh2003 reviewed
Merged

2022-11-29 03:30 UTC, rakeshjosh2003 reviewed
Merged

2022-11-29 05:17 UTC, gabtorre commented on doc/admin/how-to/repo-not-updated.md
> +7. Check the allocated resources to see the instance has enough resources to process the repositories sych using our [Resource Estimator](https://docs.sourcegraph.com/admin/deploy/resource_estimator)
```suggestion
7. Check the allocated resources to see if the instance has enough resources to process the repository sync using our [Resource Estimator](https://docs.sourcegraph.com/admin/deploy/resource_estimator)
```

2022-11-29 15:26 UTC, jasonhawkharris approved these changes
This looks great to me. Looks like Gabe and Warren got after it on the reviews here. All good! Approving!

2022-12-01 01:04 UTC, DaedalusG approved these changes

2022-12-01 01:13 UTC, gabtorre approved these changes

2022-12-01 01:18 UTC, merged