Initial bazel setup
sourcegraph/sourcegraph pull request #44755
Opened 2022-11-23 07:46 UTC by kormide

Hello from Aspect :wave: 

This is an initial BR to get the Bazel migration going. I set up an initial WORKSPACE file and bazel settings in the first commit, and in the second I converted the generation for some schema files in `client/shared/gulpfile.js` to be generated as Bazel build actions.

## Test plan

I'm not sure if this constitutes a special case as the Bazel build might live alongside the current build for the time being. Would you like me to get the build running on CI right away?

fyi: @gregmagolan @jbedard

2022-11-23 07:49 UTC, kormide commented on pnpm-workspace.yaml
> +  - "dev/release"
Although we aren't using `pnpm` yet, `rules_js` can still use this to download dependencies for all of the workspaces.

2022-11-23 09:08 UTC, burmudar commented
Hey @kormide I'll try to get people familiar assigned to look at this, otherwise I've assigned some initial reviewers. Feel free to ping me it you need anything else

2022-11-24 08:05 UTC, jhchabran commented
> I'm not sure if this constitutes a special case as the Bazel build might live alongside the current build for the time being. Would you like me to get the build running on CI right away? 

@kormide it's fine, let's get it to work locally first, having it living on the side while we get there seems to be the less disrupting way. I strongly suspect this is also going to be faster this way for you, right? 

Side note, we have a draft PR where we explored things before reaching you out that may want to take a look at: https://github.com/sourcegraph/sourcegraph/pull/41856

2022-11-25 17:41 UTC, gregmagolan commented on WORKSPACE
> +    strip_prefix = "rules_js-1.7.0",
1.8.0 is out

2022-11-25 17:44 UTC, gregmagolan commented on WORKSPACE
> +    yarn_lock = "//:yarn.lock",  # TODO: replace with pnpm_lock
when we switch to using pnpm-lock.yaml and the local workflow is still yarn, we need a diff test to fail if pnpm-lock.yaml is out-of-date with respect to the yarn.lock; this pattern is out there somewhere; I'll track it down

2022-11-25 17:45 UTC, gregmagolan commented on client/shared/src/schema/generate_schema.bzl
> +
nit: comment on the output file naming convention assumed by this macro

2022-11-25 23:47 UTC, kormide commented
> > I'm not sure if this constitutes a special case as the Bazel build might live alongside the current build for the time being. Would you like me to get the build running on CI right away?
> 
> @kormide it's fine, let's get it to work locally first, having it living on the side while we get there seems to be the less disrupting way. I strongly suspect this is also going to be faster this way for you, right?
> 
> Side note, we have a draft PR where we explored things before reaching you out that may want to take a look at: #41856

Thanks @jhchabran, I'll use that as a reference. Looks like what we have is about equivalent, minus the pnpm lock. We'll slowly migrate to pnpm as the migration progresses and will end up using a pnmp lockfile.

2022-11-25 23:47 UTC, kormide commented on client/shared/src/schema/generate_schema.bzl
> +
Updated.

2022-11-26 01:00 UTC, kormide commented
Added a third commit to generate the graphql schema file.

2022-11-28 18:52 UTC, kormide commented
@jhchabran I think this one is ready for review now if we're okay with putting the migration work into main. We could also discuss the migration approach at our kick-off meeting tomorrow.

2022-11-29 19:24 UTC, kormide commented
Fixed the formatting issues.

2022-11-30 14:47 UTC, vdavid reviewed
I gave suggestions on the two ESLint errors I found.

2022-11-30 14:47 UTC, vdavid commented on client/shared/src/generateGraphQlSchema.js
> +    console.error('Usage: node generateGraphQlSchema.js <outputFile>')
`console` calls are not allowed by the linter.
Here is more info on how to solve this: https://docs.sourcegraph.com/dev/background-information/web/web_app#logging

2022-11-30 14:47 UTC, vdavid commented on client/shared/src/generateGraphQlSchema.js
> +;(async () => await main(process.argv.slice(2)))()
Floating promises are not allowed. I'd try this:

```suggestion
;(async () => await main(process.argv.slice(2)))().then(() => {}).catch(() => {})
```

2022-11-30 16:33 UTC, marekweb requested changes

2022-11-30 19:00 UTC, kormide commented on client/shared/src/schema/generateSchema.js
> +  let schema = await readFile(path.join(schemaDirectory, `${schemaName}.schema.json`), 'utf8')
I can't see the buildkite output yet, but locally I'm getting lint errors here and I'm not sure if should add an ignore for the error or if there's something else I can here to fix it:

`Invalid type "any" of template literal expression`

I think this is because it can't deduce a type for the args? But this is JavaScript, so I don't think there's any sort of type coersion I can do?

2022-11-30 22:10 UTC, kormide commented on client/shared/src/schema/generateSchema.js
> +  let schema = await readFile(path.join(schemaDirectory, `${schemaName}.schema.json`), 'utf8')
I added some eslint ignore comments:
```
// eslint-disable-next-line @typescript-eslint/restrict-template-expressions
```

2022-11-30 22:14 UTC, kormide commented
Do you know why the `codenotify` GH action is failing?

2022-12-01 19:27 UTC, jhchabran approved these changes

2022-12-01 22:47 UTC, gregmagolan commented on .bazelversion
> +6.0.0rc2
You can bump to 6.0.0rc3 now and uncomment the `--remote_download_toplevel` flag in the CI rc file: https://github.com/aspect-build/bazel-examples/blob/b824d5c41843d0c4d88aa372be3f7da38ef11181/bazelrc/.aspect/bazelrc/ci.bazelrc#L78. The regression in Bazel has been fixed now.

2022-12-01 22:50 UTC, kormide commented on .bazelversion
> +6.0.0rc2
Updated

2022-12-02 05:14 UTC, valerybugakov approved these changes
LGTM! Left a couple of optional comments to learn more about best practices.

2022-12-02 05:14 UTC, valerybugakov commented on client/shared/src/generateGraphQlSchema.js
> +async function main(args) {
Is it worth it to make this function reusable to keep one source of truth for generation scripts and call it from the gulp file? Thinking about the bright future where we adopted Bazel, it would be nice to have a way to start the project without it. Curious what are your thoughts and suggestions on this topic.

2022-12-02 08:51 UTC, kormide commented on client/shared/src/generateGraphQlSchema.js
> +/* eslint no-console: 0 */
Yep I can move it somewhere else. It's not a problem for the script to generate an output in a different location; the output path can just be passed as an arg to the binary.

2022-12-02 08:56 UTC, kormide commented on client/shared/src/generateGraphQlSchema.js
> +async function main(args) {
Yeah avoiding duplication is always good in case this bazel entrypoint and the gulp function ever become out of sync during the migration. I'll do another pass on this.

2022-12-02 11:27 UTC, vdavid approved these changes
LGTM, but needs running Prettier. A `yarn format` command in the repo root usually solves it.

2022-12-02 11:45 UTC, jhchabran commented
@kormide I'm closing this in favour of https://github.com/sourcegraph/sourcegraph/pull/45052 (I needed to push stuff on the branch).

2022-12-02 11:45 UTC, closed without merging