Cloud CTA variants
sourcegraph/sourcegraph pull request #44776
Opened 2022-11-23 21:45 UTC by bretthayes

This closes #44770 and modifies our `CloudCtaBanner` component with flexible props.

## Changelog
- CloudCtaBanner:
  - `small` prop was added for conditional small text
  - `variant` prop was added to change styling
- centre-aligned the notice on the homepage

Variants for UX testing are listed in this [Figma](https://www.figma.com/file/qdUtoveMtn2wI8eaysE1De/UX%3A-Cleaning-up-noise-below-the-search-bar-on-dotcom?node-id=169%3A2790&t=jr4on1XLBuP1Rt9J-0).

- `?cta=a` = filled (also used as the default since this replaces our "Pro Tip" CTA)
- `?cta=b` = underlined
- `?cta=c` = undefined (no additional styling)
- `?cta=d` = outlined (not currently listed in Figma variants, but available if necessary)

## Test plan
- Ensure our CloudCtaBanner renders and looks good on other pages where it's being used
- Test the search param to render the 4 different variants (ie: `?cta=b`)

2022-11-23 21:52 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.02% (+2.56 kb) | 0.02% (+2.56 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/brett/homepage-cta/compare-report.html;tab=live_object) for a full comparison between the commits 1795ac9 and 4aaa2ba or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-23 23:22 UTC, st0nebraker requested changes
Looks good! A few small comments.

Also the `<CloudCtaBanner />`'s on `/batches/list/GettingStarted.tsx`, `CodeMonitoringGettingStarted.tsx`, `CodeInsightsDotComGetStarted.tsx` & `NotebooksGettingStarted.tsx` all need a `variant="filled"` prop along with some bottom padding to keep their previous styling please 🙏🏻

2022-11-23 23:22 UTC, st0nebraker commented on client/web/src/search/home/QueryExamplesHomepage.tsx
> -                        <H4 className={classNames('mr-2 mb-0 pr-2', styles.proTipTitle)}>Pro Tip</H4>
Can we delete this style (`.pro-tip-title`) from `QueryExazmplesHomepage.module.scss` too since this is getting removed?

2022-11-23 23:22 UTC, st0nebraker commented on client/web/src/components/CloudCtaBanner.module.scss
> +.underlined {
To me, this variant looks a little unbalanced because of the spaced icon on the left. Can we add a little right padding to lengthen the underline?
![image](https://user-images.githubusercontent.com/59381432/203661992-8ee1141b-2e36-4133-b96b-a825df9ea515.png)

2022-11-28 16:53 UTC, bretthayes commented on client/web/src/components/CloudCtaBanner.module.scss
> +.underlined {
@st0nebraker I see what you mean, but I think allowing it to flow naturally looks good as well. I think we should go with the current design for now so we don't block the PR and if @almeidapaulooliveira thinks it doesn't look right, I'll follow up with an update.

2022-11-28 16:57 UTC, st0nebraker commented on client/web/src/components/CloudCtaBanner.module.scss
> +.underlined {
This doesn't match the current Figma is my point. The underline under the right side shouldn't be sitting flush with the text above. It needs some padding. @bretthayes

2022-11-28 19:35 UTC, bretthayes commented on client/web/src/components/CloudCtaBanner.module.scss
> +.underlined {
@st0nebraker ahhh, I see! Idk how I missed that. Pushing a fix! Thanks for pointing that out!

2022-11-28 20:38 UTC, merged

2022-11-29 11:06 UTC, almeidapaulooliveira commented
Thanks, @st0nebraker, and @bretthayes !!