Allow users to sign out when there is only one oauth provider configured
sourcegraph/sourcegraph pull request #44803
Opened 2022-11-25 00:18 UTC by miveronese

Issue: #31192

This PR fixes a signout bug that happens when there's only one auth provider configured.

Bug: 
- if a user had only one auth provider and clicked the SignOut link, the user was immediately signed back (sso login)
- it was reported that this behavior caused issues in the past 
- this flow also created an annoying experience for the user, especially if they want to log in with a different account.

With this PR:
- if a user has only one auth provider and clicks the SignOut link, they will be redirected to the Sourcegraph login page.
- The session expiration behavior for only one auth provider was preserved. If the session expires, the user will still be signed back immediately.

## Test plan
- Added + updated unit tests.
- Manually tested the new behavior in a local instance.

Before vs after demos:
- Before: Signout flow + Session Expiration for 1 auth provider
https://user-images.githubusercontent.com/1552863/203876630-55ed1efd-3cf9-40c7-972a-91978221bff1.mp4

- Now: Signout  flow + Session Expiration for 1 auth provider
https://user-images.githubusercontent.com/1552863/203876673-912df8de-8424-4935-8239-03aac77dbde7.mp4

2022-11-25 14:43 UTC, mrnugget requested changes

2022-11-25 14:43 UTC, mrnugget commented on cmd/frontend/internal/app/sign_out.go
> +				})
Nitpick: I'd remove the values that are set by default (`HttpOnly: false`) and intend like this:

```suggestion
			http.SetCookie(w, &http.Cookie{
				Name:   signoutCookie,
				Value:  "true",
				Secure: true,
				Path:   "/",
			})
```

2022-11-25 14:43 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/common/utils.go
> +const SignoutCookie = "sg-signout"
This is a duplicate definition. I think we should only have one.

Since since you can't import `enterprise` code from non-enterprise code, but you'll need the cookie in `cmd/frontend/internal/app/sign_out.go` (non-enterprise) I suggest moving it to non-enterprise. For example: create a file `cmd/frontend/auth/sign_out_cookie.go` and put this definition in it and also `HasSignOutCookie`.

2022-11-25 14:43 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/oauth/middleware.go
> +			}
See comment above: I'd move the cookie name and the `HassignoutCookie` method to non-enterprise code and then use it here.

I'd also move this logic here to that same file (that I mentioned in previous comment) so it will look kinda like this:

```suggestion
			auth.RemoveSignOutCookieIfSet(r) {
```

Under the hood this function then does that the code here previously did, except all the logic for a single cookie is now in one file (well, as much as possible anyway)

2022-11-25 14:43 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/openidconnect/middleware.go
> +	if ps := providers.Providers(); len(ps) == 1 && ps[0].Config().Openidconnect != nil && !common.HasSignOutCookie(r) && !isAPIRequest {
I think this line has outgrown its one-lined-ness

```suggestion
	ps := providers.Providers()
	openIDConnectEnabled := len(ps) == 1 && ps[0].Config().Openidconnect != nil
	if  openIDConnectEnabled && !common.HasSignOutCookie(r) && !isAPIRequest {
```

2022-11-25 14:43 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/saml/middleware.go
> +		}
See above. If you extract this logic, then this won't duplicate the check & unset.

2022-11-25 14:43 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/saml/middleware.go
> +	if ps := providers.Providers(); len(ps) == 1 && ps[0].Config().Saml != nil && !common.HasSignOutCookie(r) && !isAPIRequest {
Same as above.

2022-11-25 15:12 UTC, miveronese commented on enterprise/cmd/frontend/internal/auth/common/utils.go
> +const SignoutCookie = "sg-signout"
yeah, it makes sense!

2022-11-25 17:34 UTC, miveronese commented
@mrnugget , thanks for the review!  I've addressed your suggestions, so it's ready for another look!

2022-11-28 08:33 UTC, mrnugget approved these changes

2022-11-28 08:33 UTC, mrnugget commented on cmd/frontend/auth/sign_out_cookie.go
> +const SignoutCookie = "sg-signout"
Now that all the logic is contained in here, you don't need to export the name of the cookie itself:

```suggestion
const signoutCookie = "sg-signout"
```

2022-11-28 08:33 UTC, mrnugget commented on cmd/frontend/internal/app/sign_out.go
> +			})
Maybe add a `auth.SetSignoutCookie` function and put that in there?

2022-11-28 08:33 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/oauth/middleware.go
> +		if pc := getExactlyOneOAuthProvider(); pc != nil && !isAPIHandler && pc.AuthPrefix == authPrefix && !auth.HasSignOutCookie(r) && isHuman(r) {
I think this line has grown a bit too long, I'd break it up :)

2022-11-28 08:33 UTC, mrnugget commented on enterprise/cmd/frontend/internal/auth/saml/middleware.go
> +	if ps := providers.Providers(); len(ps) == 1 && ps[0].Config().Saml != nil && !auth.HasSignOutCookie(r) && !isAPIRequest {
Same as above: I'd break th is line up. It's hard too read.

2022-11-28 09:03 UTC, pjlast commented on enterprise/cmd/frontend/internal/auth/oauth/middleware.go
> +			auth.RemoveSignOutCookieIfSet(r, w)
We can move all these `RemoveSignOutCookieIfSet` lines to the place where the sign-in cookie is created, which is here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/session/session.go?L233

Then it always happens for all sign-ins and we don't have to keep adding it to additional handlers

2022-11-28 09:21 UTC, pjlast commented on cmd/frontend/internal/app/sign_out.go
> +			})
I also don't think this is quite the right place to create the cookie.

I would prefer it a few lines up, inside the `SetActor` function. And inside there set and unset the cookie depending on if `actor == nil` or not.

Putting it inside the `ssoSignOutHandler != nil` check feels like depending on coincidence. Currently `ssoSignOutHandler` is only nil when launching Sourcegraph in OSS mode if I'm not mistaken, and coincidently OSS mode no longer supports sign-in methods besides username and password, so coincidently this doesn't matter at the moment. But there are no guarantees that it will stay this way, and then we will have unexpected behaviours in the future.

2022-11-28 09:24 UTC, pjlast commented on cmd/frontend/internal/app/sign_out.go
> +			})
Or maybe don't set the cookie in the `SetActor` function, but just underneath where it is called (so line 51 in this file).

I'm thinking now that if the cookie is set in `SetActor` it might get set on auto-signouts as well, which is not what we want.

But I still think the cookie should be un-set inside that function, so that we don't have to remember to unset the cookie all over the place.

2022-11-28 16:22 UTC, miveronese commented on enterprise/cmd/frontend/internal/auth/githuboauth/middleware_test.go
> -		}
The redirects where there to cover the case when:
- user clicks signout
- user is redirected to the sso signin flow (a 302 was expected)
now, the behavior is different
- user clicks signout
- there a get request to the SG sign in page (a 200 is expected) instead of a redirect to the sso flow  as before

2022-11-28 16:58 UTC, miveronese commented on cmd/frontend/auth/sign_out_cookie.go
> +const SignoutCookie = "sg-signout"
But, not exporting it, will make it no accessible in the unit tests.

2022-11-28 18:47 UTC, miveronese commented on cmd/frontend/internal/app/sign_out.go
> +			})
> But I still think the cookie should be un-set inside that function, so that we don't have to remember to unset the cookie all over the place.

@pjlast , when you say `that function` , you are referring not to SetActior on this file, but on `session.go`, right?
I am basing this assumption on your other comment here: https://github.com/sourcegraph/sourcegraph/pull/44803#discussion_r1033278617

2022-11-28 18:55 UTC, miveronese commented on enterprise/cmd/frontend/internal/auth/oauth/middleware.go
> +			auth.RemoveSignOutCookieIfSet(r, w)
It won't work this way.
When removing the RemoveSignOutCookieIfSet from middlewares and adding it to https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/session/session.go?L233,
after the signing happens and the user is redirected to the /search path, the cookie is set again.
As far as I tested, the only place where it is removed for sure, after sign-in, is in the middlewares.

2022-11-28 19:39 UTC, miveronese commented on cmd/frontend/auth/sign_out_cookie.go
> +		respWriter := w
FIY, without this change (without making the function receive a pointer to the Response Writer), the cookie wasn't ever deleted...

2022-11-28 19:56 UTC, miveronese commented on enterprise/cmd/frontend/internal/auth/oauth/middleware.go
> +			auth.RemoveSignOutCookieIfSet(r, w)
Initially, I thought this wouldn't work, but at the end it worked! 🎉 
Thanks for the suggestion, @pjlast . Much better this way!

2022-11-29 07:59 UTC, pjlast commented on enterprise/cmd/frontend/internal/auth/githuboauth/middleware_test.go
> -		}
But that's not the flow that this test tests. Reading the test it says:

- User is not signed in
- User tries to navigate to "http://example.com/page" sub-page
- User gets redirected to GitHub OAuth sign-in flow

This is still valid and desired behaviour. Similar goes for the test above it.

2022-11-29 14:54 UTC, pjlast approved these changes
:shipit:

2022-11-29 16:23 UTC, miveronese commented
> :shipit:

I was waiting until the build finish to ping you, @pjlast , but you were faster :D 
Thanks for insisting on the test changes  🙏

2022-11-29 16:24 UTC, miveronese commented on enterprise/cmd/frontend/internal/auth/githuboauth/middleware_test.go
> -		}
yes, you are correct!! thank you!!!

2022-11-29 16:25 UTC, merged

2022-12-02 08:42 UTC, unknwon reviewed
Nice!

2022-12-02 08:42 UTC, unknwon commented on cmd/frontend/auth/sign_out_cookie.go
> +		http.SetCookie(w, &http.Cookie{Name: SignoutCookie, Value: "", MaxAge: -1})
FYI: It is always safe to clear a cookie regardless of its existence, browser handles it. The opposite version of "upsert".