Show implementations when URL derived state points to implementations
sourcegraph/sourcegraph pull request #44908
Opened 2022-11-29 17:54 UTC by philipp-spiess

Fixes 44358

When a user clicks the "Go to implementations" link right now and the resulting references panel view does not contain any implementations, they land on a very confusing view that does not contain any information about the implementations feature:
 
<img width="1290" alt="Screenshot 2022-11-29 at 18 50 57" src="https://user-images.githubusercontent.com/458591/204605641-93f8b28b-99cc-4d60-aa3a-2e7f30f27d12.png">

This PR fixes this issue by looking at the URL derived collapse state: If the URL describes a link to the implementations page (which is the case for this button) we always want to render the implementations view, even when there are no implementations displayed.

## Test plan

https://user-images.githubusercontent.com/458591/204605898-65e1df30-ec55-4bf8-b10a-e70e40739d80.mov

_Note: The first time I click `Go to implementations` in this video I do it on a symbol that already had the references panel open for it, in which case the auto-expand doesn't seem to work. This is an unrelated issue, you can see that it works for the second symbol._

2022-11-29 17:56 UTC, philipp-spiess commented on client/web/src/codeintel/ReferencesPanel.tsx
> -    const initialCollapseState = useMemo((): Record<string, boolean> => {
TS can infer the (exact) types anyways 🤷

2022-11-29 18:03 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.02 kb) | 0.00% (+0.02 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ps/fix-references-panel-go-to-implementations/compare-report.html;tab=live_object) for a full comparison between the commits 403976f and dcfb092 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-11-30 13:41 UTC, taras-yemets approved these changes
Nice! Thank you, @philipp-spiess! 
I have a concern about the "Implementations (0 items displayed)" label. Maybe we can be more specific here and say that no implementations were found?

2022-11-30 13:42 UTC, philipp-spiess commented
@taras-yemets This is what happens:

<img width="834" alt="Screenshot 2022-11-30 at 14 42 22" src="https://user-images.githubusercontent.com/458591/204811662-65f80f7e-b476-44c0-9892-ae124d8ba1c9.png">

I added a note about the case where this does not work to the video above:

> Note: The first time I click Go to implementations in this video I do it on a symbol that already had the references panel open for it, in which case the auto-expand doesn't seem to work. This is an unrelated issue, you can see that it works for the second symbol.

2022-12-01 10:15 UTC, AlicjaSuska requested changes
Hi @philipp-spiess ! Thank you for making the changes. I think we should change the logic slightly and display the 'Implementations' section always when the bottom panel is open.

In the video that you've attached, the 'Implementations' section appears only after user clicks on 'Find implementations' but it doesn't appear when they click on 'Find references'. I think that it's not consistent - we should either display just one section that user 'requested' (not a good solution) or all sections every time we open the panel (I think this is the desired option).

Could you please make this change? Thank you!

2022-12-01 10:20 UTC, philipp-spiess commented
Sure that's not a problem but I’m curious why we had this check in the first place, I'll do some research!

2022-12-01 12:40 UTC, philipp-spiess commented
@AlicjaSuska Updated the PR and the test plan. Please re-review.

2022-12-01 14:03 UTC, AlicjaSuska approved these changes
Works great! Thank you @philipp-spiess

2022-12-01 14:22 UTC, merged