web: add webhook creation page.
sourcegraph/sourcegraph pull request #45159
Opened 2022-12-05 12:40 UTC by sashaostrikov

### Quick demo

https://user-images.githubusercontent.com/94846361/205638661-ce6254a7-179b-4019-8dce-65c46d3cbeac.mov

### Test plan
Storybook and local sg run.

Closes https://github.com/sourcegraph/sourcegraph/issues/43488. (finally)

## App preview:

- [Web](https://sg-web-ao-ui-webhooks-create-webhook-view.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

2022-12-05 13:02 UTC, ryanslade commented
Nice, just watched the video, haven't looked at the code yet.

Drive by comment:

I assume the "send test event" button doesn't do anything yet? In that case, we should probably hide it.

2022-12-05 16:48 UTC, cbart reviewed
With my limited react knowledge this looks very reasonable. But you probably want someone with more experience to look at it as well.

2022-12-05 16:48 UTC, cbart commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                            <Input
Should we actually provide faster feedback, by not displaying the secret input, but a label stating there is no secret for bitbucket cloud ahead of time? Seems like less friction for the customer.

2022-12-05 17:01 UTC, sashaostrikov commented
> I assume the "send test event" button doesn't do anything yet? In that case, we should probably hide it.

makes sense, I'll remove it!

2022-12-05 18:55 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                            <Input
@cbart 
thanks for this comment!
I thought about it but decided that the code might look hacky to handle this case.
But now I decided to include this, because UX is really improved and it is worth even not the most beautiful code.

Quick demo:

https://user-images.githubusercontent.com/94846361/205719622-3ea8fc7a-0e27-428e-a4db-d398021606a4.mov

2022-12-05 19:33 UTC, cbart commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                            <Input
👍

2022-12-05 22:04 UTC, mollylogue commented
This is maybe a "nice to have" that we could follow up on later, but could we grey out or remove the secret box when BB Cloud is selected? It seems like better UX. I'm fine w/ us addressing that later on, though.

2022-12-06 06:28 UTC, pjlast commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +function prettyPrintExternalServiceKind(kind: ExternalServiceKind): string {
So we have this function: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/actions/GoToCodeHostAction.tsx?L282:17

Might be worth using/expanding that, instead of having another function that basically does the same thing.

2022-12-06 08:55 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +function prettyPrintExternalServiceKind(kind: ExternalServiceKind): string {
thanks! I tried to find something like that, but didn't succeed. I will expand it and adjust for my usage (just the name without an icon)

2022-12-06 10:52 UTC, mrnugget requested changes
I think "kind -> url" logic should be cleaned up before we merge this. We also should handle errors.

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +    )
Have you tried using `useQuery` here and using the same GraphQL query under the hood? I suspect that would make the code a lot cleaner, especially since you don't have to do the additional `loading`/`setLoading` state manaagement

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +    const [kindsToUrls, setKindsToUrls] = useState<Map<ExternalServiceKind, string[]>>(new Map())
I don't understand why we need `kinds` and `kindsToUrls` -- shouldn't `kindsToUrls.keys()` be equivalent to `kinds`?

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +    }, [extSvcKindsOrError])
This whole thing doesn't feel _nice_. It's hard to understand and there's a lot of brittle behaviour in it (why do we always pick the first URL?).

How about only using a single data structure, the `Map`, where you have `kind => url` mapping. It seems like that's what we want, right? A single URL per code host kind. Why not express that in the data structure instead of doing `[0]` in a bunch of places?

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                codeHostURN: kindsToUrls.get(selected)?.[0] || '',
See above. this feels really brittle. I think we should return early here and/or show an error if the kind is invalid.

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +    }, [])
Do you need the second arg if it's `[]`?

Also: do you even need `useCallback` here?

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                    Please add an external service to proceed with webhooks creation.
```suggestion
                    Please add a code host connection to proceed with webhooks creation.
```

And also link to the page.

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                    Error during getting external services.
Remember: to users it's "code host connections"
```suggestion
                    Error during getting code host connections.
```

2022-12-06 10:52 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                            createWebhook({ variables: convertWebhookToCreateWebhookVariables(webhook) }).catch(noop)
`.catch(noop)`? Shouldn't we show an error?

2022-12-06 12:22 UTC, mrnugget commented
Doesn't seem to work for me: 
<img width="1209" alt="screenshot_2022-12-06_13 22 11@2x" src="https://user-images.githubusercontent.com/1185253/205911411-9bf3de25-5dce-4e59-b0f1-00bc41387e19.png">

2022-12-06 15:11 UTC, mrnugget commented
Update from IAM planning: @pjlast is going to take this PR over the finish line.

2022-12-06 23:09 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                            createWebhook({ variables: convertWebhookToCreateWebhookVariables(webhook) }).catch(noop)
the error is handled (`error: createWebhookError`) when `useMutation` is called here:
```js
    const [createWebhook, { error: createWebhookError, loading: creationLoading }] = useMutation<
        CreateWebhookResult,
        CreateWebhookVariables
    >(CREATE_WEBHOOK_QUERY, { onCompleted: data => history.push(`/site-admin/webhooks/${data.createWebhook.id}`) })
```

Then `createWebhookError` is used to show an alert like so:
```js
{createWebhookError && (
    <Alert variant="danger" className="mt-2">
        Failed to create webhook: {createWebhookError.message}
    </Alert>
)}
```

2022-12-06 23:14 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +    )
used `useQuery` and tried to simplify logic here:
3296911a8bd8022808f15411eb8cd9cdef9c4d01

2022-12-06 23:17 UTC, sashaostrikov commented
@mrnugget tried to address the comments. PTAL at new commits.

I'm open to suggestions on how to simplify the logic further and get the PR over the line soon :)

2022-12-07 09:15 UTC, mrnugget approved these changes
Looking much better but left a few comments I think we should address

2022-12-07 09:15 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +            }
This shouldn't happen right? This is just a sanity check? Because if it does happen through user action, then I think we should show that error with an `ErrorAlert` or something. If this is purely sanity check: let's keep it like it us

2022-12-07 09:15 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                ) : (
I don't think we should show that here. We only allow code hosts with URLs for webhooks and for those we enforce a schema. So technically a user shouldn't ever run into this.

Either they have code hosts of the supported type (github, gitlab, bitbucket) or they need to add one.

2022-12-07 09:15 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                                </Alert>
I think we should use `ErrorAlert` here

2022-12-07 09:15 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +    }
I think we can remove this whole function, maybe. We have this function here:

https://github.com/sourcegraph/sourcegraph/blob/8af89f8555317b7524328a533dc330b00e29dfcc/client/web/src/components/externalServices/externalServices.tsx#L1472

That means we can get the `AddExternalServiceOptions` given a `ExternalServiceKind`. And those options have a `title`, which we can and should probably use.

2022-12-07 09:20 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +            }
exactly, this cannot happen.

The check which ensures it happens in `validateKindsAndUrls` and the page shows a warning sign instead of a form when _at least 1 external service doesn't have a(t least one) URL_. 
This way `onCodeHostTypeChange` cannot be triggered by any circumstance.

I've added this check to fight the compiler but needed to suppress one thing below anyways :(

2022-12-07 09:22 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                ) : (
Yep, I understood that the schema is verified, but decided to cover up the UI from throwing ugly uncaught `ArrayIndexOutOfBounds`-like errors.

I can easily remove it and trust our code :)

2022-12-07 09:27 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +                                </Alert>
nice catch, makes total sense!

2022-12-07 09:31 UTC, pjlast commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +            }
@sashaostrikov this is because, even if the map has the entry, the array could still have no entries.

I would recommend doing it as follows and removing the ts-ignore:

```typescript
    const onCodeHostTypeChange = useCallback<React.ChangeEventHandler<HTMLSelectElement>>(
        event => {
            const selected = event.target.value as ExternalServiceKind
            const selectedUrns = kindsToUrls.get(selected)
            if (selectedUrns !== undefined && selectedUrns.length > 0) {
                setWebhook(webhook => ({
                    ...webhook,
                    codeHostKind: selected,
                    codeHostURN: selectedUrns[0],
                }))
            }
        },
        [kindsToUrls]
    )
```

2022-12-07 09:33 UTC, sashaostrikov commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +    }
I agree, I totally forgot about this nice thing

2022-12-07 09:50 UTC, pjlast commented on client/web/src/site-admin/SiteAdminWebhookCreatePage.tsx
> +        [kindsToUrls]
Adding as a separate conversation because @mrnugget resolved the other conversation 😛 

It still complains because you're calling kindsToUrls.get twice, and the compiler can't guarantee that the map's entries has not changed between calls. So the way to get it to stop complaining without disable linting errors (which I would strongly advise against) is as follows:

```suggestion
            const selected = event.target.value as ExternalServiceKind
            const selectedUrns = kindsToUrls.has(selected)
            if (!selectedUrns) {
                throw new Error(
                    `${prettyPrintExternalServiceKind(
                        selected
                    )} code host connection has no URL. Please check related code host configuration.`
                )
            }
            const selectedUrn = selectedUrns[0]
            setWebhook(webhook => ({
                ...webhook,
                codeHostKind: selected,
                codeHostURN: selectedUrn,
            }))
        },
        [kindsToUrls]
```

Might be worth doing a length check on selectedUrns as well, but this will resolve the issue without resorting to ignoring the compiler

2022-12-07 09:51 UTC, pjlast approved these changes
Looks good to me, I'd just prefer to not ignore the compiler when there are ways to do it correctly 😄

2022-12-07 11:56 UTC, sashaostrikov commented
@mrnugget @pjlast 
gentlemen, I've fixed the last bunch of comments [here](https://github.com/sourcegraph/sourcegraph/pull/45159/commits/746c2efe98bdc6f87d6f714041b24a5ba32e8e47)

Please take one last look :)

Thanks for your reviews!

2022-12-07 12:19 UTC, merged