[Pagination] add new connection resolver
sourcegraph/sourcegraph pull request #45167
Opened 2022-12-05 13:13 UTC by thenamankumar

Closes: https://github.com/sourcegraph/sourcegraph/issues/45247
This PR implements a new connection resolver helper, which is planned to be used to implement cursor-based bi-directional pagination throughout our software. This is the first PR which only implements the helper along with its basic unit tests. 

The upcoming PRs will include its integration with SavedSearches resolver. The custom sort and filters will be added separately as well.

## Test plan

Unit tests are added. 

To know more about how this helper will be used,[ check this out](https://github.com/sourcegraph/sourcegraph/pull/44347/files#diff-38da2cf9b89abf1529ca89b06fb51fcae0870e42a345e1d3b1fd8169c49cb308).

2022-12-05 13:25 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	ID() graphql.ID
```suggestion
```

The `ID()` is actually not required as we call to `MarshalCursor` instead which needs to be implemented anyways. I recommend we remove it because this way we can also make it work for legacy routes that can not be paginated in sql (e.g. git endpoints). E.g. I’m migrating the repo contributors which is not backend by a SQL query so the individual returns have no ID.

2022-12-05 13:25 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
I think there's a bug for backward pagination with:

`last: 10, before: null, after: null, first: null`

In this case, if we fetch 11 records from the database, we will now set `hasNextPage` to true even though a backward pagination without a `before` _never_ has a next page (it starts at the very end.

```suggestion
func (p *ConnectionPageInfo[N]) HasNextPage() bool {
	if p.args.First != nil {
		return p.fetchedNodesCount > p.args.Limit()
	}
	return p.args.Before != nil
}
```

In this snipped I use `First` to describe a backward navigation (both `first: xyz, after: xyz` and `first: xyz` have a first set).

2022-12-05 13:25 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
This logic works for all cases I think but it can be similfied a bit to the inverse of my above:

```suggestion
func (p *ConnectionPageInfo[N]) HasNextPage() bool {
	if p.args.First != nil {
		return p.fetchedNodesCount > p.args.Limit()
	}
	return p.args.Before != nil
}
```

2022-12-05 13:29 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	ID() graphql.ID
I can remove it from here, but in the graphql interface, any connection node MUST have an id. Why do you think in any graphql connection, a node won't have any ID? If they naturally don't then we construct an ID for them using their other props. The ID field for the git endpoint can be the endpoint URL itself. But it should definitely have an id. 


Using the ID only, you can implement table row selection and other features in the frontend. So ID should be MUST rather than being optional. RelayConnectionNode also have a required ID field.

2022-12-05 13:34 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	ID() graphql.ID
Yeah this makes sense. For the loading repo contributors via GraphQL I guess we could construct an ID based on the email address of the computer and the repo name perhaps? 

Currently in the frontend we don't require that items _must_ have an ID, and since I didn't have anything that made sense, I figured we could also drop the requirement here since it doesn't bring us a benefit here either.

2022-12-05 13:40 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
resolved.

2022-12-05 13:40 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
fixed and added a test to cover it.

2022-12-05 13:42 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	ID() graphql.ID
Yeah, I think pushing things to must-have IDs is better long term. 

Should I consider this resolved?

2022-12-05 14:06 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	ID() graphql.ID
Yeah I think that makes sense.

2022-12-05 14:07 UTC, philipp-spiess reviewed
Looks great from my side! I'll leave this open for a bit so that someone with more backend experience can also look over it though (\*cough\* @mrnugget) 🙈

2022-12-05 17:14 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	}
From our limited research by looking at other GraphQL APIs it seems best practice to require the client to define a default here. It's otherwise undefined what it means to start a page without providing a default and some of our older implementations even return _all possible rows_. IMO it's fine to be restrictive on the backend, the new frontend abstraction defines a default anyway so that you don't have to care about it when implementing it.

2022-12-05 21:27 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	 * they are sorted in opposite directions in SQL query.*/
In graphql paradigm, we never do a `nextPage()` to find out if the next page exists. It must come in the pageInfo. That is how Relay Connections are implemented and all the other ones too.

What you are saying only happens in REST, where you keep on paginating until the page returns an empty list.

2022-12-05 21:30 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	}
We looked at the Github API (which surely isn't the best) but they throw error when you don't provide any. 

I understand that with respect to gql interface, it looks more correct that optional args must have a default behaviour. But the error here implements a safeguard for the cases where the user might unintentionally miss passing the args.

2022-12-05 21:31 UTC, thenamankumar commented on internal/database/helpers.go
> +		queryArgs.Limit = sqlf.Sprintf("LIMIT %d", *p.Last)
YES!!!

And we are going to solve this while adding custom sort capabilities in future PRs. Consider this iterative work.

2022-12-05 21:32 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
when calculative pageInfo, we need to count nodes. so if in the query we are fetch both nodes and pageInfo (which is always the case) we will need to compute it twice.

2022-12-06 09:15 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +const MAX_PAGE_SIZE int32 = 100
Not having a max limit is a security concern. The user may make a request with first=100000, and that might bring the system down. I have seen it happen in so many places. 

But I do agree with you that this should not be hard-coded, so I'll go ahead and make it programmatic. We should be able to configure the max limit for each connection separately. I'll still have the default hard max limit set to 1000.

wdyt? 

cc: @mrnugget

2022-12-06 09:20 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +const MAX_PAGE_SIZE int32 = 100
cc: @philipp-spiess

2022-12-06 09:23 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +func applyMaxPageSize(limit int32) int {
because ` len(nodes) > r.args.Limit()` does not work with `int32` and we need `int` there.

2022-12-06 09:27 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +func (a *ConnectionResolverArgs) Limit() int {
because len(nodes) > r.args.Limit() does not work with int32 and we need int there.

2022-12-06 09:46 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +func (a *ConnectionResolverArgs) Limit() int {
and we never typecast Limit() where we use it

2022-12-06 09:48 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	}
Because the response of the SQL query will be *int32 and not int32 so we don't want to write an additional 1 line everywhere.

2022-12-06 09:55 UTC, mrnugget requested changes
I did a first round of review and mostly commented on code style and quality. It's still a bit hard to judge how far this interface will go without having to be changed, especially since we don't have an example in here.

Requesting changes so that you
* clean up the tests. There's a lot of code in there that can be removed. I bet that whole test file could be 1/4 of its size. (see the one test helper example that I commented)
* add comments to the tests to explain what's being tested where
* make the assertions in the tests clearer: does it matter that we pass in this function, does it not? do we assert what nodes are returned or not? for some of them you want to test the behaviour of your logic here (that the order of the nodes is reverserd, for example, but I don't see that here)
* clean up the `ConnectionResolver` (change the int/int32 stuff so it's less casting, add docstrings, remove some superfluous checks, ...)

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +type TestConnectionNode struct {
All of these types should be unexported, just to make it clearer that they're test-only.

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	ComputeNodesCalled int
I'd also unexport all the fields. Not needed in test code.

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	store := &TestConnectionStore{t, func(context.Context, *database.PaginationArgs) { return }, 0, 0}
```suggestion
	store := &TestConnectionStore{t, func(context.Context, *database.PaginationArgs) { }, 0, 0}
```

Also: you should name the fields. That helps readability and it allows you to use default values here.

```suggestion
	store := &TestConnectionStore{t: t, ComputeNodes: func(context.Context, *database.PaginationArgs) { }}
```

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	s.TestComputeNodes(ctx, args)
I would've assumed that it's this:

```suggestion
	nodes := s.TestComputeNodes(ctx, args)
```

Just as a nitpick/thought here.

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	}
```suggestion
	if count != TOTAL_COUNT {
		t.Fatal("wrong count. want=%d, have=%d", TOTAL_COUNT, count)
	}
```

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +				Before: nil,
```suggestion
				First:  toInt32(6),
```

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +		func(_ context.Context, args *database.PaginationArgs) {
As above: name the fields and remove `0, 0`

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	)
```suggestion
	resolver, err := NewConnectionResolver[TestConnectionNode](store, &ConnectionResolverArgs{
		First:  toInt32(5),
	})
```

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +		}, 0, 0}
As above: name fields, remove `nil`, remove `0`s

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	)
```suggestion
	resolver, err := NewConnectionResolver[TestConnectionNode](store, &ConnectionResolverArgs{
		Last:   toInt32(5),
	})
```

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +func TestConnectionNodesLastArg(t *testing.T) {
This test should also test when you have, say, 10 nodes and pass in `last: 5` that it only returns 5.

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	}
I think you should assert which nodes are returned here and in which order. (You can do that by comparing just the slice literal)

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	t                  *testing.T
You don't use that anywhere. Either remove it or pass it in to `TestComputeNodes`. I personally would pass it into `testComputeNodes`

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +}
I think these assertions are a bit duplicative here. The real assertion in this test is that the `after` is passed to the store, right? If so I'd highlight that and remove assertions that are covered by other tests.

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	)
This is a bit confusing as to what's being tested here. I don't understand why 1 node is returned when the `beforeCursor` is `0`. Can you add a comment that explains what's going on?

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	}
It's booleans, we can assert those in a cleaner way :)

```suggestion
	if !pageInfo.HasNextPage() {
		t.Fatal("hasNextPage should be false, but is true")
	}

	if !pageInfo.HasPreviousPage() {
		t.Fatal("hasPreviousPage should be false, but is true")
	}
```

2022-12-06 09:55 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	if diff := cmp.Diff(1, store.ComputeNodesCalled); diff != "" {
No `cmp.Diff` needed here.

2022-12-06 11:23 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		 * them in correct order, to reduce complexity */
Also, it is covered in tests. The start, end cursor checks in PageInfo tests cover it.

2022-12-06 11:55 UTC, eseliger reviewed
a bunch of nit comments here and there, nothing major. Great work :) 

I would love to see this applied to one or two of our existing connections in different parts of the code base that use slightly different patterns, to validate that we can apply this broadly

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	ID() graphql.ID
GraphQL does not prescribe that you have to use a field of ID type anywhere. We have an Interface type called `Node` that we often use because it makes it possible to retrieve individual items, but IMO if an item has an ID, it should implement `Node` properly, and thus be retrievable by its ID regardless of context. I am not sure this will work for 100% of entities, or that we really want to allow every resource to be fetched by ID. What's the reason we need to include ID here?

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +func applyMaxPageSize(limit int32) int {
a function that takes an int32 and returns an int feels slightly weird to me, but not so much that it would be blocking.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +const MAX_PAGE_SIZE int32 = 100
It should 100% be configurable, but I agree having an upper boundary makes a ton of sense, for batch changes resolvers we added that 2 years ago.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
+1

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
also syncOnce doesn't need to be initialized.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +var TOTAL_COUNT = int32(10)
```suggestion
var testTotalCount = int32(10)
```

2022-12-06 11:55 UTC, eseliger commented on internal/database/helpers.go
> +func (a *QueryArgs) AppendWhere(query *sqlf.Query) *sqlf.Query {
Agreed.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	}
GraphQL supports setting default values for arguments, this is IMO what we should use as it also is well documented at the source of truth - the schema.

But the reality is that for some resolvers today we don't have a default set and also don't enforce a maximum page size, so without breaking changes we cannot do this check here, realistically.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	cursor, err = p.store.MarshalCursor(endNode)
this is unsafe, as at the end of a connection we cannot reliably tell if there will be a next page based on this or not. 
`endCursor` must only be non-null, if a next page exists.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +package graphqlutil
General note: I would love to see a PoC reference implementation on one of our connections - to validate that it can work.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	UnMarshalCursor(string) (*int32, error)
These two are not really store methods, can we store them separately?

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	})
For some of our current resolvers we resolve the totalCount and the nodes in a single transaction, to make sure the data is coherent. I personally don't think that is necessary, but we should settle on one approach for that, whichever of the two it will be.

cc @efritz

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	})
Why do we need to memoize this? I don't see it used anywhere else.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		return nil, err
nit: i personally would make this a private method called `computeNodes` or something like that, using a publicly exposed method for internal consumption feels a bit weird.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		 * them in correct order, to reduce complexity */
Example data:
```
[A B C D E F G H]
```

When I say `first: 3` I expect to get

```
[(A B C) D E F G H]
```

with the read head positioned at A _first_, so the nodes would be `[A, B, C]`

When I say `last: 3`I expect to get

```
[A B C D E (F G H)]
```

with the read head positioned at H _last_, so the nodes would be `[F, G, H]`

This refers to https://relay.dev/graphql/connections.htm#sec-Edge-order. You should link to it in the code.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	}
Can we move this onto the store instead? Ie. make the store for `Nodes()` return `nodes, nextCursor, error`. Then the store can decide how to do this.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		r.data.nodes, r.data.nodesError = r.store.ComputeNodes(ctx, paginationArgs)
I find it a bit weird that the store would return resolvers and not DB types.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +}
I don't think these two fields need to live in a separate type, can inline where it's used.

2022-12-06 11:55 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +package graphqlutil
nice test suite :)

2022-12-06 14:03 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	cursor, err = p.store.MarshalCursor(endNode)
> `endCursor` must only be non-null, if a next page exists.

I don't think this is true? It can be `null` if the result returns _no_ items but to know if there's a next page or not, I think the idea is to use `hasNextPage` instead.

https://relay.dev/graphql/connections.htm#sec-Edge-order

2022-12-06 14:05 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +package graphqlutil
https://github.com/sourcegraph/sourcegraph/pull/44347/files#diff-38da2cf9b89abf1529ca89b06fb51fcae0870e42a345e1d3b1fd8169c49cb308 Here's an example that we worked on. before. We decided to pull out this part into a separate PR though.

2022-12-06 14:22 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +package graphqlutil
Ah nice, I'll take a look at it!

2022-12-06 14:23 UTC, eseliger commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	cursor, err = p.store.MarshalCursor(endNode)
Oh, interesting! We've done that wrong all the time then 😆

2022-12-07 15:15 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	ID() graphql.ID
> but IMO if an item has an ID, it should implement Node properly, and thus be retrievable by its ID regardless of context. I am not sure this will work for 100% of entities, or that we really want to allow every resource to be fetched by ID. What's the reason we need to include ID here?

👍  It would be cool if we could use the new style of pagination even for entries that are not `Node`s.  E.g. [here](https://github.com/sourcegraph/sourcegraph/pull/45070/) I’m using the new connection resolver for repository contributors which currently have no form of ID and if I add some I'd have to encode a lot of information to find this again and even then I need to write super awkward code to look up the contributor again (I'll basically need to load all repo contributors first because there's no constant lookup as far as I understand git shortlog).

I know Relay requires every node inside an edge to have a globally unique ID and that is because they do caching on a per-node level but the reality for us is that we have probably many more collections alrighty that are awkward like the one I mentioned and depend on git commands where a ID doesn't really make sense.

2022-12-07 15:20 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	})
The re-ordering only really makes sense when we use SQL for the connection data. We have a lot of data that is served directly from gitserver though ([like repo contributors](https://github.com/sourcegraph/sourcegraph/pull/45070/)). It feels super awkward to use this pattern together with data like that because I basically need to reverse it on purpose just to have it reversed again, Lol: https://github.com/sourcegraph/sourcegraph/pull/45070/files#diff-48c9077636ee926c31843ad917e223d19487cc971920298622d7a6dc8754255fR116-R119

I wonder if we can do this differently? I don't have to use `PaginationArgs#SQL` in my custom collection but somehow am still forced to work around this. Maybe this could be another method on `PaginationArgs` that somehow does that for me?

2022-12-12 10:41 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +func TestConnectionNodesLastArg(t *testing.T) {
this is covered under another test below: TestConnectionNodesWithLimit

2022-12-12 11:01 UTC, thenamankumar commented on internal/database/helpers.go
> +func (p *PaginationArgs) SQL() (queryArgs *QueryArgs, err error) {
resolved

2022-12-12 11:13 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	if r.data.totalError != nil || r.data.total == nil {
Just because sql always return *int32 & err so I want to make it pipeable.

2022-12-12 11:34 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		 * them in correct order, to reduce complexity */
These tests will be covered with proper integration of connection resolver with a db store. Right now these are just basis checks to cover if the correct args are paased down by connection resolver. 

The SQL queries are required to pull correct data.

2022-12-12 11:43 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	})
in case we do. just a safeguard, given it will be used by a client.

2022-12-12 12:27 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +const MAX_PAGE_SIZE int32 = 100
made configurable

2022-12-12 12:27 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	return int(math.Min(float64(limit), float64(MAX_PAGE_SIZE)))
done

2022-12-12 12:32 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	}
it doesn't make sense because those are anyways hardcoded. I'll make those tests when adding tests for actual implementation.

2022-12-12 12:33 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	t                  *testing.T
this is being used everywhere now.

2022-12-12 12:33 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +}
extracted

2022-12-12 12:37 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	})
Can we make it an incremental change under this [PR](https://github.com/sourcegraph/sourcegraph/pull/45070/) only.

2022-12-12 12:43 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	})
Of course! Do you have an idea how we could build that?

2022-12-12 12:51 UTC, mrnugget reviewed
Tests and code looks much better! Thanks! There's still a few comments that are unanswered, so I'm waiting for those to be either answered or resolved until approval

2022-12-12 12:51 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	// ComputeTotal is required to fetch the total number of items.
```suggestion
	// ComputeTotal returns the total count of all the items in the connection, independent of pagination arguments.
```

See: https://go.dev/blog/godoc for how to write docstrings in Go.

Same goes for the other methods here.

2022-12-12 12:51 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		r.data.nodes, r.data.nodesError = r.store.ComputeNodes(ctx, paginationArgs)
Yeah, agree. One could build a wrapper easily, but maybe there's another way to do this.

2022-12-12 12:51 UTC, mrnugget commented on internal/database/helpers.go
> +func (a *QueryArgs) AppendWhere(query *sqlf.Query) *sqlf.Query {
Yeah, but the names are still confusing. For example `AppendWhere` would be better named `AppendWhereClauseToQuery` for example (or `AppendWhereToQuery`).

2022-12-12 12:51 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	UnMarshalCursor(string) (*int, error)
```suggestion
	UnmarshalCursor(string) (*int, error)
```

We should be consistent with the stdlib here. One example: https://pkg.go.dev/encoding/json#Unmarshal

2022-12-12 12:51 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	nodes, err = resolver.Nodes(ctx)
Linter tells me `nodes` is unused

2022-12-12 12:51 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +}
table-driven tests :) 

```suggestion
func TestConnectionPageInfoDefault(t *testing.T) {
	for _, test := range []struct {
		name string
		args *ConnectionResolverArgs
		want *pageInfoResponse
	}{
		{
			name: "default",
			args: withFirstCA(20, &ConnectionResolverArgs{}),
			want: &pageInfoResponse{startCursor: "0", endCursor: "1", hasNextPage: false, hasPreviousPage: false},
		},
		{
			name: "first page",
			args: withFirstCA(1, &ConnectionResolverArgs{}),
			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: false},
		},
		{
			name: "second page",
			args: withAfterCA("0", withFirstCA(1, &ConnectionResolverArgs{})),
			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: true},
		},
		{
			name: "backward first page",
			args: withBeforeCA("0", withLastCA(1, &ConnectionResolverArgs{})),
			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: true},
		},
		{
			name: "backward first page without cursor",
			args: withLastCA(1, &ConnectionResolverArgs{}),
			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: false, hasPreviousPage: true},
		},
		{
			name: "backward last page",
			args: withBeforeCA("0", withBeforeCA("0", withLastCA(20, &ConnectionResolverArgs{}))),
			want: &pageInfoResponse{startCursor: "1", endCursor: "0", hasNextPage: true, hasPreviousPage: false},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			store := &testConnectionStore{t: t}
			resolver, err := NewConnectionResolver[testConnectionNode](store, test.args, nil)
			if err != nil {
				t.Fatal(err)
			}
			testResolverPageInfoResponse(t, resolver, store, test.want)
		})
	}
}
```

2022-12-12 13:30 UTC, mrnugget commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +}
Here's how you can table-drive the other tests further up in the file:

```diff
diff --git a/cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go b/cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
index 74e7f77b10..c12dd31d58 100644
--- a/cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
+++ b/cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
@@ -166,54 +159,55 @@ func testResolverNodesResponse(t *testing.T, resolver *ConnectionResolver[testCo
 	}
 }
 
-func TestConnectionNodesDefaultArgs(t *testing.T) {
-	store := &testConnectionStore{t: t, expectedPaginationArgs: withFirstPA(6, &database.PaginationArgs{})}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withFirstCA(5, &ConnectionResolverArgs{}), nil)
-	if err != nil {
-		t.Fatal(err)
+func TestConnectionNodes(t *testing.T) {
+	for _, test := range []struct {
+		name           string
+		connectionArgs *ConnectionResolverArgs
+
+		wantPaginationArgs *database.PaginationArgs
+		wantNodes          int
+	}{
+		{
+			name:               "default",
+			connectionArgs:     withFirstCA(5, &ConnectionResolverArgs{}),
+			wantPaginationArgs: withFirstPA(6, &database.PaginationArgs{}),
+			wantNodes:          2,
+		},
+		{
+			name:               "last arg",
+			wantPaginationArgs: withLastPA(6, &database.PaginationArgs{}),
+			connectionArgs:     withLastCA(5, &ConnectionResolverArgs{}),
+			wantNodes:          2,
+		},
+		{
+			name:               "after arg",
+			wantPaginationArgs: withAfterPA(0, withFirstPA(6, &database.PaginationArgs{})),
+			connectionArgs:     withAfterCA("0", withFirstCA(5, &ConnectionResolverArgs{})),
+			wantNodes:          2,
+		},
+		{
+			name:               "before arg",
+			wantPaginationArgs: withBeforePA(0, withLastPA(6, &database.PaginationArgs{})),
+			connectionArgs:     withBeforeCA("0", withLastCA(5, &ConnectionResolverArgs{})),
+			wantNodes:          2,
+		},
+		{
+			name:               "with limit",
+			wantPaginationArgs: withBeforePA(0, withLastPA(2, &database.PaginationArgs{})),
+			connectionArgs:     withBeforeCA("0", withLastCA(1, &ConnectionResolverArgs{})),
+			wantNodes:          1,
+		},
+	} {
+		t.Run(test.name, func(t *testing.T) {
+			store := &testConnectionStore{t: t, expectedPaginationArgs: test.wantPaginationArgs}
+			resolver, err := NewConnectionResolver[testConnectionNode](store, test.connectionArgs, nil)
+			if err != nil {
+				t.Fatal(err)
+			}
+
+			testResolverNodesResponse(t, resolver, store, test.wantNodes)
+		})
 	}
-
-	testResolverNodesResponse(t, resolver, store, 2)
-}
-
-func TestConnectionNodesLastArg(t *testing.T) {
-	store := &testConnectionStore{t: t, expectedPaginationArgs: withLastPA(6, &database.PaginationArgs{})}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withLastCA(5, &ConnectionResolverArgs{}), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverNodesResponse(t, resolver, store, 2)
-}
-
-func TestConnectionNodesAfterArgs(t *testing.T) {
-	store := &testConnectionStore{t: t, expectedPaginationArgs: withAfterPA(0, withFirstPA(6, &database.PaginationArgs{}))}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withAfterCA("0", withFirstCA(5, &ConnectionResolverArgs{})), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverNodesResponse(t, resolver, store, 2)
-}
-
-func TestConnectionNodesBeforeArgs(t *testing.T) {
-	store := &testConnectionStore{t: t, expectedPaginationArgs: withBeforePA(0, withLastPA(6, &database.PaginationArgs{}))}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withBeforeCA("0", withLastCA(5, &ConnectionResolverArgs{})), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverNodesResponse(t, resolver, store, 2)
-}
-
-func TestConnectionNodesWithLimit(t *testing.T) {
-	store := &testConnectionStore{t: t, expectedPaginationArgs: withBeforePA(0, withLastPA(2, &database.PaginationArgs{}))}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withBeforeCA("0", withLastCA(1, &ConnectionResolverArgs{})), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverNodesResponse(t, resolver, store, 1)
 }
 
 type pageInfoResponse struct {
@@ -259,62 +253,50 @@ func testResolverPageInfoResponse(t *testing.T, resolver *ConnectionResolver[tes
 	}
 }
 
-func TestConnectionPageInfoDefault(t *testing.T) {
-	store := &testConnectionStore{t: t}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withFirstCA(20, &ConnectionResolverArgs{}), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverPageInfoResponse(t, resolver, store, &pageInfoResponse{startCursor: "0", endCursor: "1", hasNextPage: false, hasPreviousPage: false})
-}
-
-func TestConnectionPageInfoFirstPage(t *testing.T) {
-	store := &testConnectionStore{t: t}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withFirstCA(1, &ConnectionResolverArgs{}), nil)
-	if err != nil {
-		t.Fatal(err)
+func TestConnectionPageInfo(t *testing.T) {
+	for _, test := range []struct {
+		name string
+		args *ConnectionResolverArgs
+		want *pageInfoResponse
+	}{
+		{
+			name: "default",
+			args: withFirstCA(20, &ConnectionResolverArgs{}),
+			want: &pageInfoResponse{startCursor: "0", endCursor: "1", hasNextPage: false, hasPreviousPage: false},
+		},
+		{
+			name: "first page",
+			args: withFirstCA(1, &ConnectionResolverArgs{}),
+			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: false},
+		},
+		{
+			name: "second page",
+			args: withAfterCA("0", withFirstCA(1, &ConnectionResolverArgs{})),
+			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: true},
+		},
+		{
+			name: "backward first page",
+			args: withBeforeCA("0", withLastCA(1, &ConnectionResolverArgs{})),
+			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: true},
+		},
+		{
+			name: "backward first page without cursor",
+			args: withLastCA(1, &ConnectionResolverArgs{}),
+			want: &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: false, hasPreviousPage: true},
+		},
+		{
+			name: "backward last page",
+			args: withBeforeCA("0", withBeforeCA("0", withLastCA(20, &ConnectionResolverArgs{}))),
+			want: &pageInfoResponse{startCursor: "1", endCursor: "0", hasNextPage: true, hasPreviousPage: false},
+		},
+	} {
+		t.Run(test.name, func(t *testing.T) {
+			store := &testConnectionStore{t: t}
+			resolver, err := NewConnectionResolver[testConnectionNode](store, test.args, nil)
+			if err != nil {
+				t.Fatal(err)
+			}
+			testResolverPageInfoResponse(t, resolver, store, test.want)
+		})
 	}
-
-	testResolverPageInfoResponse(t, resolver, store, &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: false})
-}
-
-func TestConnectionPageInfoSecondPage(t *testing.T) {
-	store := &testConnectionStore{t: t}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withAfterCA("0", withFirstCA(1, &ConnectionResolverArgs{})), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverPageInfoResponse(t, resolver, store, &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: true})
-}
-
-func TestConnectionPageInfoBackwardFirstPage(t *testing.T) {
-	store := &testConnectionStore{t: t}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withBeforeCA("0", withLastCA(1, &ConnectionResolverArgs{})), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverPageInfoResponse(t, resolver, store, &pageInfoResponse{startCursor: "0", endCursor: "0", hasNextPage: true, hasPreviousPage: true})
-}
-
-func TestConnectionPageInfoBackwardFirstPageWithoutCursor(t *testing.T) {
-	store := &testConnectionStore{t: t}
-	resolver, err := NewConnectionResolver[testConnectionNode](store, withLastCA(1, &ConnectionResolverArgs{}), nil)
-	if err != nil {
-		t.Fatal(err)
-	}
-
-	testResolverPageInfoResponse [...]

2022-12-12 16:46 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		r.data.nodes, r.data.nodesError = r.store.ComputeNodes(ctx, paginationArgs)
Might be the naming issue but `store` here is not the db store. I can rename it though.

2022-12-12 16:48 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	}
We tend to extract all the pagiantion logic here. If we leave it to the client, then we are writing the same logic over and over in every part of the codebase, everytime we implement a connection.

2022-12-12 16:49 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	return p.args.Before != nil
oh good idea. this needs to be update in the test as well.

2022-12-12 16:52 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver_test.go
> +	)
because the return values are hard coded. this util doesn't handle that at all. The client is provided args to be used while building the SQL query to return correct items. 

We just care about the right args being provided to the client here. 

Also only 1 item is returned because the `First` is 1 here. We can even remove the `before` which I'll do now.

2022-12-12 16:52 UTC, thenamankumar commented on internal/database/helpers.go
> +func (a *QueryArgs) AppendWhere(query *sqlf.Query) *sqlf.Query {
I'll rename.

2022-12-13 10:38 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	})
I think for most of the pagiantion we do at frontend, it is based of a DB table and it makes sense to do separate queries.

2022-12-13 10:44 UTC, mrnugget approved these changes
Let's go!

2022-12-13 12:00 UTC, philipp-spiess commented
@thenamankumar Looks like auto-merge is bugged/doesn't update when `main` was unblocked 🙈  I'll re-trigger it.

<img width="973" alt="Screenshot 2022-12-13 at 13 00 09" src="https://user-images.githubusercontent.com/458591/207312284-c2c39e60-25ed-44a6-8d11-5a1ada22ff8f.png">

2022-12-13 15:28 UTC, merged