Follow-up comments on PR
sourcegraph/sourcegraph pull request #45207
Opened 2022-12-05 19:02 UTC by pjlast

Follow-up comments from this PR: https://github.com/sourcegraph/sourcegraph/pull/44994#pullrequestreview-1204920653

Removes unnecessary nulls, which is nice :)

## Test plan

Tests adjusted where applicable.

2022-12-05 19:09 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/pjlast/graphql-webhook-updates-follow-up/compare-report.html;tab=live_object) for a full comparison between the commits 429077a and 61342b3 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-12-06 08:19 UTC, sashaostrikov approved these changes
That's nice! We really cannot have empty fields (except `secret`) during an update, so this change makes total sense.

2022-12-06 08:22 UTC, pjlast commented
There is always the option of just hard updating the webhook at the given ID with all the fields provided, and skip the whole "Only update certain fields". Basically doing a replace

2022-12-06 08:31 UTC, ryanslade approved these changes

2022-12-06 08:53 UTC, mrnugget requested changes

2022-12-06 08:53 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    updateWebhook(id: ID!, name: String!, codeHostKind: String!, codeHostURN: String!, secret: String): Webhook!
Wait! In GraphQL it's totally fine to have optional fields. I wouldn't change anything here.

I only thing once we've left the `graphqlbackend` layer we should not use pointers anymore.

2022-12-06 08:53 UTC, mrnugget commented on cmd/frontend/graphqlbackend/webhooks.go
> +	CodeHostURN  string
Same as above: let's keep the `*string` _here_, since that what we do in other GraphQL resolvers too.

2022-12-06 08:53 UTC, mrnugget commented on internal/database/webhooks.go
> +	Update(ctx context.Context, newWebhook *types.Webhook) (*types.Webhook, error)
```suggestion
	Update(ctx context.Context, webhook *types.Webhook) (*types.Webhook, error)
```

2022-12-06 08:55 UTC, mrnugget commented
In short: nullable-fields in GraphQL are okay.  See [all the other `update*` mutations](https://sourcegraph.sourcegraph.com/search?q=context:global+update+file:schema%5C.graphql+repo:sourcegraph%24&patternType=standard&sm=0&groupBy=repo). Except if it really is not possible to not set those fields. But it looks like it is.

So I think nullable-strings in `graphqlbackend` are fine, but as soon as they leave that resolver, we should have `""` instead.

2022-12-06 08:57 UTC, mrnugget commented
Example: see how this mutation handles `args.user` being nullable: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/cmd/frontend/internal/batches/resolvers/resolver.go?L1068-1094

It checks whether it's nil in the resolver, then passes `0` or the value down to the service layer.

2022-12-06 10:26 UTC, mrnugget approved these changes
LGTM! Left a question about `secretStr` though which stands out. I think that can be treated just like the other fields in GraphQL/service layer and then like a pointer in database layer? But not sure (not blocking)

2022-12-06 10:50 UTC, pjlast commented on cmd/frontend/backend/webhooks.go
> +func (ws *webhookService) UpdateWebhook(ctx context.Context, id int32, name, codeHostKind, codeHostURN string, secretStr *string) (*types.Webhook, error) {
So secrets can be null, because not all providers support secrets.

I put Str in the name here simply to keep consistent with the other functions: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/webhooks.go?L26:102

But I have some reservations with how this works. For example, I'm not sure how you would delete a secret from a webhook using this API, since the empty values should actually be valid values. Or if you would ever even need to do that.

The only scenario I could think of that this might be necessary is if you want to change the type of your Webhook from GitHub to Bitbucket. But in those cases I almost think you'd be better off creating a new Webhook altogether.

cc @ryanslade @sashaostrikov do you have any thoughts here?

2022-12-06 10:54 UTC, mrnugget commented on cmd/frontend/backend/webhooks.go
> +func (ws *webhookService) UpdateWebhook(ctx context.Context, id int32, name, codeHostKind, codeHostURN string, secretStr *string) (*types.Webhook, error) {
> So secrets can be null, because not all providers support secrets.

Yeah, in the _create_ action. But in update it's the same as any other field here, no?

> I put Str in the name here simply to keep consistent with the other functions: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/backend/webhooks.go?L26:102

Then that other function is funny too :)

2022-12-06 11:03 UTC, pjlast commented on cmd/frontend/backend/webhooks.go
> +func (ws *webhookService) UpdateWebhook(ctx context.Context, id int32, name, codeHostKind, codeHostURN string, secretStr *string) (*types.Webhook, error) {
Sure, but what if you create a GitHub provider, then use the Update to change it to a BitBucket provider, which does not support Secrets?

2022-12-06 11:26 UTC, mrnugget commented on cmd/frontend/backend/webhooks.go
> +func (ws *webhookService) UpdateWebhook(ctx context.Context, id int32, name, codeHostKind, codeHostURN string, secretStr *string) (*types.Webhook, error) {
In that case you check for `""`, no? Just like the other fields.

2022-12-06 11:44 UTC, pjlast commented on cmd/frontend/backend/webhooks.go
> +func (ws *webhookService) UpdateWebhook(ctx context.Context, id int32, name, codeHostKind, codeHostURN string, secretStr *string) (*types.Webhook, error) {
Okay  I made a change, let me know if you think it's a bit better :)

2022-12-06 11:45 UTC, pjlast commented on cmd/frontend/backend/webhooks.go
> +func (ws *webhookService) UpdateWebhook(ctx context.Context, id int32, name, codeHostKind, codeHostURN string, secretStr *string) (*types.Webhook, error) {
I'm thinking now that I should probably add checks and clear the secret if switching to a non-supported code host. Let me do that quickly

2022-12-07 01:16 UTC, sashaostrikov commented
@mrnugget just curious: with the latest change (setting back gql params to nullable) it feels like we didn't get rid of all the pointers manoeuvres, but moved them to the graphql layer instead of service layer, right? Or am I missing something?

2022-12-07 04:45 UTC, pjlast commented
@sashaostrikov yeah that's correct, the optional parameters in the GQL query remains nullable and you have to check for pointrers in the GQL layer

2022-12-07 08:42 UTC, merged

2022-12-07 09:23 UTC, mrnugget commented
> @mrnugget just curious: with the latest change (setting back gql params to nullable) it feels like we didn't get rid of all the pointers manoeuvres, but moved them to the graphql layer instead of service layer, right? Or am I missing something?

Correct. Our GraphQL library uses null-pointers for nullability. Below that layer though, we don't use them.