rs/webhook docs
sourcegraph/sourcegraph pull request #45352
Opened 2022-12-07 14:48 UTC by ryanslade

- Update webhook docs
- Add logging and deprecation info

2022-12-07 19:57 UTC, cbart approved these changes

2022-12-07 22:54 UTC, LawnGnome approved these changes

2022-12-07 22:54 UTC, LawnGnome commented on doc/admin/config/webhooks.md
> +* `.api//gitlab-webhooks`
Typo:

```suggestion
* `.api/gitlab-webhooks`
```

2022-12-08 06:42 UTC, mrnugget requested changes
I did a first pass. Main things:

1. Language, naming, formatting needs to be consistent
2. Flow should reflect order in which user needs to learn things
3. Missing: needs to explain what "repository push" is and _WHY_ a user wants to setup webhooks.

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/batch_changes.md
> +Details [here](../../admin/config/webhooks.md#webhook-logging)
```suggestion
Sourcegraph can track incoming webhooks from code hosts to more easily debug issues with webhook delivery. Learn [how to setup webhooks and configure logging](../../admin/config/webhooks.md#webhook-logging).
```

See: https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/actionable_language/#links

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +Webhook receivers can be configured on a Sourcegraph instance in order to receive webhook events from code hosts. This allows Sourcegraph to react more quickly to events that occur outside of the ins
Is "webhook receivers" the official name? In the UI they're called "Incoming webhooks"
<img width="756" alt="screenshot_2022-12-08_07 21 33@2x" src="https://user-images.githubusercontent.com/1185253/206372923-553741c2-04e8-4654-b56c-db6dc62e818f.png">

I think we should be consistent then. I also think maybe this page should be called "Incoming webhooks" instead of just "Webhooks"

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +Bitbucket Cloud | 🟢 | 🔴
Is this table helpful at this point in the doc? Does a reader know what "Repository push" means? (I don't)

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +Webhooks need to be configured both on the sending side, the code host and receiveing side, Sourcegraph.
```suggestion
Webhooks need to be configured both on the sending and the recieving side, the code host and Sourcegraph respectively.
```

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +Webhooks need to be configured both on the sending side, the code host and receiveing side, Sourcegraph.
Shouldn't we link to "get started" here or something? It's a bit weird that this sentence ends with nothing and then next up there's the "Deprecation notice"

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +## Adding a receiver
Again: I think "Creating an incoming webhook" or "Setting up an incoming webhook" might be better. No reader knows what "a receiver" is. Only the first sentence says "webhook receivers".

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +In order to receive webhook events you need to add a receiver. The receiver will be configured to accept events from a specific code host connection based on it's type and URN.
I think the first sentence is redundant.

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +In order to continue using webhooks you need to follow the steps below to [add a receiver](#adding-a-receiver) and then update the webhook configured on your code host with the new webhook url which
```suggestion
In order to continue using webhooks you need to follow the steps below to [add a receiver](#adding-a-receiver) and then update the webhook configured on your code host with the new webhook URL which will look something like `https://sourcegraph-instance/.api/webhooks/{UUID}`
```

Do we even need this sentence? It essentially says "In order to continue using webhooks, setup webhooks", which is what the rest of the document explains. I think it can probably be shortened to "If you want to continue using incoming webhooks, read on to learn how to setup a new incoming webhook."

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +1. Navigate to Site Admin > Incoming webhooks
```suggestion
1. Navigate to **Site Admin > Incoming webhooks**
```

See the batch changes docs you removed above for how to format UI instructions (I couldn't find anything in the handbook)

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +1. Click `Add webhook`
```suggestion
1. Click **Add webhook**
```

2022-12-08 06:42 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +1. You'll be presented with a form to create a new webhook receiver:
The rest of the doc was imperative ("Navigate to", "Click [...]"), so we should be consistent and not switch to passive observations now.

```suggestion
1. Fill out the form:
```

2022-12-08 11:23 UTC, ryanslade commented on doc/admin/config/webhooks.md
> +Webhooks need to be configured both on the sending side, the code host and receiveing side, Sourcegraph.
I reworded this and linked to the setup section for incoming hooks and code hosts.

2022-12-08 11:23 UTC, ryanslade commented
@mrnugget I think I've addresses everything, PTAL

2022-12-09 11:15 UTC, mrnugget approved these changes
Left some comments on formatting that I think should be fixed.

2022-12-09 11:15 UTC, mrnugget commented on doc/admin/config/index.md
> +- [Configuring incoming webhooks](./webhooks.md)
This sould also be on `doc/admin/index.md`

2022-12-09 11:15 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +Webhooks are currently implemented to speed up two types of external events:
```suggestion
Webhooks are currently implemented to speed up two operations:
```

Both items in the list aren't external events

2022-12-09 11:15 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +To receive webhooks both the receiving and sending side need to be configured. To configure the receiving side, [add an incoming webhook](#adding-an-incoming-webhook). Set up the sending side by [con
```suggestion
In order to receive webhooks both the receiving and sending side need to be configured:

1. [Add an incoming webhook](#adding-an-incoming-webhook) to be able to receive webhooks on the Sourcegraph side.
1. Start to receive webhooks by [adding the webhooks to your code host](#configuring-webhooks-on-the-code-host)
```

2022-12-09 11:15 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +       > NOTE: Secrets are not supported for BitBucket cloud
```suggestion
   1. **Secret**: An arbitrary shared secret between Sourcegraph and the code host. A default value is provided, but you are free to change it. _Secrets are not supported for Bitbucket Cloud._
```

The `NOTE` doesn't render. It just shows inline and our parser doesn't like inline blocks in our lists, so instead let's just call it out like this.

2022-12-09 11:15 UTC, mrnugget commented on doc/admin/config/webhooks.md
> +Use the unique URL present on the details page to configure [the webhook on your code host](#configuring-webhooks-on-the-code-host).
```suggestion
1. Click **Create** to create the webhook and be redirect to a page showing more details
1. Use the unique URL present on the details page to configure [the webhook on your code host](#configuring-webhooks-on-the-code-host).
```

2022-12-12 08:21 UTC, mrnugget commented
Rebased and fixed merge conflicts. Let's see what CI says.

2022-12-12 08:37 UTC, merged