fuzzy finder: add docs
sourcegraph/sourcegraph pull request #45404
Opened 2022-12-08 10:40 UTC by taras-yemets

Add fuzzy finder docs.

![image](https://user-images.githubusercontent.com/25318659/206425900-6bc41017-cae0-401c-9fa9-7895dcead381.png)

## Test plan
Tested manually.

2022-12-08 17:38 UTC, felixfbecker reviewed
👏🏻 for adding docs.

2022-12-08 17:38 UTC, felixfbecker commented on doc/code_search/explanations/features.md
> +<img src="https://i.imgur.com/ErZOOMG.png" alt="Fuzzy search">
Could we use our `sourcegraph-assets` GCS bucket instead of imgur?

2022-12-12 09:28 UTC, olafurpg requested changes
+1 to @felixfbecker's comment along with few other changes

2022-12-12 09:28 UTC, olafurpg commented on doc/code_search/explanations/features.md
> +To open the fuzzy finder, press `Cmd/Ctrl+K` anywhere on the Sourcegraph web app.
```suggestion
To open the fuzzy finder, press `Cmd+K` (macOS) or `Ctrl+K` (Linux/Windows) from any page.
```

2022-12-12 09:28 UTC, olafurpg commented on doc/code_search/explanations/features.md
> +Fuzzy finder helps you find any item by its name in the current repository or everywhere. You can search for repositories, symbols, files and files.
```suggestion
Use the fuzzy finder to quickly navigate to a repository, symbol, or file.
```

2022-12-12 09:28 UTC, olafurpg commented on doc/code_search/explanations/features.md
> +
Use the "Searching everywhere" or "Searching in this repo" filter to determine whether to search for results only in the active repository or globally.

SCREENSHOT.

2022-12-12 09:28 UTC, olafurpg commented on doc/code_search/explanations/features.md
> +To open the fuzzy finder, press `Cmd/Ctrl+K` anywhere on the Sourcegraph web app.
Use the dedicated Repos, Symbols, and Files tabs to search only for a repository, symbol, or file. Each tab has a dedicated shortcut:

* Repos: Cmd+I (macOS), Ctrl+K (Linux/Windows)
* Symbols: Cmd+O (macOS), Cmd+Shift+O (macOS Safari), Ctrl+O (Linux/Windows)
* Files: Cmd+P (macOS), Ctrl+P (Linux/Windows)

2022-12-12 12:54 UTC, taras-yemets commented
@felixfbecker, @olafurpg, 
Thank you for your feedback!

Addressed it and added experimental badge with a note linking to the [feedback issue](https://github.com/sourcegraph/sourcegraph/discussions/42874).

<img width="885" alt="Screenshot 2022-12-12 at 14 48 38" src="https://user-images.githubusercontent.com/25318659/207050116-bcfea207-17f3-40f9-8d6b-6b2e04ee46ee.png">

2022-12-14 10:15 UTC, philipp-spiess approved these changes

2022-12-14 12:58 UTC, olafurpg approved these changes

2022-12-14 16:54 UTC, merged