batches: implement URL field for downloading mounted files/executors
sourcegraph/sourcegraph pull request #45558
Opened 2022-12-12 16:08 UTC by adeola-ak

closes #45286

With both mounted files and executors using the `getPathParts` method that accepts two different types of IDs:
unmarrshalled random IDs (sent via the executor)
marshalled random IDs (sent via the UI)

We can use the URL field implemented in #44179 to create URLs for batch spec workspace files and simplify `getPathParts` to only need to accept this url.

## Test plan

2022-12-12 16:16 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | -0.00% (-0.07 kb) | -0.00% (-0.07 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/aa/implement-url/compare-report.html;tab=live_object) for a full comparison between the commits ced5d13 and 0772911 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-12-12 17:38 UTC, BolajiOlajide requested changes
This looks good.

2022-12-12 17:38 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/BatchSpecNode.tsx
> +                to={file.url}
```suggestion
                to={downloadUrl}
```
This should be the `downloadUrl`, I can't remember, but if you use the `file.url` variable directly, are you able to download the file?

The reason I added the `generateFileDownloadLink` function is because that endpoint requires authentication, and just making the request directly with the button wouldn't pass that in.

2022-12-12 17:38 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/backend.ts
> +    const file = await fetch(fileUrl, {
This needs to be prefixed with the `/.api` path or else it won't work.

2022-12-12 17:43 UTC, adeola-ak commented on client/web/src/enterprise/batches/BatchSpecNode.tsx
> +                to={file.url}
@BolajiOlajide I kept this as a draft because I didnt get to test it yet, currently reading the docs to set up a file mount but wanted to request review early since i know this has to go out soon so thanks! I will switch it.

2022-12-12 17:47 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/BatchSpecNode.tsx
> +                to={file.url}
Alright. No problem at all.

2022-12-12 17:47 UTC, adeola-ak commented
@BolajiOlajide thanks for the review, if you take a look at the buildkite, youll see the build is failing but i dont know why.. im guessing i didnt add url to all the fields needed.. is that the case? I thought since I added `url` to `PartialBatchSpecWorkspaceFileFields` `url` wouldnt need to be added everywhere but Im getting errors about it not being added to other types. Just really unsure of all the errors (except the test failures)

2022-12-12 18:10 UTC, BolajiOlajide commented
> @BolajiOlajide thanks for the review, if you take a look at the buildkite, youll see the build is failing but i dont know why.. im guessing i didnt add url to all the fields needed.. is that the case? I thought since I added `url` to `PartialBatchSpecWorkspaceFileFields` `url` wouldnt need to be added everywhere but Im getting errors about it not being added to other types. Just really unsure of all the errors (except the test failures)

<img width="804" alt="CleanShot 2022-12-12 at 18 51 43@2x" src="https://user-images.githubusercontent.com/25608335/207117941-fc84e396-83e3-4647-bebd-38c3ff90ac13.png">
The backend tests are failing most likely because you changed the order of appearance for `BatchSpecRandID` and `fileID` in the `URL` field.

For the client-side tests, I'm going to check on my PC now.

2022-12-13 01:04 UTC, eseliger commented
We've just chatted about this on slack, this still needs to be tested manually so for the sake of release stability, I suggest we don't rush this in and do our proper due diligence. This docs page outlines how to use workspace files in server-side: https://docs.sourcegraph.com/batch_changes/how-tos/server_side_file_mounts

2022-12-20 12:06 UTC, BolajiOlajide approved these changes

2022-12-21 03:22 UTC, merged