scaletesting: codehostcopy: use iterator pattern to pull and push repos concurrently for GHE as source
sourcegraph/sourcegraph pull request #45606
Opened 2022-12-13 09:04 UTC by sanderginn

Reusing the pattern from [codehostcopy](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/tree/dev/scaletesting/codehostcopy) to switch from pulling all repos from the source before pushing to the destination to a paginated pull/push. This is a GitHub Enterprise specific implementation.

The [Organization entity](https://pkg.go.dev/github.com/google/go-github/v48/github#Organization) returned by the API exposes a `TotalPrivateRepos` field which does not return correct results (caps out at 50k). Since we only need this statistic to determine where to resume the process in case of a prematurely terminated run, as well as setting the progress bar cap, it's instead supplied as an optional config value now.

## Test plan
Currently running to copy ~200k repos over to our dogfood GitLab.

2022-12-13 09:41 UTC, burmudar commented on dev/scaletesting/codehostcopy/main.go
> +	Err() error
I think these Iterator specific methods should be on its own interface and we can add a `Iter() Iterator[*store.Repo]` method here instead.

For instance `GithubCodeSource` can then do 
```
func (g *Foo) Iter() Iterator[*store.Repo] {
 return g
}
```

Ideally iterator can be it's own struct but is not critical.

2022-12-13 10:01 UTC, sanderginn commented on dev/scaletesting/codehostcopy/main.go
> +	Err() error
Thanks for the feedback, that makes more sense 👍 

When you are talking about a standalone struct, do you mean a codehost specific struct that implements the Iterator interface? What would be the benefit from that as opposed to `GithubCodeSource` implementing them? Either approach abstracts the implementation details away at the runner level.

2022-12-13 10:33 UTC, jhchabran requested changes
I like the iterator, but unless I misunderstand the PR, I feel we shouldn't expose the pagination details from our codehost API.

2022-12-13 10:33 UTC, jhchabran commented on dev/scaletesting/codehostcopy/github.go
> +func (g *GithubCodeHost) ListRepos(ctx context.Context, start int, size int) ([]*store.Repo, int, error) {
```suggestion
func (g *GithubCodeHost) ListRepos(ctx context.Context, page int, perPage int) ([]*store.Repo, int, error) {
```

2022-12-13 10:33 UTC, jhchabran commented on dev/scaletesting/codehostcopy/github.go
> +func (g *GithubCodeHost) ListRepos(ctx context.Context, start int, size int) ([]*store.Repo, int, error) {
I feel the API would be simpler if we passed a `limit int` to this function instead of exposing the pagination semantics to the caller.

2022-12-13 10:33 UTC, jhchabran commented on dev/scaletesting/codehostcopy/main.go
> +type Iterator[T any] interface {
Nice!

2022-12-13 10:33 UTC, jhchabran commented on dev/scaletesting/codehostcopy/runner.go
> +		os.Exit(1)
Ah good call 🙏

2022-12-13 14:21 UTC, sanderginn commented on dev/scaletesting/codehostcopy/config.go
> +    totalRepos?: number
👍

2022-12-13 14:27 UTC, sanderginn commented on dev/scaletesting/codehostcopy/github.go
> +func (g *GithubCodeHost) ListRepos(ctx context.Context, start int, size int) ([]*store.Repo, int, error) {
I don't know if the semantics are exposed: the runner is the caller, and it just [asks for an iterator and calls `.Next()` until done](https://github.com/sourcegraph/sourcegraph/pull/45606/files#diff-df604648a85a6d927a6d9c69a37b769f7a8e7349ad58cabd1938a3b1fa7670f1R117-R119), so it's unaware of the inner workings of the concrete code host. All pagination is encapsulated in the GitHub definition.

It did make me realise there was an excessive amount of implementation exposed to the runner elsewhere, so that is now [hidden](https://github.com/sourcegraph/sourcegraph/pull/45606/files#diff-df604648a85a6d927a6d9c69a37b769f7a8e7349ad58cabd1938a3b1fa7670f1R101-R104).

2022-12-13 14:28 UTC, sanderginn commented on dev/scaletesting/codehostcopy/main.go
> +type Iterator[T any] interface {
All @burmudar 😄

2022-12-14 09:39 UTC, jhchabran commented on dev/scaletesting/codehostcopy/github.go
> +func (g *GithubCodeHost) ListRepos(ctx context.Context, start int, size int) ([]*store.Repo, int, error) {
Very true, very true. Good call!

2022-12-14 09:42 UTC, jhchabran commented on dev/scaletesting/codehostcopy/github.go
> +func (g *GithubCodeHost) Done() bool {
This function is unused, is that a left over of the previous iterator attepmt?

2022-12-14 09:45 UTC, jhchabran commented on dev/scaletesting/codehostcopy/github.go
> +func (g *GithubCodeHost) Next(ctx context.Context) []*store.Repo {
Same, this is unused, is that normal?

2022-12-14 10:11 UTC, jhchabran approved these changes

2022-12-14 10:13 UTC, merged