repos: set corruptedAt time when gitserver detects a repo is corrupted
sourcegraph/sourcegraph pull request #45667
Opened 2022-12-14 17:30 UTC by burmudar

Sets the corruptedAt time when a repo is detected to be corrupted.

There are two cases where a repo is considered corrupted:
* Sourcegraph considers is corrupted when the head is missing or the repo is not bare - Previously this was only detected during cleanup. I've moved it now that it *also* gets detected on a `exec` call
* Git objects are unreadable like a packfile or some object under `.git/objects/`

The corruptedAt time is cleared when:
* the clone status is set
* the repo is recloned/fetched

Follow up:
- [ ] Emit a metric for when a repo is corrupted
- [ ] Make it visible on the frontend
## Test plan
Unit tests

2022-12-14 18:15 UTC, eseliger commented on migrations/frontend/1670934184_add_repo_corrupted_at/up.sql
> +COMMENT ON COLUMN gitserver_repos.corrupted_at IS 'Timestamp of when repo corruption was dectected';
```suggestion
COMMENT ON COLUMN gitserver_repos.corrupted_at IS 'Timestamp of when repo corruption was detected;
```

2022-12-14 18:15 UTC, eseliger commented on internal/database/gitserver_repos_test.go
> +		}
isn't this asserting on the record, not the field?

2022-12-14 18:15 UTC, eseliger commented on internal/database/gitserver_repos_test.go
> +	t.Run("setting close status clears corruptedAt time", func(t *testing.T) {
```suggestion
	t.Run("setting clone status clears corruptedAt time", func(t *testing.T) {
```

2022-12-14 18:15 UTC, eseliger commented on internal/types/types.go
> +	CorruptedAt *time.Time
I would make this a non-pointer, the `.IsZero()` check is usually good enough for time.Time.

2022-12-14 18:15 UTC, eseliger commented on internal/database/gitserver_repos_test.go
> +	t.Run("setting close status clears corruptedAt time", func(t *testing.T) {
```suggestion
	t.Run("setting clone status clears corruptedAt time", func(t *testing.T) {
```

2022-12-14 18:15 UTC, eseliger commented on internal/database/gitserver_repos.go
> +// SetCorruptedAt sets the corrupted_at timestamp for the repo
this docstring should be on the interface instead, otherwise it's not visible at callsites.

2022-12-14 18:15 UTC, eseliger commented on cmd/gitserver/server/cleanup.go
```suggestion
```

2022-12-14 18:15 UTC, eseliger commented on cmd/gitserver/server/cleanup.go
> +		if !corrupt {
should we also check the error, regardless of corrupt state?

2022-12-14 18:15 UTC, eseliger commented on cmd/gitserver/server/server.go
> +	}
should we only run this query if the repo became corrupt? otherwise we might run this query quite often if ever exec call triggers it

2022-12-14 18:21 UTC, burmudar commented on internal/database/gitserver_repos_test.go
> +		}
yup - thought I fixed it 🤦🏼

2022-12-14 18:23 UTC, burmudar commented on internal/types/types.go
> +	CorruptedAt *time.Time
Ah thanks. I was wondering about this 👏🏼

2022-12-14 18:50 UTC, burmudar commented on cmd/gitserver/server/server.go
> +	}
I might be misunderstanding, but we won't be running the query all the time? Only if the `checkMaybeCorruptRepo` says the repo is corrupt?

2022-12-15 10:01 UTC, burmudar commented on cmd/gitserver/server/server.go
> +	}
One thing I was wondering about is that with the move of the `missing-head` and `non-bare` checks, we will no incur disk access cost everytime the exec point is hit and the `git` output doesn't show corruption 🤔

2022-12-15 14:14 UTC, keegancsmith commented
I'm not sure I understand the WHY here of introducing extra stuff on the request path. Looking at the linked issue this is saying that when we find a corrupt repo we show it in the UI / increment a metric. So setting a boolean won't really help here since we will then reclone the repo via the janitor job and likely not spot the corrupt repo. Seems like we need some sort of event/audit table which has an entry each time a repo is corrupted.

The minimal change for that would be the janitor job (which runs regularly) can report finding a corrupt repo to a DB somewhere which can then be surfaced in the UI. Changing how and when we do corruption checks seems orthogonal to the ask.

2022-12-15 14:26 UTC, burmudar commented
> I'm not sure I understand the WHY here of introducing extra stuff on the request path. Looking at the linked issue this is saying that when we find a corrupt repo we show it in the UI / increment a metric. So setting a boolean won't really help here since we will then reclone the repo via the janitor job and likely not spot the corrupt repo. Seems like we need some sort of event/audit table which has an entry each time a repo is corrupted.
> 
> The minimal change for that would be the janitor job (which runs regularly) can report finding a corrupt repo to a DB somewhere which can then be surfaced in the UI. Changing how and when we do corruption checks seems orthogonal to the ask.

Yeah that makes sense - I added it here since that was where repo corruption was indicated previously, but you're right in the fact that it gets cleanup pretty quickly so you won't see it (which I was wondering about 😆 ). I'll create a new event table and add the details there 👍🏼

2022-12-19 07:13 UTC, mrnugget commented
> The minimal change for that would be the janitor job (which runs regularly)

I agree with that being the place where we set `corrupted_at` (that was my original idea the first time we talked about it, I think, because I vaguely remember that a janitor job already does some corruption checking), but I'm not sure we need a new events table.

What's wrong with setting the `corrupted_at` to a value and then setting it to null once it's repaired? As far as I understand the users only want to know whether a repo is corrupted or not and if it is, they want to hit that reclone button. That should "fix" the repo and unset the corruption state, right?

2022-12-19 07:34 UTC, burmudar commented
> > The minimal change for that would be the janitor job (which runs regularly)
> 
> I agree with that being the place where we set `corrupted_at` (that was my original idea the first time we talked about it, I think, because I vaguely remember that a janitor job already does some corruption checking), but I'm not sure we need a new events table.
> 
> What's wrong with setting the `corrupted_at` to a value and then setting it to null once it's repaired? As far as I understand the users only want to know whether a repo is corrupted or not and if it is, they want to hit that reclone button. That should "fix" the repo and unset the corruption state, right?

They also want to see the log messages captured for the corrupt repo which I think will help them notice a problematic repo that constantly gets corrupted. 

I'm still going to keep the corrupted_at since when it is combined with the events table, it will be the indicator that the repo isn't currently corrupted. Otherwise the events table needs to store when the repo has been "fixed" as an event too which can probably be done by a trigger on the repo table as the Clone Status is changed/Last Fetched is updated, WDYT?

2022-12-19 08:18 UTC, mrnugget commented
> I'm still going to keep the corrupted_at since when it is combined with the events table, it will be the indicator that the repo isn't currently corrupted. Otherwise the events table needs to store when the repo has been "fixed" as an event too which can probably be done by a trigger on the repo table as the Clone Status is changed/Last Fetched is updated, WDYT?

That sounds really complicated. The `gitserver_repos` and `repo` state machine itself is already complicated and adding a separate table that records state over time strikes me as something we need to be really careful about.

Wouldn't a two-column solution solve the same problem? `corrupted_at` and `corruption_log` or something?

2022-12-19 08:42 UTC, burmudar commented
> > I'm still going to keep the corrupted_at since when it is combined with the events table, it will be the indicator that the repo isn't currently corrupted. Otherwise the events table needs to store when the repo has been "fixed" as an event too which can probably be done by a trigger on the repo table as the Clone Status is changed/Last Fetched is updated, WDYT?
> 
> That sounds really complicated. The `gitserver_repos` and `repo` state machine itself is already complicated and adding a separate table that records state over time strikes me as something we need to be really careful about.
> 
> Wouldn't a two-column solution solve the same problem? `corrupted_at` and `corruption_log` or something?

Yeah that should be loads easier 🤔  Thanks! It also solves other stuff I was worried about which I won't mention for brevity!

2022-12-19 09:25 UTC, keegancsmith commented
> What's wrong with setting the `corrupted_at` to a value and then 
> setting it to null once it's repaired?

If I am not mistaken, we will pretty quickly reclone the repo so 
I'm unsure the reclone button is useful since it is likely already 
recloning. Then the other concern is they won't know that a 
certain repo keeps getting corrupted due to the quick nature of 
recloning. (except of course monorepos).

If you read the linked issue, the RFE is really just log output that is
easy to find so admins can dig in (I say that without double checking
the attached message since I am looking at email while on holiday). But
I do think we can do better than that if the complexity minimisation and
engineering capacity can be satisified.

2022-12-19 09:32 UTC, mrnugget commented
> If I am not mistaken, we will pretty quickly reclone the repo so I'm unsure the reclone button is useful since it is likely already recloning.

The RFE says:

> https://github.com/sourcegraph/accounts/issues/6716 [found](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1665579735335619) a corrupt repository weeks after it was initially corrupt. Initially, it looked like the repository was corrupt after an upgrade.

So it doesn't look like the repository is quickly recloned and fixed. 

> the RFE is really just log output that iseasy to find so admins can dig in 

Well, historically logs haven't solved any admin problems 😄 Also this part of the RFE is likely important: "show log events in the UI" -- we already log when a repo is corrupted, which is how they found out about it, but what they want is to be able to see it in the UI.

But we can make sure that what @burmudar is building here is actually solving a problem: we can corrupt a repo and see whether it shows up as corrupted or whether it will be quickly fixed. Then we can record a video and ask Mike whether that solves the problem and then he can show it to customers.

2022-12-19 13:35 UTC, burmudar commented on cmd/gitserver/server/server.go
> +	}
Took me a while but I understand your comment now @eseliger! Will be removing this :D

2022-12-19 13:40 UTC, eseliger commented on cmd/gitserver/server/server.go
> +	}
oh lord, sorry that I've missed this before :( Great!

2022-12-19 13:41 UTC, burmudar commented on cmd/gitserver/server/server.go
> +	}
Haha! No worries!

2022-12-20 13:40 UTC, burmudar commented
@mrnugget @keegancsmith PTAL: I've reworked this to have a `corruption_log` column which kind of works like the events table (TY @jhchabran for the idea) - check the PR description for details.

2022-12-21 10:46 UTC, unknwon reviewed
Drive-by review

2022-12-21 10:46 UTC, unknwon commented on migrations/frontend/squashed.sql
> +    corruption_log jsonb DEFAULT '[]'::jsonb NOT NULL
nit: `corruption_logs` since it is an array? 😁

2022-12-21 10:46 UTC, unknwon commented on internal/database/gitserver_repos.go
> +	logs = append(logs, types.RepoCorruptionLog{Timestamp: time.Now(), Reason: reason})
<img width="483" alt="CleanShot 2022-12-21 at 18 46 00@2x" src="https://user-images.githubusercontent.com/2946214/208887139-fc295181-3a37-4e6f-95bb-3762496f399d.png">

Alternatively, we could use the `||` JSONB operator: https://www.postgresql.org/docs/9.5/functions-json.html

2022-12-21 10:51 UTC, mrnugget commented on migrations/frontend/squashed.sql
> +    corruption_log jsonb DEFAULT '[]'::jsonb NOT NULL
👍 on that, since we also have `execution_logs` for workers, which is `json[]`.

2022-12-21 10:57 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
do I understand this correctly that we're now only logging corruption when we try to remove it? what if we detect corruption before, in an `/exec` call? shouldn't we also log it there (but only if the repo has not previously been marked as corrupt)?

2022-12-21 10:57 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    corrupted_at = DEFAULT,
Is this the only place where we need to set it?

2022-12-21 10:57 UTC, mrnugget commented on internal/database/gitserver_repos_test.go
> +	t.Run("consequative corruption logs appends", func(t *testing.T) {
```suggestion
	t.Run("consecutive corruption logs appends", func(t *testing.T) {
```

2022-12-21 10:57 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
After reading through whole PR: I think we need that in the `/exec` path too. Because `/exec`'s repo "corruption detection" relies on actual git output, `checkRepoDirCorrupt` here only checks whether `HEAD` exists. But I bet a repo can be corrupted even if `HEAD` exists.

2022-12-21 11:04 UTC, burmudar commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
In the next func after this `maybeCorrupt` we log the case where `/exec` marked a repo as corrupt - it's a slight trade off since we don't have the original git output so we just store `git detected repo corruption: could not read object or pack file(s). See log for more details"`

Should I keep this or rather log the original git output?

2022-12-21 11:06 UTC, burmudar commented on internal/database/gitserver_repos.go
> +    corrupted_at = DEFAULT,
We also set it when LastFetched is updated but I'll make sure I got all the places 👍🏼

2022-12-21 12:31 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
Hmm, the original git output would probably be the most useful, I suspect, right?

2022-12-21 12:44 UTC, burmudar commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
it would but we would have to truncate it either way. It would at least stop the admin from having to go jump through logs to look for the stderr output so in that regard I think it's good 👍🏼 

I'll move it 🚚

2022-12-21 14:11 UTC, burmudar commented
Current dependencies on/for this PR:
* main
  * **PR #45667** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/45667" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/45667?utm_source=stack-comment).

2022-12-21 14:14 UTC, burmudar commented on migrations/frontend/squashed.sql
> +    corruption_log jsonb DEFAULT '[]'::jsonb NOT NULL
Updated :+1:

2022-12-21 14:16 UTC, burmudar commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
Moved it:
* The git output will now also be logged
* If the git output is larger that 1mb it gets truncated

just realized I forgot a test case on the server side 😑

2022-12-21 17:17 UTC, burmudar commented on internal/database/gitserver_repos.go
> +	logs = append(logs, types.RepoCorruptionLog{Timestamp: time.Now(), Reason: reason})
My postgres foo isn't good enough but is there way to use this and truncate the resulting JSON array to be at 10 elements?

2022-12-21 17:18 UTC, burmudar commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
Moved!

2022-12-27 14:40 UTC, unknwon commented on internal/database/gitserver_repos.go
> +	logs = append(logs, types.RepoCorruptionLog{Timestamp: time.Now(), Reason: reason})
Doing JSON in SQL is so hard... 😂 

The only successful attempt found on Google that the least magical is 

<img width="670" alt="CleanShot 2022-12-27 at 22 33 39@2x" src="https://user-images.githubusercontent.com/2946214/209681767-72e79090-e20b-4a75-93b2-b74ac20d3cc9.png">

However, it would require us always insert the new entry at the beginning to work. Tested it won't error out if there are less than X items in the array.

<img width="687" alt="CleanShot 2022-12-27 at 22 39 36@2x" src="https://user-images.githubusercontent.com/2946214/209681969-df49164e-d801-4a84-971c-1c3732fc5474.png">

2022-12-28 11:20 UTC, burmudar commented on internal/database/gitserver_repos.go
> +	logs = append(logs, types.RepoCorruptionLog{Timestamp: time.Now(), Reason: reason})
Thanks @unknwon ! Updated it and it is much nicer 👏🏼

2022-12-28 15:23 UTC, burmudar commented
Well Graphite did something weird. Last time I let it rebase :|

2023-01-03 10:56 UTC, mrnugget requested changes
Left a bunch 'o comments. Most important are the intendation ones, of course. Second place goes to: making column nullable, checking errors, and only marking repo as corrupt if it hasn't been marked corrupt before.

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
Should we check whether this returns an error and log it?

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +			s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), "git detected repo corruption: could not read object or pack file(s). See log for more details")
Do we need to check for error here too?

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
What happens when if we already logged the corruption for this repo?

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +			s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), "git detected repo corruption: could not read object or pack file(s). See log for more details")
Same question as above: what if the previous `LogCorruption` call already marked this repo as corrupt?

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/server.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, repo, reason)
Do we need to check error here?

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/server.go
> +		reason := "git repo corruption - " + stderr
Hmmmmmmm, isn't this redundant?

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/server_test.go
> +
```suggestion
```

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/server_test.go
> +		repoName := api.RepoName("example.com/bar/foo")
Pull this var out to make it clear that both sub tests use the same repo

2023-01-03 10:56 UTC, mrnugget commented on cmd/gitserver/server/server_test.go
> +	})
```suggestion
	})

```

So close

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    gr.corruption_logs
```suggestion
	gr.updated_at,
	gr.corrupted_at,
	gr.corruption_logs
```

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    corruption_logs
```suggestion
	updated_at,
	corrupted_at,
	corruption_logs
```

`:set list`

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    gr.corruption_logs
Plz

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    gr.corruption_logs
Where'd the tabs go?

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    corrupted_at = DEFAULT,
Missing tab 😬

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    corrupted_at = DEFAULT
Missing tab 😬

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +WHERE repo_id = (SELECT id FROM repo WHERE name = %s)
Two things:

1. Intendation here is _wild_, man.
2. I asked this twice above, but this seems to be the best place: should we say `WHERE repo_id = (...) AND corrupted_at IS NULL` so we mark repos as corrupt if they are _already_ corrupt?

2023-01-03 10:56 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +    corrupted_at = DEFAULT,
Boy are we glad I'm keeping an eye on our tabs/spaces ratio, right?

2023-01-03 10:56 UTC, mrnugget commented on migrations/frontend/1670934184_add_gitserver_corruption_columns/up.sql
> +    ADD COLUMN IF NOT EXISTS corrupted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '0001-01-01 00:00:00.0',
Hmmmmmm, I'm strongly against this. I think this should be nullable. That allows us to query `select * from gitserver_repos where corrupted_at is null`.

`dbutil.Nulltime` (Example: https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/enterprise/internal/batches/store/batch_changes.go#L399) can be used to scan nullable time columns.

2023-01-03 10:56 UTC, mrnugget commented on migrations/frontend/1670934184_add_gitserver_corruption_columns/up.sql
> +COMMENT ON COLUMN gitserver_repos.corruption_logs IS 'log output of the corruption that was detected on the repo encoded as json';
It's multiple corruptions, right?

2023-01-03 10:56 UTC, mrnugget commented on internal/types/types.go
> +	Timestamp time.Time `json:"ts"`
Since we saved some bytes above by replacing spaces with tabs, we can add some here:

```suggestion
	Timestamp time.Time `json:"time"`
```

2023-01-03 11:08 UTC, burmudar commented on internal/database/gitserver_repos.go
> +WHERE repo_id = (SELECT id FROM repo WHERE name = %s)
1. OMG 😆 that is VERY wild. Something wrong with my vim because I don't see it in there 😱 Lemme fix it

2023-01-03 13:33 UTC, burmudar commented on cmd/gitserver/server/server.go
> +		reason := "git repo corruption - " + stderr
I think it is tbh - Looking at it now we don't really need to make a distinction in the output who detected the corruption.

I'll remove it 👍🏼

2023-01-03 13:35 UTC, burmudar commented on internal/database/gitserver_repos.go
> +WHERE repo_id = (SELECT id FROM repo WHERE name = %s)
On 2: Good call. I didn't think about logging again when a repo is corrupt - seems obvious now in hindsight

2023-01-03 20:45 UTC, burmudar commented on cmd/gitserver/server/cleanup.go
> +		s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), fmt.Sprintf("sourcegraph detected corrupt repo: %s", reason))
It would have logged it again, but now with the `AND` condition, it doesn't anymore 👍🏼

2023-01-03 20:48 UTC, burmudar commented on cmd/gitserver/server/cleanup.go
> +			s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), "git detected repo corruption: could not read object or pack file(s). See log for more details")
I have removed the logging of corruption here, since for the code to have reached this point, _corruption should have been logged **already**_  and logging it again it is pointless. 
 
 Also with the update query, having the log corruption line here would fail due to the repo already being marked as corrupt.

2023-01-03 20:56 UTC, burmudar commented on cmd/gitserver/server/server.go
> +				repo.CorruptedAt = time.Time{}
This is new - during batch syncing of RepoState, when the CloneStatus is set the `corrupted_at` is cleared.

This is different to the `SetCloneStatus` method, since this uses the `Update` method on `GitserverRepo`

2023-01-04 13:25 UTC, mrnugget commented on cmd/gitserver/server/cleanup.go
> +			s.DB.GitserverRepos().LogCorruption(ctx, s.name(dir), "git detected repo corruption: could not read object or pack file(s). See log for more details")
Nice.

2023-01-04 13:29 UTC, mrnugget approved these changes
Good stuff!

2023-01-04 13:29 UTC, mrnugget commented on internal/database/gitserver_repos.go
> +WHERE repo_id = (SELECT id FROM repo WHERE name = %s) AND corrupted_at IS NULL
Heya, it's ya pal, Mr Nit Pick

```suggestion
WHERE
      repo_id = (SELECT id FROM repo WHERE name = %s)
AND
      corrupted_at IS NULL
```

(These need to be tabs, which GitHub won't let me type)

2023-01-04 17:21 UTC, burmudar commented on internal/database/gitserver_repos.go
> +WHERE repo_id = (SELECT id FROM repo WHERE name = %s) AND corrupted_at IS NULL
fixed!

2023-01-05 05:38 UTC, sashaostrikov approved these changes
Nice, thanks for doing that!
Left a couple of non-blocking comments.

2023-01-05 05:38 UTC, sashaostrikov commented on cmd/gitserver/server/cleanup.go
> +	logger = logger.With(log.String("repo", string(repo)), log.String("dir", string(dir)))
nit: seems like the logger is still used at the same place as previously, we can bring it back to the place closer to its usage I guess

2023-01-05 05:38 UTC, sashaostrikov commented on cmd/gitserver/server/server_test.go
> +	defer cancel()
nit: `t.Cleanup()` can be used instead of `defer` funcs in tests

2023-01-05 05:38 UTC, sashaostrikov commented on cmd/gitserver/server/server_test.go
> +		if err != nil {
in this test file we already have `"github.com/stretchr/testify/assert"` imported, so at least in case of errors you can do this:

```go
assert.NoError(t, err)
```

It has a bunch of useful assertions as well, check it out :)

2023-01-09 10:47 UTC, burmudar commented on cmd/gitserver/server/server_test.go
> +		if err != nil {
Awesome! Thanks I've updated to use this intead. So much cleaner 😊

2023-01-09 15:24 UTC, burmudar commented
⏳ This pull request is set to merge as part of a Graphite merge job
Stack job ID: hSUUYP6wzZj7kdyI1hms.
See details on [graphite.dev](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/45667)

2023-01-09 15:24 UTC, merged