Naman/saved searches
sourcegraph/sourcegraph pull request #45705
Opened 2022-12-15 14:22 UTC by thenamankumar

Closes: https://github.com/sourcegraph/sourcegraph/issues/43623

Use the new cursor based pagination system to add pagination to Saved Serches pages.

## Test plan

2022-12-29 12:34 UTC, thenamankumar commented
Blocked on decision from: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1672317171091039

2023-01-02 09:15 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.02% (-0.57 kb) | -0.01% (-1.14 kb) | -0.00% (-0.58 kb) | 0.28% (+2) 🔺 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/naman/saved-searches/compare-report.html;tab=live_object) for a full comparison between the commits 328ef63 and 72f9ebf or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-01-02 14:38 UTC, thenamankumar commented
> Blocked on decision from: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1672317171091039

Resolved!

2023-01-02 17:47 UTC, limitedmage approved these changes
Frontend code looks good, left some comments to be addressed. Please have someone else review the backend Go code 😅

2023-01-02 17:47 UTC, limitedmage commented on schema/settings.schema.json
> -        },
Don't remove this because it will cause validation issues for customers that have this flag set ([this is a known issue](https://github.com/sourcegraph/sourcegraph/discussions/45232)). Instead, keep with and change the description to "REMOVED."

2023-01-02 17:47 UTC, limitedmage commented on client/web/src/search/home/SearchPage.story.tsx
> -export const CloudAuthedHome: Story = () => (
I think we should still keep these two deleted stories as we have different UI for cloud and server for authenticated users.

2023-01-02 21:25 UTC, limitedmage commented on schema/settings.schema.json
> -        },
Though take a look at https://github.com/sourcegraph/sourcegraph/pull/46045 to see if this fixes it.

2023-01-02 21:36 UTC, limitedmage commented on schema/settings.schema.json
> -        },
(It does address it!! So I recommend merging this PR after that one is merged)

2023-01-03 07:24 UTC, thenamankumar commented on schema/settings.schema.json
> -        },
The PR you mentioned is merged now. Thanks for taking care of this in the review.

2023-01-03 10:36 UTC, mrnugget requested changes
Only looked at the Go code for now. Left some comments. I think some of them should be implemented, especially the org-membership test, etc.

2023-01-03 10:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/saved_searches.go
> +}) (*graphqlutil.ConnectionResolver[savedSearchResolver], error) {
You can embed this struct:

```suggestion
func (r *schemaResolver) SavedSearches(ctx context.Context, args struct {
	graphqlutil.ConnectionResolverArgs
	Namespace graphql.ID
}) (*graphqlutil.ConnectionResolver[savedSearchResolver], error) {
```

2023-01-03 10:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/saved_searches.go
>  	if !a.IsAuthenticated() {
Doesn't this check need to be moved up, _before_ you try to query the user?

2023-01-03 10:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	}
I think we can use `auth.CheckOrgAccessOrSiteAdmin` or `auth.CheckSiteAdminOrSameUser` here.

2023-01-03 10:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	return resolver, nil
```suggestion
	return graphqlutil.NewConnectionResolver[savedSearchResolver](connectionStore, connectionArgs, nil)
```

2023-01-03 10:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	}
Do we really need that?

2023-01-03 10:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/saved_searches_test.go
> +	}{
This makes me think you should pull out the inline struct definition from the `SavedSearches` method. Example: https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/cmd/frontend/graphqlbackend/repositories.go#L21

2023-01-03 10:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +}
We didn't have these before? Hmmm

2023-01-03 10:36 UTC, mrnugget commented on internal/database/saved_searches.go
> +	query := sqlf.Sprintf(`SELECT
I'd pull that query out into a constant. Example: https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/internal/database/repo_statistics.go#L76-L85

2023-01-03 10:36 UTC, mrnugget commented on internal/database/saved_searches.go
> +	return savedSearches, nil
I'd pull the scanning out into a `scanSavedSearch` method and then you can use `basestore.NewSliceScanner` too. Example: https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/internal/database/repo_statistics.go#L129-L138

Then you can just scan like this: https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/internal/database/repo_statistics.go#L114-L115

2023-01-03 10:36 UTC, mrnugget commented on internal/database/saved_searches.go
> +	return count, nil
This can be turned into 2-3 lines. Take a look at the `Count` method here: https://docs.sourcegraph.com/dev/background-information/basestore#using-basestore-store

2023-01-03 10:36 UTC, mrnugget commented on internal/database/saved_searches.go
> +	conds := sqlf.Sprintf("WHERE user_id=%v OR org_id=%v", userID, orgID)
Instead of using an `OR` here I think it's better if `conds` is a `[]*sqlf.Query` to which you dynamically append conditions. Example:

https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/internal/workerutil/dbworker/store/store.go#L49-L56

And then you join them together with an `AND`:

https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/internal/database/executors.go#L111-L123

This whole section here can look like this.

2023-01-03 18:56 UTC, limitedmage commented on schema/settings.schema.json
> -        "showEnterpriseHomePanels": {
Can you also remove `homePanelsComputeSuggestions`?

2023-01-04 19:00 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches.go
> +}) (*graphqlutil.ConnectionResolver[savedSearchResolver], error) {
Nice to be reminded about this feature

2023-01-04 19:33 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches.go
>  	if !a.IsAuthenticated() {
removed it

2023-01-04 19:33 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	}
Nice, never used earlier. Refactored.

2023-01-04 19:35 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	return resolver, nil
lol

2023-01-04 19:35 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	}
removed

2023-01-04 19:37 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	nodeID, err := unmarshalSavedSearchID(graphql.ID(cusror))
took me a moment to realize the typo even in the diff. 

Appreciate your dedication to reviews.

2023-01-04 19:39 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches_test.go
> +	}{
done

2023-01-04 19:39 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/schema.graphql
> +}
oh yeah!

2023-01-04 19:43 UTC, thenamankumar commented on internal/database/saved_searches.go
> +	query := sqlf.Sprintf(`SELECT
done

2023-01-04 19:50 UTC, thenamankumar commented on internal/database/saved_searches.go
> +	return savedSearches, nil
sweet!

2023-01-04 19:59 UTC, thenamankumar commented on internal/database/saved_searches.go
> +	conds := sqlf.Sprintf("WHERE user_id=%v OR org_id=%v", userID, orgID)
done

2023-01-04 20:07 UTC, thenamankumar commented on internal/database/saved_searches.go
> +	return count, nil
Exactly 3. sweet

2023-01-04 20:08 UTC, thenamankumar commented on schema/settings.schema.json
> -        "showEnterpriseHomePanels": {
done

2023-01-04 21:03 UTC, thenamankumar commented on client/web/src/search/home/SearchPage.story.tsx
> -export const CloudAuthedHome: Story = () => (
added back

2023-01-05 12:35 UTC, mrnugget approved these changes
Sweet! Left two comments. One is important: we need to check for both IDs being 0 in the GraphQL layer.

2023-01-05 12:35 UTC, mrnugget commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	}
What if both are `0`? I think we should return an error in that case.

2023-01-05 12:35 UTC, mrnugget commented on internal/database/saved_searches.go
> +	where := []*sqlf.Query{sqlf.Sprintf("(user_id=%v OR org_id=%v)", userID, orgID)}
```suggestion
	var where []*sqlf.Query
if userID != 0 {
	where = append(where,  sqlf.Sprintf("user_id = %v", userID))
}
if orgID != 0 {
	where = append(where,  sqlf.Sprintf("org_id = %v", orgID))
}

```

2023-01-05 13:15 UTC, vdavid approved these changes
The VS Code-related changes LGTM!

2023-01-05 15:41 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/saved_searches.go
> +	}
fixed

2023-01-05 15:41 UTC, merged

2023-01-09 10:44 UTC, indradhanush commented on cmd/frontend/graphqlbackend/schema.graphql
> +}
Why not use `BidirectionalPageInfo` instead of defining this?