symbols: fix possible nil pointer dereference when GraphQL query
sourcegraph/sourcegraph pull request #45768
Opened 2022-12-16 14:10 UTC by sashaostrikov

contains no "query" clause in `symbols` resolver.

This is not guaranteed anywhere up the code stack (`query` is not a mandatory GraphQL parameter), that's why I added this check. I came across it during local testing with a query like:
```
query CommitSymbols($repoName: String!, $revision: String!) {
	repository(name: $repoName) {
		commit(rev: $revision) {
            symbols {
				nodes {
					name
				}
			}
		}
	}
}
```

Test plan:
Existing CI, because adding a unit test for `searchZoekt` looks non-trivial and the change is tiny.

2022-12-16 14:27 UTC, ryanslade approved these changes
LGTM, maybe add a test that causes the old code to panic?

2022-12-16 14:31 UTC, sashaostrikov commented
> LGTM, maybe add a test that causes the old code to panic?

I actually did it, but as soon as NPE is fixed, it becomes really hard to stub everything so that `searchZoekt` doesn't fail.

Do you think it is worth adding a test which just checks that an error is not the nil panic?
@ryanslade

2022-12-16 15:22 UTC, ryanslade commented
> > LGTM, maybe add a test that causes the old code to panic?
> 
> I actually did it, but as soon as NPE is fixed, it becomes really hard to stub everything so that `searchZoekt` doesn't fail.
> 
> Do you think it is worth adding a test which just checks that an error is not the nil panic? @ryanslade

What I've done in some tests is that once I'm passed the code I want to check I return a "short circuit" error and check for that:

https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@d21ad9ab836a7b3458bcc0ed59cc7128bf380f82/-/blob/cmd/frontend/graphqlbackend/user_emails_test.go?L147:29

2022-12-16 15:23 UTC, sashaostrikov commented
> > > LGTM, maybe add a test that causes the old code to panic?
> > 
> > 
> > I actually did it, but as soon as NPE is fixed, it becomes really hard to stub everything so that `searchZoekt` doesn't fail.
> > Do you think it is worth adding a test which just checks that an error is not the nil panic? @ryanslade
> 
> What I've done in some tests is that once I'm passed the code I want to check I return a "short circuit" error and check for that:
> 
> https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@d21ad9ab836a7b3458bcc0ed59cc7128bf380f82/-/blob/cmd/frontend/graphqlbackend/user_emails_test.go?L147:29

I think I'll try to do the same thing, I just need to find a thing that can be mocked there 👍🏻

2022-12-19 07:35 UTC, mrnugget requested changes

2022-12-19 07:35 UTC, mrnugget commented on internal/search/symbol/symbol.go
> +	if queryString == nil || *queryString == "" {
So previously we used the `*queryString` value, now we don't anymore. I think what you want is

```go
var raw string
if queryString != nil {
   raw = *queryString
}
if raw == "" {
   raw = ".*"
}
```

2022-12-19 07:46 UTC, sashaostrikov commented on internal/search/symbol/symbol.go
> +	if queryString == nil || *queryString == "" {
whoa, that would've been really bad to get merged...
Thanks for catching that!

2022-12-19 09:34 UTC, mrnugget approved these changes
I feel like the test/mock setup is a bit overkill for a nil check, but fine with me.

2022-12-19 09:40 UTC, sashaostrikov commented
> I feel like the test/mock setup is a bit overkill for a nil check, but fine with me.

Probably one day I will come up with a unit test for this function (which would have caught my bug, btw), so the mock is more used :)

2022-12-19 09:41 UTC, merged