Expire credential when changing code host URL
sourcegraph/sourcegraph pull request #45778
Opened 2022-12-16 17:21 UTC by evict

This commit prevents leaking of credentials by expiring credentials when changing a code host URL. Previously it was possible to change the URL of a code host, and send it to a server that would log the credential. This way credentials could be leaked.

More information be found
[here](https://github.com/sourcegraph/security-issues/issues/324).

## Test plan

- [ ] CI tests
- [ ] manual review

2022-12-16 18:46 UTC, camdencheek approved these changes
Non-blocking nits inline, but the changes look good to me! I'm not super familiar with this code though, so it might be best to get a second set of eyes from someone on repo management

2022-12-16 18:46 UTC, camdencheek commented on internal/types/secret.go
> +var urlChErr error = errors.New("Code host URL changed, please re-enter token.")
nit: `urlCh` reads to me as "urlChannel" since it's common to name channels like that in go. Could we unabbreviate that to `urlChanged`? I'm not sure we need the succinctness here 🙂

2022-12-16 18:46 UTC, camdencheek commented on internal/types/secret.go
> +	return newURL.String(), urlCh, nil
nit: small simplification

```suggestion
	urlChanged := newURL.Host != oldURL.Host
	return newURL.String(), urlChanged, nil
```

2022-12-19 07:55 UTC, mrnugget requested changes

2022-12-19 07:55 UTC, mrnugget commented on internal/types/secret.go
> +var urlChErr error = errors.New("Code host URL changed, please re-enter token.")
The error message doesn't fit for all code hosts. Some code hosts don't have a URL (`p4port`).

I think it's better to make this dynamic. Example:

```go
type codeHostIdentityChangedErr struct {
     identityProperty string
     redactedProperty string
}

func (e codeHostIdentityChangedErr) Error() string {
  return fmt.Sprintf("Property %q has been changed, please re-enter %q", e.identityProperty, e.redactedProperty)
}
```

Our site-admin UX is horrible already, let's not make it worse by adding error messages that don't make sense for some use cases.

2022-12-19 07:55 UTC, mrnugget commented on internal/types/secret.go
> +func unredactedString(new, old string) (string, bool) {
Can you add a docstring to explain when this function returns `true`/`false`?

2022-12-19 07:55 UTC, mrnugget commented on internal/types/secret.go
> +	return false
Can you add a docstring here? I find this method highly confusing

2022-12-19 09:34 UTC, unknwon commented on internal/types/secret.go
> +var urlChErr error = errors.New("Code host URL changed, please re-enter token.")
Actually, to add on top of this, `ErrCodeHostIdentityChanged` is the idiomatic naming for errors 😁

2022-12-19 09:34 UTC, unknwon commented on internal/types/secret.go
> +	return false
Based on my prior knowledge, the old version of this method does "if the value is `REDACTED`, replace it with the real value from an in-memory copy of the config, otherwise take the user input."

However, I do find it makes the method harder to explain with new changes, top off my head I think it is more clear to have a separate helper like `func shouldUnredact(...) bool`.

2022-12-19 09:51 UTC, mrnugget commented on internal/types/secret.go
> +	return false
Agree. A separate `shouldUnredact` would make the higher-level code also more readable.

2022-12-20 18:13 UTC, evict commented on internal/types/secret.go
> +
@eseliger I reverted `unredactURL` because URL checks had to be done in a different way. For this specific case we compare to URLs without credentials, and see if they changed. Then we check if the password is `REDACTED`.

2022-12-20 19:04 UTC, evict commented on internal/types/secret.go
> +			}
@eseliger we know test the URL here. We changed the map to accept a credential-less URL, so we can easily see if the URL has changed. If the old URL has changed, but not the password (it's still `REDACTED`) we return the error. The previous method did not work, as the `redactedOldURL` was the index, which would never match `new[i]` (the new URL).

2022-12-21 12:48 UTC, mrnugget reviewed
Left a comment, because I still think the whole `unredact` and boolean return value is confusing. I think I have an idea for how to make it more readable, see comment.

2022-12-21 12:48 UTC, mrnugget commented on internal/types/secret.go
> +		}
I think I just realized why I'm confused by these changes: `es.unredactString` does two things here but it reads like it only does one.

The code right now reads as:

```
if unredacting "token" was possible {
  and if the url changed {
     return error
  }
}
```

But what it should actually say to the reader is


```
if unredacted version of "token" did not change (!!) {
...
}
```

Is it not possible to make that more visible? For example:

```go
// Unredact "token"
es.unredactString(c.Token, o.Token, "token")
// If token is still same but URL changed, we need to return error
if c.Token == o.Token && c.Url != o.Url {
  return errCodeHostIdentityChanged{"url", "token"}
}
```

2022-12-21 12:48 UTC, mrnugget commented on internal/types/secret.go
> +					if r != o.Maven.Repositories[i] {
What if the order changed? Don't you need to sort before comparing?

2022-12-21 12:56 UTC, evict commented on internal/types/secret.go
> +		}
We only want to know if the value was unredacted. That means that the URL changed but the user submitted the `REDACTED` value from site-admin. The token will remain the same if the user submitted a redacted value. I did a docstring to `unredactString` explaining that it returns `true` after it unredacted a string.

An alternative would be this:

```go
// If token is `REDACTED` but URL changed, we need to return error
if c.Token == RedactedSecret && c.Url != o.Url {
  return errCodeHostIdentityChanged{"url", "token"}
}
// Unredact "token"
es.unredactString(c.Token, o.Token, "token")
```

But we'd need to add that to every case.

2023-01-03 10:15 UTC, mrnugget approved these changes

2023-01-03 10:15 UTC, mrnugget commented on internal/types/secret.go
> +
```suggestion
```

2023-01-03 10:15 UTC, mrnugget commented on internal/types/secret.go
> +				return errCodeHostIdentityChanged{"url", "password"}
Does that error message make sense? You changed the URL with a password in it, so now you need to change the password in it?

2023-01-03 10:15 UTC, mrnugget commented on internal/types/secret.go
> +
```suggestion
```

2023-01-03 10:15 UTC, mrnugget commented on internal/types/secret.go
> +
```suggestion
```

2023-01-03 10:15 UTC, mrnugget commented on internal/types/secret.go
> +
```suggestion
```

2023-01-03 10:15 UTC, mrnugget commented on internal/types/secret_test.go
> +				if tc.wantErr.Error() != err.Error() {
I'd move that up to line 494 where you already check for `err != nil`, so you can do something like:

```go
if err != nil {
  if tc.wantErr == nil {
    t.Fatal(err)
  } else {
    if tc.wantErr.Error() != err.Error() {
      t.Fatalf("received error, but not equals to expected one. want=%s, have=%s", tc.wantErr, err)
    }
  }
}

2023-01-04 10:25 UTC, evict commented on internal/types/secret.go
> +				return errCodeHostIdentityChanged{"url", "password"}
It would only trigger on a URL like: `https://foo:REDACTED@pkg.go.internal`. I think it makes sense as the user just made a change there.

2023-01-05 13:21 UTC, merged