CODEOWNERS protocol buffer
sourcegraph/sourcegraph pull request #45785
Opened 2022-12-16 20:43 UTC by cbart

This change:

- Adds a codeowners.proto file which structurally represents a CODEOWNERS file in a way that should work with GitHub, GitLab and Bitbucket Cloud.
- Adds generated Go bindings along with a bash script to regenerate them on proto file change.
- Some aspects of the configuration, like optional sections are omitted, as they are not relevant to discerning code ownership.

## Test plan

Manually used code-gen to generate Go proto bindings.

2022-12-19 14:47 UTC, eseliger approved these changes

2022-12-19 14:47 UTC, eseliger commented on internal/own/codeowners/README.md
> +./internal/own/codeowners/proto-generate.sh
should we add this to `sg generate`? Then regressions will be caught in CI

2022-12-19 14:47 UTC, eseliger commented on internal/own/codeowners/proto/codeowners.proto
> +// As various orgainzations have slightly different syntax for CODEOWNERS files,
```suggestion
// As various implementations have slightly different syntax for CODEOWNERS files,
```

2022-12-19 14:47 UTC, eseliger commented on internal/own/codeowners/proto/codeowners.proto
> +    //   `docs/*.md` will match `/src/docs/index.md` but not `/src/docs/index.js`.
should we add a section about negation rules as bitbucket uses them?

2022-12-19 17:21 UTC, eseliger commented on internal/own/codeowners/proto/codeowners.proto
> +    // In the text config, a handle always starts with `@`.
```suggestion
    // Handle can refer to a user or a team defined externally.
    // In the text config, a handle always starts with `@`.
```

2022-12-19 22:22 UTC, cbart commented on internal/own/codeowners/proto/codeowners.proto
> +    //   `docs/*.md` will match `/src/docs/index.md` but not `/src/docs/index.js`.
👍

2022-12-19 22:22 UTC, cbart commented on internal/own/codeowners/README.md
> +./internal/own/codeowners/proto-generate.sh
👍

2022-12-19 22:23 UTC, cbart commented
Adding @efritz who, I believe worked on `sg` quite a lot. Eric, could you advice if the changes to `sg generate` I made here to generate golang bindings for protobuf make sense? 🙃

2022-12-20 10:58 UTC, mrnugget approved these changes

2022-12-20 12:50 UTC, jhchabran requested changes
> Adding @efritz who, I believe worked on sg quite a lot. Eric, could you advice if the changes to sg generate I made here to generate golang bindings for protobuf make sense? 🙃

Took the liberty of doing it as I've played with this a lot, brought forward a few small things :)

2022-12-20 12:50 UTC, jhchabran commented on dev/sg/generates.go
> +		// go mod tidy errors on generated protobuf go code direstories.
```suggestion
		// go mod tidy errors on generated protobuf go code directories.
```

2022-12-20 12:50 UTC, jhchabran commented on dev/sg/internal/generate/proto/proto.go
> +	"google.golang.org/protobuf/cmd/protoc-gen-go",
Don't we want to pin a version for those? Without we could break the CI on an update of one of the binaries, if they were to include breaking changes (with the exception of `goimports`).

2022-12-20 12:50 UTC, jhchabran commented on dev/sg/internal/generate/proto/proto.go
> +	if err := golang.RunGoImports(ctx, golang.NormalOutput, reportOut, &sb); err != nil {
Just wondering, why do we need to run this? I checkout the branch and it runs fine without it + `sg generate go` doesn't complain either.

2022-12-20 12:50 UTC, jhchabran commented on internal/own/codeowners/proto/codeowners.pb.go
> +// As various orgainzations have slightly different syntax for CODEOWNERS files,
@cbart This has not been regenerated, this will fail the CI somewhere down the line 😊

2022-12-20 17:27 UTC, cbart reviewed
Thanks!

2022-12-20 17:27 UTC, cbart commented on dev/sg/internal/generate/proto/proto.go
> +	"google.golang.org/protobuf/cmd/protoc-gen-go",
Good spot!

2022-12-20 17:27 UTC, cbart commented on dev/sg/internal/generate/proto/proto.go
> +	if err := golang.RunGoImports(ctx, golang.NormalOutput, reportOut, &sb); err != nil {
🤷 good call, I was wondering too if it's necessary, but saw it in so many places using `buf` online, that I did it. Let's drop it from here (makes the diff smaller), and add it later if there is actually a reason to do so.

2022-12-20 17:27 UTC, cbart commented on internal/own/codeowners/proto/codeowners.pb.go
> +// As various orgainzations have slightly different syntax for CODEOWNERS files,
That's right! Fixed now. Thanks!

2022-12-20 17:30 UTC, jhchabran approved these changes

2022-12-20 19:45 UTC, merged