cloud: hide o11y for non-operator users
sourcegraph/sourcegraph pull request #45827
Opened 2022-12-19 20:39 UTC by michaellzc

## Test plan

2022-12-19 20:39 UTC, michaellzc commented
Current dependencies on/for this PR:
* main
  * **PR #45827** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/45827" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/45827?utm_source=stack-comment).

2022-12-19 20:47 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.11 kb) | 0.00% (+0.67 kb) | 0.00% (+0.56 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/12-19-cloud_hide_o11y_for_non-operator_users/compare-report.html;tab=live_object) for a full comparison between the commits 7c7d9ae and 40eedca or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-12-19 22:16 UTC, bobheadxi commented on client/web/src/featureFlags/featureFlags.ts
> +    | 'hide-observability-only-visible-to-sourcegraph-operator'
```suggestion
    | 'sourcegraph-operator-only-observability'
```

Then all our operator-related FFs can have the same prefix

2022-12-19 22:21 UTC, michaellzc commented on client/web/src/site-admin/SiteAdminArea.tsx
> -        return [analyticsGroup, ...props.sideBarGroups.filter(group => !isEqual(group, overviewGroup))]
I belive the label name of group is expected to be unique, or user will use duplicated group name on the UI which is confusing.

so we can remove the deep equal here, checking the label name should be enough.

2022-12-20 06:10 UTC, unknwon approved these changes
This is really stretching my TS knowledge, but LGTM 😂

2022-12-20 07:38 UTC, bobheadxi commented on client/web/src/featureFlags/featureFlags.ts
> +    | 'sourcegraph-operator-only-observability'
Looking a bit closer, should we extend this flag to cover all things we want to hide under the `Maintainence` category? Other pages we can hide:

- Updates (customers have no control over this)
- Migrations (customers also have no control over this)

Then the flag might be:

```suggestion
    | 'sourcegraph-operator-site-admin-hide-maintainence'
```

2023-01-13 22:50 UTC, bobheadxi approved these changes

2023-01-16 09:56 UTC, mrnugget requested changes

2023-01-16 09:56 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminArea.tsx
> +            props.sideBarGroups.reduce((groups, group) => {
I'm wondering whether this code wouldn't be simpler by using `map`. It's really complex for what it's trying to achieve. You're mapping over a list of groups and if it's `(curr.header?.label === maintenanceGroupHeaderLabel)` then you modify it, depending on the 3 other conditions. I think that's a `map`.

You also don't need the `curr = group` and the scary comment here. And you can get rid of the last 5 lines in this anonymous function.

2023-01-16 09:56 UTC, mrnugget commented on client/web/src/site-admin/SiteAdminArea.tsx
> +                            if (curr.header?.label === maintenanceGroupHeaderLabel) {
You only ever do something (in both top-level branches) if this condition is true. Can't you make this the top-level condition and skip anything the rest of the code?

2023-04-04 08:55 UTC, unknwon commented
@mrnugget - thanks for the review! Updated with a much-simplified version of the code logic.

2023-04-05 09:03 UTC, merged