Set Cloud Trial prefill form data by URL param vs. cookies
sourcegraph/sourcegraph pull request #45864
Opened 2022-12-20 22:33 UTC by st0nebraker

## Test plan

2022-12-20 22:43 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.22 kb) | 0.00% (+0.19 kb) | -0.00% (-0.03 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/cloud-signup-prefill-url-param/compare-report.html;tab=live_object) for a full comparison between the commits dbe1149 and 26fe8c2 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-12-21 08:08 UTC, erzhtor requested changes
Thanks for following-up and iterating on solutions. I left a few comments. Let me know if you have any questions.

2022-12-21 08:08 UTC, erzhtor commented on client/shared/src/util/url.ts
> +        if (authenticatedUser.email) {
Can we use optional chaining `?.`, instead of nested ifs?

2022-12-21 08:08 UTC, erzhtor commented on client/shared/src/util/url.ts
> +            const name = authenticatedUser.displayName.replace(' ', '_')
Why do we need this white space replacement? I belive URLSearchParams will automatically escape all non-URL symbols

2022-12-21 08:08 UTC, erzhtor commented on client/shared/src/util/url.ts
> +export function buildGetStartedURL(cloudSignup?: boolean, authenticatedUser?: AuthenticatedUser | null): string {
Would be nice to add jsDocs description and examples

2022-12-21 08:08 UTC, erzhtor commented on client/shared/src/util/url.ts
> +export const buildCloudTrialURL = (
Would be nice to add jsDocs description and examples

2022-12-21 18:00 UTC, st0nebraker commented on client/shared/src/util/url.ts
> +        if (authenticatedUser.email) {
Sure thing

2022-12-21 18:01 UTC, st0nebraker commented on client/shared/src/util/url.ts
> +            const name = authenticatedUser.displayName.replace(' ', '_')
Good call! Removed ✅

2022-12-22 10:31 UTC, erzhtor approved these changes

2023-01-02 17:18 UTC, merged