token selection: highlight hovered token
sourcegraph/sourcegraph pull request #45951
Opened 2022-12-23 09:58 UTC by taras-yemets

Highlights hovered interactive tokens.

## Test plan
Tested manually (video attached).

2022-12-23 10:05 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.28 kb) | 0.00% (+0.28 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/taras-yemets/token-selection-highlight-hovered-token/compare-report.html;tab=live_object) for a full comparison between the commits 6d19700 and 2e0ddc5 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-12-23 14:59 UTC, olafurpg reviewed
I updated the CSS class to use the mark color. However, I'm still not loving this UX because 1) the color occasionally conflicts with document highlight in unpredictable ways, 2) I find it distracting to update the background color immediately as I'm moving the mouse, 3) neither IntelliJ or VS Code use this pattern.

I took a stab at highlighting only the occurrence while the tooltip is mounted, similar to what VS Code does for the hover tooltip. I got it working for mounting, but was not able to get it to unmount correctly. Neither the unmount react hooks or the CodeMirror `destroy` functions are getting called when I expect them to https://github.com/sourcegraph/sourcegraph/pull/new/olafurpg/highlight-codeintel-tooltip-occurrence

I wonder if we can solve this problem by updating the design of the popover to show some kind of pointer towards the occurrence. I noticed that the new design of the loading tooltip no longer points at the occurrence, which I think is a minor UX regression compared to the vanilla tooltips from CodeMirror. This approach has the benefit of working uniformly for mouse-driven and keyboard-driven navigation, as well as being compatible with pinned popovers.

2022-12-23 15:24 UTC, vovakulikov commented
>I wonder if we can solve this problem by updating the design of the popover to show some kind of pointer towards the occurrence

@olafurpg are you talking about having a tail UI for the code intel tooltip in the blob view? (something like in [this demo ](https://storybook.sgdev.org/?path=/story/wildcard-popover--with-tail)


>we need to refactor the hover tooltip logic from using the CodeMirror's built-in [hoverTooltip](https://codemirror.net/docs/ref/#view.hoverTooltip) ([current implementation](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6d19700/-/blob/client/web/src/repo/blob/codemirror/token-selection/hover.ts?L32)) method to custom relatively complex event handlers tracking the hover position and showing code-intel popovers for these positions if the conditions are me 

@taras-yemets I'm 100% for it, it may seem like a complex issue to do to solve the highlights token state problem, but I see other benefits from this refactoring like we already have tooltip position logic in the wildcard, and it would be a good improvement to have it in the blob UI as well. Also, since Popover in the wildcard is a simple react component with a controlled state, we should be possible to control its appearance and hook up to appearance triggers (to perform effects such as highlighting the target symbol) 

I don't have enough experience with CodeMirror UI to know that this would solve all our problems here, so please doubt the above!

2022-12-23 15:43 UTC, olafurpg commented
> method to custom relatively complex event handlers tracking the hover position and showing code-intel popovers for these positions if the conditions are me

I just remembered that @fkling already implemented this logic with `hoverManager` https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3a852aec3a2d9e3886ceedb85ad332340390061f/-/blob/client/web/src/repo/blob/codemirror/hovercard.tsx?L388

I used `hoverTooltip` for selection-driven navigation because it was the easiest option but the correct solution is to replace `hoverTooltip` with `hoverManager`, which would get us the desired behavior of highlighting the hovered token only while the tooltip is visible.

2022-12-23 15:46 UTC, olafurpg commented
> since Popover in the wildcard is a simple react component with a controlled state, we should be possible to control its appearance and hook up to appearance triggers (to perform effects such as highlighting the target symbol)


@vovakulikov the CodeMirror has a lot of nice APIs to accomplish what we need. We should try to use CodeMirror idiomatically wherever possible instead of trying to move logic into React (where I personally find it sometimes more difficult to achieve custom functionality compared to the CodeMirror APIs). The CodeMirror APIs have a learning curve (facets, fields, extensions, state, decorations, ...) but once you get the hang of it and follow the conventions then a lot of impressive features start becoming easy to implement.

2022-12-23 16:18 UTC, vovakulikov commented
@olafurpg I'm not saying that we need to move away from the codemirror API completely. I see a lot of good parts of event-driven API that code mirror has. But also, I've seen that we rely on custom logic in Monaco and codemirror tooltip position for the tooltip UI. And this bothers me a lot because it isn't so straightforward if we need to change there something (for example, add tail UI to the popover), or for example, this problem that we got with tooltip positions very recently [here](https://github.com/sourcegraph/sourcegraph/pull/45959) 

So bottom line from me here is Codemirror API is cool for the state management but UI parts from Codemirror might be non optimal for some parts of our UI (such as code intel tooltip)

2022-12-23 16:46 UTC, fkling commented
I’m sorry that I haven’t paid closer attention to how the token selection shows hovercards.  Couldn’t it just use the `showHovercard` facet? https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3a852aec3a2d9e3886ceedb85ad332340390061f/-/blob/client/web/src/repo/blob/codemirror/hovercard.tsx?L170 

The facet controls showing the tooltip/card as well as highlighting the corresponding token range.

The nice thing about CodeMirror’s API is that you’ you can easily decouple UI logic from data providers.

2023-01-03 11:30 UTC, taras-yemets commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +)
Modified version of the [non-selection-driven `hoverManager`](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3a852aec3a2d9e3886ceedb85ad332340390061f/-/blob/client/web/src/repo/blob/codemirror/hovercard.tsx?L383-541).

2023-01-03 12:11 UTC, taras-yemets commented on client/web/src/repo/blob/codemirror/token-selection/extension.ts
> -                        warmupOccurrence(view, hoveredOccurrence)
Mouse move events are now handled in the [hover manager](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@96e4d1ad55b74c0b4ccc1b7db18af23bee5b670d/-/blob/client/web/src/repo/blob/codemirror/token-selection/hover.ts?L276). 

@olafurpg, as we use a [smaller timeout](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@96e4d1ad55b74c0b4ccc1b7db18af23bee5b670d/-/blob/client/web/src/repo/blob/codemirror/token-selection/hover.ts?L279) before fetching the code-intel data now (25ms compared to the [initial 200ms](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@35ecf2f7ca68d54bb17376c92cece67375d7acfa/-/blob/client/web/src/repo/blob/codemirror/token-selection/hover.ts?L31:77&popover=pinned)), do we still need to warm up the occurrence on hover?

2023-01-03 12:50 UTC, taras-yemets commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +                                        catchError(() => of(null)),
Needed to catch errors mentioned in
- https://github.com/sourcegraph/sourcegraph/issues/46071
(a [similar approach](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@96e4d1ad55b74c0b4ccc1b7db18af23bee5b670d/-/blob/client/web/src/repo/blob/codemirror/token-selection/keybindings.ts?L32) is used in the selection-driven nav 'Space' handler).

2023-01-04 14:02 UTC, olafurpg commented
The new behavior feels great! I tested it quickly locally and noticed that the token is not highlighted when using the pinned popover https://sourcegraph.test:3443/github.com/scalameta/metals/-/blob/tests/unit/src/test/scala/tests/IdentifierComparatorSuite.scala?L16:3&popover=pinned#tab=references

<img width="562" alt="CleanShot 2023-01-04 at 15 01 41@2x" src="https://user-images.githubusercontent.com/1408093/210571638-a4573f92-565d-4aa7-9528-f43bdf609084.png">


Will review the code in more detail later

2023-01-04 15:35 UTC, olafurpg requested changes
Two blocking comments: `scan` and pinned popovers. Otherwise, this looks great!

2023-01-04 15:35 UTC, olafurpg commented on client/web/src/repo/blob/codemirror/token-selection/extension.ts
> -                        warmupOccurrence(view, hoveredOccurrence)
I leave it to you to decide if we need a warmup or not. Waiting 25ms seems fine

2023-01-04 15:35 UTC, olafurpg commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +                                        catchError(() => of(null)),
We should update the API to return `null | undefined`

2023-01-04 15:35 UTC, olafurpg commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +
The original `hoverManager` has a `scan` step to mirror the behavior of the hover tooltip in VS Code wrt. to the direction movement of the mouse. Was there a specific reason you left this out of the re-implementation?

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@taras-yemets/token-selection-highlight-hovered-token/-/blob/client/web/src/repo/blob/codemirror/hovercard.tsx?L439

2023-01-04 15:59 UTC, taras-yemets commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +
> Was there a specific reason you left this out of the re-implementation?

It seemed to work fine without taking the cursor movement direction into consideration.
But I didn't it on long tokens, for example 🤔 When the hovered token is wider than the code-intel tooltip, hovering over the end of the token, seeing the code-intel popup, and then trying to hover over it may be impossible (the tooltip will hide after the cursor leaves the token).
Will double-check. Thanks for flagging it!

2023-01-06 11:56 UTC, taras-yemets commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +
Addressed in https://github.com/sourcegraph/sourcegraph/pull/45951/commits/fef6f59a1e73fc8ce0322ba5017d1a3c33f47228

2023-01-06 12:02 UTC, taras-yemets commented on client/shared/src/codeintel/api.ts
> +    getHover(textParameters: TextDocumentPositionParameters): Observable<HoverMerged | null | undefined>
As suggested in https://github.com/sourcegraph/sourcegraph/pull/45951#discussion_r1061606780 add `undefined` to `getHover` return type (see [`ProviderResult` type definition](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@01c578d69914fa4980a8c7e39363e7d928991d27/-/blob/client/shared/src/codeintel/legacy-extensions/api.ts?L442:1-452:37)).

2023-01-06 12:16 UTC, taras-yemets commented
Thank you for your review, @olafurpg!
Since your last review:
- added `scan` to the hover manager to respect the mouse cursor movement direction (https://github.com/sourcegraph/sourcegraph/pull/45951/commits/fef6f59a1e73fc8ce0322ba5017d1a3c33f47228)
- highlight token with pinned popover

https://user-images.githubusercontent.com/25318659/211010169-1d198fe7-417c-439d-8d2b-c1dfb9b0a27b.mov

2023-01-10 13:11 UTC, philipp-spiess approved these changes
This looks great :)

2023-01-10 16:57 UTC, olafurpg commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +                        }),
The duplication shouldn't be a problem because the code paths are never used at the same time. If we stick with selection-driven navigation then we should be able remove the duplicate code in hovercard.tsx

2023-01-10 17:04 UTC, philipp-spiess commented on client/web/src/repo/blob/codemirror/token-selection/hover.ts
> +                        }),
OH gotcha I haven't realized those are mutually exclusive.

2023-01-10 17:07 UTC, merged