web: Add Test connection button and API call to code host
sourcegraph/sourcegraph pull request #45972
Opened 2022-12-26 14:19 UTC by indradhanush

Step 1 of many.

Need to tie down the response to the button to show changes.

## Test plan

2022-12-26 14:26 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.38 kb) | 0.03% (+3.87 kb) | 0.03% (+3.50 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/ig/test-connection-button/compare-report.html;tab=live_object) for a full comparison between the commits 35e2008 and 821918c or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2022-12-29 10:26 UTC, indradhanush commented on client/web/src/site-admin/fixtures.ts
> +        hasConnectionCheck: true,
This change brought to you by `yarn build-ts` errors.

2022-12-29 10:26 UTC, indradhanush commented on client/web/src/components/externalServices/backend.ts
> +        hasConnectionCheck
This change brought to you by `yarn build-ts` errors.

2022-12-29 10:26 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServicesPage.story.tsx
> +                displayName: 'GitHub #1',
Small fix: Fixed a warning for both the displayName being same in the storybook.

2022-12-29 10:39 UTC, thenamankumar requested changes

2022-12-29 10:39 UTC, thenamankumar commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                )}
Do this rather(same for other places):

```
const checkConnectionNode = checkConnectionData?.node
const isCodeHostReachable = node?.__typename === 'ExternalService' &&
                            node?.checkConnection?.__typename === 'ExternalServiceAvailable' && 
                            node?.checkConnection?.lastCheckedAt;
 
 {isCodeHostReachable && (
    <span className="text-success">
        <Icon aria-hidden={true} svgPath={mdiCheckCircle} /> Code host is reachable.
    </span>
 )}
```

2022-12-29 11:20 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                )}
Fixed.

2022-12-29 12:21 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +    const [checkConnectionError, setCheckConnectionError] = useState<boolean | Error>(false)
I guess the type of state can be simplified to just `Error` and initially set to `undefined`.
(Or you might need `Error | undefined`, I'm not 100% sure 😁)

2022-12-29 12:21 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                            node?.hasConnectionCheck ? 'Test code host connection' : 'Connection check unavailable'
`node` is not nullable, you can remove `?`

2022-12-29 12:21 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                            disabled={!node?.hasConnectionCheck || checkConnectionLoading}
You can remove `?`

2022-12-29 12:21 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                {isErrorLike(checkConnectionError) && (
I think this can be simplified to `!checkConnectionError`. Because currently it is either `false` or `Error` which is `isErrorLike`

2022-12-29 12:21 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                {checkConnectionLoading && (
IMO it's worth moving loading part right below `<br>` tag, so that all other cases (when `loading` is false) read better one by one. WDYT?

2022-12-29 12:21 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                {isErrorLike(checkConnectionError) && (
probably, `loading` check should be added here as well

2022-12-29 12:21 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                    )}
Some thoughts about this section:
- These 2 cases can be merged in one, which checks all the common things (loading, called, errorLike, etc.), so that we don't duplicate this boolean monster
- When they are merged into one, then you can use ternary to distinguish between them (i.e. `isExternalServiceAvailable ? *available path* : *unavailable path*`)
- I think that there are too many mutually exclusive checks happening. Do we need to check all of them? `Loading` and `called`, for example. I think one of these is fine.

this way you can make this chunk of code a lot cleaner, because currently it reads really hard :)

2022-12-29 13:06 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                    )}
Fixed by moving the math outside the component rendering. Wasn't able to use a ternary operator here because `null` also evaluates to `false`, so on page load the false path was always getting executed.

2022-12-29 13:07 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                {isErrorLike(checkConnectionError) && (
> I think this can be simplified to !checkConnectionError. Because currently it is either false or Error which is isErrorLike

I think the `isErrorLike` is a stronger check here in case there's ever a bug and `checkConnectionError` is `true`, then we will end up displaying an error message with `true` in it. I checked in other places and it looks like `isErrorLike` is used in such cases. I'd vote to keep it as is. 

+1 on moving the `loading` check to be the first. Fixed that.

2022-12-29 13:08 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +    const [checkConnectionError, setCheckConnectionError] = useState<boolean | Error>(false)
Hmm. Probably. But we're doing something similar already for `isDeleting` a little above this code. Maybe we keep them the same to have a recognizable pattern in this part of the code? What do you think?

2022-12-29 13:25 UTC, sashaostrikov commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                {isErrorLike(checkConnectionError) && (
don't believe this can happen, we need to trust our code :)
but still it's your call

2022-12-29 13:26 UTC, sashaostrikov approved these changes
LGTM!
But let's wait for @thenamankumar as well.

2022-12-29 13:46 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                                {isErrorLike(checkConnectionError) && (
> don't believe this can happen, we need to trust our code :)

Yeah I trust the code now. But I'm thinking that the current check is stronger for any potential future bugs if anyone / me end up setting `true` as a value by mistake only because its technically allowed by the `type` here. Just defensive programming I guess. 😛

Since it's not too complicated in its current form and also is used quite widely in our code, keeping it is not the worst idea. 😀

2022-12-29 17:26 UTC, thenamankumar commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +    const [checkConnectionError, setCheckConnectionError] = useState<boolean | Error>(false)
`useLazyQuery` should return error on its own and you don't need to save error state separately. 

You can do `const [doCheckConnection, { loading, data, error }] = useExternalServiceCheckConnectionByIdLazyQuery(node.id)`

`defaultExternalServices` is legacy and not using the react hooks; that is why the error is handled separately there. 


Read: https://www.apollographql.com/docs/react/api/react/hooks/#error

2022-12-29 17:27 UTC, thenamankumar commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +    const onTestConnection = useCallback<React.MouseEventHandler>(async () => {
use error from `useLazyQuery`

2022-12-29 17:28 UTC, thenamankumar requested changes
https://github.com/sourcegraph/sourcegraph/pull/45972/files#r1059071884

2022-12-30 03:30 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +    const onTestConnection = useCallback<React.MouseEventHandler>(async () => {
Fixed in the latest commit [98e18be](https://github.com/sourcegraph/sourcegraph/pull/45972/commits/98e18be25b6c484a9ef22f85417b3315a4fcf3f7)

2022-12-30 06:53 UTC, thenamankumar requested changes

2022-12-30 06:53 UTC, thenamankumar commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +    const onTestConnection = useCallback<React.MouseEventHandler>(async () => {
You can directly use `doCheckConnection`. No need to wrap with `useCallback`.

2022-12-30 07:37 UTC, thenamankumar approved these changes

2022-12-30 10:52 UTC, merged

2023-01-02 10:17 UTC, mrnugget commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                        content={node.hasConnectionCheck ? 'Test code host connection' : 'Connection check unavailable'}
I'd change `Test code host connection` to `Test whether code host is reachable from Sourcegraph`

2023-01-02 10:22 UTC, mrnugget commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                            disabled={!node.hasConnectionCheck || loading}
(man, GitHub lost my comment, so here it is again)

I think we should just hide the button if `!node.hasConnectionCheck`. A disabled button suggests there's a way to enable it. In this case though, we don't support the connection check and a Sourcegraph update is required to get it enabled once we add support, meaning: nothing the user can do.

2023-01-02 10:22 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                            disabled={!node.hasConnectionCheck || loading}
> (man, GitHub lost my comment, so here it is again)

Have been seeing some reliability issues with GitHub myself this week.

2023-01-02 10:58 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                            disabled={!node.hasConnectionCheck || loading}
I get how a user might thinkg that the disabled button suggests that there's a way to enabled it. But with the suggested change, it looks inconsistent to me when one entry doesn't have that button. 

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/2682729/210222250-79d40215-c20f-45c7-8047-55f6fc963348.png">

If it looks all right to you, I can create the PR.

2023-01-02 11:15 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                        content={node.hasConnectionCheck ? 'Test code host connection' : 'Connection check unavailable'}
Created a PR: https://github.com/sourcegraph/sourcegraph/pull/46029

2023-01-02 11:15 UTC, indradhanush commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                        content={node.hasConnectionCheck ? 'Test code host connection' : 'Connection check unavailable'}
Tweaked the suggested message slightly to make it a little shorter.

2023-01-02 13:20 UTC, mrnugget commented on client/web/src/components/externalServices/ExternalServiceNode.tsx
> +                            disabled={!node.hasConnectionCheck || loading}
I think that's alright. (Ideally and further down the road we create a "details" page for code hosts where we can put this)