graphqlbackend: add `excludeRepoFromExternalService` query.
sourcegraph/sourcegraph pull request #45986
Opened 2022-12-28 10:51 UTC by sashaostrikov

Test plan:
Unit tests added.

2022-12-28 12:11 UTC, indradhanush requested changes

2022-12-28 12:11 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_services_test.go
> +		expectedConfig := `{"exclude":[{"id":"1","name":"sourcegraph/sourcegraph"},{"id":"2","name":"sourcegraph/horsegraph"}],"repositoryQuery":["none"],"token":"abc","url":"https://github.com"}`
Looks like the config updated from a preceeding test is expected as starting state for this test. Overall it's not such a great idea to have them tied together as now this test cannot be run independently and will fail:

```
➜ go-test-run TestExcludeRepoFromExternalService/ExcludeRepoFromExternalService._Empty_exclude._Repo_exclusion_added.#01
=== RUN   TestExcludeRepoFromExternalService
=== RUN   TestExcludeRepoFromExternalService/ExcludeRepoFromExternalService._Empty_exclude._Repo_exclusion_added.#01
DEBUG NewClient gitserver/client.go:78 logger.scoped {"scope": {"name": "NewClient", "desc": "returns a new gitserver.Client"}}
DEBUG gitserver.client gitserver/observability.go:56 logger.scoped {"scope": {"name": "gitserver.client", "desc": "gitserver client"}}
DEBUG schemaResolver graphqlbackend/graphqlbackend.go:576 logger.scoped {"scope": {"name": "schemaResolver", "desc": "GraphQL schema resolver"}}
DEBUG GraphQL graphqlbackend/graphqlbackend.go:532 logger.scoped {"scope": {"name": "GraphQL", "desc": "general GraphQL logging"}}
    external_services_test.go:342:
        	Error Trace:	/Users/dhanush/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend/external_services_test.go:342
        	Error:      	Not equal:
        	            	expected: "{\"exclude\":[{\"id\":\"1\",\"name\":\"sourcegraph/sourcegraph\"},{\"id\":\"2\",\"name\":\"sourcegraph/horsegraph\"}],\"repositoryQuery\":[\"none\"],\"token\":\"abc\",\"url\":\"https://github.com\"}"
        	            	actual  : "{\"exclude\":[{\"id\":\"2\",\"name\":\"sourcegraph/horsegraph\"}],\"repositoryQuery\":[\"none\"],\"token\":\"abc\",\"url\":\"https://github.com\"}"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-{"exclude":[{"id":"1","name":"sourcegraph/sourcegraph"},{"id":"2","name":"sourcegraph/horsegraph"}],"repositoryQuery":["none"],"token":"abc","url":"https://github.com"}
        	            	+{"exclude":[{"id":"2","name":"sourcegraph/horsegraph"}],"repositoryQuery":["none"],"token":"abc","url":"https://github.com"}
        	Test:       	TestExcludeRepoFromExternalService/ExcludeRepoFromExternalService._Empty_exclude._Repo_exclusion_added.#01
--- FAIL: TestExcludeRepoFromExternalService (0.03s)
    --- FAIL: TestExcludeRepoFromExternalService/ExcludeRepoFromExternalService._Empty_exclude._Repo_exclusion_added.#01 (0.03s)
FAIL
exit status 1
FAIL	github.com/sourcegraph/sourcegraph/cmd/frontend/graphqlbackend	1.166s
```

Let's keep each test state separate and set the state at the start of each test.

2022-12-28 12:11 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_services_test.go
> +			name:           "duplicate exclusion not added for AWSCodeCommit schema",
The name is slightly misleading and tripped me up a bit when I was looking at the values of `initialConfig` and `expectedConfig` as I was expecting a duplicate config in the `initialConfig`.

Looking at the asserts below cleared the confusion but maybe we can find a better name for these. Something like: "repo excluded first time, but ignored a second time for ..." or similar.

2022-12-28 12:23 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_service.go
> +	return r.externalService.SupportsRepoExclusion()
this is the property of an external service, which describes it, I decided to put it there, IMHO it belongs there better that in an API layer.

I think it can also be used in a database/service layer in future. Locking it to the place of current only usage seemed wrong to me.

2022-12-28 12:28 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services.go
> +	}
I think it is okay in this case.
This should not happen from the UI because the button which would trigger related GQL request will be disabled if an external service doesn't support excluding a repo.

2022-12-28 12:29 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +	t.Run("ExcludeRepoFromExternalService. Empty exclude. Repo exclusion added.", func(t *testing.T) {
forgot to delete the label and update the name, thanks!

2022-12-28 12:30 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +	t.Run("ExcludeRepoFromExternalService. Empty exclude. Repo exclusion added.", func(t *testing.T) {
this is just the error in test name. it checks that we don't add duplicate repos to exclude

2022-12-28 12:30 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +	t.Run("ExcludeRepoFromExternalService. Empty exclude. Repo exclusion added.", func(t *testing.T) {
yep, will rephrase

2022-12-28 12:35 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +		expectedConfig := `{"exclude":[{"id":"1","name":"sourcegraph/sourcegraph"},{"id":"2","name":"sourcegraph/horsegraph"}],"repositoryQuery":["none"],"token":"abc","url":"https://github.com"}`
We have many such tests in our code base which are run as one because they are located in one main test function and depend on a state after previous test cases.

Separating these tests will cause a lot of code duplication to reach the desired state.

You should consider it as a single test and run it either as in CI (whole test suite) or just as a normal test `TestExcludeRepoFromExternalService`.

The only reason I've added `t.Run` is to have test cases names in console. Adding labels to `RunTest` does nothing (as opposed to adding labels to `RunTests`).

2022-12-28 12:36 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +			name:           "duplicate exclusion not added for AWSCodeCommit schema",
I'll figure out a better name :)

2022-12-28 12:45 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_service.go
> +	return r.externalService.SupportsRepoExclusion()
> I think it can also be used in a database/service layer in future. Locking it to the place of current only usage seemed wrong to me.

Hmm, maybe we should come back to it if we feel the need for it in the future instead of trying to optimize for a maybe scenario of the future. My two cents.

While it's true that it's a property of external service, my thinking is that since only the API layer cares about it, the extra indirection adds little value. 

My motivation is to keep our types thin and our APIs fat. 😉

This is not blocking so I will leave the final choice on you with my recommendation being to leave it on the API layer and avoid the extra indirection for someone reading the code.👍🏽

2022-12-28 12:46 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_services.go
> +	}
Yes, true. Overall from an API design point of view silently hiding errors is a bad idea IMO. Clients should not need to know about implementation detail and trust that the API will tell them if they are doing something that is not allowed / supported.

2022-12-28 12:48 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_services_test.go
> +		expectedConfig := `{"exclude":[{"id":"1","name":"sourcegraph/sourcegraph"},{"id":"2","name":"sourcegraph/horsegraph"}],"repositoryQuery":["none"],"token":"abc","url":"https://github.com"}`
> Separating these tests will cause a lot of code duplication to reach the desired state.

Hmm. Maybe use a helper function to setup the initial state and reuse as and where you need?

Overall I found it hard to understand the individual tests when I was reading the code as I had to keep going back and forth to keep the state in my mind.

2022-12-28 12:49 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_service.go
> +	return r.externalService.SupportsRepoExclusion()
gotcha, I'll think more about that before merging, thanks for the feedback!

2022-12-28 12:51 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +		expectedConfig := `{"exclude":[{"id":"1","name":"sourcegraph/sourcegraph"},{"id":"2","name":"sourcegraph/horsegraph"}],"repositoryQuery":["none"],"token":"abc","url":"https://github.com"}`
I will try to split them and if it won't become messy, I would go for split tests :)

2022-12-28 13:22 UTC, indradhanush approved these changes
Left a couple of small comments. Approved to unblock.

2022-12-28 13:22 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_services.go
> +		r.logger.Warn("Failed to trigger external service sync after adding a repo exclusion.")
Let's add the external service ID and the repo ID here since the logger is not scoped with these fields.

2022-12-28 13:22 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_services.go
> +		return "", err
Isn't `err` going to be `nil` here? 🤔
We should return a custom error maybe?

2022-12-28 13:24 UTC, indradhanush commented on cmd/frontend/graphqlbackend/external_services.go
> +		r.logger.Warn("Tried to exclude repo from external service which config doesn't support repo exclusion.")
```suggestion
		r.logger.Warn("Tried to exclude repo from external service but config doesn't support repo exclusion.")
```

2022-12-28 13:34 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services.go
> +		return "", err
in fact we shouldn't return an error here, there should be no default, we just need to return the same config

2022-12-28 18:22 UTC, merged

2023-01-02 13:06 UTC, mrnugget commented on cmd/frontend/graphqlbackend/external_services.go
> +// Function is pretty beefy, what it does is:
I think it could/should then go into the `backend` layer: https://github.com/sourcegraph/sourcegraph/blob/main/cmd/frontend/backend/external_services.go

That's the "service" layer where we should keep domain logic (such as: check permissions, load this, then that, if this is that, then do this) and the GraphQL specific stuff (unmarshaling args, ...) in here.

2023-01-02 13:07 UTC, mrnugget commented on cmd/frontend/graphqlbackend/external_services.go
> +	err = externalServices.Update(ctx, conf.Get().AuthProviders, extSvcID, &database.ExternalServiceUpdate{Config: &updatedConfig})
Do we need to put these 3 database cals (`GetbyID`, `Repos().Get`, `Update`) into a transaction?

2023-01-02 13:16 UTC, mrnugget commented on cmd/frontend/graphqlbackend/external_services.go
> +func addRepoToExclude(ctx context.Context, externalService *types.ExternalService, repository *types.Repo) (string, error) {
I think this shouldn't be in the GraphQL layer. Either it goes into `backend` (see comment above) or into the `extsvc` package where we already have a lot of methods for parsing configs: https://github.com/sourcegraph/sourcegraph/blob/72f9ebf997ad6865e7f335314ee4b5f5b47f57f1/internal/extsvc/types.go#L506

2023-01-02 13:16 UTC, mrnugget commented on cmd/frontend/graphqlbackend/external_services_test.go
> +func TestExcludeRepoFromExternalService_ExternalServiceDoesntSupportRepoExclusion(t *testing.T) {
Nitpick/braindump: I think this and the other 3 tests like it could probably be turned into a single test with a table?

2023-01-02 13:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/external_services_test.go
> +		cachedUpdate = update
(GitHub lost my comment again!!)

FWIW I don't think you need to save the arg here. Since you're using mocks you can access the `History()` of the `UpdateFunc` and check the args for a specific call. See examples here: https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+History%28%29%5B+lang:go+file:_test.go&patternType=standard&sm=0&groupBy=repo

2023-01-03 06:12 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services.go
> +// Function is pretty beefy, what it does is:
oh, that's nice, I thought about doing such a thing just didn't find this file!

2023-01-03 06:16 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services.go
> +	err = externalServices.Update(ctx, conf.Get().AuthProviders, extSvcID, &database.ExternalServiceUpdate{Config: &updatedConfig})
great idea, will do this as well!

2023-01-03 06:18 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services.go
> +	err = externalServices.Update(ctx, conf.Get().AuthProviders, extSvcID, &database.ExternalServiceUpdate{Config: &updatedConfig})
@mrnugget just 1 thing here: should we include sync external service in transaction as well?

I mean, how crucial is that we update the config successfully, but fail to trigger a sync? Should we fail the whole operation?

2023-01-03 06:20 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +func TestExcludeRepoFromExternalService_ExternalServiceDoesntSupportRepoExclusion(t *testing.T) {
They used to be so, but then after a discussion with @indradhanush [here](https://github.com/sourcegraph/sourcegraph/pull/45986#discussion_r1058301715) I separated them

2023-01-03 06:21 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services_test.go
> +		cachedUpdate = update
oh yeah, I forgot about this thing, thanks!

2023-01-03 07:26 UTC, sashaostrikov commented
@mrnugget follow-up PR here!
https://github.com/sourcegraph/sourcegraph/pull/46064

2023-01-03 09:11 UTC, mrnugget commented on cmd/frontend/graphqlbackend/external_services.go
> +	err = externalServices.Update(ctx, conf.Get().AuthProviders, extSvcID, &database.ExternalServiceUpdate{Config: &updatedConfig})
Hmmm, I think in this case it might be fine to do the sync outside the transaction, although it would be best if the user knows that once they hit exclude, the service will be synced and the repo removed soon.

2023-01-03 09:13 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/external_services.go
> +	err = externalServices.Update(ctx, conf.Get().AuthProviders, extSvcID, &database.ExternalServiceUpdate{Config: &updatedConfig})
let's keep it in transaction for now for smoother UX: redirect and a spinner (TBD) for the already running sync.

transaction added (along with other fixes) in this PR https://github.com/sourcegraph/sourcegraph/pull/46064