[Org Members] Add pagination
sourcegraph/sourcegraph pull request #46067
Opened 2023-01-03 10:34 UTC by thenamankumar

closes: https://github.com/sourcegraph/sourcegraph/issues/43622

This PR adds pagination to org members API and frontend.

## Test plan

2023-01-03 10:42 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.10 kb) | 0.00% (+0.10 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/naman/org-members-pagination/compare-report.html;tab=live_object) for a full comparison between the commits 9d2c809 and 35ecf2f or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-01-03 10:44 UTC, thenamankumar commented
Blocked on https://sourcegraph.slack.com/archives/C0C324C91/p1672742506657099

2023-01-10 16:52 UTC, kopancek requested changes

2023-01-10 16:52 UTC, kopancek commented on client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
> +import * as React from 'react'
Since this is basically a reimplementation of the old page, I think it makes sense to reuse the layout from the deleted page as it still looks nicer to me and it was done by a designer and hence has better UX IMO.

E.g.
Move the `Members` claim into a header
Move the add member/invite member buttons to the right and let them open a modal instead of showing the text box. We have an autocomplete there for the username, which is less error prone than typing in the username...
Move the role column to the right
Hide the membership toggle in a submenu

2023-01-10 16:52 UTC, kopancek commented on client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
> +                <PageSwitcher {...paginationProps} className="mt-4" totalCount={connection?.totalCount || 0} />
Should we hide the pagination if there is only 1 page of results? Right now we gray it out, but I don't think it makes too much sense...

2023-01-11 06:40 UTC, thenamankumar commented on client/web/src/components/FilteredConnection/hooks/usePageSwitcherPagination.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
Its not my TODO and I don't have full context of this. Will talk to Philipp, about how this can be resolved separately.

2023-01-11 06:44 UTC, thenamankumar commented on client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
> +import * as React from 'react'
Any further improvements to this page can be tracked in a separate issue. This PR covers the pagination issue, the scope for which is already extended. 

The new page was not used by anyone and was only available under a feature flag. Given that, this PR will only improve things, and we can make the further improvements you suggested incrementally.

2023-01-11 06:46 UTC, thenamankumar commented on client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
> +                <PageSwitcher {...paginationProps} className="mt-4" totalCount={connection?.totalCount || 0} />
@philipp-spiess, what do you think about this? If we decide to hide it, we can do it inside the PageSwitcher component itself to reflect this behaviour at all the places this component is used.

2023-01-11 10:02 UTC, philipp-spiess reviewed
Frontend changes LGTM. I’m not sure if we should do the big deletion of the members view in the same PR though (maybe split it up so we can revert it easier if we ever had to?). I'll wait for stamping until we have some backend review as well, though :)

2023-01-11 10:02 UTC, philipp-spiess commented on client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
> +                <PageSwitcher {...paginationProps} className="mt-4" totalCount={connection?.totalCount || 0} />
Good question! I think that would make sense, yeah, since otherwise it would also show the pagination controls when there's only e.g. 1 item which would look odd

2023-01-11 10:36 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> -}
ID is still expected and called. I am just resolving the go typing here. Having a method on the interface will not work for the cases where the ID method is defined on the pointer type and not the struct itself.

2023-01-11 10:52 UTC, philipp-spiess commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> -}
But how do we enforce that an `ID()` type is set then, especially when we need to call it?

2023-01-11 10:58 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> -}
ID() is not called inside the connection_resolver itself ever. And having the interface type to restrict it is not working. So we need to make it an expectation at the graphql level and code reviews. :) 

But yeah, technically people might bypass having an ID. Let me know if you have a better solution.

2023-01-11 12:07 UTC, mrnugget approved these changes
Approving the backend part, but require the changes to be made.

2023-01-11 12:07 UTC, mrnugget commented on cmd/frontend/graphqlbackend/org.go
> +	Before *string
Please embed that `graphql.ConnectionResolverArgs` here and pull out the struct into a definition (like it was before) instead of inline.

2023-01-11 12:07 UTC, mrnugget commented on cmd/frontend/graphqlbackend/org.go
> +}
```suggestion
	return graphqlutil.NewConnectionResolver[UserResolver](connectionStore, connectionArgs, nil)
}
```

2023-01-11 12:07 UTC, mrnugget commented on internal/database/users.go
> +	conds = append(conds, sqlf.Sprintf("deleted_at IS NULL"))
```suggestion
	conds = []*sqlf.Query{sqlf.Sprintf("deleted_at IS NULL")}
```

2023-01-11 12:07 UTC, mrnugget commented on internal/database/users.go
> +	q := sqlf.Sprintf("WHERE u.deleted_at IS NULL AND %s", sqlf.Join(where, "AND"))
Nit: I'd pull the `u.deleted_at` up to line 873 where the default conditions are set in `where`, so they're next to each other.

2023-01-11 12:26 UTC, philipp-spiess approved these changes
Stamping for the front-end part. The comments from before still apply, though 😅

2023-01-16 19:31 UTC, thenamankumar commented on internal/database/users.go
> +	q := sqlf.Sprintf("WHERE u.deleted_at IS NULL AND %s", sqlf.Join(where, "AND"))
updated

2023-01-16 19:31 UTC, thenamankumar commented on internal/database/users.go
> +	conds = append(conds, sqlf.Sprintf("deleted_at IS NULL"))
updated

2023-01-16 19:31 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/org.go
> +}
updated

2023-01-16 19:31 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/org.go
> +	Before *string
updated

2023-01-16 19:32 UTC, thenamankumar commented on client/web/src/components/FilteredConnection/hooks/usePageSwitcherPagination.ts
> +    const queryVariables = {
done

2023-01-16 19:32 UTC, thenamankumar commented on client/web/src/org/settings/members/OrgSettingsMembersPage.tsx
> +                <PageSwitcher {...paginationProps} className="mt-4" totalCount={connection?.totalCount || 0} />
updated and resolved.

2023-01-16 19:35 UTC, thenamankumar commented
@mrnugget, all backend comments are resolved. 

@philipp-spiess, most of the frontend comments are resolved. Further feature improvement suggestions are skipped as part of this PR.

2023-01-17 11:25 UTC, kopancek approved these changes

2023-01-17 11:25 UTC, merged