Insights: handle repo revs when filtering by search context
sourcegraph/sourcegraph pull request #46089
Opened 2023-01-03 19:53 UTC by jtibshirani

Code insights allows filtering the repositories on-the-fly using a search
context. To support this, the insights code loads the search context query,
extracts its repo filter, and compiles the filter regex.

The search context repo filters can contain revisions too. The logic doesn't
account for this and just compiles the whole repo@revision string. This filter
will never match any repos. If the revision is not a valid regex, then it can
also fail to compile and cause a cryptic error.

Now we parse the repo filter and return an error when any revisions are
present. This lets the user know their context won't work as intended.

## Test plan

Added cases to `insight_view_resolvers_test.go`, light manual testing

2023-01-03 20:06 UTC, jtibshirani commented
Another small issue that popped up while tackling #45632. 

Here's an example when using a search context with a revision that's an invalid regex, like `repo:sourcegraph/sourcegraph rev:HEAD?*`. Without this change, insights shows a confusing error:

![Screenshot 2023-01-03 at 9 48 59 AM](https://user-images.githubusercontent.com/7461306/210432939-49ed36af-88c7-412b-aa9f-042febf09b4b.png)

2023-01-03 21:30 UTC, tbliu98 approved these changes
LGTM! 

cc @sourcegraph/code-insights

2023-01-04 11:23 UTC, leonore approved these changes
thank you @jtibshirani! for the other issue you referenced in this PR it looks like we're just propagating an error returned by search contexts, but if that's not the case, if you open an issue we'll take a look 😃 (or maybe it's fixed by this PR, I wasn't sure?)

2023-01-04 11:23 UTC, leonore commented on enterprise/internal/insights/resolvers/insight_series_resolver.go
> +				repo, _ := search.ParseRepositoryRevisions(repoFilter)
could you add a comment to say what that we're ignoring revision specifiers here (and maybe why we don't need them?) at first I thought this might be ignoring an error

2023-01-04 15:54 UTC, chwarwick requested changes

2023-01-04 15:54 UTC, chwarwick commented on enterprise/internal/insights/resolvers/insight_series_resolver.go
> +			for _, repoFilter := range inc {
I actually think the correct behavior here would be to error with with a more appropriate message that tells the user that revisions are not supported within insights. I don't want to give the user the impression that they are looking at an insight over a specific revision and I can see how applying a context that they use to specifically do that would cause confusion.   

Returning an error aligns with the create/edit experience that notifies the user that `rev:` is not supported.  Ignoring the repo would align with how we deal with other non-supported filters in the context, but in this case I think it would cause the user to think it just didn't work and result in a poor experience.

2023-01-04 16:19 UTC, jtibshirani commented on enterprise/internal/insights/resolvers/insight_series_resolver.go
> +				repo, _ := search.ParseRepositoryRevisions(repoFilter)
👍 will add a comment here explaining the behavior

2023-01-04 16:39 UTC, jtibshirani commented on enterprise/internal/insights/resolvers/insight_series_resolver.go
> +			for _, repoFilter := range inc {
I can definitely see your point! In the UI these are presented as "changing the scope of this insight", not just filtering the output, so maybe a user could think this would actually switch revisions.

And I guess there's not a big concern over breaking existing views -- these likely didn't work anyway since we were interpreting the whole `repo@revision` string as a repo.

2023-01-04 17:29 UTC, jtibshirani commented
@chwarwick I pushed a change to return an error instead of just ignoring the revision. Now when the search context query includes a revision, it renders with an error:

![Screenshot 2023-01-04 at 9 16 38 AM](https://user-images.githubusercontent.com/7461306/210614019-a54b18b7-395c-48dc-bf4c-26fc55e23a08.png)

It's not the most beautiful thing :) Let me know if you have suggestions for how to handle it better.

@leonore my comment above was a bit confusing. Issue #45632 is a big refactor issue, and I happened to find this bug while working on that. As for the error screenshot I linked, this PR will resolve that too (since we never try to regex compile the revisions).

2023-01-04 17:52 UTC, chwarwick commented
> It's not the most beautiful thing :) Let me know if you have suggestions for how to handle it better.

You're right it's not and we have some work on the insights api side we can do to clean up some of that, but it's a big improvement because now the user knows why it didn't work and how to resolve it.  

Only thing I see is that I assume this could also be an issue with the excluded repos from a context something like `-repo:sourcegraph rev:myrev` otherwise looks good to me.

2023-01-04 17:53 UTC, chwarwick approved these changes
pending change on the excluded repos side if you determine it is neccesary.

2023-01-04 18:03 UTC, jtibshirani commented
Thanks for the reviews! Exclude repo filters actually don't support revisions. The `rev` part is interpreted as a requirement for the include filters. And it doesn't work to specify it directly like `-repo:sourcegraph/sourcegraph@HEAD`.

2023-01-04 18:07 UTC, merged