createUser: mark emails as unverified on creation
sourcegraph/sourcegraph pull request #46187
Opened 2023-01-06 01:10 UTC by bobheadxi

## Test plan

2023-01-06 01:11 UTC, bobheadxi commented
Current dependencies on/for this PR:
* main
  * **PR #46183** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/46183" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #46184** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/46184" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #46187** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/46187" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/46187?utm_source=stack-comment).

2023-01-06 01:14 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/users_create.go
we _could_ send the verification email here:

```go
	if verificationCode != "" && conf.CanSendEmail() {
		if err := backend.SendUserEmailVerificationEmail(ctx, user.Username, email, verificationCode); err != nil {
			return nil, errors.Wrap(err, "failed to send verification email")
		}
	}
```

2023-01-06 01:18 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (+0.04 kb) | 0.00% (+0.63 kb) | 0.01% (+0.59 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/01-05-email_do_not_send_emails_to_unverified_emails_split/compare-report.html;tab=live_object) for a full comparison between the commits 5b40d8f and 7a6dc29 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-01-06 08:21 UTC, unknwon commented
> * We could [send a verification email on user creation](https://github.com/sourcegraph/sourcegraph/pull/46187#discussion_r1063020535), but these aren't needed if an admin expects a user to sign in via an external service, and would send an extra email on top of the password reset link if needed. This is also awkward because you must sign in before you click the verification.

IIRC, if an account is pre-created with an unverified and the user is expected to sign in via an external service, a brand new account is always created because we only consider account linking by _verified emails_.

2023-01-06 08:26 UTC, unknwon reviewed
Minor thinking: should we keep the current behavior if SMTP is not configured?

2023-01-06 08:26 UTC, unknwon commented on client/web/src/site-admin/SiteAdminCreateUserPage.tsx
> +                                Optional email for the user - verification will be required if provided.
I find it rare to use `-` in in-product descriptions
```suggestion
                                Optional email for the user that will require verification when provided.
```

2023-01-06 17:37 UTC, bobheadxi commented
> Minor thinking: should we keep the current behavior if SMTP is not configured?

SMTP configuration is not static - you might not set up SMTP until some time after an instance is stood up, for example. Also, whether the email is verified or not doesn't impact instances that don't have SMTP set up, since we cannot send emails anyway

> IIRC, if an account is pre-created with an unverified and the user is expected to sign in via an external service, a brand new account is always created because we only consider account linking by verified emails. Not saying we can't change the current behavior, just want to call out the implication.

Ah, you are right. I think I'll look harder look at having the password reset also handle email verification before making this change then

2023-01-11 20:17 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/users_create.go
Resolved in https://github.com/sourcegraph/sourcegraph/pull/46307

2023-01-12 09:12 UTC, kopancek requested changes
I think some of the changes do not make sense from a UX perspective. It still makes sense to let admins create a user with emails marked as verified - e.g. they know what they are doing and we should trust them.

I would like to also see some unit tests, since this is changing critical functionality (sending password reset links to newly created users).

2023-01-12 09:12 UTC, kopancek commented on client/web/src/site-admin/SiteAdminCreateUserPage.tsx
> +                                Optional email for the user that will require verification when provided.
This is a page for a site admin. I think they should be knowledgable enough to provide a non-bogus email for newly created users. So I think we should have this form create users with verified emails, as we did until now.

2023-01-12 09:12 UTC, kopancek commented on cmd/frontend/graphqlbackend/schema.graphql
> +        The new user's optional email address. If given, it must be verified by the user.
Instead of saying this, I would add an optional boolean parameter to the graphql endpoint - `emailVerified` or similar. That way we can say on the graphql request if the email should be marked as verified or not. By default if the parameter is not present, the email would not be marked as verified.

Which should allow for the behavior that is needed - not marking emails as verified on our graphql requests.

Since this is a backwards incompatible change, I think it also needs to be mentioned on the changelog.

2023-01-12 09:12 UTC, kopancek commented on cmd/frontend/graphqlbackend/users_create.go
> +	needsEmailVerification := email != "" && conf.CanSendEmail()
See my comment above. I think if we make the `emailVerified` param part of the request, the code here would need to be slightly modified.

2023-01-12 09:12 UTC, kopancek commented on cmd/frontend/graphqlbackend/users_create.go
> +	if conf.CanSendEmail() && r.needsEmailVerification {
I'm not sure this check is correct. 

Previous behavior: if we have SMTP configured, we send the reset password email to the user.

New behavior: if we have SMTP configured, we do not send the reset password email unless email needs to be verified. Seems like it would not work correctly for all the cases...

2023-01-12 16:37 UTC, bobheadxi commented on client/web/src/site-admin/SiteAdminCreateUserPage.tsx
> +        }
nice :)

2023-01-12 16:40 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/users_create.go
> +	if conf.CanSendEmail() && r.needsEmailVerification {
You're right, fixed!

2023-01-12 16:42 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/users_create.go
> -	// POV of the API consumer.
Added it back 👍

2023-01-12 16:44 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/users_create.go
> +	}
A verification code is required to set `Verified: false`, so if it fails to generate then we can't create the user

2023-01-12 16:48 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/users_create.go
> +	logger := r.logger.Scoped("createUser", "create user handler").With(
I've added more logging here

2023-01-12 16:48 UTC, bobheadxi commented on client/web/src/site-admin/SiteAdminCreateUserPage.tsx
> +                                Optional email for the user that will require verification when provided.
We recently had an admin create a user with a bogus email, so I'm not sure this is necessarily the case.

That said, we only _really_ care in Cloud - I could add this behind a feature flag instead

2023-01-12 16:57 UTC, bobheadxi commented on client/web/src/site-admin/SiteAdminCreateUserPage.tsx
> +                                Optional email for the user that will require verification when provided.
If a site admin wants to create a user and mark it as verified they can use the mutation `setUserEmailVerified`, which is also available in the UI

2023-01-12 16:58 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/schema.graphql
> +        The new user's optional email address. If given, it must be verified by the user.
Added a changelog entry representing the change in default behaviour. IMO we shouldn't parameterize the behaviour, since there are ways a site admin can explicitly override it - continuing discussion in https://github.com/sourcegraph/sourcegraph/pull/46187#discussion_r1067861965

2023-01-19 11:20 UTC, evict approved these changes

2023-01-20 04:10 UTC, bobheadxi commented
@kopancek thanks for the first round of reviews - I've addressed your comments and updated the behaviour, would appreciate a review when you get the chance!

2023-01-20 04:17 UTC, bobheadxi commented on client/web/src/site-admin/SiteAdminCreateUserPage.tsx
> +                                Optional email for the user that will require verification when provided.
I've updated the text generated here such that the output creates a link to the user profile, for ease of access to the manual email verification. The behaviour has also been updated such that:

1. In the UI, if SMTP is enabled _and_ password resets are possible, we create with email unverified. This is because the user is very likely to click the password reset link via their email, which will verify the email.
2. In the API, the old behaviour is always retained.

2023-01-20 04:17 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/schema.graphql
> +        The new user's optional email address. If given, it must be verified by the user.
updated - see https://github.com/sourcegraph/sourcegraph/pull/46187#discussion_r1082096098

2023-01-20 10:47 UTC, mrnugget reviewed
Do we also need to update docs?

2023-01-20 17:46 UTC, bobheadxi commented
@mrnugget I've created some docs around email verification here: https://github.com/sourcegraph/sourcegraph/pull/46187/commits/00d5137881812fc280f7b7265df34aadcb2e28d3

2023-01-23 10:29 UTC, mrnugget commented
Thanks!

2023-01-24 06:05 UTC, unknwon approved these changes

2023-01-24 06:05 UTC, unknwon commented on cmd/frontend/internal/auth/userpasswd/set_password.go
> +func HandleSetPasswordEmail(ctx context.Context, db database.DB, id int32, username string, email string, emailVerified bool) (string, error) {
```suggestion
func HandleSetPasswordEmail(ctx context.Context, db database.DB, id int32, username, email string, emailVerified bool) (string, error) {
```

2023-01-24 08:45 UTC, kopancek approved these changes
Looks good to me. Added small sugestions that should not block PR merge.

2023-01-24 08:45 UTC, kopancek commented on CHANGELOG.md
> +- When SMTP is configured, users created by site admins via the "Create user" page will no longer have their email verified by default - users must verify their emails by using the "Set password" lin
Typo `the the "Emails" tab`
```suggestion
- When SMTP is configured, users created by site admins via the "Create user" page will no longer have their email verified by default - users must verify their emails by using the "Set password" link they get sent, or have their emails verified by a site admin via the "Emails" tab in user settings or the `setUserEmailVerified` mutation. The `createUser` mutation retains the old behaviour of automatically marking emails as verified. To learn more, refer to the [SMTP and email delivery](https://docs.sourcegraph.com/admin/config/email) documentation. [#46187](https://github.com/sourcegraph/sourcegraph/pull/46187)
```

2023-01-24 08:45 UTC, kopancek commented on doc/admin/auth/index.md
> +Password reset links expire after 4 hours by default - this can be configured in site configuration with the `auth.passwordResetLinkExpiry` field.
I think it would be better to have a link that points to the site config schema definition here. Not sure how feasible that is though 🤔

2023-01-25 00:14 UTC, bobheadxi commented on doc/admin/auth/index.md
> +Password reset links expire after 4 hours by default - this can be configured in site configuration with the `auth.passwordResetLinkExpiry` field.
Added a link!

2023-01-25 00:14 UTC, bobheadxi commented on doc/admin/auth/index.md
> +Password reset links expire after 4 hours by default - this can be configured in site configuration with the `auth.passwordResetLinkExpiry` field.
Trick seems to be to view the `site_config` page in browser, and get the anchor link through there

2023-01-25 00:33 UTC, merged