add logic for release cycle to release protector
sourcegraph/sourcegraph pull request #46345
Opened 2023-01-11 21:45 UTC by BolajiOlajide

Moved the script into its own file so its easier to read and edit. Happy to move it into the yaml if it isn't convenient.

## Test plan

Tested using an ubuntu container, so I think it should work. WIll need to revamp when we switch the cadence for releases at Sourcegraph.

My shell scripting isn't great so feedback is definitely appreciated and welcome.

2023-01-11 22:21 UTC, coury-clark commented on .github/workflows/release_protector.sh
> +cut_date=$(get_closest_working_day "$(date -d "$release_date - 3 days" +%F)")
Is there any reason we wouldn't cut and freeze on the same day? What's the point of freezing before cutting?

2023-01-11 22:37 UTC, BolajiOlajide commented on .github/workflows/release_protector.sh
> +cut_date=$(get_closest_working_day "$(date -d "$release_date - 3 days" +%F)")
To reduce the number of cherry picks after the cut and ensure only crucial work go in. Might be redundant but I was following the breakdown @mrnugget shared for the starship release in March, happy to change it if it's deemed redundant.

2023-01-11 22:45 UTC, coury-clark commented on .github/workflows/release_protector.sh
> +cut_date=$(get_closest_working_day "$(date -d "$release_date - 3 days" +%F)")
ah I see, thanks

2023-01-11 22:45 UTC, coury-clark approved these changes

2023-01-12 08:51 UTC, jhchabran commented on .github/workflows/release_protector.sh
> +  if $(is_weekend "$date_to_check"); then
This triggers a bunch of warnings @BolajiOlajide, cf CI results!

2023-01-12 11:53 UTC, BolajiOlajide commented on .github/workflows/release_protector.sh
> +  if $(is_weekend "$date_to_check"); then
Taking a look. 

I pushed this last night and went to bed - I didn't bother to wait for CI results lol. Thanks

2023-01-12 13:05 UTC, mrnugget commented on .github/workflows/release_protector.sh
> +cut_date=$(get_closest_working_day "$(date -d "$release_date - 3 days" +%F)")
Freeze: no more changes going into `main`, folks are expected to test & fix
Cut: we deem what we have on `main` as releasable
Release: we are sure that what we cut as a release is correct and can go out

That's how I think about it.

2023-01-12 13:11 UTC, BolajiOlajide commented on .github/workflows/release_protector.sh
> +  while $(is_weekend "$date_string"); do
```
In .github/workflows/release_protector.sh line 29:
  while $(is_weekend "$date_string"); do
        ^--------------------------^ SC2091: Remove surrounding $() to avoid executing output.
```

I get this error when running spellcheck, however, when I remove the parenthesis, this results in an infinite loop. Do you have any ideas on how I can fix this @jhchabran ?

2023-01-12 13:16 UTC, jhchabran requested changes

2023-01-12 13:54 UTC, BolajiOlajide commented on .github/workflows/release_protector.sh
> +  if $(is_weekend "$date_to_check"); then
Fixed.

2023-01-12 17:59 UTC, jhchabran approved these changes

2023-01-12 17:59 UTC, merged