batches: merge xs and small viewport for preview changeset list
sourcegraph/sourcegraph pull request #46398
Opened 2023-01-12 23:11 UTC by adeola-ak

Closes #44716

This is to prevent text from overflowing out of its container as it would on smaller screens. Now the behavior for xs viewport is duplicated for small viewports, and the page responsiveness as well as hiding of some elements starts at an earlier width.

## Test plan
Observed screen in smaller widths without overflowing text

2023-01-13 14:17 UTC, BolajiOlajide requested changes

2023-01-13 14:17 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
> +                className="test-batches-expand-preview d-none d-md-block mx-1"
This breaks the preview mode for slightly smaller screens.

| main       | <img width="744" alt="CleanShot 2023-01-13 at 15 11 54@2x" src="https://user-images.githubusercontent.com/25608335/212339764-01ef2a20-42bd-44fa-9956-1b0cdac0482e.png">  |
|------------|---|
| new branch | <img width="750" alt="CleanShot 2023-01-13 at 15 11 41@2x" src="https://user-images.githubusercontent.com/25608335/212339693-fbfd45b7-2566-49b2-8a3e-373d0b4f4a7f.png">  |

2023-01-13 14:17 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
> +                className="test-batches-expand-preview d-none d-md-block mx-1"
I believe we still need some of the old media queries so slightly smaller screens don't have this weird look.

2023-01-27 03:25 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.52 kb) | 0.00% (+0.52 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/aa/fix-preview-list/compare-report.html;tab=live_object) for a full comparison between the commits 03d5ec9 and 692910a or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-02-21 13:50 UTC, BolajiOlajide reviewed
Also +1 to Kelli's comment, I got the same result when I ran this on my machine.

2023-02-21 13:50 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/preview/list/VisibleChangesetApplyPreviewNode.tsx
> +                {/* <div className="d-block d-md-flex justify-content-center align-content-center align-self-stretch"> */}
Did you mean to delete this?

2024-01-10 20:52 UTC, eseliger commented
As part of #wg-delete-week I am going to close this PR. If it’s still needed, feel free to reopen and restore the branch.

2024-01-10 20:52 UTC, closed without merging