graphqlutil: Fix bug with truncating extra item for pagination and switch reverse to false by default
sourcegraph/sourcegraph pull request #46497
Opened 2023-01-16 11:05 UTC by indradhanush

## Note to reviewers, please read before reading the code

Originally I wanted to create two separate PRs - one to fix the bug with truncating the last item and the second to make the `Reverse` option `false` by default instead of `true` which is the current behaviour.

But as I was working with this, both these two are closely related with each other and it became difficult to keep them separate - which would have added more work on the second PR to fix the tests that I was already fixing in this one to account for the new default behavior.

So the end result against my own wishes is a single PR that does two things. I will explain the motivation behind each individually, although the source is the same - this PR being a result of working on #46475.

### Motivation #1: Bug fix of truncating the last item

This fixes two bugs with the truncating logic.

1. Truncating from the head when `last` is used is incorrect since the data set is already reversed as a result of underlying SQL query having to run the ORDER BY DESC operation.

2. Additionally, the current logic does not take the value of the `Reverse` option into account before truncating the first or the last item.

Explained with an example with in-line comments why even for `last` in the query args, truncating the last item from the slice is the right thing to do and vice versa for when `Reverse` is set to `true`.

### Motivation #2: Switch Reverse to false by default

Setting the value of `Reverse` to `true` will flip the resulting data set. This is also the default at the moment in the connection resolver library. This leads to the library sneakily reversing the data set by default which was a source of great confusion when I was working on #46475 and had me digging to understand why this was so. In my test cases I was struggling with off-by-one errors as a result of the combination of this and the above bug.

A library should not make default assumptions on the data set it handles. Instead this should be left as an explicit decision for the consumers of the library itself. If a developer uses this library to implement support for querying the API with both `first` and `last`, they would implement `ORDER BY ASC` in their SQL query to support `first` and `ORDER BY DESC` in their SQL query to support `last`. This then becomes an explicit expectation to receive the data set in the API in reverse when `last` is used. But when the internal library sneakily reverses it by default it leads to a breakdown of this expectation. 

~~Additionally, with `Reverse` set to `true` by default will mean that when the API is queried with `first`, even then the resulting data set is going to be reversed. This appears to have little utility from an API consumers viewpoint.~~

In the only current usage of `Reverse` (in the `RepositoryContributors` API) we explicitly set `Reverse` to false. And in my implementation in #46475, I found myself doing the same. 

Finally, in Go boolean default is `false` and it seems counter-intuitive that in our code we assume a nil value to be interpreted as `true`. And if the struct is also initialised with default values, then a non-nil default would set `Reverse` to `false` which would be against what the docs for the option describe as.

## Test plan

1. Updated tests
1. Builds should pass
1. Tested this change against the code in #46475 which has its own additional tests

2023-01-16 15:43 UTC, sashaostrikov requested changes
I think we should change some UI code right away in order not to break pagination.

2023-01-16 15:43 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	// If for any reason this is not ideal for an API implementing the ConnectionResolver, setting
I think this change cannot be shipped without changing all UI usages of this API to explicitly set `reverse` to `true`, I can find that it is used in one place:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/stats/RepositoryStatsContributorsPage.tsx?L123&subtree=true

2023-01-16 15:47 UTC, indradhanush commented
A bit of an after thought: Do we even need to support reverse at this point if we're going to not be using it in our API implementations? If no, then should we just get rid of it?

2023-01-16 15:48 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +	// If for any reason this is not ideal for an API implementing the ConnectionResolver, setting
The resolver is hardcoded to use `reverse: false` at the moment. I don't see how this could be set from the client though. 🤔

2023-01-16 17:06 UTC, indradhanush commented on cmd/frontend/graphqlbackend/graphqlutil/connection_resolver.go
> +		nodes = nodes[:len(nodes)-1]
I think I messed up somewhere. This is still buggy and needs more work.

2023-01-17 04:34 UTC, indradhanush commented
### Update

I had a nice chat with @thenamankumar and I've come to realise that my approach was incorrect. I was approaching the API design from the SQL point of view: first-3 should return the first 3 items from the DB. But the API design needs to be approached from the UI's point of view, first-3 would mean exactly the opposite: return the latest 3 items from the DB. 

With a clearer understanding, this PR now does not make sense. I've verified that the "bug" does not exist.

And that we should not set "reverse to false by default" either. The reverse stands as a workaround for non-SQL based datasets and as a result the current behaviour should persist.

2023-01-17 04:34 UTC, closed without merging