create options to recover users
sourcegraph/sourcegraph pull request #46654
Opened 2023-01-19 06:02 UTC by mucles

providing customers with an easier option for restoring user records after a deletion
## Test plan
manually tested by deleting a user in UI and restoring the user through graphql api

2023-01-19 09:21 UTC, jhchabran requested changes

2023-01-19 09:21 UTC, jhchabran commented on internal/database/users.go
> +func (u *userStore) RecoverUserByID(ctx context.Context, id int32) (_ []*types.User, err error) {
You don't need to name the return values there, it'd be best to remove it as it usually indicates you're doing something with them, which is not the case here.

2023-01-19 09:21 UTC, jhchabran commented on internal/database/users.go
> +func (u *userStore) RecoverList(ctx context.Context, ids []int32) (_ []*types.User, err error) {
Same here

2023-01-19 09:21 UTC, jhchabran commented on internal/database/users.go
> +		return nil, userNotFoundErr{args: []any{fmt.Sprintf("Some users were not found. Expected to recover %d users, but deleted only %d", +len(ids), rows)}}
It's better usually to use the `args` field to signify which users were not found. 

Also, I think the "deleted" part is bit confusing, you probably want to say something like "but only %d were previously deleted". 

I would do something like: 

```
notFoundErr := userNotFoundErr{args: []any{userIDs...}}
return nil errors.Wrapf(err, "some users were not found, expected to recover %d, but found only %s, len..., strings.Join(missingUserIds}))
```

2023-01-19 09:21 UTC, jhchabran commented on internal/database/users.go
> +	defer func() { err = tx.Done(err) }()
You're never rollbacking here, is that on purpose? Because this defeats the purpose of using a transaction, as you would commit the results, while not having done all updates if one of the SQL queries return an error. 

You can leverage the fact that you're using a named error return value and do something like `if err != nil { _ = tx.Rollback() } else { err = tx.Commit() }` to fix this.

2023-01-19 19:44 UTC, mucles commented on internal/database/users.go
> +	defer func() { err = tx.Done(err) }()
@jhchabran  the tx.Done() function performs the rollback in case of an error 
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@171416653025ef363d9a93821a8b49a56161e428/-/blob/internal/database/basestore/handle.go?L31-37

2023-01-19 19:46 UTC, mucles commented on internal/database/users.go
> +		return nil, userNotFoundErr{args: []any{fmt.Sprintf("Some users were not found. Expected to recover %d users, but deleted only %d", +len(ids), rows)}}
@jhchabran  Sounds good, are there any issues with returning the missing User Ids to consider?

2023-01-19 22:33 UTC, mucles commented on internal/database/users.go
> +		return errors.Errorf("some users were not found, expected to recover %d, but found only %d: %s", len(userIDs), len(affectedUserID), strings.Join(missingUserIds, ","))
@jhchabran , @camdencheek , any ideas on how I can return this ids marshaled 👀

2023-01-20 08:58 UTC, mrnugget reviewed
Drive-by comments :)

2023-01-20 08:58 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    recoverUsers(userIDs: [ID!]!): EmptyResponse
Why two mutations when you can have only the latter one and pass in a single ID?

2023-01-20 08:58 UTC, mrnugget commented on cmd/frontend/graphqlbackend/site_admin.go
> +			return nil, errors.New("unable to delete current user")
```suggestion
			return nil, errors.New("unable to recover current user")
```

2023-01-20 08:58 UTC, mrnugget commented on internal/database/users.go
> +	}
```suggestion
	affectedUserID, err := basestore.ScanInt32s(tx.Query(ctx, sqlf.Sprintf("UPDATE users SET deleted_at=NULL, updated_at=now() WHERE id IN (%s) AND deleted_at IS NOT NULL RETURNING id", idsCond)))
	if err != nil {
		return err
	}
```

That should work :) `basestore` has some great stuff.

2023-01-20 08:58 UTC, mrnugget commented on internal/database/users.go
> +		}
You can probably get away with only one query here: `INSERT INTO names(name, user_id) SELECT username, id FROM users WHERE id IN(%s)`

2023-01-20 08:58 UTC, mrnugget commented on internal/database/users.go
> +	}
Do we also need to restore emails?

2023-01-21 00:46 UTC, mucles commented on cmd/frontend/graphqlbackend/schema.graphql
> +    recoverUsers(userIDs: [ID!]!): EmptyResponse
Yeah, that's a good point only the latter is really needed

2023-01-21 00:47 UTC, mucles commented on internal/database/users.go
> +	}
That is awesome 🔥 , Thank you 🙏

2023-01-21 00:52 UTC, mucles commented on internal/database/users.go
> +	}
As long as you have the username + password, it still lets the user log in. the user can add their email later. Maybe in the access of OAuth sign-ins, it will require the email? I am not sure how to restore that because it gets deleted 🤔

2023-01-23 10:25 UTC, mrnugget commented on internal/database/users.go
> +	}
> As long as you have the username without the email, it still lets the user log in.

If they have defined a username. If they previously logged in only with OAuth we might not have a primary email, but only external accounts.

I suggest you test this manually by logging in with GitHub as a user (use these settings: https://github.com/sourcegraph/dev-private/blob/cf78e863c204f8f4ac7c503fad33a73b7094f8f4/enterprise/dev/site-config.json#L23-L42), soft-deleting and restoring user, then trying to log back in.

Also: cc @sourcegraph/iam to possibly add something

2023-01-23 12:34 UTC, pjlast reviewed
Left a comment on restoring `user_external_accounts`, but I think it should apply to everything that can be restored. I would recommend not restoring everything that has a `deleted_at != NULL`. Instead, only restore items where you can say with a fair amount of confidence that they were deleted alongside the user account, by doing something like checking if the `deleted_at` column is within some time frame of the user's `deleted_at` column.

2023-01-23 12:34 UTC, pjlast commented on internal/database/users.go
> +	}
I'm not sure if this is a safe operation. Whenever a user deletes an external account, it is marked as deleted in the DB. Then when they add an account again, a new connection is created. So if a user added and removed a GitHub account 3 times, there will be 3 entries in the database where `deleted_at != NULL`. This would restore all of them at the same time, as well as restoring deleted accounts that were deleted intentionally.

So what we want here is to maybe isolate the accounts that were marked as deleted alongside the user account. Perhaps something like "only restore user_external_accounts where the deleted_at is within 10 seconds of the user's deleted_at timestamp".

2023-01-23 12:40 UTC, pjlast commented on internal/database/users.go
> +	}
So if you sign in using only OAuth, the first verified email address from the OAuth provider will be used as the primary address of the Sourcegraph account.

There are scenarios where you can have OAuth connections without any email set, but then the user would have to have signed in using username and password, and then connected an OAuth account. If they signed in with OAuth, the OAuth email will be their primary email.

But yes, you can't restore user emails, they get hard deleted even when the user account is soft deleted. But if the `user_external_account` is restored, a login with that external account should still work as expected and link to the original user, even if there is no email attached to the user.

2023-01-23 16:18 UTC, kopancek commented on internal/database/users.go
> +		return errors.Errorf("some users were not found, expected to recover %d, but found only %d: %s", len(userIDs), len(affectedUserID), strings.Join(missingUserIds, ","))
I think you can can catch this kind of error in the resolver and use the [`MarshalUserID`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/user.go?L100) function. At least, that would be the cleanest IMO.

2023-01-23 16:18 UTC, kopancek commented on internal/database/users.go
> +	}
Agreed. This timestamp rule should apply to all the other resources that we bring back in this method (from what I see `org_invitations`, `registry_extensions`, etc.

2023-01-23 16:18 UTC, kopancek commented on internal/database/users.go
> +	if err := tx.Exec(ctx, sqlf.Sprintf("UPDATE org_invitations SET deleted_at=NULL WHERE deleted_at IS NOT NULL AND (sender_user_id IN (%s) OR recipient_user_id IN (%s))", idsCond, idsCond)); err != ni
We should not revive any invitations that are already expired, responded or revoked

2023-01-23 16:18 UTC, kopancek commented on internal/database/users.go
> +}
This is already implemented on the resolver. I don't think our DB layer should know anything about the graphql marshaling ID logic.

2023-01-23 21:23 UTC, camdencheek commented on internal/database/users.go
> +	defer func() { err = tx.Done(err) }()
@mucles It does, but the error being referenced is not the return value. It's referencing the error defined by `u.Transact()`. This will sorta work because you're overwriting that error in most places before returning it, but on line 707, you're creating a new error and returning it, so the `err` variable will still be `nil`, which means the transaction will not be rolled back. 

This problem is also one of the inspirations for [this PR](https://github.com/sourcegraph/sourcegraph/pull/46796)

2023-01-23 21:23 UTC, camdencheek commented on internal/database/users.go
> +	idsCond := sqlf.Join(userIDs, ",")
This should work:
```suggestion
	idsCond := pq.Array(ids)
```

2023-01-24 08:10 UTC, jhchabran commented on internal/database/users.go
> +	defer func() { err = tx.Done(err) }()
Oh right, I forgot it does. But @camdencheek is right, the error won't be the good one.

2023-01-25 03:51 UTC, mucles commented on internal/database/users.go
> +	idsCond := sqlf.Join(userIDs, ",")
@camdencheek  I tried this change, but for some reason, I kept getting the follow error message 
`
{
  "errors": [
    {
      "message": "ERROR: invalid input syntax for type integer: \"{2}\" (SQLSTATE 22P02)",
      "path": [
        "recoverUsers"
      ]
    }
  ],
  "data": {
    "recoverUsers": null
  }
}
`

2023-01-25 03:55 UTC, mucles commented on internal/database/users.go
> +	defer func() { err = tx.Done(err) }()
@camdencheek @jhchabran I moved that error check to the graphql resolver like suggested, so that should no longer be an issue

2023-01-25 03:56 UTC, mucles commented on internal/database/users.go
> +}
@kopancek  thank you 🙏  I moved this to the resolver

2023-01-25 03:58 UTC, camdencheek commented on internal/database/users.go
> +	defer func() { err = tx.Done(err) }()
I would still strongly recommend  making the error return value a named return value like `(err error)`. This is still currently pretty fragile because it depends on `err` not being shadowed.

2023-01-25 04:00 UTC, camdencheek commented on internal/database/users.go
> +	idsCond := sqlf.Join(userIDs, ",")
Oh, huh. I guess the SQL value type of a set is different than an array. Feel free to ignore this comment then 👍

2023-01-25 04:04 UTC, mucles commented on internal/database/users.go
> +	//todo: @mucles - need add where condition to query to only update if deleted_at is within 10 secs of users.deleted_at
@pjlast @kopancek thank you both for your feedback 🙏 , I definitely agree that there should be a check that the deleted_at is within the same interval at the users.deleted_at before restoring. I haven't been able to quite figure out how to write the query for that. do you have any suggestions?

2023-01-25 04:12 UTC, mucles commented on internal/database/users.go
> +	defer func() { err = tx.Done(err) }()
Oh okay, I got yeah that makes now, I will update it to make the error return value a named return value 👍

2023-01-25 13:14 UTC, kopancek commented on internal/database/users.go
> +	//todo: @mucles - need add where condition to query to only update if deleted_at is within 10 secs of users.deleted_at
I think you first need to get the existing `deleted_at` timestamp from the `user` table, matching the criteria. Since you are modifying that with the `UPDATE` query, you need to do a `SELECT` query to get it first.

All the other queries can then be modified with a `WHERE` clause, something similar to (I'm just putting the timestamp comparison, ignoring the other where clauses for brevity), [and here is my doc source](https://www.postgresql.org/docs/12/functions-datetime.html):
```
WHERE deleted_at >= user_deleted_at AND deleted_at <= user_deleted_at + interval '10 second'
```

I have not tested it out, but something like this should work.

2023-01-25 13:32 UTC, kopancek reviewed
2 more comments. Looks better with some of the code moved to the resolver 👍

2023-01-25 13:32 UTC, kopancek commented on cmd/frontend/graphqlbackend/site_admin.go
> +		return nil, errors.Errorf("some users were not found, expected to recover %d, but found only %d: %s", len(ids), len(users), missingUserIds)
```suggestion
		return nil, errors.Errorf("some users were not found, expected to recover %d users, but found only %d users. Missing user IDs: %s", len(ids), len(users), missingUserIds)
```

2023-01-25 13:32 UTC, kopancek commented on internal/database/users.go
> +	if err := tx.Exec(ctx, sqlf.Sprintf("UPDATE org_invitations SET deleted_at=NULL WHERE deleted_at IS NOT NULL and revoked_at IS NOT NULL and expires_at >= now() AND (sender_user_id IN (%s) OR recipie
We actually want `revoked_at IS NULL` here, because that means the invitation is NOT revoked.
```suggestion
	if err := tx.Exec(ctx, sqlf.Sprintf("UPDATE org_invitations SET deleted_at=NULL WHERE deleted_at IS NOT NULL and revoked_at IS NULL and expires_at >= now() AND (sender_user_id IN (%s) OR recipient_user_id IN (%s))", idsCond, idsCond)); err != nil {
```

Also, not sure it makes sense to revive org invitations at all, but I am not here to decide what the feature should accomplish.

2023-01-25 20:09 UTC, mucles commented on internal/database/users.go
> +	if err := tx.Exec(ctx, sqlf.Sprintf("UPDATE org_invitations SET deleted_at=NULL WHERE deleted_at IS NOT NULL and revoked_at IS NOT NULL and expires_at >= now() AND (sender_user_id IN (%s) OR recipie
Good catch, thank you! It would make sense if the revived users could still access pending org invites, but I wonder if it is necessary since the org invite could just be resent again. If the org_invites aren't revived, we should also do hard delete org invites rather than : https://github.com/sourcegraph/sourcegraph/blob/main/internal/database/users.go#L552

2023-01-25 20:12 UTC, mucles commented on internal/database/users.go
> +	//todo: @mucles - need add where condition to query to only update if deleted_at is within 10 secs of users.deleted_at
@kopancek  sweet, thank you so much 🙏  I will give this a try!

2023-01-26 08:46 UTC, mucles commented on internal/database/users.go
> +	AND a.user_id IN (%s)
@kopancek @pjlast This query change worked, I was able to restore the user and user_external_accounts that were deleted together with the 10-second interval 🙌

2023-01-26 22:32 UTC, mucles commented
@kopancek  Thank you 🙏 
Yes, I agree; I would also include a unit test for reviving more than 1 user at a time. I can add the unit test for the revive functionality in a follow-up PR

2023-01-27 16:17 UTC, camdencheek approved these changes
LGTM! Thanks for all your work on this!

2023-01-27 16:17 UTC, camdencheek commented on internal/database/users.go
> +	Query(ctx context.Context, query *sqlf.Query) (*sql.Rows, error)
Was this intentionally added to the interface? This should probably not be exported

2023-01-30 16:25 UTC, mucles commented on internal/database/users.go
> +	Query(ctx context.Context, query *sqlf.Query) (*sql.Rows, error)
@camdencheek  this was intentionally added to be able to return the ids https://github.com/sourcegraph/sourcegraph/pull/46654/files#diff-3d3653055d46317f03f4ad8e091d551ccc70d33430e131d4f7c39fe07bbd1dd1R739

2023-01-30 16:31 UTC, camdencheek commented on internal/database/users.go
> +	Query(ctx context.Context, query *sqlf.Query) (*sql.Rows, error)
Ah, I see. `Transact` returns the interface, not the struct, and `Query` is not exported on the interface. 

We try to avoid exporting `Query`/`QueryRow`/`Exec` to maintain encapsulation. The normal pattern here is to export a private `transact()` method that returns the concrete struct rather than returning the interace. This way, methods of the struct can still use the private `transact` which returns the struct, which exposes `Query`. Example [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@fc5131c23bba44d55b4e99653d231ab4a0b05035/-/blob/internal/database/permission_sync_jobs.go?L74-77)

2023-01-30 22:16 UTC, merged