permissions-center: implement perms sync deduplication logic.
sourcegraph/sourcegraph pull request #46656
Opened 2023-01-19 09:11 UTC by sashaostrikov

Test plan:
1) sg migration up -> down -> up.
2) Database tests added.

Closes https://github.com/sourcegraph/sourcegraph/issues/46321

2023-01-19 09:15 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +ON CONFLICT DO NOTHING
Imagine saying that in a cross-team collaboration interview.

2023-01-19 09:22 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +		return nil
What can we do to record that we didn't push a job to the queue?

Could we write a log, at least, if we don't return an error?

2023-01-19 09:24 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +// checkDuplicateAndCreateSyncJob adds a new perms sync job if there is no
Can you also mention in the comment that this function should only be used with jobs with process_after = NULL.

2023-01-19 09:25 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +func buildCancelQuery(opts CancelPermissionSyncJobOptions) (*sqlf.Query, error) {
why to create a whole struct when you only need 1 ID argument?

2023-01-19 09:27 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +func buildCancelQuery(opts CancelPermissionSyncJobOptions) (*sqlf.Query, error) {
You don't need `conds` at all. just pass `ID` on line 224.

2023-01-19 09:31 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
If we only consider `state ='queued'` in the where clause then would not we be able to directly update `state = 'canceled'` `and finished_at = NOW()`?

If the job is already in processing, why do we need to set `cancel = TRUE`?

2023-01-19 09:33 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
```
UPDATE
	permission_sync_jobs
SET
	cancel = TRUE,
	state = 'canceled',
	finished_at = %s
WHERE
    id = %s
	AND
	state = 'queued'
    AND
	cancel IS FALSE
```

2023-01-19 09:33 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
why won't the above work?

2023-01-19 09:34 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +	if opts.NotNullProcessAfter {
👍

2023-01-19 09:36 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
!!!!!!

Also need to check `process_after IS NULL`

2023-01-19 09:37 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
add tests for this as well.

2023-01-19 09:39 UTC, thenamankumar commented on internal/database/schema.json
> +          "ConstraintDefinition": "CHECK ((user_id IS NULL) \u003c\u003e (repository_id IS NULL))"
TIL `\u003c\u003e` usage

2023-01-19 09:47 UTC, mrnugget requested changes
Make sure to use the transaction!

2023-01-19 09:47 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +	CancelSyncJob(ctx context.Context, opts CancelPermissionSyncJobOptions) error
Maybe, I'm not sure:
```suggestion
	Cancel(ctx context.Context, opts CancelPermissionSyncJobOptions) error
```

Since the whole thing is called `PermissionSyncJobStore` already.

2023-01-19 09:47 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +		return s.create(ctx, job)
This is a bug because you're doing the `s.create` outside the transaction. What you need is to pass `tx` to `s.create` so it's created inside the transaction and then committed when the outer function, `checkDuplicateAndCreateSyncJob`, returns.

```suggestion
		return tx.create(ctx, job)
```

this should do it, I think

2023-01-19 09:47 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +	return s.create(ctx, job)
Same as above: you need to do all of this in the same transaction

```suggestion
	err = tx.CancelSyncJob(ctx, CancelPermissionSyncJobOptions{ID: existingJob.ID})
	if err != nil {
		return err
	}
	return tx.create(ctx, job)
```

2023-01-19 09:47 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +func buildCancelQuery(opts CancelPermissionSyncJobOptions) (*sqlf.Query, error) {
Eh, I think it doesn't cost us that much and it makes it easy to extend later with other conditions ("cancel all running jobs", "cancel all jobs for user_id 99", "cancel all jobs for repo_id 123 which we just deleted")

2023-01-19 09:47 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
When it's processing then the worker canceller will pick up jobs marked where `cancel = true` and cancel them. You don't update the state in that case. That's what the cancelled will do.

2023-01-19 09:49 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
Here's an explanation: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/batches/store/batch_spec_workspace_execution_jobs.go?L433-434

(We should have docs for this 😬 )

2023-01-19 10:06 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
@mrnugget 

But we do not need to cancel processing jobs at all. 

Also, why update the state here? Because we want to immediately add an item with state="QUEUED", which will violate the DB constraint. 

So we can't rely on async updation of state when a job is marked as cancelled.

2023-01-19 10:13 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
> But we do not need to cancel processing jobs at all.

Okay, if that's the case then things get simpler. In that case I'd call it `CancelQueuedJob` or something.

2023-01-19 10:25 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +	state IN ('queued', 'processing')
Plus 1 on the tests!

2023-01-19 11:27 UTC, sashaostrikov commented on internal/database/permission_sync_jobs.go
> +ON CONFLICT DO NOTHING
lol

2023-01-19 12:42 UTC, sashaostrikov commented
@thenamankumar @mrnugget thanks for review!
I've addressed the comments, PTAL.

2023-01-19 15:30 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +WHERE id = %s AND state = 'queued' AND cancel IS FALSE
Missed checking for `process_after IS NULL`. Please also add tests to cover the case where a job already exists but is scheduled for future. We don't want to cancel that job here.

2023-01-19 15:32 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +		return errors.Newf("sync job with id %d not found", id)
In this case, we should still create the new job. But above on line 202, we abort when this error is received.

2023-01-19 15:35 UTC, sashaostrikov commented on internal/database/permission_sync_jobs.go
> +WHERE id = %s AND state = 'queued' AND cancel IS FALSE
I didn't miss that, this check is implemented above in logic. I didn't want to make this function too narrow (only for `process_after == nil` jobs), it is currently doing what is described -- cancelling the job with given ID.

2023-01-19 15:48 UTC, mrnugget approved these changes

2023-01-19 15:48 UTC, mrnugget commented on internal/database/permission_sync_jobs_test.go
> +	assert.Len(t, allUser1Jobs, 3)
Nitpicky, I know, but: I think newlines make blocks like this more readable.

```suggestion
	err = store.CreateUserSyncJob(ctx, 1, user1LowPrioJob)
	assert.NoError(t, err)
	
	err = store.CreateUserSyncJob(ctx, 1, user1HighPrioJob)
	assert.NoError(t, err)
	
	allUser1Jobs, err = store.List(ctx, ListPermissionSyncJobOpts{UserID: 1})
	assert.NoError(t, err)
	// check that we still have 3 jobs for userID=1 in total (low prio (canceled), delayed, high prio)
	assert.Len(t, allUser1Jobs, 3)
```

2023-01-19 15:48 UTC, mrnugget commented on internal/database/permission_sync_jobs_test.go
> +	assert.Len(t, allUser1Jobs, 4)
TIL that `assert` doesn't fail with `t.Fatalf` but instead continues with `t.Errorf`. Maybe we should switch to `require`? (Not in this PR, but found out today and thought of this PR)

2023-01-19 15:50 UTC, sashaostrikov commented on internal/database/permission_sync_jobs_test.go
> +	assert.Len(t, allUser1Jobs, 4)
hmm, that's a nice idea, I'll change it in next PR!

2023-01-19 17:12 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +WHERE id = %s AND state = 'queued' AND cancel IS FALSE
we can rename the func. I just want to be sure that by mistake this query do not cancel non-intended job. 

are we sure that the transaction will handle this?

2023-01-19 17:26 UTC, merged

2023-01-20 08:52 UTC, sashaostrikov commented on internal/database/permission_sync_jobs.go
> +WHERE id = %s AND state = 'queued' AND cancel IS FALSE
`CancelQueuedJob` cancels a queued job by ID. If there is no ID match, then nothing is canceled and an error is returned. Basically, we cannot accidentally cancel something random here.