insights: add http handler for exporting data for one code insight
sourcegraph/sourcegraph pull request #46662
Opened 2023-01-19 12:30 UTC by leonore

closes #45746 

This adds a new external api endpoint (`httpapi`) `./api/insights/export/{id}` for exporting code insight data for an insight view. {id} corresponds to the id we use at the moment on the frontend, e.g. https://sourcegraph.sourcegraph.com/insights/aW5zaWdodF92aWV3OiIyQmRnV2VFYktwWGF2UjlGcXpuVDA1cld0c2si

The export store function adds empty rows for times we have no data for, and does some joining on tables to get all the metadata for a user

Some nitty things to consider in your review
* Naming of things in the archive (headers, filename)
* Format of the route `./api/insights/export/{id}`

## Test plan

Tested with
* Search insight
* Capture group insight
* Compute type insight

Ensured insights with archived values had the archived values.

Tested authorization
* Ran the curl against `oss`: returns "code insights data export handler is only available in enterprise"
* Ran the curl against `enterprise`: returns "code insights data export handler is only available in enterprise"
    * not the best error message there but comes from `makeNotFoundHandler`

Curl this was tested with
```bash
curl \
  -H 'Authorization: token {token}' https://sourcegraph.test:3443/.api/insights/export/aW5zaWdodF92aWV3OiIySEx0R0plUVJxS05kS3IyRG1SdmU3ZjNjbXoi -O -J -v
```
-O makes it output it into the file it defines and -J uses the header filename rather than the {id} name.

2023-01-19 15:29 UTC, coury-clark commented
@leonore was this tested against an unauthed user, and a user that doesn't have access to the insight?

2023-01-19 16:08 UTC, leonore commented
> @leonore was this tested against an unauthed user, 

yes, it returns "Private mode requires authentication"

> and a user that doesn't have access to the insight?

good catch, we don't assert on dashboard permissions. will fix that

2023-01-20 15:11 UTC, coury-clark commented on enterprise/internal/insights/httpapi/export.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"CodeInsightsDataExport-%s.zip\"", archive.insightName))
I might suggest a timestamp on the filename, since exporting at time A might be different than exporting at time B

2023-01-20 15:15 UTC, coury-clark commented on enterprise/internal/insights/httpapi/export.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"CodeInsightsDataExport-%s.zip\"", archive.insightName))
Also, I wonder if using the title is the right choice here? Titles might have illegal characters for filenames in it. Maybe insight ID would be a safer choice (as well as potentially shorter)?

2023-01-20 15:17 UTC, leonore commented on enterprise/internal/insights/httpapi/export.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"CodeInsightsDataExport-%s.zip\"", archive.insightName))
sure, just a UX point I'm not too fussed about. I'll add insight id and timestamp

2023-01-20 15:18 UTC, coury-clark commented on enterprise/internal/insights/httpapi/export.go
> +		return nil, errors.New("could not validate user permissions")
This should return a 404 and only display something like "insight not found". We don't want to give any reference that the user could or couldn't actually see an insight, because it imply existence of something that cannot be known.

2023-01-20 15:20 UTC, coury-clark commented on enterprise/internal/insights/httpapi/export.go
> +		return nil, errors.New("could not validate user permissions")
I think we should be careful with this error, and probably return something significantly more generic here. It could be an avenue for attack in some specific scenarios to force this error message.

2023-01-20 15:21 UTC, coury-clark commented on enterprise/internal/insights/httpapi/export.go
> +	dataFile, err := zw.Create(fmt.Sprintf("%s.csv", visibleViewSeries[0].Title))
Once again, we probably need to be careful with titles and filenames

2023-01-20 15:23 UTC, coury-clark commented on enterprise/internal/insights/store/permissions.go
> +	userId := actor.FromContext(ctx).UID
I think we also need `actor.IsAuthenticated()`

2023-01-20 15:25 UTC, coury-clark commented on enterprise/internal/insights/store/store.go
> +		repoIDsPred = sqlf.Sprintf("sp.repo_name_id not in (%s)", sqlf.Join(excludedRepoIDs, ","))
I'm not so sure this should be `repo_name_id` and should instead be `repo_id`

2023-01-20 15:31 UTC, coury-clark requested changes
A few things that need to be addressed, but overall good work!

2023-01-20 17:40 UTC, leonore commented on enterprise/internal/insights/httpapi/export.go
> +		return nil, errors.New("could not validate user permissions")
I'll try a better message, but I'm curious what kind of scenarios you're suggesting? are you suggesting someone might try to derive user IDs/org IDs from this?

2023-01-20 17:46 UTC, leonore commented on enterprise/internal/insights/store/store.go
> +		repoIDsPred = sqlf.Sprintf("sp.repo_name_id not in (%s)", sqlf.Join(excludedRepoIDs, ","))
good catch! I modified this when I changed the join for the repo names table and modified it everywhere :) my test case wasn't well made enough to catch this

2023-01-20 17:47 UTC, leonore commented on enterprise/internal/insights/store/store.go
> +func (s *Store) GetAllDataForInsightViewID(ctx context.Context, insightViewId string) (_ []SeriesPointForExport, err error) {
as discussed I will make this filter down based on the current default repo/context filters

2023-01-20 17:58 UTC, coury-clark commented on enterprise/internal/insights/httpapi/export.go
> +		return nil, errors.New("could not validate user permissions")
I don't have any scenarios off the top of my head, generally I just want to avoid the entire possibility of abuse by removing that information from the API response.

2023-01-20 18:34 UTC, leonore commented
@coury-clark I've pushed some fixes for your requests. FYI I am planning on cleaning up all the repo regex loading stuff and commonising some things there as I just pulled it out the resolvers (plan is to move it out to `store/search_contexts.go`) but for the sake of time/timezone I wanted to get your review so that I could make more progress monday. hope that's ok!

2023-01-21 15:45 UTC, coury-clark commented on enterprise/internal/insights/store/store.go
> +	if len(preds) == 0 {
Not sure if this is just copied from elsewhere but I'm not sure why this is above the exclude regex predicates below. It seems like it may not matter though.

2023-01-21 15:48 UTC, coury-clark commented on enterprise/internal/insights/store/permissions.go
> +		return nil, nil, errors.New("user is unauthenticated")
Ideally this returns 401, but there may be a middleware that does that already. I'd suggest giving it a quick test. I'm also wondering if we should move this check up to the API handler explicitly, just for clarity and to ensure we don't ever accidentally refactor this into the wrong place.

2023-01-21 15:48 UTC, coury-clark approved these changes

2023-01-23 11:36 UTC, leonore commented on enterprise/internal/insights/store/permissions.go
> +		return nil, nil, errors.New("user is unauthenticated")
yeah so if you try and hit the API without an authorization header it will already return 401 (with `Private mode requires authentication`). if you try it with a wrong token it does the same. I didn't pinpoint where exactly this was happening in the middleware. I've moved this a way up to be more explicit though.

2023-01-23 11:50 UTC, merged

2023-01-23 22:26 UTC, vovakulikov commented on enterprise/internal/insights/httpapi/export.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"CodeInsightsDataExport-%s.zip\"", archive.insightName))
@leonore @coury-clark I tested it locally and I think UX here is a very vary bad when we use unreadable insight ID as a title, I can't find anything after second import already. 

I'm wondering can we still use titles but escape illegal symbols from titles?

2023-01-24 11:03 UTC, leonore commented on enterprise/internal/insights/httpapi/export.go
> +		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=\"CodeInsightsDataExport-%s.zip\"", archive.insightName))
ticket to do this: https://github.com/sourcegraph/sourcegraph/issues/46876