Modification to include BB server description
sourcegraph/sourcegraph pull request #46752
Opened 2023-01-21 01:54 UTC by mibali

fixes #46713 

Previously, we set the description to be the repo name (See [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/bitbucketserver.go?L170)). This made the `repo:has.description` parameter shows repo name instead of the description on Bitbucket server repos.

In this PR, I added a `Description` type for the Repo struct and then modified the `Description` in the `BitbucketServerSource` function to point to the description. This would make the `repo:has.description` parameter to now show the actual description instead of the repo name.

## Test plan
Tested locally.

2023-01-23 06:21 UTC, indradhanush requested changes
Great PR @mibali and thank you so much for the fix! ❤️

The changes look good to me however the tests are failing and would need to be updated. For API tests we use real API response data but save it and reuse it for subsequent test runs. In this case since we're adding a new field that we expect from the API, we should update the tests by adding the `-update` flag to the test command. In this case I can see two relevant tests that need to be updated:

1. `TestClient_LabeledRepos`
1. `TestClient_ProjectRepos`

To update them you will need access to an API token for our test instance which you can find in 1pass. You may run the tests like:

```bash
cd internal/extsvc/bitbucketserver
BITBUCKET_SERVER_TOKEN=<insert-token-here> go test -v -run TestClient_LabeledRepods -update
```

Repeat this for all the other test that need to be updated.

Additionally I would also recommend to add a description to one of the repos in the instance which get fetched from our tests and see if that is reflecting in the newly generated testdata. This should help with validating in our tests that the new changes work.

2023-01-24 12:04 UTC, indradhanush requested changes

2023-01-24 12:04 UTC, indradhanush commented on internal/repos/testdata/vcr/path-pattern.yaml
> +    status: 401 Unauthorized
This doesn't look right to me. These are the files that I updated. Let me take a look.

2023-01-24 12:10 UTC, indradhanush commented on internal/repos/testdata/vcr/path-pattern.yaml
> +    status: 401 Unauthorized
Okay I fixed the token in the test run and I'm seeing the same timeout error as you. I'll investigate this.

2023-01-24 12:14 UTC, mibali commented on internal/repos/testdata/vcr/path-pattern.yaml
> +    status: 401 Unauthorized
Interestingly Buildkite is all green on my end

2023-01-24 12:16 UTC, indradhanush commented on internal/repos/testdata/vcr/path-pattern.yaml
> +    status: 401 Unauthorized
Yep it is, but the generated file is not correct. Take a look at the `status: 401 Unauthorized'. This was likely me having a typo in the token. I've fixed it with the correct token and I am now seeing the timeout locally.

2023-01-24 12:53 UTC, indradhanush commented on internal/repos/bitbucketserver_test.go
> +			ctxWithTimeOut, cancel := context.WithTimeout(context.Background(), 10*time.Second)
```suggestion
			ctxWithTimeOut, cancel := context.WithTimeout(context.Background(), 5*time.Second)
```

2023-01-24 14:41 UTC, indradhanush approved these changes

2023-01-24 15:01 UTC, merged