Executor Job Specific Tokens
sourcegraph/sourcegraph pull request #46792
Opened 2023-01-23 19:01 UTC by Piszmog

## Test plan

TODO

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +	}
I am wondering if we shouldn't try and make the users life as easy as possible so that no additional setup is required (now needs 2 secrets configured for executors already).

Some idea for this:

We generate a secret key the first time it's used and store it in the database
  - Where we could still allow users to provide it through the settings, if they absolutely want to manage the signing key (not sure if that is a use-case some customers would want), but it is not required

---

The setup overhead for executors is already annoying so I'd like to keep the additional things to configure as minimal as possible

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +	expiry := time.Now().Add(time.Minute * time.Duration(conf.SiteConfig().Executors.JobAccessToken.Expiry))
we somehow must ensure this is longer than the executor maximum runtime, which is defined on the executor side, not Sourcegraph side.
I wonder if we need expiry though, given that we already lifecycle-manage execution jobs in the DB and access should be revoked immediately once `MarkComplete/Failed` is called.

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +		AccessToken: conf.SiteConfig().ExecutorsAccessToken,
Would this be plain text in the JWT?

2023-01-24 22:51 UTC, eseliger commented on enterprise/internal/executor/job_test.go
> +		"token": "",
should probably test that it is set to a value correctly, same below

2023-01-24 22:51 UTC, eseliger commented on internal/workerutil/dbworker/store_shim.go
>  }
I don't think I understand why we need this change, in the worker we now have T but here we map it back to the int, and I can't find another user in the middle.

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/executor/internal/apiclient/queue/client.go
> +func (c *Client) MarkComplete(ctx context.Context, job executor.Job) (_ bool, err error) {
Go API surface suggestion:

```suggestion
func (c *Client) MarkComplete(ctx context.Context, id int, token string) (_ bool, err error) {
```

This makes very explicit which fields are required, whereas passing the full executor.Job does not really convey what parts of that big struct are actually required here.

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +		AccessToken: conf.SiteConfig().ExecutorsAccessToken,
just tried, yes it is 
<img width="1209" alt="Screenshot 2023-01-24 at 23 43 43@2x" src="https://user-images.githubusercontent.com/19534377/214437658-10f52d87-705c-4dca-a44a-b19b357c5cb8.png">

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +		AccessToken: conf.SiteConfig().ExecutorsAccessToken,
since this is already signed with the signingKey, why do we need the access token to also be part of this JWT btw?

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/handler/routes.go
> +			"heartbeat": h.handleHeartbeat,
I kinda forgot about this bulk endpoint - do we have plans to migrate this to non-access-token later as well? (no strong opinion, mostly curious)

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		gitRouter.Use(withInternalActor, authExecutorMiddleware(accessToken))
This one should definitely be migrated to the job token pattern, this is the highest-risk endpoint we have, as it allows to fetch _any_ repo, all access. 😬 We would probably want to map the repoName in the path to an ID using a DB read and then check if the job is running against that repo, if not reject (and potentially log).

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		filesRouter.Use(withInternalActor, authExecutorMiddleware(accessToken))
can we make these support job tokens as well? Ie. only get files that are from the spec that's part of the job.

2023-01-24 22:51 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		lsifRouter.Use(withInternalActor, authExecutorMiddleware(accessToken))
@efritz correct me if wrong, but I think this one we should also be able to cover with the job token - at the increased security of never passing the super access token in to any docker container anymore.

2023-01-24 23:08 UTC, efritz commented on enterprise/internal/executor/http.go
> +	// TODO: This field is set to become unneccesary in Sourcegraph 4.4.
Is this version correct?

2023-01-24 23:13 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +	expiry := time.Now().Add(time.Minute * time.Duration(conf.SiteConfig().Executors.JobAccessToken.Expiry))
We can do the same thing on job reset, right? Then that would take care of every expiry scenario.

2023-01-24 23:15 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/handler/routes.go
> +			"heartbeat": h.handleHeartbeat,
Doesn't that mean it's no longer effective?

2023-01-24 23:18 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		gitRouter.Use(withInternalActor, authExecutorMiddleware(accessToken))
Yeah I actually don't care about protecting anything else honestly, it's all job metadata. Having clone access is the real danger we want to reduce the blast radius for.

2023-01-24 23:22 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		lsifRouter.Use(withInternalActor, authExecutorMiddleware(accessToken))
Yes, I believe the upload handler var (on line 48) is unauthed past this middleware, so using a job token here would be fine.

2023-01-24 23:23 UTC, efritz commented on internal/workerutil/dbworker/store_shim.go
>  }
Same. Seems like [this comment](https://github.com/sourcegraph/sourcegraph/pull/46792#discussion_r1086014021) also hinted it should maybe be reverted to support explicit parameters?

2023-01-30 21:19 UTC, Piszmog commented on internal/workerutil/dbworker/store_shim.go
>  }
@efritz @eseliger

So `store_shim.go` is weird. It implements `workerutil.Store` and then passes the data to `store.Store`. I didn't want to mess with `store.Store` since that didn't need to be modified. That is why the functions receive `T` and pass the `id`.

The user in the middle is [Queue HTTP Client](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/cmd/executor/internal/apiclient/queue/client.go).

The Queue HTTP Client implements `workerutil.Store`. So, for it to be able to send the job tokens in the HTTP request means it needs to get the token off the `executor.Job` object some how. But the existing `workerutil.Store`, today, does not give any additional context about the record besides the `id`.

I felt changing the APIs to pass `T` instead allows for more flexibility for these type of use cases.

I could add an additional explicit parameter (e.g. `token string`), but now all implementations of `workerutil.Store` would need to pass a token (which in this case is an executor specific implementation).

For this specific use case, maybe an intermediate layer (like a shim or something) could be used. But I don't really see how that would really help in this specific case since I need context from the record itself.

The only other workaround I could think of is saving the Jobs/tokens off somewhere (like in a map) and looking up the tokens when the mark functions are called. That feels weird, but acceptable.

Thoughts?

2023-01-30 23:08 UTC, eseliger commented on internal/workerutil/dbworker/store_shim.go
>  }
Ah, I get now what you do here. I am personally not opposed to either passing T down here, or having the queue store handle that in some opaque fashion, like storing the tokens in a map (that fwiw does not feel weird to me, as it keeps the abstraction clean).
One thing that I think I would like about the latter is that the interface remains very clean and it's crystal clear what fields are being used, but no strong preference. @efritz do you have thoughts on this?

2023-01-30 23:33 UTC, efritz commented on internal/workerutil/dbworker/store_shim.go
>  }
I also have such a weak preference you should do what requires the least amount of typing. Up to you, @Piszmog !

2023-01-31 17:49 UTC, Piszmog commented on internal/workerutil/dbworker/store_shim.go
>  }
I would prefer to pass `T` in the mark functions of `workerutil.Store`. In my previous experiences, I have found these type of generic/general APIs offer greater flexibility to implementers/users for their specific use cases when parameters are not explicit (less workarounds).

_thought vomit below..._

Maybe `workerutil.Store` is a misleading name? We use it both for DB interactions (`store.Store` - makes sense why it only cares about `id`) and HTTP calls (executor `queue.Client` - where additional context is needed). So it's not really a store and more of a "worker"/"processor"? Or maybe `workerutil.Store` should not be implemented by `queue.Client` but should implement something else/have a different way to process records?

2023-01-31 18:39 UTC, eseliger commented on internal/workerutil/dbworker/store_shim.go
>  }
Passing T totally works for me! 

Yes I also think the term store is heavily overloaded in many cases here.. It is the Interface to talk with the data storage underneath, and the handler is the actual processor. Other terms for that would totally work for me 😅

2023-01-31 19:13 UTC, Piszmog commented on internal/workerutil/dbworker/store_shim.go
>  }
Sounds good. Using another term is maybe something I could look into at a later time

2023-01-31 19:20 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +	}
So I will push an update, but I have updated the job tokens to just be randomized hex tokens (stored in DB). So no longer need a signing key or any site admin configs.

This change will probably address other comments you had (but I'll need to look thru to double-check).

2023-01-31 19:34 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +	expiry := time.Now().Add(time.Minute * time.Duration(conf.SiteConfig().Executors.JobAccessToken.Expiry))
I have updated the tokens to just be random hex tokens. No more expiry and they are deleted once the mark functions are called

2023-01-31 19:36 UTC, Piszmog commented on enterprise/internal/executor/job_test.go
> +		"token": "",
None of the tests have been updated/setup to test everything. That''s come right before this PR is ready. This change was made because I wasn't seeing the token in the traffic between the frontend and backend and I was troubleshooting

2023-01-31 19:46 UTC, Piszmog commented on enterprise/cmd/executor/internal/apiclient/queue/client.go
> +func (c *Client) MarkComplete(ctx context.Context, job executor.Job) (_ bool, err error) {
Marking resolve as this falls into the discussion on the changes to `workerutl.Store`

2023-01-31 19:47 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		filesRouter.Use(withInternalActor, authExecutorMiddleware(accessToken))
Yea, I don't see why not. I'll update them

2023-01-31 19:48 UTC, Piszmog commented on enterprise/internal/executor/http.go
> +	// TODO: This field is set to become unneccesary in Sourcegraph 4.4.
Yes? Was here before I got here 🤷

2023-02-01 22:09 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		gitRouter.Use(withInternalActor, authExecutorMiddleware(accessToken))
I'll update for this

2023-02-01 22:10 UTC, Piszmog commented on lib/api/version_check.go
> +var buildDate = regexp.MustCompile(`\d+_(\d{4}-\d{2}-\d{2})_[a-z0-9]{7,}(_patch)?$`)
Came across this when writing tests. I noticed we were compiling on every invoke. So I just moved this out so we just compile once

2023-02-08 08:40 UTC, sanderginn approved these changes
It all _looks_ good to me, but as I mentioned on Slack, I'm not able to review on a technically deep level yet. Added a few questions that are more for my own enlightenment than anything else 😄

2023-02-08 08:40 UTC, sanderginn commented on enterprise/cmd/frontend/internal/executorqueue/handler/routes.go
> -		registryJob := "sourcegraph-executors-registry"
Are these labels no longer required?

2023-02-08 16:16 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +	types2 "github.com/sourcegraph/sourcegraph/enterprise/internal/executor/types"
Ah, this is from refactoring. I'll fix it. Golang was trying to be helpful

2023-02-08 16:24 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/handler/handler.go
> +		token, err = h.jobTokenStore.Regenerate(ctx, job.ID, queueName)
Exist statement at L168 is when there is an error when checking if the token exist (maybe the DB is down or malformed SQL statement). And L171 is when the token doesn't exist.

So this specific scenario is an edge case that I came across when running my functional tests.

I would be running a batch change locally, then I noticed I did something wrong. So I would kill my whole instance while it was in the middle of processing a Job.

When I would start my instance back up, executors would try to dequeue the same Job that it was previously in the middle of processing. But when the code would go to create a token for the Job, the token would already exist. So I need to "regenerate" the token to be used in the new HTTP requests.

As I write this, I can probably add a check if the create error is because the token exists or something else. If the error is because it exists, then go down the regen logic (I then can remove the exists logic)

2023-02-08 16:26 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/handler/routes.go
> -		registryJob := "sourcegraph-executors-registry"
This go moved to `enterprise/cmd/frontend/internal/executorqueue/handler/handler.go`. So we still have all of these 😄 .

I move it to put it close where it is being used. I also moved the Interface implementation into `handler.go` as that made more sense to me. It was confusing that the `handler` was in `handler.go` but the interface implementation functions were in `routes.go`. So I moved all things handler to `handler.go`

2023-02-08 16:27 UTC, Piszmog commented on enterprise/cmd/executor/internal/worker/workspace/clone.go
> +		job.ID,
Makes sense to me

2023-02-09 10:31 UTC, evict requested changes

2023-02-09 10:31 UTC, evict commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		if authToken == conf.SiteConfig().ExecutorsAccessToken {
Can we do a constant time check here? crypto/subtle has a method for that: https://pkg.go.dev/crypto/subtle#ConstantTimeCompare.

It would be something like:

```
eq := subtle.ConstantTimeCompare([]byte(authToken), []byte(conf.SiteConfig().ExecutorsAccessToken))

[check eq]
```

2023-02-09 10:31 UTC, evict commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return false
Can we do a constant time check here as well?

2023-02-09 10:35 UTC, evict commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return false
I also noticed there is more in `validateExecutorToken`, it would be great to have it there as well. We only have to perform the check on the token once. So there might be a better place to do it.

2023-02-09 16:29 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		if authToken == conf.SiteConfig().ExecutorsAccessToken {
TIL about `subtle.ConstantTimeCompare`. Thank you!

2023-02-09 17:33 UTC, evict commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return false
Ah, only secret tokens. I think the jobID is not secret right? Sorry for the confusion.

2023-02-09 17:40 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		return false
sounds good. I'll only use the `ConstantTimeCompare` for secret stuff (in this case, only the general access token)

2023-02-09 17:49 UTC, evict approved these changes

2023-02-13 12:38 UTC, eseliger approved these changes
🔥

2023-02-13 12:38 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		// TODO: this is to make some integration tests happy (dev/authtest/code_intel_test.go). Add a meaningful route here.
@efritz maybe you have an idea how to solve this :)

2023-02-13 12:38 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		gitRouter.Use(withInternalActor, jobAuthMiddleware(logger, routeGit, jobTokenStore, executorStore))
should we use the user actor instead, taken from the DB Job record? That would help with sub repo permissions in the future, too (perforce).

2023-02-13 12:38 UTC, eseliger commented on migrations/frontend/1674754280_executor_job_tokens/up.sql
> +    id           SERIAL PRIMARY KEY,
I wonder if we also want to associate a job token with the user - at least for the batches queue. That way we could impersonate as them when doing pulls etc.

2023-02-13 13:31 UTC, efritz commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		// TODO: this is to make some integration tests happy (dev/authtest/code_intel_test.go). Add a meaningful route here.
Seems like the authtest is now broken since it expects all routes to accept auth uniformly whereas that's no longer true?

2023-02-13 16:35 UTC, Piszmog commented on migrations/frontend/1674754280_executor_job_tokens/up.sql
> +    repo         TEXT                                   NOT NULL,
I would prefer to use repo id, but I would need to jump thru more hoops to validate it.

The git clone request only has the repo name. So I would have to take that repo name and look up the record in the DB to get the ID. Then with the ID, I can compare against the ID in the Job Token.

I felt another DB call wasn't worth it since I can just compare the repo name.

2023-02-13 16:43 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		// TODO: this is to make some integration tests happy (dev/authtest/code_intel_test.go). Add a meaningful route here.
Kinda. It authtest was working accidentally. It was checking auth by hitting a nonexistent endpoint which happened to work since the middleware wrapped the whole thing.

If a test to authtest was added to check for successful auth, the test would fail with a 404 since `/.executors/` does not exist.

2023-02-13 16:44 UTC, eseliger commented on migrations/frontend/1674754280_executor_job_tokens/up.sql
> +    repo         TEXT                                   NOT NULL,
if you want, potentially a subquery could work `where repo_id = (select id from repo where name = %s)`

2023-02-13 16:47 UTC, Piszmog commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		gitRouter.Use(withInternalActor, jobAuthMiddleware(logger, routeGit, jobTokenStore, executorStore))
This comment plus the "associate job token with the user". How do you feel on making this a separate story? I feel that this feature has quite a bit of changes, I don't want to increase the changes more.

Also, I'm not 100% sure what you mean on 
> should we use the user actor instead, taken from the DB Job record

Could you elaborate more on this? (I can add those details in the new story if that is ok)

2023-02-13 16:49 UTC, eseliger commented on enterprise/cmd/frontend/internal/executorqueue/queuehandler.go
> +		gitRouter.Use(withInternalActor, jobAuthMiddleware(logger, routeGit, jobTokenStore, executorStore))
absolutely, doesn't have to be in this PR! 

What I meant is instead of using an internal actor is using a user actor, which would then honor the users permissions for things like sub repo permissions and such. So we somehow associate job -> initiating user and then do `ctx := actor.WithActor(ctx, actor.ForUser(job.UserID))`.

2023-02-13 19:08 UTC, Piszmog commented on migrations/frontend/1674754280_executor_job_tokens/up.sql
> +    repo         TEXT                                   NOT NULL,
alright, so I made the changes to use repo ID. The following are the changes

#### Insert

Updated the query on insert to lookup the repo ID based on the name and insert that. This is because the `Job` in the `Dequeue` function only has the repository name. So in order to persist the repo ID, I need the following query.

```sql
INSERT INTO executor_job_tokens (value_sha256, job_id, queue, repo_id)
SELECT %s, %s, %s, id from repo r where r.name = %s;
```

#### Select

Updated both the selects to also return the repo name. I use the repo name in the comparison when checking the token.

Example,

```sql
SELECT id, value_sha256, job_id, queue, repo_id, (select name from repo where id = t.repo_id) as repo
FROM executor_job_tokens t
WHERE job_id = %s AND queue = %s
```

2023-02-15 20:12 UTC, Piszmog commented
I plan on merging after cut

2023-02-28 18:40 UTC, merged