Add new src_permissions table to unify repository permissions
sourcegraph/sourcegraph pull request #47086
Opened 2023-01-30 10:06 UTC by kopancek

This PR adds a new table to hold the source code permission data. Nothing else, to keep it small and simple.

## Test plan

Manually tested that the migration queries run successfully. Tested with `sg migration` locally.

2023-01-30 10:37 UTC, sashaostrikov approved these changes
LGTM! Left a couple of comments.

2023-01-30 10:37 UTC, sashaostrikov commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +BEGIN;
AFAIR, begin and end are implicitly added during migration queries.

2023-01-30 10:37 UTC, sashaostrikov commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +    user_id INT NULL REFERENCES public.users(id) ON DELETE CASCADE,
nit: `public` can be dropped

2023-01-31 08:04 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +BEGIN;
TIL

2023-01-31 08:58 UTC, pjlast commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +    user_id INT NULL REFERENCES users(id) ON DELETE CASCADE,
Curious when `user_id` will ever be `NULL` ?

2023-01-31 09:00 UTC, sashaostrikov commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE TABLE IF NOT EXISTS src_permissions(
after getting an email from GH about updates in this PR I've got second thoughts about the name of the table 😁

feels like it is an important table, should we try to come up with a more explicit name? I only had `permissions` or `unified_permissions` in mind, but I can see that `permissions` is taken (however it is not used, worth double-checking whether it will be and should it be named like this in the first place).

engaging @mrnugget for a naming brainstorm

2023-01-31 09:31 UTC, thenamankumar commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
created_at and updated_at will not be sufficient to diff between complete & incremental syncs. How are we planning to compute `last_complete_sync_at` and `last_incremental_sync_at`? 

Add columns on users, repos table? Or compute it based on the new sync jobs table?

Perms scheduling highly depends on the current `synced_at` column on user and repo permissions tables.

2023-01-31 09:45 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +    user_id INT NULL REFERENCES users(id) ON DELETE CASCADE,
Planning to model unrestricted repositories that way, see the edge cases section in [The Doc](https://docs.google.com/document/d/1ufdLQc8DKHC1gWBpbkf2KfARzK6KSEsMFHcR9bwDNtQ)

2023-01-31 09:46 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE TABLE IF NOT EXISTS src_permissions(
@BolajiOlajide took that name for internal RBAC work, so we cannot use that. `unified_permissions` sounds like a wash, since these are only permissions for the source code.

2023-01-31 09:52 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
With the new data model, we can distinguish between a complete and incremental sync by looking at the timestamps. E.g. `SELECT updated_at FROM src_permissions WHERE user_id = 1 AND ext_account_id = 2;` and check if all the `updated_at` timestamps are the same. But this is not going to work properly, since repo sync will interfere and update the `updated_at` column as well. Or explicit permissions API call will update the table with new rows for the same user, which will lead to different updated_at values.

We also plan to change the user-based syncing to sync per external account. So you might end up with having a different timestamp for the same user, but different external accounts (the difference here being small, but still there).

Even today, it's kind of broken, since you can say a user was completely synced, but you say the same for a repo. But in reality, we do a sync per external account for the user. So what if 1 external account succeeds and another one fails. So how do you say it was a complete sync? For which entity? Which one do you pick?

I think we should revisit these metrics once the work is complete. What we want to know is:
1. Are the permissions fresh?
2. Did the job succeed?

We can get 1 by looking at the timestamps. We can get 2 by looking at DB backed perms syncer data.

2023-01-31 10:07 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE TABLE IF NOT EXISTS src_permissions(
Other ideas I had:
- `code_host_permissions`
- `source_code_permissions`
- `source_permissions`
- `code_permissions`
- `unified_repo_permissions`

2023-01-31 10:15 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE TABLE IF NOT EXISTS src_permissions(
Suggestions and any naming feedback welcome though 👍

2023-01-31 10:48 UTC, mrnugget commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE TABLE IF NOT EXISTS src_permissions(
why not `repo_permissions`? It's what it is, right? And that's what we call it?

2023-01-31 10:51 UTC, mrnugget commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE TABLE IF NOT EXISTS src_permissions(
Ah, because that's already taken. How about `user_repo_permissions` then? Makes it clear that it's a mapping between the two entities.

2023-01-31 10:55 UTC, mrnugget requested changes
Agree with @sashaostrikov: I think we should change the name. `user_repo_permissions` is my favorite because it's explicit and everybody knows what's in it just by reading the name.

I also think you need `sg generate` before you can merge this.

2023-01-31 10:55 UTC, mrnugget commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE INDEX IF NOT EXISTS src_permissions_source_idx ON src_permissions(source);
Please add a newline at the end of the file (by configuring your editor to do that and saving the file) 🙂

2023-01-31 10:55 UTC, mrnugget commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +    ext_account_id INT NULL REFERENCES user_external_accounts(id) ON DELETE CASCADE,
```suggestion
    user_external_account_id INT NULL REFERENCES user_external_accounts(id) ON DELETE CASCADE,
```

Let's be explicit about references in the names. `<table_name in singular>_id` is the standard in our codebase, I think.

2023-01-31 10:55 UTC, mrnugget commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE INDEX IF NOT EXISTS src_permissions_repo_id_idx ON src_permissions(repo_id);
I think we might also need a combined index, no? `where user_id = x and repo_id = y`?

2023-01-31 11:42 UTC, pjlast commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
You can also redefine what a "full sync" and "incremental sync" means.

The last full sync will be the time stamp of the oldest permission the user has (that has an `external_account_id`, to distinguish from explicit perms).

The last incremental sync will be the time stamp of the youngest permission the user has.

2023-01-31 12:09 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE INDEX IF NOT EXISTS src_permissions_repo_id_idx ON src_permissions(repo_id);
I'm not completely sure right now. But we can always add an index later on during the development stage.

2023-01-31 12:10 UTC, kopancek commented on migrations/frontend/1674814035_add_unified_source_perms_table/up.sql
> +CREATE INDEX IF NOT EXISTS src_permissions_source_idx ON src_permissions(source);
I have my editor configured for that, but for some reason, it completely mangles up other formatting if I let it do auto-format on save 😢 Maybe it's time for emacs finally 😛

2023-02-02 11:26 UTC, mrnugget approved these changes
Let's gooo

2023-02-02 11:26 UTC, mrnugget commented on migrations/frontend/1674814035_add_unified_source_perms_table/metadata.yaml
> +name: add_unified_source_perms_table
Nitpick: 
```suggestion
name: add_user_repo_permissions_table_for_unified_permissions
```

2023-02-02 11:39 UTC, merged