Fixed a bug where the `repo:has.description()` parameter now shows description on Bitbucket server repos, previously it shows the repo name  [#46752](https://github.com/sourcegraph/sourcegraph/pull/46752/files)
sourcegraph/sourcegraph pull request #47094
Opened 2023-01-30 11:57 UTC by mibali

## Test plan
Tested locally

2023-01-30 12:29 UTC, indradhanush requested changes
Looks good. Requesting changes for the PR title because that goes into the commit message when being merged.

The PR title should reflect what the change is in a short sentence (60-80 chars is a good limit to aim for although it's not super strict).

So in this case something like:

CHANGELOG: Add note on bug fix for bitbucketserver repo description

2023-01-30 12:29 UTC, indradhanush commented on CHANGELOG.md
> +- Fixed a bug where the `repo:has.description()` parameter now shows description on Bitbucket server repos, previously it shows the repo name [#46752](https://github.com/sourcegraph/sourcegraph/pull/
```suggestion
- Fixed a bug where the `repo:has.description()` parameter now shows description on Bitbucket server repos, previously it shows the repo name [#46752](https://github.com/sourcegraph/sourcegraph/pull/46752)
```

2023-01-30 20:26 UTC, BolajiOlajide approved these changes

2023-01-31 05:03 UTC, indradhanush approved these changes
Left a suggestion. Approved to unblock.

2023-01-31 05:03 UTC, indradhanush commented on CHANGELOG.md
> +- Fixed a bug where the `repo:has.description()` parameter now shows description on Bitbucket server repos, previously it shows the repo name [#46752](https://github.com/sourcegraph/sourcegraph/pull/
```suggestion
- Fixed a bug where the `repo:has.description()` parameter now correctly shows description of a repository synced from a Bitbucket server code host connection, while previously it used to show the repository name instead [#46752](https://github.com/sourcegraph/sourcegraph/pull/46752)
```

2023-01-31 09:50 UTC, merged