First version of writing perms to new table
sourcegraph/sourcegraph pull request #47159
Opened 2023-01-31 08:20 UTC by kopancek

## Test plan

Integration test added

2023-02-09 11:49 UTC, pjlast requested changes
Feel like there are some traps when it comes to using the database functions that can be avoided

2023-02-09 11:49 UTC, pjlast commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		IDs:    map[int32]struct{}{},
I don't think this is used anywhere

2023-02-09 11:49 UTC, pjlast commented on enterprise/internal/database/perms_store.go
> +
```suggestion
func (s *permsStore) FetchReposByExternalAccount(ctx context.Context, accountID int32) (ids []api.RepoID, err error) {
	const format = `
SELECT repo_id
FROM user_repo_permissions
WHERE user_external_account_id = %s;
`

	q := sqlf.Sprintf(format, accountID)

	ctx, save := s.observe(ctx, "FetchReposByExternalAccount", "")
	defer func() {
		save(&err)
	}()

	repos, err := basestore.ScanInt32s(s.Query(ctx, q))
	if err != nil {
		return nil, errors.Wrap(err, "scanning repo ids")
	}

	ids = make([]api.RepoID, 0, len(repos))
	for _, id := range repos {
		ids = append(ids, api.RepoID(id))
	}

	return ids, nil
}

```

We don't need a user ID, since an external account should map to a single user ID.

2023-02-09 11:49 UTC, pjlast commented on enterprise/internal/database/perms_store.go
> +	}
This means that if an external account loses access to all repositories, we won't delete them from the table

2023-02-09 11:49 UTC, pjlast commented on enterprise/internal/database/perms_store.go
> +func (s *permsStore) upsertUserRepoPermissions(ctx context.Context, permissions []authz.Permission, source string) (t []time.Time, err error) {
How confident are we in the database returning the same time for all rows here? 🙈 but regardless, unless we have a reason to want an array of times, I'd rather just return the single updated at time that applies to all rows, which might mean calculating `time.Now()` outside of the SQL statement and passing it in.

2023-02-09 11:49 UTC, pjlast commented on enterprise/internal/database/perms_store.go
> +func (s *permsStore) SetUserRepoPermissions(ctx context.Context, p []authz.Permission, entity authz.PermissionEntity, source string) (err error) {
I'm not sure if I like the `PermissionEntity` API thing here, and I'd rather have these as separate functions (`SetUserPermissions` and `SetRepoPermissions` with appropriate params).

Having to keep track of what was passed into the Entity, and then the Permissions possibly containing different values, feels like a mine field. I'd rather have
`SetUserPermissions(ctx, userID, extAccountID, repoIDs, source)`
and
`SetRepoPermissions(ctx, repoID, userWithExtAcctIDs, source)` (where `usersWithExtAcctIDs` is an array of structs or something)

2023-02-10 07:34 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +func (s *permsStore) upsertUserRepoPermissions(ctx context.Context, permissions []authz.Permission, source string) (t []time.Time, err error) {
I'm not confident, as I did not try it with thousands of rows, but does it really matter that much? We will end up with different timestamps on the rows anyway, since both user based sync and repo based sync update the same rows, but at different times.

2023-02-10 07:40 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +func (s *permsStore) SetUserRepoPermissions(ctx context.Context, p []authz.Permission, entity authz.PermissionEntity, source string) (err error) {
I think it still makes sense to keep the same array of Permissions[] as a representation of what we are going to write to the table. It makes my thinking easier when I try to use the method.

But I agree the `PermissionEntity` thing is a bit clumsy and I don't like it myself that much. This was just a first iteration to make it work, so will try to refactor that part to be easier to use and understand.

2023-02-10 07:40 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	}
Good point, we need to still delete. Thanks for figuring this out, should also add a test for that.

2023-02-10 18:28 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	}
Check out the definition of `basestore.ScanInt32s`: it's built using `basestore.NewSliceScanner(ScanAny[int32])`. That means we could add a `ScanRepoIDs = basestore.NewSliceScanner(ScanAny[api.RepoID])` to the list :)

(Drive by comment, I'll do a more thorough review on Monday)

2023-02-13 12:33 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	}
Thanks for the suggestion! Didn't notice that 👍 

I didn't want to tie the `basestore` with `api.RepoID` structure (as it's just an alias really), so I added it as a var to the perms_store instead.

2023-02-13 12:37 UTC, mrnugget reviewed
(Submitting first batch of comments since I don't know whether I'll finish rest of files before next meeting)

2023-02-13 12:37 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			return results, errors.Wrap(err, "list external repositories by exact matching")
```suggestion
			return results, errors.Wrap(err, "list private repositories by exact matching")
```

No?

2023-02-13 12:37 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		if len(results.repoPerms[acct.ID]) == 0 {
I think you might want to do a nil-check here for `results.repoPerms[acct.ID]`, right?

2023-02-13 12:37 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +	perms := []authz.Permission{}
```suggestion
	perms := make([]authz.Permission{}, 0, len(repoIDs))
```

2023-02-13 12:37 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		if UserRepoPermsEnabled(ctx, s.db) {
Shouldn't we pull the check out of the loop?

2023-02-13 12:37 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +func UserRepoPermsEnabled(ctx context.Context, db database.DB) bool {
I would add the `Unified` to the name. This one was a bit confusing to read in the rest of the perms syncer code: "UserRepoPermsEnabled? Of course they are, we're in the perms syncer after all, right?"

2023-02-13 12:37 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	}
This feels like it could backfire (what about timing inconsistencies?) Can't you instead make `upsertUserRepoPermissions` return a slice of IDs (using `RETURNING id` in the query) and then pass those in here to do a `delete from ... where id not in (... ids...)`? That seems more solid, since we're not interested in the timestamps but in the actual set of IDs, right?

2023-02-13 12:37 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	if err = rows.Scan(pq.Array(&ids)); err != nil {
All of this can be done with the `basestore` scanners we have (or a new one you can create with `basestore.NewSliceScanner`)

2023-02-13 12:37 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +func (s *permsStore) upsertUserRepoPermissions(ctx context.Context, permissions []authz.Permission, source string) (t []time.Time, err error) {
See comment above. I think we should use IDs

2023-02-13 12:37 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	return basestore.ScanTimes(rows, err)
```suggestion
	return basestore.ScanTimes(s.Query(ctx, q))
```

2023-02-13 12:37 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	}
Yeah, good call! Had that same yucky feeling ("hmm, maybe basestore shouldn't care about `api`")

2023-02-13 12:58 UTC, mrnugget reviewed
Looks good to me, but only "Comment" (instead of Approve) since I defer to others for final approval, but left comments for suggestions and want to take final look after you refactored code.

2023-02-13 12:58 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	where := sqlf.Sprintf("FALSE")
What do you think about doing a `if`/`else if`/`else` and return an error in the `else` part if neither `UserID` nor `RepoID` was set? I worry that with this someone uses the API wrong and always gets no results, but doesn't know why?

2023-02-13 12:58 UTC, mrnugget commented on enterprise/internal/database/perms_store_test.go
> +		}
I think I'd pull that out and create a little `scanPermissions` helper method. See last example in the function here (the one to scan `[]horse`): https://docs.sourcegraph.com/dev/background-information/basestore#using-basestore-helpers-for-scanning

Why? Because this mixes chores (reading & scanning) with test assertions and it's really easy to miss something and hard to tell what's tested. For example: if this returns an error here, then we don't call `rows.Close()` below, which clogs a database connection. Not a huge problem, but also something we can easily avoid.

2023-02-13 12:58 UTC, mrnugget commented on enterprise/internal/database/perms_store_test.go
> +		}
Come to think of it: I also personally prefer a `cmp.Diff` over two slices vs. comparing each element bit by bit, because then the test output tells me what was missing and what was just in wrong order, etc.

2023-02-13 12:58 UTC, mrnugget commented on enterprise/internal/database/perms_store_test.go
> +	if t.Failed() {
I don't think we need this, since you use `t.Fatal` in your test and that aborts the whole test, vs just recording an error (which is what `t.Error` does).

I also think these two helpers could use `t.Helper()` :)

2023-02-13 12:58 UTC, mrnugget commented on enterprise/internal/database/integration_test.go
> +		{"SetUserRepoPermissions", testPermsStore_SetUserRepoPermissions(db)},
For the record: I do think that with our current `dbtest` setup we might not need this whole integration test setup anymore and can just define these tests separately with `Test...` Doesn't have to be in this PR or even a follow-up soon, just sharing my thinking.

2023-02-13 12:58 UTC, mrnugget commented on enterprise/internal/database/perms_store_test.go
> +}
cool tests!

2023-02-13 13:41 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	}
I was thinking about this exact implementation, but I am not sure about the parameter limit for the ids part. What if we have 40k rows that were upserted? What if we have 100k? (e.g. a repo that is accessible by 100k users)? Would it still work performantly enough?

2023-02-13 13:46 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +				if len(currentRepos) == 0 {
It should not matter, because in that case there should be no data in the old table either.

2023-02-13 13:57 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	}
Good point. What you could also do is to create a unique ID for the sync and then write that to all the rows. All rows that don't have the unique ID could then be deleted.

2023-02-13 16:06 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +				if len(currentRepos) == 0 {
Yeah, that's what I mean: should we avoid that call by, say, returning a boolean from the other call? Or not worth it?

2023-02-13 16:07 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		if len(results.repoPerms[acct.ID]) == 0 {
Makes sense! I somehow assumed that `nil` would break `len(nil)` but your spelling-it-out here makes me feel dumb for even thinking that 😉

2023-02-13 16:17 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	}
This is very similar to what @pjlast was suggesting - supply the date from the Go runtime instead of letting Postgres set the updated_at with `now()`. In that case, I can delete all the rows that do not have the exact same `updated_at`. WDYT?

2023-02-13 16:23 UTC, kopancek commented on enterprise/internal/database/perms_store_test.go
> +		}
Yeah, I implemented it this way, because I am iterating through each row. Will refactor with scanner utility, which should output a slice instead 👍

2023-02-13 16:23 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +				if len(currentRepos) == 0 {
The thing is, there is not really a boolean we can return. If the external account is synced and does not have any repositories access, there will be no rows in the `user_repo_permissions` table. The only way to tell would be to check if there was also a job run recently for the same user account.

But I don't think it's worth it at this point. This whole chunk of code is only invoked if there is an error with syncing. Which hopefully does not happen too often in most cases.

2023-02-13 16:26 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	}
Yeah, that would also work, _if_ we use a transaction and make sure we don't run into other writes for the table.

2023-02-13 16:47 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	if err = rows.Scan(pq.Array(&ids)); err != nil {
I'm going to use those in the methods that I touched. Trying to keep the scope of the PR small, so will not try to refactor everything at this point.

2023-02-13 16:51 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +		if len(results.repoPerms[acct.ID]) == 0 {
No worries, I actually double checked that same thing myself in go playground, before I tried to make those claims.

2023-02-13 16:52 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	}
OK, will rewrite to do that instead. We *DO* use transaction here already.

2023-02-13 17:07 UTC, kopancek commented on enterprise/internal/database/integration_test.go
> +		{"SetUserRepoPermissions", testPermsStore_SetUserRepoPermissions(db)},
I wanted to ask if you might have any context on why it was done this way. The only reason that came to my mind would be performance - we do not need to spin up a test DB for each test, but instead share the same DB across them. But yes, would love to be able to just write plain tests instead, so adding it as a followup might be a good idea.

2023-02-13 17:07 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	where := sqlf.Sprintf("FALSE")
Sounds like a good idea 👍

2023-02-14 12:47 UTC, mrnugget commented on enterprise/internal/database/integration_test.go
> +		{"SetUserRepoPermissions", testPermsStore_SetUserRepoPermissions(db)},
Yeah, I think it was back then `dbtest.new` was much slower. I think the performance has improved now so using separate functions is okay.

2023-02-14 15:42 UTC, kopancek commented on enterprise/internal/database/perms_store_test.go
> +}
thanks, I tried.. They were super helpful when refactoring based on feedback though. Maybe I should start with TDD :)

2023-02-14 15:42 UTC, kopancek commented on enterprise/internal/database/perms_store_test.go
> +	if t.Failed() {
Refactored now.

2023-02-14 15:42 UTC, kopancek commented on enterprise/internal/database/perms_store_test.go
> +		}
Refactored now.

2023-02-14 15:43 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	where := sqlf.Sprintf("FALSE")
Changed accordingly

2023-02-14 15:43 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	if err = rows.Scan(pq.Array(&ids)); err != nil {
Code has been changed accordingly.

2023-02-15 08:45 UTC, pjlast commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +				if len(currentRepos) == 0 {
I'm curious about the scenario we're trying to mitigate by falling back to the old table? Is it only for the first time we're switching to the new table?

2023-02-15 08:55 UTC, pjlast approved these changes
Don't have any further comments 😄 

🚢 🤡

2023-02-15 09:10 UTC, kopancek commented
I'll postpone merging this PR until release branch is cut. Since everything is behind a feature flag, it does not make sense to force push on this - no customer will use the feature and I'd rather not break their perms syncing.

2023-02-15 09:18 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +				if len(currentRepos) == 0 {
Same question while reading through this, but in a different way:

Instead of "check new table, fall back to old table if there are no results", shouldn't we use the feature flag and only if it's on check the name table?

Because what happens in this scenario:

1. User turns feature flag on
2. We write data to new table
3. User turns feature flag off
4. We stop writing data to new table
5. Data in new table becomes outdated
6. This code here now reads outdated data and doesn't fall back to old table

2023-02-15 09:29 UTC, mrnugget approved these changes

2023-02-15 09:29 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			err = s.saveUserPermsForAccount(ctx, userID, acctID, repoIDs)
This uses a lock under the hood, but there's potentially a race condition when between two calls to `saveUserPermsForAccount` someone else can get the lock. Should we use the lock around this while loop instead?

2023-02-15 09:29 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	SetUserRepoPermissions(ctx context.Context, p []authz.Permission, entity authz.PermissionEntity, source string) error
Does this still need to be part of this interface if it's only used under the hood? A private `setUserRepoPermissions` can still be used in tests and you can still keep the docstring, but I think it's better to remove it from this interface, if `SetUserExternalAccountPerms` and `SetRepoPerms` are the preferred methods.

2023-02-15 09:29 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +	return repos, nil
```suggestion
	return scanRepoIDs(s.Query(ctx, q))
```

👌

2023-02-15 09:29 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +var scanBindIDs = basestore.NewMapScanner(func(s dbutil.Scanner) (bindID string, id int64, _ error) {
Nice!!

2023-02-15 09:29 UTC, mrnugget commented on enterprise/internal/database/perms_store.go
> +})
Okay, you're the `basestore.NewMapScanner` pro now. Additions here welcome 😎 https://docs.sourcegraph.com/dev/background-information/basestore#using-basestore-helpers-for-scanning

2023-02-15 09:29 UTC, mrnugget commented on enterprise/internal/database/perms_store_test.go
> +		return errors.New("no permissions to setup foreign keys for")
Nit: since you pass in `t *testing.T` and it's a `t.Helper()` you can also use `t.Fatalf` in here so you don't need to return `err`.

2023-02-15 09:29 UTC, mrnugget commented on enterprise/internal/database/perms_store_test.go
> +			},
```suggestion
		{
			name: "add",
			permissions: []authz.Permission{
				{UserID: 1, ExternalAccountID: 1, RepoID: 1},
				{UserID: 1, ExternalAccountID: 1, RepoID: 2},
				{UserID: 1, ExternalAccountID: 1, RepoID: 3},
			},
			expectedPermissions: []authz.Permission{
				{UserID: 1, ExternalAccountID: 1, RepoID: 1},
				{UserID: 1, ExternalAccountID: 1, RepoID: 2},
				{UserID: 1, ExternalAccountID: 1, RepoID: 3},
			},
			entity: authz.PermissionEntity{UserID: 1, ExternalAccountID: 1},
		},
```

Nitpick: I do think these still fit on one line and are actually more readable on one line :)

2023-02-15 09:36 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			err = s.saveUserPermsForAccount(ctx, userID, acctID, repoIDs)
I was originally trying to keep the lock in this function, but could not come up with a good way how to do a lock for both writing to the new table and the old table and keep the defer to unlock. Need to think about it again I guess 🤔

2023-02-15 09:37 UTC, kopancek commented on enterprise/internal/database/perms_store.go
> +	SetUserRepoPermissions(ctx context.Context, p []authz.Permission, entity authz.PermissionEntity, source string) error
Not really. I kept it in the interface because if we change the explicit permissions API to write to this table as well, we will use this function. But since that's not done yet, I can make it private for now 👍

2023-02-15 09:38 UTC, kopancek commented on enterprise/internal/database/perms_store_test.go
> +			},
Agreed. It was my editor that separated it into multiple lines. Will try to squeeze it to one-liners now.

2023-02-15 09:41 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			err = s.saveUserPermsForAccount(ctx, userID, acctID, repoIDs)
One "hack" to do this: use an anonymous function

```go
	// Using anonymous function here so we can use a lock for the function scope and use `defer`
	err = func() error {
		// NOTE: Please read the docstring of permsUpdateLock field for reasoning of the lock.
		if unifiedEnabled {
			s.permsUpdateLock.Lock()
			defer s.permsUpdateLock.Unlock()
		}
		for acctID, repoIDs := range results.repoPerms {
			if unifiedEnabled {
				err = s.saveUserPermsForAccount(ctx, userID, acctID, repoIDs)
				if err != nil {
					return errors.Wrapf(err, "set user repo permissions for user %q (id: %d, external_account_id: %d)", user.Username, user.ID, acctID)
				}
			}

			for _, repoID := range repoIDs {
				p.IDs[repoID] = struct{}{}
			}
		}
		return nil
	}()
	if err != nil {
		return result, providerStates, err
	}
```

2023-02-15 09:41 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			err = s.saveUserPermsForAccount(ctx, userID, acctID, repoIDs)
(Then you also ahve to remove the lock from `s.saveUserPermsForAccount`, so you don't run into a deadlock)

2023-02-16 07:36 UTC, kopancek commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			err = s.saveUserPermsForAccount(ctx, userID, acctID, repoIDs)
I thought about this again, and I actually think the current way is more idiomatic. To explain, on each call to `saveUserPermsForAccount` we actually make a write to the database. Yes, it can be the case, that we will need to wait for the lock in the loop, but that should be OK from my perspective. 

The only race condition that I can think about is, that we have a repo sync, that happens at the same time as user sync. And the repo sync gets different data (more fresh data), because the user account was just updated in that same millisecond. 

E.g. imagine a situation, when user based sync gets data user `bob` can access repo `sourcegraph`. Repo sync gets data 1 microsecond later which says repo `sourcegraph` is only accessible to `alice`, but not `bob`. Depending on how fast they go to the lock, repo sync might write first, although the data in user sync is not true anymore. 

**BUT** and this is a big one - we have that problem today as well - we first fetch the data and lock only before the write. So to fix this properly, we would need to lock before fetching the data, which would lock the database for a much longer time. We do rely on eventual consistency anyway, so I do not think this is a huge problem to be honest.  Sometimes the sync interval might just be unlucky.

Can you think about any other scenario that might require us to lock only once?

2023-02-16 09:42 UTC, mrnugget commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +			err = s.saveUserPermsForAccount(ctx, userID, acctID, repoIDs)
Summary of our Slack conversation:

We both think the lock is not the most useful. We now have different rows we read/write, one per user/repo. We do an `INSERT ... ON CONFLICT UPDATE`, which means the database ensures consistency here and that the last write wins. We both think that makes sense (i.e. you have two sync jobs starting one after the other, 2nd one has more info than 1st one, the last write will win. No lock helps here.)

I also don't understand why we needed that lock in the first place. Maybe there's some in-memory state it's also protecting?

2023-02-17 10:10 UTC, thenamankumar commented on enterprise/cmd/repo-updater/internal/authz/perms_syncer.go
> +	repoPerms map[int32][]int32
Nice, this should help with separate syncing of perms for different external account.

2023-02-20 11:19 UTC, merged