Client routing top level paper cuts
sourcegraph/sourcegraph pull request #47502
Opened 2023-02-09 19:29 UTC by vovakulikov

This PR does three things
- Removes top level route from the SourcegraphApp.tsx @valerybugakov 
- Fixes flex-start/start warning cc @umpox 
- Make home page built-in/not lazy loaded (in order to avoid loading spinner flashes) 

## Test plan
- Make sure that top routing is fine (search, search result page work properly)

2023-02-09 20:19 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 9.63% (+270.44 kb) 🔺 | -0.01% (-1.66 kb) | -2.29% (-272.10 kb) 🔽 | -2.31% (-17) 🔽 |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vk/clean-up-top-level-routing/compare-report.html;tab=live_object) for a full comparison between the commits f5926d5 and c173421 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-02-09 23:28 UTC, vovakulikov commented
Interesting thing, how come just Home page where we load code mirror asynchronously can add 270kb 🤔

2023-02-10 05:51 UTC, valerybugakov approved these changes
Nice, thanks, Vova!

2023-02-10 08:57 UTC, umpox approved these changes

2023-02-13 12:45 UTC, philipp-spiess requested changes
Hate to be this person but we really shouldn't ship a 10% increase in bundle size. Let's revert the part where we eager load the home page.

2023-02-13 12:45 UTC, philipp-spiess commented on client/web/src/search/SearchPageWrapper.tsx
> -const SearchPage = lazyComponent(() => import('./home/SearchPage'), 'SearchPage')
Why did you change this? We want every route to be lazy-loaded, no?

2023-02-13 13:56 UTC, vovakulikov commented on client/web/src/search/SearchPageWrapper.tsx
> -const SearchPage = lazyComponent(() => import('./home/SearchPage'), 'SearchPage')
@philipp-spiess I think that we should have some shell anyway and a home page; the main root page should be part of this, shall. Imagine how weird it's when you load the app, and then you load something else again, I mean, ideally, it should be addressed with proper SSR. Still, we don't have it, so I think having HomePage is a good candidate to have it, especially when it's just one input page without a big heavy UI. 

But I 100% agree that a 10% increase looks scary, and I suggest investigating in this direction more. I'm curious why this is happening if we lazy load code mirror input 🤔

2023-09-11 15:08 UTC, closed without merging