App and Setup experience: Other external service defines root directories for git discovery
sourcegraph/sourcegraph pull request #47779
Opened 2023-02-17 03:26 UTC by gl-srgr

to be merged into feature branch of PR https://github.com/sourcegraph/sourcegraph/pull/47673/

In PR 47673 serve-git at startup identifies a relevant root directory to be walked for local repo sync'ing. The external service configuration created at startup will define the url and not much else. That ext svc configuration does not define the directories, so we can't make updates to which directories are relevant; that is, it's fixed to what's defined by `SRC` env var.

This pull request allows external service kind Other to store the root directories in the configuration. Also, we change how serve-git handles list-repos in that it accepts a list of the directories to walk.

There are still open questions that I'll try to cover in the comments.

## Test plan

sg start app
unit tests

2023-02-17 04:04 UTC, gl-srgr commented on internal/service/servegit/extsvc.go
> +		Roots: roots,
Since we upsert() to the data store we will overwrite what was configured previously. Perhaps we have one external service just for SRC env var, which always overwrites?

2023-02-17 04:09 UTC, gl-srgr commented on internal/service/servegit/serve_test.go
> +			privateRoot := filepath.Join("private", root)
There's probably a better way to do this to pass the test, but i didnt look into it deeply.

2023-02-17 04:11 UTC, gl-srgr commented on internal/service/servegit/service.go
> +	roots := strings.Fields(c.Get("SRC", defaultReposRoot, "Root dir containing repos."))
`Config.Validate()` fails for empty string since `c.Get()` appends the error. Not sure how we should identify that a user does not want any local repo sync'ing defined by `SRC`

2023-02-17 04:12 UTC, gl-srgr commented on schema/other_external_service.schema.json
> +      "description": "For use with serve-git: The root directories to walk when discovering git repositories to mirror. More documentation here: https://docs.sourcegraph.com/admin/external_service/sr
Since this is serve-git specific, maybe it should be a new schema, instead of reusing Other? I'm fine either way, just wanted to get feedback.

2023-02-17 04:14 UTC, gl-srgr commented on internal/service/servegit/service.go
> -	if config.ReposRoot == "" {
If user passes SRC="" then should we create an Ext svc with empty Roots slice, or should we not create an ext svc at all?

Also, for the above question, does our answer change if an external service for serve-git is already in the data store?

@vovakulikov asked about creating more than one "Other" ext service which could be useful for distinguishing  different user intentions.

2023-02-17 10:31 UTC, keegancsmith reviewed
FYI I rebased this PR for you since I landed mine.

2023-02-17 10:31 UTC, keegancsmith commented on schema/other_external_service.schema.json
> +      "description": "For use with serve-git: The root directories to walk when discovering git repositories to mirror. More documentation here: https://docs.sourcegraph.com/admin/external_service/sr
We still have src serve-git in src-cli which likely shouldn't support this feature.

I think we either need something new or we somehow indicate this is for app. cc @mrnugget

2023-02-17 10:31 UTC, keegancsmith commented on internal/service/servegit/service.go
> -	if config.ReposRoot == "" {
I reckon if we want to keep supporting code specified from the command line then it should be its own external service. But to be honest if we have a nice UI I'd consider removing that support and rather make the wizard use signals like the CWD for suggestions.

2023-02-17 10:31 UTC, keegancsmith commented on internal/service/servegit/service.go
> +	roots := strings.Fields(c.Get("SRC", defaultReposRoot, "Root dir containing repos."))
oops, I'll see how we can fix that.

2023-02-17 10:31 UTC, keegancsmith commented on internal/service/servegit/serve.go
> +	fs := http.FileServer(http.Dir(filepath.Separator))
lets get rid of this for multi root.

2023-02-17 10:31 UTC, keegancsmith commented on internal/service/servegit/serve.go
> +			return filepath.Join(string(filepath.Separator), filepath.Clean(name))
we still need fromslash, name will be encoded like a url path?

2023-02-17 10:31 UTC, keegancsmith commented on internal/service/servegit/extsvc.go
> +		Roots: roots,
As mentioned elsewhere I think we should get rid of command line based setup if we have a wizard. Until then it feels correct to me to always upsert.

2023-02-17 10:31 UTC, keegancsmith commented on internal/repos/other.go
> +	req, err := http.NewRequest("GET", s.conn.Url+"/v1/list-repos", bytes.NewReader(reqBody))
if you set a body this should be a POST request.

2023-02-17 10:31 UTC, keegancsmith commented on internal/repos/other.go
> +	ListReposRequest struct {
you don't need to export this it is only used in the srcExpose method. Just declare it there or do something like `map[string]any{ "roots": s.conn.Roots}`

2023-02-20 04:20 UTC, gl-srgr commented on internal/service/servegit/serve.go
> +			return filepath.Join(string(filepath.Separator), filepath.Clean(name))
Yes I can fix this. It'll still have prefixing separator, in lieu of what used to be root

2023-02-20 04:26 UTC, gl-srgr commented
> As mentioned elsewhere I think we should get rid of command line based setup if we have a wizard. Until then it feels correct to me to always upsert.

@keegancsmith I'm okay with removing this, and then we can add it back later if we want. Do you think we should sync any directory at all before external service is configured by user? E.g. you mentioned current working directory. I'm leaning towards not sync'ing any repo unless user adds it in external service config (or defines in `SRC` env var if we decide to use that in some form later).

I think one enhancement to add later is suggestions in the setup wizard where we can walk directories and find local git directories as we already do now for `/v1/list-repos`. This might not be needed for march MVP but I can make a ticket.

2023-02-20 05:02 UTC, gl-srgr commented on internal/service/servegit/serve.go
> +	fs := http.FileServer(http.Dir(filepath.Separator))
removed; returns 204 unless the gitservice handler specific suffixes are matched for url path

2023-02-20 21:23 UTC, slimsag commented on internal/service/servegit/extsvc.go
> +		Roots: roots,
I have not had a chance to review this PR or the other discussion, sorry. Let me know if it's still useful for me to do that. I am still pushing for us to implement [this user experience](https://sourcegraph.slack.com/archives/C04J6HSHVJ5/p1676917232248969?thread_ts=1676915360.760879&cid=C04J6HSHVJ5) however:

> What I’ve discussed with people - and the expected user flows for App from my POV: there are two flows, one is CLI-only setup and the other is GUI setup. Effectively:
>
> 1. Download Sourcegraph App
> 2. In a directory with your code, OR without your code, launch sourcegraph.
> 3. If it detects you ran sourcegraph inside a Git repository, it adds that folder of code to Sourcegraph.
> 4. When you navigate to Sourcegraph, no “create admin account” page is shown (you automatically have an admin account since it’s a desktop app.)
> 5. If you don’t have any code (e.g. you didn’t run sourcegraph in a Git repo so it found none), then the setup-wizard is shown to add local or remote code. Otherwise it is not shown.
> 6. There will be an app-specific navigation link which allows you to go back to the setup wizard to add more repos (local or remote) after the fact.
>
> This is optimized to give people the fastest time-to-search-results, which I think should be our guiding star for App overall.
>
> This is what I’d like to get to by Starship, but there are lots of different folks working on this so maybe it won’t be exactly this by that time. But it’s where I’d like to see us get to in the end regardless.

I'm fine with doing other things in the interim if that helps us make progress, of course, but that's where we are going in my view / should be working towards ultimately.

2023-02-21 02:08 UTC, gl-srgr commented on internal/service/servegit/extsvc.go
> +		Roots: roots,
@slimsag no problem, I don't believe you need to do a code review for this PR since @keegancsmith and I have mostly wrapped it up. My main curiosity was how local repos can get added and whether you wanted one or both of these options available, since the first was proposed by you in a meeting a few weeks back:

1. User defines local directory via SRC environment variable: _I believe we're going to scrap this idea_
2. Sourcegraph automatically detects git directories and adds them for sync'ing, without any user input: _I believe we'll need to add this, not sure which team will work on it._

Note that we also have other options for adding local repos and the setup experience team will be responsible for delivering these:
3. After sourcegraph starts and the setup wizard is provided to the user, the user selects a directory
4. Create an external service via Manage Code Hosts, of kind Other, which uses the serve-git service of sg app

2023-02-21 08:28 UTC, slimsag commented on internal/service/servegit/extsvc.go
> +		Roots: roots,
#2 is what I had in mind here, #1 (setting an env var) does not sound like a good CLI UX to me. #2 already works right now in `main`-it's how @keegancsmith's src-expose/src-serve integration appears to be working right from what I can tell, does this PR change that behavior?

2023-02-21 12:41 UTC, keegancsmith commented
There is now discussion happening in a few places about this (thread in slack). So lets try keep things in one place, but I will keep this discussion focussed on this PR.

> Do you think we should sync any directory at all before external service is configured by user?

It sounds like in the ideal flow mentioned by Stephen we would still maintain a "magic" service which is affected by the command line. Lets debate elsewhere about if that is what we want. For now lets keep this PR small and incremental and punt on deciding it here.

2023-02-21 12:52 UTC, keegancsmith commented on internal/repos/other.go
> +	}
we need to think about backwards compatibility here. What does it mean if Roots is empty? Unset? How does it interact with all existing services which do not specify roots nor what that behaviour.

If we can determine it, unset sounds like the best approach for knowing we should fallback to the old src-serve behaviour of using its CWD to search for repos. If roots is set (and even if empty), then we use roots.

2023-02-21 17:15 UTC, gl-srgr commented on internal/service/servegit/service.go
> +	ReposRoots []string
Yeah that makes sense, initially I wanted parity between ext svc config via setup wizard, and `SRC`, but as discussions progressed I see value in not conflating setup wizard needs/nice to haves with what we bake into serve-git service.

2023-02-28 22:41 UTC, gl-srgr commented on internal/repos/other.go
> +	}
@keegancsmith That's true, this doesn't consider external services using the non-local serve git sources. I am considering making a different request based on whether the external service is sourcegraph app local code vs remote code(and thus not sourcegraph app use case).

to distinguish between them in the external service, I might just add another hardcoded indicator like `src-expose-local` to be entered as element `s.conn.Repos[0]`, which will then be checked `[here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@73155ec6ee4914681f6c6d8fb8d0d4b05c6fb2de/-/blob/internal/repos/other.go?L91)` in ListRepos().

A more elegant solution would probably be a brand new external service schema/Kind, or adding new members to the existing Other schema, but I think because this is a very specific case for local repos we can instead just add this new hardcoded indicator in `Repos[]`

2023-03-02 04:37 UTC, gl-srgr commented on internal/service/servegit/extsvc.go
> +		Roots: roots,
Just a follow up to confirm since we had conversations in different places: In my upcoming commit I'll have `SRC` removed, and we'll use current working directory. I'm also going to use the hardcoded External Service created by this file just for the cwd and not for anything setup wizard is concerned with, so setup wizard selections can persist while the cwd repos come and go.

2023-03-02 04:38 UTC, gl-srgr commented on internal/service/servegit/service.go
> -	if config.ReposRoot == "" {
Mentioned earlier but we'll have setup wizard be a different external service, and also `SRC` is removed in my next commits

2023-03-02 04:40 UTC, gl-srgr commented on schema/other_external_service.schema.json
> +      "description": "For use with serve-git: The root directories to walk when discovering git repositories to mirror. More documentation here: https://docs.sourcegraph.com/admin/external_service/sr
This came up in another thread and we're okay with using ext svc Kind `Other` for our purposes

2023-03-02 05:07 UTC, gl-srgr commented
@keegancsmith when you get a chance take a look at this PR; it's got the same concepts from the draft version for the most part

2023-03-02 05:14 UTC, gl-srgr commented on internal/service/servegit/extsvc.go
> +func doEnsureExtSVC(ctx context.Context, store database.ExternalServiceStore, url, root string) error {
if no repos detected for sync'ing, should we delete ext svc? It probably makes sense to try and delete since it won't do anything, unless we want to use the hardcoded ext svc for discovery; but I think we'll instead just reference env var `SRC_SERVE_GIT_URL` somewehere in the backend and use that for discovery, so this hardcoded ext service isn't needed for discovery either.

2023-03-02 09:36 UTC, mrnugget reviewed
Just some drive-by comments, leave it up to @keegancsmith

2023-03-02 09:36 UTC, mrnugget commented on internal/repos/other.go
> +	return req, nil
```suggestion
		return http.NewRequest("POST", s.conn.Url+"/v1/list-repos", bytes.NewReader(reqBody))
	} else {
		return http.NewRequest("GET", s.conn.Url+"/v1/list-repos", nil)
	}
```

2023-03-02 09:36 UTC, mrnugget commented on internal/service/servegit/serve.go
> +}
Can we get a test for this? :)

2023-03-02 14:29 UTC, keegancsmith reviewed
I am mid review, but got a meeting now and thought I'd rather give half baked feedback than leave ya hanging for another day.

Also I see there are conflicts against main.

2023-03-02 14:29 UTC, keegancsmith commented on internal/repos/other.go
> +	srcServeLocal := len(s.conn.Repos) == 1 && s.conn.Repos[0] == "src-serve-local"
rather than threading this through, you are already inspecting `s.conn` inside of listReposRequest. You can add the business logic there that decides to do a different API in listReposRequest.

2023-03-02 14:29 UTC, keegancsmith commented on internal/repos/other.go
> +	}
```suggestion
		return http.NewRequest("POST", s.conn.Url+"/v1/list-repos", bytes.NewReader(reqBody))
	} else {
		return http.NewRequest("GET", s.conn.Url+"/v1/list-repos", nil)
	}
```

2023-03-02 14:29 UTC, keegancsmith commented on internal/repos/other.go
> +		req, err = http.NewRequest("POST", s.conn.Url+"/v1/list-repos", bytes.NewReader(reqBody))
it feels like maybe this should be a new API endpoint? Distinguishing by POST vs GET feels a bit janky.

2023-03-02 23:15 UTC, gl-srgr commented on internal/repos/other.go
> +	}
Is there a reason to skip returning the error?

2023-03-02 23:17 UTC, gl-srgr commented on internal/repos/other.go
> +		req, err = http.NewRequest("POST", s.conn.Url+"/v1/list-repos", bytes.NewReader(reqBody))
renamed endpoint. As of now neither version of the src-serve handler won't support both but that could change later

2023-03-02 23:28 UTC, gl-srgr commented on internal/repos/other.go
> +	srcServeLocal := len(s.conn.Repos) == 1 && s.conn.Repos[0] == "src-serve-local"
updated

2023-03-03 08:46 UTC, keegancsmith commented on internal/repos/other.go
> +	}
this doesn't skip  the error, it is returned as part of NewRequest

2023-03-03 11:10 UTC, mrnugget commented on internal/repos/other.go
> +	}
why are you copying my suggestions keegan, come on man https://github.com/sourcegraph/sourcegraph/pull/47779#discussion_r1122820142

2023-03-03 11:31 UTC, keegancsmith commented on internal/repos/other.go
> +	}
great minds think alike

2023-03-03 13:28 UTC, keegancsmith requested changes
So in some places I talk about preserving the old behaviour. I think I see why you wanted to break it. So the principal I think you need to follow is this:

- you can't break the existing behaviour of the Other kind since it interacts with the src-cli serve-git command and customers use it.
- you can however add new things (which you have done).
- Our internal/service/servegit service can be whatever we want. In that case it looks like you should remove the service caring about or requiring root. Then the only interaction with `Root` will be via ensureExtService stuff.

2023-03-03 13:28 UTC, keegancsmith commented on internal/repos/other.go
> +	if req != nil {
nit: relying on req being nil is a footgun. Please return a boolean as well from srcExposeRequest indicating if we should do the req.

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/extsvc.go
> +func doEnsureExtSVC(ctx context.Context, store database.ExternalServiceStore, url, root string) error {
I think we should keep it. Reason is it is simpler mental model since you can clearly find the service and notice that it has no repos associated with it.

We don't need to do an API request to access local repos. For app we are in the same binary, we can just directly use the service.

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/serve.go
> +	root, err := filepath.EvalSymlinks(root)
you probably wanna run this and absolute path before doing your `traversed` logic above.

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/serve.go
> +		cloneURI := pathpkg.Join("/repos", path)
path is a filepath. You need to convert it into a path with `filepath.ToSlash`

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/serve_test.go
> +		reposCWD string
unused

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/serve_test.go
>  func TestReposHandler(t *testing.T) {
I've modified this test in another PR. That might make this easier to implement.

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/serve_test.go
> +					Root: "cwd",
this looks wrong?

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/serve_test.go
> +				parent := "/private"
this looks very dodgy and probably breaks on anything but macos. Use absolute path and eval symlinks maybe?

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/serve_test.go
> +	for _, sub := range []string{"http://" + testAddress, "/v1/list-repos-for-path", "/repos/"} {
don't just remove all the old tests for the old API endpoint. add new ones for the new functionality.

2023-03-03 13:28 UTC, keegancsmith commented on internal/service/servegit/service.go
> +	if pwd, err := os.Getwd(); err == nil {
why did you remove SRC?

2023-03-03 13:28 UTC, keegancsmith commented on schema/other_external_service.schema.json
> +      "description": "The root directories to walk when discovering git repositories to mirror. For use with local serve-git supporting multiple root directories. More documentation here: https://doc
this description is incorrect since we do not support serve-git from src-cli. Make the description Sourcegraph App specific and mention what we need to set for repos.

2023-03-04 03:50 UTC, gl-srgr commented on internal/service/servegit/service.go
> +	if pwd, err := os.Getwd(); err == nil {
Removal came up a few times in previous comments, linked below, and the sentiments were leaning towards removal, but I don't have a strong preference either way. I will add it back in

https://github.com/sourcegraph/sourcegraph/pull/47779#discussion_r1109591797

https://github.com/sourcegraph/sourcegraph/pull/47779#discussion_r1109287745

2023-03-04 03:57 UTC, gl-srgr commented on internal/service/servegit/service.go
> +	if pwd, err := os.Getwd(); err == nil {
PR updated

2023-03-04 04:12 UTC, gl-srgr commented
> We don't need to do an API request to access local repos. For app we are in the same binary, we can just directly use the service.

Were you planning to use app-discover-repos for the local repos discovery query (whether with file picker script, or the graphql query that takes one or more `root` paths)? For example, define graphql query which then just calls the serve-git service directly instead of submitting an http request. I'm okay with this but not sure if I misunderstood.

I believe we had diverging ideas for the discovery solution since I was going to use the `/list-repos-for-path/ `endpoint for both discovery and sync'ing; I'm fine with not using that endpoint for discovery and just having it be used for sync'ing. If you also don't want sync'ing to be done via the http handlers and instead just call the service directly then let me know because that's not the approach I was taking.

To clarify why I want to not call service directly and instead submit http requests: I wanted to reduce the amount of changes in the Other ext svc code, so I kept that the sync operation submits the http request in `ListRepos()`. For discovery I try to have `ListRepos()` be utilized in the same manner for consistency. For remote code host this was my approach, but for local repos sourcegraph app experience I'm open to a different approach.

2023-03-04 04:23 UTC, gl-srgr commented on internal/repos/other.go
> +	}
Yeah this works for me and I misread the suggestion in haste; I was tunnel visioned on not returning returned value for `req` if anything went awry in NewRequest() and instead return nil. On second thought the error checks in caller and here are def sufficient

2023-03-05 23:11 UTC, gl-srgr commented on internal/service/servegit/serve.go
> +}
Added a comment [here](https://github.com/sourcegraph/sourcegraph/issues/48473) re: reducing scope. TLDR; we won't have multiple paths/roots in the other external service connection schema, so union logic is no longer necessary and `ReposUnion()` will get removed

2023-03-05 23:15 UTC, gl-srgr commented on internal/service/servegit/serve.go
> +	root, err := filepath.EvalSymlinks(root)
`ReposUnion()` removed, see previous comment

2023-03-06 06:35 UTC, gl-srgr commented
> Our internal/service/servegit service can be whatever we want. In that case it looks like you should remove the service caring about or requiring root. Then the only interaction with Root will be via ensureExtService stuff.

Do you mean removing from `Serve` and/or `Config`?

2023-03-06 06:42 UTC, gl-srgr commented on internal/service/servegit/extsvc.go
> +func doEnsureExtSVC(ctx context.Context, store database.ExternalServiceStore, url, root string) error {
I referenced this elsewhere but discovery without needing SRC_SERVE_GIT_URL makes sense to me, especially with the PR you have open which instantiates `Serve{}` from the loaded config for serve git service (Although I also saw that we might want to replace this `Serve{}` instantiation with fetching the service itself, but this also lets us skip the request and skip needing the url).

So the `SRC_SERVE_GIT_URL` is used just for the sync (and we'll include it in the other ext svc configuration).

2023-03-06 06:51 UTC, gl-srgr commented
> you can't break the existing behaviour of the Other kind since it interacts with the src-cli serve-git command and customers use it.

I pushed more changes to the `other.go` logic for the new request. Is there anything in `other.go` that is still breaking existing behavior? I believe it will only behave differently when we detect the new magic phrase `src-serve-local` in the repos array, and when that is not in the repos list existing behavior should be the same (which already includes detecting existing magic phrases for src-expose).

2023-03-06 06:56 UTC, gl-srgr commented
@keegancsmith I still have a bunch of changes locally, including `reposUnion()` removal and reverting multiple paths. But if you have a chance to confirm my comments re: `other.go` and changing if we need `root` then that'll help confirm any remaining work which'll unblock this PR.

2023-03-06 07:56 UTC, keegancsmith commented
> Were you planning to use `app-discover-repos` for the local repos discovery query (whether with file picker script, or the graphql query that takes one or more `root` paths)?

No. app-discover-repos is purely for debugging as a developer at Sourcegraph.

> I believe we had diverging ideas for the discovery solution since I was going to use the `/list-repos-for-path/ `endpoint for both discovery and sync'ing; I'm fine with not using that endpoint for discovery and just having it be used for sync'ing. If you also don't want sync'ing to be done via the http handlers and instead just call the service directly then let me know because that's not the approach I was taking.

We are on the same page here, except my point is in App we don't need to do an API call... we are in the same process. We can just call the go function directly.

> To clarify why I want to not call service directly and instead submit http requests: I wanted to reduce the amount of changes in the Other ext svc code, so I kept that the sync operation submits the http request in `ListRepos()`. For discovery I try to have `ListRepos()` be utilized in the same manner for consistency. For remote code host this was my approach, but for local repos sourcegraph app experience I'm open to a different approach.

I think the confusion is between syncing and preview. In the wizard we want to know which repos we will sync (a preview / the LocalDirectory LocalRepo stuff). Once we add the external service, we then sync which will go via the external service.

I may be missing some context on how you are doing this stuff with other external services. I suppose you may have hooked up something else for preview in them which directly called the syncer but avoided the part which wrote to the DB? In that case you make a good point, we should just do everything via the ext service APIs.

But in that case we don't need what I propose above around LocalRepo/etc. The only API we really need is the directory picker. That sounds good to me. Where is the code which implements this or docs which describes what you plan to do so I can take a look?

> > Our internal/service/servegit service can be whatever we want. In that case it looks like you should remove the service caring about or requiring root. Then the only interaction with Root will be via ensureExtService stuff.
> 
> Do you mean removing root from being a member of `Serve` and `Config` and instead have it be passed as argument to ensureExtService stuff? That was my original intention but it got added back while merging all of the recent changes, so I'm okay with this approach.

Yes.

> > you can't break the existing behaviour of the Other kind since it interacts with the src-cli serve-git command and customers use it.
> 
> I pushed more changes to the `other.go` logic for the new request. Is there anything in `other.go` that is still breaking existing behavior? I believe it will only behave differently when we detect the new magic phrase `src-serve-local` in the repos array, and when that is not in the repos list existing behavior should be the same (which already includes detecting existing magic phrases for src-expose).

Looks good.

> @keegancsmith I still have a bunch of changes locally, including `reposUnion()` removal and reverting multiple paths. But if you have a chance to confirm my comments re: `other.go` and changing if we need `root` then that'll help confirm any remaining work which'll unblock this PR.

Why don't you just push them?

2023-03-06 22:52 UTC, gl-srgr commented
> No. app-discover-repos is purely for debugging as a developer at Sourcegraph.
Understood. After looking at the draft pr this also became clear.

> I think the confusion is between syncing and preview. In the wizard we want to know which repos we will sync (a preview / the LocalDirectory LocalRepo stuff). Once we add the external service, we then sync which will go via the external service.

As long as the sync still goes through the expected channels and submits an https request then that clarifies some of the recommendations for me.

> I may be missing some context on how you are doing this stuff with other external services. I suppose you may have hooked up something else for preview in them which directly called the syncer but avoided the part which wrote to the DB? In that case you make a good point, we should just do everything via the ext service APIs.

Yeah that's fairly accurate to what we do: If we don't have an existing external service with the configuration we need for discovery then new up an ExternalService, don't save it to DB, and pass the ExternalService to [Source](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/sources.go) / [DiscoverableSource](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/repos/discoverable_sources.go?subtree=true). Since we juggle multiple github apis for different discovery requests of organizations + repos it was easier to have these converge with the sync operations / reuse as much of the sync operations logic.

Initially since we had an earlier code freeze for setup experience than sourcegraph app I was planning to similarly have as much of the sync operations and discovery operations be shared in hopes of having minimal code additions and I suppose abstract the fact that the remote code host for src-serve-local is potentially local. That was my initial thinking in the limited time we had, but I think letting discovery not rely on the same logic as the sync is okay (like having to use endpoint `/list-repos/` ).

The PRs for the remote code host discovery operations are [here](https://github.com/sourcegraph/sourcegraph/pull/47932/files) and [here](https://github.com/sourcegraph/sourcegraph/pull/48096/files) .

> Why don't you just push them?

I wanted to confirm removing config.Root / serve.Root because the existing test is going to need updates. Even with removing the multiple paths + `ReposUnion()` logic I still have to update the test since all paths returned for `/list-repos*` endpoint are not relative. Another tricky part is the temp directory absolute path not being fixed which is why I have to add some [hack](https://github.com/sourcegraph/sourcegraph/pull/47779/files#r1124447016) when it's macos. Lastly one PR [comment](https://github.com/sourcegraph/sourcegraph/pull/47779/files#r1124447704) expresses reluctance re: replacing/overwriting the existing tests, but I'm identifying that the existing tests are not going to be valid depending on what changes we're okay with in this PR.

All of this is to say that I want the expectations to be clarified so that my test changes expedite code review.

2023-03-07 09:51 UTC, keegancsmith commented
the extra commits are likely due to rebasing a after merging. I'll see if I can clean up quick

2023-03-07 10:03 UTC, keegancsmith commented
To fix this required a bit of surgery, I ended up force pushing all your changes squashed into one commit.

2023-03-07 10:29 UTC, keegancsmith commented
I didn't know of the `externalServiceRepositories` call you added. Indeed that makes a lot of sense as how we do previews. Right now it is super GitHub specific, but lets discuss that somewhere else (I'll follow up later today on slack). I believe my super specific LocalRepository API should be removed once we can, but for now it works and unblocks frontend.

> > Why don't you just push them?
> 
> All of this is to say that I want the expectations to be clarified so that my test changes expedite code review instead of delaying approval

Meta: I'd encourage you to make decisions that seem correct and shipping stuff. If there are bits you want to debate, split those out. Its just code, we can always revert. Prefer velocity over caution.

2023-03-07 13:45 UTC, keegancsmith approved these changes
I very deeply reviewed this today and pushed a bunch of commits to properly understand what is going on / unblock progress. Please take a look at the commits I pushed, if you are happy hit that merge button.

2023-03-07 13:45 UTC, keegancsmith commented on internal/service/servegit/serve.go
> +	}
It feels like we shouldn't have to do this to work on mac. IE if we correctly pass in the absolute path as a root then all should work out. But I think lets ship it in the interest of progress since this is minor :)

2023-03-07 22:28 UTC, gl-srgr commented on internal/service/servegit/serve.go
> +	}
Yeah you are correct; Now that I better understand repoIsRoot() and I applied a fix for absolute paths in repoIsRoot (will comment on this separately) the mock stuff is not necessary and I've removed it

2023-03-07 22:30 UTC, gl-srgr commented on internal/service/servegit/serve_test.go
> +				root, err = filepath.EvalSymlinks(root)
`EvalSymlinks() `fixed the test so that I don't need the previous hack where I would prepend` /private/` for macos temp dir, so that was a good suggestion from earlier to use that

2023-03-07 22:52 UTC, gl-srgr commented on internal/service/servegit/serve.go
> +			if err != filepath.SkipDir {
This change is definitely confusing without a comment or context. I was trying out both empty string `""` and `"/"` root path for walking (either ext svc config's `root` or env var `SRC`) and noticed Walk returns skipDir error which bubbles up to repositories page with "failed to decode response from src-expose: <skip directory error message>". It kept happening and I figured for a bad input we should just not report the errors in repos page, so just not return error message and 500.

This was a bandaid added in haste though, so it'd be a lot better to handle these bad inputs differently (in follow up PRs). I've removed this check. I'm not going to work on handling the weird root path input cases in this PR but can write a ticket/PR as follow up. The better handling that comes to mind are:

1. if invalid root path input then we return before attempting `Repos()` / `Walk()` logic, since those calls are returning the errors
2. If we have some edge cases that we still want to consider valid (e.g. "/" and "") then we need to sanitize it/modify it before passing to `Repos()` / `Walk()`
3. Return Error as part of the response so that we don't have `failed to decode response`. We could consider later giving warning that input is bad, based on the returned error.

If setup experience -> file picker user flow is unlikely to end up with these unusual root path selections then this may not be that important.

2023-03-07 23:22 UTC, gl-srgr commented on internal/service/servegit/serve.go
> +	// Regular git repos won't clone without the full path to the .git directory.
Above changes for `ReposIsRoot()` were added just now since we use absolute paths for 

1.  uri and clone path metadata of the repos we return for requests `/list-repos-for-path/`
2. metadata from (1) is used for requests to gitservice handler

We can use the same logic as we do in `Walk()` for composing uri and clonePath values. We still keep `reposIsRoot()` so that we don't end up calling `subpath, err := filepath.Rel(root, path)` with root == path, which happens in `Walk()` and yields path `.`

Tested this out manually and also updated the Test case for root dir is a repo.

2023-03-07 23:29 UTC, gl-srgr commented
> To fix this required a bit of surgery, I ended up force pushing all your changes squashed into one commit.

Thanks for fixing this PR  @keegancsmith ! I've pushed some changes and will merge. Added some comments to the PR explaining recent changes.

2023-03-07 23:29 UTC, merged