Docs update for deploying with Kustomize
sourcegraph/sourcegraph pull request #47772
Opened 2023-02-16 20:18 UTC by abeatrix

## Docs update for the new base cluster with updated Kustomize setup

Close https://github.com/sourcegraph/sourcegraph/issues/45758 & https://github.com/sourcegraph/sourcegraph/issues/46755

![image](https://user-images.githubusercontent.com/68532117/219477500-9e2186e2-d624-4321-9e88-f7327b5e8147.png)
![image](https://user-images.githubusercontent.com/68532117/219477602-3ce3387a-ae18-4d5c-8f0c-addbe7b46a3e.png)

This is a docs update for the new Kustomize deployment method that will be introduced in https://github.com/sourcegraph/deploy-sourcegraph-k8s

## Test plan

1. Run `yarn docsite:serve` to stand up docs site
2. Clone the [deploy-sourcegraph-k8s ](https://github.com/sourcegraph/deploy-sourcegraph-k8s/tree/main) repo 
3. Visit http://localhost:5080/admin/deploy/kubernetes/kustomize/configure in your browser and follow the instruction to build a Kustomize Overlay configured for deploying Sourcegraph
4. Visit http://localhost:5080/admin/deploy/kubernetes/kustomize and follow the instructions to deploy Sourcegraph using an overlay

2023-02-16 21:03 UTC, jasonhawkharris requested changes

2023-02-17 00:51 UTC, DaedalusG approved these changes
Mostly nits -- this looks awesome B -- will have to run through the kustomize migration on cse-k8s as a demo 😁

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/index.md
> +>NOTE: Deploying with machine images require the necessary technical expertise and resources to maintain and manage their own infrastructure.
```suggestion
>NOTE: Deploying with machine images requires technical expertise and the ability to maintain and manage your own infrastructure.
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/index.md
> +- **Kustomize** utilizes the built-in features of kubectl to provide maximum flexibility in configuring your deployment
Should we mention the relationship of this to ease of upgrades?

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/eks.md
> +- **IAM permissions**: The user that will be performing the installtion must have permissions to work with Amazon EKS IAM roles and service linked roles, AWS CloudFormation, and a VPC and related res
```suggestion
- **IAM permissions**: The user that will be performing the installation must have permissions to work with Amazon EKS IAM roles and service linked roles, AWS CloudFormation, and a VPC and related resources.
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/index.md
> +>WARNING: Search performance will suffer tremendously without SSDs provisioned.
tremendously ❤️

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/kustomize/eks.md
> +The installation steps below will walk you through the steps using our quick-start overlay for Elastic Kubernetes Service (EKS) to deploy Sourcegraph.
```suggestion
The installation instructions below will guide you through deploying Sourcegraph on Elastic Kubernetes Service (EKS) with our quick-start overlay.
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/kustomize/eks.md
> +Once the load balancer is ready, you can access your new Sourcegraph instance at the returned IP address in your browser via HTTP. Accessing the IP address with HTTPS returns errors because TLS must
```suggestion
Once the load balancer is ready, you can access your new Sourcegraph instance at the returned IP address in your browser via HTTP. Accessing the IP address with HTTPS will return errors because TLS must be enabled first.
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/kustomize/eks.md
> +Once you have created a new overlay using the kustomization file from our quick-start overlay for AWS EKS, we strongly recommend you to:
```suggestion
Once you have created a new overlay using the kustomization file from our quick-start overlay for AWS EKS, we strongly recommend that you:
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/kustomize/gke.md
> +The installation steps below will walk you through the steps using our examples overlay for GKE to deploy the Sourcegraph.
```suggestion
The installation guide below will walk you through deploying Sourcegraph on Google Kubernetes Engine (GKE) using our GKE example overlay.
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/kustomize/migrate.md
> +Set it to `default` to deploy to the default namespace.
```suggestion
You may set `namespace: default` to deploy to the default namespace.
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/kustomize/migrate.md
> +Note: You may skip this step if your instance was not deployed using overlays from the deploy-sourcegraph repository.
Much of the rest of our documentation uses `>NOTE:` when making notes -- just a style thing

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/deploy/kubernetes/operations.md
> +The command will output the differences between the customizations specified in the overlay and the resources currently running in the cluster, allowing you to review the changes and ensure that the
```suggestion
The command will output the differences between the customizations specified in the overlay and the resources currently running in the cluster, allowing you to review the changes and ensure that the overlay produces similar resources to the ones currently being used by the active cluster before applying the new overlay.
```

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/external_services/index.md
> +Your Sourcegraph instance can be configured to use an external or managed version of these services:
Should we refer to the specific Sourcegraph services here i.e. pgsql codeinsight-db etc?

2023-02-17 00:51 UTC, DaedalusG commented on doc/admin/how-to/setup-https.md
> +This document will take you through how to setup HTTPS connection using the preinstalled [Ingress controller](../deploy/kubernetes/configure.md#ingress-controller), which allows external users to acc
```suggestion
This document will take you through how to setup HTTPS connection using the preinstalled [Ingress controller](../deploy/kubernetes/configure.md#ingress-controller), which allows external users to access your main web server over the network. It installs rules for the default ingress, see comments to restrict it to a specific host. This is our recommended method to configure network access for production environments.
```

2023-02-17 02:55 UTC, abeatrix commented on doc/admin/external_services/index.md
> +Your Sourcegraph instance can be configured to use an external or managed version of these services:
We can but I wouldn't add it to this PR as this is an [existing page](https://docs.sourcegraph.com/admin/external_services) that is not being introduced in this PR.

2023-02-17 02:55 UTC, abeatrix commented on doc/admin/deploy/index.md
> +>NOTE: Deploying with machine images require the necessary technical expertise and resources to maintain and manage their own infrastructure.
Updated by warren in one of his commit

2023-02-17 03:03 UTC, abeatrix commented on doc/admin/deploy/kubernetes/configure.md
> +Sourcegraph has removed all the Role-Based Access Control (RBAC) resources from the default base cluster. This means service discovery is not available by default, and the endpoints for each service
This is a very good point! I have updated to reflect this, thanks Jason!

2023-02-17 03:07 UTC, abeatrix commented on doc/admin/deploy/kubernetes/kustomize/migrate.md
> +Note: You may skip this step if your instance was not deployed using overlays from the deploy-sourcegraph repository.
updated

2023-02-17 04:44 UTC, jdpleiness approved these changes
Great work!

2023-02-17 04:58 UTC, abeatrix commented on doc/admin/deploy/index.md
> +- **Kustomize** utilizes the built-in features of kubectl to provide maximum flexibility in configuring your deployment
They are both easy to upgrade when follow correctly 😆

2023-02-17 19:25 UTC, jasonhawkharris approved these changes
LGTM!

2023-02-23 21:52 UTC, merged