gitserver: SRC_ENABLE_GC_AUTO to enable & disable gc on fetch
sourcegraph/sourcegraph pull request #47852
Opened 2023-02-17 21:47 UTC by abeatrix

Close https://github.com/sourcegraph/customer/issues/1955

Context: A customer is encountering an issue with one of their fast-moving repo that caused the repo unable to sync & index, making it unsearchable ([context](https://sourcegraph.slack.com/archives/C01S6JETFA7/p1676655948837959?thread_ts=1675898635.950919&cid=C01S6JETFA7)). We suspected the addition of `--no-auto-gc` in https://github.com/sourcegraph/sourcegraph/pull/36274 is the cause as the issue started after performing MVU, and the error went away when running `git gc` manually inside gitserver.

Included in this PR:
- set SRC_ENABLE_GC_AUTO to enable and disable gc on fetch
- update to run ls-remote with Git Protocol v2, based on @jhchabran 's finding [here](https://docs.gitlab.com/ee/administration/git_protocol.html)

## Test plan

Ran locally to confirm setting `SRC_ENABLE_GC_AUTO` would toggle the command flag:
```bash
[    gitserver-1] 2023/02/17 20:54:11 Setting --auto-gc to fetch
[    gitserver-1] 2023/02/17 20:57:08 Setting --no-auto-gc to fetch
```

2023-02-18 11:01 UTC, jhchabran commented on cmd/gitserver/server/serverutil.go
> +	if len(cmd.Args) > 1 {
@abeatrix can we try putting this behind a feature flag? That would make it much easier to compare how it differs on the scaletesting instance, as well as turning it off without having to make a release, were we to observe it being problematic.

2023-02-20 07:34 UTC, stefanhengl approved these changes

2023-02-20 07:34 UTC, stefanhengl commented on cmd/gitserver/server/refspecoverrides.go
> +	if e := os.Getenv("SRC_ENABLE_GC_AUTO"); e == "false" {
nit: maybe `strconv.ParseBool` would be better here? Especially because customers will set this, there might be a lot of variation in how they set it.

2023-02-20 07:34 UTC, stefanhengl commented on cmd/gitserver/server/serverutil.go
> +	if len(cmd.Args) > 1 {
Should this be a separate PR?

2023-02-20 07:34 UTC, stefanhengl commented on cmd/gitserver/server/vcs_syncer_git.go
> +		if e := os.Getenv("SRC_ENABLE_GC_AUTO"); e == "false" {
strconv.ParseBool?

2023-02-20 07:51 UTC, indradhanush reviewed
Not a blocker, but could you please add a section to the end of [this](https://docs.sourcegraph.com/dev/background-information/git_gc) doc to document this new behaviour?

Can be a follow up PR as well. Leaving the comment so that it's tracked.

2023-02-20 09:05 UTC, mrnugget requested changes
Thanks for hopping on this! Requesting changes because I think we should reuse the GC mode variable OR move the parsing of the env var closer to the others.

2023-02-20 09:05 UTC, mrnugget commented on cmd/gitserver/server/refspecoverrides.go
> +	if e := os.Getenv("SRC_ENABLE_GC_AUTO"); e == "false" {
Why do we have to check the env var here again? Can't we check whether `gitGCMode == gitGCModeGitAutoGC`?

We already parse the env var here and already have some logic to set the GC mode here: https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L56-L87

I think we should reuse that instead of adding another place where things can change.

2023-02-20 09:05 UTC, mrnugget commented on cmd/gitserver/server/serverutil.go
> +	if len(cmd.Args) > 1 {
Agree, this is a separate change that we also possibly want to separately test/revert/deploy, so I'd put it in a separate PR.

2023-02-20 09:05 UTC, mrnugget commented on cmd/gitserver/server/vcs_syncer_git.go
> +		if e := os.Getenv("SRC_ENABLE_GC_AUTO"); e == "false" {
Same as above: let's reuse `gitGCMode` or at least the parsing of the env var or move this check over to the the others and use [`.envGet`](https://sourcegraph.sourcegraph.com/search?q=context%3Asourcegraph+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+env.Get&patternType=standard&sm=0&groupBy=path).

2023-02-20 09:05 UTC, mrnugget commented on cmd/gitserver/server/vcs_syncer_git.go
> +		gc := "--auto-gc"
Do we even need to set this explicitly? I kinda assumed that, depending on the GC mode we use, we set `gc.auto = 1` or `0` in the git config. See: https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L1402-L1420

2023-02-20 17:03 UTC, abeatrix commented
Thank you all for the reviews! I wasn't aware of gitGCMode but what @mrnugget suggested makes sense to me. I do have a follow-up question to make sure I understand the current implementations correctly. It looks like we disable `gc` for [gitGCModeJanitorAutoGC & gitGCModeMaintenance](https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L1413) even when [enableGCAuto](https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L78) is set to true, can someone explain to me if this is intended (or is this the issue that we are trying to fix)?

2023-02-20 17:08 UTC, abeatrix commented on cmd/gitserver/server/serverutil.go
> +	if len(cmd.Args) > 1 {
Putting it in a separate PR makes sense to me. I've reverted the changes

2023-02-20 17:16 UTC, mrnugget commented
> It looks like we disable `gc` for [gitGCModeJanitorAutoGC & gitGCModeMaintenance](https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L1413) even when [enableGCAuto](https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L78) is set to true, can someone explain to me if this is intended (or is this the issue that we are trying to fix)?

I'll let @stefanhengl answer here (since he added it in https://github.com/sourcegraph/sourcegraph/commit/f461a4ae253faa2752d2bc64d049c90569de7a1f) but I think the thinking is this: if we use `gitGCModeJanitorAutoGC` or `gitGCModeMaintenance` we run our own garbage collection in janitor runs, every 1min, so we don't need to run `auto-gc` on commands. that's why we disable it, so a `git fetch` that triggers auto-gc can't clash with a janitor run in the background.

But: aren't we now discovering that even with janitor-git-gc-runs we still run into these problems and we should probably also use `auto-gc` even if `gitGCModeJanitorAutoGC`?

2023-02-20 18:19 UTC, abeatrix commented
> But: aren't we now discovering that even with janitor-git-gc-runs we still run into these problems and we should probably also use auto-gc even if gitGCModeJanitorAutoGC?

@mrnugget Yea that's what I believe is the issue as well and have updated to enable `gc` [here](https://github.com/sourcegraph/sourcegraph/pull/47852/commits/df06b73a2fd74612f7beda85c1bb9f7eca9cb1cb#diff-ac8c3d08e7a1b32ee4a6f37239e70e17448cec1f219cd4ca0921f556b6601ca1L1410) for `gitGCModeJanitorAutoGC`, but want to make sure why it wasn't in the first place but what you explained clarified it for me :) Will wait for @stefanhengl to confirm

2023-02-21 07:55 UTC, stefanhengl commented
> edit: @stefanhengl should we also remove the hard-coded "gc.auto=1" [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/cmd/gitserver/server/cleanup.go?L1114)?

From the [docs](https://sourcegraph.com/github.com/git/git/-/blob/Documentation/config/gc.txt)

> gc.auto::
	When there are approximately more than this many loose
	objects in the repository, `git gc --auto` will pack them.
	Some Porcelain commands use this command to perform a
	light-weight garbage collection from time to time.  The
	default value is 6700.

This is an aggressive setting for packing but AFAIK we never had trouble with it. Changing it might blow up dir sizes on gitserver. I never changed it and unless we have specific reason to remove it I wouldn't touch it.

2023-02-21 08:10 UTC, stefanhengl commented
> Thank you all for the reviews! I wasn't aware of gitGCMode but what @mrnugget suggested makes sense to me. I do have a follow-up question to make sure I understand the current implementations correctly. It looks like we disable gc for [gitGCModeJanitorAutoGC & gitGCModeMaintenance](https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L1413) even when [enableGCAuto](https://github.com/sourcegraph/sourcegraph/blob/37458d2484d78de53765dfaea929be7c22e611cf/cmd/gitserver/server/cleanup.go#L78) is set to true, can someone explain to me if this is intended (or is this the issue that we are trying to fix)?

Once it became obvious that sg maintenance caused repo corruption for customers with large repos I tried to lock down any unintentional garbage collection run by git porcelain commands IE I wanted to make sure our janitor job is the only one running gc. This whole approach failed and I recommend to take the original implementation (before I added sg maintenance) as baseline. The original implementation didn't set any repo config options like we do in `gitSetAutoGC`.

2023-02-21 09:27 UTC, sashaostrikov approved these changes

2023-02-21 18:40 UTC, mrnugget approved these changes

2023-02-21 18:55 UTC, mrnugget approved these changes

2023-02-21 19:43 UTC, merged