[rank] Enables ranking
sourcegraph/sourcegraph pull request #48059
Opened 2023-02-22 17:48 UTC by Numbers88s

This PR enables ranking on dotcom.

## Test plan
Tested manually.

2023-02-22 17:52 UTC, efritz requested changes
Let me submit a PR onto this branch that will do vacuuming for the new tables.

2023-02-22 17:52 UTC, Numbers88s commented
> 

For sure, thanks man.

2023-02-23 15:23 UTC, Strum355 commented on monitoring/definitions/shared/codeintel_ranking.go
> +				Standard.Count("reference rows processed")(ObservableConstructorOptions{
`Description: fmt.Sprintf("%s%s every %s", options.MetricDescriptionRoot, legend, options.RangeWindow.String()),`
Means this becomes `reference rows processed reference rows processed ...`, where `legend` is the input to `Standard.Count`

2023-02-23 16:11 UTC, efritz commented on monitoring/definitions/shared/codeintel_ranking.go
> +				Standard.Count("reference rows processed")(ObservableConstructorOptions{
![image](https://user-images.githubusercontent.com/103087/220964737-8a3d193a-8db3-4185-8548-85dc2dcaef42.png)

2023-02-23 16:13 UTC, Strum355 commented on monitoring/definitions/shared/codeintel_ranking.go
> +				Standard.Count("reference rows processed")(ObservableConstructorOptions{
Being super pedantic, as a non-knowledgeable person looking at this, i have no idea what they are :^)

2023-02-23 16:13 UTC, efritz commented on monitoring/definitions/shared/codeintel_ranking.go
> +				Standard.Count("reference rows processed")(ObservableConstructorOptions{
LOOM INCOMING

2023-02-23 16:39 UTC, efritz approved these changes

2023-02-23 18:39 UTC, merged