syntax highlighting: fix building grammars that require c++
sourcegraph/sourcegraph pull request #48267
Opened 2023-02-27 11:36 UTC by Strum355

blahblahblahcxxecosystemwasamistakeetcetc

## Test plan

2023-02-27 11:37 UTC, Strum355 commented on docker-images/syntax-highlighter/Dockerfile
> +RUN cargo fetch
Moving this here so that changing the below flags doesnt require the incredibly slow process of pulling all deps again and again

2023-02-27 11:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/Dockerfile
> +ENV RUSTFLAGS="-Clink-arg=-Wl,--dynamic-linker=/lib/ld-linux-aarch64.so.1"
The architecture should not be hard-coded here

2023-02-27 11:55 UTC, Strum355 commented on docker-images/syntax-highlighter/Dockerfile
> +ENV CFLAGS="-mno-outline-atomics"
unbelievable...

2023-02-27 12:03 UTC, olafurpg reviewed
We should add back at least one grammar like C++ to test that it works in CI

2023-02-27 13:11 UTC, olafurpg reviewed
Still missing `cpp_example.cc`. I use the following command to update the snapshots

```
cd crates/sg-syntax
cargo test sg_treesitter::test::test_all_files -- --nocapture || cargo insta accept
```

2023-02-27 13:15 UTC, Strum355 commented
> Still missing `cpp_example.cc`. I use the following command to update the snapshots
> 
> ```
> cd crates/sg-syntax
> cargo test sg_treesitter::test::test_all_files -- --nocapture || cargo insta accept
> ```

Added the example from your PR https://github.com/sourcegraph/sourcegraph/pull/48267/commits/91dc04ecfdf31d3f22c5e87cf69f3bcf76ca841d

2023-02-28 11:10 UTC, olafurpg commented on docker-images/syntax-highlighter/Dockerfile
> +RUN cargo fetch
Nice. This is a huge improvement to the edit/debug feedback look

2023-02-28 11:51 UTC, Strum355 commented
Closest coredump bt i could get @varungandhi-src 
```
#0  0x00000000000a6056 in ?? ()
#1  0x00007fddc43f79b8 in tree_sitter_cpp_external_scanner_create () at src/scanner.cc:98
#2  0x00007fddc45a0915 in ts_parser_set_language (self=0x555556591d00, language=0x7fddc57624e0 <language>) at src/./parser.c:1790
#3  0x00007fddc458b5d6 in tree_sitter::Parser::set_language (self=0x7fddc35ec800, language=...) at binding_rust/lib.rs:363
#4  0x00007fddc42c4b32 in tree_sitter_highlight::HighlightIterLayer::new<sg_syntax::sg_treesitter::index_language_with_config::{closure_env#0}> (source=&[u8](size=16273) = {...}, highlighter=0x7fddc35ec800, cancellation_flag=..., injection_callback=0x7fddc35ec4e8, 
    config=0x555556a22278, depth=0, ranges=Vec(size=1) = {...}) at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-highlight-0.20.1/src/lib.rs:345
#5  0x00007fddc42c4578 in tree_sitter_highlight::Highlighter::highlight<sg_syntax::sg_treesitter::index_language_with_config::{closure_env#0}> (self=0x7fddc35ec800, config=0x555556a22278, source=&[u8](size=16273) = {...}, cancellation_flag=..., injection_callback=...)
    at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-highlight-0.20.1/src/lib.rs:136
#6  0x00007fddc42cafe4 in sg_syntax::sg_treesitter::index_language_with_config (
    code="#include \"compiler/rule.h\"\n#include \"compiler/util/hash_combine.h\"\n\nnamespace tree_sitter {\nnamespace rules {\n\nusing std::move;\nusing std::vector;\nusing util::hash_combine;\n\nRule::Rule(const Rule &oth"..., lang_config=0x555556a22278)
    at crates/sg-syntax/src/sg_treesitter.rs:241
#7  0x00007fddc42caec3 in sg_syntax::sg_treesitter::index_language (filetype="cpp", 
    code="#include \"compiler/rule.h\"\n#include \"compiler/util/hash_combine.h\"\n\nnamespace tree_sitter {\nnamespace rules {\n\nusing std::move;\nusing std::vector;\nusing util::hash_combine;\n\nRule::Rule(const Rule &oth"...)
    at crates/sg-syntax/src/sg_treesitter.rs:202
#8  0x00007fddc42b3dbf in sg_syntax::sg_treesitter::test::test_all_files () at crates/sg-syntax/src/sg_treesitter.rs:587
#9  0x00007fddc42caa07 in sg_syntax::sg_treesitter::test::test_all_files::{closure#0} () at crates/sg-syntax/src/sg_treesitter.rs:568
#10 0x00007fddc42cd645 in core::ops::function::FnOnce::call_once<sg_syntax::sg_treesitter::test::test_all_files::{closure_env#0}, ()> () at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507
#11 0x00007fddc453e07f in core::ops::function::FnOnce::call_once<fn() -> core::result::Result<(), alloc::string::String>, ()> () at library/core/src/ops/function.rs:507
#12 test::__rust_begin_short_backtrace<core::result::Result<(), alloc::string::String>, fn() -> core::result::Result<(), alloc::string::String>> () at library/test/src/lib.rs:657
#13 0x00007fddc450f9ec in test::run_test::{closure#1} () at library/test/src/lib.rs:648
#14 core::ops::function::FnOnce::call_once<test::run_test::{closure_env#1}, ()> () at library/core/src/ops/function.rs:507
#15 0x00007fddc453d00a in alloc::boxed::{impl#45}::call_once<(), (dyn core::ops::function::FnOnce<(), Output=core::result::Result<(), alloc::string::String>> + core::marker::Send), alloc::alloc::Global> () at library/alloc/src/boxed.rs:2000
#16 core::panic::unwind_safe::{impl#23}::call_once<core::result::Result<(), alloc::string::String>, alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=core::result::Result<(), alloc::string::String>> + core::marker::Send), alloc::alloc::Global>> ()
    at library/core/src/panic/unwind_safe.rs:271
#17 std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=core::result::Result<(), alloc::string::String>> + core::marker::Send), alloc::alloc::Global>>, core::result::Result<(), alloc::string::String>> () at library/std/src/panicking.rs:483
#18 std::panicking::try<core::result::Result<(), alloc::string::String>, core::panic::unwind_safe::AssertUnwindSafe<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=core::result::Result<(), alloc::string::String>> + core::marker::Send), alloc::alloc::Global>>> () at library/std/src/panicking.rs:447
#19 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<alloc::boxed::Box<(dyn core::ops::function::FnOnce<(), Output=core::result::Result<(), alloc::string::String>> + core::marker::Send), alloc::alloc::Global>>, core::result::Result<(), alloc::string::String>> () at library/std/src/panic.rs:137
#20 test::run_test_in_process () at library/test/src/lib.rs:680
#21 test::run_test::run_test_inner::{closure#0} () at library/test/src/lib.rs:574
#22 0x00007fddc450a0d1 in test::run_test::run_test_inner::{closure#1} () at library/test/src/lib.rs:601
#23 std::sys_common::backtrace::__rust_begin_short_backtrace<test::run_test::run_test_inner::{closure_env#1}, ()> () at library/std/src/sys_common/backtrace.rs:121
#24 0x00007fddc450fa7b in std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure#0}<test::run_test::run_test_inner::{closure_env#1}, ()> () at library/std/src/thread/mod.rs:550
#25 core::panic::unwind_safe::{impl#23}::call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<test::run_test::run_test_inner::{closure_env#1}, ()>> () at library/core/src/panic/unwind_safe.rs:271
#26 std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<test::run_test::run_test_inner::{closure_env#1}, ()>>, ()> () at library/std/src/panicking.rs:483
#27 std::panicking::try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<test::run_test::run_test_inner::{closure_env#1}, ()>>> () at library/std/src/panicking.rs:447
#28 std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<test::run_test::run_test_inner::{closure_env#1}, ()>>, ()> () at library/std/src/panic.rs:137
#29 std::thread::{impl#0}::spawn_unchecked_::{closure#1}<test::run_test::run_test_inner::{closure_env#1}, ()> () at library/std/src/thread/mod.rs:549
#30 core::ops::function::FnOnce::call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<test::run_test::run_test_inner::{closure_env#1}, ()>, ()> () at library/core/src/ops/function.rs:507
#31 0x00007fddc48c54a3 in alloc::boxed::{impl#45}::call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2000
#32 alloc::boxed::{impl#45}::call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global> () at library/alloc/src/boxed.rs:2000
#33 std::sys::unix::thread::{impl#2}::new::thread_start () at library/std/src/sys/unix/thread.rs:108
#34 0x00007fddc48f3e68 in start () at ../src_musl/src/thread/pthread_create.c:192
#35 0x00007fddc48f4fa1 in __clone () at ../src_musl/src/thread/x86_64/clone.s:22
```

2023-03-01 15:20 UTC, olafurpg requested changes
Very excited to finally being able to add these grammars. Thank you @Strum355 for looking into this 🙏🏻 

This PR is missing cpp_example snapshot output

2023-03-01 15:20 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/build.rs
> +    println!("cargo:rustc-link-lib=static=stdc++");
Is this supposed to stay?

2023-03-01 15:27 UTC, Strum355 commented on docker-images/syntax-highlighter/crates/sg-syntax/build.rs
> +    println!("cargo:rustc-link-lib=static=stdc++");
yes, this file is what fixed the above issue (on x86_64 at least)

2023-03-01 15:27 UTC, Strum355 commented
> This PR is missing cpp_example snapshot output

Is this not it, or is it something else that is generated from this? https://github.com/sourcegraph/sourcegraph/pull/48267/files#diff-bc76e9a3c4777c2ad893b6a82d19d938e7e55f4da0cda2ee7bfa4c009aae98c6

2023-03-02 21:45 UTC, Strum355 commented on docker-images/syntax-highlighter/Dockerfile
> +RUN cargo fetch
This could be improved still, any changes to any other file unfortunately trigger an invalidation. The changes required are a bit non trivial so im not doing it now

2023-03-03 14:40 UTC, Strum355 commented on docker-images/syntax-highlighter/crates/sg-syntax/build.rs
> +    }
afaik this needs to be here because this is the crate in which linking with c++ code occurs, but I havent tested further and Im sick of it at this stage

2023-03-03 15:52 UTC, tjdevries approved these changes
green CI plus snapshot, LGTM

2023-03-03 16:01 UTC, olafurpg commented on docker-images/syntax-highlighter/crates/sg-syntax/build.rs
> +    #[cfg(target_arch = "x86_64")]
Might be worth adding a comment to explain why this is here considering how much work went into figuring it out

2023-03-03 16:01 UTC, olafurpg approved these changes
LET'S GOOO

2023-03-03 16:01 UTC, merged