build-tracker: keep better track of jobs
sourcegraph/sourcegraph pull request #48378
Opened 2023-02-28 21:38 UTC by burmudar

### Apologies for the big PR

### The following things have changed and I'd appreciate reviews on
* Build has moved to its own package, and instead of keeping track individual jobs, the Build now keeps track of Steps.
* Steps accumulate Jobs with the same name. A Step is able to determine its `FinalStatus`, which is done by looking at the last two Jobs to determine whether the step has Passed, Failed or is Fixed.
* All things Notification like has been moved to the notify package. The notifiy client no longer keeps track of teammates, instead, it keeps track of notifications that have been sent for a build. If a build wants to send an updated notification, the teammate is reused from the previous build.

## Test plan
Unit Tests and Integrations tests see this channel https://sourcegraph.slack.com/archives/C03MM9C63KQ

2023-03-03 09:09 UTC, jhchabran requested changes
Minor nits, looks great. Really appreciate the comments. Requesting changes for autogold, but otherwise, LGTM.

2023-03-03 09:09 UTC, jhchabran commented on dev/build-tracker/build/steps.go
> +	// Failed | Passed | Fixed
Thanks for taking the time to write this 🙏

2023-03-03 09:09 UTC, jhchabran commented on go.sum
> +github.com/hexops/autogold v1.3.1/go.mod h1:sQO+mQUCVfxOKPht+ipDSkJ2SCJ7BNJVHZexsXqWMx4=
Autogold v1 is banned now!

2023-03-09 17:08 UTC, burmudar commented on dev/build-tracker/build/build.go
> +func (b *Build) authorName() string {
Agreed! Will change it

2023-03-09 17:45 UTC, burmudar commented on go.sum
> +github.com/hexops/autogold v1.3.1/go.mod h1:sQO+mQUCVfxOKPht+ipDSkJ2SCJ7BNJVHZexsXqWMx4=
I did remove the use of it but still see it in the `go.sum` file even after `go mod tidy`

2023-03-09 17:48 UTC, burmudar commented on dev/build-tracker/build/build.go
> +	// for safer access to fields of the buildkite.Jobs. The name of the job is used as the key
The buildkite job has everything set as a pointer. So the wrapped Job provides "safer" access in it that it won't return null but the default value, like an empty string or 0

2023-03-09 17:50 UTC, jhchabran commented on go.sum
> +github.com/hexops/autogold v1.3.1/go.mod h1:sQO+mQUCVfxOKPht+ipDSkJ2SCJ7BNJVHZexsXqWMx4=
Strange. Let's try look from where this is coming from.

2023-03-10 07:16 UTC, burmudar commented on go.sum
> +github.com/hexops/autogold v1.3.1/go.mod h1:sQO+mQUCVfxOKPht+ipDSkJ2SCJ7BNJVHZexsXqWMx4=
It comes from our use of `github.com/hexops/valast` in enterprise/cmd/worker/internal/telemetry, so not directly imported by us - see https://github.com/hexops/valast/blob/main/go.mod#L7
```
go mod why "github.com/hexops/autogold"
# github.com/hexops/autogold
github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/telemetry
github.com/sourcegraph/sourcegraph/enterprise/cmd/worker/internal/telemetry.test
github.com/hexops/valast
github.com/hexops/valast.test
github.com/hexops/autogold
```

2023-03-10 07:17 UTC, burmudar commented on dev/build-tracker/build/build.go
> +		return fmt.Errorf("job name is empty")
Updated

2023-03-13 08:43 UTC, jhchabran approved these changes

2023-03-14 04:43 UTC, merged