internal/authz/azuredevops: Implement ValidateConnectoin
sourcegraph/sourcegraph pull request #48465
Opened 2023-03-01 15:35 UTC by indradhanush

## Test plan

- Tested locally
- Builds should pass

2023-03-01 15:52 UTC, sashaostrikov requested changes
You have a nil-pointer dereference probability in your code which needs to be fixed :)

We should add tests which would have caught it, shouldn't we?

2023-03-01 15:52 UTC, sashaostrikov commented on enterprise/internal/authz/azuredevops/provider.go
> +		_, err = client.GetAuthorizedProfile(ctx)
nil-pointer dereference alert :)
when `err` above is not nil, then the `client` is nil

2023-03-01 15:52 UTC, sashaostrikov commented on enterprise/internal/authz/azuredevops/provider.go
> +			allErrors = append(allErrors, fmt.Sprintf("%s:%s", conn.URN, err.Error()))
```suggestion
			allErrors = append(allErrors, fmt.Sprintf("%s:%s", conn.URN, err.Error()))
			continue
```

2023-03-02 09:07 UTC, indradhanush commented on enterprise/internal/authz/azuredevops/provider.go
> +		_, err = client.GetAuthorizedProfile(ctx)
That's a great catch - especially because my default test would not have caught that. Thank you. ❤️ 

I'm going to add a test case specifically to catch this as well.

2023-03-02 09:09 UTC, indradhanush commented on enterprise/internal/authz/azuredevops/provider.go
> +		_, err = client.GetAuthorizedProfile(ctx)
Hmm, seems like it's not that easy to test that without adding more if-this-is-a-test logic in the `NewClient` method. Let me know if the current tests look good or if I should do this anyway.

2023-03-02 09:25 UTC, sashaostrikov commented on enterprise/internal/authz/azuredevops/provider.go
> +		_, err = client.GetAuthorizedProfile(ctx)
yep, I can see that the only way to provoke an error is to break the URL. I think in this case we're fine :)

2023-03-02 09:25 UTC, sashaostrikov approved these changes
:shipit::shipit::shipit:

2023-03-02 09:42 UTC, mrnugget approved these changes

2023-03-02 12:25 UTC, indradhanush commented
Rebased off main after merging #48209. Had to force pushed. Nothing changed since the last review.

2023-03-02 12:39 UTC, merged