rename CACHE_DIR env var for searcher as well, and other follow-throughs
sourcegraph/sourcegraph pull request #48684
Opened 2023-03-05 06:30 UTC by sqs

- Prefer `SEARCHER_CACHE_DIR` env var name to `CACHE_DIR`.
- Use the `{SEARCHER,SYMBOLS}_CACHE_DIR` env var names in Dockerfiles, App init (`singleprogram`), and the single Docker image (`server`).
- Fix typos/grammar in the changelog and docs.

Also fixes a panic when lauching App: `env var "CACHE_DIR" already registered with a different description or value`.

## Test plan

TBD

2023-03-05 14:54 UTC, keegancsmith requested changes

2023-03-05 14:54 UTC, keegancsmith commented on cmd/searcher/Dockerfile
> +RUN mkdir -p ${SEARCHER_CACHE_DIR} && chown -R sourcegraph:sourcegraph ${SEARCHER_CACHE_DIR}
this will break backwards compatibility. If you specified cache_dir in k8s/etc your other environment it will be ignored. I think we used to do that by default (ie we had some k8s magic to refer to the pod name in cache_dir).

2023-03-06 00:15 UTC, sqs commented on cmd/searcher/Dockerfile
> +RUN mkdir -p ${SEARCHER_CACHE_DIR} && chown -R sourcegraph:sourcegraph ${SEARCHER_CACHE_DIR}
Yes, you are right. Thanks for pointing this out. This will make the default `SEARCHER_CACHE_DIR` (and same for `SYMBOLS_CACHE_DIR`) take precedence over the `CACHE_DIR` values set in k8s config at https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+cache_dir+repo:deploy&patternType=standard&sm=0&groupBy=repo.

Unfortunately, something like

```dockerfile
ENV SEARCHER_CACHE_DIR=${CACHE_DIR:-/mnt/cache/searcher}
```

would not work because the substitution would be applied at build time, not at runtime.

I believe the best fix is to revert these Dockerfile changes and make a note about the preferred env var name for setting this at runtime.

2023-03-06 00:20 UTC, sqs commented on cmd/searcher/Dockerfile
> +RUN mkdir -p ${SEARCHER_CACHE_DIR} && chown -R sourcegraph:sourcegraph ${SEARCHER_CACHE_DIR}
I reverted those changes and pushed a new commit to this PR.

2023-03-06 07:20 UTC, keegancsmith approved these changes

2023-03-06 07:24 UTC, merged