fix: rewrite html emit steps to fix multiline problems
sourcegraph/sourcegraph pull request #48769
Opened 2023-03-06 21:36 UTC by tjdevries

Fixes: https://github.com/sourcegraph/sourcegraph/issues/48657

## Test plan

- [ ] Re-enable languages
- [ ] Test that the highlighting works now
- [ ] Merge

2023-03-06 21:36 UTC, tjdevries commented
Honestly, the diff itself is not incredibly helpful to look at it because I needed to restructure the code to handle the problem of picking up in the middle of a multi-line occurrence. It was just too confusing without fixing this.

2023-03-07 13:21 UTC, olafurpg requested changes
Ouch, I hope your finger is OK and will recover quickly 😢 

I ran this locally and pushed a small commit enabling tree-sitter for C++, which allowed me to reproduce a case where highlighting is different in search results and the blob view

<img width="685" alt="CleanShot 2023-03-07 at 14 17 08@2x" src="https://user-images.githubusercontent.com/1408093/223433849-6c89f4e2-0d6f-444f-9af5-90f8db7a9b06.png">
<img width="666" alt="CleanShot 2023-03-07 at 14 17 14@2x" src="https://user-images.githubusercontent.com/1408093/223433840-efaf1a78-2b72-4e34-b007-6e34808fd629.png">

Link to reproduce https://sourcegraph.test:3443/search?q=context:global+lang:C%2B%2B+hello&patternType=standard&sm=1&groupBy=repo

Could we add some basic tests for the new `scipToHTML` function?

2023-03-07 13:21 UTC, olafurpg commented on cmd/frontend/internal/search/decorate.go
> +// TODO: I can't find any references to this function...?
Is this intentional?

2023-03-07 13:42 UTC, tjdevries commented on cmd/frontend/internal/search/decorate.go
> +// TODO: I can't find any references to this function...?
yeah, I could not find anywhere the function is referenced and would like to delete it... but tbh I don't understand how our graphql stuff works, so it might be possible that it is referenced somewhere?

2023-03-07 16:16 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.29 kb) | 0.00% (+0.29 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/tjdevries-multiline-ranges/compare-report.html;tab=live_object) for a full comparison between the commits 80174f6 and a34ac64 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-03-08 12:14 UTC, olafurpg approved these changes
LGTM 👍🏻 Let's go!

Thank you @tjdevries for fixing this so quickly

2023-03-08 12:14 UTC, olafurpg commented on cmd/frontend/internal/highlight/html_test.go
> +var telemetryDocument string
Instead of embedding a SCIP payload, we can use reprolang from the sourcegraph/scip repo, which is a pure-Go implementation of a SCIP indexer that we can update to emit `SyntaxKind` (I think it does now, but could)

2023-03-08 12:15 UTC, olafurpg commented
I rebased on top of main to resolve the conflict and bumped up the commit hash on the scip dependency to resolve a protobuf version resolution error after the rebase.

2023-03-08 13:11 UTC, merged