Add more ADO docs
sourcegraph/sourcegraph pull request #48773
Opened 2023-03-06 22:01 UTC by varsanojidan

## Test plan

docs changes

2023-03-06 22:04 UTC, varsanojidan commented
@indradhanush would you mind adding a section for permissions in doc/admin/external_service/azuredevops.md either in this PR or a follow up PR?

2023-03-07 09:22 UTC, mrnugget requested changes

2023-03-07 09:22 UTC, mrnugget commented on doc/admin/external_service/azuredevops.md
> +3. Next you will have to provide a [configuration](#configuration) for the Gerrit code host connection. Here is an example configuration:
```suggestion
3. Next you will have to provide a [configuration](#configuration) for the Azure DevOps connection. Here is an example configuration:
```

2023-03-07 09:22 UTC, mrnugget commented on doc/admin/external_service/azuredevops.schema.json
> +{
This should be a symlink instead. See the others:

```
φ ls -l doc/admin/external_service/*.schema.json
lrwxrwxrwx    42 thorstenball 21 Jan  2022 doc/admin/external_service/aws_codecommit.schema.json -> ../../../schema/aws_codecommit.schema.json
lrwxrwxrwx    43 thorstenball 21 Jan  2022 doc/admin/external_service/bitbucket_cloud.schema.json -> ../../../schema/bitbucket_cloud.schema.json
lrwxrwxrwx    44 thorstenball 21 Jan  2022 doc/admin/external_service/bitbucket_server.schema.json -> ../../../schema/bitbucket_server.schema.json
lrwxr-xr-x@   34 thorstenball  1 Feb 18:16 doc/admin/external_service/gerrit.schema.json -> ../../../schema/gerrit.schema.json
lrwxrwxrwx    34 thorstenball 21 Jan  2022 doc/admin/external_service/github.schema.json -> ../../../schema/github.schema.json
lrwxrwxrwx    34 thorstenball 21 Jan  2022 doc/admin/external_service/gitlab.schema.json -> ../../../schema/gitlab.schema.json
lrwxrwxrwx    36 thorstenball 21 Jan  2022 doc/admin/external_service/gitolite.schema.json -> ../../../schema/gitolite.schema.json
lrwxr-xr-x    38 thorstenball 14 Jul  2022 doc/admin/external_service/go-modules.schema.json -> ../../../schema/go-modules.schema.json
lrwxr-xr-x    40 thorstenball 14 Jul  2022 doc/admin/external_service/jvm-packages.schema.json -> ../../../schema/jvm-packages.schema.json
lrwxr-xr-x    40 thorstenball 14 Jul  2022 doc/admin/external_service/npm-packages.schema.json -> ../../../schema/npm-packages.schema.json
lrwxrwxrwx    50 thorstenball 21 Jan  2022 doc/admin/external_service/other_external_service.schema.json -> ../../../schema/other_external_service.schema.json
lrwxrwxrwx    36 thorstenball 21 Jan  2022 doc/admin/external_service/perforce.schema.json -> ../../../schema/perforce.schema.json
lrwxrwxrwx    39 thorstenball 21 Jan  2022 doc/admin/external_service/phabricator.schema.json -> ../../../schema/phabricator.schema.json
lrwxr-xr-x    43 thorstenball 14 Jul  2022 doc/admin/external_service/python-packages.schema.json -> ../../../schema/python-packages.schema.json
.rw-r--r--  1.8k thorstenball 28 Oct  2022 doc/admin/external_service/ruby-packages.schema.json
```

(Esxcept `ruby-packages.schema.json`)

2023-03-07 10:03 UTC, sashaostrikov reviewed
Looks good currently. There are a couple of fixes pending and also a part of doc from Indra. Will approve as soon as it is done 👍🏻

2023-03-07 10:03 UTC, sashaostrikov commented on doc/admin/external_service/index.md
> +We recognize there are other code hosts including CVS, SVN, and many more. Today, we do not offer native integrations with these code hosts and customers are advised to leverage [Src-srv-git](./non-g
nice :feelsgood:

2023-03-07 13:01 UTC, varsanojidan commented on doc/admin/external_service/azuredevops.schema.json
> +{
See, that makes a lot more sense 😅.

2023-03-07 13:02 UTC, varsanojidan commented on doc/admin/external_service/index.md
> +We recognize there are other code hosts including CVS, SVN, and many more. Today, we do not offer native integrations with these code hosts and customers are advised to leverage [Src-srv-git](./non-g
Gotta keep the docs relevant with the times 😛.

2023-03-07 13:47 UTC, mrnugget approved these changes

2023-03-07 13:48 UTC, merged