Support compact mode for the new search box UI (search result and blob pages)
sourcegraph/sourcegraph pull request #49173
Opened 2023-03-12 02:04 UTC by vovakulikov

Addresses search UI padding problem ([slack discussion](https://sourcegraph.slack.com/archives/C03CSAER9LK/p1678548618527699?thread_ts=1678361542.292339&cid=C03CSAER9LK))

| | Before | After |
| ----- | -------- |  -------- |
| Initial state | <img width="1113" alt="Screenshot 2023-03-11 at 22 51 05" src="https://user-images.githubusercontent.com/18492575/224519899-60e75361-dea9-425c-891f-ca7efbfaeb68.png"> | <img width="1113" alt="Screenshot 2023-03-11 at 22 51 03" src="https://user-images.githubusercontent.com/18492575/224519888-1df65561-4540-4b01-82dd-33436e126e6c.png"> |
| Focused state | <img width="1113" alt="Screenshot 2023-03-11 at 22 51 07" src="https://user-images.githubusercontent.com/18492575/224519879-083605bc-7286-45f3-bcb3-64fefcd4e2cd.png"> | <img width="1113" alt="Screenshot 2023-03-11 at 22 50 42" src="https://user-images.githubusercontent.com/18492575/224519864-54a34cbf-3899-4f7c-91e2-97fc6ae6f286.png"> |

## Notes
- Home page search input isn't affected by this change (it still uses standard UI mode)
- @rrhyne I implemented this in the way you suggested in the thread (added a thin border around input in focus state), but let me know if you want to try the no around-border approach, No borders-approach in the image below
<img width="600" alt="Screenshot 2023-03-11 at 22 57 50" src="https://user-images.githubusercontent.com/18492575/224519986-756f897d-3266-4d09-82b3-aa75b8f0c8a2.png">

- @rrhyne, I'm not sure about the padding in the suggestion panel, I tried to keep alignment with the history icon buttons, but it may feels like it's too close to the borders in the compact mode. Let me know if we can ignore alignment with history icon and make the padding bigger there.
- @fkling I re-layout the previous version and tried to simplify styles and HTML in the search box UI, I didn't figure out why we had to use resize observer there if this input doesn't support multiple (and always has the same height value) but let me know if there is a case for this, I think we could bring back resize observer and don't use hardcoded values for padding in CSS) 

## Test plan
- Check the Home page old/new search UI 
- Check the search result page old/new search UI 
- Check file page old/new search UI

2023-03-12 02:12 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.19 kb) | -0.02% (-2.80 kb) | -0.03% (-2.99 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/vk/fix-search-box-paddings/compare-report.html;tab=live_object) for a full comparison between the commits 692ef4d and 4dc6c24 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-03-13 13:18 UTC, rrhyne commented
Thanks Vova! 

This is a bit tighter than intended, which makes it feel a bit cramped. Here's a more precise layout than my screenshot above denoting intended margins and padding:

https://www.figma.com/file/aenTj3SG2zl1g90HcMDUm2/RFC-760-WIP%3A-Rebooting-the-search-input-UI?node-id=2539%3A49324&t=DM3bGm7H0DRsvQH8-4

2023-03-13 16:48 UTC, vovakulikov commented
@rrhyne thanks for taking a look, I update spacing so it's ready for the second round.

2023-03-13 16:50 UTC, rrhyne approved these changes
Looks great Vova, thanks for the agency and the adjustments!

2023-03-13 17:33 UTC, fkling requested changes
> I re-layout the previous version and tried to simplify styles and HTML in the search box UI, I didn't figure out why we had to use resize observer there if this input doesn't support multiple (and always has the same height value) but let me know if there is a case for this, I think we could bring back resize observer and don't use hardcoded values for padding in CSS)

The current implementation uses `position: absolute`, which means that the dimensions of the element are not taken into account when computing the position of other, normal, "flow" elements.

I think there was a problem with the timing of rendering CodeMirror and that caused the container to have a height of `0`, causing elements to shift "underneath" the query input.

So I had to somehow update the height of the container/spacer element as soon as CodeMirror rendered, and using resize observer was the only way I could think of.

Now, I've refactored the CodeMirror implementation in the meantime and maybe things are happening in a better order now.

However, I think you are running in a similar problem with your implementation: On mobile, if there are no suggestions, the padding doesn't extend around the input:

![2023-03-13_18-12](https://user-images.githubusercontent.com/179026/224779909-4c468629-4881-44c5-a7e0-677ca0714f63.png)

(It's actually worse: The first suggestions are hidden underneath the input)

I also noticed that if there are no suggestions there is more padding at the bottom than at the top. Maybe not an issue (or maybe desired?) but I think it looks better if it's symmetrical: 

![2023-03-13_17-55](https://user-images.githubusercontent.com/179026/224780423-1d19448e-f434-4c55-90f1-64c1ebd69dd3.png)


There are also some z-index issues with the tabs on the homepage:

![2023-03-13_18-10](https://user-images.githubusercontent.com/179026/224780569-add42919-ec78-4a7b-9883-061806075ef4.png)

2023-03-13 17:33 UTC, fkling commented on client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
> +    valueRef.current = value
This needs to be 

```suggestion
    useEffect(() => {
      valueRef.current = value
    }, [value])
```

Refs are not supposed to be read or written to during render (as I recently learned).

2023-03-13 17:33 UTC, fkling commented on client/branded/src/search-ui/input/experimental/codemirror/syntax-highlighting.ts
> +            padding: '1px 4px',
Unfortunately CodeMirror doesn't seem to handle this very well (at least on Firefox), which is why I didn't add horizontal padding: It looks like there was a space between the character and the cursor even though there was not (the display was `<filter> <padding> <cursor>` instead of `<filter> <cursor> <padding>`).
I found that to be confusing.


https://user-images.githubusercontent.com/179026/224781787-65a547c5-ec7b-4519-ad98-c94d3c747058.mp4

2023-03-13 17:55 UTC, vovakulikov commented on client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
> +    valueRef.current = value
@fkling just our of curiosity, what may happen if we update value during render? I thought that refs are just plain JS objects so they retain their values between renders. 

I know that documentations says that we shouldn't do this https://beta.reactjs.org/learn/referencing-values-with-refs#best-practices-for-refs

but I just don't see how it would hurt in this particular case with callbacks.

2023-03-13 18:13 UTC, vovakulikov commented on client/branded/src/search-ui/input/experimental/codemirror/syntax-highlighting.ts
> +            padding: '1px 4px',
Fair enough, reverting this

2023-03-13 19:26 UTC, vovakulikov commented
@fkling thanks for your review

> I think there was a problem with the timing of rendering CodeMirror and that caused the container to have a height of 0, causing elements to shift "underneath" the query input.

I think it's still there actually, there is a moment when we render input for the first time there is a flash because we haven't updated height props there 

https://user-images.githubusercontent.com/18492575/224809704-0ecc058b-084c-4e49-b259-1834af014794.mov

Stop frame from the video above with bad state when height hasn't get its height yet

![image](https://user-images.githubusercontent.com/18492575/224810070-491b6ffc-87a6-4085-aba6-d0459e2bc04d.png)


- I tested this PR implementation and didn't catch any jumps (I think because the new layout doesn't rely on height we wouldn't have this problem with async jumps)
- Additional padding problem is solved (there is no padding if we don't have suggestion). Feedback about rendering flow: I've found this very difficult it figure out when and where we render suggestion block because of Wrapper → Code Mirror → Suggestion UI. I think we were discussing this previously in lights of Code Mirror tooltip UI. I personally thing that sharing state from Code Mirror though context and keep UI rendering in react would be better approach here
- Cool catch with sourcegraph.com tabs overlaps, also fixed this. 

It's ready for the second round, thanks

2023-03-13 20:25 UTC, fkling commented on client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
> +    valueRef.current = value
The update might never be committed and then the ref could potentially refer to an incorrect value, or something like that?
Regardless, I'd follow to docs and be consistent. We cannot except everyone to understand the finer nuances of React.

2023-03-13 20:30 UTC, vovakulikov commented on client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
> +    valueRef.current = value
Agree, I will apply you suggestions with useEffect

>The update might never be committed and then the ref could potentially refer to an incorrect value, or something like that?

To be honest, I still don't understand, even if something has been interrupted and never committed this won't happen in a middle of the component. So the component itself should be in  inconsistent state.  I see some cases with closure when we read and write in rendering but in this case it always read in user input based callbacks, where when we read everything is settled

2023-03-13 20:32 UTC, vovakulikov commented on client/branded/src/search-ui/input/experimental/CodeMirrorQueryInputWrapper.tsx
> +    valueRef.current = value
If we really want to align with approach with user effect I suggest to talk about on our FE crew because our codebase is full of mutable write operation in rendering, if you have some specific examples it would be even cooler

2023-03-13 21:28 UTC, fkling approved these changes
Great, thank you for this!

Note: I made some changes to how static extensions are initialized, but that shouldn't affect your PR much (I just removed the function around the list to initialize them once).

2023-03-13 22:03 UTC, merged