Cloud private code host support docs
sourcegraph/sourcegraph pull request #49748
Opened 2023-03-21 07:41 UTC by filiphaftek

[issue](https://github.com/sourcegraph/pr-faqs/issues/69)

Private code hosts support documentation.

## Test plan

Not required for docs change.

2023-03-21 08:46 UTC, unknwon approved these changes

2023-03-21 09:23 UTC, bobheadxi requested changes

2023-03-21 09:23 UTC, bobheadxi commented on doc/cloud/index.md
> +To learn more about Private Code Host details and how customers can expose their private code host via AWS Private Link, refer to [our handbook](https://handbook.sourcegraph.com/departments/cloud/tec
> how customers can expose their private code host via AWS Private Link, refer to [our handbook]

IMO we shouldn't link handbook pages as official support docs, and rather more "here's how we operate X internally, check it out if you are interested" - maybe we should move the customer setup guide into docs.sourcegraph.com

2023-03-21 09:23 UTC, bobheadxi commented on doc/cloud/index.md
> +Solution architecture
```suggestion
Solution architecture:
```

2023-03-21 09:23 UTC, bobheadxi commented on doc/cloud/index.md
> +Sourcegraph Cloud connects to customer code hosts from 2 public NAT IPs. Customers can add Sourcegraph customer-dedicated IPs to their IP allowlist.
```suggestion
Sourcegraph Cloud connects to customer code hosts from 2 public NAT IPs. Customers can add the dedicated IPs for their Sourcegraph Cloud instance to an IP allowlist on their private code host.
```

2023-03-21 09:23 UTC, bobheadxi commented on doc/cloud/index.md
> +As part of enterprise tier, for customers having code host without public access deployed on AWS, Sourcegraph Cloud offers [high available site to site VPN solution](https://cloud.google.com/network-
```suggestion
As part of the [Enterprise tier](https://about.sourcegraph.com/pricing), Sourcegraph Cloud offers customers that have code hosts without public access deployed on AWS a [highly available site-to-site VPN solution](https://cloud.google.com/network-connectivity/docs/vpn/tutorials/create-ha-vpn-connections-google-cloud-aws) with [AWS Private Link](https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html) inside AWS's network, so that access to a private code host never occurs over the public internet.
```

2023-03-21 09:23 UTC, bobheadxi commented on doc/cloud/index.md
> +Site to site GCP with AWS VPN advantages:
```suggestion
Advantages of the site-to-site GCP to AWS VPN include:

```

2023-03-21 09:23 UTC, bobheadxi commented on doc/cloud/index.md
> +AWS Private Link advantages:
```suggestion
Advantages of AWS Private Link include:

```

2023-03-21 09:24 UTC, bobheadxi commented on doc/cloud/index.md
> +To learn more about Private Code Host details and how customers can expose their private code host via AWS Private Link, refer to [our handbook](https://handbook.sourcegraph.com/departments/cloud/tec
Also customers navigating to Cloud pages in the handbook will see an automatic banner that warns that handbook content is not to be used as source-of-truth user-facing documentation, because it has a lot of internal references and we play pretty loose with handbook docs:

![image](https://user-images.githubusercontent.com/23356519/226564462-bffadffd-f80f-4516-92a8-7d0364cd0969.png)

2023-03-21 20:04 UTC, coury-clark commented
this PR is flagged for backport but isn't merged yet, please either merge and backport or close quickly as the release is coming up!

2023-03-22 08:56 UTC, filiphaftek commented on doc/cloud/index.md
> +To learn more about Private Code Host details and how customers can expose their private code host via AWS Private Link, refer to [our handbook](https://handbook.sourcegraph.com/departments/cloud/tec
Agree 👍 updated docs not to link handbook guide from here.

2023-03-22 10:16 UTC, rafax commented on doc/cloud/index.md
> +### Private Code Host support
```suggestion
### Private Code Host support (AWS)
```

2023-03-22 10:18 UTC, rafax commented on doc/cloud/index.md
> +- ensures customer only opens connectivity to their code host inside AWS network
```suggestion
- connectivity to customer VPC is only available inside AWS network
```

2023-03-22 10:19 UTC, rafax commented on doc/cloud/index.md
> +- provides customer mechanism to select AWS Princincal (AWS Account or more granular), who can connect to their code host
```suggestion
-  ability to select AWS Principal (AWS Account or more granular) that can connect to customer code host
```

2023-03-22 10:19 UTC, rafax approved these changes

2023-03-22 11:27 UTC, merged