permissions-center: add a dot to status badge if some provider syncs failed.
sourcegraph/sourcegraph pull request #49964
Opened 2023-03-24 15:16 UTC by sashaostrikov

Test plan:
Local sg run and test.

### Demo

https://user-images.githubusercontent.com/94846361/227566230-db15292c-9058-4399-8e42-eaa08160a43e.mp4

Closes https://github.com/sourcegraph/sourcegraph/issues/49909

2023-03-24 15:18 UTC, kopancek commented
I think I'd rather see `PARTIAL_SUCCESS` or similar status instead of an orange badge that hides the information behind a hover.

2023-03-24 15:34 UTC, erzhtor approved these changes

2023-03-26 21:08 UTC, thenamankumar commented on client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
> +        codeHostStates.find(codeHostState => codeHostState.status) !== undefined
useMemo

2023-03-26 21:09 UTC, thenamankumar commented on client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
> +    const warningMessage = needsWarning ? 'Some of provider syncs were not successful' : undefined
`1/3 provider syncs were not successful`

2023-03-26 21:15 UTC, thenamankumar commented on client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
> +        codeHostStates.find(codeHostState => codeHostState.status) !== undefined
```javascript
const failingCodeHostSyncs = useMemo(() => codeHostStates.filter(({status}) => status === CodeHostStatus.FAILED).length, [codeHostStates])

const needsWarning = state === PermissionsSyncJobState.COMPLETED && failingCodeHostSyncs > 0
```

2023-03-26 21:15 UTC, thenamankumar commented on client/web/src/site-admin/permissions-center/PermissionsSyncJobNode.tsx
> +    const warningMessage = needsWarning ? 'Some of provider syncs were not successful' : undefined
```
`${failingCodeHostSyncs}/${codeHostStates.length} provider syncs were not successful.`
```

2023-03-26 21:18 UTC, thenamankumar requested changes
.

2023-03-26 21:21 UTC, thenamankumar commented
@sashaostrikov based on what @kopancek suggested, I think making the Completed badge fully orange rather than green is a better idea in case we have partial success. 

We can still show the message on hover but remove the orange dot.

2023-03-28 05:52 UTC, thenamankumar approved these changes

2023-03-28 05:56 UTC, thenamankumar commented
Is the font color in dark mode for all the warning badges blackish and not white? 

<img width="150" alt="image" src="https://user-images.githubusercontent.com/22571395/228141646-54d00d8c-becc-4549-8aad-85e24d5ee33a.png">

2023-03-28 06:09 UTC, sashaostrikov commented
> Is the font color in dark mode for the warning badges blackish and not white everywhere?

Yep, it's like that in both light/dark modes: https://storybook.sgdev.org/?path=/story/wildcard-badge--badges

2023-03-28 06:10 UTC, merged

2023-03-28 15:08 UTC, danielmarquespt commented
The problem with just changing the color is that Color Blind users will have an hard time perceiving the difference

![Screenshot 2023-03-28 at 16 07 24](https://user-images.githubusercontent.com/7814431/228282743-00baf3c9-c611-471e-a711-b4eb34c924ee.png)

Even though you can tell something is different about those two "completed" you can't tell which one is better than the other. 

I think we really need to change the label here.

@sashaostrikov

2023-03-28 16:40 UTC, mrnugget commented
How about `PARTIAL` as a label?

2023-03-29 06:56 UTC, sashaostrikov commented
@danielmarquespt @mrnugget 
I understand the concern. In order to introduce a new label (e.g. `PARTIAL`), I think we should also support filtering by this label (imagine user confusion when they see `PARTIAL` status, but cannot filter by it in a dropdown called `State` where any other state is listed except `PARTIAL`).

**Which means we should introduce some changes to our `worker` framework**, I can totally do it, and I think there is a way of making it nicely:
- add an error type which indicates partial success
- add related check [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/workerutil/worker.go?L402-420)

In this case we won't break any other code using worker, I'll just update the documentation and the code which uses new status (effectively only our worker at the moment).

**Here is the question**
Since we are basically introducing a new worker status, we need to make it as universal as possible, which includes its name and reason. `PARTIAL`/`PARTIAL_SUCCESS` sounds good to me and makes sense, because we clearly have a lot of batch-style processing in workers and having a partial success is really a thing. Regarding the name, anyway it will be a database/backend code representation, which can be made more concise or user-friendly in the UI of needed, so I'm happy with this wording: `PARTIAL`/`PARTIAL_SUCCESS`.

WDYT? As soon as it sounds good to you -- I'll implement it.

2023-03-29 07:16 UTC, mrnugget commented
Hmmm, I don't think we need or should change the `worker` framework. We could add another column instead, right? We do have `Post` handlers in workers, so we could check the result and then mark something as partial result. Would leave worker alone but give us additional results.

2023-03-29 07:30 UTC, sashaostrikov commented
@mrnugget 
Another column would make filtering weird, don't you think? It will become not only `WHERE status = 'COMPLETED'`, but in case of `PARTIAL` it would check for another column (maybe boolean `is_partial_success` or so).

But if we don't want to change how `worker` _works_, then it should be another column.

I like another column idea less, but it would be safer to implement, than changing the `worker` code.

I guess then I'll add a boolean column to the table.

2023-03-29 07:34 UTC, mrnugget commented
> It will become not only `WHERE status = 'COMPLETED'`, but in case of `PARTIAL` it would check for another column (maybe boolean `is_partial_success` or so).

Is that so bad?

I don't want to kill your argument by saying "let's do it my way", but the reason why I'm hesitant to add another status to `worker` is that this case here is pretty unique to our situation and _technically_ the job did _complete_, right? It finished, it did its work, the problem is that the work didn't yield the result that we want. I think the `worker_status` column should be about the _job_ status and not whether the _result_ of that job is what we want, especially if we don't retry.

Example: you have a job that that calculates average session duration for users, every day. some days some users don't log in. couldn't calculate a session duration for those users. the job still succeeds, right? even if the result is partial?

2023-03-29 07:45 UTC, sashaostrikov commented
> I think the worker_status column should be about the job status and not whether the result of that job is what we want, especially if we don't retry.

That makes a lot of sense, totally agree!

> Is that so bad?

Not really, feels a bit like diluting the status between 2 columns, but nothing much. Won't affect performance either.

Thanks for discussion, really quick and productive! 👍🏻 

Now I go and implement [this](https://github.com/sourcegraph/sourcegraph/issues/50089)