Add queue rank to permissions sync jobs table
sourcegraph/sourcegraph pull request #50195
Opened 2023-03-30 18:37 UTC by thenamankumar

Add queue rank to permission sync job items. This PR might be revered if it will not pass performance testing on production.

![image](https://user-images.githubusercontent.com/22571395/228932283-673d7792-1f29-45db-b54d-6686426c199f.png)

TODO
Test
- [ ] add unit tests

## Test plan
- unit tests need to be added

2023-03-30 20:52 UTC, vdavid approved these changes
Nice! Left some comments. I'll leave it up to you if you want to do the EXPLAIN ANALYZE before merging this, so approving.

2023-03-30 20:52 UTC, vdavid commented on internal/database/permission_sync_jobs.go
> +		columns = sqlf.Sprintf("%s, CASE WHEN queue_ranks.rank IS NOT NULL THEN queue_ranks.rank ELSE 0 END AS queue_rank", columns)
Btw, there's an index on `permissions_sync_jobs.state`, so the subquery should be fast:

<img width="615" alt="CleanShot 2023-03-30 at 22 47 44@2x" src="https://user-images.githubusercontent.com/2552265/228960823-feff36f5-7f15-4835-a57e-9118319a1cd1.png">

I'm just not sure about the query as a whole.

2023-03-31 06:17 UTC, sashaostrikov requested changes
LGTM! 👍🏻
Add some comments.
Requesting changes to add some tests before merging it

2023-03-31 06:17 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/authz.graphql
> +    queueRank: Int!
I think this can be a nullable parameter

2023-03-31 06:17 UTC, sashaostrikov commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +		if opts.State != "QUEUED" {
```suggestion
		if opts.State != database.PermissionsSyncJobStateQueued.ToGraphQL() {
```

2023-03-31 06:17 UTC, sashaostrikov commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +	opts := database.ListPermissionSyncJobOpts{WithQueueRank: true}
I'd make it other way around: not adding `WithQueueRank` here (because it happens in minority (~1/6) of cases, and flip the `if` below to:
```golang
if opts.State == database.PermissionsSyncJobStateQueued.ToGraphQL() {
  opts.WithQueueRank = true
}
```

2023-03-31 06:17 UTC, sashaostrikov commented on internal/database/permission_sync_jobs.go
> +			}
```suggestion
		} else if err := scanPermissionSyncJob(&job, rows); err != nil {
			return nil, err
```

2023-03-31 06:32 UTC, thenamankumar commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +	opts := database.ListPermissionSyncJobOpts{WithQueueRank: true}
Well, we want to show the rank by default, even if no filter is added. Like on the user permissions info page, there are no filters, but for a queued job, we want to show the rank. 

Here not including rank when state filter is selected and it is != queued is just a minor optimisation.

2023-03-31 06:43 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +		columns = sqlf.Sprintf("%s, CASE WHEN queue_ranks.rank IS NOT NULL THEN queue_ranks.rank ELSE 0 END AS queue_rank", columns)
The sub-query should be super quick given the index. And the join too, given the number of queued items at any time is not that big, as compared to size of the table. I did the EXPLAIN and things looked fine. 

Will do post-deployment tests as well.

2023-03-31 09:19 UTC, mrnugget commented on cmd/frontend/graphqlbackend/authz.graphql
> +    queueRank: Int!
FYI other worker jobs call this `placeInQueue` in the API. See: https://sourcegraph.sourcegraph.com/search?q=context%3Asourcegraph+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+placeInQueue%3A+Int&patternType=standard&sm=1&groupBy=path

2023-03-31 09:19 UTC, mrnugget commented on cmd/frontend/graphqlbackend/authz.graphql
> +    queueRank: Int!
Agree. Then you don't need that state check in frontend and can move it to backend.

2023-03-31 09:19 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +			) AS queue_ranks ON queue_ranks.id = permission_sync_jobs.id
For inspiration, take a look at what batch changes does: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@9c90bff/-/blob/migrations/frontend/squashed.sql?L1016-1028

They have a separate database view with precomputed rank from which they pull jobs. We don't have to do the view (as long as we don't need it), but the query might be interesting to look at.

Code Intel also computes rank: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@9c90bff645db034758396d7131761fc4bc8a28d8/-/blob/enterprise/internal/codeintel/autoindexing/internal/background/utils.go?L32:51-32:60#tab=references (not sure where exactly though)

2023-03-31 09:19 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +			if err := scanPermissionSyncJob(&job, rows); err != nil {
Can't we add `NULL` to the other select queries so that we can have a single scanner? Sometimes rank is `null` and sometimes it's a number, should work, no?

Multiple scanners make it hard to then construct slice scanners, etc.

2023-03-31 10:46 UTC, sashaostrikov commented on enterprise/cmd/frontend/internal/authz/resolvers/permissions_sync_jobs.go
> +	opts := database.ListPermissionSyncJobOpts{WithQueueRank: true}
Ah, okay, got it

2023-03-31 18:46 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +			if err := scanPermissionSyncJob(&job, rows); err != nil {
Scanner is used by create methods as well as the worker. It was getting too much of a headache to add that null to all other queries.

Tried that first. It made more sense to just have a separate scanner used in 1 single function vs making every function handle the nullable queryRank.

2023-04-01 08:36 UTC, mrnugget commented on internal/database/permission_sync_jobs.go
> +			if err := scanPermissionSyncJob(&job, rows); err != nil {
Hmmm, okay. Didn't think there'd be that many queries.

2023-04-04 08:07 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/authz.graphql
> +    queueRank: Int!
renamed

2023-04-04 08:08 UTC, thenamankumar commented on internal/database/permission_sync_jobs.go
> +			}
fixed

2023-04-04 08:08 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/authz.graphql
> +    queueRank: Int!
fixed

2023-04-04 08:29 UTC, mrnugget approved these changes

2023-04-04 08:30 UTC, sashaostrikov approved these changes
LGTM!

2023-04-04 08:37 UTC, merged