[feat] Add soft deleted user recovery restriction duration
sourcegraph/sourcegraph pull request #50380
Opened 2023-04-05 11:25 UTC by erzhtor

This PR adds a restriction to recover soft deleted users within 7 days. See [PRFAQ: Improved Licensing and Gating](https://docs.google.com/document/d/1Ft1EcyNnwy_VnWfZXygPBwzf6uRpVcoPUOLQ4ya-mFQ/edit#bookmark=id.b9m3rhsq0818)

> It restricts on the database store level, so API calls can't pass either.

## Test plan

## Screenshots
| Before | After |
| --: | :-- |
| <img width="1728" alt="image" src="https://user-images.githubusercontent.com/6717049/230065707-aae657f5-b81f-4d5a-96cb-120d997e3ea8.png"> | <img width="1728" alt="image" src="https://user-images.githubusercontent.com/6717049/230065431-641fecb2-3b85-421b-82be-4c12af8f42ca.png">|
| <img width="1728" alt="image" src="https://user-images.githubusercontent.com/6717049/230065759-91545af1-27a3-4c14-a240-2a3052d4ef0d.png"> | <img width="1728" alt="image" src="https://user-images.githubusercontent.com/6717049/230065522-23cee517-9327-4aa3-adb5-5cd3f7f4142b.png"> |

2023-04-05 11:26 UTC, erzhtor commented on internal/database/users.go
> +var UserRecoveryRestrictedDuration = 7 * 24 * time.Hour // 7 days
If we need to adjust the duration, this is the place to do. It will be picked up both on backend, frontend, error messages, UI popups.

2023-04-05 13:58 UTC, pjlast commented
Mentioned in [this](https://sourcegraph.slack.com/archives/C03GMM0F2BA/p1680291592818759) Slack thread, but I think we should take a different approach with this. Think we should keep discussion there (in Slack), or in the PRFAQ.

2023-04-06 05:05 UTC, thenamankumar requested changes
We never talked about setting a restriction on recovering users. We only discussed not allowing admins to delete the users again in the next 7/30 days. 

Also, this is under discussion and needs approval from Connor. Please don't rush.

2023-04-06 06:13 UTC, erzhtor commented
> We never talked about setting a restriction on recovering users. We only discussed not allowing admins to delete the users again in the next 7/30 days.

@thenamankumar I took a different approach to restrict recovery within a period because 
1. it was easier to implement, with no extra field to store last_deleted_at or smth
2. it doesn't sound like we don't allow you to delete users because we want your money, but we don't allow you to abuse our system 
3. it solves the issue with soft delete abuse

> Also, this is under discussion and needs approval from Connor. Please don't rush.

Thanks for pointing that out. I saw the conversation, and I created PR because it was a relatively simple change, and I wanted to get feedback from the team since we discussed during the last licensing sync that most of the licensing PRFAQ items can be done in parallel with other stuff that we are/will be doing.

2023-04-06 06:14 UTC, erzhtor commented
> Mentioned in [this](https://sourcegraph.slack.com/archives/C03GMM0F2BA/p1680291592818759) Slack thread, but I think we should take a different approach with this. Think we should keep discussion there (in Slack), or in the PRFAQ.

Thanks for the suggestion, @pjlast. Let's keep the conversation in Slack and based on the decision, we can proceed, change or close this PR.

2023-04-24 09:08 UTC, erzhtor commented
Closing as there are still ongoing discussions. We can re-open or create a new PR once clarified the approach. cc @kopancek, @pjlast

2023-04-24 09:08 UTC, closed without merging