permissions-center: add statistics to Permissions Center.
sourcegraph/sourcegraph pull request #50535
Opened 2023-04-11 15:37 UTC by sashaostrikov

Test plan:
Local sg run and tests.
Storybook updated.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/94846361/231214795-904b14e3-9c33-40c9-a7c4-ccaa150fc61a.png">

2023-04-11 15:58 UTC, thenamankumar commented on client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
> +                            />
Reduce the borders. This looks better and matches with the designs in figma
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/22571395/231220542-b492d2be-bf62-4d79-834b-215d9c5eb645.png">

2023-04-11 15:58 UTC, thenamankumar requested changes
add a changelog as well

2023-04-11 16:12 UTC, thenamankumar commented on client/web/src/site-admin/permissions-center/PermissionsSyncJobsTable.tsx
> +                            />
one thing i forgot to mention. We should also mention total user & repo counts. 0/199 Failing users. like this

2023-04-13 09:43 UTC, thenamankumar commented on client/web/src/site-admin/permissions-center/PermissionsSyncStats.tsx
> +                                setFilters({
You can do `setFilters((oldFilters)=> ({...oldFilters, state: newState}))`

No need to accept both filters & setFilters in props.

2023-04-13 09:47 UTC, thenamankumar approved these changes
May be try to match the fonts with the design. 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/22571395/231721944-ac4270fb-7c92-41d9-b47f-4f50d2af50a9.png">

2023-04-13 09:51 UTC, sashaostrikov commented on client/web/src/site-admin/permissions-center/PermissionsSyncStats.tsx
> +                                setFilters({
I guess we cannot do it here, because it's not the setter of a `useState` hook, which lets us do it, but it is a `(partialData: Partial<T>) => void` function of `useURLSyncedState` hook.

Or am I missing something?

2023-04-13 09:53 UTC, sashaostrikov commented
> May be try to match the fonts with the design. 

I'd ask @danielmarquespt here because I tend to reuse our existing components for UI uniformity instead of making many custom components that differ from each other, while effectively being the same thing.

2023-04-13 10:24 UTC, danielmarquespt commented
> > May be try to match the fonts with the design.
> 
> I'd ask @danielmarquespt here because I tend to reuse our existing components for UI uniformity instead of making many custom components that differ from each other, while effectively being the same thing.

Visually I prefer the new design, but being pragmatic I prefer we use the existing component instead of adding yet another style.

Rule of thumb: Consistent but ugly > Pretty but inconsistent

Also, keeping the same component allows for an easier fix in the future!

2023-04-13 10:25 UTC, sashaostrikov commented
> Rule of thumb: Consistent but ugly > Pretty but inconsistent

Yep, agree, that's my position as well!

Thanks!

2023-04-13 12:48 UTC, merged