batches: display note in dropdown if rollout windows are configured
sourcegraph/sourcegraph pull request #50608
Opened 2023-04-13 17:59 UTC by adeola-ak

closes #48217

checks if rollout windows are configured and displays a note about how changesets are processed if they are 

<img width="371" alt="CleanShot 2023-04-13 at 13 55 16@2x" src="https://user-images.githubusercontent.com/67931373/231843955-0f3e2907-56a2-4cc6-b9c1-5b4d6f3a1982.png">

## Test plan
Test with and without changesets to see the note

2023-04-13 18:07 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.28 kb) | 0.00% (+0.28 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/aa/rollout-notice/compare-report.html;tab=live_object) for a full comparison between the commits f62c93f and 24ed9ad or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-04-13 19:25 UTC, BolajiOlajide requested changes

2023-04-13 19:25 UTC, BolajiOlajide commented on client/web/src/enterprise/batches/DropdownButton.tsx
> +import { BatchChangeRolloutWindow } from '@sourcegraph/shared/src/schema/site.schema'
It seems this import is unused. We should remove it.

2023-04-20 17:35 UTC, merged

2023-04-25 02:37 UTC, courier-new commented on client/web/src/enterprise/batches/DropdownButton.tsx
> +                        <b>
Omg sorry I hate to be this person haha but I think we want `<strong`> here instead of `<b>`. `<b>` is mostly for stylistic bold text. It conveys no extra importance or emphasis. `<strong>` should be used for important text that should be emphasized, which is important because screen readers will convey this as more important text. In this case the note is something we want to emphasize, not just something we're styling differently.

2023-04-25 02:37 UTC, courier-new commented on client/web/src/enterprise/batches/DropdownButton.tsx
> +                {action.type === 'publish' && batchChangesRolloutWindows && batchChangesRolloutWindows.length > 0 ? (
Separately (and again, I regret only getting this feedback to you after you've merged this 🙈), but I think we want this on the publish as draft action type as well.