Add functionality for editing Cody messages
sourcegraph/sourcegraph pull request #51009
Opened 2023-04-21 23:29 UTC by SuperAuguste

Closes #50974 - I'll clean this up on Monday :)

## Test plan

Tested locally in VSCode and it *seems* to work - feel free to suggest additional testing methodologies :)

2023-04-21 23:36 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+1.27 kb) | 0.01% (+1.27 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/auguste/cody-edit-message/compare-report.html;tab=live_object) for a full comparison between the commits 7e3eaae and 629739e or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-04-21 23:50 UTC, abeatrix commented on client/cody-ui/src/chat/Transcript.tsx
> +import { ChatUITextAreaProps, EditButtonAction, EditButtonProps, FeedbackButtonsProps } from '../Chat'
```suggestion
import { ChatUITextAreaProps, EditButtonProps, FeedbackButtonsProps } from '../Chat'
```

2023-04-22 01:01 UTC, abeatrix requested changes
This is really really cool! So cool I went over a bit on the review so please let me know if my suggestions don't make sense 😆 
Most of them are just nits, except the new changes allow users to replace with an empty input so requesting a change on that 🙇‍♀️

2023-04-24 09:41 UTC, mrnugget commented
I pushed two commits that should help with the ESLint errors

2023-04-24 19:14 UTC, abeatrix commented on client/cody-ui/src/chat/TranscriptItem.tsx
> +                    inputHandler(value)
```suggestion
                    setFormInput(value)
```
nit: this way we can remove the `inputHandler` above

2023-04-24 19:27 UTC, abeatrix approved these changes
Nice! The update works great on my local vscode instance 👍

2023-04-24 19:51 UTC, SuperAuguste commented on client/cody-ui/src/chat/TranscriptItem.tsx
> +                    inputHandler(value)
Oops nice catch, copied this line-for-line from somewhere else in the codebase when it isn't necessary here 😅

2023-04-25 08:50 UTC, mrnugget commented
@SuperAuguste I'm gonna go ahead and merge this. Thanks!

2023-04-25 08:50 UTC, merged