Add hubspot event for Cody installation events
sourcegraph/sourcegraph pull request #51065
Opened 2023-04-25 00:25 UTC by dadlerj

## Test plan

Run Sourcegraph locally to confirm no errors

2023-04-25 00:27 UTC, dadlerj commented
Sorry Stephen, I don't know who to request a review from on this one and GitHub suggested you 😓 . Feel free to suggest someone, but hopefully this should be quick

2023-04-26 21:41 UTC, dadlerj commented
I just noticed that Stephen is out until next week 🤦 . 

I asked Cody who should review changes to this file, and I got this back:

>Based on the CODENOTIFY snippet you provided, `@mrnugget`, `@sourcegraph/dev-experience`, or `@vovakulikov` would likely be good developers to review a change to cmd/frontend/graphqlbackend/user_usage_stats.go.

Please feel free to tag someone else who should review!

2023-04-27 11:04 UTC, vovakulikov approved these changes
Heh, Thorsten also is out until next week. PR looks good to me, but just in case I'm missing something important, @sashaostrikov is this ok from a performance point of view to query user email in log events logic? I assume this is okay because we don't have millions of users but just double check

2023-04-27 11:15 UTC, sashaostrikov requested changes
Requested changes to make DB queries only on .com in order not to affect performance on other instances.

2023-04-27 11:15 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +	userPrimaryEmail, _, _ := r.db.UserEmails().GetPrimaryEmail(ctx, userID)
If this is related to .com only, let's make a DB query only in this case too. Otherwise, we will make a bunch of useless DB queries on all other instances:
```suggestion
    userPrimaryEmail := ""
	if envvar.SourcegraphDotComMode() {
	    userPrimaryEmail, _, _ = r.db.UserEmails().GetPrimaryEmail(ctx, userID)
    }
```

2023-04-27 11:15 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +		if args.Event == "CodyInstalled" && userID != 0 && userPrimaryEmail != "" && envvar.SourcegraphDotComMode() {
nit: IMHO reads better in the same order as described in a doc above:
```suggestion
		if envvar.SourcegraphDotComMode() && args.Event == "CodyInstalled" && userID != 0 && userPrimaryEmail != "" {
```

2023-04-27 11:16 UTC, sashaostrikov commented
@vovakulikov thanks for pinging me!

2023-04-27 15:13 UTC, dadlerj commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +	userPrimaryEmail, _, _ := r.db.UserEmails().GetPrimaryEmail(ctx, userID)
Great call!

2023-04-27 15:13 UTC, dadlerj commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +		if args.Event == "CodyInstalled" && userID != 0 && userPrimaryEmail != "" && envvar.SourcegraphDotComMode() {
Ack, thanks

2023-04-27 15:18 UTC, sashaostrikov approved these changes
LGTM :shipit:

2023-04-27 19:04 UTC, merged