dotcom: add subscription-based license tokens
sourcegraph/sourcegraph pull request #51074
Opened 2023-04-25 06:00 UTC by bobheadxi

Implements part of LLM-proxy auth (#50726):

1. Adds a new column, `access_token_sha256`, to the `product_licenses` table, so that we can query it when validating a token
   - Existing licenses that are not yet expired automatically get this populated. If set, this is a valid token for a subscription. This lets us have a bit of an escape hatch - we can "disable" tokens by removing `access_token_sha256` from a row, and maybe the ability to do this in the UI if we want.
   - New licenses automatically get this populated.
2. Right now, token format is a hash of the license token + a prefix. It's intentionally set up so that we can change the format if we want, with some internal plumbing for updating the value.
   - This will let customers self-serve tokens (in the future, potentially automatically generated mid-request is LLM-proxy access goes through a Sourcegraph instance)
   - This PR adds a simple UI to get the token (see below)
3. Adds a query to lookup a subscription and its traits by access token
   - This access will be granted to site admins + "service accounts" denoted by feature flag override on the account. LLM-proxy will get one for accessing this query

## Test plan

A few lightweight tests, and some manual tests:

![image](https://user-images.githubusercontent.com/23356519/234186923-08e1425b-50e8-4707-80c8-a2661bb00fce.png)

![image](https://user-images.githubusercontent.com/23356519/234187008-2164b3b2-e716-4775-9f06-6d7e3bef9e34.png)

![image](https://user-images.githubusercontent.com/23356519/234182009-4fe686cc-8bf9-4bef-a350-4c0ee358a821.png)

2023-04-25 06:08 UTC, sg-e2e-regression-test-bob commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.01% (+0.97 kb) | 0.01% (+0.97 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/dotcom_add_subscription-based_license_tokens/compare-report.html;tab=live_object) for a full comparison between the commits 9e80832 and 7f492bb or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-04-25 06:55 UTC, kopancek requested changes

2023-04-25 06:55 UTC, kopancek commented on client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
> +                            Access token
Putting the access token generation below the licenses is not a good idea. Imagine a situation, where you have 20 licenses and you need to scroll down to see the access token button.

Do we want to instead show this within the license field itself? That way the access token would be visually tied to the license, since that is what we do in the DB schema.

2023-04-25 06:55 UTC, kopancek commented on client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
> +                                    secret={true}
I don't think we need to keep this secret. It is a hash in the end that we would send over in HTTP headers.
```suggestion
```

2023-04-25 06:55 UTC, kopancek commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
> +		hashutil.ToSHA256Bytes(defaultRawAccessToken([]byte(licenseKey))),
Should we leave this as `NULL` and only set the column value when there is an actual access token? Would be easier to debug IMO. You can also then add a foreign key relationship to the `access_token_sha256` column.

2023-04-25 06:55 UTC, kopancek commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
> +func serviceAccountOrOwnerOrSiteAdmin(ctx context.Context, db database.DB, ownerUserID *int32) error {
There are no tests for this function. Given it's security related I think it is important to have them.

The code is not checking if the account is a service account, but is checking for a feature flag instead. Should we change the description accordingly? And possibly name of the function as well?

It probably also makes sense to move this to the `auth` package.

2023-04-25 06:55 UTC, kopancek commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
> +	}
If owner is not nil, should it be enough to check if it's the same user?
```suggestion
	if ownerUserID != nil {
		return auth.CheckSameUser(ctx, *ownerUserID)
	}
```

2023-04-25 06:55 UTC, kopancek commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
> +	return nil
Can be simplified using `basestore.ScanFirstInt`:
```suggestion
	query := sqlf.Sprintf("UPDATE product_licenses SET access_token_sha256=%s WHERE id=%s RETURNING id",
		hashutil.ToSHA256Bytes(value), licenseID)
	_, ok, err := basestore.ScanFirstInt(t.db.Query(ctx, query))
	if err != nil {
		return err
	}
	if !ok {
		return errLicenseNotFound
	}
	return nil
```

2023-04-25 06:55 UTC, kopancek commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
> +	return subscriptionID, nil
you could instead use [`basestore.ScanFirstString`](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/database/basestore/scan_values.go?L51) here.
```suggestion
	subID, _, err := basestore.ScanFirstString(t.db.Query(ctx, query))
	if err != nil {
		return "", errors.New("invalid token")
	}
	return subID, nil
```

2023-04-25 07:02 UTC, bobheadxi commented on client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
> +                            Access token
Good point on not having it below a potentially large list of licenses. However, I don't think it should be in the individual licenses, since although under the hood it is associated with individual licenses, the intent of a token is to represent a subscription and not a license itself. I imagine at some point we'll want to migrate away from this the key-based approach when the dust settles

2023-04-25 07:03 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/licenses_db.go
> +		hashutil.ToSHA256Bytes(defaultRawAccessToken([]byte(licenseKey))),
The upside of having it OOTB for new licenses licenses is so that instances can self-generate valid access tokens straight away, instead of needing a Sourcegraph teammate to set it up

2023-04-25 07:04 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
> +func serviceAccountOrOwnerOrSiteAdmin(ctx context.Context, db database.DB, ownerUserID *int32) error {
> The code is not checking if the account is a service account, but is checking for a feature flag instead. Should we change the description accordingly? And possibly name of the function as well?

The feature flag is the workaround to mark an account as a service account (see docstring above) - I think we don't have a formal representation of "service account" external to the application

2023-04-26 11:10 UTC, eseliger commented on client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
> +                                    secret={true}
I like that you don't accidentally leak it on a screen share or so, wdyt?

2023-04-26 13:55 UTC, unknwon commented on client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
> +                                    secret={true}
Agree on both sides so, I'll just tag @sourcegraph/security-code-review here 😂 🙏

2023-04-26 20:02 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
> +func serviceAccountOrOwnerOrSiteAdmin(ctx context.Context, db database.DB, ownerUserID *int32) error {
Aligned with @eseliger and @unknwon on the feature flag as SA approach, but I'll add some tests

2023-04-26 20:04 UTC, bobheadxi commented on client/web/src/enterprise/site-admin/dotcom/productSubscriptions/SiteAdminProductSubscriptionPage.tsx
> +                                    secret={true}
I think it doesn't really hurt to keep it hidden for the reasons above, and I don't think anyone's going to _really read_ it if it's visible, so let's keep it hidden for now :)

2023-04-26 23:51 UTC, bobheadxi commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
> +	}
Reverted this - the actor can either be an owner, or a site admin, so `CheckSiteAdminOrSameUser` is the right check

2023-04-27 08:18 UTC, kopancek approved these changes

2023-04-27 12:34 UTC, unknwon approved these changes
<img src="https://media1.giphy.com/media/NytMLKyiaIh6VH9SPm/giphy.gif"/>

2023-04-27 14:16 UTC, eseliger reviewed
a few inline questions, I think I'm slightly confused why we need to persist a sha and why we use the license over the subscription to store completions metadata. I'm sure I am just missing something.

2023-04-27 14:16 UTC, eseliger commented on cmd/frontend/graphqlbackend/dotcom.graphql
> +        productSubscriptionID: ID!
I think this would be a bit more graphql-y 

```suggestion
        productSubscription: ID!
```

2023-04-27 14:16 UTC, eseliger commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +ADD COLUMN IF NOT EXISTS access_token_sha256 BYTEA;
I probably misunderstood something, didn't we want to make these a subscription-level thing? 🤔

2023-04-27 14:16 UTC, eseliger commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +SET access_token_sha256 = digest(digest(license_key, 'sha256'), 'sha256')
if it's just the sha256 -- do we even have to store it in the DB? Or could we simplify and generate that on the fly in the resolver layer?

2023-04-27 15:07 UTC, bobheadxi commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +ADD COLUMN IF NOT EXISTS access_token_sha256 BYTEA;
No - _traits_ are subscription-level, but tokens still correspond to the key

2023-04-27 15:08 UTC, bobheadxi commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +SET access_token_sha256 = digest(digest(license_key, 'sha256'), 'sha256')
An additional column allows us the escape hatch to disable (as is done in this migration - it leaves expired licenses without this column populated)

2023-04-27 15:09 UTC, bobheadxi commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +ADD COLUMN IF NOT EXISTS access_token_sha256 BYTEA;
The alternative IMO is to give it a separate table, since we should be able to have multiple active tokens per subscription

2023-04-27 15:49 UTC, bobheadxi commented on cmd/frontend/graphqlbackend/dotcom.graphql
> +        productSubscriptionID: ID!
This currently aligns with the naming of the parameter in the existing `generateProductLicenseForSubscription` - I think maybe consistency wins out here? Happy to change it if you still think this is better though :)

2023-04-27 16:04 UTC, eseliger commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +SET access_token_sha256 = digest(digest(license_key, 'sha256'), 'sha256')
Could we make it a "disable boolean" field or so? One less persisted computed value to worry about :D

2023-04-27 16:08 UTC, eseliger commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +ADD COLUMN IF NOT EXISTS access_token_sha256 BYTEA;
That feels like a good idea. Do you think it'd be significantly more work? I see benefit in having licenses not too tightly coupled with completions access. 
Does it makes sense to just quickly talk about this again before we commit on the final approach to avoid back and forth?

2023-04-27 19:45 UTC, bobheadxi commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +SET access_token_sha256 = digest(digest(license_key, 'sha256'), 'sha256')
Fixed in https://github.com/sourcegraph/sourcegraph/pull/51074/commits/38c67e5bf620caeb8075f1ab4ffe6737c56b6cd6

2023-04-27 19:45 UTC, bobheadxi commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +ADD COLUMN IF NOT EXISTS access_token_sha256 BYTEA;
In call - this is probably too much up-front effort to "do right" at the moment, we should revisit a real access token management system if needed later

2023-04-27 20:12 UTC, eseliger approved these changes
let's go!

2023-04-27 20:12 UTC, eseliger commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/service_account.go
> +const featureFlagProductSubscriptionsServiceAccount = "product-subscriptions-service-account"
that is very smart!

2023-04-27 20:48 UTC, merged

2023-05-02 11:58 UTC, mrnugget commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +IS 'Whether this license key can be used as an access token to authenticate API requests';
For our complete API or just LLM proxy?

2023-05-02 13:35 UTC, rafax commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
> +	subID, _, err := basestore.ScanFirstString(t.store.Query(ctx, query))
Is it safe to assume we only get a single result row here? I think we can get more than one if:

- we have two identical licence keys (not sure if we have any guarantees on this)?
- SHA256 collision (not very likely :) )

2023-05-02 13:47 UTC, unknwon commented on enterprise/cmd/frontend/internal/dotcom/productsubscription/tokens_db.go
> +	subID, _, err := basestore.ScanFirstString(t.store.Query(ctx, query))
> * we have two identical licence keys (not sure if we have any guarantees on this)?

Practically this won't happen as we encode expiration in the license key and that means two license keys need to generate at the exact same time with exact same metadata with the exact same expiry.

 Though adding a unique constraint to the `product_licenses.license_key` column would help us sleep better :D



> * SHA256 collision (not very likely :) )

The world then has a problem 😂

2023-05-02 13:52 UTC, eseliger commented on migrations/frontend/1682114198_product_license_access_tokens/up.sql
> +IS 'Whether this license key can be used as an access token to authenticate API requests';
sourcegraph upstream services, like LLM and embeddings. Maybe we could clarify this a bit more though.