Fix history display/clear, add history load in VSCode
sourcegraph/sourcegraph pull request #51159
Opened 2023-04-26 15:47 UTC by SuperAuguste

Closes #51101 

## Test plan

Tested all sorts of variations (empty and save, loading and saving different sessions over and over again, etc.) locally in VSCode and everything seems fine.

2023-04-26 16:16 UTC, abeatrix requested changes
Left some comments but overall lgtm, love that we can pick up an old convo!

Requesting change due to type errors.

2023-04-26 16:16 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> +    public async clearAndRestartSession(): Promise<void> {
There are a few places giving type errors after changing this into an async function.

2023-04-26 16:16 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> +        await this.saveChatHistory()
Do we need to saveChatHistory on every steps since we have already performed `save` on each Completion End? 🤔 
https://github.com/sourcegraph/sourcegraph/blob/f46f23ca57afb79705f1a90a9e797284c4be8c1f/client/cody/src/chat/ChatViewProvider.ts#L252-L257

2023-04-26 16:32 UTC, SuperAuguste commented on client/cody/src/chat/ChatViewProvider.ts
> +        await this.saveChatHistory()
I saw this too but observed inconsistent behavior without saving chat history first :(

2023-04-26 16:40 UTC, abeatrix requested changes

2023-04-26 16:40 UTC, abeatrix commented on client/cody/src/command/LocalStorageProvider.ts
> +    private KEY_LOCAL_HISTORY = 'cody-local-chatHistory-v2'
Hmmm this case users won't have access to remove the items stored in `'cody-local-chatHistory'` anymore. Maybe instead of changing this, we can add a step to perform the migration?

2023-04-26 16:40 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> +        if (this.transcript && !this.transcript.isEmpty) {
```suggestion
        if (!this.transcript.isEmpty) {
```

2023-04-26 16:40 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> +        await this.localStorage.setChatHistory({
```suggestion
        await this.saveChatHistory()
```
Seems like this code is doing the same thing as `this.saveChatHistory()`?

2023-04-26 16:56 UTC, SuperAuguste commented on client/cody/src/chat/ChatViewProvider.ts
> +        await this.localStorage.setChatHistory({
There's actually a subtle difference - `saveChatHistory` performs a `this.chatHistory[this.currentChatID] = await this.transcript.toJSON()` which I don't want as we don't want the current chat session to also be in the history. I can probably make that assignment its own function?

2023-04-26 17:24 UTC, SuperAuguste commented on client/cody/package.json
> +        "title": "Chat History",
This command isn't under `menus.commandPalette` so it won't appear in the command palette (which was my intention). The label has no "Cody" prefix as this is the result I want:
<img width="296" alt="Screenshot 2023-04-26 at 1 24 06 PM" src="https://user-images.githubusercontent.com/19855629/234654502-e58f1454-b3fe-4269-acc9-eb0101893393.png">

2023-04-26 17:29 UTC, abeatrix commented on client/cody/package.json
> +        "title": "Chat History",
It shows up in CommandPalette by default unless you hide it: 
![image](https://user-images.githubusercontent.com/68532117/234655484-28e99c1b-8f71-4b1b-8747-48d9683c2812.png)

2023-04-26 17:47 UTC, SuperAuguste commented on client/cody/package.json
> +        "title": "Chat History",
Wow I totally missed that, thank you so much! I'll fix this and the other entries too :)

2023-04-27 19:15 UTC, abeatrix commented on client/cody/package.json
> +        "title": "Cody: Settings",
Thanks for cleaning this up! ❤️

2023-04-27 20:15 UTC, abeatrix approved these changes
Make some minor changes and did some clean up. This looks great to me thank you so much for working on it!!

2023-04-27 20:35 UTC, merged