WIP.
sourcegraph/sourcegraph pull request #51237
Opened 2023-04-27 22:49 UTC by efritz

Fixes #51173.

## Test plan

2023-05-02 18:33 UTC, DaedalusG commented
Testing against known drift in a docker-compose v3.33
```yaml
version: '2.4'
services:
  migrator:
    container_name: migrator
    image: 'index.docker.io/sourcegraph/migrator:5.0.2'
    cpus: 0.5
    mem_limit: '500m'
    command:
      ["drift", "-db=codeintel", "-version=v3.33.0"]
    environment:
      - PGHOST=pgsql
      - PGPORT=5432
      - PGUSER=sg
      - PGPASSWORD=sg
      - PGDATABASE=sg
      - PGSSLMODE=disable

      - CODEINTEL_PGHOST=codeintel-db
      - CODEINTEL_PGPORT=5432
      - CODEINTEL_PGUSER=sg
      - CODEINTEL_PGPASSWORD=sg
      - CODEINTEL_PGDATABASE=sg
      - CODEINTEL_PGSSLMODE=disable

      # If you are not running code insights, please see: 
      # https://docs.sourcegraph.com/admin/install/docker-compose/operations#database-migrations for more information
      # for information on how to configure Sourcegraph migrations
      - CODEINSIGHTS_PGHOST=codeinsights-db
      - CODEINSIGHTS_PGPORT=5432
      - CODEINSIGHTS_PGUSER=postgres
      - CODEINSIGHTS_PGPASSWORD=password
      - CODEINSIGHTS_PGDATABASE=postgres
      - CODEINSIGHTS_PGSSLMODE=disable
    restart: "on-failure"
    networks: 
      - sourcegraph
    depends_on:
      pgsql:
        condition: service_healthy
      codeintel-db:
        condition: service_healthy
```
```
λ ~/deploy-sourcegraph-docker/docker-compose/ v3.33.0* docker-compose up migrator
pgsql is up-to-date
codeintel-db is up-to-date
Recreating migrator ... done
Attaching to migrator
migrator                         | ✱ Sourcegraph migrator 5.0.2
migrator                         | ℹ️ Locating schema description
migrator                         | ✅ Schema found in Local file (/schema-descriptions/v3.33.0-internal_database_schema.json).
migrator                         | ✅ No drift detected
migrator                         | migrator exited with code 0
λ ~/deploy-sourcegraph-docker/docker-compose/ v3.33.0* docker-compose up migrator
codeintel-db is up-to-date
pgsql is up-to-date
Recreating migrator ... done
Attaching to migrator
migrator                         | ✱ Sourcegraph migrator 5.0.2
migrator                         | {"SeverityText":"FATAL","Timestamp":1683052252885738100,"InstrumentationScope":"migrator","Caller":"migrator/main.go:27","Function":"main.main","Body":"unknown schema \"codeintel-db\"","Resource":{"service.name":"migrator","service.version":"5.0.2","service.instance.id":"ffb76861-64e9-4074-8464-128cbfd7574b"},"Attributes":{}}
λ ~/deploy-sourcegraph-docker/docker-compose/ v3.33.0* docker-compose up migrator
pgsql is up-to-date
codeintel-db is up-to-date
Recreating migrator ... done
Attaching to migrator
migrator                         | ✱ Sourcegraph migrator 5.0.2
migrator                         | ℹ️ Locating schema description
migrator                         | ✅ Schema found in Local file (/schema-descriptions/v3.33.0-internal_database_schema.codeintel.json).
migrator                         | ❌ Drift detected!
migrator                         |
migrator                         | ❌ Unexpected definition of function "lsif_data_docs_search_private_delete"
migrator                         |
migrator                         | (
migrator                         |   	"""
migrator                         |   	... // 3 identical lines
migrator                         |   	AS $function$
migrator                         |   	BEGIN
migrator                         | + 	-- Decrement tally counting tables.
migrator                         |   	UPDATE lsif_data_apidocs_num_search_results_private SET count
migrator                         | = count - (select count(*) from oldtbl);
migrator                         |   	RETURN NULL;
migrator                         |   	... // 2 identical lines
migrator                         |   	"""
migrator                         |   )
migrator                         |
migrator                         | 💡 Suggested action: replace the function definition.
migrator                         |
migrator                         | CREATE OR REPLACE FUNCTION
migrator                         | public.lsif_data_docs_search_private_delete()
migrator                         |  RETURNS trigger
migrator                         |  LANGUAGE plpgsql
migrator                         | AS $function$
migrator                         | BEGIN
migrator                         | UPDATE lsif_data_apidocs_num_search_results_private SET count =
migrator                         | count - (select count(*) from oldtbl);
migrator                         | RETURN NULL;
migrator                         | END $function$;
migrator                         |
migrator                         | ❌ Unexpected definition of function "lsif_data_docs_search_private_insert"
migrator                         |
migrator                         | (
migrator                         |   	"""
migrator                         |   	... // 3 identical lines
migrator                         |   	AS $function$
migrator                         |   	BEGIN
migrator                         | + 	-- Increment tally counting tables.
migrator                         |   	UPDATE lsif_data_apidocs_num_search_results_private SET count
migrator                         | = count + (select count(*) from newtbl);
migrator                         |   	RETURN NULL;
migrator                         |   	... // 2 identical lines
migrator                         |   	"""
migrator                         |   )
migrator                         |
migrator                         | 💡 Suggested action: replace the function definition.
migrator                         |
migrator                         | CREATE OR REPLACE FUNCTION
migrator                         | public.lsif_data_docs_search_private_insert()
migrator                         |  RETURNS trigger
migrator                         |  LANGUAGE plpgsql
migrator                         | AS $function$
migrator                         | BEGIN
migrator                         | UPDATE lsif_data_apidocs_num_search_results_private SET count =
migrator                         | count + (select count(*) from newtbl);
migrator                         | RETURN NULL;
migrator                         | END $function$;
migrator                         |
migrator                         | ❌ Unexpected definition of function "lsif_data_docs_search_public_delete"
migrator                         |
migrator                         | (
migrator                         |   	"""
migrator                         |   	... // 3 identical lines
migrator                         |   	AS $function$
migrator                         |   	BEGIN
migrator                         | + 	-- Decrement tally counting tables.
migrator                         |   	UPDATE lsif_data_apidocs_num_search_results_public SET count
migrator                         | = count - (select count(*) from oldtbl);
migrator                         |   	RETURN NULL;
migrator                         |   	... // 2 identical lines
migrator                         |   	"""
migrator                         |   )
migrator                         |
migrator                         | 💡 Suggested action: replace the function definition.
migrator                         |
migrator                         | CREATE OR REPLACE FUNCTION
migrator                         | public.lsif_data_docs_search_public_delete()
migrator                         |  RETURNS trigger
migrator                         |  LANGUAGE plpgsql
migrator                         | AS $function$
migrator                         | BEGIN
migrator                         | UPDATE lsif_data_apidocs_num_search_results_public SET count =
migrator                         | count - (select count(*) from oldtbl);
migrator                         | RETURN NULL;
migrator                         | END $function$;
migrator                         |
migrator                         | ❌ Unexpected definition of function "lsif_data_docs_search_public_insert"
migrator   [...]

2023-05-02 19:00 UTC, DaedalusG commented
It looks like this PR won't correctly cover the inline sql comments `--`
<details>

```
λ ~/sourcegraph/ ef/51173* migrator drift -db codeintel -version v3.33.0
✱ Sourcegraph migrator 0.0.0+dev
ℹ️ Locating schema description
ℹ️ Reading schema definition in GitHub (https://raw.githubusercontent.com/sourcegraph/sourcegraph/v3.33.0/internal/database/schema.codeintel.json)... Schema not found (HTTP 404: https://raw.githubusercontent.com/sourcegraph/sourcegraph/v3.33.0/internal/database/schema.codeintel.json). Will attempt a fallback source.
✅ Schema found in GCS (https://storage.googleapis.com/sourcegraph-assets/migrations/drift/v3.33.0-internal_database_schema.codeintel.json).
❌ Drift detected!

❌ Unexpected definition of function "lsif_data_docs_search_private_delete"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Decrement tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_private SET count = count - (select count(*) from oldtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_private_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_private SET count = count - (select count(*) from oldtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_docs_search_private_insert"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Increment tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_private SET count = count + (select count(*) from newtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_private_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_private SET count = count + (select count(*) from newtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_docs_search_public_delete"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Decrement tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_public SET count = count - (select count(*) from oldtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_public_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_public SET count = count - (select count(*) from oldtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_docs_search_public_insert"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Increment tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_public SET count = count + (select count(*) from newtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_public_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_public SET count = count + (select count(*) from newtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_documentation_pages_delete"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Decrement tally counting tables.
  	UPDATE lsif_data_apidocs_num_pages SET count = count - (select count(*) from oldtbl);
  	UPDATE lsif_data_apidocs_num_dumps SET count = count - (select count(DISTINCT dump_id) from oldtbl);
  	... // 4 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_documentation_pages_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_pages SET count = count - (select count(*) from oldtbl);
UPDATE lsif_data_apidocs_num_dumps SET count = count - (select count(DISTINCT dump_id) from oldtbl);
UPDATE lsif_data_apidocs_num_dumps_indexed SET count = count - (select count(DISTINCT dump_id) from oldtbl WHERE search_indexed='true');
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_documentation_pages_insert"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Increment tally counting tables.
  	UPDATE lsif_data_apidocs_num_pages SET count = count + (select count(*) from newtbl);
  	UPDATE lsif_data_apidocs_num_dumps SET count = count + (select count(DISTINCT dump_id) from newtbl);
  	... // 4 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_documentation_pages_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_pages SET count = count + (select count(*) from newtbl);
UPDATE lsif_data_apidocs_num_dumps SET count = count + (select count(DISTINCT dump_id) from newtbl);
UPDATE lsif_data_apidocs_num_dumps_indexed SET count = count + (select count(DISTINCT dump_id) from newtbl WHERE search_indexed='true');
RETURN NULL;
END $function$;

{"SeverityText":"FATAL","Timestamp":1683053890537324000,"InstrumentationScope":"migrator","Caller":"migrator/main.go:21","Function":"main.main","Body":"database schema is out of sync","Resource":{"service.name":"migrator","service.version":"0.0.0+dev","service.instance.id":"4d37ee97-0ebd-4045-b35a-f6093811ced3"},"Attributes":{}}
```

</details>

2023-05-02 19:11 UTC, DaedalusG commented
Trying a different test
```
sourcegraph=# COMMENT ON TABLE versions IS 'tzeentch was here';
COMMENT
```
and running `migrator drift -db psql -version v4.5.1`
_Note that this is running a local migrator build against my local frontend db with versions set to v4.5.1 but the dbs schema is actually close to latest since its `sg`_

```

```

We're still seeing some comments in the diff unfortunately
```
❌ Unexpected comment of table "versions"
💡 Suggested action: change the table comment.

COMMENT ON TABLE versions IS '';
```

Also this one
```
❌ Unexpected properties of column "roles"."name"

schemas.ColumnDescription{
  	Name:       "name",
  	Index:      -1,
- 	TypeName:   "text",
+ 	TypeName:   "citext",
  	IsNullable: false,
  	Default:    "",
  	... // 3 identical fields
  	IsGenerated:          "NEVER",
  	GenerationExpression: "",
- 	Comment:              "The uniquely identifying name of the role.",
+ 	Comment:              "",
  }

💡 Hint: redefine the column using the definition at the following URL:

👉 https://sourcegraph.com/search?patternType=regexp&q=repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40v4.5.1+file%3A%5Emigrations%2Ffrontend%2Fsquashed%5C.sql%24+%28%5E%7C%5Cb%29CREATE%5CsTABLE%5Csroles%28%24%7C%5Cb%29+OR+%28%5E%7C%5Cb%29ALTER%5CsTABLE%5CsONLY%5Csroles%28%24%7C%5Cb%29
```

2023-05-02 19:51 UTC, DaedalusG commented
After a mishap it looks like this is working

```
sourcegraph=# \dt+  versions
                                         List of relations
 Schema |   Name   | Type  |    Owner    | Persistence | Access method | Size  |    Description
--------+----------+-------+-------------+-------------+---------------+-------+-------------------
 public | versions | table | sourcegraph | permanent   | heap          | 48 kB | tzeentch was here
 ```
 ^^ added this arbitrary comment and it doesnt show up in drift

<details>

 ```
 λ ~/ migrator drift -db frontend -version v4.5.1
✱ Sourcegraph migrator 0.0.0+dev
ℹ️ Locating schema description
ℹ️ Reading schema definition in Local file (/schema-descriptions/v4.5.1-internal_database_schema.json)... Schema not found (open /schema-descriptions/v4.5.1-internal_database_schema.json: no such file or directory). Will attempt a fallback source.
✅ Schema found in GitHub (https://raw.githubusercontent.com/sourcegraph/sourcegraph/v4.5.1/internal/database/schema.json).
❌ Drift detected!

❌ Missing enum "lsif_index_state"
💡 Suggested action: create the type.

CREATE TYPE lsif_index_state AS ENUM ('queued', 'processing', 'completed', 'errored', 'failed');

❌ Missing enum "lsif_upload_state"
💡 Suggested action: create the type.

CREATE TYPE lsif_upload_state AS ENUM ('uploading', 'queued', 'processing', 'completed', 'errored', 'deleted', 'failed');

❌ Unexpected definition of function "soft_deleted_repository_name"

strings.Join({
  	"CREATE OR REPLACE FUNCTION public.soft_deleted_repository_name(name text)",
  	" RETURNS text",
  	" LANGUAGE plpgsql",
- 	" STRICT",
  	"AS $function$",
  	"BEGIN",
- 	"    RETURN 'DELETED-' || extract(epoch from transaction_timestamp()) || '-' || name;",
+ 	"    IF name LIKE 'DELETED-%' THEN",
+ 	"        RETURN name;",
+ 	"    ELSE",
+ 	"        RETURN 'DELETED-' || extract(epoch from transaction_timestamp()) || '-' || name;",
+ 	"    END IF;",
  	"END;",
  	"$function$",
  	"",
  }, "\n")

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.soft_deleted_repository_name(name text)
 RETURNS text
 LANGUAGE plpgsql
 STRICT
AS $function$
BEGIN
    RETURN 'DELETED-' || extract(epoch from transaction_timestamp()) || '-' || name;
END;
$function$;

❌ Missing function "func_lsif_dependency_repos_backfill"
💡 Suggested action: define the function.

CREATE OR REPLACE FUNCTION public.func_lsif_dependency_repos_backfill()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
    BEGIN
        INSERT INTO package_repo_versions (package_id, version)
        VALUES (NEW.id, NEW.version);

        RETURN NULL;
    END;
$function$;

❌ Missing sequence "codeintel_lockfile_references_id_seq"
💡 Hint: define the sequence using the definition at the following URL:

👉 https://sourcegraph.com/search?patternType=regexp&q=repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40v4.5.1+file%3A%5Emigrations%2Ffrontend%2Fsquashed%5C.sql%24+%28%5E%7C%5Cb%29CREATE%5CsSEQUENCE%5Cscodeintel_lockfile_references_id_seq%28%24%7C%5Cb%29+OR+%28%5E%7C%5Cb%29nextval%5C%28%27codeintel_lockfile_references_id_seq%27%3A%3Aregclass%5C%29%3B%28%24%7C%5Cb%29

❌ Missing sequence "codeintel_lockfiles_id_seq"
💡 Hint: define the sequence using the definition at the following URL:

👉 https://sourcegraph.com/search?patternType=regexp&q=repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40v4.5.1+file%3A%5Emigrations%2Ffrontend%2Fsquashed%5C.sql%24+%28%5E%7C%5Cb%29CREATE%5CsSEQUENCE%5Cscodeintel_lockfiles_id_seq%28%24%7C%5Cb%29+OR+%28%5E%7C%5Cb%29nextval%5C%28%27codeintel_lockfiles_id_seq%27%3A%3Aregclass%5C%29%3B%28%24%7C%5Cb%29

❌ Missing sequence "codeintel_path_rank_inputs_id_seq"
💡 Hint: define the sequence using the definition at the following URL:

👉 https://sourcegraph.com/search?patternType=regexp&q=repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40v4.5.1+file%3A%5Emigrations%2Ffrontend%2Fsquashed%5C.sql%24+%28%5E%7C%5Cb%29CREATE%5CsSEQUENCE%5Cscodeintel_path_rank_inputs_id_seq%28%24%7C%5Cb%29+OR+%28%5E%7C%5Cb%29nextval%5C%28%27codeintel_path_rank_inputs_id_seq%27%3A%3Aregclass%5C%29%3B%28%24%7C%5Cb%29

❌ Missing index "batch_specs"."batch_specs_rand_id"
💡 Suggested action: define the index.

CREATE INDEX batch_specs_rand_id ON batch_specs USING btree (rand_id);

❌ Missing index "changeset_specs"."changeset_specs_rand_id"
💡 Suggested action: define the index.

CREATE INDEX changeset_specs_rand_id ON changeset_specs USING btree (rand_id);

❌ Unexpected column "changesets"."previous_failure_message"
💡 Suggested action: drop the column.

ALTER TABLE changesets DROP COLUMN previous_failure_message;

❌ Unexpected index "cm_action_jobs"."cm_action_jobs_trigger_event"
💡 Suggested action: drop the index.

DROP INDEX cm_action_jobs_trigger_event;

❌ Missing column "codeintel_path_ranks"."precision"
💡 Hint: define the column using the definition at the following URL:

👉 https://sourcegraph.com/search?patternType=regexp&q=repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40v4.5.1+file%3A%5Emigrations%2Ffrontend%2Fsquashed%5C.sql%24+%28%5E%7C%5Cb%29CREATE%5CsTABLE%5Cscodeintel_path_ranks%28%24%7C%5Cb%29+OR+%28%5E%7C%5Cb%29ALTER%5CsTABLE%5CsONLY%5Cscodeintel_path_ranks%28%24%7C%5Cb%29

❌ Unexpected column "codeintel_path_ranks"."id"
💡 Suggested action: drop the column.

ALTER TABLE codeintel_path_ranks DROP COLUMN id;

❌ Unexpected column "codeintel_path_ranks"."num_paths"
💡 Suggested action: drop the column.

ALTER TABLE codeintel_path_ranks DROP COLUMN num_paths;

❌ Unexpected column "codeintel_path_ranks"."refcount_logsum"
💡 Suggested action: drop the column.

ALTER TABLE codeintel_path_ranks DROP COLUMN refcount_logsum;

❌ Missing index "codeintel_path_ranks"."codeintel_path_ranks_repository_id_precision"
💡 Suggested action: define the index.

CREATE UNIQUE INDEX codeintel_path_ranks_repository_id_precision ON codeintel_path_ranks USING btree (repository_id, "precision");

❌ Missing index "codeintel_path_ranks"."codeintel_path_ranks_updated_at"
💡 Suggested action: define the index.

CREATE INDEX codeintel_path_ranks_updated_at ON codeintel_path_ranks USING btree (updated_at) INCLUDE (repository_id);

❌ Unexpected index "codeintel_path_ranks"."codeintel_path_ranks_graph_key"
💡 Suggested action: drop the index.

DROP INDEX codeintel_path_ranks_graph_key;

❌ Unexpected index "codeintel_path_ranks"."codeintel_path_ranks_pkey"
💡 Suggested action: drop the index.

DROP INDEX codeintel_path_ranks_pkey;

❌ Unexpected index "codeintel_path_ranks"."codeintel_path_ranks_repository_id"
💡 Suggested action: drop the index.

DROP INDEX codeintel_path_ranks_repository_id;

❌ Unexpected index "codeintel_path_ranks"."codeintel_path_ranks_repository_id_updated_at_id"
💡 Suggested action: drop the index.

DROP INDEX codeintel_path_ranks_repository_id_updated_at_id;

❌ Unexpected trigger "codeintel_path_ranks"."insert_codeintel_path_ranks_statistics"
💡 Suggested action: drop the trigger.

DROP TRIGGER insert_codeintel_path_ranks_statistics ON codeintel_path_ranks;

❌ Unexpected trigger "codeintel_path_ranks"."update_codeintel_path_ranks_statistics"
💡 Suggested action: drop the trigger.

DROP TRIGGER update_codeintel_path_ranks_statistics ON codeintel_path_ranks;

❌ Missing index "event_logs"."event_logs_user_id"
💡 Suggested action: define the index.

CREATE INDEX event_logs_user_id ON event_logs USING btree (user_id);

❌ Unexpected column "gitserver_repos"."cloning_progress"
💡 Suggested action: drop the column.

ALTER TABLE gitserver_repos DROP COLUMN cloning_progress;

❌ Missing column "lsif_dependency_repos"."version"
💡 Hint: define the column using the definition at the following URL:

👉 https://sourcegraph.com/search?patternType=regexp&q=repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%40v4.5.1+file%3A%5Emigrations%2Ffrontend%2Fsquashed%5C.sql%24+%28%5E%7C%5Cb%29CREATE%5CsTABLE%5Cslsif_dependency_repos%28%24%7C%5Cb%29+OR+%28%5E%7C%5Cb%29ALTER%5CsTABLE%5CsONLY%5Cslsif_dependency_repos%28%24%7C%5Cb%29

❌ Unexpected column [...]

2023-05-02 20:20 UTC, DaedalusG commented
The `--` comments are still borked though
<details>

```
λ ~/sourcegraph/ ef/51173 migrator drift -db codeintel -version v3.33.0
✱ Sourcegraph migrator 0.0.0+dev
ℹ️ Locating schema description
ℹ️ Reading schema definition in Local file (/schema-descriptions/v3.33.0-internal_database_schema.codeintel.json)... Schema not found (open /schema-descriptions/v3.33.0-internal_database_schema.codeintel.json: no such file or directory). Will attempt a fallback source.
ℹ️ Reading schema definition in GitHub (https://raw.githubusercontent.com/sourcegraph/sourcegraph/v3.33.0/internal/database/schema.codeintel.json)... Schema not found (HTTP 404: https://raw.githubusercontent.com/sourcegraph/sourcegraph/v3.33.0/internal/database/schema.codeintel.json). Will attempt a fallback source.
✅ Schema found in GCS (https://storage.googleapis.com/sourcegraph-assets/migrations/drift/v3.33.0-internal_database_schema.codeintel.json).
❌ Drift detected!

❌ Unexpected definition of function "lsif_data_docs_search_private_delete"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Decrement tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_private SET count = count - (select count(*) from oldtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_private_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_private SET count = count - (select count(*) from oldtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_docs_search_private_insert"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Increment tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_private SET count = count + (select count(*) from newtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_private_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_private SET count = count + (select count(*) from newtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_docs_search_public_delete"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Decrement tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_public SET count = count - (select count(*) from oldtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_public_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_public SET count = count - (select count(*) from oldtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_docs_search_public_insert"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Increment tally counting tables.
  	UPDATE lsif_data_apidocs_num_search_results_public SET count = count + (select count(*) from newtbl);
  	RETURN NULL;
  	... // 2 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_docs_search_public_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_search_results_public SET count = count + (select count(*) from newtbl);
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_documentation_pages_delete"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Decrement tally counting tables.
  	UPDATE lsif_data_apidocs_num_pages SET count = count - (select count(*) from oldtbl);
  	UPDATE lsif_data_apidocs_num_dumps SET count = count - (select count(DISTINCT dump_id) from oldtbl);
  	... // 4 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_documentation_pages_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_pages SET count = count - (select count(*) from oldtbl);
UPDATE lsif_data_apidocs_num_dumps SET count = count - (select count(DISTINCT dump_id) from oldtbl);
UPDATE lsif_data_apidocs_num_dumps_indexed SET count = count - (select count(DISTINCT dump_id) from oldtbl WHERE search_indexed='true');
RETURN NULL;
END $function$;

❌ Unexpected definition of function "lsif_data_documentation_pages_insert"

(
  	"""
  	... // 3 identical lines
  	AS $function$
  	BEGIN
+ 	-- Increment tally counting tables.
  	UPDATE lsif_data_apidocs_num_pages SET count = count + (select count(*) from newtbl);
  	UPDATE lsif_data_apidocs_num_dumps SET count = count + (select count(DISTINCT dump_id) from newtbl);
  	... // 4 identical lines
  	"""
  )

💡 Suggested action: replace the function definition.

CREATE OR REPLACE FUNCTION public.lsif_data_documentation_pages_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE lsif_data_apidocs_num_pages SET count = count + (select count(*) from newtbl);
UPDATE lsif_data_apidocs_num_dumps SET count = count + (select count(DISTINCT dump_id) from newtbl);
UPDATE lsif_data_apidocs_num_dumps_indexed SET count = count + (select count(DISTINCT dump_id) from newtbl WHERE search_indexed='true');
RETURN NULL;
END $function$;

{"SeverityText":"FATAL","Timestamp":1683058591627819000,"InstrumentationScope":"migrator","Caller":"migrator/main.go:27","Function":"main.main","Body":"database schema is out of sync","Resource":{"service.name":"migrator","service.version":"0.0.0+dev","service.instance.id":"e5b740f9-adcd-4eeb-9cc8-8223fc6db756"},"Attributes":{}}
```

</details>

2023-05-02 20:21 UTC, DaedalusG requested changes
See testing below the main comment drift is fixed but we should address these inline comments

2023-05-02 22:16 UTC, efritz commented
@DaedalusG Updated, can you check the drift on 3.33 again?

2023-05-08 21:01 UTC, DaedalusG approved these changes

2023-05-08 21:03 UTC, merged