cody: cleanup the design of the VSCode History view
sourcegraph/sourcegraph pull request #51246
Opened 2023-04-28 08:03 UTC by toolmantim

As a warmup to starting work on the VSCode Extension, I did some cleanups of the design of the Cody VSCode chat history. This pushes the most important content in the history panel (the history items themselves) much higher, and moves the clear history to just a button next to the header (instead of a whole section).

| Before | After |
| - | - |
|  <img width="1618" alt="Screenshot 2023-04-28 at 5 17 40 pm" src="https://user-images.githubusercontent.com/153/235084313-6be3495f-72ee-4e97-953c-6f2921861f8e.png"> | <img width="1618" alt="Screenshot 2023-04-28 at 5 18 27 pm" src="https://user-images.githubusercontent.com/153/235084369-6a6f2ac6-0e12-4b4c-981b-814aa7aa3e07.png"> |

Notes:

* In the process of battling the default button styles, I switched it to use standard VSCodeButton elements, which give us a bunch of nice defaults for free (hover etc).
* There's probably more work that can be done in follow up PRs to bring it up to speed with #51072, and any new work in #51165, but this at least improves what we have now.
* There was a keyboard handler and tabindex in there, but I couldn't seem to get it to trigger. Would love help for adding it back in if it was working.

## Future Fixes / Discussions

1. When starting your first chat, and then clicking history, I was expecting it to appear in Chat History. But it's more like "Previous Chat Sessions" — you have to reload, or leave and come back, to have new things appear. I feel like the current live session could still be there at the top of the History (if there's been a message sent), and clicking it would just go back to it.
2. When clicking on a recipe, I thought it would start a new chat, and the old chat would end up in history. But it just adds to the current chat 🤔
3. If you use fixup, the chat messages (and therefore chat history buttons) are a bit empty and awkward. <img width="322" alt="Screenshot 2023-04-28 at 5 49 23 pm" src="https://user-images.githubusercontent.com/153/235087671-3e584ad2-0d8b-4f13-8c56-f0003b616414.png"> <img width="297" alt="Screenshot 2023-04-28 at 5 51 04 pm" src="https://user-images.githubusercontent.com/153/235087983-76601551-cdbc-4723-94d2-4e56cc6a54ce.png"><br> Perhaps it could say "I've updated your code." instead of "Here is my attempt at rewriting the selected code:"
4. Sometimes the history buttons contain escaped HTML, which would normally be rendered as HTML in the normal chat. It might be nice to fix that.

## Test plan

Would appreciate another person’s manual test of this, given it's my first contribution to the extension 🙏🏼

* With no history, open Chat History view, verify it works okay, and that Clear History button is disabled
* Perform a chat, reload the window, open Chat History view, verify buttons and labels
* Perform another chat, reload the window, open Chat History view, verify buttons and labels
* Click Clear History

2023-04-28 10:39 UTC, eseliger approved these changes
nice 🚀

2023-04-28 13:25 UTC, SuperAuguste approved these changes
I love it! Awesome design Tim!!

2023-04-28 19:13 UTC, abeatrix requested changes
Apart from the overflow issues as mentioned, I really like the new design, def much better than what we have now!

2023-04-28 19:13 UTC, abeatrix commented on client/cody/webviews/UserHistory.module.css
> +    flex-direction: column;
We might need to add overflow and wrap to the item container:
<img width="522" alt="image" src="https://user-images.githubusercontent.com/68532117/235232666-9c9c9ab8-b035-4065-a82f-a7a4ee9b7d47.png">

2023-04-28 19:13 UTC, abeatrix commented on client/cody/webviews/UserHistory.tsx
> +                                    <VSCodeButton
Here is a screenshot that shows the weird line in each buttons as reported previously in https://github.com/sourcegraph/sourcegraph/pull/50960 :
<img width="660" alt="image" src="https://user-images.githubusercontent.com/68532117/235233201-6381a078-5a55-4699-8101-73b7d8ff18a2.png">

2023-05-04 10:57 UTC, toolmantim commented on client/cody/webviews/UserHistory.module.css
> +    flex-direction: column;
Ooh good catch! Thanks @abeatrix. I've just updated it back to using our own `<button>` (styling the shadow root element is impossible), and fixed recipe buttons while I was there.

I couldn't replicate the wrapping problem though. Could you check this PR again with your local data? Thank you!

2023-05-04 14:48 UTC, abeatrix commented
I'm still seeing the overflow issue, maybe it's just me? 🤔 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/68532117/236244263-f770b9b3-87e4-429f-b336-c551de460047.png">

2023-05-04 16:52 UTC, abeatrix commented
Looks like it's fixed, we will need to update the dependencies for this: https://github.com/microsoft/vscode-webview-ui-toolkit/issues/384

2023-05-12 22:12 UTC, abeatrix commented on client/cody/webviews/UserHistory.module.css
> +    justify-content: center;
```suggestion
    justify-content: flex-start;
    width: 100%;
```
To fix centered text issue:

<img width="565" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/a5488447-0a71-4ddc-8f3d-4cb3116df385">

2023-05-12 22:19 UTC, abeatrix approved these changes
I've updated the package that has the fix for the max-width issue and looks like it works with your changes too.
The only issue is the `justify-content: center;` I mentioned above but other than that i think it's good to go :D 

Here is what it looks like on my side after updating from `center` to `flex-start` with width set to 100%:
![image](https://github.com/sourcegraph/sourcegraph/assets/68532117/366c52b8-5232-48bd-a10d-8abf2cee8312)

![image](https://github.com/sourcegraph/sourcegraph/assets/68532117/0b278b5f-0fb2-4ed8-a839-74a646cbac98)

2023-05-16 03:32 UTC, toolmantim commented
Amazing, thank you @abeatrix! I'll get this cleaned up and ready to go.

2023-05-23 08:59 UTC, toolmantim commented
This is ready to go

2023-05-23 09:46 UTC, merged