Apply Wolfi Cloud Instance Fixes
sourcegraph/sourcegraph pull request #51263
Opened 2023-04-28 13:00 UTC by willdollman

This PR contains all the fixes and tweaks I've made during the process of getting the wolfi-test cloud instance working.

## Test plan

- Manual testing on wolfi-test cloud instance

2023-05-03 14:00 UTC, jhchabran requested changes

2023-05-03 14:00 UTC, jhchabran commented on wolfi-packages/cadvisor.yaml
> +      uri: https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz
Small thing, is there a more reliable place to download this from? Sourceforge is notorious for injecting crap in tarballs :/

2023-05-03 14:00 UTC, jhchabran commented on enterprise/dev/ci/internal/ci/pipeline.go
> +				"latest", // TODO: Do not merge; used to simplify dev
@willdollman is the TODO still being here intentional?

2023-05-03 14:09 UTC, willdollman commented on wolfi-packages/cadvisor.yaml
> +      uri: https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz
There's a [github mirror](https://github.com/wcohen/libpfm4) but it's missing release tags for recent releases. We could pin a commit but that's quite icky.

The official Google cadvisor image build [uses a sourceforge tarball](https://github.com/google/cadvisor/blob/master/deploy/Dockerfile#L10) and the hash means we'd notice if it changes. Do you think that's good enough?

2023-05-03 14:11 UTC, willdollman commented on enterprise/dev/ci/internal/ci/pipeline.go
> +				"latest", // TODO: Do not merge; used to simplify dev
👍 I'm currently using this to speed up CI by only rebuilding specific images. Before merging I need to revert this change so it includes all Wolfi images again.

2023-05-03 15:20 UTC, jhchabran commented on wolfi-packages/cadvisor.yaml
> +      uri: https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz
Ok, you're right as long as we got the hash we're good :)

2023-05-17 11:46 UTC, willdollman commented on enterprise/dev/ci/internal/ci/pipeline.go
> +				"latest", // TODO: Do not merge; used to simplify dev
This has now been removed.

2023-05-18 09:48 UTC, merged