graphqlbackend: Support perforce changelists in repo and commits API
sourcegraph/sourcegraph pull request #51291
Opened 2023-05-01 12:08 UTC by indradhanush

- Pre-requisite to https://github.com/sourcegraph/sourcegraph/pull/51195
- Part of #46488

The changes in this PR were extracted from #51195 and then iterated upon once it was clear they need to be in a separate PR.

# Why 

We want to show changelist IDs for perforce depots in the UI instead of commit SHAs which is meaningless for a perforce user.

# What

In this PR, we introduce some growing changes to the repository and commits APIs. They are:

- Added a boolean `isPerforceDepot` to the Repositories API which will be true if a repo was converted from a perforce depot
- Added a new nullable string `changelistID` to the Commits API which will display the changelist ID
- If a repo was converted from a perforce depot, we parse the `Body` of of the commit object to return the original changelist message as the `Subject`

## Test plan

- Added unit tests
- Tested with UI updates (not part of this PR)

2023-05-02 14:26 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/schema.graphql
> +    """
Is this an appropriate design from a graphql perspective? IE is it more common to do things like implement a different interface/etc? I imagine there is an alternative design which makes it cleaner to add more perforce specific attributes without just adding more and more fields.

2023-05-02 14:29 UTC, indradhanush commented on cmd/frontend/graphqlbackend/schema.graphql
> +    """
I started in my initial approach of building a new resolver for perforce changes but quickly found myself reimplementing a lot of the existing commits API at which point it stopped feeling right. 

My main reasoning for adding this property was that we don't have a first class concept of a changelist at the moment and it's a derived property from a commit's subject for now which is why I thought to add it as a property here. 

Would you recommend to break this out into its own resolver?

2023-05-02 17:19 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/schema.graphql
> +    """
I don't think it has to be its own resolver re-implementing everything else. I'd rather just somewhat namespace this, eg this is `changelist: PerforceChangeList` or something. Alternatively you can do things in graphql queries like 

```
{
  your_normal_commit_fields
  ... on PerforceChangelist {
    changelistID
  }
}
```

then in the backend side you implement a method on the commit resolver which returns this information (I can't remember the exact details). I don't know if this actually makes sense in practice, I haven't touched this stuff in a long time. But these suggestions feel like they extend more nicely / namespace the perforce stuff nicely.

2023-05-03 13:37 UTC, keegancsmith requested changes

2023-05-03 13:37 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/git_commit.go
> +			r.logger.Error(err.Error())
use our error type rather than this message. I think generally we like static strings as the logger message.
```suggestion
			r.logger.Error("failed to parse p4 fusion commit subject", log.Error(err))
```

2023-05-03 13:37 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/repository.go
> +	return false
don't do this. use `r.repo(ctx)` to get hold of the repo and then you will always have it.

2023-05-03 13:37 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/git_commit.go
> +		subject, err := parseP4FusionCommitSubject(commit.Message.Subject())
the graphqlbackend package is quite a behemoth already. I recommend new code which contains business logic to go somewhere else and then the resolver code is very very lightweight. Can you update this PR to put the P4 parsing coding and the other non-graphql specific p4 code somewhere else?

It also feels a bit weird to update just this graphql resolver to massage the subject. But I don't have a better suggestion, so I guess lets do this. But it almost feels like in some other layer you want to translate git commit messages into a different format. To me it feels like that should just be done in the p4-fusion layer? IE all you are doing is translating the message here, why not just write the mssage you want in p4-fusion? That does sound a bit more hectic to do though.

2023-05-03 13:40 UTC, sashaostrikov approved these changes
LGTM! Left a couple of comments.

2023-05-03 13:40 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/git_commit_test.go
> +		commit := &gitdomain.Commit{
These 2 test cases have identical code, the only difference is the commit message itself, right?
Let's remove the duplication, shall we?

2023-05-03 13:40 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/git_commit_test.go
> +func TestGitCommitPerforceChangelist(t *testing.T) {
Let's add a test for a non-Perforce repo that will still query `perforceChangelist`, just in case.

2023-05-03 13:40 UTC, sashaostrikov commented on cmd/frontend/graphqlbackend/perforce_changelist_test.go
> +
```suggestion
```

2023-05-03 14:21 UTC, Strum355 commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
I remember this being something @mrnugget was worried about happening (similarly to adding additional `isX` `isY` stuff to the Repository and other types)

2023-05-03 14:22 UTC, Strum355 commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
One idea we were thinking of having as an adopted pattern in the packages side of things was moving to union types across the graphql API, but thatd be a much bigger endeavor (for which we had a staffing proposal under the packages project, unfortunately not going ahead this quarter :/ )

2023-05-03 14:29 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
I agree with this concern. Should probably use the same suggestion I used here https://github.com/sourcegraph/sourcegraph/pull/51291#discussion_r1182834582

Is your suggestion something along the lines of my second suggestion? IE rely on `... on PerforceRepo {`

2023-05-03 14:31 UTC, Strum355 commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
> Is your suggestion something along the lines of my second suggestion? IE rely on `... on PerforceRepo {`

I think along that line of thought, yea. In the client code you can switch on __typename and render differently (or different components entirely) based on that value to e.g. include or exclude stuff based on if its e.g. a PerforceRepo, PackageRepo, GitRepo etc

2023-05-03 14:33 UTC, Strum355 commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
That was originally the idea we had come up with in a chat between Philipp Spiess, Ryan Slade, Peter and myself. I had planned for it to be a subproject under this quarters packages project and for the idea to be picked up then by other non-git ecosystems, but alas no staffing.

2023-05-04 10:19 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
Agree with this. I think using an interface and switching between them on the client side is the better approach. @indradhanush on the Go side of things, you can also have two top-level structs that both embed the "parent" struct, so you'd only have to implement the conversion methods (i.e. `ToPerforceDepot() (PerforceDepotResolver, bool)`...) and the additional methods. (I haven't looked at the code yet, so you might have already done this)

2023-05-04 12:12 UTC, indradhanush commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
I just added a new enum `SourceType` on the repository which could keep this clean.

@mrnugget I didn't see your comment until now - does the new change look okay or some more change is needed?

2023-05-04 12:14 UTC, Strum355 commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
I think we're thinking more in terms of a union type rather than just denoting with a field. We're gonna end up with fields that dont make sense depending on the type e.g. stars for depots, changelists for git repos etc

2023-05-04 12:25 UTC, mrnugget commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
Yeah, exactly. Instead of having an enum and switch on that, you define an `interface` and have two things implement the interface.

In our case, this might not be a trivial change though, since you'd probably need to change the "main case" (git repository) in all providers. But maybe there's a way around that and make it gradual, i.e. define a `interface PerforceDepot` and then implement `ToPerforceDepot()` on the type you have here and return new type when it's a perforce depot.

2023-05-04 12:32 UTC, indradhanush commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
> In our case, this might not be a trivial change though, since you'd probably need to change the "main case" (git repository) in all providers. But maybe there's a way around that and make it gradual, i.e. define a interface PerforceDepot and then implement ToPerforceDepot() on the type you have here and return new type when it's a perforce depot.

My only concern is if this is the right time to be implementing this as an interface, since at the root of it all its still a git repo that we're presenting as a perforce depot by only tweaking the commit message and the commit ref. 

It would have made sense if we were to introduce perforce depots as first class citizens and then this change might have been a better time to do it then. What do you think?

2023-05-04 12:42 UTC, indradhanush commented on cmd/frontend/graphqlbackend/schema.graphql
> +    isPerforceDepot: Boolean!
Okay - let me give this a try and come back with what I find out.

2023-05-04 12:53 UTC, eseliger commented on cmd/frontend/graphqlbackend/git_commit.go
> +			r.logger.Error("failed to parse p4 fusio commit subject", log.Error(err))
```suggestion
			r.logger.Error("failed to parse p4 fusion commit subject", log.Error(err))
```

2023-05-04 13:41 UTC, keegancsmith approved these changes
backend LGTM. some comments inline, I'll leave it to the people who had the further slack discussion on API design to approve the graphql schema changes.

2023-05-04 13:41 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/git_commit.go
> +		subject, err := parseP4FusionCommitSubject(commit.Message.Subject())
Ok I agree with that point. I still think p4 specific business logic like this should not live inside the graphql resolver for a git commit subject. It feels alright that we inject something here though that looks like this. IE I am mostly taking issue with `strings.HasPrefix(commit.Message.Body(), "[p4-fusion") {` living here. It feels like the impact on this function should be mostly a single function call which works something like

```
if subject, ok = maybeTransformP4Subject(ctx, r.repoResolver, commit.Message); ok {
  return subject
}
```

Or alternatively based on slack discussions the design of this is gonna change a bit and the impl of subject resolver will live in something p4 specific.

2023-05-04 13:41 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/repository.go
> +	if r.innerRepo.ExternalRepo.ServiceType == extsvc.TypePerforce {
use the returned repo above, don't directly access innerRepo

2023-05-04 15:51 UTC, peterguy commented on cmd/frontend/graphqlbackend/git_commit.go
> +		subject, err := parseP4FusionCommitSubject(commit.Message.Subject())
Yep, pushing that code you mentioned into a function would be prettier and more portable.

2023-05-04 16:23 UTC, eseliger approved these changes
GQL schema change LGTM

2023-05-04 17:18 UTC, merged