batches: [bug fix] double layer scrollbar
sourcegraph/sourcegraph pull request #51443
Opened 2023-05-03 23:18 UTC by st0nebraker

Closes #49715 - Removes the double layer scrollbar. The issue was a duplicate `height: 100%` style on `#root` and the `LayoutPage.module.scss`.

### BEFORE:

https://user-images.githubusercontent.com/59381432/236071680-89d9119b-1821-41b4-965a-ecbada45c17d.mov

### AFTER:
https://user-images.githubusercontent.com/59381432/236071661-d43f8db3-5080-40cb-ae4b-0076d7644cb9.mov

## Test plan
- UI on batch changes preview page

2023-05-03 23:25 UTC, sourcegraph-buildkite commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| -0.00% (-0.01 kb) | -0.00% (-0.01 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/becca/fix-double-scroll-bug/compare-report.html;tab=live_object) for a full comparison between the commits f6c573e and 96dff2e or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-05-08 23:54 UTC, courier-new commented
HEY sorry this review is so delayed! I wanted to make sure we gave proper consideration and testing to this change since `LayoutPage` is a component that renders for literally every page of the web app. 🤯 I'm glad you were able to narrow in on a cause of the problem here, but it looks like this change might in turn cause a different regression, this time with the sticky nav bar. 😞

**Before (is sticky)**

https://user-images.githubusercontent.com/8942601/236960819-7709f745-4193-4fc4-93f4-acde0ffafc74.mov

**After (not so sticky 😢)**

https://user-images.githubusercontent.com/8942601/236960872-a96285a9-0854-4e54-a1ed-8b163eb16d25.mov

Do you think you could take another look and see if there are alternate ways to address the same problem?

2023-05-09 18:08 UTC, st0nebraker commented
Good eye 👁️ , thanks for catching that @courier-new! I pushed an update in [11b2706](https://github.com/sourcegraph/sourcegraph/pull/51443/commits/11b27067974e52dfff1af8291bf423dbd24cf610), changing the navbar position to `fixed` with a z-index & adding some padding to the container underneath the navbar to accommodate the change. I tested on a handful more changes and the regression seems gone. Let me know what you think of this solution! 🙏🏻  Updated the PR description as well


https://github.com/sourcegraph/sourcegraph/assets/59381432/d465891c-e859-48de-a049-a09e0e9b8ddb

2023-05-15 22:02 UTC, courier-new commented
At a glance this seems like a good option, but let's tag frontend-devs for review, too, since I'm short on time right now. 🙂

2023-05-17 02:53 UTC, vovakulikov commented
I think this may effect code insight floating panels, I will check this out tomorrow morning.

2023-05-17 21:03 UTC, limitedmage requested changes

2023-05-17 21:03 UTC, limitedmage commented on client/web/src/nav/NavBar/NavBar.module.scss
> +    z-index: 5;
This may not be a good idea. z-index can be a constant war with components needing bigger and bigger z-index values. I would consider using `position: sticky` instead, or figuring out the root cause of the double scrollbar.

2023-05-18 20:43 UTC, vovakulikov commented
@st0nebraker I agree with @limitedmage about changes, it seems too risky to me, I also think that I found a root cause of this problem. It looks like that in batch changes we use visually hidden component that actually renders element but hides it visually with the following styles 

```css
    border: 0px;
    clip: rect(0px, 0px, 0px, 0px);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0px;
    position: absolute;
    width: 1px;
    white-space: nowrap;
    overflow-wrap: normal;
```

As you can see that these styles position absolute this hided element. But since we don't have any positioned relatively elements in the tree if we go up from this visually hidden element it will be positioned based on the root element (where we have height 100% and don't suppose to have scrollbar) 

<img width="1116" alt="Screenshot 2023-05-18 at 17 40 43" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/7b3242c3-ced1-45d3-a270-eaaa0ec0f3bf">

So the fix is simple and `position:relative` to the layout container that `position:absolute` element won't go out of this block and won't cause additional scrollbar.

2023-05-18 21:35 UTC, limitedmage commented
Ahhh [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1154640) strikes again

2023-05-18 21:42 UTC, st0nebraker commented
How did you find that @vovakulikov ? Woah o_O.

Adding `position: relative` to every container of `<VisuallyHidden />` doesn't seem like a _great_ solution because there's two `<VisuallyHidden />` tags on this page, and 75 in our app. I'm looking if there's another a solution even higher up the tree to use once instead of potentially 75 times; 👀-ing at that thread @limitedmage

2023-05-18 21:45 UTC, limitedmage commented
An alternative to avoid having to add `position:relative` is to use `aria-label` instead of `VisuallyHidden` if possible. 

But [we do add `position:relative` in a few places](https://sourcegraph.com/search?q=context:global+https://bugs.chromium.org/p/chromium/issues/detail%3Fid%3D1154640+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+&patternType=lucky&sm=1&groupBy=repo). It only needs to be added when inside a flexbox I think.

2023-05-18 22:32 UTC, st0nebraker commented
Thanks for the suggestion & context @limitedmage! I tested with aria-labels, but went with the `position: relative` on the containers (with a code comment on the bug) because both these items sound weird with aria-labels on screen readers since they're reading so many dynamic variables; it flows better this way, in my opinion. Let me know what you think 🙏🏻

2023-05-18 22:35 UTC, st0nebraker commented on client/web/src/nav/NavBar/NavBar.module.scss
> +    z-index: 5;
https://github.com/sourcegraph/sourcegraph/pull/51443#issuecomment-1553742423

2023-05-18 22:46 UTC, courier-new commented
WOW thank you @vovakulikov and @limitedmage for your analysis and alternative suggestions here. How sneaky and bizarre! 🤯

2023-05-18 23:12 UTC, limitedmage approved these changes

2023-05-19 01:07 UTC, courier-new approved these changes

2023-05-19 01:07 UTC, courier-new commented on client/web/src/enterprise/batches/Branch.tsx
> +    // Relative positioning needed needed to avoid VisuallyHidden creating a double layer scrollbar in Chrome.
```suggestion
    // Relative positioning needed to avoid VisuallyHidden creating a double layer scrollbar in Chrome.
```

2023-05-19 01:07 UTC, courier-new commented on client/web/src/enterprise/batches/detail/changesets/ChangesetStatusCell.tsx
> +    // Relative positioning needed needed to avoid VisuallyHidden creating a double layer scrollbar in Chrome.
```suggestion
    // Relative positioning needed to avoid VisuallyHidden creating a double layer scrollbar in Chrome.
```

2023-05-19 14:44 UTC, vovakulikov commented
@st0nebraker, sorry for the confusion; I meant that you need to add position relative to the root layout container (not adding position relative to each visually hidden element)

2023-05-19 16:11 UTC, limitedmage commented
> I meant that you need to add position relative to the root layout container (not adding position relative to each visually hidden element)

I'm not sure if this is a good idea as it might break elements that we want to purposefully position absolutely in the future. I think it's better to go with this minimal approach.

2023-05-19 16:40 UTC, merged