Ig/perforce changelist mapping
sourcegraph/sourcegraph pull request #51860
Opened 2023-05-12 10:17 UTC by indradhanush

## Test plan

2023-05-12 10:18 UTC, indradhanush commented on cmd/gitserver/server/server.go
> +	s.PerforceChangelistMappingQueue.push(&perforceChangelistMappingJob{repo: repo})
TODO: Check if repo is perforce depot before pushing.

2023-05-12 10:18 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +}
TODO: Duplicated code from GQL layer. Move to `internal/perforce` and use in both places.

2023-05-12 10:19 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +}
TODO: Pretty much a copy paste of CloneQueue to get this to start working. Use generics as a follow up.

2023-05-12 14:22 UTC, keegancsmith commented on cmd/gitserver/server/perforce.go
> +		cmd.Args = append(cmd.Args, fmt.Sprintf("%s..%s", lastMappedCommit, head))
You need to handle lastMappedCommit..head failing. eg
- gitserver disk being restored from backup meaning head is an ancestor of lastMappedCommit.
- lastMappedCommit no longer existing due to re-import from perforce. In this case you need to handle the sha <-> changelist mapping being invalid.

2023-05-12 14:37 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/perforce_changelist.go
>  var gitP4Pattern = lazyregexp.New(`\[(?:git-p4|p4-fusion): depot-paths = "(.*?)"\: change = (\d+)\]`)
out of interest do you know why git-p4 and p4-fusion use this format of trailers in git commit messages? Git has an official trailer format which integrates into commands. You've probably seen it before with things like co-authored-by: foo. If you are interested the docs are in PRETTY FORMATS section of git log, and `git help interpret-trailers`

2023-05-12 18:37 UTC, keegancsmith commented on cmd/frontend/graphqlbackend/perforce_changelist.go
>  var gitP4Pattern = lazyregexp.New(`\[(?:git-p4|p4-fusion): depot-paths = "(.*?)"\: change = (\d+)\]`)
FYI this regex is likely overly restrictive. Here is the code in git-p4 which actually parses these lines. I would imitate that, even though it doesn't properly support parsing quoted strings. https://github.com/git/git/blob/5bc069e383539824fd3a0d897100d44bbe1f8a24/git-p4.py#L1018-L1041

2023-05-13 04:51 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +		cmd.Args = append(cmd.Args, fmt.Sprintf("%s..%s", lastMappedCommit, head))
Thanks! This is what I'm thinking on how I should handle this:

1. Before invoking `newMappableCommits`, check if `git rev-parse <lastMappedCommit` works succesfully
2. If it is succesful, go ahead as above
3. If it fails, start a binary search on the list of commits mapped in the DB to find the `lastMappedCommit` in the DB that also exists in the repo on disk
4. When step 3 above returns with the correct `lastMappedCommit`, drop all rows in the DB following it for this repo
5. Start with step 2 to resume mapping from this point


What do you think?

2023-05-13 05:00 UTC, indradhanush commented
> What is the motivation for changelist mapping job living on gitserver? The hint to me that it maybe should live somewhere else is re-implementing logic like parsing HEAD and git log + exporting of logic that lives in the gitserver client for use in the server

I am seeing the changelist mapping job as a side effect of a clone / fetch operation for perforce depots. Initially I started to write this in the client and then it felt like an extra round of back and forth which we didn't need since all the information we need is already available in the clone / fetch stage inside Gitserver.

> The gitserver/server package is already quite large. This code atleast feels like it could live in a subpackage of server if indeed it belongs as part of gitserver's server.

👍

2023-05-13 05:12 UTC, indradhanush commented on cmd/frontend/graphqlbackend/perforce_changelist.go
>  var gitP4Pattern = lazyregexp.New(`\[(?:git-p4|p4-fusion): depot-paths = "(.*?)"\: change = (\d+)\]`)
> out of interest do you know why git-p4 and p4-fusion use this format of trailers in git commit messages? 

I do not know the historical reason behind git-p4 choosing this format, but p4-fusion most likely wanted to stay consistent with git-p4 except the `p4-fusion` string.

2023-05-15 10:33 UTC, mrnugget commented on cmd/gitserver/server/perforce.go
> +}
Why use this and not use our `workers`-databased-backed job? I'd say if there is one big lesson from a lot of gitserver stuff over the years it's that in-memory queues are hard to debug and often a source of bugs/confusion.

2023-05-15 11:09 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +}
I think that's a really good point and I agree, just didn't think of it. When I started this implementation I got easily influenced by the existing paradigm of the `CloneQueue` as something that works and the temptation to use this was too strong. :P

2023-05-15 11:09 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +}
To clarify - I'm now looking into implementing this as a worker job now.

2023-05-15 11:17 UTC, mrnugget commented on cmd/gitserver/server/perforce.go
> +}
Great. @alexAtSourcegraph and @thenamankumar did this for permission syncing, they can give you pointers.

Also, see the docs: https://docs.sourcegraph.com/dev/background-information/workers#adding-a-new-worker

(And take a look at the other workers that are running in `workers` process)

2023-05-16 08:09 UTC, keegancsmith commented on cmd/gitserver/server/perforce.go
> +		cmd.Args = append(cmd.Args, fmt.Sprintf("%s..%s", lastMappedCommit, head))
binary search is a fun solution here, I like it. Man having sequential revision IDs makes life so much nicer.

2023-05-16 08:13 UTC, keegancsmith commented
We have other bits of code in search and code-intel which react to commits coming in. But to be honest that stuff could be "faster" to react, and we want this to be super fast due to UX implications if it isn't. I do think in the future it would make sense for things like this not to be happening on gitserver, but for now moving the code into a sub-package and making minimal changes to the main server pkg itself sounds good to me.

This made me think, we need to make sure all code which consumes this information is aware it can be out of date.IE there will always be a delay (although small) where the changeset won't be mapped yet after a p4-fusion run.

2023-05-16 08:18 UTC, indradhanush commented
> This made me think, we need to make sure all code which consumes this information is aware it can be out of date.IE there will always be a delay (although small) where the changeset won't be mapped yet after a p4-fusion run.

Yes, the early plan is that we build out the mapping code and show a 404 for pages that depend on this and the information is not computed yet. In the meantime, we want to introduce a cache as a follow up that will serve as an alternative while the computation is in progress behind the scenes. But getting the functionality working on the ideal path of having the commit <-> changelist map created in the DB and then a user is able to access it is first priority.

2023-05-17 22:31 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +}
@mrnugget I wanted to leave a quick update on next steps in regards to this discussion:

I got on a call with @keegancsmith and @peterguy yesterday and discussed the pros and cons of using the worker vs using the clonequeue implementation and we all agreed that at the moment, the worker is adding unnecessary complexity by forcing us to have to send the git-log output over to the worker to process the job or on the other case do the job in the gitserver but just use the worker as a signaling mechanism.

The clonequeue implementation is well tested and proven to work reliably and given that this mapping job really needs to be done in gitserver there isn't a lot to be gained with adding the worker here. Additionally, we need the mapping job to complete as soon as possible and do not want to be held back in case the worker is backed up by other jobs. The urgency in completing the mapping job is required because without the mapping job completed a repo although cloned has partial functionality in the case of perforce depots.

We made some other design decisions about how we want to be inserting the rows during the first import and during each successive import (TL;DR: We want to insert them all at once or fail so that we don't have partially mapped data in the DB which makes life harder to reconcile for successive runs, see [this Slack thread](https://sourcegraph.slack.com/archives/C018CJQ5YBB/p1684310160823739) where I also asked in #chat-databases for advice on this decision and got some good suggestions), and directly executing the job in gitserver also makes this easier and removes one extra step of inter-service coordination.

If we observe any major difficulties with this approach in testing or in production, it will be easy to migrate the mapping job over to the worker without causing any disruptions to the existing customers / repos.

2023-05-23 10:33 UTC, evict commented on cmd/gitserver/server/perforce.go
> +		cmd.Args = append(cmd.Args, fmt.Sprintf("%s..%s", lastMappedCommit, head))
This is dangerous, `git log` supports an argument `--output`. If I manage to inject `--output=../path/outside/dir` I can write files. Although I cannot 100% control the content, it's still dangerous and I'd suggest making sure this cannot happen.

2023-05-23 20:20 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +		cmd.Args = append(cmd.Args, fmt.Sprintf("%s..%s", lastMappedCommit, head))
Thanks for the call out! This is great insight that and I wasn't thinking of this angle at all. Overall this should be still pretty difficult to inject since a user cannot fake commit SHAs as far as I know, but I will ensure that we safely handle non commit-SHA like strings when I follow up with another PR. Very useful thing to keep in mind for future "exec" like code that I write. Thank you! 💟

2023-05-31 16:46 UTC, indradhanush commented
It seems that I have a flakey test in `TestGetCommitsToInsert/new_repo,_never_mapped` that fails 1 in 500. Investigating this next.

2023-06-01 11:57 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +	cmd.Start()
you need to check for error here, sorry missed that

2023-06-02 08:15 UTC, indradhanush commented
Rebased off main to fix merge conflicts (bazel files) and dropped the use of `common.RunWith` in `headCommitSHA` function.

2023-06-05 08:44 UTC, keegancsmith requested changes
LGTM have a few comments I'd like to follow up on so requesting changes.

Additionally I think you should consider somehow gating this feature behind its own feature flag. There is a possibility this could produce a lot of logspam at a p4 user since:
- we don't yet support sha <-> rev changing. All inserts will just fail if I am not mistaken.
- we have very rigid parsing of p4 commit message bodies. It feels like it should be a little more permissive (ie should match the logic used by git-p4).

2023-06-05 08:44 UTC, keegancsmith commented on cmd/gitserver/server/server.go
> +			s.maybeEnqueuePerforceChangelistMappingJob(ctx, logger, req.Repo, dir)
High level design: this logic feels like it should live inside the Syncer implementation for perforce. I just checked the interface out and the problem is that CloneCommand returns an exec.Command so you don't have any hooks here. It feels wrong to fix that here, but maybe we should extend the syncer interface to have a post-fetch hook?

That would also help remove some of the tests you wrote ensuring we call this function.

Then a future nice refactor would be working out how we can make the syncer interface less clunky. Fetch does the fetch. Clone returns a command. Some implementations of clone just do the clone then return a noop clone command. IE the interface is broken.

2023-06-05 08:44 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +	StartPerforceChangelistMappingPipeline(context.Context)
preference: you can reduce the API surface and make this harder to mess up. I recommend you remove this method. Instead on `EnqueueChangelistMappingJob` you can have a sync.Once protecting initialization.

2023-06-05 08:44 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +	// Process only one job at a time for a simpler pipeline at the moment.
do we intend on making it possible to have more than 1 job? Right now there is a whole bunch of complicated machinery which could all just be us reading from the queue. IE you introduce a channel and a queue reader and a channel pusher. We could just read from the queue.

Additionally if you ever where to have multiple queue consumers this implementation would still be broken because you need to introduce some sort of concurrency control to prevent multiple writers for the same repo.

Basically, I would recommend just simplifying all of this and just reading from the queue.

2023-06-05 08:44 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +		err := s.doChangelistMapping(ctx, j)
I would recommend adding some sort of panic protection here. If one of these jobs where to panic it would take down the whole gitserver.

2023-06-05 08:44 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +func (s *Service) EnqueueChangelistMappingJob(job *ChangelistMappingJob) {
it is cheap to check the site configuration. Why don't you just check here if the mapping job is enabled? That way the business logic around mapping is nearly all contained in this file.

2023-06-05 10:53 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +	// Process only one job at a time for a simpler pipeline at the moment.
> do we intend on making it possible to have more than 1 job? 

Yes. I am planning to make it possible to run the same number of concurrent jobs as the number of concurrent clones (reuse the same config too and update the doc) so I used this PR to introduce the support structure for this and was intending to follow up once this is tested with perforce on S2 / Dogfood. Otherwise this would be quite a bit of a bottleneck for customers with heavier perforce workloads.

> Additionally if you ever where to have multiple queue consumers this implementation would still be broken because you need to introduce some sort of concurrency control to prevent multiple writers for the same repo.

Yep! I left out the concurrency limiters here because they weren't being used yet and would have added them in the follow up PR post testing on production. The code would be very similar (borderline copy-paste) to the `acquireclonelimiter` code we already have in place for managing the clone queues.

I agree that without the parallel job execution in-place this does feel like quite a bit of unnecessary job management and would be much simpler to just read from the queue one at a time. With that context in mind, would you still recommend to cut the clutter and simplify this code for now and only introduce this design in the follow up PR? 

My motivation to introduce this here was to have the producer-consumer pipeline tested before I added parallel job exection on it. I'm happy to follow your recommendation on this one either way. 🙂

2023-06-05 11:12 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +func (s *Service) EnqueueChangelistMappingJob(job *ChangelistMappingJob) {
Yes, adding the check for the mapping job being enabled here before pushing onto the queue would make sense (also agreed that we should gate it behind a site config).

For clarification - the current check in the [maybeEnqueuePerforceChangelistMappingJob](https://github.com/sourcegraph/sourcegraph/pull/51860/files/0d78121c86b0b3be4af4dd6f9c3751efbe8a3eb4#diff-f5ac848d014dd8443978e31081a9070426aecc0fc35ab065b1441f61b16452ebR2970-R2980) func is to check if this is a perforce depot and only then push on the queue. Did you also mean to bring that check inside the PerforceService API?

2023-06-05 13:05 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +	// Process only one job at a time for a simpler pipeline at the moment.
alright that makes sense to me.

2023-06-05 13:05 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +func (s *Service) EnqueueChangelistMappingJob(job *ChangelistMappingJob) {
yes I think you should do that too. My other suggestion mentioned this being part of the Syncer, then you wouldn't need to do that since you would know this was p4 synced.

2023-06-05 17:44 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +	StartPerforceChangelistMappingPipeline(context.Context)
I'm not sure how I feel about this. It feels like it would make it harder to predict how this service works over time (I could be wrong but I'm tempted to avoid the potential pit-falls of using sync.Once in case there's something that I miss). How about I do this as a side effect of calling `perforce.NewService` instead?

2023-06-06 07:25 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +	StartPerforceChangelistMappingPipeline(context.Context)
alright NewService sounds good. A lot of my go preferences in design are around using structs instead of interfaces and making sure the zero value is functional :P But NewService sounds like a good place to start the goroutine.

2023-06-06 07:26 UTC, keegancsmith approved these changes
@indradhanush I know you wanna do a quick sync on this, but I can only zoom later today. Anything I can help respond to to unblock this PR now? Based on the inline comments I don't think there is anything larger left (just some smaller things), so approving :)

2023-06-06 07:33 UTC, indradhanush commented on cmd/gitserver/server/server.go
> +			s.maybeEnqueuePerforceChangelistMappingJob(ctx, logger, req.Repo, dir)
@keegancsmith I started redesigning this yesterday and ran into some thoughtful challenges. Overall I agree that the syncer is the right place for perforce related stuff as a post clone / fetch hook. But with the current `PerforceService` designed as a "plugin" to `gitserver.Server`, to enqueue the job from inside the perforce syncer I'll need to pass the server or the `PerforceService` to the syncer as well. Which is beginning to make it look ugly and then it gets tricky to ensure its set every where the syncer is used. The challenge feels a symptom of the clunky interface design at the moment.

2023-06-06 07:35 UTC, indradhanush commented
> @indradhanush I know you wanna do a quick sync on this, but I can only zoom later today. Anything I can help respond to to unblock this PR now? Based on the inline comments I don't think there is anything larger left (just some smaller things), so approving :)

@keegancsmith, Thanks for the approval! [This](https://github.com/sourcegraph/sourcegraph/pull/51860#discussion_r1219085526) comment is the only thing that is kind of a blocker for me for which I thought a zoom call might be better. I'm all set to follow up on the other comments and not blocked on them.

2023-06-06 07:45 UTC, keegancsmith commented on cmd/gitserver/server/server.go
> +			s.maybeEnqueuePerforceChangelistMappingJob(ctx, logger, req.Repo, dir)
yup I agree there are a few smells in the interface. I think stick with what you are currently doing and land this and make forward progress :) Branch cut coming soon, lets get this out and start testing it.

Lets have a call tomorrow morning (I will be at home) and do some pairing on improving the Syncer interface. I think an hour of pairing should make some nice changes.

2023-06-06 07:46 UTC, indradhanush commented on cmd/gitserver/server/server.go
> +			s.maybeEnqueuePerforceChangelistMappingJob(ctx, logger, req.Repo, dir)
Sounds good. Let's do it tomorrow! (I'll send an invite)

2023-06-06 13:54 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +	commits, err := gitserver.ParseGitLogOutput(output)
We use a buffered scanner now so unbounded size from git log output is no longer an issue.

2023-06-06 13:55 UTC, indradhanush commented on cmd/gitserver/server/server.go
> +			s.maybeEnqueuePerforceChangelistMappingJob(ctx, logger, req.Repo, dir)
I've moved this logic inside the `perforce.Service`. Also now that I no longer need to test if this method was invoked, I didn't need the mocks which means I didn't need the `PerforceService` interface either. So I've also removed the interface and directly using the struct in definitions.

2023-06-06 13:56 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +	StartPerforceChangelistMappingPipeline(context.Context)
`NewService` now kicks off the producer consumer pipeline. Also `StartPerforceChangelistMappingPipeline` is now a private method of the struct. I've added docs on the struct and `NewService` definition that indicate that:

1. Only `NewService` should be used to instantiate `perforce.Service`
2. The side effect of calling `NewService`

2023-06-06 13:58 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +func (s *Service) EnqueueChangelistMappingJob(job *ChangelistMappingJob) {
Updated `EnqueueChangelistMappingJob` so that now it is:

1. Guarded by a new experimental feature config (`perforceChangelistMapping`)
2. Also checks if the repo belongs to a perforce code host

2023-06-06 15:23 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +		err := s.doChangelistMapping(ctx, j)
@keegancsmith Last ask for the time being: I used `goroutine.Go` for panic protection here: https://github.com/sourcegraph/sourcegraph/pull/51860/commits/10ca879acc7ca13a8c2c2816e403a778628dbc02

Does this look good or should I be trying to restart the pipeline on panic?

2023-06-07 10:57 UTC, merged

2023-06-14 12:35 UTC, indradhanush commented on cmd/gitserver/server/perforce.go
> +		cmd.Args = append(cmd.Args, fmt.Sprintf("%s..%s", lastMappedCommit, head))
@evict Follow up PR is here to fix the security concern: https://github.com/sourcegraph/sourcegraph/pull/53468

2023-06-14 13:03 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +}
Done: https://github.com/sourcegraph/sourcegraph/pull/53325