feature: added new cody receipe optimize
sourcegraph/sourcegraph pull request #51974
Opened 2023-05-16 06:51 UTC by Momilijaz96

## Test plan

Tested the feature locally by running Cody from "Run and Debug" option of VSCode; with different DSA algorithms in python and general DS/ML based applications and projects. The recipe suggests good code optimizationsto improve memory and time optimizations.

2023-05-16 07:26 UTC, Momilijaz96 commented
@cla-bot check

2023-05-18 05:21 UTC, Momilijaz96 commented
@cla-bot check

2023-05-19 09:43 UTC, mrnugget requested changes
Thanks for the PR, @Momilijaz96! Very interesting. Do you have examples of how it worked? Did you test it on some code and got good results?

There's some linting issues, according to CI:

```


> @ format:check /root/buildkite/build/sourcegraph
--
  | > prettier '**/{*.{js?(on),ts?(x),graphql,md,scss},.*.js?(on)}' --config prettier.config.js --check --write=false
  |  
  | Checking formatting...
  | [warn] client/cody-shared/src/chat/recipes/vscode-recipes.ts
  | [warn] client/cody/src/main.ts
  | [warn] Code style issues found in 2 files. Forgot to run Prettier?

```

Those need to be fixed

2023-05-19 09:43 UTC, mrnugget commented on client/cody-shared/src/chat/recipes/vscode-recipes.ts
> +        new InlineChat(),
Why the reorder?

2023-05-19 09:52 UTC, philipp-spiess reviewed
This is really interesting. I feel like we should have a recipe regarding time and space complexity!! Thank you so much for this.

2023-05-22 10:18 UTC, Momilijaz96 commented on client/cody-shared/src/chat/recipes/vscode-recipes.ts
> +        new InlineChat(),
I removed the reordering, I guess that was extra.

2023-05-22 15:18 UTC, Momilijaz96 commented on client/cody-shared/src/chat/recipes/optimize-code.ts
> +            Output format should be: The code can/cannot be optimized. Optimisation Steps: {} Time and Space Usage: {} Updated Code: {} :\n\n\`\`\`${extension}\n${truncatedSelectedText}\n\`\`\`\n${MA
I fixed the formatting issues and updated the prompt message to remove spelling inconsistencies.

2023-05-22 15:27 UTC, Momilijaz96 commented
There are few cases that I could'nt handle, even with iterative prompt development:
a. I could'nt fix the format of the output, I wanted the "optimization steps", "time/space consumption improvement" in text and "updated code block" in a code block, but no changes in the prompt helped me achieve that.
b. I also struggled with the input code not be included in response, but it is included sometimes with current prompt.
c. I tested it on limited file formats and code types.
Let me know what you guys think!
I

2023-05-22 21:51 UTC, thenamankumar approved these changes

2023-05-23 09:44 UTC, mrnugget commented
Looking at the examples here (https://github.com/sourcegraph/sourcegraph/pull/51974#issuecomment-1557420056) it seems like the formatting is broken, no? Every reply is prefixed with "Here is the response" and then it's raw Markdown.

That should be fixed before we merge this

2023-05-23 09:45 UTC, mrnugget requested changes
See my comment inline and the previous comment further up

2023-05-23 09:45 UTC, mrnugget commented on client/cody-shared/src/chat/recipes/optimize-code.ts
> +        const assistantResponsePrefix = `Here is the response  \n\`\`\`${extension}\n`
I think this breaks the formatting: we don't want every response prefixed with "Here is the response"

2023-05-23 10:42 UTC, Momilijaz96 commented on client/cody-shared/src/chat/recipes/optimize-code.ts
> +        const assistantResponsePrefix = `Here is the response  \n\`\`\`${extension}\n`
Thanks for pointing that out... removing this response prefix fixed it.
Check out these examples now:
![Screenshot 2023-05-23 at 3 39 23 PM](https://github.com/sourcegraph/sourcegraph/assets/53872365/d9751ee4-6a2f-4e34-aa34-31a2491780ed)

![Screenshot 2023-05-23 at 3 39 54 PM
![Screenshot 2023-05-23 at 3 40 18 PM](https://github.com/sourcegraph/sourcegraph/assets/53872365/57e81cdb-a0de-4fc3-9ae0-a2893ac406fb)
](https://github.com/sourcegraph/sourcegraph/assets/53872365/5e621c70-e6b7-40dd-beec-830e7f29df06)

2023-05-23 10:56 UTC, mrnugget approved these changes

2023-05-23 15:58 UTC, philipp-spiess commented
🎉 

@Momilijaz96 do you mind solving the merge conflict? I can look into it as well if you're busy. Ping me here when you did this so I can run the latest changes on CI and we can ship this 🚀

2023-05-24 07:06 UTC, Momilijaz96 commented
> 🎉
> 
> @Momilijaz96 do you mind solving the merge conflict? I can look into it as well if you're busy. Ping me here when you did this so I can run the latest changes on CI and we can ship this 🚀

Hey @philipp-spiess I don't have the write access to resolve the conflict.
<img width="838" alt="Screenshot 2023-05-24 at 12 06 29 PM" src="https://github.com/sourcegraph/sourcegraph/assets/53872365/293ef083-26bc-4788-8898-ca59507ba462">

2023-05-24 08:04 UTC, philipp-spiess commented
@Momilijaz96 You should be able to update your forked repository. Try something like this in the terminal. If that doesn't work, I can look into it :)

```
git remote -v # This should list your fork as the `origin` for this to work. 
git fetch
git merge origin/main
```

2023-05-24 09:14 UTC, Momilijaz96 commented
> 

Alright I guess it's done!

2023-05-24 09:14 UTC, Momilijaz96 commented
> @Momilijaz96 You should be able to update your forked repository. Try something like this in the terminal. If that doesn't work, I can look into it :)
> 
> ```
> git remote -v # This should list your fork as the `origin` for this to work. 
> git fetch
> git merge origin/main
> ```

Alright, i guess it's ready to be merged.

2023-05-24 09:19 UTC, philipp-spiess commented on client/cody-shared/src/chat/recipes/vscode-recipes.ts
> +import { ChatQuestion } from './chat-question'
Huh there seems to be a conflict here, this file was moved into the `client/cody` folder on `main`

2023-05-24 09:27 UTC, Momilijaz96 commented on client/cody-shared/src/chat/recipes/vscode-recipes.ts
> +import { ChatQuestion } from './chat-question'
I accidently merged current branch into main, I "undo" it and pushed again, I guess that would resolve this conflict.

2023-05-24 09:41 UTC, philipp-spiess commented on client/cody-shared/src/chat/recipes/vscode-recipes.ts
> +import { ChatQuestion } from './chat-question'
This file still seems to be added instead. Is it okay if I push onto your branch to try and resolve this??

2023-05-24 09:47 UTC, Momilijaz96 commented on client/cody-shared/src/chat/recipes/vscode-recipes.ts
> +import { ChatQuestion } from './chat-question'
yeah sure, go ahead

2023-05-24 10:30 UTC, Momilijaz96 commented on client/cody-shared/src/chat/recipes/vscode-recipes.ts
> +import { ChatQuestion } from './chat-question'
Apparently my forked repo's main branch is a few commits ahead of the upstream's main. I am trying to fetch upstream and merge into my fork's main, but that is not introducing any changes.

2023-05-25 09:15 UTC, Momilijaz96 commented
Hey @philipp-spiess , Thanks for taking care of this. 👍 
Is the conflict resolved now? or something else needs be done from my end.

2023-05-25 09:24 UTC, philipp-spiess commented
@Momilijaz96 All done from your end 🎉  I’m just working on getting CI to pass before I can merge this 🙂

2023-05-25 10:40 UTC, philipp-spiess commented
@Momilijaz96 There appears to be a bug in our CI setup right now, I've asked internally for some advice. I'll have this PR bookmarked though and will continue to look into it 🙇

2023-05-25 11:02 UTC, Momilijaz96 commented
> @Momilijaz96 There appears to be a bug in our CI setup right now, I've asked internally for some advice. I'll have this PR bookmarked though and will continue to look into it 🙇

No worries, Sounds good.

2023-05-26 16:50 UTC, merged

2023-05-26 16:50 UTC, philipp-spiess commented
Y'all we did it! 🎉  @Momilijaz96 @mrnugget

2023-05-26 19:18 UTC, Momilijaz96 commented
> Y'all we did it! 🎉 @Momilijaz96 @mrnugget

Great :-)

2023-05-29 14:48 UTC, jdorfman commented
This is a fantastic addition, great work @Momilijaz96! 

And thank you @mrnugget @philipp-spiess for reviewing it.