(fix) add repo meta create & update user-friendly error message
sourcegraph/sourcegraph pull request #51985
Opened 2023-05-16 12:15 UTC by erzhtor

Part of https://github.com/sourcegraph/pr-faqs/issues/96.

## Test plan
- `sg start`
- Enable `repository-metadata` feature flag
- Open any repo meta settings page, ex: https://sourcegraph.test:3443/github.com/sourcegraph/sourcegraph/-/settings/metadata
- Try to add duplicate key

## Screenshots
| Description | Before | After |
| --: | --: | :-- |
| Create duplicate key | <img width="1728" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6717049/03f05ff5-8bb8-4632-8c69-06963c530954"> | <img width="1728" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6717049/8b70dd30-a428-482b-b31c-bc0e28d773b9"> |
| Update non-existing key-value pair. This is mainly used by `src repos update-metadata` command  | <img width="1728" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6717049/3de8ebf2-3d25-4154-b1b8-dc66a662f72e"> | <img width="1728" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6717049/48bc3182-d682-44ff-9885-a0e5a6720f90"> |

2023-05-16 15:37 UTC, sashaostrikov reviewed
I proposed the other way around for checking that there is already an existing metadata key, PTAL

2023-05-16 15:37 UTC, sashaostrikov commented on internal/database/repo_kvps.go
> +	if err := s.Exec(ctx, sqlf.Sprintf(q, repoID, kvp.Key, kvp.Value)); err != nil {
I'd go another way here.
You can amend the SQL query by adding `ON CONFLICT DO NOTHING` and then do the check for a number of inserted rows, sth like this:
```go
	result, err := s.ExecResult(ctx, q)
	if err != nil {
		return errors.Wrap(err, "executing SQL query")
	}
	insertedRows, err := result.RowsAffected()
	if err != nil {
		return errors.Wrap(err, "getting rows affected")
	}
	if insertedRows == 0 {
		return errors.New("blah-blah already exists")
	}

```

2023-05-17 07:47 UTC, erzhtor commented on internal/database/repo_kvps.go
> +	if err := s.Exec(ctx, sqlf.Sprintf(q, repoID, kvp.Key, kvp.Value)); err != nil {
Great suggestion, thank you! Updated 2bcec90e3a0504a2ef38489b8d356508157e064d.

2023-05-17 14:29 UTC, sashaostrikov commented on internal/database/repo_kvps.go
> +	if nrows == 0 {
Sorry, but I actually misled you about the number of rows affected.
The thing is, it is impossible to understand whether the conflict has occurred (i.e. the entry already existed) with `ON CONFLICT DO NOTHING` clause. 

The SQL would get a bit messy if we want to distinguish between `INSERT 0 1` response from Postgres in case of _inserting an entry_ or _not inserting a duplicate.

If we really need this error (instead of silently skipping the duplicate), then we can use 2 separate queries, first to check existence and return an error if exists, and second to insert the entry which we (now) know, has no existing duplicates.

If we don't need this error, then you can just skip the 58-63 lines altogether.

Anyway, it's your call, sorry for confusion!

2023-05-17 14:30 UTC, sashaostrikov reviewed
PTAL at my comment, I guess I caused some confusion with my last review, sorry!

2023-05-18 07:27 UTC, kopancek requested changes

2023-05-18 07:27 UTC, kopancek commented on internal/database/repo_kvps.go
> +	if nrows == 0 {
+1 on that. Also, if we want to do 2 separate queries, we need to do them in transaction to keep the DB consistency in mind.

2023-05-18 07:27 UTC, kopancek commented on internal/database/repo_kvps.go
> +	if nrows == 0 {
We could also keep the SQL statement as it was and just catch the error properly here. E.g. if there's a conflict, we should get a specific error from postgres that we could react to.

2023-05-18 10:11 UTC, sashaostrikov approved these changes
:shipit:

2023-05-18 12:34 UTC, toolmantim approved these changes
Much nicer!! Minor suggestion is to either remove "Repo", or use the full word "Repository" at the beginning and remove "for the given repository" at the end

2023-05-18 12:34 UTC, toolmantim commented on internal/database/repo_kvps.go
> +			return errors.Newf(`Repo metadata key "%s" already exists for the given repository.`, kvp.Key)
```suggestion
			return errors.Newf(`Metadata key "%s" already exists for the given repository.`, kvp.Key)
```

2023-05-18 12:34 UTC, toolmantim commented on internal/database/repo_kvps.go
> +		return updated, errors.Newf(`Repo metadata key "%s" does not exist for the given repository.`, kvp.Key)
```suggestion
		return updated, errors.Newf(`Metadata key "%s" does not exist for the given repository.`, kvp.Key)
```

2023-05-18 15:11 UTC, camdencheek approved these changes

2023-05-18 17:21 UTC, erzhtor commented
@kopancek, looks like I can't merge PR unless you stamp it?

2023-05-18 20:59 UTC, kopancek approved these changes

2023-05-18 20:59 UTC, merged