Alter homepage copy to support the new /cody page
sourcegraph/sourcegraph pull request #52101
Opened 2023-05-17 19:07 UTC by rrhyne

## Test plan

Manually test the links to determine if they work correctly.

2023-05-17 19:17 UTC, sourcegraph-buildkite commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.35 kb) | 0.00% (+0.35 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/rrhyne-homeupdate/compare-report.html;tab=live_object) for a full comparison between the commits 8a70553 and c20a01e or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-05-17 19:26 UTC, almeidapaulooliveira approved these changes

2023-05-18 22:04 UTC, thenamankumar requested changes
LGTM, but blocking as it need to be merged after this: https://github.com/sourcegraph/sourcegraph/pull/52165

I'll approve and merge this PR myself later.

2023-05-19 10:15 UTC, thenamankumar approved these changes

2023-05-19 10:24 UTC, merged

2023-05-19 15:04 UTC, rrhyne commented
Thanks Naman!