sg: run generate buf only with changes
sourcegraph/sourcegraph pull request #52128
Opened 2023-05-18 02:11 UTC by davejrt

Adds a check to see if .proto files have changed, to determine if running `generate buf` is required. 

## Test plan

```
➜  sourcegraph git:(dt/sg_buf) ✗ go run ./dev/sg generate 
👉 Running target "buf" (Re-generate protocol buffer bindings using buf)
✅ Target "buf" done (7s)
👉 Running target "go" (Run go generate [packages...] on the codebase)
✅ 14/14 packages generated  ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  100%
ℹ️ go generate ./... (excluding doc/cli/references)
ℹ️ goimports -w
ℹ️ go mod tidy
✅ Target "go" done (21s)
➜  sourcegraph git:(dt/sg_buf) ✗ unset CI=true
➜  sourcegraph git:(dt/sg_buf) ✗ unset CI     
➜  sourcegraph git:(dt/sg_buf) ✗ go run ./dev/sg generate 
👉 Running target "go" (Run go generate [packages...] on the codebase)
✅ 14/14 packages generated  ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  100%
ℹ️ go generate ./... (excluding doc/cli/references)
ℹ️ goimports -w
ℹ️ go mod tidy
✅ Target "go" done (21s)
➜  sourcegraph git:(dt/sg_buf) ✗ gst
On branch dt/sg_buf
Your branch is up to date with 'origin/dt/sg_buf'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .proto
➜  sourcegraph git:(dt/sg_buf) ✗ ga .proto && gc "add test proto" 
[dt/sg_buf 4c1da4175a] add test proto
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 .proto
➜  sourcegraph git:(dt/sg_buf) go run ./dev/sg generate
👉 Running target "buf" (Re-generate protocol buffer bindings using buf)
✅ Target "buf" done (7s)
👉 Running target "go" (Run go generate [packages...] on the codebase)
✅ 14/14 packages generated  ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  100%
ℹ️ go generate ./... (excluding doc/cli/references)
ℹ️ goimports -w
ℹ️ go mod tidy
✅ Target "go" done (21s)
➜  sourcegraph git:(dt/sg_buf) 
```

2023-05-19 12:12 UTC, jhchabran requested changes
This code is doing to be dropped in the upcoming weeks, but I think it's a useful learning exercise :) I hope that my comment make it clear on why it's currently correct but not acceptable.

2023-05-19 12:12 UTC, jhchabran commented on dev/sg/sg_generate.go
> +			_ = runGenerateAndReport(cmd.Context, allGenerateTargets[ind], []string{})
This is quite confusing: 

- If we detect that the diff contains a proto file, we run all generators (because other targets are handled by the subcommands) 
- But if we dont, we only run the go generate target? 

It works because there are _only two targets here_, the go one and the buf one, but reading the code forces you to know about that to understand that it's correct. 

If someone would be to add a third one, this code would be introduce a nasty bug. It would sound strange to that person to think they thave to update the code that runs all generators to make it work, whereas they'd expect to simply add a new target and they'd be good to go. 

Why not work at the `generateProtoRunner(...)` func level? It would be much clearer.

2023-05-20 18:09 UTC, davejrt commented on dev/sg/sg_generate.go
> +			_ = runGenerateAndReport(cmd.Context, allGenerateTargets[ind], []string{})
@jhchabran Fair point!

I don't see how putting the logic in generateProtoRunner works, if I don't return a *generete.Report from that function there's a segfault from urfave. 

The alternative I came up with has been commited, but totally willing to accept there's something I'm over looking here.

2023-05-22 17:14 UTC, jhchabran approved these changes

2023-05-22 17:14 UTC, merged