Batch Changes support for Perforce
sourcegraph/sourcegraph pull request #52127
Opened 2023-05-18 01:09 UTC by peterguy

# Add Batch Changes support for Perforce

## 2023/05/17

- `src-cli` now recognizes Perforce repos as supported
- lots of code has been BCC'd from the ADO BC code
- `src-cli` gets HTTP 500 when attempting to download the zip archive

# Test plan

TBD

2023-05-25 19:47 UTC, sourcegraph-buildkite commented
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.00% (0.00 kb) | 0.00% (+0.05 kb) | 0.00% (+0.05 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/pg/perforce-batch-changes/compare-report.html;tab=live_object) for a full comparison between the commits 08eee45 and e4e5053 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

2023-05-31 19:16 UTC, varsanojidan reviewed
Looks good so far. I find that a good place to start on Batch Changes is in the client (internal/extsvc/perfroce/client.go), and trying to make sure that all the functions there line up to the functions in the Batches Source (batches/sources/perforce.go).

2023-06-02 18:52 UTC, peterguy commented on enterprise/internal/batches/sources/perforce.go
> +var _ ForkableChangesetSource = PerforceSource{}
> Does perforce have support for doing PRs through forks?

Nope; I'll clean it up. Part of my initial BCC from ADO just to get it working so I could iterate. Thanks!

2023-06-02 18:55 UTC, peterguy commented on enterprise/internal/batches/sources/perforce/types.go
> +	*perforce.Changelist
I appreciate the clarification on the purpose of an Annotated PullRequest/Changelist. We don't plan to support information about builds or reviews this iteration, because we'd have to go elsewhere to get that. I think that kind of info is available from other Perforce tools, like Swarm, but we are not set up to look there. Maybe later. I'll probably leave this in there and add your post as a comment so that we will be more clear about what we might do in the future.

2023-06-02 18:56 UTC, peterguy commented on enterprise/internal/batches/store/changesets.go
> +		t.Metadata = new(p4batches.AnnotatedChangelist)
Thanks; I did overlook that as a TODO

2023-06-02 19:44 UTC, courier-new commented
Hey Peter, as promised, adding some thoughts here as to what to do with the changelist ID after you've created the commit with gitserver!

We have a field on the `batches.types.Changeset` called `ExternalID` (see [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/internal/batches/types/changeset.go?L261)), which for other code hosts is a reference to the PR/MR id on that code host. I think recording the changelist ID as the `ExternalID` of a Perforce changeset would make sense here, then.

Since we only know this ID after the changelist is created, I think we'll need to be more strategic about what we do with the `CreateCommitFromPatchResponse ` from gitserver in the `batches/reconciler/executor`. Now, I'll leave it up to you if you want the changelist ID to be its own property on the response, or if we just want to use it in place of `rev` since it's the closest equivalent to a fully qualified branch ref would be as the `rev` for git. But if it's on the `CreateCommitFromPatchResponse` somewhere, I would update `executor.pushCommit` to return it. I actually [need to return the `rev`](https://github.com/sourcegraph/sourcegraph/commit/fcd017ec83beaa6120ee6466c97dc7d50a21b50c#diff-904da760e6b4d0f7b7cbcd03c0ceeb301e378a79916d25fe13383cf4738731c2R645-R660) for another feature we have in progress, so if decide to go the route of rev = changelist ID, you could just copy me on that! 😛

Then in `executor.pushChangesetPatch` after we've called `pushCommit`, we can update the `Changeset` right away. For this, I'd suggest we add a new method to the `ChangesetSource` type like `UpdateChangesetFromRev` or `UpdateChangesetFromCommit`. For every other code host source's implementation, this method would be a no-op. But for Perforce, it would update the changeset record in the DB to record the rev/changelist ID as its `ExternalID`. The changeset is already available on the executor here as `e.ch`, as well as an ongoing DB transaction for invoking store methods on, `e.tx`.

From here, we would start to have more of an ability to surface the ID from GraphQL and do special things with it in the UI if we see that the changeset is for a Perforce repo. We already expose `externalID` on the `Changeset` type [over GraphQL](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@main/-/blob/enterprise/cmd/frontend/internal/batches/resolvers/changeset.go?L135), for instance. If there's a way to programmatically build Swarm changelist URLs given a base Swarm URL and a changelist ID, we could even tap into that to create external URLs for the changesets by adding a site setting for `perforceBaseSwarmURL` or something that a site admin could configure. But let's not get too ahead of ourselves there yet of course, hehe. 🙂 Starting by capturing the changelist ID at the time of shelving the changes seems like something that ought to happen for sure, though.

2023-06-02 21:13 UTC, peterguy commented
Thank you, @courier-new! Great walk-through; I'll pull it together pretty much like you describe. 

Instead of returning only the `Rev` from `pushCommit`, how about returning the whole `protocol.CreateCommitFromPatchResponse`?

Assuming that sounds like a good idea, would it be helpful for me to make a separate commit/PR for surfacing `protocol.CreateCommitFromPatchResponse` all the way back to `executor.pushChangesetPatch`?

2023-06-05 15:36 UTC, evict requested changes

2023-06-05 15:36 UTC, evict commented on cmd/gitserver/server/patch.go
> +
This can be dangerous, would it be possible to do this in Go while adding similar protections as we have here: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/unpack/unpack.go?L142-177? Alternatively you can write it to a file.

2023-06-05 19:19 UTC, peterguy commented on cmd/gitserver/server/patch.go
> +
Hah, I had originally written a Go function to unpack the tar file, then re-wrote it to use `tar` because I didn't want to miss any edge cases with my routine that `tar` would handle. I can definitely use `unpack.go`'s `Tar` function instead. Looks like it takes a `io.Reader`, so I shouldn't even have to write it to a file first.

Just so I have a more complete understanding, ~what is the danger you're highlighting? Using a native binary? Using `tar` specifically? Piping two commands together?~ Ohhh, I see: it's the potential paths inside the tarball. `Tar` uses `sanitizeTarPath` to make sure nothing escapes the target directory.

2023-06-14 10:46 UTC, evict commented on cmd/gitserver/server/patch.go
> +	}
Nice! I will include this in the secure coding notebook when it's merged into main. 👍

2023-06-14 16:27 UTC, courier-new approved these changes
Sooooo good! Great work on all this. The p4 stuff fits in really nicely in `patch.go`, I think. I mostly focused on reviewing the Batch Changes parts of this; left a few comments around your `ChangesetSource` method TODOs, but things overall looked fine to me so feel free to follow up on those later. 🙂

2023-06-14 16:27 UTC, courier-new commented on enterprise/internal/batches/sources/perforce.go
> +	// so it can handle it differently from Git repos.
Creative, I love it!!

2023-06-14 16:27 UTC, courier-new commented on enterprise/internal/batches/sources/perforce.go
> +	return errors.New("not implemented")
This one's probably a no-op, like `CreateDraftChangeset`, if Perforce doesn't submit a concept of changelists that are even more WIP than ones that are shelved.

2023-06-14 16:27 UTC, courier-new commented on enterprise/internal/batches/sources/perforce.go
> +	return errors.New("not implemented")
Delete could work here, is there any other notion of abandoning a shelved changelist but in a way that it's not totally deleted?

Cody suggesetd `p4 shelve -d <changelist number>` accomplishes this but I haven't actually tested if that's a real command. 😜

2023-06-14 16:27 UTC, courier-new commented on enterprise/internal/batches/sources/perforce.go
> +}
This is probably a no-op since any updates (changes to the title, "commit" message, author, etc.) would all happen from gitserver with the p4 commands, right?

Probably here you would just want to make sure to reload the changeset so we've got the most recent metadata recorded for it:

```suggestion
// UpdateChangeset can update Changesets.
// Noop since Perforce pushes updates directly with p4
func (s PerforceSource) UpdateChangeset(ctx context.Context, cs *Changeset) error {
	return s.LoadChangeset(ctx, cs)
}
```

2023-06-14 16:27 UTC, courier-new commented on enterprise/internal/batches/sources/perforce.go
> +	return errors.New("not implemented")
If there _is_ a way to abandon changelists, and then if there's a way to restore them _after_ they're abandoned, this is what we'd want to do here.

Cody suggests you can restore abandoned changelists with `p4 shelve -r <changelist number>`, but again, I have not verified this suggestion. 😛

2023-06-14 16:27 UTC, courier-new commented on enterprise/internal/batches/sources/perforce.go
> +	return errors.New("not implemented")
I'd opt for submitting here. Users will always have the ability to manage their changesets in other tools, too, we just tap into the underlying code host functions to enable things that are often impossible in other tools, like merging/submitting in bulk across code hosts. 😄

2023-06-14 16:27 UTC, courier-new commented on enterprise/internal/batches/sources/perforce_test.go
These tests that mock the p4 client are great, but I'd love to see some VCR tests that work with a real (test) p4 depot, too, so that we have some actual inputs and outputs recorded. 🙂

2023-06-14 16:42 UTC, courier-new commented
As I'm sure you're well aware, haha, looks like there are a few tests that are failing currently. I think the Percy one might be a flake, but I see a few others failing that might be real if you download the build artifact log file [here](https://buildkite.com/organizations/sourcegraph/pipelines/sourcegraph/builds/227324/jobs/0188b7fc-3ec9-41e9-944b-795265e754b5/artifacts/0188b807-cb10-4e06-a1b7-3d296a257549).

If you can't reproduce those failures locally let me know and I'm happy to help troubleshoot.

2023-06-20 23:12 UTC, merged