Cody: Add Task View for Non-Stop Cody
sourcegraph/sourcegraph pull request #52282
Opened 2023-05-22 20:32 UTC by abeatrix

Moved from https://github.com/sourcegraph/sourcegraph/pull/51953
Close https://github.com/sourcegraph/sourcegraph/issues/51939

See Loom: https://www.loom.com/share/131312eca9b44d63bbc7a515412e9888

This PR introduces:
- A new feature flag called `cody.experimental.nonStop`
- If `cody.experimental.nonStop` is set to true, a task list view for fixup will be available under Cody's chat view
- A new recipe called non-stop cody
- A new command to run the non-stop cody recipe if the feature flag is on

NOTE: The primary goal of this OR is to add a task view for the future implementation for non-stop Cody. It does not include the ability to run multiple tasks at the moment. It only displays a list of tasks started by the non-stop recipe with their status.

Here are some screenshots from the latest commit:
<img width="368" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/aec049d4-88f4-4beb-8925-1bdc563014d1">
<img width="376" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/1735aede-edd1-43bc-b531-f3b35db1ad8d">
<img width="377" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/c071bcb3-2871-466b-9e2c-f6f9267e1ddd">
<img width="371" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/a27b9a92-701e-4d15-a86a-5ec8b53eac37">

## Test plan

See Loom: https://www.loom.com/share/131312eca9b44d63bbc7a515412e9888

2023-05-23 01:16 UTC, abeatrix commented on client/cody-shared/src/chat/recipes/inline-chat.ts
> +        const selection = context.editor.controllers?.inline.selection
this change is due to how we are now passing in the controller for inline-chat as an object: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@76d7383093f038edcb1b210b3d01c792280aa58e/-/blob/client/cody/src/main.ts?L84-86

2023-05-23 01:16 UTC, abeatrix commented on client/cody-shared/src/chat/recipes/fixup.ts
> +        const selection = context.editor.getActiveTextEditorSelection() || context.editor.controllers?.inline.selection
this change is due to how we are now passing in the controller for inline-chat as an object: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@76d7383093f038edcb1b210b3d01c792280aa58e/-/blob/client/cody/src/main.ts?L84-86

2023-05-23 03:01 UTC, dominiccooney requested changes
This is a big improvement in that it is more concentrated and the fixup task type and tree view node types are separate. But there is still a lot we can strip from this, and a lot we can add to it like a test that all the buttons are present and can trigger methods in a stub controller. I have given detailed feedback inline with some directions to pursue.

2023-05-24 02:59 UTC, toolmantim commented on client/cody/package.json
> +				"title": "Cody: Go to task file",
"Cody: Go to Fixup"

(p.s. VS Code’s UI button/label capitalisation style is https://title.sh)

2023-05-24 03:03 UTC, toolmantim commented on client/cody/package.json
> +				"title": "Cody: Add Fixups with highlighted code",
```suggestion
				"title": "Cody: Auto-Apply Fixups",
```

2023-05-24 03:03 UTC, toolmantim commented on client/cody/package.json
> +				"title": "Cody: Show this Fixup",
```suggestion
				"title": "Cody: Go to Fixup",
```

2023-05-24 03:07 UTC, toolmantim commented on client/cody/package.json
> +				"title": "Cody: Add Fixups with highlighted code",
On second thought, is this a toggle? In which case, "Toggle" and "mode" is the word that VS Code uses in actions…

```suggestion
				"title": "Cody: Toggle Fixup Auto-Apply Mode",
```

2023-05-24 03:30 UTC, abeatrix commented
Added buttons with empty methods to task controller

<img width="523" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/4010a0ca-6fe0-483e-a017-72e8561d570b">

<img width="376" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/0a860546-2013-4e6b-9d5b-ecdac4a3d1a9">

2023-05-24 11:55 UTC, dominiccooney requested changes
I've been through a good chunk of this and have a bunch of feedback inline.

2023-05-24 11:55 UTC, dominiccooney commented on client/cody/package.json
> +        "enablement": "!cody.task.view.isEmpty && !cody.task.running",
`!cody.task.running` isn't right, we need to be able to apply completed fixups even if other fixup tasks are in-flight.

2023-05-24 11:55 UTC, dominiccooney commented on client/cody/package.json
> +          "when": "cody.nonstop.fixups.enabled && view == cody.tasks.view && cody.activated && viewItem == fsPath",
We should use the state to show or enable this button when it will (probably) do something. That is, when the file in question has fixups we can apply.

The controller will publish a list of files which this button should be enabled for, I think I called it filesWithApplicableFixups. You can include the resource URI in the viewItem, and then do something like `viewItem in cody.fixup.filesWithApplicableFixups`

You don't need to do the bit where the controller sets that state. But do have a test which sets that state and so on so you can verify that the button appears at the right time.

Can Playwrite tests interact with the vscode treeview? Let's work out how to do that because you can use it to test this and it will be very valuable knowledge for integration tests later.

2023-05-24 11:55 UTC, dominiccooney commented on client/cody/src/non-stop/FixupTask.ts
> +import * as vscode from 'vscode'
I like the name FixupTask for this class. Above I pushed back on naming things cody.task, etc. but in this case, FixupTask *is* a good name for this particular class. It would get confusing if we just call it "Fixup" because that's like a brand for the whole feature.

2023-05-24 11:55 UTC, dominiccooney commented on client/cody/src/non-stop/FixupTask.ts
> +// TODO(bee): Create CodeLens for each task
I'm a fan of TODOs everywhere pointing to bits that need to be wired up later. Great.

2023-05-24 11:55 UTC, dominiccooney commented on client/cody/src/non-stop/FixupTask.ts
> +    public id: string
I anticipate a lot of churn here but we should get this committed and we can both hack on it. As long as we have tests to tell us if we break stuff we should be fine.

2023-05-24 11:55 UTC, dominiccooney commented on client/cody/src/non-stop/TaskController.ts
> +    private _disposables: vscode.Disposable[] = []
We need to dispose of these at some point.

2023-05-24 18:31 UTC, abeatrix commented on client/cody/src/non-stop/FixupTask.ts
> +import * as vscode from 'vscode'
This makes sense! What you said actually clears a lot of things up for me so thank you!

2023-05-24 18:31 UTC, abeatrix commented on client/cody/src/non-stop/FixupTask.ts
> +import * as vscode from 'vscode'
This makes sense! What you said actually clears a lot of things up for me so thank you!

2023-05-24 18:32 UTC, abeatrix commented on client/cody/package.json
> +				"title": "Cody: Add Fixups with highlighted code",
Updated to `Cody: Fixup (Experimental)`

2023-05-24 18:36 UTC, abeatrix commented on client/cody-shared/src/editor/index.ts
> +    add(input: string, selection: ActiveTextEditorSelection): string | null
We are building the controller in client/cody https://github.com/sourcegraph/sourcegraph/blob/6c1739b9b0f63d7a9fcf10543555706b4af13dd3/client/cody/src/main.ts#L83
It just requires us to also update the type for the recipes in client/cody-shared to pick up 😅

2023-05-24 19:34 UTC, abeatrix commented on client/cody/package.json
> +          "command": "cody.task.apply",
All the registered commands are available in command palette by default, so we need to set it to `false` manually to "hide" it from the command palette lol

2023-05-24 19:39 UTC, abeatrix commented on client/cody/package.json
> +          "command": "cody.task.applyDir",
Nice catch LOL i got confused because the file is listed as a directory in our UI 🤣

2023-05-24 19:43 UTC, abeatrix commented on client/cody/package.json
> +          "id": "cody.tasks.view",
done

2023-05-25 12:00 UTC, dominiccooney commented on client/cody/package.json
> +        "enablement": "!cody.task.view.isEmpty && !cody.task.running",
Again, `!cody.task.running` isn't right because we want to be able to commit fixups while other fixups are running.

Because these two issues are ones I've mentioned before, let me pass this back to you and let you do another pass over the feedback and check its been addressed. If it is unclear, let me know... maybe we should go through it in VC.

2023-05-26 02:03 UTC, abeatrix commented on client/cody/package.json
> +          "when": "cody.nonstop.fixups.enabled && view == cody.tasks.view && cody.activated && viewItem == fsPath",
Added cody.fixup.filesWithApplicableFixups

2023-05-26 02:12 UTC, abeatrix commented on client/cody-shared/src/chat/recipes/non-stop.ts
> +                    await context.editor.replaceSelection(
Removed

2023-05-26 02:16 UTC, abeatrix commented on client/cody-shared/src/chat/recipes/non-stop.ts
> +        const humanInput =
I've added a TODO to remove this when chat is disconnected. 

There is no fixup for web but all recipes in Cody-share share the same recipe structures so it will always get passed down even if we don't use it?

2023-05-26 06:27 UTC, dominiccooney approved these changes
Love the integration test.

2023-05-26 06:27 UTC, dominiccooney commented on client/cody/src/non-stop/TaskController.ts
> +        this._disposables.push(vscode.commands.registerCommand('cody.fixup.open', id => this.showThisFixup(id)))
If we don't use _disposables after the constructor, we should just make a local array and hand it off to the taskViewProvider.

Why do it this way, though? What if the controller outlives the view, then its commands will be disposed when the view is disposed.

2023-05-26 06:27 UTC, dominiccooney commented on client/cody/src/non-stop/TaskViewProvider.ts
> +        let text = `${this.tasks.size} fixups`
Let's use pluralize here so we have 1 fixup, 2 fixups

2023-05-26 06:27 UTC, dominiccooney commented on client/cody/test/fixtures/mock-server.ts
> +        const isFixupRequest = req.body.messages[2].text.includes('<selection>')
Fine for now.

I wonder if we could put something in the test request itself where we tell it what to respond with, or have a method on the server to send a set response the next time it sees a trigger word in the request.

Reason to do it this way: over time it is not going to be manageable to keep the test responses and the tests in sync if they are so far apart.

2023-05-26 21:18 UTC, abeatrix commented on client/cody/test/fixtures/mock-server.ts
> +        const isFixupRequest = req.body.messages[2].text.includes('<selection>')
Yea I will look into that in my PR to add test to task view. Added a TODO :D

2023-05-26 21:18 UTC, abeatrix commented on client/cody/src/non-stop/TaskViewProvider.ts
> +        let text = `${this.tasks.size} fixups`
Done!
<img width="493" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/a3298c7f-8f4c-47a6-9044-d330e4cf51f0">

2023-05-26 21:19 UTC, abeatrix commented on client/cody/src/non-stop/TaskController.ts
> +        this._disposables.push(vscode.commands.registerCommand('cody.fixup.open', id => this.showThisFixup(id)))
I kept thinking the controller is linked to the provider that's why I did it this way, but what you explained makes sense so I've updated taskcontroller to have its own dispose method! 👍

2023-05-27 00:31 UTC, merged