Fix CodyInstalled logic for relogins
sourcegraph/sourcegraph pull request #52345
Opened 2023-05-24 02:00 UTC by nathan-downs

## Test plan

Run VS Code extension in debug mode
Verify events in event_logs
Verify events on dotcom

2023-05-24 02:03 UTC, nathan-downs commented
![Screenshot 2023-05-23 at 7 02 38 PM](https://github.com/sourcegraph/sourcegraph/assets/85511556/7dcd21ea-91a9-48d4-a6fa-625760dc1b2c)

2023-05-24 02:03 UTC, nathan-downs commented on client/cody-shared/src/telemetry/EventLogger.ts
> -        console.log('api requqest for anonID: ' + anonymousUserID)
Old debug line.

2023-05-24 02:04 UTC, nathan-downs commented on client/cody/src/event-logger.ts
> +    await eventLogger.log(eventName, anonymousUserID, argument, publicArgument)
This is the second part of what was breaking event logging.

2023-05-24 03:44 UTC, nathan-downs commented
![Screenshot 2023-05-23 at 8 43 56 PM](https://github.com/sourcegraph/sourcegraph/assets/85511556/fb7a04f3-c3d6-4a20-bf67-11ce1e0bb5f8)

2023-05-24 03:44 UTC, nathan-downs commented
Verified that this is fixed and showing up both in the s2 event_logs and in dotcom as an anonymous event.

2023-05-24 07:36 UTC, philipp-spiess requested changes
I think we need some changes here. This logic starts to await network roundtrips (up to two requests per event) in very latency susceptible parts of the code base (e.g. completion calculation).

It's unclear to me why this is needed. Do we have issues with out-of-order events? If so, can we add a queue to the event logger interface instead?

2023-05-24 07:36 UTC, philipp-spiess commented on client/cody/src/completions/index.ts
> +        await logEvent('CodyVSCodeExtension:completion:started', LOG_INLINE, LOG_INLINE)
Do we need to await the event sending everywhere? This introduces additional latency to some of the highly interacted with code paths for something that is not needed for the user to know about. 

If there are issues with out-of-order events we should implement proper queueing on the event logger instance instead.

```suggestion
        logEvent('CodyVSCodeExtension:completion:started', LOG_INLINE, LOG_INLINE)
```

2023-05-24 07:36 UTC, philipp-spiess commented on client/cody/src/event-logger.ts
> +    await eventLogger.log(eventName, anonymousUserID, argument, publicArgument)
Can you clarify how this is breaking event logging? I think the only difference here is that we do not wait for the event to be sent before completing with the rest of the logic

2023-05-24 18:03 UTC, nathan-downs commented on client/cody/src/completions/index.ts
> +        await logEvent('CodyVSCodeExtension:completion:started', LOG_INLINE, LOG_INLINE)
I'll do some testing on removing that--logEvent is making an API call that wasn't getting completed that I'm trying to solve for

2023-05-25 04:10 UTC, nathan-downs commented
<img width="1133" alt="Screenshot 2023-05-24 at 9 07 18 PM" src="https://github.com/sourcegraph/sourcegraph/assets/85511556/8faa4282-4748-4dca-843d-7efa53d7954c">
<img width="995" alt="Screenshot 2023-05-24 at 9 07 09 PM" src="https://github.com/sourcegraph/sourcegraph/assets/85511556/f3e0985e-d590-4bdf-8c7d-f7e9b9c99650">

2023-05-25 08:47 UTC, philipp-spiess approved these changes
Nice! Thank you for changing this to not block our critical paths 💪

2023-05-25 08:48 UTC, merged