first commit
sourcegraph/sourcegraph pull request #52862
Opened 2023-06-02 14:48 UTC by akalia25

Add field useContext to events to inform us what context users are using: embeddings, keyword, none

## Test plan
test locally and verify data is showing args field

2023-06-02 15:15 UTC, dadlerj requested changes
Thank you for this! Question: should we also add whether suggestions is toggled, chat predictions, inline, guardrails, non stop, etc.? Perhaps just a higher level `configuration` field that contains all of those? We could exclude the uninteresting ones (like debug options) and ones that contain private data (like `codebase`).

2023-06-02 15:15 UTC, dadlerj commented on client/cody-shared/src/telemetry/EventLogger.ts
> +    private useContext = _getUseContextFromConfig(config)
I don't think we use the underscore notation for internal functions in this codebase, so you can remove it

2023-06-02 15:15 UTC, dadlerj commented on client/cody-shared/src/telemetry/EventLogger.ts
> +            useContext: this.useContext,
I would just call this `context`, or maybe `contextSelection` or something like that. While the config option _is_ called `useContext`, it's not the most intuitive name for analytics purposes.

2023-06-02 15:15 UTC, dadlerj requested changes
Thank you for this! Question: should we also add whether suggestions is toggled, chat predictions, inline, guardrails, non stop, etc.? Perhaps just a higher level `configuration` field that contains all of those? We could exclude the uninteresting ones (like debug options) and ones that contain private data (like `codebase`).

2023-06-02 15:36 UTC, akalia25 commented on client/cody-shared/src/telemetry/EventLogger.ts
> +    private useContext = _getUseContextFromConfig(config)
> Thank you for this! Question: should we also add whether suggestions is toggled, chat predictions, inline, guardrails, non stop, etc.? Perhaps just a higher level `configuration` field that contains all of those? We could exclude the uninteresting ones (like debug options) and ones that contain private data (like `codebase`).

Great suggestion! It would be like our `extensionDetails` but for `configuration`. I'll update this PR to reflect; we'll need to keep an eye out for new configurations that get added going forward so we can continue expanding this :D

2023-06-02 17:43 UTC, akalia25 commented
validated that we are receiving this in dotcom.events in the format we want:
 
![image](https://github.com/sourcegraph/sourcegraph/assets/32119652/9ae57e33-694b-4e9d-9d57-bfb427159dea)

2023-06-02 17:43 UTC, nathan-downs approved these changes
Verified that data is coming through, LGTM!

2023-06-02 18:04 UTC, dadlerj requested changes

2023-06-02 18:04 UTC, dadlerj commented on client/cody-shared/src/telemetry/EventLogger.ts
> +    private configurationDetails = {
I think we need to either move this into the event logging function (so we pull this data live each time an event is logged) OR set up a listener for configuration changes so we can update this object whenever the user changes anything. Otherwise, we'll be reporting config details from when VS Code was last started up, and any changes won't be reflected live.

The latter option is definitely better—it won't require re-pulling config details on EVERY event, which could slow things down.

I think the right way to do this is create a top level function in the eventlogger called `onConfigurationChange` that handles a new config object being passed in (that updates this variable), and then to call it from here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@513afd9/-/blob/client/cody/src/main.ts?L283

2023-06-05 20:40 UTC, akalia25 commented
confirmed this is working and updating as the config file updates
![image](https://github.com/sourcegraph/sourcegraph/assets/32119652/6cbcd948-9969-4c45-93a5-2c68b73ebc4e)

2023-06-05 22:54 UTC, akalia25 commented on client/cody-shared/src/telemetry/EventLogger.ts
> +    private configurationDetails = {
Hey @dadlerj, updated the PR to follow the latter suggestion of the top level function `onConfigurationChange`. Tested the changes and its working as expected when configuration changes, the logging updates to reflect that (see screenshot). 

All the CI checks pass, i'll tag team-cody for review and get this merged. Thanks for the suggestion of adding a listener!! 🚀

2023-06-07 15:02 UTC, dadlerj requested changes
Thank you @akalia25 ! Sorry for all of the comments, these are mostly just code hygiene. Let me know if you want to do a walkthrough.

2023-06-07 15:02 UTC, dadlerj commented on client/cody/src/main.ts
> +            onConfigurationChange(newConfig)
So with the changes above (moving the `onConfigurationChange` into the `EventLogger` class), you can now change the way you call this. I would actually import `eventLogger` (the global singleton eventlogger) from client/cody/src/event-logger.ts, and change this line to `eventLogger.onConfigurationChange(newConfig)`. That would work better with the function being a member of the EventLogger class, and would also allow you to remove an unnecessary import (the cody-shared/src/telemetry/EventLogger.ts library) that got added here!

2023-06-12 04:51 UTC, akalia25 commented on client/cody-shared/src/telemetry/EventLogger.ts
>  const config = vscode.workspace.getConfiguration()
great point! It was a const prior to this PR, updated to remove this and use `vscode.WorkspaceConfiguration()`

2023-06-12 04:54 UTC, akalia25 commented on client/cody-shared/src/telemetry/EventLogger.ts
> +export function onConfigurationChange(newconfig: any): any {
Thanks for this suggestion! I moved `onConfigurationChange` inside the eventLogger class and update `this.configurationDetails` with the `newconfig` that gets passed

2023-06-12 04:55 UTC, akalia25 commented on client/cody-shared/src/telemetry/EventLogger.ts
> +let configurationDetails = {
implemented :)

2023-06-12 04:58 UTC, akalia25 commented on client/cody/src/main.ts
> +            onConfigurationChange(newConfig)
Great point! I imported eventLogger and called the function through that :) thank you for your detailed comments

2023-06-12 05:04 UTC, akalia25 commented
@dadlerj Thanks for the detailed review; I really appreciate it! :) I implemented the suggestions you made and tested to confirm that it is logging the correct settings when updates are made.

2023-06-12 05:07 UTC, akalia25 commented on client/cody/src/main.ts
> +                eventLogger.onConfigurationChange(vscode.workspace.getConfiguration())
on `main.ts` I used `eventLogger.onConfigurationChange(vscode.workspace.getConfiguration())` instead of passing in `newConfig` since configurationDetails wasnt actually getting updated with that.

2023-06-12 05:08 UTC, akalia25 commented on client/cody/src/event-logger.ts
> +export let eventLogger: EventLogger | null = null
had to export so it could be used in `main.ts`

2023-06-12 23:30 UTC, dadlerj approved these changes
Looks great! I would suggest at least one review from an engineer on the Cody team. Thanks

2023-06-13 15:23 UTC, akalia25 commented on client/cody/src/main.ts
> +                eventLogger.onConfigurationChange(vscode.workspace.getConfiguration())
Yes, that's what I'm finding is that `newConfig` is not being updated 🤔. Whenever I passed `newConfig` to the function `onConfigurationChange` it would never update to the latest Cody settings and keep sending the old settings to BQ. I don't know if you remember but thats also the reason I reinitiated newConfig in the `onConfigurationChange` function ref [here]((https://github.com/sourcegraph/sourcegraph/pull/52862#discussion_r1221735136) ) https://github.com/sourcegraph/sourcegraph/pull/52862#discussion_r1221735136 since it wouldnt send the right data to BQ otherwise. I'll file a bug with the team and let them know what I discovered

2023-06-14 03:36 UTC, thenamankumar commented on client/cody-shared/src/telemetry/EventLogger.ts
> +    return config.get<string>('cody.useContext', '')
`return config?.get<string>('cody.useContext', '') || ''`

Not a blocker, but you can do ^.

2023-06-14 03:37 UTC, thenamankumar approved these changes

2023-06-14 14:29 UTC, merged