Cody: Chat History
sourcegraph/sourcegraph pull request #52904
Opened 2023-06-05 05:12 UTC by deepak2431

This PR closes #52544,  #52848 and #52890.

The issues mostly overlapped, so I handled it in this PR.

Changes made:
1. Add history to the history list on each new conversation started.
2. Display the last human message in history instead of the assistant message.
3. Add a delete button to delete individual chats from history.
4. Load the most recent chat, if available, from the history.
5. Fix the loading of context files.

## Test plan

All E2E tests have passed.

2023-06-05 06:13 UTC, deepak2431 commented
@abeatrix @toolmantim Requesting review for this PR.

2023-06-05 14:09 UTC, abeatrix commented
@deepak2431 Thanks for the ping! I have tagged my team for review and we will get to this asap, thank you so much for the PR ❤️

2023-06-05 14:31 UTC, deepak2431 commented
> @deepak2431 Thanks for the ping! I have tagged my team for review and we will get to this asap, thank you so much for the PR ❤️

Thanks a lot, @abeatrix. I was looking to add more E2E tests for this. Just a question, how to run the extension in browser mode so I can look over the proper selectors to pick and attach events to it? 
Or is there a different way to debug extensions for getting the selectors to attach test events?

2023-06-06 10:54 UTC, abeatrix commented
@deepak2431 if you start the e2e test in debug mode and then hit record in the pop up console, it will show you the name of each selector you hover or click on (all thanks to @philipp-spiess 🙏 )

2023-06-06 15:26 UTC, deepak2431 commented
> all thanks to @philipp-spiess 🙏 )

@abeatrix Got that. This works fantastic this way as it captures most of it during the record.

2023-06-06 15:27 UTC, deepak2431 commented
> > all thanks to @philipp-spiess 🙏 )
> 
> @abeatrix Thanks, Got that. This works fantastic as it captures most of it during the record.

2023-06-06 16:46 UTC, deepak2431 commented
@abeatrix Added the tests. It was fun to write tests by recording the events in sequential order to get the selectors.

2023-06-07 07:21 UTC, abeatrix requested changes
Left some comments inline. The new behavior makes a lot more sense to me so thank you so much for working on this 🙇  
In addition, the Clear History button is still clickable if you remove the history item one by one. I tried updating it to `disabled={!userHistory || !Object.keys(userHistory).length}` and it fixed it for me :)

2023-06-07 10:27 UTC, deepak2431 commented
> Left some comments inline. The new behavior makes a lot more sense to me so thank you so much for working on this 🙇 In addition, the Clear History button is still clickable if you remove the history item one by one. I tried updating it to `disabled={!userHistory || !Object.keys(userHistory).length}` and it fixed it for me :)

Thanks a lot for the review @abeatrix, and for thoroughly testing it. I will make all the requested changes here soon.

2023-06-07 10:33 UTC, deepak2431 commented on client/cody/webviews/UserHistory.tsx
> +                                                    onClick={event => {
Thanks for pointing this out, I can reproduce it here too.

2023-06-07 10:34 UTC, deepak2431 commented on client/cody/webviews/UserHistory.module.css
> +    top: 0.25rem;
yeah, that would be better to do.

2023-06-07 10:43 UTC, deepak2431 commented on client/cody/src/chat/ChatViewProvider.ts
> +        this.sendChatHistory()
Yeah, it's calling saveChatHistory(), but the method I have used is sendChatHistory(). So, this should send the current chat instantly the response is received for the started chat or not.

2023-06-07 18:55 UTC, deepak2431 commented on client/cody/src/chat/ChatViewProvider.ts
> +        await this.localStorage.deleteChatHistory(chatID)
I think both might be the same, as while saving the chat history, we are updating the local storage to rewrite its values getting the chat and input history.  We can go with either was I feel. Let me know what you think would be best way!

2023-06-07 18:58 UTC, abeatrix approved these changes

2023-06-07 18:58 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> +        this.sendChatHistory()
I'm not sure too but this is working so we can revisit later if it becomes an issue :)

2023-06-07 19:03 UTC, deepak2431 commented on client/cody/src/chat/ChatViewProvider.ts
> +        await this.localStorage.deleteChatHistory(chatID)
Just curious, what issue do you think it can create later?

2023-06-07 19:09 UTC, deepak2431 commented
> Approved! Once the conflict is resolved, we can merge this 🎉 thank you so much for the great work!

Thanks a lot, @abeatrix, for the complete review. I have resolved the conflicts so all good to be merged now!

2023-06-08 07:07 UTC, abeatrix commented
@deepak2431 i tried to merge but your PR is not passing the e2e tests 🤔

2023-06-08 07:44 UTC, deepak2431 commented
@abeatrix Hmm, not sure, as it's passing all of them here 👀
![iScreen Shoter - Code - 230608131158](https://github.com/sourcegraph/sourcegraph/assets/44617923/a9463c5b-1b90-474c-b88a-08f659391137)

2023-06-10 06:30 UTC, toolmantim commented
@deepak2431 I think https://github.com/sourcegraph/sourcegraph/pull/53224 should fix the build errors. Can you merge main into this branch, so we can see? Thanks!

2023-06-10 15:14 UTC, deepak2431 commented
> @deepak2431 I think #53224 should fix the build errors. Can you merge main into this branch, so we can see? Thanks!

@toolmantim I have merged the main and updated the integration test, which I saw now was breaking because we can now load the last chat. So, we need to clear the history after each test gets completed.

All the E2E tests are passing locally. 
All integration tests have passed, too, except the Local file finder one.

I hope now the build will succeed as in the logs it shows E2E tests failing, but I'm not sure why!

2023-06-12 10:53 UTC, deepak2431 commented
@philipp-spiess @abeatrix @toolmantim  Thanks a lot. Finally, I can see that the required failing build is successful in this PR!

2023-06-12 11:13 UTC, merged