Cody WIP: Add CodeLens to Fixup Task
sourcegraph/sourcegraph pull request #52975
Opened 2023-06-06 00:14 UTC by abeatrix

Close https://github.com/sourcegraph/sourcegraph/issues/52873

PR to add Code Lens to each Fixup Task

TODO: Update e2e test

## Test plan

Loom: https://www.loom.com/share/e34903d90dbc4a7f8dde06d48320b727
 
TODO: Update e2e test

2023-06-06 14:26 UTC, dominiccooney requested changes
Good start, feedback inline.

2023-06-06 14:26 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLens.ts
> +        void vscode.commands.executeCommand('workbench.action.files.save')
I don't think we want to save the file here. We just want to apply the fixup.

- Add an interface for triggering diffs or applying a fixup.
- Implement the interface in the FixupController.
- Add a field to the FixupCodeLens for that role interface.
- Pass the FixupController to the FixupCodeLens, but narrow it to that interface. Look how the decorator does it.
- When there's an action, call back into the FixupController to do the action.

2023-06-06 14:26 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLens.ts
> +        if (id && id !== this.id) {
This pattern recurs in a few places and it looks odd to me. When would you call remove with no id? Why does the codelens have default id of ''?

We should have one code lens provider, and it can maintain whatever it needs for a fixup in maps and things.

2023-06-06 14:26 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLens.ts
> +        this.selectionRange = null
These ranges will need to be live and respond to edits. Add a method which I can ping when the range changes.

2023-06-06 14:26 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLens.ts
> +        this.status = CodyTaskState.idle
This duplicates a bunch of things about the fixuptask, like status and ranges. Duplicate if you have to, but if you can instead just hold onto tasks, observe them, and use their state—do that.

2023-06-06 14:26 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLens.ts
> +        state === CodyTaskState.applying
Let's add doc comments to the CodyTaskState because I'm not clear what the states mean.

2023-06-06 14:26 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLens.ts
> +        tooltip: 'Click to remove decorations',
Is there a vscode style guide for strings like this? Our other tooltips don't say "click to ..."

2023-06-06 14:26 UTC, dominiccooney commented on client/cody/src/non-stop/FixupTask.ts
> +import { FixupCodeLens } from './FixupCodeLens'
We should keep the fixuptask separate from the code lens. The FixupController should operate on the task, and farm out notifications to whatever needs to know.

We could tie them together more like this, but we'll regret it when we want to do things like saving and restoring fixup tasks, or having a more complicated tasks like fixup in notebooks.

2023-06-06 20:02 UTC, abeatrix commented on client/cody/src/non-stop/FixupCodeLens.ts
> +            vscode.commands.registerCommand('cody.fixup.codelens.save', (id: string) => this.save(id)),
This is just using the same code lens from Inline Assist. Wanted to confirm with you on how you want the Code Lenses to be structured before I make further changes so don't worry about the wordings for now 😄

2023-06-07 21:57 UTC, dominiccooney approved these changes
Great! Some comments inline.

Is it possible to test this yet, or do we want to e2e test and need more functionality done?

2023-06-07 21:57 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLenses.ts
> +    public static get instance(): FixupCodeLenses {
I'd like to avoid globals like this as much as possible, feel it will control our entrypoints through the controller. Can the controller simply instantiate this and hang onto it?

2023-06-07 21:57 UTC, dominiccooney commented on client/cody/src/non-stop/FixupCodeLenses.ts
> +function getLensesByState(codeLensRange: vscode.Range, state: CodyTaskState, id: string): vscode.CodeLens[] {
This is cool, it's great how clearly the set of items we're providing in each state is laid out here.

2023-06-07 21:57 UTC, dominiccooney commented on client/cody/src/non-stop/FixupController.ts
> +        this.codelenses.set(task.id, CodyTaskState.queued, task.selectionRange)
Why do we need to make repeated calls like this?

2023-06-07 21:57 UTC, dominiccooney commented on client/cody/src/non-stop/FixupController.ts
> +        this.getFilesWithApplicableFixups()
"get..." sounds like it is just reading some data. Rename this method to reflect the state transition that happened "did..." or at least updating objects "update...".

Prefer the "didX", just need to work out what "X" is.

Question, but why do we need to iterate over all fixups when just one of them may have changed? We should try to do as little work as possible so we don't get huge cascades of work. For example, applying a fixup may already cause text and range changed updates to other fixups. If we refresh them all all the time we're going to end up doing *lots* of redundant work.

2023-06-07 21:57 UTC, dominiccooney commented on client/cody/src/non-stop/FixupController.ts
> +        await task.apply()
Let's rename this because it sounds like it applies the task, but it is just causing the state transition IIRC. We could even make this `setState` and route all the task state changes through it; then that method can have a switch statement which shows what the valid state transitions are.

2023-06-07 21:57 UTC, dominiccooney commented on client/cody/src/non-stop/FixupTask.ts
> +    private async replaceSelection(): Promise<void> {
We won't do replacement this way, we will send vscode a minimal set of edits without adjusting the selection. So delete this, put a TODO where you were calling it and I'll work in the edit building code from that hacky apply diff.

2023-06-07 23:45 UTC, abeatrix commented on client/cody/src/non-stop/FixupController.ts
> +        this.getFilesWithApplicableFixups()
I don't remember to be honest. it was added in the last PR, but it does seem unnecessary at the moment. I'm going to try removing it and see if that affect anything

2023-06-07 23:45 UTC, abeatrix commented on client/cody/src/non-stop/FixupController.ts
> +        await task.apply()
Yea agree! I've made this change in my local branch 😄

2023-06-07 23:46 UTC, abeatrix commented on client/cody/src/non-stop/FixupController.ts
> +        await task.apply()
Yea agree! I've made this change in my local branch 😄

2023-06-08 01:38 UTC, abeatrix commented on client/cody/src/non-stop/FixupController.ts
> +        this.getFilesWithApplicableFixups()
Removed 👍

2023-06-08 06:12 UTC, abeatrix commented
### progress update:

https://www.loom.com/share/0050b9ed72b645af9fc899a8b3c0f940

Will clean up the code and address the rest of the unresolved issues tmr, and then start on the tests

2023-06-08 11:29 UTC, merged