Cody: Add status bar item
sourcegraph/sourcegraph pull request #53307
Opened 2023-06-12 13:35 UTC by philipp-spiess

Closes #52597

This PR adds a new status bar item for Cody that we can use as a global loading indicator (helpful for completions) and an easy way to enable/disable features. More features coming soon!

As a follow-up we should make sure that all of these three features can be turned on/off without having to reload the editor cc @abeatrix @lrhacker 

## Test plan

https://github.com/sourcegraph/sourcegraph/assets/458591/ab2b5a5e-6b38-4010-92f1-1796ef0a3c10

2023-06-12 15:16 UTC, umpox approved these changes
Nice!

2023-06-12 15:16 UTC, umpox commented on client/cody/CHANGELOG.md
> +- Added a new Cody status bar item to relay global loading states and allowing you to quickly enable/disable features [pull/](https://github.com/sourcegraph/sourcegraph/pull/)
```suggestion
- Added a new Cody status bar item to relay global loading states and allowing you to quickly enable/disable features [pull/53307](https://github.com/sourcegraph/sourcegraph/pull/53307)
```

2023-06-12 15:16 UTC, umpox commented on client/cody/src/status-bar.ts
> +                    await vscode.window.showInformationMessage(name + ' ' + (isEnabled ? 'disabled' : 'enabled') + '.')
```suggestion
                    const response = await vscode.window.showInformationMessage(name + ' ' + (isEnabled ? 'disabled' : 'enabled') + '.', 'Reload Window')
                    
                    if (response === 'Reload Window') {
                      // Execute reload vscode command
                    }
```

Optional: If it's not trivial to make these work without reloading, we could add a button to the message that prompts users to reload VSCode. Didn't check this code

2023-06-12 15:16 UTC, umpox commented on client/cody/src/status-bar.ts
> +                    label: '$(cody-logo) Share Feedback',
```suggestion
                    label: '$(feedback) Share Feedback',
```

So it is consistent with the current feedback item?

2023-06-12 19:48 UTC, abeatrix reviewed
Update:Resolved. I had cody.suggestions enabled instead of cody.completions

Is there anything I'll need to change to get the cody icon to show up in my status bar?

<img width="2044" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/2038c130-3e67-413b-a0f8-7c699df5c300">

2023-06-12 19:48 UTC, abeatrix commented on client/cody/src/status-bar.ts
> +import * as vscode from 'vscode'
should we move this to `/src/services`?

2023-06-12 20:39 UTC, abeatrix requested changes

2023-06-12 20:39 UTC, abeatrix commented on client/cody/src/status-bar.ts
> +    statusBarItem.text = '$(cody-logo)'
```suggestion
    statusBarItem.tooltip = 'Cody Features Toggle'
    statusBarItem.name = 'Cody AI by Sourcegraph'
    statusBarItem.text = '$(cody-logo)'
```

Before: 
No hover test:
<img width="675" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/03075c42-5f37-41f9-8d23-2d926df55055">

<img width="1144" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/dcb49e93-d3de-4b3b-a738-63379e1c735d">


After:
<img width="458" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/9ef80dea-c377-4bf4-a9ce-787a63fbb977">
<img width="803" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/96b4a096-c659-49e4-93e7-efac4ace8d8d">

2023-06-12 20:39 UTC, abeatrix commented on client/cody/src/main.ts
> +        const statusBar = createStatusBar()
```suggestion
    const statusBar = createStatusBar()
    disposables.push(statusBar)
    if (initialConfig.completions) {
```

Shouldn't we display the logo even if completions is not enabled so that users can still toggle other features using the status bar?

2023-06-12 20:39 UTC, abeatrix commented on client/cody/src/status-bar.ts
> +                createFeatureToggle('Code Fixups (Beta)', 'cody.experimental.inline', c => c.experimentalInline),
```suggestion
                createFeatureToggle('Code Inline Assist (Beta)', 'cody.experimental.inline', c => c.experimentalInline),
                createFeatureToggle('Code Fixups (Experimental)', 'cody.experimental.nonStop', c => c.experimentalNonStop),
```

2023-06-12 20:59 UTC, philipp-spiess commented on client/cody/src/main.ts
> +        const statusBar = createStatusBar()
YES sorry that was a total oversight I added it _only_ for completions first. :D

2023-06-12 20:59 UTC, philipp-spiess commented on client/cody/src/status-bar.ts
> +import * as vscode from 'vscode'
Sure whatever works :)

2023-06-12 21:00 UTC, philipp-spiess commented on client/cody/src/status-bar.ts
> +    statusBarItem.text = '$(cody-logo)'
Also makes sense, thanks! 😎

2023-06-13 10:48 UTC, abeatrix approved these changes

2023-06-13 10:48 UTC, abeatrix commented on client/cody/src/status-bar.ts
> +                createFeatureToggle('Code Fixups (Experimental)', 'cody.experimental.nonStop', c => c.experimentalNonStop),
```suggestion
               
```
Sorry I added this but I talked to Dom and it seems like non stop doesn't support toggling at the moment so we might want to remove it for now 🙇‍♀️

2023-06-13 12:01 UTC, valerybugakov approved these changes

2023-06-13 12:01 UTC, valerybugakov commented on client/cody/src/status-bar.ts
> +            option.onSelect()
Does it make sense to catch and log an error here?

2023-06-13 12:03 UTC, philipp-spiess commented
@toolmantim You have to reload afterwards. I have a follow-up ticket to make it automatically reload. Will add @umpox's suggestion of a reload button for now

2023-06-13 12:39 UTC, toolmantim commented
Alright, I've just pushed up some design improvements…

<img width="658" alt="Screenshot 2023-06-13 at 10 36 41 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/dd8d3006-4827-4335-a38a-87a85f7e8d26">

I'll beef up the icon a bit…

2023-06-13 12:44 UTC, toolmantim commented
> You have to reload afterwards. I have a follow-up ticket to make it automatically reload. Will add @umpox's suggestion of a reload button for now

@philipp-spiess oh, I wasn't even talking about using the feature… more just that it doesn't seem to be affecting the actual underlying setting at all:

https://github.com/sourcegraph/sourcegraph/assets/153/eebd6444-0acf-41af-b32d-f5cb100e8f4f

2023-06-13 13:06 UTC, philipp-spiess commented
@toolmantim I can not reproduce this but I also noticed I have uncommitted changes 😶‍🌫️ Maybe that's why it works for me? 

https://github.com/sourcegraph/sourcegraph/assets/458591/b69279e1-45a2-4cf8-86a4-f86fdb8f3b59

2023-06-13 13:38 UTC, toolmantim commented
@philipp-spiess has the setting been renamed? Perhaps we need to smooth migrate people across to the new setting, if it causes this bug? It would be fine to have it just reset, given it was experimental… but probably not stop you from turning it on…

Here's my Cody-related user settings JSON:

```json
{
  "cody.experimental.chatPredictions": false,
  "cody.experimental.suggestions": true,
  "cody.experimental.inline": false,
  "cody.experimental.nonStop": true,
  "cody.debug.enable": true,
  "cody.debug.verbose": true,
  "cody.completions": false
}
```

2023-06-13 13:39 UTC, toolmantim commented
Alright! Chunkier logo is in 🏴‍☠️

<img width="178" alt="Screenshot 2023-06-13 at 11 35 40 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/0cd8896c-f724-4cc0-a4e6-832ca1840027">

2023-06-13 13:50 UTC, philipp-spiess commented
> @philipp-spiess has the setting been renamed? Perhaps we need to smooth migrate people across to the new setting, if it causes this bug? It would be fine to have it just reset, given it was experimental… but probably not stop you from turning it on…

Hmm yeah that's probably it. It tried to be smart about it and enable completions when the deprecated flag value is set but I haven't considered the UI to change settings so now it will show as disabled in the UI even when it's enabled 🙃  I think we'll need to run a migration script on startup or so instead. I'll revert the change on `main` (Since we aren't 100% sure on the name yet + I want to push a bugfix release) and will follow up with the fixes.

Glad you found this 😬

2023-06-13 13:53 UTC, toolmantim approved these changes

2023-06-14 09:47 UTC, philipp-spiess commented
@toolmantim Here's a final video. This looks so good now 😍 

https://github.com/sourcegraph/sourcegraph/assets/458591/6061f01f-ab5f-4db6-8d93-9fa83ce19c21

2023-06-14 10:07 UTC, philipp-spiess commented on client/cody/src/services/FeedbackOptions.ts
> +]
cc @abeatrix this is the shared stuff as that I mentioned in the Figma :)

2023-06-14 10:19 UTC, merged

2023-06-14 13:07 UTC, abeatrix commented on client/cody/src/services/FeedbackOptions.ts
> +]
Oh I've already added it to my PR yesterday, but if yours land first i can remove mine and merge yours 👌 https://github.com/sourcegraph/sourcegraph/pull/53434

2023-06-14 13:10 UTC, philipp-spiess commented on client/cody/src/services/FeedbackOptions.ts
> +]
@abeatrix Already landed mine 😬