cmd/gitserver: Add in-built metrics to common.Queue
sourcegraph/sourcegraph pull request #53325
Opened 2023-06-12 17:44 UTC by indradhanush

Part of #40330.

## Test plan

- Updated test
- Did some quick smoke tests for repo cloning, changelist mapping and metrics in Grafana, need to do some more

2023-06-12 19:51 UTC, peterguy commented on cmd/gitserver/server/perforce/perforce.go
> +	if j.uuid == uuid.Nil {
This isn't thread-safe. Are there thread-safe controls placed around callers? What about using `sync.Once` here?

2023-06-12 19:51 UTC, peterguy commented on cmd/gitserver/server/server.go
> +	if c.uuid == uuid.Nil {
Should `sync.Once` also be used here?

2023-06-12 20:23 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +	return fmt.Sprintf("src_%s_%s", q.name, name)
rather hardcode the name then use a label to distinguish which queue this is. Benefit of hardcoding the name is you can then find other queues as well as having a metric which you can actually grep for.

2023-06-12 20:23 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +	q.waitTime.WithLabelValues(job.UUID(), job.Identifier(), "push").Observe(float64(time.Now().Unix()))
you can't put high cardinality data into prometheus. IE both UUID and identifier can't be a label. 

additionally you are observing the current time, not the wait time.

2023-06-13 10:35 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	return fmt.Sprintf("src_%s_%s", q.name, name)
That's a good idea. Fixed.

2023-06-13 10:35 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +	if j.uuid == uuid.Nil {
Changed the approach a little bit as per Keegan's suggestions and now I don't need UUID anymore. But I'm using `sync.Once` in other places now. Great callout!

2023-06-13 10:36 UTC, indradhanush commented on cmd/gitserver/server/server.go
> +	if c.uuid == uuid.Nil {
Fixed.

2023-06-13 10:39 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	q.waitTime.WithLabelValues(job.UUID(), job.Identifier(), "push").Observe(float64(time.Now().Unix()))
Hmm. That makes sense. Initially I was trying to for:

1. Insert timestamp at push
2. Insert timestamp at pop
3. Calculate delta in metric

And I realised that `waitTime` wasn't the best choice of name for the kind of metrics this was going to store. After reading your comment and more thought, I have now changed the approach to:

1. On push, track the current time as part of the job's metadata
2. On pop, insert the time delta by reading the `pushedAt` time from the job's metadata 

So now `waitTime` would make more sense. Also now I don't need to track unique job's and can use the job identifier as the only dimension. Multiple writes with the same job identifier (for a subsequent clone / mapping request of the same repo for example) should not be a problem anymore.

2023-06-13 11:01 UTC, keegancsmith requested changes
I have quite a bit of feedback here, happy to jump on a call to help. But I think this PR can be drastically simplified.

2023-06-13 11:01 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +	}, []string{"queue"})
dequeued total is a redundent metric since it is just enqueued total - queue length.

2023-06-13 11:10 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	job.SetPushedAt()
If the same job is pushed to the queue in quick succession before the first copy of the job has been processed, we're going to have two elements with the same job identifier. I thought about this and is why ended up adding the metadata on the job itself. How can we track two jobs that have the same identifier as separate entities on the queue? 🤔

2023-06-13 11:48 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +		Name: "src_gitserver_generic_queue_wait_time",
Fixed.

2023-06-13 11:50 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +func (q *Queue[T]) RecordProcessingTime(job T, start time.Time) {
Hmm. But isn't recording the processing time part of the interaction with the queue? And having it as part of the queue's API would ensure future implementers are less likely to miss this? Besides, if we want to drop this method we need to then export the underlying metric. And we don't do that for the other metrics and this starts feeling like an anti-pattern against the other metrics. I'm not 100% convinced. Happy to get on a call and find the optimal design.

2023-06-13 11:51 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	name string
Fixed.

2023-06-13 11:51 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	}, []string{"queue"})
Makes sense. Fixed.

2023-06-13 12:06 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +	job.SetPushedAt()
See my suggestion above around a done function. You then do central bookkeeping to make decision on if a job is in the queue, being processed, both or neither. Right now setpushedat doesn't really stop that stuff.

2023-06-13 12:20 UTC, keegancsmith commented
I am guessing you are wanting this to get in before branch cut tomorrow. I will check my github notifs again before my EOD, but you are welcome to opsgenie alert me before 5pm SAST today for faster feedback. Of course also happy to jump onto a call.

2023-06-13 12:52 UTC, indradhanush commented
> I am guessing you are wanting this to get in before branch cut tomorrow. I will check my github notifs again before my EOD, but you are welcome to opsgenie alert me before 5pm SAST today for faster feedback. Of course also happy to jump onto a call.

@keegancsmith Yes, that's right. I just pushed another commit to address the suggestion to return a doneFunc from `Pop`. If there's more follow up needed, then let's jump on a call today or tomorrow in that case. I'm around.

2023-06-13 13:29 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +	}
if I am not mistaken you don't need to pass in a val. You could do this
```suggestion
	processingStart := time.Now()
	return &job, func() {
		q.processingTime.Observe(time.Since(processingStart).Seconds())
	}
```

2023-06-13 13:31 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +	Identifier() string
no longer used?

2023-06-13 13:31 UTC, keegancsmith commented on cmd/gitserver/server/common/queue_test.go
> +func (t *testJob) UUID() string { return t.Value }
neither of these are used? Same for some other impl of Jobber

2023-06-13 13:37 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +	job.SetPushedAt()
FYI if you want to remove the interface Jobber entirely you can remove SetPushedAt by having

```go
type queueItem[T] struct {
    value T
    pushedTime time.Time
}
```

then

```suggestion
    q.jobs.PushBack(queueItem[T]{
      value: job,
      pushedTime: time.Now(),
    })
	q.Cond.Signal()
```

2023-06-13 13:38 UTC, keegancsmith commented on cmd/gitserver/server/common/queue.go
> +}
its not clear to me why you need a sync.Once. Why would you push the same struct multiple times? From what I can tell you always push a brand new struct whenever you use Push.

2023-06-13 13:39 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +}
no longer called

2023-06-13 14:42 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	}
Yeah, that makes sense. I just tested it out with this:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	start := time.Now()
	slowFunc := func() {
		fmt.Println("starting slow func")
		time.Sleep(2 * time.Second)
		fmt.Println(time.Since(start).Seconds())
	}

	fmt.Println("since start", time.Since(start).Seconds())
	slowFunc()
}
```

And the output is:

```
$ go run main.go
since start 4.2e-08
starting slow func
2.000240834
```

2023-06-13 14:48 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	}
I've fixed this now. But the function now returns the duration elapsed so that consumers know how long it took and can decide to do something based on that information if they want.

2023-06-13 14:48 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +func (q *Queue[T]) RecordProcessingTime(job T, start time.Time) {
Fixed.

2023-06-13 14:50 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	Identifier() string
Sorry forgot to delete. Fixed now.

2023-06-13 14:50 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +	job.SetPushedAt()
Makes sense. I've dropped the interface and it looks much simpler now. Thank you. :)

2023-06-13 14:51 UTC, keegancsmith approved these changes
I am approving to unblock. I believe the implementation is correct and we can follow-up with design nits.

2023-06-13 14:52 UTC, indradhanush commented on cmd/gitserver/server/common/queue.go
> +}
I've deleted this API now. When I wrote this, because this was available for consumers to call, I wanted to guard against acccidental misuse as resetting the pushedAt would have led to painful debugging.

2023-06-13 16:50 UTC, merged

2023-06-14 06:42 UTC, keegancsmith commented on cmd/gitserver/server/perforce/perforce.go
> +			s.Logger.Warn("mapping job took long to complete", log.Float64("seconds", timeTaken.Seconds()))
fyi there is `log.Duration`

2023-06-14 06:52 UTC, indradhanush commented on cmd/gitserver/server/perforce/perforce.go
> +			s.Logger.Warn("mapping job took long to complete", log.Float64("seconds", timeTaken.Seconds()))
TIL. Will fix.