Make embeddings status icon realtime
sourcegraph/sourcegraph pull request #54215
Opened 2023-06-26 20:39 UTC by thenamankumar

- Update tooltips
 - Make embeddings status indicator updates realtime - poll every 5 seconds
 - Show the status of queued, in progress and failed embeddings jobs.

## Test plan
- open scope selector check and hover for embeddings status icons.

2023-06-26 21:04 UTC, chwarwick requested changes
I don't think that we can merge this with the changes to the admin only aspect of the jobs resolver.

2023-06-26 21:44 UTC, almeidapaulooliveira approved these changes

2023-06-26 22:00 UTC, slimsag commented on enterprise/cmd/frontend/internal/embeddings/resolvers/resolvers.go
> -	// 🚨 SECURITY: Only site admins may list repo embedding jobs.
For app itself I think it'd be OK to disable this, but yeah for enterprise deployments this absolutely must stay here - and best we avoid diverging between app and enterprise as much as possible

2023-06-27 01:54 UTC, thenamankumar commented on client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
> +const getEmbeddingStatus = ({
I discussed this with @rrhyne & @taylorsperry and they asked to show the latest embedding job's errors & status.

2023-06-27 02:04 UTC, rrhyne commented on client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
> +const getEmbeddingStatus = ({
Yep. We can’t assume no error exists in the current latest, and users should have confidence this set of embeddings has the latest code.

2023-06-27 02:36 UTC, chwarwick commented on client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
> +const getEmbeddingStatus = ({
I understand the sentiment of wanting to ensure that embeddings haven't started failing and can understand showing if the latest job failed.

For other states embeddings will continue to regenerate on a daily basis meaning once a day you'll start to see that the repo is now queued/ in progress, but any interactions with Cody will be using embeddings. 

Embeddings are only every "accurate" to a single commit and update daily.

2023-06-27 04:16 UTC, thenamankumar commented on enterprise/cmd/frontend/internal/embeddings/resolvers/resolvers.go
> -	// 🚨 SECURITY: Only site admins may list repo embedding jobs.
Put the check back in and handled the site admin case via conditionally requesting embeddingJobs from the client.

2023-06-27 04:21 UTC, thenamankumar commented on client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
> +const getEmbeddingStatus = ({
@chwarwick with the [indexing status banners and progress bar](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=3880-146970&mode=design&t=WmvedrIzAZ1EDobS-4) planned for the chat UI. Keeping the behaviour as it is right now makes sense. 

We may change it later if the design/product decides on that.

2023-06-27 11:55 UTC, chwarwick approved these changes
This looks good to me assuming the new status is only used for the tooltip/icons.  The previous embeddings exist check on the repository should be used to determine if the embeddings search is used for gathering context. 

In future updates I think we can provide more clarity in that the repo is already indexed (embedded) and these queued/processes/error events are related to updates to that status.

2023-06-27 13:21 UTC, chwarwick commented on client/web/src/cody/components/ScopeSelector/RepositoriesSelectorPopover.tsx
> +const getEmbeddingStatus = ({
@rrhyne  I've approved for now, but just want to reiterate that showing a repo as `Not Indexed` when an a job to bring embeddings up to date is queued or in progress, is not accurate.  The repository is still Indexed and will use embeddings when chatting with Cody.  It's just hasn't been updated.  The state is the same as it was 1 second before the job was queued, just as far out of date, but still has embeddings available.

There is probably less room for confusion with this on App since there are only a few repos and it should process the incremental updates quickly, but on dotcom and enterprise where there could be 100's or 1000's of repos that are getting queued for updates, I think it will lead to confusion as to why are my repos all showing as unindexed now?  

 I approved because for now this confusion will be limited only to Admins because all other users will see the repo as Indexed, which in my mind is the correct state.

2023-06-27 15:34 UTC, closed without merging