Cody: Add some recipes buttons to the welcome message
sourcegraph/sourcegraph pull request #54277
Opened 2023-06-27 11:45 UTC by dominiccooney

This adds three recipes to the welcome chat message in VScode to help users get started. Fixes issue #54232 .

![Screenshot 2023-06-27 at 20 41 51](https://github.com/sourcegraph/sourcegraph/assets/55120/2a87b960-4bf8-4184-8212-31f3bf0947d2)

## Test plan

Open Cody. A new chat now has buttons. Clicking the buttons starts those recipes.

2023-06-27 11:46 UTC, dominiccooney commented
For now these buttons are hard-coded, but it will be cool when Cody can generate actions and buttons to trigger them.

2023-06-27 18:29 UTC, abeatrix requested changes
I run into an issue where the recipe was giving me an error, and if i select a new section of code to run the recipe again it would should the highlighted code from my previous selection (see video from 0:00 to 0:10). Other than that everything works as expected!

https://github.com/sourcegraph/sourcegraph/assets/68532117/19fd59e3-2966-441b-8df6-c8649b037d7e



Pushed some spacing for the buttons (hope you don't mind 😁  ):
<img width="575" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/548c3b0f-cec9-4f18-b925-c6c9b63a54e0">

2023-06-28 00:40 UTC, dominiccooney commented
Thanks for the styling fixes and thanks for trying this out. Will take a look.

2023-06-28 06:42 UTC, toolmantim commented
Does "Fixup code from inline instructions" require you to do more than just select some code? If so, we're perhaps better off replacing it with "Generate a unit test"

2023-06-29 03:13 UTC, dominiccooney commented
@toolmantim Yep, fixup requires you to write in the file. Maybe it can come back when we have the input/quickpick for fixup instructions. For now I've replaced *Fixup ...* with *Generate unit test.*

@abeatrix please take another look! I can't reproduce that thing you're seeing where the selection is "one behind." Could you send me a log?

2023-06-29 07:32 UTC, abeatrix approved these changes
i cant reproduce the issue anymore, and the error message that was caused by https://github.com/sourcegraph/sourcegraph/pull/54319 is gone, so I suspect the original issue was also caused by the same PR which has now been reverted!

2023-06-29 12:33 UTC, merged