cody: add indexing state for cody app jobs
sourcegraph/sourcegraph pull request #54416
Opened 2023-06-29 05:08 UTC by abeatrix

Close https://github.com/sourcegraph/sourcegraph/issues/54227 https://github.com/sourcegraph/sourcegraph/issues/54230 https://github.com/sourcegraph/sourcegraph/issues/54229

This PR adds:
- New button to add repo into Cody App that will then be indexed automatically by App.
- Indexing progress bar for indexing codebase when connected to App
  - The progress bar will get render on every keystroke entered in the editor
- cleaned up the webmessage for `history` and grouped them together into one function `handleChatHistory`
- Cleaned up onConfigChange functions that caused publishConfig to get called multiple times

## Test plan

### Demos

Add repository to App. it takes App some time to add the repository  and index the repository respectively:
https://www.loom.com/share/80a3b069899e413bafa3396722b1091b
<img width="1229" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/59bb3962-151c-4085-bf40-17f951a61138">

Progress bar for indexing job (App only):
https://www.loom.com/share/909a1462dfda41cba583fc58d3c254e5?sid=f2c1fa46-706f-495a-ac10-5b27ec98fcea
<img width="1266" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/68532117/f5a56f0e-f7cd-437d-b482-9c1ee180a66c">

2023-06-29 05:44 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> +        const update = async (): Promise<void> => {
this is basically a clone of `updateCodebaseContext` minus some conditions that was blocking the codebaseContext to be updated correctly

2023-06-29 05:51 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -                await this.updateCodebaseContext()
this doesn't work because it'd fail in `this.updateCodebaseContext()` where only changes in workspace root path can pass.

2023-06-29 05:52 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -            vscode.workspace.onDidChangeWorkspaceFolders(async () => {
moved to `publishContextStatus()`

2023-06-29 05:52 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -            vscode.workspace.onDidChangeWorkspaceFolders(async () => {
moved to `publishContextStatus()`

2023-06-29 05:52 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -            case 'removeHistory':
grouped all of these to `handleChatHistory`

2023-06-29 05:55 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> +    // TODO: Move this into publishContextStatus.update()
moved logic to the `update()` in `publishContextStatus()`. This function gets called on every ConfigChange which does not work, because if the user is only changing their endpoint or assetToken, it would failed at `workspaceRoot === this.currentWorkspaceRoot` because the workspaceRoot would stay the same, so the new ContextStatus would not get published.

2023-06-29 06:01 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -        this.disposables.push(this.configurationChangeEvent.event(() => send()))
we don't need to `publishConfig()` on every config change because not all the config is related to webview config (eg enabling a feature should not required the webview to be updated). Move the call to syncAuthStatus instead because we only need to update the webview Config when auth config are updated.

2023-06-29 06:04 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -        this.disposables.push(this.configurationChangeEvent.event(() => send()))
this is also why the auth status gets updated repeatedly as making config changes to endpoint and token are counted as 2 changes, resulting in 2 publishConfig calls that also update the authStatus

2023-06-29 06:04 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -        this.disposables.push(this.configurationChangeEvent.event(() => send()))
this is also why the auth status gets updated repeatedly as making config changes to endpoint and token are counted as 2 changes, resulting in 2 publishConfig calls that also update the authStatus if I understand correctly

2023-06-29 06:05 UTC, abeatrix commented on client/cody/src/chat/ChatViewProvider.ts
> -            case 'removeHistory':
grouped all of these to `handleChatHistory`

2023-06-29 12:01 UTC, dominiccooney requested changes
Some feedback inline.

I don't grok this yet, but I am confident enough to make these suggestions for improvements.

2023-06-29 13:42 UTC, toolmantim commented on client/cody-ui/src/chat/inputContext/ChatInputContext.tsx
> +                <p className={styles.progressBarInner} style={{ width: `${completed}%` }} />
In theory, but I just tested this locally to check, and sadly [you can't animate](https://bugs.chromium.org/p/chromium/issues/detail?id=486195#c4) the internal elements using `@keyframes` on Chrome… only Safari.

```html
<html>
<style>
    :root {
        background-color: #333;
        padding-top: 100px;
    }
    body {
        display: flex;
        gap: 50px;
        flex-direction: column;
        align-items: center;
        justify-items: center;
    }
    progress {
        appearance: none;
        height: 3px;
    }
    progress::-webkit-progress-bar {
        appearance: none;
        background-color: #444;
        border-radius: 3px;
    }

    @keyframes background-scroll {
        to {
            background-position-x: -200%;
        }
    }
    /* TODO: Indeterminate */
    progress:not([value])::-webkit-progress-bar {
        background: linear-gradient(90deg, #444 0%, #5b5b5b 20%, #444 40%);
        animation: background-scroll 1.5s linear infinite;
        background-size: 200% 100%;
        border-radius: 3px;
    }

    /* Determinate */
    progress[value]::-webkit-progress-value {
        background: linear-gradient(90deg, #a112ff 0%, #ff5544 25%, #00cbec 50%, #ff5544 75%, #a112ff 100%);
        animation: background-scroll 3s linear infinite;
        background-size: 200% 100%;
        border-radius: 3px;
    }
</style>
<body>
<progress value="1" max="100">0%</progress>
<progress max="100">0%</progress>
<script>
    const progress = document.querySelector('progress[value]');
    setInterval(() => {
        progress.value = (progress.value + 1) % 100;
        progress.text = `${progress.value}%`;
    }, 100);
</script>
```

Safari:

https://github.com/sourcegraph/sourcegraph/assets/153/e532fcd6-5d9c-47f6-9958-5faf4267d209


Chrome:

https://github.com/sourcegraph/sourcegraph/assets/153/0f687edb-7c07-4bff-b67d-78f2d5ea7076

2023-06-29 13:49 UTC, toolmantim commented on client/cody-ui/src/chat/inputContext/ChatInputContext.tsx
> +                <p className={styles.progressBarInner} style={{ width: `${completed}%` }} />
Actually if you tweak the design a little, you can do it:


```html
<html>
<style>
    :root {
        background-color: #333;
        padding-top: 100px;
    }
    body {
        display: flex;
        gap: 50px;
        flex-direction: column;
        align-items: center;
        justify-items: center;
    }
    progress {
        appearance: none;
        height: 3px;
        background: linear-gradient(90deg, #444 0%, #5b5b5b 20%, #444 40%);
        animation: background-scroll 1.5s linear infinite;
        background-size: 200% 100%;
        border-radius: 3px;
    }
    progress::-webkit-progress-bar {
        appearance: none;
        background-color: transparent;
        border-radius: 3px;
    }
    @keyframes background-scroll {
        to {
            background-position-x: -200%;
        }
    }
    /* TODO: Indeterminate */
    progress:not([value]) {
        background: linear-gradient(90deg, #444 0%, #5b5b5b 20%, #444 40%);
        animation: background-scroll 1.5s linear infinite;
        background-size: 200% 100%;
        border-radius: 3px;
    }
    /* Determinate */
    progress[value]::-webkit-progress-value {
        background: linear-gradient(90deg, #a112ff 0%, #ff5544 25%, #00cbec 50%, #ff5544 75%, #a112ff 100%);
        background-size: 200% 100%;
        border-radius: 3px;
    }
</style>
<body>
<progress value="1" max="100">0%</progress>
<progress max="100">0%</progress>
<script>
    const progress = document.querySelector('progress[value]');
    setInterval(() => {
        progress.value = (progress.value + 1) % 100;
        progress.text = `${progress.value}%`;
    }, 100);
</script>
```

Chrome:

https://github.com/sourcegraph/sourcegraph/assets/153/1cf3b483-5322-4444-abc3-ed510ce7236e

2023-06-29 15:22 UTC, abeatrix commented on client/cody-shared/src/sourcegraph-api/graphql/client.ts
> +interface CodyAppGetLocalCodeHostsResponse {
This was shared with us by the App team and i don't think if we have a policy in place. From our [docs](https://docs.sourcegraph.com/dev/background-information/graphql_api#making-breaking-changes):
> Try to avoid making breaking changes, but if you have to, be sure to give clients time to migrate. This usually involves splitting the change into 2 parts. For example, if you want to rename a field in the return type of a query:
> Add a new field with a different name, deprecate the old field, and communicate the deprecation in the changelog
Give clients time to migrate (2 release cycles is a common guideline), remove the old deprecated field, and communicate the removal in the changelog

2023-06-30 02:56 UTC, toolmantim commented on client/cody/src/chat/ChatViewProvider.ts
> +        // send new context status on every change in doc to display selected line number and indexing progress if any
It makes me sad when software requires poking by a user to refresh its UI :(

Even updating every 3 seconds would be okay though!

In the past it used to be a pain to clear/manage intervals, but React made it relatively for me using `useEffect` — unless we're under different constraints?

2023-06-30 09:52 UTC, fkling commented on client/cody-shared/src/sourcegraph-api/graphql/client.ts
> +        }).then(response => extractDataOrError(response, data => data.addExternalService))
This is the old way of adding local repositories. We now have a new GraphQL mutation that only accepts the path (and in the backend creates a service config for a different type). See https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@e2580a4c1953708c163df0266abc76d98ad548db/-/blob/client/web/src/setup-wizard/components/local-repositories-step/hooks.ts?L42-56

2023-06-30 18:28 UTC, vovakulikov commented on client/cody-ui/src/chat/inputContext/ChatInputContext.tsx
> +                <p className={styles.progressBarInner} style={{ width: `${completed}%` }} />
I think in Firefox, we still have a problem with styles over the progress bar value. My take here is that the custom progress bar doesn't require a lot of aria attributes, so we can do our version without big problems in implementation. I will take a look. It's worth doing this because we use the same UI in the setup flow (currently without animation), so having it in our wildcard makes sense.

2023-06-30 20:08 UTC, vovakulikov commented on client/cody-ui/src/chat/inputContext/ChatInputContext.tsx
> +                <p className={styles.progressBarInner} style={{ width: `${completed}%` }} />
Here is my PR for the progress component @toolmantim I hope you can help me there with colors for different themes 

https://github.com/sourcegraph/sourcegraph/pull/54504

2023-07-10 11:48 UTC, sqs commented
<kbd>*semi-automated message*</kbd> Cody's source code has moved to a new repository, https://github.com/sourcegraph/cody.

I've migrated this branch for you: https://github.com/sourcegraph/cody/compare/bee/cody-index-progress?expand=1. If you still intend to merge this change, please reopen your PR on that new repository.

<details>

<summary>Script that I used to migrate that branch</summary>

``` shell
#!/bin/bash

# run like `move-branch.sh branch-name` within a separate clone of sourcegraph/sourcegraph

set -eux

BRANCH=$1

git fetch origin refs/heads/$BRANCH:refs/remotes/origin/$BRANCH
git filter-repo \
	--force \
	--refs refs/remotes/origin/$BRANCH \
	--path client/cody \
	--path 'client/cody-icons-font' \
	--path 'client/cody-shared' \
	--path 'client/cody-ui' \
	--path 'client/cody-web' \
	--path 'client/cody-agent' \
	--path 'client/cody-slack' \
	--path 'client/cody-cli' \
	--path-rename client/: \
	--path-rename cody/:vscode/ \
	--path-rename cody-web/:web/ \
	--path-rename cody-agent/:agent/ \
	--path-rename cody-slack/:slack/ \
	--path-rename cody-cli/:cli/ \
	--path-rename cody-icons-font/:lib/icons/ \
	--path-rename cody-shared/:lib/shared/ \
	--path-rename cody-ui/:lib/ui/ \
	--message-callback 'import re;return re.sub(br"(?<!\[)#(\d{4,5})", br"https://github.com/sourcegraph/sourcegraph/pull/\1", message)'

git filter-repo --invert-paths --use-base-name --path-glob '*.bazel' --path 'CODENOTIFY'

git push https://github.com/sourcegraph/cody refs/heads/$BRANCH:$BRANCH
```

</details>

In case it's helpful, here are some of the path mappings from the old repository (https://github.com/sourcegraph/sourcegraph) to the new repository (https://github.com/sourcegraph/cody):

- `client/cody/ -> vscode/`
- `client/cody-shared/ -> lib/shared/`
- `client/cody-ui/ -> lib/ui/`

Thank you for the PR, and sorry for the inconvenience!

2023-07-10 11:48 UTC, closed without merging