GitHub App worker: Sync Apps
sourcegraph/sourcegraph pull request #54455
Opened 2023-06-29 20:56 UTC by st0nebraker

Closes #54066 - Deletes GitHub Apps when they don't exist

## Test plan

2023-07-12 04:52 UTC, BolajiOlajide requested changes

2023-07-12 04:52 UTC, BolajiOlajide commented on internal/github_apps/store/store.go
> +}
Can you add a test case for this?

2023-07-12 04:52 UTC, BolajiOlajide commented on internal/extsvc/github/v3.go
> +}
Can you return a GitHub app instead of a boolean? Returning an instance of a GitHub App aligns with the name of this method which implies it's fetching an instance of an App.

I think it should be available in the `go-github` library as `*github.App`.

If the GitHub App doesn't exist, I believe it'll default to `nil` in that case, so you can update the callers of this method to simply check if `returnedApp == nil` to check if the app exists.

2023-07-19 02:00 UTC, courier-new commented
Hmm sorry we didn't get a chance to align about this before all your work on this PR, but having given this a bit of thought, I'm not sure this is actually desirable behavior anymore. Bear with me a moment.

I'm wondering how much deleting the App actually helps the end users. If we keep it around, we won't try to use it to sign any commits because we won't find any matching installations for the repos. So it just... won't do anything, right? Maybe it will throw a couple warnings during the worker sync?

I just want us to be careful not to overeagerly delete Apps on the Sourcegraph side just because we couldn't find them on GitHub. Like, we should _only_ delete them if the `GET` request returns a 404, and maybe we even issue a second request just to be _extra sure_, but we should certainly keep them for any other status code. Otherwise if GitHub's servers blip out or there's a temporary network connectivity problem, oops we accidentally deleted all the GH Apps on Sourcegraph! 😅

It just strikes me that if an App got deleted on GitHub, it's either:
a) intentional, and the user doesn't care about using it for Batch Changes anymore, or
b) accidental and likely to go unnoticed, and what we're doing makes it _even harder_ to troubleshoot.

Like imagine I accidentally deleted an App we were using in the SG org and you don't see me do it. What you _do_ see is that when you go to publish some batch change, the commits aren't signed anymore. What gives, Sourcegraph? Clearly it's a bug with Batch Changes. You go to settings to investigate and lo and behold, the App doesn't show up under commit signing anymore. Well that's clearly the problem! Why did the app disappear from Sourcegraph? Grumble grumble time to go contact your admin to add a new one because you don't have permission by yourself. And _maybe_ then your admin realizes that the App got deleted on the GitHub side. But us deleting the App on SG didn't _really_ do anything to help the user, it just cleaned up an unused App in the DB. Whereas if we had just kept the deleted App around, the second a user tried to go look up that App on GitHub, it'd be obvious what the problem is.

Maybe the better user experience is that rather than deleting an App if we got a 404, we record that it looks deleted, and surface that from the admin UI?

2023-07-20 20:59 UTC, st0nebraker commented
To me, this would follow the same concept as the worker removing installations in place, follow CRUD and clean up the DB.

> Maybe the better user experience is that rather than deleting an App if we got a 404, we record that it looks deleted, and surface that as a warning from the admin UI?

I like this, it's very explicit. Unfortunately, I don't think it'll be able to get done soon with our current priorities ☹️  I'll log it to the issue though for posterity. Thanks for your perspective @courier-new 🙏🏻

2023-08-15 19:40 UTC, closed without merging