[SG-54465] : Simplify post signup flow SG-54465
sourcegraph/sourcegraph pull request #54653
Opened 2023-07-06 06:30 UTC by gitstart-sourcegraph

## Description
Before allowing users who have signed up to access the system, they need complete additional steps:

Verify their email
Indicate how they will use Cody (which causes lead generation to occur)
Currently, users who have just signed up are taken to the search homepage and we open a modal
over the page while blocking other content. We also first cookie the users when they are coming
from the about site to know they are new signups.   

These screens are not extendable and the code to determine this flow is a bit brittle, especially since it now requires cookies.

Solution:
We need to reduce the need for cookies and other measures of determining how to show these steps, and simply
redirect all signups to sourcegraph.com (but not a server installation) from any type of signup (email or OAuth)
to dedicated ‘setup’ pages that do not require altering the main layout.

Repurpose the existing interactions (do not block on verify, block on form submission)
  
[Figma](https://www.figma.com/file/DIk3eGdgKszigQVec7Y8SD/Frictionless-Cody?type=design&node-id=1617-37199&mode=design)

## Refs
[Sourcegraph issue](https://developers.gitstart.com/client/sourcegraph/ticket/SG-54465)
[Gitstart Ticket](https://clients.gitstart.com/sourcegraph/1/tickets/SGM-54465)

2023-07-07 06:16 UTC, mrnugget commented
In the test plan you mention

> Run the sourcegraph app

But I assume you mean `sg start dotcom`, no?

2023-07-07 06:28 UTC, sashaostrikov reviewed
Left a couple of comments, LGTM apart from that, but I'd defer to someone with more Cody flows knowledge to approve.

2023-07-07 06:28 UTC, sashaostrikov commented on client/web/src/LegacyLayout.tsx
> +    // Redirect to post-sign-up page if email is not verified and lead form is not submitted
Couple of comments here:
1) Let's also add a part that it happens only on dotcom.
2) "if email is not verified **and** lead form is not submitted", but the code says "OR". Which one is correct?

2023-07-07 06:28 UTC, sashaostrikov commented on client/web/src/auth/PostSignUpPage.tsx
> +export const PostSignUpPage: React.FunctionComponent<PostSignUpPageProps> = ({ authenticatedUser }) => (
It would be nice to have a screenshot of this page in PR description :)

2023-07-07 06:31 UTC, mrnugget commented
I try to test it, but `post-sign-up` doesn't work and it looks like there's recursion going on that kills the tab for me:

https://github.com/sourcegraph/sourcegraph/assets/1185253/15fa36f4-08c2-4cf7-9cf1-e787541ee52c

2023-07-07 06:50 UTC, gitstart-sourcegraph commented on client/web/src/auth/PostSignUpPage.tsx
> +export const PostSignUpPage: React.FunctionComponent<PostSignUpPageProps> = ({ authenticatedUser }) => (
Thanks, added now.
We have also added a storybook, [available here](https://5f0f381c0e50750022dc6bf7-bzzanqbsuu.chromatic.com/?path=/story/web-src-auth-postsignuppage--post-sign-up)

2023-07-07 06:51 UTC, gitstart-sourcegraph commented on client/web/src/LegacyLayout.tsx
> +    // Redirect to post-sign-up page if email is not verified and lead form is not submitted
Thanks, OR is correct. Would update comment.

2023-07-07 06:57 UTC, mrnugget requested changes
Requesting changes because there's 2 hard blockers:

1. Recursion kills the page for me, it doesn't work.
2. The page shows up post *sign-in*, or basically one very page load. I think the original intention is to show it only post *sign-up*, i.e. after a new account is created.

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/LegacyLayout.tsx
> +        props.isSourcegraphDotCom &&
I'm pretty sure it needs this to fix the recursion.

```suggestion
    if (
        !isPostSignUpPage &&
        props.isSourcegraphDotCom &&
```

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/auth/PostSignUpPage.tsx
> +                src="https://sourcegraph.com/.assets/img/sourcegraph-mark.svg?v2"
Should this be an absolute URL? Looks like we usually use relative URLs: https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+sourcegraph-mark.svg+lang:typescript&patternType=standard&sm=0&groupBy=repo

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/auth/PostSignUpPage.tsx
> +            )}
Why do we need to check for `authenticatedUser` here again? Shouldn't we redirect the user here instead of showing them an empty page?

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +        // we calculate "hasSubmittedSurvey" value based on whether they already have submitted survey
I think the comment has outlived its usefulness.

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +    const redirectToGetCody = (): void => window.location.replace(PageRoutes.GetCody)
Why not use the `<Navigate />` component here? This messes with window history.

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +        return null
Shouldn't the redirect go in here?

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
> +            {!isSiteInit && !isSignInOrUp && !isGetCodyPage && !isPostSignUpPage && (
Do we need this on this page? Why?

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/auth/PostSignUpPage.tsx
> +        <Page className={styles.page}>
Shouldn't this page also have a `<title>`? Right now it only says `Admin - Sourcegraph` for me.

2023-07-07 06:57 UTC, mrnugget commented on client/web/src/LegacyLayout.tsx
> +        (!props.authenticatedUser.hasVerifiedEmail || !hasSubmittedCodySurvey)
Where is the check that this page only shows up post *sign-up*? Right now it also shows up post *sign-in*, meaning: every user that signs-in will be redirect to this.

2023-07-07 07:32 UTC, gitstart-sourcegraph commented on client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
> +            {!isSiteInit && !isSignInOrUp && !isGetCodyPage && !isPostSignUpPage && (
This ensures that the global navbar, stays hidden on /post-sign-up page.

2023-07-07 07:41 UTC, gitstart-sourcegraph commented on client/web/src/LegacyLayout.tsx
> +        (!props.authenticatedUser.hasVerifiedEmail || !hasSubmittedCodySurvey)
Based on the conversation with Rob, [Ref here](https://gitstart.slack.com/archives/C04QFRW7XG8/p1688479528727089?thread_ts=1688331794.645069&cid=C04QFRW7XG8),

> The idea is that the user must complete these post-signup items before using the product.

We deduced from it, that the users should be routed to `/post-sign-up` page irrespective of the page the were on, to fulfil this part `must complete these post-signup items before using the product`. Perhaps this is a wrong deduction, kindly help confirm?

2023-07-07 08:26 UTC, mrnugget commented on client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
> +            {!isSiteInit && !isSignInOrUp && !isGetCodyPage && !isPostSignUpPage && (
Yes, but you're also doing that on the other layout, right? This here is in `client/web/src/storm` -- is that used?

2023-07-07 10:07 UTC, gitstart-sourcegraph commented on client/web/src/storm/pages/LayoutPage/LayoutPage.tsx
> +            {!isSiteInit && !isSignInOrUp && !isGetCodyPage && !isPostSignUpPage && (
Thanks's right.

2023-07-07 16:18 UTC, gitstart-sourcegraph commented on client/web/src/LegacyLayout.tsx
> +        (!props.authenticatedUser.hasVerifiedEmail || !hasSubmittedCodySurvey)
Thank you, @mrnugget, for the clarification. I agree that this page should only be shown to new users who have just created an account.

Moreover, I came across a comment by @erzhtor [here](https://github.com/sourcegraph/sourcegraph/issues/54465#issuecomment-1614302980) which raises some interesting points about the usefulness of having a universal redirect like the one we're discussing. It would address situations such as signups through the sign-in page or when users close the post-sign-up page before completing the mandatory steps.
With the new property `.completedPostSignup` you have supported, we can now simplify this condition for universal redirect. WDYT?

2023-07-10 13:03 UTC, rrhyne commented on client/web/src/LegacyLayout.tsx
> +        (!props.authenticatedUser.hasVerifiedEmail || !hasSubmittedCodySurvey)
@mrnugget thanks for reviewing. I believe we do want to cause users to complete post-signup actions before logging in. 

Not all returning users have validate their email, so having folks from 1 year ago return and see this screen is desired. 

Also consider the following:

* User signs up
* User verifies email
* User closes browser window
* User later clicks link that redirects them to a product page after signing in
* User can use the product without signifying their intention (work or personal form)

In another interesting scenario, I imagine those actions could change... (we might not always have the for work or personal use form), so the system should probably flexibly support post-signup-completed. For example:

Imagine we have new terms all users need to agree to. We could then show a new post signnup flow to everyone logging in again. 

For those reasons, I think we want to show this for any user who has not completed the steps, regardless of where they are in the flow.

2023-07-10 13:06 UTC, rrhyne commented on client/web/src/LegacyLayout.tsx
> +    // Redirect to post-sign-up page if email is not verified and lead form is not submitted
@sashaostrikov  is correct, this should only happen on dotcom. @gitstart-sourcegraph  can you implement that change and test other releases carefully to make sure this doesn't appear in server enterprise versions?

2023-07-10 13:07 UTC, rrhyne commented
> 2. The page shows up post _sign-in_, or basically one very page load. I think the original intention is to show it only post _sign-up_, i.e. after a new account is created.

Actually, I think this should appear for dot com users until conditions are met: https://github.com/sourcegraph/sourcegraph/pull/54653#discussion_r1258229886

2023-07-10 14:54 UTC, mrnugget commented on client/web/src/LegacyLayout.tsx
> +        (!props.authenticatedUser.hasVerifiedEmail || !hasSubmittedCodySurvey)
Okay, got it, so we can essentially drop the "post signup" when it comes to technical requirements. Instead we can say: every user on dotcom needs to complete these steps.

2023-07-11 11:16 UTC, mrnugget reviewed
Left some comments, but haven't tried it locally yet. @sourcegraph/source I need you also to review

2023-07-11 11:16 UTC, mrnugget commented on client/web/src/auth/SignUpPage.tsx
> -            window.location.replace(returnTo)
Can we simply remove `returnTo`? Is this only used on dotcom?

Why not replace it on line 63?

2023-07-11 11:16 UTC, mrnugget commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +    mutation setCompletedPostSignup($userID: ID!) {
```suggestion
    mutation SetCompletedPostSignup($userID: ID!) {
```

2023-07-11 11:25 UTC, mrnugget commented
It doesn't work for me:

https://github.com/sourcegraph/sourcegraph/assets/1185253/9037e5ae-ddc7-409a-ad3f-fcd8c1e031b2

2023-07-11 11:58 UTC, mrnugget commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +                updatePostSignupCompletion().then(onSubmitEnd).catch(console.error)
So if `submitCodySurvey` fails here, you still want to `updatePostSignupCompletion`? That seems wrong, no?

2023-07-11 12:12 UTC, pjlast requested changes

2023-07-11 12:12 UTC, pjlast commented on client/web/src/jscontext.ts
> +    | 'completedPostSignup'
This needs a corresponding entry in `cmd/frontend/internal/app/jscontext/jscontext.go` , in the `CurrentUser` struct. The `createCurrentUser` function will have to be updated to use the `UserResolver` to fetch this field from the DB. Otherwise it will always be false, which is why the flow is not working for @mrnugget

2023-07-11 12:22 UTC, mrnugget commented on client/web/src/LegacyLayout.tsx
> +    if (
@rrhyne I don't think we should have this redirect for admins. It's _really_ confusing to setup a new instance and get redirected to this page immediately after creating an admin account.

2023-07-11 12:22 UTC, mrnugget commented on client/web/src/jscontext.ts
> +    | 'completedPostSignup'
Yeah, here's what you need to do, @gitstart-sourcegraph:

```diff
diff --git a/cmd/frontend/internal/app/jscontext/jscontext.go b/cmd/frontend/internal/app/jscontext/jscontext.go
index a1e34f5536..875cabe839 100644
--- a/cmd/frontend/internal/app/jscontext/jscontext.go
+++ b/cmd/frontend/internal/app/jscontext/jscontext.go
@@ -107,6 +107,7 @@ type CurrentUser struct {
 	TosAccepted         bool       `json:"tosAccepted"`
 	Searchable          bool       `json:"searchable"`
 	HasVerifiedEmail    bool       `json:"hasVerifiedEmail"`
+	CompletedPostSignUp bool       `json:"completedPostSignup"`
 
 	Organizations  *UserOrganizationsConnection `json:"organizations"`
 	Session        *UserSession                 `json:"session"`
@@ -435,6 +436,11 @@ func createCurrentUser(ctx context.Context, user *types.User, db database.DB) *C
 		return nil
 	}
 
+	completedPostSignup, err := userResolver.CompletedPostSignup(ctx)
+	if err != nil {
+		return nil
+	}
+
 	return &CurrentUser{
 		GraphQLTypename:     "User",
 		AvatarURL:           userResolver.AvatarURL(),
@@ -454,6 +460,7 @@ func createCurrentUser(ctx context.Context, user *types.User, db database.DB) *C
 		ViewerCanAdminister: canAdminister,
 		Permissions:         resolveUserPermissions(ctx, userResolver),
 		HasVerifiedEmail:    hasVerifiedEmail,
+		CompletedPostSignUp: completedPostSignup,
 	}
 }

```

See also this comment: https://github.com/sourcegraph/sourcegraph/blob/a027f461119acb1839bb7e79a4bf48bcc9cc3cc2/client/shared/src/auth.ts#L5-L8

2023-07-11 12:31 UTC, gitstart-sourcegraph commented on client/web/src/jscontext.ts
> +    | 'completedPostSignup'
Thanks @pjlast @mrnugget,
Would update the files shorty.

2023-07-11 12:39 UTC, kopancek reviewed
Instead of adding another field `completedPostSignup` to the authenticatedUser object, I think we can detect if the current user has a verified email and has completed the cody survey. That way we do not even need the final mutation `SetCompletedPostSignup` on form submit and it should make the code easier to read and understand.

We also need a DB migration that will handle all the existing users - we do not want them to fill in the form or be redirected to post sign up.

2023-07-11 12:39 UTC, kopancek commented on client/web/src/auth/PostSignUpPage.module.scss
> +        max-width: 1360px;
Where does this number come from? Seems arbitrary...

2023-07-11 12:39 UTC, kopancek commented on client/web/src/auth/PostSignUpPage.story.tsx
> +)
I would love it if we could also add another story for `hasVerifiedEmail: true` and `completedPostSignup: true`

2023-07-11 12:39 UTC, kopancek commented on client/web/src/auth/SignUpPage.tsx
> +            window.location.replace(PageRoutes.PostSignUp)
Doing a redirect this way loses the returnTo parameter. Can we add the query parameter from the URL to the post sign up path?

Should we only do a redirect to post sign up flow on special instances? E.g. on dotcom? (It does not make sense for our self-hosted customers to be redirected to the post sign up flow as far as I understand).

2023-07-11 12:39 UTC, kopancek commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +    const [submitCodySurvey] = useMutation<SubmitCodySurveyResult, SubmitCodySurveyVariables>(SUBMIT_CODY_SURVEY, {
What about loading and error states of the mutation? Should we add handling for those?

2023-07-11 12:39 UTC, kopancek commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +    const [updatePostSignupCompletion, { loading }] = useMutation<
Same as above, what if this fails? Should we show an error message?

2023-07-11 12:39 UTC, kopancek commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +        setCompletedPostSignup(userID: $userID) {
Where is this mutation implemented? I do not see it as part of this PR...

2023-07-11 12:41 UTC, gitstart-sourcegraph commented on client/web/src/auth/SignUpPage.tsx
> -            window.location.replace(returnTo)
Line 63, currently redirects when the component mounts.
In this context, we would need to redirect only after a successful signup.

> Is this only used on dotcom

I think this is right, would update the logic to only return to `post-sign-up` on successful signup on dotcom.

2023-07-11 13:24 UTC, gitstart-sourcegraph commented on client/web/src/auth/SignUpPage.tsx
> +            window.location.replace(PageRoutes.PostSignUp)
Agreed, would update this to only redirect to post-sign-up on dotcom. Thanks.

2023-07-11 13:36 UTC, gitstart-sourcegraph commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +    const [updatePostSignupCompletion, { loading }] = useMutation<
I think we should.
Double checking with @rrhyne to confirm how the error state would be rendered on UI.

2023-07-12 08:41 UTC, mrnugget commented
> Instead of adding another field `completedPostSignup` to the authenticatedUser object, I think we can detect if the current user has a verified email and has completed the cody survey. That way we do not even need the final mutation `SetCompletedPostSignup` on form submit and it should make the code easier to read and understand.

Just for the record here: we specifically decided on having this mutation, because we want to keep persistent state and we don't know whether someone has completed the cody survey.

2023-07-12 13:57 UTC, rrhyne commented
One additional thing we need to make sure happens:

We should pre-populate any new fields / checks to ensure we do not show the screens to users who have already completed them. 

I don't know the code, but if that's difficult to do due to use of local storage or cookies and such, it would be ok with me if we assume existing users have already met the requirements and repopulate any database fields accordingly. 

cc @mrnugget and @erzhtor

2023-07-13 07:18 UTC, mrnugget commented on client/web/src/LegacyLayout.tsx
> +    if (
> Actually, I'm not sure I agree... we should be verifying admin emails if we require this for all users.

Yeah, but that's not what this page does, right?

Agree on "scoped to dotcom" though.

2023-07-13 09:14 UTC, pjlast reviewed
Some code cleanup comments

2023-07-13 09:14 UTC, pjlast commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +    const [submitCodySurvey] = useMutation<SubmitCodySurveyResult, SubmitCodySurveyVariables>(SUBMIT_CODY_SURVEY, {
You can simplify the whole loading and error state handling here:

```suggestion
    const [submitCodySurvey, { loading, error }] = useMutation<SubmitCodySurveyResult, SubmitCodySurveyVariables>(SUBMIT_CODY_SURVEY, {
```

`useMutation` can return states like that.

Then you only need to use those states, you don't need to do the whole `setLoading` and `setShowError` dance

2023-07-13 09:14 UTC, pjlast commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +                setLoading(false)
So thesse `setLoading` and `setShowError` statements can fall away

2023-07-13 09:14 UTC, pjlast commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +                )}
And here you can just check for `error` instead of `showError`

2023-07-13 10:54 UTC, gitstart-sourcegraph commented on client/web/src/marketing/toast/CodySurveyToast.tsx
> +    const [submitCodySurvey] = useMutation<SubmitCodySurveyResult, SubmitCodySurveyVariables>(SUBMIT_CODY_SURVEY, {
Thanks @pjlast,
We initially opted for this approach, since we needed to monitor the loading/error states of `submitCodySurvey` and `updatePostSignupCompletion` mutations.

WDYT about the new update, where we use the loading/error state from both cases and didn't define a new state too.

```javascript
const [updatePostSignupCompletion, { loading: loadingPostSignup, error: setPostSignupError }] ...
const [submitCodySurvey, { loading: loadingCodySurvey, error: submitSurveyError }] ...

const loading = loadingCodySurvey || loadingPostSignup
const error = !!submitSurveyError || !!setPostSignupError
```

2023-07-13 11:12 UTC, pjlast approved these changes

2023-07-17 14:05 UTC, rrhyne commented on client/web/src/LegacyLayout.tsx
> +    if (
Ok, let's just keep this all scoped to dotcom and not worry about the admin to keep things simple.

2023-07-17 16:52 UTC, gitstart-sourcegraph commented on client/web/src/LegacyLayout.tsx
> +    // Redirect to post-sign-up page if email is not verified and lead form is not submitted
Thanks @rrhyne ,
This is handled now.

2023-07-18 09:03 UTC, mrnugget approved these changes
Approving since all the others comments seem to be addressed.

One last question: have you tested this manually with `sg start dotcom`?

2023-07-18 12:19 UTC, gitstart-sourcegraph commented
Hi @mrnugget,

We've been able to test the current changes locally using `sg start dotcom`.

2023-07-19 07:07 UTC, mrnugget commented
Any concerns left, @sourcegraph/source? Or can we merge?

2023-07-19 10:20 UTC, BolajiOlajide approved these changes
LGTM

2023-07-20 15:44 UTC, rrhyne commented
I just tested and saw only one issue:

 A new admin on .com saw /get-cody and was asked to complete the cody usage form. They should not have. Can we create a separate issue to fix that and merge as is?  
 
 Admins and users on enterprise instances were not presented with these pages or /get-cody so I thnk this is ready to go.

2023-07-20 15:45 UTC, rrhyne approved these changes
Tested and seems to work as expected.

2023-07-20 16:36 UTC, mrnugget approved these changes

2023-07-20 17:48 UTC, merged