Added the export changeset button and its download logic for all chan…
sourcegraph/sourcegraph pull request #54795
Opened 2023-07-11 16:30 UTC by mibali

This PR  is created to add an Export button to enable users to download specific changeset info for all or selected changesets in a batch change.

This is what the changeset page currently looks like:
![image](https://github.com/sourcegraph/sourcegraph/assets/111276665/335c2ba6-2d9c-4f78-87fa-d2f13cc8cd78)

Here's what it looks like with the added export button
![image](https://github.com/sourcegraph/sourcegraph/assets/111276665/c965540c-4cce-4b7f-8ab6-2ed513e150ee)

The csv file, when you download for all changesets
![image](https://github.com/sourcegraph/sourcegraph/assets/111276665/790d2d75-f739-454d-b32b-d41783da4762)

When you select changesets, there is now an export button next to `Select Action`
![image](https://github.com/sourcegraph/sourcegraph/assets/111276665/65676132-6ea9-4a7d-92b2-5d3ddc27af34)

What the csv file now looks like
![image](https://github.com/sourcegraph/sourcegraph/assets/111276665/bd161bf3-0683-4552-98af-5846fa784021)

This feature request some of our customers have requested for in the past, now most recently
- [Grab](https://sourcegraph.slack.com/archives/C04K6E9QGH0/p1686127655773899)
- [Checkr ](https://sourcegraph.slack.com/archives/C03U5QATUH2/p1687802867394979)

## Test plan

2023-07-13 10:34 UTC, eseliger requested changes
Thank you for working on this and congrats on your first(?) frontend contribution to SG! 

A few general notes on PRs:

- Commit descriptions and PR titles should use imperative form, [see here](https://docs.sourcegraph.com/dev/background-information/commit_messages)
- Please no customer name mentions in the public repo, you can use https://github.com/sourcegraph/accounts to refer to them in a private way
- Pull request descriptions require a [Test Plan](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans) to be mergable, please provide one in the PR description (the link contains more information)
- To keep PR reviews lightweight and fast for reviewers, please ideally start with a Draft PR, make sure the PR meets the above criteria, and that Buildkite CI passes [https://buildkite.com/sourcegraph/sourcegraph/builds/233806](Link to failing build)
  - This will require less comments around "this needs to be formatted differently
  - These checks are there to help build a clean PR, with ideally little feedback required
  - For now, I've left a few of these comments, but CI will also tell you about more cases

---

That's for PRs in general, for this feature, I have one suggestion (and cc @danielmarquespt maybe you have some thoughts as well):
The persistent "Export" button clutters the UI with a button that is not actually useful until something is selected.
When selected, the filter bar disappears and is replaced by an action selector dropdown (and now the export button). This action bar also supports selecting changesets beyond the length of the currently displayed page, which will be useful for export too. So here's my proposal: 
Instead of the export feature being a separate button, how would you feel about adding it as another action in the dropdown menu, both decluttering the action and filter bars, and also providing the export all feature by using the same "select all" mechanism that all other changeset actions support?

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/MultiSelectContext.tsx
Revert formatting in this file

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/batch-spec/execute/ActionsMenu.tsx
Revert formatting in this file

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/detail/backend.ts
Revert formatting in this file

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
> +import { node } from 'src/site-admin/SiteAdminPackagesPage.module.scss'
we usually import those as `import styles from X` and then access these fields as `style.node`: https://sourcegraph.sourcegraph.com/search?q=context:global+import+styles+from+r:%5Egithub%5C.com/sourcegraph/sourcegraph%24+&patternType=standard&sm=1&groupBy=repo

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
> +// const [selectedChangesets, setSelectedChangesets] = useState();
Commented out code should be removed to keep the source clean

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
> +
only 1 consecutive newline should be used

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
> +    selectedChangesets: any[]
`any` types should not be used whenever possible, what is `selectedChangesets`s actual type? 
Otherwise, we might be erroneously pass wrong data to the prop in the future.

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/detail/changesets/ChangesetSelectRow.tsx
> +import React, { useMemo, useContext, useState, useEffect } from 'react'
Looks like these imports are unused

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/detail/changesets/BatchChangeChangesets.tsx
> +            // return items.id === selected})
Remove commented out code please

2023-07-13 10:34 UTC, eseliger commented on client/web/src/enterprise/batches/DropdownButton.tsx
Looks like a lot of formatting changes in this file, cluttering the diff. Please run prettier against this file which will remove the newly added semi colons and so forth

2023-07-18 07:44 UTC, mibali commented
@eseliger Thanks for this insightful feedback!
I would incorporate these changes ASAP.
Just to clarify here, you mean the `Export Button" should be among the actions in the `Select Action` Dropdown right?

2023-07-18 16:34 UTC, eseliger commented
> Just to clarify here, you mean the Export Button" should be among the actions in the Select Action` Dropdown right?


Yes, I think that would declutter the UI. We can also ask @danielmarquespt what he thinks

2023-07-18 20:50 UTC, mibali commented
HI @eseliger 

I spent some time trying to add the export changes under the `select action` but I discovered that the actions under select action are returned from a query to the graphql server. 

I noticed The reason why some of the actions are not clickable is because they are not returned as an available action from the available bulk operation.

Please would you be able to guide me on how I can make the export changeset action to be added to the available bulk operation from the backend?

Or would it be much more straightforward to remove the export button in the changeset UI and leave the changeset button beside the select action?

2023-07-19 11:07 UTC, BolajiOlajide commented
> HI @eseliger
> 
> I spent some time trying to add the export changes under the `select action` but I discovered that the actions under select action are returned from a query to the graphql server.
> 
> I noticed The reason why some of the actions are not clickable is because they are not returned as an available action from the available bulk operation.
> 
> Please would you be able to guide me on how I can make the export changeset action to be added to the available bulk operation from the backend?
> 
> Or would it be much more straightforward to remove the export button in the changeset UI and leave the changeset button beside the select action?

Hey @mibali ,

Here's the [PR](https://github.com/sourcegraph/sourcegraph/pull/33054) that moves the bulk operations to the GraphQL API - I would suggest you take a look at it to understand how it works.

Here's the [file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/batches/service/service.go?L1680%3A1-1768%3A2) that contains all the operations that'll be surfaced on the frontend. Since the `Export` action will be available to all changeset, you'll need to increment it for every changeset in that loop that we use to update the counter.

2023-08-15 01:06 UTC, mibali commented
I have made the changes in this new PR : https://github.com/sourcegraph/sourcegraph/pull/55850

2023-08-30 11:53 UTC, closed without merging