Use Buildkite to run Sonarcloud
sourcegraph/sourcegraph pull request #54875
Opened 2023-07-12 17:42 UTC by willdollman

## Test plan

2023-07-12 18:06 UTC, mohammadualam approved these changes

2023-07-17 08:21 UTC, jhchabran requested changes
Looking at the build associated to this PR, it didn't run. Once you get it to run in CI and be green, we can take over :) 

As for the errors seen in there, I think a rebase will fix it.

2023-07-17 08:21 UTC, jhchabran commented on dev/ci/sonarcloud-scan.sh
> +export SONAR_SCANNER_OPTS="-server"
I'd much prefer this to be declared at the pipeline level, especially since we can't run this script as is, because of the hardcoded paths.

2023-07-17 08:21 UTC, jhchabran commented on dev/ci/sonarcloud-scan.sh
> +cd /buildkite-git-references/sourcegraph.reference
This is incorrect, that's not the place where the code lives. This should be the build folder and you shouldn't need to `cd` in there, because Buildkite puts you there by default.

2023-07-17 08:21 UTC, jhchabran commented on dev/ci/sonarcloud-scan.sh
> +curl --create-dirs -sSLo /buildkite/sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
Should use a tmpdir instead. Also, it's missing the `failfast` flag on the Curl command.

2023-07-19 07:59 UTC, jhchabran reviewed
@willdollman @shivasurya all good, it's working now 👍 

I'll reach you out on Slack, I'm a bit concerned about the duration of the scan, 12m is pretty long, but perhaps there's a way to make it better.

2023-07-19 20:18 UTC, shivasurya commented
Thanks @jhchabran 👍🏻  I'll verify that soon!

2023-07-21 16:03 UTC, jhchabran approved these changes

2023-07-21 16:16 UTC, merged