bazel: monitoring docs gen
sourcegraph/sourcegraph pull request #54965
Opened 2023-07-14 16:11 UTC by burmudar

### Changes
improve `write_generated_to_source_files` to:
- allow prefixes to be stripped from generated files
- specify a different destination
- handle being called from a different package than being next to the src target

This seemed like an easy change on the outset but it turned out to be quite involved. Some of the problems I encountered while doing this which required the above changes:

* monitoring-generator copies to a total different path in the repo route than what it normally outputs - ie. docs/alerts.md, docs/dashboard.md -> doc/admin/observability/
* `//monitoring:generate_config` outputs are local to it and AFAIK you can copy/move files to the parent package/dir
* The `//monitoring:generate_config` already does 90% of what we needed, but the outputs needed to be massaged a bit to fit out use case.
* When one target calls another target in a macro and they're not in the same package, the "outside" targets outputs will have it's package name prepended. Which is why we use `root_paths` during copy to have the copied file paths the same as if the target was called in the same package
Example:
```
bazel run //:write_monitoring_docs
-> calls //monitoring:generate_config
-> results in outputs being available under `bazel-out/.../monitoring/outputs/`

bazel run //monitoring:write_monitoring_docs
-> calls //monitoring:generate_config
-> results in outputs  being available under `bazel-out/.../outputs/
```

## Test plan
run locally

- [ ] Other generated targets still work

2023-07-14 16:23 UTC, burmudar commented on dev/write_generated_to_source_files.bzl
> +
```suggestion
```

2023-07-17 08:29 UTC, jhchabran requested changes

2023-07-17 08:29 UTC, jhchabran commented on monitoring/main.go
> +//go:generate bazel run //:write_monitoring_docs
This is still a `go:generate` statement, even if it's calling Bazel. This should instead be called by `//dev:write_all`.

2023-07-17 08:29 UTC, jhchabran commented on BUILD.bazel
> +    dest = "doc/admin/observability/",
This looks fragile, it means that we have a target being declared in the root repo, that does things with a given package and write it in a different place. If we keep that logic, it's going to be really hard to understand what's going to happen when similar rules pops up more.

2023-07-17 08:29 UTC, jhchabran commented on BUILD.bazel
> +    strip_prefix = "outputs/docs/",
neat 💯

2023-07-17 08:29 UTC, jhchabran commented on dev/write_generated_to_source_files.bzl
> +        # }
left-over?

2023-07-17 08:54 UTC, jhchabran commented
Need to add the target itself to `//dev:write_all_generated`

2023-07-17 17:46 UTC, burmudar commented on doc/admin/observability/BUILD.bazel
> +        "monitoring/outputs/docs/alerts.md",
I am not a fan of repeating `monitoring/outputs/docs` here and in `strip_prefix` but it is required due to how `//monitoring:generate_config` works atm.

2023-07-19 07:56 UTC, jhchabran approved these changes

2023-07-19 12:20 UTC, merged

2023-07-21 13:16 UTC, mrnugget commented
How do I run this? Nothing I try regenerates docs.

2023-07-21 13:20 UTC, mrnugget commented
I had to manually run this: `cp bazel-bin/monitoring/outputs/docs/* doc/admin/observability/` Otherwise the docs aren't updated.

2023-07-21 13:38 UTC, mrnugget commented
No, doesn't work:

```
$ git diff monitoring
diff --git a/monitoring/definitions/git_server.go b/monitoring/definitions/git_server.go
index 0c4a8d5502..c17c730d2c 100644
--- a/monitoring/definitions/git_server.go
+++ b/monitoring/definitions/git_server.go
@@ -45,7 +45,7 @@ func GitServer() *monitoring.Dashboard {
                                Rows: []monitoring.Row{
                                        {
                                                {
-                                                       Name:        "go_routines",
+                                                       Name:        "fooooooooooooooooooooogo_routines",
                                                        Description: "go routines",
                                                        Query:       "go_goroutines{app=\"gitserver\", instance=~`${shard:regex}`}",
                                                        NoAlert:     true,
$ bazel build //doc/admin/observability:write_monitoring_docs
INFO: Analyzed target //doc/admin/observability:write_monitoring_docs (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //doc/admin/observability:write_monitoring_docs up-to-date:
  bazel-bin/doc/admin/observability/write_monitoring_docs_update.sh
INFO: Elapsed time: 0.113s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action


$ git diff doc

```

No doc generated

2023-07-21 13:55 UTC, burmudar commented
🤔 I'll take a look!

Thanks for reporting it

2023-07-21 14:13 UTC, burmudar commented
> 🤔 I'll take a look!
> 
> Thanks for reporting it

@mrnugget my bad it should've been `bazel run` instead of `bazel build` but regardless it isn't obvious and it should have done it behind the scenes in `sg gen`. I'll update it next week!

```
bazel run //dev:write_all_generated
```
```
-### Git Server: Golang runtime monitoring
+### Git Server Rawr: Golang runtime monitoring

 #### gitserver: go_goroutines

@@ -7437,7 +7437,7 @@ Query: `max by(instance) (go_gc_duration_seconds{job=~".*gitserver"})`

 <br />

-### Git Server: Kubernetes monitoring (only available on Kubernetes)
+### Git Server Rawr: Kubernetes monitoring (only available on Kubernetes)

 #### gitserver: pods_available_percentage

diff --git a/monitoring/definitions/git_server.go b/monitoring/definitions/git_server.go
index 0c4a8d5502..8a4800ae1d 100644
--- a/monitoring/definitions/git_server.go
+++ b/monitoring/definitions/git_server.go
@@ -24,7 +24,7 @@ func GitServer() *monitoring.Dashboard {

        return &monitoring.Dashboard{
                Name:        "gitserver",
-               Title:       "Git Server",
+               Title:       "Git Server Rawr",
                Description: "Stores, manages, and operates Git repositories.",
                Variables: []monitoring.ContainerVariable{
                        {
```