ci: add buf_breaking_test - missing against field input
sourcegraph/sourcegraph pull request #55036
Opened 2023-07-17 18:57 UTC by mucles

added `buf_breaking_test`.   it checks the schema in .proto files for breaking changes to maintain backward compatibility.

see [Buf Breaking Bazel Setup Doc](https://buf.build/docs/build-systems/bazel/#example-2)
## Test plan

2023-07-18 23:38 UTC, jhchabran requested changes
all good overall, just want to understand the decision around committing the file + we really need some doc / comment to explain how to generate that file again.

2023-07-18 23:38 UTC, jhchabran commented on internal/BUILD.bazel
> +    ],  # The Protobuf library
```suggestion
    ], 
```

2023-07-18 23:38 UTC, jhchabran commented on internal/grpc/testprotos/news/v1/BUILD.bazel
> +    strip_import_prefix = "/internal",  # keep
Ah, nice that you found out what was causing a problem here. That being said, didn't you say earlier that this proto file was not useful and is just a left-over from testing things? 

Can't we just drop it?

2023-07-18 23:38 UTC, jhchabran commented on internal/BUILD.bazel
> +    against = ":image.binpb",
What make you decide to commit this? It's a pretty small file and it's quite convenient to have it. 

What motivated your decision in the end? 

Also, you probably want to document (I think a comment here is fine) how to re-create this file when it needs to be updated.

2023-07-19 22:52 UTC, ggilmore commented
After @mucles and I talked, I think we need the following:

- A way to automatically generate a [buf image ](https://buf.build/docs/reference/images) for every commit to main. 
- A way in CI for buf breaking to automatically to target the [image](https://buf.build/docs/reference/images) in the base branch to check against. 

Right now, the image is simply committed to the repository and there isn't a workflow for updating it. We need a moving target (commit on the base branch for this to be useful). We also need a workflow that ensures that it's only updated on the base branch (updating based off of the latest commit would effecitvely mean that the buf breaking check is only checking the current commit - which isn't useful). 

As such, I think it's best to park this PR until we have more time to commit to solving the above issues. The plan is to make gRPC the default in the 5.2.x release - and remove all the rest code for the 5.3.x. relase. I think it's fine to wait until after 5.2.x to work on this PR, since I think a PR like this naturally falls under the  "making gRPC the only way to do  things in the 5.2.x - 5.3.x interim period" umbrella.

2023-07-21 18:51 UTC, closed without merging