bazel: Enable bazel for web-sveltekit
sourcegraph/sourcegraph pull request #55177
Opened 2023-07-20 22:31 UTC by fkling

Where to begin...

This PR adds support for building the SvelteKit prototype via bazel. This is the prerequisite to bundle the prototype in production.

It took me some time to figure out how to make it work. I don't claim that this is the best setup (because I don't really have an idea what I'm doing here), I just tried to get things working. The main issues had been around loading the generate `client/*` packages and importing `*.scss` files.

### Loading `@sourcegraph/*` packages

Unlike our other build tools, SvelteKit/vite load the application into Node for pre-rendering. This happens regardless whether pre-rendering/server-side-rendering is enabled or not (these settings live in the source code because they can be enabled/disabled per route).
Long story short I had to configure vite to also process any `@sourcegraph/*` packages in order to make them compatible with node.

You might wonder why that's not necessary when running vite directly in the repo? In the repo the `@sourcegraph/*` dependencies are all links to the corresponding `client/*` packages. Vite detects that and automatically treats them as "sources", not dependencies.

### SCSS files

Somewhat related to the previous point, the built `@sourcegraph/*` packages do not contain any source SCSS files, only the generated CSS files. So importing SCSS files via `@sourcegraph/.../....scss` doesn't work. Furthermore, the generate code in the packages themselves import SCSS files, which also doesn't work.

The "fix" for this is to rewrite any `*.scss` file imports to `*.css` file imports, but only inside those packages or only referencing files inside those packages. That's what we do in our `webpack.bazel.config.js` file as well.

However, for global styles we need the SCSS files. I added a new target for copying those to the sandbox.

---

Additionally this PR makes the following changes:

- Rearrange style imports to remove unnecessary duplication and reduce the number of callsites that import from `@sourcegraph/*` packages.
- Remove React integration with Notebooks and Insights. It was broken anyway at the moment and removing it reduces the number of dependencies and therefore points of failure.
- Added a new target to copy the image files used by the prototype into the sandbox.
- Disables gazelle for the sveltekit package for the time being. Type checking won't pass anyway because the code in the other client packages don't follow the same restrictions as `client/web-sveltekit`.
- Updated the main header and dev server to proxy requests for notebooks, code insights and user settings to sourcegraph.com.

## Test plan

In `client/web-sveltekit` ran the following commands:

- `pnpm dev` and tested the dev version of the app
- `pnpm build && pnpm preview` to test the prod version of the app
- `bazel build '//client/web-sveltekit:web-sveltekit'` to test the bazel build

2023-07-20 22:43 UTC, fkling commented
Looks like I need to add a target to build the GraphQL type definitions. I was wondering why it worked without locally, but it makes sense now: The file already exists so it's just copied over.

2023-07-21 14:21 UTC, jhchabran commented
@fkling Getting some errors from `bazel configure`: 

```
~/work/sourcegraph S fkling/sveltekit/bazel $ bazel configure
Updating BUILD files for protobuf, go, javascript
WARN[0000] Failed to load base tsconfig file @sourcegraph/tsconfig: open /Users/tech/work/sourcegraph/@sourcegraph/tsconfig: no such file or directory 
Failed to parse tsconfig file client/web-sveltekit/tsconfig.json: ERR: position:399 object key must be string pos:399 : 
918 BUILD files visited
0 BUILD files updated
```

Also, the CI isn't building your target, because it's a leaf in the build tree and no tests depends on it. I'm adding a `build_test` target so you do get it build by the CI.

2023-07-21 14:23 UTC, fkling commented
> Getting some errors from bazel configure:

I think that's because of the comments in the JSON file. I removed them at some point and then there where other warnings. I don't know yet how to resolve them.

> Also, the CI isn't building your target, because it's a leaf in the build tree and no tests depends on it. I'm adding a build_test target so you do get it build by the CI.

Thank you!

2023-07-21 14:24 UTC, jhchabran requested changes
Hey @fkling, nice hacking you did there :) 

I'm reluctant to merge this unless we have tested that we can use the svelte produced client code in the frontend, just building the target as you mentioned in the test plan is not enough.

2023-07-21 14:25 UTC, fkling commented
Do you want me to include all the other necessary changes for serving the files in this PR?

2023-07-24 16:19 UTC, vovakulikov commented
Sorry @fkling I haven't looked into this yet, it's on my radar for the first part of this week (tomorrow, I will take a proper look)

2023-07-27 20:51 UTC, vovakulikov commented on client/web-sveltekit/BUILD.bazel
> +# gazelle:ignore
Does Gazelle struggle with svelte files?

2023-07-27 20:54 UTC, jbedard commented on client/web-sveltekit/BUILD.bazel
> +# gazelle:ignore
I'm curious as well... it looks like vite is also parsing the ts?

2023-07-27 21:09 UTC, fkling commented on client/web-sveltekit/BUILD.bazel
> +# gazelle:ignore
I think when I ran it gazelle complained that it cannot validate imports that imported types or values from Svelte files into TS files.
I know there is an option to disable just the import validation. Gazelle will then still generate a `ts_project` rule, though I don't know how useful that is.
Another problem could be (I don't know) that this projects `tsconfig.json` extends another `tsconfig` file that only exists after building the sveltekit project (e.g. via `pnpm run sync`).

2023-07-31 15:50 UTC, fkling commented
Friendly reminder to review this PR 🙏🏻

2023-08-03 18:58 UTC, fkling commented on cmd/frontend/internal/app/ui/handlers.go
> -	WebpackDevServer bool // whether the Webpack dev server is running (WEBPACK_DEV_SERVER env var)
It's not used anywhere anymore. It was used in the `app.html` template file but with the addition esbuild that was changed ([commit](https://github.com/sourcegraph/sourcegraph/commit/b4f29df8ca345355ae1fd8154c11771418f7b1fc#diff-94b3bd3cd44766807683bda36e902916ac5e1a25d846cb2a97311bb94e9e338c)).
I was wondering how this value was relevant for my situation and it turned out that it didn't have any affect so I removed it (but this can also be done in a separate PR).

2023-08-10 09:35 UTC, fkling commented
What do I need to do to move this forward?

2023-08-10 15:40 UTC, vovakulikov commented
@fkling correct me if I'm wrong, but your Svelte prototype is on stage where it works properly already (no dev problems, no unexpected exceptions, right? I'm fine with merging this since this PR doesn't change much about the main app but just adds support for the svelte package. 

@jhchabran can you expand a bit on this, what kind of testing you're referring to? Are you concerned about the production-ready status of the svelte project, or you think that something will affect our CI and Bazel integration because of these changes? 

>I'm reluctant to merge this unless we have tested that we can use the svelte-produced client code in the frontend, just building the target, as you mentioned in the test plan, is not enough.


@fkling, one question that I got here is how I can switch back to the original client, I think that there might be a trap between two states, if you're in a svelte build you can't go back to the react build? 

Also, I'm a bit confused here because in one place you're saying 
>This is not ready to be officially tested, not even internally

but a few lines below you suggest trying it in production 
>At this point, we just need to try how SvelteKit feels in production.

Can you expand on further plan a bit more, what things will happen after this PR is merged?

2023-08-10 16:21 UTC, fkling commented
@vovakulikov 

> correct me if I'm wrong, but your Svelte prototype is on stage where it works properly already (no dev problems, no unexpected exceptions, right?

It works to the degree that I tested it which means code search and browsing repositories. Since I'm just proxying to .com at the moment I haven't tested all the edge cases (e.g. accessing an empty repository). There are also some TS issues that need to eventually be fixed and there is no extensive test coverage (e.g. no integration tests).

You can give it a try yourself by running `pnpm dev` inside `client/web-sveltekit/` and see if anything stands out that would prevent testing this in prod.

> one question that I got here is how I can switch back to the original client, I think that there might be a trap between two states, if you're in a svelte build you can't go back to the react build?

The settings page is rendered in the React app. You can just go to settings and disable the feature flag for yourself.

> Can you expand on further plan a bit more, what things will happen after this PR is merged?

What I meant with this is that it's not ready to be used as an alternative for the React app, not even internally. There are still features missing.
But I think it's at a point where *some people* can/should evaluate it in a production environment to gain more data points to eventually make a decision about whether to move forward with it or not. I still want to make some improvements if that helps the evaluation (e.g. add code intel hovers) but don't want to implement everything if we decide to drop it (e.g. repo settings pages).

Does that make sense? If it's a bit more feature complete I'm happy to let people use it internally.

2023-08-14 20:46 UTC, jhchabran commented
> @jhchabran can you expand a bit on this, what kind of testing you're referring to? Are you concerned about the production-ready status of the svelte project, or you think that something will affect our CI and Bazel integration because of these changes?

There are two things we need to be careful with: the robustness of the new tests and how it affects build times. Right now @valerybugakov is working on transitionning to ESBuild, but once that's done, at least the build times shouldn't be a problem much more. 

For the first part, the reliability, it's all about how reliable the tests are and how much value this brings to the table. If we're adding a big chunk of code, with flaky tests, for an experimental thing that isn't close to completion, it's obviously not the same thing as if we'd be shipping something that is used let's say in the admin by everyone. 

I hope you it's not too annoying to hear my cold thoughts about this, I know how much an effort it is to rewrite stuff, I'm just a bit careful with the timing, given ESBuild is around the corner (or is about to). Another interesting thing is that we recently rolled-out buildkite analytics (at the bazel target) level, so if you let a few day pass so we can accumulate data, we can totally merge and compare.

After all, nothing is set into stone, it's going to be a revert away if something goes wrong :)

2023-08-15 07:57 UTC, fkling commented
@jhchabran 

> There are two things we need to be careful with: the robustness of the new tests and how it affects build times. Right now @valerybugakov is working on transitionning to ESBuild, but once that's done, at least the build times shouldn't be a problem much more.

Just to clarify: SvelteKit uses it's own bundler, vite, do switching to esbuild won't have any  effect on this part. Building this app will always increase build time by X, regardless what's used for the rest of the front end code.

> For the first part, the reliability, it's all about how reliable the tests are and how much value this brings to the table.

I guess for better or worse there are no tests except the "build" test that you added.

With tests it's a bit of a chicken/egg problem: Adding comprehensive and useful tests take time, which makes sense to do once we know that we want to move forward with this.

---

I can completely understand that we don't want to make multiple changes that affect the build at the same time. I just want to point out that both of these (this prototype and esbuild) don't affect each other.

2023-08-17 15:15 UTC, fkling commented
@jhchabran Can I access the analytics somewhere? What should I look out for?

2023-08-17 15:18 UTC, jhchabran commented
@fkling you can just check the builds on Buildkite, the pipeline displays the average time for it to complete. Just to be clear, unless this is adding 5m, we're perfectly fine. How much time does the test I added takes to complete?

2023-08-17 15:26 UTC, fkling commented
@jhchabran Not sure whether I need to find a build that doesn't say "cached" but e.g. this one says 0.2 seconds: https://buildkite.com/sourcegraph/sourcegraph/builds/236242#0189981c-a0ae-434c-b550-c17785275b35/317-447

2023-08-17 15:28 UTC, jhchabran commented
@fkling oh right my bad, I gave you wrong instructions, that's because the test is basically a no-op, the meat is in the build phase, which isn't printed here. Timing how time it takes on your machine might be easiest way around.

2023-08-17 15:35 UTC, fkling commented
So I changed something int the `vite.config.ts` file to force a rebuild and this is what I got:

```
$ bazel test //client/web-sveltekit:vite_build_test                        
INFO: Analyzed target //client/web-sveltekit:vite_build_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //client/web-sveltekit:vite_build_test up-to-date:
  bazel-bin/client/web-sveltekit/vite_build_test.sh
INFO: Elapsed time: 29.659s, Critical Path: 29.20s
INFO: 4 processes: 1 internal, 2 linux-sandbox, 1 local.
//client/web-sveltekit:vite_build_test                          (cached) PASSED in 0.0s

Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 4 total actions
```

2023-08-21 06:53 UTC, valerybugakov approved these changes
Thanks for sharing a lot of context in the PR description, @fkling! 

Context from my side: I started looking into the `esbuild` migration from `webpack`, but this work is superseded for me by Cody-related tasks. We're searching for a volunteer to drive this forward with my help. 

I tested builds locally, and I do not see any critical issues. Since this PR is focused on the Sveltekit package and does only a few tweaks outside of it LGTM.

2023-08-21 06:53 UTC, valerybugakov commented on gulpfile.js
> +const development = gulp.series(generate, gulp.parallel(watchGenerators, developmentServer, buildSvelteKit))
Does it make to have a separate command that includes `buildSvelteKit`? Or putting it differently: is there a case where we want to have `developmentServer` and `buildSvelteKit` running in parallel?

2023-08-24 18:16 UTC, vovakulikov commented
@jhchabran so to summarise here a bit, you mentioned two concerns as I understood
- the robustness of the new tests
- how it affects build times

I'm a bit confused here about what tests exactly we're talking about here. If you're referring to newly added Bazel rules for the svelte version of the app, I think they look pretty solid, at least at this stage. I mean, we definitely encountered some problems with how our style imports work, but It seems like Felix solved this problem (not ideal, but it is what we need for the prototype, I think Felix hasn't changed anything about non-svelte logic, so changes here should be safe to merge) 

For the second problem, I think 30 seconds for the cold start should be fast enough to not worry much about the general speed of svelte build Bazel tests, but not sure. I doubt that we will have many PRs about svelte since it's not the main version of the app, so Bazel cache should make it part of the pipeline fast enough that we won't see a difference. 

About ESbuild integration, I think with another reorg and plan iterations esbuild migration was pushed out, but even if this migration was happening now, I also don't think this would be affected by this PR, again changes pretty much encapsulated only in svelte specific package. 

cc @valerybugakov, curios about your thoughts here.

2023-08-24 18:17 UTC, vovakulikov commented
Oh, I see that Valery already took a look at this. Sorry you can ignore my comment and mention above (I was looking at the old non-refreshed version of this PR)

2023-09-06 11:40 UTC, fkling commented on gulpfile.js
> +const development = gulp.series(generate, gulp.parallel(watchGenerators, developmentServer, buildSvelteKit))
@valerybugakov 

> is there a case where we want to have developmentServer and buildSvelteKit running in parallel?
Without it the SvelteKit files will be missing when running `sg start enterprise`. I guess I could introduce a new command, `sg start enterprise-sveltekit`, not sure what the best way is... do you have any thoughts/preferences?

2023-09-06 12:08 UTC, valerybugakov commented on gulpfile.js
> +const development = gulp.series(generate, gulp.parallel(watchGenerators, developmentServer, buildSvelteKit))
A separate command would be helpful for folks who intend to run only the react application. Running Sourcegraph services locally eats a lot of resources, and it's nice to have granularity.

2023-09-06 12:37 UTC, fkling commented on gulpfile.js
> +const development = gulp.series(generate, gulp.parallel(watchGenerators, developmentServer, buildSvelteKit))
I added an environment variable that will add the sveltekit build process when set, and created separate `enterprise-*-sveltekit` commands to `sg`.

2023-10-16 09:40 UTC, jhchabran commented on ui/assets/enterprise/assets.go
> +//go:embed all:*
@fkling what does this means? It's the first time I see this syntax

2023-10-16 09:47 UTC, fkling commented on ui/assets/enterprise/assets.go
> +//go:embed all:*
My bad, I should have explained this somewhere (I though I did!):

Funny thing about [`go:embed`](https://pkg.go.dev/embed#pkg-overview):

> If a pattern names a directory, all files in the subtree rooted at that directory are embedded (recursively), except that files with names beginning with ‘.’ or ‘_’ are excluded.

So specifying `*` won't actually embed all files (recursively) in this folder, files beginning with `.` or `_` are excluded.
SvelteKit creates a couple of files that start with `_`. I don't have control over how these are named.

I think switching to `all:*` should be OK since, afaik, there are no files that we wouldn't want to be included. But if that's a concern I guess I could list the SvelteKit files explicitly, maybe something like `//go:embed * all:_sk/*`.

2023-10-16 09:51 UTC, jhchabran approved these changes

2023-10-16 09:52 UTC, fkling commented on ui/assets/enterprise/assets.go
> +//go:embed all:*
Uh yeah, I should have explained what `all` does too... 🤦🏻

2023-10-16 09:53 UTC, jhchabran commented on ui/assets/enterprise/assets.go
> +//go:embed all:*
I think this is uncommon enough to warrant a comment explaining the whole thing above the go:embed pragma!

2023-10-16 12:15 UTC, merged