Add internalRepoVisibility option to GitHub and GitLab connections
sourcegraph/sourcegraph pull request #55404
Opened 2023-07-28 16:02 UTC by pjlast

Adds an `internalRepoVisibility` option to GitHub and GitLab code host connections that can be either `"private"` or `"public"`.

This comes up enough to warrant a configurable option and not require the weird "add another code host connection" workaround.

TODO: Update docs

## Test plan

Tests added for different `internalRepoVisibilty` options.

2023-07-28 16:12 UTC, eseliger approved these changes
As you said, some docs will be good :)

2023-07-28 18:06 UTC, kopancek reviewed
This seems like a hack to me. It will break the permission reason column that I was just touching in 
#55394 .

Could we instead add internal as a column to the repo table? We could then easily modify authzQuery to do what we want - if the repo is internal, check if user has an external account linked to the same code host.

2023-07-29 09:11 UTC, pjlast commented
@kopancek but that isn't what customers want. Some customers want internal repositories to be treated as public repositories. This means being visible even if the person hasn't connected an external account.

2023-07-31 08:43 UTC, erzhtor approved these changes

2023-07-31 08:43 UTC, erzhtor commented on internal/repos/github.go
> +		}
I guess, can be simplified as:
```suggestion
		isPrivate = s.config.InternalRepoVisibility !== 'public'
```

2023-07-31 08:43 UTC, erzhtor commented on internal/repos/gitlab.go
> +		}
Same here

2023-07-31 09:36 UTC, pjlast commented on internal/repos/github.go
> +		}
Be careful, your JavaScript is showing 😆 

But yeah definitely, thanks!

2023-08-01 11:52 UTC, mrnugget requested changes
This needs docs and a changelog if we want to land it.

2023-10-12 09:34 UTC, closed without merging