Fix issue of gerrit repsonese being trimmed when they didn't need to be
sourcegraph/sourcegraph pull request #55561
Opened 2023-08-03 18:43 UTC by varsanojidan

Fixes https://github.com/sourcegraph/sourcegraph/issues/55352

## Test plan

Manual

![image](https://github.com/sourcegraph/sourcegraph/assets/20795805/a40ca7cd-9272-483a-9568-8dce2b9f5083)

2023-08-04 07:07 UTC, mrnugget requested changes
I need to see a test for this and example data 😄

2023-08-04 09:58 UTC, sashaostrikov reviewed
Agree for tests, especially taking the "Gerrit attaches this prefix to **_most_** of its responses" part into consideration.

2023-08-04 09:58 UTC, sashaostrikov commented on internal/extsvc/gerrit/client.go
> +		if len(bs) >= 4 && string(bs[:4]) == ")]}'" {
Love the `bs` naming :)

2023-08-04 11:04 UTC, mrnugget commented on internal/extsvc/gerrit/client.go
> +		if len(bs) >= 4 && string(bs[:4]) == ")]}'" {
You also don't need the cast:

```go
		if len(bs) >= 4 && bs[:4] == ")]}'" {
```

Or, more idiomatic:

```suggestion
		if strings.HasPrefix(s, ")]}'") {
```

2023-08-15 16:27 UTC, varsanojidan commented
@mrnugget @sashaostrikov added a test that queries gerrit with invalid creds, which verifies the unauthorized comes back in full. The other tests passing verify the scenarios where the trimming is happening.

2023-08-15 16:49 UTC, sashaostrikov approved these changes
LGTM!

2023-08-15 16:49 UTC, sashaostrikov commented on internal/extsvc/gerrit/main_test.go
> +func TestTrimming(t *testing.T) {
Let's add a more verbose name explaining the test a bit better :)

2023-08-17 11:56 UTC, mrnugget approved these changes
Approving to unblock, but I think the test is not very self-explanatory and complex for just checking a string.

2023-08-17 11:56 UTC, mrnugget commented on internal/extsvc/gerrit/main_test.go
> +	testutil.AssertGolden(t, "testdata/golden/TestNoTrimmingWhenGerritPrefixIsntPresent.txt", *update, err.Error())
Do you need `testutil.AssertGolden` here or could you just check the string?

2023-08-17 11:56 UTC, mrnugget commented on internal/extsvc/gerrit/main_test.go
> +func TestNoTrimmingWhenGerritPrefixIsntPresent(t *testing.T) {
And where do we test what happens _if_ the prefix is present?

I'm wondering whether the test wouldn't be more readable (if I don't look at the implementation, I'd have a really hard time finding out what the test even tests by just reading the test itself) if you'd test the `do` method directly with two different `httptest`-testserver payloads and assert that it cuts of the prefix if present  and works if it's not present too.

2023-08-17 11:58 UTC, eseliger approved these changes
What Thorsten said, fix LGTM

2023-08-17 11:58 UTC, eseliger commented on internal/extsvc/gerrit/main_test.go
Go nit: `main_test.go` is usually only used for test runner setup. This test should live in `client_test.go`.

2023-09-12 13:59 UTC, eseliger approved these changes

2023-09-12 13:59 UTC, eseliger commented on internal/extsvc/gerrit/client.go
> +		return nil, err
in case the readall here fails we might not close the body, I think we should move back up to above the readAll call

2023-09-12 14:06 UTC, pjlast commented on internal/extsvc/gerrit/client.go
> +		return nil, err
Huh, I think I've been doing this pattern wrong this whole time

2023-09-12 14:07 UTC, pjlast commented on internal/extsvc/gerrit/client.go
> +		return nil, err
Oh, no, I usually put it after the `res, err :=`

2023-09-12 14:07 UTC, pjlast commented on internal/extsvc/gerrit/client.go
> +		return nil, err
:sweating:

2023-09-12 14:25 UTC, merged