dep: bump up caddy version to 2.7.2
sourcegraph/sourcegraph pull request #55606
Opened 2023-08-07 09:48 UTC by evict

This PR makes sure we use a later version of Caddy, with less vulnerabilities. We move from version 2.4.5 to 2.7.2.

## Test plan
Tested the changes locally, confirms it's still serving SSL with 2.7.2.

2023-08-07 09:56 UTC, willdollman approved these changes

2023-08-07 09:57 UTC, burmudar commented on dev/caddy.sh
> +version="2.7.2"
```suggestion
version="2.7.3"
```
> Do not use this release, use [v2.7.3](https://github.com/caddyserver/caddy/releases/tag/v2.7.3) instead which contains several hot fixes.

2023-08-07 09:58 UTC, burmudar reviewed
2.7.3 got released over the weekend and the official recommendation is to use that rather than 2.7.2

2023-08-07 09:58 UTC, burmudar requested changes
See previous comment

2023-08-07 09:59 UTC, burmudar commented on sg.config.yaml
> +      CADDY_VERSION: 2.7.2
```suggestion
      CADDY_VERSION: 2.7.3
```

2023-08-07 09:59 UTC, burmudar approved these changes

2023-08-07 10:29 UTC, willdollman commented
Waiting on caddy 2.7.3 docker images to be released

2023-08-15 10:19 UTC, willdollman commented
Caddy 2.7.3 released https://hub.docker.com/layers/library/caddy/2.7.3/images/sha256-f9824933254e3e43e0508670ee9bdcde704621017e95119a05317383b1878f4f?context=explore

2023-08-16 09:48 UTC, merged