Update use_cases.md
sourcegraph/sourcegraph pull request #55627
Opened 2023-08-08 03:55 UTC by iskyOS

Updates the use cases docs page for new commands function plus inline chat for refactors.

## Test plan

Docs only.

2023-08-08 19:24 UTC, MaedahBatool requested changes
Overall looks good. Left a few comments. :)

2023-08-08 19:24 UTC, MaedahBatool commented on doc/cody/explanations/use_cases.md
> +To refactor code inline, try:
```suggestion
To refactor code inline:
```

2023-08-08 19:24 UTC, MaedahBatool commented on doc/cody/explanations/use_cases.md
> +2. Click the `+` icon in the gutter to the left of the first line of code.
```suggestion
2. Click the `+` icon to the left of the first line of code.
```

2023-08-08 19:24 UTC, MaedahBatool commented on doc/cody/explanations/use_cases.md
> +4. Click `Ask Cody`.
```suggestion
4. Click `Ask Cody` (or alternatively use shortcut `Cmd + Enter`)
```

2023-08-09 03:09 UTC, iskyOS commented
Thanks @MaedahBatool! I've updated. I also made one more commit to clean up formatting and make a note about inline chat being VS Code only at the moment.

2023-08-09 16:09 UTC, merged