JetBrains: Cody: make it optional to include `https://` prefix to Sourcegraph endpoint
sourcegraph/sourcegraph pull request #55632
Opened 2023-08-08 08:40 UTC by Sa1to

Fixes [#55104](https://github.com/sourcegraph/sourcegraph/issues/55104).

Previously, users had to type out `https://` when configuring the Sourcegraph endpoint. This PR makes this step optional so users can type out the domain directly, like `sourcegraph.com` instead of `https://sourcegraph.com`.

## Test plan
* Open Cody settings
* Mark `Use an enterprise instance` radio button 
* In `Sourcegraph URL` text field type in url without protocol
* After changing focus from this text field, `http://` prefix should be added automatically

https://github.com/sourcegraph/sourcegraph/assets/9321940/9d64ccf7-6c83-41bd-85f5-9bc7e5a292ba

2023-08-10 15:44 UTC, mkondratek commented on client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
> +        if (!StringUtils.startsWith(url, "http://") && !StringUtils.startsWith(url, "https://") && !url.isEmpty()) {
pls consider usage of `UriUtil.splitScheme` - it is a bit better than working on plain strings

2023-08-10 15:47 UTC, mkondratek commented on client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
> -                    ? new ValidationInfo("This is an invalid URL", urlTextField)
I would rather keep the validation (just to check for any other protocols which I guess should be still forbidden). The only change should be to allow url without scheme.

2023-08-17 09:30 UTC, Sa1to commented
@olafurpg Please take a look :)

2023-08-17 11:42 UTC, olafurpg requested changes
@Sa1to Thank you for this contribution!

2023-08-17 15:39 UTC, Sa1to commented on client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
> +          urlTextField.setText("http://" + urlTextField.getText());
I can go with this solution but just FYI, we are already adding `/` at the end of the url if its not present, so after those changes if the user insert `sourcegraph.com` and enters the config again, it will show `sourcegraph.com/`. Maybe it makes sense to add `https://` as well.

https://github.com/sourcegraph/sourcegraph/assets/9321940/6d2703c8-b954-4a36-9729-de5d62e42ab0

2023-08-18 08:42 UTC, olafurpg commented on client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
> +          urlTextField.setText("http://" + urlTextField.getText());
Good point. Ideally, the value of the input field should always be exactly what the user typed regardless if the input field got unfocused or if the user saves settings, quits IntelliJ, and opens settings the day after. We're not respecting this ideal for the trailing `/` for now, but we can fix that later. For `https://`, I think it's best to never display it to the user, we just silently infer it.

2023-08-18 09:13 UTC, olafurpg approved these changes
The latest changes look great. The build was failing due to an import for a renamed symbols, you can just remove the import. 

One last blocking question about the validation logic, otherwise LGTM 👍🏻 Thank you for addressing the feedback!

2023-08-18 09:13 UTC, olafurpg commented on client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
> +          if (urlTextField.getText().isEmpty()) {
Is this diff still needed? It seems to be reimplementing the validation logic with a new API but it's unrelated to inferring the missing `https://` 🤔

2023-08-18 10:26 UTC, Sa1to commented on client/jetbrains/src/main/java/com/sourcegraph/config/SettingsComponent.java
> +          if (urlTextField.getText().isEmpty()) {
This is displaying dialog to the user when he is typing in the input and no text is entered, so maybe it makes sense to have it, i guess this is more a matter of UX.

2023-08-22 10:19 UTC, olafurpg commented
Thank you for this contribution @Sa1to ! In order to merge the PR, someone else with merge rights needs to open a separate PR to get the CI green. I was going to do this but realized that we're preparing a new rewrite of authentication settings where the concrete diff in this PR is going to look differently with  the new UI. Instead, I'm going to close this PR as a wontfix.

2023-08-22 10:19 UTC, closed without merging