[test] Tests for docsite
sourcegraph/sourcegraph pull request #55681
Opened 2023-08-09 17:10 UTC by Numbers88s

testing css changes for preview link
## Test plan

2023-08-11 20:39 UTC, mucles commented on doc/_resources/templates/root.html
> +                <script src="{{assetsFromVersion .ContentVersion "railroad.js" }}"></script>
```suggestion
                <script src="{{.assetsFromVersion .ContentVersion "docsite.js" }}"></script>
                <script src="{{.assetsFromVersion .ContentVersion "railroad.js" }}"></script>
```

2023-08-11 20:41 UTC, mucles commented on doc/_resources/templates/root.html
> +                <link rel="stylesheet" type="text/css" href="{{assetsFromVersion .ContentVersion "docsite.css" }}" />
```suggestion
                <link rel="stylesheet" type="text/css" href="{{assetsFromVersion .ContentVersion "docsite.css" }}" />
```

2023-08-11 20:42 UTC, mucles commented on doc/_resources/templates/root.html
> +                <script src="{{assetsFromVersion .ContentVersion "railroad.js" }}"></script>
```suggestion
                <link rel="stylesheet" type="text/css" href="{{.assetsFromVersion .ContentVersion "docsite.css" }}" />
                <script src="{{.assetsFromVersion .ContentVersion "docsite.js" }}"></script>
                <script src="{{.assetsFromVersion .ContentVersion "railroad.js" }}"></script>
```

2023-08-11 20:42 UTC, mucles commented on doc/_resources/templates/root.html
> +                        <img src="{{assetsFromVersion .ContentVersion "logo-theme-dark.svg" }}" class="theme-dark" alt="Sourcegraph docs"/>
```suggestion
                        <img src="{{.assetsFromVersion .ContentVersion "logo-theme-light.svg" }}" class="theme-light" alt="Sourcegraph docs"/>
                        <img src="{{.assetsFromVersion .ContentVersion "logo-theme-dark.svg" }}" class="theme-dark" alt="Sourcegraph docs"/>
```

2023-08-11 20:45 UTC, mucles requested changes
The following changes should resolve the Bazel error, tested locally. 
![image](https://github.com/sourcegraph/sourcegraph/assets/78464298/0a64f383-c702-4e3a-9cbf-01030851611c)

2023-08-11 20:45 UTC, Numbers88s commented on doc/_resources/templates/root.html
> +                <script src="{{assetsFromVersion .ContentVersion "railroad.js" }}"></script>
I'm not sure that is the reason. The `assetsFromVersion` is a template function much like this one https://github.com/sourcegraph/sourcegraph/pull/55681/files#diff-ca039c482acee552fabec35e6aefe88310ebb6cd3f9bcbe97643340f37df4c29R236

2023-08-11 20:46 UTC, Numbers88s commented
> The following changes should resolve the Bazel error, tested locally. ![image](https://user-images.githubusercontent.com/78464298/260147673-0a64f383-c702-4e3a-9cbf-01030851611c.png)

Interesting, then how come [this template function](https://github.com/sourcegraph/sourcegraph/pull/55681/files#diff-ca039c482acee552fabec35e6aefe88310ebb6cd3f9bcbe97643340f37df4c29R236) doesn't need the dot?

2023-08-11 21:23 UTC, mucles commented
> @mucles Interesting, then how come [this template function](https://github.com/sourcegraph/sourcegraph/pull/55681/files#diff-ca039c482acee552fabec35e6aefe88310ebb6cd3f9bcbe97643340f37df4c29R236) doesn't need the dot?
@Numbers88s Oh, you're right. I thought it was a variable. My mistake; that is old that it would pass.  You have this [PR](https://github.com/sourcegraph/docsite/pull/96) where you defined **assetsFromVersion**. This most likely will need to be merged first before the test will pass.

2023-08-14 18:26 UTC, efritz approved these changes

2023-08-14 20:43 UTC, mucles approved these changes

2023-08-17 17:33 UTC, merged