[cody/web] Papercuts: Hide delete & update history icon
sourcegraph/sourcegraph pull request #55749
Opened 2023-08-10 16:32 UTC by st0nebraker

Closes #55746 - Hides delete chat item or clear all chat history when there are no chat interactions. Updates chat history icon to match [VS Code's](https://github.com/sourcegraph/cody/pull/323)

### Empty chat history
<img width="602" alt="Screenshot 2023-08-10 at 9 20 52 AM" src="https://github.com/sourcegraph/sourcegraph/assets/59381432/eb3a8d18-f0b1-482d-92fa-99d697a8cf17">
<img width="479" alt="Screenshot 2023-08-10 at 9 25 40 AM" src="https://github.com/sourcegraph/sourcegraph/assets/59381432/be229104-b94d-4711-a2c5-10d1a3dc5224">

### Filled chat history
<img width="449" alt="Screenshot 2023-08-10 at 9 21 42 AM" src="https://github.com/sourcegraph/sourcegraph/assets/59381432/c2e4b713-675f-4c43-8483-52e5f63b1c4d">
<img width="632" alt="Screenshot 2023-08-10 at 9 27 22 AM" src="https://github.com/sourcegraph/sourcegraph/assets/59381432/74d45754-abde-4aee-b644-fa32523fbd4e">

## Test plan
- Manual test on cody sidebar & cody chat page: With chat history and without

2023-08-14 18:11 UTC, thenamankumar requested changes

2023-08-14 18:11 UTC, thenamankumar commented on client/web/src/cody/sidebar/CodySidebar.tsx
> +                        {showHistory && transcriptHistory[0].interactions.length > 0 && (
"Clear all chats" depends on `transcriptHistory.length` and not on `transcriptHistory[0].interactions.length`

transcriptHistory stores the list of all chats. 

Need to change everywhere else too.

2023-08-15 06:06 UTC, thenamankumar commented on client/web/src/cody/sidebar/CodySidebar.tsx
> +                        {showHistory && transcriptHistory[0].interactions.length > 0 && (
To handle that case the correct logic would be:

`showHistory && (transcriptHistory.length > 1  || !!transcriptHistory[0]?.interactions?.length)`

2023-08-15 17:00 UTC, st0nebraker commented on client/web/src/cody/sidebar/CodySidebar.tsx
> +                        {showHistory && transcriptHistory[0].interactions.length > 0 && (
My question was about your original point & if there is another spot this change needs to touch?

2023-08-18 17:31 UTC, thenamankumar commented on client/web/src/cody/sidebar/CodySidebar.tsx
> +                        {showHistory && transcriptHistory[0].interactions.length > 0 && (
Where all the "Clear all chats" logic is there. Delete history item logic is fine.

2023-08-21 18:19 UTC, st0nebraker commented on client/web/src/cody/sidebar/CodySidebar.tsx
> +                        {showHistory && transcriptHistory[0].interactions.length > 0 && (
Thanks! Updated in [af6e49d](https://github.com/sourcegraph/sourcegraph/pull/55749/commits/af6e49d8ac332a04fe83f72dd867a1986e102574)

2023-08-23 13:34 UTC, thenamankumar approved these changes

2023-08-23 13:34 UTC, merged