Add GraphQL read resolvers for code hosts
sourcegraph/sourcegraph pull request #55882
Opened 2023-08-15 17:47 UTC by eseliger

## Test plan

2023-08-16 04:58 UTC, BolajiOlajide approved these changes

2023-08-16 06:30 UTC, kopancek approved these changes
Overall looks good to me, added a few non-blocking comments.

2023-08-16 06:30 UTC, kopancek commented on cmd/frontend/graphqlbackend/code_hosts.go
> +package graphqlbackend
Unrelated to this PR, but every time I see the path `cmd/frontend/graphqlbackend`, it hurts 😿

2023-08-16 06:30 UTC, kopancek commented on cmd/frontend/graphqlbackend/code_hosts.go
> +	return &codeHostConnectionResolver{
~~Should we name this `codeHostResolver` instead? Since we call this file`code_hosts` the function is called `CodeHosts`, that's what I would expect to get.~~

I see now that it is meant to be the graphql connection. Why on earth did graphql call it a connection is beyond me. Naming sucks 😢 . 

But it is really confusing since we do have an entity called `code host connection`. Can we rename this to something better, e.g. `codeHostNodesResolver` or `codeHostListResolver` instead?

2023-08-16 06:30 UTC, kopancek commented on cmd/frontend/graphqlbackend/code_hosts.go
> +	m, ok, err := store.GetByID(ctx, 24)
Can we have this magic number defined as a constant? How sure are we that it will always be 24. Can we use some other mechanism to check if the migration was done other than using it's ID?

2023-08-16 06:30 UTC, kopancek commented on cmd/frontend/graphqlbackend/code_hosts.go
> +func (r *codeHostConnectionResolver) IsMigrationDone(ctx context.Context) (bool, error) {
Why do we need to know if the migration was done as part of the graphql layer? In all the other work we have done in the past with OOB migrations, I do not remember needing code like this.

2023-08-16 06:30 UTC, kopancek commented on cmd/frontend/graphqlbackend/code_hosts.go
> +type codeHostResolver struct {
Can we split the `codeHostResolver` related parts into it's own file? E.g. `code_host.go` in the same dir? Would be more readable to me.

2023-08-16 13:16 UTC, eseliger commented on cmd/frontend/graphqlbackend/code_hosts.go
> +	return &codeHostConnectionResolver{
I think in the name of consistency, we should actually leave this name :sadge: In GraphQL the code host connection is still called `ExternalService` so I'm hoping this makes it a little clearer

2023-08-16 13:17 UTC, eseliger commented on cmd/frontend/graphqlbackend/code_hosts.go
> +	m, ok, err := store.GetByID(ctx, 24)
We've not merged the PR with the migration yet that will define this constant, I can make sure to use it here once merged 👍

2023-08-16 13:18 UTC, eseliger commented on cmd/frontend/graphqlbackend/code_hosts.go
> +func (r *codeHostConnectionResolver) IsMigrationDone(ctx context.Context) (bool, error) {
We want to display a banner to show "the data is still being backfilled" because not all code hosts might be returned from the API until then

2023-08-16 13:23 UTC, eseliger commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +func TestSchemaResolver_CodeHosts(t *testing.T) {
can we get a test for CodeHost by ID through `node(id: $id)` ?

2023-08-16 13:23 UTC, eseliger commented on internal/database/code_hosts.go
> +	}
can we share this logic between list and count?

2023-08-16 13:23 UTC, eseliger commented on internal/database/code_hosts.go
> +	return count, nil
`basestore.ScanFirstInt32` can be our friend here :)

2023-08-16 13:23 UTC, eseliger commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +		{ID: 3, URL: "bitbucket.com", Kind: extsvc.KindBitbucketServer, APIRateLimitQuota: pointers.Ptr(int32(3)), APIRateLimitIntervalSeconds: pointers.Ptr(int32(3)), GitRateLimitIntervalSeconds: pointers
can we have a fourth code host with null limits?

2023-08-16 13:23 UTC, eseliger commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +	after := "Q29kZUhvc3Q6MQ=="
would like to see a test for each

- no first
- first and no after
- first: 1 and after to paginate through the list and see it properly paginate through all 3 hosts

2023-08-16 14:06 UTC, varsanojidan commented on cmd/frontend/graphqlbackend/code_hosts.go
> +package graphqlbackend
big agree

2023-08-16 17:48 UTC, varsanojidan commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +	after := "Q29kZUhvc3Q6MQ=="
currently first is non-nullable, do we want to change that?

2023-08-16 21:04 UTC, varsanojidan commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +	after := "Q29kZUhvc3Q6MQ=="
Heyo, I've addressed the other comments, except fwo:

1) first being nullable, its non-nullable rn but I can just change that and add the test.
2) for pagination, I added extra tests that simulate going through the code hosts 1 by 1, but its all pretty mocked because the DB responses are mocked, do you think its worth doing an unmocked test for pagination or are the tests I just added sufficent?

2023-08-18 08:52 UTC, mrnugget requested changes

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_host.go
> +	// only accessible to admins anyways.
"returned _to_ site-admins", right?

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			}`,
Intendation here seems off.

2023-08-18 08:52 UTC, mrnugget commented on internal/database/code_hosts_test.go
> +	ten := int32(10)
```suggestion
	quotaOne := int32(10)
```

2023-08-18 08:52 UTC, mrnugget commented on internal/database/code_hosts_test.go
> +	twenty := int32(20)
```suggestion
	quotaTwo := int32(20)
```

2023-08-18 08:52 UTC, mrnugget commented on internal/database/code_hosts_test.go
> +		results  int32
```suggestion
		wantResults  int32
```

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +		t.Run(tc.name, func(t *testing.T) {
Nitpick but you could probably get rid of the `name` because it's redundant with the description.

```suggestion
		t.Run(fmt.Sprintf("first=%d after=%d", tc.first, tc.after), func(t *testing.T) {
```

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			}
Does this have to be in the body of the main test loop?

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			newAfter := "null"
Isn't this `wantEndCursor`?

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			})
There's a ton of string concatenation and escaping and quoting going on in here. I wonder whether the test wouldn't be more readable if you use a temporary struct here and marshal that to JSON? i.e.

```go
type codeHostsResult struct {
  codeHosts []struct {
    // ...
  }
TotalCount int
PageInfo struct {
  HasNextPage bool
  EndCursor string
}
}
```
etc. 

And then you can do:

```go
wantResult := codeHostsResult{...}
wantResultResponse := json.Marshal(wantResult) // etc
```

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +	codeHost := &types.CodeHost{ID: 2, URL: "github.com", Kind: extsvc.KindGitHub, APIRateLimitQuota: pointers.Ptr(int32(1)), APIRateLimitIntervalSeconds: pointers.Ptr(int32(1)), GitRateLimitIntervalSec
Let's format this a bit :)

2023-08-18 08:52 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +		}`,
Intendation off

2023-08-18 08:52 UTC, mrnugget commented on internal/database/code_hosts_test.go
> +			name: "count with cursor , no matches",
```suggestion
			name: "count with cursor, no matches",
```

2023-08-18 12:40 UTC, varsanojidan commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			})
I think using anonymous structs might be a bit large, because this struct is nested, initializing it would look like:

```go
tcodeHostsResult := struct {
    CodeHosts struct {
        Nodes []struct {
            ID                          string
            Kind                        string
            URL                         string
            ApiRateLimitIntervalSeconds int
            ApiRateLimitQuota           int
            GitRateLimitIntervalSeconds int
            GitRateLimitQuota           int
            ExternalServices            []struct {
                DisplayName string
                ID          string
            }
        }
    }
    TotalCount int
    PageInfo   struct {
        HasNextPage bool
        EndCursor   string
    }
}{
    CodeHosts: struct {
        Nodes []struct {
            ID                          string
            Kind                        string
            URL                         string
            ApiRateLimitIntervalSeconds int
            ApiRateLimitQuota           int
            GitRateLimitIntervalSeconds int
            GitRateLimitQuota           int
            ExternalServices            []struct {
                DisplayName string
                ID          string
            }
        }
    }{
        Nodes: []struct {
            ID                          string
            Kind                        string
            URL                         string
            ApiRateLimitIntervalSeconds int
            ApiRateLimitQuota           int
            GitRateLimitIntervalSeconds int
            GitRateLimitQuota           int
            ExternalServices            []struct {
                DisplayName string
                ID          string
            }
        }{
            // NODES GO HERE
        },
    },
    TotalCount: 0, // Initial value
    PageInfo: struct {
        HasNextPage bool
        EndCursor   string
    }{
        HasNextPage: false,
        EndCursor:   "",
    },
}
```

Do you think it would be better to just create all the types? Leave it as is?

2023-08-18 13:36 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			})
My proposal was to create a type (or a few of them). The anonymous struct obviously doesn't help with readability:

Compare:

```go
func withoutTypes() {
	result := struct {
		CodeHosts struct {
			Nodes []struct {
				ID                          string
				Kind                        string
				URL                         string
				ApiRateLimitIntervalSeconds int
				ApiRateLimitQuota           int
				GitRateLimitIntervalSeconds int
				GitRateLimitQuota           int
				ExternalServices            []struct {
					DisplayName string
					ID          string
				}
			}
		}
		TotalCount int
		PageInfo   struct {
			HasNextPage bool
			EndCursor   string
		}
	}{
		CodeHosts: struct {
			Nodes []struct {
				ID                          string
				Kind                        string
				URL                         string
				ApiRateLimitIntervalSeconds int
				ApiRateLimitQuota           int
				GitRateLimitIntervalSeconds int
				GitRateLimitQuota           int
				ExternalServices            []struct {
					DisplayName string
					ID          string
				}
			}
		}{
			Nodes: []struct {
				ID                          string
				Kind                        string
				URL                         string
				ApiRateLimitIntervalSeconds int
				ApiRateLimitQuota           int
				GitRateLimitIntervalSeconds int
				GitRateLimitQuota           int
				ExternalServices            []struct {
					DisplayName string
					ID          string
				}
			}{
				// NODES GO HERE
			},
		},
		TotalCount: 0, // Initial value
		PageInfo: struct {
			HasNextPage bool
			EndCursor   string
		}{
			HasNextPage: false,
			EndCursor:   "",
		},
	}
}

func withTypes() {
	type codeHostNode struct {
		ID                          string
		Kind                        string
		URL                         string
		ApiRateLimitIntervalSeconds int
		ApiRateLimitQuota           int
		GitRateLimitIntervalSeconds int
		GitRateLimitQuota           int
		ExternalServices            []struct {
			DisplayName string
			ID          string
		}
	}

	type pageInfo struct {
		HasNextPage bool
		EndCursor   string
	}

	type codeHostsResult struct {
		CodeHosts struct {
			Nodes []codeHostNode
		}
		TotalCount int
		PageInfo   pageInfo
	}

	result := codeHostsResult{
		CodeHosts: struct {
			Nodes []codeHostNode
		}{
			Nodes: []codeHostNode{
				// NODES GO HERE
			},
		},
		TotalCount: 0, // Initial value
		PageInfo: pageInfo{
			HasNextPage: false,
			EndCursor:   "",
		},
	}
}
```

2023-08-18 13:40 UTC, varsanojidan commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			})
ahh I guess when I read your suggestion and it said temporary struct and saw the use of []struct here
```go
type codeHostsResult struct {
  codeHosts []struct {
    // ...
  }
TotalCount int
PageInfo struct {
  HasNextPage bool
  EndCursor string
}
}
```
thats where the confusion came from. I didn't know whether you meant anonymous struct or creating types for it.

Cool yeah, the multiple types makes sense to me too
>Do you think it would be better to just create all the types? Leave it as is?

2023-08-18 15:18 UTC, varsanojidan commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			})
done, in the most recent commit.

2023-08-21 08:17 UTC, mrnugget approved these changes

2023-08-21 08:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +	}
Nitpick, but I think the `pointers.Ptr` usage is a bit overdone :)

```suggestion
	newCodeHost := func(id int32, url, kind string, quota int32) *types.CodeHost {
		var q *int32 = nil
		if quota != 0 {
			q = &quota
		}
		return &types.CodeHost{
			ID:                          id,
			URL:                         url,
			Kind:                        kind,
			APIRateLimitQuota:           q,
			APIRateLimitIntervalSeconds: q,
			GitRateLimitQuota:           q,
			GitRateLimitIntervalSeconds: q,
		}
	}

	testCodeHosts := []*types.CodeHost{
		newCodeHost(1, "github.com", extsvc.KindGitHub, 1),
		newCodeHost(2, "gitlab.com", extsvc.KindGitLab, 2),
		newCodeHost(3, "bitbucket-cloud.com", extsvc.KindBitbucketCloud, 0),
		newCodeHost(4, "bitbucket-cloud.com", extsvc.KindBitbucketCloud, 4),
	}
```

2023-08-21 08:17 UTC, mrnugget commented on cmd/frontend/graphqlbackend/code_hosts_test.go
> +			hasNext := false
```suggestion
			wantHasNext := false
```

No? It's just like the value next to it, the `endCursor`

2023-08-21 13:10 UTC, merged