KS/set first verified email to primary
sourcegraph/sourcegraph pull request #55950
Opened 2023-08-16 23:58 UTC by MrStacks

Closes #48996
Added a check to the `SetVerified` function to see if the primary email wasn't set. If it isn't set, call the `SetPrimaryEmail` function with the newly verified email. 

## Test plan

Added the test `TestUserEmails_SetVerified_SetsPrimaryIfNoneExist` to the `user_emails_test.go` test package.

2023-08-17 15:09 UTC, MrStacks commented
CLA has been signed but the check still fails.

2023-08-17 20:37 UTC, jdorfman commented
@cla-bot check

2023-08-17 20:39 UTC, jdorfman commented
Thanks @MrStacks I will make sure this gets the right eyes on it!

2023-08-17 22:11 UTC, MrStacks commented
Thanks @jdorfman! Is there anything I can do to fix the unsuccessful checks?

2023-08-18 16:02 UTC, jdorfman commented
@MrStacks an engineer will need to look into it. Might be early next week.

2023-08-21 07:02 UTC, kopancek requested changes
@MrStacks Thanks for providing the PR, the intention looks great to me. I've added 2 suggestions to improve the existing solution. Let us know if you want to followup or if we should do the changes suggested ourselves.

2023-08-21 07:02 UTC, kopancek commented on internal/database/user_emails.go
> +		}
I think the code would be safer if we did all of the DB operations in the same transaction. The easiest would probably be to change the UPDATE SQL query above, to something like:
```
UPDATE user_emails 
SET 
    verification_code=null, 
    verified_at=now(),
    is_primary=(NOT EXISTS (
        SELECT 1 
        FROM user_emails
        WHERE 
            user_id=$1
            AND email != $2
            AND is_primary=TRUE
    ))
WHERE 
    user_id=$1
    AND email=$2
```

That way we do everything in one SQL query and do not need the business logic Go code. The existing unit tests should already cover it, so it should be easy to verify that my SQL handwriting actually works.

2023-08-21 23:33 UTC, MrStacks commented on internal/database/user_emails_test.go
> +	}
Did that and integrated my test with the `SetVerified` test so that it uses the `t.Run` convention and tests all aspects of `SetVerified`.

2023-08-21 23:34 UTC, MrStacks commented on internal/database/user_emails.go
> +		}
Updated to that and local tests showed that it worked. Pushing new commit for PR. @kopancek Thank you for your review.

2023-08-22 04:24 UTC, kopancek approved these changes

2023-08-22 14:53 UTC, kopancek requested changes

2023-08-22 14:53 UTC, kopancek commented on output.log
> +ok  	github.com/sourcegraph/sourcegraph/internal/database	171.204s
This file seems unnecessary. Can we remove it?

2023-08-23 00:23 UTC, MrStacks commented on output.log
> +ok  	github.com/sourcegraph/sourcegraph/internal/database	171.204s
Oops. I made it output `.log` files because the test output exceeded my terminal window. Sorry! Fixed.

2023-08-23 06:27 UTC, kopancek approved these changes

2023-08-23 07:21 UTC, merged

2023-08-23 07:31 UTC, kopancek commented
FYI I ran our secret CI steps and it passed, so I merged the PR 🎉 Thanks for the contribution 🙇

2023-08-23 21:51 UTC, jdorfman commented
Thanks @MrStacks, for your contribution!

Thanks @kopancek for making this happen. :)