JetBrains: add ability to override automatic "codebase" detection
sourcegraph/sourcegraph pull request #56151
Opened 2023-08-22 22:31 UTC by slimsag

Adds a setting to configure `cody.codebase` in the same way as e.g. VS Code:

<img width="723" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/3173176/fab27cfa-2be0-4922-9678-aba6ffff393b">

## Test plan

Manually tested, I ran:

```
./gradlew -PenableAgent=true -PforceAgentBuild=true :runIde
```

Then modified the `Codebase` field and confirmed the agent was using that value to find embeddings.

2023-08-22 23:27 UTC, chwarwick requested changes
It looks to me like this setting will be continually overwritten based on the automatic repo detection feature in `CodyAgentCodebase.java`.  The opposite should be true that this value overrides the detected.

2023-08-22 23:27 UTC, chwarwick commented on client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
> +        .setCodebase(getApplicationLevelConfig().getCodyCodebase())
should this just be the `getCodyCodebase()` that works it's way though Project -> Application -> User level settings?

2023-08-23 01:21 UTC, slimsag commented
> It looks to me like this setting will be continually overwritten based on the automatic repo detection feature in CodyAgentCodebase.java. The opposite should be true that this value overrides the detected.

I believe I've fixed this now with the logic in `ConfigUtil.java` `updateAgentConfigurationWithDetectedCodebase`, PTAL.

Not sure if this is the best way to do this, I've been having trouble navigating our Java code and am a Java noob so any guidance appreciated :)

2023-08-23 07:24 UTC, vdavid requested changes
Added a few suggestions. Also, we probably want to include a docs change in README.md to document the new setting.

2023-08-23 07:24 UTC, vdavid commented on client/jetbrains/src/main/java/com/sourcegraph/config/ConfigUtil.java
> +  public static ExtensionConfiguration updateAgentConfigurationWithDetectedCodebase(
I suggest using an architecture where
a.) we have the override right in `getCodyCodebase` OR
b.) if we need to be able to get the stored config directly, then create `getCodyCodebaseWithAutodetectFallback` and use that in `CodyAgentCodebase`. 

Why: The verb "update" leads me to think this method involves a state change. But when I started to think about a better name, I realized this architecture is very unusual to me, probably unidiomatic.

2023-08-23 08:11 UTC, vdavid commented
I've talked to @olafurpg, and we concluded that rather than adding this to settings UI, it'd be better to:
1. Add it to the chat sidebar under the textbox like same [way](https://share.cleanshot.com/Y3kYcnPN) we have it for Cody Web
2. If there's an enterprise need for a fixed overwrite, then add it as a VM option or a setting in the properties file.

So I'll stop my review on this one, and we can probably close this PR, or repurpose it for strategic.

2023-08-24 10:20 UTC, olafurpg commented
Closing this PR as wontfix since we prefer to mirror the UI for Cody on the web where users select repo context in the chat sidebar instead of in settings.

2023-08-24 10:20 UTC, closed without merging