Update Cody capabilities
sourcegraph/sourcegraph pull request #56269
Opened 2023-08-28 21:20 UTC by iskyOS

Update to the Cody docs homepage + capabilities page. Re-ordering features to lead with autocomplete, and updating some messaging across the pages.

## Test plan

Docs change only. Local testing.

2023-08-29 11:09 UTC, MaedahBatool requested changes
Left some feedback. Overall this is good. :)

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +**Commands** allow you to quickly run common actions. Commands are predefined, reusable prompts accessible by hotkey from within the [VS Code extension](https://marketplace.visualstudio.com/items?ite
```suggestion
**Commands** allow you to run common actions quickly. Commands are predefined, reusable prompts accessible by hotkey from within the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=sourcegraph.cody-ai). Like autocomplete and chat, commands will search for context in your codebase to provide more contextually aware and informed answers (or to generate more idiomatic code snippets).
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +**Custom commands** let you to save your own quick actions and prompts for Cody based on your common workflows. They are defined in JSON format and let you call CLI tools, write custom prompts, and s
```suggestion
**Custom commands** let you save your quick actions and prompts for Cody based on your common workflows. They are defined in JSON format and allow you to call CLI tools, write custom prompts, and select context to be sent to Cody. This provides a flexible way to tailor Cody to your needs.
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +You can invoke custom comamnds with the same hotkey as predefined commands. Alternatively, you can right-click on selected code, open the Cody context menu and select the `Custom Commands (Experiment
```suggestion
You can invoke custom commands with the same hotkey as predefined commands. Alternatively, you can right-click the selected code, open the Cody context menu, and select the `Custom Commands (Experimental)` option.
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +You can define custom commands for Cody in the `cody.json` file. To make commands only available for a specific project, create the `cody.json` file in the `.vscode` directory of that project. These
```suggestion
You can define custom commands for Cody in the `cody.json` file. To make commands only available for a specific project, create the `cody.json` file in that project's `.vscode` directory. When you work on that project, these workspace-specific custom commands will be available.
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +To make custom commands globally available across multiple projects, create a new `cody.json` file in the `.vscode` folder of your home directory. These global custom commands will be available for y
```suggestion
To make custom commands globally available across multiple projects, create a new `cody.json` file in your home directory's `.vscode` folder. These global custom commands will be available in Cody in any workspace.
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +Cody uses LLMs trained on broad code, and we've found it to effectively support all common programming languages. However, the quality of autocompletions and other features may vary based on how well
```suggestion
Cody uses LLMs trained on broad code, and we've found it to support all common programming languages effectively. However, the quality of autocompletion and other features may vary based on how well the underlying LLM model was trained in a given language.
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +We've found Cody to work especially well with Python, Go, JavaScript, and TypeScript code.
```suggestion

```

I think this is a repetitive line we can omit it.

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/overview/index.md
> +Cody is a free and open-source AI coding assistant that can write, understand, and fix code. Cody is powered by Sourcegraph's <a href="https://docs.sourcegraph.com/cody/explanations/code_graph_contex
```suggestion
Cody is a free, open-source AI coding assistant who writes, understands, and fixes code. Cody is powered by Sourcegraph's <a href="https://docs.sourcegraph.com/cody/explanations/code_graph_context">code graph</a> and uses knowledge of your entire codebase to give more accurate answers and generate idiomatic code.
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/overview/index.md
> +| [Autocomplete](./../capabilities.md#autocomplete)    | Cody makes context-based code autocompletions. Cody can autocomplete single lines, or whole functions, in any programming language, configurat
```suggestion
| [Autocomplete](./../capabilities.md#autocomplete)    | Cody makes context-based code autocompletions. Cody can autocomplete single lines or whole functions in any programming language, configuration file, or documentation.
```

2023-08-29 11:09 UTC, MaedahBatool commented on doc/cody/overview/index.md
> +| [Chat](./../capabilities.md#chat)    | Ask Cody questions in the chat view, or inline with code, and it will use Sourcegraph’s code graph to answer using knowledge of your codebase. |
```suggestion
| [Chat](./../capabilities.md#chat)    | Ask Cody questions in the chat view or inline with code, and it will use Sourcegraph’s code graph to answer using knowledge of your codebase. |
```

2023-08-29 14:10 UTC, iskyOS commented on doc/cody/capabilities.md
> +<p class="subtitle">Learn more about Cody's features.</p>
Yes, for sure. My goal with that change was not to overpromise the product while it's beta. I can make a new suggestion here.

2023-08-29 14:10 UTC, iskyOS commented on doc/cody/capabilities.md
> +<p class="subtitle">Learn more about Cody's features.</p>
```suggestion
<p class="subtitle">Learn and understand more about Cody's features and core AI functionality.</p>
```

2023-08-29 14:15 UTC, iskyOS commented on doc/cody/capabilities.md
> +### Configure autocomplete on Sourcegraph Enterprise
It is treated as a license/SKU name. Today it is typically capitalized, and we could reconsider that, but we should make some changes for consistency then. Here's an example of how it's used today: https://handbook.sourcegraph.com/departments/product/process/gtm/licensing

2023-08-29 14:17 UTC, iskyOS commented on doc/cody/overview/index.md
> +Cody is a free and open-source AI coding assistant that can write, understand, and fix code. Cody is powered by Sourcegraph's <a href="https://docs.sourcegraph.com/cody/explanations/code_graph_contex
Do you think it's too much personification to refer to Cody with "who" here? I don't think we've done that before

2023-08-29 14:22 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +<p class="subtitle">Learn more about Cody's features.</p>
This looks better. 👍

2023-08-29 14:24 UTC, MaedahBatool commented on doc/cody/overview/index.md
> +Cody is a free and open-source AI coding assistant that can write, understand, and fix code. Cody is powered by Sourcegraph's <a href="https://docs.sourcegraph.com/cody/explanations/code_graph_contex
Yeah, I also had second thoughts about referring to Cody as "who." I think we can use "that" instead.

2023-08-29 14:25 UTC, MaedahBatool commented on doc/cody/capabilities.md
> +### Configure autocomplete on Sourcegraph Enterprise
Having an "enterprise" aspect is pretty much a norm in the tech world. I'd suggest let's reconsider how we're naming it.

2023-08-29 15:44 UTC, iskyOS commented on doc/cody/overview/index.md
> +Cody is a free and open-source AI coding assistant that can write, understand, and fix code. Cody is powered by Sourcegraph's <a href="https://docs.sourcegraph.com/cody/explanations/code_graph_contex
```suggestion
Cody is a free, open-source AI coding assistant that writes, understands, and fixes code. Cody is powered by Sourcegraph's <a href="https://docs.sourcegraph.com/cody/explanations/code_graph_context">code graph</a> and uses knowledge of your entire codebase to give more accurate answers and generate idiomatic code.
```

2023-08-29 15:50 UTC, iskyOS commented on doc/cody/capabilities.md
> +### Configure autocomplete on Sourcegraph Enterprise
That's fair. For that kind of change, we should roll it out as a synchronized change (on docs, handbook) all together when we're ready. For now, can we rework this to avoid conflict?
```suggestion
### Configure autocomplete on an enterprise Sourcegraph instance
```

2023-08-30 11:28 UTC, MaedahBatool approved these changes
LGTM 👍

2023-08-30 18:50 UTC, merged