aspect workflows: add initial aspect workflow yaml
sourcegraph/sourcegraph pull request #56569
Opened 2023-09-13 09:24 UTC by burmudar

Initial aspect workflow config
## Test plan
aspect workflow pipeline picks this up

2023-09-13 09:42 UTC, eseliger approved these changes

2023-09-13 17:13 UTC, kormide commented on .aspect/workflows/config.yaml
> +tasks:
Above `tasks` add `queue: aspect-default`.

2023-09-14 09:06 UTC, burmudar commented on .aspect/workflows/config.yaml
> +tasks:
added!

2023-10-05 17:51 UTC, kormide commented on .aspect/workflows/config.yaml
> +        collect_coverage: false
Note that this option should be `coverage: false`.

2023-10-10 17:36 UTC, kormide commented on .aspect/workflows/config.yaml
> +        collect_coverage: false
I'm not sure if the earlier fix was reversed, but everything below `rcfiles` belongs directly under `test` rather than under `bazel`. In a future release we have some warnings when the config doesn't match the schema.

2023-10-19 12:15 UTC, keegancsmith commented on internal/httpcli/client_test.go
> +				if os.Getenv("CI") != "" {
we did this because it broke on peoples machines. Rather just always use notFoundTransport until we resolve this on CI.

2023-10-19 12:15 UTC, keegancsmith commented on dev/gqltest/sub_repo_permissions_test.go
> +	t.Skip("SKIPPED because this fails in Aspect Workflows CI")
do we have an issue tracking this? This not running seems like a footgun which may turn into a footbfg

2023-10-19 12:17 UTC, burmudar commented on dev/gqltest/sub_repo_permissions_test.go
> +	t.Skip("SKIPPED because this fails in Aspect Workflows CI")
Not yet - I'll create one soon. For now we're only trying to see what else fails and then circle back to these issues

2023-10-19 12:18 UTC, pjlast commented on dev/gqltest/sub_repo_permissions_test.go
> +	t.Skip("SKIPPED because this fails in Aspect Workflows CI")
Yep I'm looking into it here: https://github.com/sourcegraph/sourcegraph/issues/57662

2023-10-23 11:26 UTC, pjlast submitted a review, later dismissed

2023-10-27 16:17 UTC, burmudar commented on internal/httpcli/client_test.go
> +				if os.Getenv("CI") != "" {
reverted now that we have had all other tests passed so that we can focus on this

2023-11-01 16:00 UTC, jhchabran requested changes

2023-11-01 16:00 UTC, jhchabran commented on .aspect/workflows/config.yaml
> +          - //testing:codeintel_integration_test
We should put a comment here that ultimately, this should just run on `main`, that's how it is right now, but we're not handling it here. That's fine for the time being, as we're just going to compare it to `main`, but it's so easy to forget.

2023-11-01 16:00 UTC, jhchabran commented on dev/gqltest/external_service_test.go
> +	t.Skip("TEMPORARY SKIP: aspect workflows")
We should not merge that in `main`, as is at least

2023-11-01 16:01 UTC, burmudar commented on .aspect/bazelrc/BUILD.bazel
> +        "correctness",  # temporary for sanity checking: DO NOT LAND!
Dont think so, I'll remove it

2023-11-01 16:02 UTC, burmudar commented on client/shared/dev/runMochaTestsWithPercy.js
> +  if (!JS_BINARY__EXECROOT || !BAZEL_BINDIR) {
Yup, its comes from Greg's branch

2023-11-01 16:03 UTC, jhchabran commented on client/shared/dev/runMochaTestsWithPercy.js
> +  if (!JS_BINARY__EXECROOT || !BAZEL_BINDIR) {
Ack, mystery solved!

2023-11-02 11:00 UTC, burmudar commented on .aspect/workflows/config.yaml
> +    - --noexperimental_reuse_sandbox_directories
Added a comment why we still need it

2023-11-02 13:13 UTC, jhchabran commented on testing/BUILD.bazel
> +        "exclusive",
@burmudar do we still need this?

2023-11-02 13:14 UTC, burmudar commented on testing/BUILD.bazel
> +        "exclusive",
Yes, previously the varous e2e tests failed when running together. But I can do a test run to confirm

2023-11-02 13:15 UTC, jhchabran commented on testing/BUILD.bazel
> +        "exclusive",
Yeah, if you don't mind, otherwise this is going to slow things down a lot actually.

2023-11-06 16:37 UTC, burmudar commented on dev/gqltest/external_service_test.go
> +			disabled: true,
`git-p4` is a new test that was added that uses `git p4` ... it timed out on aspect-workflows. After consulting with @pjlast I disabled it since the `p4 fusion` covers perforce

cc @jhchabran

2023-11-09 09:43 UTC, burmudar commented on client/branded/BUILD.bazel
> +        "//:postcss_config_js",
This is needed otherwise the tests fails with `cannot find module "autoprefixer"` which is a dep of `postcss_config_js`

2023-11-22 15:15 UTC, jhchabran commented on client/web/src/end-to-end/frontend-platform/theme-switcher.test.ts
> +describe.skip('Theme switcher', () => {
TODO comment

2023-11-22 15:15 UTC, jhchabran approved these changes

2023-11-22 16:28 UTC, burmudar commented on client/web/src/end-to-end/frontend-platform/theme-switcher.test.ts
> +describe.skip('Theme switcher', () => {
Added

2023-11-22 17:56 UTC, gregmagolan commented on WORKSPACE
> +    strip_prefix = "bazel-lib-1.37.0",
I recommend pre-factoring the upgrade to the latest 1.x bazel-lib (v1.38.1) and the corresponding changes to `.aspect/bazelrc/*`. Landing those ahead of time will make it easier to identify which changes created breakages in the non-workflows pipelines or with local development workflows if any come up.

2023-11-22 17:56 UTC, gregmagolan commented on WORKSPACE
> +    strip_prefix = "bazel-lib-1.37.0",
https://github.com/aspect-build/bazel-lib/releases/tag/v1.38.1

2023-11-22 17:58 UTC, gregmagolan commented on client/shared/dev/runMochaTestsWithPercy.js
> +  const { JS_BINARY__EXECROOT, BAZEL_BINDIR } = process.env
Changes in this file would also be good to pre-factor since they are non-determinism fixes which can stand on their own.

2023-11-22 17:59 UTC, gregmagolan commented on dev/mocha.bzl
> -            stamp = 1,
This goes along with the non-determinism fix above in `runMochaTestsWithPercy.js`

2023-11-22 18:36 UTC, gregmagolan commented on .aspect/workflows/config.yaml
> +          # TODO(burmudar): Let this only run on main branch
Hmm. We don't have a built-in way to select different target for different branches at the moment. We'll think about the best way to support a use case like that.

2023-11-22 18:55 UTC, gregmagolan commented on client/web/src/integration/BUILD.bazel
> -    is_percy_enabled = True,
Looks like this line snuck in from testing. Should remove it and set `is_percy_enabled = True` here and ensure CI is still passing for this test. I'll leave it out of the prefactor.

2023-11-22 19:00 UTC, gregmagolan commented on cmd/embeddings/shared/BUILD.bazel
> -    allow_symlink = True,
I don't recall making this change or why it would be needed. Was this in your testing @burmudar ?

2023-11-22 19:02 UTC, burmudar commented on cmd/embeddings/shared/BUILD.bazel
> -    allow_symlink = True,
I ... have no idea either. This didn't fail at some point for me to start debugging it 😅 I'll look when it got in

2023-11-22 19:28 UTC, gregmagolan commented on client/web/BUILD.bazel
> +    tags = ["exclusive"],
Was this one necessary or just left over from testing?

2023-11-22 19:28 UTC, gregmagolan commented on cmd/embeddings/shared/BUILD.bazel
> +        "exclusive",
Was this one necessary or just left over from testing?

2023-11-22 19:29 UTC, gregmagolan commented on internal/httpcli/client_test.go
> +				cli.Transport = notFoundTransport{}
Can be undone now after the Cloud NAT fix or is this related to DNS somehow?

2023-11-23 04:53 UTC, burmudar commented on internal/httpcli/client_test.go
> +				cli.Transport = notFoundTransport{}
This is related to DNS. I re-retried it with the Cloud NAT fix but it still failed. 

My suspicion is that we're using systemd-resolved and NetworkManager in the image. So need to disable NetworkManager and let everything be handled with systemd.

2023-11-23 08:04 UTC, burmudar commented on client/web/BUILD.bazel
> +    tags = ["exclusive"],
I added this recently since it is effectively what we do now on our pipeline. We build `//client/web:bundle` before all targets because it is resource intensive. So figured I could get the same effect by making it exclusive here.

2023-11-23 08:04 UTC, burmudar commented on cmd/embeddings/shared/BUILD.bazel
> +        "exclusive",
I think this is a leftover from testing as it was failing more often than not. I'll remove it and test

2023-11-23 15:37 UTC, gregmagolan commented on .aspect/workflows/config.yaml
> +    CI: "true"
CI should already be set to "1" by BUILDKITE

2023-11-23 15:39 UTC, gregmagolan commented on .aspect/workflows/config.yaml
> +    PGUSER: postgres
nit: These look unnecessary since you're already setting the env vars in the `.bazelrc` explicilty,

```
build --test_env=PGUSER=postgres
build --test_env=PGPASSWORD=postgres
build --test_env=PGSSLMODE
build --test_env=PGDATABASE=postgres
```

You could also set `build --test_env=PGSSLMODE=disable` in `.bazelrc` and you should be able to remove all of the `PG*` envs from here

2023-11-23 15:40 UTC, gregmagolan commented on .aspect/workflows/config.yaml
> +    PGUSER: postgres
Ohhh.. the ones in `.bazelrc` should be `test --test_env=...` tho so they apply to the `bazel test` command :)

2023-11-23 15:48 UTC, gregmagolan commented on client/web/src/end-to-end/BUILD.bazel
> +        "GH_TOKEN": "$(GH_TOKEN)",
Hmm. Looking at `mocha.bzl`, the addition of `"GH_TOKEN": "$(GH_TOKEN)",` looks redundant and unnecessary here since it is added automatically the env in `mocha.bzl`. Looks like I added this one by mistake.

2023-11-23 15:49 UTC, gregmagolan commented on .aspect/workflows/config.yaml
> +queue: aspect-default
`aspect-default` is the default queue so this line can be removed :)

2023-11-23 15:49 UTC, gregmagolan commented on .aspect/workflows/config.yaml
> +        update_strategy: rebase
nit: rebase strategy is default as well so the whole `branch_freshness` block can be removed if you prefer a shorter config

2023-11-23 15:50 UTC, gregmagolan commented on .aspect/workflows/config.yaml
> +    # gazelle:
I'll put up a PR to enable the gazelle: check after this PR lands

2023-11-23 16:02 UTC, gregmagolan commented on .aspect/bazelrc/ci.sourcegraph.bazelrc
> +test --test_env=PGSSLMODE
I think you need
```
test --test_env=PGSSLMODE=disable
```
to be equivalent to what you had set in `env`

2023-11-24 09:52 UTC, merged