Push VS Cody install events to HubSpot
sourcegraph/sourcegraph pull request #56669
Opened 2023-09-15 07:01 UTC by thenamankumar

closes part of https://github.com/sourcegraph/cody/issues/954

## Test plan

2023-09-15 09:00 UTC, vdavid approved these changes
Makes sense

2023-09-15 14:01 UTC, dadlerj requested changes

2023-09-15 14:01 UTC, dadlerj commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
I would not send a second (and sort of duplicative) custom HubSpot event here. Instead, we should log the IDE being used as a user-level property in the call on line 163 in this file above (and you can log the new `VSCodyInstalledEmailsEnabled: emailsEnabled,` property there as well).

2023-09-15 17:26 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
I am not sure how HubSpot work, but Isn't ContactProperty saved per user and not per event?

If it is stored separately per event, then it makes sense and I'll do it. 

@Shannonking456 can you confirm?

2023-09-18 16:09 UTC, dadlerj commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
Thanks! The contact property **is** stored per user, but HubSpot has a timeline of changes and you can see which event caused which property to change.

That said, I'm not sure I understand why that would matter for this change? The property will be stored per user regardless of which event it was associated with, right?

2023-09-18 16:18 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
Hey @dadlerj, I checked with Shannon. Properties get overridden by each future event. I think it is better to send separate events to HubSpot otherwise each CodyInstall event will override the IDE property.

2023-09-18 16:26 UTC, dadlerj commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
Thank you! I don't understand, though—why would that affect sending two events, versus sending a single event that conditionally includes the property?

2023-09-18 16:35 UTC, dadlerj commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
I don't mean to create a pain here, and if you strongly prefer this, that's fine... I just figured this would be cleaner (in the code and in HubSpot) :shrug:.

2023-09-21 10:52 UTC, thenamankumar commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
I talked to a few people from HubSpot, and I have updated it to pass additional props to the CodyInstall event itself.

Though event props are different from contact properties. 

I'll merge and test this out.

2023-09-21 17:23 UTC, dadlerj commented on cmd/frontend/graphqlbackend/user_usage_stats.go
> +				hubspotutil.SyncUser(userPrimaryEmail, hubspotutil.VSCodyInstalledEventID, &hubspot.ContactProperties{
Understood thanks!

2023-09-22 16:15 UTC, dadlerj approved these changes

2023-09-25 13:27 UTC, merged