e2e tst: add actions to create github teams
sourcegraph/sourcegraph pull request #56777
Opened 2023-09-19 14:54 UTC by burmudar

add actions to create github teams and assign users to those teams. Also
added actions to remove added teams.

## Test plan
tested in wb/e2e/poc

2023-09-19 14:54 UTC, burmudar commented
Current dependencies on/for this PR:
* main
  * **PR #56774** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56774" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #56775** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56775" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #56776** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56776" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #56777** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56777" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56777?utm_source=stack-comment).

2023-09-20 11:58 UTC, jhchabran requested changes

2023-09-20 11:58 UTC, jhchabran commented on dev/tst/github_client.go
> +	team, resp, err := gh.c.Teams.GetTeamBySlug(ctx, org.GetLogin(), name)
Same thing as in the previous PR, regarding the errors

2023-09-20 11:58 UTC, jhchabran commented on dev/tst/store.go
> +	// Store it twice so we have two ways of retrieving a team
I'm not sure to understand why we need this

2023-10-05 10:13 UTC, jhchabran commented on dev/codehost_testing/team.go
> +	panic("cannot retrieve org before scenario is applied")
`t.Fatal` ?

2023-10-09 16:35 UTC, jhchabran approved these changes

2023-10-10 12:33 UTC, merged