e2e test: define base tst framework for easier scenario setup
sourcegraph/sourcegraph pull request #56774
Opened 2023-09-19 14:53 UTC by burmudar

Defines the base framework for easier e2e test scenario setup.

## Test plan
Tested in wb/e2e/poc branch

2023-09-19 15:23 UTC, burmudar commented on dev/tst/action.go
> +func (m *actionRunner) Apply(ctx context.Context, store *ScenarioStore, actions []Action, failFast bool) error {
The aim ultimately is to build a graph out of actions and do a topological sort. Actions currently have a passive dependency on other actions. Like most actions require the github org to exist. If we have actions declare their dependencies explicitly that will enable us to build a graph. By having a graph, there is no particular order in which actions have to be called since the graph approach will figure out the right order.

2023-09-29 15:37 UTC, burmudar commented on dev/tst/BUILD.bazel
> +    name = "tst",
renamed it  to `codehost_scenario` ... but think I'll rename it again to be more explicit to testing, as you mentioned `codehost_testing`

2023-10-05 10:03 UTC, jhchabran requested changes
Well done, and nice documentation 😊! There are two things that should be addressed: 

- one missing deferred close 
- unclear semantics on the action index or it's an off by one.

2023-10-05 10:03 UTC, jhchabran commented on dev/codehost_testing/scenario.go
> +	return s.appliedActionIdx >= len(s.actions)
Judging by its name, `appliedActionIdx`, I would expect the value to be `3` if we have 4 actions for example, effectively pointing as the last element that was applied. 

But the code here suggests otherwise, which hints that `appliedActionIdx` points at the next non applied element instead of the last one that was applied. 

So, we're off by one or the naming is incorrect?

2023-10-05 11:50 UTC, pjlast commented on dev/codehost_testing/util.go
> +}
Fun fact: the `github` package you're importing has helpers for these: https://pkg.go.dev/github.com/google/go-github/github#String

2023-10-05 11:51 UTC, pjlast commented on dev/codehost_testing/scenario.go
> +type GithubScenario struct {
```suggestion
type GitHubScenario struct {
```

Consistent capitalization 🙏

2023-10-06 09:42 UTC, burmudar commented on dev/codehost_testing/github_client.go
> +		return nil, errors.Newf("failed to create org %q - %s", name, respErr)
This is actually just bad naming. `githubResponseErr` just formats the msg for use in an error. I have since renamed it

2023-10-08 11:39 UTC, burmudar commented on dev/codehost_testing/scenario.go
> +	return s.appliedActionIdx >= len(s.actions)
Renamed and added a test

2023-10-09 07:29 UTC, burmudar commented on dev/codehost_testing/github_client.go
> +// It is recommended that the configered token passed to the client has the following scopes:
Added README in this PR https://github.com/sourcegraph/sourcegraph/pull/56779

2023-10-09 16:33 UTC, jhchabran approved these changes

2023-10-09 16:33 UTC, jhchabran commented on dev/codehost_testing/scenario.go
> +// * create a GitHub User, which returns a codehost_scenario User
need to be updated

2023-10-09 16:33 UTC, jhchabran commented on dev/codehost_testing/scenario.go
> +	append(a ...*action)
public?

2023-10-10 14:30 UTC, merged