e2e tst: add actions to create github users
sourcegraph/sourcegraph pull request #56776
Opened 2023-09-19 14:53 UTC by burmudar

add actions to create github users and also remove created users.

note: we cannot create admins so instead of search and map a user to the
Admin user

## Test plan
tested in wb/e2e/poc

2023-09-20 11:56 UTC, jhchabran requested changes

2023-09-20 11:56 UTC, jhchabran commented on dev/tst/github_client.go
> +	user, resp, err := gh.c.Admin.CreateUser(ctx, name, email)
From the godocs: 

> When err is nil, resp always contains a non-nil resp.Body. Caller should close resp.Body when done reading from it. 

We need to close `resp.Body` regardless of the status code if there's no error

2023-09-20 11:56 UTC, jhchabran commented on dev/tst/github_client.go
> +	if resp.StatusCode >= 400 {
If there's an error on the transport layer, the underlying HTTP Get will return an error and a nil response, which will panic here. We can't skip checking `err`

2023-09-20 11:56 UTC, jhchabran commented on dev/tst/users.go
> +var Admin GitHubScenarioUser = *NewGitHubScenarioUser("admin")
What is this about?

2023-09-20 12:58 UTC, burmudar commented on dev/tst/users.go
> +		name = client.cfg.User
should be `client.cfg.AdminUser`

2023-09-29 15:20 UTC, burmudar commented on dev/tst/github_client.go
> +	user, resp, err := gh.c.Admin.CreateUser(ctx, name, email)
Fixed

2023-09-29 15:21 UTC, burmudar commented on dev/tst/users.go
> +		name = client.cfg.User
Fixed

2023-09-29 15:21 UTC, burmudar commented on dev/tst/users.go
> +var Admin GitHubScenarioUser = *NewGitHubScenarioUser("admin")
no longer relevant

2023-10-09 16:38 UTC, jhchabran approved these changes
pre-approving to unblock

2023-10-09 17:35 UTC, burmudar commented on dev/codehost_testing/scenario.go
> +	baseUser := &User{
Fixed

2023-10-10 08:05 UTC, burmudar commented on dev/codehost_testing/scenario.go
> +			email := "test-user-e2e@sourcegraph.com"
Good catch - yes this caused an issue. It is fixed now. Tested by adding another user and adding a unique email id

2023-10-10 12:41 UTC, merged