e2e tst: add actions to create github org
sourcegraph/sourcegraph pull request #56775
Opened 2023-09-19 14:53 UTC by burmudar

Add actions to create github org and also to tear it down

## Test plan
tested in wb/e2e/poc

2023-09-19 14:53 UTC, burmudar commented
Current dependencies on/for this PR:
* main
  * **PR #56774** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56774" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #56775** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56775" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/56775?utm_source=stack-comment).

2023-09-20 11:49 UTC, jhchabran requested changes

2023-09-20 12:33 UTC, burmudar commented on dev/tst/github_client.go
> +		io.Copy(os.Stdout, resp.Body)
Ah good catch!

2023-09-29 15:20 UTC, burmudar commented on dev/tst/github_client.go
> +		io.Copy(os.Stdout, resp.Body)
Fixed

2023-10-05 10:06 UTC, jhchabran commented on dev/codehost_testing/org.go
> +	panic("cannot retrieve org before scenario is applied")
What about doing a `t.Fatal` instead, as we can get `t` through the scenario.

2023-10-05 10:06 UTC, jhchabran commented on dev/codehost_testing/org.go
> +
```suggestion
```

2023-10-05 10:06 UTC, jhchabran commented on dev/codehost_testing/scenario.go
> +			fmt.Printf("Visit %q to delete the org\n", deleteURL)
I was about to suggest using `t.Log` but that would have the unfortunate consequence of hiding this message if we're not running tests in verbose mode.

2023-10-06 09:19 UTC, burmudar commented on dev/codehost_testing/org.go
> +	panic("cannot retrieve org before scenario is applied")
Yeah I think that would be much better

2023-10-06 12:04 UTC, jhchabran approved these changes

2023-10-10 12:50 UTC, merged