Add MATLAB search-based code navigation
sourcegraph/sourcegraph pull request #56800
Opened 2023-09-19 21:41 UTC by SuperAuguste

Closes #56373

## Test plan

2023-09-22 18:29 UTC, SuperAuguste commented
I was forced to add tree-sitter highlighting as the local code nav must be enabled through `scip-syntax` :)

2023-09-22 22:39 UTC, varungandhi-src commented
> I was forced to add tree-sitter highlighting as the local code nav must be enabled through scip-syntax :)

Could you elaborate on this with links to the relevant code?

At the moment, IIUC, the enhanced local code navigation based on tree-sitter is turned on for Perl and Go.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/syntax-highlighter/crates/scip-syntax/src/languages.rs?L285-286

The list of languages for which we use tree-sitter for highlighting doesn't include Perl.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/syntax-highlighter/crates/scip-syntax/src/languages.rs?L230-242

Am I misunderstanding something? Why is there a coupling between syntax highlighting and local code nav? Sure, they both use tree-sitter, but it seems weird if your point is that adding queries for one also requires adding queries for another.

2023-09-22 22:41 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +pub enum DefinitionStrength {
Please add doc comments for this type and the cases.

I understand that the existing code barely has any doc comments, but let's not continue that if multiple people are to work on this code.

2023-09-22 23:21 UTC, SuperAuguste commented
@varungandhi-src I'm not sure either, I just followed the format of other PRs adding the same features. As far as I can tell, they're interlinked, but thanks for pointing the Perl thing out. I'll take a look.

2023-09-22 23:24 UTC, varungandhi-src commented
> I'm not sure either, I just followed the format of other PRs adding the same features

Could you link to the other PRs which you followed?

2023-09-22 23:33 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.m
> +% Copyright (c) 2021-2022, The MathWorks, Inc.
Please rewrite this test case.

The main things of interest are:

1. Global variables (if possible, at different levels of scope)
2. Local variables at different levels of scope
3. Persistent variables (equivalent of static in C)
4. Handling for different forms of `clear`. https://www.mathworks.com/help/matlab/ref/clear.html (maybe cover some basic forms and list out the unhandled forms in a FIXME comment)
5. Function parameters
6. Anonymous function parameters
7. Captured variables used in anonymous functions

While this test case was useful for language detection, it is unsuitable for testing local code navigation, because the snapshot output is too big and has a high degree of redundancy.

2023-09-23 01:55 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.m
> +% Copyright (c) 2021-2022, The MathWorks, Inc.
Right; I was not planning on keeping this for the final release. Thanks for the list of lang features to track!

2023-09-23 01:57 UTC, SuperAuguste commented
> Could you link to the other PRs which you followed?

https://github.com/sourcegraph/sourcegraph/pull/49931 :)

2023-10-02 15:33 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +                    todo!("I'm not sure what to do yet, think more now (is a scope with the same range being recorded twice?)");
Unsure; we could probably just turn this into a comment to make it non-dangerous as this is a rare and, as far as I can tell, not very useful case.

2023-10-03 19:49 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.m
> +% Copyright (c) 2021-2022, The MathWorks, Inc.
Hmm `clear` is going to take a bunch more work, if we want to get this in ASAP (before release) it'll have to be a TODO, otherwise I can take a jab at it.

2023-10-05 16:14 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +                    eprintln!("TODO: I'm not sure what to do yet, think more now (is a scope with the same range being recorded twice?)");
Please add some contextual information to this print line. Otherwise, if this shows up in a log, it will be hard to understand what exactly is going on.

2023-10-05 16:24 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +    // let mut weak_definitions = vec![];
nit: Please delete stray comments

2023-10-05 16:25 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +                            Some(other) => panic!("unknown definition strength: {}", other),
nit: This should be `unreachable!`

2023-10-05 16:28 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +                            None => {}
Why is `None` allowed here? Should it also be `unreachable!`? If one wants the default behavior, then one doesn't need to specify the `#set! "strength"` in the first place.

2023-10-05 16:32 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.m
> +% TODO handle clear
Was this TODO meant for this PR or for some indeterminate point in the future? If it's meant as a future thing, then please file a GitHub issue and link that here.

2023-10-05 16:33 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +                            // syntax_kind: todo!(),
nit: Stray comment (and similarly one above)

2023-10-05 16:37 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_matlab.snap
> +//         ^ definition local 3
This seems buggy -- global variables shouldn't be getting local symbol names.

2023-10-05 16:39 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/testdata/locals.m
> +% TODO handle clear
Just saw your response elsewhere, please file a follow-up issue for `clear` in that case and link that here.

2023-10-05 16:55 UTC, varungandhi-src requested changes
Please don't merge this as-is, we should not be cloning any scope-related hash maps during name lookup.

2023-10-05 21:16 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +        let mut declarations_above = declarations_above.clone();
Good call :)

2023-10-05 21:26 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +pub enum DefinitionStrength {
What about `Assignment`? Regardless, I don't really want to rewrite this much of scip-locals in this PR, this seems like a better fit for a large/few small refactoring PRs (nomenclature issues also present in globals and symbols + we could probably reconcile all three of these tree-sitter indexing methods as well as some more refactoring opportunities)

2023-10-05 21:42 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_matlab.snap
> +//         ^ definition local 3
Agreed, though this seems to be the bar we've set, see [this Go snapshot](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go.snap). I'm happy to open a tracking issue about this though. :)

2023-10-05 23:39 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +pub enum DefinitionStrength {
Generally, "assignment" refers to the full thing:

```
a = b
```

`a` is an lvalue, `b` is an rvalue, and the statement is an assignment statement or expression.

So calling `a` "assignment" would be incorrect.

> Regardless, I don't really want to rewrite this much of scip-locals in this PR

This PR is adding a new type. My main point was that you rename that to something more standard.

Unless I'm missing something, the "extra" stuff that's involved here is renaming one more type (the `Definition` type). I'm fine if you don't want to rename that in this PR, but we should fix that regardless because it's just plain confusing.

> nomenclature issues also present in globals and symbols + we could probably reconcile all three of these tree-sitter indexing methods as well as some more refactoring opportunities

I don't know what you're referring to here but if there's known problems, it would be nice to at least document those in a GitHub issue or somewhere central in the code.

2023-10-06 14:19 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +pub enum DefinitionStrength {
> So calling a "assignment" would be incorrect.

Yes, but what about calling the enum "ReassignmentBehavior", I think that would make the most sense. I agree with the Definition -> LValue rename, though.

2023-10-06 14:33 UTC, SuperAuguste commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_matlab.snap
> +//         ^ definition local 3
Issue opened: https://github.com/sourcegraph/sourcegraph/issues/57419

2023-10-06 18:59 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/locals.rs
> +        declarations_above.pop();
Could you add a test case for re-assignment within the same scope?

```
a = 10
a = 20
```

It's not obvious to me that the current pushing/popping logic will actually cause a reference to be emitted for the second one.

And add a test for code like this:

```
function f()
  if false
    a = 1;
  else
    a = 2;
  end
  disp(a);
end
```

Ideally, we should be emitting two definitions here and a single reference.

2023-10-06 19:42 UTC, varungandhi-src approved these changes
Approving based on convo over Zoom. We can do more refactoring here later.

2023-10-06 21:54 UTC, merged