add docs for recorded commands
sourcegraph/sourcegraph pull request #56944
Opened 2023-09-22 10:38 UTC by BolajiOlajide

Closes [#56682](https://github.com/sourcegraph/sourcegraph/issues/56682)

## Test plan

Added docs.

2023-09-22 17:29 UTC, MaedahBatool requested changes
I am leaving a few comments. 👍

2023-09-22 17:29 UTC, MaedahBatool commented on doc/admin/repo/recording.md
> +1. Go to Site Admin > Site Configuration
```suggestion
- Go to Site Admin > Site Configuration
```

2023-09-22 17:29 UTC, MaedahBatool commented on doc/admin/repo/recording.md
> +1. Go to Site Admin > Site Configuration
Can we please use bullets instead? 🙏

2023-09-22 17:29 UTC, MaedahBatool commented on doc/admin/repo/recording.md
> +2. Add a `gitRecorder` object to the configuration object
```suggestion
- Add a `gitRecorder` object to the configuration object
```

2023-09-22 17:29 UTC, MaedahBatool commented on doc/admin/repo/recording.md
> +Recorded commands include information like start time, duration, exit status, command executed, directory, and output. Sensitive information like usernames, passwords, tokens are automatically redact
```suggestion
Recorded commands include information like start time, duration, exit status, command executed, directory, and output. Sensitive information like usernames, passwords, and tokens are automatically redacted from the command and output.
```

2023-09-22 17:29 UTC, MaedahBatool commented on doc/admin/repo/recording.md
> +### Potential Risks
```suggestion
### Potential risks
```
We don't title case the headings if they are not product names.

2023-09-22 17:29 UTC, MaedahBatool commented on doc/admin/repo/recording.md
> +Depending on the number of repositories and size of the recording set, enabling command recording could result in increased disk usage in Redis.
```suggestion
Depending on the number of repositories and size of the recording set, enabling command recording could increase disk usage in Redis. 
```

2023-09-22 17:29 UTC, MaedahBatool commented on doc/admin/repo/recording.md
> +When Redis is full, it may start evicting data which can impact other parts of Sourcegraph that rely on Redis. Sourcegraph may experience degraded performance or instability.
```suggestion
When Redis is full, it may start evicting data, impacting other parts of Sourcegraph that rely on Redis. Sourcegraph may experience degraded performance or instability.
```

2023-09-23 16:57 UTC, mrnugget requested changes

2023-09-23 16:57 UTC, mrnugget commented on doc/admin/repo/recording.md
> +- Go to Site Admin > Site Configuration
I think we should link to the doc page, see: https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:doc+content:%22site_config.md%29%22&patternType=standard&sm=0&groupBy=path

2023-09-23 16:57 UTC, mrnugget commented on doc/admin/repo/recording.md
> +```
Can we make this a valid JSON object so it renders without errors?

```suggestion
```jsonc
{
  // [...]

  "gitRecorder": {
      // the amount of commands to record per repo  
      "size": 30,
    
      // repositories to record commands. This can either be a wildcard '*' 
      // to record commands for all repositories or a list of repositories
      "repos": ["*"],
    
      // git commands to exclude from recording. We exclude the 
      // commands below by default.
      "ignoredGitCommands": [
        "show",
        "rev-parse",
        "log",
        "diff",
        "ls-tree"
      ]
   }
}
```
```

I think you can also use `jsonc` here. (See: https://sourcegraph.sourcegraph.com/search?q=context:sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:doc+jsonc&patternType=standard&sm=0&groupBy=path)

2023-09-23 16:57 UTC, mrnugget commented on doc/admin/repo/recording.md
> +Command recording allows site admins to view all git operations executed on a repository.
Would be great to have a screenshot here. It would explain a lot of the other things here.

2023-09-23 16:57 UTC, mrnugget commented on doc/admin/repo/recording.md
> +This provides visibility into git operations performed by Sourcegraph on a repository, which can be useful for debugging and monitoring.
Does it also include Perforce? Or not at all? I think we should explicitly call this out.

2023-09-23 16:57 UTC, mrnugget commented on doc/admin/repo/recording.md
> +Depending on the number of repositories and size of the recording set, enabling command recording could increase disk usage in Redis.
I'm pretty sure it will increase disk usage, not just "could" :) I think the thing to call out here is that it could significantly change disk usage, which you do in the 2nd paragraph. So I'd combine them.

2023-09-23 16:57 UTC, mrnugget commented on doc/admin/repo/recording.md
> +When Redis is full, it may start evicting data, impacting other parts of Sourcegraph that rely on Redis. Sourcegraph may experience degraded performance or instability.
I'd add something like "Depending on your configuration"

2023-09-25 19:05 UTC, BolajiOlajide commented on doc/admin/repo/recording.md
> +Depending on the number of repositories and size of the recording set, enabling command recording could increase disk usage in Redis.
Gotcha.

2023-09-25 19:05 UTC, BolajiOlajide commented on doc/admin/repo/recording.md
> +- Go to Site Admin > Site Configuration
Done.

2023-09-26 13:25 UTC, MaedahBatool approved these changes
LGTM 👍

2023-09-26 13:44 UTC, mrnugget approved these changes

2023-09-26 13:46 UTC, merged