[OCT Launch] Cody Client: Docs updates for JetBrains
sourcegraph/sourcegraph pull request #56991
Opened 2023-09-24 16:44 UTC by MaedahBatool

This PR adds docs updates for the Cody Client — JetBrains extension.

- Adds the `Beta` tag and removes the `Experimental` status
- Adds details for autocompletion
- Adds details for embeddings
- Share info about user onboarding with what log in options a user gets

## Test plan

Docs added.

2023-09-25 16:18 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +For **free** users, installing the JetBrains extension prompts installing the Cody app for better responses with embeddings. Enterprise users are guided to contact their admin for embeddings.
For October 4th, we are not going to support the App integration for the JetBrains plugin.

2023-09-25 16:18 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +For **free** users, installing the JetBrains extension prompts installing the Cody app for better responses with embeddings. Enterprise users are guided to contact their admin for embeddings.
We still support embeddings for

- Free users on OSS repos on sourcegraph.com that have embeddings
- Paid users for enterprise instances

2023-09-25 16:18 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +By default, the autocomplete feature is disabled for read-only files but is compatible with [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim).
> disabled for read-only files

I don't think it's necessary to mention this. I would just focus on compatibility with IdeaVim

2023-09-25 21:39 UTC, taylorsperry approved these changes
I think it would be valuable to add the complete list of JetBrains IDEs that are supported by this plugin. @olafurpg would you be able to supply that list?

2023-09-25 21:39 UTC, taylorsperry commented on doc/cody/overview/install-jetbrains.md
> +You can also override automatic “codebase detection” by manually setting up the codebase.
I feel like you've said you're not super keen on lots of screen shots/images, but we've seen a couple users who were confused about how to do this. I think we should either add instruction (something like, "Cody is pretty good at inferring the codebase context based on the project open in your workspace, but if you can override it by clicking on the repo name below Cody chat and adding the Git URL") or provide a screenshot. 
<img width="640" alt="Screenshot 2023-09-25 at 3 29 30 PM" src="https://github.com/sourcegraph/sourcegraph/assets/43555476/51581265-527b-4580-934f-07bbf0da4ca6">

2023-09-25 21:39 UTC, taylorsperry commented on doc/cody/overview/install-jetbrains.md
> +By default, the autocomplete feature is disabled for read-only files but is compatible with [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim).
Maybe also add that you can manually trigger a completion with Option+\ (or Alt+\)? And clarify that you can customize completion colors within the settings.

2023-09-25 22:24 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +You can also override automatic “codebase detection” by manually setting up the codebase.
I agree it's a good idea to include a screenshot for this specific use-case since it has come up many times. 

@taylorsperry judging by your screenshot, you are already running an outdated version because the embedding status icon is not an button anymore 
![CleanShot 2023-09-25 at 18 23 37@2x](https://github.com/sourcegraph/sourcegraph/assets/1408093/2dc93581-6c1c-4102-a084-d972d511aa3a)

2023-09-26 13:38 UTC, MaedahBatool commented on doc/cody/overview/install-jetbrains.md
> +For **free** users, installing the JetBrains extension prompts installing the Cody app for better responses with embeddings. Enterprise users are guided to contact their admin for embeddings.
Noted removing the irrelevant details.

2023-09-26 13:42 UTC, MaedahBatool commented on doc/cody/overview/install-jetbrains.md
> +By default, the autocomplete feature is disabled for read-only files but is compatible with [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim).
@taylorsperry can you once again confirm the shortcut? It's `Option+\` (for macOS) or `Alt+\` (for Windows) right?

2023-09-26 13:43 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +By default, the autocomplete feature is disabled for read-only files but is compatible with [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim).
@MaedahBatool Correct. We register a shortcut for `alt BACK_SLASH`, which is option+\ on macOS

2023-09-26 16:10 UTC, taylorsperry commented on doc/cody/overview/install-jetbrains.md
> +You can also override automatic “codebase detection” by manually setting up the codebase.
The one Olaf shared above is current :)

2023-09-27 15:55 UTC, olafurpg requested changes

2023-09-27 15:55 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +![override-codebase-context](https://storage.googleapis.com/sourcegraph-assets/Docs/override-context.png)
Here is another screenshot that highlights the button the user should click on. The current screenshot highlights the icon, which is not clickable.

![CleanShot 2023-09-27 at 11 39 02@2x](https://github.com/sourcegraph/sourcegraph/assets/1408093/be82a657-9aae-4bc8-afa1-11ae968881dd)

2023-09-27 15:55 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +## Autocomplete
This section needs restructuring IMO. It would be good to capture the following details:

- Basics: autocomplete suggestions appear as inlay hints. Press `Alt-Backslash` (macOS `Option-Backslash`) to manually trigger autocomplete. Press `Tab` to accept a suggestion and `Escape` to reject it.
- Automatic trigger: autocomplete is automatically triggered by default. You can optionally disable the automatic trigger through the Cody icon in the status bar or in Cody settings.
- Autocomplete color: by default, autocomplete hints use the same color as inline parameter hints according to your configured theme. You can optionally customize this color in the Cody settings.

2023-09-27 15:55 UTC, olafurpg commented on doc/cody/overview/install-jetbrains.md
> +You can manually trigger autocomplete suggestions by pressing `Option+\` (for macOS) or `Alt+\` (for Windows) and its also compatible with [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim).
We can remove the mention of IdeaVim. Users take it for granted that it works with IdeaVim, it's not a feature we have to call out.

2023-09-27 19:19 UTC, MaedahBatool commented on doc/cody/overview/install-jetbrains.md
> +You can manually trigger autocomplete suggestions by pressing `Option+\` (for macOS) or `Alt+\` (for Windows) and its also compatible with [IdeaVim](https://plugins.jetbrains.com/plugin/164-ideavim).
Noted 👍

2023-09-27 20:25 UTC, taylorsperry approved these changes
LGTM! Thank you!

2023-09-27 20:52 UTC, olafurpg approved these changes
LGTM 👍🏻 This is great!

2023-09-27 20:52 UTC, merged