Code Navigation: trim last line from content in CodeMirrorBlob
sourcegraph/sourcegraph pull request #57815
Opened 2023-10-23 17:42 UTC by jasonhawkharris

Before, an empty line appeared in the CodeMirrorBlob. Most editors ignore/hide this line. CodeMirrorBlob now hides it too. 

## Test plan
Tested manually
1. Visual test on multiple files.

2023-10-23 18:25 UTC, camdencheek commented on client/web/src/repo/blob/CodeMirrorBlob.tsx
> +            const state = EditorState.create({ doc: trimmedContent, extensions })
Nice! Glad to see it was straightforward. Two things: 
1) I don't think we want to trim all whitespace. For example, we want to maintain the extra lines if there are actually mutliple empty lines at the end of the file. I think we can just trim the last character if it is a newline character.
2) Can we add a comment explaining why this is necessary?

2023-10-23 19:01 UTC, camdencheek commented on client/web/src/repo/blob/CodeMirrorBlob.tsx
> +            const trimmed = blobInfo.content.slice(0, -1)
Files don't _have_ to end in a newline, it's just that most do. So, if the last character is not a newline, we don't want to remove it, otherwise we'll be removing actually useful parts of the content. I think this should only trim if the last character is a newline.

2023-10-23 23:06 UTC, camdencheek commented on client/web/src/repo/blob/codemirror/utils.ts
> +    const lastLineIsNewLine = /\n|\r$/
A newline is usually either `\n` or `\r\n` (on Windows), so I wouldn't ever expect the last character to be `\r`. Maybe just something like `content.replace(/\r?\n$/, '')`?

2023-10-24 06:07 UTC, fkling requested changes
In general I'd avoid modifying the file content in any way. It just feels wrong to me.

It's possible to use a [replace decoration ](https://codemirror.net/docs/ref/#view.Decoration^replace)to hide the last line.

However there are a couple of additional things to consider IMO:

- Some tools show an indicator when there is no trailing new line, e.g. git shows `\ No newline at end of file`, `cat` shows a `%`. Not sure if it's necessary, but it seems reasonable to do something similar (after all how would you know whether there is a trailing new line or not?). I wonder what GH/GL do.
- How are files rendered that literally only contain a line break? Or only line breaks?

2023-10-24 14:00 UTC, jasonhawkharris commented on client/web/src/repo/blob/codemirror/utils.ts
> +    const lastLineIsNewLine = /\n|\r$/
oh wow. Good call. That makes it one line.

2023-10-26 15:51 UTC, fkling approved these changes
Nice! Accepting to unblock, but I'd appreciate it if you moved this into its own module.

2023-10-26 15:51 UTC, fkling commented on client/web/src/repo/blob/CodeMirrorBlob.tsx
> +        const decoReplace = Decoration.replace({}).range(lastLine.from - 1, lastLine.from)
You could move the `Decoration.replace({})` part outside of the callback, since it will always be the same. You can give then give it a meaningful name too.
I'd also add a comment explaining why we do `lastLine.from - 1`.

2023-10-26 15:51 UTC, jasonhawkharris commented
For files that don't end with a new line, this message will be displayed at the bottom of the blob without a line number:
![Screenshot 2023-10-26 at 10 40 39 AM](https://github.com/sourcegraph/sourcegraph/assets/62355966/db14480b-569b-4bad-91a5-4fe3883e5a3c)
This is the same convention that `git` uses.

2023-10-27 08:57 UTC, taiyab commented
@jasonhawkharris All good Jason. I think that you've done is great 👍

2023-10-27 08:58 UTC, taiyab approved these changes

2023-10-27 14:14 UTC, camdencheek approved these changes
Woo hoo! Thanks for the persistence!

2023-10-30 18:48 UTC, merged