msp: add subscription deploy type
sourcegraph/sourcegraph pull request #57971
Opened 2023-10-29 23:15 UTC by michaellzc

## Test plan

2023-10-29 23:15 UTC, michaellzc commented
Current dependencies on/for this PR:
* main
  * **PR #57971** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/57971" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/57971?utm_source=stack-comment).

2023-10-31 01:06 UTC, unknwon approved these changes
Otherwise LGTM!

2023-10-31 01:06 UTC, unknwon commented on dev/managedservicesplatform/spec/environment.go
> +		if len(s.Subscription.Images) > 1 {
why not? 🤔 
```suggestion
		if len(s.Subscription.Images) != 1 {
```

2023-10-31 01:06 UTC, unknwon commented on dev/managedservicesplatform/spec/environment.go
> +	// In the future, we may support subscribing by semver constraints.
Who is this docstring for?

2023-10-31 20:03 UTC, bobheadxi commented on dev/managedservicesplatform/spec/environment.go
> +	// In the future, we may support subscribing by semver constraints.
Maybe add a `TODO` here?

2023-10-31 20:04 UTC, bobheadxi commented on dev/managedservicesplatform/spec/environment.go
> +	Repo string `json:"repo,omitempty"`
this feels a bit funky to me, because now we have 2 places to describe the image/repo (top-level service, and in here as well)

2023-10-31 20:06 UTC, bobheadxi commented on dev/managedservicesplatform/spec/environment.go
> +	Images []EnvironmentDeployTypeSubscriptionImageSpec `json:"images,omitempty"`
I'm not 100% sure we have a use case for this yet, and IMO i might prefer that we deploy adjacent services as separate services using IAP rather than use sidecars

2023-10-31 20:07 UTC, bobheadxi commented on dev/managedservicesplatform/spec/environment.go
> +	Images []EnvironmentDeployTypeSubscriptionImageSpec `json:"images,omitempty"`
I think we should just condense `EnvironmentDeployTypeSubscriptionImageSpec` into here for now, and we can revisit the sidecar case in the future. For example, I would prefer to describe sidecars as `EnvironmentDeploySpec[]` instead of being nested in here

2023-10-31 20:07 UTC, bobheadxi requested changes
thank you! feedback would be to remove multi-container specification for now, and remove the ability to override the top-level image repository

2023-10-31 20:40 UTC, michaellzc commented
> thank you! feedback would be to remove multi-container specification for now, and remove the ability to override the top-level image repository

updated

2023-10-31 21:08 UTC, bobheadxi commented on dev/managedservicesplatform/spec/environment.go
> +	Image EnvironmentDeployTypeSubscriptionImageSpec `json:"image,omitempty"`
```suggestion
	// Tag is the tag to subscribe to.
	Tag string `json:"tag,omitempty"`
	// TODO: In the future, we may support subscribing by semver constraints.
```

2023-10-31 21:19 UTC, bobheadxi approved these changes
thank you!!

2023-10-31 21:29 UTC, merged