[Cody GA Docs] Improvements to Cody Quickstart tutorial
sourcegraph/sourcegraph pull request #58358
Opened 2023-11-15 23:21 UTC by MaedahBatool

## Test plan

Docs added

2023-12-04 23:26 UTC, taylorsperry commented on doc/cody/quickstart.md
> +2. Identify errors and suggest code fixes
"and get suggested code fixes"

2023-12-04 23:26 UTC, taylorsperry commented on doc/cody/quickstart.md
> +After installing the extension, the side activity bar will display an icon for **Cody**. Click this icon, and Cody's **Chat** panel will open. This interface is used to ask Cody questions and paste i
I think this refers to the old UX, no? The new UX won't open the chat panel automatically.

2023-12-04 23:26 UTC, taylorsperry commented on doc/cody/quickstart.md
> +To ensure code quality and early bug detection, one of the most useful commands that Cody offers is **Generate unit tests**. It quickly helps you write a test code for any snippet that you have highl
"helps you write ~a~ test code"

2023-12-05 00:33 UTC, MaedahBatool commented on doc/cody/quickstart.md
> +After installing the extension, the side activity bar will display an icon for **Cody**. Click this icon, and Cody's **Chat** panel will open. This interface is used to ask Cody questions and paste i
Fixed it.

2023-12-05 11:52 UTC, toolmantim approved these changes

2023-12-07 21:54 UTC, kalanchan requested changes
overall looks good, added some comments!

2023-12-07 21:54 UTC, kalanchan commented on doc/cody/quickstart.md
> +![Cody icon in side activity bar ](https://storage.googleapis.com/sourcegraph-assets/Docs/cody-quickstart/cody-icon-vscode.png)
@MaedahBatool let's bump this to v0.18 at least, new search UI will be present

2023-12-07 21:54 UTC, kalanchan commented on doc/cody/quickstart.md
> +  <source src="https://storage.googleapis.com/sourcegraph-assets/Docs/Media/code-comments-cody.mp4" type="video/mp4">
nice!

2023-12-07 21:54 UTC, kalanchan commented on doc/cody/quickstart.md
> +1. Click **New Chat** button, type `/` in the chat bar, and Cody will suggest a list of commands
nit: maybe add an image here to showcase each of these trigger command operations?

2023-12-08 18:25 UTC, kalanchan commented on doc/cody/quickstart.md
> +![Cody icon in side activity bar ](https://storage.googleapis.com/sourcegraph-assets/Docs/cody-quickstart/cody-icon-vscode.png)
it's still showing v0.14.5 :( 

could you update the image to show v0.18 so that the new search bar is present as well!

2023-12-11 17:51 UTC, merged