Implemented tree-sitter-dart
sourcegraph/sourcegraph pull request #58480
Opened 2023-11-21 22:40 UTC by matthewnitschke

## Test plan

2023-11-21 22:47 UTC, matthewnitschke commented
@cla-bot cla has been signed

2023-11-21 22:51 UTC, matthewnitschke commented
@keynmol Snapshots have been generated, and this is now ready for review!

2023-11-22 06:23 UTC, varungandhi-src commented
@matthewnitschke I've re-titled this PR and the linked issue to make it clearer that they're related to syntax highlighting, not search-based code nav for locals (which we also support via Tree-sitter), and not related to implementing the grammar itself (tree-sitter-x is conventionally used for the grammar names).

2023-11-24 17:56 UTC, matthewnitschke commented
> @matthewnitschke I've re-titled this PR and the linked issue to make it clearer that they're related to syntax highlighting, not search-based code nav for locals (which we also support via Tree-sitter), and not related to implementing the grammar itself (tree-sitter-x is conventionally used for the grammar names).

Interesting, I was hoping I'd be able to utilize symbol searching in dart with this update, but that does not sound like the case. Is there a future where this functionality (referring to `type:symbol` searching) could be provided by scip? If not, could you point me in the location of where this is currently handled within the sourcegraph codebase?

2023-11-28 14:54 UTC, varungandhi-src commented
@matthewnitschke yes, `type:symbol` search can also be handled via SCIP. For that, take a look at the following things:

- Usages of `BundledParser` type/cases, including the place with `create_tags_configuration`
- `scip-tags.scm` files (we'd need a similar one for Dart)

I would recommend handling that in a separate PR, since this PR is already quite big.

I think that should be enough, but if we need to add separate `Kind` cases to SCIP for handling Dart constructs, we may need some extra work in the [Zoekt](https://github.com/sourcegraph/zoekt) repo to handle those.

2023-11-28 15:11 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//     ^^^^^^ IdentifierType
Can enum constants be used as types too? If not, I think `IdentifierConstant` would be more suitable.

2023-11-28 15:12 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//      ^^^ IdentifierBuiltin
`age` should be `Identifier` not `IdentifierBuiltin`

2023-11-28 15:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//              ^^^^^ IdentifierBuiltin
`fruit` should be marked `Identifier` or `IdentifierLocal` here.

2023-11-28 15:21 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//               ^^^^^^ IdentifierBuiltin
`fruits` should be `Identifier` or `IdentifierLocal`

2023-11-28 15:22 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//  ^^^^^ IdentifierBuiltin
`final` should be `Keyword` instead of `Builtin`

2023-11-28 15:24 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//                ^ IdentifierOperator
If possible, the `<` and `>` here should be treated as punctuation brackets instead of `IdentifierOperator`

2023-11-28 15:25 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +    try {
Missing `Keyword` on `try` and `catch` here.

2023-11-28 15:29 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/dart/highlights.scm
> +    "show"
The `hide` keyword is missing. Could you rearrange this list to be in alphabetical order. That way makes it easier to compare with https://dart.dev/language/keywords

Same goes for the list earlier.

2023-11-28 15:58 UTC, matthewnitschke commented
@varungandhi-src Oof, looks like the existing tree-sitter-dart implementation is not in the place I was hoping it was, I'll need to spend some time digging into the project

As far as fixes go, would the preferred route be fixing the original [tree-sitter-dart](https://github.com/UserNobody14/tree-sitter-dart), and then updating sourcegraph's [fork](https://github.com/sourcegraph/tree-sitter-dart) once its ready? Just looking to address this stuff in the cleanest way possible

2023-11-28 20:43 UTC, varungandhi-src commented
> As far as fixes go, would the preferred route be fixing the original [tree-sitter-dart](https://github.com/UserNobody14/tree-sitter-dart), and then updating Sourcegraph's [fork](https://github.com/sourcegraph/tree-sitter-dart) once its ready?

Yes, that would be the best way to do things.

2024-02-10 20:59 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//     ^^^^^^ IdentifierType
enum constants can be used as types as well, for example, the following is valid dart:

```dart
enum Status { active, inactive, suspended }
void doAThing(Status theStatus) => print(theStatus);
```

I think that would imply that `IdentifierType` is the correct tag for this symbol, correct?

2024-02-10 21:02 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//      ^ IdentifierOperator
This should be resolved within: https://github.com/UserNobody14/tree-sitter-dart/pull/61

2024-02-11 04:09 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//      ^^^ IdentifierBuiltin
Resolved within https://github.com/UserNobody14/tree-sitter-dart/pull/62

2024-02-16 14:13 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//     ^^^^^^ IdentifierType
Sorry, I think there's some confusion because I didn't highlight the full range properly for this comment.

```
enum Status { active, inactive, suspended }
void doAThing(Status theStatus) => print(theStatus);
```

Here, `active`, `inactive` and `suspended` are the enum constants. They're currently marked as `IdentifierType`, but I believe `IdentifierConstant` as these cannot be used in type position. `Status` itself is a type and hence makes sense to be marked as `IdentifierType`.

2024-04-06 19:32 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/files/dart.dart
> +// Libraries and Imports
It does, I'll update accordingly

2024-04-06 19:35 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//     ^^^^^^ IdentifierType
Ah, yes, that makes more sense then, I'll look to update that

2024-04-06 19:41 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//     ^^^^^^ IdentifierType
Resolved within https://github.com/UserNobody14/tree-sitter-dart/pull/66

2024-04-07 16:06 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/tree-sitter-all-languages/Cargo.toml
> +tree-sitter-dart = { git = "https://github.com/UserNobody14/tree-sitter-dart", rev = "923fbe0d3e62340ea78422551166ce946bc05222" }
I mirrored the changed applied to https://github.com/sourcegraph/tree-sitter-dart, in the upstream: https://github.com/UserNobody14/tree-sitter-dart/pull/67

Unsure if there were other reasons for `sourcegraph/tree-sitter-dart`, but I think that repo can be closed now

2024-04-07 16:19 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//      ^ IdentifierOperator
`tree-sitter-dart` has been updated to correctly mark these as `@punction.bracket`, but it appears as though the test framework no-longer annotates [these markings](https://github.com/sourcegraph/sourcegraph/pull/58480/files#diff-217c61600cc8e060e0d1cbad5050967c5cd195392819527603043e0797cec803R136)

Is this intentional? or is there something wrong within the highlights.scm side of things?

2024-04-07 16:19 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//              ^^^^^ IdentifierBuiltin
resolved

2024-04-07 16:20 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//               ^^^^^^ IdentifierBuiltin
Resolved

2024-04-07 16:20 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//  ^^^^^ IdentifierBuiltin
Resolved

2024-04-07 16:21 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//         ^^^^^^^^ Identifier
Resolved

2024-04-07 16:21 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +//                ^ IdentifierOperator
Same as https://github.com/sourcegraph/sourcegraph/pull/58480#discussion_r1555004826, doesn't look like `@punction.bracket` is included anymore

2024-04-07 16:22 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/sg-syntax/src/snapshots/sg_syntax__sg_treesitter__test__dart.dart.snap
> +    try {
resolved

2024-04-07 16:22 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/scip-treesitter-languages/queries/dart/highlights.scm
> +    "show"
resolved

2024-04-07 16:24 UTC, matthewnitschke commented
@varungandhi-src @keynmol 

A bit of a delay on this one... but I've gone ahead and addressed all of varun's original comments in the upstream `tree-sitter-dart`

Should be ready for another round of reviews

2024-04-08 09:56 UTC, varungandhi-src requested changes

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(symbol_literal) @symbol
If you see `const MATCHES_TO_SYNTAX_KINDS: &[(&str, SyntaxKind)]` in the Rust code, there is no SyntaxKind mapping for `symbol`, unlike `string` or `constant.builtin`. So we should use something else here.

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +    (break_statement)
```suggestion
    (break_builtin)
```

Otherwise we'll end up marking the full range of the statement as a keyword.

Please add test cases for all the non-string keywords at least.

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(super) @function
Is this always correct or can `super` sometimes be a variable? I noticed this in the grammar.

https://github.com/UserNobody14/tree-sitter-dart/blob/6da46473ab8accb13da48113f4634e729a71d335/grammar.js#L843-L848

Where it seems like `super` can be compared for equality, which is usually not the case for functions in other languages.

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(dotted_identifier_list) @string
AFAICT, this isn't covered by any existing test cases. Could you add a test case for this?

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//  ^^^ IdentifierType
If possible, it would be nice to mark the built-in types with `@type.builtin` rather than just `@type`.

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//                        ^ PunctuationDelimiter
Missing highlighting for `~/` as an operator.

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +  ;(identifier) @type)
```suggestion
```

It looks like `type_identifier` is already covered below so this can be removed?

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(null_literal) @constant.builtin
```suggestion
(null_literal) @constant.null
```

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(ERROR) @error
```suggestion
```

There is no `"error"` in `const MATCHES_TO_SYNTAX_KINDS`

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//                ^^^^^^^ Identifier
Why is `delayed` not getting picked up as a function here?

2024-04-08 09:56 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +    return Future.delayed(Duration(seconds: 2), () => "Data loaded");
Looks like we're missing highlighting for `seconds` - is that deliberate?

2024-04-10 05:12 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(super) @function
While technically super can be used in an equality statement
```dart
class Bar {}
class Foo extends Bar {
  void thing() {
    print(super == this); // valid dart
  }
}
```

Seems like an obscure edge case

I feel like just marking super as a `keyword` would align better with the [language spec](https://dart.dev/language/keywords)

2024-04-10 05:17 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(dotted_identifier_list) @string
Added a test case for this, but honestly I'm not sure what the original intent of this `dotted_identifier_list` mark is for? each should be treated as an identifier, not a string

I've gone ahead and removed this

2024-04-10 06:10 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(super) @function
I think marking it as a keyword is also OK. 👍🏽

2024-04-11 04:36 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(super) @function
resolved

2024-04-11 04:36 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//  ^^^ IdentifierType
Resolved, all builtin types should be annotated as `@type.builtin`

2024-04-11 04:37 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//                        ^ PunctuationDelimiter
Resolved

2024-04-11 04:37 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +  ;(identifier) @type)
Removed

2024-04-11 04:37 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(null_literal) @constant.builtin
Resolved

2024-04-11 04:37 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(ERROR) @error
Removed

2024-04-11 04:52 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//                ^^^^^^^ Identifier
Resolved

2024-04-11 04:52 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +    return Future.delayed(Duration(seconds: 2), () => "Data loaded");
resolved

2024-04-11 05:05 UTC, varungandhi-src approved these changes
LGTM modulo the minor remaining change for null. I'll do a quick end-to-end test before merging.

2024-04-11 05:05 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(null_literal) @constant.builtin
Perhaps you forgot to commit the change? I still see `@constant.builtin` here. Please also add a test case for null.

2024-04-11 05:11 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(null_literal) @constant.builtin
Ah, shoot, just forgot to push

Looking at the generated result though, the parser is considering `null` a `Keyword`, which makes sense from both a [highlight.scm](https://github.com/sourcegraph/sourcegraph/pull/58480/files/449e5b07047add3281e138565793c26502f0da0c#diff-2292d504d6948fca07b0902fb7a5a371c5418af1aa789046203943dad6dc311fR234) and a [dart keywords](https://dart.dev/language/keywords) perspective

Unless you think otherwise, It might be best to just remove this, and rely on null being a keyword

2024-04-11 05:14 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(null_literal) @constant.builtin
I think we should use `@constant.null` as null/nil is highlighted differently from keywords in the Sourcegraph UI.

![CleanShot 2024-04-11 at 13 13 58@2x](https://github.com/sourcegraph/sourcegraph/assets/93103176/f46c1da3-2074-48a2-824b-de8a86aa7ea8)

2024-04-11 05:19 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/dart/highlights.scm
> +(null_literal) @constant.builtin
Sounds good, should be updated now

2024-04-11 06:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//                                 ^^^^ IdentifierFunction
@matthewnitschke while doing end-to-end testing, I noticed that this was incorrectly getting marked as `IdentifierFunction` instead of just `Identifier`. Can you fix this?

2024-04-11 14:56 UTC, matthewnitschke commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__dart.dart.snap
> +//                                 ^^^^ IdentifierFunction
Should be resolved now, nice find!

2024-04-12 03:04 UTC, varungandhi-src commented
@matthewnitschke I've asked internally if we can trigger CI for PRs from forks. If not, I can recreate the PR on a separate branch.

2024-04-12 09:00 UTC, varungandhi-src commented
@matthewnitschke can you rebase on top of the latest changes on `main`? I think the base being outdated might be causing the backcompat tests to fail.

2024-04-15 04:12 UTC, matthewnitschke commented
> @matthewnitschke can you rebase on top of the latest changes on `main`? I think the base being outdated might be causing the backcompat tests to fail.

@varungandhi-src Merged `main` and CI's looking green!

2024-04-15 13:24 UTC, varungandhi-src approved these changes

2024-04-15 13:24 UTC, merged