WIP: snapshot the evaluation results
sourcegraph/sourcegraph pull request #58500
Opened 2023-11-22 15:11 UTC by keynmol

## Test plan

- This PR adds evaluation snapshot testing logic

2024-01-25 14:27 UTC, varungandhi-src commented
@kritzcreek can you review this PR? It's a bit big, it's near end-of-day for me, and I'd like to spend some focus time on planning related stuff tomorrow.

2024-01-26 10:02 UTC, kritzcreek requested changes
Mostly nits, looks great in general!

2024-01-26 10:02 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/scip-treesitter-cli/testdata/scip-index.sh
> +# docker setup on CI where it runs in a sidecar.
Should we open an issue about this after merging, so we don't forget?

2024-01-26 10:05 UTC, keynmol commented on docker-images/syntax-highlighter/crates/scip-treesitter-cli/testdata/java/build.gradle
> +    // TODO: add dependencies
Actually I think this comes from the gradle project scaffold
I'll remove the TODO to avoid confusion - we don't index dependencies so it doesn't matter to us

2024-01-26 13:23 UTC, keynmol commented on docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/bin/scip-treesitter.rs
> +                disable_colors: no_color,
Done in https://github.com/sourcegraph/sourcegraph/pull/58500/commits/3b6a3d83f24cbb8278f4467fa703f16aa7a225e6

2024-01-26 13:23 UTC, keynmol commented on docker-images/syntax-highlighter/crates/scip-treesitter-cli/testdata/scip-index.sh
> +# docker setup on CI where it runs in a sidecar.
Yep, I'll do that

2024-01-26 13:24 UTC, keynmol commented on docker-images/syntax-highlighter/crates/scip-treesitter-cli/src/index.rs
> +            .unwrap();
Can do in a separate PR, this particular function was designed to be throwing as it's the side-effectful part of CLI (end of the world).

But I agree with argument for ? and with_context

2024-01-26 13:49 UTC, kritzcreek approved these changes

2024-01-26 15:14 UTC, merged