Enable logging Fireworks requests for Self-Serve users
sourcegraph/sourcegraph pull request #58556
Opened 2023-11-24 14:21 UTC by rafax

## Test plan

2023-11-24 14:59 UTC, eseliger approved these changes

2023-11-24 15:26 UTC, philipp-spiess approved these changes

2023-11-24 18:30 UTC, bobheadxi commented on cmd/cody-gateway/internal/httpapi/completions/fireworks.go
> +					// LogEvent is a channel send (not an external request), so should be ok here
does `act.IsDotComActor` === actor is a PLG user?

2023-11-24 18:32 UTC, bobheadxi commented on cmd/cody-gateway/internal/httpapi/completions/fireworks.go
> +			getRequestMetadata: func(ctx context.Context, logger log.Logger, act *actor.Actor, body fireworksRequest) (model string, additionalMetadata map[string]any) {
Instead of expanding this signature and generating another event log, can we just return all the new data as part of `additionalMetadata`? It gets logged in https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@237d1f237ef79938e432387cdc75b437d1fd9f5e/-/blob/cmd/cody-gateway/internal/httpapi/completions/upstream.go?L286

2023-11-24 18:33 UTC, bobheadxi requested changes
Let's keep `getRequestMetadata` without side effects, and avoid logging an additional event, and return the desired new metadata as part of the `additionalMetadata` return parameter of `getRequestMetadata`, which gets logged at the end of the request (whether it succeeded or not)

2023-11-24 19:29 UTC, rafax commented on cmd/cody-gateway/internal/httpapi/completions/fireworks.go
> +					// LogEvent is a channel send (not an external request), so should be ok here
For now - I think that's true, and even if there's a special case, we can log prompts for sourcegraph.com users.

2023-11-24 19:31 UTC, bobheadxi commented on cmd/cody-gateway/internal/httpapi/completions/fireworks.go
> +					// LogEvent is a channel send (not an external request), so should be ok here
let's update the docstring to reflect that this covers all doctom users then, seems we have pretty liberal terms for dotcom users so it's a bit of a free-for-all anyway

2023-11-24 19:32 UTC, rafax commented on cmd/cody-gateway/internal/httpapi/completions/fireworks.go
> +			getRequestMetadata: func(ctx context.Context, logger log.Logger, act *actor.Actor, body fireworksRequest) (model string, additionalMetadata map[string]any) {
I thought about that, but my primary considerations were:

- this code is temporary, I expect it to be gone in 14 days (ideally sooner) - keeping it separate makes it easier to remove
- the data we want to capture will be removed from event_logs table, and it's "cleaner" to filter and delete by event name than by a subproperty in metadata field

With those 2 things in mind, would you still use `additionalMetadata`?

2023-11-24 19:33 UTC, rafax commented
> Let's keep `getRequestMetadata` without side effects, and avoid logging an additional event, and return the desired new metadata as part of the `additionalMetadata` return parameter of `getRequestMetadata`, which gets logged at the end of the request (whether it succeeded or not). You can add a flag field in `additionalMetadata` that can be used to query and generate your dataset

See my comment above - assuming we plan to remove this code in 14 days, and also remove the data captured from `event_logs` table (and lather remove it altogether), would you agree that using a separate logging event is the way to go?

2023-11-24 19:48 UTC, bobheadxi commented on cmd/cody-gateway/internal/httpapi/completions/fireworks.go
> +			getRequestMetadata: func(ctx context.Context, logger log.Logger, act *actor.Actor, body fireworksRequest) (model string, additionalMetadata map[string]any) {
> the data we want to capture will be removed from event_logs table, and it's "cleaner" to filter and delete by event name than by a subproperty in metadata field

Ah, I missed this requirement - fair enough, a separate event would be better for this use case. Thanks for clarifying!

2023-11-24 19:49 UTC, bobheadxi commented on cmd/cody-gateway/internal/httpapi/completions/fireworks.go
> +			getRequestMetadata: func(ctx context.Context, logger log.Logger, act *actor.Actor, body fireworksRequest) (model string, additionalMetadata map[string]any) {
(I thought we would only be generating this data for N time, not that the data itself would need to be removed as well)

2023-11-24 19:49 UTC, bobheadxi approved these changes

2023-11-24 19:50 UTC, bobheadxi commented
LGTM to serve the use case of removing this data later 👍

2023-11-27 08:15 UTC, merged

2024-02-09 16:13 UTC, rafax commented
> > Let's keep `getRequestMetadata` without side effects, and avoid logging an additional event, and return the desired new metadata as part of the `additionalMetadata` return parameter of `getRequestMetadata`, which gets logged at the end of the request (whether it succeeded or not). You can add a flag field in `additionalMetadata` that can be used to query and generate your dataset
> 
> See my comment above - assuming we plan to remove this code in 14 days, and also remove the data captured from `event_logs` table (and lather remove it altogether), would you agree that using a separate logging event is the way to go?

This took more than 14 days, but it's now getting removed https://github.com/sourcegraph/sourcegraph/pull/60372