[Cody GA Docs] Add Cody pricing and usage
sourcegraph/sourcegraph pull request #58574
Opened 2023-11-26 04:40 UTC by MaedahBatool

## Test plan

Docs added

2023-11-28 22:12 UTC, chenkc805 requested changes
Left a bunch of comments, thanks for driving this! It's getting there 💪

2023-11-28 22:12 UTC, chenkc805 commented on doc/cody/usage-and-pricing.md
> +Cody Enterprise is designed for enterprises prioritizing security and administrative controls, starting at a consumption-based pricing capped at $19 per user per month. You get additional capabilitie
CC: @ryphil to review this section

2023-12-01 04:38 UTC, MaedahBatool commented on doc/cody/usage-and-pricing.md
> +The free plan provides access to local context with keyword search and embeddings on open-source code via Sourcegraph.com. Additionally, you can benefit from private embeddings *up to a specified amo
What does "user lifetime" mean here? Can you please elaborate?

2023-12-01 17:39 UTC, MaedahBatool commented
Hey @chenkc805, I would like to get another pass from you. Addressed all your feedback in the PR.

2023-12-01 17:50 UTC, chenkc805 commented on doc/cody/usage-and-pricing.md
> +The free plan provides access to local context with keyword search and embeddings on open-source code via Sourcegraph.com. Additionally, you can benefit from private embeddings *up to a specified amo
"User lifetime" means they have 200 mb that they can ever use throughout the life of the user. 

So if they embed 150 MB of code, then they can only embed another 50 MB of code. If they delete that 150 MB of code embedding, then they have 200 MB of code embeddings available again. 

If they embed repo 1 = 150 MB and repo 2 = 25 MB, then they have only 25 MB left for other embeddings.

2023-12-04 17:12 UTC, chenkc805 approved these changes

2023-12-05 20:33 UTC, taylorsperry commented on doc/cody/usage-and-pricing.md
> +The free plan provides access to local context with keyword search and embeddings on open-source code via Sourcegraph.com. You get 200 MB of embeddings with the ability to manage these from the user
@chenkc805 Is there an expectation that generating embeddings for local projects is gated behind Pro? As far as I know, all PLG users will be able to generate "app-less" embeddings for GA.

2023-12-05 20:37 UTC, taylorsperry commented on doc/cody/usage-and-pricing.md
> +The plan includes the ability to create an unlimited number of Custom Commands for personalized workflows. In addition to using the local context of your code to improve responses, you can embed up t
Same comment as above. If this work is underway, I don't know about it.

2023-12-05 20:38 UTC, taylorsperry commented on doc/cody/usage-and-pricing.md
> +Support for Cody Pro is available through Discord, ensuring prompt assistance and guidance. However, it's essential to note that the Cody Pro plan is limited to **50 developers** per month. Finally,
Note that LLM selection is only available for VSC today.

2023-12-05 20:38 UTC, taylorsperry commented on doc/cody/usage-and-pricing.md
> +The free plan provides access to local context with keyword search and embeddings on open-source code via Sourcegraph.com. You get 200 MB of embeddings with the ability to manage these from the user
Also, this is only supported in VSC right now.

2023-12-05 21:42 UTC, chenkc805 commented on doc/cody/usage-and-pricing.md
> +The free plan provides access to local context with keyword search and embeddings on open-source code via Sourcegraph.com. You get 200 MB of embeddings with the ability to manage these from the user
> Is there an expectation that generating embeddings for local projects is gated behind Pro?

No, users will be able to have embeddings in all tiers: Free, Pro, and Enterprise. They just get different amounts: Free = 200mb/user/lifetime, Pro = 1 GB/user/lifetime, Enterprise = some higher amount. 

Good callout on VS Code though, we should mention this in the docs. Ultimately line 11 should read something like:

The free plan provides access to local context with keyword search and embeddings on open-source code via Sourcegraph.com. You **also** get 200 MB of embeddings with the ability to manage these from the user settings **in VS Code, with JetBrains IDE support coming soon**. The free plan ensures local context utilization and allows you to seamlessly integrate Cody into your preferred client, whether it's VSCode, JetBrains, or Neovim. Finally, you'll have default support with Anthropic and StarCoder as the officially supported LLMs.

2023-12-05 21:42 UTC, chenkc805 commented on doc/cody/usage-and-pricing.md
> +The plan includes the ability to create an unlimited number of Custom Commands for personalized workflows. In addition to using the local context of your code to improve responses, you can embed up t
>In addition to using the local context of your code to improve responses, you can embed up to **1 GB** of your private code for even better Cody responses that reflect a deep understanding of your own code **in VS Code, with JetBrains IDE support coming soon.**

2023-12-12 02:20 UTC, MaedahBatool commented
Since I have the approval on this PR, I am merging this with the main GA docs release. Find it here: https://github.com/sourcegraph/sourcegraph/pull/58903

2023-12-12 02:20 UTC, closed without merging