Code Navigation: show full tree context
sourcegraph/sourcegraph pull request #58598
Opened 2023-11-27 22:19 UTC by jasonhawkharris

Before, if a user refreshed the blobview after navigating to a file from the file tree, the full tree context would disappear, leading to a frustrating experience for some users. 

Now, users can choose if they'd like to show the full context of the file tree or not. See video: 

https://www.loom.com/share/afdea775679945fd9b42a4cfc817edb0

## Test plan
1. Manual testing

2023-11-27 22:24 UTC, jasonhawkharris commented on client/shared/src/settings/settings.tsx
> +    showFullTreeContext: true,
I'd love some input on this. Making this the default VS having the users change this.

2023-11-27 23:03 UTC, peterguy commented on client/shared/src/settings/settings.tsx
> +    showFullTreeContext: true,
Absolutely want to make it the default, but let's give it time to settle. Maybe make a followup PR for defaulting it to `true`, and then another one for removing it and making the behavior the default behavior.

2023-11-27 23:04 UTC, peterguy approved these changes
Love the new behavior; looks like a really simple change!

2023-11-28 01:47 UTC, BolajiOlajide approved these changes

2023-11-28 07:47 UTC, fkling requested changes

2023-11-28 07:53 UTC, fkling commented on client/web/src/repo/RepoRevisionSidebar.tsx
> +    const [initialFilePath, setInitialFilePath] = useState<string>(showFullTreeContextEnabled ? '' : props.filePath)
Looks like the `filePath` prop is already weird because the way it's used it's already ignored in subsequent renders (so really it should be renamed to `initialFilePath` or something). Still, I don't think it's a good idea to introduce exceptions in every layer of the tree. If it can easily be set in the caller then we should do that.

2023-11-28 07:59 UTC, fkling approved these changes

2023-11-28 07:59 UTC, fkling commented on client/web/src/repo/RepoRevisionSidebar.tsx
> +    const [initialFilePath, setInitialFilePath] = useState<string>(showFullTreeContextEnabled ? '' : props.filePath)
Uh, OK. `filePath` is also used elsewhere... I think a good solution would be to add a `contextFilePath` prop (or something like that) to this component and have it set by the caller but 🤷🏻

2023-11-28 08:10 UTC, fkling commented
A couple of things to consider:

- We should make corresponding changes to the GraphQL API to allow us to fetch multiple subtrees in a single query. Right now we have to make multiple requests to fetch the children of every folder in the path. That's one of the reasons why I didn't implement this behavior in the SvelteKit prototype.
- We still need to be aware that it doesn't actually preserve the current file tree's state. I.e. folders that are open but not directly in the path of the opened file won't show up as open.
- The selected file should be scrolled into view. I'm even inclined to say that the situation is not much better than before because you are loosing your position in the tree. It's possible that you don't immediately see where you are when the page loads. This would possibly be solved when we fetch all subtrees in a single query.
- The UX is likely going to be bad for cases where you are at `a/b/c/d.txt` and `b` is a larger directory with > 1000 files. You won't see the contents of `c/` until the contents for `b/` was fetched. Fetching larger directories is slower than fetching smaller directories, which is also a problem for the first point.

2023-11-28 14:23 UTC, jasonhawkharris commented on client/web/src/repo/RepoRevisionSidebar.tsx
> +    const [initialFilePath, setInitialFilePath] = useState<string>(showFullTreeContextEnabled ? '' : props.filePath)
Wouldn't that give us three separate file path props to deal with? That sounds confusing to me.

2023-11-28 15:18 UTC, merged

2023-11-28 15:39 UTC, camdencheek commented
> fetch multiple subtrees in a single query

@fkling what do you mean by this? A single GraphQL request can always fetch multiple objects if we know what we want in advance. We also have the `ancestors` query, which is really nice for getting everything that would be viewable by default for a file tree that is expanded up to an entry.

2023-11-28 15:45 UTC, fkling commented
@camdencheek 

If you open file `a/b/c/d.txt` and we want to show the whole file tree, then we need to fetch all children of `a` and `b` too. Looks like `ancestors` is what I was looking for.