[Cody GA Docs] Improvements to VS Code Cody Client docs
sourcegraph/sourcegraph pull request #58761
Opened 2023-12-05 01:47 UTC by MaedahBatool

## Test plan

Docs added

2023-12-05 20:07 UTC, taylorsperry reviewed
Can we add an explanation of VS Code Actions here? ("Ask Cody to Fix," "Ask Cody to Explain," and "Ask Cody to Edit")

2023-12-05 20:07 UTC, taylorsperry commented on doc/cody/overview/install-vscode.md
> +After connecting Cody's extension to Sourcegraph.com, you can optionally use [Code Graph Context](./../core-concepts/code-graph.md) to improve Cody's context of existing code. Code Graph Context is o
I don't believe "Code Graph Context" and "embeddings" are one and the same, and I'm not sure what are the different options for Enterprise vs Community users to enable "Code Graph Context" and what it supports. Please check with eng?

2023-12-06 03:25 UTC, MaedahBatool commented on doc/cody/overview/install-vscode.md
> +### Enhanced Context Selector
In my opinion, it's not a settings icon. Because typically, it's a gear "⚙️". We might confuse users since I was looking for a gear sign in the chat input window as well.

2023-12-07 22:21 UTC, kalanchan requested changes
left some comments!

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +![install-vscode-extension](https://storage.googleapis.com/sourcegraph-assets/Docs/cody-new-ui.png)
this is the same image as the one below, did you mean to put the vs code marketplace image here instead?

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +You can use Sourcegraph Enterprise with the Cody VS Code extension. Click the **Sign In to Your Enterprise Instance**, and it connects to your enterprise environment.
```suggestion
You can use Sourcegraph Enterprise with the Cody VS Code extension. Click the **Sign In to Your Enterprise Instance**, and it connects to your enterprise environment. For Enterprise users, please sign in with your custom Sourcegraph instance URL and access token. Enterprise accounts are not compatible with community accounts.
```

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +Cody's Enhanced Context enables Cody to leverage search and embeddings-based context. It's enabled by default, though embeddings for Enterprise users are controlled by administrators and community us
```suggestion
Cody's Enhanced Context enables Cody to leverage search and embeddings-based context. Community users can generate local embeddings for their projects by clicking the icon next to the chat input. Users can also disable Enhanced Context to have more granular control of Cody's context by including `@-files` or `@#-symbols` in the chat input.

**Note: Embeddings for Enterprise users are controlled by their administrators.**
```

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +![](https://storage.googleapis.com/sourcegraph-assets/Docs/enhanced-context.png)
let's update this image to use the new enhanced context UI. Feel free to index any open source repo for it

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +|                          | Opened Files                 | Highlighted Code            | Embeddings (If available)  | Symf (as backup)            | Graph Context (BFG)         |
```suggestion
|                          | Opened Files                 | Highlighted Code            | Embeddings (If available)  | Search (as backup)            | 
```

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +|                          | Opened Files                 | Highlighted Code            | Embeddings (If available)  | Symf (as backup)            | Graph Context (BFG)         |
woops this is my bad Maedah, let's not advertise or mention BFG just yet. We'll add it back in once BFG is ready to go!

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +| Enhanced Context Enabled  | ✅                           | ✅                          | ✅                          | ✅                          | ❌                          |
```suggestion
| Enhanced Context Enabled  | ✅                           | ✅                          | ✅                          | ✅                          |                   
```

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +| Enhanced Context Disabled | ❌                           | ❌                          | ❌                          | ❌                          | ❌                          |
```suggestion
| Enhanced Context Disabled | ❌                           | ❌                          | ❌                          | ❌                          |                     
```

2023-12-07 22:21 UTC, kalanchan commented on doc/cody/overview/install-vscode.md
> +After connecting Cody's extension to Sourcegraph.com, you can optionally use [Code Graph Context](./../core-concepts/code-graph.md) to improve Cody's context of existing code. Code Graph Context is o
where did you get this information from?

2023-12-08 13:00 UTC, toolmantim commented on doc/cody/overview/install-vscode.md
> +While this feature will be available to Community and Pro users, the ability to search across your entire codebase from within the IDE is limited to Enterprise users who have purchased both our Cody
@taylorsperry just flagging this: this feature works the same for all users at the moment, and searches across your entire codebase from within the IDE — that's not Enterprise only

2023-12-11 20:43 UTC, merged