Expanding logging to siteadmin actions
sourcegraph/sourcegraph pull request #58840
Opened 2023-12-08 02:23 UTC by mohammadualam

To expand our audit logging capabilities, we have to add more actions, especially siteadmin ones within our even logging setup.

The actions that we have identified to be of particular importance are being logged with this change so that they can be collected for analysis

## Test plan

Tested locally

2023-12-11 11:43 UTC, evict commented
Can we create a helper in our security events code like they did here: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/sign_out.go?L81:73-81:90?

2023-12-11 17:13 UTC, mohammadualam commented on internal/database/security_event_logs.go
> +func (s *securityEventLogsStore) LogSecurityEvent(ctx context.Context, eventName SecurityEventName, url string, userID uint32, anonymousUserID string, source string, arguments []byte) {
@evict Something like this? Re:your feedback on making it a function.

2023-12-11 17:15 UTC, evict commented on internal/database/security_event_logs.go
> +func (s *securityEventLogsStore) LogSecurityEvent(ctx context.Context, eventName SecurityEventName, url string, userID uint32, anonymousUserID string, source string, arguments []byte) {
```suggestion
func LogSecurityEvent(ctx context.Context, eventName SecurityEventName, url string, userID uint32, anonymousUserID string, source string, arguments []byte) {
```

2023-12-11 17:15 UTC, evict commented on internal/database/security_event_logs.go
> +	LogSecurityEvent(ctx context.Context, eventName SecurityEventName, url string, userID uint32, anonymousUserID string, source string, arguments []byte)
```suggestion
```

2023-12-11 17:17 UTC, evict commented on internal/database/security_event_logs.go
> +func (s *securityEventLogsStore) LogSecurityEvent(ctx context.Context, eventName SecurityEventName, url string, userID uint32, anonymousUserID string, source string, arguments []byte) {
Almost! Just as a function as good enough, and then replace the previous logging with that function. 👍

2023-12-11 17:18 UTC, mohammadualam commented on internal/database/security_event_logs.go
> +func (s *securityEventLogsStore) LogSecurityEvent(ctx context.Context, eventName SecurityEventName, url string, userID uint32, anonymousUserID string, source string, arguments []byte) {
Yup, i am updating those now, just wanted to see if i got your feedback correct

2023-12-13 19:23 UTC, evict requested changes

2023-12-13 19:23 UTC, evict commented on cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
> +		if err := database.LogSecurityEvent(ctx, database.SecurityEventNameDotComSubscriptionUpdated, "", uint32(actor.FromContext(ctx).UID), "", "BACKEND", argsJSON, s.db.SecurityEventLogs()); err != nil
You are passing the `s.db.SecurityEventLogs()`. Why don't you update the function and do that there? Same for the marshalling of the json, you can do that in `LogSecurityEvent` as well.

2023-12-13 19:26 UTC, evict commented on client/web/src/featureFlags/featureFlags.ts
> +    'auditlog_expansion',
nit: other names have `-` instead of `_`. What about naming it 'enhanced-auditlog' or 'extra-audit-logs'. It's temporary right?

2023-12-13 19:59 UTC, mohammadualam commented on cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
> +		if err := database.LogSecurityEvent(ctx, database.SecurityEventNameDotComSubscriptionUpdated, "", uint32(actor.FromContext(ctx).UID), "", "BACKEND", argsJSON, s.db.SecurityEventLogs()); err != nil
i will work on doing the marshalling within the function. 
Regarding the s.db.securityeventlog() passing, i had my function setup this way 
`func (s *securityEventLogsStore) LogSecurityEvent(ctx context.Context, eventName SecurityEventName, url string, userID uint32, anonymousUserID string, source string, arguments []byte) {......}` 

do you mean i should go back to that definition or are you referring to something else?

2023-12-13 22:00 UTC, evict commented on cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
> +		if err := database.LogSecurityEvent(ctx, database.SecurityEventNameDotComSubscriptionUpdated, "", uint32(actor.FromContext(ctx).UID), "", "BACKEND", argsJSON, s.db.SecurityEventLogs()); err != nil
> do you mean i should go back to that definition or are you referring to something else?
I am sorry, yes. 🤦  I didn't realize you'd then have to pass that `db` reference around. So your previous method is the cleanest one. I thought it would be nice to instantiate everything in the exported function, but we need the `db` handle from the request to actually touch the database.

2023-12-13 23:12 UTC, mohammadualam commented on cmd/frontend/internal/dotcom/productsubscription/subscriptions_db.go
> +		if err := database.LogSecurityEvent(ctx, database.SecurityEventNameDotComSubscriptionUpdated, "", uint32(actor.FromContext(ctx).UID), "", "BACKEND", argsJSON, s.db.SecurityEventLogs()); err != nil
reverted back to the original version.

2023-12-14 09:14 UTC, pjlast approved these changes
Seems good to me pending @evict 's approval if he's happy after his requested changes

2023-12-14 09:14 UTC, pjlast commented on internal/database/security_event_logs.go
> +
```suggestion
		return errors.Wrap(err, "error marshalling arguments")
```

Might be worth seeing why the marshalling failed in the error

2023-12-14 14:18 UTC, mohammadualam commented on internal/database/security_event_logs_test.go
> +	})
They were supposed to be removed.

2023-12-15 11:02 UTC, evict approved these changes
Looks good! Nice work.

2023-12-15 21:25 UTC, merged

2023-12-16 12:00 UTC, eseliger commented on cmd/frontend/graphqlbackend/org.go
> +				if featureflag.FromContext(ctx).GetBoolOr("auditlog-expansion", false) {
I'm curious, what's so secret about orgs that we would log access to them? 
Not saying it's not important, just curious :)