Add Cody providers to pings
sourcegraph/sourcegraph pull request #58848
Opened 2023-12-08 12:37 UTC by taras-yemets

Adds Cody completions and embeddings providers data to pings.
Provider name is always included. Model name is included only for "sourcegraph" provider. 

Closes https://github.com/sourcegraph/sourcegraph/issues/58826

BigQuery pings schema update
- https://github.com/sourcegraph/analytics/pull/1028

<table>
<thead>
<tr>
<td>Site config</td>
<td>Value in pings</td>
<td>Note</td>
</tr>
</thead>
<tbody>
<tr>
<td><code>{
"cody.enabled": false
}</code></td>
<td><code>"codyProviders": {
      "Embeddings": null,
      "Completions": null
  }</code></td>
<td>If Cody is disabled, completions and embeddings are not used. Return empty values similar to <code><a href="https://github.com/sourcegraph/sourcegraph/blob/82b5f4f5d73f56e31adfe7f5bd82bf2a4206cd46/internal/conf/computed.go#L575">GetCompletionsConfig</a></code> and <code><a href="https://github.com/sourcegraph/sourcegraph/blob/82b5f4f5d73f56e31adfe7f5bd82bf2a4206cd46/internal/conf/computed.go#L816">GetEmbeddingsConfig</a></code></td>
</tr>
<tr>
<td><code>{
"cody.enabled": true,
"completions": {
    "chatModel": "claude-v1",
    "completionModel": "claude-instant-v1",
    "fastChatModel": "claude-instant-1"
    "provider": "anthropic",
    "accessToken": "REDACTED"
}
}</code></td>
<td><code>"codyProviders": {
        "Embeddings": {
            "Model": "openai/text-embedding-ada-002",
            "Provider": "sourcegraph"
        },
        "Completions": {
            "Provider": "anthropic",
            "ChatModel": "",
            "CompletionModel": "",
            "FastChatModel": ""
        }
    }</code></td>
<td>Cody is enabled, completions config is defined, embeddings - is not. Return only provider name for completions provider (don't return model names as the provider is not "sourcegraph"). Return default embeddings provider.</td>
</tr>
<tr>
<td><code>{
"cody.enabled": true,
"embeddings": {
    "provider": "sourcegraph",
    "accessToken": "REDACTED"
}
}</code></td>
<td><code>"codyProviders": {
        "Embeddings": {
            "Model": "openai/text-embedding-ada-002",
            "Provider": "sourcegraph"
        },
        "Completions": {
            "Provider": "sourcegraph",
            "ChatModel": "anthropic/claude-2.0",
            "CompletionModel": "anthropic/claude-instant-1",
            "FastChatModel": "anthropic/claude-instant-1"
        }
    }</code></td>
<td>Cody is enabled, embeddings config is defined, completions - is not. Return the provider and model name for the completions provider (note, the model name is not provided in the site config - the default one is used). Return default completions provider (with model names as the provider is "sourcegraph").</td>
</tr>
</tbody>
</table>

## Test plan
- CI passes
- Tested manually: most recent ping contains correct Cody providers data (see values in the table above)

## Preview 🤩
[Preview Link](https://docs.sourcegraph.com/@ty/cody-providers-pings)

2023-12-08 13:56 UTC, chwarwick approved these changes
See note about model's otherwise I think once you get the test passing it 👍 .  Remember to wait for the data pr before merging.  Also pings used to require an approved RFC.

2023-12-08 13:56 UTC, chwarwick commented on internal/updatecheck/handler.go
> +	CodyProviders                 json.RawMessage `json:"codyProviders"`
```suggestion
	CodyProviders                 json.RawMessage `json:"cody_providers"`
```

2023-12-08 15:09 UTC, taras-yemets commented on internal/usagestats/cody_providers.go
> +	providers := types.CodyProviders{
Makes sense!
Addressed in https://github.com/sourcegraph/sourcegraph/pull/58848/commits/b02484be53e70712cfdc4c6abb0ca5a566f3b171

2023-12-08 18:20 UTC, chwarwick requested changes

2023-12-11 23:44 UTC, taras-yemets commented on internal/usagestats/cody_providers.go
> +			Provider: c.Completions.Provider,
Thank you, @chwarwick! Updated code and PR description.

2023-12-12 01:07 UTC, chwarwick approved these changes

2023-12-12 16:45 UTC, dadlerj approved these changes
See comments in the thread about the future of collecting this via pings: https://sourcegraph.slack.com/archives/CN4FC7XT4/p1702399336866429?thread_ts=1702377291.476959&cid=CN4FC7XT4

For now, approved!

2023-12-12 16:45 UTC, dadlerj commented on client/web/src/site-admin/SiteAdminPingsPage.tsx
> +                                    <li>Provider</li>
Can you clarify this a bit more? is there a discrete list of these options? If so, can you make it more clear, e.g.:

`<li>Provider (e.g. "sourcegraph", "azure-openai", "anthropic", etc.)</li>` 

or something?

In general, our ping documentation should be extremely explicit about the potential data being collected.

2023-12-12 16:45 UTC, dadlerj commented on client/web/src/site-admin/SiteAdminPingsPage.tsx
> +                                    <li>Provider</li>
Same

2023-12-12 16:45 UTC, dadlerj commented on doc/admin/pings.md
> +    - Chat, fast chat and completion model names (only for "sourcegraph" provider)
```suggestion
    - Chat, fast chat, and completion model names (only for "sourcegraph" provider)
```

2023-12-12 16:53 UTC, taras-yemets commented on client/web/src/site-admin/SiteAdminPingsPage.tsx
> +                                    <li>Provider</li>
Addressed in https://github.com/sourcegraph/sourcegraph/pull/58848/commits/0faaf3ea737ebe67e8d415809352ca06aa447313: Mentioned all currently [supported completion providers](https://github.com/sourcegraph/sourcegraph/blob/82b5f4f5d73f56e31adfe7f5bd82bf2a4206cd46/internal/conf/conftypes/consts.go#L32-L39).

2023-12-12 17:46 UTC, merged