Docs: Replaced the link of slack with a discord server for the open source contributors
sourcegraph/sourcegraph pull request #58873
Opened 2023-12-09 12:15 UTC by ibilalkayy

## Test plan

Hey @jdorfman, Last week, we discussed the Slack link for the open-source contributors [here](https://github.com/sourcegraph/sourcegraph/discussions/58672) and you raised an [issue](https://github.com/sourcegraph/sourcegraph/issues/58700) also. Now I have replaced the link of it with a Discord server because the Slack channel was deleted.

![Screenshot from 2023-12-09 17-12-03](https://github.com/sourcegraph/sourcegraph/assets/64713734/de476a6c-a41f-4d20-82d0-58bf6c7d0ec6)

2023-12-12 15:34 UTC, jdorfman requested changes

2023-12-12 15:34 UTC, jdorfman commented on doc/dev/setup/quickstart.md
> +> - [As an open source contributor](https://discord.gg/s2qDtYGnAE)
Use: https://discord.com/servers/sourcegraph-969688426372825169

2023-12-17 05:33 UTC, ibilalkayy commented
I finally updated the link with your given one.

2023-12-19 05:17 UTC, jdorfman approved these changes

2023-12-22 16:30 UTC, closed without merging