frontend/auth: implement ip allowlist
sourcegraph/sourcegraph pull request #58877
Opened 2023-12-11 04:00 UTC by michaellzc

## Test plan

2023-12-11 04:01 UTC, michaellzc commented
Current dependencies on/for this PR:
* main
  * **PR #58877** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/58877?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/58877?utm_source=stack-comment).

2023-12-11 04:06 UTC, michaellzc commented on cmd/frontend/internal/cli/http.go
> +	sm.Handle(urlPathPrefix+"/", ipAllowlistMiddleware.Handle(http.StripPrefix(urlPathPrefix, secureHeadersMiddleware(assetHandler, crossOriginPolicyAssets))))
this wraps the ip allowlist at the outest layer, so it's always run first before even attempting anything else

2023-12-11 17:33 UTC, evict requested changes
I like the idea, but there are some concerns around IP spoofing with some of the supplied headers. We could add a trusted proxy/lb field, so we know after which IP we can trust the client IP? I also would love to see some tests for the new behaviour.

2023-12-11 17:33 UTC, evict commented on cmd/frontend/auth/ipallowlist/checker/checker.go
> +		return nil
You could use a `map[string]struct{}`, then you don't have to iterate over all the list for existence checks.

2023-12-11 17:33 UTC, evict commented on cmd/frontend/auth/ipallowlist/checker/checker.go
> +		}
This can be spoofed if the using the `X-Forwarded-For` header with a Google Loadbalancer: https://cloud.google.com/load-balancing/docs/https/#x-forwarded-for_header.  [The sample applies for](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#x-forwarded-for) CF as well.

2023-12-11 18:45 UTC, michaellzc commented on cmd/frontend/auth/ipallowlist/checker/checker.go
> +		}
yeah, that's a known limitation as I documented in the code and user-facing docs.

the admin is responsible for ensuring the header are trusted. For example:

user -> cloudflare proxy -> application load balancer -> sourcegraph frontend svc

the admin needs to ensure the ALB only accepts connection from cloudflare edge servers, and use [CF-Connecting-IP](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#cf-connecting-ip) to infer the real user IP.

2023-12-11 20:28 UTC, michaellzc commented
> I like the idea, but there are some concerns around IP spoofing with some of the supplied headers. We could add a trusted proxy/lb field, so we know after which IP we can trust the client IP? I also would love to see some tests for the new behaviour.

added some tests.

we can add `remoteAddr[]` for addition check when `userHeaders` is in used

2023-12-11 20:32 UTC, keegancsmith reviewed
Are there any other systems which make requests into sourcegraph? The only thing that comes to mind is webhooks. Maybe worth mentioning in the docs.

Additionally all the code you are adding is only used by cmd/frontend. Feels like it should all live under frontend/internal.

I just did a quick pass by review which is why I didn't approve, can do a deeper review if ya like.

2023-12-11 20:32 UTC, keegancsmith commented on cmd/frontend/auth/ipallowlist/checker/checker.go
> +	errorMessageTmpl *template.Template
You could simplify a lot of the logic you have here around synchronization by flipping how you think of this from a bunch of little fields, to something that is computed from state (eg config, envvars)  and you just do a single atomic load to get the latest version of it.

For example right now you don't have any protection for reads on errorMessageTmpl even though it can be written to concurrently.

A useful primitive we have for this is the conf.Cached function.

2023-12-11 23:36 UTC, michaellzc commented on cmd/frontend/auth/ipallowlist/checker/checker.go
> +	errorMessageTmpl *template.Template
nice, thank you. the code is much better now.

2023-12-12 00:46 UTC, bobheadxi commented on doc/admin/auth/index.md
> +## IP Allow List
nit - I think allowlist is generally one word? you use it as such in most of your docstrings as well

2023-12-12 00:53 UTC, bobheadxi commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	}
are we sure we want to error out at startup? It looks like `Checker` is mostly stateless, and resolves the most recent configuration from the computed `configResolver` every time we authorize a request, so if an error occurs it'll show up in logs there. Preventing startup on a misconfiguration in site config seems difficult to deal with

2023-12-12 00:53 UTC, bobheadxi commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +// to subscribe to configuration changes in the background.
I think there's no longer a `Start()`:

```suggestion
// New returns a new Checker.
```

2023-12-12 03:18 UTC, michaellzc commented on schema/site.schema.json
> +        },
added the concept of `trustedClientIpAddress`. if `Remote.Addr` matches one of these, any further check will be bypass.

cc @evict

2023-12-12 03:18 UTC, michaellzc commented
> Are there any other systems which make requests into sourcegraph? The only thing that comes to mind is webhooks. Maybe worth mentioning in the docs.
> 
> Additionally all the code you are adding is only used by cmd/frontend. Feels like it should all live under frontend/internal.
> 
> I just did a quick pass by review which is why I didn't approve, can do a deeper review if ya like.

thank you. it should be good for a proper review now.

2023-12-12 03:19 UTC, michaellzc commented on cmd/frontend/internal/cli/http.go
> +	h = ipAllowlistMiddleware.Handle(h)
@evict this ensures we always run ip allowlist first before touching anything else

2023-12-12 10:53 UTC, evict approved these changes
Nice work and a nice feature to have! 🚀

2023-12-12 12:24 UTC, filiphaftek approved these changes
Very nice feature @michaellzc ! My only concern is how to highlight, that enabling this feature without properly setting `trustedClientIpAddress` could break instance - would this make sense to enforce having `trustedClientIpAddress` even if empty? So admin is aware that their disabled this feature on purpose.

2023-12-12 15:29 UTC, michaellzc commented on schema/schema.go
> +	UserIpRequestHeaders []string `json:"userIpRequestHeaders,omitempty"`
ClientIp only cares about connect (like TCP, so no HTTP header), UserIp could be either client IP or header from a trusted header.

So, fs matches TrustedClientIpAddress, userIp check will be bypass

2023-12-12 16:08 UTC, michaellzc commented
> Very nice feature @michaellzc ! My only concern is how to highlight, that enabling this feature without properly setting `trustedClientIpAddress` could break instance - would this make sense to enforce having `trustedClientIpAddress` even if empty? So admin is aware that their disabled this feature on purpose.

I am hesitant to do so, cuz it may not be needed depending on the deployment type. I think our docs should cover this case. Also, they can always access the instance from localhost.

2023-12-12 23:26 UTC, daxmc99 commented
> This will break inter-pod communication
Looking at https://stackoverflow.com/questions/61847788/inquiring-pod-and-service-subnets-from-inside-kubernetes-cluster it also appears there is no easy solution here. 

That is my biggest concern for end-users. A site admin is not necessarily a DevOps or network engineer. Not blocking but something where it would be nice to have some tooltip inform the cluster of current IP address of the pod so they consider ensuring local comms still work. 

Lastly, we could request the full list of endpoints in our namespace and automatically add them as whitelisted (might be too much for this but a possibility) 
We have done this [before](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/endpoint/k8s.go?L37)

2023-12-12 23:37 UTC, michaellzc commented
> That is my biggest concern for end-users. A site admin is not necessarily a DevOps or network engineer. Not blocking but something where it would be nice to have some tooltip inform the user of current IP address of the pod so they consider ensuring local comms still work.

local comm will always work since `127.0.0.1` is added to trusted client IP, which bypass any further check.

> Looking at https://stackoverflow.com/questions/61847788/inquiring-pod-and-service-subnets-from-inside-kubernetes-cluster it also appears there is no easy solution here.

> Lastly, we could request the full list of endpoints in our namespace and automatically add them as whitelisted (might be too much for this but a possibility) We have done this [before](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/endpoint/k8s.go?L37)

yeah, this will require pulling all endpoints (they are ephemeral), and update the list on the fly. that feels like a lot of work, and customers may not like RBAC.

Also, this approach only works for k8s. If customer is on docker-compose, we're out of luck.

2023-12-13 10:35 UTC, pjlast approved these changes

2023-12-13 11:28 UTC, evict commented
> > That is my biggest concern for end-users. A site admin is not necessarily a DevOps or network engineer. Not blocking but something where it would be nice to have some tooltip inform the user of current IP address of the pod so they consider ensuring local comms still work.
> 
> local comm will always work since `127.0.0.1` is added to trusted client IP, which bypass any further check.
> 
> > Looking at https://stackoverflow.com/questions/61847788/inquiring-pod-and-service-subnets-from-inside-kubernetes-cluster it also appears there is no easy solution here.
> 
> > Lastly, we could request the full list of endpoints in our namespace and automatically add them as whitelisted (might be too much for this but a possibility) We have done this [before](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/endpoint/k8s.go?L37)
> 
> yeah, this will require pulling all endpoints (they are ephemeral), and update the list on the fly. that feels like a lot of work, and customers may not like RBAC.
> 
> Also, this approach only works for k8s. If customer is on docker-compose, we're out of luck. unless we run another privileged service that has access to the docker daemon, and query from it.
> 
> My take is: a niche use case, and only Cloud will use it. Generally customers are better off just deploying in a private network or do filtering at the LB.



> > That is my biggest concern for end-users. A site admin is not necessarily a DevOps or network engineer. Not blocking but something where it would be nice to have some tooltip inform the user of current IP address of the pod so they consider ensuring local comms still work.
> 
> local comm will always work since `127.0.0.1` is added to trusted client IP, which bypass any further check.
> 
> > Looking at https://stackoverflow.com/questions/61847788/inquiring-pod-and-service-subnets-from-inside-kubernetes-cluster it also appears there is no easy solution here.
> 
> > Lastly, we could request the full list of endpoints in our namespace and automatically add them as whitelisted (might be too much for this but a possibility) We have done this [before](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/endpoint/k8s.go?L37)
> 
> yeah, this will require pulling all endpoints (they are ephemeral), and update the list on the fly. that feels like a lot of work, and customers may not like RBAC.
> 
> Also, this approach only works for k8s. If customer is on docker-compose, we're out of luck. unless we run another privileged service that has access to the docker daemon, and query from it.
> 
> My take is: a niche use case, and only Cloud will use it. Generally customers are better off just deploying in a private network or do filtering at the LB.

@michaellzc you can also opt to use [Gitea's hostmatcher](https://pkg.go.dev/code.gitea.io/gitea@v1.18.0/modules/hostmatcher) for the matching logic. You can then easily allow all private ranges using  `MatchBuiltinPrivate` as a hostlist in an allowlis. It's quite flexible and we're already [using it for external connections](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@cc03635fdd41d5a829e81e7b50ac6492299bb604/-/blob/internal/httpcli/client.go?L443-449).

2023-12-13 12:11 UTC, keegancsmith commented
> My take is: a niche use case, and only Cloud will use it. Generally customers are better off just deploying in a private network or do filtering at the LB.

Why can't cloud do the same?

2023-12-13 14:10 UTC, andreeleuterio commented
@keegancsmith Cloud was doing this on the Cloudflare level but a recent Cloudflare migration pulled the rug from under us and we can no longer use terraform to manage these allowlists. They changed their APIs so that we can no longer manage multiple Cloudflare rules in separate tf namespaces. The GCP LB was also restrictive in its options and did not allow for us to have as many CIDR ranges as we needed in the rules.

2023-12-13 14:20 UTC, keegancsmith approved these changes
LGTM. A bunch of mostly minor feedback, but some may make you delete a bunch of code :)

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	if ok := containsIP(clientIp, cfg.trustedClientIps, cfg.trustedClientRanges); ok {
very minor: I think its clearer to not use the indirection of the ok variable here, since you can more easily "read" what the conditional is saying. eg if containsIP(... and below if !containsIP(...

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +		return errors.Wrap(err, "execute error message template")
if we end up in this situation, its useful to also include the original `msg`.

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +		return errors.Newf(msg)
Newf should only have format strings as the first argument, if msg contains format strings in it you will end up with a formatting error in your string. Same applies below when you pass in buf.String(). I think you can just do errors.New

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	}
if we fail to parse TrustedClientIpAddress then we will end up with a config without localhost. You should append in localhost independently of parsing user input.

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +		if v := os.Getenv("AUTH_ALLOWED_IP_ADDRESS_USER_IP_REQUEST_HEADERS"); v != "" {
you should make it clearer in the name that this is an override given it behaves differently to the rest.

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	configResolver = conf.Cached(getConfig)
If we only expect cloud to use this, will they ever configure it via the site config? Or will they only use environment variables?

If the latter, then I would consider only exposing this as envvars and removing the logic around site configuration. That would simplify this a bunch and avoids another feature we need to support that customers may use.

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	if ok := containsIP(clientIp, cfg.trustedClientIps, cfg.trustedClientRanges); ok {
there is coupling here which may bite us down the road. If trustedClient* is empty this will return true, and we will never do the other checks. The coupling is that it will never be empty due to use always having localhost. But that feels like the sort of change we might accidently make.

You could adjust the signature of the function to explicitly encode the empty return. Or maybe adjust the name, since this isn't really containsIP, but containsIPOrEmpty

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/ipallowlist.go
> +				w.Write([]byte(err.Error()))
you need to return here

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	}
unnecessary to check this. We never check if this is nil, it is implied it is always set.

2023-12-13 14:20 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	}
is it worth failing the startup of frontend if misconfigured? It looks like the decision was made to instead just log. I think you can likely update New to not return an error, which simplifies handling at the callsites for it and ipallowlist.

2023-12-13 14:21 UTC, keegancsmith commented
> @keegancsmith Cloud was doing this on the Cloudflare level but a recent Cloudflare migration pulled the rug from under us and we can no longer use terraform to manage these allowlists. They changed their APIs so that we can no longer manage multiple Cloudflare rules in separate tf namespaces. The GCP LB was also restrictive in its options and did not allow for us to have as many CIDR ranges as we needed in the rules.

To play the devils advocate then, why not configure in the kubernetes ingress? I assuming that is likely just nginx under the hood :)

2023-12-13 17:20 UTC, michaellzc commented
> > @keegancsmith Cloud was doing this on the Cloudflare level but a recent Cloudflare migration pulled the rug from under us and we can no longer use terraform to manage these allowlists. They changed their APIs so that we can no longer manage multiple Cloudflare rules in separate tf namespaces. The GCP LB was also restrictive in its options and did not allow for us to have as many CIDR ranges as we needed in the rules.
> 
> To play the devils advocate then, why not configure in the kubernetes ingress? I assuming that is likely just nginx under the hood :)

we don't run our own ingress (e.g., nginx controller) on Cloud, but use GCP external application load balancer. The filtering rule syntax available (Cloud Armor, GCP's WAF solution) for GCP ALB does not work with our current setup.

Below is the lifecycle of a user accessing frontend on a Cloud instance:

users -> Cloudflare proxy -> Cloud Armor -> GCP ALB -> frontend

Cloud Armor is configured to prevent origin bypass attacks, i.e., only accept connections from Cloudflare proxy. 

When IP allowlist is enabled, we create rules in Cloudflare that are evaluated in the Cloudflare proxy. Like what @andreeleuterio described, this path no longer works.

> Cloudflare proxy adds `CF-Connecting-IP` header to all proxied requests to reflect real user IP.

Cloud Armor rule syntax is impossible to filter on connection IP and user IP (from headers) simultaneously. This could change if we move the WAF capability to Cloud Armor from Cloudflare, but we are not dropping it anytime soon.

users -> Cloud Armor -> GCP ALB -> frontend

2023-12-13 17:48 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	authorizedClientRanges []net.IPNet
for ipv4, we can just append `/32`. I am not sure if ipv6 works the same tho, without digging into another rabbit hole, I'll keep it the way it is.

2023-12-13 17:51 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	configResolver = conf.Cached(getConfig)
on Cloud, Cloud will set some stable IP allowlist via env var to ensure internal comm still works (this will prevent user from accidentally removing internal IP addresses from site config)

then customers will manage their own IP allowlist from the site config.

2023-12-13 18:00 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	if ok := containsIP(clientIp, cfg.trustedClientIps, cfg.trustedClientRanges); ok {
I decided to offload this check to the caller, and explicty check if empty. more code but less gotchat haha

2023-12-13 18:02 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +		return errors.Wrap(err, "execute error message template")
ended up returnning a multi error

2023-12-13 18:03 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	if ok := containsIP(clientIp, cfg.trustedClientIps, cfg.trustedClientRanges); ok {
fixed

2023-12-13 18:17 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +			addr := strings.Split(allowlist, ",")
whitespace separated feels kind of weird to me, maybe just I've never used it before.

took a glance of the usage in` sourcegra/sourcegraph`, it seems like we have a mix use of whitesapce and comma separated config as a string, but the majority are still comma separated.

how about adding a new helper to `internal/env`?

```go
func GetSliceFunc[V any](name string, defaultValues []V, description string, parse func(v string) (V, error)) ([]V, error)
```

2023-12-13 20:00 UTC, keegancsmith commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +			addr := strings.Split(allowlist, ",")
Only issue is how will you handle errors here when this is running at init time? The env package normally calls these helpers Must*, so panics if it runs into an error.

Alternatively you can just have a simple unexported helper in this package which does what you want and isn't as generic:

```go
func getEnvCommaSeparated(name string) []string {
  vals := strings.Split(os.Getenv(name), ",")
  filtered := vals[:0]
  for _, s := range vals {
    s = strings.TrimSpace(s)
    if s != "" {
      filtered = append(filtered, s)
    }
  }
  return filtered
}
```

2023-12-13 20:44 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +	}
fixed

2023-12-13 20:44 UTC, michaellzc commented on cmd/frontend/internal/auth/ipallowlist/checker/checker.go
> +		if allowlist := os.Getenv("AUTH_ALLOWED_IP_ADDRESS_STABLE_USER_IP_ALLOWLIST"); allowlist != "" {
fixed, move to config builder method

2023-12-13 22:11 UTC, merged