Gitlab Native integration: Fix code element target selector (#58931)
sourcegraph/sourcegraph pull request #58941
Opened 2023-12-12 18:40 UTC by vovakulikov

* Fix code element target selector
* Support div and span like lines

(cherry picked from commit 9b829847b91d907e54bbba4347fd03bc3bc7ec52)

## Test plan
- CI is passing

2023-12-12 18:58 UTC, jasonhawkharris approved these changes
LGTM

2023-12-12 18:59 UTC, camdencheek requested changes
> (cherry picked from commit https://github.com/sourcegraph/sourcegraph/commit/9b829847b91d907e54bbba4347fd03bc3bc7ec52)

I would recommend we always update the branch to a commit on main, otherwise we're going to have to deal with merge conflicts forever and ever

2023-12-12 19:05 UTC, peterguy commented
> > (cherry picked from commit [9b82984](https://github.com/sourcegraph/sourcegraph/commit/9b829847b91d907e54bbba4347fd03bc3bc7ec52))
> 
> I would recommend we always update the branch to a commit on main, otherwise we're going to have to deal with merge conflicts forever and ever

Do you mean @vovakulikov should rebase `bext/fix-code-target-selector` first? Looks like he's picking one commit from that branch for this PR, but that branch is pretty out of date.

2023-12-12 19:18 UTC, vovakulikov commented
@camdencheek I actually tried this a few days ago, just to make sure I understand, do you suggest that I merge main into bext/release?

2023-12-12 20:13 UTC, camdencheek commented
> do you suggest that I merge main into bext/release?

Yes, specifically "rebase and merge", not "squash and merge." We want `bext/release` to be pointing to something on the history of `main`. Really, it would probably be best to just release with tags on `main` rather than by merging to this branch, but that's not really something I want to tackle right now 🙂

2023-12-12 20:24 UTC, vovakulikov commented
@camdencheek got it, here is rebase PR https://github.com/sourcegraph/sourcegraph/pull/58946

2023-12-13 17:23 UTC, camdencheek commented
Thanks! This one good to close then?

2023-12-14 14:10 UTC, closed without merging