ci: permit changes to doc/cloud/*
sourcegraph/sourcegraph pull request #59189
Opened 2023-12-21 23:31 UTC by michaellzc

## Test plan

2023-12-21 23:31 UTC, michaellzc commented
Current dependencies on/for this PR:
* `main`
  * **PR #59189** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/59189?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/59189?utm_source=stack-comment).

2023-12-21 23:34 UTC, eseliger approved these changes

2023-12-21 23:34 UTC, eseliger commented on doc/cloud/index.md
> +### Private Connectivit (test remote later)
is this change intentional?

2023-12-21 23:34 UTC, michaellzc commented on doc/cloud/index.md
> +### Private Connectivit (test remote later)
yeah going to revert later after pasing the build as test plan

2023-12-21 23:44 UTC, jamesmcnamara approved these changes

2023-12-22 00:04 UTC, jamesmcnamara requested changes
Sorry my github UI is currently not loading very effectively so I can't leave this inline.

Currently the doubly-nested continue is causing the `continue` to have no effect. I think you'll need to wrap it in a function i.e.

```go
func isDiffAllowed(filename string) bool {
  for _, allowed := range allowDocChangesPrefixAllowlist {
    if strings.HasPrefix(allowed, filename) {
      return true
    }
  }
  return false
}
```

And then later:
```go
for filename := range diff {
  if !isDiffAllowed(filename) {
    diffset[filename] = struct{}{}
  }
}
```

2023-12-22 00:51 UTC, jamesmcnamara approved these changes

2023-12-22 01:27 UTC, michaellzc commented on doc/cloud/index.md
> +### Private Connectivit (test remote later)
```suggestion
### Private Connectivity
```

2023-12-22 01:34 UTC, merged