Add logic to auto disable google signups from non-gmail domain for 24hrs if too many signups from same domain.
sourcegraph/sourcegraph pull request #59243
Opened 2023-12-27 12:57 UTC by thenamankumar

1. Add logic to auto-disable Google signups from non-Gmail domains during a 24-hour window if too many (> 30) signups from the same domain.
2. Check if is email domain is banned based on SRC_EMAIL_DOMAIN_DENY_LIST for social logins as well. Currently only used for user password signup.

## Test plan
.

2023-12-27 14:23 UTC, evict commented on cmd/frontend/auth/user.go
> +					redisStore.SetEx(key, 24*60*60, 1)
```suggestion
					redisStore.SetEx(key, 24 * time.Hour, 1)
```

2023-12-27 14:43 UTC, evict reviewed
If this is specifically for Google Workspace, can we move the checks to here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@1c1e795c2777444182be17769ae075b9623f35a5/-/blob/cmd/frontend/internal/auth/openidconnect/middleware.go?L313-318? 

We can then also add a field to the site-config so we don't have to hardcode the account auth provider and the limts:

```
  "auth.providers": [
    {
      "type": "openidconnect",
      "issuer": "https://accounts.google.com", // All Google Workspace domains use this issuer URI.
      "clientID": "my-client-id",
      "clientSecret": "my-client-secret",
      "requireEmailDomain": "example.com"
      "maxDomainSignUps": 30,
    }
```

2023-12-27 14:43 UTC, evict commented on cmd/frontend/auth/user.go
> +				}
Can we move this code into a separate function? You could put this in the security package for instance, make it so that we could call it like `IsSignUpAllowedForDomain(serviceID, domain)`? Then we can easily re-use this for other sign-ups.

2023-12-28 16:33 UTC, thenamankumar commented on cmd/frontend/auth/user.go
> +				}
Have moved this to a separate function inside security package.

2023-12-28 16:36 UTC, thenamankumar commented
> If this is specifically for Google Workspace, can we move the checks to here

As this is experimental and may extend to other signup options based on abuse behaviour in future, I have not moved the logic. 

I have also not made the limit controlled by the site config for now. Recently, it has been tricky to update the configuration and then wait for the cache to refresh, making fighting with abuse even more difficult. 

If we decide to keep this logic for longer, will integrate it with the site config. This is highly unlikely though as the new SAMS system is under works and this abuse prevention logic will move there.

2023-12-28 18:37 UTC, evict commented on internal/security/security.go
> +		redisStore.SetEx(key, 24*60*60, 1)
Can we handle the error for `SetEx`? And you can use `int(24 * time.Hour)` here for readability as well.

2023-12-28 18:37 UTC, evict commented on cmd/frontend/auth/user.go
> +			}
This logic is repeated in the if-statement below as well. Can you create a function instead?

2023-12-28 18:40 UTC, evict reviewed
Did you manage to test the changes? If so, can you provide that inside the test plan ?

2023-12-28 18:59 UTC, chenkc805 commented
Thanks Naman. What's the error message we show to users if their domain gets blocked for 24 hours from too many signups?

2023-12-28 18:59 UTC, chenkc805 requested changes

2023-12-28 18:59 UTC, chenkc805 commented on schema/site.schema.json
> +      "default": 0,
Should this be 30?

2023-12-28 19:01 UTC, thenamankumar commented on schema/site.schema.json
> +      "default": 0,
No by default lets keep this 0 (disabled) in the code. I'll create a separate PR in separate repo to update the prod site config and set it to 30. 

Also just to confirm with you, 30 sounds good?

2023-12-28 19:48 UTC, chenkc805 commented on schema/site.schema.json
> +      "default": 0,
Gotcha. Yeah 30 sounds good.

2023-12-29 04:49 UTC, chenkc805 commented on schema/site.schema.json
> +      "default": 0,
And confirming, 0 won't automatically ban all non-gmail domains right? Because if I follow the logic:
- Add logic to auto-disable Google signups from non-Gmail domains during a 24-hour window if too many (> N) signups from the same domain.
  - If N = 0, then all non-gmail domains will be banned. 

If I'm following, should this be a very high number instead, like 10000 as a default?

2023-12-29 07:12 UTC, thenamankumar commented on schema/site.schema.json
> +      "default": 0,
N = 0 means disabled. This check won't be performed. It's taken care of in the code.

2023-12-29 17:47 UTC, chenkc805 commented
> Thanks Naman. What's the error message we show to users if their domain gets blocked for 24 hours from too many signups?

@thenamankumar friendly bump on this ^^

2024-01-01 11:29 UTC, thenamankumar commented
> > Thanks Naman. What's the error message we show to users if their domain gets blocked for 24 hours from too many signups?
> 
> @thenamankumar friendly bump on this ^^

"this email address is not allowed to register"

2024-01-01 11:56 UTC, thenamankumar commented
> Did you manage to test the changes? If so, can you provide that inside the test plan ?

I did test the non-google auth flows and they seem to work fine. Google Oauth2.0 [doesn't allow](https://developers.google.com/identity/protocols/oauth2/policies#secure-response-handling) local Oauth connections. 

Except the one if condition everything else is well tested.  `if acct.AccountSpec.ServiceID == "https://accounts.google.com"`

Verified from the prod DB that the serviced will be `"https://accounts.google.com"` only.

2024-01-02 00:11 UTC, chenkc805 commented
Can we change the message to "There seem to be too many signups occurring today. Please try again at a later time." 

I know this may be giving away some information but I'm hoping that the actual blocking mechanism is annoying enough and that this copy is vague enough for a bad actor but kind of helpful for real users. 

Once that's changed, I'll approve.

2024-01-02 06:41 UTC, thenamankumar commented
Error message updated @chenkc805

2024-01-02 09:52 UTC, pjlast approved these changes

2024-01-02 10:07 UTC, merged

2024-01-02 14:30 UTC, vdavid commented
This is merged but the test plan is still empty. I think we need test plans for compliance reasons, plus also, as a team member it's helpful for me to know how much we tested this.

2024-01-02 14:31 UTC, vdavid commented
Forgot to ping @thenamankumar with my last message