Improves locals queries for Go
sourcegraph/sourcegraph pull request #59320
Opened 2024-01-04 08:27 UTC by kritzcreek

Fixes the go specific part of #57791

Stops recording top-level functions and var bindings as locals with our Go queries.

To allow skipping top-level var bindings I added the `skip` feature we talked about yesterday to our locals DSL.

## Test plan

Tested locally and in our test snapshots

2024-01-04 10:45 UTC, varungandhi-src commented
> Fixes the go specific part of ...

I've added a checklist to the issue so that we can track what languages need updating. I've also linked this PR from the Go item. For future PRs, it'd be helpful to check things off that checklist and link the PRs similarly. (Mentioning this in case I forget to update that issue myself)

2024-01-04 11:27 UTC, varungandhi-src requested changes
Directionally, this looks correct, but please add more test cases.

2024-01-04 11:27 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_functions.snap
> -//     ^^^^^^^^^ definition local 2
Please update this test to make sure that we're not emitting local symbols for other non-local entities like:
- consts
- types
- field names in types
- methods in interface definitions
- references to "inherited" interfaces in interface definitions: `type B interface {}; type A interface { B }`
- type lists in interface definitions like `interface { int | string }`
- method definitions (this test currently only has free functions)

I'm not 100% sure if that covers everything.

2024-01-04 11:27 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go.snap
>    func main() {
It seems like the 3 different test files are essentially checking the behavior of locals, just for different scoping structures/patterns, right? Thoughts on merging them? It seems a bit hard to see what cases are covered/what cases are missing when the tests are split across different files but are conceptually testing the same thing.

2024-01-04 11:27 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-locals.scm
> +;;  (#set! "hoist" "function"))
There seems to be some similarity between `#set! "scope" "global"` and `@definition.skip` in that both are saying "this is a global entity, don't treat it as a local". So I'm not super clear on whether we need both... Do we?

I wonder if the `#set! "scope"` functionality can be removed entirely? With this removal, only the Java grammar will be using `#set! "scope" "parent"`. 🤔

2024-01-04 11:27 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go.snap
> +   }
I think we're missing test cases for `switch` and `for`? They have similar affordances. E.g. this is allowed:

```
	switch s := 0; s + 1 {
	case s + 2:
		_ = s
	default:
		_ = s
	}
    // s cannot be used here
```

`for` also allows defining local variables, e.g. `for i := 0; i < 3; i++`.

Please add them if they're missing.

2024-01-04 11:45 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/scip-syntax/docs/locals-query-dsl.md
> +```
There's no decision from my side yet. I've decided to go with this approach for now because it was easy to implement, which didn't seem worthy of writing down.
My plan was to go with it for a bit and see if it satisfies the immediate cases we know about.

2024-01-04 11:45 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-locals.scm
> +  (var_spec name: (identifier) @definition.skip)))
I don't think anything in here handles const definitions yet. I can look into adding those.

2024-01-04 11:45 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/scip-syntax/queries/go/scip-locals.scm
> +;;  (#set! "hoist" "function"))
There is no `#set! "scope"` functionality in the old or the new implementation. I'm not sure why this was here, I just didn't remove it.
If we're sure `scip-locals.scm` is exclusive to the locals.rs implementation I can get rid of these attributes.

2024-01-04 11:45 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_functions-2.snap
> -  hoisted_def Something (7, 5)-(7, 14)
I gave this a try before, but for some reason insta made this difficult. I'll try again and report back.

2024-01-04 11:45 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_go.snap
>    func main() {
Yeah I thought this was a bit silly as well. One thing that's a bit of a shame when merging all of them, is that a single line addition in the test file causes the entire snapshot to light up in the diff, because all line numbers change.

I'll merge the test cases for now, and we can decide if we want a multi-level structure at some point (e.g. `testdata/go/if.go`)

2024-01-04 13:28 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__can_do_functions-2.snap
> -  hoisted_def Something (7, 5)-(7, 14)
Okay, I remember now. Because it's macro nonsense we need to repeat the test names multiple times, but it's probably still better than bad output names. I added a commit for explicitly naming these tests.
Once I've merged the different go tests into one file, we can think about the naming scheme.

2024-01-05 09:49 UTC, varungandhi-src approved these changes
There is one minor comment where I thought of some more tests which I didn't realize were missing before, but LGTM otherwise.

2024-01-05 09:49 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/scip-syntax/src/snapshots/scip_syntax__locals__test__go_occurrences.snap
> +// ^^^^^ definition local 1
We've covered the different definition forms, but I just noticed that the various reference forms are not covered. Maybe it's worthwhile to make sure we're emitting references for them as expected?

- Assignment `a = 3` (we have plenty of `:=` but only assignments to globals from a quick glance)
- Slice/map assignment `x[y] = 3`
- Assignment after dereference: `*x = 3`

There's also the range syntax `x[a:b]` but I don't think that's allowed as an lvalue.

2024-01-05 14:40 UTC, merged