Filters Panel: Add reset all filters button
sourcegraph/sourcegraph pull request #60024
Opened 2024-01-31 21:04 UTC by jasonhawkharris

This adds a button that resets all chosen filters currently selected in the filters panel.

## Test plan
Test manually. CI/CD passing

2024-01-31 21:15 UTC, vovakulikov commented
@taiyab I really don't know about link-like button. I'm biased here because I always don't like this variation, it looks like a link but it doesn't do anything with URL and it confuses me because of this. Visually it looks a bit off as well since button above has visible border area and this button doesn't. Maybe we could use here outline secondary again. (I think button link was a mistake in our wildcard :) )

<img width="502" alt="Screenshot 2024-01-31 at 18 12 49" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/d72bf3dc-3687-4d62-b7d5-bf5bac52adbb">

2024-01-31 21:17 UTC, camdencheek reviewed
The code itself looks good, but let's take a pass at the design. Seconding Vova's comments about the link-like button, and also it takes up quite a bit of valuable vertical space for what I expect is a pretty rarely-used action.

![CleanShot 2024-01-31 at 14 15 51@2x](https://github.com/sourcegraph/sourcegraph/assets/12631702/078d4341-b5d7-42e8-8c8b-a3201018283d)

2024-01-31 21:17 UTC, camdencheek commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
> +                                aria-label="Reset all filters"
In this case, I think we should use `aria-hidden={true}` since the purpose of the button exists in the label itself, so the icon is just visual sparkle.

2024-01-31 21:39 UTC, jasonhawkharris commented
@taiyab @camdencheek mentioned the possibility of maybe having the buttons inline and with much less information. Maybe even just the icons. Thoughts?

2024-02-01 12:44 UTC, taiyab commented
>@taiyab I really don't know about link-like button. I'm biased here because I always don't like this variation, it looks like a link but it doesn't do anything with URL and it confuses me because of this. Visually it looks a bit off as well since button above has visible border area and this button doesn't. Maybe we could use here outline secondary again. (I think button link was a mistake in our wildcard :) )

I don't think the link button is a mistake at all, the problem here is that we're really missing another variant I'd like which is a "ghost" button.

A ghost button essentially visually fills the button space on hover with a (in this case) light gray but with no border.

Before hover:
<img width="358" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/635d0a08-50dd-4048-9eaa-83f2af95998a">

During hover:
<img width="345" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/cba4e627-873e-4bc4-a71f-a97ca25ec3ff">

If we can implement something like this, it would work IMO.

> Seconding Vova's comments about the link-like button, and also it takes up quite a bit of valuable vertical space for what I expect is a pretty rarely-used action.

I don't necessarily mind the vertical space taken here (with a bit of tweaking). We could also only have it appear once more than one filter is applied.

For reference, my original treatment had this as a small option inline with a "Filter results" title, however, we probably (rightfully) stripped that out:
<img width="354" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/c1cc016b-f588-4cbf-bbad-18ad1bb124d9">

Alternatively, I'm happy to just delete it. It's not providing *that much* value in a world where you can only apply like 3-4 filters via the panel anyway.

2024-02-02 20:38 UTC, jasonhawkharris commented
Second pass over the design, and added shortcut for clearing filters.

Uploading Screen Recording 2024-02-02 at 1.29.52 PM.mov…

2024-02-02 21:16 UTC, vovakulikov reviewed
@jasonhawkharris a few things that I noticed 
- Since @camdencheek PR about making type filter real filters has been merged we should move filter results title and reset button on the top of the filters panel 

<img width="554" alt="Screenshot 2024-02-02 at 18 09 35" src="https://github.com/sourcegraph/sourcegraph/assets/18492575/0916350c-9b6d-4c22-b1ef-6e667a9a9de4">

- I think we should also add keybinding since we have `kbd` icon with keyboard combination to be able to reset filters from keyboard
- About button, again feel free to ignore here but I think that we should intro this ghost variation button with hover state and also `kbd` icon should be within this button so if I click it filter will be reset (now you have to aim to the reset filter text, which is link)

2024-02-02 21:16 UTC, vovakulikov commented on client/wildcard/src/hooks/useOperatingSystem.ts
> +        detectOS();
why do you need to have a function here? Can you just run this function body in the useEffect directly?

2024-02-02 21:25 UTC, jasonhawkharris commented on client/wildcard/src/hooks/useOperatingSystem.ts
> +        detectOS();
I like reading this line because it's clear what it does:

`const os = useOperatingSystem`

I feel like it's easier to immediately understand than the alternative. I've also found myself needing this info before, so I thought it'd be good to make it a reusable hook.

2024-02-02 22:09 UTC, camdencheek commented on client/wildcard/src/hooks/useOperatingSystem.ts
> +        detectOS();
Why do we need this to be a hook or stateful at all? Couldn't this just be a function that returns the operating system?

2024-02-02 22:14 UTC, camdencheek commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +export const KbdBadge = React.forwardRef(function KbdBadge({
Rather than creating a custom component, we should probably use the [`<kbd>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd) element. That will be more accessible, have better default styling, and will likely require a lot less code

2024-02-03 21:30 UTC, jasonhawkharris commented on client/wildcard/src/hooks/useOperatingSystem.ts
> +        detectOS();
ahhh... sorry I misunderstood. I see what you're saying.

2024-02-03 21:34 UTC, jasonhawkharris commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +export const KbdBadge = React.forwardRef(function KbdBadge({
So, @vovakulikov and I actually chatted about this. Personally, I think the <kbd> element doesn't look great. At first, I wanted to introduce a new badge variant (kbd), but that was handling too much logic, so we came to the conclusion that a new wildcard component would be good for this. I've also found myself needing a better kbd element to introduce keymaps and this solves that problem.

2024-02-05 10:39 UTC, taiyab commented
@vovakulikov Thanks for clarifying on the other related changes.

I think once those are in place we should be good to go.

We should make sure to test the keyboard shortcut button (and the relevant icons) on Windows/Mac, etc.

2024-02-05 10:40 UTC, taiyab reviewed
@vovakulikov Thanks for clarifying on the other related changes.

I think once those are in place we should be good to go.

We should make sure to test the keyboard shortcut button (and the relevant icons) on Windows/Mac, etc.

2024-02-05 15:27 UTC, vovakulikov commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +export const KbdBadge = React.forwardRef(function KbdBadge({
I actually missed the fact that this component doesn't use the `kbd` tag.

 I mean I agree that a separate component is okay here because we have to deal with a global `.kbd` CSS class. And we don't have time to migrate all other kbd UI in the Sourcegraph (probably), So we could do a few things here
 - Have a wildcard component for kbd and still use `kbd` element in this component implementation (as @camdencheek said this should help use with a11y) and then fix styling in this component styles. 
 - If for some reason we can't use `kbd` element in this component we need to make sure that this doesn't different in any way from real kbd (maybe we have to sue aria labels and types there but not sure, never tried to listen kbd elements in VoiceOver really)

2024-02-05 16:40 UTC, camdencheek commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +    if (isArray(kb.selector)) {
nit: instead of using lodash, we can just use builtins

```suggestion
    if (kb.selector instanceof Array) {
```

2024-02-05 16:46 UTC, jasonhawkharris commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +export const KbdBadge = React.forwardRef(function KbdBadge({
@vovakulikov @camdencheek After working with it over the past hour, I think we should irradicate the <kbd> element from the code base. It's difficult to style, the default padding/margins are way off. In general, I think it's just a frustrating element to work on and I think this wildcard component can make all our jobs a lot easier in the future when trying to style these buttons. That's my two cents. I'm happy to do what you all want to do, but just wanted to give my input.

2024-02-05 18:26 UTC, camdencheek requested changes

2024-02-05 18:26 UTC, camdencheek commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +}
Why separate modifier and selector? Sometimes we can have multiple modifiers (cmd+ctrl is fairly common). I also think we can simplify the formatting significantly if this type just becomes `[]string`.

2024-02-05 18:26 UTC, camdencheek commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +            <div className={classNames(styles.keybind, onClick && styles.withCursor)} onClick={onClick}>
What happens if `onClick` is undefined? Wouldn't that evaluate to a class name `false`?

2024-02-05 18:26 UTC, camdencheek commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +}) as ForwardReferenceComponent<'span', KbdBadgeProps>
I don't think we should be casting here. Instead, we should just `export const KbdBadge: ForwardReferenceComponent<'span', KbdBadgeProps>` above so the type system catches any issues.

2024-02-05 18:39 UTC, jasonhawkharris commented on client/wildcard/src/hooks/useOperatingSystem.ts
> +}
@camdencheek If this were the case we'd have to account for the value being undefined on mount... isn't it better to return a hook so that the component updates when it determines the OS?

2024-02-05 18:40 UTC, jasonhawkharris commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +            <div className={classNames(styles.keybind, onClick && styles.withCursor)} onClick={onClick}>
Wouldn't it return nothing at all? Since onClick would evaluate to undefined?

2024-02-05 18:58 UTC, camdencheek commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +}) as ForwardReferenceComponent<'span', KbdBadgeProps>
There's also `satisfies` which could be a good option here as well

2024-02-05 18:59 UTC, camdencheek commented on client/wildcard/src/components/KbdBadge/KbdBadge.tsx
> +            <div className={classNames(styles.keybind, onClick && styles.withCursor)} onClick={onClick}>
Maybe? But then the question is just how does `classNames` handle `undefined`? Have you tested to see if this works with no click handler?

2024-02-05 21:33 UTC, camdencheek approved these changes
Looks great! Thanks for iterating with me

2024-02-06 09:46 UTC, taiyab reviewed
LGTM! Nice work @jasonhawkharris.

2024-02-06 09:46 UTC, taiyab commented on client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
> +    color: var(--oc-gray-6);
We can't use static colors here. We can try `--color-bg-1` here instead.

2024-02-06 09:46 UTC, taiyab commented on client/branded/src/search-ui/results/filters/NewSearchFilters.module.scss
> +    color: var(--gray-06);
Similarly here, we should try `--text-muted`.

2024-02-06 15:51 UTC, vovakulikov commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
> +    const handleKeyDown = useCallback(
@jasonhawkharris Usually all functions that are used only within `useEffect` stay inside useEffect. 
Something like this in this case 

```ts
 useEffect(() => {
        function handleKeyDown(e: KeyboardEvent): void {
            if (e.altKey && e.key === 'Backspace') {
                setSelectedFilters([])
            }
        } 
        
        document.addEventListener('keydown', handleKeyDown)
        
        return () => {
            document.removeEventListener('keydown', handleKeyDown)
        }
    }, [setSelectedFilters])
```

2024-02-06 15:54 UTC, merged

2024-02-06 16:11 UTC, vovakulikov commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
> +    return undefined
There is no need for return undefined, just `return` is enough since `return` without value after returns `undefined` already