Search filters: do not select a type by default
sourcegraph/sourcegraph pull request #60028
Opened 2024-01-31 23:58 UTC by camdencheek

This modifies the types section of the dynamic filters sidebar to not have any type selected by default. This is to better represent the default search behavior where we return code, repositories, and paths in the result set.

[Loom walkthrough](https://www.loom.com/share/947ef0784d0245398839e326e30adc35)

## Test plan

Manual testing that the behavior feels correct.

2024-02-01 14:37 UTC, vovakulikov requested changes
Left a few comments and one question about omitting filters

2024-02-01 14:37 UTC, vovakulikov commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
> +    useEffect(() => {
Can it be also a calculation-like (with useMemo) logic or we need to react on their changes as we do it here in useEffect. I always prefer useMemo and useEffect only when it's absolutely needed (to avoid possible effect races)

2024-02-01 14:37 UTC, vovakulikov commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
> +    const onClickFilterType = useCallback(
Nit: This is my personal policy so feel free to ignore this. I try to follow the next pattern when I name props and their handlers 
- `on[handlerName]` is how we name prop callback in some component (like this ` onClick` in the `FilterTypeList`)
- `handle[EventName]` is how we name callback in consumer for this on-Prop, so here it would be `handleFilterTypeClick`

2024-02-01 14:37 UTC, vovakulikov commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
> -function omitImpossibleFilters(filters: URLQueryFilter[], searchType: SearchFilterType): URLQueryFilter[] {
@camdencheek I think removing this one will cause a regression about preserving filters as you go through different filter types. Try to go to File type, set some language filter and then go to the Repositories filter type. 
Prior to this lang filter will be reset in order to avoid empty state (since repo filter type can't have lang filters)

I checked it manually in this PR and I think this is the case here

2024-02-01 17:22 UTC, camdencheek commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
> -function omitImpossibleFilters(filters: URLQueryFilter[], searchType: SearchFilterType): URLQueryFilter[] {
Aaah shoot. Good catch. Fixed in the latest commit -- thank you!

2024-02-02 10:23 UTC, taiyab commented
Thanks for these changes @camdencheek, great stuff! :)

A few important things from my perspective:

- **I'm very much happy with treating the type list differently.** When originally designing this, I almost saw those at the top-level "categories" that you could use to switch between types, whilst everything below was an actual filter in the traditional sense (hence even adding the "Filter by" title was below the types in design, along with the reset button). Even the type list was treated visually slightly different in that everything could be slightly bigger, to indicate they're the parent categories that the filters below apply to. It almost meant when you hit reset all, it didn't reset the type, but did reset everything else below.

- Overall, I would want this to default to `Code` (which I know that's not how it works today so it's fine it's like this for now). We should continue to work with Search Suite to get alignment on this and push forward changes in the future.

So yea, I'm happy with these being like this right now, but, I would want us to explore and work with Search Suite to see if we can move things in a simpler direction.

2024-02-02 12:20 UTC, taiyab commented
@camdencheek Doing this also means we need to add in a `x` remove filter button on the RHS on the type items in the filter pane.

2024-02-02 14:06 UTC, vovakulikov commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
>          }
Maybe we could use `useLayoutEffect` instead since `useEffect` runs after rendering when layout effect is running before jsx render. This should help with render optimisation when user select/deselect types in filter bar

2024-02-02 14:07 UTC, vovakulikov approved these changes
Code looks good. I don't have strong preferences about how exactly it should work, I leave it to @taiyab

2024-02-02 15:58 UTC, camdencheek commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
>          }
Happy to return to this, but based on what I'm reading [here](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect), it doesn't sound like `useLayoutEffect` is intended for this?

2024-02-02 16:37 UTC, camdencheek commented
@taiyab thanks for the feedback!

> I'm very much happy with treating the type list differently

Yes! I am also happy to treat the type list differently where it makes sense.

Where I think it makes sense right now:
- Show all types at all times to improve discoverability
- Give them different visual treatment to clarify their use as top-level categories

Where I do not think it makes sense right now:
- Selecting a type by default. This is a significant behavior change, and it would make invalid some searches that were previously accepted.
- Mutating the query text. This also breaks some previously valid queries. Additionally, adding the `type:` filter to the query bar duplicates visual information, increasing noise and making it unclear where the source of truth is. This is a behavior difference between the type filters and the subfilters that I don't think is adding value, so in that case, I'd prefer for the behavior to be consistent.

Where I think this makes sense in the future:
- Searching only code by default. Agreed that we should work with the platform team after the release. Definitely still some risk here since we'd no longer be surfacing things like repos in broad, exploratory searches like `sourcegraph`, but seems like something we can mitigate with good design.

> Doing this also means we need to add in a x remove filter button on the RHS on the type items in the filter pane.

Good catch -- added in the latest commit 👍 


![CleanShot 2024-02-02 at 09 37 02@2x](https://github.com/sourcegraph/sourcegraph/assets/12631702/e50c992c-6539-446d-a5f4-2404de2967aa)

2024-02-02 17:09 UTC, merged

2024-02-02 18:54 UTC, vovakulikov commented on client/branded/src/search-ui/results/filters/NewSearchFilters.tsx
>          }
The difference here that useEffect doesn't block rendering and runs after you already can see something on the screen, so there should be possible to see some flashes if query has gotten some type filters and we should reset some URL filters (search filter panel) with useLayoutEffect since react performs this hook after jsx creation but before actual rendering synchronously this should prevent all possible flashes with inconsistent search filters URL state