highlighter: De-couple server code from highlighting
sourcegraph/sourcegraph pull request #60039
Opened 2024-02-01 06:09 UTC by varungandhi-src

Makes partial progress towards https://github.com/sourcegraph/sourcegraph/issues/59792

Addresses feedback from https://github.com/sourcegraph/sourcegraph/pull/59890

- `*Query` types are now moved to the server code.
- syntax-analysis crate no longer depends on Rocket (web server).
  Instead, it just takes a FileInfo struct for highlighting,
  and the server code converts a query into a FileInfo value.
- syntax-analysis crate doesn't depend on JSON for highlighting.
  There is still JSON usage in the ctags bit, but we can
  separate that out in a different PR as this is already quite big.

As part of this, I've introduced different types for the different
grammar names (Syntect/Sublime vs Tree-sitter) so that the code is
easier to follow. For simplicity, we do not eagerly validate
the grammar names on construction, but return an error as part of
highlighting if there is no match found. This matches the old
behavior. In the future, we could clean this up to be more
'correct by construction'.

## Test plan

- [x] Existing tests are passing
- [ ] Test manually by spinning up syntax-highlighter and making sure
      there aren't any issues.

2024-02-01 06:10 UTC, varungandhi-src commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/60039?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #60037** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/60037?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #60038** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/60038?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #60039** <a href="https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/60039?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/sourcegraph/60039?utm_source=stack-comment).

2024-02-01 13:15 UTC, kritzcreek requested changes
Some things that jumped out at me, I'll do another round later.

2024-02-01 13:15 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +        let path = Path::new(&self.path);
Here we're rewrapping the path again.

2024-02-01 13:15 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +impl<'a> FileInfo<'a> {
Any reason for a second impl block, rather than merging the two FileInfo ones?

2024-02-02 03:10 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +    fn extension(&self) -> Option<&str> {
I've elaborated on the doc comment. WDYT now?

2024-02-02 03:10 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +        let path = Path::new(&self.path);
I've simplified the implementation of `extension()` to use `Path::extension` under the hood. The return type being `Option<&str>` makes it easier to match against (e.g. we're doing it for `ncl`) and also pass it to syntect after a simple `unwrap_or("")`

2024-02-02 03:11 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +impl<'a> FileInfo<'a> {
I mostly just copy pasted the code and converted some functions that were in a certain place to method. So I introduced the impl blocks in the same place to avoid moving code around. But it's not a big deal, I've merged the impl blocks.

2024-02-02 03:19 UTC, varungandhi-src commented on docker-images/syntax-highlighter/src/lib.rs
> +pub fn syntect_highlight(q: SourcegraphQuery) -> JsonValue {
Agreed, fixed.

2024-02-02 10:07 UTC, kritzcreek approved these changes
Thanks for the clarification 

EDIT: Actually I couldn't let it rest and opened https://github.com/sourcegraph/sourcegraph/pull/60088 please take a look before merging

2024-02-05 11:12 UTC, merged