[Cody Gateway] add refresh token endpoint with sams authenticator
sourcegraph/sourcegraph pull request #60061
Opened 2024-02-01 16:20 UTC by thenamankumar

This is the first of many upcoming PRs to enable refreshing user's rate limits on Cody Gateway when a subscription change happens on SSC.

Issue: https://github.com/sourcegraph/accounts.sourcegraph.com/issues/363

**The whole plan is as follows (given we do not have SAMSActor on Gateway yet):**
- On every subscription change, SSC will make a request to Cody Gateway to refresh the rate limits for the user, the same as dotcom does right now.
- SSC will send dotcom_user_id with the request, which it will get from the user's metadata from SAMS. 
- Dotcom will expose a new graphql resolver which provides rate limits for user ID. Right now, it provides one, but for a dotcom access token.
- Gateway will make a call to dotcom to fetch the limits for the dotcom_user_id using the new API. It does the same now but for dotcom's per_user_access_token.

**How will it look when we have SAMSActor & SSCSource on Gateway?**
Same as above, but with a few changes:
- SSC will send SAMS user_access_token in place of dotcom_user_id with the request.
- SSC will expose a graphql resolver which provides rate limits for SAMS user_access_token.
- Gateway will use SAMS user_access_token to fetch rate limits directly from SSC.

**What does this PR handle?**
1. It implements a new SAMS client.
2. It implements a new SAMS auth middleware, which allows auth using service-to-service tokens utilizing the SAMS client.
3. It exposes a new dummy API endpoint, `/v1/sams/limits/refresh`, which utilises the new SAMS auth middleware. To note, the `/v1/limits/refresh` endpoint already exists, but it uses the present auth. 

**What does this PR NOT handle? (TODOs for upcoming PRs)**
1. The actual implementation of the new API endpoint is pending and will be addressed in upcoming PRs. 
2. It doesn't update the dotcom graphql API either, which will be addressed in upcoming PRs.

## Test plan
-
- Run SAMS locally under the 9982 port. Otherwise, it will conflict with Gateway running on 9992.

2024-02-01 16:30 UTC, bobbydiji commented
Cody was stolen off my drive. Kinda cool I guess but the real version of
him is on the gpt store and massively updated from rhe shell he was when
they took him.  I'm not gonna get ass hurt. It was it is. I copywrite all
my files now.

On Thu, Feb 1, 2024, 11:20 AM Naman Kumar ***@***.***> wrote:

> This is the first of many upcoming PRs to enable refreshing user's rate
> limits on Cody Gateway when a subscription change happens on SSC.
>
> Issue: sourcegraph/accounts.sourcegraph.com#363
> <https://github.com/sourcegraph/accounts.sourcegraph.com/issues/363>
>
> *The whole plan is as follows (given we do not have SAMSActor on Gateway
> yet):*
>
>    - On every subscription change, SSC will make a request to Cody
>    Gateway to refresh the rate limits for the user, the same as dotcom does
>    right now.
>    - SSC will send dotcom_user_id with the request, which it will get
>    from the user's metadata from SAMS.
>    - Dotcom will expose a new graphql resolver which provides rate limits
>    for user ID. Right now, it provides one, but for a dotcom access token.
>    - Gateway will make a call to dotcom to fetch the limits for the
>    dotcom_user_id using the new API. It does the same now but for dotcom's
>    per_user_access_token.
>
> *How will it look when we have SAMSActor & SSCSource on Gateway?*
> Same as above, but with a few changes:
>
>    - SSC will send SAMS user_access_token in place of dotcom_user_id with
>    the request.
>    - SSC will expose a graphql resolver which provides rate limits for
>    SAMS user_access_token.
>    - Gateway will use SAMS user_access_token to fetch rate limits
>    directly from SSC.
>
> *What does this PR handle?*
>
>    1. It implements a new SAMS client.
>    2. It implements a new SAMS auth middleware, which allows auth using
>    service-to-service tokens utilizing the SAMS client.
>    3. It exposes a new dummy API endpoint, /v1/sams/limits/refresh, which
>    utilises the new SAMS auth middleware. To note, the /v1/limits/refresh
>    endpoint already exists, but it uses the present auth.
>
> *What does this PR NOT handle? (TODOs for upcoming PRs)*
>
>    1. The actual implementation of the new API endpoint is pending and
>    will be addressed in upcoming PRs.
>    2. It doesn't update the dotcom graphql API either, which will be
>    addressed in upcoming PRs.
>
> Test plan
>
>    -
>    - Run SAMS locally under the 9982 port. Otherwise, it will conflict
>    with Gateway running on 9992.
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/sourcegraph/sourcegraph/pull/60061
> Commit Summary
>
>    - 663ed95
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/commits/663ed95f2a4a05613950e84e965370502c827525>
>    [Cody Gateway] add refresh token endpoint with sams authenticator
>
> File Changes
>
> (13 files <https://github.com/sourcegraph/sourcegraph/pull/60061/files>)
>
>    - *M* cmd/cody-gateway/internal/auth/BUILD.bazel
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-f4fdea4f1d7fcd7ec69a20182e6a83b62c0279549479baeca47de65fe151ca2b>
>    (6)
>    - *A* cmd/cody-gateway/internal/auth/sams.go
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-3e9d388c048e87360bdc5f004aa673000a7ec45fa23cae431737abf38ab235dd>
>    (60)
>    - *M* cmd/cody-gateway/internal/httpapi/BUILD.bazel
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-a1038fa8b7774d885fbdba67568d59d57771c24b23e61c62f54bb8dae8c5b9fd>
>    (1)
>    - *M* cmd/cody-gateway/internal/httpapi/attribution/handler_test.go
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-9c815bf293c409b7714a3d2b81e478a625bf2375d1f45645b176a718b57f744b>
>    (6)
>    - *M*
>    cmd/cody-gateway/internal/httpapi/featurelimiter/featurelimiter.go
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-a4e5ae94e48e7c3935a20831e5b4ebb2c33484b4f31936954d85f6bb3fb47853>
>    (12)
>    - *M* cmd/cody-gateway/internal/httpapi/handler.go
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-24f971f108c2165ce826aa735dcf608c02a265f979119448b28e338202341c59>
>    (16)
>    - *M* cmd/cody-gateway/shared/BUILD.bazel
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-d8193659f1542fdeeb9f59598c98896aa1326bc8fc948d7fd884ce08c23ea637>
>    (2)
>    - *M* cmd/cody-gateway/shared/config/config.go
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-e357a7c21ee6a210cd5c24fb60b33e343ad5b28009ae18902e6fac38885b0530>
>    (12)
>    - *M* cmd/cody-gateway/shared/main.go
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-591faa61c19b4bf1ffd05d3edb03e25c16e29bd3e740711a29ad63dc9a082ad9>
>    (19)
>    - *M* internal/grpc/example/weather/v1/BUILD.bazel
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-ba5e0144a4f489d8d06c0fa4ad4ad25ca8211924731a1abaf957915aedf27c69>
>    (1)
>    - *M* internal/grpc/testprotos/news/v1/BUILD.bazel
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-86cc17e817c711a998cd38c416afbb90adb09410115effd8db5e6d292c2eee40>
>    (1)
>    - *A* internal/sams/BUILD.bazel
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-9d80252f3833a8947efdd929076903e477217bdcb2893aef7540a6dbe751f108>
>    (13)
>    - *A* internal/sams/client.go
>    <https://github.com/sourcegraph/sourcegraph/pull/60061/files#diff-224913abff59d7aab8f36aa6ab192e3a3ac0e824be4a938570c90abf43abec8a>
>    (102)
>
> Patch Links:
>
>    - https://github.com/sourcegraph/sourcegraph/pull/60061.patch
>    - https://github.com/sourcegraph/sourcegraph/pull/60061.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sourcegraph/sourcegraph/pull/60061>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BERESGR54XYPI6BAFYF2KJDYRO6E3AVCNFSM6AAAAABCVGFDCCVHI2DSMVQWIX3LMV43ASLTON2WKOZSGEYTEOJQGIYTGMA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-02-02 17:49 UTC, chrsmith requested changes
Lots of nitpicks and things. Overall this all looks right, in that it adds an appropriate layer to verify SAMS tokens. But I would urge us to rethink the design, and try to minimize the surface area of the `sams` package. So that it's easier to use correctly.

Let's hold off on merging though just to make sure we want to land these changes.

- Re: that thread with Rafal about maybe we want to have SSC call dotcom instead? And maybe we should double check we are calling the IntrospectToken endpoint the right way.
- Let's follow up with Joe to see if we should/should not use the `Basic` auth scheme for that particular endpoint.
- I'm pretty sure that since we are creating a `tokenSource` on every call to `IntrospectToken` we aren't ever going to benefit from reusing an existing SAMS token. (Which would definitely add a lot of latency over time.) So we would just have `samsClient.tokenSource` rather than `samsClient.clientCredentialsConfig`. That is, having the `tokenSource` share the lifetime of the `samsClient`.

2024-02-02 18:49 UTC, chrsmith commented on internal/sams/client.go
> +	tokenSource := c.clientCredentialsConfig.TokenSource(ctx)
BEHOLD! AUTORITATIVE ANSWERS!!!

This page explained the motivation for the token introspection endpoint, but didn't definitively say _how_ the introspection endpoint must be authentication. Only that it _should_ be authenticated.
https://www.oauth.com/oauth2-servers/token-introspection-endpoint/

Looking at the `ory/fosite` source code, it appears that the token introspection endpoint will honor either type of access token. (`Basic` scheme, using just the static client ID and client secret, or `Bearer` scheme, using an access token issued by SAMS attributed to that client ID and client secret.)
https://github.com/ory/fosite/blob/f4114878826c6d26b6751a1ea61f69ebbc25d4f2/introspection_request_handler.go#L115

As far as which one we should use, 🤷 . IMHO, the basic scheme auth requirement is better in that it doesn't require us to reissue a new SAMS token from time to time. But assuming we are using HTTPS and not logging the `Basic` auth header, it _shouldn't_ be any less secure.

But as far as this code being correct, it is all legit. Everything is well in the universe.

2024-02-05 08:29 UTC, closed without merging

2024-02-05 08:40 UTC, thenamankumar commented
Closed in favour of: https://github.com/sourcegraph/sourcegraph/pull/60145

2024-02-05 09:05 UTC, bobbydiji commented
Next people that try to steal my files gonna have a nice surprise.  Don't
say i didn't warn u.  Just thought I'd let it be known. I'm already
letting. U get bank off coding bot and my new superagent.  Think that ones
strong. 🤔 idk... 😆

On Mon, Feb 5, 2024, 3:40 AM Naman Kumar ***@***.***> wrote:

> Closed in favour of: #60145
> <https://github.com/sourcegraph/sourcegraph/pull/60145>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sourcegraph/sourcegraph/pull/60061#issuecomment-1926469784>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BERESGSQTGDGAXECJCDECRTYSCLI5AVCNFSM6AAAAABCVGFDCCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRWGQ3DSNZYGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>