licensing: create dashboard page for Cody enterprise
sourcegraph/sourcegraph pull request #60100
Opened 2024-02-02 16:45 UTC by BolajiOlajide

## Test plan

WIP

2024-02-02 16:45 UTC, BolajiOlajide commented on client/web/src/routes.tsx
> -        path: `${PageRoutes.Cody}/*`,
@sqs Just confirming that it's okay to remove this since we have the marketing page added now.

2024-02-07 17:34 UTC, taiyab requested changes
In the preview it looks like you have Code Search enabled but the Code Search banner is still appearing (it shouldn't).

This banner should only appear when they don't have a Code Search license.

2024-02-07 19:53 UTC, BolajiOlajide commented
> In the preview it looks like you have Code Search enabled but the Code Search banner is still appearing (it shouldn't).
> 
> This banner should only appear when they don't have a Code Search license.

Done.

2024-02-08 12:30 UTC, taiyab reviewed
All good! 👍

2024-02-08 12:30 UTC, vovakulikov approved these changes

2024-02-08 12:31 UTC, taiyab approved these changes
Approved.

2024-02-08 12:32 UTC, merged