Extract reposcheduler and add support for syntactic indexes
sourcegraph/sourcegraph pull request #60958
Opened 2024-03-08 14:31 UTC by keynmol

### 
## Test plan

2024-03-21 20:57 UTC, mmanela commented on internal/codeintel/autoindexing/internal/background/scheduler/job_scheduler.go
> +		go func(repositoryID int) {
New to go, out of curiosity, why change to pass repoid into the goroutine versus using the lexical closure of `repository` and just grabbing .ID in the method?

2024-03-22 09:53 UTC, keynmol commented on internal/codeintel/autoindexing/internal/background/scheduler/job_scheduler.go
> +		go func(repositoryID int) {
I have asked our local Council of Gophers and this _used_ to be necessary (https://pauldigian.com/advanced-go-loops-and-goroutines)

But we very recently upgraded to 1.22 which no longer has this problem: https://tip.golang.org/doc/go1.22

2024-03-25 11:10 UTC, varungandhi-src reviewed
I did a first round visiting 20/30 files, will do a second round later since this PR is quite big. 😬

2024-03-25 11:10 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/store_observability.go
> +			Name:              fmt.Sprintf("codeintel.reposcheduler.store.%s", name),
Should these two names be more similar/do you know what both of these are doing?

2024-03-25 11:10 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/store.go
> +	}
Here, the `0` will be translated to a `LIMIT 0` in the query right? Is that deliberately allowed/possible somehow in some site configuration?

2024-03-25 11:10 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/store.go
> +
```suggestion
```

Maybe you can annotated debug lines with some comment `// REVIEW: remove this` as a reminder 😅

2024-03-25 12:52 UTC, keynmol commented on internal/codeintel/reposcheduler/store.go
> +
I wonder if we could have a linter that detects that - there's probably very few cases where we want prints instead of logging, and it should save time on the review

2024-03-25 17:18 UTC, keynmol commented on internal/codeintel/autoindexing/init.go
> +	autoindexingDeps AutoIndexingService,
> it's unclear why there is Deps here and Svc elsewhere

Ah, this is left over from trying to break this weird AutoIndexingService apart, but IIRC I hit on cyclic dependencies and resolving them would require more changes than this PR could handle.

I will revisit in a separate PR.

2024-03-26 01:40 UTC, varungandhi-src commented on internal/codeintel/autoindexing/init.go
> +	autoindexingDeps AutoIndexingService,
This question is about a local variable name, not sure why there would be cyclic dependencies involved? Did you mean to post this reply to one of my other comments?

2024-03-26 03:25 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/store_test.go
> +	assertRepoList(t, store, NewBatchOptions(time.Hour, true, nil, 100), now.Add(time.Minute*95), []int(nil))
1. It looks like the comments are out-of-sync with the actual `assertRepoList` lines.
2. Could you explain the significance of the time instants chosen here? I don't understand what the numbers 20, 30, 90 and 95 are derived based on.

2024-03-26 03:47 UTC, varungandhi-src requested changes
Mostly LGTM, would be good to have more clarity on the test logic and the decision to set the boolean to be on by default.

2024-03-26 03:47 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/store_test.go
> +*/
Looks like this comment was copy-pasted from the comment on the above test - should this say `precise` instead of `syntactic`?

Also, it seems like the bulk of the logic between these tests is the same -- thoughts on factoring it out into a common function? (or do we expect that we will need to evolve these tests differently?)

2024-03-26 03:47 UTC, varungandhi-src commented on internal/database/schema.md
> + syntactic_indexing_enabled  | boolean                  |           |          | true
Does making this true by default from the get-go create a risk of spawning a bunch of jobs that aren't processed to the end? During our initial discussion, I believe we agreed on doing a gradual rollout where we enable it for certain repos at the start, see how it works (or doesn't) and then gradually increase the number of repos, before making it on-by-default.

2024-03-26 03:47 UTC, varungandhi-src commented on migrations/frontend/squashed.sql
> +    syntactic_indexing_enabled boolean DEFAULT true
Is there a reason for this to be nullable/what does the null state mean?

2024-03-26 09:27 UTC, keynmol commented on internal/database/schema.md
> + syntactic_indexing_enabled  | boolean                  |           |          | true
Here's what I was thinking:

1. This particular field will only decide whether repositories will be _ever_ marked as candidates for syntactic scheduling. This current PR will just update and maintain the syntactic indexing last scan table, not spawn any jobs
2. For jobs to actually be spawned, it needs a worker 
3. Before I PR the worker in, I want to introduce a site config setting (disabled by default) which enables/disables syntactic indexing - this setting will also enable/disable UI toggle that will control this particular boolean field

The site config setting will obviously be enabled on demo and S2, where we can then further control the rollout of this. Customers and dotcom won't have any jobs scheduled.

I don't have a strong opinion about exact value of this field in context of this PR, so can happily revert back to false.

2024-03-26 09:28 UTC, keynmol commented on internal/database/schema.md
> + syntactic_indexing_enabled  | boolean                  |           |          | true
> This current PR will just update and maintain the syntactic indexing last scan table, not spawn any jobs

Oh and also that will only happen upon the invoking the syntactic version of this code, which the worker does.

Anyways, for sanity reasons I'll revert it to false.

2024-03-26 10:18 UTC, varungandhi-src commented on internal/database/schema.md
> + syntactic_indexing_enabled  | boolean                  |           |          | true
👍🏽 Yeah, I think having it as `false` by default is safer so that when the site config setting is enabled (e.g. we change the default), you still need to have a policy for syntactic indexing (so that we can gradually enable it for specific repos).

2024-03-26 10:53 UTC, keynmol commented on internal/codeintel/autoindexing/init.go
> +	autoindexingDeps AutoIndexingService,
I'm responding to "and it's unclear why there is Deps here and Svc elsewhere" specifically - previously I made an attempt to break apart and refactor the Service + renamed it to Deps, and then reverted that change because I introduced cyclical dependencies.

The variable name will be changed.

2024-03-26 10:59 UTC, keynmol commented on migrations/frontend/squashed.sql
> +    syntactic_indexing_enabled boolean DEFAULT true
No reason, it's an oversight - I focused on the existing data, and forgot to add a constraint for data going forward, fixed in https://github.com/sourcegraph/sourcegraph/pull/60958/commits/81a3d53c6f012b5936953e3a1e4859a9d4b67d00

2024-03-26 14:54 UTC, keynmol commented on internal/codeintel/reposcheduler/store_test.go
> +*/
@varungandhi-src At this point we don't expect them to evolve differently, so I converted duplicated tests into a table test and added hopefully better comments to all the code I copied over from the code before this PR, see https://github.com/sourcegraph/sourcegraph/pull/60958/commits/6f66b24673e052303875d4b63188c2ecf0b26665 for comments and https://github.com/sourcegraph/sourcegraph/pull/60958/commits/57ccc2072cda6fdcc0b5b7786c97212896abc1cb for refactor

2024-03-26 14:54 UTC, keynmol commented on internal/codeintel/reposcheduler/store_test.go
> +	assertRepoList(t, store, NewBatchOptions(time.Hour, true, nil, 100), now.Add(time.Minute*95), []int(nil))
Addressed hopefully in https://github.com/sourcegraph/sourcegraph/commit/6f66b24673e052303875d4b63188c2ecf0b26665 - let me know if more clarity is needed

2024-03-27 10:04 UTC, keynmol commented on internal/codeintel/reposcheduler/store.go
> +	}
Technically there's nothing wrong with a 0 value for this particular setting - the setting is computed here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/conf/computed.go?L315-322 and it only handles the `-1` case to explicitly identify "no limit" setting.

This particular limit only controls the number of repositories returned from matching a global policy - which can match _all_ repos on an instance and therefore should be tightly controlled. Setting limit to 0 would be equivalent to disallowing global policy altogether, but as it stands 0 is not an erroneous value - albeit a useless one.

2024-03-27 10:51 UTC, keynmol commented on cmd/worker/internal/codeintel/autoindexing_scheduler.go
> +		*services.AutoIndexingService,
I took a closer look, and it's a mess.

The code for various internal services is intermingled with what graphql resolvers need.

For now I reverted the changes here, we can take another pass at refactoring this - I took three attempts as part of this PR and don't feel like it's worth it anymore.

2024-03-27 11:32 UTC, varungandhi-src approved these changes
Thanks for all the changes. The test cases in particular are much more easily understandable.

2024-03-27 11:32 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/init.go
> +		now time.Time) (_ []RepositoryToIndex, err error)
```suggestion
	GetRepositoriesForIndexScan(ctx context.Context, _ RepositoryBatchOptions, now time.Time) ([]RepositoryToIndex, error)
```

Minor tweak to match typical formatting style

2024-03-27 11:32 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/options.go
> +	GlobalPolicyRepositoriesMatcLimit *int
```suggestion
	GlobalPolicyRepositoriesMatchLimit *int
```

2024-03-27 11:32 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/options.go
> +	AllowGlobalPolicies bool
```suggestion
	// If AllowGlobalPolicies is false, then configuration policies that do not specify
	// a repository name or patterns will be ignored.
	// When true, such policies apply over all repositories known to the instance.
	AllowGlobalPolicies bool
```

Do we literally allow site admins to specify a repository id that is an integer? Or does "id" just here mean the base case of a literal pattern? If it's a string, might be clearer to say "repository name".

2024-03-27 11:32 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/store.go
> +)
```suggestion
type storeType int8

const (
	preciseStore   StoreType = 1
	syntacticStore StoreType = 2
)
```

Suggestion: Make these private, since AFAICT, the values are only used within this same package.

2024-03-27 11:32 UTC, varungandhi-src commented on internal/codeintel/reposcheduler/store_test.go
> +			assertRepoList(t, tt.store, NewBatchOptions(1*time.Hour, true, nil, 100), now.Add(time.Minute*90), []int{50, 51, 52, 53})
Thank you, now this is much more understandable. I think part of what was throwing me off was the names. Here, the function name starts with `assert` and the query this bottoms out is `getRepositoriesForIndexScanQuery`. However, that query modifies state, and consequently, this `assertBlah` function also modifies state, whereas normally you'd expect 'get' and 'assert' to not modify state.

I don't have specific alternate naming suggestions, but the usage of `get` for a query which does inserts seems a bit unfortunate.

2024-03-27 12:04 UTC, keynmol commented on internal/codeintel/reposcheduler/store_test.go
> +			assertRepoList(t, tt.store, NewBatchOptions(1*time.Hour, true, nil, 100), now.Add(time.Minute*90), []int{50, 51, 52, 53})
Yeah, the upsert nature of that operation is a bit confusing - also makes it hard to debug.
The insert is pushed into the query for (I believe) atomicity and to handle possible dotcom batch sizes (though I wonder how much of a problem it is to literally return only integer repository IDs, you can do thousands of them)

We can rename it to Calculate/Compute, and replace this single helper method assert with a combo of assert + a local `computeReposForScheduling` or something, but I think we'd hit diminishing returns wrt readability

2024-04-02 10:37 UTC, merged