[WIP] Count token
sourcegraph/sourcegraph pull request #61134
Opened 2024-03-14 09:40 UTC by arafatkatze

## Test plan

2024-03-15 14:55 UTC, arafatkatze commented on internal/completions/client/azureopenai/openai.go
> +			tokenManager := tokenusage.NewTokenUsageManager()
NOTE: I realize that some outputs and some place will show me the tokenusage in the responses too so maybe I can use those in some places. It still shouldn't deter from the essence of this PR. 

Also it seems like the. current implementation is generic enough to be used as it is and we can probably make use of the response token numbers as an efficiency measure later.

2024-03-15 17:31 UTC, dadlerj commented on internal/completions/tokenusage/tokenusage.go
> +	baseKey := fmt.Sprintf("%s:%s:%s:", model, feature, streamDescription(stream))
Just to confirm—this set of possible strings here will be consistent across all instances, right? I think so looking at how they're generated above. Our schema needs to be explicitly structure, and won't adapt easily to arbitrary strings.

As part of this PR, we would need to go add these possible keys to our BigQuery ping schema so that we get the data in a usable format. Is it possible to create a list of keys now?

Another option, if we expect the list of possible values to grow quickly, would be to change the format of the usageData field in the GetAllTokenUsageData func below to be an array of `{"description": ${baseKey}, "tokens": ${tokenCount}}`?

2024-03-15 19:11 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +	baseKey := fmt.Sprintf("%s:%s:%s:", model, feature, streamDescription(stream))
> this set of possible strings here will be consistent across all instances, right?

Yes in the sense that we are not doing anything in this string that will make it different on the basis of an instance but different instances shall focus on different models so for some all the metrics are for the anthropic model and for some its openai model. 

Some will have slightly different names for the exact same model because of using bedrock etc the model naming convention could be changed. So all in all there is a huge overlap but there could still be a lot of different cases. 

> Another option, if we expect the list of possible values to grow quickly, would be to change the format of the usageData field in the GetAllTokenUsageData func below to be an array of {"description": ${baseKey}, "tokens": ${tokenCount}}?

That I think makes even more sense because I do think that this combination of providers and different models could potentially grow to 15-20 and then more with time so if it helps your team with data processing to do it the way you suggested then I would be down to make that change. Just give me a thumbs up here.

2024-03-15 19:35 UTC, chwarwick requested changes
This is a good start, but right now it's not clear to me what the tokens counts in the ping are inteted to be all time use vs this period use. 

Additionaly other pings aggregate data from the local db's event logs which is nice because it leaves a record of this locally that can be queryable.  Considering the most common use here is customers in BYOK mode likely self hosted having this aggregated data in the local event log may be neccessary so customer can extract it.

2024-03-15 19:35 UTC, chwarwick commented on internal/completions/tokenusage/tokenusage.go
> +func (m *TokenUsageManager) GetTokenCounts(key string) (int, bool) {
If these are ever increasing values are you sure that an int is sufficent to hold the number of tokens? Considering we look at pricing per million tokens I suspect an int is not large enough.

2024-03-15 21:37 UTC, dadlerj commented on internal/completions/tokenusage/tokenusage.go
> +	baseKey := fmt.Sprintf("%s:%s:%s:", model, feature, streamDescription(stream))
That change in ping data structure would be great, thank you!

2024-03-16 00:21 UTC, slimsag commented
General question: if we lose all redis cache data, what is the impact on whatever functionality this provides?

All data in Redis depoyments is generally considered ephemeral to us. i.e., customers are (an have historically been) advised that if they do not back up Redis data and all of it is lost in e.g. an accident, then the only 'real' impact on users will be that they need to sign in again - and in some cases things may be a little bit slower until the caches re-populate.

Given that, any concerns with using Redis for this functionality?

2024-03-16 00:25 UTC, slimsag commented on internal/rcache/rcache.go
> +		return 0, false
This seems bad for other uses, if for some reason the value here is wrong (e.g. key conflict with other usage in our codebase or something) then we would start getting zero values back here and not really know what is going on. The log warning also doesn't mention the `key` so we wouldn't know what it is related to.

I would prefer to see this function return an error instead, for the caller to log appropriately, and replace the `bool` return parameter with a 'does not exist' error instead.

2024-03-16 00:26 UTC, slimsag commented on internal/completions/tokenusage/tokenusage.go
> +func (m *TokenUsageManager) GetTokenCounts(key string) (int, bool) {
seconded

2024-03-16 00:29 UTC, slimsag commented on internal/completions/tokenusage/tokenusage.go
> +func NewTokenUsageManager() *TokenUsageManager {
In a lot of places in this PR (like, per-request and stuff) you are calling `NewTokenUsageManager` - which is calling `rcache.NewWithTTL`. I think this is not good for performance or GC.

Instead, see if you can pass an instance of `*TokenUsageManager` around places and not call `NewTokenUsageManager` so much.

2024-03-18 09:52 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +	baseKey := fmt.Sprintf("%s:%s:%s:", model, feature, streamDescription(stream))
Done

2024-03-18 10:11 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +func (m *TokenUsageManager) GetTokenCounts(key string) (int, bool) {
Great Catch 🙇

2024-03-18 10:26 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +func streamDescription(stream bool) string {
Cool I just wanted to be comprehensive but you are right I don't see how this adds value to the tokenization. 

I do think that whether its chat or autocomplete does make a difference though

2024-03-18 10:43 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +func (m *TokenUsageManager) GetAllTokenUsageData() map[string]int {
@dadlerj This looks pretty cool, what do you think?(The only suggestion being that input/output tokens will be in different keys)


The current format  per your suggestion is 
```

{
descriptions: ["model1:chat_feature:input", "model2:chat_feature:output", "model3:completion_feature:input" ],
tokens:           [4000,                                          500,                        600]

}

```

Is the format good enough for you dan or would you suggest something different like this recommendation?

2024-03-18 11:36 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +		Cache: rcache.NewWithTTL("LLMUsage", 1800),
Great catch.

Theres two ways that I think we can deal with this
1. using Sorted sets of reddis where each entry is separate and then we delete keys older than 30 mins and then do cumulative operations 
Cons: 
- Hard to implement
- Probably risky if done imperfectly

3. When doing the pings every 30 minutes we can just :delete the key on it being successfully put into the struct [here](https://github.com/sourcegraph/sourcegraph/pull/61134#discussion_r1528301428)

Cons: There might be a very slight offset of a few operations because of how redis handles concurrent calls.  If a key is updated in Redis right after it's read but before it's deleted, those updates could be lost. 
The way to handle this con is to have a shared mutex lock
```

func (m *TokenUsageManager) TokenizeAndCalculateUsage(inputText, outputText, model, feature string) error {
	m.mu.Lock() // Lock the mutex at the start
	defer m.mu.Unlock() // Ensure the mutex is unlocked at the end

	tokenizer, err := tokenizer.NewTokenizer(model)
	if err != nil {
		return err
	}

	inputTokens, _ := tokenizer.Tokenize(inputText)
	outputTokens, _ := tokenizer.Tokenize(outputText)

	baseKey := fmt.Sprintf("%s:%s:", model, feature)

	m.updateTokenCounts(baseKey+"input", int64(len(inputTokens)))
	m.updateTokenCounts(baseKey+"output", int64(len(outputTokens)))
	return nil
}

func (m *TokenUsageManager) GetAllTokenUsageData() TokenUsageSummary {
	m.mu.Lock() // Lock the mutex at the start
	defer m.mu.Unlock() // Ensure the mutex is unlocked at the end

	allKeys := m.Cache.ListAllKeys()
	var summary TokenUsageSummary

	for _, key := range allKeys {
		cleanedKey := strings.SplitN(key, "LLMUsage:", 2)[1]
		value, found := m.Cache.GetInt(cleanedKey)
		if !found {
			continue
		}
		summary.Descriptions = append(summary.Descriptions, cleanedKey)
		summary.Tokens = append(summary.Tokens, value)

               // Delete the key after processing
            err := m.Cache.Delete(cleanedKey)
            if err != nil {
               log15.Warn("Failed to delete key", "key", cleanedKey, "error", err)
            }
	}


	return summary
}
```

I think the second choice works and if you give me a thumbs up then I will add it

2024-03-18 13:01 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +	currentTokens, _ := m.Cache.GetInt(key)
Great catch. 

I definitely should have thought about this. 

Thanks for the catch.

2024-03-18 13:58 UTC, arafatkatze commented
@slimsag you asked a great question

> All data in Redis depoyments is generally considered ephemeral to us. i.e., customers are (an have historically been) advised that if they do not back up Redis data and all of it is lost in e.g. an accident, then the only 'real' impact on users will be that they need to sign in again - and in some cases things may be a little bit slower until the caches re-populate.

I wanna go with this as the answer. 

<img width="1280" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/95c3ed39-c427-4833-b5b0-4a1156427db5">

2024-03-18 14:41 UTC, arafatkatze commented on internal/rcache/rcache.go
> +		return 0, false
Good recommendation: This reminds me that this PR could have many different points of failure so I fixed the error handling all over the place.

2024-03-18 15:40 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +func NewTokenUsageManager() *TokenUsageManager {
Makes sense I did that

2024-03-18 16:39 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +func (m *TokenUsageManager) GetAllTokenUsageData() map[string]int {
Thanks I will make a change for this

2024-03-18 16:44 UTC, arafatkatze commented on cmd/cody-gateway/internal/httpapi/completions/anthropic.go
> +	anthropicTokenizer *tokenizer.TiktokenTokenizer
Yeah makes sense

2024-03-18 17:04 UTC, arafatkatze commented on internal/completions/tokenizer/tokenizer.go
> +type Tokenizer interface {
Yeah I actually used that. The idea is to use this generically as we grow to add more models and then other stuff will be implementation of this.

2024-03-18 19:16 UTC, arafatkatze commented on internal/completions/client/anthropic/anthropic.go
> +	return err
Makes sense and I made the changes.

Just for further clarification: 
- Can we say in general that telemetry failures in general should be NON blocking on the main operation and therefore we shouldn't error out because of them?  Would that be the reason to not error out here?

2024-03-18 19:21 UTC, arafatkatze commented on internal/completions/tokenizer/tokenizer.go
> +type TiktokenTokenizer struct {
Makes sense, I fixed this.

2024-03-18 20:43 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +func (m *TokenUsageManager) GetAllTokenUsageData() map[string]int {
@dadlerj @chwarwick I have changed the format. If you are cool with this this please resolve this issue.

2024-03-18 21:14 UTC, arafatkatze commented on cmd/cody-gateway/internal/httpapi/completions/anthropic.go
> +	anthropicTokenizer, err := tokenizer.NewAnthropicClaudeTokenizer("anthropic/claude-2")
> Does that model name ever get used because it will likely be wrong in many cases.

So I finally refactored it to look [like this](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fsourcegraph.git&branch=count-token&file=cmd%2Fcody-gateway%2Finternal%2Fhttpapi%2Fcompletions%2Fanthropic.go&editor=VSCode&version=2.2.16&start_row=47&start_col=57&end_row=47&end_col=57) essentially the idea here is that we initialize a tokenizer which is the only thing exported from that package and give it a model name and then it "magically" figures out the right [tokenizer to use](https://sourcegraph.com/-/editor?remote_url=https%3A%2F%2Fgithub.com%2Fsourcegraph%2Fsourcegraph.git&branch=count-token&file=internal%2Fcompletions%2Ftokenizer%2Ftokenizer.go&editor=VSCode&version=2.2.16&start_row=26&start_col=8&end_row=36&end_col=1) based on whether its openai/azure/claude or something else. I didn't yet add the granularity to be able to specifically double down on claude-2 so the model name is actually not used.

@philipp-spiess says that for claude 3 onwards [the request itself](https://sourcegraph.slack.com/archives/C05497E9MDW/p1710514378197969?thread_ts=1710514215.874919&cid=C05497E9MDW) would give use the token count so perhaps I can learn how to add that somehow in the requests we make to anthropic and force this to only work with claude 2.x /claude instant models.

<img width="820" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/11155207/a89d5b6b-6efb-48f2-8b6d-092d2fe4c9d2">

  
Anyway chris, I am open to ideas here: I am also happy to make followup changes to use the value of claude3+ tokens in a separate PR too. What do you think?

2024-03-18 21:18 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +func (m *TokenUsageManager) GetAllTokenUsageData() map[string]int {
Done

2024-03-19 14:01 UTC, philipp-spiess commented on cmd/cody-gateway/internal/httpapi/completions/anthropic.go
> +	anthropicTokenizer, err := tokenizer.NewAnthropicClaudeTokenizer("anthropic/claude-2")
@arafatkatze There's too much context in this PR and I haven't caught up on all of this but regarding your ping: The `/messages` API that we're moving to give you exact token counts (this is not related to Claude 3, so even Claude 2 will get us usage data on that API).

Ideally we would always use usage data as reported by the inference APIs if these exist because models change and new models come with new tokenizers. I don't have context as to why these changes are important for us right now but if we can avoid having to add tokenizers for every new model being added, I imagine it would help a ton going forward.

2024-03-19 14:03 UTC, philipp-spiess commented on internal/completions/client/anthropic/anthropic.go
>  }
This seems wrong, wouldn't there also be tokens necessary to explain to the LLM what the boundaries are between user/system/and assistant messages?

2024-03-19 14:24 UTC, arafatkatze commented on internal/completions/client/anthropic/anthropic.go
>  }
Yeah I though I had fixed it but I hadn't. I will fix that soon.

2024-03-19 18:57 UTC, arafatkatze commented on cmd/cody-gateway/internal/httpapi/completions/anthropic.go
> +	anthropicTokenizer, err := tokenizer.NewAnthropicClaudeTokenizer("anthropic/claude-2")
Great idea Philip. If this is the case then Ideally I should get rid of tokenizer for anthropic because it serves no purpose if the `/messages` api can take care of the usage counting for all the models of anthropic now(as show on docs and tested by us). Basically for any model related to anthropic we should first fully migrate to the `/messages` api  so first we do 
1. https://github.com/sourcegraph/sourcegraph/pull/60953 
2. I add support for `/messages` api for amazon bedrock because they too support [token output now](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html#model-parameters-anthropic-claude-messages-request-response) and that does have the output tokens that we are looking for
3.  Once both those PRs are merged I rebase this PR on top of them and then get rid of the anthropic tokenizer altogether because getting rid of it while adding. support for claude 3 is easier than doing shenanigans to support claude 3 token counting. 

@chwarwick can you give me a thumbs up for this and then I will implement it?

2024-03-19 18:59 UTC, arafatkatze commented on cmd/cody-gateway/internal/httpapi/completions/anthropicmessages.go
>  	return isFlaggedRequest(tk,
I will do the refactoring after getting rid of the tokenizer see [here](https://github.com/sourcegraph/sourcegraph/pull/61134#discussion_r1530930597)

2024-03-20 14:04 UTC, rafax commented on internal/completions/tokenusage/tokenusage.go
> +type TokenUsageManager struct {
nit: call this Manager, so it's used as `tokenusage.Manager`, not `tokenusage.TokenUsageManager`

2024-03-20 14:06 UTC, rafax commented on internal/completions/tokenusage/tokenusage.go
> +type TokenUsageManager struct {
https://go.dev/wiki/CodeReviewComments#package-names

2024-03-20 14:10 UTC, rafax commented on internal/completions/tokenusage/tokenusage.go
> +		Cache: rcache.NewWithTTL("LLMUsage", 1800),
> The way to handle this con is to have a shared mutex lock

This won't work if you have more than one process exporting usage (and it seems like it gets exported from `frontend` which generally runs multiple replicas)?

2024-03-20 14:20 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +type TokenUsageManager struct {
Makes sense

👍

2024-03-22 14:48 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +		Cache: rcache.NewWithTTL("LLMUsage", 1800),
Yeah you are right, that won't work. So I did something different. Basically I am now gonna retrieve a value from the redis and then use DecrBy and then because that operation in itself is atomic it will only decrease it by the value that it sent to our dashboards.

2024-03-22 17:32 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +		Cache: rcache.NewWithTTL("LLMUsage", 1800),
CC @rafax @slimsag

2024-04-02 15:42 UTC, arafatkatze commented on internal/updatecheck/client.go
> +		randomDelay := time.Duration(rand.Intn(10)) * time.Second
Currently set to this for testing but I will change it before the merge

2024-04-02 15:57 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +		Cache: rcache.NewWithTTL("LLMUsage", 1800),
Got rid of ttl alltogether and now I just decrement the keys atomically when sending to redis.

2024-04-02 21:09 UTC, slimsag commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +	//nolint:logging // TODO move all logging to sourcegraph/log
what's this needed for? I suspect it can be removed

2024-04-02 21:11 UTC, slimsag commented on internal/updatecheck/client.go
> +		randomDelay := time.Duration(rand.Intn(10)) * time.Second
definitely need to undo these changes, same for `const delay` above

2024-04-02 21:13 UTC, slimsag commented on cmd/cody-gateway/internal/httpapi/completions/anthropic_test.go
> +	tk, err := tokenizer.NewAnthropicClaudeTokenizer("anthropic/claude-2")
same things w.r.t. constants in this file

2024-04-02 21:14 UTC, slimsag commented on cmd/cody-gateway/internal/httpapi/completions/anthropicmessages_test.go
> +	_, err := tokenizer.NewAnthropicClaudeTokenizer("anthropic/claude-2")
Also with this function call `tokenizer.NewAnthropicClaudeTokenizer`

2024-04-02 21:24 UTC, slimsag commented on internal/rcache/rcache.go
> +func (r *Cache) IncrbyInt64(key string, value int64) (int64, error) {
I think you have a typo here `IncrbyInt64` -> `IncrByInt64`

2024-04-02 21:24 UTC, slimsag commented on internal/rcache/rcache.go
> +func (r *Cache) IncrbyInt64(key string, value int64) (int64, error) {
same for `DecrbyInt64`

2024-04-02 21:26 UTC, slimsag commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +		convertedTokenUsageData[telemetry.ConstString(key)] = value
```suggestion
		convertedTokenUsageData[key] = value
```

Can we just write this instead? It's weird that `telemetry.ConstString` is a thing TBH, would be ideal to not expose it from that package if that works.

2024-04-02 21:31 UTC, slimsag commented on internal/completions/client/anthropic/anthropic.go
> +	return nil
This if statement + `return nil` is exactly the same as `return dec.Err()` - no need to make this change.

Actually the `if` statement added is potentially more error-prone, because it relies on `dec.Err()` returning the same error twice

2024-04-02 21:39 UTC, slimsag commented on internal/completions/tokenusage/tokenusage.go
> +	modelsData := make([]map[string]interface{}, 0)
```suggestion
	modelsData := make([]map[string]interface{}, 0, len(tokenUsageData))
```

more optimal

2024-04-02 21:48 UTC, slimsag commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +	tokenUsageData, err := tokenManager.FetchTokenUsageDataForAnalysis()
It occurs to me that as the code is written today the following could happen:

* Usage is recorded in redis
* The update client runs and sends recorded redis data to our telemetry servers (or e.g. in a fully offline deployment, fails to send data to our telemetry servers.) Either way, `RetrieveAndResetTokenUsageData` gets called and resets all counters to zero,
* Then 1s later a loop of `ScheduleStoreTokenUsage` runs, but since `RetrieveAndResetTokenUsageData` ran before it now the usage is set to zero. No usage is recorded.

This could lead to the last minute of data being lost somewhat infrequently, which leads to the overall numbers being incorrect and suspect.

The only obvious way I see to address this is to make sure that `StoreTokenUsage` directly prior to any `RetrieveAndResetTokenUsageData` calls.

I also suggest changing the `// Wait for 1 minute before the next execution` to 5 minutes, as that would surface this type of bug better (and 1 minute is fairly aggressive anyway)

2024-04-02 21:49 UTC, slimsag requested changes
Left some feedback inline, you're definitely on the right track though! Give me a ping on Slack when you need another look.

2024-04-03 10:28 UTC, arafatkatze commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +	//nolint:logging // TODO move all logging to sourcegraph/log
This comment stayed because I copy paste a lot of stuff. I fixed it.

2024-04-03 10:28 UTC, arafatkatze commented on cmd/cody-gateway/internal/httpapi/completions/anthropic.go
> +	anthropicTokenizer, err := tokenizer.NewTokenizer("anthropic")
Makes so much sense 🙇

2024-04-03 10:45 UTC, arafatkatze commented on internal/rcache/rcache.go
> +func (r *Cache) IncrbyInt64(key string, value int64) (int64, error) {
Good catch. I made the fix

2024-04-03 11:03 UTC, arafatkatze commented on internal/completions/tokenizer/tokenizer_test.go
> +	tk, err := tokenizer.NewAnthropicClaudeTokenizer("testModel")
I know what you mean. Basically I got rid of exposing `NewAnthropicClaudeTokenizer` and then now I only use `tokenizer.NewTokenizer `everywhere and I use model names as constants so this makes everything a whole lot cleaner and the interface is pretty clean too.

2024-04-03 11:12 UTC, arafatkatze commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +		convertedTokenUsageData[telemetry.ConstString(key)] = value
sadly no 😢

2024-04-03 11:14 UTC, arafatkatze commented on internal/completions/client/anthropic/anthropic.go
> +	return nil
👍

2024-04-03 17:17 UTC, dadlerj commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +	tokenUsageData, err := tokenManager.FetchTokenUsageDataForAnalysis()
>I also suggest changing the // Wait for 1 minute before the next execution to 5 minutes, as that would surface this type of bug better (and 1 minute is fairly aggressive anyway)

I agree with this!

2024-04-03 17:19 UTC, dadlerj commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +	if err := recorder.Record(ctx, "llmTokenCounter", "modelUsage", &telemetry.EventParameters{
```suggestion
	if err := recorder.Record(ctx, "cody.llmTokenCounter", "record", &telemetry.EventParameters{
```

To confirm—this event occurs every [1] minute(s), right? So the _action_ here is more of a "record" or a "store" action than a "model was used", right? Let me know if the logic behind these changes and questions makes sense

2024-04-03 17:24 UTC, dadlerj commented on internal/completions/tokenusage/tokenusage.go
> +		modelData := map[string]interface{}{
Not a dealbreaker, but any reason not to make this a struct type? It's probably fine to leave it simple like this, but it might be worth adding a comment here that this structure shouldn't be changed without a corresponding change to our BigQuery telemetry database.

2024-04-03 21:21 UTC, arafatkatze commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +	tokenUsageData, err := tokenManager.FetchTokenUsageDataForAnalysis()
Makes sense I added a fix

2024-04-03 21:23 UTC, arafatkatze commented on internal/completions/tokenusage/tokenusage.go
> +		modelData := map[string]interface{}{
Makes sense so Made a struct type

2024-04-04 04:33 UTC, slimsag commented on cmd/frontend/internal/bg/store_token_usage_in_postgres.go
> +		// Wait for 1 minute before the next execution
```suggestion
		// Wait for 5 minutes before the next execution
```

2024-04-04 04:40 UTC, slimsag commented on internal/rcache/rcache.go
> +			// Decide whether to return this error or not based on your error handling policy.
```suggestion
```

2024-04-04 04:41 UTC, slimsag commented on internal/rcache/rcache.go
> +			// Decide whether to return this error or not based on your error handling policy.
```suggestion
```

2024-04-04 04:42 UTC, slimsag commented on internal/updatecheck/client.go
> +	const delay = 5 * time.Minute
@arafatkatze please make sure you undo this change and the one below.

2024-04-04 04:44 UTC, slimsag approved these changes

2024-04-04 15:49 UTC, merged