Add syntax highlighting for Pkl files
sourcegraph/sourcegraph pull request #61478
Opened 2024-03-28 19:55 UTC by mmanela

Fixes PRIV-2879

Adds syntax highlighting for the [Pkl configuration](https://pkl-lang.org/) language. 

**Key Changes/Notes/Questions**
1. Added reference to the Pkl tree-sitter package
2. Added references to the new language in the syntax highlighter rust project
3. Added the Pkl tree sitter queries (.scm files) (got them from the [pkl tree sitter repo](https://github.com/apple/tree-sitter-pkl/blob/main/queries/highlights.scm))
4. **!IMPORTANT!** Changed the logic in `into_tree_sitter_name` to not hard-code fall back just for Nickle files and instead re-use the existing map of file extension to language to generally do the fall back.
5. **QUESTION** Made 2 changes outside of the syntax highlighter project in `internal/gosyntect/languages.go` and `lib/codeintel/languages/extensions.go` but I am not sure if these are actually needed. 
6. Generated unit test snapshot for Pkl

![image](https://github.com/sourcegraph/sourcegraph/assets/304410/68a678bb-522b-4838-90dd-6884a7484f25)

## Test plan
- [ ] Update unit tests
- [ ] Validate local instance colors pkl correctly
- [ ] validate in S2 after deploy

2024-03-28 22:55 UTC, eseliger reviewed
I don't feel confident to approve this, but I don't see anything that screams wrong at me, and it works so.. 
I'll defer for final approval to the Graph team :)

Thanks for tagging me for the learning experience, and congrats on shipping a customer request in <48h after we heard about it on a call!

2024-03-28 22:55 UTC, eseliger commented on docker-images/syntax-highlighter/Cargo.Bazel.lock
> +          "url": "https://static.crates.io/crates/adler/1.0.2/download",
I have no clue about rust, but I wonder how this change comes to be. Did they just change their domains at some point?

2024-03-29 02:50 UTC, varungandhi-src requested changes
Thank you for the PR. I appreciate your enthusiasm to get your hands dirty and help out.

I noticed that there are lots of test cases missing. During the first pass, we should be aiming for coverage of as many of the various syntax features as possible, so that we don't have to keep coming back to fix small things (it's also quite likely that if some things work and other don't, users won't like the UX but they won't dislike it enough to complain about it).

I've outlined some in the inline comments, some more that are missing (non-exhaustive):
- Type annotations (simple identifiers as well as generic types)
- Escaped identifiers such as `` `class` ``.
- Chained amends expression
- Field accesses
- Class definitions
- Method definitions
- Method calls
- `new` expressions
- Various property keywords such as `fixed`, `hidden`, `local`, `const` etc.
- Annotations such as `@Deprecated`

You can go through the language reference (https://pkl-lang.org/main/current/language-reference/index.html) and add test cases for these.

If it's not possible to pick out some syntax features based on the grammar, we should still add a test case for that and note in a comment that it is because of an upstream limitation.

I do not feel comfortable merging this in its current state given the low coverage. Please re-request code review once you've made the suggested changes.

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/locals.scm
> +  (identifier) @local.reference)
I'm pretty sure that Pkl files can reference entities in other files, so these are not correct. Since this PR is for highlighting, please remove the locals navigation queries.

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//       ^^^^^^^^^^^^^ StringLiteral
`pigeon1.pkl` should get marked as `IdentifierNamespace`, not `StringLiteral`.

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//^^^^^^ Identifier
`amends` should be marked as a `Keyword`, not as `Identifier`.

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//                ^^^ Identifier
These are incorrect, `extends` and `amends` have syntax similar to `import`. Please add a test for `extends` too. https://github.com/apple/tree-sitter-pkl/blob/main/grammar.js#L128-L131

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//         ^^^^^^^^^ StringLiteral
This line doesn't add anything over the previous one, please remove it.

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +  name = "Great green macaw"
Please add tests for the following inside strings: https://pkl-lang.org/main/current/language-reference/index.html#strings

1. Escape sequences, especially `\"`, and `\\` and `\u{<codepoint>}`
2. String interpolation
3. Multiline strings, with and without interpolation, with and without leading whitespace.
4. Strings with custom delimiters
5. Multiline strings with custom delimiters (not super obvious that this is supported, but seems plausible)

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +
Please add tests for [duration literals](https://pkl-lang.org/main/current/language-reference/index.html#durations) and [data sizes](https://pkl-lang.org/main/current/language-reference/index.html#data-sizes). It's weird that these are not recorded in the grammar, maybe that needs to be fixed upstream first.

https://pkl-lang.org/main/current/language-reference/index.html#durations

I think maybe we should mark the suffixes (`min` in the context `5.min`) as keywords.

2024-03-29 02:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +  woodPigeon {
Please remove the code here and below this, since it's not testing anything new.

2024-03-29 03:02 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +            }
The layering here is wrong - the caller (from Go) should be passing the language `"Pkl"`, we should try to avoid doing more language detection here. We already run language detection in Go as pass a language as input to the caller here. This old code is basically a workaround and should be removed eventually or be made consistent with the rest instead of this special hack.

The correct fix would be to modify `func getLanguagesByExtension` in Go and add an extra `map[string]string unsupportedByEnryExtensionsMap` until Linguist and consequently go-enry get support for Pkl.

2024-03-29 10:13 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +            }
@varungandhi-src I first made this change while struggling to understand why the unit test (test all files) was failing . That test path relies on either the file under test matching in syntect or the hard code work around that was here for nickel already based on extension.

How do you suggest I re-work that test?

2024-03-29 10:18 UTC, mmanela commented
@varungandhi-src Thanks for the thorough review ( I was eager for you to show me the ropes here ).


Couple questions /comments
1. By add unit tests in this case you mean make my pkl test file cover all the key language features you layout right?

2. The scm file I copied from the tree sitter pkl repo, I just assumed it was correct so thanks for poking at that. Good opportunity to understand more there and make sure that file is correct.

3. I will make a second pass today and make as many changes as I can.

2024-03-29 10:19 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/locals.scm
> +  (identifier) @local.reference)
1. So remove this whole file right?

2. For my own education can you explain why this jumped out to you as wrong ( it's my first time using or reading tree sitter queries )?

2024-03-29 11:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/locals.scm
> +  (identifier) @local.reference)
> So remove this whole file right?

I'm not 100% sure if we leave these blank for other languages where we don't support locals navigation or not have these files at all, but I think removing seems reasonable.

> For my own education can you explain why this jumped out to you as wrong ( it's my first time using or reading tree sitter queries )?

It doesn't have anything to do with Tree-sitter queries specifically but the purpose of this file (it's called `locals.scm`), which is to mark local variables for faster code navigation without extra queries from the client to the server. We're not implementing code navigation functionality here, so it's out-of-place for this PR.

If your question was about language semantics, I saw 'classes' and 'methods'; it would be unusual for a language to have such abstraction facilities if they were confined to a single file.

2024-03-29 11:26 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +            }
The test code can be changed to pass in the language for the Pkl case. It might sound a bit weird (why would you want to spread this logic in more places instead of keeping it confined here?), but we want to ideally remove the language detection logic in the highlighter, and mimic the situation where the language is passed in from the outside (which is what should be happening in production), so it makes sense for the test to mimic what the Go code would do in production.

I don't think it's a HUGE deal, it's more work than what you've done here, but if there is code that starts accidentally relying on this codepath for something other than Pkl (because now you're suddenly doing language detection for many cases!), then it will be harder to undo.

2024-03-29 11:39 UTC, varungandhi-src commented
> By add unit tests in this case you mean make my pkl test file cover all the key language features you layout right?

I skimmed through the language reference (https://pkl-lang.org/main/current/language-reference/index.html) and noted things which looked missing. I did not look at everything in the language reference. When you're adding test cases, you should add test cases for the different syntactic features as written in the language reference (my list is a subset).

Generally, it is also good to add test cases for "interesting" combinations of features, e.g. how I wrote "Multiline strings, with and without interpolation, with and without leading whitespace." What exactly is an "interesting" combination is hard to define, but it's useful to think through variations. You may also want to look at the grammar.js file directly for inspiration, or the test cases in the tree-sitter-pkl repo. (https://github.com/apple/tree-sitter-pkl/tree/main/corpus)

> The scm file I copied from the tree sitter pkl repo, I just assumed it was correct so thanks for poking at that. Good opportunity to understand more there and make sure that file is correct.

1. Please add a link and attribution at the top of the file as the original is Apache 2.0 licensed.
2. That's why we have the snapshot tests; you see there is this line https://github.com/apple/tree-sitter-pkl/blob/main/queries/highlights.scm#L101 but in your snapshot output, `amends` was getting marked as an identifier. I think this might be because the order matters -- generally the identifier queries should come at the end, and keywords and operators should come at the beginning. So the upstream queries are buggy (and if you look at the language reference, that also has some incorrect highlighting for code snippets that doesn't match the intent of the queries).

    If you're feeling so inclined, you could submit an issue or PR upstream too and point them to your improved queries.

2024-03-29 18:29 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +
I added them to the test file but I am not sure how to mark the duration and unit suffices as keywords. I looked into the grammer.js but I see what you meant that they don't explicitly seem to label those

2024-03-29 18:59 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//       ^^^^^^^^^^^^^ StringLiteral
I tried a while to figure out how to do this but nothing I tried worked. I probably am missing knowledge here. If this is critical, we can chat later and just handle unresolved feedback in one session. 

I also notice other languages like Typescript also list things like this as StringLiteral
![image](https://github.com/sourcegraph/sourcegraph/assets/304410/494bf4c8-6c24-4cac-bd71-377d7f66d4df)

2024-03-29 19:07 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +  name = "Great green macaw"
Done

2024-03-29 19:24 UTC, mmanela commented
@varungandhi-src  Thanks for your detailed information. I made a second attempt to address as much of your feedback as I could figure out.

2024-03-31 03:31 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//       ^^^^^^^^^^^^^ StringLiteral
Thanks for bringing up TypeScript, I didn't realize we were doing that, this means we have a code nav bug with TypeScript. https://github.com/sourcegraph/sourcegraph/issues/61508

FWIW, the "right" fix for this would be to add a query like:

```
(importClause "import" (stringConstant) @identifier.module)
```

However, I don't think we should do that, because from a highlighting POV, you probably want this to be highlighted like a string literal anyways. I suggested this earlier as a workaround for the incorrect assumption in the client-side code for interactive occurrence filtering (https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1711010206641949?thread_ts=1710936490.391979&cid=C05EA9KQUTA, see `const INTERACTIVE_OCCURRENCE_KINDS` in the client code), but in hindsight, I don't think we should make the highlighting wrong to work around bugs.

Let's leave this as StringLiteral.

2024-03-31 04:00 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +
> I added them to the test file but I am not sure how to mark the duration and unit suffices as keywords. I looked into the grammer.js but I see what you meant that they don't explicitly seem to label those

One good way to check the tree form is to check out the grammar repo and modify one of the corpus files, and run `tree-sitter test --update` using the Tree-sitter CLI. Here is a diff I got:

```
diff --git a/corpus/number/numberUnderscores.txt b/corpus/number/numberUnderscores.txt
index 16c98e9..c60f793 100644
--- a/corpus/number/numberUnderscores.txt
+++ b/corpus/number/numberUnderscores.txt
@@ -26,2 +26,4 @@ res21 = 0o755
 res22 = 0o7_5_5__
+res23 = 5.min
+res24 = true.xor(false)
 
@@ -98,2 +100,14 @@ res22 = 0o7_5_5__
     (identifier)
-    (intLiteral)))
+    (intLiteral))
+  (classProperty
+    (identifier)
+    (propertyCallExpr
+      (intLiteral)
+      (identifier)))
+  (classProperty
+    (identifier)
+    (methodCallExpr
+      (trueLiteral)
+      (identifier)
+      (argumentList
+        (falseLiteral)))))
```

Based on that, you could make this patch to handle the pure literal cases:

```
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm b/docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
index 4ac335590ae..f3db64ed547 100644
--- a/docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
+++ b/docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
@@ -126,2 +126,6 @@
 
+; Units of measure
+(propertyCallExpr (intLiteral) (identifier) @identifier.type)
+(propertyCallExpr (floatLiteral) (identifier) @identifier.type)
+
 (parameterList (typedIdentifier (identifier) @variable.parameter))
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap b/docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
index 06533df8eba..8aff890a0d8 100644
--- a/docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
+++ b/docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
@@ -221,3 +221,3 @@ expression: "snapshot_treesitter_syntax_kinds(&document, &contents)"
 //             ^ PunctuationDelimiter
-//              ^^^ Identifier
+//              ^^^ IdentifierType
   xySeconds = (x + y).s
@@ -239,3 +239,3 @@ expression: "snapshot_treesitter_syntax_kinds(&document, &contents)"
 //             ^ PunctuationDelimiter
-//              ^ Identifier
+//              ^ IdentifierType
 //                 ^^^^^^^^^^^^^^^^^^^^^^^^ Comment
@@ -607 +607,3 @@ expression: "snapshot_treesitter_syntax_kinds(&document, &contents)"
 //            ^^^^^^ StringLiteral
+  
+
```

However, because this is also supported for more complex expressions, when the grammar sees `foo.s`, it is not clear whether it is OK to unambiguously interpret that as marking it as a duration in seconds, or whether if the `foo` object actually has an `s` field, then this does a field projection instead of a wrapping operation. Since we can only mark durations in the literal cases, it would lead to inconsistent highlighting in other cases.

I've filed a bug against the tree-sitter-pkl repo for this: https://github.com/apple/tree-sitter-pkl/issues/6

2024-03-31 04:12 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
> +        }
```suggestion
        if_chain! {
            if language_from_syntect.raw.is_empty()
                || language_from_syntect.raw.to_lowercase() == "plain text";
            if let Some(extension) = filepath.extension();
            if let Some(parser_id) = ParserId::from_file_extension(extension.to_str().unwrap());
            then {
                return TreeSitterLanguageName::new(parser_id.name());
            }
        }
```

After adding `use if_chain::if_chain` (you can see other examples in the code), since this feature isn't stabilized yet. https://github.com/rust-lang/rust/issues/53667

2024-03-31 04:13 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/tree_sitter.rs
> +            let language = get_language_for_test(&filepath, &contents);
There is another code path doing a similar dance in `fn test_files_with_locals`, please update that too to avoid divergence.

2024-03-31 04:27 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +            }
Please follow up on this comment before marking this comment thread as resolved.

> The correct fix would be to modify `func getLanguagesByExtension` in Go and add an extra `map[string]string` `unsupportedByEnryExtensionsMap` until Linguist and consequently go-enry get support for Pkl.

At the moment, you've modified the `baseHighlightConfig`, but that's the wrong place to modify because we want to make sure `.pkl` is detected as the Pkl language everywhere else too, not just for highlighting.

I strongly suggest not touching the Nickel-related code in this PR instead of removing it as it's not related to Pkl.

2024-03-31 04:32 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//               ^ StringLiteral
This is not correct, `+` shouldn't be getting marked as a `StringLiteral`.

2024-03-31 04:52 UTC, varungandhi-src reviewed
Looking much better, will do a further pass later.

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//  ^^^^^^^^^ IdentifierType
`#` is not [valid comment syntax](https://pkl-lang.org/main/current/language-reference/index.html#comments), please remove that here and below.

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//                   ^^^^^^^^ IdentifierType
NaN and Infinity should be marked as builtins rather than as types.

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +(falseLiteral) @constant.builtin
```suggestion
(falseLiteral) @boolean
```

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +(trueLiteral) @constant.builtin
```suggestion
(trueLiteral) @boolean
```

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +(nullLiteral) @constant.builtin
```suggestion
(nullLiteral) @constant.null
```

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +"function" @keyword
```suggestion
"function" @keyword.function
```

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +    ...entries1
Missing occurrence for the `...`?

2024-03-31 04:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +// ^^^^^^^^^^ IdentifierType
Should ideally be IdentifierAttribute for the full range, instead of `IdentifierOperator` and `IdentifierType`

2024-03-31 12:10 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +            }
Thanks, I missed that, will revise .

2024-04-01 15:47 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +
And as you mentioned, I left this as is for now

2024-04-01 15:48 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__pkl.pkl.snap
> +//       ^^^^^^^^^^^^^ StringLiteral
Ok will leave as is , thanks for the info on how to go about it. I understand tree-sitter queries a lot more now

2024-04-01 16:13 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting.rs
> +            }
Updated, thanks for catching.

2024-04-02 13:19 UTC, varungandhi-src commented on docker-images/syntax-highlighter/Cargo.Bazel.lock
> +          "url": "https://static.crates.io/crates/adler/1.0.2/download",
It's a recent change. https://blog.rust-lang.org/2024/03/11/crates-io-download-changes.html

2024-04-03 21:02 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/pkl/highlights.scm
> +(objectBodyParameters (typedIdentifier (identifier) @variable.parameter))
I added the following example which does parse as ObjectBodyParamters
```
// dynamic object with object body parameters
birds = new Dynamic {
  default { _ ->
    species = "Bird"
  }
  ["Falcon"] {}
}

```


```
module [0, 0] - [6, 0]
  (classProperty [0, 0] - [5, 1]
    (identifier [0, 0] - [0, 5])
    (newExpr [0, 8] - [5, 1]
      (type [0, 12] - [0, 19]
        (qualifiedIdentifier [0, 12] - [0, 19]
          (identifier [0, 12] - [0, 19])))
      (objectBody [0, 20] - [5, 1]
        (objectProperty [1, 2] - [3, 3]
          (identifier [1, 2] - [1, 9])
          (objectBody [1, 10] - [3, 3]
            (objectBodyParameters [1, 12] - [1, 16]
              (typedIdentifier [1, 12] - [1, 13]
                (identifier [1, 12] - [1, 13])))
            (objectProperty [2, 4] - [2, 20]
              (identifier [2, 4] - [2, 11])
              (slStringLiteral [2, 14] - [2, 20]))))
        (objectEntry [4, 2] - [4, 15]
          (slStringLiteral [4, 3] - [4, 11])
          (objectBody [4, 13] - [4, 15]))))))
          ```

2024-04-04 16:28 UTC, merged