release: sg release cut
sourcegraph/sourcegraph pull request #61623
Opened 2024-04-05 10:42 UTC by BolajiOlajide

## Test plan

N/A

2024-04-25 03:20 UTC, Chickensoupwithrice approved these changes
Looks good!

Not a blocker, but some further thoughts: 
How do we decide version numbers, especially with `auto` being a part of `create` which comes after `cut`? Should we integrate `auto` here instead? 
Is it expected that the version numbers be different between the two given the time difference?

2024-04-25 14:43 UTC, jhchabran requested changes
It's great that you never shy away from adding `sg` commands @BolajiOlajide 🙏 

I'm requesting changes here, because there's some duplicate code with an existing package that you weren't (I suppose) aware of. I've shared a link in the comments.

2024-04-25 14:43 UTC, jhchabran commented on dev/sg/internal/execute/exec.go
> +package execute
While the wrapping part is nice, you might prefer to use github.com/sourcegraph/run 

Also, recently @burmudar made a pass on Git helpers as well, see https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ea689de4d74f2c9f5647a20bb31ec011aa69b8e0/-/blob/dev/sg/internal/repo/git_repo.go which is a better home for this.

2024-04-25 14:43 UTC, jhchabran commented on dev/sg/internal/release/cut.go
> +	defaultBranch := "main"
Why not turn this into a flag with a default? It will get us more context when running `--help`.

2024-04-29 12:15 UTC, BolajiOlajide commented on dev/sg/internal/release/cut.go
> +	defaultBranch := "main"
Done

2024-04-29 12:37 UTC, jhchabran approved these changes

2024-04-29 12:37 UTC, jhchabran commented on dev/sg/internal/execute/exec.go
> +package execute
This is still using `os.Exec` but it's fine, moving on, as it's not really important especially now it's simpler :)

2024-04-29 13:08 UTC, BolajiOlajide commented on dev/sg/internal/execute/exec.go
> +package execute
I'll move those in a follow up PR, I'll add a TODO for that now. It'll require a bit of work (mostly because the helpers don't have some of the functionality used by the callers of the function in here) and I don't want to complicate this PR.

2024-04-29 13:11 UTC, jhchabran commented on dev/sg/internal/execute/exec.go
> +package execute
Yeah, this is why I approved anyway 😊

2024-04-29 13:22 UTC, merged

2024-05-20 09:48 UTC, craigfurman commented on dev/sg/internal/backport/backport.go
> +	if _, err := backportBranchRepo.FetchOrigin(cmd.Context); err != nil {
@BolajiOlajide I think this might have broken backporting, since we try to fetch a remote branch that we never pushed, having just created it locally a few lines up.

If I'm right (which I might not be!), it might be the cause of this issue: https://sourcegraph.slack.com/archives/C02E4HE42BX/p1716198421187289?thread_ts=1716192268.358549&cid=C02E4HE42BX