Graph: Support JSX syntax highlighting
sourcegraph/sourcegraph pull request #62027
Opened 2024-04-19 02:10 UTC by mmanela

Fixes ENG-20458

Adds support to highlight JSX files. Follows the same pattern we followed for highlighting TSX file. I didn't reuse the same code since I wanted to leave open the option for JSX/TSX coloring divergence in the future 

<img width="562" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/304410/575197e0-2d6d-4745-aff0-4b20e493fbe1">

## Test plan
- Added unit test
- Manual testing

2024-04-19 02:12 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/jsx/highlights.scm
> +(jsx_attribute (property_identifier) @identifier.attribute)
@varungandhi-src This is the only thing we were specifically highlighting in our tsx file so I kept this the same here

2024-04-19 06:35 UTC, varungandhi-src requested changes
For the source of truth, we rely on languages.yml in Linguist, because language detection going forward is based on go-enry, which in turn is based on Linguist. Yes, there is some old code relying on language detection from syntect, but we want to rely on that less with time.

https://sourcegraph.com/github.com/github-linguist/linguist/-/blob/lib/linguist/languages.yml

You'll notice that TSX and TypeScript are listed as separate languages there, whereas the 'jsx' file extension is present on JavaScript. So we should not introduce a new language/ParserId for JSX here, we should instead:
1. Add the JSX-specific query to the JavaScript queries
2. Make sure that `.jsx` files are getting mapped to `JavaScript` in the language detection code in our Go wrapper code for go-enry in `package languages`.

When `JavaScript` (or `javascript`) is passed as the language from the Go code, we should use the correct Tree-sitter grammar automatically.

2024-04-20 02:37 UTC, mmanela commented on internal/highlight/language.go
> -		"jsx":  "jsx", // default `getLanguage()` helper doesn't handle JSX
This is not needed, since go-enry properly returns jsx as javascript which is what we want

2024-04-22 04:12 UTC, varungandhi-src commented
I noticed that the SCIP kind was copied from tsx/highlights.scm and it was incorrect there too. So I've fixed the SCIP kinds (see scip.proto for descriptions https://github.com/sourcegraph/scip/blob/main/scip.proto#L582-L583). It looks like `@identifier.attribute` is actually being misused in a bunch of queries, we should fix those later.

Updated screenshots in light mode and dark mode.

![CleanShot 2024-04-22 at 12 00 54@2x](https://github.com/sourcegraph/sourcegraph/assets/93103176/758ab794-503c-41dd-99ef-63b2370ead89)
![CleanShot 2024-04-22 at 11 58 54@2x](https://github.com/sourcegraph/sourcegraph/assets/93103176/01411fc7-b9c7-4368-bcb7-c27f49a2304d)

2024-04-22 04:14 UTC, varungandhi-src approved these changes

2024-04-22 04:14 UTC, varungandhi-src commented on internal/highlight/language_test.go
> +	cases := []testCase{
```suggestion
	// JSX is mapped to javascript but TSX is mapped to 'tsx' language
	// because Linguist contains a separate language for TSX but not JSX
	cases := []testCase{
```

2024-04-22 19:05 UTC, merged