WIP: Move SSC frontend to the monorepo
sourcegraph/sourcegraph pull request #62058
Opened 2024-04-19 21:06 UTC by vdavid

Little progress with moving the SSC front end to the monorepo.

Caveats / WIP parts:
- Three major components missing
- Need to replace Tailwind styling with CSS (Cody or ChatGPT should help)
- Need to replace icons with Wildcard icons
- Need to import Stripe through `@sourcegraph/cody-plg` rather than directly
- "refetch" needs to be mocked
- Absolutely untested

## Test plan

Move first, then make sure it works with the mocked back end. Once it works, we can merge this branch behind a feature flag if needed. Without a feature flag, it might be confusing: even if we don't publish the link anywhere, someone might stumble upon it.
But we could also just continue by connecting it to the back end.

2024-04-19 21:22 UTC, chrsmith reviewed
Some minor suggestions about how to make sure we can minimize confusion during the transition.

2024-04-19 21:22 UTC, chrsmith commented on client/cody-plg/package.json
> +  "name": "@sourcegraph/cody-plg",
I'd suggest we try to avoid using the phrase "Cody PLG" **wherever** possible. It just isn't a good, descriptive name. (It's a strategy, not an actual product or component.)

Instead, I'd suggest we use something like `cody-pro`. That is, it is functionality specific to the Cody Pro SKU of the Cody Product. (Separate from, say, `Cody-enterprise`.) That however, is still misleading, because "Cody Free" is another SKU too... but it's much closer to `cody-plg` than `Cody-enterprise`.


Regardless, I'd love to avoid putting `cody-plg` into a top level folder name if we can avoid it.

2024-04-19 21:22 UTC, chrsmith commented on client/web/src/cody/plan/CodyPlanPage.tsx
> +export const CodyPlanPage: FunctionComponent = () => {
What is the distinction between `client/web/src/cody/...tsx` and `client/cody-plg/package.json`?

Would we want this to be in `client/web/src/cody-plg` (or `cody-pro`) because it is specific to the non-Enterprise queue? (I have no idea how the code is organized here, so perhaps this is a dumb question.)

2024-04-19 21:22 UTC, chrsmith commented on cmd/frontend/internal/app/ui/router.go
> +		{path: "/cody/manage", name: "cody-manage", title: "Cody Manage", index: false},
Would you mind adding some doc comments here, to clarify what things are "in use today" vs. "part of our temporary moving the SSC-specific UI into dotcom"?

It will very likely be a source of confusion, e.g. why _some_ Cody pages are behind a feature flag, and yet others aren't. So trying to head that off and make that clear during this (hopefully brief 🤞) transition period would be helpful.

2024-04-19 21:24 UTC, chrsmith commented on client/cody-plg/package.json
> +  "name": "@sourcegraph/cody-plg",
Thinking about this a little bit more, I still don't like having `cody-plg` in the code, but this probably is the best name.

Since we do _not_ want to hard-code the UI based on the SKU. (Since e.g. suppose we have an Enterprise feature that we later want to make available to Cody Pro. That shouldn't require refactoring the codebase! Only just changing some flags.)

However, this PR and the current set of UI elements we are migrating are _not_ about features per-say. But really, the crux of the entire "Cody Pro" experience. So yeah, `cody-plg` is probably the best term to use. #namingishard

2024-04-27 05:40 UTC, chrsmith requested changes
Hey @vdavid, so I spent the day poking at the sg/sg repo and trying to get things wired in. And I think we should start with a different approach for the "first step" in migrating the SSC UI. (I'll send it out for review shortly.)

There are a few things that I think we want to do differently.

**We shouldn't fuss with a separate NPM package for now**

While we may want to do this eventually, I don't think we are ready to try and have an NPM package separate the "Cody Pro" and "Cody Enterprise" UI. Because they are _already_ deeply intertwined, and kinda broken. So adding an NPM package in the mix would just add overhead without actually improving the situation.

For example, the `[cody/subscription](https://sourcegraph.com/cody/subscription)` page shows the Cody SKUs side by side. (Which is something we'd want on the "Cody Pro" site, but not "Cody Enterprise"... however if you try view that same page on S2 (https://sourcegraph.sourcegraph.com/cody/subscription) you get a nice 500 error.

Similarly, the "Cody Dashboard" page acts/behaves totally differently for Cody Pro and Cody Enterprise, too.

So as far as migrating the ~3 UI pages from the SSC UI into the monorepo, I think we shouldn't try to isolate them in their own NPM package. (As it doesn't really provide any benefit.)

And instead, try to get the basics right about which pages should serve a 404 vs. be displayed. Clearly delineating any SKU-specific functionality or APIs, etc.

**Is a "site config setting" preferable to "temporary setting"?**

I may totally be wrong, but from what I could find about "[Temporary Settings](https://docs.sourcegraph.com/dev/background-information/web/temporary_settings)", I don't know if they are the right fit for what we are trying to enable. (And neither is a feature flag for that matter.)

Just having a boolean site configuration option, e.g. `ssc.embeddedUIEnabled` seemed like the least complicated option. As well as being more easily accessible (via `window.context`) rather than a React hook. (Maybe?)

2024-06-13 20:35 UTC, vdavid commented
Closing this as obsolete

2024-06-13 20:35 UTC, closed without merging