feat(sg/release): allow auto versioning on release
sourcegraph/sourcegraph pull request #62106
Opened 2024-04-23 02:05 UTC by Chickensoupwithrice

This adds `--version auto` functionality to `sg` for performing releases. Resolves 

One concern I have about this is that it hard codes the sourcegraph endpoint specifically, but we use `sg release create` in various other repos. Currently we only use `sg release` to deploy sourcegraph (alongside deploy-* where we would instead want to query the latest public release and use that number, rather than generate a new one), but this sets the wrong precedent. 

I don't see a clear path towards calling this in a `release.yaml`, and hard coding specific git repo seems like a bad idea too. Welcome to suggestions. 

## Test plan

Manually tested locally:

<img width="755" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/22575913/fc686466-ba8a-41a1-b3fe-b27d4a1d952e">

2024-04-23 09:10 UTC, craigfurman commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
I'm new to release registry / sg-release, so I might be missing context, but: why do we hardcode the minor version here? If the patch version is the awkward thing to determine, perhaps we ask the user to specify the major.minor, e.g. instead of `sg release create --version auto`, something like: `sg release create --next 5.3`?

More of a question than a blocker!

2024-04-23 11:06 UTC, BolajiOlajide requested changes

2024-04-23 11:06 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
Yeah, we can't hardcode the `<major>.<minor>` version for the release registry endpoint.

![CleanShot 2024-04-23 at 12 04 13@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/37e37f9b-ef58-4e58-8d1e-55f62cd58192)

Could we use the Github endpoint to fetch the latest release and parse the `tag_name` to get the `<major>.<minor>` version to use.

```
curl https://api.github.com/repos/sourcegraph/sourcegraph/releases/latest | jq '.tag_name'
```

2024-04-23 12:47 UTC, craigfurman commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
@BolajiOlajide is it a safe assumption that we are always building a release on the latest minor series? Do we always roll forward, or do we maintain multiple patch series? e.g. backport a patch to older, but still maintained, minor series

2024-04-23 14:27 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
This is true for patch release bumps (monthly / patch releases).

2024-04-23 14:36 UTC, craigfurman commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
💡 right, so when (e.g.) 5.4.PATCH comes out, there will be no more 5.3 releases?

2024-04-23 14:40 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
Correct. And for that, we'd have to specify the version explicitly and not use the `auto` flag.

2024-04-23 21:10 UTC, Chickensoupwithrice commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
Good catch! I re-worked this such that we don't hardcode the `<major>.<minor>` in the URL, but still call out to `releaseregistry` rather than Github Releases. However, it's using latest id instead of latest release time, which may be a problem still? Currently the way the `releaseregistry` is seeded, newer IDs correspond to newer releases, but this assumption is not necessarily true?

2024-04-23 21:11 UTC, Chickensoupwithrice commented
Updated to no longer hardcode `<major>.<minor>` in the URL requesting the next version. 

Tested locally again:

<img width="755" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/22575913/d5b420cd-9c48-46d2-bca1-ede3c51645d5">

2024-04-24 08:35 UTC, craigfurman approved these changes
🚀

2024-04-24 08:35 UTC, craigfurman commented on dev/sg/internal/release/release.go
> +	newestVersion := versions[0].Version
non-blocking note: we should probably check the length of versions first, but tbh the resultant panic if it is zero-length will be pretty obvious too, so no big deal!

2024-04-24 12:45 UTC, BolajiOlajide requested changes

2024-04-24 12:45 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +func DetermineMinorVersion() (string, error) {
Tiny nit: This function isn't used anywhere else so no need to export it, same with the `ReleaseInfo` struct.

2024-04-24 12:45 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +		fmt.Print(err)
We don't need this `fmt.Print` since we're returning the error already.

I'm guessing this was left there during debugging.

2024-04-24 12:45 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +	latestVersionBody, _ := io.ReadAll(latestVersion.Body)
How about we check the status code of the response before reading the body, that way if the status code isn't 200, we can return err.

Lastly, it might not be a bad idea to `defer latestVersion.Body.Close()` so it runs as a cleanup.

2024-04-24 12:45 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +	newestVersion := versions[0].Version
Yeah, +1 to what craig said.

If the version specified doesn't exist, the API returns `nil` so it's better to have a `len(versions) == 0` check.

2024-04-24 12:45 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +	newestVersion := versions[0].Version
Also, to be safe, I'd pass the `.Version` with `semver.New` or `semver.Parse` (Can't remember the API signature), then that way we can get the patch and minor version by calling

`.Patch`
or
`.Minor`

2024-04-24 17:43 UTC, Chickensoupwithrice commented on dev/sg/internal/release/release.go
> +	latestVersionBody, _ := io.ReadAll(latestVersion.Body)
Is status code errors not part of `err`?

2024-04-24 17:46 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +	latestVersionBody, _ := io.ReadAll(latestVersion.Body)
No. This will return an error if there was an error with making the request, but it won't necessarily throw an error if the request returns an error code . For example, it won't return an error because the request 404'd.

You'd explicitly need to check the .StatusCode field of the http response.

Sorry the formatting of my message is bad, i'm typing from my mobile.

2024-04-24 18:15 UTC, craigfurman commented on dev/sg/internal/release/release.go
> +	latestVersionBody, _ := io.ReadAll(latestVersion.Body)
What bolaji said is right: If you get a legal HTTP response back, err will be nil. That err is basically for transport errors only

2024-04-24 19:04 UTC, Chickensoupwithrice commented on dev/sg/internal/release/release.go
> +	url := fmt.Sprintf("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/%s", strconv.FormatInt(newestVersion.Major(), 10) + "." + strconv.FormatInt(newestVersion.Minor(), 10))
I'm not sure this is much better than what I was doing previously, but at least it's type checked?

2024-04-25 16:46 UTC, BolajiOlajide approved these changes

2024-04-25 16:46 UTC, BolajiOlajide commented on dev/sg/internal/release/release.go
> +func determineMinorVersion(ctx context.Context) (string, error) {
```suggestion
func determineNextReleaseVersion(ctx context.Context) (string, error) {
```

2024-04-26 08:22 UTC, jhchabran commented on dev/sg/internal/release/release.go
> +		resp, err := http.Post("https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph/next/5.3", "", nil)
> 5.4.PATCH comes out, there will be no more 5.3 releases 

We might have to release an emergency patch though, so we don't want to cut one nor we plan to, but we may have to.

2024-04-26 08:31 UTC, jhchabran requested changes
Thanks! Comments are minor, and easy to fix but I believe that the status code error should at least be fixed before merging this.

2024-04-26 08:31 UTC, jhchabran commented on dev/sg/internal/release/release.go
> +// Determines latest major.minor.patch version number by hitting the releaseregistry
nit: godoc conventions are to start the comment with the function name. 

```suggestion
// determineNextReleaseVersion determines latest major.minor.patch version number by hitting the releaseregistry
```

2024-04-26 08:31 UTC, jhchabran commented on dev/sg/internal/release/release.go
> +	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "https://releaseregistry.sourcegraph.com/v1/releases/sourcegraph", nil)
nit: extracting this to a constant will open up the path for a later PR to use a flag to swap the endpoint. Why wouldn't you want to use the `dev` variant of the deployment when iterating locally?

2024-04-26 08:31 UTC, jhchabran commented on dev/sg/internal/release/release.go
> +		return "", errors.New("Releaseregistry did not return statuscode 200")
This error message won't help to understand what's wrong, because we're not sharing what was the status code. We should log the status code and the body if any.

2024-04-26 08:31 UTC, jhchabran commented on dev/sg/internal/release/release.go
> +	bodyBytes, _ := io.ReadAll(resp.Body)
Why skip handling the error here?

2024-04-26 08:31 UTC, jhchabran commented on dev/sg/internal/release/release.go
> +		return "", errors.New("Releaseregistry did not return statuscode 200")
Same

2024-04-26 08:31 UTC, jhchabran commented on dev/sg/internal/release/release.go
> +		return "", errors.New("Releaseregistry did not return statuscode 200")
```suggestion
		return "", errors.Newf("API error, got status %d", resp.StatusCode)
```

2024-04-26 18:14 UTC, jhchabran approved these changes

2024-04-26 18:37 UTC, merged