Add new ssc.useEmbeddedUI site configuration setting
sourcegraph/sourcegraph pull request #62224
Opened 2024-04-27 05:49 UTC by chrsmith

Adds a new ssc.useEmbeddedUI site config value. If set along with `SOURCEGRAPHDOTCOM_MODE`, it controls whether or not a new "Subscription Management Page" is available in the UI. (On `/cody/manage/subscription`.)

This is essentially a spiritual successor to @vdavid 's PR https://github.com/sourcegraph/sourcegraph/pull/62058. The objective is to start migrating the SSC UI pages into the monorepo. So as a first step, this PR just tries to get the mechanism by which we can enable/develop these new pages right.

After doing my best to research the options, I think (and may be totally wrong) that a site configuration setting is the most straight-forward option. We could make a "feature flag" or "temporary setting" work as well, but the site-config option seemed to be the easiest to grok.

As far as what that new `ssc.useEmbeddedUI` option controls, I just stubbed out a new `ManageSubscriptionPage` page. Served from `/cody/manage/subscription`, and not to be confused by `/cody/subscription` or `/cody/manage`. (And yes, we may want to revisit our URL layout as what we have today isn't particularly clear.)

## Test plan

Ran locally and confirmed we show a 404 if the site config value isn't set.

<img width="367" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/4029847/4b272135-f055-4239-a426-f727a520a720">

Otherwise, you are greeted with this beautiful sight:

<img width="1207" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/4029847/900e2dbb-2ef8-473b-aa22-706f26807c95">

2024-04-27 17:03 UTC, chrsmith commented on schema/site.schema.json
> +    "ssc.useEmbeddedUI": {
Actually, rather than having several properties with the "ssc" prefix, we should probably just bite the bullet and have an `object` bundling everything. e.g.

```json
...
"codyProConfig": {
      "type": "object",
      "properties": {
          "useEmbeddedUI": {
          "type": "boolean",
          "default": false,
          }
     }
}
...
```

This way we can isolate all of the Cody Pro-specific configuration settings, such as the Stripe publishable key, URLs to the SSC backend, etc.

2024-04-28 04:37 UTC, thenamankumar requested changes
The overall scaffolding looks good. Have left 2 comments. Highly recommend using feature flag to control the visibility of this feature rather than the site config.

2024-04-28 04:37 UTC, thenamankumar commented on client/web/src/cody/management/subscription/ManageSubscriptionPage.tsx
> +        telemetryRecorder.recordEvent('cody.new-subscription-checkout', 'view')
Event name should be updated to `cody.manage-subscription`, `view`.

2024-04-28 04:37 UTC, thenamankumar commented on client/web/src/cody/management/subscription/ManageSubscriptionPage.tsx
> +                                Hello {authenticatedUser?.displayName}. Depending on whether or not you have a Cody Pro
For the upcoming PR implementing what is described in the text here. I recommend to isolate stripe checkout into a separate page and redirect there if no subscription if found on this page.

2024-04-28 04:37 UTC, thenamankumar commented on client/web/src/cody/util.ts
> +    return window?.context?.useSelfServeCodyEmbeddedUI === true
We should not use the site config here but rather use feature flag, which should be simple and also provide us the ability to turn on this feature for specific internal users or all sourcegraph teammates for testing on prod before releasing it to the wider audience. 

I do not think that is possible with site config, or at least as simple as calling `useFeatureFlag`.

You should be able to simply `useFeatureFlag` hook to evaluate the feature flag. It is equally easy to do it at the backend as well.

Enable/Disable a feature flag is also much easy than updating the site config.

2024-04-28 21:26 UTC, chrsmith commented on client/web/src/cody/management/subscription/ManageSubscriptionPage.tsx
> +        telemetryRecorder.recordEvent('cody.new-subscription-checkout', 'view')
Sounds good. But what should we do if we have the same URL (`/manage/subscription`) perform different actions? e.g. if you don't already have a subscription we show the "new subscription flow", and if you do the "manage existing subscription" functionality.

I assume there is no problem with us emitting multiple telemetry events in that case? e.g.

```
ManageSubscriptionPage emits {cody.manage-subscription, view}
... which renders NewSubscriptionComponent, which emits {cody.new-subscription, view}
```

2024-04-28 21:28 UTC, chrsmith commented on client/web/src/cody/management/subscription/ManageSubscriptionPage.tsx
> +                                Hello {authenticatedUser?.displayName}. Depending on whether or not you have a Cody Pro
Gotcha, so `manage/subscription` would redirect to `manage/subscription/new` if the user doesn't have a subscription? And otherwise show the "Update existing subscription" flow?

For reference, I think the latest [Figma designs are here](https://www.figma.com/file/FMSdn1oKccJRHQPgf7053o/Cody-PLG-GA?type=design&node-id=4042-4927&mode=design&t=WGtu3w1Iq7T3ZHCL-0). (But I am not certain.)

2024-04-28 21:43 UTC, chrsmith commented on client/web/src/cody/util.ts
> +    return window?.context?.useSelfServeCodyEmbeddedUI === true
I see the benefits of a feature flag, and having more granular control for rolling things out. But I'm not quite convinced we should start with it. Because we'll need to wire site configuration data to the frontend anyways (for the "Stripe publishable key"). So needing both site configuration _and_ a feature flag to access the new UI seems redundant.

> Just "for now". When we are closer to actually shipping the new functionality, I would totally be onboard with removing `useEmbeddedUI` and requiring a feature flag. But it will be a little bit until we are ready to start testing this outside of `localhost`.)


For reference, this is the current shape of the `dotcom.codyProConfig` as I continue hacking on things.

```json
  "dotcom": {
    ...
    "codyProConfig": {
      "useEmbeddedUI": true,
      "stripePublishableKey": "pk_test_0b1ei45h7ypIEeAkXYKBU059",
      "samsBackendOrigin": "http://localhost:19992",
      "sscBackendOrigin": "http://localhost:19992"
    },
    ...
    // Existing SAMS client credentials, for contacting the SSC backend.
    // Since this is only applicable to the Cody Pro functionality, we can
    // maybe replace the "sams." prefix, with "samsCreds" and put the
    // values in the "dotcom.codyProConfig" block. WDYT?
    "sams.server": "http://localhost:19992",
    "sams.clientID": "sams_cid_...",
    "sams.clientSecret": "sams_cs_..."
    ...
  },
```

2024-04-29 16:14 UTC, thenamankumar commented on client/web/src/cody/util.ts
> +    return window?.context?.useSelfServeCodyEmbeddedUI === true
`useEmbeddedUI` in the site config will not allow us to enable this for internal users before we release this to all the users. Feature flags have a purpose and they are not even difficult to use. It is only one line of code. 

We should focus on doing the things right way and not take shortcuts. I again highly recommend to use feature flag for this. If you need further help in understanding how to implement that, please follow this guide from Sourcegraph docs: https://docs.sourcegraph.com/dev/how-to/use_feature_flags#implement-a-feature-flag

2024-04-29 20:02 UTC, vdavid commented on client/web/src/cody/management/subscription/ManageSubscriptionPage.tsx
> +                <PageHeader className="mb-4 mt-4">
Hmm, does this work? What provides the tailwind classes? 🤔 I don't think we have tailwind in the monorepo, do we?

2024-04-29 20:03 UTC, vdavid commented on client/web/src/cody/management/subscription/ManageSubscriptionPage.tsx
> +                                Hello {authenticatedUser?.displayName}. Depending on whether or not you have a Cody Pro
Yeah, I agree with Naman, it'd be the same or better UX and better devX to have the two features on two separate pages.

2024-04-29 20:03 UTC, vdavid commented on client/web/src/cody/util.ts
> +    return window?.context?.useSelfServeCodyEmbeddedUI === true
Sounds like a great case for a feature flag indeed, and a feature flag is a lot comfier to set and toggle (for testing) than a site config item.

2024-04-29 20:05 UTC, chrsmith commented
I've made a bit more progress on porting the overall SSC UI over, and will be closing this out in favor of the newer changes I have with all the things working end-to-end.

The first PR just adds the site configuration, here: https://github.com/sourcegraph/sourcegraph/pull/62255. I appreciate the feedback Naman, but I still don't think it's worth wiring through both the site configuration and a feature flag. But hopefully I'm able to get things ported over quickly enough that it's a moot point. (That is, replacing the config with a feature flag for rollout, and then have it enabled globally by default so we can remove the setting/flag all together.)

2024-04-29 20:05 UTC, closed without merging

2024-04-29 20:06 UTC, vdavid commented on client/web/src/routes.constants.ts
> +    // Free, Pro, and Enterprise tiers.
I'm unsure if these comments are helpful. This one is inaccurate, as in a mobile view, it's not a side-by-side comparison. Maybe if the comments capture the _function_ of the page rather than its layout, it could be more accurate and future-proof?

2024-04-29 20:07 UTC, vdavid commented on client/web/src/routes.constants.ts
> +    // existing Cody Pro subscription, or sign up for a new Cody Pro subscription.
Note that this might just get inaccurate as soon as we split the two pages.