release: handle more registries for promotion
sourcegraph/sourcegraph pull request #62269
Opened 2024-04-30 08:41 UTC by burmudar

For cloud-ephemeral we want release also to be pushed to it's registry so that people launch ephemeral environments for releases.

This refactor the promotion script to handle handle additional registries. As a follow up a util func will be added to handle formating of the additional registries to ensure they're separated by a ` ` so that array splitting can happen.
## Test plan
Tested locally
vars
```
export VERSION=6.6.666
export PUBLIC_REGISTRY='index.docker.io/sourcegraph-dev'
export ADDITIONAL_PROD_REGISTRY="us.gcr.io/sourcegraph-dev us.gcr.io/sourcegraph/cloud-ephemeral"
export INTERNAL_REGISTRY="us.gcr.io/sourcegraph/internal"
```
```
./tools/release/promote_images.sh gitserver
--- Copying gitserver from private registry to public registries
docker pull "us.gcr.io/sourcegraph/internal/gitserver:6.6.666"
docker tag "us.gcr.io/sourcegraph/internal/gitserver:6.6.666" "index.docker.io/sourcegraph-dev/gitserver:6.6.666"
docker push "index.docker.io/sourcegraph-dev/gitserver:6.6.666"
docker tag "us.gcr.io/sourcegraph/internal/gitserver:6.6.666" "us.gcr.io/sourcegraph-dev/gitserver:6.6.666"
docker push "us.gcr.io/sourcegraph-dev/gitserver:6.6.666"
docker tag "us.gcr.io/sourcegraph/internal/gitserver:6.6.666" "us.gcr.io/sourcegraph/cloud-ephemeral/gitserver:6.6.666"
docker push "us.gcr.io/sourcegraph/cloud-ephemeral/gitserver:6.6.666"
```
Annotation
```
## Release: image promotions

| Name | From | To |
|---|---|---|
| gitserver | `us.gcr.io/sourcegraph/internal/gitserver:6.6.666` |  `index.docker.io/sourcegraph-dev/gitserver:6.6.666` `us.gcr.io/sourcegraph-dev/gitserver:6.6.666` `us.gcr.io/sourcegraph/cloud-ephemeral/gitserver:6.6.666` |

```

2024-04-30 10:12 UTC, BolajiOlajide approved these changes

2024-04-30 14:44 UTC, burmudar commented on tools/release/promote_images.sh
> +while read -r registry; do
hold up

2024-04-30 14:46 UTC, jhchabran requested changes
I see some remaining occurence of `ADDITIONAL_PROD_REGISTRY`: 

![CleanShot 2024-04-30 at 16 46 11@2x](https://github.com/sourcegraph/sourcegraph/assets/10151/401752e8-1ca4-44de-99bb-335160a8d4cc)

2024-04-30 14:52 UTC, burmudar commented
> I see some remaining occurence of `ADDITIONAL_PROD_REGISTRY`:
> 
> ![CleanShot 2024-04-30 at 16 46 11@2x](https://private-user-images.githubusercontent.com/10151/326854388-401752e8-1ca4-44de-99bb-335160a8d4cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODg2ODksIm5iZiI6MTcxNDQ4ODM4OSwicGF0aCI6Ii8xMDE1MS8zMjY4NTQzODgtNDAxNzUyZTgtMWNhNC00NGRlLTk5YmItMzM1MTYwYThkNGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE0NDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMWI5ZDQ5N2UwNzBhMzBiMjRhODI4MTE4NjEwMzZiMWRlYzUxNzY4YzEwZDhkMDdiODFkOGQ5NjY3NDk5NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2KWjQ3kc9OyxaOK9kpaEjgFCJYLpoiFAz_RD1MLPXgo)

Updated. The `push_all` script can already handle multple registries so just updated the env var to be consistent

2024-04-30 15:22 UTC, burmudar commented
> Issue on https://github.com/sourcegraph/sourcegraph/pull/62269/files#diff-08b887c877bc36e59a90a823b4211912dd155bd0c083a033352c0cd94f443137R81 but @burmudar is on it.
> 
> Pre-approving as I'll afk for an hour and it's an easily testable fix.

Testing script
```bash
#!/usr/bin/env bash

ADDITIONAL_PROD_REGISTRIES="index.docker.io us.gcr.io/sourcegraph-dev"

prod_registries=()

if [ -n "${ADDITIONAL_PROD_REGISTRIES}" ]; then
  IFS=' ' read -r -a registries <<< "$ADDITIONAL_PROD_REGISTRIES"
  prod_registries+=("${registries[@]}")
fi

for r in "${prod_registries[@]}"; do
  echo "registry: $r"
done

```

which produces
```
bash test.sh
registry: index.docker.io
registry: us.gcr.io/sourcegraph-dev
```

which shows that the added bash handles splitting of strings into appropriate array values

2024-05-01 19:42 UTC, Chickensoupwithrice approved these changes

2024-05-02 08:16 UTC, merged