SSC: Teams and Invites v1
sourcegraph/sourcegraph pull request #62453
Opened 2024-05-06 13:50 UTC by vdavid

Static version v0.1 is done.

## Test plan

(No tests yet)

2024-05-06 18:23 UTC, chrsmith reviewed
This looks like it is on the right track. And the screen shots you posted on Slack look great!

Most of my feedback can be summed up with:

"This is totally fine for a draft PR. Here is a suggestion for how to clean things up when this is ready for a proper review. (But is more than likely something you were probably already planning on doing anyways, since this is just a WIP Draft.)"

2024-05-06 18:23 UTC, chrsmith commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    useEffect(() => {
We shouldn't keep reimplementing this same check across all of our pages. There is an existing React component that we can use to wrap our pages that will have perform this navigation. (And centralize our logic for handling any edge cases as needed.)

> I'm totally new to the sg/sg repo. And maybe there is some obvious reason why we _shouldn't_ use the existing `withAuthenticatedUser` function.
>
> But even in that case, we should still standardize/centralize how we require the Cody Pro pages to perform any authentication/authorization checks. Since later, we'll want to make it easy to decouple the "React Page" from any sort of auth check and/or pre-fetching. e.g. confirming that the current user is an admin of the Cody Pro team they are accessing.

```ts
import { withAuthenticatedUser } from '../../../../auth/withAuthenticatedUser'

...

// Step 1. Define the `*Props` object where `AuthenticatedUser` is not null/undefined.
interface NewCodyProSubscriptionPageProps extends TelemetryV2Props {
    authenticatedUser: AuthenticatedUser
}

// Step 2. Define the `Authenticated*` component, like you normally would.
const AuthenticatedNewCodyProSubscriptionPage: React.FunctionComponent<NewCodyProSubscriptionPageProps> = ({
    authenticatedUser,
    telemetryRecorder,
}) => {
    ...
}

// Step 3. At the bottom of the file, export the component wrapped in
// the `withAuthenticatedUser` function.
port const NewCodyProSubscriptionPage = withAuthenticatedUser(AuthenticatedNewCodyProSubscriptionPage)
```

2024-05-06 18:23 UTC, chrsmith commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    const teamMembers = [
👍

2024-05-06 18:23 UTC, chrsmith commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    const revokeAdmin = useCallback(
This might be too specific. Right now we only have { member, admin }. But it isn't too unreasonable to think that we'd support other types of "roles" in the future. (e.g. a billing admin, or team admin. Things that grant some -- but not all -- privileges.)

So perhaps we would want to revise this to just be `cody.team.modifyMemberRole` instead?

2024-05-06 18:23 UTC, chrsmith commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    const revokeInvite = useCallback((): void => {
Rather than having N-different one-off telemetry callbacks like this. Can we just put this all into a dedicated service, e.g. `./CodyTelemetry.ts`?

That would allow for the type checker to catch usage errors, as well as cut down on the boiler plate. And also mean that if you want to know the events that we do record, you could just look in one place. Rather than searching the codebase for string literals that may-or-may-not be consistent in naming.

So the usage would look something like:

```ts
const codyTelemetry = new CodyTelemetry(telemetryRecorder)

...
<button
    onClick={() =>
        codyTelemetry.recordMemberRemoved(currentUserId, currentTeamId)
        ...
    }>
    ...
```

2024-05-06 18:23 UTC, chrsmith commented on client/web/src/routes.tsx
> +                condition={({ licenseFeatures }) => licenseFeatures.isCodyEnabled}
This `CodyManageTeamPage` is only applicable to Cody Pro. (Since we have no plans for having "Teams or Invites" apply to Cody Enterprise, nor would that really make sense.)

So before this is submitted we would just want to update this condition to have a more specific check. e.g. the `featureFlag(use-embedded-ui)` or at the very least `isDotComMode`.

(But for a Draft PR, don't worry about it. I would suggest just adding a `// TODO:` or `// DO NOT SUBMIT UNTIL: ...` type of comment to make sure we address this before submitting the code.

2024-05-06 19:03 UTC, vdavid commented on client/web/src/routes.constants.ts
> +    CodyManageTeam = '/cody/manage-team',
`/cody/manage/team` was the original URL (actually, I used `/cody/team/manage`), but it clashed with the app's routing and went to some search page every time, so I was like "okay, I'll just cut this short and use one less depth in the path. 🤷 But yeah, I agree it'd be nicer.
And I think in the case of no-admin-privileges, we might just redirect the user to `/cody/team` or something. I wouldn't want to blend the two, they feel too different.

2024-05-06 19:09 UTC, chrsmith commented on client/web/src/routes.constants.ts
> +    CodyManageTeam = '/cody/manage-team',
I'm pretty sure this is the culprit, and so perhaps the _ordering_ of how we register the routes matters.

```ts
    {
        path: PageRoutes.CodyChat + '/*',  <--------
        element: (
            <LegacyRoute
                render={props => (
                    <CodyIgnoreProvider isSourcegraphDotCom={props.isSourcegraphDotCom}>
                        <CodyChatPage
                            {...props}
                            context={window.context}
                            telemetryRecorder={props.platformContext.telemetryRecorder}
                        />
                    </CodyIgnoreProvider>
                )}
                condition={({ licenseFeatures }) => licenseFeatures.isCodyEnabled}
            />
        ),
    },
```

> okay, I'll just cut this short and use one less depth in the path. 🤷 But yeah, I agree it'd be nicer.

Given how much of a pain it is to gracefully migrate URL routes, I'd suggest we figure this out and fix our over-zealous Cody Chat handler. Reserving all of `/cody/*` URLs is not a good idea. (And should instead be something like `/cody/chats/*`.)

> And I think in the case of no-admin-privileges, we might just redirect the user to /cody/team or something

That doesn't sound like a good idea, IMO. Because we would be coupling the "expected user permissions" with the URL route. And that seems like a recipe for bugs.

Similarly, if we registered the two different URL routes (a read-only `/cody/team` and a read/write `/cody/team/manage`), then it's another source of bugs coming from "I am a team admin, but why don't I see any edit buttons?!?

So I'd suggest we just have a _single_ `/cody/team` page, and depending on the current users permissions show/hide more UI options. (Not that I couldn't be convinced of the "redirect approach", just that it makes it possible to have a certain class of bug that having a single route does not.)

2024-05-06 19:17 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +                <div className={classNames('p-4 border bg-1 d-flex flex-column', styles.container)}>
Yeah, I agree. I'll see how long the page gets (probably too long) and break it down if it reaches the threshold where it feels wrong.

2024-05-06 19:18 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    const revokeInvite = useCallback((): void => {
I'm not entirely convinced if it'd be an improvement, but I'll keep it in mind! Thanks for the idea!

2024-05-10 13:12 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +                setIsProUser(responseJson && !!responseJson.endedAt)
@chrsmith, this seemed like the best way to determine whether the user is Pro or not based on [this type](https://github.com/sourcegraph/self-serve-cody/pull/758/files#diff-de206eea9a9e38fe5be3f50203844adc997915ddab0496ee9e4d815953d51623R126). Is this fine or can you recommend a better solution?

2024-05-10 13:13 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +        return Math.max(subscriptionSeatCount || 0 - (memberCount + invitesUsed), 0)
@chrsmith let me know if you have a better suggestion to calculate this based on the available data.

2024-05-10 14:19 UTC, vdavid commented on client/web/src/routes.constants.ts
> +    CodyManageTeam = '/cody/manage-team',
Hmm, now it just magically works, without any changes to other routes. I've just done the URL change (to `/cody/team/manage` because that seemed better) and accepted that it works. If the problem arises again, I'll investigate.

2024-05-10 23:16 UTC, chrsmith requested changes
There's a lot of good stuff in this PR, and it's super-exciting to see the Teams and Invites functionality come together! But I think this PR still needs a bit more work before it is checked-in.

As far as a next step, let's try to see if we can find a time to review this PR in a VC meeting so we can discuss tradeoffs more quickly. (I can come in a couple hours earlier any day of the week, just let me know with some notice.)

Overall, each of my PR comments probably boils down to one of the following:

1. A starting point for discussing how we want to build Cody Pro. e.g. not so much a concrete suggestion, but more double checking how we want to approach certain aspects of the design or UX.

2. Engineering rigor types of things that I (annoyingly) won't budge on. We are going to create a Cody Pro codebase that we will be proud of, and be constructed in such a way that anybody on the team will be able to easily and safely make changes to. This will require adding some layers of abstraction or formalizing things to a higher degree than immediately seems required. But alas, "sorry not sorry".

3. Engineering rigor types of things that I (perhaps reluctantly) will budge on. While I have suggestions for how to make the code easier to read or maintain, you don't need to accept every single one. (Nor should you?) Maybe I'm just factually wrong. Or it's a matter of opinion, and you just prefer it some other way. Or we both acknowledge that something is wrong, but it just doesn't make sense to deal with it at this time.

Unfortunately I cannot say for certain which things fall into camp 2 vs. camp 3. (In the extremes, some things are clearly "wrong", IMO and other things I could easily be convinced are A-OK.)

But it'll probably take some time for us to norm on where exactly we want to draw the line here. e.g. coming up with a standard for code quality that we want to shoot for on the Cody Prime team. Or the degree to which we rely on sophisticated data types or design patterns in order to make it easier to write correct code.

Anyways, if you could try to address the PR feedback that you agree we can figure out the best way to address some of these other issues next week. (e.g. I'll try to send out a PR with a TypeScript "API client library" for the SSC backend API, which will address some of the things I call out.)

2024-05-13 12:05 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +                <div className={classNames('p-4 border bg-1 d-flex flex-column', styles.container)}>
I broke it down since, so closing this thread.

2024-05-13 12:23 UTC, vdavid commented on client/web/src/cody/management/subscription/new/CodyProCheckoutForm.tsx
> +import type { Stripe } from '@stripe/stripe-js'
Not sure I get your concern. I mean, this is how you import stuff in TypeScript?
If you do otherwise (use `import` where `import type` is enough, you get an "ESLint: All imports in the declaration are only used as types. Use `import type`.(@typescript-eslint/consistent-type-imports)"
I've never seen the linter fail in this.

2024-05-13 12:24 UTC, vdavid commented on client/web/src/cody/management/subscription/new/CodyProCheckoutForm.tsx
> +import type { Stripe } from '@stripe/stripe-js'
I'll just resolve this for now, feel free to reopen if this is a category #2 brick wall type of issue you want to go deeper into.

2024-05-13 12:31 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    const newSeatsPurchasedParam = parameters.get('newSeatsPurchased')
It works but it isn't wired up. To try it, pass `?newSeatsPurchased=5` to the page. It's for the case when you've just added a few seats to your subscription.
_Not_ everything is wired up in this PR, this is an incremental improvement. I've added task list item "Wire up the "newSeatsPurchased" param on the checkout page to pass the number of new seats." [here](https://github.com/sourcegraph/self-serve-cody/issues/725) to track this and make sure there are no loose ends.

2024-05-13 12:47 UTC, vdavid commented on client/web/src/cody/util.ts
> +        ...(!['GET', 'HEAD'].includes(method) && params ? { body: JSON.stringify(params) } : null),
The solution I implemented is idiomatic with our codebase, and with TypeScript standards.
[This line](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web-sveltekit/src/lib/Hotkey.ts?L72) is closest to what I found to this in our codebase. It is 13 days old, so it's not that it's some legacy stuff we're trying to get rid of.
It might be different from what you're used to, and I understand you find it hard to read but I'm finding the word "unacceptable" _way_ too harsh for this.
I'm willing to change my code to whatever you suggest as long as it's functional in order to get my PR merged because I want to get the project done in time. But I strongly hold that my solution is way more elegant, more readable, and more idiomatic with our codebase than the alternative you suggested.
For now, I'm closing this thread as I've considered your suggestion in good faith, but I disagree. Feel free to reopen it if you insist, and I'll update the PR with your solution, no questions asked.

2024-05-13 13:51 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.module.scss
> +.container {
I agree with the sentiment.
After a quick search, it seems to me that many of those `.container` CSS definitions are for different types of containers, and often, it looks like they just add some additional styling to components that are styled elsewhere. It's probably similar for alerts.
I'm less concerned from the eng POV because I've found our CSS relatively easy to maintain, but we definitely want to provide a consistent UI.
We started a discussion with @rrhyne and the design team is mindful that we'll have to have a common Cody UI design system, but we don't seem to be ready to flesh out the specific components. We're not sure if those would live in Wildcard or in a new design system, and probably the Svelte change also complicates things.
All in all, I think this is on top of mind for many people now, and I'm happy that Rob has visibility into our design efforts in this project.

2024-05-13 14:01 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.module.scss
> +        // Blue checkmark SVG – TODO: The duplication is not nice. It's the same as the purple one except for the color.
I find it counterproductive to enforce such high standards in a single team and not do the same thing across the eng org.
Scroll through the [180 TODOs added in the past month in the monorepo](https://sourcegraph.com/search?q=context:global+repo:sourcegraph/sourcegraph+type:diff+TODO+since:2024-04-13+file:.tsx%3F&patternType=keyword&sm=0) to see many examples where we didn't do `TODO[sourcegraph#xxxx]` and didn't remove the TODO. _Possible_ that we planned to address all of those in the _next PR_, but I find it unlikely.

I'll remove this particular TODO because it's marginal, but I'd like to ask you to bring this up on `#team-engineering` if you think this is important enough (I don't, TBH), or let's leave it for later and keep our standards where they are.

2024-05-13 14:07 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    authenticatedUser: AuthenticatedUser | null
Thanks, added it!

2024-05-13 14:09 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    // const [teamDataError, setTeamDataError] = useState<null | Error>(null)
I agree with the sentiment but disagree in this case because I'm clearly addressing it as I'm actively working on https://github.com/sourcegraph/self-serve-cody/issues/725 and it's a requirement, but to simplify things, I've just removed the commented code.

2024-05-13 14:10 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +    const remainingInviteCount = useMemo(() => {
Not sure what you mean, but if you'd only use `useEffect` to do `setState` then definitely better idea to memoize the value with `useMemo`. You might also be interested in `useCallback` that memoizes functions in the same manner.

2024-05-13 14:12 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +                                    to="/cody/manage/subscription/new"
Yup, I wasn't sure where to link from "Add seats". Will address this when working on the follow-up of this PR. I've added an item "Make sure "Add seats" is wired up correctly" to https://github.com/sourcegraph/self-serve-cody/issues/725.

2024-05-13 14:16 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.tsx
> +                {subscriptionDataError || membersDataError || invitesDataError ? (
I'd rather keep it as-is while I'm actively debugging this, but added "Address Chris's [feedback](https://github.com/sourcegraph/sourcegraph/pull/62453#discussion_r1597220151) and deduplicate error message variables on the page." to https://github.com/sourcegraph/self-serve-cody/issues/725. For the generic page error, it's part of wildcard but we wanted this to look differently. First I wanted to add it to wildcard as a new type, but it didn't feel right so just created a custom one. I'll be the first to reconcile this as soon as we have a defined design language or at least some patterns emerging.

2024-05-13 14:31 UTC, vdavid commented on client/web/src/cody/team/InviteUsers.tsx
> +        const emailAddresses = emailAddressesString.split(',').map(email => email.trim())
Extracted the parsing logic in https://github.com/sourcegraph/sourcegraph/pull/62453/commits/1ed809118cc6ab675261240c9700d298e09b8c5b

2024-05-13 14:33 UTC, vdavid commented on client/web/src/cody/team/InviteUsers.tsx
> +            {!!remainingInviteCount && (
To me, that change would actually have a slight _negative_ effect on readability, so I'd rather keep it like this.

2024-05-13 14:36 UTC, vdavid commented on client/web/src/cody/team/InviteUsers.tsx
> +                                {remainingInviteCount === 1 ? '' : 's'}
Actually, we do have `pluralize()`—I just remembered I used it before. Thanks, addressed this in https://github.com/sourcegraph/sourcegraph/pull/62453/commits/68dba70f992256ac3bb4693ccb014fe2892b786d

2024-05-13 14:37 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +export interface TeamInvite {
👍  I suggest doing that in a follow-up PR to unblock the current one.

2024-05-13 14:40 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +            setActionResult(null)
Agreed this being an anti-pattern. Removed it in https://github.com/sourcegraph/sourcegraph/pull/62453/commits/c7d064e15b0cb8aa312f2717295b20320b9c1c87

2024-05-13 14:42 UTC, vdavid commented on client/web/src/routes.tsx
> +                    isSourcegraphDotCom && licenseFeatures.isCodyEnabled && useEmbeddedCodyProUi()
I've added the check: https://github.com/sourcegraph/sourcegraph/pull/62453/commits/c3e99c3f0e1d3e3011302129654b0eb1b08185c8

2024-05-13 14:45 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +                    setActionResultWithTimeout('Failed to revoke admin. Error code was: ' + response.status, true)
Will update it in a few moments.

2024-05-13 14:45 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +                    setActionResultWithTimeout('Admin revoked.', false)
Thanks, I forgot to update the success message.

2024-05-13 14:53 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +                    setActionResultWithTimeout('Failed to revoke admin. Error code was: ' + response.status, true)
Turns out none of our versions complied with our [styles and mechanics](https://handbook.sourcegraph.com/company-info-and-process/communication/content_guidelines/actionable_language/#error-messages). I've updated to a version that does, in https://github.com/sourcegraph/sourcegraph/pull/62453/commits/59df3c4cd16d7d96603df0b1ae5ab9ad11433861

2024-05-13 14:56 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +        async (accountId: string, newRole: 'member' | 'admin'): Promise<void> => {
It's because of the loading state. I don't want to let the role be set again if another change is being made. This is a safeguard to avoid success or error messages overwrite each other before the action finishes, that's all.
Added clarifying comments in https://github.com/sourcegraph/sourcegraph/pull/62453/commits/bb66b42c99baa66e74d31e54fa1b7ae51ce8ca2e

2024-05-13 14:57 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +                                            <em className="ml-4">Invite sent {invite.sentAt /* TODO format this */}</em>
I already have an issue to do this in https://github.com/sourcegraph/self-serve-cody/issues/725, won't be forgotten.

2024-05-13 15:00 UTC, vdavid commented on client/web/src/cody/team/TeamMembers.tsx
> +                                {isAdmin && (
That sounds like an anti-pattern in React 😕 This is pretty linear this way and that's the normal way to do it. Wouldn't be a huge thing to extract that for sure, but I think it'd decrease readability. If it was more complex, I'd extract the action buttons into a separate component, but it's not that complex in its current state, so of the solutions I've evaluated (incl. the one suggested above), I find this the best one.

2024-05-13 15:01 UTC, vdavid commented
> As far as a next step, let's try to see if we can find a time to review this PR in a VC meeting so we can discuss tradeoffs more quickly. (I can come in a couple hours earlier any day of the week, just let me know with some notice.)

The earliest we can do that is tomorrow (Tuesday). Let's do that tomorrow, then. Could you schedule something within my work hours that fits your schedule?

However, as I've addressed each piece of feedback, I suggest you re-review this PR to unblock, and we can address the rest in follow-ups.

2024-05-13 16:23 UTC, chrsmith commented on client/web/src/cody/team/CodyManageTeamPage.module.scss
> +        // Blue checkmark SVG – TODO: The duplication is not nice. It's the same as the purple one except for the color.
Apologies for not being super-clear in what I was trying to communicate. I assume we are probably are on the same page, but perhaps I didn't do a good job explaining what I'd like you to do in this comment.

> There are 180+ TODO comments added in _the past month_, without an assigned ticket number.

I don't want to come across as saying this is inherently a bad thing. (Read: symptom but not cause.)

Ultimately, IMHO, the real concern here is whether or not the code is "correct". Does the code actually do what we need it to do?

If there are bugs or critical aspects are missing, then we definitely should call those out! And, depending on the timeline for when we will address those things, file an actual ticket to ensure that we do that extra work.

I suspect this isn't a controversial opinion. (That if the code is "missing something important", we need to call it out.)

> Where unticketed TODOs do cause a problem...

So I won't give you grief for TODOs added into the codebase in the past month. My concern is for TODOs that _remain_ in the codebase, 3-6 months or even _years_ later.

If the underlying issue actually wasn't important enough to fix, or the missing functionality not really necessary, then in hind sight the code probably was "correct" and "complete" as-is. When it was first checked in.

However, because of various TODO comments, the person reading the code has no idea if that is the case or not. (e.g. "I'm looking in this part of the code, and from the comments, it sounds like it was only half-done! Or is missing all sorts of things! It has all of these bugs!)

... so the thing I would highlight in my earlier comment is "then let's just be honest with ourselves and delete the TODO comment entirely". That is, rather than lying to ourselves and saying we _will_ address that thing... let's just not call that out. (And not feel bad for leaving the code as-is.)

e.g. imagine you are coming across some code you are unfamiliar with, and see these comments.

```
// TODO: This requires N-different database queries and will be slow. We need to
// rewrite this to fetch the data in-bulk.

vs.

// This requires N-different queries. If this becomes a bottleneck, a good fix
// would be to rewrite the `TeamStore` layer to fetch the data for multiple teams
// in one query.
```

While they are both essentially communicating the same thing, (I'd argue) that the second comment makes it clear that the code isn't inherently wrong. But does call out that it could potentially break down in some way down the road. (And providing a suggestion for what that could be.)

So back to this particular instance, all I'm (gently) suggesting here is that rather than using "TODO" and communicating that this code isn't correct/complete, that this is instead a suggestion for later improvement should the need arise.

```diff
- // Blue checkmark SVG – TODO: The duplication is not nice.
+ // Blue checkmark SVG. This is duplicated with the other SVGs in this file, so
+ // so consider generalizing if we find ourselves editing this often.
```

2024-05-14 08:39 UTC, vdavid commented on client/web/src/cody/team/CodyManageTeamPage.module.scss
> +        // Blue checkmark SVG – TODO: The duplication is not nice. It's the same as the purple one except for the color.
I think it's a difference in definitions. To me, seeing the word "TODO" in code comments doesn't convey the meaning "this code is wrong". To me, these read pretty much the same:
```
// Blue checkmark SVG. This is duplicated with the other SVGs in this file,
// so consider generalizing if we find ourselves editing this often.
```

```
// Blue checkmark SVG. TODO: This is duplicated with the other SVGs in this file,
// so consider generalizing if we find ourselves editing this often.
```

We can give "TODO" a higher significance and a better-defined meaning, but I think we should do that org-wide and put it in the handbook and into the awareness of our engineers. Currently, we don't have that.
My two cents is that this isn't worth the effort, though.

2024-05-14 15:32 UTC, chrsmith approved these changes
Approving to not hold up the Teams and Invites stuff any more. 

Though as we continue to flesh out this part of the codebase, let's try to pin down the specific patterns we do and do not want to follow in order to keep things simple and maintainable. (e.g. using the `withAuthenticatedUser()` wrapper, and similar things.)

2024-05-15 08:01 UTC, merged