Add Syntax Highlighting for Hack Language
sourcegraph/sourcegraph pull request #62770
Opened 2024-05-17 16:20 UTC by mmanela

As part of GRAPH-205 for support Hack language, this PR adds Syntax highlighting.  

Key notes
1. Added a reference to the Hack tree-sitter package
2. Add a highlights query for identifying the items to highlight (Note: I built our version off of the solid foundation found in the [Neovim](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/hack/highlights.scm)  tree sitter repo. But iterated a decent amount for how we would like it highlighted. 
3. Added updated test cases trying to cover many interesting languages features. Hack is a large language and  I am not covering everything possible but many key features.
4. It seems there are some gaps in the upstream tree-sitter grammar such as doesn't support `module` statement and doesn't support string interpolation (parses just as string) 
 
# Screenshots
 
![image](https://github.com/sourcegraph/sourcegraph/assets/304410/5875968d-b47e-41db-91c4-8041f1543430)
![image](https://github.com/sourcegraph/sourcegraph/assets/304410/5e5488bd-7d5b-4226-b3f7-313bf567d3cf)

## Test plan
 - Unit tests
 - Validate UI and ensure it looks appropriate

2024-05-22 02:01 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//                             ^ PunctuationDelimiter
Marking `C` and `Vec` as `IdentifierNamespace` is not correct.

https://docs.hhvm.com/hack/source-code-fundamentals/namespaces

>  ```
>  use namespace NS1\{C, I, T}; // instead of `NS1\C, NS1\I, NS1\T`
>  ```
>
>  Imported names can designate a namespace, a sub-namespace, a class or interface or trait, a function, or any built-in type.

2024-05-22 02:04 UTC, varungandhi-src commented
> It [seems](https://github.com/slackhq/tree-sitter-hack/blob/main/grammar.js) there are some gaps in the upstream tree-sitter grammar such as doesn't support module statement and doesn't support string interpolation (parses just as string)

Please file 1-2 issues upstream so that we can link them here.

2024-05-22 02:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//                             ^ PunctuationDelimiter
Hmm, these docs indicate that it can only be namespaces?

https://docs.hhvm.com/hack/statements/use

🤔

2024-05-22 02:26 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +use type Space\Type\T;
Please add test cases for `use`:
- without `namespace`/`const`/`type`.
- with `function`

2024-05-22 02:26 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +  function foo(int $arg): shape(...){
Is highlighting deliberately missing for `...` ?

2024-05-22 15:43 UTC, muglug commented
Thanks for doing this!

I know you have the tree-sitter grammar already, but we also have a slightly-more-up-to-date TextMate grammar here that supports `module` and more: https://github.com/slackhq/vscode-hack/blob/master/syntaxes/hack.json

2024-05-22 15:45 UTC, mmanela commented
@muglug  Thanks. Our highlighting is based on tree-sitter, so would be great to get the missing parts added to the hack tree-sitter lib. I plan to file issues there on what I found

2024-05-22 16:02 UTC, muglug commented
Sounds good — at Slack we’re not yet using modules, so that’s no sort of blocker. Once we start considering that we’ll push necessary changes to the tree-sitter grammar.

2024-05-22 16:10 UTC, mmanela commented
Yea I think the bigger annoyance will be the lack of string interpolation support

2024-05-22 20:29 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +  function foo(int $arg): shape(...){
Good catch

2024-05-22 20:29 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//                             ^ PunctuationDelimiter
From what I read seems like namespace in this case, so I plan to leave as that

2024-05-24 01:49 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +    return shape();
It would be good to have test cases for more complex shape types.

2024-05-24 01:49 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +</tt>;
There is a `->:` operator marked as [Access XHP Attributes](https://docs.hhvm.com/hack/expressions-and-operators/XHP-attribute-selection) here, let's add a test for that.

More generally, it would be useful to go through the various operators on that page and make sure each "group" at least has one test case (e.g. you don't need to test each bitwise operator)

2024-05-24 01:49 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +// imports
Q: Did you find any online compiler/playground where this code can be pasted and checked if it parses properly?

2024-05-24 01:49 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +// NOTE: Tree-sitter grammar seems to not support module
Please link the bug reports here and below as well.

2024-05-24 01:49 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +EOT;
There are 4 types of string literals, looks like we're missing coverage for the nowdoc style of literals. https://docs.hhvm.com/hack/source-code-fundamentals/literals#string-literals

2024-05-24 04:20 UTC, varungandhi-src requested changes
Please go through https://docs.hhvm.com and identify the different syntax forms which aren't being tested and add tests for those. I've identified some which are missing, I haven't tried to be exhaustive.

2024-05-24 04:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +  echo "\$v1 = ".$v1.", \$v2 = ".$v2."\n";
`echo` is one built-in function. Please add tests for various built-in functions such as:
- exit: https://docs.hhvm.com/hack/expressions-and-operators/exit
- invariant: https://docs.hhvm.com/hack/expressions-and-operators/invariant
- `idx()`: https://docs.hhvm.com/hack/expressions-and-operators/coalesce#-and-idx

2024-05-24 04:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +  // Expressions
Please add tests for:
1. Tuple unpacking using `list(...)`. https://docs.hhvm.com/hack/expressions-and-operators/list, including with nesting
2. `@` operator: https://docs.hhvm.com/hack/expressions-and-operators/error-control
3. type assertions using `is`, `as` and `?as`, as well as the legacy type predicate functions (these could be marked as built-in functions): https://docs.hhvm.com/hack/expressions-and-operators/type-assertions
4. Ternary operator `? :` https://docs.hhvm.com/hack/expressions-and-operators/ternary
5. Coalescing using `??` and `??=`: https://docs.hhvm.com/hack/expressions-and-operators/coalesce

2024-05-24 04:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +  using ($new = new Object(), $file = new File('using', '+using')) {}
Please add tests for different kinds of `new` calls: (https://docs.hhvm.com/hack/expressions-and-operators/new)
- `new $clsname()`
- Different keywords between `new` and the constructor call

2024-05-24 04:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +  foreach (($array as vec[]) as $item) {}
Please add tests for `continue`, `try`, `catch`, `finally`. https://docs.hhvm.com/hack/statements/introduction

2024-05-24 04:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +// Types
Please add tests for:
- `noreturn`: https://docs.hhvm.com/hack/built-in-types/noreturn

2024-05-24 04:20 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/tree-sitter-all-languages/Cargo.toml
> +tree-sitter-hack = { git = "https://github.com/slackhq/tree-sitter-hack", rev = "fca1e294f6dce8ec5659233a6a21f5bd0ed5b4f2", version = "0.0.4" }
```suggestion
tree-sitter-hack = { git = "https://github.com/slackhq/tree-sitter-hack", rev = "fca1e294f6dce8ec5659233a6a21f5bd0ed5b4f2" }
```

For `git` dependencies, specifying the `rev` is enough, it's unclear why `version` is being specified here.

2024-05-31 20:33 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +// imports
Yes we can run it via docker. This file does not parse properly, will take some work to change it to that. I can work on that next.

2024-05-31 20:36 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +// imports
This is the simplest way to run the compiler. 
```
docker pull hhvm/hhvm 
docker run  --tty --interactive hhvm/hhvm:latest /bin/bash -l 
hhvm --version
```

2024-06-01 03:40 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +// imports
Ok did a pass and its much closer to compiling but some of the features together (especially modules) make it hard to compile. But was able to validate most of the code.

2024-06-02 12:38 UTC, varungandhi-src requested changes
I've gone through about 700/1650 lines in the snapshot output and 325/450 lines in the queries. Please go through the feedback and re-request review after addressing existing comments.

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +  (#match? @comment.documentation "^[*][*][^*].*[*]$"))
We do not have anything such as `@comment.documentation` in `MATCHES_TO_SYNTAX_KINDS`, please remove this.

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +"function" @keyword.function
Please merge this with the other keywords; see my comment below for the various `@keyword` suffixes.

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +    list($one, $two, $three) = $tuple;
Please add a test for function pointer syntax `f<>`. https://docs.hhvm.com/hack/modules/closures-and-function-pointers

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +
```suggestion
```

Stray whitespace

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    (identifier) @type))
This seems unjustified. Looking at https://github.com/slackhq/tree-sitter-hack/blob/main/grammar.js#L81-L94, it seems plausible that this might refer to a [static method](https://docs.hhvm.com/hack/classes/methods).

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +
```suggestion
```

nit: Stray whitespace

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +(null) @constant.builtin
```suggestion
(null) @constant.null
```

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +  (_) @type)
I think you might be able to combine these with `["newtype" "type"]` perhaps? Seems a bit redundant otherwise.

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +(float) @number.float
We don't have `number.float` in `MATCHES_TO_SYNTAX_KINDS`, this can simply be `@number`.

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +  (#eq? @variable.builtin "INF"))
These should be `@constant.builtin`, not `@variable.builtin`

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    (xhp_class_identifier) @variable)
Why are we specifically checking for `xhp_class_identifier` in this sub-tree? Should we instead mark `xhp_class_identifier` as `@identifier` everywhere?

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    name:  (qualified_identifier (identifier) @variable.module))
Would prefer `@identifier.module` to be used here (we should probably rename that wholesale to `identifier.namespace` everywhere since we're using `IdentifierNamespace` in SCIP). Using `variable` in the name conveys some kind of local bindings, but very few languages like OCaml support first-class modules.

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +  (qualified_identifier
```suggestion

(qualified_identifier
```

Please use consistent formatting and spacing.

2024-06-02 12:38 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +  alias: (identifier)? @variable.module)
1. When will this be triggered instead of the similar `use_statement` query earlier?
2. Why does this use `(_) @variable.module .` whereas the sub-fragment of the `use_statement` query is `(identifier) @variable.module .`?

2024-06-03 18:47 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +"return" @keyword.return
I will update for Hack and we can discuss the broader change after. But curious on if it would it be useful to keep these though, since having the distinction in the highlights can help us in the future if we want to decide to identifier these separately later? But I guess since we don't test them today we don't trust it anyway. So for now I do agree.

2024-06-03 18:58 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//         ^^^ IdentifierFunction
They call it built-in in their docs so I will go with that.

2024-06-03 20:17 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    (identifier) @type))
This matches the left hand side of the scoped identifier.  So for `Person::typicalGreeting()` it would match `Person` as a type. Is that not right and its assuming too much

2024-06-04 01:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +"return" @keyword.return
> since having the distinction in the highlights can help us in the future if we want to decide to identifier these separately later

In practice, no mainstream IDEs today distinguish between various kinds of keywords via highlighting.

> But I guess since we don't test them today we don't trust it anyway

Yes, exactly. When we want to use one of these, we want to try to be consistent across languages.

2024-06-04 10:32 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    (identifier) @type))
You're right, I misread the query.

2024-06-04 10:34 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//                   ^^^ IdentifierType
Can we avoid marking the last one as `IdentifierType` and just fall back to `Identifier`?

2024-06-04 11:12 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//                   ^^^ IdentifierType
I believe it's this query 

```
(collection
  (qualified_identifier
    (identifier) @type .)) 
```

Since it sees the last segment as collection definition since it ends with the {}. I will see if I can condition this more

2024-06-04 11:43 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//                   ^^^ IdentifierType
Ah. I suppose that's OK, that doesn't seem easily fixable. 😐

2024-06-04 17:57 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +  alias: (identifier)? @variable.module)
1. `use_statement` is used when you have selecting specific sub-items  like `use namespace HH\Lib\{C, Vec}` and `use_clause` is used when you don't `use namespace HH\Lib`.
2. Ah, I used the `(_)` before you had the suggestion to add a identifier node into the hack grammar

2024-06-04 18:13 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/files/hack.hack
> +// imports
Done

2024-06-04 18:17 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__hack.hack.snap
> +//      ^ IdentifierOperator
Done with one annoying caveat. In the Jsx grammar it wouldnt let me match in `"</"` and I had to match on the characters individually. I am not sure why, that is why for the jsx snap it shows up like this.

![image](https://github.com/sourcegraph/sourcegraph/assets/304410/1e1b3b4c-5965-4664-88a9-18b96d470217)

2024-06-04 18:29 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
> +  ["<" "/"] @tag.delimiter
I want to do `"</" @tag.delimiter` but this errors and not sure why.

2024-06-06 04:15 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
> +  ["<" "/"] @tag.delimiter
Please split out the JSX change into a separate PR. This PR is already quite big.

2024-06-06 04:17 UTC, varungandhi-src commented on internal/highlight/language_test.go
> +		{
Please avoid adding unrelated changes in the same PR. This change is related to a different issue.

2024-06-06 04:22 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
> +  ["<" "/"] @tag.delimiter
Couple of minor points:

> I want to do ...

If something is sub-optimal in the code, then prefer adding a code comment first and then flagging it in review, instead of just having a PR review comment. That way someone who reads the code next has the context available; coming to this PR and going through the comments is much more time-consuming (and ergo, less likely).

> but this errors and not sure why.

It would be helpful to state what error you got, what steps you took to investigate it, etc.

2024-06-06 06:26 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    (#eq? @function.builtin "is_string"))
It seems like `#any-of?` is broken, I changed this to use `#match?` instead.

2024-06-06 06:26 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +(braced_expression) @none
There is no `none` in `MATCHES_TO_SYNTAX_KINDS`. Also, applying any kind of highlighting information to braced expressions as a whole doesn't make much sense -- the punctuation is handled separately, and the sub-expression inside will be handled separately.

2024-06-06 06:35 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
> +  ["<" "/"] @tag.delimiter
We're using v0.20.0 of the tree-sitter-javascript grammar, and that has this definition:

```
    jsx_closing_element: $ => seq(
      '<',
      '/',
      field('name', $._jsx_element_name),
      '>'
    ),
```

https://github.com/tree-sitter/tree-sitter-javascript/blob/rust-0.20.0/grammar.js

2024-06-06 10:58 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    (#eq? @function.builtin "is_string"))
Yea I tried any-of multiple times to condense this and it didn't work. I think any-of matches multiple captures

2024-06-06 11:02 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
> +  ["<" "/"] @tag.delimiter
Ah! I didn't even think that the grammar I was looking at was newer than the one we were using. Thanks for seeing that

2024-06-06 11:04 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/javascript/highlights-jsx.scm
> +  ["<" "/"] @tag.delimiter
For mainstream grammars, you can use the playground to check a query against the latest version. https://tree-sitter.github.io/tree-sitter/playground

2024-06-06 11:08 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/hack/highlights.scm
> +    (#eq? @function.builtin "is_string"))
Good to see that `match` works for it. Thanks

2024-06-06 11:10 UTC, varungandhi-src approved these changes
LGTM except for the outstanding comments on splitting JSX and language detection changes into different PRs.

2024-06-06 20:16 UTC, merged