Initial set of changes to support highlighting Magik
sourcegraph/sourcegraph pull request #62919
Opened 2024-05-24 21:14 UTC by mmanela

Fixes GRAPH-621

Key notes
1. Added a reference to a fork of the Magik tree-sitter package since the upstream didn't support rust and was using a newer version of tree-sitter which we are not yet supporting.
2. Add a highlights query for identifying the items to highlight  
3. Added test cases based on language description on wikipedia, example in tree sitter package and other examples online. 
4. I do not have a way to run Magik programming and I could not find a full language specification, so I am not confident this covers everything.
5. The tree-sitter grammar is missing support for a couple things in their own examples. I will follow and link to issues soon 

# Screenshots
 
 
<img width="463" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/304410/2e61ea34-a236-4093-b576-d59a767fccd9">
<img width="365" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/304410/d49f5087-6ec5-41a1-9372-96f9656a08ec">

## Test plan
 - Unit tests
 - Validate UI and ensure it looks appropriate

2024-06-05 18:07 UTC, mmanela commented
@sebastiaanspeck Thanks for the quick work there. I pulled the changes in and they work great!

2024-06-06 13:16 UTC, kritzcreek requested changes
We're currently depending on a `rust-bindings` branch for our fork of the upstream grammar, could we instead have our `main` be ahead of the upstream so it's easier to see at a glance how they compare when browsing via GH?

2024-06-06 13:16 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +(class _ @keyword) @type
IIUC this is trying to target `_class` as keyword here. It would be less brittle to just add `"_class"` to the list of keywords. I don't know if you want to highlight the entire class definition as `@type` because it also targets the surrounding pipe symbols.

I have no clue why I can't target the `java_classname` field though, seems like a weird tree-sitter bug.

2024-06-06 13:16 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__magik.magik.snap
> +  _private _method person.init(name, age)
Why aren't we marking the dot in here as `IdentifierOperator`? We seem to do so in other places

Do we need to add a `(method "." @operator)` query?

2024-06-06 13:16 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +  receiver: (variable) @variable )
```suggestion
```
`variable`'s already get marked as `@variable` universally.

2024-06-06 13:16 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +  message: (identifier) @variable)
```suggestion
```

same as above

2024-06-06 13:16 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +] @number
```suggestion
(number) @number
```

2024-06-06 13:16 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +] @string
```suggestion
(string_literal) @string
```

2024-06-06 13:16 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +] @include
```suggestion
"_package" @include
```

2024-06-06 13:20 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +(class _ @keyword) @type
Yea I did this just to make that whole part as @type just because I couldnt target it any other way. But open to just leave as not-highlighted

2024-06-06 15:07 UTC, kritzcreek commented
Codel looks good from my side WDYT about the branch management?

> We're currently depending on a rust-bindings branch for our fork of the upstream grammar, could we instead have our main be ahead of the upstream so it's easier to see at a glance how they compare when browsing via GH?

Does this change need an entry in the changelog as well?

2024-06-06 16:26 UTC, mmanela commented
@kritzcreek  Thanks for the feedback. I updated change log and our forked repo as you suggested

2024-06-06 16:28 UTC, kritzcreek approved these changes

2024-06-06 20:49 UTC, merged

2024-06-07 02:33 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> + (label)
This one is interesting. Labels are not really variables. However, we don't really have a SyntaxKind in SCIP to mark labels. GoLand does highlight labels differently, using bold in the theme that I have.

![](https://github.com/sourcegraph/sourcegraph/assets/93103176/e696651a-105c-4e84-80a7-bff22c1b87f1)

We should probably add a `ControlFlowLabel` syntax kind to SCIP and use that here. I've filed a follow-up issue: https://linear.app/sourcegraph/issue/GRAPH-661/add-syntaxkindcontrolflowlabel-to-scip

2024-06-07 02:33 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__magik.magik.snap
> +//        ^^^^^^^^^^^^^^ Identifier
The current view must be quite amazing to have two exclamation marks `!current_view!` 😆

2024-06-07 02:33 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__magik.magik.snap
> +//       ^^^^^^^^^ Identifier
You'll notice that the space between `@` and `l` is being marked as an identifier too. It seems like the more idiomatic syntax is to not have a space there. See the code example below which shows other places where `@label` can be used, that would be useful to add a test case for to make sure the loop label is being picked up correctly in other places.

https://sourcegraph.com/github.com/krn-robin/tree-sitter-magik@main/-/blob/test/corpus/loop.txt?L85-94

2024-06-07 02:33 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +; NOTE(issues: https://github.com/krn-robin/tree-sitter-magik/issues/49): Grammar does not support traversing to the children in the pragma
I see there is an open PR here: https://github.com/krn-robin/tree-sitter-magik/pull/50

Should we file a follow-up issue on our side to update the queries once that PR is merged/how would you like to handle this?

2024-06-07 02:36 UTC, varungandhi-src commented
@sebastiaanspeck does Magik have a standard nil/null value? I don't see it in the grammar, but I think other Smalltalk languages typically have `nil` (Smalltalk-80, Squeak, Pharo).

2024-06-07 03:03 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +] @constant
Then is `@identifier` the best best for `(symbol)`?

2024-06-07 05:05 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +] @constant
Sorry I should've mentioned that. We should mark them as `@string`, since in most languages, symbols are simply interned strings. Other editors do the same. For example: https://github.com/github-linguist/linguist/blob/master/script/fast-submodule-update#L19-L28

2024-06-07 06:50 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +  (unset)
Let's mark `unset` as `@constant.null` based on: https://github.com/sourcegraph/sourcegraph/pull/62919#issuecomment-2154183110

2024-06-07 06:52 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/highlighting/snapshots/syntax_analysis__highlighting__tree_sitter__test__magik.magik.snap
> +//       ^^^^^^^^^ Identifier
I meant this as feedback for @mmanela to add more tests to make sure the highlighting is working properly in cases such as `_continue@outer_loop`.

2024-06-07 12:55 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +; NOTE(issues: https://github.com/krn-robin/tree-sitter-magik/issues/49): Grammar does not support traversing to the children in the pragma
https://linear.app/sourcegraph/issue/GRAPH-662/handle-pragma-for-magik-language-when-grammar-is-updated

2024-06-07 12:59 UTC, mmanela commented on docker-images/syntax-highlighter/crates/syntax-analysis/queries/magik/highlights.scm
> +(documentation) @comment
This doesn't seem right to me @sebastiaanspeck . Why would this be an attribute?

2024-06-07 13:20 UTC, mmanela commented
Addressed new comments in this [PR](https://github.com/sourcegraph/sourcegraph/pull/63155)