feat(code insights): language stats speed improvements by using archive loading
sourcegraph/sourcegraph pull request #62946
Opened 2024-05-28 14:23 UTC by bahrmichael

We previously improved the performance of Language Stats Insights by introducing parallel requests to gitserver: https://github.com/sourcegraph/sourcegraph/pull/62011

This PR replaces the previous approach where we would iterate through and request each file from gitserver with an approach where we request just one archive. This eliminates a lot of network traffic, and gives us an additional(!) performance improvement of 70-90%.

Even repositories like chromium (42GB) can now be processed (on my machine in just one minute).

---

Caching: We dropped most of the caching, and kept only the top-level caching (repo@commit). This means that we only need to compute the language stats once per commit, and subsequent users/requests can see the cached data. We dropped the file/directory level caching, because (1) the code to do that got very complex and (2) we can assume that most repositories are able to compute within the 5 minutes timeout (which can be increase via the environment variable `GET_INVENTORY_TIMEOUT`). The timeout is not bound to the user's request anymore. Before, the frontend would request the stats up to three times to let the computation move forward and pick up where the last request aborted. While we still have this frontend retry mechanism, we don't have to worry about an abort-and-continue mechanism in the backend.

---

Credits for the code to @eseliger: https://github.com/sourcegraph/sourcegraph/issues/62019#issuecomment-2119278481

I've taken the diff, and updated the caching methods to allow for more advanced use cases should we decide to introduce more caching. We can take that out again if the current caching is sufficient.

Todos:

- [x] Check if CI passes, manual testing seems to be fine
- [x] Verify that insights are cached at the top level

---

Test data:

- sourcegraph/sourcegraph: 9.07s (main) -> 1.44s (current): 74% better
- facebook/react: 17.52s (main) -> 0.87s (current): 95% better
- godotengine/godot: 28.92s (main) -> 1.98s (current): 93% better
- chromium/chromium: ~1 minute: 100% better, because it didn't compute before

## Changelog

- Language stats queries now request one archive from gitserver instead of individual file requests. This leads to a huge performance improvement. Even extra large repositories like chromium are now able to compute within one minute. Previously they timed out.

## Test plan

- New unit tests
- Plenty of manual testing

2024-05-29 14:31 UTC, bahrmichael commented
Currently two problems, the `pax_global_header` is probably from my changes in https://github.com/sourcegraph/sourcegraph/pull/62946/commits/ec96924a738785a1316e83d27bac8d64797f9f08.
<img width="759" alt="Screenshot 2024-05-29 at 16 30 00" src="https://github.com/sourcegraph/sourcegraph/assets/1830132/cacd1e0c-9f50-4b01-98db-ea04f5167efd">
<img width="574" alt="Screenshot 2024-05-29 at 16 29 49" src="https://github.com/sourcegraph/sourcegraph/assets/1830132/aef6d90c-d565-4b49-9092-54f4db067c93">

2024-05-30 14:05 UTC, eseliger commented
for the pax_global_header you _might_ be able to get around that issue by adding a `fd.IsRegular()` check. It's a magical file that is unfortunately added to tar archives :|

2024-05-30 14:10 UTC, bahrmichael commented
> for the pax_global_header you _might_ be able to get around that issue by adding a `fd.IsRegular()` check. It's a magical file that is unfortunately added to tar archives :|

Thank you for the idea! I found that my changes to the reader have seemed to cause this, which I reverted in https://github.com/sourcegraph/sourcegraph/pull/62946/commits/fb2536ec3cb74a5c4ab6be7e55c08a0c18bf1066.

I'll double check the impact of pax_global_header so we don't report false numbers.

2024-05-30 14:23 UTC, bahrmichael commented
The pax_global_header is not counting towards the language stats, because it's skipped at https://github.com/sourcegraph/sourcegraph/blob/0e2a668954f2f8169da51224902865686fa8e472/cmd/frontend/internal/inventory/inventory.go#L89.

2024-05-30 14:25 UTC, eseliger commented
great!

2024-05-31 18:19 UTC, eseliger approved these changes

2024-05-31 18:19 UTC, eseliger commented on cmd/frontend/internal/inventory/inventory.go
>  		return lang, nil
could we save the call to getFileReader here at all, if `skipEnhancedLanguageDetection`?

2024-05-31 18:19 UTC, eseliger commented on cmd/frontend/internal/inventory/entries.go
> +		if inv, ok := c.CacheGet(ctx, string(c.Repo)); ok {
does the cache key need to account for what HEAD resolves to as well, or is that intentional to invalidate the cache less frequently?

2024-05-31 18:19 UTC, eseliger commented on cmd/frontend/internal/inventory/entries.go
> +		return Inventory{}, err
I wonder if a RevisionNotFoundError here should mean empty inventory but no error? 

Use-case: An empty repo should IIRC throw this error, but that feels expected.

2024-05-31 18:19 UTC, eseliger commented on cmd/frontend/internal/inventory/entries.go
> +				return Sum(invs), nil
not sure how expensive that is but to save on memory here, we could build the sum for every or every N `th` we visit, not just keep 600k inventories in memory

2024-05-31 18:19 UTC, eseliger commented on cmd/frontend/internal/inventory/entries.go
> +			continue
I'm not sure if we had that before, but this is the code path that would allow for incremental indexing. We can leave that out for now, but should monitor the latency and load this causes for large repos (i.e., let's check on large cloud customers after the release).

2024-06-01 08:53 UTC, eseliger commented on cmd/frontend/internal/inventory/entries.go
> +		if inv, ok := c.CacheGet(ctx, string(c.Repo)); ok {
in that case, we should probably reimplement the caching at the dir level first

2024-06-18 19:46 UTC, camdencheek commented on cmd/frontend/internal/inventory/entries.go
> +		if inv, ok := c.CacheGet(ctx, string(c.Repo)); ok {
Okay, finally got the chance to take another look at this, and I think we should go ahead and move forward with this close to as-is, but using the commit hash as part of the cache key. We do some theoretical extra work by not caching at the tree level, but this also drastically reduces the load on the cache and massively improves the "cold start" time. Since very large repos previously would fail to index at all, this is a big improvement there, and 1.4s for sourcegraph/sourcegraph (a medium-sized repo) on a cache miss is acceptable IMO.

That said, I think we should follow this up by moving the language stats insight from an on-demand thing to a pre-computed thing, slotting it into the existing framework for computing updated values for code insights. That way, no user should see a cold start, and we will also have historical data for this so we could show language stats over time.

2024-06-18 19:47 UTC, eseliger commented on cmd/frontend/internal/inventory/entries.go
> +		if inv, ok := c.CacheGet(ctx, string(c.Repo)); ok {
that sounds great!

2024-06-25 11:10 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +			continue
At the end of May I gave it a try to cache based on the directory, and found that it's a bit harder than before. This is mainly because now we get a flat list of records, files and directories in them. 

I don't recall exactly if the directory came before the files or after, and am not sure if the order of files and directories is guaranteed. Can you confirm that @eseliger? 

I had two ideas: (1) Remember the directory, process files, and when a new directory appears, cache the above. Discarded that again because it felt too hacky. (2) Load everything into a tree structure and process like before, but then we'll need to load everything and actually lose the benefit directory level caching would bring us.

2024-06-25 12:46 UTC, bahrmichael commented on cmd/frontend/internal/inventory/inventory.go
>  		return lang, nil
I think we can drop the nil check and move the getFileReader call downwards. Previously nil indicated that the language check should be skipped, but we now have that as a bool.

Previous nil init (see deleted code in this PR):
```
	if !useEnhancedLanguageDetection && !forceEnhancedLanguageDetection {
		// If USE_ENHANCED_LANGUAGE_DETECTION is disabled, do not read file contents to determine
		// the language. This means we won't calculate the number of lines per language.
		invCtx.NewFileReader = func(ctx context.Context, path string) (io.ReadCloser, error) {
			return nil, nil
		}
	}
```

New init of according bool:
```
ShouldSkipEnhancedLanguageDetection: !useEnhancedLanguageDetection && !forceEnhancedLanguageDetection,
```

2024-06-25 14:05 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +				return Sum(invs), nil
I've pushed an update in https://github.com/sourcegraph/sourcegraph/pull/62946/commits/7e0aeb3a542bf8e81adfa3c762b7e71d5c35c873 where I just took 1000, let me know if you think that a different value is better.

2024-06-25 14:23 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +		if inv, ok := c.CacheGet(ctx, string(c.Repo)); ok {
I pushed a change that includes the commitID, and will spin up a ticket for moving this to a pre-computed style.

2024-06-26 05:06 UTC, eseliger commented on cmd/frontend/internal/inventory/entries.go
> +			continue
> I don't recall exactly if the directory came before the files or after, and am not sure if the order of files and directories is guaranteed. Can you confirm that @eseliger?

I think the order should be guaranteed _within one commit_, but might differ between commits. No 100% guarantee - I'd need to check in the git code to be sure. How important is that? I don't think that's documented behavior of the API today, so would be something implicit we rely on.

2024-06-26 10:02 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +			continue
Within one commit is fine. I tried to use the folder as an open or close marker to its files. To determine when all files in a folder have been read and caching that before the whole process completes, the guaranteed order is essential.

Here's what I recall seeing:

```
...
folder1
folder1/a
folder2/a
folder2/b
folder2/c
folder2
folder3/a
...
```

If the enclosing folder always comes before or after the files, we can use the leading or trailing folder to determine when all files have been read. That's all the guarantees I'm looking for here. Either before or after, but always right before or right after all of its files.

2024-06-26 10:13 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +		return Inventory{}, err
Tested it, and this is the error we get on a fresh repo without any commits:

<img width="1159" alt="Screenshot 2024-06-26 at 12 06 24" src="https://github.com/sourcegraph/sourcegraph/assets/1830132/2016f642-a727-4ce5-ace6-420152248401">

Once there's a commit, we can see this behavior (introduced originally by https://github.com/sourcegraph/sourcegraph/pull/20856).

<img width="1173" alt="Screenshot 2024-06-26 at 12 07 46" src="https://github.com/sourcegraph/sourcegraph/assets/1830132/b195b9c8-cf7d-452c-9614-6993652e6270">

I agree that showing a styled error message is much more helpful than the error message we currently show.

2024-06-26 10:47 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +		return Inventory{}, err
I found https://github.com/sourcegraph/sourcegraph/pull/61938 which handles the RevisionNotFoundError and turns it into a "" commit, which then is turned in the error message we see above here:

https://github.com/sourcegraph/sourcegraph/blob/bc49218e6ca9a5d9ab867b9a688a06a2c14ff699/cmd/frontend/backend/inventory.go#L51-L53

If there is no revision, the code execution doesn't get to the point where you recommended handling the error.

Changing the error message will still be helpful.

2024-06-26 12:47 UTC, bahrmichael commented
@camdencheek @eseliger I went through your comments on the code, and think this is ready for another review :) Let me know what you think!

2024-06-27 16:08 UTC, camdencheek requested changes

2024-06-27 16:08 UTC, camdencheek commented on cmd/frontend/internal/inventory/inventory.go
>  		lang.TotalBytes = uint64(file.Size())
This seems to be missing `lang.TotalLines` when enhanced language detection is disabled. Is that right?

2024-06-27 16:08 UTC, camdencheek commented on cmd/frontend/internal/inventory/entries.go
> +	}
Could you create a followup Linear issue for dealing with "unknown" or "ambiguous" results? Out of scope for this PR, but we should probably improve our handling there.

2024-06-27 16:08 UTC, camdencheek commented on cmd/frontend/internal/inventory/entries.go
> +				return Sum(invs), nil
1000 seems fine to me 🙂

2024-06-27 16:08 UTC, camdencheek commented on cmd/frontend/internal/inventory/entries.go
> +			continue
This is starting to sound like a leetcode problem 🙂

2024-06-28 07:37 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +var maxInvsLength, _ = strconv.Atoi(env.Get("GET_INVENTORY_MAX_INV_IN_MEMORY", "1000", "When computing the language stats, every nth iteration all loaded files are aggregated into the inventory to re
Will do, thank you!

2024-06-28 08:22 UTC, bahrmichael commented on cmd/frontend/backend/repos.go
> +	inv, err := invCtx.All(ctx, s.gitserverClient, commitID)
Yeah, the current approach looks not well rounded. I'm inclined towards Option 1.

2024-07-01 21:43 UTC, eseliger approved these changes
A few last comments and Camden should also review, but from a Source perspective, this seems fine

2024-07-01 21:43 UTC, eseliger commented on cmd/frontend/backend/inventory.go
> +			}
Yea I'm not sure the tar entries would satisfy this check

2024-07-09 08:26 UTC, bahrmichael commented
FYI: I'm currently focussing on the batch changes work with Bolaji, and will continue to work on this afterwards. Probably by the end of the week.

2024-07-15 11:17 UTC, bahrmichael commented on cmd/frontend/backend/inventory.go
> +			}
👍 I stopped using this for the new approach.

2024-07-15 11:21 UTC, bahrmichael commented on cmd/frontend/internal/inventory/inventory.go
>  		lang.TotalBytes = uint64(file.Size())
Yes, we can't guess the number of lines without knowing the content.

2024-07-15 12:56 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +	}
Looking at the `getLang` function, here are the non-error cases when we return `Lang{}`:

```
if file == nil {
		return Lang{}, nil
	}
```

```
if !file.Mode().IsRegular() || enry.IsVendor(file.Name()) {
		return Lang{}, nil
	}
```

```
if err == io.EOF {
			// No bytes read, indicating an empty file
			return Lang{}, nil
		}
```

None of them look like unknown or ambiguous results to me. (2) deliberately skips files that we don't consider worth checking the language for.

2024-07-15 13:27 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +		}
I will keep that in mind! Thank you for the patient and detailed explanation :)

With the rewrite of the tar file processing, I opted to compute the Sum every time we complete an inventory. That's the point where we want to cache, and waiting for too many records doesn't seem worth it. Also the benchmarking for Sum shows that it's not an issue if we call it a bit more often:

```
	// n=1000: ~8500 ns/op
	// n=100: ~1100 ns/op
	// n=10: ~360 ns/op
	// n=5: ~300 ns/op
	// n=2: ~280 ns/op
```

2024-07-16 11:13 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +		return Inventory{}, err
That makes sense to me. Updated this to return an empty inventory.

2024-07-16 11:39 UTC, bahrmichael commented on cmd/frontend/backend/repos.go
> +	}
I've updated this to return an error that the commitID must not be empty, and updated the four usages of this function to handle the empty commitID. It feels a bit awkward to do that handling in all the places when it could default to an empty Inventory here, but I'm happy to roll with it.

2024-07-16 11:46 UTC, bahrmichael commented
@eseliger @camdencheek I completed another pass, and the PR is ready for you to review again. The major change is that I reworked the inventory code to be simpler to test, then added some complicated caching logic, and with @camdencheek decided to drop that caching again. This means the code is now just a bit simpler to test, and doesn't cache except at the repo-level. Let me know what you think!

2024-07-16 11:49 UTC, bahrmichael commented on cmd/frontend/internal/inventory/context.go
> +	CacheGet func(context.Context, string, api.CommitID) (Inventory, bool)
I used `string` so that it would support the repoId (now with a commitID suffix) as well as the file name (via the CacheKey function) from the other code paths that still use the old approach.

2024-07-16 11:50 UTC, bahrmichael commented on cmd/frontend/graphqlbackend/search_results_stats_languages.go
> +			inv, err := invCtx.Entries(ctx, key.commitID, work.fullEntries...)
Reworked this.

2024-07-16 11:50 UTC, bahrmichael commented on cmd/frontend/backend/repos.go
> +	inv, err := invCtx.All(ctx, s.gitserverClient, commitID)
I updated it to align with Option 1.

2024-07-16 14:51 UTC, camdencheek commented on cmd/frontend/internal/inventory/entries.go
> +	}
`GetLanguageByFilename` can return an empty string for the language:

```
func main() {
	language, _ := enry.GetLanguageByFilename("hslgha.hsjahsg9")
	fmt.Printf("Language: %q\n", language)
}
```

2024-07-16 14:56 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +	}
Right! I created SRCH-737

2024-07-16 15:09 UTC, camdencheek requested changes
Almost there! Just a couple of quick things before I think this is ready to go

2024-07-16 15:09 UTC, camdencheek commented on cmd/frontend/internal/inventory/entries.go
> +				return n.FileReader, nil
When is `FileReader` closed?

2024-07-16 15:09 UTC, camdencheek commented on cmd/frontend/internal/inventory/entries.go
> +	ctx := context.Background()
Creating a new `context.Background()` is usually not what we want. Instead, we should still pass in a context and use `context.WithoutCancel` to remove the cancellation signal. That way we still retain all the other stuff contexts carry, like tracing information, authentication information, etc.

2024-07-17 06:38 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +				return n.FileReader, nil
This happens in `inventory.go` right after the function to get the file reader is called.

```
	rc, err := getFileReader(ctx, file.Name())
	if err != nil {
		return Lang{}, errors.Wrap(err, "Failed to create a file reader.")
	}
	if rc != nil {
		defer rc.Close()
	}
```

I'm adding a unit test to make sure this behavior doesn't break.

2024-07-17 07:17 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +	ctx := context.Background()
That's better indeed! I updated it in https://github.com/sourcegraph/sourcegraph/pull/62946/commits/719c13dc1e35d4d2c444fd542c1770a69e816d5b to use `WithoutCancel` and brought back the trace one level up. I think tracing in the for loop that iterates over files wouldn't bring much value compared to the overhead of creating traces.

2024-07-17 07:18 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +				return n.FileReader, nil
You can see the test here: https://github.com/sourcegraph/sourcegraph/pull/62946/commits/f8c5be275b9ededc64df577dadfa874628052fb3

2024-07-17 07:44 UTC, bahrmichael commented on cmd/frontend/backend/inventory.go
> +		},
Nope, we don't need that anymore. Dropped it with https://github.com/sourcegraph/sourcegraph/pull/62946/commits/9c254829b5b23fce60f10dc5ac8602d71a9fa654.

2024-07-17 07:45 UTC, bahrmichael commented on cmd/frontend/backend/inventory.go
> +		CommitID:                            commitID,
I like that, and also moved the language detection upwards. It felt odd to have the GitServerClient as a field after all the other functions, so I moved that up, too.

Here's the commit for that: https://github.com/sourcegraph/sourcegraph/pull/62946/commits/d0228c7e814a326bcb955b3c10f3b9a5462db153

2024-07-17 07:49 UTC, bahrmichael commented on cmd/frontend/graphqlbackend/git_commit.go
> +	}
This came from the conversations https://github.com/sourcegraph/sourcegraph/pull/62946#discussion_r1661566403 and https://github.com/sourcegraph/sourcegraph/pull/62946#discussion_r1661567202.

I wasn't aware that an empty string could mean HEAD and will check the code again. Do you have any objection to making sure we explicitly map empty string to HEAD when that is acceptable, and reject requests otherwise? I would prefer to remove the implicit meaning here.

2024-07-17 08:19 UTC, bahrmichael commented on cmd/frontend/internal/inventory/entries.go
> +				return n.FileReader, nil
As far as I can see, it's just the general io problems with leaks when you don't close readers.

In the `All` code we have an ArchiveReader (which now gets closed with https://github.com/sourcegraph/sourcegraph/pull/62946/commits/2d90cef9cacbc557b32c57d6e32da2ac8fc489b7) that gets handed to various `io.NopClosers`.  I think with the ArchiveReader's closing and the other calls to close, we should be safe.

2024-07-17 14:56 UTC, bahrmichael commented on cmd/frontend/graphqlbackend/git_commit.go
> +	}
I reverted the changes to the handling of non-absolute commits in https://github.com/sourcegraph/sourcegraph/pull/62946/commits/83e5ee30d3a0300d187a46d96fd3d56b924295fb.

It all started with trying to improve the error message, and that lead to a couple bad changes, that we can probably better leave untouched for now.

2024-07-17 14:57 UTC, bahrmichael commented on cmd/frontend/backend/repos.go
> +	}
I reverted my changes to the error-handling, since there were effects on other parts of the code that I'll better leave untouched for now. More context in https://github.com/sourcegraph/sourcegraph/pull/62946#discussion_r1679570588.

2024-07-17 15:10 UTC, camdencheek commented on cmd/frontend/graphqlbackend/git_commit.go
> +	}
Thanks!

2024-07-17 17:56 UTC, camdencheek approved these changes
Looks great -- thank you!

2024-07-18 06:40 UTC, merged