Graph 646/scip syntax java package namespace fix
sourcegraph/sourcegraph pull request #63048
Opened 2024-06-03 17:07 UTC by keynmol

## Test plan

## Changelog

2024-06-04 12:27 UTC, kritzcreek requested changes

2024-06-04 12:27 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__scip_snapshot_globals.java.snap.new
I think `.snap.new` files are for files you still need to review with `insta`. We don't want to commit these and instead accept their changes into the `.snap` file.

2024-06-04 13:47 UTC, varungandhi-src commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__test__scip_snapshot_globals.java.snap.new
Let's add `.snap.new` to `.gitignore` so that they don't accidentally get committed.

2024-06-05 09:22 UTC, keynmol commented on docker-images/syntax-highlighter/crates/scip-syntax/testdata/java/index.scip
> +../../../../../../bazel-bin/docker-images/syntax-highlighter/crates/scip-syntax/index-java.scip
Looks like this wasn't updated during crate reshuffle - only affects local `cargo test`, Bazel tests work fine.

2024-06-05 09:48 UTC, kritzcreek approved these changes
:+1:

2024-06-05 09:51 UTC, merged