Resolve syntactic symbol at request range
sourcegraph/sourcegraph pull request #63189
Opened 2024-06-10 14:38 UTC by kritzcreek

Closes https://linear.app/sourcegraph/issue/GRAPH-666/resolve-syntactic-symbol-at-the-range-specified-in-the-usages-request

Because the new occurrences API allows passing both a symbol or a range we need to be able to retrieve the syntactic symbol at the given range.

I added some utilty functions to the `shared.Range` and `shared.Position` types, which I assume are the position-ish types we want to use to communicate between resolver and codenav service code. 

I left a few NOTE and TODO's that I'd like to discuss during review.

## Test plan

I added both unit as well as property based tests for the utility functions on position and range.

In order to test the service functions I'd need to mock a bunch of systems, and I'm not sure if the test would have any meaning at that point (the logic is literally a single iteration and overlap check). If you'd like me to add it anyways let me know.

2024-06-11 02:24 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/util.go
> +func TranslateRange(r *scip.Range) shared.Range {
It's a bit weird for this function to live here given that we own the `shared.Range` type; let's move this to the `shared` package and call it `NewRange` matching the convention of other `New` functions.

2024-06-11 02:31 UTC, varungandhi-src commented on internal/codeintel/codenav/shared/types.go
> +	return cmp.Or(cmp.Compare(p.Line, other.Line), cmp.Compare(p.Character, other.Character))
```suggestion
	if ret := cmp.Compare(p.Line, other.Line); ret != 0 {
		return ret
	}
	return cmp.Compare(p.Character, other.Character)
```

The current code will do a redundant comparison (this is what I was talking about earlier: https://github.com/sourcegraph/sourcegraph/pull/63029#issuecomment-2144984378)

2024-06-11 03:13 UTC, varungandhi-src commented on internal/codeintel/codenav/shared/types.go
> +}
This seems off. SCIP ranges are meant to be half-open... I'll create a PR against the SCIP repo so that the `Range` type there is more generally useful and better documented.

2024-06-11 04:49 UTC, varungandhi-src commented on internal/codeintel/codenav/shared/types.go
> +}
https://github.com/sourcegraph/scip/pull/247

2024-06-11 04:56 UTC, varungandhi-src commented
I've moved the utility functions to the SCIP repo. https://github.com/sourcegraph/scip/pull/248

Rationale for the change:
- Those types already exist, converting them to the Sourcegraph specific types here isn't giving us anything. If we want to keep `shared.Range` as-is for now, I recommend implementing the code in terms of `scip.Range` and then replacing the usages of `shared.Range` with `scip.Range`.
- It seems at least some of the logic in this PR is predicated on the assumption that the Sourcegraph-specific types represent closed intervals (unless I'm misreading the code), which is not correct, at least when we're converting from the `scip.Range` type. Having fewer `Range` types overall reduces the risk of confusion.

2024-06-11 09:53 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/util.go
> +func TranslateRange(r *scip.Range) shared.Range {
Unfortunately `NewRange` overlaps with the other constructor function in here. Maybe this will all become obsolete if we decide to stick to `scip.Range` going forward.

2024-06-11 13:44 UTC, varungandhi-src requested changes
Left some initial comments, key one is changing the signature of the `getSyntacticSymbolsAtRange` function.

2024-06-11 13:53 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +) (symbols []*scip.Symbol, err error) {
This function is resolving the symbol at the range in the request, not the ranges returned via Search.

2024-06-11 13:57 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +) (symbols []*scip.Symbol, err error) {
The document fetching must not happen multiple times for the (repo, commit, path) triple. Where is that logic being handled?

2024-06-11 13:58 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	}
Is there a specific reason to not use `scip.FindOccurrences` here? We're already using the same function in a bunch of other places.

2024-06-11 14:11 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +	}
Mostly because I didn't know it existed. I do have a range and not a single position to check against though.

2024-06-11 14:24 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +) (symbols []*scip.Symbol, err error) {
Well in this PR there is only a single document fetched so far.

In the PoC branch: https://github.com/sourcegraph/sourcegraph/blob/a53f6fb759f4e6b13606f8802216047069a24c51/internal/codeintel/codenav/service.go#L1030-L1072

All search results are already grouped by file, so there's no re-fetching there. Only the document fetched for resolving the requested symbol would be requested twice, but I'm sure once I properly implement the paging and push logic down into individual resolvers I'll have to keep a dataloader cache around.

2024-06-12 05:36 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +) (symbols []*scip.Symbol, err error) {
OK, got it. I was confused because I didn't see this function being used anywhere else, so it wasn't clear to me what the layering was supposed to be. Might be worth adding a cautionary note in the doc comment to not call this in a loop (even if we add a separate document cache, going through the document multiple times doesn't make a lot of sense).

2024-06-12 05:47 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	}
Would recommend using https://pkg.go.dev/golang.org/x/exp/slices#BinarySearchFunc here. Document canonicalization guarantees that the occurrences will be sorted.

2024-06-12 06:01 UTC, varungandhi-src approved these changes
Looks directionally OK, left some minor improvement suggestions.

2024-06-12 08:56 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +	// TODO: Adjust symbolRange based on revision vs syntacticUpload.Commit
`GitTreeTranslator` is also a cache and has a relatively complicated API, might be a good candidate to look at during pairing.

2024-06-12 16:37 UTC, merged