Adds function to find candidate occurrences via search
sourcegraph/sourcegraph pull request #63196
Opened 2024-06-11 09:42 UTC by kritzcreek

Closes https://linear.app/sourcegraph/issue/GRAPH-640/pre-filter-candidate-files-by-consulting-zoektsearcher

## Test plan

No tests yet, once we've merged both #63180 and this PR I can stitch them together and see if I can write an integration test.

2024-06-13 09:26 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	language := "java"
You can use the `GetLanguages` function here from the `lib/codeintel/languages.go` package - that will be simpler than getting the language from the document. We currently don't have conversion logic from SCIP languages to enry languages. I've made a note of that here. https://github.com/sourcegraph/langur/issues/14#issuecomment-2165113060

2024-06-13 10:28 UTC, varungandhi-src requested changes

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +	}
I tried to look into when this planning can fail, and got tricked into a wild-goose chase around user settings etc. Never mind. 🤷🏽

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +		return nil, err
If we're getting errors, especially from other subsystems, let's wrap them up with some contextual information to aid with debugging.

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +		fileMatch, ok := match.(*result.FileMatch)
```suggestion
	for _, streamResult := range stream.Results {
		fileMatch, ok := streamResult.(*result.FileMatch)
```

The word `match` is used multiple times later, this is a bit confusing to read, because it's a different type from the `matches` slice

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +		}
We can accumulate a count and log an error if this is non-zero. It's not a fatal error, and we don't have `debug_assert!`.

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +					panic("FileMatch with chunkMatch.Ranges from a different file")
Same advice as above, let's keep track of a `count` and log that if greater than zero, instead of panicking.

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +				})
1. Are these ranges zero-based or one-based? `scip.Range` should be zero-based.
2. Are these offsets UTF-8 byte offsets or rune offsets? Regardless of what they are, please file a sub-issue of https://linear.app/sourcegraph/issue/GRAPH-673/correct-utf-8-and-utf-16-offset-handling-in-code-graph-apis and mention that here `FIXME(issue: <blah>)`.

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +		}
I don't think so, no. We'd already be logging an error if a result is skipped.

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +// TODO: Check for local symbols, and don't return a name (needs an isLocal method for scip.Symbol)
If the first descriptor has a local suffix, then this must be a local symbol.

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/transport/graphql/root_resolver.go
> +		}
I think we should log the error here and keep going instead of returning the error to the user. The error can happen because all sorts of random things like the query planning failing because it failed to get the settings or something.

2024-06-13 10:28 UTC, varungandhi-src commented on internal/codeintel/codenav/transport/graphql/root_resolver.go
> +		}
Let's move this logic into `func (args *UsagesForSymbolArgs) Resolve`, and return a more verbose error to the client in case they sent a malformed range, instead of whatever error the `scip` library returns. The error formatting in the `scip` library is deliberately sparse to avoid accidentally triggering a lot of formatting work if there are a bunch of malformed ranges.

2024-06-13 11:01 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +		return nil, errors.Newf("no matching occurrences found for range")
I think as the caller you'd want to be able to differentiate between: "There were no usages for the symbol at the given coordinate" and "there was no symbol at the given coordinate".
The second one most likely means you have a bug when constructing the request.

I agree that mixing that error condition with all the others is bad. If only there was a language feature that would let you make a "sum" of possible error states. I don't know how to handle this in Go. Add an extra "bool" parameter to the output so you have `usages, ok, err` where `!ok` means the request args might be malformed?

2024-06-13 11:19 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +) ([]struct{}, error) {
Returning real results happens after the next PR in which we filter the candidate matches against our syntactic scip documents. I thought showing the integration of the different parts up to this point would be a good idea anyway.

2024-06-13 11:25 UTC, kritzcreek commented on internal/codeintel/codenav/syntactic.go
> +				})
Good catch and questions. These are one-based rune offsets according to https://github.com/sourcegraph/zoekt/blob/c21df410093acfc887b458f901ada70aded67aee/api.go#L201-L219

2024-06-13 11:29 UTC, varungandhi-src commented on internal/codeintel/codenav/syntactic.go
> +	}
I'm wondering if we should handle a timeout error in a special way here (or in the outer loop maybe?) 🤔

2024-06-13 11:31 UTC, varungandhi-src commented
> I'm wondering what to do about o11y here. Should I be adding something to the operations, or some more logging?

We should add an operation for each public method (at least, that's the pattern we're following for now). So yes, we should have an operation for `SyntacticUsages`. For the cross-service call, the search code will handle creating a span, so we're good there. However, it's generally useful to attach extra information about the results to a final event. How many files were matched, total number of matches etc. We should also attach an event related to the query details, it looks like the Execute function doesn't attach any information related to that.

2024-06-13 13:36 UTC, kritzcreek commented on internal/codeintel/codenav/syntactic.go
> +				})
The docs are lying! DON'T TRUST THE DOCS.

2024-06-13 14:30 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +	commit api.CommitID,
There is no pre-condition. Error handling is more fine-grained/less fatal now. (I'm assuming that's what you were aiming at?)

2024-06-13 14:36 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	commit api.CommitID,
I asked because it wasn't clear from the code...

In some parts of the code, the path is passed around post-existence check, and in some cases, it is pre-existence check. I wonder if we should have a few different types for:
- A `repo, commit` pair that has is known to exist.
- A `repo, commit` pair with a `path` that hasn't gone through an existing check
- A `repo, commit, path` pair that has been checked to exist

That might help understand in which situation some error is "weird" (OK, you can force-push, yes, but typically it's the main branch being indexed) and in which situation it is "normal". 🤔

2024-06-14 07:29 UTC, kritzcreek commented
I handled most of the feedback, but decided after a while that some of it is not actually required for the MVP stage. I've filed a follow-up issue for me to come back for some of these https://linear.app/sourcegraph/issue/GRAPH-683/syntactic-usages-tech-debt

2024-06-14 07:37 UTC, kritzcreek commented on internal/codeintel/codenav/syntactic.go
> +				})
It's on my list ^^ As the docs are in the zoekt repo, I'd like to come up with a reproducer that doesn't involve all of sourcegraph/sourcegraph

2024-06-14 08:57 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +type SyntacticUsagesErrorCode = int
```suggestion
type SyntacticUsagesErrorCode int
```

We don't want a type alias, we want a newtype wrapper. Yes, there are some places where Go will do implicit conversions anyways, but this will be more confusing to debug.

2024-06-14 09:12 UTC, varungandhi-src reviewed
Will do another pass after an hour or so.

2024-06-14 09:12 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	defer endObservation(1, observation.Args{})
I just looked into this; it looks like `endObservation` will log the error if we pass in a proper pointer here. So if we really want to return `SyntacticUsageError` from this function, then we can do the following sequence.

```suggestion
) (_ []struct{}, err *SyntacticUsagesError) {
    var erasedError error
	// The `nil` in the second argument is here, because `With` does not work with custom error types.
	ctx, trace, endObservation := s.operations.syntacticUsages.With(ctx, &erasedError, observation.Args{Attrs: []attribute.KeyValue{
		attribute.Int("repoId", int(repo.ID)),
		attribute.String("commit", string(commit)),
		attribute.String("path", path),
		attribute.String("symbolRange", symbolRange.String()),
	}})
	defer endObservation(1, observation.Args{})
	defer func(){ if err != nil { erasedError = *err } }()
```

2024-06-14 09:12 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	langs, langErr := languages.GetLanguages(path, func() ([]byte, error) { return nil, errors.New("Ambiguous language") })
- The function argument allows returning an error because content-fetching might return an error. If we don't have access to the content here, you can pass `nil` for the second argument. So there won't be any error returned from the API.
- If there are multiple languages returned, we should do an `AND` instead of taking the first one.

2024-06-14 10:36 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	commit api.CommitID,
Marking this as resolved as it is not super pressing.

2024-06-14 10:45 UTC, varungandhi-src approved these changes
I updated the tech debt issue with more details. I'm OK with merging this as-is for now, but I don't want us to rush stuff like this purely for demo day, we can share a demo in Slack outside of demo day too.

2024-06-14 10:57 UTC, merged

2024-06-14 11:07 UTC, kritzcreek commented
> but I don't want us to rush stuff like this purely for demo day

Nothing about demo day and everything about the MVP milestone. This code doesn't need to deal with language ambiguity to check its viability, but that's what I want to be laser-focused on.

2024-06-14 11:29 UTC, kritzcreek commented
Just want to clarify, I'm not saying I don't appreciate the thorough review, feedback, and discussion. I read every comment and definitely intend to get back to and address the rest of it.
I just decided that the bar for things I want to do _right now_ has to impact the MVP aspect of the project.