chore(codeintel): Use internal language detection package for insights
sourcegraph/sourcegraph pull request #63254
Opened 2024-06-13 20:08 UTC by mmanela

Updates two more places to use the common language detection package (which wraps go-enry) instead of using go-enry directly. This provides us more flexibility and ensures a consistent mechanisms across the product. 

## Test plan
- Updated unit tests
 
## Changelog

- Code clean up to use common language detection mechanism in more places

2024-06-13 21:58 UTC, camdencheek commented on lib/codeintel/languages/languages.go
> +		return []byte(contents), nil
Why do we copy and truncate contents here?

2024-06-13 22:01 UTC, camdencheek commented on lib/codeintel/languages/languages.go
> +		if lang != "" {
Will `GetLanguages` return an empty string language? If so, we should document that because it seems unintuitive to me.

2024-06-13 22:03 UTC, camdencheek commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
Why does this signature use a resolved `contents` rather than a callback function like `GetLanguages`? I think the callback function makes for a more flexible API since we can lazily make an API request for the contents if needed rather than forcing us to either 1) fetch the contents in advance, or 2) never have any contents for language detection.

2024-06-13 23:50 UTC, mmanela commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
I did the byte array here to be more consistent with the existing api usage I was replacing. I am fine to change to the callback method

2024-06-13 23:55 UTC, mmanela commented on lib/codeintel/languages/languages.go
> +		return []byte(contents), nil
Fixed

2024-06-13 23:55 UTC, mmanela commented on lib/codeintel/languages/languages.go
> +		if lang != "" {
That is a good question, I was just modeling after the existing `GetMostLikelyLanguage` which seems to indicate it does, but I am not sure based on reading it if it is actually possible. It does call out to the underlying go-enry and not sure if that library can either.

2024-06-14 00:51 UTC, camdencheek approved these changes
LGTM pending open question about extra truncations. Thanks Matt!

2024-06-14 01:28 UTC, varungandhi-src commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
This function is too tempting to use, because it seems simpler than the `GetLanguages` API. However, it allows the caller to ignore the important case of the language being ambiguous.

Please remove this function/the caller should be contextually handling the case of ambiguity.

2024-06-14 01:50 UTC, varungandhi-src commented on lib/codeintel/languages/languages.go
> +		if lang != "" {
`GetLanguages` will not return an empty string (unlike some enry APIs). https://github.com/sourcegraph/sourcegraph/pull/63260

2024-06-14 01:52 UTC, varungandhi-src requested changes
Please remove the `GetFirstMatchingLanguage` function.

2024-06-14 01:59 UTC, varungandhi-src commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
> to be more consistent with the existing go-enry api

Consistency with go-enry APIs is a non-goal; they are error prone.

2024-06-14 02:09 UTC, mmanela commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
That is why I named it clearly first matching language, seems silly for each caller to make the same decision when the intent is to choose the first matching language which is what go-enry was already doing

2024-06-14 02:17 UTC, varungandhi-src commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
Historically speaking, the API you've added has had people ignoring the second return value (i.e. incorrectly assuming that the language detection will always succeed, or incorrectly passing `""` to the caller).

Other than that,
- In our GraphQL API, we return all possible languages. Previously we just returned one language -- which was wrong.
- For code insights language classification, instead of just picking the most likely language, maybe it's valuable to actually mark "ambiguous" files separately, so that we can see how many files are ambiguous. Once you have a way of tracking that using insights, then you can start refining the heuristics, or maybe we can hint to the user ("psst, you can add these override settings for language detection").

Once the caller has the array, you need to think about the various cases. Yes, someone can still do the naive thing and pick the first element, but at least the decision has to be made there.

If this were Rust code, I would've made the API return an enum with `Unknown | Confident(Language) | Ambiguous(Vec<Language>)`.

2024-06-14 02:23 UTC, varungandhi-src commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
The problem with reifying the bad habit (pick the first element carelessly) in an API is that it reinforces a _conceptual error_, namely that there is always a most likely language. For header files that are both valid C and C++, there is no reasonable notion of "most likely" that makes sense at a file-level. It only makes sense when analyzed at a project level.

2024-06-14 15:35 UTC, mmanela commented on lib/codeintel/languages/languages.go
> +func GetFirstMatchingLanguage(path string, contents []byte) (language string, found bool) {
Thanks for explaining your principles so clearly. I updated the code to use GetLanguages. I put a comment indicated at the call site that they are picking the first language for now. But Ill leave it up to @camdencheek  for the future if he wants to make more explicit use of the multiple potential returns

2024-06-17 05:40 UTC, varungandhi-src approved these changes

2024-06-17 05:48 UTC, varungandhi-src commented
I've filed https://linear.app/sourcegraph/issue/SRCH-548/correctly-handle-ambiguous-languages-in-code-insights

2024-06-17 18:03 UTC, merged