fix: Check (uploadID, path) pairs in bulk
sourcegraph/sourcegraph pull request #63485
Opened 2024-06-26 05:39 UTC by varungandhi-src

Fixes https://linear.app/sourcegraph/issue/GRAPH-700

Previously, there were two code paths which were checking if certain
upload IDs containing a specific repo-relative path. One was using the
better GetPathExists API, the another one that I recently added was
much more stupid, it was deserializing the full SCIP Document.

However, using `GetPathExists` in a loop is also not great; we should
push the loop into the database. This patch replaces both of those usage
sites with a single function that handles bulk filtering, and replaces
the `GetPathExists` lsifstore method with `FindDocumentIDs`.

Q: Why are we returning document IDs if the caller doesn't need them?
A: Getting the document ID is essentially "free", so I thought it would be
better to return a mapping instead of a set.

However, I didn't generalize the API to support multiple paths within
the same upload, as that would complicate the method signature somewhat.
(the argument and return types would be both `collections.Set[Pair[int, UploadRelPath]]`).

I'm open to changing the method to work with sets instead and renaming
it to `CheckPathsExist`.

## Test plan

Modified GetPathExists test to use the new FindDocumentIDs API.

## Changelog

2024-06-26 05:42 UTC, varungandhi-src commented on internal/codeintel/uploads/shared/types.go
> -var _ core.UploadLike = &CompletedUpload{}
I changed this because the other code currently works with []CompletedUpload, and I wanted to use that as `[]U` where `U` implements `UploadLike`.

2024-06-26 05:44 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +func filterUploadsImpl[U core.UploadLike](
This function is generic because:
1. Reading and typing `uploadsshared.CompletedUpload` in multiple places gets old quickly.
2. There's actually no need for the other fields, we only really care about the ID and the Root.

2024-06-27 03:23 UTC, kritzcreek requested changes
Thank you for looking into this. Have a few comments (mostly docs related)

2024-06-27 03:23 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +// The skipDBCheck function avoids consulting the database for certain uploads.
I don't fully get the `skipDBCheck` parameter here

- Does "avoid consulting the database" mean the upload is always included or excluded from the result?
- The comments says we're skipping the DB check, but in the loop over candidate further down we unconditionally add all paths to `lookupPaths`, before passing them to `FindDocumentIDs`

2024-06-27 03:23 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +	queries := []*sqlf.Query{}
The name is a bit confusing as these are not SQL queries. Maybe something like `searchTuples`?

2024-06-27 03:23 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +	}
Could we simplify this with `basestore.NewMapScanner`?

2024-06-27 03:23 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +		s.logger.Warn("FindDocumentIDs failed", log.Error(err))
Should this use the request specific trace logger instead? It would probably be easier to debug if this starts failing if we had the context of the request.

2024-06-27 03:23 UTC, kritzcreek commented on internal/codeintel/codenav/service.go
> +	}
We should document at the function level that both error and result values can be populated at the same time here.

2024-06-27 10:32 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +// The skipDBCheck function avoids consulting the database for certain uploads.
Ah, I tried simplifying the code and dropped a `continue` earlier. I've documented the expected behavior of `skipDBCheck`.

2024-06-27 10:43 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +	}
Documented this post-condition

2024-06-27 10:44 UTC, varungandhi-src commented on internal/codeintel/codenav/service.go
> +		s.logger.Warn("FindDocumentIDs failed", log.Error(err))
Good catch, changed to use TraceLogger

2024-06-27 10:44 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +	}
Yes, simplified this as suggested.

2024-06-27 10:44 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +	queries := []*sqlf.Query{}
`queries` -> `searchTuples` ✅

2024-06-27 11:09 UTC, kritzcreek approved these changes

2024-06-28 08:31 UTC, merged