chore/enterpriseportal: add test for iam_model, remove unused relation
sourcegraph/sourcegraph pull request #63503
Opened 2024-06-27 00:12 UTC by bobheadxi

Uses the guidance in https://openfga.dev/docs/modeling/testing to craft some rudimentary IAM model tests for Enterprise Portal IAM, and removes an unused relation (`user view cody_analytics` - we should do this via roles only)

Not automated for now - the model tests must be run manually:

```
go run github.com/openfga/cli/cmd/fga@latest model test --tests='cmd/enterprise-portal/service/iam_model.fga.yml'
```

If we end up changing the model more I'll ask around in dev-infra to see how we should automate this.

## Test plan

CI and:

```
go run github.com/openfga/cli/cmd/fga@latest model test --tests='cmd/enterprise-portal/service/iam_model.fga.yml'
```

2024-06-27 14:10 UTC, jac requested changes
this doesn't look correct to me. it was passing but I don't think the assertions were actually correct

_the uuids are painful to review lol_ 😭

2024-06-27 14:10 UTC, jac commented on cmd/enterprise-portal/service/iam_model.fga.yml
> +
don't we need to make it so members of a specific customer admin have access to specific subscriptions?
```suggestion
- user: customer_admin:80ca12e2-54b4-448c-a61a-390b1a9c1224#member
  relation: view
  object: subscription_cody_analytics:80ca12e2-54b4-448c-a61a-390b1a9c1224

- user: customer_admin:4CDA7E9F-69D8-4594-9637-F964693ADFE5#member
  relation: view
  object: subscription_cody_analytics:4CDA7E9F-69D8-4594-9637-F964693ADFE5

```

(is it expected that customer admin objects and subscription_cody_analytics objects have the same IDs?)

2024-06-27 14:10 UTC, jac commented on cmd/enterprise-portal/service/iam_model.fga.yml
> +        view: false
the assertions should be they can view, right? (+ a typo in the second subscription id)
```suggestion
        view: true

    - user: user:617E04BC-905D-4543-94E7-55DCF7F5E92F
      object: subscription_cody_analytics:4CDA7E9F-69D8-4594-9637-F964693ADFE5
      assertions:
        view: true
```

2024-06-27 14:10 UTC, jac commented on cmd/enterprise-portal/service/iam_model.fga.yml
> +      object: subscription_cody_analytics:CDA7E9F-69D8-4594-9637-F964693ADFE5
same typo
```suggestion
      object: subscription_cody_analytics:4CDA7E9F-69D8-4594-9637-F964693ADFE5
```

2024-06-27 14:10 UTC, jac commented on cmd/enterprise-portal/service/iam_model.fga.yml
> +      object: subscription_cody_analytics:CDA7E9F-69D8-4594-9637-F964693ADFE5
same typo
```suggestion
      object: subscription_cody_analytics:4CDA7E9F-69D8-4594-9637-F964693ADFE5
```

2024-06-27 18:51 UTC, jac approved these changes

2024-06-27 18:56 UTC, merged

2024-08-14 01:00 UTC, unknwon reviewed
TIL!