feat: complete batch changes github app flow for user credentials
sourcegraph/sourcegraph pull request #63635
Opened 2024-07-04 09:42 UTC by bahrmichael

## Test plan

## Changelog

2024-07-04 09:49 UTC, bahrmichael commented on internal/batches/service/service.go
> +		externalServiceType:    args.ExternalServiceType,
I moved this code from `cmd/frontend/internal/batches/resolvers/resolver.go`.

2024-07-04 09:49 UTC, bahrmichael commented on internal/batches/service/service.go
> +	}
I moved this code from `cmd/frontend/internal/batches/resolvers/resolver.go`.

2024-07-04 10:42 UTC, BolajiOlajide commented on cmd/frontend/internal/batches/resolvers/credential.go
> +	ghastore   ghastore.GitHubAppsStore
This is a duplicate field. There's a field in [here on R80](https://github.com/sourcegraph/sourcegraph/pull/63635/files#diff-8febe19ec37d1bfa67bf2999a628e7f0249698869ece953173a04f64413371adR80) that has this already.

Can we consolidate them? `ghastore` and `ghstore`

2024-07-04 10:42 UTC, BolajiOlajide commented on cmd/frontend/internal/batches/resolvers/errors.go
> -type ErrBatchChangeInvalidName struct{ error }
I don't think we should remove this. I understand this field is unused but if this is wrapped by any error down the line, it'd be hard to unwrap.

2024-07-04 10:42 UTC, BolajiOlajide commented on cmd/frontend/internal/batches/resolvers/resolver.go
> +	"github.com/sourcegraph/sourcegraph/lib/pointers"
These imports aren't properly sorted. 

It's one of the weirdness I encountered with Goland, I haven't found a way to integrate `golangci-lint`.

2024-07-04 10:42 UTC, BolajiOlajide commented on cmd/frontend/internal/batches/resolvers/resolver.go
> +	return &batchChangesSiteCredentialResolver{credential: cred}, nil
We also need to pass in the `GitHubAppsStore`

2024-07-04 10:58 UTC, BolajiOlajide requested changes

2024-07-04 10:58 UTC, BolajiOlajide commented on cmd/frontend/internal/githubapp/httpapi.go
>  	}
Are there plans to fix this TODO in this PR?

2024-07-04 10:58 UTC, BolajiOlajide commented on cmd/frontend/internal/githubapp/httpapi.go
> +		if kind == ghtypes.UserCredentialGitHubAppKind {
You'll need to replicate this for Site Credentials, this only works for user credentials right now.

2024-07-04 10:58 UTC, BolajiOlajide commented on internal/batches/service/service.go
> +func (s *Service) generateAuthenticatorForCredential(ctx context.Context, args generateAuthenticatorForCredentialArgs) (extsvcauth.Authenticator, error) {
I didn't handle this earlier but we'll need a check for if `authenticationStrategy` is GitHubApp so we can create a github app authenticator.

2024-07-04 10:58 UTC, BolajiOlajide commented on internal/batches/sources/sources.go
> +	// Empty authenticators are not for non-GitHubApp authentication strategies.
This comment is redundant, we should remove it. It should just read `// Empty authenticators are not allowed.`

2024-07-04 10:58 UTC, BolajiOlajide commented on internal/github_apps/store/store.go
> +	GetByDomain(ctx context.Context, domain itypes.GitHubAppDomain, kind ghtypes.GitHubAppKind, baseURL string) (*ghtypes.GitHubApp, error)
We should renamed this `GetByDomainAndKind` so it's clear what's going on here. The `domain` isn't the main source of truth for github apps anymore.

2024-07-04 11:48 UTC, bahrmichael commented on internal/github_apps/store/store.go
> +	GetByDomain(ctx context.Context, domain itypes.GitHubAppDomain, kind ghtypes.GitHubAppKind, baseURL string) (*ghtypes.GitHubApp, error)
Done! I wanted to wait with that until I got a reasonable stable state.

2024-07-04 11:50 UTC, bahrmichael commented on cmd/frontend/internal/githubapp/httpapi.go
>  	}
Yes! I'll address that right away.

2024-07-04 11:54 UTC, bahrmichael commented on cmd/frontend/internal/batches/resolvers/errors.go
> -type ErrBatchChangeInvalidName struct{ error }
I'll bring it back 👍

2024-07-04 11:58 UTC, bahrmichael commented on cmd/frontend/internal/batches/resolvers/resolver.go
> +	"github.com/sourcegraph/sourcegraph/lib/pointers"
I'm wondering what the source (or tool) of truth is. I just ran `sg lint --fix format` and that didn't update imports.

2024-07-04 12:00 UTC, bahrmichael commented on cmd/frontend/internal/batches/resolvers/resolver.go
> +	return &batchChangesSiteCredentialResolver{credential: cred}, nil
👍

2024-07-04 12:00 UTC, bahrmichael commented on cmd/frontend/internal/batches/resolvers/credential.go
> +	ghastore   ghastore.GitHubAppsStore
Yup, done that!

2024-07-04 12:34 UTC, bahrmichael commented on cmd/frontend/internal/githubapp/httpapi.go
> +		if kind == ghtypes.UserCredentialGitHubAppKind {
Done, but not tested (apart from existing CI)

2024-07-04 17:20 UTC, BolajiOlajide commented on cmd/frontend/internal/batches/resolvers/resolver.go
> +	"github.com/sourcegraph/sourcegraph/lib/pointers"
Yeah, `golangci-lint` is what usually does this on vscode, but I haven't found a way to do it on GoLand.
![CleanShot 2024-07-04 at 18 19 21@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/8e256688-e7b9-4971-a936-4cd53e884bf3)

2024-07-04 17:33 UTC, BolajiOlajide commented on cmd/frontend/internal/batches/resolvers/resolver.go
> +	"github.com/sourcegraph/sourcegraph/lib/pointers"
![CleanShot 2024-07-04 at 18 29 41@2x](https://github.com/sourcegraph/sourcegraph/assets/25608335/d4de45da-f34a-415a-93b8-6e01f2facf6c)

https://plugins.jetbrains.com/plugin/12496-go-linter

I was able to get it working with this.

2024-07-05 08:09 UTC, bahrmichael commented on cmd/frontend/internal/batches/resolvers/resolver.go
> +	"github.com/sourcegraph/sourcegraph/lib/pointers"
We should put this into our handbook, golangcli-lint doesn't seem to mentioned anywhere in sg/sg nor in notion. `sg lint` should use it, too.

2024-07-05 08:51 UTC, bahrmichael commented on internal/batches/service/service.go
> +func (s *Service) generateAuthenticatorForCredential(ctx context.Context, args generateAuthenticatorForCredentialArgs) (extsvcauth.Authenticator, error) {
I see that you took care of this in https://github.com/sourcegraph/sourcegraph/pull/63635/commits/3aa0a9d700a2fbc7aa20763cee70503fafe6df0e. Thank you!

2024-07-05 11:30 UTC, BolajiOlajide approved these changes
Just a couple of comments and this should be good to go.

2024-07-05 13:55 UTC, BolajiOlajide approved these changes

2024-07-05 13:56 UTC, merged