WIP: Extracts a MappedIndex abstraction for syntactic usages
sourcegraph/sourcegraph pull request #63781
Opened 2024-07-11 11:27 UTC by kritzcreek

TODO

## Test plan

TODO

2024-07-15 12:23 UTC, kritzcreek commented
Sorry for messing around with the reviewers, I think Varun has a lot more context for this change. I'll ask Anton for review when I use this new abstraction to write syntactic usages tests.

2024-07-15 16:13 UTC, varungandhi-src requested changes
Took a brief look, will take a look at the rest tomorrow

2024-07-15 16:13 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +func (s *store) SCIPDocument(ctx context.Context, uploadID int, path core.UploadRelPath) (_ *scip.Document, found bool, err error) {
I thought you were going to change this to use `core.Option`, right? I think the problem you must've run into is that you shouldn't copy `scip.Document` since it has a mutex. Maybe we can add an API to `core.Option` that takes in a pointer argument?

2024-07-15 16:13 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +}
Please add doc comments here. Is `TargetCommit` guaranteed to be a descendant of `IndexCommit` or can it be unrelated or an ancestor?

Maybe `TargetCommit` should be called `NavCommit` or `NavigationCommit` instead, since the point is that we support code navigation at that commit?

2024-07-15 16:13 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	hunkCache, err := NewHunkCache(100)
Suggestion: Create an issue and link that here?

2024-07-15 16:13 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +// NewMappedIndex creates a MappedIndex for an uploaded index and a targetCommit
nit: I don't think this doc comment is adding anything over the type signature.

2024-07-15 16:13 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	}
There is a data race here. If two goroutines call `GetOccurrences` concurrently on the same `mappedDocument`, then one of them may do an unsynchronized read from `d.isMapped` while the other does a write to `d.isMapped`. The read and write may race as the read is not protected by the mutex. You can use an RWMutex here, or have the lock/unlock sequence at the start of the function.

2024-07-15 16:13 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	defer d.isMappedLock.Unlock()
See note about data race earlier, both reads and writes need to be synchronized.

2024-07-15 16:18 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	}
On second thought, holding the lock across the call to `GetTargetCommitRangeFromSourceRange` seems like an anti-pattern. Generally, you want to hold the lock for the shortest time possible, but there might be a network request in `GetTargetCommitRangeFromSourceRange`.

2024-07-16 00:51 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index.go
> +	}
> There is a data race here.

Yep, realized that as I went to bed as well :D

> Generally, you want to hold the lock for the shortest time possible

Yeah I've been thinking about this. What about using sync.Once, but only blocking `GetOccurrences` on this, and creating a copied occurrences slice (especially given that I also need to filter as you noted in the other comment).

Then `GetOccurrencesAtRange` could just check an atomic bool and be certain that the occurrences slice it's iterating over doesn't get changed concurrently.

2024-07-16 01:04 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	}
On second thought, holding the mutex is probably fine since the Go runtime will automatically unlock/lock it based on scheduling decisions. In Rust, the sync mutex is not connected to async runtimes, so this is a problem.

I think `sync.Once` is also a good option, since the logic where the state needs to be protected will be contained inside a function call. But you need to make sure that reads don't happen before the `sync` call.

> Then GetOccurrencesAtRange could just check an atomic bool and be certain that the occurrences slice it's iterating over doesn't get changed concurrently.

Let's not have multiple things for synchronization if we can avoid it. `tryGetDocument` follows a very simple pattern, it first calls `Do` on the `sync.Once`. After that, all the code just does reads. This is safe because:
- If sync.Once.Do is not running, the first goroutine will start running it
- If sync.Once.Do is running, other goroutines will be stuck at the Do ("Because no call to Do returns until the one call to f returns" per the docs)
- If sync.Once.Do returns, all goroutines can proceed with reads.

We can do the same here. A `sync.Once.Do` internally uses an atomic (https://go.dev/src/sync/once.go), so having an extra atomic bool would be redundant.

2024-07-16 02:24 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +func (s *store) SCIPDocument(ctx context.Context, uploadID int, path core.UploadRelPath) (_ *scip.Document, found bool, err error) {
I wasn't sure how deep I should push the Option, but as this is still within `codeintel/` you're right.

> Maybe we can add an API to core.Option that takes in a pointer argument?

I don't know if that's required, looks like `core.Option[*T]` works just fine.

2024-07-16 02:26 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +func (s *store) SCIPDocument(ctx context.Context, uploadID int, path core.UploadRelPath) (_ *scip.Document, found bool, err error) {
> looks like core.Option[*T] works just fine.

In that case, None and Some(nil) would both represent "not found", right? Adding pointer-based APIs to `Option` would collapse those two states into one.

2024-07-16 02:34 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +func (s *store) SCIPDocument(ctx context.Context, uploadID int, path core.UploadRelPath) (_ *scip.Document, found bool, err error) {
I think if we decide that "not found" in codeintel means `option.None` we can reclaim `*T` to mean "never nil, here for mutability/perf reasons"

2024-07-16 02:49 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index.go
> +}
> Is TargetCommit guaranteed to be a descendant of IndexCommit or can it be unrelated or an ancestor?

I don't think it matters for the implementation or the caller? The important thing is that all arguments and return values are specified in "TargetCommit" coordinates.
As these functions aren't called at the moment I could also just remove them for now?

> Maybe TargetCommit should be called NavCommit or NavigationCommit instead, since the point is that we support code navigation at that commit?

I'm not in love with the "target" name, but as this is an abstraction I don't want to name anything after one of its usage sites. After I merge this PR I was planning to switch the codegraphdata API over to using this as well, at which point it'll be used in a non-navigation context.

2024-07-16 02:53 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index.go
> +	}
I tried a different implementation in 80b68c4fec123fe9cbb37faf35523c26c53dcff4 PTAL

> Let's not have multiple things for synchronization if we can avoid it.

The problem is that it's slow to map all occurrences in all candidate documents during syntactic usages. Having the `GetOccurrencesAtRange` API do less translations in cases we only care about a few ranges is noticeably quicker.
That unfortunately means there's a branch for "all occurrences have been mapped previously" and one for "occurrences are still unmapped" in `GetOccurrencesAtRange`.

2024-07-16 03:06 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +}
> I don't think it matters for the implementation or the caller?

git diff will work with both `git diff A B` and `git diff B A` but we only propagate upload visibility in one direction in the commit graph.

Is your point that if the commit graph mechanism somehow supported visibility in the backwards direction, then this will just handle that case out-of-the-box without changes?

If it doesn't matter, then let's document that it doesn't matter.

> After I merge this PR I was planning to switch the codegraphdata API over to using this as well, at which point it'll be used in a non-navigation context

The CodeGraphData API is also present for the purpose of code navigation (specifically, it will be invoked when the user is browsing the file)

It's not a big deal though, leaving the naming up to you.

2024-07-16 04:25 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	}
Left a comment here: https://github.com/sourcegraph/sourcegraph/commit/80b68c4fec123fe9cbb37faf35523c26c53dcff4#r144271554 (not sure why it doesn't show up normally in the PR review)

2024-07-16 07:29 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index.go
> +	}
> not sure why it doesn't show up normally in the PR review

Yeah, it's weird.. I responded to the comment.

2024-07-16 09:44 UTC, kritzcreek commented
How about this one? :D Sorry for the back and forth, still getting to grips with concurrency in Go.

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/lsifstore_documents.go
> +	}
```suggestion
	if err != nil || !ok {
		return core.None[*scip.Document](), err
	}
```

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	GetDocument(context.Context, core.RepoRelPath) (core.Option[MappedDocument], error)
Please document the situation when `None` is returned.

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +}
Since there is synchronization and aliasing involved here, please document whether the caller is free to modify the returned slices themselves and the occurrences.

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	if document, ok := optDocument.Get(); ok {
Let's mention this in the `GetDocument` API docs in the interface (i.e. each request loads the full document from the DB) instead of leaving it as a TODO here.

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +		})
This code will be silently incorrect when we add a new field to `Occurrence`. I know it's a bit icky, but it would be more future-proof to roundtrip serialize->deserialize (through Protobuf) and overwrite the value in the copy. Another alternative is to use `reflect.DeepCopy`, but I'd be worried about how that might interact with the extra

```
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
```

fields inside Occurrence created by the Protobuf codegen.

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	defer d.document.lock.RUnlock()
```suggestion
```

This RLock is unnecessary (albeit somewhat future proof if we were to start writing to those fields in some other function), as the reads below will not be concurrent with any writes to those fields, since the writes only happen inside the `Do` block, and if one goroutine is inside the `Do` block, then other goroutines which reach the `Do` will be paused there. ("no call to Do returns until the one call to f returns" -- https://pkg.go.dev/sync#Once.Do)

We need to acquire the read lock in the other function since that function performs reads which do not synchronize with the `mapOnce`.

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	}
This doesn't have data races AFAICT, but a bit too pessimistic.

```suggestion
	d.document.lock.RLock()
	occs := d.document.inner.Occurrences
	if d.document.isMapped {
	    d.document.lock.RUnlock()
		return FindOccurrencesWithEqualRange(occs, rg), nil
	}
	d.document.lock.RUnlock()
```

Let's reduce the size of the critical section. You can use `occs` later without extra synchronization instead of `d.document.inner.Occurrences`, since `occs` will refer to a local variable, and there isn't any code modifying the occurrences themselves.

If you don't like the duplication of `RUnlock`, you can introduce an immediately invoked function literal.

2024-07-16 10:45 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index.go
> +	Range := rg.SCIPRange()
Please let's use `range_` or `indexedRange` or `targetRange` or similar instead of `rg`, and please don't capitalize local variable names.

2024-07-16 10:48 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index_test.go
> +	require.Len(t, allOccurrences, 3)
Let's convert this to a property based test instead?

2024-07-16 10:51 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index_test.go
> +	require.Len(t, allOccurrences, 3)
Let's convert this to a concurrent property based test. You may want to use `sourcegraph/conc`, that has nicer APIs than the stdlib. Our tests should be run with `-race`, so this might help catch races should they slip through when modifying the code.

2024-07-17 03:55 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index.go
> +		})
I think the icky-ness is coming from using protobuf generated types in our domain code. Having to pass pointers everywhere because there's a "DontCopyMe" marker Mutex in there.

Maybe it's worth to consider a layer of types that we deserialize the proto messages into, with exhaustruct annotations etc.

For now I've used https://pkg.go.dev/google.golang.org/protobuf@v1.34.2/proto#Clone which is how you're apparently supposed to copy proto messages.

2024-07-17 04:08 UTC, kritzcreek commented
Thanks for the great review again!

I like having the simple non-property-based unit tests here, because they nicely show how to make a faked `MappedIndex` for the syntactic/search-based usages tests.
I don't mind adding some property based tests later on top, but I don't want to spend a bunch of time on writing generators right now.

If that's allright with you, please take another look.

2024-07-17 11:42 UTC, varungandhi-src approved these changes
Since I've been busy with support work, I have not had the time to look at all the unit tests carefully, or look at the moved code.

For the code involving locks, I think we should have at least 1 test exercising that code in parallel with 10-100 goroutines.

Approving to unblock.

2024-07-18 03:51 UTC, kritzcreek reviewed
I tried writing a test like you suggested, but can't get it to fail even after removing all the of the locking calls and adding an artificial thread.Sleep to the translator mock.

Unless I can get the test to fail somewhat regular when I remove the locks it doesn't add any confidence for me.
```go
func TestMappedIndex_ConcurrentIndex(t *testing.T) {
	targetCommit, upload, lsifStore := setupSimpleUpload()
	translator := fakeTranslator(targetCommit, -2, func(_ string, _ shared.Range) bool {
		return false
	}, 250)
	mappedIndex := NewMappedIndexFromTranslator(lsifStore, translator, upload)
	ctx := context.Background()
	mappedDocumentOption, err := mappedIndex.GetDocument(ctx, core.NewRepoRelPathUnchecked("indexRoot/a.go"))
	require.NoError(t, err)
	mappedDocument := mappedDocumentOption.Unwrap()

	for i := 0; i < 100; i++ {
		wg := conc.NewWaitGroup()
		for i := 0; i < 50; i++ {
			wg.Go(func() {
				occurrences, err := mappedDocument.GetOccurrencesAtRange(ctx, shiftSCIPRange(testRange(1), 2))
				require.NoError(t, err)
				require.Len(t, occurrences, 1)
				require.Equal(t, scip.NewRangeUnchecked(occurrences[0].GetRange()).Start.Line, int32(3))
			})
		}
		for i := 0; i < 10; i++ {
			wg.Go(func() {
				allOccurrences, err := mappedDocument.GetOccurrences(ctx)
				require.NoError(t, err)
				require.Len(t, allOccurrences, 3)
			})
		}
		wg.Wait()
	}
}
```

2024-07-18 03:51 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index_test.go
> +			ref("a", 2)))
I looked at the test involving reprolang, but they're not suitable for testing syntactic, because the tests need to make it clear they're matching up ranges from search results with ranges in SCIP indices.
reprolang doesn't give me any tools to be explicit about source ranges. The tests you reference instead use autogold to just generate whatever ranges we ended up parsing.

> I've been saying that we shouldn't need to hand-write large struct literals and do specific tests against with specific counts/structures. That makes both reading and updating test code more time-consuming.

I find the use of auto-gold makes reading test-code very time consuming, as it machine-writes large struct literals in the middle of the code I'm reading.

2024-07-18 03:51 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index_test.go
> +func TestMappedIndex_GetDocumentNoTranslation(t *testing.T) {
But they're in the same package as all the other tests. This naming conventation seems to be everywhere I look? (without the `_`, but eg. tests in `service_hover_test.go` all start with `TestHover`)

2024-07-18 03:51 UTC, kritzcreek commented on internal/codeintel/codenav/mapped_index_test.go
> +	occurrences, err := mappedDocument.GetOccurrencesAtRange(ctx, shiftSCIPRange(testRange(1), 2))
Yeah, it was confusing to me as well initially. The issue is that the `gitTreeTranslator` passed into the service uses the target commit as its "TranslationBase", which means the direction `index -> target` sets the reverse flag to true.

Hopefully this gets more straightforward when we remove TranslationBase from GitTreeTranslator and just explicitly request `from` and `to` commits for every operation.

I can add a comment for now.

2024-07-18 03:52 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index_test.go
> +			ref("a", 2)))
Let's discuss this later, it's not a blocking concern.

2024-07-18 03:53 UTC, varungandhi-src commented on internal/codeintel/codenav/mapped_index_test.go
> +func TestMappedIndex_GetDocumentNoTranslation(t *testing.T) {
Sure, it was a minor suggestion, it's fine to leave it in.

2024-07-18 03:54 UTC, merged