Syntactic indexing non local refs java
sourcegraph/sourcegraph pull request #63822
Opened 2024-07-15 09:49 UTC by keynmol

This PR adds non-local references support to Java (and more generally to our locals handling code).

The main idea is to cherrypick nodes that _can_ contain global or ambiguous (see below) references, handle them first, and then mark everything else as locals.

- Pure Global references are formed from types of definitions that _can't_ be locals in our code. Currently it's only methods and some known 
- 

## Test plan

- Eyeballing new snapshots

## Changelog

2024-07-15 09:50 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +    Either,
This needs a better name. `Resolved`?

2024-07-15 09:51 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +    non_local_references_at_offsets: HashSet<usize>,
TODO: may be this can be folded into `skip_occurrences_at_offsets`

2024-07-15 09:52 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                .to_string(), //format_symbol(def_id.as_local_symbol()),
TODO: format as global symbol

2024-07-15 10:28 UTC, kritzcreek requested changes
Just a few drive-by comments

2024-07-15 10:28 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +    Either,
How about `Option<ReferenceKind>`?

2024-07-15 10:28 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +            debug_assert!(true, "Unknown reference type: {str}");
```suggestion
            debug_assert!(false, "Unknown reference type: {str}");
```

2024-07-15 10:28 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                    kind: ReferenceKind::Local,
This is a tiny bit sus... Could this be referencing a non-local definition at some point?

2024-07-15 10:28 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                .to_string(), //format_symbol(def_id.as_local_symbol()),
Any plans for emitting an "appropriate" descriptor here? Class vs Value vs Macro vs ...

2024-07-15 10:28 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                let skip = self
booleans are not not hard. Let's try to reduce the nesting here with some early continues (once the logic here is complete)

2024-07-15 10:29 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                .to_string(), //format_symbol(def_id.as_local_symbol()),
I was thinking about it – in a lot of cases we just won't be able to because in some grammars it's just (identifier).

But I will extend this with at least `reference.global.method` or something, to emit the proper kind where we can

2024-07-15 10:31 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                    kind: ReferenceKind::Local,
I think I had this change before introducing `Either` - I think it's a more reasonable default (or, as you suggested, None)

2024-07-16 12:02 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                let skip = self
I've changed the structure to reduce nesting

2024-07-16 12:18 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +    non_local_references_at_offsets: HashSet<usize>,
It can't, they have different purposes and I'd rather not overload it.

2024-07-16 13:08 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                .to_string(), //format_symbol(def_id.as_local_symbol()),
I've implemented it here: https://github.com/sourcegraph/sourcegraph/pull/63822/commits/9c30a6ba295ae9bf6fc21b8e8f1029b27b75ecc9

2024-07-16 13:09 UTC, keynmol commented on docker-images/syntax-highlighter/crates/scip-syntax/benches/symbol_parsing.rs
> +        scip_strict::Symbol::parse(symbol).unwrap();
Clippy recommended this so it must be right, right?

2024-07-18 02:32 UTC, kritzcreek requested changes

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/lib.rs
> +    options: &LocalResolutionOptions,
As `LocalResolutionOptions` are `Copy` I wouldn't bother with using a reference anywhere.

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +enum ReferenceKind {
`Kind` is very generic, it could just as well describe the Descriptor. How about `Visibility`?

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +
When I said we should avoid the duplicate entries in the scope tree, I didn't mean "we should avoid printing them" I meant we should avoid inserting them 😄

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                    }
What about the `Nothing` case here? No visibility modifier can still produce a local reference

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +                    // order of rules in the queries
If we can't rely on the order to decide which reference to pick we either need to come up with a precedence rule to disambiguate, or we'll have to use query properties to specify visibility and descriptor and rely on tree-sitter's match de-duplication.

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +            .with_context(|| anyhow!("Failed to resolve interned name {:?}", reference.name))
```suggestion
```

I wouldn't bother with the extra error message. `reference.name` is going to just be a hash that won't help with debugging. It's fine to just unwrap here.

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +        });
I'd prefer to use `scip_strict` here (means you'd need to move it from the `scip-syntax` crate into `syntax-analysis`).

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
> +            symbol: format_symbol(def_id.as_local_symbol()),
`scip_strict` this as well while we're at it.

2024-07-18 02:32 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_scopes.snap
>        ref chars (10, 22)-(10, 27)
Huh, this one's weird. Overlapping def and ref might be a bug in scope tree construction that existed before this PR.

2024-07-23 15:23 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap
> +//       ^^^^^^^^^ reference scip-syntax `java.lang`/
Frankly at this point I'm not sure how to fix it without extra logic

2024-07-23 15:54 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap
> +//       ^^^^^^^^^ reference scip-syntax `java.lang`/
I've attempted to identify overlapping nodes in the simplest possible way, and while this does help, it breaks Perl:

```
   11    11 │           ref @$self (8, 13)-(8, 19)
   12       │-          ref $self (8, 14)-(8, 19)
```

```perl
    7     7 │       if (@_ == 2) {
    8     8 │           my $self = shift;
    9     9 │ //           ^^^^^ definition local 2
   10    10 │           push(@$self, shift);
   11       │-//              ^^^^^ reference local 2
```

In the queries we extract both `$self` and `@$self` as references, but `@$self` comes first and contains within it `$self`. Problem is - `@$self` cannot be resolved to a local definition.

2024-07-24 01:07 UTC, kritzcreek commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap
> +//       ^^^^^^^^^ reference scip-syntax `java.lang`/
Not the GOAT when it comes to Perl, but I think the reference and definition we should _actually_ be targeting there is `self`. See https://perldoc.perl.org/perlintro#Arrays where you can declare an array as `@animals` and refer to it via `$animals[0]`.

(Not saying go fix the Perl locals, just don't let them stop you from implementing a simpler solution if you've found one)

2024-07-24 06:52 UTC, keynmol commented on docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap
> +//       ^^^^^^^^^ reference scip-syntax `java.lang`/
The simple solution for choosing the longest reference node and ignore all matches contained within:

```rust
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs b/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
index ba64c9362aa..4c57e85b56f 100644
--- a/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
+++ b/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
@@ -587,6 +587,7 @@ impl<'a> LocalResolver<'a> {
         let mut definitions: Vec<DefCapture> = vec![];
         let mut references: Vec<RefCapture<'a>> = vec![];
         let mut skip_references_at_offsets: HashSet<usize> = HashSet::new();
+        let mut min_reference_start: usize = 0;
 
         for match_ in cursor.matches(&config.query, tree.root_node(), source_bytes) {
             let properties = config.query.property_settings(match_.pattern_index);
@@ -622,7 +623,11 @@ impl<'a> LocalResolver<'a> {
                 } else if capture_name.eq_ignore_ascii_case("reference") {
                     let offset = capture.node.start_byte();
 
-                    if skip_references_at_offsets.contains(&offset) {
+                    if offset < min_reference_start {
+                        continue;
+                    }
+
+                    if self.skip_occurrences_at_offsets.contains(&offset) {
                         continue;
                     }
 
@@ -642,11 +647,13 @@ impl<'a> LocalResolver<'a> {
                         other => other,
                     };
 
-                    if self.skip_occurrences_at_offsets.contains(&offset) {
-                        continue;
-                    }
+                    eprintln!(
+                        "{:?} {offset} {min_reference_start} {:?}",
+                        capture.node.utf8_text(source_bytes),
+                        capture.node.kind()
+                    );
 
-                    skip_references_at_offsets.insert(offset);
+                    min_reference_start = capture.node.end_byte();
 
                     let descriptor = match visibility {
                         Some(Visibility::Global) => kind_property
```

This fixes Java imports and is somewhat generic.

re:Perl - indeed the reference should be to `self`, but our current grammar does a very crude selection of entire `(array)` node. I'm exploring switching back to upstream or syncing at least part of the changes into our fork to make this possible

2024-07-25 10:33 UTC, kritzcreek approved these changes
I think this is in good enough shape to merge. The extra reference to `lang.` is not going to matter, because search is going to give us identifiers on word boundaries anyway. (and having a few false positives is not the end of the world, it's certainly better than false negatives)

I'll open an issue for some follow-up scip_strict usage, and any simplification I think we could make in the future.

If there are other issues we know of, please open issues for those as well, and we can look at them independently of this PR.

2024-07-25 10:42 UTC, keynmol commented
For future reference, here's the latest attempt to prefer a longer reference in case there are referenced subparts contained entirely within it.

It causes issues in perl because we cast a wide net when marking identifiers as reveferences in the grammar, producing `@$self` and `$self` references from same occurrence of `@$self`

I attempted to update the grammar we have (https://github.com/sourcegraph/tree-sitter-perl/pull/4) but it causes other issues because of how it's structured.

```diff rust
diff --git a/docker-images/syntax-highlighter/Cargo.lock b/docker-images/syntax-highlighter/Cargo.lock
index 7f33669d4d5..985bc58e8ae 100644
--- a/docker-images/syntax-highlighter/Cargo.lock
+++ b/docker-images/syntax-highlighter/Cargo.lock
@@ -2633,7 +2633,7 @@ dependencies = [
 [[package]]
 name = "tree-sitter-perl"
 version = "0.0.1"
-source = "git+https://github.com/sourcegraph/tree-sitter-perl?rev=e1b4844afd17b7dc019a436b1ac890568d79a1f2#e1b4844afd17b7dc019a436b1ac890568d79a1f2"
+source = "git+https://github.com/sourcegraph/tree-sitter-perl?rev=25473ee75c2fc0757b019d5be54cba0cbe412437#25473ee75c2fc0757b019d5be54cba0cbe412437"
 dependencies = [
  "cc",
  "tree-sitter",
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/queries/java/scip-locals.scm b/docker-images/syntax-highlighter/crates/syntax-analysis/queries/java/scip-locals.scm
index fcf8e3c67d8..1a91b868483 100644
--- a/docker-images/syntax-highlighter/crates/syntax-analysis/queries/java/scip-locals.scm
+++ b/docker-images/syntax-highlighter/crates/syntax-analysis/queries/java/scip-locals.scm
@@ -91,18 +91,28 @@
 
 ; REFERENCES
 
-
+; NOTE: commented out because current implementation produces overlapping
+; references (in the example below, java.util and util will be produced)
 ; import java.util.HashSet
 ;        ^^^^^^^^^ namespace
 ;                  ^^^^^^^ type (could also be a constant, but type is more common)
+; (import_declaration
+;   (scoped_identifier
+;     scope: ((_) @reference (#set! "kind" "global.namespace"))
+;     ))
+
+; (import_declaration
+;   (scoped_identifier
+;     name: (_) @reference (#set! "kind" "global.type")
+;   ))
 (import_declaration
   (scoped_identifier
-    scope: ((_) @reference (#set! "kind" "global.namespace"))
+    scope: (_) @occurrence.skip
     ))
 
 (import_declaration
   (scoped_identifier
-    name: (_) @reference (#set! "kind" "global.type")
+    name: (_) @occurrence.skip
   ))
 
 (field_access object: (identifier) @reference)
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/queries/perl/scip-locals.scm b/docker-images/syntax-highlighter/crates/syntax-analysis/queries/perl/scip-locals.scm
index 80fd51e2eaf..3d0c04bd8ee 100644
--- a/docker-images/syntax-highlighter/crates/syntax-analysis/queries/perl/scip-locals.scm
+++ b/docker-images/syntax-highlighter/crates/syntax-analysis/queries/perl/scip-locals.scm
@@ -5,11 +5,56 @@
 
 ;; TODO: Add `state` variables once we've updated the grammar. Only
 ;; `our` variables are non-local, so we must not include them here
-(variable_declaration "my" (_) @definition.term)
-(for_statement my_var: (_) @definition.term)
-
-((scalar) @reference (#set! "kind" "local"))
-((array) @reference (#set! "kind" "local"))
-((arraylen) @reference (#set! "kind" "local"))
-((hash) @reference (#set! "kind" "local"))
-((glob) @reference (#set! "kind" "local"))
+(variable_declaration
+  "my"
+  variable: [
+    (scalar (varname) @definition.term)
+    (array (varname) @definition.term)
+    (arraylen (varname) @definition.term)
+    (hash (varname) @definition.term)
+    (glob (varname) @definition.term)
+  ]
+                      ; (_) @definition.term
+)
+
+(variable_declaration
+  "my"
+  variables: ([
+    (scalar ((varname) @definition.term))
+    (array ((varname) @definition.term))
+    (arraylen ((varname) @definition.term))
+    (hash ((varname) @definition.term))
+    (glob ((varname) @definition.term))
+  ])*
+)
+
+(for_statement
+  my_var: [
+    (scalar (varname) @definition.term)
+    (array (varname) @definition.term)
+    (arraylen (varname) @definition.term)
+    (hash (varname) @definition.term)
+    (glob (varname) @definition.term)
+  ]
+)
+
+(scalar
+    ((varname) @reference (#set! "kind" "local"))
+)
+
+(array
+  (varname) @reference (#set! "kind" "local")
+)
+
+(arraylen
+  (varname) @reference (#set! "kind" "local")
+)
+
+(hash
+  (varname) @reference (#set! "kind" "local")
+)
+
+(glob
+  (varname) @reference (#set! "kind" "local")
+)
+
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs b/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
index ba64c9362aa..a5cf70b6e1c 100644
--- a/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
+++ b/docker-images/syntax-highlighter/crates/syntax-analysis/src/locals.rs
@@ -587,6 +587,7 @@ impl<'a> LocalResolver<'a> {
         let mut definitions: Vec<DefCapture> = vec![];
         let mut references: Vec<RefCapture<'a>> = vec![];
         let mut skip_references_at_offsets: HashSet<usize> = HashSet::new();
+        let mut skip_references_until: Option<usize> = None;
 
         for match_ in cursor.matches(&config.query, tree.root_node(), source_bytes) {
             let properties = config.query.property_settings(match_.pattern_index);
@@ -626,6 +627,11 @@ impl<'a> LocalResolver<'a> {
                         continue;
                     }
 
+                    match skip_references_until {
+                        Some(end_offset) if offset < end_offset => continue,
+                        _ => (),
+                    }
+
                     let kind_property = properties
                         .iter()
                         .find(|p| p.key.as_ref() == "kind")
@@ -647,6 +653,7 @@ impl<'a> LocalResolver<'a> {
                     }
 
                     skip_references_at_offsets.insert(offset);
+                    skip_references_until = Some(capture.node.end_byte());
 
                     let descriptor = match visibility {
                         Some(Visibility::Global) => kind_property
@@ -666,6 +673,7 @@ impl<'a> LocalResolver<'a> {
                 } else if capture_name == "occurrence.skip" {
                     let offset = capture.node.start_byte();
                     self.skip_occurrences_at_offsets.insert(offset);
+                    skip_references_until = Some(capture.node.end_byte());
                 } else {
                     debug_assert!(false, "Discarded capture: {capture_name}")
                 }
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap b/docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap
index 924113e1d29..f58a8ac1117 100644
--- a/docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap
+++ b/docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_occurrences.snap
@@ -5,16 +5,8 @@ expression: dumped
   package com.hello;
   
   import java.lang.AutoCloseable;
-//       ^^^^^^^^^ reference scip-syntax `java.lang`/
-//            ^^^^ reference scip-syntax lang.
-//                 ^^^^^^^^^^^^^ reference scip-syntax AutoCloseable#
   import java.util.*;
-//       ^^^^ reference scip-syntax java/
-//            ^^^^ reference scip-syntax util#
   import java.util.stream.*;
-//       ^^^^^^^^^ reference scip-syntax `java.util`/
-//            ^^^^ reference scip-syntax util.
-//                 ^^^^^^ reference scip-syntax stream#
   
   @Deprecated
 // ^^^^^^^^^^ reference scip-syntax Deprecated#
diff --git a/docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_scopes.snap b/docker-images/syntax-highlighter/crates/syntax-analysis/src/snapshots/syntax_analysis__locals__test__java_scopes.sn [...]

2024-07-25 10:44 UTC, merged