fix(cody): remove client check for context filters
sourcegraph/sourcegraph pull request #63855
Opened 2024-07-16 14:26 UTC by olafurpg

Previously, Sourcegraph Enterprise instances with context filters enabled rejected requests from all unknown clients out of concern that they might not respect context filters. This behavior makes it incredibly impractical to release now agent-based clients (CLI, Eclipse, Visual Studio, Neovim, ..) that do respect context filters out of the box thanks to the reused logic in the Cody agent.

This logic suffers from both false positives and false negatives:

- False negatives: upcoming Cody clients (CLI, Eclipse, Visual Studio) already support context filters out of the box thanks to using the Cody agent but they can't send requests unless we add a special case to them.
- False positive: a malicious client can always fake that it's "jetbrains" with a valid version number even if the client doesn't respect context filters. This gives a false sense of security because it doesn't prevent malicious traffic from bypassing context filters.

Now, with this change, Sourcegraph Enterprise instances only reject requests from old versions of Cody clients that are known to not support context filters. This ensures we never have false positives or false negatives.

## Test plan
See updated test case which accepts a request from an unknown "sublime" client.

## Changelog

2024-07-17 09:55 UTC, willdollman approved these changes

2024-07-17 09:55 UTC, willdollman commented on cmd/frontend/internal/httpapi/completions/handler.go
> +		// 2024.
```suggestion
		// By default, allow requests from any client. We only want to reject
		// requests from older client versions that we know definitely don't
		// support context filters.
		// All agent-based clients (JetBrains, Eclipse, Visual Studio) support 
		// context filters out of the box since the original support was added 
		// for JetBrains GA in May 2024.
```

Just feel like we don't want to advertise this!

2024-07-17 14:41 UTC, taras-yemets approved these changes

2024-07-17 14:51 UTC, taras-yemets requested changes

2024-07-17 14:51 UTC, taras-yemets commented on cmd/frontend/internal/httpapi/completions/handler_test.go
>  				"client-name": []string{"sublime"},
> we require both clientName and clientVersion params but check the version only for VS Code and JetBrains

This test still should fail based on this requirement ([thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1721203969781859?thread_ts=1721138647.380249&cid=C05AGQYD528))

2024-07-17 14:51 UTC, taras-yemets commented on cmd/frontend/internal/httpapi/completions/handler.go
> +		return nil
We need to check if the client version is provided. If it's not, the function should still return an error ([thread](https://sourcegraph.slack.com/archives/C05AGQYD528/p1721203969781859?thread_ts=1721138647.380249&cid=C05AGQYD528)).

2024-07-18 11:27 UTC, olafurpg commented on cmd/frontend/internal/httpapi/completions/handler.go
> +		return nil
Good catch. I've updated the logic to accept an empty version for web only, and require semver for other clients. Added relevant tests

2024-07-18 11:27 UTC, olafurpg commented on cmd/frontend/internal/httpapi/completions/handler_test.go
>  				"client-name": []string{"sublime"},
Good catch. Fixed.

2024-07-18 11:36 UTC, olafurpg commented
Looks like the meat of this PR got merged via https://github.com/sourcegraph/sourcegraph/commit/277648821ccf929574b910ac027b1dfcf1235bf2 This PR now only includes changes to address the review comments

2024-07-18 11:37 UTC, taras-yemets commented on cmd/frontend/internal/httpapi/completions/handler.go
> +		cvc = clientVersionConstraint{client: clientName, constraint: ">= 0.0.0"}
We should also consider the value of the `cody-context-filters-clients-test-mode` feature flag (refer to the logic a few lines above). Pre-release versions might not satisfy the ">= 0.0.0" condition. I'm not completely sure about this, so it's worth double-checking.

2024-07-18 11:37 UTC, taras-yemets approved these changes

2024-07-18 11:41 UTC, taras-yemets commented
> Looks like the meat of this PR got merged via https://github.com/sourcegraph/sourcegraph/commit/277648821ccf929574b910ac027b1dfcf1235bf2 This PR now only includes changes to address the review comments

@olafurpg, The referenced PR only removed the feature flag that gated the Cody context filters usage before client support was in place. Without this flag enabled, admins would receive an error when trying to define `"cody.contextFilters"` in the site config.

Your PR is necessary to allow support for clients other than `vscode`, `jetbrains`, and `web` clients.

2024-07-18 11:44 UTC, merged