[Svelte]: UI Updates for Perforce Depots and Git Repos
sourcegraph/sourcegraph pull request #64014
Opened 2024-07-23 20:09 UTC by jasonhawkharris

## UI Updates for Perforce Depots and Git Repos

This PR introduces changes to the UI to differentiate between Perforce Depots and Git repositories. Below are the key changes included in this commit:

### 1. Dynamic Top-Level Navigation

**For Perforce Depots:**

![Screenshot 2024-07-31 at 10 10 37 AM](https://github.com/user-attachments/assets/2d261b51-f8fa-4599-acae-3520d38996f3)

**For Git Repos:**

![Screenshot 2024-07-31 at 10 10 14 AM](https://github.com/user-attachments/assets/0f9ee3f7-918a-42d8-908f-04593ed52ebd)

### 2. Tabs on Revision Picker

**For Perforce Depots:**

Since we only need one tab for changelists, no tabs are shown.

![Screenshot 2024-07-31 at 10 20 24 AM](https://github.com/user-attachments/assets/f1006d56-67aa-41ab-a13b-905e157cb283)

**For Git Repos:**

We have tabs for Branches, Tags, and Commits.

![Screenshot 2024-07-31 at 10 23 02 AM](https://github.com/user-attachments/assets/38907d51-0407-4cd7-ad4c-1c5967dfddf3)

### 3. Commits/Changelists Page

**For Git Repos:**

The page displays Git commits.

![Screenshot 2024-07-31 at 10 26 23 AM](https://github.com/user-attachments/assets/85245d1d-708f-4d51-9da3-0425c3f085d0)

**For Perforce Depots:**

The page displays Perforce changelists.

![Screenshot 2024-07-31 at 10 26 39 AM](https://github.com/user-attachments/assets/2f6f16aa-d498-4763-949d-d1a13f9a26ac)

### 4. Vocabulary Adjustments

- We display either Git commit SHAs or Changelist IDs based on the project type.
- For authorship, we use "submitted by" for Perforce and "committed by" for Git.
- We refer to "Commits" for Git projects and "Changelists" for Perforce projects.

**Examples:**

- **For Git Commits:**

![Screenshot 2024-07-31 at 10 37 08 AM](https://github.com/user-attachments/assets/ac15b0b3-4c85-4a4c-80c0-ec9384b72eca)

- **For Perforce Changelists:**

![Screenshot 2024-07-31 at 10 37 35 AM](https://github.com/user-attachments/assets/4230cb32-5285-4141-b374-f3ea23042e1d)

### 5. URL Mapping

URLs are now structured differently based on the project type:

- **Commits Page:**
  - Git: `/[repo-name]/-/commits`
  - Perforce: `/[repo-name]/-/changelists`
  
- **Individual Item Page:**
  - Git: `/[repo-name]/-/commit/[commit-hash]`
  - Perforce: `/[depot-name]/-/changelist/[changelist-ID]`

When viewing a specific commit or changelist:
- **Git:** `/[repo-name]@[git-commit-hash]`
- **Perforce:** `/[repo-name]@changelist/[changelist-id]`

_NOTE: The value displayed in the search field will also change accordingly._

### What is left to be done?
**On repo search results, when searching a revision, we still show the git commit SHA instead of the changelist ID for perforce depots:**
![Screenshot 2024-07-31 at 10 59 12 AM](https://github.com/user-attachments/assets/38bc2a3e-be8b-4585-9fe0-776149a7f230)

I plan to make a follow-up issue for this and begin work on it immediately. It's a little trickier than the other changes because in the RepositoryMatch type, there is no value that can help us determine whether a project is a depot or a repo. We need to find another way to fetch that data. 

### Request for reviewers: 
1. Please try to break these new features and tell me what you find. I stumbled on a number of little gotchas while working on this, and I'm sure I've missed some. 

## Test plan

- Manual/Visual testing
- Adjust e2e and integration tests to obtain a passing CI
- Test directly visiting a URL versus getting there via click

2024-07-31 18:19 UTC, bahrmichael requested changes
The changes look good overall. One request that I have is to use `isPerforce` everywhere instead of `isP4`.

I have not done any exploratory testing (time-constrained), but would be happy to take a look at it together.

2024-07-31 18:19 UTC, bahrmichael commented on client/web-sveltekit/src/lib/TabsHeader.svelte
> +    export let isP4: boolean
What does `P4` stand for? If it's perforce related, I'd suggest `isPerforce` instead.

2024-07-31 18:19 UTC, bahrmichael commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
>                      seeAllItemsURL={`${repoURL}/-/commits`}
Should the `seeAllItemsUrl` be perforce-aware as well?

2024-07-31 18:19 UTC, bahrmichael commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
> +                            {/if}
If you want to shorten this, I _think_ it could be written as `<Badge variant="link">{value.perforceChangelist?.cid ?? value.abbreviatedOID}</Badge>`. I'll leave it up to your personal preference.

2024-07-31 18:19 UTC, bahrmichael commented on client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
> +                                {/if}
(non-blocking) Would the UI also work if we don't add `Changelist ID:` in front of perforce changesets? Could the user infer from the context that this is the id of a changelist and not a commit?

2024-07-31 18:19 UTC, bahrmichael commented on client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.ts
> +    const commit = 'node' in result?.data ? result.data?.node?.changelist.commit : result.data?.repository?.commit
If you want to shorten this, you could write it as `result.data?.node?.changelist.commit ?? result.data?.repository?.commit`.

2024-07-31 18:33 UTC, jasonhawkharris commented on client/web-sveltekit/src/lib/TabsHeader.svelte
> +    export let isP4: boolean
P4 is the CLI tool for perforce. I thought it was universally recognized enough, but now that you mention it, it's probably not. I'll change it.

2024-07-31 18:33 UTC, jasonhawkharris commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
>                      seeAllItemsURL={`${repoURL}/-/commits`}
ooooooo good catch. See this is why I love reviews.

2024-07-31 18:35 UTC, jasonhawkharris commented on client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
> +                                {/if}
Most likely, yes, they could. I was trying to preserve the design parameters that currently exist in the React app, instead of designing it myself. Maybe @taiyab has some thoughts on this? Taiyab, you can see what were talking about in the screen shot for the changelist page in the PR message.

I think the whole design could be tinkered with, however, this PR is more about making sure Perforce support is, at the very least, present.

2024-07-31 18:44 UTC, camdencheek commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
> +                        return isP4 && commit.perforceChangelist
If `isP4` is true, wouldn't `commit.perforceChangelist` always exist? Or are not all commits changelists?

2024-07-31 18:44 UTC, camdencheek commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
> +                            {/if}
nit: we can put the `if` branch inside the `Badge` tag

2024-07-31 18:44 UTC, camdencheek commented on client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
> +                                        <a href={commit.perforceChangelist?.canonicalURL} title="View commit"
should this read "view changelist"?

2024-07-31 18:44 UTC, camdencheek commented on client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/-/commits/[...path]/+page.svelte
> +                            >
nit: can we clean up the formatting in this file? Prettier won't add whitespace between tags because it's a semantic change, but it doesn't make a difference in this case

2024-07-31 18:44 UTC, camdencheek commented on client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.svelte
> +                    {#if isPerforce}
We can move this branch inside the `<li>`

2024-07-31 18:44 UTC, camdencheek commented on client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.ts
Q: given the amount of branching in this page, does it make sense to just make a separate page for showing a changelist? I don't have any strong opinion here, just curious what you think

2024-07-31 18:52 UTC, camdencheek commented
![screenshot-2024-07-31_12-52-03@2x](https://github.com/user-attachments/assets/f0c6514a-0808-4991-9b46-e46f25109905)

I think we should adjust the flex behavior here so the changelist id is not truncated

2024-07-31 18:54 UTC, camdencheek commented
![screenshot-2024-07-31_12-53-40@2x](https://github.com/user-attachments/assets/a88b53d1-95cc-40ac-85da-b3b91c12eac2)
![screenshot-2024-07-31_12-53-53@2x](https://github.com/user-attachments/assets/d6dca25c-ecc2-4846-bd78-36577fa96d0b)

Clicking a changelist title causes an error

2024-07-31 18:56 UTC, camdencheek commented
![screenshot-2024-07-31_12-54-59@2x](https://github.com/user-attachments/assets/efbfa655-1b64-4166-891c-6c4344441270)
![screenshot-2024-07-31_12-55-28@2x](https://github.com/user-attachments/assets/b2f8c646-3e61-4f30-b694-c7b70686a3c9)

Clicking a file name in the changelist view links to a commit hash, not a changelist

2024-07-31 19:29 UTC, jasonhawkharris commented on client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.ts
I don't know that this would have any real advantage, personally. Expecially after simplifying according to your previous comment. My logic was just messy.

2024-07-31 19:30 UTC, jasonhawkharris commented
> Clicking a changelist title causes an error. This error also happens when clicking a commit in the history panel.
Thank you @camdencheek this is the kind of stuff I'm looking for!

2024-07-31 19:45 UTC, jasonhawkharris commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
> +                        return isP4 && commit.perforceChangelist
ListboxOption, which is the type here, does not allow `value` to be undefined or null. Adding the extra check here satisfies a type restriction that was happening when I tried to return a value of `{value: commit.perforceChangelist?.cid, label: commit.id}`

2024-07-31 19:45 UTC, camdencheek commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
> +                        return isP4 && commit.perforceChangelist
ah, gotcha, so it's just type appeasement

2024-07-31 19:46 UTC, jasonhawkharris commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
> +                        return isP4 && commit.perforceChangelist
To clarify, `label` can be null, but `value` cannot, and I don't think that should change, so I wrote it this way.

2024-07-31 20:02 UTC, peterguy commented
Loving these changes (and the presentation - the detail in the description is phenomenal).

Had to hunt for awhile (even the Blame panel uses Perforce lingo!), but I found another place we can fix.

The Permalink button has Git-centric hover text and creates a URL with the Git commit hash.

<img width="1349" alt="Screenshot 2024-07-31 at 12 57 53" src="https://github.com/user-attachments/assets/553690da-ab9e-4fac-ae29-14267daf5c1d">

2024-07-31 20:12 UTC, peterguy commented
> Clicking a changelist title causes an error. This error also happens when clicking a commit in the history panel.

Also, clicking the changelist in the Blame panel. It opened a URL with the Git commit hash.

When I changed that URL to use the changelist ID, it works.

<img width="638" alt="Screenshot 2024-07-31 at 13 04 58" src="https://github.com/user-attachments/assets/7db8cd1e-44d4-4495-abd8-120b3c3cea23">

<img width="982" alt="Screenshot 2024-07-31 at 13 05 14" src="https://github.com/user-attachments/assets/7e143bb5-c111-4b97-bfda-6b9d3b414c90">

<img width="757" alt="Screenshot 2024-07-31 at 13 05 46" src="https://github.com/user-attachments/assets/92b80d39-a9fc-40b0-9000-4096aeedacbe">

2024-08-01 05:36 UTC, fkling commented on client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
> +    $: isPerforceDepot = data.resolvedRepository.externalRepository.serviceType === 'perforce'
Instead of repeating this comparison here and in other pages, I'd make the layout data loader return a `isPerforce` flag, since this a general property of the respository.
We do the same for other information, like display name or the default branch name, so that this information doesn't have to be recomputed in multiple places.

```js
// In src/routes/[...repo=reporev]/+layout.ts

return {
    // ...
    isPerforceDepot: data.resolvedRepository.externalRepository.serviceType === 'perforce'
    // ...
}
```

Then layouts and pages can just access `data.isPerforceDepot`.

We should also explore abstracting the perforce checks completely. For example, instead of having the layout conditionally change the navigation entries, the navigation entries could be returned by the loader too (and the loader creates the correct navigation entries).

An example of this is in `src/routes/+layout.ts` where we create entries for the global navigation menu depending on whether or not we are in dotcom mode, and other conditions.

2024-08-01 05:36 UTC, fkling commented on client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.svelte
I would not call this parameter `path`. It doesn't seem to have anything to do with what I would normally consider a path. And `commit_or_changelist` seems overly verbose (and long) even though I appreciate that it contains the possible values for the parameter.

Maybe something like `[changekind=changekind]` instead. Naming is hard, maybe others have better suggestions.

2024-08-01 13:42 UTC, jasonhawkharris commented on client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
> +    $: isPerforceDepot = data.resolvedRepository.externalRepository.serviceType === 'perforce'
Yeah. This makes a lot of sense. I am still getting used to these SvelteKit conventions. Good call.

2024-08-01 14:04 UTC, jasonhawkharris commented on client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
> +    $: isPerforceDepot = data.resolvedRepository.externalRepository.serviceType === 'perforce'
I've added isPerforceDepot to the page loader and changed the references accordingly. However, I'm going to hold off on doing the second thing you mentioned:

> We should also explore abstracting the perforce checks completely. For example, instead of having the layout conditionally change the navigation entries, the navigation entries could be returned by the loader too (and the loader creates the correct navigation entries).

So I can concentrate on finishing these features out for the August 7th release. Marking as resolved.

2024-08-01 15:04 UTC, jasonhawkharris commented on client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.svelte
Will include this in my follow-up after I get the MVP out.

2024-08-02 23:35 UTC, jasonhawkharris commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
>                      seeAllItemsURL={`${repoURL}/-/commits`}
Follow up work next week will include this. I'm leaving it out of this PR.

2024-08-03 02:45 UTC, camdencheek reviewed
Looking more closely at this, I do think we should consider making separate pages for `/-/changelist` and `/-/changelists`. Basically, I think this is a scenario where the deduplication actually makes us more fragile. But that can be saved for a followup and does not need to block this PR. 

I pushed a few changes to re-genericize some components, make some things more data-driven, and to fix a few errors. I think I fixed up the remaining hard errors so now the worst you should see is getting linked to a commit when you should really be linked to a changelist. I also left a few TODOs in the code that we can follow up on next week.

2024-08-03 02:45 UTC, camdencheek commented on client/web-sveltekit/src/lib/TabsHeader.svelte
> -    $: tabs = isPerforceDepot ? removeGitTabs() : tabs
@jasonhawkharris I walked back this change because a generic component like `TabsHeader` should never know anything about perforce

2024-08-03 02:45 UTC, camdencheek commented on client/web-sveltekit/src/lib/repo/RepositoryRevPicker.svelte
>                      seeAllItemsURL={`${repoURL}/-/commits`}
I walked this change back to point to `/-/commits` because there is no `/-/changelists` yet, so this link errored

2024-08-03 02:45 UTC, camdencheek commented on client/web-sveltekit/src/routes/[...repo=reporev]/+layout.svelte
> +                    path: '/-/commits',
`/-/changelists` doesn't yet exist, but the commits page is currently patched to show perforce-specific language

2024-08-03 02:45 UTC, camdencheek commented on client/web-sveltekit/src/routes/[...repo=reporev]/-/[path=commit_or_changelist]/[...revspec]/+page.ts
> +        if (params.path === 'changelist') {
Previously, we were checking if the repo was a perforce repo here. That's problematic because many links still direct to a commit page, but a commit hash is not a valid perforce changelist ID. Instead, this modifies the logic so that if we go to `/-/changelist`, we look up a changelist, otherwise we look up a commit.

2024-08-03 02:45 UTC, camdencheek commented on client/web-sveltekit/src/lib/repo/RepositoryRevPickerItem.svelte
> -        }
![screenshot-2024-08-02_20-20-24@2x](https://github.com/user-attachments/assets/f794b00b-1ac8-488d-bb64-7964426c02f6)

This broke overflow for long branch names

2024-08-03 02:45 UTC, camdencheek approved these changes

2024-08-03 02:45 UTC, camdencheek commented on client/web-sveltekit/src/lib/repo/RepositoryRevPickerItem.svelte
> -        }
Fixed in https://github.com/sourcegraph/sourcegraph/pull/64014/commits/0d917d1072da8b6002b852d49429198bb9578b95

2024-08-03 02:47 UTC, merged

2024-08-05 15:01 UTC, jasonhawkharris commented on client/web-sveltekit/src/lib/TabsHeader.svelte
> -    $: tabs = isPerforceDepot ? removeGitTabs() : tabs
Yup. That makes total sense.