Styling updates to tabs, explore panel, action buttons, and code font-size
sourcegraph/sourcegraph pull request #64080
Opened 2024-07-25 12:52 UTC by taiyab

## Context

This started out as just fixing tab colors, but later evolved into making a bunch of styling updates throughout.

Requires careful attention to the global changes: monospace/code font-sizes (this needs to be thoroughly reviewed wherever we display code), but also all the smaller, local changes.

| Before    | After |
| -------- | ------- |
| ![CleanShot 2024-07-25 at 13 48 42@2x](https://github.com/user-attachments/assets/b61ee462-2d3d-42de-8cf0-7bb4e408af72)  
![CleanShot 2024-07-25 at 13 49 38@2x](https://github.com/user-attachments/assets/cc005023-c387-4093-866c-5f0333679660)
| ![CleanShot 2024-07-25 at 13 47 16@2x](https://github.com/user-attachments/assets/29dff29e-da94-496e-a173-7f3624c4d22c)   
![CleanShot 2024-07-25 at 13 51 09@2x](https://github.com/user-attachments/assets/9cd6d175-6b0e-49f3-b9c2-00753855f23c)
 |

## Test plan
Manually tested locally for visual changes.

2024-07-29 16:23 UTC, camdencheek requested changes

2024-07-29 16:23 UTC, camdencheek commented on client/web-sveltekit/src/lib/TabsHeader.svelte
> +        --icon-color: var(--icon-color);
This changes it to be effectively a no-op, so we should just remove the line if that's intentional

2024-07-29 16:23 UTC, camdencheek commented on client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
> -        color: var(--text-muted);
These are departures from the designs, right? What's the process for reconciling these?

2024-07-29 16:23 UTC, camdencheek commented on client/web-sveltekit/src/lib/repo/Permalink.svelte
> +        --icon-color: var(--icon-color);
This is a no-op

2024-07-29 16:23 UTC, camdencheek commented on client/web-sveltekit/src/routes/[...repo=reporev]/(validrev)/(code)/-/blob/[...path]/OpenInCodeHostAction.svelte
> +        --icon-color: var(--icon-color);
Another no-op

2024-07-29 16:23 UTC, camdencheek commented on client/web-sveltekit/src/routes/svelte-overrides.scss
> -    --font-size-tiny: 0.8125rem;
Looks like there are a couple of spots where `--font-size-tiny` is still used

2024-08-01 15:11 UTC, taiyab commented on client/web-sveltekit/src/lib/codenav/ExplorePanel.svelte
> -        color: var(--text-muted);
Decided to revert the change here instead and make sure the icon color is correct.

2024-08-01 15:11 UTC, taiyab commented on client/web-sveltekit/src/routes/svelte-overrides.scss
> -    --font-size-tiny: 0.8125rem;
Should be cleared now.

2024-08-01 15:44 UTC, closed without merging