chore: Update main occurrence extraction code to allow for symbol-based matching
sourcegraph/sourcegraph pull request #64082
Opened 2024-07-25 13:19 UTC by varungandhi-src

At the heart of the loop for extracting usages across a Sourcegraph instance
is the `extractLocationsFromPosition` function, which extracts source ranges
from a single SCIP Document. Since we want to perform matching based on
symbol names, and also return symbol names for each associated source range,
this function needs to be updated to:
1. Be able to take a symbol name for doing lookups. This is done using the new
    `FindUsagesKey` type which allows two forms - position-based and symbol-based.
2. Be able to return symbol names associated with every source range. This is
    done by creating a new `UsageBuilder` type which somewhat subsumes
    the `Location` type. We avoid repeating the same 'UploadID' and 'Path' fields
    eagerly for clarity; that will be handled by callers in the future when they
    mix `UsageBuilder` values across different Documents (by first calling `build`).

So I've introduced a new function `extractRelatedUsagesAndSymbolNames` which
does the above, and `extractLocationsFromPosition` delegates to that. In the future,
`extractLocationsFromPosition` will be removed.

TODO: Remove unused helper functions and types.

## Test plan

Covered by existing tests. I will add more tests once we can pass in a `FindUsagesKey`
with a symbol-based `Matcher` from some other functions higher up in the call chain.

2024-07-25 13:19 UTC, varungandhi-src commented on internal/codeintel/codenav/shared/types.go
> +
TODO: Remove this

2024-07-25 13:20 UTC, varungandhi-src commented on internal/codeintel/codenav/shared/types.go
> +}
TODO: Remove these for now.

2024-07-25 13:24 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +func (key *FindUsagesKey) IdentifyMatchingOccurrences(allOccurrences []*scip.Occurrence) (out []*scip.Occurrence, strategy MatchStrategy) {
IDK if this is worth adding a property-based test for? It doesn't seem that complicated logic-wise...

2024-07-26 05:45 UTC, kritzcreek requested changes
Thanks for the clear documentation and factoring. I added a few comments.

2024-07-26 05:45 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
> +		// not be targetable by code navigation. This will require a DB migration.
I'm generally in favor of enforcing the SCIP specification more strictly. I don't know if I'd single out occurrences with an empty string, though. I think we should drop any occurrence we can't parse as a valid symbol name.

I'd want to be able to return this as an error to the user (so they could fix their indexer), but because the upload process is asynchronous that would be tricky. Maybe we could _also_ run the check in `src-cli` (with some flagging logic to avoid wasted computation in CI)

2024-07-26 05:45 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +		return scip.NewRangeUnchecked(occ.Range).Compare(range_)
We've got this function in `codenav.FindOccurrencesWithEqualRange`. (Might need to move it up in the package graph)

2024-07-26 05:45 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +		if occ.Symbol == symbolToMatch {
WDYT about checking the canonical symbols here? Or would that be too performance intensive?

2024-07-26 05:45 UTC, kritzcreek commented on internal/codeintel/codenav/shared/types.go
> +	hasEnd      bool
```suggestion
	end         core.Option[scip.Position]
```

2024-07-26 05:48 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +		if occ.Symbol == symbolToMatch {
We should either do canonical comparisons everywhere, or nowhere at all. At the moment, we don't do canonicalized comparisons in the DB, so we shouldn't do that here.

2024-07-26 05:49 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +		if occ.Symbol == symbolToMatch {
Fair enough

2024-07-26 05:52 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +func (key *FindUsagesKey) IdentifyMatchingOccurrences(allOccurrences []*scip.Occurrence) (out []*scip.Occurrence, strategy MatchStrategy) {
I wouldn't go for a PBT here either, but I think having a unit test or two for as a "sanity check" wouldn't hurt.

2024-07-26 07:15 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
> +		// not be targetable by code navigation. This will require a DB migration.
Ack, I'll file a follow-up issue, it's a bit tricky to do this without knowing how often this is hit in practice. It might be the case that our own indexers are emitting bad data.

2024-07-26 07:18 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
> +		// not be targetable by code navigation. This will require a DB migration.
> I'd want to be able to return this as an error to the user (so they could fix their indexer), but because the upload process is asynchronous that would be tricky.

I don't think we should block uploads based on this, it's too harsh compared to stripping out malformed information, but we can log warnings/errors.

2024-07-26 07:40 UTC, varungandhi-src commented on internal/codeintel/codenav/shared/types.go
> +	hasEnd      bool
Changed to use Option

2024-07-26 07:41 UTC, kritzcreek commented on internal/codeintel/codenav/internal/lsifstore/locations_by_position.go
> +		// not be targetable by code navigation. This will require a DB migration.
> I don't think we should block uploads based on this, it's too harsh compared to stripping out malformed information, but we can log warnings/errors.

Yeah definitely don't block uploads, but a user doesn't necessarily have access to the logs. If we're filtering out occurrences I think we'd want to be able to communicate that, so the user can fix their indexer/notify us that ours are buggy.

2024-07-26 08:20 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +func (key *FindUsagesKey) IdentifyMatchingOccurrences(allOccurrences []*scip.Occurrence) (out []*scip.Occurrence, strategy MatchStrategy) {
Added some unit tests

2024-07-26 08:20 UTC, varungandhi-src commented on internal/codeintel/codenav/internal/lsifstore/store.go
> +		return scip.NewRangeUnchecked(occ.Range).Compare(range_)
Moved this function to a different package and changed the code

2024-07-26 08:45 UTC, kritzcreek approved these changes

2024-07-26 10:28 UTC, merged