feat: Add support for precise usagesForSymbol
sourcegraph/sourcegraph pull request #64126
Opened 2024-07-29 13:35 UTC by varungandhi-src

Incomplete - not ready for review

## Test plan

TODO

## Changelog

TODO

2024-07-30 12:34 UTC, varungandhi-src commented on internal/codeintel/codenav/transport/graphql/root_resolver.go
> +			pageInfo: pageInfo,
TODO: Below this, we need to return an empty result instead of saying un-implemented.

2024-07-30 13:58 UTC, kritzcreek requested changes
Thanks, this is looking really good. Do you have plans for how you're going to test the new `PreciseUsages` logic?

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +				log.String("cursorType", string(currentCursor.PreciseCursorType)))
I think we're duplicating this warning between `root_resolver` and here?

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +	ctx, trace, endObservation := s.operations.syntacticUsages.With(ctx, nil, observation.Args{Attrs: []attribute.KeyValue{
Should be the `preciseUsages` operation, and as this doesn't use a structured error you can also pass `err` as the second argument.

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +			switch currentCursor.PreciseCursorType {
This feels like behaviour pretty specific to `PreciseCursorType`, maybe we could define`PreciseCursorType.next() Option[PreciseCursorType]`?

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +			trace.Warn("nextUsages == 0 should imply nextCursor.Phase == \"done\"",
```suggestion
			trace.Warn("len(nextUsages) == 0 should imply nextCursor.Phase == \"done\"",
```

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +			Matcher:      shared.NewSCIPBasedMatcher(args.Range, lookupSymbol),
I'd prefer `Option[string]` for lookupSymbol here. AFAICT at the only place we're pulling it back out we immediately check against the empty string.

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/transport/graphql/root_resolver.go
> +				preciseUsages = preciseUsages[:remainingCount]
Is this going to drop results that won't be in the next page if we don't also modify the cursor? If so I'd prefer just returning more results than requested here.

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
> +	// - Avoid refetching/re-splitting the contents repeatedly for the same file
It looks like `locResolver` has some caching built-in here? Did you check the trace to see if the same file is being fetched multiple times?

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/transport/graphql/root_resolver.go
> +					trace.Warn("expected precise matches for symbol but didn't find any matching blobs",
```suggestion
					trace.Warn("expected precise matches for symbol but didn't find any matching uploads",
```

2024-07-30 13:58 UTC, kritzcreek commented on internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
> +		// TODO: Record if we got the results from Searcher or Zoekt
I checked with Julie and Stefan and we don't have a way of getting these results. There are some metrics recorded in Honeycomb, but nothing for an individual match. (Especially since hybrid search means a given search command can end up hitting both)

2024-07-30 14:02 UTC, varungandhi-src commented on internal/codeintel/codenav/service_new.go
> +				log.String("cursorType", string(currentCursor.PreciseCursorType)))
No, they're two different warnings. This is checking the individual usages in a single call, to the underlying APIs, whereas the caller is checking the net result across different kinds of usages. I'll change the message for clarity.

2024-07-30 14:12 UTC, varungandhi-src commented on internal/codeintel/codenav/service_new.go
> +			switch currentCursor.PreciseCursorType {
The order chosen is somewhat arbitrary, and this logic might need changes once we allow filtering. If we address the `TODO(id: doc-N-traversals)`, the APIs being called above will likely change (instead of calling separate `GetDefs`, `GetRefs` etc., we will pass a bit-set of the usage kinds we want to a more general `GetUsages`), and this logic might be removed anyways. So leaving this as-is for now instead of putting into a method.

2024-07-30 14:34 UTC, varungandhi-src commented on internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
> +	// - Avoid refetching/re-splitting the contents repeatedly for the same file
I read through the code and it doesn't have any caching for the contents, but I'll double-check the trace.

2024-07-30 14:37 UTC, varungandhi-src commented on internal/codeintel/codenav/service_new.go
> +			Matcher:      shared.NewSCIPBasedMatcher(args.Range, lookupSymbol),
This is a weird case where we don't want to allow an empty string as a valid input. So we want something like `Option<NonEmptyString>`. I've kept this function as-is, but changed the internal representation to use `Option[string]`. Changing this signature makes the code more cumbersome for callers, and still requires the code internally to fold `Some("")` to `None`.

2024-07-30 15:23 UTC, varungandhi-src commented on internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
> +	// - Avoid refetching/re-splitting the contents repeatedly for the same file
Just confirmed, we'll issue multiple requests for the same file.

2024-07-30 15:24 UTC, varungandhi-src commented on internal/codeintel/codenav/transport/graphql/root_resolver_usages.go
> +		// TODO: Record if we got the results from Searcher or Zoekt
Then let's file a feature request against Search Platform team? It'd be useful to have this information for debugging.

2024-07-30 15:26 UTC, varungandhi-src commented
> Do you have plans for how you're going to test the new PreciseUsages logic?

No, I need to think about it some more and look at the existing tests. But I will be working on this after fixing the perf hole.

2024-07-31 05:43 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +			Matcher:      shared.NewSCIPBasedMatcher(args.Range, lookupSymbol),
I've looked around a bit, but I still don't understand why we need special handling for `""`. Is it because the cursor json encoding ends up using the empty string to signal "None"?

2024-07-31 05:43 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +			Matcher:      shared.NewSCIPBasedMatcher(args.Range, lookupSymbol),
We can fix this in a follow-up (don't want to hold up a stack of PRs over this).

2024-07-31 05:44 UTC, kritzcreek approved these changes

2024-07-31 05:54 UTC, varungandhi-src commented on internal/codeintel/codenav/service_new.go
> +			Matcher:      shared.NewSCIPBasedMatcher(args.Range, lookupSymbol),
Looking up for the empty string doesn't make sense (because it's not a valid symbol string), but the documents we store in the DB may have some occurrences with empty string as the symbol name (the current normalization scheme doesn't strip those out). So if we allow creating `Some("")`, we need to do a check later during symbol comparison to handle `Some("")` differently from `Some(non-empty string)`.

2024-07-31 05:55 UTC, merged

2024-07-31 06:10 UTC, kritzcreek commented on internal/codeintel/codenav/service_new.go
> +			Matcher:      shared.NewSCIPBasedMatcher(args.Range, lookupSymbol),
Okay, that sounds to me like `None` and `Some("")` are not the same after all. `None` means I'm not supposed to filter based on symbol, while `Some("")` means the user asked to match against the empty symbol... which is just not going to produce any matches, but that would be just as true for `Some("1234")`.

> but the documents we store in the DB may have some occurrences with empty string as the symbol name (the current normalization scheme doesn't strip those out).

Have you seen these occurrences or did you just infer they exist because of the existing `""` checks in the code? I still don't understand why `""` is the only invalid symbol string we care about, other than Go null value fears.

2024-07-31 06:24 UTC, varungandhi-src commented on internal/codeintel/codenav/service_new.go
> +			Matcher:      shared.NewSCIPBasedMatcher(args.Range, lookupSymbol),
> Okay, that sounds to me like None and Some("") are not the same after all. None means I'm not supposed to filter based on symbol, while Some("") means the user asked to match against the empty symbol... which is just not going to produce any matches, but that would be just as true for Some("1234").

It's not terribly obvious here, but the outer loop means that the symbol values being matched against will dynamically change (e.g. during Find impls, we will find other symbol names, and we don't want to accidentally get null). So even if you start a request, if there is some bad index data, it's possible that we start matching using `""`.

> Have you seen these occurrences or did you just infer they exist because of the existing "" checks in the code? I still don't understand why "" is the only invalid symbol string we care about, other than Go null value fears.

1. Ideally, we'd assert that all symbol names that are present in the DB and that we get as inputs are well-formed, but that is a much more complex undertaking.
2. Having `""` is a very easy mistake to make, and we don't want to accidentally return `""` in the symbols in the API (so if we don't put the check here, we need to push the check to code later in the pipeline).

It's not a perfect solution for sure, but I think it's better to have the checks that we can have for now, instead of not checking anything at all, or risking checking too much and potentially breaking code nav for a bunch of people.