Policy patch - leave fields unchanged if they're missing from request
sourcegraph/sourcegraph pull request #64174
Opened 2024-07-31 09:07 UTC by antonsviridov-src

Specifically this allows us avoid updating syntactic_indexing_enabled when we don't have the value available.

## Test plan

## Changelog

2024-07-31 10:14 UTC, antonsviridov-src commented
@cla-bot check

2024-07-31 11:24 UTC, antonsviridov-src commented
@cla-bot check

2024-07-31 11:35 UTC, jhchabran commented
@cla-bot check

2024-08-01 09:51 UTC, kritzcreek requested changes

2024-08-01 09:51 UTC, kritzcreek commented on internal/codeintel/policies/internal/store/configurations.go
> +	syntactic_indexing_enabled = COALESCE(%s, p.syntactic_indexing_enabled),
Let's not push the nullability of the GraphQL API this deep. Afaict at the call site we have access to the previous record, so we should be able to do the merging in Go code

2024-08-01 09:51 UTC, kritzcreek commented on internal/codeintel/policies/shared/types.go
> +}
nit-ish: Maybe we could extract the shared part into a struct and make the patch: 
```
ConfigurationPolicyPatch = ConfigurationPolicyShared + Option[bool]
ConfigurationPolicyEntity = ConfigurationPolicyShared + bool
```
that should also let you avoid some of the spurious changes in policies/service.go by passing around the shared struct.
Using Option over `*` let's us be more explicit as well (some of the ptrs in here are not about optionality afaict

2024-08-01 09:58 UTC, antonsviridov-src commented on internal/codeintel/policies/internal/store/configurations.go
> +	syntactic_indexing_enabled = COALESCE(%s, p.syntactic_indexing_enabled),
Hm, this is the callsite - all we have is the constructed patch struct from the graphql args: https://github.com/sourcegraph/sourcegraph/pull/64174/files#diff-84bf2c19aa6cbb0438b9bbfb47f4eba71b981a3f4b9318f63d4f02895639a186R91-R100

unless I'm missing something?

2024-08-01 10:05 UTC, kritzcreek commented on internal/codeintel/policies/internal/store/configurations.go
> +	syntactic_indexing_enabled = COALESCE(%s, p.syntactic_indexing_enabled),
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@be17da7305215f5e28e9ec109f746739ddd3ac34/-/blob/internal/codeintel/policies/internal/store/configurations.go?L310

Isn't this where this is used?

2024-08-01 10:35 UTC, antonsviridov-src commented on internal/codeintel/policies/internal/store/configurations.go
> +	syntactic_indexing_enabled = COALESCE(%s, p.syntactic_indexing_enabled),
🤦 how did I miss that

2024-08-01 10:36 UTC, antonsviridov-src commented on internal/codeintel/policies/internal/store/configurations.go
> +	syntactic_indexing_enabled = COALESCE(%s, p.syntactic_indexing_enabled),
Only issue is that it's not going to be atomic, but I seriously hope people don't blast policy update endpoint with concurrent requests

2024-08-01 10:42 UTC, kritzcreek commented on internal/codeintel/policies/internal/store/configurations.go
> +	syntactic_indexing_enabled = COALESCE(%s, p.syntactic_indexing_enabled),
It's wrapped in a transaction https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@be17da7305215f5e28e9ec109f746739ddd3ac34/-/blob/internal/codeintel/policies/internal/store/configurations.go?L305, so it should be atomic

2024-08-01 10:45 UTC, kritzcreek approved these changes
Blocking comment was addressed

2024-08-01 10:48 UTC, antonsviridov-src commented on internal/codeintel/policies/shared/types.go
> +}
My hope is that _eventually_ (after a minor release possibly) we can remove the special status from syntactic indexing field, remove its optionality and either

1. promote patch to actually useful struct by relaxing the API and making lots more fields optional
2. remove patch if relaxing the API doesn't make sense

In case of (1) I would like to use options instead, yes.

2024-08-01 11:01 UTC, merged