Update the default Sourcegraph-supplied LLM models
sourcegraph/sourcegraph pull request #64281
Opened 2024-08-05 20:44 UTC by chrsmith

This PR sets the defaults for "Sourcegraph supplied LLM models". 

## When will these "defaults" be used?

These models will _only_ be used IFF the Sourcegraph instance is _explicitly_ using the newer "modelConfiguration" site configuration data. (And opts into using Sourcegraph-supplied LLM models.)

If the Sourcegraph instance is using the older "completions" configuration blob, then _only_ the user-supplied models will be used. (Or, based on the specific defaults defined in the code for the completions provider.)

## What about Cody Pro?

😬 yeah, we're going to need to deal with that later. Currently Sourcegraph.com is _not_ using the newer "modelConfiguration" site configuration, and instead we have some hacks in the code to ignore the internal modelconfig. See this "super-shady hack":
https://github.com/sourcegraph/sourcegraph/blob/e5178a6bc0e0f2f5208f9dedb0c226661c881d98/cmd/frontend/internal/httpapi/completions/get_model.go#L425-L455

We _do_ want Sourcegraph.com to only return this data, but there are a few things we need to get straightened out first. (e.g. Cody Gateway being ware of mrefs, and having Cody Clients no longer using `dotcom.ts` to hard-code Cody Pro LLM models.)

## Test plan

I tested things locally, and unfortunately it doesn't look like any clients are filtering based on the model capabilities. So "StarCoder" is showing up in the Cody Web UI, despite failing at runtime.

<img width="777" alt="image" src="https://github.com/user-attachments/assets/bb00d798-4a7f-46e4-9c29-d2e8de37f26d">

## Changelog

NA?

2024-08-05 20:49 UTC, slimsag commented
> What about Cody Pro?

Just FYI, there is also some silly business going on in the clients where we leverage percentage-user-feature-flags to override 'fireworks/starcoder' to 'deepseek V2'... I haven't traced that code path, but something we'll need to figure out. I think it only applies to dotcom, but not 100% positive.

2024-08-05 20:50 UTC, aramaraju requested changes
A few small nits that popped up to my eyes

2024-08-05 20:50 UTC, aramaraju commented on internal/modelconfig/embedded/models.json
> +      "capabilities": ["autocomplete", "chat"],
FYI @chrsmith StarCoder is only available for autocomplete, not Chat. This might fix your error on the Chat dropdrown

2024-08-05 20:50 UTC, aramaraju commented on internal/modelconfig/embedded/models.json
> +      "contextWindow": {
@hitesh-1997 Can you share what the max input and output tokens we are using for StarCoder?

2024-08-05 20:51 UTC, slimsag commented on cmd/cody-gateway-config/dotcom_models.go
> +				// NOTE: THis model name is virutalized.
```suggestion
				// NOTE: This model name is virtualized.
```

2024-08-05 20:52 UTC, slimsag commented on cmd/cody-gateway-config/main.go
> +		Revision: "0.0.`0+dev",
this looks weird?

2024-08-05 20:52 UTC, chrsmith commented
> > What about Cody Pro?
> Just FYI, there is also some silly business going on in the clients where we leverage percentage-user-feature-flags to override 'fireworks/starcoder' to 'deepseek V2'... I haven't traced that code path, but something we'll need to figure out. I think it only applies to dotcom, but not 100% positive.

@slimsag not sure about the specific, as there are several places where we could "virtualize" the model name. And/or pick something different via feature flag.

But this is what first comes to mind:
https://github.com/sourcegraph/sourcegraph/blob/e5178a6bc0e0f2f5208f9dedb0c226661c881d98/cmd/cody-gateway/internal/httpapi/completions/fireworks.go#L229

2024-08-05 20:52 UTC, chrsmith commented on cmd/cody-gateway-config/main.go
> +		Revision: "0.0.`0+dev",
That's a typo, good catch 😅

2024-08-05 20:52 UTC, slimsag commented on internal/modelconfig/embedded/models.json
> +  "revision": "0.0.`0+dev",
possibly related

2024-08-05 20:55 UTC, slimsag commented
@chrsmith here's a thread to pull on: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/completions/providers/create-provider.ts?L194-240

(again, no idea what is going on there specifically)

2024-08-05 20:59 UTC, chrsmith commented on internal/modelconfig/embedded/models.json
> +      "capabilities": ["autocomplete", "chat"],
Good catch. I had updated the code, but failed to regenerate the `models.json` file. Fixed.

2024-08-05 20:59 UTC, chrsmith commented on cmd/cody-gateway-config/dotcom_models.go
> +				// NOTE: THis model name is virutalized.
Fixed.

2024-08-05 21:08 UTC, chrsmith commented on internal/modelconfig/embedded/models.json
> +      "contextWindow": {
For reference, these are the values we have hard-coded in the client in a few places:

- We use 7k input tokens for most models.
- The newer models with expanded context windows, default to 30k tokens.

Cody Gateway imposes its own hard constraints that it will not allow a user to exceed.
- 4k _output_ tokens at maximum
- XXk input tokens before your request gets flagged and/or blocked. (Since we aren't using a super-precise token count before we send the request to the LLM provider, we very much do not want to get close to that limit. And instead keep it much lower.)

So for now, I would think that the 30k input tokens is probably a good value. But I cannot seem to find an exact number for what the model supports. (Or its different variants.)

2024-08-05 21:10 UTC, hitesh-1997 commented on internal/modelconfig/embedded/models.json
> +      "contextWindow": {
The number of input tokens are limited to `2048` and output tokens to `256`.
Adding the code link:
1. [Input token limit](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/completions/providers/fireworks.ts?L143)
2. [Output token limit](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/completions/providers/get-completion-params.ts?L5)

2024-08-05 21:22 UTC, aramaraju commented on internal/modelconfig/embedded/models.json
> +      "contextWindow": {
@chrsmith I believe those values are for chat models, autocomplete is going to be different. Let's use the values Hitesh provided ^

2024-08-05 21:40 UTC, chenkc805 commented on cmd/cody-gateway-config/main.go
> +			Chat:           types.ModelRef("anthropic::2023-06-01::claude-3.5-sonnet"),
I see Claude 3.5 Sonnet called `anthropic/claude-3-5-sonnet-20240620`, according to Gateway telemetry. Flagging in case it's worth making these names consistent (`3-5` vs `3.5`)

2024-08-05 21:43 UTC, chenkc805 reviewed
Re: Cody Free/Pro using a super-shady hack: 

When will we address this? Because my understanding of the server-side model selection is that it'll be easier to set up new models, so easy in fact that even a [PM can do it](https://sourcegraph.slack.com/archives/C06FCLRQ4BF/p1713943275104509?thread_ts=1713943052.961949&cid=C06FCLRQ4BF). 

If these experiences bifurcate like what's being described here, will we have achieved this goal? If not, do we have a follow up planned?

2024-08-05 21:46 UTC, chrsmith commented on cmd/cody-gateway-config/main.go
> +			Chat:           types.ModelRef("anthropic::2023-06-01::claude-3.5-sonnet"),
That's a good concern to call out, but the difference is 100% A-OK in this case.

Here we are using the _Model ID_ `claude-3.5-sonnet`. This will refer to an object with a _Model Name_ of `claude-3-5-sonnet-20240620`. One of the benefits of using this whole "model config" system is that we are no longer conflating the two. And can treat them as separate values.

So `claude-3.5-sonnet` can later refer to `claude-3-5-sonnet-20240805` without needing to make as many changes across the codebase.

2024-08-05 21:48 UTC, chrsmith commented
> **Re: Cody Pro and modelconfig**
> If these experiences bifurcate like what's being described here, will we have achieved this goal? If not, do we have a follow up planned?

@chenkc805 I will update the tickets in Linear this week to call out the sequence of steps needed so we can make Cody Pro "just work" with the new model config system. (It's not a lot of work, but  we do need to be careful when we roll out the changes to avoid any disruptions.)

2024-08-05 21:57 UTC, chrsmith commented on internal/modelconfig/embedded/models.json
> +      "contextWindow": {
Done.

Part of me is worried, since those are so different from the other token limits from other models. But perhaps this could be explained by StarCoder being trained primarily on source code, and therefore could use a more efficient or larger-sized tokenizer? 🤷

2024-08-05 22:04 UTC, chrsmith commented
@aramaraju PTAL

2024-08-06 02:23 UTC, aramaraju commented on internal/modelconfig/embedded/models.json
> +      "contextWindow": {
Given the use case being completion, these limits are fine as they are balanced slightly more towards latency.

2024-08-06 02:24 UTC, aramaraju commented
> @aramaraju PTAL

Looks good to me, Chris! Thank you 🙇

2024-08-06 12:02 UTC, aramaraju approved these changes
LGTM

2024-08-06 17:26 UTC, merged